### ISSUE TITLE
Osd doesn't switch to HD with HDZERO

### ISSUE THREAD

**Issue by Pascal687** [iNavFlight/inav#10001]
OSD PROBLEM

Speedybee FC on Inav 7.1 with HDZERO Race1 Vtx and Sharbyte VRX on FS HDO2.

-Bad display both fonts and position (see photo)
-When activated: Inav menu's display is good
-When activated: VTX menu is bad same issue as main display
-I have another plane with the same FC with good osd (see photo). Have swapped the VTX cam with the same results (seems not VTX related)
-Have tried WALKSNAIL on the same FC, no display problem.
-Have mounted another FC MATEK F405 with the same issue.
-Same problem view here https://youtu.be/q_HLM5wrEBQ?si=ZOotPrHq8b35rthH

![Capture d'écran 2024-04-27 175752](https://github.com/iNavFlight/inav/assets/116525299/b7e4ff0d-dd61-4106-a491-5c61c402a0fe)
 

![Capture d'écran 2024-04-27 175221](https://github.com/iNavFlight/inav/assets/116525299/fbba6422-1890-4684-9654-fbdcad4781f4)

****

## Steps to Reproduce

1.Try another FC done ! SAME PROBLEM
2.Try another FC brand ! MATEK F405, SAME PROBLEM
3.Try anoter VTX done ! HDZERO whoop, SAME PROBLEM
4.Try another VTX brand (WS) done... **this one works fine**

## Expected behavior
 Normal display of the OSD as seen on the photos of the OSD of the second plane.

## Additional context

---

- FC Board name and vendor: SPEEDYBEEWINGF405, MATEK F405 
- INAV version string: Inav 6.0.0 , 6.1.1 , 7.1.0

**Comment by MrD-RC** [comment]
Are you sure you're using the correct font in HDZero?

Both Walksnail and HDZero are using the same code to make and provide the OSD. So if Walksnail is working fine. It is unlikely an INAV issue.

**Comment by Pascal687** [comment]
Hi Darren.

I’m gonna re check this . I probably have a video too.
Kind regards 
Pascal

Envoyé de mon iPhone

**Comment by Pascal687** [comment]
Yesterday I managed to get it on 6.0.0 fw while opening Inav menu... but it did not last after the menu closed

https://youtu.be/f5uv4LElwa8

I tried again the FC on 7.1 with walksnail without any problem but any improvement in HDZero (to be sure I added a font file in the Ressource file)


https://github.com/iNavFlight/inav/assets/116525299/1a1f99cf-ca5e-4e13-b1c7-9d0be0ef3ffc

**Comment by Pascal687** [comment]
Same HDZero VRX with another bird on SPEEDYBEE with 6.0.0 fw... no problem

I tried to downgrade the fw on the other one but the problem is the same.

https://github.com/iNavFlight/inav/assets/116525299/e4ceaf82-f6fb-42a2-9aac-c2bd17d367d3

**Comment by Pascal687** [comment]
Solved; Problem due to overlapping elements !
