### ISSUE TITLE
Please use the actual rate.

### ISSUE THREAD

**Issue by jsungho** [iNavFlight/inav#10013]
hello. I'm flying a multicopter with Betaflight.
I would like to perform the autopilot function of inav.
Actual rates cannot be applied and cannot be changed.

Please add a method or function to apply the actual rate.

Thank you. I'm looking forward.

**Comment by DzikuVx** [comment]
INAV has just **RATES**. You set max rotation speed in `dps` and adjust expo accordingly to match your liking. And that is all required in terms of rates
