### ISSUE TITLE
wrong altitude and longitude values on OSD screen

### ISSUE THREAD

**Issue by ZipovUA** [iNavFlight/inav#10063]
Environment: 7.1

Please help me with my situation:
I am new in iNav - so I am not sure that it's a bug. Maybe I have wrong configuration:

So when I add GPS altitude and longitude on the screen - I see that it has not all digits:
in my case location is near 50.40129342003092, 30.203631039267947

but as you can see on the screen we can see first digit ("5", then empty, empty, empty, empty and then some digits)
<img width="1512" alt="Screenshot 2024-05-19 at 22 47 39" src="https://github.com/iNavFlight/inav/assets/5374149/bd08e9d9-6d7d-4629-989d-21e2a276fe87">

in iNav configuration I see that GPS page shows me correct position, but on OSD screen it's strange

**Comment by ZipovUA** [comment]
Here is my OSD configuration screen
<img width="1512" alt="Screenshot 2024-05-19 at 22 58 07" src="https://github.com/iNavFlight/inav/assets/5374149/c2d5d870-5dc0-43d3-9383-3c75ac1d60b2">

**Comment by ZipovUA** [comment]
P.S. also please take a look at video channel info: looks like it's shown on the screen with empty values

**Comment by sensei-hacker** [comment]
At the bottom right of the OSD configuration page you'll see the button to choose and upload a font to your OSD. Please try that and let us know if it doesn't work for you.

**Comment by ZipovUA** [comment]
@sensei-hacker, thank you! now I see that after applying font "clarity", I can see all digits in longitude and latitude.

Sorry for doubts

**Comment by ZipovUA** [comment]
But still is not clear: is it expected behaviour that if you don't specify font and use some default font - you can not see properly latitude, longitude? it's strange... is it really not a bug?

**Comment by breadoven** [comment]
Looks like you had overlapping fields which were blocking out the Lat/Lon fields in the first post. There's the throttle symbol (S shaped) to the left of the 3 for longitude. Later in the Configurator OSD screen the throttle seems to have moved which is why the Lon displays correctly. Did you move the Throttle field. Overlapping fields will be indicated with red shading.

**Comment by ZipovUA** [comment]
@breadoven I did not move throttle field.

I moved:
- latitude
- longitude
- satelits count
- vtx channels / power
