### ISSUE TITLE
Motor speed up by themselves 

### ISSUE THREAD

**Issue by HoVietHien** [iNavFlight/inav#10069]
![Screenshot 2024-05-21 221341](https://github.com/iNavFlight/inav/assets/127669741/f7439eb9-f769-4e5f-b620-f5d1dc0af4f5)
![Screenshot 2024-05-21 221617](https://github.com/iNavFlight/inav/assets/127669741/e46578ee-ce4e-4c2e-a81f-892cd1766d66)

when i test my motor without propellers at angle mode but motor 1,3 always speed up by themselves. How to solve this problem.

Thanks !!!

**Comment by MrD-RC** [comment]
That's just airmode. It's expected.

**Comment by HoVietHien** [comment]
> That's just airmode. It's expected.

But i had turned off airmode

**Comment by MrD-RC** [comment]
Dan you show a diff. By default it's permanently enabled.

**Comment by DzikuVx** [comment]
Motors will always speed you without propellers are control loop is broken. There is small error that PID wants to fix but can't since propellers are removed. So the error accumulates over time. 
Bottom line: PID controller does not work without propellers

**Comment by HoVietHien** [comment]
> Motors will always speed you without propellers are control loop is broken. There is small error that PID wants to fix but can't since propellers are removed. So the error accumulates over time. Bottom line: PID controller does not work without propellers

I don't know why my setpoint rare Pitch =1 while the others =0. How to fix it? Thanks

**Comment by sensei-hacker** [comment]
@HoVietHien for a more intuitive understanding  maybe this will make sense for you:

By switching to angle mode, you are commanding INAV to make the aircraft perfectly level. One side is 1mm lower than the other, so INAV spins up the props as much as necessary to lift the low side and level out the quad.

With no props, just a little spinning doesn't lift the quad, so but it keeps trying as hard as it can to do what you told it to do and level out.

**Comment by HoVietHien** [comment]
> Motors will always speed you without propellers are control loop is broken. There is small error that PID wants to fix but can't since propellers are removed. So the error accumulates over time. Bottom line: PID controller does not work without propellers

![Screenshot 2024-05-23 164648](https://github.com/iNavFlight/inav/assets/127669741/efc9a56d-87d5-49b4-b5b7-103ea5ccbd0d)
I had already got props to motors. When arming and switching to Angle mode, hover drone by hand, 1 motor always not spin. Do you have any ideas for solving this problem. Thanks !!!
