### ISSUE TITLE
ESC PROTOCOL

### ISSUE THREAD

**Issue by HoVietHien** [iNavFlight/inav#10072]
![Screenshot 2024-05-23 172939](https://github.com/iNavFlight/inav/assets/127669741/a8a13498-563f-44e2-a3ae-1edd515f1912)

Why my ESC protocol can not change to another protocol except "STANDARD"

I use 6.1.1 firmware STM32F411CEU6

My motor A2212/13T
My ESC hobbywing 40a

**Comment by DzikuVx** [comment]
What do you mean you can not change? What happens when you change to Multishot and save?
