### ISSUE TITLE
ESC not recognized.

### ISSUE THREAD

**Issue by Eliot-fpv** [iNavFlight/inav#10074]
Hello, I'm writing to you because I'm encountering an issue. I'm using the FC F745 AIO V3, and after flashing it with version 7.1 of INAV, my ESCs are not recognized in the motor tab. I took the time to flash my ESCs using BLHeli Configurator.

<img width="1278" alt="Capture d’écran 2024-05-23 à 17 25 53" src="https://github.com/iNavFlight/inav/assets/170650059/07685b11-c5be-4bef-8cb0-ba8cfd46d27c">

Don't hesitate to reach out if you have any information to help me, or if you need additional information. 
Have a great day!

**Comment by KrackJack1** [comment]
hallo
I got same issue using speedybee f405 mini with 7.1.1 flashing back on 7.1.0 works fine...please advise thanks..

**Comment by Eliot-fpv** [comment]
yes it's works ! Thanks a lot

**Comment by KrackJack1** [comment]
solved thanks 
![Screenshot 2024-05-25 172706](https://github.com/iNavFlight/inav/assets/28574788/4216d4df-f6e4-4225-8db9-3d687de07b21)
