### ISSUE TITLE
MSP data corruption

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1008]
As reported in https://github.com/betaflight/betaflight/issues/1386#issuecomment-259934193.
INAV F1 and F4 targets seem to be affected as well starting from INAV-1.2 and up to latest code.
INAV-1.1. seem to be working fine. Primary suspect - UART/DMA & new IO.

**Comment by digitalentity** [comment]
@jflyper, @martinbudden FYI

**Comment by digitalentity** [comment]
Bisecting narrowed it down to this specific (in)famous commit f440eadc03ac60d5437369ac1806d15a9c9456f6

**Comment by martinbudden** [comment]
I've just had a quick look. The circular buffer handling looks suspect to me. It seems `s->port.txBufferHead != s->port.txBufferTail` is used to indicate not empty. So it looks like there could be a wrapping error.

It may be OK but it just "smells" wrong.

**Comment by digitalentity** [comment]
As @jflyper figured out we have large bursts of data when corruption happens so my guess is that we initialize the DMA transfer with incorrect chunk size. No idea why or where it happens.

**Comment by digitalentity** [comment]
Interesting thing is that F3 doesn't seem to be affected, however the DMA TX code is the same for all targets.

**Comment by martinbudden** [comment]
Code is not quite the same. For F3 we have:
```
    if (!s->txDMAChannel && (ISR & USART_FLAG_TXE)) {
        if (s->port.txBufferTail != s->port.txBufferHead) {
            USART_SendData(s->USARTx, s->port.txBuffer[s->port.txBufferTail++]);
            if (s->port.txBufferTail >= s->port.txBufferSize) {
                s->port.txBufferTail = 0;
            }
        } else {
            USART_ITConfig(s->USARTx, USART_IT_TXE, DISABLE);
        }
    }
```
for F4 we have:
```
    if (!s->txDMAStream && (USART_GetITStatus(s->USARTx, USART_IT_TXE) == SET)) {
        if (s->port.txBufferTail != s->port.txBufferHead) {
            USART_SendData(s->USARTx, s->port.txBuffer[s->port.txBufferTail]);
            s->port.txBufferTail = (s->port.txBufferTail + 1) % s->port.txBufferSize;
        } else {
            USART_ITConfig(s->USARTx, USART_IT_TXE, DISABLE);
        }
    }
```
Although they should do the same, the F3 code is more robust (and easier to read).

**Comment by digitalentity** [comment]
This code is not for DMA but for interrupt-driven functionality while the bug lurks somewhere in DMA-driven code.

**Comment by martinbudden** [comment]
OK, I'm barking up the wrong tree.

**Comment by martinbudden** [comment]
Can you point me to the DMA-driven code you are talking about?

**Comment by digitalentity** [comment]
Ok, I think I'm onto something.

Our DMA TX is initiated by `void uartStartTxDMA(uartPort_t *s)` in `serial_uart.c`. Normally it should get called when the buffer is not empty, however, it ocasionally gets called with `s->port.txBufferHead == s->port.txBufferTail` (empty buffer). In this case it will transfer the `256 - txBufferTail` bytes of garbage. 

We can simply add protection there, but this is masking the bug. And the real bug is **why DMA transfer is initiated on empty buffer**.

**Comment by digitalentity** [comment]
It's actually even deeper than that - garbage is being transfered in other cases as well - not sure what cases exactly yet.

**Comment by digitalentity** [comment]
Ok, I'm starting to suspect that it's a reentrance issue. `uartStartTxDMA` is not reenterant, but it may get called from DMA TC ISR and from `uartWrite`. Will continue to dig deeper tomorrow.

**Comment by jflyper** [comment]
@digitalentity I'll test if protecting `uartStartTxDMA` with `ATOMIC_BLOCK` works.

EDIT
I think we've got it. Interaction with MWOSD looks clean. Continuing on with configurator now.
... 30min. Errors should be displayed as Packet error at the bottom, right?

EDIT2
Submitted a PR for betaflight, requesting some comments from reviewers.
Fix UART TXDMA corruption betaflight/betaflight#1968

EDIT3
Still working on the bf PR.

**Comment by digitalentity** [comment]
@jflyper as a workaround can you submit a PR into `master` to disable TXDMA on all targets?

**Comment by jflyper** [comment]
@digitalentity Ack.

**Comment by digitalentity** [comment]
@jflyper thank you. Take you time - this is the last bugfix I intend to have in 1.5.1

**Comment by jflyper** [comment]
PR is up. Need regression test.
