### ISSUE TITLE
PID Settings

### ISSUE THREAD

**Issue by HoVietHien** [iNavFlight/inav#10087]
Uploading 20240527_091902.mp4…

![image](https://github.com/iNavFlight/inav/assets/127669741/047ca323-17d5-4ff2-87f2-b4bf465384f7)

https://github.com/iNavFlight/inav/assets/127669741/058e4578-11b1-4708-abd1-d8496b93f917

How to set up perfect PID for quadcopter. Because my graph does not obey to any rules of PID

**Comment by DzikuVx** [comment]
Hi, 
I would guess your tune has not enough I-gain and P-gains. The flip forward was very strange. Gradually increase P-gains until it will be stable. If oscillations appear, try lowering the gyro lpf
