### ISSUE TITLE
Display GPS coordinates as MGRS

### ISSUE THREAD

**Issue by clodzeischi** [iNavFlight/inav#10143]
## Current Behavior

Coordinates displayed on OSD and radio telemetry in LAT/LON format.

## Desired Behavior

Have an option to display the coordinates in MGRS format.

## Suggested Solution

Perhaps add Proj4 library to make automatic conversions.

## Who does this impact? Who is this for?

This affects any user who wants to record flight data in MGRS. 

## Additional context

MGRS is more user friendly and more intuitive for estimating distances and battery requirements for missions.

**Comment by stronnag** [comment]
The INAV project has no desire to support the Military Grid Reference System

In any case, your suggestion is not practical

* The proj library would most likely exceed the capacity of  the firmware
* There are already options for displaying distances in commonly used units

In any case, it is trivial for use to convert recorded flight data to any CRS they desire.
