### ISSUE TITLE
List of waypoints on the flysky fsi6b remote control screen

### ISSUE THREAD

**Issue by Mounrealle** [iNavFlight/inav#10168]

**Comment by mmosca** [comment]
Is this a feature request, or a bug report?

**Comment by Mounrealle** [comment]
Good afternoon, I have not been able to display the mission numbers, waypoints, and homepoints on the remote screen, so I think that this feature simply does not exist. If it is initially there, then I did not understand how to do it.

**Comment by stronnag** [comment]
This is not an INAV function, it is a function of some firmware (which does not exist) on your device
