### ISSUE TITLE
Antenna Pointer to Home Location

### ISSUE THREAD

**Issue by axljackass** [iNavFlight/inav#10195]
## Desired Behavior
Option to have Antenna Pointer mounted in fixed wing/Planes

## Suggested Solution
Adaptation of Antenna Tracker but instead mounted in fixed wing/Plane

## Who does this impact? Who is this for?
We already have ELRS which is good for long range system but the video system is being left behind in the development.
Instead of using high power video system, Antenna Pointer will be use together with a high gain antenna.

## Additional context
Antenna Tracker in the ground using high gain antenna.
Antenna Pointer in the fixed wing/plane using high gain antenna as well but low power video system to lessen the power consumption.
It would be a perfect system.

**Comment by MrD-RC** [comment]
This is not a good idea. A patch/directional antenna on the aircraft, plus pan and tilt mechanisms for it, would be draggy. The best option is to use an omni on the aircraft and increase the directional antenna gain on the ground.

The ability to point an antenna to home already exists. There is the azimuth data. Use the programming framework to update a servo to point in the correct direction.
