### ISSUE TITLE
Target for TMOTOR Velox F7 SE?

### ISSUE THREAD

**Issue by jaakobus** [iNavFlight/inav#10216]
## Current Behavior
No support for TMOTOR Velox F7 SE

## Desired behavior
Target for TMOTOR Velox F7 SE

## Additional context
Are there any plans to support this FC?

---

**Comment by mmosca** [comment]
Requirements for a target are listed here:
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
