### ISSUE TITLE
Blackbox field definitions update required for MAX_SUPPORTED_SERVOS = 18

### ISSUE THREAD

**Issue by bartslinger** [iNavFlight/inav#10232]
Blackbox header includes only up to servo[15]

https://github.com/iNavFlight/inav/blob/904794d0afb77fd2c124f51ebb8c4719fe8254de/src/main/blackbox/blackbox.c#L349-L354

I think we need to add 16 and 17 to make blackbox compatible with `MAX_SUPPORTED_SERVOS` set to 18.

**Comment by bartslinger** [comment]
Actually it would be nicer if blackbox would only log the servos that are actually used, like how it is done with motors.

A lot of effort was made (predictions, encoding, etc) to reduce the number of bytes. But then we just write a lot of unused servo data.

**Comment by bartslinger** [comment]
@mmosca Could you have a look at this?

**Comment by stronnag** [comment]
There are other problems here wrt BBL; as stated we only write out 16 servo entries and then populate 18 servo fields, corrupting the logs,

Leave it with me, I'll see how it's best fixed, hopefully only writing servos in use.

**Comment by stronnag** [comment]
#10263 trivially adds the required header fields. BBLs for vehicles with servos are no longer corrupt. 
Tested with the SITL.

Making this use just the defined servos is not so trivial, in that `getServoCount()` is somewhat binary; it returns either 0 or  `MAX_SUPPORTED_SERVOS` so for now this at least fixes the log corruption.

**Comment by stronnag** [comment]
Other options include:
* Add `SERVOS` to  the array of optionally included fields. As the use case for recding servos is probably quite small, this would be an easy benefit.
* Provide and use an API to provide the actual number of in use servos and follow the pattern used for motors.

**Comment by stronnag** [comment]
I was wrong about `getServoCount()`, so doing this properly is back on.

**Comment by b14ckyy** [comment]
is https://github.com/iNavFlight/inav/pull/10272 the final fix here so we can close?

**Comment by mmosca** [comment]
Yes, I believe we can close this one now. It has been addressed by propperly supporting the extra servos and only writting used servos to the log.
