### ISSUE TITLE
HGLRCF 722 Mini compatibility on inav

### ISSUE THREAD

**Issue by TiaaMatt** [iNavFlight/inav#10230]
Hello everyone, i'm new to inav, and i wanted to try it on my HGLRCF 722mini fc, i saw some posts online where this fc was supported, but when i flash the HGLRCF F722 firmware on it (in DFU mode) it says that the process was succesfull but when i try to connect it after a while it says MSP connection succesfully closed, without seing the interface. It is a compatibility problem?
PS i always used betaflight and i never had problems.

**Comment by b14ckyy** [comment]
There is no target for it. the F722 mini needs a dedicated target. You should contact HGLRC and ask them https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by UltraExpress** [comment]
any update here I have exact same issues

**Comment by BigMike2021** [comment]
I have the same issue as well. Any chance there will be support for this FC Module?
