### ISSUE TITLE
GPS Telemetry data not received on TX16S with SpeedyBee F405V3 / iNav 7.1.2

### ISSUE THREAD

**Issue by MauiKano** [iNavFlight/inav#10235]
I upgraded all firmware: ExpressLSR on sender and receiver to latest version, iNav to 7.1.2 and EdgeTx on the Radiomaster TX16S to 2.10.2. Before, I was on versions about a year old. All worked including GPS/telemetry. After these upgrades (no change on HW) It seems that I somehow lost the GPS telemetry functionality. 

GPS works and sends data to the FC. I can connect to the FC via the SpeedyBee app (basically a iNav configurator)  with bluetooth and see GPS data. More than 6 satellites and correct coordinates.

Telemetry works. Using 'discover sensors' on the Radiomaster gives me 19 values. Missing are all GPS related values.
All the rest seems to work like before the SW/FW upgrades. 

I did reset all FC/iNav settings to 'default' and started configuring my values from scratch. No change. Everything works as documented except I do not get GPS telemetry data. 

# # status
INAV/SPEEDYBEEF405V3 7.1.2 Jun  1 2024 / 00:45:26 (4e1e59eb)
GCC-10.3.1 20210824 (release)
System Uptime: 854 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 22.43V (4S battery - OK)
CPU Clock=168MHz, GYRO=BMI270, ACC=BMI270
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=UNAVAILABLE, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
SD card: Startup failed
Stack size: 6144, Stack address: 0x10010000, Heap available: 1920
I2C Errors: 65, config size: 10429, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = ADC 3
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 7, cycle time: 504, PID rate: 1984, RX rate: 9, System rate: 9
Arming disabled flags: NAV HWFAIL RX CLI
OSD: MAX7456 [30 x 16]
VTX: not detected
GPS: HW Version: UBLOX10 Proto: 34.09 Baud: 115200
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    Galileo 1/1
    BeiDou 1/1
    Glonass 1/0
    Max concurrent: 3

**Comment by MauiKano** [comment]
This can be closed.
It is NOT a bug in iNav.
It seems that i got conflicting script files on the transmitter SD card. Not quite sure which one it was. I did install the latest EdgeTX version again on my Radiomaster TX16S. I did also copy all files from the original EdgeTX source to the SD card and incrementally copied my old configurations (mainly the models) over. The issue was gone. I can see now 24 paramters on telemetry. All GPS telemetry data are here. Most likely, the issue was with the ExpressLRS LUA script, where I used a previous version.

**Comment by jankiefer** [comment]
exact same issue here with a Jumper T15.... I did replace all the lua scripts but problem persists...  @MauiKano any hint where to look at?

**Comment by sensei-hacker** [comment]
> exact same issue here with a Jumper T15.... I did replace all the lua scripts but problem persists... @MauiKano any hint where to look at?

Start by looking at the telemetry page in the radio rather than the Lua scripts.  If you only have radio-related telemetry there, one of the two wires on the receiver-FC uart probably isn't properly connected.

If you have GPS telemetry on the telemetry page of the radio but not in the Lua script, that's a Lua script problem.

**Comment by MauiKano** [comment]
As stated earlier. I resolved it by reinstalling the LUA scripts on the TX16s.

**Comment by jankiefer** [comment]
Thanks. To me it looks like Inav is not updating the GPS values to the telemetry. GPS is connected, INAV/App shows values and fix. telemetry screen then shows 19 regulararly updated values, then GPS and aa few others (total 24) are shown and red but not updated. I guess it's a problem in iNAV not notifying/broadcasting the updated gps values to the telemetry layer. GPS seems to be evaluated properly inside iNAV for Flightmode/Arm etc, functions. just values are not transmitted to receiver. Other values are transmitted properly. 

I use
- Jumper T15 edgetx 2.10.3 with lateste elrs (3.4.3?, don't remember)
- BetaFPV Nano ELRS receiver (or 7CH DIY PWM module, happymodel -  same behaviour)
- Speedybee F405 WIng MIni
- iNav 7.1.2
GPS Telemetry did work with FRSKY XSR receiver using SBUS and S.port telemetry on TX 2 of the FC.

But I wnat to go ELRS for future... 

I have no further ideas where to look at. I suspect a bug in iNAV

**Comment by bheatcoker** [comment]
I have the same issue. 
All telemetry but no GPS, the GPS is working I can see the parameters inside INAV 8.0.1. I use a radiomaster pocket with EdgeTX, and ExpressLSR, all updated to today.  The LUA script also doesnt work now. In the past everything was working, so now I already downgrade a few version of ExpressLSR, and INAV and EdgeTX, with not luck. 
Basicily the same issue, iNav read the telemetry but looks like is not sending that back to my receiver OR it is sending it back but there is issue in my receiver, someone managed to solve this issue?
