### ISSUE TITLE
Add support for the TBS LUCID FC 

### ISSUE THREAD

**Issue by bkleiner** [iNavFlight/inav#10265]
## Current Behavior
[Flight Controller](https://www.team-blacksheep.com/products/prod:lucidfc_freestyle) is not supported :-1: 

## Desired Behavior
[Flight Controller](https://www.team-blacksheep.com/products/prod:lucidfc_freestyle) is supported :+1: 

## Suggested Solution
I can supply the appropriate target configuration and any other changes required to the firmware.
I can arrange for samples to be sent out to other developers.

**Comment by b14ckyy** [comment]
In Progress 👌
