### ISSUE TITLE
(GoFilm 20) Happymodel Super F405HD ELRS AIO support possible?

### ISSUE THREAD

**Issue by mszulen** [iNavFlight/inav#10266]
This board is used by GoFilm 20 drone (but relabelled as Caddx F405 AIO ELRS).
It works with betaflight as BETAFLIGHTF4, but there are custom settings required to make gyro and baro working
Can this be used with iNav (or the support is already there?)

This is the manufacturer's information for Betaflight to compare:
![image](https://github.com/user-attachments/assets/c08ebe08-1fc4-44a3-a56f-10d09e71cc95)

**Comment by b14ckyy** [comment]
There is an official Process for new Firmware targets. You can find info about that here: https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

This process is mandatory for an official target. But the changes are minimal and there is a BETAFLIGHTF4 target for INAV. 
I could try to make you a custom target to test after work. Ping me on Discord or Facebook as I will close this ticket here for now.

**Comment by mszulen** [comment]
Thanks! I spoke with HappyModel team. They will request it the official way. They also have mentioned that the Caddx F405 AIO ELRS (from Caddx GoFilm 20 drone) is the same board.

**Comment by GlidLov** [comment]
hi, any news on this?

**Comment by mszulen** [comment]
I would love to know it too…

**Comment by mszulen** [comment]
This is the response I've just got from HappyModel team:

"We have already sent the sample flight controllers to INAV team , and now are working on it . Maybe we think it would be supported later , thank you ."

**Comment by b14ckyy** [comment]
I have not noticed that this happened But I suggest you ask on Discord where the other core devs are, if one of them is in contact with them

**Comment by yannbouteiller** [comment]
Hi, I'm also very interested in this and hoping we can have support soon.

Linked resource:

https://github.com/iNavFlight/inav/discussions/10942

**Comment by sensei-hacker** [comment]
I have the sample from Happy Model. I anticipate this will be in INAV 8.1, assuming things go smoothly.

**Comment by yannbouteiller** [comment]
This is great news, thanks @sensei-hacker !

**Comment by mszulen** [comment]
> I have the sample from Happy Model. I anticipate this will be in INAV 8.1, assuming things go smoothly.

Ah, great news. It took them some time to provide the sample..haha :)

**Comment by konradgeomiar-sudo** [comment]
Not sure if this target will also work with the CRAZYF405HD ELRS ELRS 1-2S AIO?
