### ISSUE TITLE
Ukrainian language for INAV version 7.1.1

### ISSUE THREAD

**Issue by AndrewKZV** [iNavFlight/inav#10281]
[messages.json](https://github.com/user-attachments/files/16507634/messages.json)
![image](https://github.com/user-attachments/assets/1741f72c-9bac-4a05-98d4-9a3edc472673)

**Comment by b14ckyy** [comment]
This is some awesome work. 
Just please use English for opening a ticket, especially the title ;) 

Feel free to create a PR for it.

**Comment by b14ckyy** [comment]
I will move this ticket over to the Discussions as its not a bug ticket. 
If you need help with a PR just ping me in the discussion thread.
