### ISSUE TITLE
Quad will not calibrate

### ISSUE THREAD

**Issue by Ulisses1478** [iNavFlight/inav#10318]
## Current Behavior
My quad will not calibrate right I point down and calibrate up, I point one side calibrate the other one or simply won't calibrate.

## Steps to Reproduce
1. Flash Inav
2. Set board yaw for 135 degree
3. Try to calibrate

## Expected behavior
I should be able to calibrate using the correct side,

## Additional context
I also tried to fly calibrating with this behavior but the quad in each new calibration got worse, first tried to fly  foward, then i tried outside with gps and the quad armed normally but when tried to fly it goes 100% throttle I simply could use inav anymore. 

I am using betaflight right now If my dump is essential I will flash again

- FC Board name and vendor: Speedybee F405 v3
- INAV version string: 7.2

**Comment by sensei-hacker** [comment]
Calibrating the accelerometer / flight controller calibrates - the accelerometer; not an airframe, which gets attached after calibration is done.

The FLIGHT CONTROLLER needs to be pointed up, down, etc.

**Comment by sensei-hacker** [comment]
8,)

**Comment by sensei-hacker** [comment]
PS - if you ever start flying larger aircraft, you may find that it gets to really be a big hassle if you wait until after the FC is installed to calibrate it.  Turning the whole aircraft to each position starts to be a real pain as they get larger.

![airplane-upside-down](https://github.com/user-attachments/assets/7b3f20f8-cb3a-4b2e-94aa-c708d55e5ec2)
