### ISSUE TITLE
failsafe_recovery_delay resets to 117 when 'save and reboot' on failsafe tab

### ISSUE THREAD

**Issue by isilcala** [iNavFlight/inav#1032]
Hi,

Found something weird on my build, not sure if it's just me or someone see the same happens.

Whenever I click 'save and reboot' on failsafe tab, the value of failsafe_recovery_delay resets to 117. I have to go to cli to change it each time. Or it will cause it almost impossible to abort the failsafe procedure because it needs RC link to stay good for 11.7+0.2=11.9 seconds. The craft could be long on the ground already by then.

My build is a fixed wing, CC3D Atom running iNav v1.5, with iNav configurator v1.5.2

Thanks!

**Comment by digitalentity** [comment]
Fix pending merge
