### ISSUE TITLE
can't see the rc control mission number

### ISSUE THREAD

**Issue by Todor319** [iNavFlight/inav#10418]
controller speedybее wing ivav 7.1.2 . I receive ibus telemetri but I can't activate a sensor to show me a wp mission number

**Comment by sensei-hacker** [comment]
As far as I can see, IBUS doesn't have a waypoint number field. LTM does.

https://github.com/iNavFlight/inav/blob/master/docs/Telemetry.md#available-sensors

You can, of course, display the waypoint number on your OSD. Unless you have a DJI, in which case you only get the values they decided you want.

**Comment by Todor319** [comment]
can you tell me how i can show the point number

На пт, 18.10.2024 г., 9:52 Sensei ***@***.***> написа:

**Comment by Todor319** [comment]
![IMG_20241020_110310](https://github.com/user-attachments/assets/e389f26f-c182-4983-9eec-9f870bb95bcf)
![IMG_20241020_110255](https://github.com/user-attachments/assets/1316d4f1-2341-4cab-90f3-d07827c4383a)
![IMG_20241020_110241](https://github.com/user-attachments/assets/e2000eba-05d9-4381-afef-8af8317140c9)
![IMG_20241020_110227](https://github.com/user-attachments/assets/961588d8-148a-401a-923c-0dea98ee221b)
hi these are the sensors i am getting

**Comment by MrD-RC** [comment]
Waypoint number is not sent via any control link telemetry. It is shown in the OSD. 

If you are doing autonomous missions without OSD. You should really use a ground station with a long range telemetry radio, such as mLRS, via MSP or MAVLink. They will have full access to mission information.

**Comment by Todor319** [comment]
I am new to inav and I apologize if my inputs are wrong, I thought that the function is available for all controllers because I have purchased a controller with inav 4.1.0 installed, which through telemetry transmits information about mission points, which is quite convenient for rover
![IMG_20241020_141233](https://github.com/user-attachments/assets/4803bb8c-8c1a-45dc-9ba8-c381f0231ec4)
