### ISSUE TITLE
Horizon mode -> tail servos self workin when UAV on the table

### ISSUE THREAD

**Issue by sia88** [iNavFlight/inav#10410]
Hi

UAV lay on the table, everything working correct, no problem with any of servos or accelerometr. 
But when activating Horizon mode we see that servos on a tail pushing down but the position of UAV not changing.

**Comment by sensei-hacker** [comment]
With no airflow because it's not flying, we wouldn't expect the attitude of the plane to change, would we?

**Comment by sia88** [comment]
> With no airflow because it's not flying, we wouldn't expect the attitude of the plane to change, would we?

I understand. Thank you, try to emulate flight in hands and it's look like working correct:)
