### ISSUE TITLE
STM32F411 custom board connection issue

### ISSUE THREAD

**Issue by Suturin-Daniil** [iNavFlight/inav#10419]
Hello inav contributors! I want to build my own flight controller based on F411 chip. For tests I decided to use STMF411CEU6 board. I build MATEKF411 firmware as a reference. When I successfully flashed it and connected board in order to open configurator nothing happened. I cannot connect board for some reason, and even don't see automatically detected COM port in upper right corner of the configurator as usual. I nothing changed in target.h and target.c I use inav 7.0.0 version
I also checked mpu connection, it is right

**Comment by mmosca** [comment]
Don't use F411.

F411 support is no longer supported from INAV 8.0
