### ISSUE TITLE
New Firmware for MATEKF411SE_S6_SR1

### ISSUE THREAD

**Issue by alexvazquez** [iNavFlight/inav#10439]
There was a bug for Mavlink to send that over softserial that was fixed in the following issue

https://github.com/iNavFlight/inav/issues/3045

Does anyone know if that fix is included in any recent firmware that I can use for MatekF411SE?

Appreciate it.

**Comment by sensei-hacker** [comment]
#3045 is a person had their Dragonlink radio set far too slow. There is no bug.
