### ISSUE TITLE
Matek F411SE problem with analog airspeed

### ISSUE THREAD

**Issue by LazyPythonCoder** [iNavFlight/inav#10432]
I have Matek 411WSE controller and analog airspeed sensor. Everything worked OK with firmware 7.1.1 But after I had installed firmware 7.1.2 I faced with problem too long initialization controller. Sometimes it takes about two minutes(previous was about 20-30 sec maximum)
 Inav configurator 7.1.2
Firmware F411SE -7.1.2

**Comment by b14ckyy** [comment]
Could be a generally noisy sensor that delays the runtime calibration. 

I am not sure if this has an effect on the Airspeed as well but try this: 

set baro_cal_tolerance = 250 

Default is 150. Check if it works better afterwards. In general we recommend to use a digital airspeed sensor instead. Makes things easier.
