### ISSUE TITLE
RUSH_BLADE_F7, 7.1.2, quad, motors 3-4 don't operate 

### ISSUE THREAD

**Issue by alexanderdzyuba** [iNavFlight/inav#10453]
Freshly flashed Rush Blade F7 analog stack with "erase chip" option. Battery connected. A reversed rotation was chosen, using the "Quad X" scheme.

Right motors rotate, left - not. 
Tried to change options in "mixer" - I can make left motors rotate, but never all 4 motors together.

https://pastebin.com/EuUktQtP

> version
> INAV/RUSH_BLADE_F7 7.1.2 Jun  1 2024 / 00:28:05 (4e1e59eb)
> GCC-10.3.1 20210824 (release)

**Comment by mmosca** [comment]
Force timer8 and timer 3 to motor in the mixer tab.

This fc was poorly designed and causes inav to try to use S1, S2, S5 and S6 as motors, as indicated in your mixer tab.
