### ISSUE TITLE
motors stop working while trying to take off

### ISSUE THREAD

**Issue by MohamedNour1452** [iNavFlight/inav#10455]
## Current Behavior
<! -- when I try to raise the drone up it motors just stops working momentary and start working again maybe after the drone is already flipped. it happened to my 3 times and the drone works perfectly fine after the crash and before as well. 
## Steps to Reproduce

1. arming the quad
2. raising the throttle 
3. airmode off

## Additional context

---
log: 
[LOG00046.TXT](https://github.com/user-attachments/files/17639396/LOG00046.TXT)
cli:
[INAV_7.1.2_cli_20241106_003329.txt](https://github.com/user-attachments/files/17639428/INAV_7.1.2_cli_20241106_003329.txt)
![image](https://github.com/user-attachments/assets/c945a743-0815-454f-b1a9-4f46f28f4cc6)
it shows here in the image throttle is 1000 that can't be for because I have spring centered throttle and I didn't pull it down 

- speedybee f405 v4
- INAV version : 7.1.2

**Comment by sensei-hacker** [comment]
What wasn't mentioned here is the user ID forcing the throttle to 0% using the programming tab.

**Comment by MohamedNour1452** [comment]
Hello there, since you are the one replying here Let's just continue our discussion in discord
