### ISSUE TITLE
Adjusting sensitivity for Caddx GM series/ C-20T/C-20D gimbals with UART Control

### ISSUE THREAD

**Issue by jaroszmm** [iNavFlight/inav#10474]
## Current Behavior
Using either CLI or Inav 8.0 RC1 configurator it is impossible to set gimbal sensitivity to negative values.
If using configurator and typing negative value in the gimbal sensitivity window after Save&Reboot it reverts to 0.
I using CLI it responds with this:

set gimbal_sensitivity = -15
gimbal_sensitivity set to 241
set gimbal_sensitivity = 15
gimbal_sensitivity set to 15

although CLI clearly states:

get gimbal_sensitivity
gimbal_sensitivity = 15
Allowed range: -16 - 15

## Steps to Reproduce

1.Type negative value of gimbal sensitivity in the configuration tab in INAV configurator and hit save&reboot
or

2. type in CLI 

set gimbal_sensitivity = -15

## Expected behavior
Sensitivity should be set to negative value after reboot.

## Suggested solution(s)
I'm too stupid for that ;)

## Additional context
I would like to be able to adjust sensitivity mid flight like it is now possible with PWM control.
---

INAV/SPEEDYBEEF405WING 8.0.0 Nov 15 2024 / 17:30:40 (5f78f962) dev
GCC-13.2.1 20231009

**Comment by mmosca** [comment]
```# set gimbal_sensitivity = -1
gimbal_sensitivity set to 255
# set gimbal_sensitivity = -10
gimbal_sensitivity set to 246```

Something is certainly wrong
