### ISSUE TITLE
inav configurator 7.1.2 does not show reason for navigation is not safe (cli same)

### ISSUE THREAD

**Issue by swissembedded** [iNavFlight/inav#10470]
## Current Behavior
I nav does not arm. Arming disabled flags only show CLI in CLI.
Everything seems fine GPS 3d lock, receiver center, calibration, ...

Problem on speedybee F405Wing Mini and Matek F765 Wing. Both new setup with inav 7.1.2.

**Comment by b14ckyy** [comment]
Added in 8.0 as a new feature: https://github.com/iNavFlight/inav/pull/10280
Also in Status bar: 
![image](https://github.com/user-attachments/assets/b99251be-16f3-433e-bd25-60511690ede9)

**Comment by sensei-hacker** [comment]
The detail of why navigation is unsafe is shown on the OSD for 7.1.2.  To see it in the CLI, you can try the new INAV 8.0 RC1 that was just made available.


https://github.com/iNavFlight/inav/pull/10280

**Comment by swissembedded** [comment]
I checked with osd, it just shows gps as reason, but in inav I see that it has 3d lock and values are fine.
<img width="358" alt="Screenshot 2024-11-17 112257_cut" src="https://github.com/user-attachments/assets/39a01eb1-00da-4574-93b3-6d56a7288302">
[status.txt](https://github.com/user-attachments/files/17790105/status.txt)
[INAV_7.1.2_cli_20241117_110704.txt](https://github.com/user-attachments/files/17790106/INAV_7.1.2_cli_20241117_110704.txt)

Also tried to remove ground assistance type, galileo, beidou, did not help. HDOP, EPH, EPV seems fine to me. Magnetometer is disabled. It would be nice if it could show the reason in details. Will check 8.0 too and give feedback.

**Comment by b14ckyy** [comment]
I see your problem. 

set inav_max_eph_epv = 1000

this should fix it. 
its a bug we have still not found the cause of. the value of this parameter is sometimes set to 1.000 instead of 1000. 
Change that in CLI and it should be fine again.

**Comment by swissembedded** [comment]
Yes, that that was it, will test with the other if the same and with 8.0. Thank you very much.

**Comment by sensei-hacker** [comment]
Was the configuration of the Matek board copied over from the SpeedyBee board?

**Comment by swissembedded** [comment]
Speedybee board exactly the same issue. 

Matek: old config with inav 6.0 updated to 7.1.2, I did not do full erase, but flashed and used setup / reset setting and configured everything from scratch including calibration. Guess that is the mistake.
Speedybee: Virgin Board from speedybee, I think it had ardupilot installed (not sure anymore). Flashed and most probably did not select full erase either. Then configured everything from scratch.

**Comment by b14ckyy** [comment]
Full erase is always recommended but does not cause this issue. 
Something is causing this setting to be set wrongly and we still don't know why. Most people reporting that are using SpeedyBee F405 Wing FCs but also some Matek ones. We don't even know if that happens on first initialization after flash or with a diff transfer or just randomly later during use... Its really annoying when it happens.

**Comment by swissembedded** [comment]
I have  3 new controllers from speedy be with f405 left here to fool around for some old models to add inav. Any hint how to setup to reproduce?

**Comment by b14ckyy** [comment]
We don't know how to exactly reproduce issue. 
You can try: 
- Check what INAV version they have out of box and what value is set there from factory
- set some basics like mixers modes and change a few settings. then pull a diff and look if that setting is in the DIFF and with what value
- Update INAV to 7.1.2 with full erase and maybe also once with no chip erase and then check in CLI the parameter again
- Then load back the previous diff and check again the parameter... 

Would be interesting if at any of these steps the value changes or when it is at 1.000 again in general.

**Comment by mlochen** [comment]
> I see your problem.
> 
> set inav_max_eph_epv = 1000
> 
> this should fix it. its a bug we have still not found the cause of. the value of this parameter is sometimes set to 1.000 instead of 1000. Change that in CLI and it should be fine again.

Thank you so much for this solution! I was already doubting my sanity because all the sensors worked perfectly in inav-configurator but it still said that navigation wasn't safe and wouldn't let me arm. I have a SpeedyBee f405 wing mini with inav 7.1.2 on a flying wing if that helps.
