### ISSUE TITLE
FAILSAFE - an option keep failsafe active on signal recovery

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1047]
Add an option to keep failsafe active until pilot moves the sticks or switches (configurable).

This way when i.e. RTH was initiated on failsafe the machine will keep doing RTH even if signal is recovered and exit RTH mode only when pilot is ready.

**Comment by stronnag** [comment]
Good idea. Actually I'd erroneously assumed this was what would happen, as the pilot may not know the link had returned. Explains a lot; but nothing that a bit of epoxy couldn't fix:)

**Comment by csurf** [comment]
vector has this feature and I've always wanted it... In vector, you'll see a 'move sticks to regain control' message appear on screen after the link is reestablished, and RTH is maintained unless/until there's some stick input.

**Comment by digitalentity** [comment]
Done in #1196. For sub-tasks see #1203
