### ISSUE TITLE
BLHeli interface Naze32

### ISSUE THREAD

**Issue by tonyintn** [iNavFlight/inav#1048]
This is not a bug just a question I am using the latest 1.51 and have made a custom flash file for my Naze32 by removing the blackbox and adding the LEDs. (Thanks again for the help on how to do this!).

I do understand reading thru the Issues that the BLHeli interface was removed from the Naze32 target due to memory of the F1. 
My question is since I have removed the blackbox is it possible for me to add it to my custom build if so which line would I need to change/add. I have looked at the common and naze32 target but unsure which one to add back into the build or if this is even possible.

Thanks in advance.

Never mind I found it  USE_SERIAL_4WAY_BLHELI_INTERFACE  I did not look hard enough.  Got it compiled successfully by removing Telemetry and Blackbox was able to add back the BLHeli 4way Interface and Led option back to the Naze32.

**Comment by handsomejackuk** [comment]
Hi Tony, wold you mind sharing this build with me as ihave original naze32 and wold love to get blheli interface working too... and i dont use blackbox either thanks...

**Comment by HaseebNain** [comment]
@handsomejackuk Simply go into the target.h file and uncomment the line 

    #define USE_SERIAL_4WAY_BLHELI_INTERFACE 

it can be found here: [src/main/target/NAZE/target.h](https://github.com/iNavFlight/inav/blob/master/src/main/target/NAZE/target.h#L198)

and then add in the following after that line.

    #undef BLACKBOX
    #undef TELEMETRY

**Comment by tonyintn** [comment]
I will not disable Telemetry as there would not be a need to; the file size will be fine with telemetry enabled.

Naze 1.6.1 Build - https://www.dropbox.com/sh/8s8l4f1hgsnnid0/AAA0GBG83afUFN-DM1sRnPTHa?dl=0
includes (Updated 3/8/2017)
LED
Serial_4Way

Removed
Blackbox
