### ISSUE TITLE
After intalling MTF-01 optic flow althold does not work.

### ISSUE THREAD

**Issue by and-sh** [iNavFlight/inav#10487]
Inav 8.0.0
Althold was tuned before installing optflow. Worked normal.
After installing optflow.
Under approx 2m - work normal.
Higher does not work.
Testing in field over flat surface (snow). Sunny day.
Surface mode = OFF
nav_max_terrain_follow_alt = 100
inav_max_surface_altitude = 100

Max altitude where rangefinder measure reliable data 120cm.
![Screenshot From 2024-11-29 15-59-37](https://github.com/user-attachments/assets/25cc0870-42bf-4674-87d1-66c5a959fc52)

Max altitude where rangefinder measure something about 3m.
![Screenshot From 2024-11-29 16-00-45](https://github.com/user-attachments/assets/c394cd89-915a-43b4-a0a2-d6ebae5581c0)

About 16m rangefinder report zero altitude
![Screenshot From 2024-11-29 16-04-02](https://github.com/user-attachments/assets/17700a8a-52b2-4c04-8899-edf42b65794b)
At the same time surface reliability = 1000.
 
Log
[blackbox_log_2024-11-28_131957.TXT](https://github.com/user-attachments/files/17958253/blackbox_log_2024-11-28_131957.TXT)

**Comment by and-sh** [comment]
Nobody need rangefinder here?

**Comment by and-sh** [comment]
Is the way disable rangefinder from switch?

**Comment by sensei-hacker** [comment]
> Is the way disable rangefinder from switch?

Turning off surface should turn off the rangefinder, except for autoland. Unless I'm mistaken.

**Comment by and-sh** [comment]
I think I got it. The rangefinder readings are not used directly to calculate the position. When the quality of the readings is high, they are used to calculate the correction for the barometer and GPS, when the quality is low, this correction is simply a constant.

What is the difference between the following parameters?
nav_max_terrain_follow_alt
inav_max_surface_altitude

**Comment by and-sh** [comment]
If I set to zeroes 
inav_w_z_surface_p
inav_w_z_surface_v
Will it effectively disable rangefinder for z position estimator?
Will surface mode work in this case?

**Comment by sensei-hacker** [comment]
> If I set to zeroes
> inav_w_z_surface_p
> inav_w_z_surface_v
> Will it effectively disable rangefinder for z position estimator?
> Will surface mode work in this case?

Yes, that would disable the sensor that measures the distance to the surface. Which would make surface mode not work.


> What is the difference between the following parameters? nav_max_terrain_follow_alt inav_max_surface_altitude

They are almost the same.  max_terrain_follow_altitude is the maximum altitude it will go in surface mode. Your "throttle" (altitude)  input is scaled based on this value.
inav_max_surface_altitude is the maximum reading at which your rangefinder should be trusted.

It often makes sense to set them to the same value.

**Comment by and-sh** [comment]
It seems to me that the equal sign should be removed in this place.
![Screenshot_20241204-090103_Firefox](https://github.com/user-attachments/assets/1f9f5941-4f04-465e-8552-1379ee762acf)
Because
![Screenshot_20241204-090411_Firefox](https://github.com/user-attachments/assets/5a26f099-7999-4890-a9b5-e42365e05d6b)

**Comment by and-sh** [comment]
If somebody can fast recompile corrected source for matek 722 mini se, I can give it a try

**Comment by sensei-hacker** [comment]
It seems so to me as well. At very least, in the case of that particular type of sensor. I wonder if the same applies to others?

See also the similar line around 

https://github.com/iNavFlight/inav/blob/1c15fcc3deedbf0159968d33f6f2790f03665637/src/main/sensors/rangefinder.c#L250

Are you familiar with how to make a pull request?

**Comment by sensei-hacker** [comment]
That rangefinder is connected via MSP, right?
So it should already be handled here
https://github.com/iNavFlight/inav/blob/1c15fcc3deedbf0159968d33f6f2790f03665637/src/main/io/rangefinder_msp.c#L68

Above, you wrote "About 16m rangefinder report zero altitude", but your screenshot shows 1 rather than 0.

**Comment by and-sh** [comment]
> Above, you wrote "About 16m rangefinder report zero altitude", but your screenshot shows 1 rather than 0.

That means the problem is somewhere else.
Will try to check readings by rangefinder itself. Micoair have dedicated programm. May be this is problem of rangefinder itself.

**Comment by and-sh** [comment]
I think I found the real problem. The rangefinder was installed incorrectly.

**Comment by sensei-hacker** [comment]
Glad you found the problem!
For the next person, what was incorrect about the installation? Was there something below the rangefinder it was getting a reading of? That is, something "blocking" part of the view so it was reading the distance the landing gear or whatever?

**Comment by and-sh** [comment]
There was nothing directly below it. But it has a field of diffusive light of almost 180 degrees. Any object that hits it scatters light and becomes decisive at high altitudes, when the main signal becomes weak. The sensitivity of this simple devise is amasing.

It is necessary to have a switch to turn off the rangefinder, since any scattering from dust or fog can disrupt stabilization and lead to a sharp change in altitude

**Comment by and-sh** [comment]
The rangefinder started working
![Screenshot From 2024-12-06 21-22-04](https://github.com/user-attachments/assets/e5fb897d-4a97-49e6-ab97-8d030e97a2bd)

**Comment by and-sh** [comment]
Ok. I remove the optical flow and return to the working combination of GPS + barometer + compass. If anyone in the future is interested in finishing the optical flow and rangefinder, contact me.

**Comment by utrinque96** [comment]
Check and comment on this, please:
https://github.com/iNavFlight/inav/issues/10566#issuecomment-2566742928
