### ISSUE TITLE
[8.0 RC1] custom OSD element preview 

### ISSUE THREAD

**Issue by rts18** [iNavFlight/inav#10488]
The ability to preview Custom OSD elements in configuration is very useful. However its not allowing character elements greater than 255 to be displayed.

- FC Board name and vendor:
- INAV version string: 8.0 RC1

**Comment by MrD-RC** [comment]
That is because only characters below 256 are supported by custom OSD elements. Due to the drawing method. Maybe it can be addressed in the future. But it's not a Configurator limitation.
