### ISSUE TITLE
Softserial Speedybee F745 AIO

### ISSUE THREAD

**Issue by smcStevesmc** [iNavFlight/inav#10496]
Inav 7.1.2
Enabled Softserial option in Configuration but nothing shows up in Ports tab.

# version
# INAV/SPEEDYBEEF745AIO 7.1.2 Jun  1 2024 / 00:49:37 (4e1e59eb)
# GCC-10.3.1 20210824 (release)

# status
INAV/SPEEDYBEEF740
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    Galileo 1/1
    BeiDou 1/1
    Glonass 1/0
    Max concurrent: 3

# 
Voltage: 14.59V (4S battery - OK)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
Stack size: 6144, Stack address: 0x20010000, Heap available: 1716
I2C Errors: 5, config size: 10443, max available config: 32768
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = none, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 12, cycle time: 506, PID rate: 1976, RX rate: 9, System rate: 9
Arming disabled flags: NAV RX CLI
OSD: MSP DisplayPort: BetaFlight Compatability mode [30 x 16]
VTX: not detected
GPS: HW Version: UBLOX10 Proto: 34.09 Baud: 115200
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    Galileo 1/1
    BeiDou 1/1
    Glonass 1/0
    Max concurrent: 3

# diff all

# version
# INAV/SPEEDYBEEF74500

# Adjustments [adjrange]

# Re_hz = 100
set setpoint_kalman_q = 200
set gyro_zero_x = 5
set gyro_zero_y = 6
set gyro_zero_z = -4
set ins_gravity_cmss =  968.405
set acc_hardware = MPU6000
set acczero_x = 9

# Mixer: motor mixer

mmix reset

mmix 0  1.000 -1.000  _roll = 25
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_type = PT3
set d_boost_min =  1.000
seiguration
save

# 0
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 3

set mc_i_pitch = 90
set mc_d_pitch = 27
set mc_p_roll = 36
set mc_i_roll = 80
set mc_d_roll = 25
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_type = PT3
set d_boost_min =  1.000
set d_boost_max =  1.000
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
mixer_profile 1
profile 1
battery_profile 1

# save configuration
save

# 0
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 3

set mc_i_pitch = 90
set mc_d_pitch = 27
set mc_p_roll = 36
set mc_i_roll = 80
set mc_d_roll = 25
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_type = PT3
set d_boost_min =  1.000
set d_boost_max =  1.000
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
mixer_profile 1
profile 1
battery_profile 1

# save configuration
save

# 0
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 3

set mc_i_pitch = 90
set mc_d_pitch = 27
set mc_p_roll = 36
set mc_i_roll = 80
set mc_d_roll = 25
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_type = PT3
set d_boost_min =  1.000
set d_boost_max =  1.000
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
mixer_profile 1
profile 1
battery_profile 1

# save configuration
save

# 0
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75

**Comment by MrD-RC** [comment]
The F745 has on MCU inverters. So there is no need for SoftSerial. It would be a performance downgrade for nothing.
