### ISSUE TITLE
INAV 8.0.0 RC1 Issue that Pops up on Target (gcc-arm-none-eabi 11.2.1 "is not implemented and will always fail")

### ISSUE THREAD

**Issue by synersignart** [iNavFlight/inav#10501]
Issue that Pops up on Target compilation

:/Workspace/xpack/xpack-arm-none-eabi-gcc-13.2.1-1.1/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/ld.exe: E:/Workspace/xpack/xpack-arm-none-eabi-gcc-13.2.1-1.1/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc_nano.a(libc_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0xc): warning: _close is not implemented and will always fail

is this the correct Xpack for compilation of Target for this Version of INAV?
xpack-arm-none-eabi-gcc-13.2.1-1.1

![inav 8 0 0 target](https://github.com/user-attachments/assets/5cc247fa-d01f-4ab3-b7ef-439c08ee4aa5)
![inav 8 0 0-2 target](https://github.com/user-attachments/assets/f38ef453-9e21-42ee-93f3-0b1ba74a5360)

**Comment by mmosca** [comment]
Try using WSL instead of MSYS. I don't think anyone is activelly using MSYS these days.

https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20or%2011%20with%20Linux%20Subsystem.md
