### ISSUE TITLE
Cannot connected to inav-configurator when fc board without any sensor?

### ISSUE THREAD

**Issue by kigik** [iNavFlight/inav#10524]
Is there anything  preventing the INAV fc board connected to inav-configurator when fc board without any sensor and OSD chip?
I flashed a fc board ( no any sensor and OSD chip)with INAV FW ,but just see COM5, Failed to open MSP connection.
I think it's more properly to connected to configurator and show error message when some sensor or other peripheral fail (for example, after air crushed), if just stuck on connected to configurator , there is no way to find any PCBA Fail.

**Comment by sensei-hacker** [comment]
> Is there anything preventing the INAV fc board connected to inav-configurator when fc board without any sensor and OSD chip?

No.

> for example, after air crushed

Physical destruction of the board will prevent it from connecting. You can try connecting over UART1 if the USB port is damaged.
