### ISSUE TITLE
motor mixer for FLYING_WING and AIRPLANE only supports single motor setup

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#1052]
I just tried configuring a flying wing using the second motor output on pin #2, but found that it isn't working. After taking a look at the code, I found that these two templates currently only support a single motor on output pin #1. The motor layout diagrams within configurator for these two fixed-wing templates show that both outputs #1 and #2 should be usable for either a single or dual motor setup.

Here's the mixer code that shows both templates implementing the 'mixerSingleProp' motor template for a single-motor setup:
https://github.com/iNavFlight/inav/blob/master/src/main/flight/mixer.c#L215
https://github.com/iNavFlight/inav/blob/master/src/main/flight/mixer.c#L235
https://github.com/iNavFlight/inav/blob/master/src/main/flight/mixer.c#L194

**Comment by digitalentity** [comment]
I'd say we should fix this for 1.6 - simply making default mixer use the same mix both motor outputs is enough. It can be extended for differential thrust quite easily.

**Comment by Schalonsus** [comment]
Just wanted to remind that there is an issue with differential thrust in passthrough
#933

**Comment by Linjieqiang** [comment]
If I use the same timer how can I devide the 50Hz for servos and 400Hz for motors in my fixwing?

**Comment by digitalentity** [comment]
@Linjieqiang impossible, but in general on airplanes motors are fine with 50Hz update rate as well.

**Comment by Linjieqiang** [comment]
Oh???Can I use 50Hz to update the motor?I will have a try. Thanks for your advise.

**Comment by digitalentity** [comment]
On airplanes - yes.

**Comment by Linjieqiang** [comment]
OK.I try it and it shows well.

**Comment by digitalentity** [comment]
Fixed in #1052
