### ISSUE TITLE
NEW TARGET: FOXEER F405V2

### ISSUE THREAD

**Issue by 66nola66** [iNavFlight/inav#10529]
Propose addition of new target asset FOXEER F405V2

**Comment by MrD-RC** [comment]
Are you a representative of Foxeer?

**Comment by mmosca** [comment]
Also, have a look at the new hardware policy: https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by 66nola66** [comment]
No i just bought one and realized its not supported, i like inav. But better ardu.....so hope to see it soon

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Dec 12, 2024 at 4:37 PM, Darren ***@***.***> wrote:   


Are you a representative of Foxeer?

**Comment by MrD-RC** [comment]
> No i just bought one and realized its not supported, i like inav. But better ardu.....so hope to see it soon

You should contact Foxeer and let them know that you would like an INAV target for this flight controller.

**Comment by 66nola66** [comment]
Nope, flying good on ardu.....no reason

**Comment by 66nola66** [comment]
Yeah, it works just fine on ardu, im gonna remove tjis request

**Comment by 66nola66** [comment]
Not needed
