### ISSUE TITLE
LAUNCH - add an option to specify launch idle throttle

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1053]
From RCG:

> I'm using launch mode with my FPV49 wing and it worked many times so far. However, the wing often comes really close to the ground during launch because it needs quite long to spin up the motor and pick up speed. I suppose, a big part of the "dead time" is due to motor_stop preventing the motor to spin on arming in launch mode.

> Sounds like a good idea - set launch_idle_throttle in range from [1000;2000] - 1000 meaning "force motor stop".

**Comment by skaman82** [comment]
@digitalentity wrote you about a possible idea regarding extended autolaunch on gitter
