### ISSUE TITLE
Formatting error in markdown documentation for programming

### ISSUE THREAD

**Issue by psfales** [iNavFlight/inav#10545]
## Current Behavior
There is a formatting error in the documentation for the programming frame work at 
 https://github.com/iNavFlight/inav/blob/master/docs/Programming%20Framework.md
 
 The description for operation 50 (Delta) wants to say |A|>=B, but since | is a markdown character it looks different in the output

## Steps to Reproduce
View the page at https://github.com/iNavFlight/inav/blob/master/docs/Programming%20Framework.md

## Expected behavior
The description of the operation should be visible

## Suggested solution(s)
Escape the markdown characters

## Additional context
As a side note, I found this confusing, as I first thought |A| meant "Absolute value of A" rather than "The amount that A changed in the last 100msec.   Another fix would be to write it differently, perhaps Delta(A)

**Comment by sensei-hacker** [comment]
Done.

https://github.com/iNavFlight/inav/pull/10546
