### ISSUE TITLE
Board position alignment

### ISSUE THREAD

**Issue by Grahamtisse** [iNavFlight/inav#108]
I have discovered an issue regarding the Board Alignment with the naze32.  No matter what degrees of Yaw Rotation is input, the axis remains unchanged!

**Comment by digitalentity** [comment]
Please read the documentation. Board alignment is in deg*10 units.

**Comment by Grahamtisse** [comment]
Thank you for a quick responce.  Im new to github and could you point me in the direction where this is.

**Comment by oleost** [comment]
http://www.rcgroups.com/forums/showthread.php?t=2495732&page=1

https://github.com/iNavFlight/inav/wiki

And please try to dig around and search before asking...
Also use forums for support instead of github.

**Comment by Grahamtisse** [comment]
Thank you for the advise.  Did not realise this kind of information is on
forums.

Best Regards

Graham

**Comment by csurf** [comment]
@Grahamtisse please close out issue if it has been resolved... :)
