### ISSUE TITLE
Sonar not working on beerotorF3 (spracing target)

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav#1088]
I am trying to get sonar working on beerotorF3. rctimer said that it has to go on the SC Port
RC7-SONAR TRIG
RC8-SONAR RCHO

but I just get a flat line in the sensors tab

Am I overlooking something?

**Comment by skaman82** [comment]
Will confirm this with a second unit later

**Comment by digitalentity** [comment]
I wouldn't even try to use sonar with INAV yet. Let's say it's not supported at the moment :smile:

**Comment by DzikuVx** [comment]
@skaman82 it should be now possible to use HC-SR04 with SPracingF3 target
