### ISSUE TITLE
HW - Support for SD-card blackbox logging

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#110]

**Comment by Linjieqiang** [comment]
The "SPRACING F3 EVO" board used sd-card for logging history flight data.It's nice and  effective.[manual](http://seriouslypro.com/files/SPRacingF3EVO-Manual-latest.pdf).So I want know when inav can support this feature……Thanks.

**Comment by digitalentity** [comment]
SD-card logging is there already.
