### ISSUE TITLE
add safeguard to serial processing for 'R' char / bootloader mode entry

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#1111]
Some serial bluetooth modules will output verbose connection info in 'AT' command format during a connection/disconnection event...

example message for a successful manual disconnect:
+DISC=SUCCESS
+READY
+PAIRABLE

The 'R' in the above '+READY' output message will cause the board to inadvertently go into bootloader mode on disconnect. This happens either due to an intentional or link-related disconnect.

Per @stronnag's suggestion, perhaps there should be a check/timeout to make sure that the firmware will go into bootloader mode only when a single 'R' char is sent (i.e., no further characters are received after the R).

**Comment by digitalentity** [comment]
This is tricky. The thing is that we don't have any place to schedule the delay for rebooting into bootloader - the reboot happens instantly after we receive an 'R' character.

**Comment by martinbudden** [comment]
Why is an 'R' character used, why not something more obscure like '~' or '$' ?

**Comment by stronnag** [comment]
Agreed, but perhaps require a quiet period prior to the R. By recording millis for the last received character. Even 500ms would fix the buggy client issue and be easily done in make and the UI

**Comment by stronnag** [comment]
Isn't $ the lead in for MSP. And the character is configurable in the CLI.

**Comment by digitalentity** [comment]
We can probably add a dummy `delay()` for i.e. 100ms and check if there's any more characters in the serial receive buffer. If there is - don't reboot. This will cause a minor 100ms hickup in processing the data but will definitely solve the garbage issue.

**Comment by digitalentity** [comment]
I wouldn't change the default reboot character as it will break Configurator compatibility with previous versions.

**Comment by csurf** [comment]
side-note, but it would seem like a good idea to be able to manually change the reboot character in configurator as well. Or, perhaps have configurator query firmware and retrieve the configured reboot char?

**Comment by digitalentity** [comment]
@csurf can you test the #1113?

**Comment by csurf** [comment]
ok, will test later today/tonight & post back...

**Comment by csurf** [comment]
just built & tested.
Now, there seems to be a problem with the CLI. The exit/save commands aren't correctly rebooting when in CLI, even when connected via USB. 

Plus, when I run 'dump', there's a quick 'beep' at about the halfway point during the scrolling output. 
Also, after trying to save/exit, the EEPROM is being corrupted (all settings are set back to default).

Once I've entered the CLI, I can't get back to the normal tabs, even if I manually disconnect & reconnect. The port seems to hang even though the board is still alive (LED's blinking normally, i.e., it's not in bootloader mode).

I don't know if these issues are related to the 1.6 dev version, my version of configurator (1.5.2), the version of gcc I'm using (5.4q2), or if the serial delay patch is simply breaking everything.

Let me know if you need more info...

**Comment by stronnag** [comment]
Happens regardless of this patch on development  at the moment. Possibly a result of pg changes?

**Comment by csurf** [comment]
@digitalentity, can you help me out by getting me a patched naze build of the release version? I suck at git...

**Comment by DzikuVx** [comment]
I'm on it

**Comment by DzikuVx** [comment]
@csurf https://drive.google.com/file/d/0Bx6X245zlrsnS2E1bks4ZFNZeDA/view?usp=sharing

**Comment by csurf** [comment]
@DzikuVx isn't that a 1.6 build? I need a patched 1.5.1 build

**Comment by DzikuVx** [comment]
ah... damn, my bad :) That was before my morning coffee :) Will make a new one

**Comment by DzikuVx** [comment]
@csurf now it should be fine https://drive.google.com/file/d/0Bx6X245zlrsneDYzWUdoOTJvNUk/view?usp=sharing

**Comment by csurf** [comment]
@DzikuVx 
thanks man, that worked.

@digitalentity, patch seems to work fine, no more issues with board going into bootloader on serial disconnect... looks good...

**Comment by digitalentity** [comment]
Ok, merging and closing.
