### ISSUE TITLE
RTH - Improve RTH with emergency landing

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#113]
By changosurf@RCG: 

> Idea of an 'e-landing timeout'  where it'll basically just do a blind ALT hold at the RTH height (based on whatever RTH height mode was preconfigured) for a given timeout period, and then come down for an emergency landing (probably might help to also have a user-configurable descent rate

**Comment by oleost** [comment]
I would say this sounds good. But without the alt hold at configured rth height, just make it hold current height. (Would suck to see it fly up in case of failure, and would also make it drift longer when emergency landing without GPS)

Reason I think the blind angle mode and alt is a good idea is with acrobatic planes and multirotors one often loses/drops low on satelites when banking hard and doing rolls. With an timer like 5s one would give the GPS a chance of getting a lock.
