### ISSUE TITLE
NAZA E300 esc beeping from INAV 1.4 on

### ISSUE THREAD

**Issue by damsport11** [iNavFlight/inav#1133]
Hello,
I have been trying to revive a F450 using the stock NAZA E300 ESCs, however, when I flash the newest INAV firmware (1.5.1) and connect the LiPo, the esc's start and continue beeping (beep...beep...beep). By accident I uploaded a old version of INAV and this works fine (standard NAZA riddle and motors are functional). I went back to older versions and the beeping starts from INAV 1.4 on. Has been tested on a Naze32 rev6 and SPracing F3 evo. Any idea how to get the ESCs working on the newest version?
Cheers.

**Comment by digitalentity** [comment]
Did you enable PWM_OUTPUTS in Configurator?

**Comment by damsport11** [comment]
...of course not... sorry bout that...
Thanks for the fast help and making great software ;-)

**Comment by digitalentity** [comment]
No worries. Happy flying!
