### ISSUE TITLE
rssi_ppm_invert not working

### ISSUE THREAD

**Issue by sjobbe** [iNavFlight/inav#1150]
It seems CLI command **rssi_ppm_invert** does not do anything. Regardless if it is ON or OFF i get the inverted result: no signal 100% and vice versa, radio next to the copter powered on i get 6% signal.

To replicate the issue: 
- SP Racing EVO with PWM RSSI pads soldered together. (see manual)
- Cable from X4R-SB RSSI pad to SP3 EVO RSSI input
- iNAV version 1.5.1

**Comment by SPlissken** [comment]
I can confirm this issue with a D4R-II and iNAV 1.5.1:

Direct connection from receiver RSSI port to SP Racing Evo RSSI PWM input.
RSSI reading in iNAV Configfurator 1.5.2 shows as inverted: 3% for full signal, 100% for no signal.

**Comment by digitalentity** [comment]
That's actually not a bug. `rssi_pwm_invert` is applied only for RSSI injected into a RC channel. We'll replace it with rssi_invert `setting` that will be applied always

**Comment by digitalentity** [comment]
@sjobbe @SPlissken can you test #1234?

**Comment by SPlissken** [comment]
I can confirm that 'set rssi_invert = ON' now inverts the RSSI reading with a PWM input on the SP3 Racing EVO board with the current development branch.

It doesn't seem massively accurate though so some form of offset in addition to the RSSI scaling may be needed to get it matching the FrSky readings. Should I open a feature request?

Good work on getting the inversion sorted for all RSSI inputs, thanks!

**Comment by digitalentity** [comment]
>It doesn't seem massively accurate though so some form of offset in addition to the RSSI scaling may be needed to get it matching the FrSky readings. Should I open a feature request?

Yes please, we'll try to have this sorted out in 1.7

**Comment by konraddi** [comment]
set rssi_ppm_invert is no valid command in iNav? I cannot invert the ezuhf ppm rssi :(
set rssi_invert = ON is not doing it... 
Update: my bad, the value stays the same, but in the OSD I get a value if 99% with very seldom drops when I go away from the plane in my house

**Comment by digitalentity** [comment]
@konraddi RSSI inversion is working fine in current development. Fix will be included in next release
