### ISSUE TITLE
Flight mode configuration and switching issues

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#116]
Reported by @stronnag:

> Something wierd is happening between at least 'testing' and the configurator. If I check the setting of the machine that successfully executed WP as http://www.rcgroups.com/forums/showp...postcount=4018, then the configurator shows NAV_WP is not set, and HOME_RESET is on my WP switch (and multiple other switches). I do not have HOME_RESET enabled.
> 
> Something very strange, as flipping the switch executed a WP mission on Monday and I've not changed any settings. Glad I didn't know that when I performed the mission test.
> 
> However, if I impose the same CLI settings on e.g. gps-remove-svinfo branch, then the NAV_WP switch is displayed correctly in the configurator; something not right in 'testing'?

**Comment by digitalentity** [comment]
@stronnag 
Not really a bug. I added a new BOX mode - GCS NAV on request from @oize, CLI mode IDs got shifted. 1.0.2 will have a big warning to re-configure AUX settings.

**Comment by Oize** [comment]
Could you please not mention me here. I don't even know you guys :)
Good luck in this project!

2016-03-17 15:03 GMT+03:00 Konstantin Sharlaimov notifications@github.com:

**Comment by digitalentity** [comment]
@Oize, mea culpa, I ment @eziosoft (he goes by oize on RCG) :smile:

**Comment by stronnag** [comment]
I think it is a bug. If I save the settings as:
![cleanflight - configurator_423](https://cloud.githubusercontent.com/assets/158229/13856485/532d0598-ec6d-11e5-9f4c-a50a40ff5ede.png)
Then I disconnect / reconnect (or reboot), then I get this:
![cleanflight - configurator_424](https://cloud.githubusercontent.com/assets/158229/13856511/6e48cd12-ec6d-11e5-91d3-25df7e0b4f3b.png)
(or worst, sometimes with HOME_RESET on multiple switches. 
This is after flashing with clear eeprom, and re-inputting the switches.

Whereas on last nights gps-remove-svinfo build, **with the same aux CLI**, I get
![cleanflight - configurator_425](https://cloud.githubusercontent.com/assets/158229/13856631/02c5bdba-ec6e-11e5-8f59-e676c514d4ed.png)
Note that this build (eab91a4) also has the new HOME_RESET and GCS_NAV options; it just handles them correctly, unlike testing (b0dcc7f).

~~If possible, it would be nice if new modes could be added at the end so as not to break prior settings, and I'm confused as to why just the new settings would break old configs with only numerically lower values (as the gps_remove_svinfo example).~~ --- ah, removal of GTUNE prevents that. Still doesn't explain the inability to retain NAV WP???

**Comment by stronnag** [comment]
And, if I change the order of boxnames in the enum in `./src/main/io/rc_controls.h` to match that in which the names are defined in `./src/main/io/serial_msp.c` (i.e. move `BOXGCSNAV` to the end, then saving NAV WP works again.

And, yes, I distinctly recall hydra telling us that  `permanentId` fixed all this ...

**Comment by digitalentity** [comment]
@stronnag 
I think I've spotted the bug. MSP_MODE_RANGES assumed that boxes[] array is ordered and indexed exactly as boxId_e enum, which may not be true. Saving modes worked correctly, retreiving them and sending to configurator that's what failed.

Fixed, thanks for reporting
