### ISSUE TITLE
Barometer not correctly reading

### ISSUE THREAD

**Issue by Florioo** [iNavFlight/inav#1160]
I have a "sp racing f3 Deluxe" Flight controller. 

If I flash Cleanflight, the barometer works correctly with default settings. (So I know the sensor is working)
 
If I use flash iNav with, the height reading goes to zero after a short time).
This is what happens if i move the controller 0.7 metres up: (Red is what it should be)
![image](https://cloud.githubusercontent.com/assets/1660226/22257633/e4bf8dcc-e25e-11e6-93f2-bbe25b7c38e6.png)

Moving up 1 meter and then down:
![image](https://cloud.githubusercontent.com/assets/1660226/22257546/b5f8aabe-e25e-11e6-85b1-3b85a70f1fb9.png)

**Status Report**
```System Uptime: 279 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 0.01
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, SONAR=NONE, GPS=NONE
Stack size: 2048, Stack address: 0x10002000
Cycle Time: 2005, I2C Errors: 0, config size: 2024
```

Everything is calibrated and the correct barometer is selected.

**Comment by oleost** [comment]
Hi.

This is normal.

Please read wiki https://github.com/iNavFlight/inav/wiki/Getting-started-with-iNav#notes--common-issues

Closing this one.
