### ISSUE TITLE
Parameter Groups - diff does not include mmix

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1161]
`diff` does not include `mmix` when needed (regression against pre-PG) 2725e6a9fc09eceb81b4be6cd2a6ad3929334cbe
````
# mixer
mixer CUSTOM

# servo
```` 
pre-PG (e.g.):
````
# mixer
mixer CUSTOM
mmix reset
mmix 0  1.000 -0.625  1.000 -1.000
mmix 1  1.000 -0.625 -0.250  1.000
mmix 2  1.000  0.625  1.000  1.000
mmix 3  1.000  0.625 -0.250 -1.000

# servo
````
Note that they do appear in `dump`

**Comment by martinbudden** [comment]
OK, thanks. I'll look into it.

**Comment by stronnag** [comment]
Thanks. I've now configured two machines via the PG CLI  (deadcat quad and a tri-copter) and tether-tested them. Seem to respond as expected. I'll fly 1.6 at the weekend.

**Comment by martinbudden** [comment]
Looks like there may be a problem in the diff code for mmix that was ported over from betaflight, see https://github.com/betaflight/betaflight/issues/2223

**Comment by martinbudden** [comment]
Fixed in PR https://github.com/iNavFlight/inav/pulls
