### ISSUE TITLE
Rethink what's reported to "Sensors" tab in Configurator

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1162]
Current design with "Barometer" sensor showing actually estimated altitude is creating issues like https://github.com/iNavFlight/inav/issues/1160.

I think we need to show actual barometer sensor readings (as is done with acc/gyro) there and create a new way to show actual altitude there.

**Comment by WaspFPV** [comment]
How about showing air pressure instead of altitude?

**Comment by DzikuVx** [comment]
I like idea of @andre92

**Comment by DzikuVx** [comment]
This change is already in place. Sensors shows both pressure and altitude now
