### ISSUE TITLE
Will sbufWriteU32 sbufReadU32 cause problem?

### ISSUE THREAD

**Issue by liutairan** [iNavFlight/inav#1180]
I saw the sbufWriteU32 and sbufReadU32 actually use uint_8 to define the basic structure. So when dealing with GPS coordinates, there might be negative values. I found in mwptools uses int32_t for latitude and longitude. So will this cause problem when dealing with GPS coordinates? 

Thanks.

**Comment by stronnag** [comment]
This is not a problem. The use of uint_8 means that that the byte stuffing in iNav handles sign extension correctly. The deserialisation is mwp means that the sign is extended correctly into the result. I fly W of the median (so longitude is -ve :); mwp decodes positions correctly.

**Comment by liutairan** [comment]
All right, thanks~
