### ISSUE TITLE
Unable to arm fixed-wing build on iNav 1.6

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1181]
![image](https://cloud.githubusercontent.com/assets/5670710/22400353/99724b00-e5b2-11e6-84f7-73dd0dfcdd07.png)

Arm mode doesnt not light up.
![image](https://cloud.githubusercontent.com/assets/5670710/22400356/accdb964-e5b2-11e6-8f16-ea776a10f08f.png)

![image](https://cloud.githubusercontent.com/assets/5670710/22400385/61d9ec7e-e5b3-11e6-8a5d-0daf931ba53f.png)

Servo controll is working, and when using `Motor` tab and manually applying throttle to motor the motor spins.

Status, bootlog and dump in pastebin. http://pastebin.com/rVDdErWW

**Comment by flounderscore** [comment]
I’m having the same issues. Flashed OMNIBUS from the latest development. But in my case, it’s possible I’m missing something, although all checks show up green the the configurator and I have GPS lock.

**Comment by digitalentity** [comment]
Interesting. I've just tried on CC3D w/o GPS and it armed without issues. I'll find a GPS module and test again.

**Comment by digitalentity** [comment]
@oleost I believe this is caused by #1182 (easily verifiable by trying arming by sticks). Fixed by #1183

**Comment by oleost** [comment]
Closing this one as the new created issue will servo better. #1182 

( Did try with stick arming, first time also, but failed to realise that I didnt have setup my yaw channel on my taranis on the wing 👍  )

**Comment by DrSensor** [comment]
I have the same problem with sp racing f3 in flying wing setup

**Comment by digitalentity** [comment]
@cimnex please verify that you have all pre-arming checks on main configurator screen all "green" and stick mapping correct.
