### ISSUE TITLE
Switch arming doesn't work

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1182]
Looks like switch arming sometimes is not detected. Might be the root cause for #1181 

Steps to reproduce:

1. Clean the board config
1. Configure remote
1. Calibrate accel
1. Verify that stick arming works
1. Configure ARM mode
1. Verify that switch arming works and stick arming doens't work
1. Reboot the board
1. Switch arming doesn't work BUT stick arming works regardless of ARM mode.

**Comment by digitalentity** [comment]
Looks like `useRcControlsConfig()` is not called on boot which causes `isUsingSticksToArm` to stay `false` on boot regardless of mode config. @martinbudden I believe this was a side-effect of PG conversion.

**Comment by digitalentity** [comment]
We probably are missing a call to `useRcControlsConfig()` from `activateConfig()`

**Comment by martinbudden** [comment]
Yes, certainly seems an error introduced by the conversion.

I think we should rename `useRcControlsConfig` since it is no longer used to set the old config pointers.

**Comment by oleost** [comment]
Bench tested, can confirm fix #1183 working.

**Comment by flounderscore** [comment]
Same here. Bench test went fine.

**Comment by digitalentity** [comment]
@martinbudden can you remind me why you reopened this?

**Comment by martinbudden** [comment]
I think it was so that we would remember to rename `useRcControlsConfig`, since that name is no longer appropriate.

**Comment by martinbudden** [comment]
Addressed by PR https://github.com/iNavFlight/inav/pull/1251
