### ISSUE TITLE
Mixer and PIDs can not be changed without reboot between

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#1187]
Scenario:

1. reset config
1. send MSP_SET_BF_CONFIG and set mixer to airplane
1. send MSP_SET_PID and change PID[0] to any value different from default
1. send MSP_EEPROM_SAVE

Expected behavior:

1. PIDs for FixedWing PID bank are changed

Current behavior:

1. PIDs for MR PID bank are changed

@digitalentity looks like STATE(FIXED_WING) has to be set inside MSP_SET_BF_CONFIG to allow PID and MIXER change without reboot.

**Comment by digitalentity** [comment]
Good find. I'll fix it.

**Comment by digitalentity** [comment]
@DzikuVx please have a look at #1189
