### ISSUE TITLE
Adding Distance to Home in Smartport Telemetry

### ISSUE THREAD

**Issue by elepete** [iNavFlight/inav#1192]
In case of interest for others.
To measure distances I am sending (uint32_t)GPS_distanceToHome in the RPM field.
With that I can measure distances to my (home location). To measure distance between 2 positions away from home location I am reseting home location by a switch during flight.
The code change needed in smartport.c is simple, and can be posted in case of interest.
Just posting here in case this could be of interest as feature to others.

**Comment by DzikuVx** [comment]
Why not to add it as a custom sensor? SmartPort protocol allows it after all?

**Comment by rb1205** [comment]
If that's the case then the best way would be IMHO to include the home coordinates. It's trivial to get the distance from it and you can use it for more advanced stuff, like heading-to-home or a map.

**Comment by digitalentity** [comment]
Anyone going to implement this?

**Comment by DzikuVx** [comment]
I might give it a try as Custom sensor. With my schedule, not sooner than march :)

**Comment by digitalentity** [comment]
@DzikuVx so 1.7 is fine then :wink:

**Comment by elepete** [comment]
@DzikuVx - thank you, but you may not need to do that
I have all code (which is tiny) misusing RPM ready - I will modify to a custom sensor and share, so no need for you to do that work - having that by end of March is no issue

**Comment by DzikuVx** [comment]
Implementation in place in #1414
