### ISSUE TITLE
LED Strip in 1.5.1 Naze...confused!

### ISSUE THREAD

**Issue by GBIAN** [iNavFlight/inav#1199]
I read the Getting Started...hard to believe, but I really did!

Looking to make LED strip work on Naze32 Rev 6.

Wiki says you need to enable in the code using cygwin.

I followed the instructions and looked at the target.h (Naze) for 1.5.1 and found that LED is already defined.

So in the GUI when I enable the option I show 0 available leds.

What did I do wrong?

**Comment by GBIAN** [comment]
When I look in the CLI LED_Strip shows up as a feature that is enabled

**Comment by GBIAN** [comment]
![image](https://cloud.githubusercontent.com/assets/25286369/22451456/86d02446-e723-11e6-86a5-e36f93259f10.png)

**Comment by GBIAN** [comment]
![image](https://cloud.githubusercontent.com/assets/25286369/22451562/7f69aa50-e724-11e6-852c-5d5bec58c539.png)

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/blob/master/src/main/target/NAZE/target.h#L188

Two slashes in front means that it's commented out and is basically not there.

**Comment by GBIAN** [comment]
Oleost. Thank you. I'll try changing it to defined.

Steep learning curve happening over here!

**Comment by GBIAN** [comment]
Did the edit and tried to compile.

Here is what I got;
 /cygdrive/c/dev/inav
$ make TARGET=NAZE
%% startup_stm32f10x_md_gcc.S
make: arm-none-eabi-gcc: Command not found
make: *** [Makefile:738: obj/main/NAZE/startup_stm32f10x_md_gcc.o] Error 127

What did I do wrong?

**Comment by tonyintn** [comment]
In order to add back the LEDs you will need to give up something.  Example in my case I sacrificed Blackbox data recording. I commented that one out and added back the line for the LEDs otherwise the file size will be to big and will not compile without giving an error.
if that's the route you want to go:

Add the following to your Naze (target.h)
1.  Change: //#define LED_STRIP to #define LED_STRIP
2. Also add the following line to the Naze (target.h) #undef BLACKBOX

https://www.dropbox.com/s/xr83nblgnm94z34/inav_1.5.1_NAZE.hex?dl=0

**Comment by GBIAN** [comment]
I did that and still got the same error message when I compiled.

![image](https://cloud.githubusercontent.com/assets/25286369/22534048/698af8be-e8a6-11e6-9e52-3b2dd55f5edb.png)
$ make TARGET=NAZE
%% startup_stm32f10x_md_gcc.S
make: arm-none-eabi-gcc: Command not found
make: *** [Makefile:738: obj/main/NAZE/startup_stm32f10x_md_gcc.o] Error 127

**Comment by oleost** [comment]
Your build environment is not set up correctly, either you forgot to install something or you have forgot to set up path. Follow the guide to the letter.

**Comment by tonyintn** [comment]
****make: arm-none-eabi-gcc: Command not found****
Yep, I would say your path is incorrect the Environment variables must match your arm-none-XXXX path name you called it, it must be consistant.

This might help keep in mind that vid is old so the path and version he is showing is no longer valid but the principle is the same.
 https://www.youtube.com/watch?v=n3Z1fOQJAg8&feature=youtu.be
also 
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows.md

**Comment by GBIAN** [comment]
Thats what I was thinking it might be, I'll double check it all. Thanks.

**Comment by digitalentity** [comment]
This issue seems to be support-related. Closing

**Comment by GBIAN** [comment]
Where do I continue to persue my support-related issue?
