### ISSUE TITLE
telemetry vbat and current

### ISSUE THREAD

**Issue by hali9** [iNavFlight/inav#1201]
In mavlink.c:
In void mavlinkSendSystemStatus(void)
          feature(FEATURE_VBAT) ? amperage : -1,
Should be FEATURE_CURRENT_METER ?

In smartport is:
                if (feature(FEATURE_CURRENT_METER)) {
                    smartPortSendPackage(id, amperage / 10); // given in 10mA steps, unknown requested unit
                    smartPortHasRequest = 0;
                }

**Comment by digitalentity** [comment]
Scheduling for 1.7 - will do a lot of new cool stuff with MAVLink there
