### ISSUE TITLE
NRF24 - Make INAV protocol FCC-compliant

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1202]
Current implementation uses 8 hopping channels which are selected based on `rxTxAddr` (chosen by transmitter). Dwell time is 5ms.

FCC §15.247 Operation within the bands 902-928 MHz, 2400-2483.5 MHz, and 5725-5850 MHz.

> (a) (1) Frequency hopping systems shall have hopping channel carrier frequencies separated by a minimum of 25 kHz or the 20 dB bandwidth of the hopping channel, whichever is greater. Alternatively, frequency hopping systems operating in the 2400-2483.5 MHz band may have hopping channel carrier frequencies that are separated by 25 kHz or two-thirds of the 20 dB bandwidth of the hopping channel, whichever is greater, provided the systems operate with an output power no greater than 125 mW. The system shall hop to channel frequencies that are selected at the system hopping rate from a pseudo randomly ordered list of hopping frequencies. Each frequency must be used equally on the average by each transmitter. The system receivers shall have input bandwidths that match the hopping channel bandwidths of their corresponding transmitters and shall shift frequencies in synchronization with the transmitted signals.

>(a) (1) (iii) Frequency hopping systems in the 2400-2483.5 MHz band shall use at least 15 channels. The average time of occupancy on any channel shall not be greater than 0.4 seconds within a period of 0.4 seconds multiplied by the number of hopping channels employed.

We need to ensure that on TX address is chosen in pseudo-random matter and actual hopping channels are distributed equaly over the band (on average). To be FCC-compliant we also need to increase number of hopping frequencies to at least 15.

It would also be good to be able to exclude certain frequencies from the hopping sequence - this will allow i.e. 2.4GHz digital video (wifi based) to co-exist with nRF24 RC control.

**Comment by martinbudden** [comment]
There's already a facility to exclude certain frequencies. But other aspects of the channel hopping need work. But changing any of this should be fairly straightforward.
