### ISSUE TITLE
Create one place to handle all mapping of sticks to "buttons"

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1211]
Currently I see that its done one way in rc_controls.c
https://github.com/iNavFlight/inav/blob/master/src/main/fc/rc_controls.c#L150
and another way in cms.c ( Which are also hardcoded values )
https://github.com/iNavFlight/inav/blob/master/src/main/cms/cms.c#L582

It would be benifitial to have one place to detect "stick commands" / "stick buttons", so it can be easily used everywhere. Also not hardcoded use todays `min_check` and `max_check`

**Comment by digitalentity** [comment]
Done in https://github.com/iNavFlight/inav/pull/1254
