### ISSUE TITLE
HoTT telemetry problems on REVO

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#1215]
When I activate GPS on the main serial port, HoTT Telemetrie on the flexiport (4pin) and SUMD on UART 6, it does not work all together.
I use the Openpilot Revolution F4 (Revo) Board.

Without the HoTT telemetry it seem to work.

**Comment by digitalentity** [comment]
Please define "doesn't work". Board doesn't boot, hangs up, something is
not functioning etc?

**Comment by Ralfde** [comment]
SUMD on UART6 and GPS on UART3:  The prearmimng check shows hardware health fail and navigation is safe fail. GPS seem not to work correct.

SUMD on UART6 and no GPS, but HOTT Telemetry on UART3: Telemetry does work. The transmitter does show an Electric Air sensor. But no hardware health failure. But the vario values show wrong values.
-500 m and -1.2m/s. Please correct. The value 0 is -500 m. So please check for the offset. The value 120 = 0m/s.
The vario does also not react on pressure changes.

 SUMD on UART6 and no GPS, but HOTT Telemetry on UART1: hardware health pass, but HoTT Telemetry does not work. No Electric Air sensor found.

SUMD on UART6 and GPS on UART 1, but HOTT Telemetry on UART3: hardware health fail

SUMD on UART3 and GPS on UART1: hardware health fail

SUMD on UART1: hardware health pass

SUMD on UART1, no GPS, HoTT telemetry on UART6: hardware health pass, but no Electric Air sensor found. No telemetry.

HoTT Telemetry on UART6, SUMD on UART3, Telemetry does not work. Hardware health pass.

My GPS doesn't work any more. Need to test it, why. But HoTT telemetry does work only on UART3.

**Comment by digitalentity** [comment]
Hm... Looks like your GPS module isn't functioning. I'm not a big expert in HoTT telemetry, there might be harware compatibility issues. Can you verify if HoTT telemetry works with i.e. Betaflight?

**Comment by Ralfde** [comment]
The GPS problem was caused by a died GPS voltage regulator. But the HoTT Telemetry works only on UART3 and the vario data have the offset and do not show the correct altitude and m/s. Please correct this.

**Comment by digitalentity** [comment]
So, to summarize:

 * HoTT telemetry works only on UART3 (Flex port)
 * HoTT telemetry shows incorrect altitude and climb rate data.

@Ralfde is this correct?

**Comment by digitalentity** [comment]
@Ralfde HoTT in INAV only supports EAM sensor (battery status) and GPS sensor (coordinates, altitude above mean sea level, ground speed, distance and direction to home). There is no vario data reported via HoTT telemetry.

**Comment by Ralfde** [comment]
Yes, but EAM and GPS include also vario datas, which should be used correctly.

**Comment by digitalentity** [comment]
Since none of the devs have Graupner radio it might get tricky to develop and test this functionality fast. Scheduling for 1.7

**Comment by Ralfde** [comment]
Dear Konstantin Sharlaimov,
would you or another programmer need a graupner radio for testing?Where should I sent it? 
To who should I send the HoTT protocol data?
Best regards,Ralf
-------- Ursprüngliche Nachricht --------Von: Konstantin Sharlaimov <notifications@github.com> Datum: 02.02.17  12:13  (GMT+01:00) An: iNavFlight/inav <inav@noreply.github.com> Cc: Ralfde <ralf73230@online.de>, Mention <mention@noreply.github.com> Betreff: Re: [iNavFlight/inav] HoTT telemetry problems on REVO (#1215) 
Since none of the devs have Graupner radio it might get tricky to develop and test this functionality fast. Scheduling for 1.7

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iNavFlight/inav","title":"iNavFlight/inav","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iNavFlight/inav"}},"updates":{"snippets":[{"icon":"PERSON","message":"@digitalentity in #1215: Since none of the devs have Graupner radio it might get tricky to develop and test this functionality fast. Scheduling for 1.7"}],"action":{"name":"View Issue","url":"https://github.com/iNavFlight/inav/issues/1215#issuecomment-276930466"}}}

**Comment by digitalentity** [comment]
@Ralfde please email me at konstantin.sharlaimov@gmail.com, I'll handle better HoTT support. Thanks.
