### ISSUE TITLE
Telemetry problem Naze32 full rev6, XR4-SB and INAV

### ISSUE THREAD

**Issue by BoLtWD** [iNavFlight/inav#1216]
I have a Telemetry problem

I am using… Naze32 full rev6, XR4-SB and INAV.

I am using a softserial port 1 Pins 5 & 6 shorted together and connected to the smart port on the XR4-SB. 

I need the Telemetry  to be on a softserial as I need the UART for the GPS

GUI  In configuration of INAV enable CPU serial ports & Telemetry output is ON.
GUI  In ports of INAV soft serial 1 is set to Telemetry Smartport  AUTO 
GUI In the CLI set telemetry_inversion = ON

With above settings I get Telemetry in Clean Flight but not in INAV is there something I am missing?﻿

**Comment by oleost** [comment]
Yes, smartport telemetry is not available on Naze target.

Please read all the mandatory wiki pages.
https://github.com/iNavFlight/inav/wiki/Getting-started-with-iNav
