### ISSUE TITLE
WIKI: Where did the chapters about setting up e.g. ALTHOLD and POSHOLD go?

### ISSUE THREAD

**Issue by Ralf-W** [iNavFlight/inav#1217]
Why were they deleted?
How can they be restored?

Edit:
Found it here https://github.com/iNavFlight/inav/wiki/Navigation-modes#poshold---horizontal-position-hold

But it is missing in the index / table of content.

**Comment by WaspFPV** [comment]
If you expand the "Pages" tab on the right side of the screen, above the table of contents, you will see all pages present in the wiki. The page is listed there too.

**Comment by DAquad** [comment]
Are the CLI commands for ALT+VEL PID Tuning steps still present in INav 1.7.3 I cant follow the guide due to missing "nav_alt_p"\i\d
