### ISSUE TITLE
Battery voltage display with Openpilot Revolution (Revo) F4 board 

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#1218]
I added the voltage devider 10K to 2K2 like descriped here:
http://opwiki.readthedocs.io/en/latest/user_manual/revo/voltage_current.html

I get a voltage reading of only 0.5 V, instead of 12.3 V and I adjusted the voltage scale already to 200.
So the voltage reading is about factor 20 too low.
What is the reason for this? Is the voltage scale calcuated maybe wrong?

**Comment by DzikuVx** [comment]
Is this the oroginal OP Revolution Board or some kind of a clone?

**Comment by digitalentity** [comment]
If it's a cloned board it may already have a voltage divider onboard. Please consult your board manufacturer or vendor for this.

**Comment by Ralfde** [comment]
It is the original one.

**Comment by digitalentity** [comment]
For 2K2/10K divider (1:5.5 divider) you should use VBAT Scale value of 55. I've just tested and classic 1K/10K divider works fine on REVO

**Comment by Ralfde** [comment]
Thanks a lot

**Comment by digitalentity** [comment]
@Ralfde did you manage to get it working?
