### ISSUE TITLE
HW - user-configurable mag calibration timeout

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#122]
In many cases, the hard-coded 30sec timeout period for mag calibration is too fast to perform a proper calibration. So, here is a proposal to add a new CLI var for configuring the mag calibration timeout period, mag_calib_timeout, uint8_t, which would be the desired  timeout period (in seconds), range 30-255, defaults to 30. This would require some simple changes to compass.c & a new definition within CLI.c, etc. 

compass.c
`
 if ((currentTime - tCal) < 30000000) {    // 30s: you have 30s to turn the multi in all directions
//convert to...
 if ((currentTime - tCal) < (cfg.mag_calib_timeout * 1000000)) {
`

...and perhaps it might be more efficient to do a bit-shift in the above case...
`
if ((currentTime - tCal) < ((uint32_t)cfg.mag_calib_timeout << 20 )) {
`

...as absolute precision isn't required and it might help speed up math op's.

Ideally, it would be cooler if we could just have the mag calibration routine detect when the user has stopped moving the model for ~5 seconds, based on gyro readings, but this seems like it would be somewhat complicated & messy to implement. For now, it would seem that it would be easier to just allow the user to configure a longer timeout for mag calibration.

**Comment by brat002** [comment]
Will be great to have visualisation of calibration process like in MissionPlanner.
