### ISSUE TITLE
1.6alpha - naze32 - Extra UART & UART config not saving

### ISSUE THREAD

**Issue by PaulHam211** [iNavFlight/inav#1222]
Possibly 2 different issues here (extra UART & config not saving)

I have just flashed inav_1.6.0_NAZE.hex onto an old Naze32 board (using configurator 1.6.0, installed manually a couple of days ago), I have found a couple of things unusual.
The Ports tab shows UART1, UART2 & UART1 (again, but MSP unchecked)
![image](https://cloud.githubusercontent.com/assets/7596825/22567919/a8c61e94-e989-11e6-8bd8-352c799e0293.png)

When checking the GPS box on  UART2 , it resets to unchecked after clicking 'save and reboot'

And the same for the checkbox for 'gps for navigation and telemetry' in the configuration tab', it resets to unchecked.
![image](https://cloud.githubusercontent.com/assets/7596825/22567930/b268ca6e-e989-11e6-843c-3c953bac53da.png)

**Comment by digitalentity** [comment]
Fixed in #1223
