### ISSUE TITLE
need different nav_rth_abort_threshold for FW vs MC

### ISSUE THREAD

**Issue by WaspFPV** [iNavFlight/inav#1225]
Please consider using 2 seperate values for nav_rth_abort_threshold. The default of 500 meter may be too big for some multirotor pilots. I fly on a field that is not even that big and 500 meter would land my multirotor on a house or on a freeway. 50 meter would do for a MC.
I suggest splitting it in nav_MC_rth_abort_threshold and nav_FW_rth_abort_threshold

**Comment by digitalentity** [comment]
You have presets. 
A lot of parameters are shared between multirotor and fixed wing but should have different values.

**Comment by WaspFPV** [comment]
Ok I will check out the presets and see if that will set a better value for multicopter.

**Comment by digitalentity** [comment]
Currently it doesn't set different values for multicopters vs airplanes, but we should look into it.

**Comment by digitalentity** [comment]
Let's continue the discussion in the Configurator.
