### ISSUE TITLE
INAV 1.6-ALPHA1 Servo settings are not saved

### ISSUE THREAD

**Issue by isilcala** [iNavFlight/inav#1230]
Trying the INAV 1.6-ALPHA1, found that the settings in Servo tab are not being saved. 

Tried two boards: XRACER v2.1 (firmware: SPRACING F3) and Omnibus F3 AIO. Flashed boards with Full Chip Erase checked, then go right into Servo tab, change something and hit Save, then come out and back, settings are gone.

**Comment by digitalentity** [comment]
Fixed by #1232
