### ISSUE TITLE
Blackbox gyro broken

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1231]
On latest alpha gyro is scaled incorrectly which breaks attitude data and scaled [dps] values. @martinbudden I figure this might be related to gyro scaling change.

**Comment by martinbudden** [comment]
Are you using the latest version of the blackbox viewer? It was updated when the scaling was changed in betaflight.

**Comment by digitalentity** [comment]
You are right, I didn't update

**Comment by DzikuVx** [comment]
@martinbudden do you remember a timeframe when this happened in BF viewer?

**Comment by martinbudden** [comment]
The betaflight PR was https://github.com/betaflight/betaflight/pull/1853 , so it would have been sometime around then.
