### ISSUE TITLE
Flashed FC Verification failure timed out but INAV still works is there a problem?

### ISSUE THREAD

**Issue by BoLtWD** [iNavFlight/inav#1249]
I have flashed INAV on my SP Racing F3 Deluxe but after flashing and during Verification it failed With a report "timed out" but after rebooting the FC INAV still works.

Do you think I may have a problem or as all seams to be working don`t worry about it?

I do know I have a faulty magnetometer sensor and not bothered as I wont be using this I will be using an external and will remove this chip from the FC

Can you advise?

**Comment by hali9** [comment]
I still had the CC3D.
Uploading never not completed correctly.
Typically, error verification.
And how have arrived to the end is also a error.
But I never had any probemów with the operation and during flights.

But with SPRACINGF3 upload it always ends up correctly without any errors.
