### ISSUE TITLE
msp on uart1

### ISSUE THREAD

**Issue by killerm1** [iNavFlight/inav#1260]
Hi,

I have an omnibus f3 with a broken usb port but have been able to run betaflight using uart1 and a ftdi. 
when I flashed inav I can no longer get a connection. Im assuming that msp is not enabled on uart1 by default being omnibus has a vcp. Am I correct in thinking this? and if so is it possible to enable it without a usb connection?

**Comment by digitalentity** [comment]
Good point. Maybe we should enable MSP on UART1 regardless of VCP presence.

**Comment by oleost** [comment]
I also have a friend that have exactly this issue.

What I need to change to let him have MSP on UART1?

9. feb. 2017 2.24 p.m. skrev "Konstantin Sharlaimov" <
notifications@github.com>:

**Comment by killerm1** [comment]
I think it should be. you can always disable it if you dont require it on UART1.

**Comment by digitalentity** [comment]
@oleost @killerm1 on it.

**Comment by killerm1** [comment]
@digitalentity thankyou 👍

**Comment by digitalentity** [comment]
I figure this was a side-effect of migrating to parameter groups config storage. Should be easy to fix.
