### ISSUE TITLE
Feature request, betaflight peripherals. Smartaudio and tramp vtx

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1262]
This is to control example immersionrc tramp vtx from FC( extended to example control vtx from Taranis )

https://github.com/betaflight/betaflight/pull/2106
https://github.com/betaflight/betaflight/pull/1283

https://github.com/betaflight/betaflight-configurator/pull/355

Example of use: http://www.nitbeatfpv.com/tramphv-vtx-settings-taranis

**Comment by StewLG** [comment]
I'm interested enough in this to do the work of the merge. Should I attempt a PR, or is there more formality/process in the way the project pulls from CleanFlight/BetaFlight?

**Comment by tgreer** [comment]
Following as would like this too. @StewLG don't see any reason why you couldnt do a PR...

**Comment by fiam** [comment]
Isn't this one fixed by #2084?

**Comment by digitalentity** [comment]
Yes, looks like it. Closing
