### ISSUE TITLE
eeb3f74b32c6b9fd0c96ce8f28d7c230586135b7 does not boot on F1

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1271]
I flashed eeb3f74b32c6b9fd0c96ce8f28d7c230586135b7 to an F1 (flip32). It will not then boot (just the blue led). Subsequent flash attempts require shorting the boot pins (and then it will not reboot).

**Comment by digitalentity** [comment]
Oops, config storage overflow. I missed one `#ifdef` when doing non-volatile waypoints. Fixing.

**Comment by digitalentity** [comment]
@stronnag fixed by #1273
