### ISSUE TITLE
Fixedwing doesnt try and descend after RTH

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1282]
```
INAV/SPRACINGF3MINI 1.6.0 Feb 12 2017 / 00:15:25 (490c164)
mixer FLYING_WING
set nav_rth_allow_landing = ON

```
Folder includes some videos, some logs, DIFF and complete DUMP. https://drive.google.com/open?id=0B-yHzNtOXxbEdERWRWZLOEo0ZVE

Log 129 and video 172539 is together. To sync up watch when I flip arm switch on video. ( Last switch ) RTH should be enabled from 05:12 to 08:00

I let it circle for long time without it dropping any altitude..

PS ignore the failed launch, totally my fault. ( One time failed to turn up throttle and one time forgot I had not set up arm switch as part of bench testing )

**Comment by digitalentity** [comment]
Bug confirmed. The plane doesn't understand that home is reached. Fix pending.

**Comment by digitalentity** [comment]
A fixed-wing will circle around the home waypoint (at `nav_fw_loiter_radius` radios) without reaching it (need to be closer than `nav_wp_radius`). We need to consider home reached for fixed-wing when we are doing circular loiter around it.
