### ISSUE TITLE
Difference between get and dump on various parameteres

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1287]
INAV/SPRACINGF3MINI 1.6.0 Feb 12 2017 / 00:15:25 (490c164)

Looks like there is difference values returned from `get` and `dump / diff`

Example:

![image](https://cloud.githubusercontent.com/assets/5670710/22922442/1661d4ee-f29e-11e6-8940-7b3524a93219.png)

This is when using fixed wing mixer.

While using fixedwing mixer I did try and do `set mc_p_pitch = 39`, this results in dump command showing its still 40. While `get` returns `mc_p_pitch = 39`. So the other way around.

**Comment by oleost** [comment]
Seems to be mainly isolated to mc_ and fw_ spesific pids.

**Comment by digitalentity** [comment]
@oleost I can't reproduce the issue

**Comment by digitalentity** [comment]
Everything is working as it should on CC3D board. Can you please re-test?

**Comment by oleost** [comment]
Out flying now, could you test on an F3 based?

**Comment by digitalentity** [comment]
Tested on EVO - no issues.

**Comment by oleost** [comment]
https://youtu.be/SSFVw8lKEgM

**Comment by oleost** [comment]
This shows much. everything seems like it stuck someplace.  ( difference between GUI, dump and get )

**Comment by oleost** [comment]
So, its seems like somehow I selected profile, probably due to some accidental stick commands or something? However I tried chaning it back by typing `profile 0` but it doesnt seems to work.

**Comment by digitalentity** [comment]
Will try reproducing today, thanks.

**Comment by digitalentity** [comment]
Confirmed.
Looks like diff does not respect the profile at all.

**Comment by digitalentity** [comment]
Ok, figured it out. `profile` commands indexes are incorrect. 'profile 0' is meaningless.

**Comment by digitalentity** [comment]
@oleost is this still relevant? I believe I've fixed the 'profile` command issue - it now accepts numbers 1-2-3 for Profile 1, Profile 2 and Profile 3 and dump/diff provides consistent results.

**Comment by oleost** [comment]
I believe I saw a commit for you fixing it.
Since you have tested it probably safe to assume it fixed.

I'm in work period now and limited time to test.

If I I get any issues again I will reopen issue.
