### ISSUE TITLE
NAV - RTH procedure when close to home

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#129]
Current RTH implementation is buggy:
MR: Climb -> land
FW: Climb out -> RTH -> loiter

Should be:
MR: Land instantly
FW: Don't activate RTH at all

**Comment by oleost** [comment]
Does this take height into account?

So if fix wing are 100meter up above home posisition, what will happend? 

If not I think maybe the old way for FW was better. Maybe someone else can comment aswell.

**Comment by digitalentity** [comment]
@oleost, it doesn't account for altitude. Why you think old behaviour was better?

**Comment by oleost** [comment]
MR is fine, you still have failsafe.

FW new method you loose failsafe. Or is it still climb > loiter?

**Comment by oleost** [comment]
Guess it could be implemented differntly when this is done #91 
So it can enable some kind of loiter with low throttle, (or no throttle if low altitude)
