### ISSUE TITLE
MWOSD modes display support broken with 1.6 c012702

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#1296]
I'm not able to display any modes with MWOSD firmware and microMinimOSD hardware anymore.

**Comment by digitalentity** [comment]
@Schalonsus I don't have a MinimOSD at hand to verify and debug. Can you bisect which commit intorduced the bug?

**Comment by Schalonsus** [comment]
not iNav's fault, some defines in MWOSD firmware causing this.

**Comment by digitalentity** [comment]
Can anybody confirm the issue?

**Comment by Schalonsus** [comment]
There was no issue with iNav, it was MWOSD firmware fault.
Look here, i discussed it with shikra: http://fpvlab.com/forums/showthread.php?34250-MWOSD-for-BETAFLIGHT-CLEANFLIGHT-RACEFLIGHT-PIXHAWK-KISS-DRONIN-INAV-and-others&p=826766&viewfull=1#post826766

**Comment by digitalentity** [comment]
@Schalonsus thanks!
