### ISSUE TITLE
OSD on OmnibusF4SD 1.6 no longer working

### ISSUE THREAD

**Issue by TwoToneEddy** [iNavFlight/inav#1298]
When running the most recent stable firmware the osd was working fine, updating to 1.6 stopped the OSD from working. Any ideas?

**Comment by TwoToneEddy** [comment]
Forget that, i'm being an idiot.

**Comment by ahfynjj** [comment]
My OmnibusF4SD also encountered the OSD does not work, ask, how is your problem solved? THS

**Comment by TwoToneEddy** [comment]
I forgot to enable it on the main configuration screen. There is a switch somewhere on that screen you need to set. Took me a while to find!
