### ISSUE TITLE
Autopilot enhancement: nav_fw_bank_rate paramter to avoid jerky AP behavior

### ISSUE THREAD

**Issue by Dronek** [iNavFlight/inav#1300]
As explained [here](https://www.rcgroups.com/forums/showpost.php?p=36894819&postcount=11335) it would be nice to limit the rate at which nav_fw_bank_angle is reached in order to maintain smooth aircraft behavior in nav mode (i.e. turning to next WP or 180 deg turns after triggering RTH). Similar rate parameters are imaginable for dive and climb too but bank_rate would certainly be the most useful one for fixed wing.

Please close with a short comment when this functionality can be achieved by other parameters.

**Comment by oleost** [comment]
https://youtu.be/50C61gqCBSQ?t=5m15s

**Comment by oleost** [comment]
Maybe try and reduce self leveling p-gain `p_level`

Video showing is an Z84 wing with high rates, but p_level reduced to 10 from 20. Could probably even reduce it more.

**Comment by Dronek** [comment]
Will p_level affect steering input from AP?

**Comment by oleost** [comment]
Ap?

If you mean GPS modes like WP etc then yes.

This adjusts self leveling in angle mode. And all other modes than acro is based on angle mode ( Just like angle works on top of acro mode ).

But I gain should take the rest.

**Comment by digitalentity** [comment]
@Dronek @oleost 
`LEVEL P` controlls the speed of response to angle command. The higher it is - the faster the machine will try to reach the commanded angle
`LEVEL I` is the low-pass frequency of angle response. If you want it smoother (but still fast) - reduce this down to 1 (zero disables)

**Comment by Dronek** [comment]
Thank you both. Will try and report :)

**Comment by Dronek** [comment]
>  LEVEL P  controlls the speed of response to angle command. The higher it is - the faster the machine will try to reach the commanded angle
 LEVEL I  is the low-pass frequency of angle response. If you want it smoother (but still fast) - reduce this down to 1 (zero disables)

Still no chance to fly due to stormy weather. Will close this issue and re-open if the method above doesn't help.
