### ISSUE TITLE
Which  modes work for Airplane and Flying Wing on v1.5

### ISSUE THREAD

**Issue by default-pt** [iNavFlight/inav#1301]
Hi,

I'm having a difficult time to identify which flight modes are working/meant to Airplane and Flying wings. There is no clear statements that can help to check what modes work or not.

From the existing ones (https://github.com/iNavFlight/inav/wiki/Flight-modes) can anyone help identify:

ANGLE - makes sense
HORIZON - makes sense
NAV POSHOLD - makes sense
NAV RTH - makes sense
NAV WP - makes sense
PASSTHRU - makes sense
NAV ALTHOLD - makes sense
TURN ASSIST
AIR MODE
SURFACE
HEADING LOCK
MAG
HEADFREE
HEADADJ
ARM - makes sense
CAMSTAB	
BEEPER - makes sense	
LEDLOW	
OSD SW - makes sense	
TELEMETRY - makes sense	
BLACKBOX - makes sense	
FAILSAFE - makes sense	
HOME RESET - makes sense	
GCS NAV - makes sense	
FLAPERON - makes sense	
NAV LAUNCH - makes sense
SERVO AUTOTRIM - makes sense

Also the configurator should only show modes that can be used for the type of aircraft that is selected.

Can you please check?

Note: Can add a new column on https://github.com/iNavFlight/inav/wiki/Flight-modes to check what type of aircraft is working.

Regards

**Comment by flounderscore** [comment]
For AIRMODE, I'd even say it's required for fixed wing to keep the control
loop running at 0 throttle.

**Comment by default-pt** [comment]
So it should be added to all flight modes?

**Comment by sppnk** [comment]
I said this before, but IMHO, AIRMODE is a weird thing for FW. It should be removed or hardcoded for fw.

**Comment by DzikuVx** [comment]
Firmware allows Configurator only modes that can be enabled on a Fixed Wing or Multirotor.
