### ISSUE TITLE
FW - Speed-aware navigation

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#131]
Option to stabilise speed, not throttle

**Comment by oleost** [comment]
Possible solution

http://fpvlab.com/forums/showthread.php?27854-NAZE32-for-fixed-wing&p=785877&viewfull=1#post785877

""The only thing the FW actually do is checking if ground speed is >5m/s.
If its lower it will increase the throttle to push forward against the wind.
But it's based cruise throttle as speed.
It never go below that in cruise only when descending.""

**Comment by digitalentity** [comment]
@oleost looks like a good solution for airplanes that don't have pitot tube sensor

**Comment by digitalentity** [comment]
@oleost 
Did a quick and dirty implementation of PatrickE's min speed guard - see "fw-throttle-controller" branch. It will be working only when PH/RTH is active.

I'm not sure I didn't break anything, use caution!

**Comment by oleost** [comment]
@digitalentity https://vimeo.com/161521808

At 01:09 its below 5m/s. I think I heard the throttle go up, but not sure.
