### ISSUE TITLE
为什么我刷了inav的固件解不了锁？

### ISSUE THREAD

**Issue by Leen-35** [iNavFlight/inav#1311]
Six surface calibration has been completed, the throttle stroke has been adjusted, but still not. For F3 flight control

**Comment by digitalentity** [comment]
請使用英語。:laughing:

**Comment by liguo-git** [comment]
Six surface calibration has been completed, the throttle stroke has been adjusted, but still not. For F3 flight control

**Comment by digitalentity** [comment]
You can't arm? What is shown on the main screen of Configurator? What version of the firmware do you use?

**Comment by Leen-35** [comment]
Can trigger the unlock, but failed to unlock; buzzer only a drop, I can only describe so much. Brush version 1.5 firmware.


I use the translation software translation, can understand it?

**Comment by Leen-35** [comment]
It seems to have no relationship with inav
