### ISSUE TITLE
CLI PID not save in 1.6rc2

### ISSUE THREAD

**Issue by hali9** [iNavFlight/inav#1319]
In CLI:
> profile 3
> set mc_p_pitch = 96
> save

After reboot in profile 3 nothing change and profile 1 change Pitch P to 96.
Similarly:
mc_p_pitch
mc_i_pitch
mc_d_pitch
mc_p_roll
mc_i_roll
mc_d_roll
mc_i_level

But this work ok:
roll_rate
pitch_rate
tpa_rate

**Comment by digitalentity** [comment]
Looks like in CLI code offset for profile values was not calculated correctly.
