### ISSUE TITLE
LTM stops when failsafe activates. 1.6 RC1

### ISSUE THREAD

**Issue by sppnk** [iNavFlight/inav#1322]
Hi, tested yesterday the following conditions (cc3d):

- autolaunch set.
- plane armed ready to launch.
- LTM starts to work (as I have it configured to send when arming).
- I kick failsafe through switch or switching off my transmitter. This before launch the plane.
- LTM stops sending telemetry (may be it starts the MSP mode, but I dont see the plane disarming).

**Comment by digitalentity** [comment]
If throttle was never increased failsafe will disarm instead of entering failsafe procedure. Try simulating a launch.

**Comment by sppnk** [comment]
I dont see the led of the plane disarming ?¿ It remains not blinking

**Comment by digitalentity** [comment]
Is LTM shared with MSP?

**Comment by sppnk** [comment]
yes it is, because I use minimosd in the same port. Minimosd can read both protocolos at the same time

**Comment by sppnk** [comment]
tested again; when I do a successful launch it remains sending LTM when I switch to failsafe. It stops only LTM if failsafe is activated during autolaunch, and also the launch is aborted (the motor stops). 

So closing this. Thanks.
