### ISSUE TITLE
F3 location failed cannot unlock  （F3飞控gps定位失败，无法解锁）

### ISSUE THREAD

**Issue by Leen-35** [iNavFlight/inav#1327]
How to turn off the GPS positioning  detect？
（怎么关掉这个gps定位检测？）
                                                                                   Thank you！

**Comment by Leen-35** [comment]
@digitalentity

**Comment by rb1205** [comment]
Sorry, what?
(Scusa, cosa?)

**Comment by Leen-35** [comment]
I give up

**Comment by digitalentity** [comment]
I can't understand what you are asking.

**Comment by AkiOffice73** [comment]
在cli輸入 set nav_extra_arming_safety = OFF

**Comment by AkiOffice73** [comment]
然後離開cli前輸入save 否則不會保存

set nav_extra_arming_safety = OFF
save

**Comment by Leen-35** [comment]
我今天更新下1.6试试

**Comment by rb1205** [comment]
Ohh i get it now.

**Comment by DzikuVx** [comment]
I'm closing this since looks like the solution was found

**Comment by Leen-35** [comment]
可以了 @AkiOffice73
![image](https://cloud.githubusercontent.com/assets/20086629/23493790/7b13d3c6-ff49-11e6-82f0-f1fffddc4a15.png)
everybody can try，I didn't search the satellite normal takeoff。（大家可以试试，我的不搜星也能飞了！）
