### ISSUE TITLE
1.6 RC 2 OSD missing toggles 

### ISSUE THREAD

**Issue by crofton77** [iNavFlight/inav#1328]
I just got a Omnibus F3 and flashed to INAV and when configuring the OSD, I have 2 items that I can't turn off. One is the craft_name and the other is 'ch:1' see the image below. Anyone know why I can't turn the off?
![img_0244](https://cloud.githubusercontent.com/assets/3284422/23302159/4a596198-fad9-11e6-8d2b-36983e46fbfc.PNG)

**Comment by DzikuVx** [comment]
See #1333
