### ISSUE TITLE
Serialpassthrough feature

### ISSUE THREAD

**Issue by handsomejackuk** [iNavFlight/inav#1332]
serialpassthrough on naze32 rev 5 targets is this possible ? betaflight has it

and if it is possible is serial passthrough available through softserial ports ?

with the new mwosd chrome configurator i found that communication through serial passthrough and through a bluetooth transmitter was possible so configuration of minim osd is real easy, and osd does not need to be unplugged to  modify osd configuration...

**Comment by sppnk** [comment]
I like the idea

**Comment by metalnow** [comment]
I will make a pr for this one.

**Comment by digitalentity** [comment]
@metalnow thanks

**Comment by hali9** [comment]
There is a gpspassthrough, so work only to GPS.
Unify it to all ports is great idea.

**Comment by RealNightEagle** [comment]
Hi I am new to the forum so sorry for posting in wrong area, if I have.
Can anyone tell me if I can serialpassthrough in INAV to connect to minim OSD via MWOSD software GUI?
I tried serialpassthrough 0 115200  It did not work
My minim OSD is on UART 1 on a SP F4 EVO
Cheers

**Comment by david-ng-hk** [comment]
@RealNightEagle  I own a SP F4 EVO too, and try to do the osd pass through like you did.
here is how to do it. (I am in iNav 2.0RC6, MWOSD is in 1.6, osd is connect to UART 1)

1) in iNav Configurator -> CLI:    serialpassthrough 0 115200 rxtx
2) now, click the disconnect button on the top right corner (iNav Configurator).
3) launch chrome app MWOSD 1.6 free, download here https://github.com/ShikOfTheRa/scarab-osd-gui/tree/master/MW_OSD_GUI/R1.6
4) set the port same as the one in iNav Configurator, and set the baud rate to the one you set in CLI (in this case 115200), then click "Connect"
5) in MWOSD chrome app, it should show "Connected"
6) after you change the setting in MWOSD, save, and click "Disconnect"
7) unplug the fc battery and usb, and plugin again. you can now use the iNav Configurator again.
