### ISSUE TITLE
Blackbox logs shows wrong Hz?

### ISSUE THREAD

**Issue by fireduckfpv** [iNavFlight/inav#1335]
![log-4khz](https://cloud.githubusercontent.com/assets/24962379/23338779/2c2fd58a-fc14-11e6-84aa-3575b98346df.jpg)
![log-500hz](https://cloud.githubusercontent.com/assets/24962379/23338780/2c3094e8-fc14-11e6-9b28-96e78aff5ad1.jpg)

Here are two logs from the same quad flown just minutes apart. (Just hovering) First log is with 4kHz FC looptime, second is with 500Hz FC looptime. But they show very different noise frequencies in the BlackBox Explorer. They both claim to show from 0 - 500Hz. But one (or both) of them have to be wrong. In order to use the D-term and gyro notch filters properly one needs to know what frequencies to use..

In Betaflight the range changes depending on the FC loop. So if one has 1kHz FC loop, it shows 0-500Hz. If one has 2kHz FC loop it shows 0-1kHz and so on. (I assume this is because of the Nyquist frequencies sampling) Should not iNav do this too?

I assume the 4kHz log shows 0-2kHz and the 500Hz log shows 0-250Hz.

4kHz log : [LOG00001.TXT](https://github.com/iNavFlight/inav/files/801847/LOG00001.TXT)
500Hz log : [LOG00002.TXT](https://github.com/iNavFlight/inav/files/801849/LOG00002.TXT)

Drone : Quad 700
FC : Omnibus F4 v2 Pro (onboard sd)

**Comment by DzikuVx** [comment]
I will try to take a look a this

**Comment by DzikuVx** [comment]
OK, looks like frequencies are computed correctly, only spectrum analyzer range is broken and there are few reasons for it. Looks like it has to be fixed in few places

**Comment by fireduckfpv** [comment]
Oki

**Comment by DzikuVx** [comment]
@tomidland issue (and some more) should be fixed in https://github.com/iNavFlight/blackbox-log-viewer/commit/db3b33b7640164fd54935d2caef43b82d52c9623

Please test and in case on any problems create a ticket in Blackbox Explorer project

**Comment by fireduckfpv** [comment]
Great! :) Will check it out!
