### ISSUE TITLE
Feature request: Softserial on Omnibus targets

### ISSUE THREAD

**Issue by isilcala** [iNavFlight/inav#1346]
Latest version of Betaflight does enabled softserial on Omnibus targets, perhaps we could port it to iNav?

**Comment by raul-ortega** [comment]
This is necessary, because like in my case, I have UART1 for MSP, UART2 for GPS and UART3 for RX (FrSky receiver), and I need an additional port to send telemetry to ground station :(

**Comment by scoop3** [comment]
Agreed! I'm on an OmnibusF4Pro, and I need ONE MORE port for Telemetry. Please!! 😄

**Comment by Riffer** [comment]
Afaik Omnibus already support soft serial:
From https://github.com/iNavFlight/inav/blob/master/docs/Board - Omnibus F4.md

> 4 UART ports (UART1, UART3, UART6, Softserial1)

From https://github.com/iNavFlight/inav/blob/master/docs/Board - OMNIBUS.md
> All UARTs are Serial RX capable.

**Comment by scoop3** [comment]
Sorry, yes it does, what I need is for iNav to incorporate resource remapping, so that softserial can be assigned to pwm5 (current BF supports)

**Comment by scoop3** [comment]
Unless I'm missing something... Does anyone know what the default pin is for softserial 1 and 2 in iNav?

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md

( And it only supports 1 softserial, not two. )

**Comment by oleost** [comment]
Closing this one, feel free to reopen if anything is not working as expected.

**Comment by urlu75** [comment]
> Sorry, yes it does, what I need is for iNav to incorporate resource remapping, so that softserial can be assigned to pwm5 (current BF supports)

any tips/news on how to use PWM5 and 6 for softserial instead of small pad ch5 & 6 ?

**Comment by scoop3** [comment]
I believe, currently, as resources aren't currently remappable, custom firmware is the only option. :-/

**Comment by scoop3** [comment]
I agree tho, those pads are tiny.. and I already lifted ch6... So gonna have to figure out how to compile something new..

**Comment by urlu75** [comment]
It should be somewhere in target.h I guess ...
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_TIMER_RX_HARDWARE 4 // CH5
#define SOFTSERIAL_1_TIMER_TX_HARDWARE 5 // CH6

I already made some test with different value, no success, compilation failed or it just doesn't work.
I don't what code lines have to be changes to move softserial to pin A1 and A8 (PW5 & 6).

**Comment by scoop3** [comment]
You might need to unassigned motor 5 and 6 first somewhere as well, so it's not assigned twice?

**Comment by scoop3** [comment]
I'd they'd just incorporate the remappable assets from bf3.1, that'd be perfect haha

**Comment by scoop3** [comment]
I'd they'd just incorporate the remappable assets from bf3.1, that'd be perfect haha

**Comment by stronnag** [comment]
I somehow doubt that; it would just break the diverse platform types that work on iNav and do not work in βF.

**Comment by scoop3** [comment]
If*

How would being able to remap resources to any pin of your choosing do anything other than add diversity to iNav?

**Comment by stronnag** [comment]
So generate the PR and the documentation that does so; the latter being something missing in βF.
For most users this is so far not practical.

**Comment by Riffer** [comment]
Is softserial really to be used by those two incredible tiny pads on the bottom side of the controller?

**Comment by scoop3** [comment]
Haha yes... I already lifted my ch6 pad too :(

Perfect example of why remappable resources would be great.... :-/

**Comment by urlu75** [comment]
for sure with time pad 5 and 6 will be damage and softserial is needed for telemetry :/
GPS, compass and receiver are using other UART.
Remappable ressources or some tips to build a custom firmware with softserial on pwm5 & 6...

**Comment by Gavsv8** [comment]
I followed the doc for the ch5/6 pads and softserial but had to set the baud rate to 19200 on my Flip32 F4 pro 2.5 with XSR to get it working. There was a note somewhere else about this being the maximum for softserial.

**Comment by TwoToneEddy** [comment]
CH5 and CH6 are no longer available at all on the V4 board. If you're using SBUS, external mag and GPS you can't use telemetry which is a pain if you want to do waypoint flying. Can we remap soft serial to pwm5 and 6? I'm just looking into it now but I'm not sure exactly how to do it.

**Comment by cocolimon** [comment]
Where is the ch5 and ch6?

**Comment by teckel12** [comment]
@cocolimon You'll probably find this image useful:

![CH5/CH6 Pads](https://static.rcgroups.net/forums/attachments/7/1/8/0/4/7/a10263427-106-OF4PROV3_001.JPG)

Note that with INAV v1.7.4 the LED pin will be on the J1 connector.  With 1.7.3 it's on PWM5 as illustrated in the above image.

**Comment by haplm** [comment]
I need to second @TwoToneEddy - I have v5 board, and CH5/6 is not there either. Is it possible to move this to PWM5 and PWM6, and have 2 softserials, as in Betaflight?

**Comment by TwoToneEddy** [comment]
I haven't got one of these boards anymore but can't you just use resource reassignment on the cli? I never tried it.

**Comment by haplm** [comment]
If I understand #1145 correctly, resource reassignment is not available in iNav, and maybe will be added in 2.0 when it is released...

**Comment by teckel12** [comment]
I don't believe resource reassignment (at least how betaflight does it) is on the schedule for INAV 2.0. So I wouldn't hold your breath for this.

**Comment by zector555** [comment]
I have been having this issue too, my board does not have the 2 small pads, but PWM5/6 are available.  Im using inav as well.  I think i am close, but softserial still will not enable for me.  This is what ive done (basicly tried to change the ch pads to the pwm pads):

OMNIBUSF4/target.c
// original line { TIM5, IO_TAG(PA1), TIM_Channel_2, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM5, TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO }, // MOTOR_5
{ TIM5, IO_TAG(PA1), TIM_Channel_2, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM5, TIM_USE_ANY }, // MOTOR_5 mod to soft serial

// original line { TIM1, IO_TAG(PA8), TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM1, TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO }, // MOTOR_6
{ TIM1, IO_TAG(PA8), TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM1, TIM_USE_ANY }, // MOTOR_6 mod to soft serial

OMNIBUSF4/target.h
#define USE_SOFTSERIAL1
// original line #define SOFTSERIAL_1_RX_PIN PC8
#define SOFTSERIAL_1_RX_PIN PA1
// original line #define SOFTSERIAL_1_TX_PIN PC9
#define SOFTSERIAL_1_TX_PIN PA8

I got a response on FB inav group for this, someone said it may not be possible  because of the timers shared between gpio pins. Can anyone here weigh in?

**Comment by teckel12** [comment]
@zector555 I believe the issue is the timers.  Timers can be challenging to deal with on microcontrollers. And most have limitations where timers only work on certain pins. But, others have mentioned BF better able to reassign the pins, so that's where I would look first. I have a Pro, so I have the ch5/ch6 pads for SS.

**Comment by zector555** [comment]
Timer issues is way above my level.  I was able to compile, and get the softerial showing in resources, however it does not appear to push any smart port data.  When i get more time, i was going to hook up a ftdi and see if any data is coming out.  Is it worth spending more time on, or am i just beating my head on a wall?

Raul has been helping me on the inav FB group too.

Thanks
# resource
IO:
----------------------
A00: FREE 
A01: SOFTSERIAL1 UART TX
A02: MOTOR4 OUT
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: SOFTSERIAL1 UART RX

**Comment by shellixyz** [comment]
I also tried to move softserial pins to M5/M6 in #2556 without success.

**Comment by r0ba** [comment]
Whats about regular Omnibus board (f3)?

**Comment by grancarajo** [comment]
yes what about regular omnibus f3 board? Using Inav and all uart take it for gps, mag and rx need a sofserial for telemetry if it's possible.
