### ISSUE TITLE
Getting parse error when applying custom mix

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1348]
Verified on fresh install of INAV1.6 on both spracingf3mini and spracingf3.

Trying to example load:
mixer CUSTOMAIRPLANE
mmix reset
mmix 0 1.000 0.000 0.000 0.000
smix reset
smix 0 3 0 -100 0 0 100 0
smix 1 4 0 -100 0 0 100 0
smix 2 2 1 -100 0 0 100 0

Gives this:

INAV 1.6:
![image](https://cloud.githubusercontent.com/assets/5670710/23476023/991d9f90-feb9-11e6-8141-bcc2638dd468.png)

INAV 1.5.1:
![image](https://cloud.githubusercontent.com/assets/5670710/23476041/accc8894-feb9-11e6-93f6-48df375d5583.png)

**Comment by Schalonsus** [comment]
Remove the last zeros from smix. 

smix 0 3 0 -100 0 0 100
smix 1 4 0 -100 0 0 100
smix 2 2 1 -100 0 0 100

**Comment by oleost** [comment]
Is this done on purpose?

The last number are `<box> rule will be applied only when <box> is zero or corresponding SERVOx mode is enabled.`

If this is on purpose and the function is removed, some documents should be updated.
 [Mixer.md](https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md)
https://github.com/iNavFlight/inav/blob/master/src/main/flight/servos.c#L110

**Comment by DzikuVx** [comment]
I remember a commit @digitalentity that removed trailing `0`

**Comment by digitalentity** [comment]
Yes, we removed `SERVOx` modes for some time now as nobody seemed to be using them. `smix` `<box>` rule was a remainder of that and was removed in 1.6

Mixer docs indeed need updating.
