### ISSUE TITLE
Omnibus F4 w SD card Baro problem

### ISSUE THREAD

**Issue by UAV112** [iNavFlight/inav#1350]
I loaded the Omnibus F4 software 1.6. I know that Betaflight has a Hex for Omnibus F4 SD. It seems that INAV does not recognize the barometer on the board. If i try (set baro_hardware = auto )to enable auto the FC Goes into Hardware failure. if i upload the firmware to the board the hardware failure goes away. but, no baro.???

**Comment by digitalentity** [comment]
Are you using OMNIBUSF4PRO target?

**Comment by UAV112** [comment]
No.

**Comment by digitalentity** [comment]
Please use `OMNIBUSF4PRO` target. Tested on Omnibus F4 with SD-card slot
