### ISSUE TITLE
Enhancement: Force passthrough on plane until gyro has done its boot calibration.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1352]
As title says, is it possible to force passthrough mode on airplanes until gyro has done a succesfull self calibration?

I`ve heard of two examples now where this probably would have helped pilot not to crash the airplane. For many is hard to react and think that passthrough is the solution after example an power failure and reboot of FC in air.

**Comment by digitalentity** [comment]
Might be a good idea.

**Comment by digitalentity** [comment]
@oleost can you please test the #1610 and close this issue if it works for you?

**Comment by oleost** [comment]
I've been unable to test lately.

@brat002 @sppnk got a chance to test?
