### ISSUE TITLE
Failsafe kill switch refactoring

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1355]
I wonder if failsafe kill switch setting should be removed completely. If you can spare a switch for FAILSAFE mode you surely can space a switch for ARMing which will give you the same manual disarm opportunity.

If you want actual signall loss do disarm the machine the best way to do that is to configure failsafe procedure to DROP the machine.

**Comment by martinbudden** [comment]
I've always wondered why anyone would want to set failsafe with a switch. It is useful for testing failsafe mode, I suppose, but I can't really see a use for it in normal flight.

**Comment by digitalentity** [comment]
`FAILSAFE` flight mode is useful for receivers that can't go to no-pulses and only have pre-set failsafe (like many Spektrum-compatible receivers).

I'm talking about `failsafe_kill_switch` setting which bypasses failsafe procedure and disarms instantly if `FAILSAFE` flight mode is activated from a switch (basically implementing a *disarm* switch).

**Comment by Redshifft** [comment]
@martinbudden  Essentially It needs to be called just "kill switch" and do just that, a safety feature.
Also any links to the failsafe mechanism be  removed as far as possible

**Comment by raul-ortega** [comment]
I would remove it!!!

**Comment by digitalentity** [comment]
I suggest changing it to a flight mode called `KILL SWITCH` that would instantly disarm and prevent rearming.

**Comment by oleost** [comment]
@digitalenitity do we need it? Why just not disarm?

**Comment by Redshifft** [comment]
@digitalentity  Yup, pretty much what it does now with a less confusing name - perfect

**Comment by sppnk** [comment]
I vote for remove enterely this 'kill switch' thing. As @digitalentity said, you can set failsafe to drop  the aircraft, so if this is causing troubles and  disarming machines in-flight it should be removed.

**Comment by Dronek** [comment]
> I suggest changing it to a flight mode called  KILL SWITCH  that would instantly disarm and prevent rearming.

@digitalentity : thinking of fixed wing, it may make sense to additionally kill PWM output when killswitch is activated. As of now a disarmed plane will still direct roll/pitch commands to the servos. IMHO, a killswitch should completely kill any thrust/steering related output.

**Comment by digitalentity** [comment]
@Dronek good point - and not only on airplanes, but also on multirotors. To let ESCs know that everything is dead.

EDIT: If we are going to keep the kill switch it should do something more than just disarm. Maybe block re-arming completely, killing motors/servos, LEDs etc.

**Comment by oleost** [comment]
I feel we have two choices.

1. Keep it as it, but update documentation more.
2. Remove it entirely

Or third:

Remove it entirely. Create a new flight mode which is "Kill switch / output 0" and let it disable all output just like the pwn feature. It will not disarm only kill outputs.

**Comment by oleost** [comment]
#1475
