### ISSUE TITLE
F3 1.6 compass does not recognize!（F3飞控 1.6指南针不识别！）

### ISSUE THREAD

**Issue by Leen-35** [iNavFlight/inav#1358]
Compass normal！

**Comment by digitalentity** [comment]
What's the issue exactly?

**Comment by Leen-35** [comment]
The compass is normal and the ground station is not detected。Repeated insertion, sometimes normal。the ground station 1.6。

**Comment by DzikuVx** [comment]
Since topic seems to be abandoned and it looks like it's a hardware failure, I'm closing it. In case new information appears, feel free to reopen
