### ISSUE TITLE
Detect GPS glitch issue

### ISSUE THREAD

**Issue by mahowik** [iNavFlight/inav#136]
I suppose 2nd condition is true almost always and it means gps glitch will be detected for 99% of new gps data:   

https://github.com/iNavFlight/inav/blob/master/src/main/flight/navigation_rewrite_pos_estimator.c#L217

```
/* Condition 1: New pos is within predefined radius of predicted pos */
    if (gpsDistance > INAV_GPS_GLITCH_RADIUS)
        return true;

    /* Condition 2: New position must be reachable within INAV_GPS_GLITCH_ACCEL * dt * dt from previous position */
    if (gpsDistance > (0.5f * INAV_GPS_GLITCH_ACCEL * dT * dT))
        return true;
```

for 10hz gps output: (0.5f \* INAV_GPS_GLITCH_ACCEL \* dT \* dT) = 5 
for 5hz gps output: (0.5f \* INAV_GPS_GLITCH_ACCEL \* dT \* dT) = 20

where gpsDistance it's position error between prediction and noisy raw gps data and always more than 5cm I think

Just for example, Arducopter code has almost the same logic but 2nd condition will run only if 1st condition is false

```
 // all ok if within a given hardcoded radius
    if (distance_cm <= _radius_cm) {
        all_ok = true;
    } else{
        // or if within the maximum distance we could have moved based on our acceleration
        accel_based_distance = 0.5f * _accel_max_cmss * sane_dt * sane_dt;
        all_ok = (distance_cm <= accel_based_distance);
    }

```

**Comment by digitalentity** [comment]
@mahowik good spot, thanks!
