### ISSUE TITLE
Take volts and amps values from MSP

### ISSUE THREAD

**Issue by sppnk** [iNavFlight/inav#1366]
As MWOSD can take variables from FC like RSSI and others, why dont allow the reverse thing? Could be done? (of  course FC should to be able to take them).

This is because in many setups the volts and amps are only in the OSD, but sometimes we fly the same airplanes w/o vtx, third view, and would be nice the FC to have this (for telemetry at least).

Another advantage for some boards is that you wouldn`t have to make a voltage divider for the FC when mounting the minimosd.

I have open the same request in mwosd repo.

What do you think?

**Comment by tednv** [comment]
i have voltage + current in both osd and fc/gc/ez-gui in all my NAZE and F3 builds. what FC are you using and where are you seeing a limitation?

**Comment by sppnk** [comment]
Where are you measuring them? I do in my OSD, so I cant take the values to the FC. May be I should forget this and take always the reads in my FC's directly, but it is a more complex wiring.

**Comment by tednv** [comment]
I use an apm power module with NAZE and F3 FCs (for current sensor and as UBEC). Wiring is simple, you just split the wire. One will go to the FC and one to OSD. For VBAT/VCC it's the same thing, you just have a wire going from battery to both and in OSD settings turn off FC voltage/current and use the readings directly in both FC and OSD. Current and Voltage inputs on OSD and FC are both analog voltage measurements, so you can send it to as many things as you want

**Comment by sppnk** [comment]
Thanks for your advices, I have just finished the mod in my cc3d. Now I read the values directly in it.

Re.thinking on this, I guess it is better this way, so I dont know if the effort to modify MSP worths it.

So, I am fine now. Closing this.
