### ISSUE TITLE
Problem with RC input and OneShot ESC on REVO target

### ISSUE THREAD

**Issue by anbello** [iNavFlight/inav#1377]
On my Revolution Mini board with iNav 1.6 if I set normal PWM ESC I have no problems if I set OneShot ESC the RC input stops to work.
If I try to run the motors from the configurator is all OK so there is no problems with my ESC in OneShot mode.

**Comment by digitalentity** [comment]
Are you using PWM or PPM RC input?

**Comment by digitalentity** [comment]
Also, what target do you use? Does REVO target support Revolution Mini boards?

**Comment by anbello** [comment]
I am using PPM RC input.
The Revolution Mini is identical to the Revolution, the only difference is that the Mini has no radio module, and so the target is REVO.
I tried both with the original 1.6 (internal compass) and with the little mod I asked you on the forum (external compass) and I have the same problem when I set OneShot.

For those who have not read about in the forum, the mod for external compass on external i2c bus is:
add:
#define MAG_I2C_INSTANCE I2C_DEVICE_EXT
to:
src/main/target/REVO/target.h

**Comment by digitalentity** [comment]
@anbello thanks. This is now enough to try and reproduce the issue

**Comment by digitalentity** [comment]
This is a hardware timer issue. On a REVO we have a lot of motor output - 11, and one of the outputs use the same timr (TIM12) that is used for PPM input.

**Comment by anbello** [comment]
Is it possible to eliminate the use of the motor output that use TIM12?

**Comment by digitalentity** [comment]
@anbello this is possible. I'll remove the clash.

**Comment by anbello** [comment]
@digitalentity 
With this mods in file "main/target/REVO/target.h":
```
// Number of available PWM outputs
//#define MAX_PWM_OUTPUT_PORTS    11   // this is modified
#define MAX_PWM_OUTPUT_PORTS    6
#define TARGET_MOTOR_COUNT      6   // this is added
```
I have PPM RC input and OneShot ESC working together, but I think this is no news to you.
