### ISSUE TITLE
Feature Request: add support for CJMCU-530 / vl53l0x i2c laser sensor to replace sonar

### ISSUE THREAD

**Issue by tednv** [iNavFlight/inav#1379]
For low altitude hover the i2c CJMCU-530 or VL53L0X  laser sensor would be much better than sonar

These sensors have a 2 meter range

Sonar has many issues especially transitioning between different surface types and changes in airflow

This sensor is inexpensive, tiny, low power consumption, is safe for your eyes, and there's already plenty of arduino code that simply has to be ported over to inav driver

There are some issues in cleanflight github mentioning expensive laser sensors, but no one wants to touch them in cleanflight code. These are fairly cheap and are readily available on ebay and amazon

code here:
https://codeload.github.com/pololu/vl53l0x-arduino/zip/master

more info on sensor:
http://www.st.com/en/imaging-and-photonics-solutions/vl53l0x.html

I believe this could be a very valuable driver for inav for landing assistance, low altitude hover, or even for avoiding collisions

**Comment by Linjieqiang** [comment]
This sensor looks great.

**Comment by digitalentity** [comment]
I have one of those in the post office waiting to be picked up. @DzikuVx is testing his sample as so far is not very happy about it's performance.

**Comment by digitalentity** [comment]
If it will function up to 1.5-2m *in daylight* - it will be a sonar killer

**Comment by tednv** [comment]
I'm waiting for mine to come in also, will do some testing using arduino code first but from the specs it looks much better than sonar sensors. I ended up giving up on them and removing them from my builds since they are essentially useless when moving over changing surfaces or even solid concrete with slight changes in throttle

this page has good description, should work well in bright daylight according to them
http://www.icstation.com/cjmcu-laser-range-sensor-module-rangefinder-distance-measurement-sensor-p-9907.html

test:
https://youtu.be/v8BYS-LokaE?t=381

**Comment by digitalentity** [comment]
Sonars in general are not that bad - cheap ones like $1 HC-SR04s are crap, but more expensive ones are amazing. You need to mount them properly and process the data with sufficiently smart algorithms. 

Have a look at CONNEX Falcore drone - it uses sonar for altitude hold and it's perfect.

**Comment by DzikuVx** [comment]
OK, since implementation is in place, I suppose we can close this one #1944
