### ISSUE TITLE
Problem: Calibrate magnetometer button greyed out

### ISSUE THREAD

**Issue by avirotstein** [iNavFlight/inav#1384]
Calibrate magnetometer button in the inav configurator (1.6.2) is greyed out unless first clicking sensors tab and then clicking back to the setup tab

**Comment by digitalentity** [comment]
Wrong repository. Please re-open in inav-configurator repo: https://github.com/iNavFlight/inav-configurator

**Comment by AustinSaintAubin** [comment]
Posted to: https://github.com/iNavFlight/inav-configurator/issues/162
