### ISSUE TITLE
Problem: garbled blackbox logs

### ISSUE THREAD

**Issue by avirotstein** [iNavFlight/inav#1387]
As instructed here https://github.com/iNavFlight/inav/blob/master/docs/Blackbox.md using Cleanflight's blackbox log viewer on iNav log files generated by iNav 1.6.0 on an Seriously Pro Racing F3 Delux board (onboard spi flash), results in most parameters and graphs outputting garbled data. (however works correctly via Cleanflight firmware)

**Comment by WaspFPV** [comment]
Does it work with the Betaflight blackbox viewer?

**Comment by oleost** [comment]
Use INAV blackbox viewer. @digitalentity maybe release it to the store as well?

And yes, docs should probably get updated

**Comment by DzikuVx** [comment]
@avirotstein Please use INAV version of BB logs viever : https://github.com/iNavFlight/blackbox-log-viewer
