### ISSUE TITLE
Target: BETAFLIGHTF3

### ISSUE THREAD

**Issue by gregorg** [iNavFlight/inav#1389]
This is a great AIO board, can you add this target ?

**Comment by digitalentity** [comment]
I need to have a look. I suspect there is no possibility to add compass there which will render it useless for quads with INAV; also it only has 4 outputs meaning it is a viable option only for flying wings with only 2 servos.

**Comment by digitalentity** [comment]
Actually I2C can be made available if UART1 is removed. Then it will be possible to use it on a quad.

**Comment by oleost** [comment]
Also remember you got DJI naza GPS for boards without i2C exposed.

**Comment by gregorg** [comment]
Actually I want to use this board for a flying wing :)

**Comment by digitalentity** [comment]
I'm postponing this to 1.8 in anticipation to make it along with  #1591

**Comment by brkdwn** [comment]
I'am also interested for this target on a wing. I don't see it in 1.7. Is it still planned for 1.8 ? and then what is the time frame for 1.8 (not very aware of inav release  rythme)...

thx you for the great work !

**Comment by airiclenz** [comment]
I would love to see the  BetaflightF3 as a target as well. Thanks for your awesome work!
/Airic

**Comment by miginv** [comment]
I would also like to have it. Even without compass, I always like to use inav because GPS works great and iNav, but the same setup in Cleanflight or Betaflight doesn't work as good or even it is not detected. In my case I use GPS to have the coordinates in case I lose the drone far away. It already save my life once.

**Comment by shellixyz** [comment]
I tried to add support for this board, feedback is welcome in PR #2514. You can find the code here https://github.com/shellixyz/inav/tree/BETAFLIGHTF3_target_complete

**Comment by digitalentity** [comment]
Done
