### ISSUE TITLE
Improve preset so it knows what board ( CPU ) its applying preset to

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1394]
From issue #1392 :
 @oleost @DzikuVx I wonder if we can report CPU family as an extra field in MSP_BOARD_INFO and check it when assigning presets.

It's somhow more comlicated since ale gyro bus comes in place. But yes, CPU family reposrting would be nice. At least we could say the user that this is probable to fail

**Comment by DzikuVx** [comment]
With deprecated F1 this is not relevant anymore
