### ISSUE TITLE
NAV - Use raw GPS velocity in calculations

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#14]
Current code calculates GPS velocity from coordinate difference. @bubi-007 suggested that raw velocity from GPS unit should be used instead. I think it's worth trying out.

**Comment by digitalentity** [comment]
This can be done by using `GPS_speed` and `GPS_ground_course`, but code MUST check that GPS unit provide these values - it is not a GGA message, it's a RMC message and it can be disabled in GPS module for some reason.

**Comment by digitalentity** [comment]
GPS data validity addressed in 6375c485a53eea080cd23bf85c0b0b3a75548305

**Comment by bubi-007** [comment]
you 'can' disable everything.
but you can subscribe for the velocities in the ned frame:
0xB5,0x62,            // Header             Turn On UBLOX NAV-VELNED Msg
0x06,0x01,            // ID
0x03,0x00,            // Length
0x01,                     // Msg Class    NAV
0x12,                     // Msg ID       VELNED
 0x01,                    // Rate         1
0x1E,0x67,            // CK_A, CK_B

depends on what you like.

**Comment by digitalentity** [comment]
The navigation code should not depend on a specific hardware feature (in your example an UBLOX GPS module). If GPS for whatever reason does not provide velocity information, navigation code must still function properly.

**Comment by bubi-007** [comment]
i just take what works - ublox does and the rest is not so reliable.

**Comment by digitalentity** [comment]
Sticking with ublox-specific features would effectively remove support for nmea-only gps receivers. We can detect provided information and use what's best - that would be velocity info if available and coordinate difference as a fallback. This will improve things for ublox users and will not break anything for others.

**Comment by digitalentity** [comment]
Done in 05c115ba6edb79f5f64f8c756c2787d14e1336d0. Untested.
Edit: It just occured to me that this patch also prevents a possible bug with polled GPS (i.e.I2C-NAV). When no new data is available a polled gps module would return previous data, Coordinate difference would then yield zero velocity which will probably be incorrect. Using last known velocity is a better option IMO.

**Comment by digitalentity** [comment]
Did a test today. Didn't work as good as I thought it will be. However the test was done on poorly tuned copter, so it could be vibration messing up with velocity calculation from accelerometer. Need to re-tune and re-test. If it will work less reliable than coordinate derivative - this will be removed.

**Comment by digitalentity** [comment]
Did another test today. Was working MUCH worse than plain old coordinate derivative. Closing.

**Comment by bubi-007** [comment]
the current approach sucks.
bf and cf need a complete rewrite on this subject.

**Comment by digitalentity** [comment]
@bubi-007 
Please assist in getting this working,

**Comment by bubi-007** [comment]
first i am integrating altitude hold using gps and accelerometer.
then i go into navigation.

**Comment by digitalentity** [comment]
@bubi-007 
Can you please share your code?
