### ISSUE TITLE
Is it possible to arm by sending out arm signal and then hold last valid value?

### ISSUE THREAD

**Issue by liutairan** [iNavFlight/inav#1415]
I am trying to use MSP as the wireless control and telemetry method. 

I am able to arm my quadcopter by sending out raw rc values (aux1 for ARM) to FC continuously or get data from FC separately, but I wish to be able to get data (mainly GPS and other flight status) while flying. 

The serial port will get too busy if sending out raw rc values and requesting data at the same time. So I wonder is it possible to send out arm signal and then hold the last valid value so that I only need to send out ARM signal once, then the rest time I can focus on getting flight data.

**Comment by liutairan** [comment]
Currently once I stop sending out arm signal, FC will get to failsafe mode quickly.

**Comment by rodizio1** [comment]
If I remember correctly, RX_MSP wants a new packet every 200ms or at 5Hz rate, otherwise it considers the R/C link as broken and will enter failsafe. Do you send packets at a high rate? 5 MSP packets per second shouldn't fill up the serial link (not sure what baudrate you use though, and if something forces you to a low baudrate).

**Comment by liutairan** [comment]
@rodizio1 Because I use RX_MSP to check GPS, sensor status, flight mode, send out raw rc .... I did too much with it. Lol.

**Comment by liutairan** [comment]
I use baudrate 115200 for RX_MSP.

**Comment by rodizio1** [comment]
I have never used it to do other stuff with it, just sending msp raw rc packets. On an F1 based Afroflight rev 5 running Cleanflight I used 100 packets per second which worked fine without overloading the FC. I don't remember exact figures, but I think it was at about 200 or 300 packets per second when the FC became overloaded.

So I'd figure, sending only let's say 5-10 msp raw rc packets per second (just enough to keep it from going into failsafe) shouldn't affect other stuff like telemetry too much.
