### ISSUE TITLE
FW - Make "Elevator compensation" adjustable

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#142]
Make "Elevator compensation" adjustable in as CLI command.
http://www.rcgroups.com/forums/showpost.php?p=34338337&postcount=4392

**Comment by sppnk** [comment]
great, thanks.

**Comment by stronnag** [comment]
I guess this does not yet use SONAR to detect landing more accurately (I have  a number of auto-land on a crappy baro and sonar equipped machine if that is useful).

**Comment by digitalentity** [comment]
@stronnag code for sonar-based landing detection is there, but I'm not sure it's working...
