### ISSUE TITLE
CLI - update docs, remove "rateprofile" command

### ISSUE THREAD

**Issue by skavengeer** [iNavFlight/inav#1420]
inav ver 1.6.1 nase32
command  CLI
rateprofile index (0 to 2)
/*
https://github.com/iNavFlight/inav/blob/master/docs/Cli.md
*/
do not work 
Unknown command, try 'help'

**Comment by digitalentity** [comment]
Rate profiles were removed since 1.6. Need to update docs.

**Comment by skavengeer** [comment]
opps
Is this a thruth, someone must change file CLI.md

**Comment by digitalentity** [comment]
I've changed the name, lets keep it open
