### ISSUE TITLE
ESC not regognized

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#1421]
Hi there.

I got an problem. My ESCs won't connect. Nothing happens not one single Beep.
Everything works fine with Cleanflight just inav won't work.
Do I have to flash my ESCs?
If yes, how? I'm pretty sure that my ESCs have BlHeli bootloader.

thanks for response :)

**Comment by oleost** [comment]
Have you enabled pwm output as the red glowing text tells you?

**Comment by ghost** [comment]
i thought it is just for pwm input.
not for sbus

i will try it
but thanks
