### ISSUE TITLE
[Feature support]Add airspeed support for plane.

### ISSUE THREAD

**Issue by Linjieqiang** [iNavFlight/inav#1423]
- [x] Add analog airspeed indicator support (ADC support, #1456)
- [x] Add analog airspeed indicator support (actual driver, #1503)
- [ ] Add virtual airspeed sensor
- [ ] Add airspeed PID scaling
- [ ] Add airspeed controller for navigation modes

**Comment by Dronek** [comment]
It is coming...
See [here](https://github.com/iNavFlight/inav/pull/386) and [here](https://github.com/iNavFlight/inav/pull/793).

**Comment by Linjieqiang** [comment]
I will take some PRs in this https://github.com/iNavFlight/inav/pull/1456.

**Comment by digitalentity** [comment]
@Linjieqiang I took the liberty to edit your issue description and change it to task list.

**Comment by Linjieqiang** [comment]
@digitalentity Great.Come on.

**Comment by ServError** [comment]
Edit - Was just made aware of an existing PX4 driver for this sensor as well (for raw mode), located [here](https://github.com/ArduPilot/PX4Firmware/blob/master/src/drivers/ets_airspeed/ets_airspeed.cpp)

A number of us already own the EagleTree Airspeed V3 sensor from other projects, which reads two bytes over i2c in "raw" mode, providing a m/s reading using a formula which has been semi-verified [here](https://www.rcgroups.com/forums/showpost.php?p=25357499&postcount=142)

It also supports a ["3rd Party" mode](http://www.eagletreesystems.com/Manuals/microsensor-i2c.pdf) in which i2c reads out in mph or kph, using the built-in self-correcting calibration, depending on what the user has set. There is no way to determine if it is in mph or kph through the data though, so this gets complicated unless you poll the user for which mode it is in from the configurator.

Official documentation claims that the i2c address is 0xEA while some users report needing to use 0x75

From the pdf above, it seems a driver would be trivially easy to implement. Does anyone with a unit want to take a stab at it? If not, I'll try to get around to it at some point.

**Comment by digitalentity** [comment]
@ServError now this is interesting. Yes, I believe it should be fairly trivial to implement - I would have a crack at it, but unfortunately I don't own a unit to debug with.
