### ISSUE TITLE
AIRPLANE configurations don't work on SPARKY board

### ISSUE THREAD

**Issue by denrom** [iNavFlight/inav#1426]
When you turn on the "Flying Wing" configuration, the PPM input stops working.
Board: Sparky1.1
Firmware: 1.6

**Comment by digitalentity** [comment]
It's only for flying wing or for any airplane configuration - ARIPLANE, CUSTOM_AIRPLANE as well?

**Comment by digitalentity** [comment]
Nevermind, figured it out. Airplane configurations are not supported on Sparky at the moment.
