### ISSUE TITLE
blheli 1wire issue

### ISSUE THREAD

**Issue by Viald** [iNavFlight/inav#1429]
Hello.
I'm not able to connect BLHelisuite to my ESC using 1wire.
I can do it if my FC is running cleanflight. I have flashed my ESC with the last firmware and change the bootloader to the last blheli release.
Does inav still support 1wire ?

**NAZE32 rev 6a / Inav 1.6.2 / [ESC ](https://goo.gl/Ay4bHY) BL20A BLHeli 16.6.14 Bootloader BLHeli c /**

Thank you.

**Comment by Redshifft** [comment]
Blheli Passthrough is not available for Naze32 targets - quickly flash some old cleanflight on and setup the ESC's

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/wiki/Supported-boards

**Comment by Viald** [comment]
Thank you.
