### ISSUE TITLE
Flip32 F4 stuck on "erasing..." flash failed using target revo and airbot f4

### ISSUE THREAD

**Issue by hopatz** [iNavFlight/inav#1431]
Hi,
already try flashing Flip32 F4 several hours using inav target revo and airbot F4, both stuck at "erasing,,," step. 

error log
2017-03-19 @ 06:16:51 -- USB device successfully opened with ID: 19
2017-03-19 @ 06:16:51 -- Detected device with total flash size 1024 kiB
2017-03-19 @ 06:16:56 -- USB device successfully closed

why always closed? after usb opened?
please help how to flash this board 

note 
flashing via betaflight no problem

thanks

**Comment by oleost** [comment]
Tried unticking "Full Erase" ?

**Comment by hopatz** [comment]
Still same no help..
But just solved using dfuse injection file method
