### ISSUE TITLE
Built in OSD (omnibus f3): Battery level icon is always almost full

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#1444]
The icon representing the battery level always keep almost full.

[https://www.youtube.com/watch?v=hqOCHuA-ISE](https://www.youtube.com/watch?v=hqOCHuA-ISE)

**Comment by raul-ortega** [comment]
[simba-1.6.1-19.03.2017-diff.txt](https://github.com/iNavFlight/inav/files/856509/simba-1.6.1-19.03.2017-diff.txt)
[simba-1.6.1-19.03.2017-dump.txt](https://github.com/iNavFlight/inav/files/856510/simba-1.6.1-19.03.2017-dump.txt)

**Comment by digitalentity** [comment]
Try uploading this font
[default.mcm.gz](https://github.com/iNavFlight/inav/files/856625/default.mcm.gz)

**Comment by raul-ortega** [comment]
The font by itself doesn't solve this issue. However, the pull request I have submitted solves it together with the font.
By the other hand, the closed issue [#1443](https://github.com/iNavFlight/inav/issues/1443) is solved by using the font you uploaded.

**Comment by raul-ortega** [comment]
I re-open this issue because I have detected that the icon is full once the battery level is lower than the minimum voltage (lower than 9.9 volts for 3 cell battery, for example).

I suspect (not sure) that the problem comes from function calculateBatteryPercentage, which would be returning 100 for vbat levels lower than the minimum.

**Comment by raul-ortega** [comment]
[https://youtu.be/8ufZkhPB6o4?t=747](https://youtu.be/8ufZkhPB6o4?t=747)

**Comment by digitalentity** [comment]
Firmware has no option to configure battery cell size - cell count is calculated automatically by dividing measured voltage by `vbat_min_cell_voltage` (default 3.3V). Therefore voltages lower than 9.9 are miscalculated to be a fully charged 2S battery.

Solution - set `vbat_min_cell_voltage` and `vbat_max_cell_voltage` according to your battery chemistry and min/max voltages.

**Comment by DzikuVx** [comment]
Tested INAV 1.7.2 and it works fine. Closing
