### ISSUE TITLE
Can't arm by switch. But can arm with stick combination.

### ISSUE THREAD

**Issue by DscoveryHD** [iNavFlight/inav#1447]
Can't arm by switch. But can arm with stick combination. No GPS installed.
Model: flying wing.

[dump_1.6.1_23.03.17.txt](https://github.com/iNavFlight/inav/files/863007/dump_1.6.1_23.03.17.txt)

**Comment by oleost** [comment]
Screenshot of your modes tab with armed turned switch turned on and off please.

**Comment by DscoveryHD** [comment]
![2017-03-23 22 58 02](https://cloud.githubusercontent.com/assets/26610753/24268017/4f6856b8-101d-11e7-9220-37bb564489f3.png)
![2017-03-23 22 58 15](https://cloud.githubusercontent.com/assets/26610753/24268018/4f862e9a-101d-11e7-88d0-8ec04ca1414c.png)
![2017-03-23 22 58 52](https://cloud.githubusercontent.com/assets/26610753/24268019/4f91412c-101d-11e7-8055-4b9803b1dcfd.png)

**Comment by oleost** [comment]
Hmm, no idea why that happening for you, guess have to wait for someone else.

Just to be sure, you end points are showing 1000 in throtte and 1500us the rest right?

**Comment by DscoveryHD** [comment]
While arming by switch:
Throttle 1000 +-5
Yaw 1500 +-5 
Roll 1500 +-5
Pitch 1500 +-5
AUX3 2000 +-5
![2017-03-24 00 10 57](https://cloud.githubusercontent.com/assets/26610753/24270481/6acd97e8-1026-11e7-8784-09e809422308.png)

**Comment by digitalentity** [comment]
I'll try reproducing this from my end.

**Comment by digitalentity** [comment]
I can't reproduce the issue.

**Comment by digitalentity** [comment]
Can't reproduce.

**Comment by DscoveryHD** [comment]
т.е. во всем виноваты мои руки? искать где накосячил, так?

**Comment by digitalentity** [comment]
Более подробное описание что и как подключено может помочь. У нас уже был баг, который проявлялся только на конкретном оборудовании.
