### ISSUE TITLE
Channels Fallback Settings does not show in UI on OmnibusF4Pro and IBUS 

### ISSUE THREAD

**Issue by alfag4** [iNavFlight/inav#1448]
I'm not able to set fallback channel because the options are not showed in the configurator
INAV 1.6.1
Configurator 1.6.2
OmnibusProF4 v3
IBUS and FluSky FS-X6B receiver

**Comment by giacomo892** [comment]
You should better read the release notes.
Failsafe has changed. No more stage 1
