### ISSUE TITLE
OMNIBUS F4PRO v2 Softserial

### ISSUE THREAD

**Issue by urlu75** [iNavFlight/inav#1449]
I was not able to get the softserial working on with Inav.
resources are correctly enable :
C08: SOFTSERIAL1 UART RX
C09: SOFTSERIAL1 UART TX

C8 and C9 are the small pad (as shown on [figure 5](https://www.rcgroups.com/forums/thumbgallery.php?do=threadgallery&t=2791327)).

When checking for a signal with an oscillo I have flat 3v on PC8 pad and gnd on PC9 pad.
Telemetry inversion is on (X4R receiver), I tried different baud rate.
I tried with BF and resource mapping, softserial works well on ch5 & 6 so board is ok.
I have no idea on how I can make more test to find if it's an issue with the FW or on me...

Any idea ?
thanks

**Comment by Riffer** [comment]
How did you solve this issue?
