### ISSUE TITLE
GPS Coordinates not displaying using SmartPort Telemetry in OpenTX - SPRacingF3EVO

### ISSUE THREAD

**Issue by MRC3742** [iNavFlight/inav#1455]
After hours of trying different combinations of OpenTX firmware versions and iNav versions I am unable to show or log GPS Coordinates via SmartPort telemetry for my location using a Taranis X9D+. All other GPS related telemetry appears to be OK. It will not show GPS Copordinates in all stable versions of CleanFlight, iNav and BetaFlight up to and including v3.0.1. HOWEVER IT WORKS PROPERLY using BetaFlight on any firmware versions higher than 3.1.0.

Firmware versions listed in descriptions below

The screenshots shown below are using OpenTX v2.1.9 and iNav 1.6.1 and Although nothing appears on the telemetry screen (Pics 1 and 2) on the edit screen the longitude value shows correctly (Pic 3 upper row)
![screen-2017-03-23-195008](https://cloud.githubusercontent.com/assets/26642502/24306854/6f826788-1098-11e7-9a63-2e55611c9eb1.jpg)          ![screen-2017-03-24-125346](https://cloud.githubusercontent.com/assets/26642502/24306928/afa30ed0-1098-11e7-9712-05a37b9422c1.jpg)           ![screen-2017-03-24-125403](https://cloud.githubusercontent.com/assets/26642502/24307076/2907bd34-1099-11e7-9c33-75064b043f73.jpg)

Using BetaFlight with firmware versions 3.1.0 and newer, the following appears correctly on telemetry screen.
![screen-2017-03-23-194822](https://cloud.githubusercontent.com/assets/26642502/24307572/1c0738ce-109b-11e7-8bbe-53ea60ac334f.jpg)

Updating OpenTX to version 2.2 RC14 (N366) does change the display somewhat showing the latitude as all 0's and the longitude now shows on the telemetry screens but in the second location. (As it was shown
 in the first location slot on OpenTX v2.1.9)
![screen-2017-03-23-193702](https://cloud.githubusercontent.com/assets/26642502/24307932/662b926e-109c-11e7-9482-cefb90340f99.jpg)         ![screen-2017-03-24-124123](https://cloud.githubusercontent.com/assets/26642502/24308045/dc513868-109c-11e7-9278-d14771dc8ba8.jpg)          ![screen-2017-03-24-130118](https://cloud.githubusercontent.com/assets/26642502/24308101/16a4d682-109d-11e7-95dd-9872be78af44.jpg)

Again using BetaFlight firmware versions 3.1.0 and newer, with OpenTX V2.2 RC14 the following appears correctly on telemetry screen. (the Lat/Lon are on opposite rows from earlier OpenTX v2.1.9 with latitude now appearing on the top row)
![screen-2017-03-23-193352](https://cloud.githubusercontent.com/assets/26642502/24307803/f7f7d3de-109b-11e7-9a5b-a58973673eae.jpg)

Hardware I am using: 
Taranis X9D+ with OpenTX 
SPRacing F3 EVO (Not a Clone) 
Ublox M8N GPS (Clone) on Uart3 with external HMC5883 Compass on I2C1
FrSky XR4-SB using PPM and SmartPort Telemetry on Uart2
I have also moved GPS and Smartport to different Uarts including SoftSerial with same results

Also GPS Coordinates DO SHOW PROPERLY in iNav configurator in the setup and GPS screens.

I have searched the forums and it was reported to be working form their home location but changing to a different area seems to make it stop working?

**Comment by MRC3742** [comment]
Haven't been able to get GPS Latitude Coordinates to display on Taranis LCD. Also logging csv file GPS column is blank using smartport telemetry on X4R-SB.

It will work if I change RX to D8R-XP and iNav setup from Smartport to Frsky using hub telemetry on iNav 1.6.1.

I am able to compile my own hex and have been working in smartport.c but have not been able to get latitude to display. I believe gpsSol.llh.lat is not available here? Switching gpsSol.llh.lat with gpsSol.llh.lon in smartport.c causes the longitude coordinate to be displayed as latitude (My negative value is displayed as South instead of North as expected) but the longitude on the display (which is now set as gpsSol.llh.lat) is now displayed as 0's

As I have very limited knowledge to programming code, am I on the right track and working in the right file?

**Comment by DzikuVx** [comment]
I can confirm GPS coordinates working with X4R receiver and OpenTX 2.2 on Taranis and INAV 1.7.
Closing this one
