### ISSUE TITLE
"feature motor_stop" vs "RTH"

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#1458]
If feature "motor_stop" is enabled, it is possible to shut down motor when in RTH mode with throttle stick to zero.

**Comment by Linjieqiang** [comment]
No.It will be dangerous.But in DJI product drone,you just only put yaw and pitch channel at 1000 , throttle and roll channel at 1000 ,the motor will shut down.

**Comment by Schalonsus** [comment]
Yes it is a bug, thats why i report it!

**Comment by digitalentity** [comment]
This is indeed dangerous, but to be honest I'm against overriging MOTOR_STOP by anything but failsafe.

MOTOR_STOP is intended to be a safety feature giving pilot the ability to quickly shutdown motors in case of the emergency.

**Comment by oleost** [comment]
Yeah, I noticed this earlier on my airplane. But figured it was by design as motor_stop is intedend to stop motors at 0% throttle.

**Comment by Schalonsus** [comment]
In passthrough yes, but in Angle/RTH/PosHold/AltHold/WP? 
I consider this more unsafe... But maybe we should just state this somewhere in the wiki so that people are aware if this "function"

**Comment by oleost** [comment]
In angle mode its obvious its going to stop the motor.

But think for people that are not using a switch to arm. Those maybe choose motor_stop to have an easy way to cut throttle.

**Comment by WaspFPV** [comment]
Looks like this is intentional behaviour. Motor_stop sort of works like a kill switch. When using motor_stop, consider setting up an idle up switch on your transmitter so you don't kill the motors by accident. 
Or when switch arming, use a 3 position switch for arm + idle up. Idle up doesn't use extra aux channels, just an extra switch position on your radio. If you use switch arming, it can work on a 3 position switch combined with arming.

**Comment by Dronek** [comment]
Actually I never considered motor_stop as a safety feature.
From my understanding currently only motor_stop allows for gliding with a folded prop AND full PI stabilization.
(Switch-)disarming is no option to glide or land a plane/wing due to obvious reasons.

I support the idea of overriding motor_stop by failsafe, at least for fixed-wing.

**Comment by digitalentity** [comment]
Failsafe always ignores motor_stop. If we are in failsafe and system requires motor to spin - it will spin.

**Comment by WaspFPV** [comment]
@Dronek Sure I agree, but for fixed wing vs multirotor, motor_stop has a different use. You could consider it a safety feature on multirotors if you don't have an arm switch but want to stop the motors asap. Stick disarming without motor_stop still takes a few seconds at idle.

**Comment by Dronek** [comment]
> You could consider it a safety feature on multirotors if you don't have an arm switch but want to stop the motors asap. Stick disarming without motor_stop still takes a few seconds at idle.

That's true. It seems that motor_stop has quite different applications and implications when it comes to multirotors vs. fixed-wings.

@all : would it make more sense to not use motor_stop on fixed wing and just set min-throttle to 1000?
This would prevent from "accidentally" cutting throttle in nav modes while still allowing to cut throttle in modes like angle, acro, pass-through etc. for gliding purposes.

**Comment by Redshifft** [comment]
@Dronek  The system works, there has not been a need to tell people not to turn off their transmitters while flying, so after a couple of long walks they will figure this one out also :D

**Comment by hali9** [comment]
I use always this feature and I agree with @digitalentity:
> MOTOR_STOP is intended to be a safety feature giving pilot the ability to quickly shutdown motors in case of the emergency.

MOTOR_STOP should always stop all motors if pilot have control. One and only one exception should be failsafe when pilot do not have a control.
It is sometimes the last resort to do no harm to anyone.

**Comment by giacomo892** [comment]
is this still actual or has being solved?
EDIT.

It should be solved by https://github.com/iNavFlight/inav/commit/0778619547fd33b62a2119b0433dcc1b2a517c0b

We should close this.

**Comment by fiam** [comment]
@giacomo892 Thanks for noticing it. Fixed in https://github.com/iNavFlight/inav/commit/0778619547fd33b62a2119b0433dcc1b2a517c0b
