### ISSUE TITLE
Possible failsafe bug

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1459]
Reported on RCG: https://www.rcgroups.com/forums/showpost.php?p=37182329&postcount=12611

Possible bug with failsafe locking user out completely unless in passthrough mode (fixed-wing).

**Comment by oleost** [comment]
@digitalentity https://www.rcgroups.com/forums/showpost.php?p=37185149&postcount=12636

**Comment by oleost** [comment]
![image](https://cloud.githubusercontent.com/assets/5670710/24334582/e5ec000c-126c-11e7-8990-65faadb65b0e.png)

https://github.com/iNavFlight/inav/blob/master/docs/Failsafe.md
![image](https://cloud.githubusercontent.com/assets/5670710/24334590/038ff780-126d-11e7-821c-5c24bce6f856.png)

**Comment by digitalentity** [comment]
Pilot lockout is possible when failsafe disarms the machine - it then locks pilot out of control for 30 seconds (including PASSTHROUGH mode). Fix pending https://github.com/iNavFlight/inav/pull/1465
