### ISSUE TITLE
Documentation update (Ubuntu builds) request

### ISSUE THREAD

**Issue by Maxzor** [iNavFlight/inav#1462]
Hello

See this thread :
https://www.fc-forums.com/viewtopic.php?f=12&p=12#p12
building on Ubuntu might need some update, I couldn't get Terry's toolchain.

**Comment by stronnag** [comment]
Building on Ubuntu (latest) should just work as it's a fairly recent arm-gcc (6.21). PRs to fix broken documentation are always welcome.
