### ISSUE TITLE
motorCount from mixer does not match pwm driver.

### ISSUE THREAD

**Issue by marbalon** [iNavFlight/inav#1470]
I have a board with definition for airplane with one motor only (in target.c). So if PWM driver initialise PWM's it initialise only one motor. But when mixer code try to call some functions eg. pwmShutdownPulsesForAllMotors(motorCount); it uses local variable motorCount = 2 for fixedwings, so it is out of motor pointer table from PWM driver and board hangs if call this function - hopefully on restart only ;-)
I fixed this problem locally in mixer.c 

        //motorCount = mixers[currentMixerMode].motorCount;
        motorCount = pwmGetOutputConfiguration()->motorCount;

But maybe this should be in the other place.

**Comment by digitalentity** [comment]
Good catch!

**Comment by digitalentity** [comment]
Fixed, thanks
