### ISSUE TITLE
Attitude is crazy unstable in blackbox INAV/OMNIBUS 1.6.3 (87fb5ee1)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1488]
In both live and recorded LTM, attitude looks normal. The craft flies very well. Blackbox attitude looks broken. 1.6.3 (87fb5ee1)

https://vimeo.com/210813419
http://seyrsnys.myzen.co.uk/bad-attitude/LOG00001.TXT

**Comment by digitalentity** [comment]
Thanks, fixed
