### ISSUE TITLE
Optical Flow Support?

### ISSUE THREAD

**Issue by johnsilvester** [iNavFlight/inav#1505]
Any chance we could see optical flow support via an adns3080 or a px4 anytime soon for use with position hold?

**Comment by Linjieqiang** [comment]
Maybe inav will support it in Version 2.0.

**Comment by Pairan** [comment]
Still hoping and waiting for @digitalentity 's code to be reaseled which uses : 
"**Cheerson CX-OF CXOF Optical Flow Module**"

**Comment by Pairan** [comment]
any news on this?

**Comment by digitalentity** [comment]
2.0 branch has some perliminary support for opticla flow sensor (combined with GPS or solo).
