### ISSUE TITLE
OSD Speed always displayed in km/h

### ISSUE THREAD

**Issue by flounderscore** [iNavFlight/inav#1513]
The speed is always displayed as km/h even when set to imperial units.

**Comment by oleost** [comment]
Board, which type of osd are you using?

**Comment by flounderscore** [comment]
I'm using a OminbusF4SD. It's just not implemented in osd.c yet (only for
the altitude). If it's still an open issue later, I'll give it a shot.
Should be a 5 minute fix.

**Comment by StewLG** [comment]
Flounderscore is right, this happens on Omnibus F3 as well.

**Comment by flounderscore** [comment]
#1546
