### ISSUE TITLE
Magnetometer: Not necessary an issue just a question

### ISSUE THREAD

**Issue by tonyintn** [iNavFlight/inav#1516]
I noticed that the Mag was missing from the flight modes, does this mean that it is always on by default? I have checked the wiki doc but do not see any info on this matter.  
I also noticed another mode "Kill Switch".

Thanks in advance.

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav/wiki/Flight-modes

Mag mode is now called Heading Hold and can be used without compass.
Killswitch disarms regardless of way of arming without any additional contidions
