### ISSUE TITLE
Feature request...osd alarm disable

### ISSUE THREAD

**Issue by Hwurzburg** [iNavFlight/inav#1536]
It would be nice to disable the osd alarms for alt and timer by setting them to 0 as in MWOSD. I routinuely fly above 200 feet and the flashing display is very annoying...

**Comment by fiam** [comment]
@Hwurzburg Altitude alarm is already ignored when it's set to zero. I've just submitted #2789, which disables the time alarm when it's set to zero.

**Comment by digitalentity** [comment]
#2789 merged. Closing
