### ISSUE TITLE
Feature request: save and accumulate statistics (semi-)permanently on FC

### ISSUE THREAD

**Issue by Dronek** [iNavFlight/inav#1549]
In mwosd it is quite common to display flight statistics like traveled distance, max. distance from home, max. height, top speed, flight time etc. at the end of a flight. The data is usually lost when we disconnect the battery.

It might be quite interesting to have such data being saved **and added up** locally on the FC itself in order to keep track of absolute traveled distance, absolute flight time, absolute number of flights and optionally some absolute max. values. 

These values could be a subset of CLI parameters that are updated in defined time intervals while the aircraft is armed or at least on each disarm. It would allow the user to save and restore the data prior and after FC firmware updates, respectively.

Example CLI parameters:
stat_flight_time_last = 25.2 (minutes)
stat_flight_time_total = 7.88 (hours)
stat_flight_distance_last = 17234 (meters)
stat_flight_distance_total = 323.2 (km)
...

**Comment by maybeyes** [comment]
it would be just great! We need this feature )

**Comment by krzysztofmatula** [comment]
I like this idea.
It seems to be enough to update flash on each disarm only.

**Comment by Dronek** [comment]
Functionality available in current release. Therefore closing.... which doesn't work.
Feel free to close.
