### ISSUE TITLE
Jeti EX Bus telemetry broken

### ISSUE THREAD

**Issue by Tony4aro** [iNavFlight/inav#1556]
I have 2 quads with identical hardware (other than GPS for iNav)... one set up with iNav, and one with Beta flight.  (Jeti R5 receiver, SPF3)   On the iNav Quad, I don't get any telemetry back on the EX Bus... but I do have control of the quad.   Even thing works as it should with the BetaFlight quad.   I'm mostly just looking for the flight battery back.   

Since they are set up the same... I'm assuming that the EX Bus telemetry is broken on the iNav build.

**Comment by Dutch-Drone-Dude** [comment]
I think it isn't only with the EX Bus telemetry, i don't also get any telemetry with my Dodo and X4R-SB.
