### ISSUE TITLE
BF OSD: no way to calibrate RSSI

### ISSUE THREAD

**Issue by ABLomas** [iNavFlight/inav#1559]
On MW-OSD we had RSSI calbration menu (analog or digital). Now with integrated RSSI there's no such menu. Also, i do not see any CLI options for that.
So, if RSSI is not perfectly mapped to digital 1000....2000 is not going to be displayed nicely. Can we have calibration menu back, or at least get opton to set min/max on CLI?

**Comment by digitalentity** [comment]
Closed via 2076. Please test and report if it doesn't work for you
