### ISSUE TITLE
Send 1 second worth of telemetry on shared MSP/telemetry port after disarming

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1562]
Per @stronnag's suggestion:

>In theory, this is a really nice feature, not only from a diagnostic point of view, but also because it could potentially simply the CGS MSP -> LTM -> MSP switch by providing a reliable status value, rather than having to depend on a timeout.

**Comment by stronnag** [comment]
On further consideration, just sending X, S, X, S on shutdown would work too, and possibly be easier than a timer.

**Comment by digitalentity** [comment]
We can have other telemetries shared with MSP. Timer is easier and more suitable for different kinds of telemetry.

**Comment by sppnk** [comment]
Please, take a look at #1356 if you consider it is related to this.
