### ISSUE TITLE
Request to add distance from home to OSD

### ISSUE THREAD

**Issue by TwoToneEddy** [iNavFlight/inav#1563]
I think this would be a really great addition and probably fairly trivial to implement. Any chance of adding it? Direction to home would also be great.

**Comment by ABLomas** [comment]
This is already available, just configure (turn on/off required elements).
Proof - random flight video, see both elements in top-right corner: https://www.youtube.com/watch?v=JVu4Zl1ciFs

**Comment by TwoToneEddy** [comment]
But there is no indication that this is inav or betaflight osd. This could be a minim osd. I've just checked and there are no available elements that give this functionality. I'd be keen to know the exact elements you refer to. Thanks

**Comment by ABLomas** [comment]
I really don't get your issue. Did you tried, at least, to turn on "Direction to home" or "Distance to home" elements?
![clipboard01](https://cloud.githubusercontent.com/assets/8989151/25125544/e4353828-2437-11e7-8bad-c1c47bc13fc1.jpg)

**Comment by PaulHam211** [comment]
@TwoToneEddy Perhaps you were on an older version of the configurator? I tried on 1.6.1 and the new OSD options were not there. I downloaded 1.7.0 and they all show now.

Q for devs - Direction to home is a number currently, could this possibly be an arrow, pointing to the home pos?

**Comment by digitalentity** [comment]
@PaulHam211 did you upload the font?

**Comment by PaulHam211** [comment]
@digitalentity nope. ill give it a go. cheers

**Comment by TwoToneEddy** [comment]
Sorry, my original issue was i was using an out of date version of the firmware. Those additional elements are there now. Sorry for the stupid mistake.

**Comment by digitalentity** [comment]
@TwoToneEddy happens :smile:

**Comment by TwoToneEddy** [comment]
Do I need to close this issue now?
