### ISSUE TITLE
Target Request: SP Racing F3 Neo

### ISSUE THREAD

**Issue by gfacek** [iNavFlight/inav#1567]
Is it possible to migrate the SPRF3 Neo from Cleanflight or Betaflight to iNav?

**Comment by oleost** [comment]
@gfacek If you bought it from Seriously Pro, maybe ask @hydra ?
Would guess it would be in his interest to have his boards working on INAV.

**Comment by hydra** [comment]
Should be easy enough for someone to pull the commits or code from Cleanflight master.  If whoever does this has questions just ask.

**Comment by digitalentity** [comment]
@hydra pulling over commits should indeed be fairly trivial. I might do it if I have some time to spare on this one.

**Comment by gfacek** [comment]
This would be nice :)
I would be doing it by myself, if I knew what I have to do. But I'm afraid, I could delete the whole project...maybe the whole internet. ;)

**Comment by gfacek** [comment]
Any news here?

**Comment by martinbudden** [comment]
Yes, we should do this. It's just a question of having some spare time...

**Comment by martinbudden** [comment]
@hydra , I've made a first cut at PR https://github.com/iNavFlight/inav/pull/1695 , can you review please? (`target.c` file needs careful checking.)

**Comment by gfacek** [comment]
Nice! Thank you so long. Hopefully I can finally bring my copter in the air soon. :)

**Comment by DzikuVx** [comment]
SPRF3NEO has been added some time ago, so I'm closing
