### ISSUE TITLE
Switch RTH to airplane mode in case of compass failure

### ISSUE THREAD

**Issue by brat002** [iNavFlight/inav#1573]
What do you think about next feature: in case of compass failure due RTH for multirotors instead of landing in unknown conditions switch flight mode to "airplane mode?. This mean - multirotor fly only forward and heading calculated only by GPS. After reach home location multirotor should initiate landing as usual behaviour for RTH.

**Comment by rb1205** [comment]
Is a sudden compass failure a likely scenario? I sometime have the issue where it's not detected after a FC reboot, but aside for that it never failed mid flight on me.

**Comment by brat002** [comment]
I think this method of RTH is much safe for all autonomous flights. No matters what is the reason of this flight.

**Comment by rb1205** [comment]
It changes a simple and prevedible straight line flight into a potentially long turn, increasing the space and time it takes to return and lowering the pilot control. Also what are you going to do when the multicopter reaches the home position? Normal multicopter automated landing is done in GPS hold which can't be done without compass, so it'd be either "eternal" loitering or an emergency landing.

**Comment by digitalentity** [comment]
Quad can't do a coordinated turn without knowing what direction it is facing. During a turn it will drift sideways which may lead to a situation where it is already facing new direction of flight but still flies in old direction (sideways). Therefore I think that switching to "hybrid" RTH mode is in fact less safe than landing where it is. Also, it's always safer to make sure compass if functioning properly.
