### ISSUE TITLE
All Servo Outputs Limited to 1000uS / 2000uS

### ISSUE THREAD

**Issue by taileron** [iNavFlight/inav#1575]
For all kind of tilt/vectored thrust issues servo outs up to 2500uS / 500uS are needed as the gui´s servo tab offers, but the real servo outputs are limited to 1ms/2ms (custom, Custom Plane and Custom Tri) (iNav 1.5/1.6 Gui 1.6/1.7)   cli example: servo 0 500 2500 1500 90 90 100 -1

**Comment by DzikuVx** [comment]
@taileron I think this has been solved with mixer rework in latest release. Please check, I'm closing this for now. If it still does not work and clips at 1000/2000 please reopen
