### ISSUE TITLE
INAV 1.7.0-RC1: Built in OSD failures

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#1577]
- Startup message doesn't appear (INAV version, and how to enter to osd are missing).

- ARMED message doesn't appear when arming (from switch).

- Statistics doesn't appear when disarming (from switch).

- Can't enter in osd menu with THR MID + YAW LEFT + PITH UP

**Comment by digitalentity** [comment]
@raul-ortega what board and what target do you use?

**Comment by raul-ortega** [comment]
Betaflight F3 AIO v1.1 target OMNIBUS.

With 1.6.1 everything about OSD works well.

**Comment by digitalentity** [comment]
Interesting. I'm current traveling and can't verify and debug. @DzikuVx do you still have Omnibus F3 board? Can you confirm the issue?

**Comment by raul-ortega** [comment]
Yes, this is my actual board (the Banggood clon), I fly my s800 sky shadow
with it. I confirm the issue.

**Comment by DzikuVx** [comment]
I should have one somewhere. Mini, not regular version, but the same target

**Comment by Soph** [comment]
I can confirm I have the same issues. Omnibus F4 PRO. Works on 1.6.1, with 1.7 RC1 it doesn't (and also if you compile from development)

**Comment by Soph** [comment]
I looked a bit at the code and the commits since 1.6.1. If I checkout 1.7.0-RC1 and revert this commit

https://github.com/iNavFlight/inav/pull/1506/commits/0f2138ca4781e0a3d3bd24a821f0c315cbec2f8a

The stick commands make the menu appear again. But then it's not responding to any input.

**Comment by DzikuVx** [comment]
@raul-ortega @Soph could you please share CLI dump in which OSD is not working like expected?

**Comment by Soph** [comment]
@DzikuVx here is the dump for my setup. Flashed to "stock" 1.7.0 RC1 before doing the dump. https://gist.github.com/Soph/520ee8617bf8b72fded57c4126a79f0c

**Comment by DzikuVx** [comment]
@Soph OK, I will try to flash my omnibusf4Pro today

**Comment by Soph** [comment]
@DzikuVx for the Omnibusf4pro: To debug on the device, does this still apply: https://github.com/iNavFlight/inav/blob/master/docs/development/Hardware%20Debugging.md

Or is there an easier way to debug straight trough the USB connection?

**Comment by DzikuVx** [comment]
@Soph I think this is the only way to debug.

@marbalon can we have your assistance on the topic of CMS not working like expected? You seems to know what is happening down there

**Comment by raul-ortega** [comment]
Here you are my dump and diff configuration files.

[inav_1.6.1_S800_SkyShadow-diff-LAUNCH-ARM-AUTOTUNE-SWITCHES.txt](https://github.com/iNavFlight/inav/files/959502/inav_1.6.1_S800_SkyShadow-diff-LAUNCH-ARM-AUTOTUNE-SWITCHES.txt)
[inav_1.6.1_S800_SkyShadow-dump-LAUNCH-ARM-AUTOTUNE-SWITCHES.txt](https://github.com/iNavFlight/inav/files/959501/inav_1.6.1_S800_SkyShadow-dump-LAUNCH-ARM-AUTOTUNE-SWITCHES.txt)

**Comment by Soph** [comment]
Since we both use the FLYING_WING mixer (and a SkyShadow ;) ) I just tried if it's related to that because it's not using YAW at all. But switching to a quad preset didn't change anything.

**Comment by raul-ortega** [comment]
Erased, I did a bad translation!

**Comment by digitalentity** [comment]
Fixied. @raul-ortega thanks for reporting the problem.

**Comment by raul-ortega** [comment]
Tested, startu up message is shown, and you can enter to the MENU, but  **it is not possible to enter in the menu options,  neither SAVE or EXIT**.

**Comment by digitalentity** [comment]
@raul-ortega I've verified that menu works fine before closing this. Tested on Omnibus F4 Pro. Can you please check again and describe exact steps to reproduce the issue.

**Comment by raul-ortega** [comment]
Ok, tested again and it works. Some minutes before I was testing it on a multicopter with NAZE and external OSD, and I applied YAW LEFT instead of PIT LEFT.

It was a confusion, I apologyze (too many owers testing, with different systems).

**Comment by digitalentity** [comment]
@raul-ortega no worries, it's good to double check as I might have missed something :smile:
