### ISSUE TITLE
ANYFCF7 : CPU load 

### ISSUE THREAD

**Issue by urlu75** [iNavFlight/inav#1579]
with default firmware 1.7-RC1.
Racer 5" racer configuration applied and then just change gyro, acc attitude and loop time to maximum. CPU load is >400%. Can be more than 600% if some features are enabled.

```
# status
System Uptime: 166 seconds
Voltage: 0 * 0.1V (3S battery - OK)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=NONE, SONAR=NONE, GPS=NONE
SD card: None inserted
Stack size: 2048, Stack address: 0x20010000
I2C Errors: 1, config size: 3271, max available config: 262144
System load: 425, cycle time: 141, PID rate: 7092, RX rate: 24, System rate: 9
```

I2G mag issue still there with 1.7.

**Comment by stronnag** [comment]
Not sure what problem you're reporting here. 

If you enable features beyond that which the CPU can support, it does not work. So what do you expect?

**Comment by urlu75** [comment]
So you are saying that it is normal that on on an F7 board, CPU is load is > 400% just with 
- gyro LPF cutoff 256Hz
- sync mode : all
- gyro task : 8kHz
- acc task : 1kHz
- attitude : 1kHz
- FC loop time : 8kHz

Same configuration on an F4 board, CPU load is only 35%

**Comment by sambas** [comment]
All the performance updates from BetaFlight has not yet landed here

**Comment by digitalentity** [comment]
@sambas what's the status of this? Fixed or should we postpone to 1.8?

**Comment by sambas** [comment]
postpone, not sure why pid controller isn't happy when using 8/8

**Comment by digitalentity** [comment]
Aye!

**Comment by digitalentity** [comment]
@sambas any news regarding this?

**Comment by DzikuVx** [comment]
I just tested AnyFCF7 with 8/8kHz, acc at 1kHz and attitude and 500Hz. Load at 37%, I suppose we can assume problem solved. Thank everyone
