### ISSUE TITLE
Softserial not working if "Custom Airplane" Mixer is selected

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#158]
If i select "Airplane" Mixer Bluetooth works over Softserial.
If i select "Custom Airplane" Mixer it is not working anymore.

**Comment by digitalentity** [comment]
@Schalonsus 
What target?

**Comment by digitalentity** [comment]
@Schalonsus, I was unable to reproduce the issue on NAZE board. Softserial works with both Airplane and Custom airplane mixers.

**Comment by Schalonsus** [comment]
Ok then it is maybe really a EzGUI issue. I rewrote mixer.c so that it meets my stick input and am able to connect to EzGUI with normal Airplane Mixer now.
