### ISSUE TITLE
Naze32 Rev5 won't take "board and Sensor"

### ISSUE THREAD

**Issue by rholt51** [iNavFlight/inav#159]
Not sure if this is where I should post this - but i have a Naze32 Rev5 and when i go to put 90 in on the yaw offset in CF, and save, while it takes the "90" (even in CLi), the yaw correction does not take effect. i've  checked this a few times, and finally flashed back to the regular version of CF, and tried the Yaw 90deg correction and it worked. went back to the iNav version, and i go NO changes again.
![board sensor align 90deg setting](https://cloud.githubusercontent.com/assets/8038898/14426735/d20616de-ffbe-11e5-986f-e16f3ad26741.png)
![cli showing 90deg setting](https://cloud.githubusercontent.com/assets/8038898/14426738/d4bb6172-ffbe-11e5-9d31-c510b8416449.jpg)
![quad tilted left side down](https://cloud.githubusercontent.com/assets/8038898/14426740/d78b2400-ffbe-11e5-8f8c-358e28874fda.jpg)

**Comment by digitalentity** [comment]
Please describe the issue. It's unclear what you mean by "won't take board and sensor".

**Comment by rholt51** [comment]
Sorry about that first submission. My cat hit the enter key before I had finished. It should be updated now.

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/wiki/Advanced-accelerometer-calibration

You have to degress x 10 and do it in CLI.

Also read rest of wjki while your at it ;)

This can be closed

**Comment by DzikuVx** [comment]
@rholt51 iNav works with centidegrees and Configurator is not supporting this feature. To enter correct alignment you have to use CLI:
`set align_board_yaw=900`
`save`

**Comment by digitalentity** [comment]
@oleost, @DzikuVx you are fast :+1:

**Comment by rholt51** [comment]
Solved. Working now!
