### ISSUE TITLE
Development version: "Navigation is safe" without GPS fix.

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#1613]
I apologyze if this is not the right place, but I'm not sure if this is a ina-configurator issue or a fimware issue.

The GPS has **no FIX** and **nav_extra_arming_safety** set to **ON** the pre-arming checks are all green, and I **can arm** (see picture).

![navigation-is-safe](https://cloud.githubusercontent.com/assets/12935392/25554049/3004e5f2-2cc4-11e7-9c3d-3d94e7bcd6d7.png)

My TARGET is OMNIBUS (ombnibus f3 aio v1.1 Banggood).

[inav_1.7.0-RC1_S800_SkyShadow-dump-LAUNCH-ARM-AIR-SWITCHES.txt](https://github.com/iNavFlight/inav/files/965995/inav_1.7.0-RC1_S800_SkyShadow-dump-LAUNCH-ARM-AIR-SWITCHES.txt)

**Comment by giacomo892** [comment]
Are you sure you have enabled GPS in the configuration tab?

**Comment by raul-ortega** [comment]
Yes, of course. Have you taken a look to the dump file and the pre-arming chek picture?

**Comment by raul-ortega** [comment]
I have tested it just now with 1.6.1 and it works as it should. Therefore, I guess it is a firmware problem (development version).

**Comment by digitalentity** [comment]
You don't have any navigation GPS-aware modes enabled. There is no chance that GPS will be required so firmware is not enforcing the GPS fix.

**Comment by raul-ortega** [comment]
I don't understand!
Thas this mean that when nav_extra_arming_safety is on and I don't have the home position set, I should be able to arm?
Should I activate the PS mode (I have it configured RTH and PH in aux channels)?

**Comment by digitalentity** [comment]
You don't have PosHold or RTH modes configured in your dump. Please check that your modes tab is set up correctly.

**Comment by digitalentity** [comment]
Extra arming safety enforces GPS fix only if there is a possibility that GPS would be required - if PosHold, Waypoint, RTH of Failsafe-RTH is configured.

**Comment by raul-ortega** [comment]
Ups!!!! You are right, my dump seems to have errors (missing modes) when I change from version 1.7-RC1 to the the development. I really don't know what's happening, if I am doing something wrong...Does the development version override the configuration of the 1.7.0-RC1?

**Comment by digitalentity** [comment]
Actually no, `aux` should be compatible between 1.6, 1.7 and development.
