### ISSUE TITLE
Testing 1.7.0 RCs

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1617]
A little belated, but a place for reports of successful (or otherwise) tests of 1.7.0 Release Candidates

**Comment by stronnag** [comment]
**Commit**: b69f0a23
**Board**: SPEVO
**Aircraft**: 600mm tricopter
**Results**:
Successful. Free flight, PH, WP, RTH. LTM not affected by recent changes.

**Comment by stronnag** [comment]
**Commit**: 8c39f12a (+ de_msp_denial_of_service_fix + #1600)
**Board**: OMNIBUS F3 AIO
**Aircraft**: 420mm quad
**Results**:
Successful. Free flight, PH, WP, RTH. No observed difference (+ve or -ve) for #1600.

**Comment by stronnag** [comment]
**Commit**: 10b9250e
**Board**: SPRF3 Acro + I2C baro / mag
**Aircraft**: 250mm quad / deadcat
**Results**:
Successful. Free flight, PH, WP, RTH. 

**Commit**: 10b9250e
**Board**: RMRC Dodo (SPRF3 firmware)
**Aircraft**: 280mm tricopter (no navigation sensors)
**Results**:
Successful. Free flight.

**Comment by ahfynjj** [comment]
Commit: 
Board: OMNIBUS F4 Pro(V2)+ DJI GPS MAG
Aircraft: FX-61 flywing
Results:
Successful. ANGLE  HORIZON  NAV RTH

**Comment by digitalentity** [comment]
I think we're ready for the final release. Other bugs would be fixed in 1.7.1 if necessary.

**Comment by giacomo892** [comment]
Commit: INAV 1.7.1 RC1 + MSP FLOOD FIX
Board: NAZE
Aircraft: Custom Quad
Results: All working. ANGLE HORIZON AIRMODE ALTHOLD and LTM telemetry

**Comment by isilcala** [comment]
Board: X-RACER v2.1 with SPRACEING F3 firmware + Beitian BN-200 GPS
Aircraft: FliteTest Tiny Trainer
Results: Successful. ANGLE AIRMODE STAB PASSTHRU RTH

**Comment by digitalentity** [comment]
Thanks everybody!

**Comment by krzysztofmatula** [comment]
Just for reference - tested:

1. SPRACINGF3, 250mm quad, 6" - HORIZON, BARO, PH, RTH, FS, LTM - all ok.
2. SPRACINGF3EVO, 550mm quad, 10" - ANGLE, BARO, PH, RTH, LTM, CHANNEL_FORWARDING - all ok.
