### ISSUE TITLE
Feature request: Addition of GTUNE

### ISSUE THREAD

**Issue by TwoToneEddy** [iNavFlight/inav#1618]
Is this possible to add without too much work? Would it be a case of copying it from cleanflight?

**Comment by stronnag** [comment]
afaik, it is no longer if CF; it never really worked.

**Comment by digitalentity** [comment]
If I recall correctly GTUNE never really worked. We do need a good autotune algorithm for quads though.

**Comment by 11digits** [comment]
What if we could have a different approach, a mode that would record data in blackbox for curent PID's and "auto" tune them after landing based on recorded data (even if it would offer some suggestions in the configurator like turn the P down or etc) ? Would that be possible maybe?

**Comment by digitalentity** [comment]
GTUNE is not going to make it back. We will see to a different approach to autotune eventually.
