### ISSUE TITLE
Servo pins #6 and #7 not working for CUSTOMAIRPLANE mixer

### ISSUE THREAD

**Issue by Dejw4g** [iNavFlight/inav#1619]
I'm trying to use servo pins 7 for Flaps and 8 for a retractable landing gear.

This is my smix:
smix 0 0 1 100 0 0 100
smix 1 1 0 100 0 0 100
smix 2 2 2 100 0 0 100
smix 3 6 10 100 0 0 100
smix 4 7 9 100 0 0 100

Elevator, Ailerons, Rudder and Throttle working just fine, I have a problem with last two definitions.

When I don't define them in SMIX (6 and 7) - these pins are just dead, even when I select respective AUX channel in Servos tab - still dead. I get a default signal out of them when I define smix for them as stated above (10 is AUX3, 9 is AUX2) but even though it looks like this in Motor tab: http://take.ms/n4EAn the real servos won't move at all - they will just get into default position when power cycled (unlike when not defining them in smix). I tried servo_tilt and channel_forwarding feature, nothing works (real servos still won't move).

The only way to make them work is set the mixer to AIRPLANE and they suddenly start working - the problem is the AIRPLANE has SMIX defined for servo pins number 6 (servo 7) with a throttle, so it's not usable for me.

I tried to do a dump of all configuration when AIRPLANE mixer in use and diff-compare it to CUSTOMAIRPLANE mixer and the only difference is in a name of a mixer and SMIX (SMIX is not listed in the dump when AIRPLANE in use). I tried to do "SMIX LOAD AIRPLANE" when CUSTOMAIRPLANE mixer is in use to get the same configuration for SMIX but with no success, it's still not moving when CUSTOMAIRPLANE mixer is active, but it moves when AIRPLANE mixer is active - when comparing these two dumps, only the name of the mixer is different.

I would say I tried all different combinations, I also used servo tester to make sure all servos are fine, but I can't make it work with CUSTOMAIRPLANE mixer.

**Comment by Dejw4g** [comment]
Ok, so I managed to get it working - the problem is that the numbering of servos is different when CUSTOMAIRPLANE is in used compared to AIRPLANE mixer.

With customairplane mixer, servo 3 is servo pin 3 (so you count from one to three - so you have two on the left free and third pin is servo 3). In other words, max servo number (for SP Racing F3) is number 8, but you don't see that servo in Configurator, cause servo pin 7 = servo 8 in Motor tab and servo 7 in Servo tab - so servo pin 8 is out of range.

Working smix:
smix 0 3 0 100 0 0 100 // ailerons (I use Y connector - so only one pin is needed) - on FC this is third servo pin, in motor tabs it's number 4 and in servo tab it's number 3
smix 1 4 1 100 0 0 100 // elevator, 4th on FC, number 5 in motor tab, number 4 in servos tab
smix 2 5 2 100 0 0 100 // rudder
smix 3 6 10 100 0 45 100 // flaps
smix 4 7 9 100 0 0 100 // gear

weird is, that this is also working with the same setup of ailerons, elevator and rudder (same FC pins), but flaps and gear are not working:
smix 0 0 1 100 0 0 100
smix 1 1 0 100 0 0 100
smix 2 2 2 100 0 0 100
smix 3 6 10 100 0 0 100
smix 4 7 9 100 0 0 100

honestly, I have no idea why I can use for ailerons (for example, it's the same with rudder and elevator) in smix servo number 3 or 0 and it works for the same pin on the FC - the third one

**Comment by TNgineering** [comment]
Did you get all of your outputs working yet? It looks like your smix lines don't include pins id's 3-5.

**Comment by Dejw4g** [comment]
As I wrote, this is a working smix for me:
smix 0 3 0 100 0 0 100 // ailerons
smix 1 4 1 100 0 0 100 // elevator
smix 2 5 2 100 0 0 100 // rudder
smix 3 6 10 100 0 45 100 // flaps
smix 4 7 9 100 0 0 100 // gear

but the problem is, that this:
smix 0 0 1 100 0 0 100 // ailerons
smix 1 1 0 100 0 0 100 // elevator
smix 2 2 2 100 0 0 100 // rudder

and this
smix 0 3 0 100 0 0 100 // ailerons
smix 1 4 1 100 0 0 100 //elevator
smix 2 5 2 100 0 0 100 // rudder

do exactly the same thing - with the same pins used on FC (SP racing F3) - both configurations work for the same pins used on the FC (third, fourth and fifth from left-side)

**Comment by DzikuVx** [comment]
OK, thanks for solution. I'm closing this with a remark that there will be changes how servos are handled in Configurator in the future
