### ISSUE TITLE
OmnibusF4 SD and random big shakes

### ISSUE THREAD

**Issue by alfag4** [iNavFlight/inav#1622]
Randomly when fly without any apparent reason my quad shake for about 1-2 secs then i can fly normally. Yesterday shaking two times in one pack. Today nothing in 5 packs
This issue also happens with BF on the same FC. Seems that disabling sd dma on this FC can solved the problem but from INAV CLI i don't see this option.
Running with 8k gyro and 4k pid multishot CPU at 15%
GPS and external compass

https://github.com/betaflight/betaflight/issues/2631

**Comment by TwoToneEddy** [comment]
Hi,
I have this flight controller and haven't had this problem. Can you do a diff all, I can compare it to my configuration.

**Comment by alfag4** [comment]
Here my settings:
# version
# INAV/OMNIBUSF4PRO 1.7.0 Apr 30 2017 / 19:03:42 ()

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mixer CUSTOM
mmix 0  1.000 -1.000  0.772 -1.000
mmix 1  1.000 -1.000 -0.772  1.000
mmix 2  1.000  1.000  0.772  1.000
mmix 3  1.000  1.000 -0.772 -1.000

# servo

# servo mix

# feature
feature -RX_PPM
feature RX_SERIAL
feature GPS
feature CURRENT_METER
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper -SYSTEM_INIT
beeper -ON_USB

# map

# serial
serial 0 64 115200 38400 0 115200
serial 5 2 115200 57600 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1900 2100
aux 1 1 1 900 1100
aux 2 2 1 1400 1600
aux 3 20 0 1900 2100
aux 4 3 2 1900 2100
aux 5 9 4 1800 2100
aux 6 8 3 1900 2100
aux 7 11 5 1900 2100

# adjrange

# rxrange

# master
set looptime = 250
set gyro_sync = ON
set gyro_sync_denom = 1
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 80
set gyro_notch1_hz = 200
set gyro_notch1_cutoff = 100
set gyro_notch2_hz = 330
set gyro_notch2_cutoff = 230
set acc_hardware = MPU6000
set acczero_x = 199
set acczero_y = -53
set acczero_z = -566
set accgain_x = 4083
set accgain_y = 4112
set accgain_z = 4010
set mag_hardware = HMC5883
set magzero_x = -44
set magzero_y = 12
set magzero_z = -100
set baro_hardware = BMP280
set min_check = 1020
set max_check = 1990
set serialrx_provider = IBUS
set blackbox_rate_denom = 4
set min_throttle = 1030
set max_throttle = 1950
set motor_pwm_rate = 8000
set motor_pwm_protocol = MULTISHOT
set failsafe_throttle = 1400
set failsafe_procedure = RTH
set align_board_roll = -4
set align_board_pitch = 12
set gps_sbas_mode = EGNOS
set nav_extra_arming_safety = OFF
set nav_mc_hover_thr = 1540
set osd_video_system = 1
set osd_units = METRIC
set osd_rssi_pos = 1047
set osd_crosshairs = 2048
set osd_gps_speed_pos = 2103
set osd_gps_sats_pos = 3424
set osd_gps_lon = 2450
set osd_gps_lat = 2432
set osd_home_dir = 2414
set osd_home_dist = 2081
set debug_mode = GYRO
set async_mode = GYRO

# profile
profile 1

set mc_p_pitch = 68
set mc_i_pitch = 52
set mc_d_pitch = 33
set mc_p_roll = 58
set mc_i_roll = 43
set mc_d_roll = 33
set mc_d_yaw = 20
set max_angle_inclination_rll = 450
set max_angle_inclination_pit = 450
set dterm_lpf_hz = 90
set yaw_lpf_hz = 0
set dterm_notch_hz = 280
set dterm_notch_cutoff = 130
set nav_mc_vel_z_p = 110
set rc_expo = 75
set roll_rate = 13
set pitch_rate = 13
set yaw_rate = 13

# profile
profile 2


# profile
profile 3


# restore original profile selection
profile 1
