### ISSUE TITLE
Feature request. Make possible to mount Fc vertical and Mag horizontal

### ISSUE THREAD

**Issue by Mow06** [iNavFlight/inav#1626]
1. Off board mag is preferable.
2. The capability is there to mount the FC vertically, on the side of a fuselage for example.
3. A GPS  needs to be mounted horizontal.
4. An external mag on that GPS cannot be used as the mag needs to be in the same plane as the FC.
https://www.rcgroups.com/forums/showpost.php?p=37428051&postcount=13710

Would it be possible to have the capability to use a mag mounted in a different plane to the FC, perhaps a roll option in align_mag?

**Comment by oleost** [comment]
Already exsist issues regarding this, please use search function before opening new issue.

#1029 
#86

**Comment by Mow06** [comment]
Sorry.Searched but obviously not for the right thing.
