### ISSUE TITLE
SP racing F3 board have motors issue on INav1.6~1.7

### ISSUE THREAD

**Issue by falconnet88** [iNavFlight/inav#1632]
I tried Inav 1.6 and Inav 1.7, sometimes only 2 of 4 motors can spin up.
In addition, the motors can only be throttle up, no any response to Rud/Aile/Elev.

After I flashed back to Inav1.5, all motors work well...

**Comment by digitalentity** [comment]
Please provide config dump and details of your setup.

**Comment by falconnet88** [comment]
Sorry, I don't know how to use CLI to check the setup.
These are some screenshots from my current INav configulator setting.

![image](https://cloud.githubusercontent.com/assets/28338424/25664477/46c317fa-304d-11e7-8aee-eba567a72a1f.png)
![image](https://cloud.githubusercontent.com/assets/28338424/25664503/648f10b8-304d-11e7-849d-aa7c92960d93.png)
![image](https://cloud.githubusercontent.com/assets/28338424/25664519/6ef52bd2-304d-11e7-9e11-553d322e0f1c.png)

**Comment by falconnet88** [comment]
I'm using stock 5" racer setting for my 250mm drone.
Using Blheli14.6 version.

My friend and I have the same issue.

**Comment by rb1205** [comment]
What's the point of having 2 kHz oneshot signals to the ESCs if your looptime is 1 kHz?

**Comment by falconnet88** [comment]
Re rb1205: Im using the stock setting of INav1.7 for 250mm racer drones. Didn't change anything. The CPU loading become 50%, is it one of the reason my drone behave strangely?

**Comment by stronnag** [comment]
Please post a CLI diff.
* Open the CLI tab
* type `diff`
* Paste the output here (in the <> 'insert code' style in the editor).

Note the the racer setting is intended for an Acro mode racer; no nav / sensors.

**Comment by falconnet88** [comment]
Thanks Stronnag, I chose 5" GPS setting today, 4 motors work well now. My friend and I all chose 5" racer setting and opened GPS before.

**Comment by digitalentity** [comment]
@falconnet88 I believe the issue can be closed now?

**Comment by falconnet88** [comment]
Yes, please. Thanks for the reply for solving this issue which caused by my wrong setting.
