### ISSUE TITLE
Magnetometer/Heading PID in configurator

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#1635]
I'm running 1.7 in order to test it, and I noted that Magnetometer/Heading in the PID tab of the configurator does not have any effect in the configuration (just run a diff).

I always wondered about the meaning of that parameter. 

![screenshot 2017-05-03 12 48 13](https://cloud.githubusercontent.com/assets/20860004/25657609/ffcf8246-2ffe-11e7-85c8-9f14a3660325.jpg)

```
# diff
# INAV/NAZE 1.7.0 May  3 2017 / 12:38:26 (55e8de9)
feature GPS
serial 1 2 115200 38400 0 115200
aux 0 8 0 1300 1700
set acc_hardware = MPU6050
set mag_hardware = HMC5883
set baro_hardware = NONE
profile 1
```

Is this a bug in the code or only configurator that left that parameter for ancient versions compatibility maybe?

**Comment by DzikuVx** [comment]
Just tested, it really looks like a bug. MAG pid not available in dumo or diff

**Comment by giacomo892** [comment]
@DzikuVx It might be a leftover in the configurator since I cannot find any meaningful parameter in the CLI.
It might be there from pre INAV era where mag data wasn't fused into the IMU but taken in account separately.

**Comment by DzikuVx** [comment]
with #2669 we can close this one I suppose

**Comment by adri94** [comment]
Hello,

I have a tricopter LR with a kakuteF7 and tekko32 ESC, the servo is a digital ES3054 from Emax. 

I flashed the FC with iNAV and the tricopter setup, I did the calibration but the heading is drifting one degree at a time every 15 seconds or so, still in the same direction.

If someone can point me in the right direction...

Regards,
