### ISSUE TITLE
GPS_PROTO_UBLOX_NEO7PLUS on F3 and F4 targets

### ISSUE THREAD

**Issue by rb1205** [iNavFlight/inav#1637]
Looking at the code I found this switch that configures the GPS for better sample rates (10 hz) along with other tweaks, but it's only defined on the AnyF7 target. Is it safe to test on F3 and F4 targets or there's more behind that makes it unflyable? I searched for issues and all I found is #431, bud doesn't seems anything critical.

**Comment by digitalentity** [comment]
Unfortunately many cloned M7 and even M8 GPS units don't support PVT message and enabling `GPS_PROTO_UBLOX_NEO7PLUS` makes them useless.

**Comment by rb1205** [comment]
I see. Still, is this safe to test? Should I expect better navigation performances if my GPS works with it?

Also if this is the case you may want to remove it from the AnyF7 target as well.

**Comment by stronnag** [comment]
It works just fine on my F3 FCs with m8n.It may or may not work for your devices. Your choice.

**Comment by rb1205** [comment]
OK, will test and post back any result. I'm closing this.

**Comment by rb1205** [comment]
Tested GPS_PROTO_UBLOX_NEO7PLUS on 1.7 on a 400mm quad. All GPS flight mode worked flawlessy. I noticed a better handling of braking when entering POSHOLD while going at speed. Other than that no noticeable improvements, at least at naked eye.

FC: SP3Evo

GPS: Belitian BN-880
