### ISSUE TITLE
Add "Cruise Control" flight mode

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#1642]
I am thinking about a "cruise control" like flight mode that can be applied to MC and FW.

Basically the mode should work like this.

1)the pilot reaches the desidered forward speed.
2)enables the mode (in conjuction with PH (cruise) and eventually AH)
3)releases the pitch stick to the middle and the machine maintains the current speed and direction.
4)now the speed can be adjusted by giving (speed up) or removing (decelerate) pitch.

What do you think?

I would like to contribute but I don't have enough skills to deep so down in the code.

**Comment by sppnk** [comment]
We talked about this long time ago here #92 and also related to #1416
