### ISSUE TITLE
OSD: GPS speed display corrupted. Omnibus F4 Pro V2 Fixed Wing

### ISSUE THREAD

**Issue by Martijn666** [iNavFlight/inav#1664]
Dear Devs,

I noticed on the latest 1.7 that the GPS speed icon for km/h is wrong. Also in the summary screen, the number doesn't correspond with the max velocity. See https://youtu.be/etGFGMyuhWY
Setup: S800 Sky Shadow, INAV/OMNIBUSF4PRO 1.7.0 May  3 2017 / 11:23:36 (104b66c)

**Comment by flounderscore** [comment]
That must have been my mistake. I did some chances while implementing
imperial units, but never had time to test them. There might also be a
mismatch between the character constants and the font.

Thanks for reporting it.

**Comment by digitalentity** [comment]
@flounderscore I believe fix should be fairly simple, no?

**Comment by flounderscore** [comment]
I'm getting the hardware for a new test setup (hopefully) today. I will
have a look.

**Comment by flounderscore** [comment]
@Martijn666 If you have a chance, can you (or someone) else test #1688? Should be working now, but it's going to be a while before I can test and fly it.

**Comment by Martijn666** [comment]
It will take me some time, will try to test tomorrow. Thanks.

**Comment by flounderscore** [comment]
Could you please also verify that distance and altitude alarms are working as expected?

**Comment by Martijn666** [comment]
I'll compile and flash now, testing will take place tomorrow afternoon. I'll post a dvr recording.

**Comment by Martijn666** [comment]
I have difficulties compiling. Can someone please compile TARGET=OMNIBUSF4PRO including #1688 ?

**Comment by flounderscore** [comment]
I'll upload a hex for you tonight (1h or two).

**Comment by Martijn666** [comment]
Thanks @flounderscore 

![image](https://cloud.githubusercontent.com/assets/5358522/26127222/eb2d8880-3a88-11e7-99ef-7dc415af370f.png)
That's all I get.

**Comment by flounderscore** [comment]
@Martijn666 You can get the hex from: https://ufile.io/4r3ep It's built form yesterday's development/HEAD

The checksum is (in case you're paranoid) is b55431c032f17f6cf371b107596699e9.

Thanks for testing.

**Comment by Martijn666** [comment]
Just my luck. Destroyed the bootloader button. I have another f4pro in the mail, expecting tomorrow. Stay tuned.

**Comment by flounderscore** [comment]
Flight tested today (in imperial mode) and max speed and distance from home was correct. Not sure about distance travelled (quite a large number in "ft", but probably correct).

**Comment by digitalentity** [comment]
Fix merged. Closing

**Comment by digitalentity** [comment]
@flounderscore thanks!
