### ISSUE TITLE
CLI current scale max should be much larger than 1000

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav#1668]
With my current setup I need to input a current scale of 2674. Its not possible because the max value is 1000.

**Comment by DzikuVx** [comment]
I see that code say -10000 to 10000

```
{ "current_meter_scale",        VAR_INT16  | MASTER_VALUE, .config.minmax = { -10000,  10000 }, PG_BATTERY_CONFIG, offsetof(batteryConfig_t, currentMeterScale) },
   ```

Anybody knows why scale can be lower than 0?

**Comment by skaman82** [comment]
My bad, overseen a zero :D But it is still 1000 in configurator

**Comment by DzikuVx** [comment]
@skaman82 not anymore

**Comment by krzysztofmatula** [comment]
> Anybody knows why scale can be lower than 0?

Didn't try this yet, but it is for sensors that report lower voltage as the current increases. Like for example ACS756KCA (which may be used both ways, with actually the reverse way being more attractive as it would guarantee the voltage will not exceed 3.3V, which is a limit for most FCs).

**Comment by DzikuVx** [comment]
OK, closing this one
