### ISSUE TITLE
Omnibus F4 V3 - RGB Led doesn't work

### ISSUE THREAD

**Issue by DangerD256** [iNavFlight/inav#1669]
I have this one:
http://shop.myairbot.com/index.php/flight-control/cleanflight-baseflight/omnibusf4v3.html

RGB Led works on Betaflight fine.

**Comment by flounderscore** [comment]
Did you use the led connector or PWM5/6?

**Comment by DangerD256** [comment]
Led connector, works well on betaflight

**Comment by flounderscore** [comment]
There were some timer conflicts on earlier revisions of the board that where fixed by moving the led to a different port, if I remember correctly. Some of the devs might chime in.

**Comment by DangerD256** [comment]
Need to move it back =)

**Comment by jstremmler** [comment]
In betaflight LED_strip is on B6 for OmnibusF4 Pro V3 and (mandatory) on A8 for OmnibusF4 Pro V2.
In iNav it is by default on A1 if you switch feature LED on. So I would try A1 (=  PWM Motor5) for the OmnibusF4 Pro V3.
So what we would need is a resource mapping in iNav which betaflight offers!

**Comment by modellbobby** [comment]
Anything here? I cannot make it work on PWM5
