### ISSUE TITLE
Roll and Tilt Orientation are wrong after set Yaw Orientation not equal to "0"

### ISSUE THREAD

**Issue by Stoeny** [iNavFlight/inav#1671]
After setting Yaw orientation to 90 deg or 270 deg in configurator, Roll- and Pitchorientation are exchanged.

**Comment by digitalentity** [comment]
This is not a bug. Roll, Pitch and Yaw alighment are relative to the **board** - meaning it's how your frame is aligned against the board.

**Comment by DzikuVx** [comment]
Closing
