### ISSUE TITLE
Feature request: simple LED control in LED Strip tab

### ISSUE THREAD

**Issue by Ozyris** [iNavFlight/inav#1686]
Hello.

Is it possible to add simple ON/OFF feature on LED Strip pin to control illumination mosfets? For example when arming motors send digitalWrite High on LED Strip pin.

**Comment by skaman82** [comment]
I think you can configure that already. Just select black color (leds off) for disarmed.

**Comment by Ozyris** [comment]
Is it simpler than change pin state? With this feature possible many things, not only switch lights.

**Comment by krzysztofmatula** [comment]
Making binary output from led-strip is pretty easy. All you need is a module like this one: http://allegro.pl/modul-led-ws2811-rgb-ws2812-neopixel-arduino-avr-i6765766807.html

You can easily replace led with mosfet to control anything. And you can chain a number of such devices. Alternatively you can just use the ws2811 chip, but module like the mentioned one is easy to use and costs close to nothing.

**Comment by Bobrcnut** [comment]
Isn't that the purpose of LEDLOW?  LEDLOW is added to the Modes page when you activate LEDstrip, and linking LEDLOW to an AUX channel allows you to turn all LEDs on or off without affecting their settings or assignments, so it somehow must be changing the state of the LED digital input line.

**Comment by krzysztofmatula** [comment]
LEDLOW works well allowing to torn off the lights when activated. It basically forces black color for all elements of led strip. You still need ws2811 controller.
