### ISSUE TITLE
F3 Plus f;light controller

### ISSUE THREAD

**Issue by rassievd** [iNavFlight/inav#1687]
Hi can any one help to add a servo to motor 5 or 6 output on the F3 plus FC. Ii am using only 4 motors for a quad copter, using n PPM input to the FC and use INAV1.7 software with SPracerf3 combination. I am setting the servo on AUX 2 and activate servo tilt in INAV but can not get the servo to react on motor 5 or 6 output.
Thanks

**Comment by DzikuVx** [comment]
Try motors 7 and 8. Servo tilt is passed to those outputs if I remember correctly.

**Comment by rassievd** [comment]
I put it on the FC  input pin 8 and channel forwarding on and it is now  working fine.
