### ISSUE TITLE
Request for fixedwing differential thrust stabilization

### ISSUE THREAD

**Issue by cabinw** [iNavFlight/inav#1694]
Hi all,
Since I also fly a racing quad, recently I am considering if it's possible to introduce differential thrust stabilization for fixedwings with two motors?

Like a quad, two motors can provide yaw and roll to a plane. You may need fast ESCs with active breaking on. But I think it's possible.

Is it?

**Comment by taileron** [comment]
No Problem use Custom Plane:
mixer CUSTOMAIRPLANE
mmix reset
mmix 0 1.000 0.000 0.000 1.000
mmix 1 1.000 0.000 0.000 -1.000
smix reset
smix 0 0 0 100 0 0 100 0
smix 1 1 0 100 0 0 100 0
smix 2 0 1 -100 0 0 100 0
smix 3 1 1 100 0 0 100 0

**Comment by oleost** [comment]
Yes this is correct.

Closing this one.
