### ISSUE TITLE
Switch to MWOSD's character map - discussion

### ISSUE THREAD

**Issue by flounderscore** [iNavFlight/inav#1697]
I was planning to fix the max7645_symbols.h (and update osd.c accordingly).

In that context I'd like to propose one of the following:

1. Keep using beta flight's character map (limited number symbols, because large fraction is used by betaflight logo)
2. Switch to MWOSD's character map (easiest solution, most/all? symbols already present, no space to implement a iNAV logo at a future point)
3. Make a custom iNAV character map (larger effort, needs to be maintained, would allow to implement a small-ish logo and still support all the bells-and-whistles)

What are your opinions on that?

**Comment by skaman82** [comment]
I like 2. the most. Never liked the betaflight logo taking so many characters for an useless splashscreen

**Comment by digitalentity** [comment]
I like the option 2 as well!

**Comment by flounderscore** [comment]
Ok, 2 it is!

**Comment by moggiex** [comment]
Daft question, could you not make the word "iNav" out of existing characters and display that at the beginning instead? Just a thought :)

**Comment by fiam** [comment]
This seems to have been superseded by several other OSD enhancements and the new tools we have for maintaining the character set.
