### ISSUE TITLE
How to flash Quanton FC 

### ISSUE THREAD

**Issue by ther0x** [iNavFlight/inav#1700]
Dear Friends, how can I flash INav from Taulabs?

Thanks a lot! :)

**Comment by ukmook** [comment]
Use an ST-Link V2 and load the .hex file using the SWD Port, i have not succeeded using taulabs GCS.

**Comment by digitalentity** [comment]
Unfortunately it's not possible to flash Quanton via Taulabs GCS or USB (it doesn't have a boot button). You have to use ST/Link V2 ISP adapter to flash the firmware.
