### ISSUE TITLE
mode GCS NAV,it will  fly away

### ISSUE THREAD

**Issue by lit1088** [iNavFlight/inav#1704]
I use f3 in  INAV 1.7.0, I can  poshold, but when i active GCS NAV,  it will fly away. in the GCS NAV mode ,i have active  ANGLE, NAV ALTHOLD ,NAV POSHOLD, GCS NAV  at the same time  with my phone  in ez-gui ,what can i do now?

**Comment by giacomo892** [comment]
Does your phone send to the drone a correct position to follow?

**Comment by lit1088** [comment]
How do I know if the correct data is sent?  i have checked my phone gps number  is  11，and the Aerocraft
gps number is 12，and can  3d poshold

**Comment by digitalentity** [comment]
NAV GCS merely allows your phone to control position of the quad. It's most likely the Ez-GUI issue, not INAV's

**Comment by giacomo892** [comment]
@lit1088 from ezGUI map

**Comment by tonyintn** [comment]
Not sure if it makes a difference but I do not believe you need to have ANGLE active just  NAV POSHOLD   NAV ALTHOLD   MAG  TOGETHER with  GCS_NAV.  But I suppose it does not hurt. 
I could not get mine to work good enough to where I would trust it the app always craps out not a inav issue was an issue with Ez-GUI found it to be buggy (always disconnecting) at least on my Note it is.

**Comment by digitalentity** [comment]
INAV doesn't validate what data is coming in from GCS. If GCS sends "fly to North Pole" - INAV will happily execute.
