### ISSUE TITLE
navPos[2] and navVel[2] going crazy in ANGLE mode at significant tilt

### ISSUE THREAD

**Issue by miradarya** [iNavFlight/inav#1708]
I believe I've noticed this earlier, but I recently reproduced it in 1.7 and recorded the event ([Diff](https://drive.google.com/open?id=0B40_6dQZRxYiRTFzdGhhTllXZDA), [Backbox log](https://drive.google.com/open?id=0B40_6dQZRxYiMmdlSm8wRTNQYjA), issue occurs in flight 3/3 at around 42 seconds, [Taranis Log](https://drive.google.com/open?id=0B40_6dQZRxYiMlNYQjBWX050UVU), issue starts at 11:27:28).

When flying in NAV ALTHOLD + ANGLE mode, navPos[2] goes crazy when accelerating e.g. with 40° pitch attitude after some seconds. The position estimator seems to think the multirotor is going down (navPos[2] decreases, navVel[2] goes negative) which in fact does not correspond to reality. ALTHOLD therefore increases throttle up to max, which leads to an uncommanded climb.

![image](https://cloud.githubusercontent.com/assets/2003693/26281985/afb8bd10-3e07-11e7-90bb-5d5e2c1107e3.png)

As you can see, baro altitude and navPos[2] diverge during the maneuver, with baro altitude actually corresponding well to what was really happening, i.e. the quadcopter was climbing from 10m to almost 30m during the event. The Taranis log shows that GPS altitude looks similar to baro altitude. So, the false decend the position estimator calculates can neither come from the baro nor from GPS.

I am somewhat familiar with coding and did take a look at the position estimator code, but I don't fully get the math behind it and therefore could not really figure out what was happening and where the false decend was coming from.

**Comment by digitalentity** [comment]
Attached log doesn't have the Log 3/3

**Comment by miradarya** [comment]
Oops, sorry about that, took the completely wrong file... This one is correct: [Log](https://drive.google.com/open?id=0B40_6dQZRxYiOWhBNHBTVXVpNjA)

**Comment by digitalentity** [comment]
Known issue - hardware vibration problem. Vibration beyond certain level causes accelerometer to go crazy and report acceleration that has nothing to do with reality. Usually happens when throttle goes above certain level:

![image](https://cloud.githubusercontent.com/assets/11059099/26295044/3884711c-3f0b-11e7-8f28-d5411cdc7e79.png)

Solution: soft-mount your FC.

**Comment by miradarya** [comment]
Ok, thanks, that makes sense! I didn't think about looking at the acc traces this time because they always looked pretty clean in other situations. I'll close this then and fix it by soft-mounting.
