### ISSUE TITLE
Feature request: Resource remapping as in BF

### ISSUE THREAD

**Issue by vinicentus** [iNavFlight/inav#1715]
How easy would it be to just port over the code for resource remapping from BF? Would this break something or should we give it a try? I kind of need this to max out the capabilities of my FC (Omnibus F4 pro)...

**Comment by digitalentity** [comment]
Duplicate of https://github.com/iNavFlight/inav/issues/1145

Also see my last comment in the thread https://github.com/iNavFlight/inav/issues/1145#issuecomment-275632775
