### ISSUE TITLE
Fixed-wing two motor issue

### ISSUE THREAD

**Issue by cabinw** [iNavFlight/inav#1717]
I've set up a plane with twin motors. All using BLS escs.
Protocol is multishot and esc refresh rate is 2k.

This setting caused a problem that one of the esc which was in the pin 2 cannot be detected by BLHeliSuite after flight. The esc will work just fine at low throttle. When the throttle is above almost 50% it makes strange noise.

This cause three escs cannot be detected. All of them work fine with Betaflight before I put them on iNav.

Really don't know why. Should I plug all escs on pin 1?

**Comment by digitalentity** [comment]
Wires to ESCs are too long. Twist signal wires from FC to ESCs, connect signal ground, solder a 1000uF capacitor to power lines near ESC.

For further support please use RCGroups forums.

**Comment by cabinw** [comment]
@digitalentity Thanks！I'll use RCGroups next time
