### ISSUE TITLE
Variometer for audio channel of VTX

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#1733]
Would be great to have the ability to make use of the baro support from the flight controller as an audible variometer feed to the audio channel of the video transmitter.
https://www.rcgroups.com/forums/showpost.php?p=37609866&postcount=14105
https://www.rcgroups.com/forums/showpost.php?p=37612975&postcount=14117

**Comment by GTorreil** [comment]
This feature could be integrated in the OSD ! MW OSD still supports the arduino tone() function ... ;)

**Comment by Schalonsus** [comment]
https://github.com/ShikOfTheRa/scarab-osd/issues/434
