### ISSUE TITLE
WingWing Z-84 Preset - Add Servo Reverse

### ISSUE THREAD

**Issue by moggiex** [iNavFlight/inav#1746]
Howdy,

In the next available release, can you set this:

`servo 3 1000 2000 1500 -100 -1 `

As part of the preset for the WingWing Z-84 so that the servos work correctly. Right now servo 3 is backwards and setting this as part of the preset would save a step for a new user (and potential foam snow)

ta! 

Matt :)

**Comment by DzikuVx** [comment]
Presets are Configurator only features, so moved to iNavFlight/inav-configurator#205
