### ISSUE TITLE
Looptime <2000 doesn't work on F3 

### ISSUE THREAD

**Issue by dyter** [iNavFlight/inav#175]
Looptime configuration is saved but not in cpu status

![inav1 1rc2](https://cloud.githubusercontent.com/assets/17790169/14897555/c1ae9c26-0d82-11e6-8247-ab266e095dba.png)

**Comment by digitalentity** [comment]
`gyro_sync=ON` makes looptime irrelevant.
`gyro_sync_denom=2` is effectively setting cycle time to 2000, so you get precisely what you ask for.
