### ISSUE TITLE
OSD: "UK Mode" Show Speed in mph, while other values in Metric

### ISSUE THREAD

**Issue by moggiex** [iNavFlight/inav#1756]
Howdy,

At first glance this might sound odd! 

> Why would someone want the speed in miles per hour (mph), but the other values, such as height or distance in metres or kilometers?

Here's the thing, in the United Kingdom car speedo's are in mph, so the we understand speed in mph (and not kmph), however in schools we're taught to use measurements in metres etc...

Hence the request, is it possible to be able show mph for speed, but keep the metric values for the options?

Matt

**Comment by martinbudden** [comment]
@digitalentity , while this does seem odd, it does actually make sense for people flying in the UK.

**Comment by moggiex** [comment]
@martinbudden we're "special" in more ways than one :)

**Comment by martinbudden** [comment]
It amuses me that all quadcopter measurements are metric, except prop sizes which are imperial. And there's even an exception to that rule - prop sizes for small brushed quads are metric.

**Comment by Redshifft** [comment]
Lol, great subject. Imperial system is total crap really but I'm guessing even British kids out of school now only catch fish in pounds from water depth measured in feet ;) and If you told them how fast your car was in kph they would say..wtf is that in real speed :D 

But like that school kid, I look at the metric osd and think how fast is that really...LOL but for sure I don't need a calculator to work out how far home is in time when I have km's and meters and i'm flying in km's opposed to miles and feet.

**Comment by geofrancis** [comment]
real nerds use meters per second lol

**Comment by fiam** [comment]
@martinbudden Please, send this one my way too

**Comment by flounderscore** [comment]
@fiam Thanks Alberto for contributing so much to iNav lately. Since you're doing a lot of OSD related work, maybe you could consider switching over to the MWOSD char map (I started working on it in https://github.com/iNavFlight/inav/pull/1796 )

**Comment by fiam** [comment]
Should have been automatically fixed by #2049. Can someone with write access mark this as fixed?

**Comment by digitalentity** [comment]
Fixed by #2049
