### ISSUE TITLE
Last LUX release is 1.3

### ISSUE THREAD

**Issue by 2ndalpha** [iNavFlight/inav#1757]
Not sure if it is a issue with a release procedure or configurator but the last version for Lumeniers LUX board is 1.3
Building it manually works fine.

![screen shot 2017-06-03 at 17 24 18](https://cloud.githubusercontent.com/assets/2319203/26754859/25c609f8-488b-11e7-99b6-1728c014f45b.png)

**Comment by digitalentity** [comment]
Fixed.
