### ISSUE TITLE
Gyrosync not work

### ISSUE THREAD

**Issue by dyter** [iNavFlight/inav#176]
Gyrosync=ON doesn't work (can not use more cpu)

![inav1 1rc2](https://cloud.githubusercontent.com/assets/17790169/14897805/c9fa2534-0d83-11e6-9551-ebe1a9912bb0.png)

**Comment by digitalentity** [comment]
Unable to reproduce the issue on SPRacingF3:
![2016-04-29 08 01 44](https://cloud.githubusercontent.com/assets/11059099/14903670/0de5e7ee-0de6-11e6-80bc-aa8b791ed352.png)

**Comment by digitalentity** [comment]
What board do you have?

**Comment by dyter** [comment]
It's a Beerotor F3

**Comment by digitalentity** [comment]
Just to verify - did you power-cycle the board after enabling gyro sync?

**Comment by dyter** [comment]
I set looptime to 250 but it's stay to 1000, I don't understand !

(I use Inav configurator and last build of Inavflight)

![presse-papiers-1](https://cloud.githubusercontent.com/assets/17790169/14917426/436837b2-0e1f-11e6-99c1-10845de238f8.png)

**Comment by digitalentity** [comment]
As I said in #175":

> `gyro_sync=ON` makes `looptime` setting irrelevant.

```
gyro_sync=ON
gyro_sync_denom=1
```

sets the cycle time to 1000. It is unwise to attempt to go lower than that on INAV.

**Comment by digitalentity** [comment]
Apparently gyro_sync works on your board. Issue is closed.
