### ISSUE TITLE
Feature Request: BLHeli32 PassThrough and D-Shot (150 would be enough)

### ISSUE THREAD

**Issue by SoulPictures** [iNavFlight/inav#1761]
Hi there Dev. Team, the new BLHeli32 ESC got quiet neat features for Wings like Current Protection. Due to Betaflight already having Passthrough working (BF3.2) it shouldn't be hard to port it? Additionally an D-Shot mode, even the slowest would be perfect to completely eliminate noise on the ESC line. Are there possibilities to port those features?

**Comment by digitalentity** [comment]
Very low priority. DSHOT doesn't give any benefit over "analog" protocol but actually masks a potential problem with EMI noise.

**Comment by kingdraki** [comment]
BLHeli32 ESC featuring onboard telemetry and can report VBAT and Current via UART to the FC. This would be a great benefit to use these Sensors in Inav.

**Comment by VoicOfReason** [comment]
I agree

**Comment by Feldsalat** [comment]
I had to flash betaflight today, only to adjust my 32bit esc. Would be nice if that would also be possible with Inav :-)

**Comment by digitalentity** [comment]
@Feldsalat please check if https://github.com/iNavFlight/inav/pull/2530 works for you
