### ISSUE TITLE
iNav 1.7.1 no ALT icon

### ISSUE THREAD

**Issue by wiesiekkr** [iNavFlight/inav#1762]
The icon should be at the top right
https://goo.gl/photos/pGCyv96kc6tyRvu36

**Comment by wiesiekkr** [comment]
Board: KFC32F3

**Comment by giacomo892** [comment]
Maybe you need a GPS fix

**Comment by wiesiekkr** [comment]
Of course I have GPS fix......and 400m AGL :)

https://goo.gl/photos/xQFx9op5w1aQYwMy8

**Comment by flounderscore** [comment]
As far as I know the current firmware doesn't show an icon for altitude.

**Comment by marbalon** [comment]
Yes but should show, it is wrong symbol in definitions. Will be fixed in next release.

**Comment by flounderscore** [comment]
I'm working on replacing the betaflight font with the default MWOSD font.
The symbol definition is going to be updated as well.

**Comment by digitalentity** [comment]
Fix merged. @flounderscore how is your work coming along?

**Comment by flounderscore** [comment]
I updated the symbols file and osd.c a while back, but I haven't had time
to test it yet. Hopefully I'll get a chance this weekend (too many other
projects :-o ). Once I submit the PR I will need some help with the vario
as I've never used it and I'm not 100% sure how it's used.
