### ISSUE TITLE
Omnibus F4 (non pro)  SBUS not working

### ISSUE THREAD

**Issue by Key0nee** [iNavFlight/inav#1763]
Hello,
   I am using an Omnibus F4 (non pro) purchased from RTFQuads... in a small GPS camera ship build.  I am using an Futaba Sbus receiver (R7008SB) connected to UART 6 marked PPM/SBUS and SBUS is shorted to middle pad.  All other required iNav settings are verified (ie port, serial rx type etc...)  No receiver values are making it to the flight controller.  I've also tried latest iNav version for other Omnibus f4 targets with no luck..

I thought it was a bad board but then I tried the latest version of Cleanflight for F4SD target and it worked fine... all values from receiver are being reported in Cleanflight.  Only tested on UART 6.

Also works in Betaflight latest version for F4SD Target

**Comment by scrapit85** [comment]
This is the same issue as #1643 
Also tried to get it to work with Frsky sbus. As you said Betaflight and Cleanflight work fine and so does the modified Exotic OMNIBUS iNav 1.6.1 with it setup on UART 6

**Comment by Key0nee** [comment]
Sorry... I should have read thru here more thoroughly... I already felt out of place posting here and not being a developer...
Thanks for the post... I'll read issue #1643

**Comment by moggiex** [comment]
@Key0nee daft one, see this video as you might have 3 pads that 2 of them might need bridging to make SBUS work [https://www.youtube.com/watch?v=ZFVIbU4aJvo](https://www.youtube.com/watch?v=ZFVIbU4aJvo) or at least a sanity check you've done it right as I had the same issue, Matt

**Comment by jflyper** [comment]
@all Sorry, it's my bad not submitting PR for this problem. It jumped two notches in my list of todos... 😭

**Comment by iconicj** [comment]
I thought this was a known limitation of the f4s only supporting sbus inversion on one uart - uart1, next to the motor output headers.

**Comment by DzikuVx** [comment]
@iconicj It's not STM32F4 but rather FC itself problem. SBUS can be connected only to UART that has additional inverter in from of it. It can be any UART or even any number of UARTs

**Comment by jflyper** [comment]
@here 
#1779 is submitted, but need some testing.
[inav_1.7.1_OMNIBUSF4V3-0.hex.zip](https://github.com/iNavFlight/inav/files/1064490/inav_1.7.1_OMNIBUSF4V3-0.hex.zip)

I also need someone to test F4, F4V2 and F4Pro for regression test...

**Comment by scrapit85** [comment]
@jflyper Just tested on a F4 V3 board and Frsky the SBUS input is now working.
Also tested on a F4 Pro V2 and the SBUS is still working.

**Comment by jflyper** [comment]
@scrapit85 
Thanks for testing! Can you keep the OMNIBUSF3V3 running, possibly with flight test?

**Comment by scrapit85** [comment]
Will leave it running for a while then just got to install it in a plane hopefully test tomorrow.

**Comment by jflyper** [comment]
@scrapit85 Ah, I meant "can you leave the board loaded with OMNIBUSF3V3" by "keep it running".  Looking forward to hearing the flight test :)

**Comment by Key0nee** [comment]
Futaba SBUS working on F4v3...

**Comment by Key0nee** [comment]
@jflyper Thanks for the fix my futaba SBUS is working well but I have a new issue (maybe)... Can you comment on weather PR [ #1607](https://github.com/iNavFlight/inav/pull/1607) is rolled up in the firmware you linked above.  If I understand this correctly the servo/ESC outputs have been moved two set down so PWM 1 is now on PWM 3 output pins.

I get NO signal to my ESC's on PWM outputs 1&2 but they show up fine on PWM output 3&4, as outputs from motor channels 1&2.  Currently, I don't have a need for servo outputs so I don't have pins soldered to PWM outputs 5&6.  If the PWM outputs are just remaped as I understand it, is there a simple end user method to remap to stock settings... maybe like mmix ?


Added 6-11 at 4pm
Just tried the same test with Released version 1.7.1 F4PRO (I am using a non-PRO v.3 board) PWM output mapping is what I expected with motor channel 1 appearing on PWM output 1

Thank You
K

**Comment by jflyper** [comment]
@Key0nee Ah, I think I know what's happening.

**Comment by jflyper** [comment]
@Key0nee Your esc/servo mapping issue is completely different from the SBUS problem?

**Comment by jflyper** [comment]
@Key0nee Proposed mapping in #1607 is effective only for airplane or some mixer with servos. It shouldn't affect pure multi-rotor vehicles. Oh, are you using servos for a gimbal?

**Comment by Key0nee** [comment]
@jflyper No gimbal or servos used... wih inav 1.7.1 installed and using the motor tab to individually test spin motors i get what I expected, motors 1-4 corresponding to PWM outputs 1-4

When using inav 1.7.1 F4V3-0, using the motor tab to individually spin up motors result in no output on PWM 1-2, but motors 1-2 present on PWM outputs 3-4...  i will try get pins installed for PWM outputs 5-6 tomorrow and test again...

**Comment by jflyper** [comment]
@Key0nee Ah!!! It's probably my bad... Hang on, I'll investigate and fix it.

EDIT
Okay, new firmware is at the end of #1779. Should fix the motor shift issue.

**Comment by jflyper** [comment]
@Key0nee
Did you try the updated firmware?

**Comment by Key0nee** [comment]
@jflyper I just downloaded... been busy at work and haven't had time but will try and report tonight...

**Comment by Key0nee** [comment]
@jflyper installed and initial power up all look good... SBUS works great and motor shift issue is gone.. will continue to update... Thanks

**Comment by jflyper** [comment]
@Key0nee Thanks for testing & reporting!

**Comment by Key0nee** [comment]
@jflyper  just tested the LED strip control... No Bueno... [Link](https://github.com/iNavFlight/inav/issues/1803)
