### ISSUE TITLE
V-Tail210 - SP Racing F3 Evo -Accelerometer - Magnetometer / OSD not available 

### ISSUE THREAD

**Issue by yo8aiv** [iNavFlight/inav#1764]
While Gps works great and there are great options 
V-Tail210 - SP Racing F3 Evo - Accelerometer -Magnetometer / OSD not available 

not detected correctly and when i select still its not taken into account

- works in cleanflight
CPU Clock=72MHz, GYRO=MPU9250, ACC=MPU9250, BARO=BMP280, MAG=AK8963 
So there must be some conflicts
OSD not being detected .

- iNav status below:
GYRO=MPU6500, ACC=MPU6500, BARO=BMP280, MAG=AK8963
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, SONAR=NONE, GPS=UNAVAILABLE
If needed i can make tests.
Thanks.

**Comment by stronnag** [comment]
iNav correctly reports the GYRO/ACC as MPU6500, it works perfectly. My favourite iNav board. From the manufacturer's data sheet:

> The MPU-9250 is a System in Package (SiP) that combines two chips: the MPU-6500, which contains a 3-axis gyroscope, a 3-axis accelerometer, and an onboard Digital Motion Processor™ (DMP™) capable of processing complex MotionFusion algorithms; and the AK8963, the market leading 3-axis digital compass.

**Comment by DzikuVx** [comment]
> Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK

Like @stronnag wrote: everything is OK since MPU9250 is 2 devices in 1 package
