### ISSUE TITLE
Feature request: beep at compass calibration start

### ISSUE THREAD

**Issue by dragon1020** [iNavFlight/inav#1765]
When you start calibration via sticks it's hard to understand, when it starts, and does it starts at all. A plain "beep" by buzzer will be nice.

**Comment by krzysztofmatula** [comment]
I've also seen FC, where during whole compass calibration phase a short beeps/ticks were produced as the controller was moved. This was giving nice feedback when the procedure started and when stopped, and also when new "angles" were used during the process.
