### ISSUE TITLE
Feature Request: Add HDOP to OSD

### ISSUE THREAD

**Issue by moggiex** [iNavFlight/inav#1767]
Howdy,

Is it possible to add HDOP as an option to display on the OSD please?

Reason: Might not have a low enough value when arming and would be able to see that, delay for a minute or two until the HDOP is a more acceptable value before taking off.

Matt

**Comment by fiam** [comment]
@moggiex Not sure how to implement this one. Should we add a new OSD element for the HDOP or a setting for the `OSD_GPS_SATS` to make it display HDOP next to the satellite number?

**Comment by moggiex** [comment]
Good question @fiam 

In an ideal world it would be a separate value to be shown on the OSD. Personally I would always have it showing under the sat count on my screens, Matt

**Comment by fiam** [comment]
@moggiex How does this one look? It's just displaying the integer part of the HDOP to save some space. Do you think adding decimals is worth it?
<img width="499" alt="screen shot 2017-09-17 at 16 23 43" src="https://user-images.githubusercontent.com/41529/30522250-05c95eba-9bc5-11e7-87b7-37fe8e786809.png">

**Comment by moggiex** [comment]
Just seen your message, yes adding one decimal place is the "norm", Matt

**Comment by fiam** [comment]
@moggiex We'll add a decimal place once we merge fixed width number formatting. I'll reopen this issue to avoid forgetting it.

**Comment by fiam** [comment]
HDOP now uses one decimal, so this is now fixed.
