### ISSUE TITLE
RSSI (FrSky XM+ via Channel 16)

### ISSUE THREAD

**Issue by plogibear** [iNavFlight/inav#1768]
Hi,

INAV somehow cannot detect the RSSI from Aux 12 w/c is outputted by the FrSky XM+ on channel 16. It does work on Betaflight.

Cheers.

**Comment by isilcala** [comment]
I'm using XM+ with iNav without a problem. Shouldn't it be the aux 12?

**Comment by digitalentity** [comment]
Channels 1-4 are flight channels (AETR), channel 5 is Aux 1 - therefore channel 16 is Aux 12. 
RSSI on XM+ works well on my setups.

**Comment by Schalonsus** [comment]
@plogibear , did you buy from BG? Then you have to flash the rssi firmware to the xm+...

**Comment by plogibear** [comment]
Yes as a matter of fact I did buy it from Banggood. Thanks for the tip @Schalonsus . I almost threw it out the window.

**Comment by DzikuVx** [comment]
@plogibear if you don't mind, I will close this ticket since it's not INAV firmware related
