### ISSUE TITLE
failsafe setting for fixed wing

### ISSUE THREAD

**Issue by xianglibao** [iNavFlight/inav#1769]
i am flying a fixed wing and i use a switch to arm or disarm craft.   i can't understand, why need to set the arm switch to disarmed when set failsafe on RX?  and i found failsafe setting in the wiki and doc are different and conflicting.

<img width="920" alt="doc" src="https://cloud.githubusercontent.com/assets/4018195/26813497/2c99a9f6-4ab1-11e7-8993-330f507ab096.png">
<img width="618" alt="wiki" src="https://cloud.githubusercontent.com/assets/4018195/26813498/2ca9c21e-4ab1-11e7-81e7-17bad85ccd30.png">

**Comment by isilcala** [comment]
depending on your gears, if you can set your rx to no signal at all when failsafe, then that'll be good enough. if not, set arm channel accordingly. Either way, double check the failsafe setting in your FC and do bench testing.
