### ISSUE TITLE
Can't get servo output...........

### ISSUE THREAD

**Issue by cdog4twenty** [iNavFlight/inav#1771]
I am using a colibri race FC, I am all green on the setup screen. I have connected the servo ground and signal to outputs 3&4 on the flight controller. I am powering the servos and fc from the same bec, but the servos are not feed power from and through the FC. I cannot for the life of me get any servo movement except a jitter when plugging in. I have tested the servos throuought and they work fine. Im lost. I have also played with the channels and servos in the servo tab and im still lost......... The esc connected to output 1 does work. Do I need something special to drive the servos?

**Comment by moggiex** [comment]
Howdy,

A couple of daft things to check

- Do the servos actually work? (are you _Really_ sure?)
- Has iNav been set to be a flying wing or fixed wing model on the configuration tab?
- Is the board armed?
- Is your receiver inputs working correctly?
- Have you plugged the servo into the correct PWM outputs? (PWM 3 & PWM 4 for a flying wing)
- On the configuration tab, do you have the servo refresh rate set to 50Hz

Hope those pointers help, Matt

**Comment by sambas** [comment]
target doesn't have any Servo outputs mapped
https://github.com/iNavFlight/inav/blob/master/src/main/target/COLIBRI_RACE/target.c

**Comment by digitalentity** [comment]
Servos are not supported on COLIBRI RACE target

**Comment by cdog4twenty** [comment]
Well that is terrible news. I have a few I was hoping to use. Can the situation be fixed? The colibri race has four outputs on the FC to connect to.

**Comment by digitalentity** [comment]
It may be fixed along with timer cleanup https://github.com/iNavFlight/inav/pull/1591

**Comment by cdog4twenty** [comment]
Would I just re-install the latest inav firmware for colibri race to see if it works?

**Comment by digitalentity** [comment]
PR in place. Closing

**Comment by S-T-A** [comment]
i have a TBS colibri v1.2 on i nav 1.9.1 with the "wing preset" only one servo works. With servo output to aux selected the other servo works on my arm switch mixers don't work can i get help to het this working with presets ??? with custom settings i got this to work
mmix reset
mmix 0 1.000 0.000 0.000 0.000
smix reset
smix 0 3 0 -100 0
smix 1 4 0 -100 0
smix 2 2 1 -100 0 *it doesn't work with out this line why?
smix 3 3 1 -100 0
smix 4 4 1 100 0
save
