### ISSUE TITLE
iNAV Ver 1.7.1....Home direction Pointer Arrow.

### ISSUE THREAD

**Issue by EnglishTurbines** [iNavFlight/inav#1784]
A small bug, inside iNAV the OSD layout shows the Home Pointer Arrow as a numeric value instead of an Arrow Pointer.

 The Distance from home value also appears to have the Home Pointer Arrow stuck on the end of it for some reason?  Only inside iNAV though. Anyway, all's good now....:)
![omnibus 4](https://user-images.githubusercontent.com/29343996/27010982-2edfe3aa-4ea9-11e7-92f8-0e37ca34c076.jpg)

**Comment by digitalentity** [comment]
Not sure what bug are you decribing - if on a real board everything it good and it's displayed incorrect only inside INAV Configurator - this bug should be reported there.

**Comment by DzikuVx** [comment]
From my latest tests, home arrow works good. Perhaps you had old font uploaded? I'm closing this for now, if any new data appears, feel free to reopen
