### ISSUE TITLE
Lux FC - servos do not work

### ISSUE THREAD

**Issue by 2ndalpha** [iNavFlight/inav#1795]
Based on this issue I might be only one of a few who is trying to run iNav on Lux: https://github.com/iNavFlight/inav/issues/1757

I do not get servos to work, they jump when plugging in the battery and then nothing.
They do not try to hold any position. I'm trying it in passthrough mode.

I tried the same steps/setup with Naze, worked as expected.

Might it be related to TODO-s here? https://github.com/iNavFlight/inav/blob/master/src/main/target/LUX_RACE/target.c

**Comment by digitalentity** [comment]
Yes, servos are not implemented for LUX target. We'll probably fix it along with merging https://github.com/iNavFlight/inav/pull/1591

**Comment by digitalentity** [comment]
PR in place. Closing
