### ISSUE TITLE
CURRENT_METER_SCALE on OmnibusF4PRO (SD)

### ISSUE THREAD

**Issue by alfag4** [iNavFlight/inav#1800]
The default value is now 265 (in target.h) but measuring the current with an ammeter the correct scale for my omnibus seems 400. Why this new default value?

**Comment by DzikuVx** [comment]
Probably different revision of the board. The ones we received from Airbot had 265 not 400. Which makes sense, since scale 400 gives max readout of about 82A at 3.3V

**Comment by alfag4** [comment]
I bought it on airbot shop in march, so i don't know which version i have probably V3. In my case the value of 400 returns a current absorption identical to the ammeter.
Thanks.

**Comment by DzikuVx** [comment]
OK, since looks like there are multiple types of this board on market (and clones and so on) and it is not possible to determine current meter scale from software, looks like we have to leave it as it is. Every user would have to calibrate it by himself
