### ISSUE TITLE
LED strip control not working in inav_1.7.1_OMNIBUSF4V3-1

### ISSUE THREAD

**Issue by Key0nee** [iNavFlight/inav#1803]
Hello,
      I have been testing inav_1.7.1_OMNIBUSF4V3-1 obtained [Here](https://github.com/iNavFlight/inav/pull/1779)  LED strip control does not appear to be working.. I have tested the same board in the exact setup with Cleanflight v2.0.2 for OMNIBUSF4SD target and it works fine.

**Comment by flounderscore** [comment]
In iNav the led strip needs to be connected to PWM5 (see
https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md
).

**Comment by Key0nee** [comment]
Copy that... 

Thanks..

**Comment by jflyper** [comment]
FYI, F4 V3 (and some variants) has PB6 connected to the designated LED strip signal pin.

Ref:
https://github.com/betaflight/betaflight/wiki/Board---OMNIBUSF4#v317-and-later-led-strip-pin-assignment-has-changed-for-omnibusf4sd-target

**Comment by Key0nee** [comment]
@jflyper 
I have it working for the most part on PWM 5 output but I have noticed that assigning an led color for battery condition doesn't change regardless of battery level..
Also Is there a method for changing  the color assignments for modes
