### ISSUE TITLE
Omnibus F4 v3 DFU Mode detection problems..  Not unique to iNav... 

### ISSUE THREAD

**Issue by Key0nee** [iNavFlight/inav#1804]
Hello,
         Probably not a firmware issue but I thought posting here might save others time and frustration.  I am using an Omnibus F4v3 for my latest build and found that my laptop will not recognize the Omnibus in DFU mode with a GPS plugged in and powered up.  This also happens with the latest version of Cleanflight for OMNIBUSF4SD target.  Removing power from the GPS seems to allow proper DFU mode detection and driver configuration...

K

**Comment by oleost** [comment]
GPS or the compass ? Sda/SLC lines?

Having compass connected without powering it up is often begging for
problems.

18. jun. 2017 5.32 p.m. skrev "Key0nee" <notifications@github.com>:

**Comment by Key0nee** [comment]
@oleost 
  I guess I should have included this detail.. but for me its the GPS... I am using the NEO m8N's compass but, the problem seems to be the same with the Sda/Slc connected or not...

**Comment by digitalentity** [comment]
It's the hardware limitation. Built-in bootloader activates on USB/UART1. If there is activity on UART1 bootloader doesn't enable USB DFU.

**Comment by Key0nee** [comment]
Copy that....
