### ISSUE TITLE
Spektrum Serial Telemetry Receiver (SPM4649T) Interfacing

### ISSUE THREAD

**Issue by JulianGoesPro** [iNavFlight/inav#1806]
It looks like iNav hasn't jumped on the Spektrum Telemetry Hype Train :) ...but it's pretty cool to just use on Tx pad for both rcLink and TLM so that one UART can do that (Tx) and e.g. SmartAudio (Rx) with a TBS Unify^^
I am not sure how much work it is to use the code Betalight has for this bi-directinal protocol. 
[url]https://www.rcgroups.com/forums/showthread.php?2775731-Spektrum-Serial-Telemetry-Receiver-%28SPM4649T%29-Interfacing[/url]
Thanks!

**Comment by martinbudden** [comment]
I'll look at doing this for the next release. @JulianGoesPro are you volunteering to do the testing? (I don't have any Spekturm hardware.)

**Comment by JulianGoesPro** [comment]
Sure, I have an OmniBusF4ProV3 running iNav and an SPM4649T (setup as a normal SpekSat right now) and sure would help testing :)

**Comment by JulianGoesPro** [comment]
On what UART do you want me to solder it to?
