### ISSUE TITLE
Setting pids from this doc doesn't work

### ISSUE THREAD

**Issue by Dutchy-79** [iNavFlight/inav#1807]
Hi,

I followed this 450 size pids for my S550 Hex build but all is Invalid name

https://github.com/iNavFlight/inav/wiki/Default-values-for-different-type-of-aircrafts

> # set p_pitch = 90
Invalid name

# set i_pitch = 34
Invalid name

# set d_pitch = 54
Invalid name

# set p_roll = 90
Invalid name

# set i_roll = 34
Invalid name

ETC,..

>

**Comment by oleost** [comment]
Read first line..

This is outdated, INAV 1.6 is out and is using PRESET. Values here are old.

That is an outdated document for old INAV versions. Since then variables have also changed name.
