### ISSUE TITLE
MSP QUESTION: is there a way to omit certain parameters?

### ISSUE THREAD

**Issue by johnsilvester** [iNavFlight/inav#1808]
I was hoping to use the MSP_SET_RAW_RC but only wanted to override roll and still have access to the other inputs via a separate RC PWM controller. Is this possible?

**Comment by johnsilvester** [comment]
Oops I hope this wasn't the wrong place for this question!

**Comment by DzikuVx** [comment]
I'm affraid this does not works that way @johnsilvester . `MSP_SET_RAW_RC` sets all channels. If data is missing, `0` is assumed. So you would have to read other channels with `MSP_RC`.
Besides the fact, that I'm not sure it is ok to use `MSP_SET_RAW_RC` and reguler RC input at the same time. You would have to check that yourself
