### ISSUE TITLE
Sonar on SPR F3? 1.7.1

### ISSUE THREAD

**Issue by johnsilvester** [iNavFlight/inav#1812]
I saw that sonar was back in 1.7 and I was wondering if there was a way to enable it through the inav configurator? Thanks!

**Comment by johnsilvester** [comment]
nevermind!

**Comment by liutairan** [comment]
Did you find it? I am also looking for it.

**Comment by Bobrcnut** [comment]
On the Configuration page, there is a list of sensors.  The last one is 'Rangefinder'.  Set it to your type of Sonar device, then Save and Reboot.  The Sonar indicator at the top of the page immediately after connecting should now be green.
