### ISSUE TITLE
LTM/other telemetry - Allow lower baudrates than 9600bps

### ISSUE THREAD

**Issue by sppnk** [iNavFlight/inav#183]
AFAIK, when baudrate decreases, the range increases. So It would be good to permit lower baudrates to LTM protocol (until 1200bps perhaps).May be for a audio-over-video downlink or other telemetry systems.

I my actual setup I use openlrsng, and I guess that the 'serial baudrate' (telemetry data link in openlrsng) for it has to be lower than 'baudrate' (radio connection). So if I use 'baudrate' = 9600 bps, then there is no margin for 'serial baudrate' lower than that. Would be nice if I could set LTM to 2400 and radiolink to 9600. For airplanes in mission WP for example, radiolink  could be down to 4800 bps and telemetry down to 1200 bps.

Now I have set radiolink ('datarate' in openlrsng) to 19200 and 'serial baudrate' to 9600 in order this to work. And it does, but I would prefer to have more range.

Please, feel free to correct me if I am wrong with something of this.

**Comment by DzikuVx** [comment]
I can only agree. Lower baud rates would be nice addition. I wonder if min at 9600 is some kind of legacy from MultiWii or there is a real reason for it?

**Comment by digitalentity** [comment]
I've looked into it and if we do it we will break compatibility with Cleanflight Configurator as it operates indexes, not numeric baud rates.
What we can do is force AUTO baud rate for LTM telemetry to be actually 1200 baud.

**Comment by stronnag** [comment]
On 4 May 2016 10:07:40 BST, Konstantin Sharlaimov notifications@github.com wrote:

> I've looked into it and if we do it we will break compatibility with
> Cleanflight Configurator as it operates indexes, not numeric baud
> rates.
> What we can do is force AUTO baud rate for LTM telemetry to be actually
> 1200 baud.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/iNavFlight/inav/issues/183#issuecomment-216802631

Current LTM is effectively at or perhaps just over 2400baud. The original implementation catered for low (<2400) and higher (>2400) rates. This was removed for CF due to 9600 minimum. We'd need to reimplement for 1200, which would be easy.

**Comment by digitalentity** [comment]
@stronnag 
LTM for low and high baud rates would be a good thing!

Once I release initial version of INAV configurator I intend to deliberately break compatibility with original Cleanflight configurator to avoid issues with board alignment etc, We can look into adding lower baud rates to Configurator then.

What do you think?

**Comment by stronnag** [comment]
On 4 May 2016 10:20:09 BST, Konstantin Sharlaimov notifications@github.com wrote:

> @stronnag 
> LTM for low and high baud rates would be a good thing!
> 
> Once I release initial version of INAV configurator I intend to
> deliberately break compatibility with original Cleanflight configurator
> to avoid issues with board alignment etc, We can look into adding lower
> baud rates to Configurator then.
> 
> What do you think?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/iNavFlight/inav/issues/183#issuecomment-216808281

Yes to both

**Comment by digitalentity** [comment]
Scheduling for 1.3 to be done along with #365
