### ISSUE TITLE
SPRacing F3 tricopter and servo tilt

### ISSUE THREAD

**Issue by rtlopez** [iNavFlight/inav#1840]
Hi,

I'm looking for solution to be able to run 2-axis servo gimbal on tricopter. I'm observing development branch too, and in target.c there are only two servo output provided (TIM_USE_MC_SERVO) where I need at least 3. Also I'm not quite understand, why the servo output starts from 7th pin and pins from 4-6 are unused. I believe that there are some reason why it is implemented in that way, but I cannot figure it out now. Do you think it is possible to add support for servo on unused motor pins or use PWM inputs?

Cheers, Lopez.

**Comment by DzikuVx** [comment]
It should be solved by new mixer approach from #2978 where mixer will be easier to configure
