### ISSUE TITLE
Request: Auto Return Home when battery is low

### ISSUE THREAD

**Issue by tonyintn** [iNavFlight/inav#1845]
Not sure how complicated this would be but it would be nice to have the option to auto trigger a return home if the voltage level reaches a predetermined level.
1. Button to turn on feature
2. Detect if the voltage options is used by the FC
3. If in use, allow the use of the auto RTH feature
4. Allow user to set a min voltage allowed.

**Comment by giacomo892** [comment]
See https://github.com/iNavFlight/inav/issues/74 and https://github.com/iNavFlight/inav/issues/1475 and close this.

Thanks

**Comment by tonyintn** [comment]
Ah ok thanks
