### ISSUE TITLE
Question -will enabling magnetometer for fixed wing create any issues?

### ISSUE THREAD

**Issue by thewolfbird** [iNavFlight/inav#1848]
Currently flying without mag for fixed wing, works well, but if I enable mag will this create any issues. 
Anyone flying with mag enabled for fixed wing? is it safe to use?

**Comment by thewolfbird** [comment]
I've purchased the external gps with mag as recommended by inav, does anyone know the correct set align_mag  value
 set align_mag = CW270FLIP seems to work, but a bit slow

**Comment by Redshifft** [comment]
Anytime you can avoid using Mags do so and don't look back. they are without doubt the most troublesome component, why do you want to use it ?

**Comment by thewolfbird** [comment]
Just wanted to see if it works, but from your experiences using the mag, I may not want to now. I have it setup with my quad and it works ok.
