### ISSUE TITLE
Omnibus F3 Pro 

### ISSUE THREAD

**Issue by madoboy** [iNavFlight/inav#1856]
Hi. After flashing Omnibus hex on FC it wont recognise the board anymore. I can flash back Betaflight and connects without issue. Thanks

**Comment by DzikuVx** [comment]
@madoboy without any other data we are not able to help

**Comment by madoboy** [comment]
Hi. What kind of data you need? Happy to help

2017. aug. 9. de. 8:43 ezt írta ("Paweł Spychalski" <
notifications@github.com>):

**Comment by DzikuVx** [comment]
Well, anything. I flashed mine few days ago and everything worked like a charm for example. Do you have anything connected to the board for example?

**Comment by madoboy** [comment]
No. Literally it arrived from Banggood. I plugged in tested connection with
Betaflight then wanted to flash with Inav. It goes to DFU mode and i can
flash it. It writes that finished the verifying. But when it restarts board
only flashes and won't recognise. I can give you afternoon what patern is
flashes. If is helping something. I tested on other comp and with different
cables and drivers.
After this i need to press boot button to go in DFU mode and i can flash
with Betaflight.

2017. aug. 9. de. 9:00 ezt írta ("Paweł Spychalski" <
notifications@github.com>):

**Comment by padcom** [comment]
I also have a problem with this board and iNav. While flashing it won't even go past the erase phase.

**Comment by madoboy** [comment]
Hi Mr.Pawel. I saw your video on YouTube about pitot tube. Can you share
how to connect it. And also this gonna help with RTH and AH modes throttle
management? Are you maybe member of INav Autopilot group on Facebook it has
about 1000 member.

2017. okt. 6. 10:24 ezt írta ("Paweł Spychalski" <notifications@github.com
>):

Closed #1856 <https://github.com/iNavFlight/inav/issues/1856>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/issues/1856#event-1281425368>, or mute
the thread

**Comment by DzikuVx** [comment]
@madoboy https://quadmeup.com/how-to-connect-apm-airspeed-sensor-pitot-tube-to-inav/

Facebook group with 1000 members about INAV? Let me look for it :)

**Comment by madoboy** [comment]
https://www.facebook.com/groups/1309125302467027/

2017. okt. 7. 9:46 ezt írta ("Paweł Spychalski" <notifications@github.com>):

@madoboy <https://github.com/madoboy> https://quadmeup.com/how-to-
connect-apm-airspeed-sensor-pitot-tube-to-inav/

Facebook group with 1000 members about INAV? Let me look for it :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/issues/1856#issuecomment-334920524>,
or mute
the thread

**Comment by madoboy** [comment]
Thanks for the link. I'm using INav on Mini Talon. Now with pitot tube it
gonna help with RTH throttle management?

2017. okt. 7. 9:47 ezt írta ("Stifler Fpv" <mado1326@gmail.com>):

**Comment by DzikuVx** [comment]
Not yet, ATM it is use informative

**Comment by madoboy** [comment]
Thanks for informations. Please join in our group you can have lot's of
inputs and experiences from pilots to help your development.

2017. okt. 7. 9:55 ezt írta ("Paweł Spychalski" <notifications@github.com>):
