### ISSUE TITLE
Altitude calculation and descending problem

### ISSUE THREAD

**Issue by pstryju** [iNavFlight/inav#1857]
Hi. I've got a problem with altitude. Not exactly with hold, because when it's not changing quad remains stable, also there is no problem when it's going up, only when going down. Quad just don't want to lose altitude even with throttle on 0. Or it's going down for some meters, stops and again.
Also I've noticed weird altitude calculation visible on sensors tab.

![aaa](https://user-images.githubusercontent.com/4330162/27773524-cebf69d0-5f7b-11e7-9ece-b31a831a6a9b.png)

I've moved quad about 80cm up and stopped. At the beginning altitude is calculated properly, even baro behaves good, but Alt is going back to even smaller level than was before moving.
I think that acc calculation is proper because fast changes are good, later it drifts despite not drifting baro sensor.

Not attaching settings dump, because it's the same even after reflashing board so settings are default.

Here is blackbox dump when landing during RTH failed (last flight).

[blackbox_log_2017-07-02_215529.TXT](https://github.com/iNavFlight/inav/files/1118103/blackbox_log_2017-07-02_215529.TXT)

F450, 920kv, 30A SimonK, Naze32 Rev6 Full, NZ GPS Ublox-7, 1045 props

**Comment by Ralf-W** [comment]
From the BB-Log your acc(z) values are jumping much too strongly - probably due to vibration problems - at high throttle settings. Since iNAV is calculating altitude by integrating acc(z) over time this results in wrong altitude data.

**Comment by DzikuVx** [comment]
I agree here. To much vibration is causing this kind of problems. Balance propellers and motors, check if nothing is loose or broken

**Comment by digitalentity** [comment]
Yes, most likely vibration issues - accelerometer is very jumpy.

**Comment by DzikuVx** [comment]
@pstryju I'm closing this ticket since it appears that vibrations are your problem. If any new data appears, feel free to reopen
