### ISSUE TITLE
SPRacingF3 Rangefinder HC-SR04 not detected

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#1859]
315925eb59a38144ef915fe33d6d5eb625eef094 HC-SR04 does not work in latest development. Detection returns HARDWARE_UNHEALTHY, trigger pin gives state HIGH, checked with oscilloscope

**Comment by DzikuVx** [comment]
The same, BTW, goes for1.7.1 (not working), checking older versions

**Comment by DzikuVx** [comment]
Works with INAV 1.2.1, 1.3, 1.4, 1.5

**Comment by stronnag** [comment]
Detected for me in INAV 1.6.2 (61426848) SPRACINGF3 as discussed in https://github.com/iNavFlight/inav/pull/1395 (not much use, but detected).

**Comment by DzikuVx** [comment]
OK, it is a Configurator error after all. and some "user error" as well. Never mind :)

iNavFlight/inav-configurator#214
