### ISSUE TITLE
Problem OSD and Smartport at Softserial on a SPRacingF3

### ISSUE THREAD

**Issue by DerDominik** [iNavFlight/inav#1860]
Hi there,

I want to use a MicrominimOSD and the Smartport telemetry at both softserial ports on a SPRacingF3, but I got always "No Data" message on my OSD while both are activated. If a disable telemetry, the OSD is working fine.
Is this a problem with INav and/or the FC? Or is this combination generally not working?

edit:
On my OSD I tried also to set activate following settings:
#define BAUDRATE 9600
#define MSP_SPEED_LOW
#define FORCE_MSP

**Comment by DzikuVx** [comment]
I can confirm that MSP and SmartPort do not work together on SoftSerials here. Softserials should be used as last resort.
You might want to switch MinimOSD to LTM protocol, that might help.

**Comment by DerDominik** [comment]
Thanks for your help, I'll try later.
Only change the setting in the MicrominimOSD?
Or do I've to change something else in iNav?

**Comment by DzikuVx** [comment]
You have to configure MW OSD to use LTM and set LTM as telemetry on that SoftSerial
