### ISSUE TITLE
Help / Question: Dual Receiver Mode? Both via MSP port and Transmitter / Receiver (Edited)

### ISSUE THREAD

**Issue by johnsilvester** [iNavFlight/inav#1866]
I was wondering if it was possible to have two receivers connected to an SPF3 at the same.
I wanted to make an iPhone app controller controller via bluetooth and MSP but also have the ability to still use a regular transmitter like a FlySky. is this possible? Thanks!!

**Comment by giacomo892** [comment]
Yes. When MSP data stop to be received it will jump to standard radio otherwise it will switch to failsafe

**Comment by johnsilvester** [comment]
Thank you for the response! But I cannot get both PPM / PWM to work along side MSP due in the Configuration Tab under 'Receiver Mode', you have to select either 'PPM RX Input' , 'PWM RX Input', or 'MSP RX Input'.  Is there any way to select both?
