### ISSUE TITLE
Not sure if bug: FAILSAFE "land" not descending when ALTHOLD is active.

### ISSUE THREAD

**Issue by darmach** [iNavFlight/inav#1872]
Few days ago I experienced what I'd consider a bug in failsafe behaviour. Not sure if it's relevant in light of https://github.com/iNavFlight/inav/issues/1475

I recently installed iNav, was testing ALTHOLD/POSHOLD. It was holding and then decided to test manually enabled (aux switch) FAILSAFE - configured to lower throttle and "land". Quad started beeping as expected, but did not descend. After configured 15 seconds for land elapsed, quad disarmed mid-air, falling.

Looks like enabled ALTHOLD stopped failsafe semi-land from descending. Shouldn't failsafe procedure be executed no matter what other mode is active? In this case I was low, and over a empty field, could've been worse.

I can replicate and attach logs if necessary.

**Comment by digitalentity** [comment]
@darmach thanks for reporting. This bug indeed needs to be fixed ASAP.

**Comment by Manawyrm** [comment]
@digitalentity: Can confirm, a friend had his copter falling out of the sky while testing failsafe in this exact configuration. 

./main/navigation/navigation.c:void activateForcedRTH(void) is responsible for this functionality. fallback RTH is the only place this method gets called. 

Something like
  
```
DISABLE_FLIGHT_MODE(NAV_ALTHOLD_MODE | NAV_POSHOLD_MODE | NAV_WP_MODE | NAV_LAUNCH_MODE);
ENABLE_FLIGHT_MODE(NAV_RTH_MODE);
```
at the top of this function should force the correct mode, right? I will test this and create a pull request.

**Comment by digitalentity** [comment]
@Manawyrm @darmach please attach your configurations.

@Manawyrm it's more complicated than that. Navigation is handled via a state machine, not flight mode flags. Likely cause of the bug is handling the failsafe condition.

**Comment by digitalentity** [comment]
Found the problem. Failsafe didn't override navigation system (PosHold/AltHold/RTH/WP) modes. This caused a bug when failsafe was applying control input for an open-loop landing, but AltHold was overriding it later in the code. 

Fix pending.

**Comment by digitalentity** [comment]
Guys, please test https://github.com/iNavFlight/inav/pull/1873, failsafe LAND and DROP should now bypass AltHold and other navigation modes.

**Comment by giacomo892** [comment]
Is this only referring to ones that set LAND/DROP action as failsafe?

I tested failsafe many times, having setted it as RTH, and always landed (and disarmed) the machine even if it was ALT+POS HOLD previously.

**Comment by digitalentity** [comment]
@giacomo892 yes, only LAND/DROP procedure is affected by the bug. RTH requires navigation subsystem and therefore is not affected by the bug at all.

**Comment by darmach** [comment]
Should this issue still exist in 1.7.3? (I am aware that 1.8 is already out)

**Comment by stronnag** [comment]
Am I losing my sanity .... 
````
grep -r --include \*.c bypassNavigation .
# nothing
````

**Comment by digitalentity** [comment]
@stronnag at which version of INAV did we have "bypassNavigation" ?

**Comment by digitalentity** [comment]
@stronnag I must be insane as well. How come #1873 was not merged?
