### ISSUE TITLE
Feature Request: Rate/Angle hybrid mode

### ISSUE THREAD

**Issue by heathicus** [iNavFlight/inav#1876]
While training my young daughter to fly her drone FPV, I thought of a good feature that would be helpful.  I don't want to start her off with Angle mode and the bad habits that starts, but Acro is a little rough.  But if there was a mode that behaved just like Acro (no auto leveling) except limited the angle the craft could be in, like Angle mode, that would help significantly.

**Comment by oleost** [comment]
Unsure what's going to happen with angle mode with angle p gain set to zero?

**Comment by DzikuVx** [comment]
@oleost that would not work.
@heathicus I actually like the idea, since I also want to teach my daughter to fly :)

**Comment by Redshifft** [comment]
@heathicus  you are assuming the younger faster uncluttered brain will struggle, just soften it up a bit and go find some soft grass :D
