### ISSUE TITLE
 IBUS only 6 chanels.

### ISSUE THREAD

**Issue by straga** [iNavFlight/inav#188]
ibus show only 6 chanel, but RX and TX have 10 chanels

**Comment by DzikuVx** [comment]
@straga accoring to code, iNav should support 8 channels over iBus. Which radio are you using?

**Comment by DzikuVx** [comment]
@straga I've ported 10CH iBus from cleanflight in #189 
I do not own any iBus radio ATM, so maybe you could test it? What FC board are you using so I can build you a version

**Comment by straga** [comment]
Turnigy TGY-i10 - Cleanflight and Betaflight - work correctly.

**Comment by DzikuVx** [comment]
@straga I will build a version that should work, but I need to know which board you are using.
SPRacingF3, Naze, CC3D? Smth lese?

**Comment by straga** [comment]
I compiled myself, now works all the 10 channels.

**Comment by DzikuVx** [comment]
Superb! Thank you for finding that
