### ISSUE TITLE
how to join this source code work?

### ISSUE THREAD

**Issue by LuctenFinger** [iNavFlight/inav#1886]
I m a sophomore of Computer Science and i m very interest in code working.  I want to make my own firmware for my FC !
  I know program language C and python.  but the problem is where to start?
  Should I read any book or video? or just read the source code ?
 any recommend?

**Comment by DzikuVx** [comment]
@LuctenFinger here is a documentation how to setup working environment: https://github.com/iNavFlight/inav/tree/master/docs/development

You have to fork this repository and propose pull requests with your changes.

**Comment by LuctenFinger** [comment]
thx !
