### ISSUE TITLE
New failsafe procedure

### ISSUE THREAD

**Issue by hali9** [iNavFlight/inav#1887]
In failsafe.md is written:
"If any required navigation sensor becomes unavailable during a Return to Home (eg. loss of GPS fix), an emergency landing similar to SET-THR but with barometer support will be performed after a short timeout. An emergency landing would also be performed right when the failsafe is triggered if any required sensor is reported as unavailable."
Is it possible to add an "emergency landing" as a failsafe option ?
And second failsafe option "emergency landing with poshold" (just like landing after RTH procedure).
I currently use SET-THR, but there are problems:
when I fly high propellers can stop before landing
when I fly low propellers spin on ground more time
I cannot use RTH as failsafe because there are high trees around.
Ideally, if the excavator landed in a controlled manner where it is and the propellers stop or disarm.

**Comment by ShawnzAZ** [comment]
Or maybe a pre defined RTH with landing mission could be executed in the case of failsafe?
