### ISSUE TITLE
acc calibrate problem

### ISSUE THREAD

**Issue by enrique15241524** [iNavFlight/inav#190]
hi;
i did load inav 1.1 c3
but it is not acc calibrate..
after calibrate values:
pitch=-1.3
roll = 0

regards
Murat

![acc_calib](https://cloud.githubusercontent.com/assets/18192626/15099320/dfaef574-155a-11e6-84fa-e9bedb391595.png)

**Comment by skaman82** [comment]
Have you read this? https://github.com/iNavFlight/inav/wiki/Advanced-accelerometer-calibration

**Comment by enrique15241524** [comment]
thanks skaman :)
my bad english :)

i applied this steps and values:
is normal?

![acc_calib](https://cloud.githubusercontent.com/assets/18192626/15099582/db3b173c-1561-11e6-8a47-2a16d2bf6d5d.png)

**Comment by sppnk** [comment]
please check this : #187

**Comment by skaman82** [comment]
@enrique15241524 yes, a small offset after calibration is normal. You can tune the small offset in the configuration tab in this area: 
<img width="201" alt="bildschirmfoto 2016-05-08 um 21 58 43" src="https://cloud.githubusercontent.com/assets/11768024/15100069/0f3b6bda-1568-11e6-8960-3f0f7a2a5851.png">

**Comment by enrique15241524** [comment]
Thanks for all help... 
i will try tomorrow 
so do not close the topic...

Regards....

**Comment by theArchLadder** [comment]
I think this shows that this is not user friendly, i think most people expect the acc calibration to also do a level calibration. Not sure why this is not done... @digitalentity?

**Comment by digitalentity** [comment]
@theArchLadder two reasons:
1) Calibration means only that sensor chip is providing consistent and sane data. With compass calibration doesn't mean you'll have your heading right - you need to adjust magnetic declination. Accel is alike - calibration doesn't mean it will read level correctly, it only means it will measure acceleration and gravity correctly.
2) We will have better calibration procedures - compass, accelerometer, level calibration in new Configurator (hopefully this will happen shortly after 1.1 release)

**Comment by oleost** [comment]
@digitalentity I understand what your saying.

But isn't it possible that when doing the 1. posision of the accelelrometer process it also adjust "align_board_pitch" and "align_board_roll" so it will say its leveled?

**Comment by digitalentity** [comment]
@oleost 1-st position isn't necessary level, it has margin of ~15 degrees. The 6-point calibration is designed in such way that it doen't require 6 points to be strictly 90 deg apart it has rather big margin. I would rather implement a "Calibrate level" button in Configurator.

**Comment by oleost** [comment]
@digitalentity Sounds good.

**Comment by enrique15241524** [comment]
Thanks i solved to problem..... very stable....

Regards
Murat
