### ISSUE TITLE
Board - Naze rev6 support

### ISSUE THREAD

**Issue by xalex88** [iNavFlight/inav#192]
Hello,
sorry in advance for my English. :-)
When supported INAV the NAZE32 rev6?

Best regards

**Comment by digitalentity** [comment]
Naze32 rev6 is supported by NAZE target.

**Comment by xalex88** [comment]
however, I can find gps fixed nobody. with cleanflight already

**Comment by digitalentity** [comment]
Can you explain more, what's the issue about?

**Comment by xalex88** [comment]
i didnt have GPS with INAV.
With Clmeanflight i have 7 Sat's
<img width="958" alt="bildschirmfoto 2016-05-09 um 18 04 26" src="https://cloud.githubusercontent.com/assets/19264417/15119327/ac6d2b5c-1610-11e6-865a-e81d52c204e9.png">

**Comment by DzikuVx** [comment]
@xalex88  iNav does no longer reports each individual sat in Cleanflight Configurator.
Instead, it reports there only HDOP value. Let GPS lay little longer to get the fix and you will notice value 99 drops down as fix quality increases.
Or you can use [iNav Configurator](https://github.com/iNavFlight/inav-configurator) instead

**Comment by digitalentity** [comment]
Not an firmware issue. Closing.
