### ISSUE TITLE
RunCam Split control via serial port

### ISSUE THREAD

**Issue by marekrewers** [iNavFlight/inav#1921]
Is it possible to cherry-pick this feature from cleanflight?
This enables full control of Runcam Split from the radio, 
for example you could auto-start recording when armed.

https://github.com/cleanflight/cleanflight/pull/2852

**Comment by digitalentity** [comment]
Good idea, but we'll have to extend usable box modes field to 64-bits, otherwise we won't be able to add required modes.

**Comment by tgreer** [comment]
I've got an Omnibus F4 Pro V3 in my craft with a split, happy to do any testing on a PR.

**Comment by fiam** [comment]
Isn't this fixed by https://github.com/iNavFlight/inav/pull/1977 ?

**Comment by digitalentity** [comment]
@fiam thanks for pointing this out. Closing!
