### ISSUE TITLE
LED Strip not working on target OMNIBUS

### ISSUE THREAD

**Issue by wizardrnd** [iNavFlight/inav#1922]
LED Strip is not working on iNAV 1.7.2 target OMNIBUS. 
Feature LED_STRIP is on and configured. 
With previous iNAV 1.7.1 LED Strip is working correctly.

**Comment by DzikuVx** [comment]
@digitalentity looks like timer issue

**Comment by digitalentity** [comment]
@wizardrnd @DzikuVx yes, looks like timer issue. I don't have any Omnibus F3 boards on me now, will try to fix this blind :smile:

**Comment by digitalentity** [comment]
Fixed
