### ISSUE TITLE
SP RACING F3 HEX6X mixer not working in iNAV 1.7.2

### ISSUE THREAD

**Issue by jstremmler** [iNavFlight/inav#1928]
Just upgraded a hexacopter from iNav 1.6.1 to 1.7.2. FC is a SPRACINGF3.

When I specify the mixer as a Hex X in the configuration menue it returns after rebooting to a QuadX mixer.

 Same happens, when I key in in the CLI menue: MIXER HEX6X and SAVE. It returns to a QUADX mixer.

Is there any solution or do I have to operate with a custom mixer?

**Comment by KiwiDavid** [comment]
This is a radial 6 motor and not a hex Y?

**Comment by jstremmler** [comment]
No it is not a Y6 but  a normal radial X hexacopter with 600mm diameter.So the CLI command is correct. Pls type in the CLI menu : "mixer list" to see all valid mixer commands! 
For a Hex X multicopter the correct command is: MIXER  HEX6X and then save, but it returns always to a QuadX mixer.

**Comment by jstremmler** [comment]
Will try a custom mixer today with:

mixer custom
mmix reset
mmix 0 1.0 -0.50  0.866  1.0
mmix 1 1.0 -0.50 -0.866  1.0
mmix 2 1.0  0.50  0.866 -1.0
mmix 3 1.0  0.50 -0.866 -1.0
mmix 4 1.0  -1.0 -0.0   -1.0
mmix 5 1.0   1.0  0.0    1.0

**Comment by digitalentity** [comment]
Fix ready, closing

**Comment by dimak771** [comment]
Hello!
I have iNav 1.7.3 on CC3D Atom. I can`t use custom HEX6X in CLI:
_______________________
mmix 4 1.0 -1.0 -0.0 -1.0
index must be between 0 and 3
_______________________
Can I configure HEX6X on 1.7?

**Comment by stronnag** [comment]
https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20CC3D.md
