### ISSUE TITLE
alt hold

### ISSUE THREAD

**Issue by mueller2030** [iNavFlight/inav#1930]
hello, the other day i was letting my son fly my s800. i put alt hold on and he could fly left and right. it worked great except the wing would not try to recover altitude when it lost some in turns. so the alt hold was more of a pitch lock in my opinion.  i would have assumed the wing would try to recover the alt it had lost.
reptile s800 
sp racing fc 
v1.7.1

**Comment by digitalentity** [comment]
On a plane moving the pitch stick in AltHold mode equals command to change altitude. When flying in altitude hold mode you should only use roll (and yaw).
