### ISSUE TITLE
iNav doesn't work on BlueJayF4

### ISSUE THREAD

**Issue by andrejpodzimek** [iNavFlight/inav#1931]
Flashing my BlueJayF4 revision 3 with iNav (1.7.2) makes it unusable and one has to use the boot button to reflash it (back to Betaflight). It doesn't respond on the USB port (i.e., there's no `/dev/ttyACM0` appearing upon connection). When I connect battery power, it beeps in a way [not listed here](https://github.com/iNavFlight/inav/blob/master/docs/Buzzer.md): 5 short beeps are followed by two long beeps and this sequence repeats indefinitely. No ESC beeps occur.

**Comment by andrejpodzimek** [comment]
1.6.1 has the same issue.

**Comment by digitalentity** [comment]
@andrejpodzimek this beep sequence indicate not detected gyro. If it works in Betaflight - we have an issue with drivers for that board in INAV. Can you post Betaflight's `status` output here?

**Comment by andrejpodzimek** [comment]
Yes, it works and flies with Betaflight 3.1.7 as well as Git master (3.2). Here's a status from 3.2:

    # status
    System Uptime: 161 seconds
    Voltage: 166 * 0.1V (4S battery - OK)
    CPU Clock=168MHz, GYRO=ICM20608G, ACC=ICM20608
    SD card: Startup failed
    Stack size: 2048, Stack address: 0x10010000
    I2C Errors: 0, config size: 1918, max available config: 16384
    CPU:66%, cycle time: 37, GYRO rate: 27027, RX rate: 111, System rate: 9
    Arming disable flags: CMS

The reason why I wanted to test iNav was because [my compass and baro don't work](https://github.com/betaflight/betaflight/issues/3605#issuecomment-317259612) in Betaflight. However, iNav always brings the FC to a state in which only the boot button can help. I tried to port some of the iNav-specific changes to `target.h` and `target.mk` into Betaflight (to get compass support), but to no avail. That's why I'd like to try iNav.

**Comment by andrejpodzimek** [comment]
[Here's more info about the aircraft](https://www.rcgroups.com/forums/showthread.php?2593106-BlueJayF4-STM32F4-based-FC/page68#post38017641) that doesn't work with iNav. (But I also tried to flash a bare FC with nothing else connected and it was failing the same way.)

EDIT: And here’s a new [status with compass, baro, telemetry and GPS working](https://www.rcgroups.com/forums/showthread.php?2593106-BlueJayF4-STM32F4-based-FC/page70#post38028235) in Betaflight.

**Comment by digitalentity** [comment]
Ok, this is certainly an issue with drivers for ICM gyro in INAV on that target. Will look into it.

**Comment by digitalentity** [comment]
@andrejpodzimek can you try attached hex?
[inav_1.7.3_BLUEJAYF4.zip](https://github.com/iNavFlight/inav/files/1203836/inav_1.7.3_BLUEJAYF4.zip)

ICM20608 gyro is supported by generic MPU6500 driver in INAV, but our current BlueJayF4 target was built without it.

**Comment by andrejpodzimek** [comment]
Neat, that works and boots, at the first glance. So the blocking gyro issue is fixed. \o/

Sadly there's a glitch that causes the configurator and/or the board to get blocked each time the battery is connected (in the "waiting for data" screen). Disconnecting and reconnecting the USB won't help; one has to disconnect both the USB and battery and then reconnect the board. This prevents me from testing the receiver and GPS properly.

My sensors appear to get recognized, just GPS is sort of weird and remains red.
![image](https://user-images.githubusercontent.com/947737/29195262-d8689468-7e2d-11e7-8630-da9f0d834a05.png) Well, considering that I [have a faulty GPS](https://github.com/betaflight/betaflight/issues/3777#issuecomment-320618894), that's probably not a big deal. I'll retry this once I get a new and better one. But I think the device is not recognized at all; unlike Betaflight, iNav doesn't seem to have a pull-down menu in Ports that would say on which port the GPS is (UART3).

One thing I noticed immediately: No DShot in the motor settings. Is DShot disabled because of timer mappings ([recently resolved in Betaflight](https://www.rcgroups.com/forums/showthread.php?2593106-BlueJayF4-STM32F4-based-FC/page69#post38018598) for hexacopters) or is it not supported at all?

Also, attempts to restore my settings from Betaflight have been an "ooops" moment, because most of them have different names. But that's likely because this is forked from Cleanflight, not Betaflight.

The 1kHz maximum loop frequencies are a bit of a culture shock. In Betaflight I use 16/16 kHz, because why not. :-) The purpose of this aircraft is to do 10+ aggressive flips and park on GPS in 200 meters of altitude 1 minute later. Just for fun, "because we can". That's why I'm exploring all possible options.

**Comment by digitalentity** [comment]
@andrejpodzimek 
DShot is not supported in INAV on any boards because of added issues without much real benefit.

Different names - you have to read the manual to convert settings. INAV supports much more than racing quads - most settings are named to avoid confusion.

1kHz maximum loop time - it depends on what you want. If you want GPS with I2C compass and baro working - 1kHz is as much as you are going to get due to limited speed of I2C bus. 16kHz is neither possible nor useful on a GPS/compass equipped machine. If you disable compass and baro you can probably get 8kHz but what/s the point.

Board hanging up - not sure what's causing it. Other F4 boards don't exhibit such behavior.

**Comment by andrejpodzimek** [comment]
16 kHz with compass, GPS and baro is both possible and useful in Betaflight. [Here’s a status](https://www.rcgroups.com/forums/showpost.php?p=38028235&postcount=1039) with compass, baro, GPS **and** 16kHz/16kHz gyro and PID loop rates.

This of course doesn’t mean that all the sensors (especially I2C ones) can be updated in every single loop iteration. Gyro (on SPI) is the most important sensor that can do high-speed updates. Easier tuning and better responsiveness / propwash resilience is the key point. Other sensors are not that vital for flight performance and “stick feel”, but it’s good to have them on board — motivation stems e.g. from teaching other people to fly, from the comfort and versatility of just “parking” the drone in the air for a while and playing with its RunCam Split etc. So, that’s the point — having a drone with racer-like performance, but also with GPS, compass and baro. (That’s also where DShot would have a benefit.)

Although Betaflight supports all the sensors and high (gyro <-> PID) loop frequencies, [glitches like this one](https://github.com/betaflight/betaflight/issues/3823) are making many sensors … less useful, to say the least. That’s why I was curious about iNav — people use it successfully even for autonomous flights, so I guess it must have solved this issue somehow. Yet the altitude PID settings seem to be the same as in Betaflight.

The board freeze occurs whenever I have the board on USB and connect the battery. This prevents me from checking the receiver settings. Connecting or disconnecting the battery in Betaflight doesn’t cause a freeze. Is there a way to get debugging information from the configurator? It actually looks like the board works to some extent, just the MSP communication breaks.

**Comment by digitalentity** [comment]
At 16khz one iteration is just 62.5us. Reading from I2C compass alone at 400khz speed takes 160us. We'll have to skip 3 (three) gyro updates to read one compass iteration. Betaflight is doing precisely that - skipping gyro and PID iterations. As long as you are flying ACRO - you don't even notice these microsecond glitches, however when you will try to do something more advanced than just stabilizing angular rates - things will start to get messy.

In INAV scope unstable gyro reads/cycle times will lead to inaccurate IMU operation (frequently referred to as "horizon drift") which in turn will cause less accurate navigation or total failure to maintain attitude and navigate.

So, what would you chose - 16khz loop time (which you will barely feel) or stable ANGLE mode and navigation (which is affecting user much more).

**Comment by digitalentity** [comment]
To further debug the board freezing I'll probably need hardware. It's impossible to debug remotely. Maybe you can reach out to board manufacturer and convince them to send me a sample to troubleshoot with?

**Comment by andrejpodzimek** [comment]
I haven’t delved into the code to double-check, but don’t think Betaflight synchronously waits for I2C. One of the differences of Betaflight (from Cleanflight) are numerous asynchronous operations outside the main PID loop. (Some ESC protocols require that.) Status reports a cycle time of 66 microseconds, which is well above 15 kHz. Also, the reported CPU load grows with growing PID and gyro frequency and is almost the same with or without the I2C sensors enabled. If Betaflight had to wait for I2C synchronously, I think this wouldn’t be the case and I’d see a constant CPU load for any cycle frequency setting above ~4 kHz.

I’m not exactly sure who the board manufacturer is; got it from Helipal. Yet another option would be to give up on this F4 board and connect one of the F7 boards that I’ve just got.

**Comment by digitalentity** [comment]
@andrejpodzimek I2C reads are blocking in Betaflight https://github.com/betaflight/betaflight/blob/master/src/main/drivers/bus_i2c_busdev.c#L34-L37
https://github.com/betaflight/betaflight/blob/master/src/main/drivers/bus_i2c_stm32f10x.c#L208

The reason you don't see 4kHz loop is because baro is read at relatively low rate (c. 100Hz). This means that your PID loop is 16kHz, but 100 times a second there's a 160us delay.

There are absolutely no asunchronous operations regarding PID loop, even if gyro is read in the interrupt handler at 16kHz PID is unable to consume the reading if it's blocked by baro read task.

**Comment by andrejpodzimek** [comment]
I see. Thanks for looking it up. So the ancient discussion about using an RTOS-type library probably didn’t materialize. But in spite of the 160us glitches,  the racer-like settings work just fine for me in Betaflight.

BTW, [if this is the original manufacturer](https://bluejayrc.com/), they explicitly advertise iNav support. But [what I bought](http://www.helipal.com/flymaster-fmf405-f4-flight-controller-bluejayf4.html) is a clone of some sort. The layout looks exactly like a BlueJayF4 revision 3, but in fact it didn’t even boot in iNav without the gyro fix. So I’d love to reach out to the manufacturer and ask them to send you a specimen for debugging. It should be in their best interest to get this fixed. But [their website](http://fly-master.com/) is not exactly informative. :-(

This looks like the same old and sad story again. I’d rather pay $100 for the supported original than $50 for a clone with all the hassle. But the former was just nowhere to be found.
