### ISSUE TITLE
OSD not showing "mph" label for GPS speed if using imperial units

### ISSUE THREAD

**Issue by Nihilistic** [iNavFlight/inav#1933]
The crosshair blinks on and off for me on the OSD with iNAV 1.7.2 loaded on my Omnibus F3 V3 with BEC.

Also, there is no "mph" label for the GPS speed when Imperial units is selected.

**Comment by DzikuVx** [comment]
Freshly tested on Omnibus F4 v2 Pro and I confirm issue is there. Crosshair is blinking when AHI is enabled.
@marbalon I suspect this is connected with OSD refreshes. Looks like crosshair has to be rendered always after AHI

**Comment by digitalentity** [comment]
Crosshair issue fixed. As for mph label - we lack the symbol in the font.

**Comment by Nihilistic** [comment]
Sweet! So the crosshair fix appears in 1.7.3? Or 1.8?

**Comment by digitalentity** [comment]
@Nihilistic crosshair fix will be included in next release. I'm not sure if it's going to be 1.7.3 or 1.8 yet. If we have new MSP stuff merged - probably 1.8

**Comment by fiam** [comment]
@digitalentity Can you assign me this one? I'd like to get some OSD improvements done after #2019 is merged.

**Comment by fiam** [comment]
This should have been automatically fixed when #2048 was merged. Can someone mark it as fixed manually?
