### ISSUE TITLE
iNav 1.7.2 ANYF7 with external Baro.

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#1937]
Using ANYFCF7_EXTERNAL_BARO, an external MS5611 baro is not detected.
Monitoring the external bus, as far as I can see, firmware never polls the external bus for a baro (but I could be wrong).
Is there something I am missing to make the standard release automatically detect an external baro?

FYI:
Looking at target.h in  ANYFCF7_EXTERNAL_BARO, I can see the ifdef that should enable the external bus for a baro.
Replacing that with the following works perfectly (although only for this specific hardware set up).

#define BARO
#define USE_BARO_MS5611
#define BARO_I2C_INSTANCE I2C_DEVICE_EXT

**Comment by Gavsv8** [comment]
Have you got the other pins wired to select the correct address, CSB=low  and I2C mode PS high and have pull-up resistors in circuit?

![img_1247](https://user-images.githubusercontent.com/20474604/28671345-eab7d7f2-730e-11e7-95f7-b5a32c32e50e.PNG)

**Comment by DzikuVx** [comment]
@flyfisher2 I'm not following your logic here. Are you sure that you used and/or compiled `ANYFCF7_EXTERNAL_BARO` target, not generic `ANYFCF7` target?

**Comment by ghost** [comment]
Thanks for the responses.
Sorry I did not make myself clear .The standard hex worked fine but I self compiled 1.7.2 to move the buzzer to output 8 on the bg pro version and that was the problem.
It looks like I must have used the wrong target as everything is now good.
Very embarrassed.

**Comment by DzikuVx** [comment]
No problem, good that it worked in the end
