### ISSUE TITLE
INAV - AnyFC7 upload not working

### ISSUE THREAD

**Issue by ThomasH3** [iNavFlight/inav#1942]
Hi

When I try to Flash INAV on my ANFC f7 Pro the tool is freezing during erase.
Betaflight and cleanflight are working.

**Comment by ghost** [comment]
untick FULL CHIP ERASE.
Should now work.

**Comment by ThomasH3** [comment]
unfortunately, it doesn't work

**Comment by DzikuVx** [comment]
@ThomasH3 which version of Configurator do you have?

**Comment by ThomasH3** [comment]
Version 1.7.2
I was able to flash it. but Firmware will not start after reboot .... the connection closes after 10 sec

**Comment by DzikuVx** [comment]
I just flashed AnyFC F7 Pro from BG with INAV 1.7.2 and no problems detected. Are you sure you are using latest C
![anyfc f7](https://user-images.githubusercontent.com/966811/28743078-216b0f2a-7441-11e7-9539-159e30902eae.png)
onfigurator?
![img_20170729_093048](https://user-images.githubusercontent.com/966811/28743079-27bdcbba-7441-11e7-88fe-1dc487a103d4.jpg)

Could you try flashing the board using different PC?

**Comment by ThomasH3** [comment]
After I disconnected my external GPS and compass, INAV is working now, however GPS, I2C (compass) and voltage sensor is not.

**Comment by digitalentity** [comment]
@ThomasH3 you have GPS connected to UART1? This explains alot.

Built-in bootloader in DFU mode listens to activity on USB or UART1 (whichever happens first). GPS is sending data all the time, so bootloader switches to UART1 and listens to upload there.

**Comment by ThomasH3** [comment]
I used TX/RX 7.

**Comment by DzikuVx** [comment]
Flashed AnyFCF7 with 1.7.3 and 1.7.4 without any problems few days ago. Closing
