### ISSUE TITLE
LED is not working after removing to S5 ( resource A15 )

### ISSUE THREAD

**Issue by fred-chen** [iNavFlight/inav#1943]
Following is the thread that I've posted in RCGroups https://www.rcgroups.com/forums/showthread.php?2912273-Matek-Flight-Controller-F405-AIO/page7#post37981481. 

As asked, now filing an issue as a reminder.

I've downloaded and installed the iNav inav_1.7.3_MATEKF405_483a42a3.hex and installed onto my MATEK F405-OSD AIO board. It managed to recognize all my devices and seemed working fine ( gyro, acc, gps, baro, mag all responded to movements ).

The only thing that doesn't work, is the led. I connected led stripe to the led out pad, then enabled led stripe in 'configuration', then it started to beep rapidly. I assume that means some error. 

So I researched and found your post here saying "I2C requires that the WS2812 led strip is moved to pad S5 / pin PA15 (motor 5), thus WS2812 is probably only usable on quadcopters.". So I just simply moved my led stripe's DIN wire to S5 pad, but it won't work ( all lights out ).

* So does that mean I need to solder the led stripe's signal pin ( the DIN ) to S5?
* And do I need to remap the LED resource to S5 and how can I do that in CLI?

Following is my current resource map. Hope I can eventually get my led to work. Thanks a lot!
# resource 
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: FREE 
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR6 OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: LED2 OUT
A15: LED STRIP OUT
B00: FREE 
B01: FREE 
B02: FREE 
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: LED1 OUT
B10: OSD CS
B11: FREE 
B12: FREE 
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE 
C01: SDCARD CS
C02: MPU CS
C03: MPU EXTI
C04: ADC CH2
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR3 OUT
C09: MOTOR4 OUT
C10: FREE 
C11: FREE 
C12: SERIAL5 UART TX
C13: BEEPER OUT
C14: FREE 
C15: FREE 
D02: SERIAL5 UART RX

**Comment by digitalentity** [comment]
@fred-chen please test #1954 - there was a bug introduced when moving ledstrip to PA15.
