### ISSUE TITLE
Auto re-arm after landing

### ISSUE THREAD

**Issue by wizardrnd** [iNavFlight/inav#1971]
Omnibus F3, nav_disarm_on_landing is ON, motor_stop is OFF, arming by ARM mode (not by stick),
If the throttle position above minimum, auto-disarm after landing work correctly. But if the throttle position is minimum - FC immediately do re-arm, since "arm switch is on and throttle position is minimum". If the drone landing with throttle above minimum, successfully auto-disarm after landing and then I down throttle  to minimum - FC also do auto-arm.
This behavior is unsafe, so I suggest checking out not simply state of the ARM, but remember ARM state in previous loop - and if last_arm_state is OFF and current_arm_state is ON, then ARM state is switch ON.

**Comment by digitalentity** [comment]
Fixed in 1.7.3
