### ISSUE TITLE
ANYFCF7 LED strip not working in 1.7.2

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#1975]
LED strip worked in previous versions but not in 1.7.2

**Comment by ahfynjj** [comment]
I have also encountered this problem with ANYFCF7

**Comment by ghost** [comment]
Thanks, that confirms that I don't have a hardware problem.

**Comment by digitalentity** [comment]
@flyfisher2 @ahfynjj did you check latest defelopment firmware?

**Comment by ghost** [comment]
No, I only quickly tested the official release before flying to Scotland.
I will be away from home until the end of October, so unfortunately will not be able to do any more testing until then.

**Comment by ahfynjj** [comment]
Latest development firmware? I do not know where to download？

**Comment by digitalentity** [comment]
Try this one:
[inav_1.7.3_ANYFCF7.zip](https://github.com/iNavFlight/inav/files/1236967/inav_1.7.3_ANYFCF7.zip)

**Comment by ahfynjj** [comment]
THS！
This firmware（1.7.3） still can not drive the LED。
I tried the firmware of 1.7.0 can be used normally

**Comment by sambas** [comment]
compare constants missing from HAL implementation.
    BIT_COMPARE_1 = 97;
    BIT_COMPARE_0 = 38;

e: had wrong timing originally for high bit

**Comment by stronnag** [comment]
While we're here, is this significant (gcc 7 catch):
````
./src/main/drivers/light_ws2811strip.c: In function 'ws2811LedStripInit':
./src/main/drivers/light_ws2811strip.c:93:5: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
     memset(&ledStripDMABuffer, 0, WS2811_DMA_BUFFER_SIZE);
     ^~~~~~
````
ledStripDMABuffer being uint32_t (vice uint8_t) on F4 / F7 ?

**Comment by capblack** [comment]
Hi , also Motor #9 output as buzzer output , is not work

**Comment by digitalentity** [comment]
@sambas can you verify if this is still relevant?

**Comment by sambas** [comment]
fixed in https://github.com/iNavFlight/inav/pull/2057
