### ISSUE TITLE
cannot enable notch filter

### ISSUE THREAD

**Issue by Woojin-Crive** [iNavFlight/inav#1982]
i am using the flip32 board. 10dof version. This board uses naze32 firmware. regardless of the firmware version, i cannot modify the notch filter value. when i change the default value 0,1(freq, cut off) to something like (400,300)and save, if i press the refresh the value goes back to defaults. other pid values are able to modify.

**Comment by digitalentity** [comment]
Notch filter is not supported on NAZE target due to flash memory and CPU power limits.

**Comment by Woojin-Crive** [comment]
aha.. thanks..
