### ISSUE TITLE
Board hungs on boot when I2C devices are disconnected

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#1987]
1. Configure external I2C devices (baro/mag)
1. Disconnect power from those devices
1. Reboot
1. Board (F7 and F3 but will have to verify) hangs and is not accepting connections over MSP

**Comment by digitalentity** [comment]
Can't be helped. Unpowered device is holding the SCL/SDA low which is interpreted by FC as "bus busy".
