### ISSUE TITLE
GPS fix indication via LED Strip

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#199]
https://github.com/cleanflight/cleanflight/pull/2101

**Comment by skaman82** [comment]
The blink feature is also great for position lights.

**Comment by DzikuVx** [comment]
@skaman82 https://github.com/DzikuVx/rc_lights_controller

**Comment by Linjieqiang** [comment]
This is necessary , because I can know the status of GPS in time without GCS ,.Hope that soon merged into the master branch.Thanks your work,
