### ISSUE TITLE
Fixedwing Failsafe stuck with motor spinning

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1991]
Full cli dump https://pastebin.com/G6KBLnnn
https://youtu.be/jpONlr_NJME

With an fixedwing and configured for RTH without GPS this happens. It just keeps motor spinner forever it seems like.

Also I think I have seen the same if you have an fixedwing with GPS but example your have not taken of yet so your don't have a valid heading. Guessing it also maybe make some trouble with an gps equipped fixedwing configured for RTH, but has armed before homepoint is set.

If blackbox is needed I can record it.

**Comment by digitalentity** [comment]
This is how failsafe behaves. It blocks MOTOR_STOP and keeps motor spinning regardless.
