### ISSUE TITLE
GPS - Modify GPS so it provides MSL altitude in cm

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#20]
Current GPS code provides altitude in meters, insufficient for good altitude hold, NMEA is capable of 10cm resolution, should use all available precission.

**Comment by csurf** [comment]
@digitalentity, I'm confused, is the CF code currently using cm, 10*cm, or meters in its calculations?

**Comment by digitalentity** [comment]
@csurf, I was confised as well. Most of the code uses cm, however gps.c sets GPS_altitude to meters. Similar thing for angles: imu calculated RPY angles in 0.1 degrees, however legacy navigation code (and my code as well) uses 0.01 degrees. I might think about fixing that in future.

**Comment by csurf** [comment]
so, will there be any problems with the recent issue/code change with defining NAV_RTH_ALTITUDE to use cm? I'm still not sure what type of units the nav code is using, need to know this before I try to flight test. please advise...

**Comment by digitalentity** [comment]
I designed nav-rewrite code is using cm for distances everywhere, except for `distanceToHome` variable (calculated in meters for compatibility with the rest of the code)

**Comment by digitalentity** [comment]
I figure there is already an issue for GPS altitude opened in cleanflight: https://github.com/cleanflight/cleanflight/issues/367

**Comment by digitalentity** [comment]
Done.
