### ISSUE TITLE
Refactor yaw_control_direction

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#200]
Current way of using yaw_control_direction is strange. Instead of being applied on mixer or even PID output level, it is applied on rcCommand and MAG_HOLD controller separately in a different way: in rcCommand it is inverted, in MAG_HOLD it is not inverted.

It would be good idea to unify it, possibly without modifying rcCommand

**Comment by digitalentity** [comment]
Yes, it's confusing. I would either apply it to rcCommand[YAW] only. It's a direction of Yaw control via the stick. Positive rate will still be is still clockwise rotation, but we would be able to choose wether "yaw stick to the right" is CW or CCW.

**Comment by DzikuVx** [comment]
Since new MAG_HOLD controller is no longer modifying rcCommand it's either has to be done twice or after PID loop

**Comment by digitalentity** [comment]
I think we can simply drop the yaw_control_direction. If you have your
motors or servos the opposite way you can reverse direction via custom
mixer/servo mixer. Thats yaw_control_direction is actually confusing and
not really useful. What do you think? Drop it?

**Comment by DzikuVx** [comment]
I love to drop useless features :)

**Comment by digitalentity** [comment]
Me too. They free up space for something useful :smile:

**Comment by DzikuVx** [comment]
solved by #195 , closing
