### ISSUE TITLE
GPS UBLOX NEO8m via I2C

### ISSUE THREAD

**Issue by VictorBucha** [iNavFlight/inav#2001]
As I have run out of spare UARTS on my SPRACING F3, I wonder is it possible to acquire GPS data via i2c bus? @digitalentity mentioned this possibility couple of years ago for old GPS in Cleanflight but nothing is mentioned for INAV.

**Comment by digitalentity** [comment]
Not possible. Ublox modules won't work at I2C speeds faster than 100kHz which is really a show stopper.
