### ISSUE TITLE
skyline32 (naze clone) led_strip do not work

### ISSUE THREAD

**Issue by laurentdrone** [iNavFlight/inav#2005]
radio : ppm
gps in rc3 and rc4 work
led strip in rc5 work on betaflight/clinflight but not in inav
i have tested 1.7.2 1.7.1 1.7.0 1.6.1 1.6.0 but no work

**Comment by stronnag** [comment]
Not supported, well documented restriction

https://github.com/iNavFlight/inav/wiki/Supported-boards
