### ISSUE TITLE
Magneto calibraton greyed

### ISSUE THREAD

**Issue by tinou1** [iNavFlight/inav#2013]
Hello.
I have flash my revolution board with inav, i can see the mag is green on the top but the button for the calibration is greyed. 
And the gps icon on the top is red. My gps is a gps compass Naza.
Thanks for your help

**Comment by tinou1** [comment]
So now i don't know why i can calibrate the magnetometer.
But my gps is always on red. It's a dji gps/compass Naza. Can i try whith ubmock ftdi?

**Comment by DzikuVx** [comment]
1. This issue belongs to Configurator project and is a duplicate of iNavFlight/inav-configurator#162
1. Temporary solution is to enter any other tab and then go back to Setup tab and button will be clickable
1. Closing

**Comment by tinou1** [comment]
Thanks ;)
