### ISSUE TITLE
New concept of flight modes

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2040]
Current concept of flight modes is confusing - you need to activate a combination of modes to get something working.

Suggestion - refactor concept of flight modes with following points in mind:

1. BOXes are assigned to AUX channels as usual
2. BOXes are split into "FLIGHT MODE", "MODIFIER" and "FUNCTION"
3. Only one FLIGHT MODE is active at any given time
4. (implied by the previous point) FLIGHT MODE is self-contained, no need to combine with anything else. This will also require that we add a new flight mode "ACRO"
5. MODIFIER - changes the behavior of a FLIGHT MODE. I.e. HEAD FREE could be a modifier for ANGLE mode.
6. FUNCTION is independent and used to activate certain features of flight controller. Example: BEEPER, BLACKBOX.

Navigation modes will fit nicely into this concept - they are already mostly self-contained.

**Comment by mikeller** [comment]
What is the difference between 'MODIFIER' and 'FUNCTION' in terms of the actual implementation? Or rather can and should they be combined into 1, so that you have a 'FLIGHT MODE' selector, and a set of 'FUNCTION's that can be switched on and off irrespective of flight mode?

**Comment by digitalentity** [comment]
@mikeller in terms of implementation - none. We'll probably have a mask to allow a FUNCTION to activate only with certain flight modes.

**Comment by mikeller** [comment]
@digitalentity: Definitely. A lot of the existing modes are already dependent on some sort of condition, including a specific flight mode being active.

**Comment by martinbudden** [comment]
This is definitely a welcome improvement.

**Comment by fiam** [comment]
This is definitely an improvement over the current system. Any mode which only works with ANGLE and is unlikely to work with HORIZON/ACRO in the future should be "promoted" to "FLIGHT MODE".

Now, I'm thinking about how to show this on the OSD. How many MODIFIER modes which can be applied to at least two of ANGLE/HORIZON/ACRO do we have? I guess AIR could be applied to any of them, but what about HEADFREE, AUTOTUNE and AUTOTRIM? I'd really like to be able to show all of this to the user without requiring to set up a complicated OSD configuration (probably by making OSD_FLYMODE two lines).

Also, the more I think about it, the more I'd like an OSD element for temporary messages. It would allow us to show when a function mode has been enabled/disabled (e.g. "Beeper is on", "Beeper is off") or the reason for not arming (e.g. "Gyro not calibrated") or the current RTH phase (e.g. "Climbing", "Going home", "Landing").

**Comment by Bobrcnut** [comment]
Removing inappropriate post as requested.

**Comment by mikeller** [comment]
@Bobrcnut: Your comment is off topic for this issue. Please open a new issue with your suggestion, so that we can keep track of it.

**Comment by kabturek** [comment]
> Also, the more I think about it, the more I'd like an OSD element for temporary messages. It would allow us to show when a function mode has been enabled/disabled (e.g. "Beeper is on", "Beeper is off") or the reason for not arming (e.g. "Gyro not calibrated") or the current RTH phase (e.g. "Climbing", "Going home", "Landing").
This is something i'm missing from other flight controllers (notably vector).

**Comment by sin5678** [comment]
i think now concept of flight modes is the best, just add a extra check of the combination is enough

**Comment by digitalentity** [comment]
@sincoder "the most flexible" - yes, "the best" - I'm not so sure. There are too many combinations of incompatible modes to check - and checks happen in a lot of different places in the code. It's very easy to miss something when adding a new mode - and then have a report about something bad happening because used enabled the two together.

**Comment by sin5678** [comment]
maybe we can learn how DJI  does, flight mode P , A ,  F , S , function button : RTH , STOP ,Intelligent flight mode: head less ....etc, just as you think
