### ISSUE TITLE
RC Rate - is it really needed?

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#205]
While working on #204 I got to a conclusion, that RC Rate is useless. It is used only to build stick curve as a prescaler. With PID rates in dps I see no reason for such a thing. Does anybody knows a good reason to have it? Some radio issues? MultiWii experiment when there were no real rates? Honestly, this setting makes no real sense to me...

**Comment by theArchLadder** [comment]
Perhaps the idea was to be able to tune roll/pitch/yaw rates with only one setting and then fine-tune with induvidual settings for roll, pitch and yaw...?

But yes, i agree, this is useless and confusing. Only having separate roll, pitch and yaw rate settings in DPS (degrees per second) would be more user friendly!

**Comment by skaman82** [comment]
With roll pitch and yaw rates being zero by default, you can make your quad even a bit slower by lowering the RC rate - good for filming or rookies.

Von meinem iPhone gesendet

**Comment by theArchLadder** [comment]
That may be a feature now, but is no reason for keeping rc rate.
The proposed change should allow roll, pitch and yaw rates to be set to 90dps or something like that if one wants super slow rates.

**Comment by DzikuVx** [comment]
Exactly. With absolte rate 60dps for example there is no need for rc rate

**Comment by stronnag** [comment]
RC Rate is a hang over from the original MW PID controller. All the modern controllers just consider RC rate and axis rates as additive, the original MW controller treated them differently. Thus there is no need for it any more.

**Comment by DzikuVx** [comment]
So it will be gone....

**Comment by DzikuVx** [comment]
And it is gone in f112a127820148690cc782f17b604a19def0be3a

**Comment by digitalentity** [comment]
@DzikuVx @theArchLadder @stronnag 
If we would make very low roll/pitch/yaw rates possible (like 60-90dps) `rcRate` really becomes obsolete. I can't remember ever changing `rcRate` :smile: 
Thanks for addressing this. I wonder how much more useless/obsolete code is there?

**Comment by DzikuVx** [comment]
A lot. For example look at https://github.com/iNavFlight/inav/blob/master/src/main/mw.c#L135 Duplicated code. I will also get rid of those in #204 

Only getting rid of rc_rates freed ~ 300 bytes of flash
