### ISSUE TITLE
matek 405-osd doesn't see external comapas

### ISSUE THREAD

**Issue by egorrrr** [iNavFlight/inav#2079]
I use MATEK 405 OSD , bn-880 and Inav 1.7.3
Matek.sys say use s5 and s6 pin  as sda, scl - but Inav doesn't allow remap resources
Magnetometer doesn't work
but cli says something about scl,sda:
B06: I2C1 SCL
B07: I2C1 SDA
Thanks a lot!

**Comment by digitalentity** [comment]
On MatekF405 OSD there is no I2C outputs available. S4/S6 could be made possible, but will require adding a new target with only motor/servo outputs (s1, s2, s3, s5)

**Comment by stronnag** [comment]
This topic is already discussed on some detail, and potential solutions offered in
https://github.com/iNavFlight/inav/issues/2047

**Comment by egorrrr** [comment]
Thank you!
