### ISSUE TITLE
EZUHF.....SPPM Inputs....Are they supported on the F4 Boards?

### ISSUE THREAD

**Issue by EnglishTurbines** [iNavFlight/inav#2089]
Question is as Title, is this receiver sppm input supported on the F4 Boards.?????

 EZUHF is a popular FPV Control link, I think the RX output may be digital?
 Documentation seems limited about what receiver types are supported..?

**Comment by digitalentity** [comment]
What's SPPM?

**Comment by EnglishTurbines** [comment]
Shared Pulse Proportional Mode..?

**Comment by EnglishTurbines** [comment]
Or "Muxed" output from the EZUHF reciever.

**Comment by digitalentity** [comment]
Majority of the INAV-capable boards support PPM input (which is quite often referred to as CPPM). In fact I can't think of a board **without** PPM input.

**Comment by EnglishTurbines** [comment]
Yes, agreed CPPM...I have my EZUHF receiver configured for Muxed output, its bound and working / talking to my Transmitter..
   Question is, is it supported and what should my set up look like inside iNAV..???
Im already using iNAV and an L9R FrSky receiver, it works great, but is the EZUHF supported is my question?
                  Thanks...:)

**Comment by digitalentity** [comment]
From FC perspective EzUHF is no different than L9R or any other receiver if it's talking PPM, S.Bus or other supported protocool. I don't own a EzUHF, but I know people are using it (not sure in S.Bus or PPM mode though)

**Comment by EnglishTurbines** [comment]
Yes, thanks...it would be great if you could ask them how they have their port settings inside iNAV then?

 Can't seem to get receiver outputs going inside iNAV.....Help welcome please....:)

**Comment by digitalentity** [comment]
What board are you using, how your receiver is connected and what settings do you have for receiver in INAV?

**Comment by EnglishTurbines** [comment]
Hi....Yes, I am using an Omnibus F4 V1 Board.
 I have my EZUHF RX setup for "Muxed" or ppm output on CH1.
Inside iNAV, I have PPM enabled....(which I assume means SBUS is disabled)

  Thanks...:)

**Comment by DzikuVx** [comment]
@EnglishTurbines if you have anything connected to UART1 that explains it. PPM input and UART1 are shared by default. 
This explains it or similar board https://quadmeup.com/uart1-and-ppm-on-airbot-f4-flip32-f4-flight-controllers/

**Comment by EnglishTurbines** [comment]
Thanks DzikuVx......, The board in the Link photo is not quite the same as mine.

   The F4 (Omnibus) V1 board I have has what looks like two (tiny resistors or jumpers??) across the 
![f4 resistors](https://user-images.githubusercontent.com/29343996/30239353-d237350e-9552-11e7-984f-a7810239ab89.jpg)
jumper links.

    One for SBUS and One for PPM.
  Having substituted a FrSky RX, I can get RX Channel outputs fine, so the board is working ok.

 Does this mean I need to remove the SBUS Jumper or resistor to get CPPM to work?

**Comment by EnglishTurbines** [comment]
Happy Days......Removing the SBUS Jumper allowed the SPPM stream on the EZUHF receiver to work...:)

 Tip:
 Since I had the Servo Pinout Rail soldered on, I decided to try and lever off the jumper using a Scalpel...it worked......Using a soldering iron would have been really tricky.

 Thanks to those who helped me out with this...:)

**Comment by DzikuVx** [comment]
Like I said, UART1 was the problem. Solved, closing
