### ISSUE TITLE
SPRacing F3 600% CPU, i2c errors

### ISSUE THREAD

**Issue by Dalew74** [iNavFlight/inav#2102]
This not a new issue, the work around is to change the i2c the clock speed from 400kHz to 200kHz. No one mentions HOW to do this... It seems possible in 1.7.2 as per [this thread](https://github.com/iNavFlight/inav/issues/1969) Does anyone have some tips for a noob that really needs to fix this or its no flying until 1.7.3 is out :( 

Thanks

**Comment by stronnag** [comment]
A bit of superficial research finds a answer, e.g. via https://www.rcgroups.com/forums/showpost.php?p=38069405&postcount=15130

**Comment by Dalew74** [comment]
Heya, thanks for the reply.
