### ISSUE TITLE
CC3D Change Mixer to something else then Quad-X is not working

### ISSUE THREAD

**Issue by DaPeace** [iNavFlight/inav#2109]
Ive tried to change the mixer to Hex-X on my CC3D but after saving and reboot its back on Quad X.
Ive tried to reflash but still the same. On Betaflight it works as expected..

Regards, Jan

**Comment by oleost** [comment]
Hi.
Known bug that Hex-X is not working, should be fixed in latest INAV 1.7.3 beta.

Or you could use custom motor mixer.

**Comment by DaPeace** [comment]
Tried out.. I used the hex from here https://github.com/iNavFlight/inav/releases/tag/1.7.3
Its the same like on the other releases..

**Comment by digitalentity** [comment]
HEX-X issue is fixed in 1.7.3

**Comment by DaPeace** [comment]
Not really.. ive tried out. Deleted the Flash, Flashed the hex-File from https://github.com/iNavFlight/inav/releases/tag/1.7.3

For me its the same. I cant even change to ANY other motor-scheme then quad-x on the CC3D.

**Comment by digitalentity** [comment]
Being an F1 target CC3D only supports TRI, QUADP, QUADX, HEX6X multirotor motor layouts. Any other multirotor mixer has to be implemented as CUSTOM mix.

**Comment by DaPeace** [comment]
Oh ok.. thank you.. why is betaflight working with hex-X?

**Comment by digitalentity** [comment]
Because Betaflight is not INAV :smile: 
In INAV we removed support for "exotic" mixes on F1 targets for quite a while, otherwise CC3D and NAZE would be EOL'ed much earlier - see https://github.com/iNavFlight/inav/wiki/Custom-mixes-for-exotic-setups

**Comment by DaPeace** [comment]
Thank you very much for your help. ive ordered  2 F3-Boards to play around.
