### ISSUE TITLE
Naze32 1.7.3 beta DYI build

### ISSUE THREAD

**Issue by tonyintn** [iNavFlight/inav#2115]
Having an issue building the latest release 1.7.3 beta  receiving the following errors

---------- error begin ------
settings.yaml -> settings_generated.h, settings_generated.c
/bin/sh: ruby: command not found
make: *** [Makefile:933: src/main/fc/settings_generated.h] Error 127
------------- error end -------

Looks like the reference c and header files are missing from fc directory for setting_generated as they are being called but not in the directory.

#include <string.h>
#include <stdint.h>

#include "common/string_light.h"

#include "fc/settings_generated.h" <--- Called but not found in src/main/fc
#include "fc/settings.h"

#include "fc/settings_generated.c" <--- Called but not found src/main/fc

Thanks

**Comment by stronnag** [comment]
You need to install ruby. See the updated developer documentation.

**Comment by tonyintn** [comment]
Thanks, for the quick response, suppose I should had look there to begin with my stupid mistake.

Thanks again

**Comment by stronnag** [comment]
It should perhaps have been mentioned in the release note. OTOH, it's not unreasonable to assume folks building their own firmware will look in the PRs / git log for changes.

**Comment by stronnag** [comment]
Added to release note. Closing.
