### ISSUE TITLE
Use PB6 for LED_STRIP on Omnibus F4 V2 and above

### ISSUE THREAD

**Issue by jstremmler** [iNavFlight/inav#2117]
If I try to configure iNav 1.7.3 for a X-hexacopter on my Omnibus F4 Pro V3 and want to use an additional LED strip, then this is impossible because, when activating the LED_strip in the config menu resource A1 is now reserved for the LED strip and no longer for motor 5. If I disable the feature for the LEDstrip in the config menu again then A1 is  correctly reserved for motor no. 5 of the hexacopter.

So here is the question: Why is the resource for the LED_strip not routed to B6 instead of A1?

**Comment by digitalentity** [comment]
Good point. Omnibus V2 and above have a dedicated output for LEDs.

**Comment by michaelvanderhoek** [comment]
Could this also be working for omnibus F4 Pro? (this is also called V2) Cant find port B6?

**Comment by jstremmler** [comment]
Sure you can!

On the Omnibus F4 PRO board layout have a look at the bottom side. You will find there connector J1 with the 3 pinouts GND, 5V and LED_Strip. The pin for LED_Strip is connected to B6 of the processor and this is why iNAV should reserve LED_strip 1 as resource B6 instead of A1.The actual resource allocation prevents you from using LED's and a hexacopter configuration same time.
Btw for a quadrocopter or a tricopter you wouldn't need this because you simply can solder the DIn port of the LED_Strip to A1 and activate the LED_Strips in the configuration menue of iNAV.

**Comment by michaelvanderhoek** [comment]
Hi jstremmler, 

Someone told me earlier that the dedicated led_strip on Omnibus F4 wasnt working at all. 
So what you are saying is that it IS possible. 

I'm happy to hear that! Already was going to sell my hexa because the ideas with LEDs weren't possible

**Comment by jstremmler** [comment]
Hi Michael,

pls note that with iNav version 1.7.3 it is actually not possible to use a LED_Strip on a hexacopter with an Omnibus F4 Pro FC, but with version 1.8.0 it will be possible. If you wanted to use a LED_Strip on a hexacopter with iNav version 1.7.3 you would have to use a different FC. I think, e.g., a SPRACINGF3 would work.....

**Comment by michaelvanderhoek** [comment]
Will wait for 1.8 then! Looking forward to it!

**Comment by digitalentity** [comment]
@jstremmler can you test #2233 on your board? Please note that on cloned boards from banggood ledstrip connector is not usable)

**Comment by jstremmler** [comment]
I tested it and the LED's work, but due to a thunderstorm and bad weather I did not test version 1.7.4 in flight. Best wishes to Komsomolsk! (Have visited it!)

**Comment by michaelvanderhoek** [comment]
Hi jstremmler, what kind of board do you own? An original or clone?

**Comment by jstremmler** [comment]
I own both, but as digitalentity pointed out the clone cannot work because Chinese cloners connected the Led_Strip_Out pin of connector J1  on the board to a wrong pin of the processor.

**Comment by digitalentity** [comment]
@jstremmler great! Then we can merge #2233. You should visit here again :wink:

**Comment by michaelvanderhoek** [comment]
Jstremmler, oke tnx. I was just checking :D

**Comment by teckel12** [comment]
At least I read this and will know why my LEDs will stop working when I upgrade to 1.7.4.  I'd suggest we make a release notes (if this wasn't already thought of).

**Comment by digitalentity** [comment]
@teckel12 good idea to mention that in release notes. There is a wiki work-in-progress page for that https://github.com/iNavFlight/inav/wiki/1.8.0-Release-notes

**Comment by jstremmler** [comment]
Well, one couldn't  use LED strips with a hexacopter in iNav 1.7.3 before because A1 for motor 5 was resourced for the LED_Strips. 

To avoid confusion in iNAV version 1.7.4 I would like to suggest that reserving B6 for the LED _Strip is only happening with a hexacopter frame! 
With any quadcopter resource A1 should be reserved. Then people with quadcopters (and Omnibus clones) and people with hexacopters (and an original Omnibus) can use LED_strips.

**Comment by digitalentity** [comment]
@jstremmler I'd rather support LEDSTRIP as it is on original Airbot boards. Trying to support all of Chinese clones is impossible.

**Comment by a6j** [comment]
If you do this:
> 
> define LED_STRIP
> if defined(OMNIBUSF4PRO) || defined(OMNIBUSF4V3)
>    define WS2811_PIN                      PA1
>    define WS2811_DMA_HANDLER_IDENTIFER    DMA1_ST4_HANDLER
>    define WS2811_DMA_STREAM               DMA1_Stream4
>    define WS2811_DMA_CHANNEL              DMA_Channel_6
> 
then LED STRIP will work on the OMNIBUSF4PRO clone with BG

**Comment by putimir** [comment]
Hi, I have a cloned (BG) Omnibus F4 v2 (pro? - [prod. link](https://www.banggood.com/BF3_1_5-Omnibus-F4-V2-Flight-Controller-STM32-F405-MCU-Integrated-OSD-Built-in-5V-BEC-Current-Meter-p-1143258.html)), I connected the led strip to the J1 connector and I'm running iNav 1.8RC2, but the leds still aren't working...

My resource output says: 

`B05: LED1 OUT`
`B06: LED STRIP OUT`

So should it work or not? If it's true, that wiring is wrong, can I access the B06 from another pin?

**Comment by teckel12** [comment]
With a clone it probably won't work on J1. You need to o use the new OMNIBUSF4PRO_LEDSTRIPM5 target and connect the LED strip to M5 (PWM5).

**Comment by putimir** [comment]
I suppose this target isn't going to be pre-built, can I ask someone with a running dev environment to build it? Thank you!

**Comment by teckel12** [comment]
It seems the new LEDSTEIPM5 target is not in the latest RC. It will be included in 1.8.

**Comment by a6j** [comment]
[inav_1.8.0-RC2_OMNIBUSF4PRO_LEDSTRIPM5.hex](https://yadi.sk/d/8o27JTtK3P6heL)

**Comment by simtcrom** [comment]
My FC is Omnibus F4 Pro v2 (clone) and running inav 2.0.0 target OMNIBUSF4PRO_LEDSTRIPM5.
I am using PWM5 pin as data input to my LED strip.

https://www.electroya.com/wp-content/uploads/2017/10/Betafligth-Omnibus-F4-Pro-v2-TOP-pinmap.jpg

I would like to do a DIY gimbal using two sg90 micro servos. As per the instructions, these servos to be connected to PWM5 and PWM6.

Can I simply remove the LED data input from PWM5 and connect servo there?
Or Do I have to reflash the FC with target OMNIBUSF4PRO?

**Comment by vavisimo** [comment]
> With a clone it probably won't work on J1. You need to o use the new OMNIBUSF4PRO_LEDSTRIPM5 target and connect the LED strip to M5 (PWM5).

Hi Tim, may I ask, if clones are wrongly connected, did you find where did they connect PB6 to?
and if it is missleading and connected to nothing, the only way to use leds and M5 as PWM5 (needed for airplane, would be creating a tiny connection direct from chip leg PB6 to signal cable of led?

Thanks for reply ;)
