### ISSUE TITLE
Default values for 600 sized multicopter

### ISSUE THREAD

**Issue by FlyingGustel** [iNavFlight/inav#2119]
https://github.com/iNavFlight/inav/wiki/Default-values-for-different-type-of-aircrafts

The inav wiki got already a textbox for 600 sized quadcopter but it doesn't contain any information yet.
I'm currently testing my tarrot 690 with an omnibus pro v3 flashed with inav 1.2 .
Did someone achieve experience with such a setup yet?

**Comment by oleost** [comment]
Why are you using old outdated firmware?

**Comment by oleost** [comment]
Also I'm closing this issue. Use rcgroups thread for support. But update your firmware first.

**Comment by FlyingGustel** [comment]
Oh sorry, that was by mistake.
I meant 1.7

**Comment by FlyingGustel** [comment]
Why rcgroups? The inav wiki is simply not complete?

**Comment by stronnag** [comment]
Anyone can edit the wiki, you are welcome to contribute.

**Comment by oleost** [comment]
Then read the first line in that wiki page, in BOLD actually.

"This is outdated, INAV 1.6 is out and is using PRESET. Values here are old."

**Comment by FlyingGustel** [comment]
Is it planned to start a new wiki?

**Comment by stronnag** [comment]
Why would we do that? The existing wiki is a mass of useful information.

**Comment by FlyingGustel** [comment]
No, just refering to the comment from oleost above mine. Not the whole wiki the default value page.😄
