### ISSUE TITLE
Switch profiles based on battery cell count

### ISSUE THREAD

**Issue by eziosoft** [iNavFlight/inav#213]
As I fly with two sets of batteries, 3S and 4S I would love to see automatic profile selection based on cell count (battery voltage)
It will allow to tune the quad for each battery without thinking of changing a profile.
What do you think.

**Comment by DzikuVx** [comment]
I'm still working on #74 that will expose battery level as virtual AUX. Not the same, but if cell count also would be exposed as virtual AUX level and profile switching made mode selectable, that would might work too and give possibilities to switch profiles with switches, not only sticks

**Comment by kn8alpha** [comment]
Can this be done by using setConfigProfile() from any function, for example some function that detects cell count, and apply the settings when disarmed?
