### ISSUE TITLE
Consumed mAh in Telemetry not working on Omnibus F4 Pro v3 + CRSF

### ISSUE THREAD

**Issue by FPVZaphod** [iNavFlight/inav#2130]
Hello all,

In my Setup ( Omnibus F4 v3 Pro, Crossfire Micro v2 RX, Crossfire TX, Taranis, iNav 1.7.3 ) it shows the consumed mAh's in iNav GUI, but not in the Telemetry on the Taranis. The Sensor is recognized, but it remains 0. All others work fine.
Receiver is connected by UART1, CRSF Mode.

Thanks a lot - great work!

**Comment by digitalentity** [comment]
Thanks for reporting. Will check. We might have a bug in CRSF telemetry code.

**Comment by tgreer** [comment]
I have this exact config, so happy to do some test/debugging if required.

**Comment by digitalentity** [comment]
@FPVZaphod @tgreer PR #2293 should fix the issue.

**Comment by FPVZaphod** [comment]
Cool, thanks a lot!
How do I test this, any hex file available?

**Comment by digitalentity** [comment]
@FPVZaphod can you please test if the issue is still present in recently released 1.8-RC1?

**Comment by FPVZaphod** [comment]
Just tested it, works perfect on the Taranis now! Could not test it on the OSD yet, but this is independent from my Crossfire setup I guess. 
Thanks a lot!
