### ISSUE TITLE
RSSI Scaling for digital / PPM source

### ISSUE THREAD

**Issue by FPVZaphod** [iNavFlight/inav#2131]
Hello all,

different Receivers show their RSSI value in different ways in a PPM channel. Some use 1000-2000ms for 0-100%, others use 1300-1700. Would be nice to have the possibility to adjust this. Easiest would be saving the value for "TX off (RSSI = 0%)" and "TX 50cm away from RX (100%)".  
Or just similar to the analog RSSI Scaling, could use the same values!

Thanks!

**Comment by digitalentity** [comment]
There is a PR https://github.com/iNavFlight/inav/pull/2076 which needs to be tested.

**Comment by FPVZaphod** [comment]
Thanks - sorry, did not see this!

**Comment by digitalentity** [comment]
Fixed by #2076
