### ISSUE TITLE
Omnibus F4 osd电压不准

### ISSUE THREAD

**Issue by pdwdw** [iNavFlight/inav#2141]
Omnibus F4 osd显示电压不准,显示0.5v,调节也是这个范围变化,确定不是硬件问题,刷了几块都这样,刷bf
固件可以正常显示

**Comment by digitalentity** [comment]
English please

**Comment by fiam** [comment]
Just an automated translation, trying to make some sense of it:

```
Display voltage are not allowed to show 0.5v, the regulation is also the scope of change,
to determine the hardware is not a problem, brush a few are so, brush bf
Firmware can be displayed normally
```

So it seems to me that he can't get the decimal part of the voltage to show up somewhere (OSD? telemetry?) while in ßF it seems to work (`"brush bf
Firmware can be displayed normally"`).

**Comment by Jozx900** [comment]
English:   
Omnibus F4 osd voltage could not correct display. Always show 0.5v. It's not Hardware problem, we try put Inav firmware to other F4, still the same. But F4 can show correct voltage when use BF firmware.

**Comment by digitalentity** [comment]
My Omnibus F4 shows voltage correctly. For further troubleshooting a photo of the board and a CLI dump is required.

**Comment by DzikuVx** [comment]
Since ticket seems to be stuck and seems like it is hardware connected, I'm closing it. Thanks
