### ISSUE TITLE
Documentation update required - Matek F405-OSD servo mapping different from commonly used

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#2160]
just wired up the Matek F405-OSD in combination with the Matek 6s HUB ... 

I am used to the following connections:
**SERVO 1** = ESC
**SERVO 3** = LEFT elevon
**SERVO 4** = RIGHT elevon

Now, SERVO 4 (alias S4) seems to be dead! Then I got some curious and tried S2 instead ... which turned out to be SERVO 3 !?

This then makes it as follows:
**SERVO 1** = ESC
**SERVO 2** = LEFT elevon
**SERVO 3** = RIGHT elevon

A mate has the same effect on his config/Matek F405-OSD !
Update: Another member of the blackwingsociety reported this

the connections are made via the PDB. I tried to connect to the FC's S4 output but had the same effect.

@stronnag : if I remember right, you should have a Matek F405 at hands. can you confirm this?

**Comment by digitalentity** [comment]
IIRC this is not wrong, this is what hardware allows. We need, however, to document this feature.

**Comment by Pairan** [comment]
Ah ... i see . then we really need to document that on the MATEK Board MD so people can figure this!

**Comment by digitalentity** [comment]
@Pairan I've took the liberty of renaming the issue to reflect the actual problem, I hope you don't mind :smile:

**Comment by Pairan** [comment]
@digitalentity no worries - we figured "It's like that- and its not a bug!" then we surely can rename it to something more fitting :)

**Comment by chtay** [comment]
Hi all
I encountered the same thing. But I have another problem. On my F3 board (SPRacing F3 Clone), I can configured customairplane which I use S3 to S6 for servo, but doing the same on this Matek F405-AIO, the S5 and S6 is not responding. If I set it to hexcopter, set motor signal as PWM, on motor test, the servos that connected to S5 and S6 is working.

**Comment by Pairan** [comment]
I did a change to the documentation ... this could help, but maybe @stronnag will take a look at it

**Comment by digitalentity** [comment]
#2269 is merged. Closing
