### ISSUE TITLE
Feature Request: Backing up configured mode settings

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#2161]
I came across that currently we have no option to backup the modes in iNav. Is that something to place within the DUMP/DIFF of the CLI or simply per backup as in BF/CF? 

As my setups are getting complex, its a pain in the behind to configure every fc to do, what its predecessors my have done before :)

**Comment by digitalentity** [comment]
CLI dump/diff has a number of `aux` commands - which is precisely what you are looking for.

**Comment by Pairan** [comment]
then I'll have to look more sharp and return to RTFM-Mode! ...
