### ISSUE TITLE
Servo gimbal feature not working in SP Racing F4 board (quad x)

### ISSUE THREAD

**Issue by jaahaavi** [iNavFlight/inav#2184]
I have SP Racing F4 board on quad X. I tried to enable servo gimbal in options and map aux channel so that I can tilt camera with my TX. I can see the servo 0 output bar from motors page and it's moving correctly from TX, but there's no correct output pwm signal from motor 5 - 8 output pins.

also I don't see any servos from resource mapping from CLI:
# resource
IO:
----------------------
A00: LED1 OUT
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: FREE 
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: FREE 
A15: FREE 
B00: MOTOR8 OUT
B01: MOTOR7 OUT
B02: INVERTER OUT
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: MOTOR5 OUT
B07: MOTOR6 OUT
B08: I2C1 SCL
B09: I2C1 SDA
B10: FREE 
B11: FREE 
B12: SDCARD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: ADC CH3
C01: FREE 
C02: FREE 
C03: FREE 
C04: FREE 
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR4 OUT
C09: MOTOR3 OUT
C10: SERIAL4 UART TX
C11: SERIAL4 UART RX
C12: FREE 
C13: MPU EXTI
C14: SDCARD IN
C15: BEEPER OUT
D02: FREE

**Comment by jaahaavi** [comment]
I have now tried to re-flashing and erasing all settings, but I still I can't make any servo work on this FC.
I have tried servos on PWM 5-8 headers and even I can seen on configurator (motor tab) that servo bar is moving but servos aren't moving. It's like there's no PWM signal coming out from FC.
Is this a bug with inav firmware or is there something that I don't understand?

**Comment by jaahaavi** [comment]
Just checked the code in the inav/src/main/target/SPRACINGF4EVO/target.c
lines 42 & 43:
    { TIM3,  IO_TAG(PB1),  TIM_Channel_4, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },
    { TIM3,  IO_TAG(PB0),  TIM_Channel_3, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },

Those PWM 7 and PWM 8 doesn't have TIM_USE_MC_SERVO and TIM_USE_MC_CHNFW defined there like this:
    { TIM3,  IO_TAG(PB1),  TIM_Channel_4, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | **TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO** | TIM_USE_FW_MOTOR },
    { TIM3,  IO_TAG(PB0),  TIM_Channel_3, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | **TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO** | TIM_USE_FW_MOTOR },

I don't have environment to compile and test if this would fix the servo issue. Could @digitalentity or someone else to check if this is the issue. I can verify and test the change with my FC.

**Comment by digitalentity** [comment]
Fixed
