### ISSUE TITLE
Flight mode and tx rx

### ISSUE THREAD

**Issue by tinou1** [iNavFlight/inav#2194]
Hello. 
When angle and horizon are selecte the color change from grey to blue but not with other mode like rth or gps hold. Normal??
I have revolution board and i use the flexi io port for ppm input. Can i use the pin 7and 8 (tx rx) for my minimosd?
Tks

**Comment by tinou1** [comment]
For mode now it,s ok but not for the telemetry.
I have connect tx rx into the minimosd but change nothing in the video, just the video without traitment. I can unplug tx rx and +5v change nothing.
How i need to configure inav for have tx and rx in the flexiio port?
Tks

**Comment by DzikuVx** [comment]
Port tab has to used to configure correct UART and protocol on that port
