### ISSUE TITLE
Board Req

### ISSUE THREAD

**Issue by 0higgins0** [iNavFlight/inav#2195]
any plans to include the CL Racing F4 board

**Comment by oleost** [comment]
Have you tried contacting the company of that board with an request getting it supported in INAV?

If they have made themselves incompatible with one of current targets they should aim to get supported on different firmwares.

**Comment by 0higgins0** [comment]
I will do that. Thanks

**Comment by DzikuVx** [comment]
I can see this target for 1.8. Closing
