### ISSUE TITLE
cpu_underclock affecting roll/pitch rate?

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#2209]
I did a test flight with my race wing and "set cpu_underclock = on"
It seemed that the rates were fairly low, maybe got divided by underclock?

**Comment by Schalonsus** [comment]
Never mind, i think it has to do with new servo mixer output scaling.
Migrated from 1.7.1 to 1.7.3 and control was very slow and rubbish. Checked the servo travel at the flying field at this is way too little. But now i know where to tune.

**Comment by digitalentity** [comment]
@Schalonsus thanks for letting us know. Indeed, mixer weights for flying wing changed in 1.7.3

**Comment by DzikuVx** [comment]
And just to mention: right now it is a proper mixer for flying wing. Previous one was wrong
