### ISSUE TITLE
external compass

### ISSUE THREAD

**Issue by Hoog2000** [iNavFlight/inav#2210]
I have some problemes with i2c port and external compass. can someone give me a complete description of how i setup external compass in inaw with i2c port? :)

**Comment by DzikuVx** [comment]
1. SDA to SDA pad
2. SCL to SCL pad
3. 3.3V to Vcc
4. GND to GND
5. Enable MAG in Configurator and choose proper hardware. Tab "Configuration"
6. If not working:
    1. Check wiring
    1. Check if I2C on FC is not shared with any UART (UART3 for example on majority of STM32F4 boards)
    1. Lower CLI `i2c_speed` to 200 or even 100 kHz

**Comment by Hoog2000** [comment]
thanks
