### ISSUE TITLE
Gps not detected 

### ISSUE THREAD

**Issue by sniperxnl** [iNavFlight/inav#2218]
This is what i am using
GPS:https://hobbyking.com/en_us/mini-ublox-neo-m8n-gps-for-apm-and-pixhawk.html
Omnibus f4:https://www.banggood.com/BF3_1_5-Omnibus-F4-V2-Flight-Controller-STM32-F405-MCU-Integrated-OSD-Built-in-5V-BEC-Current-Meter-p-1143258.html?rmmds=myorder

Connect TX /RX/5v/gnd to Uart1, activate GPS 115200 (tryed alle rates)
Activate Ublox, Autodected, also Europe
Gps stay red, and get no gps information in the GPS tab.

When i Connect my old M6N gps, it works directly

**Comment by DzikuVx** [comment]
https://quadmeup.com/hardware-revisions-of-omnibus-f4-flight-controllers/

> PPM and UART1 can be used together when S.BUS jumper is removed (close to PPM/SBUS connector)

Also it is described here: https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md
