### ISSUE TITLE
support for FrSky XSRF3O

### ISSUE THREAD

**Issue by twistedwings** [iNavFlight/inav#2222]
I would like to see support for FrSky XSRF3O.

**Comment by DzikuVx** [comment]
If FrSky would be willing to contribute by donating boards to dev team it might happen

**Comment by twistedwings** [comment]
is it possible to steal the code from betaflight ?

**Comment by giacomo892** [comment]
@janbolt of course it is. but it is not stealing. Betaflight is opensource and you can port code to iNAV with "ease"

**Comment by DzikuVx** [comment]
Only you can not just "copy-paste" since it will not work. Additional work and testing is required

**Comment by twistedwings** [comment]
what about cleanflight ? Can the code be "copied & pasted" from there ?

**Comment by digitalentity** [comment]
Cleanflight = Betaflight in many aspects, including code portability. No, code can't be directly copy-pasted from there. Required changes are usually minor, but require some understanding of STM32 hardware.

**Comment by DzikuVx** [comment]
With work in progress in #2430 I'm closing this one. Expect this target in release after 1.8
