### ISSUE TITLE
If GPS worked and stops working - show last assigned GPS coordinates

### ISSUE THREAD

**Issue by romanas** [iNavFlight/inav#2223]
Had a water dive in to river, and BEC was damaged, GPS was connected via external BEC with servos, camera after water splash disconnected (but VTX still was working and telemetry ok), so GPS just stop working (no more data) and OSD did not show any coordinates (doh).
Question: is there a way to make it remember last GPS coordinates (If they were assigned before)?

I know it's better to always use DVR.

**Comment by teckel12** [comment]
I know FrSky telemetry always shows last GPS coordinates.  OSD should also show last coordinates, maybe flashing or something to indicate that they're not current values but last known location?  Would also be useful if GPS lock is lost even while flying due to buildings/trees.
