### ISSUE TITLE
Unable to make latest master

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#223]
Can't compile latest master with SPRACINGF3
Tried just making for Naze32 and it worked, still some errors.

My build enviroment is Windows 8, and setup like in the docs https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Windows.md

http://pastebin.com/gze0xEHC <<<--- make TARGET=SPRACINGF3

http://pastebin.com/qWxKUEwc <<<--- make

**Comment by digitalentity** [comment]
This is caused by #149.
@martinbudden, can you fix this please?

**Comment by martinbudden** [comment]
@digitalentity , a fix for this was already on the way...

See PR https://github.com/iNavFlight/inav/pull/224 , this is the first part of the sonar initialisation cleanup. There are a couple of more sonar initialisation cleanup PRs on the way...

**Comment by digitalentity** [comment]
Fixed by https://github.com/iNavFlight/inav/commit/4c3c8a1b4870f7d806cde07db668f1751b88ad40
