### ISSUE TITLE
MSP not working on Softserial if other Softserial Baudrate is different

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#2232]
Have a HC-05 connected to Softserial 1 and MSP 9600 baud.
When i select Softserial 2 to be LTM and 9600 baud everything is fine.
But if i change LTM to 1200 baud, Softserial 1 MSP is not working anymore.

**Comment by DzikuVx** [comment]
I suppose this is one of SS limitations we are facing. This was never working very reliably when more than 1 SS was used

**Comment by DzikuVx** [comment]
And this is not only F1 issue, so I'm changing topic

**Comment by stronnag** [comment]
Not sure how you expect it to work. You would also need to change the rate of every other device; BT, radios, ground station. Not an fc issue as LTM at 1200 works with correctly configured hardware.

**Comment by stronnag** [comment]
Ignore me, misread the question. OTOH, isn't it a SS limitation that the rates are the same for each ?

**Comment by giacomo892** [comment]
That's stated also in the documentation. SS ports must all run at the same baud rate. Limiting but a reality.

**Comment by DzikuVx** [comment]
So, close? I suppose...

**Comment by giacomo892** [comment]
If someone wants to ammend this is very welcome. SS needs a total rework

**Comment by Schalonsus** [comment]
ok thanks for the information, then i have to live with it

**Comment by fiam** [comment]
@DzikuVx , @digitalentity How feasible would be to allow different speeds on multiple SS?
