### ISSUE TITLE
OSD elements are not erased at their old position after moving them

### ISSUE THREAD

**Issue by lavaed** [iNavFlight/inav#2237]
![default](https://user-images.githubusercontent.com/12794053/31046062-c053f2d8-a5fa-11e7-9b42-ad48ed464433.png)

When configuring icons in the configurator on the osd screen, the icons in the fpv image are cloned. The dragged icon remains in the old place and on the new one.

**Comment by fiam** [comment]
@lavaed This has been already fixed and will be part of 1.8

**Comment by fiam** [comment]
Just added the 1.8 milestone because I I discovered this one myself and I think I  fixed it without opening an issue. This way we won’t forget to mention it in the release notes.

**Comment by skaman82** [comment]
@fiam does your fix also includes the stats screen still being there (partly) after the throttle stick is moved up to hide the stats? The screen is only being fully refreshed after rearm.
![img_20170930_194814](https://user-images.githubusercontent.com/11768024/31048181-6eb47e8e-a618-11e7-88ea-da9573e9f623.jpg)

**Comment by fiam** [comment]
@skaman82 AFAIK I fixed that one too, but on a different commit.

**Comment by fiam** [comment]
@skaman82 Fixed in https://github.com/iNavFlight/inav/commit/c5cfe4ac845351016d6fd233b48403bdc2c1b4a0 and then reworked in a better way in https://github.com/iNavFlight/inav/pull/2163
