### ISSUE TITLE
Using GPS Altitude

### ISSUE THREAD

**Issue by AgentOra** [iNavFlight/inav#2238]
Hello,

i´ve got a Quadcopter with a DYS F4 Pro FC without Barometer. It is possible to use only the GPS
Altitude for the RTH Altitude Modes?
Thanks all

**Comment by giacomo892** [comment]
No. It will not work on multicopters. Only airplanes.

**Comment by DzikuVx** [comment]
And even so it is not encouraged to use only GPS Altitude. It is not reliable enough
