### ISSUE TITLE
Allow Fixed Wing RTL to gain altitude by circling instead of maintaining current heading

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#2241]
Gaining altitude before RTL is always a good thing and it is enabled by default in iNAV. That's great.

It is also nice that altitude is gained on the current heading since it is supposed that the pilot was flying toward a safe spot.

This could not be case if you fly in moutains where you can easily go below the launch altitude so then the plane could impact ground when climbing if you loose signal when returning to launch point.

I think then we should have an option to allow the plane to climb while loitering and then return to launch point safely. 

This is what I mean:

https://youtu.be/bq-rIFpAGQg

I lost my wing (I supposed it crashed into rocks) at 2000m. If the wing immediatelly started loitering and gaining altitude I would have recovered it. 

OT. I suppose FAILSAFE didn't worked properly since the plane didn't gain any altitude after the first AUTO RTH message on the OSD, moreover it has sunk more.

**Comment by Dronek** [comment]
Related to... 
https://github.com/iNavFlight/inav/issues/1283

**Comment by breadoven** [comment]
Closed by https://github.com/iNavFlight/inav/pull/6437.
