### ISSUE TITLE
Display alarm on the OSD if altitude is below a threshold (negative one is the most useful case)

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#2242]
It would be very helpful to display an alarm if the altitude drops under a certain threshold.

**Comment by fiam** [comment]
How should we implement this one? A new configurable alarm for negative altitude or just hardcode it to blink below, let's say, -10m?

**Comment by giacomo892** [comment]
I think we can made it configurable with a default of -10m.

Warning the user going under the landing altitude is important to prevent radio / video loss and the possibility of hitting objects along the route.

**Comment by fiam** [comment]
Configurable with a default of -10m it is 👍

**Comment by digitalentity** [comment]
Good thing. @giacomo892 you know first hand why this warning is required :laughing:

**Comment by giacomo892** [comment]
@digitalentity Yes. After the second rescue mission the wing still missing. RIP :)

**Comment by fiam** [comment]
Let us take a moment of silence for that Wing Wing. It will always be remembered as the wing who brought us low altitude alarms!

**Comment by giacomo892** [comment]
I'll place a marble commemorative stone where I lost it. You are all invited to the ceremony.

**Comment by digitalentity** [comment]
Fixed via 2296
