### ISSUE TITLE
Request for new Hardware Support SP Racing F3 OSD/PDB

### ISSUE THREAD

**Issue by Mmarsian** [iNavFlight/inav#2253]
Sorry if I'm requesting at the wrong place. Since the SP Racing F4-EVO is now supported, I'm requesting to port the code of the SP Racing F3 OSD/PDB from Cleanflight into INav, so that the OSD provided by this board is usable in iNav. The OSD PDB has a separate version of Cleanflight 2.1.0 and is currently not recognized by the OSD in iNav.
SP Racing F3, F3-EVO and F4-EVO are designed to be stacked with the F3 OSD/PDB and thus there would be an easy way to provide the OSD to iNav porting the already existing code (cleanflight_2.1.0_SPRACINGF3OSD).

TIA.

**Comment by Target0815** [comment]
+1

**Comment by DzikuVx** [comment]
After some discussions in the team, I'm forced to close it. The INAV team will not actively add this target without external support. If for example @hydra will decide to add it to INAV then great. If not, chance of that happening are rather not existent
