### ISSUE TITLE
Matek F405OSD: Leaving OSD menu via sticks destroys old screen afterwards

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#2271]
There is a bug within the OSD menu.

1) _**Save and Reboot wont reboot!**_
Buzzer beeps once, but FC doesn't reboot
Demonstrated in the video

2) _**Entering and Leaving OSD menu via sticks messes up the OSD Screen afterwards**_
Enter the menu, leave the menu, OSD screen is messed up with fragments.

see the video: [Video on YouTube](https://www.youtube.com/watch?v=HFEvBdCgVIQ)

**Comment by digitalentity** [comment]
@Pairan it's already fixed in upcoming release, thanks for reporting.

**Comment by Pairan** [comment]
Thanks for your feedback - this needs to be closed then. Do I simply hit the CLOSE button here?

**Comment by digitalentity** [comment]
Closed :smile:
