### ISSUE TITLE
Omnibus F4 I2C not working

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2273]

**Comment by jstremmler** [comment]
What is wrong with the I2C at the Omnibus F4?  

I own several Omnibus F4 Pro V2 and the Eachine modified Omnibus F4 V3. On all of them I2C is working and the magnetometes which I have connected at least seem to work correctly. (iNAV version1.7.3)

**Comment by digitalentity** [comment]
@jstremmler sorry, I looket at my local testing branch where I've removed I2C support for some reason :grimacing:
