### ISSUE TITLE
Change alarm to always use SI units internally. Make zero disable an alarm.

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav#2297]
Currently the altitude alarm has different meanings, depending on the OSD units. When using SI units, the altitude alarm is interpreted as meters, while setting the units to IMPERIAL interprets the alarm as specified in feet.

This design requires the code in osd.c to perform unnecessary arithmetic for converting the altitude alarm on demand (since it could be changed at any time) to the necessary unit, wasting a few cycles every time the altitude indicator is drawn. It also complicates the code without any good reason.

My proposal is changing the alarms to behave like the new distance and negative altitude alarms. Always use SI units internally and convert between meters and the imperial unit which makes more sense (feet for altitude, miles for distance) in the configurator UI.

Also, setting an alarm to zero should disable it. That would allow us to set a zero default for some of the alarms which don't have a clearly useful default value for all users (e.g. battery capacity).

PRs with the implementation for these two new alarms can be found at:

INAV: https://github.com/iNavFlight/inav/pull/2296
Configurator: https://github.com/iNavFlight/inav-configurator/pull/276

As you can see, doing the conversion in the UI requires just a bit of code and since we're already doing it for these new alarms, we might as well do it for all of them a save a few bytes of flash and cycles on the FC.

Feel free to just use thumbs up or down.

**Comment by digitalentity** [comment]
I'm all in for this. Consistency is good.

**Comment by fiam** [comment]
Fixed by #2296
