### ISSUE TITLE
ACC calibration won´t work if FC is mounted upsidedown or in another angle

### ISSUE THREAD

**Issue by gurkenfolie** [iNavFlight/inav#230]
The ACC calibration doesn´t take the FC alignment in account, it is not possible to calibrate it as shown in the pictures when the FC is mounted in another angle or upside down.
It is only possible to calibrate the FC when the FC points to the directions as shown in the calibration pictures, makes calbration a little bit confusing.

**Comment by digitalentity** [comment]
Yes, that's a known bug. I'll address it.

**Comment by eziosoft** [comment]
Is it present also in 1.0.1? That would explain why PH doesn't work for me nicely.

**Comment by Flugsicherung** [comment]
Today I testing V1.1 on my SPRacingF3 Deluxe. The Board is mounted 180° in YAW to connect the short motor cables to the FC. Calibration of Gyro doesn´t work in this configuration.

**Comment by digitalentity** [comment]
@Flugsicherung can't reproduce.

**Comment by digitalentity** [comment]
First acc calibration point should be FC in the upright position. If FC is mounted upside down this means first position should be UAV upside down (so FC would be upright). Minor bug, postponing for 1.3

**Comment by Flugsicherung** [comment]
I don´t mount the FC upside down, I mount the FC 180° in YAW to connect short motor cables.

**Comment by digitalentity** [comment]
Then there is no reason for calibration to fail, unless you don't follow the procedure - https://github.com/iNavFlight/inav/wiki/4.-Sensor-calibration#accelerometer-calibration-steps

**Comment by oleost** [comment]
@flugsichdrung Are you doing it like this  https://youtu.be/HxWSn_noNgg?

**Comment by Flugsicherung** [comment]
Thanks for the info. I did it like cleanflight and that was wrong :)

**Comment by oleost** [comment]
@digitalentity why did you close this?

**Comment by digitalentity** [comment]
Because it's irrelevant. First position of calibration has to be FC upright and calibration works if this is done properly. 

We need a more user-friendly calibration, but that's a different issue.

**Comment by oleost** [comment]
Fair enough, just wondered if you did it by mistake since you labeled it bug a while ago.

**Comment by digitalentity** [comment]
I thought that I would rework the procedure only in formware, however now I think it should be done better from both firmware and UI sides. Not user-friendly calibration is not forgotten :smile:

**Comment by DzikuVx** [comment]
I also have this topic somewhere in my mind in context of Configurator
support

wt., 15.11.2016 o 15:07 użytkownik Konstantin Sharlaimov <
notifications@github.com> napisał:
