### ISSUE TITLE
Omnibus F7 (Banggood) onboard barometer (BMP280) not detected

### ISSUE THREAD

**Issue by swemonstro** [iNavFlight/inav#2312]
I recently got a F7 omnibus from banggood, where there should be (and physically are mounted on the board) an BMP280 barometer, but I cant get any values from it. 

Im very new to iNav, but I think I managed to flash the board to version 1.7.3 

Any suggestions where to start? and what kind of information could I include here (and how) to make it easier to find the problem.

Sincerely yours

Carl from sweden

**Comment by DzikuVx** [comment]
I falshed INAV to my Omnibus F7 (original, not BG clone) and it worked fine. Baro detected and functional.

**Comment by digitalentity** [comment]
@swemonstro please provide a link to the board you purchased.

**Comment by swemonstro** [comment]
Should have bought a real one (wasnt aware it was a clone when I bought it) 

No other changes, norhing under ports or such?

**Comment by DzikuVx** [comment]
https://quadmeup.com/hands-on-omnibus-f7-flight-controller/

No changes were required, this baro is SPI connected. Either we again have a clone that changed something or board is damaged

**Comment by michaelvanderhoek** [comment]
try setting baro type to AUTO, my banggood board would not let me see baro also at first. Setting it to AUTO and pressing save,  then reboot the board did it for me.

**Comment by swemonstro** [comment]
The link to the board:
https://www.banggood.com/BF3_2-Omnibus-F7-Flight-Controller-STM32-F745-Integrated-OSD-Built-in-5V-2A-BEC-Dual-Sensors-p-1177839.html

I tried both set i manual and auto, but no luck

**Comment by michaelvanderhoek** [comment]
thats weird. maybe try flashing an older version of Inav, did you flash it in DFU mode?

**Comment by swemonstro** [comment]
I did flash it in DFU, trying right now to do that, but now it get stuck at 'erase'

trying to reinstall driver thru zadiq

**Comment by swemonstro** [comment]
and after that I cant reconnect at all. the computer dont even recognize the board as stm32, just Unknown USB Device (Device Descriptor Request Failed)

think my board is toast...  :(

**Comment by DzikuVx** [comment]
@swemonstro it's not that easy to fly a STM32. Probably it's only a driver problem

**Comment by giacomo892** [comment]
Try to put it into bootloader and flash again with a different firmware and using "no reboot sequence"

**Comment by swemonstro** [comment]
In back again after some problems getting back into DFU.

there are only one firmware for omnibus F7. so not much to choose from unfortunately. or do you suggest trying another board?

**Comment by michaelvanderhoek** [comment]
try to flash it again in DFU mode. make sure you ticked the box: no reboot sequence. 
Maybe it will work. if not then i think its a broken board

**Comment by swemonstro** [comment]
I got the card back in DFU mode last night, and flashed it again. (but not sure if I ticked the 'no boot sequence' - what does that do?)

So now the flight controller works as Before, with acc. and so, but still no barometer.

**Comment by digitalentity** [comment]
My best bet is that it's a faulty board. Original Omnibus F7 works fine

**Comment by swemonstro** [comment]
Banggood asked be to document the behavior on video, so I did. Perhaps anybody can see if I do anything wrong.

https://youtu.be/UiZz_-FuWUs

**Comment by DzikuVx** [comment]
Like I wrote in the other ticket, I flashed Omnibus F7 yesterday, everything seemed to be working fine, including barometer. So sorry, but looks like INAV has nothing to do with your problems and it seems to be hardware issue.

BTW, I watched the video, and I do not see anything wrong with your setup

**Comment by swemonstro** [comment]
Thank you. no I also believe that it's the board that's the problem.

Thank you for the support!

**Comment by Arvycka** [comment]
I've just received F3 Pro from AliExpress - Barometer on it doesn't work either. Probably doesn't work on any of the clones.

**Comment by giacomo892** [comment]
@Arvycka Try 1.8RC

**Comment by Arvycka** [comment]
Thanks, tried that - still no go for baro

**Comment by digitalentity** [comment]
@Arvycka please provide a link to a board. I'll try to get one and tackle the baro issue.

**Comment by Arvycka** [comment]
@giacomo892  I have since received an identical board from another supplier and baro worked right away on it - so it's a hardware issue. That's what I get for being a cheapskate. Thanks for your help and sorry for posting to a closed thread.

**Comment by swemonstro** [comment]
Just an update, I recieved another board from bangood (same omnibus F7) and the Barometer worked instantly, so it was a faulty board.

thanks for the support!!

**Comment by digitalentity** [comment]
@swemonstro thanks for the update!
