### ISSUE TITLE
Automatically generate CLI documentation

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2316]
Since we now have cool `settings.yaml` why not put descriptions there as well and have a script that will generate `CLI.md` in the docs. One less file to maintain.

**Comment by fiam** [comment]
This definitely makes a lot of sense. I think we should also move the default setting values to the `yaml` file when possible.

**Comment by digitalentity** [comment]
Good idea. We can auto-generate `#define`s for default setting values and we could use those defines in PG reset structures.
