### ISSUE TITLE
Omnibus F4 v2 usb came off

### ISSUE THREAD

**Issue by sniperxnl** [iNavFlight/inav#2321]
Guys,

In the field today after some testing inflight the usb came off, and also the pads.
Someone knows away to get it back online?

**Comment by DzikuVx** [comment]
@sniperxnl I do not think this is the correct place to ask that specific hardware questions. But if pads are gone, it might be undoable and getting a new board might be the cheapest solution

**Comment by sniperxnl** [comment]
That is not true, when it happen in betaflight then there is a special betaflight firmware that activate on a other uart the msp, you need to load that with a st-link v2 tool. So there is a inav firmware needed that use a diffrent msp port

**Comment by digitalentity** [comment]
MSP is enabled by default on UART1 on all boards with VCP
