### ISSUE TITLE
Betaflight OmniBus F4 Pro V2 Flight Control Built-in OSD/BEC For FPV Drone Quad

### ISSUE THREAD

**Issue by alanfj** [iNavFlight/inav#2325]
This FC came pre-flashed w/ Betaflght 3.10 OMNIBUSF4SD. It will not flash w/ any of the INAV Omnibus targets. It just hangs in erase mode. Any idea what could be my problem?

**Comment by fiam** [comment]
@alanfj The bug has already been fixed in the configurator and will be available in the next release.

As a temporary workaround, disable full chip erase while flashing. Flash INAV and then go to the CLI and enter the `defaults` command. It should have the same effect as a full chip erase.
