### ISSUE TITLE
Naze32 inav 1.7.3 buzzer and baro

### ISSUE THREAD

**Issue by StariyHopeer** [iNavFlight/inav#2330]
after flashing no beeping boozer on naze32 now. After the L2c port connected 3dof Compass HMC5983 BMP180 barometer. on of them is automatically started only a compass, a barometer is not defined. When trying to put the barometer in the manual, nothing happens and on the Board the led blinks.

**Comment by stronnag** [comment]
The BMP180 (BMP085) is not compiled by default on NAZE target. As F1 will not be supported after 1.8, your will have to compile your own firmware. See https://github.com/iNavFlight/inav/wiki/Building-custom-firmware if you need some assistance.

**Comment by StariyHopeer** [comment]
Thanks for the help, but for me it's too difficult, have no barometer.

**Comment by giacomo892** [comment]
Here you are 1.7.3 with BMP180 enabled.
@StariyHopeer 

[inav_1.7.3_NAZE_BMP180.hex.zip](https://github.com/iNavFlight/inav/files/1382368/inav_1.7.3_NAZE_BMP180.hex.zip)

**Comment by DzikuVx** [comment]
And since Naze will not be supported in next version of INAV, I'm closing this one. Thanks everyone

**Comment by StariyHopeer** [comment]
thank you very much for the help!
