### ISSUE TITLE
Suggesting add a param to disable failsafe when flying waypoints

### ISSUE THREAD

**Issue by sin5678** [iNavFlight/inav#2340]
waypoint behind builds or fly very far away will surly cause failsafe active and then waypoints task exit，so I suggest add a param to disable failsafe when flying WP and auto enable it when WP task done

**Comment by sin5678** [comment]
no one understand what i mean ?

**Comment by digitalentity** [comment]
Duplicate of #770. See also #977. Might happen in 1.9

**Comment by vitalyga** [comment]
I'm also highly interested in this feature. Can somebody clarify what is the status? I saw it was added to 1.9 milestone, then removed, then closed... Is that somehow dropped/forgotten?
