### ISSUE TITLE
Allow in-flight adjustment of settings via channels

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav#2341]
A 1500us value should be interpreted as no changes to the configured permanent setting. Values in the [1000, 1500) and (1500, 2000] range should increase or decrease the setting proportionally up to a minimum and a maximum value.

We should require any channels linked to a setting to be centered before arming. When this happens, we should show a message in the OSD informing the user.

Things that could be adjusted during a flight include:

- Cruise speed
- RTH altitude
- Level adjustment

Feel free to add more ideas for adjustable settings in comments.

**Comment by Dronek** [comment]
I'm already running out of my 12 channels. It would be nice if steering sticks (existing channels) could be used for this purpose. Maybe together with a momentary switch.

Maybe like this: 
if momentary switch engaged -> steering commands freeze + sticks change different parameters
if momentary switch released -> parameters are saved + steering via sticks allowed again

With momentary switch engaged, left stick could be used for selecting the parameter to change. For example left-down vs. left-right vs. top-center etc. This would allow to assign 9 different parameters according to 9 different easily manageable stick positions (including full center).
The right stick would be used for changing the actual parameter (e.g. up and down) with optional functionality by using left and right deflections.

Just an idea...
