### ISSUE TITLE
ACRO or STB mode, throttle will mix with servos.

### ISSUE THREAD

**Issue by Jozx900** [iNavFlight/inav#2353]
https://www.youtube.com/watch?v=v0Zdn3U-BGg&feature=youtu.be
In ACRO and STB mode, just like video shows, when I change the throttle, the servos will change also. they seems mixed together. I didn't set any mix in the transmitter, so it must be some mix in the INAV, is that normal?

**Comment by fiam** [comment]
Did you enable AIRMODE? In any case, post a dump of your configuration so we can see if there’s something misconfigured.

**Comment by Jozx900** [comment]
all mode will happen this problem.here is my setting:
# dump# version# INAV/OMNIBUSF4PRO 1.7.2 Jul 20 2017 / 11:59:41 (81b85de)# resources# mixermixer FLYING_WINGmmix reset# servoservo 0 1000 2000 1500 100 -1 servo 1 1000 2000 1500 100 -1 servo 2 1000 2000 1500 100 -1 servo 3 1000 2150 1480 110 -1 servo 4 1000 2150 1555 -110 -1 servo 5 1000 2000 1500 100 -1 servo 6 1000 2000 1500 100 -1 servo 7 1000 2000 1500 100 -1 # servo mixsmix reset# featurefeature -RX_PPMfeature -VBATfeature -RX_SERIALfeature -MOTOR_STOPfeature -SERVO_TILTfeature -SOFTSERIALfeature -GPSfeature -TELEMETRYfeature -CURRENT_METERfeature -3Dfeature -RX_PARALLEL_PWMfeature -RX_MSPfeature -RSSI_ADCfeature -LED_STRIPfeature -DASHBOARDfeature -BLACKBOXfeature -CHANNEL_FORWARDINGfeature -TRANSPONDERfeature -AIRMODEfeature -SUPEREXPOfeature -VTXfeature -RX_SPIfeature -SOFTSPIfeature -PWM_SERVO_DRIVERfeature -PWM_OUTPUT_ENABLEfeature -OSDfeature RX_PPMfeature VBATfeature MOTOR_STOPfeature GPSfeature CURRENT_METERfeature PWM_OUTPUT_ENABLEfeature OSD# beeperbeeper RUNTIME_CALIBRATIONbeeper HW_FAILUREbeeper RX_LOSTbeeper RX_LOST_LANDINGbeeper DISARMINGbeeper ARMINGbeeper ARMING_GPS_FIXbeeper BAT_CRIT_LOWbeeper BAT_LOWbeeper GPS_STATUSbeeper RX_SETbeeper ACTION_SUCCESSbeeper ACTION_FAILbeeper READY_BEEPbeeper MULTI_BEEPSbeeper DISARM_REPEATbeeper ARMEDbeeper SYSTEM_INITbeeper ON_USBbeeper LAUNCH_MODE# mapmap AETR1234# namename -# serialserial 20 1 115200 38400 0 115200serial 0 1 115200 38400 0 115200serial 2 1 115200 38400 0 115200serial 5 2 115200 115200 0 115200# ledled 0 0,0::C:0led 1 0,0::C:0led 2 0,0::C:0led 3 0,0::C:0led 4 0,0::C:0led 5 0,0::C:0led 6 0,0::C:0led 7 0,0::C:0led 8 0,0::C:0led 9 0,0::C:0led 10 0,0::C:0led 11 0,0::C:0led 12 0,0::C:0led 13 0,0::C:0led 14 0,0::C:0led 15 0,0::C:0led 16 0,0::C:0led 17 0,0::C:0led 18 0,0::C:0led 19 0,0::C:0led 20 0,0::C:0led 21 0,0::C:0led 22 0,0::C:0led 23 0,0::C:0led 24 0,0::C:0led 25 0,0::C:0led 26 0,0::C:0led 27 0,0::C:0led 28 0,0::C:0led 29 0,0::C:0led 30 0,0::C:0led 31 0,0::C:0# colorcolor 0 0,0,0color 1 0,255,255color 2 0,0,255color 3 30,0,255color 4 60,0,255color 5 90,0,255color 6 120,0,255color 7 150,0,255color 8 180,0,255color 9 210,0,255color 10 240,0,255color 11 270,0,255color 12 300,0,255color 13 330,0,255color 14 0,0,0color 15 0,0,0# mode_colormode_color 0 0 1mode_color 0 1 11mode_color 0 2 2mode_color 0 3 13mode_color 0 4 10mode_color 0 5 3mode_color 1 0 5mode_color 1 1 11mode_color 1 2 3mode_color 1 3 13mode_color 1 4 10mode_color 1 5 3mode_color 2 0 10mode_color 2 1 11mode_color 2 2 4mode_color 2 3 13mode_color 2 4 10mode_color 2 5 3mode_color 3 0 8mode_color 3 1 11mode_color 3 2 4mode_color 3 3 13mode_color 3 4 10mode_color 3 5 3mode_color 4 0 7mode_color 4 1 11mode_color 4 2 3mode_color 4 3 13mode_color 4 4 10mode_color 4 5 3mode_color 5 0 9mode_color 5 1 11mode_color 5 2 2mode_color 5 3 13mode_color 5 4 10mode_color 5 5 3mode_color 6 0 6mode_color 6 1 10mode_color 6 2 1mode_color 6 3 0mode_color 6 4 0mode_color 6 5 2mode_color 6 6 3mode_color 6 7 6mode_color 6 8 0mode_color 6 9 0mode_color 6 10 0# auxaux 0 0 1 1300 2100aux 1 1 0 1150 1700aux 2 8 0 1700 2100aux 3 27 2 1825 2100aux 4 18 0 1900 2100aux 5 0 0 900 900aux 6 0 0 900 900aux 7 0 0 900 900aux 8 0 0 900 900aux 9 0 0 900 900aux 10 0 0 900 900aux 11 0 0 900 900aux 12 0 0 900 900aux 13 0 0 900 900aux 14 0 0 900 900aux 15 0 0 900 900aux 16 0 0 900 900aux 17 0 0 900 900aux 18 0 0 900 900aux 19 0 0 900 900# adjrangeadjrange 0 0 0 900 900 0 0adjrange 1 0 0 900 900 0 0adjrange 2 0 0 900 900 0 0adjrange 3 0 0 900 900 0 0adjrange 4 0 0 900 900 0 0adjrange 5 0 0 900 900 0 0adjrange 6 0 0 900 900 0 0adjrange 7 0 0 900 900 0 0adjrange 8 0 0 900 900 0 0adjrange 9 0 0 900 900 0 0adjrange 10 0 0 900 900 0 0adjrange 11 0 0 900 900 0 0# rxrangerxrange 0 1000 2000rxrange 1 1000 2000rxrange 2 1000 2000rxrange 3 1000 2000# masterset looptime = 2000set gyro_sync = ONset gyro_sync_denom = 2set align_gyro = DEFAULTset gyro_hardware_lpf = 20HZset gyro_lpf_hz = 60set moron_threshold = 32set gyro_notch1_hz = 0set gyro_notch1_cutoff = 1set gyro_notch2_hz = 0set gyro_notch2_cutoff = 1set vbat_adc_channel = 2set rssi_adc_channel = 3set current_adc_channel = 1set airspeed_adc_channel = 0set acc_notch_hz = 0set acc_notch_cutoff = 1set align_acc = DEFAULTset acc_hardware = MPU6000set acc_lpf_hz = 15set acczero_x = 140set acczero_y = -31set acczero_z = -345set accgain_x = 4115set accgain_y = 4105set accgain_z = 4117set align_mag = DEFAULTset mag_hardware = NONEset mag_declination = 0set magzero_x = 0set magzero_y = 0set magzero_z = 0set mag_calibration_time = 30set baro_hardware = BMP280set baro_use_median_filter = ONset pitot_hardware = NONEset pitot_use_median_filter = ONset pitot_noise_lpf =  0.600set pitot_scale =  1.000set mid_rc = 1500set min_check = 1100set max_check = 1900set rssi_channel = 0set rssi_scale = 30set rssi_invert = OFFset rc_smoothing = ONset serialrx_provider = SPEK1024set sbus_inversion = ONset spektrum_sat_bind = 0set rx_min_usec = 885set rx_max_usec = 2115set serialrx_halfduplex = OFFset blackbox_rate_num = 1set blackbox_rate_denom = 0set blackbox_device = SERIALset sdcard_detect_inverted = ONset min_throttle = 1100set max_throttle = 1950set min_command = 1099set motor_pwm_rate = 400set motor_pwm_protocol = STANDARDset failsafe_delay = 5set failsafe_recovery_delay = 5set failsafe_off_delay = 200set failsafe_throttle = 1000set failsafe_throttle_low_delay = 100set failsafe_procedure = RTHset failsafe_stick_threshold = 50set failsafe_fw_roll_angle = 100set failsafe_fw_pitch_angle = -45set failsafe_fw_yaw_rate = 50set align_board_roll = 2set align_board_pitch = 22set align_board_yaw = 1800set gimbal_mode = NORMALset battery_capacity = 0set vbat_scale = 110set vbat_max_cell_voltage = 43set vbat_min_cell_voltage = 33set vbat_warning_cell_voltage = 35set current_meter_scale = 400set current_meter_offset = 0set multiwii_current_meter_output = OFFset current_meter_type = ADCset yaw_motor_direction = 1set yaw_jump_prevention_limit = 200set 3d_deadband_low = 1406set 3d_deadband_high = 1514set 3d_neutral = 1460set servo_center_pulse = 1500set servo_pwm_rate = 50set servo_lpf_hz = 20set flaperon_throw_offset = 200set tri_unarmed_servo = ONset reboot_character = 82set imu_dcm_kp = 2500set imu_dcm_ki = 50set imu_dcm_kp_mag = 10000set imu_dcm_ki_mag = 0set small_angle = 180set fixed_wing_auto_arm = ONset disarm_kill_switch = ONset auto_disarm_delay = 20set gps_provider = UBLOXset gps_sbas_mode = AUTOset gps_dyn_model = AIR_1Gset gps_auto_config = ONset gps_auto_baud = ONset gps_min_sats = 5set deadband = 5set yaw_deadband = 5set pos_hold_deadband = 20set alt_hold_deadband = 50set 3d_deadband_throttle = 50set fw_autotune_overshoot_time = 100set fw_autotune_undershoot_time = 200set fw_autotune_threshold = 50set fw_autotune_ff_to_p_gain = 10set fw_autotune_ff_to_i_tc = 600set inav_auto_mag_decl = ONset inav_gravity_cal_tolerance = 5set inav_use_gps_velned = ONset inav_gps_delay = 200set inav_reset_altitude = FIRST_ARMset inav_max_surface_altitude = 200set inav_w_z_surface_p =  3.500set inav_w_z_surface_v =  6.100set inav_w_z_baro_p =  0.350set inav_w_z_gps_p =  0.200set inav_w_z_gps_v =  0.500set inav_w_xy_gps_p =  1.000set inav_w_xy_gps_v =  2.000set inav_w_z_res_v =  0.500set inav_w_xy_res_v =  0.500set inav_w_acc_bias =  0.010set inav_max_eph_epv =  1000.000set inav_baro_epv =  100.000set nav_disarm_on_landing = OFFset nav_use_midthr_for_althold = OFFset nav_extra_arming_safety = OFFset nav_user_control_mode = ATTIset nav_position_timeout = 5set nav_wp_radius = 100set nav_wp_safe_distance = 10000set nav_auto_speed = 300set nav_auto_climb_rate = 500set nav_manual_speed = 500set nav_manual_climb_rate = 200set nav_landing_speed = 200set nav_land_slowdown_minalt = 500set nav_land_slowdown_maxalt = 2000set nav_emerg_landing_speed = 500set nav_min_rth_distance = 1set nav_rth_climb_first = ONset nav_rth_climb_ignore_emerg = OFFset nav_rth_tail_first = OFFset nav_rth_allow_landing = OFFset nav_rth_alt_mode = AT_LEASTset nav_rth_abort_threshold = 50000set nav_rth_altitude = 9000set nav_mc_bank_angle = 30set nav_mc_hover_thr = 1500set nav_mc_auto_disarm_delay = 2000set nav_fw_cruise_thr = 1600set nav_fw_min_thr = 1300set nav_fw_max_thr = 1850set nav_fw_bank_angle = 46set nav_fw_climb_angle = 23set nav_fw_dive_angle = 15set nav_fw_pitch2thr = 10set nav_fw_loiter_radius = 4500set nav_fw_land_dive_angle = 2set nav_fw_launch_velocity = 300set nav_fw_launch_accel = 1600set nav_fw_launch_max_angle = 45set nav_fw_launch_detect_time = 40set nav_fw_launch_thr = 1850set nav_fw_launch_idle_thr = 1000set nav_fw_launch_motor_delay = 500set nav_fw_launch_spinup_time = 100set nav_fw_launch_timeout = 7000set nav_fw_launch_climb_angle = 30set telemetry_switch = OFFset telemetry_inversion = OFFset frsky_default_latitude =  0.000set frsky_default_longitude =  0.000set frsky_coordinates_format = 0set frsky_unit = IMPERIALset frsky_vfas_precision = 0set frsky_vfas_cell_voltage = OFFset hott_alarm_sound_interval = 5set smartport_uart_unidir = OFFset ibus_telemetry_type = 0set ltm_update_rate = NORMALset ledstrip_visual_beeper = OFFset osd_video_system = 0set osd_row_shiftdown = 0set osd_units = METRICset osd_rssi_alarm = 20set osd_cap_alarm = 2200set osd_time_alarm = 10set osd_alt_alarm = 100set osd_main_voltage_pos = 2433set osd_rssi_pos = 3162set osd_flytimer_pos = 2199set osd_ontime_pos = 343set osd_flymode_pos = 2423set osd_throttle_pos = 2177set osd_vtx_channel_pos = 200set osd_crosshairs = 0set osd_artificial_horizon = 2248set osd_current_draw_pos = 2465set osd_mah_drawn_pos = 2497set osd_craft_name_pos = 83set osd_gps_speed_pos = 2275set osd_gps_sats_pos = 3138set osd_gps_lon = 402set osd_gps_lat = 384set osd_home_dir = 2414set osd_home_dist = 2455set osd_altitude_pos = 2295set osd_vario = 2230set osd_vario_num = 2168set osd_pid_roll_pos = 2510set osd_pid_pitch_pos = 2478set osd_pid_yaw_pos = 386set osd_power_pos = 47set i2c_overclock = OFFset debug_mode = NONEset acc_task_frequency = 500set attitude_task_frequency = 250set async_mode = NONEset throttle_tilt_comp_str = 0set input_filtering_mode = OFFset mode_range_logic_operator = ORset stats = OFFset stats_total_time = 0set stats_total_dist = 0# profileprofile 2set mc_p_pitch = 40set mc_i_pitch = 30set mc_d_pitch = 23set mc_p_roll = 40set mc_i_roll = 30set mc_d_roll = 23set mc_p_yaw = 85set mc_i_yaw = 45set mc_d_yaw = 0set mc_p_level = 20set mc_i_level = 15set mc_d_level = 75set fw_p_pitch = 32set fw_i_pitch = 7set fw_ff_pitch = 40set fw_p_roll = 31set fw_i_roll = 7set fw_ff_roll = 40set fw_p_yaw = 6set fw_i_yaw = 10set fw_ff_yaw = 60set fw_p_level = 25set fw_i_level = 5set fw_d_level = 75set max_angle_inclination_rll = 300set max_angle_inclination_pit = 300set dterm_lpf_hz = 40set yaw_lpf_hz = 30set dterm_setpoint_weight =  0.000set fw_iterm_throw_limit = 165set fw_reference_airspeed =  1000.000set fw_turn_assist_yaw_gain =  1.000set dterm_notch_hz = 0set dterm_notch_cutoff = 1set pidsum_limit = 500set yaw_p_limit = 300set iterm_ignore_threshold = 200set yaw_iterm_ignore_threshold = 50set rate_accel_limit_roll_pitch = 0set rate_accel_limit_yaw = 10000set heading_hold_rate_limit = 90set nav_mc_pos_z_p = 50set nav_mc_pos_z_i = 0set nav_mc_pos_z_d = 0set nav_mc_vel_z_p = 100set nav_mc_vel_z_i = 50set nav_mc_vel_z_d = 10set nav_mc_pos_xy_p = 65set nav_mc_pos_xy_i = 120set nav_mc_pos_xy_d = 10set nav_mc_vel_xy_p = 180set nav_mc_vel_xy_i = 15set nav_mc_vel_xy_d = 100set nav_fw_pos_z_p = 50set nav_fw_pos_z_i = 0set nav_fw_pos_z_d = 0set nav_fw_pos_xy_p = 75set nav_fw_pos_xy_i = 5set nav_fw_pos_xy_d = 8set rc_expo = 0set rc_yaw_expo = 20set thr_mid = 50set thr_expo = 0set roll_rate = 11set pitch_rate = 14set yaw_rate = 20set tpa_rate = 33set tpa_breakpoint = 1300#

**Comment by fiam** [comment]
@Jozx900 Please, next time paste your configuration as it is, not as a single line. It's a pain to read it like this.

You don't have AIRMODE enabled. Upgrade to 1.7.3 and type the following in the CLI:

```
feature AIRMODE
save
```

That should make the servos behave as you expect them.

**Comment by Jozx900** [comment]
Sorry about that. I copy from my mobile phone.
# dump

# version
# INAV/OMNIBUSF4PRO 1.7.2 Jul 20 2017 / 11:59:41 (81b85de)

# resources

# mixer
mixer FLYING_WING

mmix reset


# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1000 2150 1480 110 -1 
servo 4 1000 2150 1555 -110 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# servo mix
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature RX_PPM
feature VBAT
feature MOTOR_STOP
feature GPS
feature CURRENT_METER
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE

# map
map AETR1234

# name
name -

# serial
serial 20 1 115200 38400 0 115200
serial 0 1 115200 38400 0 115200
serial 2 1 115200 38400 0 115200
serial 5 2 115200 115200 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 0 1 1300 2100
aux 1 1 0 1150 1700
aux 2 8 0 1700 2100
aux 3 27 2 1825 2100
aux 4 18 0 1900 2100
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 2000
set gyro_sync = ON
set gyro_sync_denom = 2
set align_gyro = DEFAULT
set gyro_hardware_lpf = 20HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6000
set acc_lpf_hz = 15
set acczero_x = 140
set acczero_y = -31
set acczero_z = -345
set accgain_x = 4115
set accgain_y = 4105
set accgain_z = 4117
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set mag_calibration_time = 30
set baro_hardware = BMP280
set baro_use_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 0
set blackbox_device = SERIAL
set sdcard_detect_inverted = ON
set min_throttle = 1100
set max_throttle = 1950
set min_command = 1099
set motor_pwm_rate = 400
set motor_pwm_protocol = STANDARD
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 100
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = 100
set failsafe_fw_pitch_angle = -45
set failsafe_fw_yaw_rate = 50
set align_board_roll = 2
set align_board_pitch = 22
set align_board_yaw = 1800
set gimbal_mode = NORMAL
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 180
set fixed_wing_auto_arm = ON
set disarm_kill_switch = ON
set auto_disarm_delay = 20
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 5
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = OFF
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 1
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 9000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1600
set nav_fw_min_thr = 1300
set nav_fw_max_thr = 1850
set nav_fw_bank_angle = 46
set nav_fw_climb_angle = 23
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 4500
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1600
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1850
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 7000
set nav_fw_launch_climb_angle = 30
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set osd_video_system = 0
set osd_row_shiftdown = 0
set osd_units = METRIC
set osd_rssi_alarm = 20
set osd_cap_alarm = 2200
set osd_time_alarm = 10
set osd_alt_alarm = 100
set osd_main_voltage_pos = 2433
set osd_rssi_pos = 3162
set osd_flytimer_pos = 2199
set osd_ontime_pos = 343
set osd_flymode_pos = 2423
set osd_throttle_pos = 2177
set osd_vtx_channel_pos = 200
set osd_crosshairs = 0
set osd_artificial_horizon = 2248
set osd_current_draw_pos = 2465
set osd_mah_drawn_pos = 2497
set osd_craft_name_pos = 83
set osd_gps_speed_pos = 2275
set osd_gps_sats_pos = 3138
set osd_gps_lon = 402
set osd_gps_lat = 384
set osd_home_dir = 2414
set osd_home_dist = 2455
set osd_altitude_pos = 2295
set osd_vario = 2230
set osd_vario_num = 2168
set osd_pid_roll_pos = 2510
set osd_pid_pitch_pos = 2478
set osd_pid_yaw_pos = 386
set osd_power_pos = 47
set i2c_overclock = OFF
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0

# profile
profile 2

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 32
set fw_i_pitch = 7
set fw_ff_pitch = 40
set fw_p_roll = 31
set fw_i_roll = 7
set fw_ff_roll = 40
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 25
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 0
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 11
set pitch_rate = 14
set yaw_rate = 20
set tpa_rate = 33
set tpa_breakpoint = 1300

#

**Comment by Jozx900** [comment]
Actually we don’t want this mix exist anymore.

**Comment by digitalentity** [comment]
There is no mix between throttle and servos, however there IS a "mix" between motor vibration and servos throught the gyro and PID. Go fly. This is normal.

**Comment by Jozx900** [comment]
Thanks

**Comment by DzikuVx** [comment]
As well as a "mix" between throttle and Iterm that becomes active when throttle is up. I'd say everything is fine here, so closing
