### ISSUE TITLE
1.8-RC1 - default OSD config doesnt show "vario" when you enable it 

### ISSUE THREAD

**Issue by kabturek** [iNavFlight/inav#2367]
It's hidden behind "horizon sidebars" that are enabled by default and cant be moved until one disabled "horizon sliders". Maybe move them right ? (and move "vario num" too)
It does work when changed the positions to:
```
set osd_vario_pos = 2231
set osd_vario_num_pos = 2296
```
before: http://prntscr.com/gyugl1
after: http://prntscr.com/gyug9c

**Comment by fiam** [comment]
@kabturek Thanks for the report. I had noticed this some time ago but then forgot about it, thanks for reminding me. Working on a fix.
