### ISSUE TITLE
Servos Tab....Confusing terminology.?

### ISSUE THREAD

**Issue by EnglishTurbines** [iNavFlight/inav#2374]
Can someone explain what Servo # 0 is please?

It's actually Servo, or more accurately, PWM Output 1......So why not call it PWM 1????

Servo # 0 or Servo # 2 is meaningless terminology anyway because it's actually referring to PWM (servo) outputs as labelled on the PCB schematic diagram as far as I can see. It's the Schematic pcb diagram that people look at to determine which pwm output number is which, important because mixing is done on the board, and specific servos need to be plugged into these outputs as per the diagrams inside iNAV, which are very useful. 

Im also confused why there are reversing tickboxes inside the same Tab, because reversing is achieved using either +100 or -100..?.....So there are two ways to do the reversing?....Confusing.

If there is a good explanation, Im listening....:)......Thanks.

**Comment by Dronek** [comment]
You might find your answers [here](https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md).

As far as I understand, there is a distinction between servo slots (# 1....) and actual PWM outputs. You can e.g. map any servo slot to any PWM output and so on.
