### ISSUE TITLE
Not defining USE_UNDERCLOCK cause skipping of systemClockSetup

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#2375]
I was trying to save some space on F1 and I found an issue that will impact also F3. 

If you don't define USE_UNDERCLOCK in common.h the systemClockSetup function called in fc_init.c is not executed causing the CPU clock not correctly set.

First noticeable fact is looptime of 5ms instead of the configured 2ms.

I think a quick rework of #defines will solve easily the issue.

**Comment by digitalentity** [comment]
I'm adding this to 1.9 milestone since only custom-built targets seem to be affected
