### ISSUE TITLE
ANYFC F7 PMW1 channel physical damage

### ISSUE THREAD

**Issue by ahfynjj** [iNavFlight/inav#2378]
My ANYFC F7 PMW1 channel physical damage, no output, may I be able to adjust the output of this channel to other channels, or can set the output of each channel settings?

My English is not good, I hope you can understand

**Comment by ShikOfTheRa** [comment]
Yes...

https://github.com/iNavFlight/inav/wiki/Custom-mixes-for-exotic-setups

**Comment by DzikuVx** [comment]
Like mentioned by @ShikOfTheRa  it can be done with custom mixer
