### ISSUE TITLE
Multirotor Auto Launch Feature 

### ISSUE THREAD

**Issue by sammichael25** [iNavFlight/inav#2404]
Would it be feasible to add an auto launch feature for multirotors that once activated will launch aircraft to a pre-defined height (eg. 2m above ground) with the aircraft in position and altitude hold mode?

**Comment by rb1205** [comment]
A basic waypoint mission would do what you're asking, no need for a dedicated mode

**Comment by michaelvanderhoek** [comment]
@rb1205 , is this true? when you arm the copter on the ground and hit waypoint feature it will autolaunch? I think it will crash because it doesnt has any height.
