### ISSUE TITLE
fixed_wing_auto_arm broken since version 1.7.3

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav#2406]
fixed_wing_auto_arm no longer works since version 1.7.3 (neither does in 1.8-RC1, RC2)

Omnibus F3 pro
- Fixed wing
- fixed_wing_auto_arm=on
- Feature Motor_stop

Flash Version 1.7.2: Push throttle stick up - motor auto-arms and starts spinning
Flash Version: 1.7.3: Push throttle stick up - motor does not arm. (stick arming still working with fixed_wing_auto_arm=off)
Flash Version 1.8 RC1/RC2: Push throttle stick up - motor does not arm. (stick arming still working fixed_wing_auto_arm=off)
Flash Version 1.7.2: Push throttle stick up - motor auto-arms and starts spinning.

Has this option been removed?

**Comment by digitalentity** [comment]
Fix ready. Closing

**Comment by digitalentity** [comment]
@Arvycka found a bug, thanks for reporting. Will be fixed in next build.

**Comment by Arvycka** [comment]
Thanks. Sent you a beer :)

2017 spal. 27 02:55 pop. "Konstantin Sharlaimov" <notifications@github.com>
rašė:
