### ISSUE TITLE
Allow servo outputs on multicopter mixer and a BeeRotorF4 board 

### ISSUE THREAD

**Issue by chan2328** [iNavFlight/inav#2434]
whatever mixer type (quadx, custom, customairplane) i used in beerotor F4.  mmix and smix can not change   any output pin ordering, for my case, i connected 4 motors to output 1 to 4, and 1 servo to output 7 showed as picture. i have tried a lot of times to change the value of mmix and smix. base on https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md .  it does not change anything in the output ordering. 
![beerotorf4_front](https://user-images.githubusercontent.com/32637631/32215170-2890f82c-be5c-11e7-8ec0-d9adab7eb7ba.jpg)

**Comment by digitalentity** [comment]
`mmix` and `smix` can't change output ordering, they are designed to map mixer input (roll, pitch, yaw, throttle) to outputs. Order and functionality of outputs is board-specific.

**Comment by chan2328** [comment]
@digitalentity thanks for reply, so, at this moment, the connection showed in above picture is not able to work at current inav firmware.

**Comment by digitalentity** [comment]
@chan2328 what do you want servos for? I believe we can allow 8th output to be a servo on multicopters.

**Comment by chan2328** [comment]
@digitalentity the attached picture shows what i designed, which is a camera mounted on a servo.  i want to see the view by changing my camera's angle with the servo when using GPSHOLD, or for landing purpose. 
![3](https://user-images.githubusercontent.com/32637631/32264048-aece1c56-bf17-11e7-91be-b7a10d5dd936.jpg)

**Comment by digitalentity** [comment]
Ok, I see. I'll change the name of the issue to reflect the the problem better.

**Comment by chan2328** [comment]
@digitalentity thanks for help.

**Comment by chan2328** [comment]
@digitalentity any chance to change pin 5,6 to be servo out in release 1.9?

**Comment by shellixyz** [comment]
@chan2328 Please test this build enabling servos to be used for multirotors on PWM outputs 5 to 8 and report your results in #2829:
[inav_1.9.0_BEEROTORF4.hex.zip](https://github.com/iNavFlight/inav/files/1754559/inav_1.9.0_BEEROTORF4.hex.zip)

**Comment by digitalentity** [comment]
Fix merged. Closing
