### ISSUE TITLE
Functioning setup for Omnibus F7V2 requested

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#2436]
To make a long story short, I have a TBS G2 frame with TBS Endurance motors and a 4-in-1 ESC (Lumenier BLHeli_S 35A 4-in-1 12v / 5v BEC DSHOT ESC +Current Sensor). In Betaflight 3.2.1 it flew perfectly. Switching to iNav, I tried several ESC protocols, none of which would work. The motors would twitch or else quad would lift off violently and flip over. I tried to revert back to Betaflight, but from that point onward, the quad continued to behave erratically even in betaflight (going back to Dshot600). So, I re-calibrated the motors and one of them literally started smoking. 

I since replaced the motor and upgraded the ESC to a Lumenier Blheli_32 4-in-1. 

Now, it flies again perfectly in Betaflight 3.2.1. So, I crossed my fingers and again flashed iNav (latest). This time I started with Multishot protocol. Quad zips up in the air a few inches and does a violent flip 360 degrees. Yes, I HAVE done a throttle calibration. I'm not messing with protocols anymore until someone can give me settings that are verified to work with a setup like this. Just to be clear, I have installed iNav and flown with it on 2 other quads I built. 

Some will claim that software settings cannot ruin hardware. I disagree (https://oscarliang.com/esc-on-fire-burn-smoke/). But, at the very least I want/choose to be cautious. I can't afford to have to replace another ESC and/or motor(s). Below is a dump of the latest setup I tried. Maybe someone can give me some workable settings. 

`# version
# INAV/OMNIBUSF7V2 1.8.0 Oct 24 2017 / 07:24:22 (0f1975ce)

# resources

# mixer
mixer QUADX

mmix reset

# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1000 2000 1500 100 -1 
servo 4 1000 2000 1500 100 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# servo mix
smix reset

# feature
feature -RX_PPM
feature -VBAT
feature -RX_UIB
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature MOTOR_STOP
feature GPS
feature TELEMETRY
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED

# map
map AETR5678

# name
name -

# serial
serial 20 1 115200 38400 0 115200
serial 0 64 115200 38400 0 115200
serial 1 0 115200 38400 0 115200
serial 2 0 115200 38400 0 115200
serial 5 2 115200 115200 0 115200
serial 6 0 115200 38400 0 115200

# aux
aux 0 0 0 1925 2100
aux 1 1 1 900 1600
aux 2 20 1 1350 2100
aux 3 3 3 1400 1600
aux 4 9 3 1400 1600
aux 5 8 3 1850 2100
aux 6 21 2 1450 2100
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 2000
set gyro_sync = OFF
set gyro_sync_denom = 2
set align_gyro = CW270
set gyro_hardware_lpf = 42HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set gyro_to_use = 0
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = CW270
set acc_hardware = MPU6000
set acc_lpf_hz = 15
set acczero_x = 123
set acczero_y = -61
set acczero_z = -203
set accgain_x = 4086
set accgain_y = 4113
set accgain_z = 3989
set align_mag = DEFAULT
set mag_hardware = HMC5883
set mag_declination = 0
set magzero_x = 128
set magzero_y = -268
set magzero_z = -121
set mag_calibration_time = 30
set baro_hardware = BMP280
set baro_use_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set receiver_type = SERIAL
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 100
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = CRSF
set sbus_inversion = ON
set rx_spi_rf_channel_count = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set sdcard_detect_inverted = ON
set min_throttle = 1050
set max_throttle = 1900
set min_command = 980
set motor_pwm_rate = 2000
set motor_pwm_protocol = MULTISHOT
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 100
set failsafe_procedure = SET-THR
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 1800
set gimbal_mode = NORMAL
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 44
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 10
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set gps_provider = UBLOX7
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = ALWAYS
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 1000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 5000
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 5000
set nav_fw_launch_climb_angle = 18
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = METRIC
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_percent = OFF
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set osd_video_system = 0
set osd_row_shiftdown = 0
set osd_units = METRIC
set osd_rssi_alarm = 20
set osd_cap_alarm = 0
set osd_time_alarm = 10
set osd_alt_alarm = 100
set osd_artificial_horizon_reverse_roll = OFF
set osd_crosshairs_style = DEFAULT
set osd_left_sidebar_scroll = NONE
set osd_right_sidebar_scroll = NONE
set osd_sidebar_scroll_arrows = OFF
set osd_main_voltage_pos = 2060
set osd_rssi_pos = 23
set osd_flytimer_pos = 311
set osd_ontime_pos = 279
set osd_flymode_pos = 396
set osd_throttle_pos = 65
set osd_vtx_channel_pos = 200
set osd_crosshairs_pos = 0
set osd_artificial_horizon_pos = 2248
set osd_current_draw_pos = 2145
set osd_mah_drawn_pos = 2177
set osd_craft_name_pos = 84
set osd_gps_speed_pos = 2103
set osd_gps_sats_pos = 2400
set osd_gps_lon_pos = 2450
set osd_gps_lat_pos = 2432
set osd_home_dir_pos = 2414
set osd_home_dist_pos = 2081
set osd_altitude_pos = 2049
set osd_vario_pos = 183
set osd_vario_num_pos = 248
set osd_pid_roll_pos = 322
set osd_pid_pitch_pos = 354
set osd_pid_yaw_pos = 386
set osd_power_pos = 47
set osd_air_speed_pos = 163
set osd_ontime_flytime_pos = 2423
set osd_rtc_time_pos = 407
set osd_messages_pos = 2465
set osd_gps_hdop_pos = 320
set osd_main_cell_voltage_pos = 44
set osd_throttle_auto_thr_pos = 70
set osd_heading_graph_pos = 82
set osd_efficiency_pos = 161
set i2c_speed = 400KHZ
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0
set tz_offset = 0

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 50
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 5
set fw_i_pitch = 7
set fw_ff_pitch = 50
set fw_p_roll = 5
set fw_i_roll = 7
set fw_ff_roll = 50
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500

# 
`

**Comment by DzikuVx** [comment]
Try one of Presets that is close to your setup. ESC protocol is the least important thing

**Comment by VoicOfReason** [comment]
I tried that once already but it didn’t help any. What I’m looking for is workable, verified settings on this flight controller.

**Comment by DzikuVx** [comment]
Flight controller has nothing to do. Really. And hoping you will find anyone alse with the same setup are rather slim. I strongly suspect 5" GPS Racer preset will be suitable

**Comment by VoicOfReason** [comment]
Ok ill try that setup.

-- 
Peter Freund
Sent with Airmail

**Comment by digitalentity** [comment]
`set gyro_hardware_lpf = 42HZ` this is where your violent shakes come from. 

Please understand that Betaflight has an advantage of being pre-tuned for racing setups, because it's not being used on anything else. INAV doesn't have this advantage - this is why we have presets.

**Comment by VoicOfReason** [comment]
Ok. I still don’t get why my other quad with an f4 works fine with iNav
whereas this one with f7 won’t even fly.

**Comment by VoicOfReason** [comment]
What should I set gyro_hardware_lpf to?

**Comment by digitalentity** [comment]
>Ok. I still don’t get why my other quad with an f4 works fine with iNav whereas this one with f7 won’t even fly.

@VoicOfReason if you will post a dump of your F4 quad settings, I could get a hint what's different.

> What should I set gyro_hardware_lpf to?

For miniquads a value of choice is `256HZ`. Preset will handle that for you.

**Comment by VoicOfReason** [comment]
Nope nope nope nope. It will NOT fly. I did all of what you said. I did 5" GPS racer preset, and I even changed lpf to 256. With the smallest throttle it violently flips over onto its back. There is something seriously wrong here. I need help. I'm not going to ruin my quad again with this. Is there anyone how has ACTUALLY flown on the F7 with iNav who can give me their settings???

**Comment by digitalentity** [comment]
Flies fine for me. Flipping over usually means that either motor order or board alignment is incorrect. Since the board doesn't have an alignment arrow, our default board orientation might be different from Betaflight's. Please verify that model in the Configurator follows actual copter movements.

For the record. Just did a hover test on Omnibus F7 V2. Default settings.

**Comment by VoicOfReason** [comment]
Yes! That did it. Betaflight's alignment was very different than iNav. So, a few quick questions:
1. LED is not working yet despite me trying to configure in GUI. Any workaround for this?
2. I know this is a tuning issue, but it's twitch a bit when hovering. Which PID should be adjusted?
3. Throttle seems a bit mushy. In betaflight, the throttle felt more crisp and responsive. 

Should I be adjusting PID values for NAV settings as well?
