### ISSUE TITLE
PPM / S-BUS on F1 (Naze32) not working

### ISSUE THREAD

**Issue by Ginganinja82** [iNavFlight/inav#2458]
### Board and Version
_Afroflight Naze32 Rev6.
_1.7.3 - NAZE - 2017-9-10 10:53 _

# version
# INAV/NAZE 1.6.1 Mar  9 2017 / 00:36:58 (6c878ae)

### Behavior
* PPM signal not responding on FlySky receivers. (Tested with FS-IA6B and FlySky X6B)
* BetaFlight and Cleanflight works fine (not a hardware problem)
* Tested with Two rev6 boards. 

Vanilla Firmware load no additional config.

**Comment by stronnag** [comment]
1. F1 boards are no longer supported
2. PPM and Serial RX work for me on F1 
3. 1.6.1 is obsolete and no one is going to support it

**Comment by sergeysi779** [comment]
I think there was a bug either in iNav or iNavConfigurator. PPM and PWM were mistakenly swapped. Try changing the setting to PWM or upgrade configurator and iNav.

**Comment by digitalentity** [comment]
@fiam @DzikuVx can you look into it? I'll try to confirm with latest configurator as well.

**Comment by DzikuVx** [comment]
Check what? INAV/NAZE 1.6.1 or 1.7.3? but ok, i will try to verify on 1.7.3

**Comment by Ginganinja82** [comment]
Thanks guys. 

DzikuVx - I have installed the latest on both. Configurator(1.8.1) and firmware on 1.7.3. I was not aware that the Naze boards or F1 chips are not supported anymore. quite sad as it it still very cheap on ebay for budget builds.

Attachments for reference though... (this on Vanilla. No additional changes made) 

![screen shot 2017-11-08 at 7 14 57 pm](https://user-images.githubusercontent.com/24269801/32563172-32bf1f96-c4b9-11e7-97f9-35bf7f47b5d2.png)
![screen shot 2017-11-08 at 7 15 12 pm](https://user-images.githubusercontent.com/24269801/32563174-32f0c73a-c4b9-11e7-82f6-7cb7836478cb.png)

**Comment by Schalonsus** [comment]
I think i saw some configuration issues with 1.8 configurator and 1.7.3 too. Use the 1.7 configurator

**Comment by Ginganinja82** [comment]
Thanks! I'll try 1.7.2. Cannot find 1.7 on iNavFlight/inav-configurator release page..

**Comment by danarrib** [comment]
I can confirm: On Naze32, INAV 1.7.3 (last version available for this board), the Configurator 1.8.1 do not work. Using the Standalone 1.7.3 version of Configurator everything works fine.

**Comment by jstremmler** [comment]
If I look on the screenshot of your configurator above you did not configure a PPM RX but a serial RX with IBUS. 

Did you then connect the IBUS signal of your RX correctly to pin 3 of the NAZE instead of pin 1? 

- signal of ppm RX is connected to pin 1 of the NAZE32
- signal of a serial RX is connected to pin 3 of the NAZE32

**Comment by Ginganinja82** [comment]
@danarrib - THANK YOU ! Confirmed, 1.7.3 standalone works on PPM... happy days ! 

@jstremmler - Thank I tried both.. the screenshots are for the "missing" sliders when selecting i-bus as the serial input..

**Comment by fiam** [comment]
Just submitted a PR for the configurator that fixes this problem: https://github.com/iNavFlight/inav-configurator/pull/303

**Comment by JyskMaker** [comment]
In 1.8.1 just set it to "PWM RX INPUT" if you want to use PPM
