### ISSUE TITLE
Support for OMNIBUS F4 Pro Corner

### ISSUE THREAD

**Issue by RMFPV** [iNavFlight/inav#2463]
### Board and Version
_Omnibus F4 Pro Corner from Airbot
_Version of INAV used goes here_1.8

_Use CLI command `version` and put its output here_
INAV/OMNIBUSF4PRO 1.8.0 Nov  1 2017 / 06:34:32 (912d1315)

### Behavior
* _Describe the problem_

SBUS FRSKY X4R all channels are 1500 and not moving
Same config and settings with Cleanflight FW works very well
SBUS connected to UART3 

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

https://pastebin.com/bsQFMijC

**Comment by digitalentity** [comment]
On OMNIBUSF4PRO board inverted S.Bus is only supported on UART1

**Comment by RMFPV** [comment]
This is strange. There is no inverter on UART1. But there are invertors at both UART3 and 6. Please check documentation for Pro Corner.

Anyway as I mentioned it works with Cleanflight FW at Uart3. Why can't you make it also work with Inav?

**Comment by digitalentity** [comment]
Then we need a separate target definition for Pro Corner which is apparently a different design than other Omnibus Boards.

**Comment by RMFPV** [comment]
Will be this issue fixed in a new FW, or you can share a patched FW now?

If you will support this board can you please also add I2C support? It's not mentioned in original manual at all. 
Thank you.

**Comment by digitalentity** [comment]
It's hard to tell. We've just discovered the issue with S.Bus on UART3 thanks to you.
Regarding I2C support - I need to check the available pins. If UART3 has an inverter - shared I2C/UART3 is not possible. Most likely there won't be any I2C support due to incompatible hardware design.

**Comment by RMFPV** [comment]
It says that inverter at UART3 can be switched off by pulling PC9 as low. Can this help with I2C support?

**Comment by digitalentity** [comment]
No, since for I2C pin has to be bi-directional. Inverter is an uni-directional device regardless of being turned on or off

**Comment by RMFPV** [comment]
I see. Thank you for the explanation. They also suggest to desolder inverter from the board if it's not needed. Will that help?

**Comment by ShikOfTheRa** [comment]
Just checked diag. can confirm UART3 and 6 have inverter. UART1 does not. PC9 is inversion control for UART3. PC8 for 6
No inverter for UART1
I2C breakout is I2C2 hence is is shared with UART3
Also note PPM1 input is connected to UART6 RX prior to inversion.

**Comment by digitalentity** [comment]
OMG this Pro Corner board is so messed up!

**Comment by DzikuVx** [comment]
BTW, I've changed title of this issue since apparently it was refering to F3, not F4

**Comment by digitalentity** [comment]
@DzikuVx thanks, I probably did a typo without noticing

**Comment by RMFPV** [comment]
Hi, any news on fixing SBUS?
I've tested Naza GPS on UART1 - works fine.
The only concern that there are a lot (22715) errors at GPS statistic window and 3 timeouts. What does it mean?

**Comment by RMFPV** [comment]
Hi, any news? Will it be fixed?

**Comment by BFMav** [comment]
Hi I just got this board, need to use Sbus on Uart 3, I have an external telem on uart 1, I want to add Naza GPS on uart 6 but I need to disable the inverter, how do I do this ?

**Comment by RMFPV** [comment]
It looks like developers doesn't want to support this board. Nothing changed for many months. This is strange attitude. 
This board must be removed from the supported boards list, because it's misleading.

**Comment by DzikuVx** [comment]
@MFlghts and how do you think developers should get few pieces of those boards? Try add a new traget without a board to test. You think we should invest both our time and money buying things we do not really need?

**Comment by fiam** [comment]
@MFlghts It's not that we don't want to support it, but time is limited and none of us have this board. That means that we'd need to write the code to support it "blindly" and ask users to test it on our behalf. Unfortunately, that's very time consuming and a pretty ineffective use of developer resources.

On the other hand, if you have the board and you want to add support for it in INAV, PRs for it would be welcome.

**Comment by digitalentity** [comment]
@MFlghts None of the active developers has the board to test the fixes. As @fiam wrote developing blindly is a waste of developer time that could be used more effectively. 

Corner was designed for simple wiring for racing quads. Given that Corner board is most likely incapable of supporting I2C it will only be usable on airplanes where it won't be of much convenience because of form factor.

Where is this board listed as supported?

**Comment by RMFPV** [comment]
@digitalentity 
it's listed here https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md
I agree that this is not the best board, and it's better to leave it alone, and there is no any problem with that. The problem will come when people buy it, because it is in the list of the supported boards and they will have to trash their money because it's not going to be supported. This is quite tricky situation. Not very nice in fact.
I hope that it's not gonna happen with the other boards like Kakute F4 V2 or else.

**Comment by stronnag** [comment]
It is not on the list of supported boards; https://github.com/iNavFlight/inav/wiki/Supported-boards

That there is a board document is no endorsement of "supported".

**Comment by RMFPV** [comment]
You are wrong, because your link leads to a text that refers to the file I mentioned, and it means that the board is supported. 

**See the docs folder for additional information regards to many targets in INAV, to example help in finding pinout and features.**

If it's not supported why the hell do you have this line in the docs with the header Omnibus F4 Pro Corner??!
**Uses target OMNIBUSF4PRO**

Please don't make an idiot out of me. If board is not supported it should not be mentioned anywhere in the docs with such a statement.

**Comment by digitalentity** [comment]
Omnibus F4 Pro Corner **is** supported. Board boots and is flyable.

The only things that don't work are I2C (due to hardware design issues) and inverted S.Bus. Works fine with non-inverted S.Bus, Crossfire or IBUS.

If you feel that S.Bus support is mandatory - please open an issue specifically for that

**Comment by RMFPV** [comment]
Without I2C and SBUS this board is useless for me. 
I think the board DOC file must be updated with the resent info, and this issue can be closed.
Thank you.

**Comment by digitalentity** [comment]
@MFlghts While we might try fixing S.Bus inversion, I2C support is not possible on this board. Thus as I previously said - this board is not suitable for INAV anyway.

Indeed, we should amend the docs stating a warning that "Corner" doesn't have S.Bus inversion and I2C.

**Comment by RMFPV** [comment]
In fact this board can be used for fixed wing, and even for multis with Naza GPS. But it also has some bad issues with noisy onboard dc-dc that affects imu, so I believe it's better to forget it.

**Comment by digitalentity** [comment]
I'll submit a PR to amend the docs with a BIG WARNING about this board.

**Comment by RMFPV** [comment]
Good. Thanks.

**Comment by jstremmler** [comment]
Why should the Omnibus F4 Pro corner not work properly with iNav? I left SCL and SDA where iNav definies them to be (at UART3), connected the SBUS RX to UART 6 (works fine) and have connected the GPS to UART1......

**Comment by Dinirofpv** [comment]
I have same problem, inav 1.9.1 sbus not working on uart 3 and 6. Im stuck for days try to put sbus working!!!

**Comment by jstremmler** [comment]
Try SBUS on UART1 and GPS on UART6!

**Comment by Frank-Seider** [comment]
I have GPS on UART 1 and S-Bus on UART 6 and it works, but the UART 3 which I want to use for telemetry do nothing. Is it because I2C is on UART 3?  I try to use Softserial but no success. What can I do?
