### ISSUE TITLE
DFU command

### ISSUE THREAD

**Issue by Martijn666** [iNavFlight/inav#2466]
I use CLI command DFU a lot to flash firmware. It seems to have been removed. Can you bring it back, or is DFU mode no longer supported? Using configurator 1.8.1

**Comment by DzikuVx** [comment]
I can not confirm. Just testes on Airbot F4 , INAV 1.8, Configurator 1.8.1 and DFU command works just fine

**Comment by teckel12** [comment]
I used it on Omnibus F4 Pro just yesterday and it worked as well.

**Comment by Martijn666** [comment]
I just turned in. Will check again tomorrow. Thanks for your quick response

**Comment by DzikuVx** [comment]
I suppose we can close this one. If new data appears please reopen
