### ISSUE TITLE
LED Strip not working with Matek F405 AIO 

### ISSUE THREAD

**Issue by Dom33l** [iNavFlight/inav#2479]
Hi
LED strip is not working with Matek F405 AIO FC and 1.8 - MATEKF405 - 2017-11-1 1 10:13 (stable).  I have tested the same board in the exact setup with Betaflight for MATEK F405  and it works fine.

**Comment by stronnag** [comment]
Have the read the board documentation https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20MatekF405.md and in particular the wiring for LED strip in iNav?

**Comment by Dom33l** [comment]
Thank you ! sorted :)
