### ISSUE TITLE
Does AnyF7 have barometer? Supported in iNav?

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#2484]
I can't seem to find a straight answer as to whether the AnyF7 FC has a barometer. I know iNav lists it as a target, but even readytoflyquads seems to show a picture of their AnyF7 without a barometer (comparing pictures to others online). 

Anyone using the AnyF7 board successfully with iNav?

**Comment by DzikuVx** [comment]
This should answer all your questions: https://quadmeup.com/anyfc-f7-and-a-missing-baro-problem/
