### ISSUE TITLE
Disabling stick command profile selection 

### ISSUE THREAD

**Issue by joeclone** [iNavFlight/inav#2485]
I'm running 1.7.3 on a flying wing. Crashed the other day coz accidentally changed profiles while on ground fiddling with the tx sticks. Don't see any mention in the wiki about possibility of disabling profile selection by stick command. Would like to have the option to do that like how blheli does, disabling tx programming.

**Comment by digitalentity** [comment]
Seems like a nice feature to me. I also only use one profile and accidentally switching to another one may cause bad stuff to happen.

We can dedicate a feature bit to enabling profile selection (enabled by default).

**Comment by joeclone** [comment]
Thats good to hear. Yea enabled at default and maybe a tick box on pid page option to disable by the user.  Thanks.

**Comment by Redshifft** [comment]
Excellent idea + this would enable us to use 2 stick arming with less fear of "in Air" disarm and save another switch or two (if you run an arm guard switch)

**Comment by digitalentity** [comment]
#2830 merged. Closing
