### ISSUE TITLE
F3Neo VTX not working

### ISSUE THREAD

**Issue by meep2** [iNavFlight/inav#2489]
### Board and Version
F3Neo FPV Stack
inav 1.8

INAV/SPRACINGF3NEO 1.8.0 Nov  1 2017 / 06:26:33 (912d1315)

### Behavior
I don't get a VTX signal from a F3Neo VTX.
With Cleanflight, it works as intended but I can't get it to work in inav.

If this VTX is not supported yet, this might be a  new feature request.

Thank you

**Comment by shellixyz** [comment]
I believe this is being worked on. See  #2471

**Comment by meep2** [comment]
Great, thanks the link.
