### ISSUE TITLE
Шрифты для OSD в прошивке 1.8.0 для OMNIBUS не загружаются

### ISSUE THREAD

**Issue by librol** [iNavFlight/inav#2497]
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by DzikuVx** [comment]
I'm sorry, but there is no content here. I'm forced to close it
