### ISSUE TITLE
CLEANUP: Unify usage of USART/UART

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#250]
In different parts of the code USARTx and UARTx #defines are mixed up which causes confusion.

**Comment by martinbudden** [comment]
This will happen as part of issue https://github.com/iNavFlight/inav/issues/338 - Convert device drivers to new IO

**Comment by martinbudden** [comment]
Fixed as part of issue https://github.com/iNavFlight/inav/issues/338
