### ISSUE TITLE
Throtle control during crash in RTH

### ISSUE THREAD

**Issue by satesinz** [iNavFlight/inav#2500]
Hi! I would like to know in INAV what happens with the throttle if the plane crashes during its way back to launch point in rth.
Does it stop the motor? Does it detects zero speed or some safetey measures like the expensive OSDs?
My eagletree doesnt engage the motor if its detects a crash (no gps speed) or low altitude.
I would like to know some of that because im thinking about mounting INAV on my wing and im scared of that.
Thaaankss!!﻿

**Comment by krzysztofmatula** [comment]
Some related discussion is here: #2331
