### ISSUE TITLE
CLEANUP: LEDSTRIP code cleanup

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#251]
Unify DMA handling code, catch-up with CF

**Comment by DzikuVx** [comment]
I was looking what CF done with LED and it will be big task. There are many, many changes and commits there

**Comment by digitalentity** [comment]
Yes, but we might be able to save some space and also clean up the hardware
part of the code.

**Comment by martinbudden** [comment]
I think it is worthwhile to include this. I reckon it will save around 500 bytes of ROM, which might just be enough to include the LED code in the CC3D build.

**Comment by shaw05** [comment]
Would also supercede issue #199

**Comment by majik12345** [comment]
The LED changes dont appear to be too much work, but in any case I would suggest before any more new features are added or worked on catching up with the current cleanflight commits should be a priority

**Comment by gaelj** [comment]
Parameter groups would be nice to have first, for one thing.

**Comment by digitalentity** [comment]
@gaelj it's peing slooooooowly worked on in #151

**Comment by skaman82** [comment]
@digitalentity Can you include the current LED functionality from CF in 1.2 or is it too much work? Having the GPS state in LED Strip is realy a nice thing. Blink Mode too.

**Comment by gaelj** [comment]
It can be easily adapted from the Betaflight version, which does not use PGs.
