### ISSUE TITLE
Runtime calibration fails with acc / gyro rationalisation (f416435e)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#2524]
As noted in #2503, the new acc / gyro rationalisation appears to break run-time calibration (tested on SPRF3 with #2503 and Omnibus with just  `# INAV/OMNIBUS 1.8.1 Nov 28 2017 / 17:34:27 (f416435e)`

* CLI reports 'CAL' as an arm blocker
* Configurator reports "Run-time calibration" arm blocker
* 3D model is not stable

**Comment by digitalentity** [comment]
I have a hunch that it might be related to one of recently merged PRs: #2515, #2516, #2517 #2518 or #2520

**Comment by digitalentity** [comment]
Nailed it.
