### ISSUE TITLE
Accelerometer not working correctly in 1.8.1 at #2527 iNavFlight/de_fix_acc_calculation

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#2531]
I flashed my OMNIBUS F3 with latest development  77a2e859e Merge pull request #2527 from iNavFlight/de_fix_acc_calculation and I found out that accelerometer isn't working right when the board is upside down.

The acc is calibrated and I tried even to recalibrate it on 1.8.1
No special configuration applied. Just stock + calibration.

The accZ should indicate -1G when upside down but as soon I rotate the board all the axis tend/go to zero.

Working 1.8 build

![screenshot 2017-11-29 13 16 23](https://user-images.githubusercontent.com/20860004/33374791-dc24bfec-d507-11e7-934c-7d71b0e7da5b.jpg)

Not working 1.8.1 build:

![screenshot 2017-11-29 13 15 59](https://user-images.githubusercontent.com/20860004/33374793-dc54144a-d507-11e7-97b2-c3620e678f5c.jpg)

**Comment by digitalentity** [comment]
Appears to be a harmless type conversion error in MSP layer. Fixed in https://github.com/iNavFlight/inav/pull/2532

**Comment by giacomo892** [comment]
I'll try it later. Thanks for the fix
