### ISSUE TITLE
Request: flip32 second softserial.

### ISSUE THREAD

**Issue by sashan13** [iNavFlight/inav#2533]
### Board and Version
flip32 lite F4 - the one with mpu6050 only. This one: 
![alt text](http://cdna3.zoeysite.com/Adzpo594RQGDpLcjBynL1z/cache=expiry:31536000/resize=fit:max,width:1200/compress/http://s3.amazonaws.com/zcom-media/sites/a0iE000000GWIo4IAH/media/catalog/product/1/2/12-1-2016_3-05-52_pm.jpg "flip32 f4")
### Behavior
This a new feature request!

As the title goes. I'm out of UARTs, and considering the fact that F4 processor has lots of computing power in spare I guess it can handle second softserial. 

I've got it as follows: 
uart1 - s.bus
uart3 - pins occupied by i2c.
uart6 - GPS
softserial1 - smart port telemetry

And now I'm out of UARTs for OSD. 

Reasonable? ;)

**Comment by DzikuVx** [comment]
Yes, but where would you connect TX and RX of sencond SoftwareSerial? There are no reusable pins for us on this board

**Comment by sashan13** [comment]
There is "ch2" pad free - under "UART3 TX" arrow on the picture. 
There are also PB12 and PB13 pads on the bottom - routed to respective pins 33 and 34 on the processor.  IMO using them would be the best. Yes, I've just checked it with multimeter, they are indeed routed that way.
