### ISSUE TITLE
Not an issue but a thank you

### ISSUE THREAD

**Issue by MW2Stambo** [iNavFlight/inav#2534]
Not an issue but a thank you to all you people who have helped or are helping to develop this amazing firmware.
I have looked at it in the past and it all goes way over my head, you must be a bunch of very clever people.
I am so glad there are people in this world that are willing to put their time in to something like this and I don't believe this is recognised often enough.

I currently have it installed on a Omnibus F4 V2 in a Nano Talon and am just embarking on the tuning process (if this wind will go away maybe I could get it done).
I also intend to put it on my Blackout 360 which is set up as a camera platform.

I hope this is not the wrong place to post this as at least here it gets to the intended recipients rather than being lost amongst thousands of posts in the RCG forums.

**Comment by DzikuVx** [comment]
Thank you very much for your thank you. Very much appreciated!
But I will close this issue just to keep open what needs to be kept open ;)
