### ISSUE TITLE
FC / Raspberry / Mavlink / LTM

### ISSUE THREAD

**Issue by diyquad** [iNavFlight/inav#2540]
Hi,

I'm having troubles to send data from my FC to a raspberry.
I only want to get the telemetry data in the raspberry, so i can play with it in python.
(like gps position, altitude, flight mode etc.) 
Here is what i have:
- RPI 2 (and 3)
- FC Omnibus F4 v3
I tryed 2 things:
1) plug the FC & RPI in USB
2) Use the GPIO & UART1 of FC (RX/TX)

But no matter it send no data to the RPI.
I check MSP and/or Mavlink (also tryed LTM) on the Inav Port Configuration, but doesn't change anything: no data.
When i launch Inav directly from the RPI (with Chromium), it works, so i know the USB connection si OK, and i should be able to get all infos, but no

Anyone have an idea how to do it?
Thanks for help

**Comment by digitalentity** [comment]
Bear in mind that if you have both MSP & telemetry enabled on the same port - telemetry data will only be sent out when board is ARMed.

**Comment by diyquad** [comment]
Hey 
Thanks for quick answer.
Ok good to know, only when armed.
Is their a way to get the data anytime?
(only with msp? or telemetry?)


thanks again

**Comment by DzikuVx** [comment]
Yes, use an UART that has only "Telemetry" function assigned to it

**Comment by diyquad** [comment]
Great will try this today and let you know if it work.

**Comment by diyquad** [comment]
Still one question:
Their is not "telemetry" option.
What should i use? FrSky? HoTT? LTM? Mavlink? 

Thanks again

**Comment by DzikuVx** [comment]
Whichever you want and RPi can underdtand
