### ISSUE TITLE
Pixracer vs SPRACINGF3

### ISSUE THREAD

**Issue by aloniko84** [iNavFlight/inav#2550]
Hello,
We are using now SPRACINGF3 with INAV ver 1.8(last released version)
Because there is not enough memory for dubbing we thinking to switch to PIXRACER with F4.
The question is that as I see, last released PIXRACER version is 1.6, and SPRACINGF3 is 1.8.
Is it should work with PIXRACER as SPRACINGF3.

thank you.

**Comment by DzikuVx** [comment]
There are several different flight controller board with F4 or even F7 CPU. Just pick one. Pixracer is not popular.

List of supported boards is here: https://github.com/iNavFlight/inav/tree/master/docs

**Comment by aloniko84** [comment]
thank you,
which one would you suggest with a debugging port ?
