### ISSUE TITLE
ANYFC F7 BB log not working in 1.8

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#2553]
Just upgraded from 1.7 to 1.8 and have a problem with BB logging.

After the uprade using a new empty card, in the BB tab, instead of the normal message showing available space, I am getting "FILE SYSTEM STARTING".This creates a FREESPACE.E file of 0KB on the card and not surprisingly, no log folder or files can be created.

Initialising the card in 1.7 then using it in 1.8, new log files can be created in the LOGS folder but they are always shown as 4096KB long and basically contain garbage.

**Comment by sambas** [comment]
F7 would need some porting from BF for SPI_LL driver to make SD card work more reliable.

**Comment by ghost** [comment]
Will this happen in the near future?
Apart from this problem, it is a very good board and I would like to keep using it.
Thanks

**Comment by ghost** [comment]
Well, guess not.
Time to change to another type.

**Comment by digitalentity** [comment]
@sambas when you would be able to look into this?

**Comment by sambas** [comment]
I'm middle of moving my place, so might take a while.

**Comment by digitalentity** [comment]
@sambas noted, thanks. Might have a look at it myself if I have the time. Is the issue fixed in Betaflight?

**Comment by sambas** [comment]
Last time I check it was working ok.

**Comment by digitalentity** [comment]
Ack. I'll have a look.

**Comment by ghost** [comment]
Retested BB log with 1.8 and it is now working correctly.
Only difference, this time I used a formatting tool from the SD Association and not the one included in WIN 10.
According to them, operating system formatting tools may not optimise SDHC cards.
