### ISSUE TITLE
Feature Request: Alternate OSD layouts

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#2567]
MWOSD allowed for having multiple OSD layouts tied to a 3-Position switch. This is very helpful for long-range FPV flights where it's sometimes desirable to switch to a lighter OSD layout while still maintaining some user-configured vital flight stats visible on the alternate screens.

What would it take in order to add such a feature to the built-in OSD functionality within iNav?

**Comment by krzysztofmatula** [comment]
I think the feature is already planned. See: #2477

**Comment by digitalentity** [comment]
Done.
