### ISSUE TITLE
Any chance to get Omnibus F4 Channel Forwarding working? [support]

### ISSUE THREAD

**Issue by parnz** [iNavFlight/inav#2571]
I've this board and I don't use LED.
Needed this feature to forward aux to PWM5 and PWM6 to control gimbal
My setup is QuardX mainly use for take video. 

[![omnimbus.png](https://s18.postimg.org/6g68uej5l/omnimbus.png)](https://postimg.org/image/qnjompgmt/)
[![HTB1_D0_ATRFXXXXcz_Xp_XXq6x_XFXXXW.jpg](https://s18.postimg.org/qnjomre2x/HTB1_D0_ATRFXXXXcz_Xp_XXq6x_XFXXXW.jpg)](https://postimg.org/image/3yuhn6wp1/)
[![HTB1r5_Qs_RFXXXXbba_XXXq6x_XFXXXs.jpg](https://s18.postimg.org/514o5r2nt/HTB1r5_Qs_RFXXXXbba_XXXq6x_XFXXXs.jpg)](https://postimg.org/image/py0waf0ol/)

I read some where that because timer conflict.
I know coding as I'm a programmer but in the MCU world don't know how pin and timer work.
I do coding in Arduino but there is no timer and pin related.
 
 Any suggestions are all appreciated.
Thanks

**Comment by chan2328** [comment]
same matter #2434, at this moment, inav can not support to change output pin for the mixer QuardX as fixed output pin, I just know that it is available to change output pin by the CLI command "RESOURCE" in betaflight. you can study it https://github.com/betaflight/betaflight/wiki/Betaflight-resource-remapping or may be you can study #2328 to do coding as well.

**Comment by parnz** [comment]
afaik inav does not support command RESOURCE mapping.

But I'm looking into another way - use dedicated hardware (Arduino) to extract IBUS to PWM externally.
[![IMG_20171209_181510.jpg](https://s18.postimg.org/ickjsssnt/IMG_20171209_181510.jpg)](https://postimg.org/image/ipbxyzaxh/)

**Comment by parnz** [comment]
I managed to get it working by adding arduino to decode IBUS to PWM.
I can control gimbal by AUX channel now.
Plus I can detect a failesafe signal which I assigned to channel10.
When failesafe activated it will re-center the camera and return to home.

**Comment by giacomo892** [comment]
Do you mind sharing how you detect failsafe on iBUS?

**Comment by flybabo** [comment]
If you use a FrSky X4RSB receiver, you can access 2 channels (CH9,10) in addition to the SBUS and CPPM.
I'm using those 2 channels for pan and tilt servos of video cam without going through the FC.
Note that if you program the receiver with non-CPPM firmware, you can access 3 channels (CH9,10,11).
