### ISSUE TITLE
betaflight F4 support?

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#2579]
Building a new long range fixeed wing plane, I won a betaflight F4 board in a giveaway, i know it doesn't have a barometer but that's not a big deal as obviously it will have a gps installed.

Is it possible to make a target for this board? i'm assuming that should be relatively easy to do?

[https://www.racedayquads.com/products/betaflight-f4-flight-controller-aio-bff4-by-fpvmodel](url)
charlie

**Comment by shellixyz** [comment]
We are working on it in #2573 but it is not functional yet.

**Comment by wx4cb** [comment]
Ok cool.. i'll follow that thread, this one can be closed. if y'all need help let me know.

**Comment by BlinkFPVita** [comment]
Any update about this? I have the same build waiting for the firmware :) Thanks!
