### ISSUE TITLE
Feature Request: PWM1 for servo

### ISSUE THREAD

**Issue by twistedwings** [iNavFlight/inav#2581]
It would be great if PWM1 could be used as servo output.
Most airplanes only have one motor but possibly many servos.

**Comment by shellixyz** [comment]
There is PR in progress discussing this: #2328

**Comment by twistedwings** [comment]
Not sure if that does what I want.
I stumbled over Mixer.md which says
"Currently, pin id's 0 and 1 can only be used for motor outputs. "

**Comment by shellixyz** [comment]
Yes currently. If you want to use PWM1 for a servo then what is discussed is what will enable this possibility through dynamic allocation of the outputs opposed to static allocation as it is now allowing only max 2 motors and the two first outputs reserved for motor use.

**Comment by jflyper** [comment]
@janbolt It depends on a board and a timer assignments if you can actually use only one motor output, and even if it's possible, it may not be the first output pin. This is a limitation imposed by MCU hardware.

#2328 will allow user to dynamically assign motors and servos within the limitation.
