### ISSUE TITLE
feature GPS broken in 1.8.1 dev

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#2587]
With 7e280defb64 (and possibly a few earlier), `feature GPS` in the CLI is broken.
````
# serial
serial 1 2 115200 38400 0 115200

# feature
Enabled: VBAT BLACKBOX 

# feature GPS
unavailable
````
Enable GPS from the configurator.
````
# feature
Enabled: VBAT GPS BLACKBOX 
````
I'm pretty sure this got me a week ago when the GPS failed to restore from a `diff`.

**Comment by shellixyz** [comment]
Bug is in 7a1491. Fixed in PR #2590

**Comment by stronnag** [comment]
Thanks, I could have grepped for 'unavailable' had I put my mind to it. I wonder how many more of these missing USE_ cases we have?

**Comment by stronnag** [comment]
Closing, fix available

**Comment by shellixyz** [comment]
I'll try to check to see if others could have been missed

**Comment by stronnag** [comment]
#2590 fixes this on SPRF3 but not on OMNIBUS ??? What?

**Comment by shellixyz** [comment]
I can't see how it is possible :grin:

**Comment by stronnag** [comment]
PEBCAK

**Comment by shellixyz** [comment]
I found some more. I opened another PR #2591
