### ISSUE TITLE
Latest MATEK F405 changes prevent legacy F405OSD from booting.

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#2588]
The changes to support the new Matek F405 board variants prevent the legacy F405OSD from booting.
 7e280defb642d85f45cfbb784a57b6e051935400 will not boot.

reverting to 9a3cf280 allows the board to boot again

**Comment by digitalentity** [comment]
Will investigate, thanks

**Comment by digitalentity** [comment]
F405OSD board (not AIO). Boots fine. @stronnag please try flashing with full erase.
Maybe it's some specific config that prevents the board from booting?

**Comment by stronnag** [comment]
It was  flashed with full erase, twice, `dfu-util` with the `mass-erase` option. I'll try the configurator later and post the diff.

**Comment by digitalentity** [comment]
My bad, checked the wrong commit. Indeed it doesn't boot. Strange, I definitely checked that commit before merging.

**Comment by stronnag** [comment]
I did the same thing yesterday on the use_gps fix test. :)

**Comment by digitalentity** [comment]
Damn. Found it! I left a `while(1);` in MPU6000 detection code ("not detected" execution path). Used that when debugging `busDevice` code. Matek board doesn't have the MPU6000 so it got stuck in infinite loop.

**Comment by stronnag** [comment]
That might explain another strange non booting migrate to busdev ...

**Comment by digitalentity** [comment]
Fix ready. Closing. @stronnag thanks for reporting!
