### ISSUE TITLE
Matek F405-MINI Flight Controller 

### ISSUE THREAD

**Issue by toddkurtz** [iNavFlight/inav#2595]
Hi,

I see that iNav supports several of the Matek FCs. Does it by chance run on the Matek F405-MINI Flight Controller??? If not, any chance of adding it? It's a nice small board and I'd love to get iNav and a GPS on a small build. I think I can get the FC and GPS at under 10grams which would be AWESOME!

Thank you!!! Todd

**Comment by HJOGermany** [comment]
Yes, that would be great. 
I use it with the OSD HEX.

**Comment by digitalentity** [comment]
MatekF405-Mini works fine with MATEKF405 target. Dataflash support was added in https://github.com/iNavFlight/inav/pull/2633 so blackbox now works as well. Closing
