### ISSUE TITLE
Add FPV camera control support from BetaFlight

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#2597]
Integrate FPV camera control 'joystick mode' from Betaflight in order to be able to enter FPV camera OSD and adjust camera settings.

**Comment by Snake675** [comment]
camera_control and a pin remapping function would be very nice!

**Comment by xermalk** [comment]
Another vote for this. Its really nice being able to swap day/night modes directly from the osd. And finertune the camera for overcast/sunny and so on.

**Comment by freeshot74** [comment]
Yes please!

**Comment by Lasakro** [comment]
Pretty please?

**Comment by nikpoz** [comment]
Yes I do vote for this one for sure
It would be so nice !!!

**Comment by tonyyng** [comment]
+1

**Comment by LeonLoo** [comment]
This would be very useful, please consider implementing it.

**Comment by pmarkiewicz** [comment]
Any progress on this?

**Comment by alex-martynov** [comment]
See https://github.com/iNavFlight/inav/pull/4969

**Comment by P-I-Engineer** [comment]
i was hoping for this, thank you
