### ISSUE TITLE
Failsafe RTH -> switch to drop when inverted

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#2599]
There should be a additional check if Failsafe RTH that detects the state when copter is upside-down.
It happened today for me: copter went inverted during landing, crashed and motors kept going until I was able to disconnect battery.

I'm not sure this is a feature request or a bug tho ;)

**Comment by shellixyz** [comment]
This would help in that case: #2331

**Comment by giacomo892** [comment]
Also maybe some other sanity check can be placed. Like if during automatic landing the copter banks more lets say than 90 degs then cut motors.

**Comment by DzikuVx** [comment]
another observed condition: should fallback to drop when cell voltage below sane values

**Comment by ErnestFPV** [comment]
Happened to me today, 4s pack dropped below 9v, quad crash landed into woods far away from me, motors were spinning till pack completely died (around 5mins) draining all from pack so i couldnt even use beeper to find quad when i arrived there. So it shouldnt be based on degrees but on pack health compared to cell number.
