### ISSUE TITLE
Omnibus F7 Pro not detecting on iNav 1.8.1

### ISSUE THREAD

**Issue by Gaz93** [iNavFlight/inav#2600]
I'm having issues connecting to my board after flashing to the latest 1.8 iNav firmware and tried 1.7.3 but none give me a successful connect. I have no issues flashing the board in DFU mode and flashing it back to Betaflight lets me connect.

Failed to connect to serial port on every com port usually 5 or 7 for bflight.

What I do get when in device manager after I install inav is two instances of the stm32 virtual port when I plug in usb and I've tried unstalling and reinstalling both and tried connecting with just one but nothing works I can install the FW but I can't connect. The F7 is on your supported boards but I suppose the F7 Pro isn't supported?

"Omnibus F7 Pro Flight Controller Built-in Dual Gyro AIO OSD Current Sensor and LC Power Filter"

https://www.banggood.com/Omnibus-F7-Pro-Flight-Controller-Built-in-Dual-Gyro-AIO-OSD-Current-Sensor-and-LC-Power-Filter-p-1169518.html?rmmds=myorder&cur_warehouse=CN

Using configurator 1.8.1 and firmware version OMNIBUSF7 1.8

**Comment by shellixyz** [comment]
I could be wrong but it looks like it isn't supported. Did you try the V1 and V2 versions ?

**Comment by Gaz93** [comment]
I've tried the V2 version too same result, I think I'll just try a different board for the moment.

**Comment by putimir** [comment]
Same here: Airbot Omnibus F7 v2 (supposedly supported). I can connect to the board flashed with betaflight, but when using Inav 1.8.0, I get 2 instances of "STM32 Virtual ComPort in FS mode", in the USB devices but no COM port.

Anyone figured this out?

**Comment by putimir** [comment]
Hi,  #2647 fixed the duplicated STM devices for me, and I can now connect to the board...

**Comment by Gaz93** [comment]
I had noticed the board started working after trying the newest release and I can say I'm a happy fellow now so I closed the issue :)

**Comment by teknokraze** [comment]
For anyone else coming late to the party like me, the quick and easy fix is to use ImpulseRC's driver fixer downloaded from here:

[ImpulseRC Driver Fixer](https://impulserc.com/pages/downloads)

Solved it for me.
