### ISSUE TITLE
More control over FLAPs in flight

### ISSUE THREAD

**Issue by linuxras** [iNavFlight/inav#2601]
I have been making a lot of use of FLAPERONS lately but I find it extremely annoying to not be able to dial in the amount of flaps I want in flight.
Could we please have flaperon_throw_offset assignable to a POT on my transmitter.

It would also be very cool to be able to reverse the direction into sploilerons in flight as well.

**Comment by DzikuVx** [comment]
INAV 2.0 will free mixer settings and it will be possible to mix any RC channel into any servo on any airplane, so POT will be able to drive flap throw and so. 
Because so, I'm closing this ticket, thanks for participation
