### ISSUE TITLE
Help - OMNIBUS F4 v2 Pro Servo big Delay

### ISSUE THREAD

**Issue by Christianmix** [iNavFlight/inav#2603]
Due to my bad English, I made a video without speaking, just showing what happens.
I'll make it well explained here, just look at the video that will see that there is a delay in the servo movement, even when reaching the end with the transmitter stick, the servo moves slowly, this in Angle activated mode, when leaving the inav in passthru this does not happen, but when returning to the angle mode it does again, when I lift the accelerator stick and it worsens, in addition to slowly go to the position that I place the stick, when releasing the stick the servo gradually returns to the normal position look first here he going to wander and come back even after having released the stick https://youtu.be/q2SgRFqvyGg?t=321 and then in this other moment of the video, I show that the servo comes back quickly but well after having the transmitter stick ... https://youtu.be/q2SgRFqvyGg?t=417 .............. I do not know what to do anymore I tried on 2 boards f4v2 and 1 cc3d and gave the same problem, when the plate is moved the servo works quickly, without any delay, the delay in servo response only exists through the transmitter, but with the card connected to the usb and moving the stick of the transmitter can see in the program that the commands come quickly on the board look at this moment ... https://youtu.be/q2SgRFqvyGg?t= 50
please help me, I do not know what to do, I've tried several versions of inav and all gave the same problem, I must be doing something wrong and I can not find out.
Remembering that I have already tried on 2 other boards besides this one and with 6 other servos, it must be some configuration error.

complete video: https://www.youtube.com/watch?v=q2SgRFqvyGg

**Comment by shellixyz** [comment]
Please post your config dump

**Comment by shellixyz** [comment]
To me it looks like your servo is struggling. Are you sure it is powered appropriately and that it is working ? Did you try with another servo ? If the issue comes from the servo it would explain why it didn't work on two different boards. Other than that quickly looking at the settings you showed I can't see what could cause that.

**Comment by Christianmix** [comment]
#shellixyz, when this in passthru works perfectly, the problem only happens when it is in some way stabilized or failsafe. This is the dump.


# dump

# version
# INAV/OMNIBUSF4PRO 1.7.2 Jul 20 2017 / 11:59:41 (81b85de)

# resources

# mixer
mixer FLYING_WING

mmix reset


# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1000 2000 1500 100 -1 
servo 4 1000 2000 1500 100 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# servo mix
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature VBAT
feature RX_SERIAL
feature MOTOR_STOP
feature GPS
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE

# map
map AETR1234

# name
name -

# serial
serial 20 1 115200 38400 0 115200
serial 0 64 115200 38400 0 115200
serial 2 2 115200 57600 0 115200
serial 5 0 115200 38400 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 0 0 1950 2075
aux 1 1 1 900 1575
aux 2 3 1 1450 1575
aux 3 10 1 1950 2050
aux 4 14 2 1600 1775
aux 5 18 1 1775 1875
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 2000
set gyro_sync = ON
set gyro_sync_denom = 2
set align_gyro = DEFAULT
set gyro_hardware_lpf = 20HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6000
set acc_lpf_hz = 15
set acczero_x = 68
set acczero_y = 54
set acczero_z = -170
set accgain_x = 4077
set accgain_y = 4103
set accgain_z = 4033
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = -1600
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set mag_calibration_time = 30
set baro_hardware = BMP280
set baro_use_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = SBUS
set sbus_inversion = ON
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set sdcard_detect_inverted = ON
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set motor_pwm_rate = 400
set motor_pwm_protocol = STANDARD
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 0
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set align_board_roll = -4
set align_board_pitch = 4
set align_board_yaw = 0
set gimbal_mode = NORMAL
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 265
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = OFF
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_climb_first = OFF
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 9900
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 3000
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 5000
set nav_fw_launch_climb_angle = 18
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set osd_video_system = 0
set osd_row_shiftdown = 0
set osd_units = METRIC
set osd_rssi_alarm = 20
set osd_cap_alarm = 2200
set osd_time_alarm = 10
set osd_alt_alarm = 200
set osd_main_voltage_pos = 2403
set osd_rssi_pos = 1047
set osd_flytimer_pos = 2422
set osd_ontime_pos = 343
set osd_flymode_pos = 2444
set osd_throttle_pos = 2274
set osd_vtx_channel_pos = 99
set osd_crosshairs = 2048
set osd_artificial_horizon = 2248
set osd_current_draw_pos = 2145
set osd_mah_drawn_pos = 2177
set osd_craft_name_pos = 84
set osd_gps_speed_pos = 2211
set osd_gps_sats_pos = 3158
set osd_gps_lon = 402
set osd_gps_lat = 384
set osd_home_dir = 2158
set osd_home_dist = 2326
set osd_altitude_pos = 2294
set osd_vario = 182
set osd_vario_num = 2261
set osd_pid_roll_pos = 322
set osd_pid_pitch_pos = 354
set osd_pid_yaw_pos = 386
set osd_power_pos = 47
set i2c_overclock = OFF
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 2
set fw_i_pitch = 15
set fw_ff_pitch = 70
set fw_p_roll = 2
set fw_i_roll = 15
set fw_ff_roll = 30
set fw_p_yaw = 50
set fw_i_yaw = 45
set fw_ff_yaw = 0
set fw_p_level = 10
set fw_i_level = 15
set fw_d_level = 75
set max_angle_inclination_rll = 900
set max_angle_inclination_pit = 900
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 35
set pitch_rate = 9
set yaw_rate = 20
set tpa_rate = 33
set tpa_breakpoint = 1300

**Comment by shellixyz** [comment]
Just some ideas

I think you should avoid using 90° as max roll/pitch, 45° should be safer to start with
```
set max_angle_inclination_rll = 900
set max_angle_inclination_pit = 900
```

Also please test in acro mode (no mode configured) first with
```
set fw_p_pitch = 0
set fw_i_pitch = 0
set fw_p_roll = 0
set fw_i_roll = 0
```

**Comment by Christianmix** [comment]
I already fly a long time fixed wing, with a cc3d, I put 90º pr that I do not like long corners, but I discovered one thing, I feed my servo through my esc, off the board, but when I put it on the board does not work . I checked the pins where I connect the servos, before connecting the servo all the pins are with 4.7v, when connecting only 1 servo, that voltage drops to 1.06v on all pins, less on the SBUS, on the pin that gives the current to the receiver still 4.7v, will the 2 new cards have problems?

**Comment by shellixyz** [comment]
I'm not sure to understand but if your 5V rail goes down to 1.06V it can't work that's for sure. Make sure your 5V rail can feed enough power to your servos and also that your servo grounds are connected directly to your FC. Make sure your servo power rail is independent from the FC 5V rail.

It is unlikely that all your boards have the same issue.

**Comment by shellixyz** [comment]
Where are you from @Christianmix ?

**Comment by Christianmix** [comment]
Brazil

**Comment by Christianmix** [comment]
I use cc3d with inav and never isui the board to power the servos, always use the bec of the esc, but that would not be problem to give that delay so great in the servo, if the problem was in the servo when in the passthru mode should happen same problem, I think it's the same board, it does not have to stay this way, the answer is very slow when using some flight mode, I tried with the air mode and also happened the same.

**Comment by Christianmix** [comment]
look how the voltage drops

https://youtu.be/X53EXUvqfZY

**Comment by shellixyz** [comment]
From the video it looks like you are powering the board from your ESC BEC 5V. Please check from your FC documentation but from what I know the F4Pro board has an onboard "BEC" and should be powered directly from your battery. If the FC's output power rail get 5V from the FC 5V you should only connect your servo ground and signal to the FC. The 5V wire for the servos should not be connected to the board but directly to your ESC BEC 5V.

You can quickly confirm if the issue is not coming from the software by disconnecting everything from your FC but keeping the receiver. Then connect the FC with USB to your computer and external power if it is needed for your receiver. Finally connect to your FC with the configurator and go to the motors tab. There you can see what the software is commanding the servos to do. If the output values are moving as expected then it is an hardware issue.

**Comment by Christianmix** [comment]
Hi I did the tests as you said, with nothing on the board, and I looked at the engine flap as the servos behaved and to my surprise they appear very problematic, but with the same PLCA in the beta flight is perfect, and to despair I took another f4 v2 hehehehehe are 3 now in front of me, if I put in some mode of flight, I have problem with the servos, no flight modes is perfect, but I want the flight stabilized, so I did not advance the controllers anything , I did a lot of research on the internet and did not find anything, it follows the video with the demonstration of how the graphics of the servants behave in the programs BF and Inav. Thanks for the help, but I'm thinking of giving up and going back to old apm that never left me in the hand.
 video

https://youtu.be/5FUp_Qca0Bs

**Comment by shellixyz** [comment]
What mode is enabled in your last video ? Also did you set roll/pitch P and I term to 0 ?

**Comment by Christianmix** [comment]
when p i d this zero works well. Why that?
same mode the last video

look

https://www.youtube.com/watch?v=hdv05oGqKZ4

**Comment by shellixyz** [comment]
It is because when your board is armed the I term accumulates the error of the gyroscope. When on the ground you should only test with the board disarmed. When the board is disarmed the I term have no effect.

**Comment by Christianmix** [comment]
so the sign is good and this error will only hit the ground? When you're gone, will not it be okay then? can I put the default values of P I?

**Comment by shellixyz** [comment]
For your first flight your P and I terms should be 0. Always test your aircraft first in passthrough and carefully test the other mode(s) while being prepared to switch back to passthrough in case there is a problem.

For tuning the PID controller please follow this guide:
https://github.com/iNavFlight/inav/wiki/Tune-INAV-PIFF-controller-for-fixedwing

**Comment by Christianmix** [comment]
I understood, I now tested with horizon mode without being armed and with the default pid and it really did not give any problem, so the one who was creating the problem was just me activating the controller on the ground, but one thing happens that I found strange, if I hold the stick trtansmissor in any maximum position, when lifting the stick of the accelerator, even if I do not decrease the commands of the other stick they will decrease according to how much increase the accelerator, as if it were a mix of the plate making that the more speed, less command . is this right?

**Comment by shellixyz** [comment]
Yes this is all right this is because of your tpa_rate setting

**Comment by shellixyz** [comment]
With increased air speed (inferred from increased throttle) your control surfaces have more control so the movement should be less for the same effect.

**Comment by Christianmix** [comment]
ok thank you very much, you helped me a lot in the mistake that I was causing, thank you for the patience you had with me.
now I just have to find out why I can not power the servos directly on the board, none of them I can, the only connection that stays constant the 5v is in the sbus, in the servo connections when I put the servo the low voltage and they do not work, it will be do I have to activate anything on board or inav?

**Comment by shellixyz** [comment]
You should just have to split the red wire from your servo connectors and connect them directly to your ESC BEC 5V.

**Comment by Christianmix** [comment]
is really this is the best solution, i bought 2 more boards f3 10 dof to use, i am hoping to get from china, i prefer the connection mode of it, in these f4 i am using op gps and i had to adapt the bigger connector because the port where this original gps connector comes in, it's uart 3 which is the port that sbus uses, I just thought it was wrong, inav should give us the option to put the uart according to our need, that is, I could have a programming where we would place the connector that is in the same uart of sbus in another uart, I do not know if you understand me? my gps is from the small 4-wire connectors and the connector for it on f4 v2 is in the same uart as SBUS, this should have change, type a programming where i can put the SBUS on uart 6 that i do not use the connector, would much easier than having to go behind a large connector and use only the first 4 wires.

**Comment by shellixyz** [comment]
F4 boards don't have inverters in the MCU that's why you can connect SBUS only to one of the UART. The one equipped with an external inverter.

**Comment by shellixyz** [comment]
F3 board have integrated inverters in the MCU allowing to use SBUS on every one of the UART units.

**Comment by Christianmix** [comment]
I wanted to know half of what you know, it would be great for me, did you learn all this by using the inav or did you take a course? if it was only using the inav should be time that isa it, I met the inav because I had a cc3d here and not used for lack of rth, and since I always fly more than 3km I can not take the risk of losing radio signal or video and not having an automatic return home, it was when I read about inav, watched some videos of Matt and I configured my cc3d, it was perfect, then I decided to buy the f4 to put in a mini heel, but I could not understand how to do the mixagen of the tail then discarded the project, I thought I'd ask for a copy of Matt's configuration, but I was ashamed. I'll wait and buy a 2.8 APM that I know set up for the tail tail. But I thank you so much for helping me. thank you

**Comment by Christianmix** [comment]
Mini talon v Tail

**Comment by Christianmix** [comment]
, then I decided to buy the f4 to put in a mini talon v tail, but I could not understand how to do the mixagen of the v tail then discarded the projec

**Comment by shellixyz** [comment]
I'm a software engineer so it is helping to understand the iNav software but other than that all I know about about flight controllers and how to use them comes from the internet. I read all the free flight controller software documentations (iNav/Betaflight/Cleanflight/LibrePilot/Ardupilot). Also there is a lot of good videos on youtube: [Painless360](https://www.youtube.com/user/Painless360) and [Project Blue Falcon](https://www.youtube.com/channel/UCObMtTKitupRxbYHLlwHE3w) for example.

For iNav the best is to start with the [wiki](https://github.com/iNavFlight/inav/wiki) and the [docs](https://github.com/iNavFlight/inav/tree/master/docs).

To configure the iNav mixer for a Mini Talon V tail you should be able to use ready to use config:
[Custom mixes for exotic setups - V tail fixed-wing](https://github.com/iNavFlight/inav/wiki/Custom-mixes-for-exotic-setups#v-tail-fixed-wing)

For an explanations please watch this video by Painless360:
[Setting up custom servo mixes in iNav for V tail](https://www.youtube.com/watch?v=qL2LMFF5bJ4)

**Comment by PScott1** [comment]
@shellixyz  JC's  (Project Blue Falcon) died in a motorcycle accident a few months ago...his videos are still great.

**Comment by shellixyz** [comment]
@PScott1 I know. Very sad !

**Comment by Christianmix** [comment]
I was thinking here about the accelerator changing the commands, is that why when I accelerate my fixed wing starts losing altitude?

**Comment by shellixyz** [comment]
Probably not.

Are you talking about Angle or Horizon mode ? If yes then it is probably because the way you calibrated the accelerometer makes your model fly flat relative to the ground with the pitch command centered. You need to increase `pitch degrees` in the configuration tab until your aircraft is not gaining nor losing altitude when your pitch command is centered.

It can also be a thrust angle issue. What fixed wing model are you talking about ?

**Comment by Christianmix** [comment]
i talking about fly wing.

**Comment by Christianmix** [comment]
Hi, I flew today, and until it went well, until at some point the fly wing started to fly badly and in osd gave message that it was necessary the calibration, I do not know why this, but this is not the biggest problem, the biggest Problem was the flick of the osd when I accelerate, when I decrease the throttle back to the norm, I'm using the same battery for everything, then the battery negative then the camera and the video transmitter, it's the same negative that also turns on the flight controller . here the black wire is negative and the red wire is positive. In the flight controller only the video signal is on. Look at the video as it was. 

https://youtu.be/N-k6R7KdWlw

**Comment by digitalentity** [comment]
@Christianmix you have too much noise on your camera/VTX power. Try powering them with a separate small battery and if it works - invest in a good LC-filter.
