### ISSUE TITLE
Implement FPort

### ISSUE THREAD

**Issue by rb1205** [iNavFlight/inav#2604]
BetaFlight and FrSky have developed [FPort](https://github.com/betaflight/betaflight/wiki/The-FrSky-FPort-Protocol), a new serial protocol that takes care of all the communications between RX and FC on a single wire: channels, telemetry, RSSI, MSP tunnelling... It can be added to existing X4R or XSR receivers by updating their firmware, and only needs a single s.port capable serial on the FC.

Given that most of us use two different ports for channels (sbus) and telemetry (s.port), this protocol would free a serial port, which would be great. Is it possible to merge it or it'd require a major overhaul of the API to do so?

**Comment by artusmuc** [comment]
yes it would be nice to - i have x4rsb and xsr-e reciever and as i read this will solve all uninverted problems and and only need 1 uart
