### ISSUE TITLE
STM LIS3MDL compass support ?

### ISSUE THREAD

**Issue by fiveangle** [iNavFlight/inav#2607]
### LIS3MDL Compass Support ?

In looking for an ultra-lightweight GPS-Compass module, an RCG member suggested this:

https://store.mrobotics.io/product-p/mro-ugps-samm8q-01.htm

But I noticed that it uses the STM LIS3MDL compass:

http://www.st.com/en/mems-and-sensors/lis3mdl.html ([datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/54/2a/85/76/e3/97/42/18/DM00075867.pdf/files/DM00075867.pdf/jcr:content/translations/en.DM00075867.pdf))

 [Reviewing here](https://github.com/iNavFlight/inav/tree/development/src/main/drivers/compass), it looks like this isn't directly supported.

Does anyone know if this uses the same protocol as one of the supported magnetometers and so should work ?  Or would support have to be fully ported ?  I did a bit of digging and suspect it isn't a drop-in as PX4 support looks like it was added March 2016 and looks to be an entirely separate driver:

https://github.com/PX4/Firmware/blob/master/src/drivers/lis3mdl/lis3mdl.cpp

The reason for asking is that I'm trying to implement the lightest-weight solution possible for emergency position-hold (and *maybe* RTH if something goes wrong with video feed).  It will otherwise be dead weight on every flight, and at <8g, I can't find anything close to this with an M8.

This is probably the alternative if I can't find an M8 unit - this is <10g NEO-6M:

https://hobbyking.com/en_us/micro-hkpilot-gps-and-compass-u-blox-neo-6-and-hmc5883.html

Thanks,

-=dave

**Comment by digitalentity** [comment]
This issue somehow didn't grab my attention. LIS3MDL is not supported by INAV and will require a separate driver to be written. I don't have the hardware, so I can't implement & test.

**Comment by fiveangle** [comment]
Thanks for confirming.

The LIS3MDL is about [2 bucks at the usual suspects](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20180221082345&SearchText=LIS3MDL) so I could order a couple and send you one if/when you might get around to it 🤷‍♂️

**Comment by digitalentity** [comment]
Purchased a few.

**Comment by abenn1** [comment]
I'm new to the way things work here.  Does the last comment mean that LIS3MDL support will be in iNav v2.0?  My favoured supplier (Drotek, France) now uses it in its M8N modules.

**Comment by fiveangle** [comment]
It means the target goal for implementing support for LIS3MDL is 2.0.  That doesn't necessarily mean it will be in that version ;)

**Comment by abenn1** [comment]
Thank you fiveangle.

**Comment by bforbort** [comment]
Sorry folks, I didn't realize this was a requested feature.  I actually wrote a driver for the LIS3MDL for v1.9.1 a while ago.  See https://github.com/bforbort/inav/tree/MAG_LIS3MDL

I'll see if I can rebase it and do a PR.

Note: If you want to try this, don't forget to add `USE_MAG_LIS3MDL` to your target's target.h file, and `drivers/compass/compass_lis3mdl.c \` to it's target.mk.

**Comment by digitalentity** [comment]
@bforbort cool, please post a PR

**Comment by fiveangle** [comment]
@bforbort - It seems you completed your port to BF (https://github.com/betaflight/betaflight/pull/6514) let us know if you're interested in rebasing / submitting pr.

Thanks !

-=dave

**Comment by fiveangle** [comment]
@bforbort. Curious if this ever got sorted out ?

**Comment by shellixyz** [comment]
@bforbort  Support has been merged August first.

@digitalentity Looks like we can close this ?

**Comment by digitalentity** [comment]
Yep, I think it could be closed.
