### ISSUE TITLE
Feature - resource mapping / remapping !!

### ISSUE THREAD

**Issue by yo8aiv** [iNavFlight/inav#2608]
i'm trying to remap some of the pwm outputs to a different pin/resource on the board and no command works.
is this not implemented/not supposed to work yet?.
Could be a great advantage being able to remap unused or broken pins.
Edit - also camera control over pwm its another good feature (resource re/mapping dependant).

omnibusF4 v2 Pro.

Thanks. 
Great job anyway.

**Comment by shellixyz** [comment]
I can confirm resource remapping isn't implemented.

**Comment by DzikuVx** [comment]
Duplicate of #1145. Closing, thanks
