### ISSUE TITLE
[FEATURE REQUEST] Use GPS Alt if there's no baro in the OSD

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#2609]
Have a way of having the GPS altitude in the OSD instead if there's no baro onboard.

Same discussion here on the betaflight github: https://github.com/betaflight/betaflight/issues/4800

**Comment by Pairan** [comment]
I don't know if I get this Feature Request right, but I fly without Barometer (FW) and in fact have ALT in my OSD which only can be measure by the GPS which is installed!

In case you intended to archieve this ... ehm ... its done (for FW) ! :D

**Comment by wx4cb** [comment]
hmm.... strange. i don't get altitude on my osd (unless im missing something) can you post a pic of your osd config screen. on mine all i get that says "gps" is speed heading lat/long HDOP course etc.

The only "altitude" one is checked, but i don't see a GPS Altitude

**Comment by krzysztofmatula** [comment]
scarab-osd has two separate altitude widgets:
- "Altitude - shows the altitude from prime altitude source BARO is used else GPS"
- "GPS altitude - display GPS altitude"

I wonder if we'd also prefer to have both in iNav - one showing the altitude FC uses for computation, and the second - raw reading from GPS to give pilot another view...?

**Comment by ShawnzAZ** [comment]
I'd like to have the option for Altitude MSL vs just AGL from launch.  Obviously MSL would be from GPS.  AGL can come from either.

Today in 1.8 I can display both the baro and GPS altitude AGL.

**Comment by wx4cb** [comment]
@krzysztofmatula the issue with that is, they COULD be both the same if there's no baro. that was my reasoning behind, (in the betaflight thread i linked to) just leaving "altitude" in the current spot, and then adding the gps alt code into where it does all the computation and if there's a baro, use that if there's no baro then use the gps alt if it's there.

**Comment by cj7hawk** [comment]
Did anything happen with this? It doesn't appear to be present in 3.3.1 - Will it be included in 3.4?

**Comment by DzikuVx** [comment]
INAV Altitude comes from position estimator. It merges all available sensors.

**Comment by Riffer** [comment]
@DzikuVx does this mean Altitude in OSD and Telemetry is coming from both Baro and GPS and the values are calculated together? If yes, is the mixup in the calculation of Altitude influenced by nav_w_z_baro_p and nav_w_z_gps_p? If not: Where can one set 'show altitude from [baro|gps] only?

**Comment by DzikuVx** [comment]
In "sensors" tab in configurator or in blackbox log
