### ISSUE TITLE
Home resets during FS cycling

### ISSUE THREAD

**Issue by Hwurzburg** [iNavFlight/inav#2614]
This is a potential fatal issue!

_Omnibus Pro F3
_INAV/OMNIBUS 1.8.0 Nov  1 2017 / 06:14:28 (912d1315)

Problem:
Home point resets while going from in FS mode to signal re-acquisition.
First tests of flying to FS point while hands off in ALTHOLD+STABLE mode in flying wing. FS is entered and RTH begins normally....as it turned back toward home in RTH the OSD flashed "ARMED" briefly, and then the FC re-entered FS, but home point is now at current distant location...luckily, by re-orienting TX signal was re-acquired and plane recovered.

the plane operates in all nav modes properly. FS is setup in RX and FC for no pulses using XM+ rx.
The only "non-standard" setup items I can think of is that it is using an ARM switch on a high channel (ch 11) and that I had fixed_wing_auto_arm enabled from previous uses which did not have an ARM switch configured. I suspect that the recent code fix for this feature in the arming sequence may be the culprit. Perhaps when an arm switch is used the FS code requires that this feature be disabled, although it is not stated?

DIFF is here: https://pastebin.com/JVHks7Qk

**Comment by digitalentity** [comment]
Something caused machine to disarm and re-arm in the air. Do you have logs by any chance?

**Comment by Hwurzburg** [comment]
no, sorry....am a little afraid of re-attempting with an SD card in to get them with auto_arm enabled, which my gut says is somehow the issue, since the arming code was changed to make it work nominally....but when weather cooperates after XMAS I will attempt it again with SD card logging...  first I think I may try to simulate it on the ground, watching to see if I get a re-arm and home shift as I turn the TX on and off after running with it beyond the FS min dist....

  On Friday, December 22, 2017, 6:52:13 PM CST, Konstantin Sharlaimov <notifications@github.com> wrote:  
 
 
Something caused machine to disarm and re-arm in the air. Do you have logs by any chance?

**Comment by Hwurzburg** [comment]
I have flown again several times, toggling the "RANGE" check on my taranis to invoke toggling FS's.....so far, I have not seen another flash of the arming screen and reset of home position....I will keep doing this every time I fly to see if I can capture it with logging on, but at this point its a one-off gremlin...

**Comment by digitalentity** [comment]
I guess we can close this. Failsafe by itself doesn't cause home reset.
