### ISSUE TITLE
CLI parsing error in SERVO

### ISSUE THREAD

**Issue by Hwurzburg** [iNavFlight/inav#2615]
versions...at least from 1.7.3 onward

while it is possible to set servo travel to 125% in the config and this is dumped properly...loading this value in via CLI (for backup restores) is failed as a parsing error...

**Comment by shellixyz** [comment]
Looks like it never worked for rate values < -100 or > 100. Fix is in PR #2616.

**Comment by DzikuVx** [comment]
merged, thank a lot
