### ISSUE TITLE
Detect Memory Flash on NAZE32

### ISSUE THREAD

**Issue by xnukes** [iNavFlight/inav#2621]
Hello ,

On INAV 
please fix detect memory flash on board NAZE. In cleanflight is ok, please fix it :)) Thaanks

**Comment by fiveangle** [comment]
It may not be enabled due to lack of space in F1.

If so, you'll have to custom compile to get that feature (and remove unused features)

**Comment by DzikuVx** [comment]
Naze32 does not have enough flash memory for blackbox and GPS. Plus, it is no longer supported.
You might want to compile it yourself if you fins enough functions to disable to make space for blackbox.

Closing it I'm affraid
