### ISSUE TITLE
BetaflightF4 Board Support

### ISSUE THREAD

**Issue by CircuitBender** [iNavFlight/inav#2622]
### If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

Is there a way to integrate the BetaflightF4 FC from FPVModels to the current inav version ? Is there a way to import it from Betaflight and what would have to have to be done for this ?
As a programmer myself I would happily contribute if I would get some general advice on the proceeding.

### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_
1.7 and BetaflightF4

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by wx4cb** [comment]
already being worked on here: https://github.com/iNavFlight/inav/pull/2573

Ther is a semi working version, but it's still in development. @shellixyz has done a crapload of work on it.
