### ISSUE TITLE
A983 compass use

### ISSUE THREAD

**Issue by Xgdc** [iNavFlight/inav#2623]
I have a M8N GPS with onboard compass A983. I've tried all the existing options in the configurator but it remains undetected (I have another 6M GPS with onboard compass L883 and that works) this using an Omnibus F4 pro V2.1 board. Is there any way I could make the A983 compass work as I would like to use the more advanced M8N GPS? I am using: inav_1.8.0_OMNIBUSF4V3.hex

**Comment by digitalentity** [comment]
Which GPS module is this? Can you post a picture of the module and where did you purchase it?

**Comment by Xgdc** [comment]
![m8n_a983](https://user-images.githubusercontent.com/34891008/34404552-ef8716b4-ebb6-11e7-89cd-254599210dc4.jpg)

I hope the image is visible, It was bought (some time ago) from Good Luck Buy and is called: NEO-M8N Flight Controller GPS Module with Shell & Stand for PX4 Pixhawk V2.4.6 APM 2.6 Compatible.

**Comment by digitalentity** [comment]
Can you send a link to a product? I'll purchase one. 
A983 is a designation of HMC5983 compass which is compatible with HMC5883L driver. Since it's not detected by INAV - this is likely another instance of cloned HMC5883 (or pin-to-pin compatible knock-off with different API)

**Comment by Xgdc** [comment]
http://www.goodluckbuy.com/neo-m8n-flight-controller-gps-module-with-shell-and-stand-for-px4-pixhawk-v2-4-5-apm-2-6-compatible.html

As I said, this was bought some time ago but they do currently still offer it for puchase (I've just checked).

**Comment by Xgdc** [comment]
So this is what i decided to do. Fitted a whole new L883 Mag board (filed to fit and hot glued) Works great!

![m8nmoddedmag](https://user-images.githubusercontent.com/34891008/34442091-8b5f0c1a-ecc8-11e7-8a81-56d120bb6d08.JPG)
