### ISSUE TITLE
matek f405-aio does not work led

### ISSUE THREAD

**Issue by prkrstnk** [iNavFlight/inav#2627]
There is a problem
1) We have the controller matek f405-aio
2) We have a Led panel for 10 LEDs (that's it https://ru.aliexpress.com/item/Original-Eachine-Wizard-X220S-FPV-Racer-Spare-Part-Taillight-Tail-LED-Light-with-Loud-Buzzer-for/32824563811.html?spm=a2g0s.9042311.0.0.Ewlu5g)
3) Through INAV - Configurator it is impossible to adjust LEDs
4) In Betaflight - Configurator, everything works fine (on the same controller and with the same panel)

**Comment by MATEKSYS** [comment]
S5 pad is used for 2812LED in INAV target

**Comment by digitalentity** [comment]
@prkrstnk can't reproduce. Everything works fine on MATEKF405-AIO board (MATEKF405 target)
