### ISSUE TITLE
Port Betaflight AIORacerF3 (Crius) to INAV using INAV target SPRacingF3Evo as base setup

### ISSUE THREAD

**Issue by tootomthumb** [iNavFlight/inav#2630]
I'm using the "Crius AIO Racer F3 with integrated OSD" which you can find on places like https://www.aliexpress.com/item/CRIU...737854451.html runs extremly well on Betaflight and Cleanflight (except the GPS functions, hence this post)

It uses similar components the SP Racing F3 Evo:
- STM32F303CC with 32bit/72MHz/256K Flash/40K SRAM
- MPU9250 via SPI bus, 8K ready
- BMP280 barometer
- Micro SD for logging
- Integrated MWOSD and FTDI debug socket
- UART2/UART3/SWD/PPM/RSSI solder pads
- ZH 1.5-3P socket used for DSM/S.BUS. and others SRX receivers
- Integrated IR-LED/Buzzer drivers
- Voltage detection and ARPDB solder pads

So I flashed INAV's SPRacingF3EVO target to the board and the MPU is recognised as MPU6500 & AK8963 and baro correctly as BMP280. Mag appears to work and I can calibrate it (so the pre-flight check goes green) ditto the Accelerometer. Also I have a Ublox Neo-M8N connected to the system and it gets full position updates with almost no drift. So INAV's GUI shows Gyro, Accel, Mag, Baro and GPS all lit up on the top status bar and the virtual QUAD X copter moves around sensibly on the Status page. It's on a PPM RX input and everything checks out on the Receiver page. In all it is running at around 3% CPU load in a Quad X configuration.

The Current and Voltage didnt work but I was able to solve the issue with the incorrect Current and Voltage pins by using CLI commands like: "**set current_adc_channel = 1**"

By using the CLI command: "resource" I can see that my Motors 1-8 are mapped to the incorrect resources. After discussing the issue in RCGroups.com I realised The Betaflight function of "**resource [function name] [index]**" doesnt appear to work in INAV eg "**resource MOTOR 1 NONE**" does nothing but re-list the resources again.

So it seems I need to somehow port Betaflight AIORacerF3 settings into INAV using something like SPRacerF3Evo as a base target to remap the motors as follows

INAV Res (Current)	== TO ==>	Betaflight Equivalent (I need)
A00: MOTOR1 OUT	== TO ==>	A00: FREE 
A01: MOTOR2 OUT	== TO ==>	A01: MOTOR 4
A02: MOTOR3 OUT	== TO ==>	A02: MOTOR 3
A03: MOTOR4 OUT	== TO ==>	A03: FREE 
A06: MOTOR5 OUT	== TO ==>	A06: FREE 
A07: MOTOR6 OUT	== TO ==>	A07: MOTOR 2
B01: MOTOR8 OUT	== TO ==>	B01: MOTOR 1

I'm willing to do the work myself but have no experience in this sort of project and if someone can ideally point me to a resource like "**Porting a Betaflight target to INAV borrowing from an existing INAV target**" (I wish!) that would be great, but any steerage would be useful. BTW I did Google that title and variations without success.

I can, of course, supply the full resource lists for the working Betaflight 3.1.7 AIORacerF3 or anything else if requested. 

I also have a spare board which I would gladly donate to the cause and send to anyone who might be able to make more progress than myself.

**Comment by wx4cb** [comment]
take a look at the target.h file in src/main/targets/SPRacingF3EVO directory. that is the pin assignments IIRC

There may be other issues, like timers etc, but that would be a good start

**Comment by tootomthumb** [comment]
Hi wx4cb!

If you do a search over at Betaflight under AIORACERF3 you will confirm that according to this post https://github.com/betaflight/betaflight/pull/1932 the AIORacerF3 is identical to the SPracingF3Evo with the exception of the motor pin assignments.

Unfortunately I cannot find those source files in BetaFlight under their target directory https://github.com/betaflight/betaflight/tree/master/src/main/target

I'm not a programmer so I'm wondering if I have missed something obvious as the AIORACERF3 is still available from their configurator. Do you understand what has happened to it? Or is it some sort of variant on the SPRacingF3Evo build that gets created on the fly?

I also tried to get the copy of the INAV git source files and compile the SPracingF3EVO on my local computer but cannot compile it without errors. So I'm wondering if you might be able to spot any issues?

**scatt@Gaming /cygdrive/c/dev/inav
$ make target=spracingf3evo
C:/Ruby25-x64/lib/ruby/2.5.0/open3.rb:199:in `spawn': No such file or directory - C:\Program Files (x86)\GNU Tools ARM Embedded\7 2017-q4-major\bin/arm-none-eabi-g++.exe -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fsingle-precision-constant -Wdouble-promotion -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target -I./lib/main/STM32F30x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM1/CoreSupport -I./lib/main/CMSIS/CM1/DeviceSupport/ST/STM32F30x -I./lib/main/MAVLink -I./src/main/target/SPRACINGF3 -ggdb3 -DDEBUG -std=c++11 -Wall -Wextra -Wunsafe-loop-optimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F303xC -DSTM32F303 -DFLASH_SIZE=256 -DHSE_VALUE=8000000 -DUSE_STDPERIPH_DRIVER -DSPRACINGF3 -D__FORKNAME__=inav -D__TARGET__=SPRACINGF3 -D__REVISION__=912d1315 -dM -E -o ./obj/stamp ./obj/stamp.cpp (Errno::ENOENT)
        from C:/Ruby25-x64/lib/ruby/2.5.0/open3.rb:199:in `popen_run'
        from C:/Ruby25-x64/lib/ruby/2.5.0/open3.rb:95:in `popen3'
        from C:/Ruby25-x64/lib/ruby/2.5.0/open3.rb:258:in `capture3'
        from C:/dev/inav/src/utils/compiler.rb:84:in `run'
        from ./src/utils/build_stamp.rb:66:in `hash_config'
        from ./src/utils/build_stamp.rb:44:in `stamp'
        from ./src/utils/build_stamp.rb:87:in `<main>'
make: *** [Makefile:956: obj/build.stamp] Error 1**

**Comment by wx4cb** [comment]
what is the version string returned in the CLI when you do the VERSION command? 

As for the compile errors, i'm not sure, I compile under a linux VM and usually the target is in capital letters so i would assume that it's:

make target=SPRACINGF3EVO ? 

remember that *nix based systems are case sensetive

**Comment by tootomthumb** [comment]
You mean for the Betaflight version of AIORacerF3? Idont have it installed right now but my copied DUMP file has "**Betaflight / AIORACERF3 3.1.7 Apr  3 2017 / 21:48:12 (e1c4b5c)**"

I also re-ran the make command as: "**make target=SPRACINGF3EVO**"

And get the same error.

I note that the error gives a path of: "**C:\Program Files (x86)\GNU Tools ARM Embedded\7 2017-q4-major\bin/arm-none-eabi-g++.exe**" and that seems strange because it is using both a backward and forward slash around the "**bin**" is that allowed?

Sifting around the Betaflight git further I noticed that the "Missing" files are in the SPRACINGF3EVO directory! https://github.com/betaflight/betaflight/tree/master/src/main/target/SPRACINGF3EVO

So they are using some sort of magic to create two targets with one definition. That's great from the perspective of compatibility of the two boards (they must be close) but for a newbie like me, it is making the whole thing even more complex!

**Comment by wx4cb** [comment]
i think you're running into the "spaces in a file path from windows" issue.

as to how they're doing it it's definately Makefile trickery.

What are the differences between the two boards pin wise ?

**Comment by tootomthumb** [comment]
Interesting idea, I'll reinstall tomorrow using a directory path without spaces or caps.

In regards to the Motor pins the difference boils down to:

**INAV   Resources |   | Betaflight Resources**
A00: MOTOR1 OUT | == TO ==> | A00: FREE
A01: MOTOR2 OUT | == TO ==> | A01: MOTOR 4
A02: MOTOR3 OUT | == TO ==> | A02: MOTOR 3
A03: MOTOR4 OUT | == TO ==> | A03: FREE
A06: MOTOR5 OUT | == TO ==> | A06: FREE
A07: MOTOR6 OUT | == TO ==> | A07: MOTOR 2
B01: MOTOR8 OUT | == TO ==> | B01: MOTOR 1

I'm only using 4 motors for a Quad X but figure if this gets done I might as well try to map all of them, in case others use it. I also had to switch the pins for the Current and Voltage measurement which I did using the INAV function.

Just for completeness, the entire resource list side by side is below:

**INAV   Resources | ...Vs… | Betaflight Resources**
A00: MOTOR1 OUT | ...Vs… | A00: FREE
A01: MOTOR2 OUT | ...Vs… | A01: MOTOR 4
A02: MOTOR3 OUT | ...Vs… | A02: MOTOR 3
A03: MOTOR4 OUT | ...Vs… | A03: FREE
A04: ADC CH1 | ...Vs… | A04: ADC_CURR
A05: ADC CH2 | ...Vs… | A05: ADC_BATT
A06: MOTOR5 OUT | ...Vs… | A06: FREE
A07: MOTOR6 OUT | ...Vs… | A07: MOTOR 2
A08: FREE | ...Vs… | A08: FREE
A09: SERIAL1 UART TX | ...Vs… | A09: SERIAL_TX 1
A10: SERIAL1 UART RX | ...Vs… | A10: SERIAL_RX 1
A11: FREE | ...Vs… | A11: FREE
A12: FREE | ...Vs… | A12: FREE
A13: FREE | ...Vs… | A13: FREE
A14: FREE | ...Vs… | A14: FREE
A15: PPM IN | ...Vs… | A15: PPM
B00: MOTOR7 OUT | ...Vs… | B00: FREE
B01: MOTOR8 OUT | ...Vs… | B01: MOTOR 1
B02: ADC CH3 | ...Vs… | B02: ADC_RSSI
B03: SPI1 SCK | ...Vs… | B03: SPI_SCK 1
B04: SPI1 MISO | ...Vs… | B04: SPI_MISO 1
B05: SPI1 MOSI | ...Vs… | B05: SPI_MOSI 1
B06: I2C1 SCL | ...Vs… | B06: I2C_SCL 1
B07: I2C1 SDA | ...Vs… | B07: I2C_SDA 1
B08: LED1 OUT | ...Vs… | B08: LED 1
B09: MPU CS | ...Vs… | B09: MPU_CS
B10: SERIAL3 UART TX | ...Vs… | B10: SERIAL_TX 3
B11: SERIAL3 UART RX | ...Vs… | B11: SERIAL_RX 3
B12: SDCARD CS | ...Vs… | B12: SDCARD_CS
B13: SPI2 SCK | ...Vs… | B13: SPI_SCK 2
B14: SPI2 MISO | ...Vs… | B14: SPI_MISO 2
B15: SPI2 MOSI | ...Vs… | B15: SPI_MOSI 2
C13: MPU EXTI | ...Vs… | C13: MPU_EXTI
C14: SDCARD IN | ...Vs… | C14: SDCARD_DETECT
C15: BEEPER OUT | ...Vs… | C15: BEEPER
F00: FREE | ...Vs… | F00: FREE
F01: FREE | ...Vs… | F01: FREE
F04: FREE | ...Vs… | F04: FREE

**Comment by wx4cb** [comment]
ok i may take a look at this monday see if i can see anything, but you need to re open the issue as i can't unless there's a moderator that can do it. I am just learning inav myself so it may be out of my league

**Comment by tootomthumb** [comment]
Cool either way, I appreciate your help but of course understand if it's too much of a pain in the arse...

BTW looking at https://github.com/betaflight/betaflight/blob/master/src/main/target/SPRACINGF3EVO/target.c

I realise I don't understant most of it but there are some conditional statements clearly defining things based on an AIORACERF3 versus the SPRACINGF3EVO amongst others. So for AIORacerF3 you have:
```
#if defined(AIORACERF3)
    DEF_TIM(TIM3,  CH4, PB1,  TIM_USE_MOTOR,                     0), // PWM1
    DEF_TIM(TIM17, CH1, PA7,  TIM_USE_MOTOR,                     0), // PWM2
    DEF_TIM(TIM15, CH1, PA2,  TIM_USE_MOTOR,                     0), // PWM3
    DEF_TIM(TIM2,  CH2, PA1,  TIM_USE_MOTOR,                     0), // PWM4
    DEF_TIM(TIM3,  CH3, PB0,  TIM_USE_MOTOR,                     0), // PWM5
    DEF_TIM(TIM3,  CH1, PA6,  TIM_USE_MOTOR,                     0), // PWM6
    DEF_TIM(TIM15, CH2, PA3,  TIM_USE_MOTOR,                     0), // PWM7
    DEF_TIM(TIM2,  CH1, PA0,  TIM_USE_MOTOR,                     0), // PWM8
```
and for SPRacingF3EVO you have:
```
#else // SPRACINGF3EVO / SPRACINGF3MQ
    DEF_TIM(TIM2,  CH1, PA0,  TIM_USE_MOTOR,                     0), // PWM1 [TIM2_CH1 (D1_CH5)]
    DEF_TIM(TIM2,  CH2, PA1,  TIM_USE_MOTOR,                     0), // PWM2 [TIM2_CH2 (D1_CH7)] [TIM15_CH1N (D1_CH5)]
    DEF_TIM(TIM2,  CH3, PA2,  TIM_USE_MOTOR,                     0), // PWM3 [TIM2_CH3 (D1_CH1)] [TIM15_CH1  (D1_CH5)]
    DEF_TIM(TIM15, CH2, PA3,  TIM_USE_MOTOR,                     0), // PWM4 [TIM2_CH4 (D1_CH7)]
    DEF_TIM(TIM16, CH1, PA6,  TIM_USE_MOTOR,                     0), // PWM5 [TIM16_CH1  (D1_CH3 / D1_CH6)] [TIM3_CH1 (D1_CH6)]
    DEF_TIM(TIM3,  CH2, PA7,  TIM_USE_MOTOR,                     0), // PWM6
    DEF_TIM(TIM3,  CH3, PB0,  TIM_USE_MOTOR,                     0), // PWM7
    DEF_TIM(TIM3,  CH4, PB1,  TIM_USE_MOTOR,                     0), // PWM8
```

**Comment by tootomthumb** [comment]
Sorry to spam you, but if you dont mind a friendly bribe, if you want an AIORacerF3 I would be more than happy to send it to you!

**Comment by wx4cb** [comment]
it's the timer assignments that would be the issue more than anything else because of potential conflicts :)

**Comment by tootomthumb** [comment]
In the Target.c file for Betaflight there is (reduced to just the AIORACERF3 motor parts)
```
    DEF_TIM(TIM3,  CH4, PB1,  TIM_USE_MOTOR,                     0), // PWM1
    DEF_TIM(TIM17, CH1, PA7,  TIM_USE_MOTOR,                     0), // PWM2
    DEF_TIM(TIM15, CH1, PA2,  TIM_USE_MOTOR,                     0), // PWM3
    DEF_TIM(TIM2,  CH2, PA1,  TIM_USE_MOTOR,                     0), // PWM4
    DEF_TIM(TIM3,  CH3, PB0,  TIM_USE_MOTOR,                     0), // PWM5
    DEF_TIM(TIM3,  CH1, PA6,  TIM_USE_MOTOR,                     0), // PWM6
    DEF_TIM(TIM15, CH2, PA3,  TIM_USE_MOTOR,                     0), // PWM7
    DEF_TIM(TIM2,  CH1, PA0,  TIM_USE_MOTOR,                     0), // PWM8
```
And in the INAV target.c for SPRACINGF3EVO we have:
```
    { TIM2,  IO_TAG(PA0),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_1, TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },  // PWM1
    { TIM2,  IO_TAG(PA1),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_1, TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },  // PWM2
    { TIM15, IO_TAG(PA2),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_9, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO },  // PWM3
    { TIM15, IO_TAG(PA3),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_9, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO },  // PWM4
    { TIM3,  IO_TAG(PA6),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_FW_SERVO },  // PWM5
    { TIM3,  IO_TAG(PA7),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_FW_SERVO },  // PWM6
    { TIM3,  IO_TAG(PB0),  TIM_Channel_3, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO },  // PWM7
    { TIM3,  IO_TAG(PB1),  TIM_Channel_4, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO },  // PWM8
```

So if I want to remap the Betaflight pins to the INAV target.c would it be?:
```
	{ TIM3,  IO_TAG(PB1),  TIM_Channel_4, 1, IOCFG_AF_PP, GPIO_AF_1, TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },  // PWM1
    { TIM3,  IO_TAG(PA7),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_1, TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR },  // PWM2
    { TIM15, IO_TAG(PA2),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_9, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO },  // PWM3
    { TIM2,  IO_TAG(PA1),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_9, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO },  // PWM4
    { TIM3,  IO_TAG(PB0),  TIM_Channel_3, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_FW_SERVO },  // PWM5
    { TIM3,  IO_TAG(PA6),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_FW_SERVO },  // PWM6
    { TIM15, IO_TAG(PA3),  TIM_Channel_2, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO },  // PWM7
    { TIM2,  IO_TAG(PA0),  TIM_Channel_1, 1, IOCFG_AF_PP, GPIO_AF_2, TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO },  // PWM8
```
I made the assumptions (based on the comments which indicate PWM1-8 is ordered sequentially disregarding IO_TAG order) that the PWM placement is determined by list order. I also assumed that I needed to keep the associated Channel and Timer from the original definition with respect to the IO_TAG. One assumption which I had no circumstantial evidence either way were was whether the parts like "**TIM_USE_MC_MOTOR | TIM_USE_MC_CHNFW | TIM_USE_FW_SERVO }**" needed to move with the IO_TAG or stay in the sequential order (I kept same sequential order).

I know that this is trial and error monkey see/do programming but hope it's not too far off!

**Comment by tootomthumb** [comment]
Well, I made various permutations of the lists above and the code compiled (thanks for you earlier suggestion of simplifying the path, it worked) but the board wouldnt even connect with my changes.

I dont know enough about how this stuff works to do anything other than semi-random changes so I'll wait to see if anyone else has any bright ideas!
