### ISSUE TITLE
OSD indication of loaded waypoints

### ISSUE THREAD

**Issue by Hwurzburg** [iNavFlight/inav#2636]
enhancement to add an indicator in the OSD that confirms a non-zero number of waypoints are loaded in volatile memory....ie to confirm that  valid waypoints were transferred from NV to RAM by stick command....anything will do... or even a message prior to arming after the cannot arm warnings are gone: "WAYPOINTS LOADED!" which disappears upon arming....either should be simple to implement....once # waypoints is implemented in the OSD mode display or enroute message in the future, then maybe that can be used also, ie " X Waypoints loaded!"

**Comment by digitalentity** [comment]
@fiam @shellixyz @DzikuVx what do you think?

**Comment by shellixyz** [comment]
It would be useful. I'll take a look.

**Comment by fiam** [comment]
Would be easy to implement on top of a message bus

**Comment by breadoven** [comment]
Closed by various PRs.
