### ISSUE TITLE
No summary screen after disarming 

### ISSUE THREAD

**Issue by compuatic** [iNavFlight/inav#2638]
Issue on inav 1.8.1
No summary screen on OSD after disarming following a long flight. Usually beyond 60km and 60mins+. Have not seen this with 1.7.2

Using omnibus F4 pro

**Comment by mrcottonmouth** [comment]
I had the same problem 2 times today, same board, same inav version. No stats screen. I didn't seem to disarm either after reviewing the video. Maybe it's ok in 1.9?

**Comment by shellixyz** [comment]
I can't find any bug that could cause this. The summary screen should be displayed unless the throttle or pitch sticks are pushed (high position). I will try to reproduce the issue.

**Comment by fiam** [comment]
Maybe we should wait ~1 second to clear the stats if THR or PIT is already high when disarming.

**Comment by shellixyz** [comment]
Yes that or wait for them to not be high before taking into account the high value to clear the stats.

**Comment by shellixyz** [comment]
@compuatic @mrcottonmouth 
Please try this binary and tell us if it is working better for you:
[inav_1.9.0_OMNIBUSF4PRO.hex.zip](https://github.com/iNavFlight/inav/files/1850112/inav_1.9.0_OMNIBUSF4PRO.hex.zip)

**Comment by mrcottonmouth** [comment]
Thank you so much for prompt attention to this issue!!
I will try it at my 1st opportunity, which may be this weekend. I will go ahead and make the transition from 1.8 to 1.9 test rom and be ready for the weekend.

**Comment by fiam** [comment]
@shellixyz I definitely prefer your idea. Better to check if THR/PIT are high on disarm and wait until they become low and then high again to clear the stats.

**Comment by mrcottonmouth** [comment]
@shellixyz 
This did fix the issue. After a 71 minute flight, no issues. Summary screen was perfect. Thank you! 4 flights, 2 over 60+ minutes.

**Comment by digitalentity** [comment]
Fixed. Closing
