### ISSUE TITLE
Matek F405 CTR (feature request)

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#2646]
It seems that "INAV1.8.0_MatekF405 listed in INAV configurator can’t support F405-CTR", as it says on the mateksys product page.

[http://www.mateksys.com/?portfolio=f405-ctr#tab-id-5](http://www.mateksys.com/?portfolio=f405-ctr#tab-id-5)

Mateksys has published its own hex file for this flight controller and I wonder if the source code has been added to the oficial development branch of iNav for next release...

[http://www.mateksys.com/Downloads/FW/inav_1.8.0_MATEKF405.hex](http://www.mateksys.com/Downloads/FW/inav_1.8.0_MATEKF405.hex)

Thanks

**Comment by stronnag** [comment]
Please see https://github.com/iNavFlight/inav/pull/2566 (and if it meets your needs, please also close this issue).

**Comment by raul-ortega** [comment]
Please keep it open, I would like to test the development version as soon as possible on my MATEK F04 CTR for an airplane and will close the issue if it really works.

**Comment by mrduncan626** [comment]
I have a couple of the Matek F405-CTR on order for use with iNav.  Does the iNav firmware on the Matek website, as noted above, work on the this FC?

**Comment by Sedgee** [comment]
I am looking at purchasing the same and would also be interested in knowing.

**Comment by Azuxul** [comment]
Firmware form iNav configurator dosen't work but the firmware on the Matek web site work.
Tested with my Matek F405-CTR and inav_1.8.0_MATEKF405 firmware.

**Comment by stronnag** [comment]
you need to wait for 1.9, or build the development branch.

There's a build from just now at  http://seyrsnys.myzen.co.uk/inav_dev/inav_1.9.0_MATEKF405.hex.gz
if you want to test random hex from the internet.

**Comment by digitalentity** [comment]
Closing, MATEK F405-CTR is supported by `development` and will be supported by 1.9
