### ISSUE TITLE
Angle for Aileron/Elevator for FPV Wing/Airplane

### ISSUE THREAD

**Issue by binleo** [iNavFlight/inav#2652]
Hi all, This is the first time I use Github.
I don't know if I post my question right or wrong. 
if Wrong, please forgive me
I want to ask everyone about the angle for Aileron (way Aileron) is best. Now I set 15deg for up and 15deg for down.
I using Techone FPV Wing and my friend using S800.
Sorry for my bad English.

Thanks and best regard.

**Comment by DzikuVx** [comment]
as a rule of thumb ailerons should not move more than 30 deg. 15 might also be fine
