### ISSUE TITLE
I2C for Ublox?

### ISSUE THREAD

**Issue by Riffer** [iNavFlight/inav#2653]
In https://github.com/cleanflight/cleanflight/issues/363 there were a promising approaches to use I2C for GPS with Ublox.

Has anything in iNav improved the basis for this? Would really be great to use I2C for GPS and freeing up an uart on my Omnibus F3 for Smart-Audio.

**Comment by digitalentity** [comment]
Ublox via I2C was tested, and confirmed to be impossible/impractical because Ublox only supports 100kHz I2C clock which is way too slow.
