### ISSUE TITLE
 Omnibus F4 Pro V3 Telemetry Issue using a DJI Style GPS

### ISSUE THREAD

**Issue by mrduncan626** [iNavFlight/inav#2654]
I have a Omnibus F4 Pro 3 (iNav 1.8.0 firmware) which I'm setting up with an SBUS Rx (FrSky XSR), S.Port Telemetry, and a DJI Naza GPS (clone).  GPS type in the iNav configurator is DJI Naze.  In the iNav Configurator, I see all the GPS data but in the telemetry data stream on my Taranis (OpenTX 2.2.0) I see everything accept for the GPS data (Lat/long, GAlt, Number of Satellites, and GSpd).  Is this a known issue?

**Comment by sergeysi779** [comment]
Have you discovered new sensors on Taranis after enabling GPS?

**Comment by mrduncan626** [comment]
Yes, performed Discover Sensors many times. I even tried reinstalling INav.

**Comment by mrduncan626** [comment]
UPDATED Information. 

This is the data I see in the telemetry stream:
Acc XYZ
Tmp1
Tmp2 (the information in this looks to be valid - e.g. 2803, 2904, 3906 is a sample of some of the data)
A4
VFAS
Alt
Hdg 
VSpd
F000 (no idea what this is)
And, the usual A2, RSSI, and RxBt

I DO NOT see the following in the Telemetry stream:
GSpd
GPS
GAlt
0420

However, I do see valid GPS data (GSpd, GPS, GAlt) in the iNav Configurator GPS tab. And yes, I did do several re-Discover Sensors after installing the GPS/Compass.

**Comment by mrduncan626** [comment]
UPDATE:  

Apparently, in order for the "Discover Sensor" to discover all the sensors, including all the GPS data (GSpd, GPS, GAlt, and 0420) on an Omnibus F4 Pro V3, you must enable the "Discover Sensor" function with the computer USB disconnected and only the Lipo connected.  For some reason when both USB and the Lipo are connected, all the sensors are not discovered, as I noted above.
