### ISSUE TITLE
inav 1.6 msp communication

### ISSUE THREAD

**Issue by amitmanish** [iNavFlight/inav#2660]
I am trying to implement serial communication between naze32 rev and raspberry pi. Naze32 has inav 1.6 firmware. My ultimate goal is to control my drone i.e naze32 using raspberry pi. I tried pymultiwii library with my receiver type rx msp in inav configurator. What am i doing wrong

**Comment by shellixyz** [comment]
Never done this but check if you are connected to the right serial port (the one you enabled MSP on) and see if you can read data with MSP to check if your connection is right.

**Comment by amitmanish** [comment]
I can read data like accelerometer value but cant arm drone using raspberry pi. Is msp communication one way.

**Comment by shellixyz** [comment]
No it is not. MSP is the same protocol used by the configurator. You should read the MSP source code on the iNav side to make sure the commands are right/up-to-date on the Pi side.

**Comment by amitmanish** [comment]
Thanks shellixyz. I wiill look into the msp source code of inav.
