### ISSUE TITLE
SP Rracing F4 EVO - Sonar

### ISSUE THREAD

**Issue by mattschinkel** [iNavFlight/inav#2662]
### Board and Version
SP Rracing F4 EVO
INAV 1.8.0
INAV/SPRACINGF4EVO 1.8.0 Nov  1 2017 / 06:45:36 (912d1315)

### Behavior
I'd like to setup sonar on my board, but there is no documentation. Where do I connect sonar to my board?

_Is this a new feature request?_
Maybe

**Comment by DzikuVx** [comment]
I'm affraid this is not possible, we also have no idea how @hydra planned to connect sonars to it. And @hydra is not active lately. Due to that, chances are rather slim or to be more precise, non existen without @hydra support I'm affraid
