### ISSUE TITLE
iNAV Auto_launch - do servo channels have to be centred?

### ISSUE THREAD

**Issue by rcflyers** [iNavFlight/inav#2664]
Apologies if posted in the wrong place but how far off 1500us can the elevator or aileron servos be before iNAV will think that a pilot has touched the sticks and abort a NAV-Auto launch?

**Comment by shellixyz** [comment]
It depends on the althold deadband setting

**Comment by shellixyz** [comment]
~I can't check now but I think the default is 5. So it will stay in launch mode from 1495 to 1505.~

**Update: checked it is 50 so 1450 <= command <= 1550**

**Comment by rcflyers** [comment]
Ok, thank you.
