### ISSUE TITLE
Issue with ez-gui mission planning

### ISSUE THREAD

**Issue by retif** [iNavFlight/inav#2665]
INAV, version: 1.8.0
Board: SRF3, version: 0

I can not download mission from FC into ez-gui.

Steps:
1. Connecting with otg-usb to the phone. Launching ez-gui. Successfully connecting to the FC.
2. Opening Mission Planner page. Making new mission. Uploading it to FC with no errors.
3. Clearing mission on the phone. Trying to download mission from FC.
4. Only one "RTH WP" appears in the WP list.

**Comment by stronnag** [comment]
Please report this on the ezgui bug tracker. This is not an FC bug. Mission upload / download works perfectly.

**Comment by retif** [comment]
ok. which versions of ez-gui and inav works good?

**Comment by stronnag** [comment]
Please ask on the ezgui bug tracker. This is the iNav project, not ezgui, which is a separate project.

misison upload / download has worked in all versions on iNav since it was introduced.
