### ISSUE TITLE
Missing sensors with Crossfire and Wing fc

### ISSUE THREAD

**Issue by sniperxnl** [iNavFlight/inav#2667]
Guys

i have a wing fc with this firmware
https://github.com/iNavFlight/inav/releases/download/1.8/inav_1.8.0_FF_WINGF4.hex

My Crossfire is activated on uart5 and telemtry activated, i get no sensors like Vbat, Fuel or current when i discover new sensors.

When i take my old omnibus with same crossfire i get all the sensors
GPS, Fuel, Vbat, Current

Any idear guys?

Also switched between crossfire reciever, all have the same firmware so why it work on my omnibus and not on my Wingfc?

**Comment by sergeysi779** [comment]
I can't find documentation for this FC. Could you try different UART? Maybe there is a hardware inverter on TX pin of this UART?

**Comment by shellixyz** [comment]
I never used crossfire telemetry but it looks like it needs to be inverted so you need an hardware inverter on the UART for it to work. The F3 MCU on the Omnibus FC have inverters integrated on every UART but the F4 MCU doesn't have integrated inverters. FCs with F4 MCU often have only one discrete inverter on one of the UARTs. You probably either need to connect your telemetry on the right UART having the inverter or build an inverter yourself like this one: https://quadmeup.com/smartport-inverter-for-f4-flight-controllers/

**Comment by sniperxnl** [comment]
I know from the maker from that WingFc that it have not inverters, i have also quads with crossfire and F4 boards and then it works perfect, uart5 have not inverter so it need to work somehow

**Comment by digitalentity** [comment]
FF WING is now released as "FF F35" FC. I have the board on my desk and will try to test in the following days.

**Comment by sniperxnl** [comment]
Aah great, 2 guys that i know have the same issue so

**Comment by furiousfpv** [comment]
Wrong pin define on UART5
#define UART5_TX_PIN            PC11
=> #define UART5_TX_PIN            PC12. 

We'll change.

**Comment by digitalentity** [comment]
Oops, good catch @furiousfpv. Are you doing a PR for the fix?

**Comment by furiousfpv** [comment]
Yes, MJ will help me push. Thanks.

**Comment by proepkes** [comment]
I have the same issue, using FF35 Lightning FC with iNav 2.0.0 and TBS CrossFire Tx + TBS Crossfire Micro RX

In OpenTX I select "Discover new Sensors" but it doesn't find any. (I've also installed the modchip, FrSky Horus)
