### ISSUE TITLE
Can INAV support STM32F411 series ?

### ISSUE THREAD

**Issue by nyway** [iNavFlight/inav#2685]
I have a board,the mcu is STM32F411CEU6.
I chance some codes in target.h and flash it,and nothing happen
So I don't know INAV can support

**Comment by shellixyz** [comment]
Too little info. What is it ? There is probably nothing preventing iNav to work on this MCU providing matching target files are filled with the right info.

**Comment by nyway** [comment]
@shellixyz 
You mean STM32F411 series can be supported in iNav?
Maybe my target files config error,i will check it

**Comment by shellixyz** [comment]
Yes. Where did you get this board from ?

**Comment by nyway** [comment]
@shellixyz 
I designed it myself,just for test fly wing and multirotor.
I build target,but not working.I don't know if something wrong in define for f411

**Comment by shellixyz** [comment]
Did you put it in the F411_TARGETS group in target.mk ?

```
F411_TARGETS   += $(TARGET)
```

**Comment by nyway** [comment]
Yes,same as betaflight .
And everything normal working in betaflight

**Comment by shellixyz** [comment]
Well i'm afraid I won't be much more useful. I don't know enough about STM32 MCUs. I guess there is something in the initialization code that blocks the boot-up. I guess you could use HW debug if you broke the debugging pins out.

**Comment by nyway** [comment]
@shellixyz 
OK, I will continue to test.
Thanks for your help

**Comment by YFZ450MANNY** [comment]
I just purchased a FC that has that same F411 MCU. Was hoping to load iNav on it for a delta wing project, but I don’t see a target for it in the flashing dropdown box. :(

**Comment by digitalentity** [comment]
@YFZ450MANNY which FC did you purchase? Support for 411 is coming

**Comment by nyway** [comment]
@digitalentity DALRCF411 target can support betaflight,but not support in inav yet,i try to change the target.h code ,but not success,could't run.Do you have source code can support F411 now with inav?

**Comment by YFZ450MANNY** [comment]
@digitalentity , YYEESSSSS!!!! lol. Thank you. This is the FC I purchased. https://www.banggood.com/F4_SVTX-STM32F411C-Flight-Controller-Integrated-5_8G-48CH-25100200mW-Switchable-VTX-OSD-20x20mm-p-1271788.html?rmmds=myorder&cur_warehouse=CN

Any timeframe on when it will be supported? Not trying to rush anyone.. Just want to have an idea on how long I will put this project aside.

**Comment by fiam** [comment]
@YFZ450MANNY The problem with that FC specifically for INAV is that it doesn't have any uarts broken out for GPS. Do you plan to solder directly to the MCU?

**Comment by nyway** [comment]
@digitalentity @fiam 
This is DALRC F411.With STM32F411CEU6
![1](https://user-images.githubusercontent.com/20869563/38593123-62627fcc-3d72-11e8-8eed-7bf0abb1f23e.png)
![2](https://user-images.githubusercontent.com/20869563/38593128-6838fbe2-3d72-11e8-9709-667883e2fb4e.png)

**Comment by YFZ450MANNY** [comment]
@fiam I'm not planning to use GPS at all on this build. Just simple gyro assisted flight and pass-through. It's a very small delta wing. 450mm WS.

**Comment by digitalentity** [comment]
@fiam since we added better airplane support to INAV many boards without GPS/compass support suddenly became relevant because of INAV's capability to act as a stabilizer for fixed-wing aircraft (even without RTH and other GPS-assisted features)

**Comment by fiam** [comment]
@YFZ450MANNY @digitalentity That makes sense. With GPS modules being so cheap these days, I wouldn't buy an FC without at least one uart, but I understand some pilots just want stabilization.

**Comment by digitalentity** [comment]
This is done
