### ISSUE TITLE
Feature Request free Servo and Motor mix options

### ISSUE THREAD

**Issue by Redshifft** [iNavFlight/inav#2696]
Talking to @DzikuVx  about his current work on the servo mixer for the GUI I suggested a simple total assignable option for servos and motors. 
As per nasty picture below servos/motors can be selected from the relevant drop-downs. 
Mix  source or multiple sources are then simply selected for each servo with obviously the option of  direct channel or stabilized FC outputs etc.

This will give Inav the option of  controlling more different flying machine configurations.

Any thoughts? 

![20180125_143905 1](https://user-images.githubusercontent.com/11429036/35454819-7d4fca1e-02c7-11e8-9f8e-db828e94ade8.jpg)

**Comment by ukmook** [comment]
Be very handy to have a stabilised servo for altitude. Re: Single rotor / Heli

**Comment by Redshifft** [comment]
That picture was just a basic idea for custom aeroplane, if all sources are available as mix masters any manner of flying machine should be able to be catered for. From basic mixing stuff like Elevons, 4 servo wings, differential motor control and thrust vectoring to single or twin rotor Helicopters etc..
