### ISSUE TITLE
Implement Flaperon mode 

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#270]
INAV is missing flaperon support. At least I was missing it when I still had an airplane :)

Ideas: 
1. AUX activated flight mode that that will apply predefined offset to aileron servos  
1. No special flight mode, predefined AUX channel will be mapped to servo offset: AUX low, no flaperons, AUX high full flaperon

Idea, suggestions?

**Comment by digitalentity** [comment]
I would prefer special "FLAPS" flight mode that would directly pass some value to flaps servo or add offset to aileron servos (depending on some mixer setting).

**Comment by oleost** [comment]
Its already possible to use flaperons / spoilerons with just controlling servo directly with aux.

https://github.com/iNavFlight/inav/wiki/3.-Fixed-wing-guide#optional--guides-related-to-fixed-wing

See link in the wiki. Also showing a video.

**Comment by DzikuVx** [comment]
@oleost I know it is doable, but let's be honest here, not easy to setup. I think most users would prefer something easier like activating a flight mode

**Comment by DzikuVx** [comment]
And just imagine INAV automatically deploying flaps during RTH and LAND approach... how cool is that?

**Comment by digitalentity** [comment]
Flaperon more is merged
