### ISSUE TITLE
Inav for Holybro Kakute F4 V2

### ISSUE THREAD

**Issue by IgorZaharchuk** [iNavFlight/inav#2707]
Inav for Holybro Kakute F4 V2.
Firmware for testing.

https://www.rcgroups.com/forums/showatt.php?attachmentid=10692676&d=1517341708

**Comment by IgorZaharchuk** [comment]
http://www.holybro.com/product/50

**Comment by digitalentity** [comment]
@IgorZaharchuk please have a look at #2708 and if your implementation is different - let's combine effort.

**Comment by digitalentity** [comment]
Oh, you have source code in your attachment as well. I'll review, thanks.

**Comment by Azuxul** [comment]
Link of the first message dosen't work (https://www.rcgroups.com/forums/showatt.php?attachmentid=10692676&d=1517341708) ... 
Please update it.

**Comment by digitalentity** [comment]
@Azuxul INAV 1.9-RC1 will be released soon. It will include support for Kakute V2

**Comment by IgorZaharchuk** [comment]
1.8 https://www.rcgroups.com/forums/showatt.php?attachmentid=10694258&d=1517380262
1.8.1 
https://www.rcgroups.com/forums/showatt.php?attachmentid=10694843&d=1517412958
