### ISSUE TITLE
Feature Request : Add Support for brainFPV Radix

### ISSUE THREAD

**Issue by SystemsGuy** [iNavFlight/inav#2711]
Looking for someone interested in adding support for the radix F/C - happy to get you one to play with....

**Comment by digitalentity** [comment]
Interesting FC. I'm especially interested if Bosch accelerometer will suffer the same resonance effects as Invensence ones.

**Comment by digitalentity** [comment]
After 1.9 is release I think we should look into supporting this board. Full grafic OSD would be quite nice feature to have.

**Comment by digitalentity** [comment]
https://github.com/BrainFPV/betaflight/tree/brainfpv

**Comment by fiam** [comment]
If RadixFPV is interested in sending some samples, we could definitely take advantage of the full graphic OSD. Would probably be an F4 only feature, since RAM in F3 is pretty close to the limit.

**Comment by digitalentity** [comment]
IIRC they have their own OSD hardware implementation driven by FC itself, so it's indeed F4-only feature.

**Comment by tgreer** [comment]
have prodded martin on the FB group to see if we can get the hardwares

**Comment by flounderscore** [comment]
Any word from the developers yet? ( @mluessi  )

**Comment by expipiplus1** [comment]
Did anything come of this?

**Comment by mluessi** [comment]
@expipiplus1 we maintain support for inav on RADIX in the BrainFPV fork https://github.com/BrainFPV/inav

**Comment by digitalentity** [comment]
@mluessi and you're doing quite a good job there 😄

**Comment by expipiplus1** [comment]
Thanks for the info, Martin
