### ISSUE TITLE
Feature request: In-flight Adjustment of nav_fw_cruise_thr

### ISSUE THREAD

**Issue by Hazakins** [iNavFlight/inav#2719]
looked around, could find no In-flight Adjustments for this.
Would be nice to be able to change speed / throttle value (wing in my case) on a TX pot during GPS assisted modes.

**Comment by shellixyz** [comment]
The feature has been merged this issue can be closed

**Comment by putimir** [comment]
Hi, sorry for newb question: is this implemented in current release (1.9.1)? If so, how can this feature be implemented? Thanks!
