### ISSUE TITLE
Implement F4 target support

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#274]
This is a list of tasks that need to be completed to support F4 targets on iNav
- [x] Move `pmw_init` and `timer` changes to `target` directory files
- [x] Create F4 branch `stm32f4`
- [x] Merge in @ledvinap 's `exti_io` code, see PR https://github.com/betaflight/betaflight/pull/428 and [betaflight link](https://github.com/betaflight/betaflight/pull/428/commits/3787a435341b59f1c17320efdee1dbe63a5e110e) and PR https://github.com/cleanflight/cleanflight/pull/1421
- [x] Fix issue https://github.com/iNavFlight/inav/issues/250 - Unify usage of USART/UART
- [x] Update Makefile
- [x] Add STM32F4 target linker scripts
- [x] Add STM32F4 startup files
- [x] Update timers to STM32F4 as necessary
- [x] Convert device drivers to new IO, issue https://github.com/iNavFlight/inav/issues/338
- [x] Update device drivers to STM32F4 as necessary
- [x] Update `sensors/`
- [x] Update `io/`
- [x] Update `main.c`
- [x] Update `config.c`
- [x] Add STM32F4 targets, at least REVO
- [x] Add STM32F4 VCP support
- [x] Add USARTS 4,5,6 
- [x] Add STM32F4 libraries

See also https://github.com/betaflight/betaflight/pull/452/commits for and PR https://github.com/iNavFlight/inav/pull/264 for useful commits.

**Comment by blckmn** [comment]
@martinbudden Let me know if you need any help? I can always work on BF for anything missing and you can pull it in here.

**Comment by martinbudden** [comment]
@blckmn , thanks for the offer. I don't think there are any blocking issues at the moment, but if I find any I'll ask for help. At the moment its just a question of working through the tasks. There are still some betaflight bugs outstanding, especially the F4 ESC passthrough - so your continued work in that area is needed and appreciated.

**Comment by digitalentity** [comment]
I believe all is done here. @martinbudden can you confirm?

**Comment by martinbudden** [comment]
I need to double check.

**Comment by martinbudden** [comment]
@digitalentity , I've now checked through all these and there are, as far as I can tell, no F4 related changes that need to move over from betaflight.

However betaflight has fixed some bugs in the BLHELI passthrough code and also has some enhancements to the LED STRIP that are not yet in iNav. Do you want me to move these over for the next release candidate, or do you want to wait for 1.3?

**Comment by digitalentity** [comment]
@martinbudden we have no bugs for them but they can be considered significant bugfixes. If possible please pull the code to INAV for next release candidate, thanks!

**Comment by martinbudden** [comment]
Closing this. I will create separate PRs for the LEDSTRIP and BLHELI passthrough fixes.
