### ISSUE TITLE
matek f405 osd 

### ISSUE THREAD

**Issue by mariotxt** [iNavFlight/inav#2741]
https://www.youtube.com/watch?v=uC_qPh1EOo4&list=UU8mn4p_ip6O67MPsg8zJbBQ
 when activating the function. the servo goes down. I'm using version 1.8

**Comment by shellixyz** [comment]
That's because the LED output is on PWM5. You can't use both a servo on PWM5 and the LED_STRIP feature.

**Comment by stronnag** [comment]
This support issue appears resolved, closing
