### ISSUE TITLE
Add support for NRF24L01 based receivers

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#275]
The NRF24L01 is a low cost low power transceiver in the 2.4GHz band. It is used by many toy quadcopters.

**Comment by digitalentity** [comment]
Thanks! I'll try testing this when new hardware gets to me.

**Comment by martinbudden** [comment]
@digitalentity , I've merged this in now.

**Comment by jamedavid2017** [comment]
this project do not work .
