### ISSUE TITLE
IST8310 Magnetometer

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#2750]
can not get the IST8310 to work with INAV 1.8.0. Which I2C adress do you support or do you check all possible?
I use the Omnibus PRO V3 with MPU6000 and connect the IST8310 to the I2C port. The HMC5883 did work, but when I change the magnetometer to IST8310 setting or Auto detect, it does not find the IST8310.

**Comment by shellixyz** [comment]
Looking at the source code it will only be detected if it has the adress 0x0C

**Comment by digitalentity** [comment]
In 1.8.0 IST8310 is not enabled for most targets. Already fixed in development. Stay tuned for upcoming 1.8.1-RC1
