### ISSUE TITLE
LED indicator not working properly on Matek F722

### ISSUE THREAD

**Issue by MrAlfabet** [iNavFlight/inav#2759]
### Board and Version
Matek F722
Development branch 1.8.1 as can be downloaded here: https://github.com/iNavFlight/inav/files/1670858/inav_1.8.1_MATEKF722.zip
As provided by digitalentity in this issue thread: https://github.com/iNavFlight/inav/issues/2686

INAV/MATEKF722 1.8.1 Jan 28 2018 / 07:30:22 (5afb5b8e)

### Behavior
I have 32 LED's on my quadcopter, with an X layout as can be seen here: https://i.imgur.com/sv27r6n.png
The outermost 3 LEDs on each arm function as GPS LEDs (this or other functions/just color doesn't matter), with the indicator overlay enabled. All of these have orientation set (set or not set doesn't matter). 
I want to use LEDs 5-6-7, 13-14-15, 21-22-23 and 29-30-31 as indicators for the quad going to pitch/roll. However, only LEDs 7, 15, 23, 29-30-31 work as indicator lights. If you read closely, you saw that on the right rear arm all 3 LEDs work as indicators, but on the other arms only the outermost LEDs.

This is not a feature request.

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/vMi0MrV8

**Comment by putimir** [comment]
I would like to add that on my MATEKF405 I'm also having problems setting up indicators. Behaviour is exactly as described in Betaflight issue 2225 (https://github.com/betaflight/betaflight/issues/2225).
