### ISSUE TITLE
tolet bowl 3d hold

### ISSUE THREAD

**Issue by autodog2** [iNavFlight/inav#2770]
ok just a freq thing
rth and 3d rock solid hold (good thing). Did good cals. I fixed the fly aways, yep set align_mag = cw270_flip.
problem: my hold is so strong that the drone will brake to an angle of 45deg. Very hard braking effect.
Problem 2: toilet bowl effect when only pointed at east. Walk up and push it around if its pointed N,S, or West. You ask how well do it hold, 10mph gust and i can hang things on it for 10 min flight time.
  This is my first build so im new to it all (be kind).   Frame Realacc real1s.  FC Matec f722.  ESC Racer star 4in1 35A (spec beli600).  Racer star 2307 fire ed.  e-flit 4S lipo.  Standered GPS PIDs

**Comment by DzikuVx** [comment]
https://www.youtube.com/watch?v=FlEm0-pXNf0 but since there is no desciption, I'm closing this one
