### ISSUE TITLE
wiki suggestion: Guide for mission planing

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav#279]
I just started to look into waypoints stuff a week ago and very quickly run in to some problems.
I can't find a guide how to setup things and things that I need for it. I am a mac OS user (no pc, no android devices) so information is nearly non existent.

So please, create a wiki (windows/android/osx/idevices in mind) how to get things going.
• What hardware is needed to monitor the quad during flight? (BT/3DR and so on)
• How to configure a mission and where is the GUI for that? (Win/Mac/...)

I have bought a 3DR Radio Telemetry Kit but can't find a GUI for MacOS, so I gave up on playing with missions for the moment.

**Comment by stronnag** [comment]
I keep meaning to do this, from the numerous private emails I end up writing in the subject.

**Comment by skaman82** [comment]
@stronnag can't wait for it!

**Comment by skaman82** [comment]
It would also be great if someone could include GCS and a mission setup tab into configurator. 
I can help to make the interface for this.

**Comment by stronnag** [comment]
wiki page started https://github.com/iNavFlight/inav/wiki/iNavFlight-Missions. This is work in progress.

**Comment by skaman82** [comment]
Great, thank you. From the looks of it there is currently no real solution for me to get mission planing working :(. I hope we can include this into configurator so we don't have the issues of different platforms.

**Comment by stronnag** [comment]
I think MAVLink (for 1.12) will make other tools available, some of which are available on macOS (e.g. QGroundControl).

**Comment by skaman82** [comment]
Thanks, QGroundControl looks actually quite nice - looking forward to mavlink then :)

**Comment by DzikuVx** [comment]
Question about MAVLink... It will be full MAVLink? This topic has somehow skipped me

**Comment by stronnag** [comment]
It is not full MAVlink. AFAIK from when I tested the CF implementation with mwp, it is enough to do mission monitoring, and could easily be extended to support mission upload (I don't believe this is yet implemented on the FC side). I know how you like these little challenges :)

**Comment by DzikuVx** [comment]
I've allowed myself to add a few links to my web page (QuadMeUp) with howtos and tutorials.

**Comment by skaman82** [comment]
@stronnag this sounds promising for OSX/iOS users, at least after MAVLink is supported: https://github.com/mavlink/qgroundcontrol/issues/3573#issuecomment-226251791

**Comment by digitalentity** [comment]
At the moment MAVLink support is going to be one-way (telemetry only). In future we might also implement waypoint protocol via MAVLink telem.

**Comment by skaman82** [comment]
_sadface_ :)

**Comment by stronnag** [comment]
That is what the wiki page currently states.

**Comment by skaman82** [comment]
@stronnag as far I can see there is no mention of the qgroundcontrol project

**Comment by stronnag** [comment]
https://github.com/iNavFlight/inav/wiki/iNavFlight-Missions#telemetry-protocols

**Comment by skaman82** [comment]
@stronnag sorry, my bad

**Comment by oleost** [comment]
Guess this issue can be closed?
