### ISSUE TITLE
Request: Switch Arming detection delay

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#2793]
This Feature request is due to 2 crashes with a quadcopter during use of an backup recievcer. 

Issue: We used an backup Receiver because the planned one with better range and quality did need a few weeks of shipping. 
We used a cheap single antenna receiver on our camera quadcopter. During a mission flight test, suddenly the quad just dropped out of the sky from about 25m height. Unfortunately the Blackbox was not enabled and we did not found the cause of the crash. A few days later during another test flight the same happened again but we had attached a GoPro filming with sound. On the video we heard that the SPRacing F3 Deluxe made beep signals that could be an arming beep and immediately after props stopped, they have powered on again and tried to catch the quad mid air but it was falling too fast and crashed again (but not as hard because it was 30m high this time).

It seemed that the receiver made some glitches on single channels (PPM) that caused a very short disarm and the FC took too long to power up motors again on alt hold mode. This is not the first time I saw these glitches on different receivers with PPM or PWM signals. 

The possibility of activating a delay of accepting disarm signals, let's say 0.5s, would avoid such issues. Of course a Stick Disarm would avoid this too but in emergency situations I prefer switch disarming.

**Comment by DzikuVx** [comment]
@b14ckyy this will be a part of INAV 2.0 as done in here #3118
Default disarm delay is 150ms and can be configured.
