### ISSUE TITLE
Bug: iNav Configurator 1.9.1: Expo Graph

### ISSUE THREAD

**Issue by BigTradioman** [iNavFlight/inav#2795]
The RC Expo Gaph, the botoom one on the receiver tab is not working and doesn't show  up until the Manual RC is moved from 0.0.

**Comment by shellixyz** [comment]
This issue should be posted to the iNav-configurator issues: https://github.com/iNavFlight/inav-configurator/issues

I can reproduce the issue with chromium on Linux the manual expo graph is not working. The standalone app does not experience this bug.

**Comment by Redshifft** [comment]
Yes there is strange **** going on with chrome Inav configurator atm !
