### ISSUE TITLE
SD Card doesn't work on MATEK F722

### ISSUE THREAD

**Issue by StefanRvO** [iNavFlight/inav#2796]
I am using a MATEK F722 board with iNav 1.9.0-RC1. 

When trying to use the SD-Card for blackbox logging, i get the following error in the configurator: "Fatal error. Reboot to retry", and blackbox logging does not work during flight.

Logging works in the newest betaflight, so there should be no issues with the hardware.

**Comment by dleask** [comment]
Confirmed, was also the same Fatal Error message with 1.8.1 and both Matek provided 1.8.1 hex's
Works fine in Betadlight

**Comment by StefanRvO** [comment]
I am willing to try to find the reason for the issue myself, but as I haven't worked with iNav before, it would be helpfull if someone could give some hints at what parts of the code could cause the issue.
As I guess the problem is probably some kind of misconfiguration of the MATEKF722 target, I have tried to compare the target files in iNav with the ones in betaflight, but didn't find any difference which I thought was likely to be the cause.

**Comment by dleask** [comment]
I’ve tried three different SD cards today and I can get one of them to work with the 1.9.0 firmware. Looks like it may be down to sensitivity of the card format. I’ll fry different formatters to see if there is some consistency.

**Comment by MrAlfabet** [comment]
I'm using the hex from this issue: https://github.com/iNavFlight/inav/issues/2686

It's working fine with blackbox logging. Just FYI.

**Comment by StefanRvO** [comment]
I just bought a Sandisk Ultra 16GB card as suggested by the Wiki. This one seems to work as opposed to the 1 GB no-name sdcard I used before. 
However, I still don't get why it would work in betaflight and not in iNav (i tried the build suggested by MrAlfabet with the same result).

**Comment by digitalentity** [comment]
It's possible that Betaflight uses lower SD-card clock.

**Comment by putimir** [comment]
Same to report as StefanRvO: Sandisk Ultra 16GB HC1 works, but none of the 8 noname older 1,2,4 GB cards...
Not to much of a big deal as far as I'm concerned...

**Comment by wilco1967** [comment]
Same here.....
blackbox logging doesn't work on iNav with 2 different cards (1GB + 16 GB).
Fatal error....

after Flashing with betaflight, it works... (but I'm not interested in betaflight.... ;-)

version: INAV/MATEKF722 1.9.1 Mar 27 2018 / 20:57:12 (3a5e34e6) (self compiled development version)

update
Just tried newest development, with the same SD card, and now it seems to work (the one that started working with betaflight)...
version: INAV/MATEKF722 1.9.1 Apr  3 2018 / 22:11:47 (af554014)

and going back to 27 mar version, still works.... Very strange...

I didn't remove the card in between various versions... started working with betaflight, and kept working since.... (for as long as the FC stayed powered.

BUT: after powering down the FC, same problem again.....

**Comment by b-shukhat** [comment]
Can confirm the issue:

MATEK F722-STD
iNav 1.9.1
SD card: Transcend 16GB MicroSDHC Class10 UHS-1.
Reformatted with both Windows and SD Card Formatter, FAT32.
Display: "Fatal Error. Reboot to retry".
Works with Betaflight.

Response from Matek asked to post the issue.

**Comment by b-shukhat** [comment]
Is there any solution/advice for the issue?

**Comment by wilco1967** [comment]
Tried quite a few cards. Found one that works, but others that don't.

Some of the ones not working with iNav, do work with betaflight.... (on the same FC)

Somehow iNav is really picky.... But it does work, at least with some cards

**Comment by b-shukhat** [comment]
Could you share actual card types it works with?

**Comment by StefanRvO** [comment]
I have blackbox logging working with two different Sandisk Ultra cards:
* Sandisk Ultra 64GB microSDXC UHS class 1
* Sandisk Ultra 16GB microSDHC UHS class 1.

It did not work with:
* Pendrive 16GB microSDHC class 10.
* Some no-name 1GB microSDHC card

**Comment by wilco1967** [comment]
Also a SanDisk ultra 16 I got working

**Comment by b-shukhat** [comment]
I can confirm that SanDisk microSDHC UHS-1 16GB works

**Comment by Nicholas-81** [comment]
Здравствуйте. Подскажите, какая модель Sandisk Ultra 16GB microSDHC UHS class 1 действительно работает в Matek F722?
SDSDUNB-016G-GN3IN
SDSQUNB-016G-GN3MA
SDSQUNB-016G-GN3MN
SDSQUNS-016G-GN3MA
SDSQUNS-016G-GN3MN

Хочу приобрести, но боюсь ошибиться. Ни одна microSD карта, которая у меня есть, в контроллере не определилась.

**Comment by b-shukhat** [comment]
SDSQUSC-016G-ANCIA
https://www.amazon.com/gp/product/B00APCMMEK/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

**Comment by b-shukhat** [comment]
Did you try iNav? I cannot make poshold and althold work.
Thanks, Boris 

    On Thursday, June 21, 2018, 6:07:46 AM EDT, Nicholas-81 <notifications@github.com> wrote:  
 
 
Здравствуйте. Подскажите, какая модель Sandisk Ultra 16GB microSDHC UHS class 1 действительно работает в Matek F722?
SDSDUNB-016G-GN3IN
SDSQUNB-016G-GN3MA
SDSQUNB-016G-GN3MN
SDSQUNS-016G-GN3MA
SDSQUNS-016G-GN3MN

Хочу приобрести, но боюсь ошибиться. Ни одна microSD карта, которая у меня есть, в контроллере не определилась.

**Comment by Dronitoni** [comment]
I tried to use a Samsung Evo 64G, but did'nt work with my MATEK F722 STD.
Switched to Sandisc Ultra 32G, works perfect.
I'm using INAV 2.0.

**Comment by mikko80** [comment]
Not work:
Kingston micro SDHC V30 32GB (red label)
Kingston micro SDHC 10  32GB (white label)
Kingston micro SDHC I 10 64GB (white card, blue label)

Work:
SanDisk Ultra 16GB micro sdhc I 10 A1 ( Red / Gray)

**Comment by FlyingJonas** [comment]
I have issues with my Matek F722Std as well.
Cant get any of my SD-Cards to initialize.
Sandisk Ultra 16GB and Samsung EVO 32GB and some no Name Cards, all Same result in my Case...
Fatal SD Error...
Can anybody post an freespace file somewhere? so people can try if it works when copy pasted to sd?

**Comment by digitalentity** [comment]
Fixed in development. Will be part of 2.1 release

**Comment by expipiplus1** [comment]
@digitalentity What was the problem and fix?

**Comment by DzikuVx** [comment]
@expipiplus1 SD cards work as long as good Class 10 are used. LIke Sandisk  Ultra 16GB

**Comment by digitalentity** [comment]
@expipiplus1 fixed by https://github.com/iNavFlight/inav/pull/3984

**Comment by NSCOTTSTEVENS** [comment]
I have a PNY 32 gig that returns the same error in INAV 2.2.0  on Matek 722se.  I formatted with Tuxera formater.  Will try windows FAT32

**Comment by FlyingJonas** [comment]
It turned out that my FC Matek F722 Std was faulty. I replaced it with Matek F722 SE. Check the connections of your sd card slot. try to resolder them or replace FC. I think its hardware problem.

**Comment by NSCOTTSTEVENS** [comment]
Must be...16 gig PNY also no go.  I got it locally so I didn't have to wait.  Will order recommended cards before tearing down and re-soldering PIA.  I have another FC but that will be more of a project.  Can't tune well without BB so whatever it takes.
