### ISSUE TITLE
Feature Request: Remaining flight time/ Remaining reach in OSD

### ISSUE THREAD

**Issue by FranzAr** [iNavFlight/inav#2804]
Maybe a nice feature for OSD:

Remaining flight time and/or remaining reach based on efficiency data.
Reach is a bit difficult due to wind conditions but flight time looks doable to me.

Any thoughts on that?

**Comment by shellixyz** [comment]
Linked to #2792

**Comment by fiam** [comment]
I think @shellixyz is working on this, reopening.

**Comment by DzikuVx** [comment]
Done in #2863
