### ISSUE TITLE
6-point accelerometer calibration broken in 1.9-RC1

### ISSUE THREAD

**Issue by furiousfpv** [iNavFlight/inav#2806]
I'm using F35 with MPU9250 sensor in fw 1.9, after finish 6 steps, my board can not level. 
<img width="200" alt="screen shot 2018-02-21 at 3 09 48 pm" src="https://user-images.githubusercontent.com/18002594/36471102-de51de08-171f-11e8-88ac-ef653f041929.png">

When i use FF_WING fw 1.8 and do calib in 6 step, it worked great, board can level. Can you help me check again with calib process in MPU9250 sensor? 
<img width="173" alt="screen shot 2018-02-21 at 3 37 30 pm" src="https://user-images.githubusercontent.com/18002594/36471031-90784a96-171f-11e8-8225-79d9fa0f1da1.png">

**Comment by digitalentity** [comment]
Will test. Are you using the Configurator 1.9.1 ?

**Comment by furiousfpv** [comment]
In fw 1.9, i used 1.9.1
In fw 1.8, i used 1.8

**Comment by digitalentity** [comment]
Ack. Will test and get back to you ASAP

**Comment by furiousfpv** [comment]
My customers have same issue with calib process, https://drive.google.com/open?id=1-L-KMOah_carw_SIp7FWPumnAZh25kmh

Thank you so much @digitalentity

**Comment by digitalentity** [comment]
@furiousfpv try doing a full erase when flashing 1.9. Helped in my case.

**Comment by furiousfpv** [comment]
@digitalentity Yes, i tried many time with full erase. Same problem.

**Comment by furiousfpv** [comment]
@digitalentity  BTW, i tried with FF_FORTINIF4 worked great with 6 steps calib. Board can level and all axis are good. FortiniF4 use MPU6500 library.

**Comment by brat002** [comment]
I don't really know if the bug is similar, but my friend also got an very strange behaviour last week https://youtu.be/ZQlX_PnT1fE?t=36. Horizon started to behave like crazy. We seen that at least 3 times during 2 weeks. 

Matek f405-ctr
Inav 1.8.1

**Comment by digitalentity** [comment]
Bug confirmed. Some other boards seem to be affected as well.

**Comment by digitalentity** [comment]
Found a bug. Fix pending.

**Comment by furiousfpv** [comment]
So cool, Can you give me target file of F35 for test? @digitalentity

**Comment by digitalentity** [comment]
@furiousfpv sure, once I make a proper fix

**Comment by furiousfpv** [comment]
Can you finish today?

**Comment by digitalentity** [comment]
@furiousfpv hex for testing
[inav_1.9.0_FF_F35_LIGHTNING.zip](https://github.com/iNavFlight/inav/files/1746700/inav_1.9.0_FF_F35_LIGHTNING.zip)

**Comment by furiousfpv** [comment]
<img width="175" alt="screen shot 2018-02-22 at 1 20 34 pm" src="https://user-images.githubusercontent.com/18002594/36523244-3eda09f4-17d3-11e8-89b0-05b8cfc7923c.png">
It worked great @digitalentity . Thank you so much.

**Comment by digitalentity** [comment]
Good to hear! Fixed.
