### ISSUE TITLE
F35 Lightning FC baro not detected

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2807]
Firmware 1.9
Baro is not detected.

@furiousfpv, my sample of F35 board has MS5611 baro while target file indicates that only BMP280 is supported. Which baro does the production board have and how is it connected? If possible, send me production board schematics by email.

@MJ666 maybe you can assist?

**Comment by furiousfpv** [comment]
Hi @digitalentity F35 production use BMP280. Prototype board i sent you before use MS5611.

**Comment by digitalentity** [comment]
Thanks.
