### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#282]
The readme is all about Cleanflight - it should be about iNav!

**Comment by digitalentity** [comment]
You are right! I'm always busy writing code - usually don't have much time to write docs :smile:

**Comment by DzikuVx** [comment]
OK, on it...

**Comment by DzikuVx** [comment]
OK, done in a588ee08b96dcbba54e903b9c9b596a7e068ded8
I also allowed myself to change few sentences, remove baseflight migration

**Comment by martinbudden** [comment]
I don't think we should close this yet.

The readme doesn't really give a summary about what iNav is all about. The first line is:
"Clean-code version of baseflight flight-controller - flight controllers are used to fly multi-rotor craft and fixed wing craft." It goes on to talk about software development practices and then has a big list of features none of which are to do with navigation.

I'll mark this issue as "in progress" and people can make improvements as and when they have time.

**Comment by DzikuVx** [comment]
Yeap, you are right... help welcome
