### ISSUE TITLE
Sensor MPU9250 cannot detect in EZGUI or Android app for INAV

### ISSUE THREAD

**Issue by furiousfpv** [iNavFlight/inav#2824]
I'm using F35 Lightning with 1.9 INAV fw. In 1.9 we changed lib to MPU9250, all software on Android or IOS cannot detect this sensor. 1.8 with MPU6500 no problem. 

@digitalentity can you help us check? 

Thank you so much.

**Comment by digitalentity** [comment]
If the board itself works and sensors are shown correctly in CLI and Configurator - it's not a firmware issue. Please open issues in ground station software that doesn't work properly.
