### ISSUE TITLE
Add softserial definition in MatekF405 target

### ISSUE THREAD

**Issue by MATEKSYS** [iNavFlight/inav#2841]
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_TX_PIN      PA0  //TX4 pad
#define SOFTSERIAL_1_RX_PIN      PA1  //RX4
 pad

{ TIM5, IO_TAG(PA0),    TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM5, TIM_USE_PWM },  //TX4 softserial1_tx
    
{ TIM5, IO_TAG(PA1),    TIM_Channel_2, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM5, TIM_USE_PWM },  //RX4 softserial1_rx

new target file
[MATEKF405_target.zip](https://github.com/iNavFlight/inav/files/1761583/MATEKF405_target.zip)

customized firmware
[inav_1.9.0_MATEKF405_softserial.zip](https://github.com/iNavFlight/inav/files/1761586/inav_1.9.0_MATEKF405_softserial.zip)

**Comment by digitalentity** [comment]
I believe we can close this
