### ISSUE TITLE
Adding an AUTO ON/OFF FAA Altitude Height limit of 400FT option.

### ISSUE THREAD

**Issue by alanfj** [iNavFlight/inav#2843]
In the USA according to the FAA, we are now required to fly our quads no higher than 400ft. It would be nice to have a AUTO ceiling height limit switch as part of the flight modes. Flying within this requirement and being safe is now the law. Maybe this can be added for future releases?

**Comment by shellixyz** [comment]
Linked to #1510 and #2322

**Comment by giacomo892** [comment]
@alanfj for the moment you can set an altitude alarm on the OSD. No one will ever come and say you were breaking the altitude limit by few meters...

**Comment by Redshifft** [comment]
Overlooked is the fact that the 400ft height limit is AGL, how will INAV be able to work that out if you fly around hills and mountains ?

I personally think a ALT warning is adequate and I sit on the side of the fence that considers rules and regulation less valuable that common sense. Many may consider the 400ft their right when sharing Air space and I doubt they are even aware full size aviation has no Low altitude limit over open water or sparsely populated areas (Generally the same places us sensible FPV pilots fly)
