### ISSUE TITLE
Mixing Throttle and AUX 2

### ISSUE THREAD

**Issue by OH6MQM** [iNavFlight/inav#2845]
If you activate UART 3 for any purposes
Then Throttle and AUX 2 and other channels will be mixed 
while having PWM receiver

**Comment by OH6MQM** [comment]
Flight controller is SP Racing F3

**Comment by digitalentity** [comment]
This is expected behavior because UART3 uses the same pins as PWM_IN3 and IN4. Channels are not mixed, they are shifted and you should connect your receiver's CH3 to IN5, CH4 to IN6 etc.
