### ISSUE TITLE
Add total trip distance to OSD

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2847]
This is a very useful value to see for long-range pilots.

**Comment by shellixyz** [comment]
I propose to use this icon for the trip OSD item based on the one used by minimosd-extra: ![trip](https://user-images.githubusercontent.com/4030264/36954792-b5b7dcbe-2024-11e8-8e99-e4089f5f7abd.png)

**Comment by digitalentity** [comment]
Good idea!
