### ISSUE TITLE
led stripe not working at Kakakute F4

### ISSUE THREAD

**Issue by TIMSCHMITZ** [iNavFlight/inav#2858]
### Board and Version
# version
# INAV/KAKUTEF4V2 1.9.0 Feb 26 2018 / 06:49:22 (1b9c3a39b)

### Behavior
LED Config via Configurator tab isn't working because while in wire ordering mode no numbers are assigned.

with cli 
# feature LED_STRIP
Enabled LED_STRIP

# led 0 0,15:SD:AWI:0
Unknown command, try 'help'
#

thank you in advance

**Comment by digitalentity** [comment]
LEDSTRIP is not supported on KAKUTEF4 board

**Comment by digitalentity** [comment]
Try this firmware 
[inav_1.9.0_KAKUTEF4V2.zip](https://github.com/iNavFlight/inav/files/1771487/inav_1.9.0_KAKUTEF4V2.zip)
