### ISSUE TITLE
Benewake Lidar TFMini and TF02 support

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#2868]
Betaflight does now support the Benewake Lidar TFMini and TF02.
Will inav support this in the next version, too? 
Also the Teraranger evo would be really interesting to support.

**Comment by shellixyz** [comment]
I've got a Benewake TFMini Lidar. I will probably add support for it soon.

**Comment by Ralfde** [comment]
This would be great. Thanks for the answer.

**Comment by GrosserBlonder** [comment]
I am also very interested in iNav support for Benewake TFMini Lidar and/or Teraranger!

**Comment by DzikuVx** [comment]
Done in #3725
