### ISSUE TITLE
MATEK F772 STD - NO OUTPUT ON S6 PAD.

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#2872]
There is no output on the S6 pad for motor 6 on a Hex copter.
Board seems OK as it works in Betaflight.
Similarly, no servo output on this pad when configured for AIRPLANE.

**Comment by shellixyz** [comment]
I can reproduce this issue. ~On my board the S6 pad is not connected directly to any pin of the MCU so it would explain the issue...~

EDIT: There is 200ohm resistors between MCU pins and outputs on this board that's why the continuity tester couldn't find the pin. S6 is connected to PA8 as expected. So this is not the cause of the issue.

**Comment by digitalentity** [comment]
@MATEKSYS - hardware issue?

**Comment by shellixyz** [comment]
Scratch that it looks like there is a resistor between the MCU pins and the output pads.

**Comment by shellixyz** [comment]
S6 is connected to PA8 via a 200ohm resistor. So the output definition in `target.c` looks good. Timer 1 channel 1 is the right timer definition too. No other timer can be used with this pin.

**Comment by ghost** [comment]
As a work around, I have edited target.c and used a customairplane mix to route the rudder output to pad 5 instead of 6..
It works on the bench but is it safe?

**Comment by shellixyz** [comment]
You can do that it is safe. The only thing is that with this mod basically you can't use a different PWM frequency for the ESC and servos. Just use standard 50Hz PWM frequency for the ESC and servo and everything will be alright.

**Comment by ghost** [comment]
Thanks for that. I assume that this is because it is sharing Timer 3 with M1?
This is my first foray into FW so I am taking my time with it. 
Hopefully by the time I am ready to fly, this problem will have been fixed.
Thanks again.

**Comment by shellixyz** [comment]
Yes it is because timer 3 is shared

**Comment by ghost** [comment]
Just noticed that there is a pad 8 on the board.
So, would using the normal target.c (M2 enabled) but using a custom mix to route the elevator to pad 8 be a better work around.

Sorry meant pad 7, PB8

**Comment by shellixyz** [comment]
Yes it uses a different timer from the others pins so you wouldn't have the sync ESC/servos PWM frequency limitation.

**Comment by digitalentity** [comment]
Interesting findings. @shellixyz any clue why this output doesn't work then?

**Comment by shellixyz** [comment]
@digitalentity No idea yet unfortunately. Could it be something special about F7 MCUs ?

**Comment by digitalentity** [comment]
It's definitely related to timer driver implementation on F7. Might take a while to figure out.

**Comment by MATEKSYS** [comment]
Tested 1.9.0_RC1 & final release just now, no servo signal on S6
Tested 1.8.1 built on Jan.18. It works

[inav_1.8.1_MATEKF722_0118.zip](https://github.com/iNavFlight/inav/files/1787717/inav_1.8.1_MATEKF722_0118.zip)

**Comment by digitalentity** [comment]
Found a bug. Good old memory corruption. Not fun to track without SWD. 
@MATEKSYS please consider adding SWD pads on your boards 😉

**Comment by digitalentity** [comment]
Fixed by #2891. Closing
