### ISSUE TITLE
(Bug)Inflight board Adjustments

### ISSUE THREAD

**Issue by JonnyFPV** [iNavFlight/inav#2880]
### Board and Version
Omnibus F4 Pro V3
INAV/OMNIBUSF4PRO_LEDSTRIPM5 1.9.0 Mar  5 2018 / 00:22:05 (dc4ef594f)

### Behavior
* _I configured inflight adjustment for the new criuse trottle and board alingnment values. 

if i want to change board alignment for roll it changed values for pitch. And if i want to change pitch it changes roll values in configuration tab.

**Comment by digitalentity** [comment]
You probably have yaw board alignment at 90 or 270 deg.

Board alignment values are from the board perspective - if the board is 90deg rotated pitch alignment for aircraft becomes roll alignment for board.

In-flight adjustments (as well as stick commands) are relative to the aircraft for pilot's convenience and firmware takes care of yaw board rotation for you.

**Comment by shellixyz** [comment]
I checked again to be sure and it is working fine for me. Firmware version 1.9.0 release and configurator version 1.9.2. The roll adjustment is changing roll alignment angle and pitch adjustment is changing the pitch alignment angle.

**Comment by digitalentity** [comment]
I believe this issue is irrelevant. I've also tested and board alignment adjustments work correctly.
