### ISSUE TITLE
Add Spektrum Bidir SRXL

### ISSUE THREAD

**Issue by mwsadc** [iNavFlight/inav#2886]
Could Spektrum Bidir SRXL be added as a Serial Receiver Provider, as in Betaflight?

https://github.com/betaflight/betaflight/wiki/Spektrum-SPM4649T-SRXL-Telemetry-setup

**Comment by fiam** [comment]
@mwsadc I don't think any of the active contributors have Spektrum gear, so it seems unlikely. Writing code blindly and then asking someone to test it for you is very time consuming (even if you can reuse some code from BF, the RX layer is quite different right now). However, if you can write the code, test it and send a PR it will be gladly accepted.

**Comment by ninja-zx11** [comment]
That would be great if someone could please add it.Eagerly waiting for it.Not an expert otherwise i would have tried it at least but absolutely no programming/coding knowledge.I used it on betaflight and it works nicely.Now waiting for it on inav.

**Comment by mathewpeterson** [comment]
@SpektrumRC, is this something you would be willing to contribute or sponsor since you added SRXL2 to Betaflight recently?

**Comment by SpektrumRC** [comment]
> @SpektrumRC, is this something you would be willing to contribute or sponsor since you added SRXL2 to Betaflight recently?

Sorry not 100% sure what you're asking here? Are you asking if we'd implement Bidi SRXL, implement SRXL2, or providing gear to active developers for testing? 
I have not looked at iNav code much so I'm not sure how much it differs from betaflight now, and how difficult that would make merging the protocol implementations from betaflight to here.

**Comment by mathewpeterson** [comment]
@SpektrumRC Yes (inclusive `or`) :)

My ask is to get SRXL (and/or) SRXL2 support into iNav flight firmware.

I only speak on behalf of myself so I have no idea what the active contributors would be willing to do, if anything, if they were provided support from you folks (be it test gear or anything else).

If the active contributors are not inclined to write the code themselves, is this something you could look at doing?

**Comment by SpektrumRC** [comment]
@mathewpeterson I (Miguel) have considered taking some time at some point to implement SRXL2 at least since I use iNav in one of my planes. I was going to wait until the SRXL2 implementation that was just merged into betaflight master at least makes it into a release first, then hopefully I can look into how much effort it might take to merge that to iNav. I'm not sure when I'll have a chance to do that though. If one of the active iNav dev's are interested in taking ownership of Spektrum related stuff though, I could possibly look into providing them with some Spektrum gear for testing/verification purposes.

**Comment by mathewpeterson** [comment]
Thanks for responding! 

That sounds great to me! Please let me know if there's anything I can help test!

**Comment by CloudsCapone** [comment]
I am still not seeing support for SRXL2 with iNav, am I missing it, can it be done in CLI like betaflight?

**Comment by michalsok** [comment]
Just adding my vote to see the SRXL added to iNav since telemetry is critical in remote/ semi autonomous flying.
Thank you for considering.

**Comment by DzikuVx** [comment]
@SpektrumRC we have more users requesting SRXL and it's really up to you

**Comment by MiguelFAlvarez** [comment]
I have added an update to issue #5265 with a link to test builds for SRXL2 support. This does NOT include support for the older Bidi-SRXL.
