### ISSUE TITLE
iNav should consider implementing a semi-armed state

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#289]
In the semi-armed state servos are enabled but motors are not. This enables servos (rudders, elevators, tri-copter tail servo, camera gimbal servos) to be pre-flight tested without arming the aircraft.

Arming could be on a three-position switch, or if arming with sticks first arming action semi-arms the quad, second fully arms it.

This behaviour should be user-configurable.

**Comment by flounderscore** [comment]
Why not always enable the servos?

**Comment by oleost** [comment]
I can already move servos on airplane without arming?
15. jun. 2016 8.53 p.m. skrev "Florian" notifications@github.com:

**Comment by DzikuVx** [comment]
Servos all always written, no matter the armed state

**Comment by martinbudden** [comment]
OK,I'll close his.
