### ISSUE TITLE
GPS red, while magnetometer is blue. Matek 405 CTR + TS100

### ISSUE THREAD

**Issue by Alex-Chist** [iNavFlight/inav#2895]
### Board and Version
Matek 405 CTR 
INAV 1.9.0 
firmware from manufacturer website 

# INAV/MATEKF405 1.9.0 Feb 18 2018 / 15:03:23 (f8dcc1a47)

### Behavior
Connect GPS as shown in videos and on site
Setup in configuration -> Sensors -> QMC5883 magnetometer
Expect to see Magnetometer and GPS OK
Actual results only Magnetometer works while module lights green. 
Heading is being read, but in GPS tab or in GPS module icon - nothing/red icon.

_Is this a new feature request?_
No

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/j1MYv2kv

**Comment by stronnag** [comment]
You have not calibrated the magnetometer. Please read the documentation before creating issues. This is not a support channel.
