### ISSUE TITLE
Omnibus F4 V2.1: Ibus reciever, GPS red, will not find satellite, no messages 

### ISSUE THREAD

**Issue by spflyer** [iNavFlight/inav#2897]
I've been trying for days to get the GPS working with my Omnibus F4 V2.1 clone purchased from Banggood. https://www.banggood.com/BF3_1_5-Omnibus-F4-V2-Flight-Controller-STM32-F405-MCU-Integrated-OSD-Built-in-5V-BEC-Current-Meter-p-1143258.html?cur_warehouse=CN  I am using Omnibus F4 Pro as target and the latest version, 1.9 firmware.  Setup has proceeded normally until I get to GPS.  GPS is Beitian B-880, also purchased from Banggood. https://www.banggood.com/UBLOX-NEO-M8N-BN-880-Flight-Control-GPS-Module-Dual-Module-Compass-p-971082.html?cur_warehouse=CN I have my FS IA 6b receiver connected to the board with leads soldered directly to the special pads on the flight controller designated for DSM/IBUS.  They are the pads on the underside of the board next to the SD card holder.  Reciever is designated in Inav as Uart 1 and is working properly.  I have combined the wires from the GPS/compass into one six slot appropriately sized plug and connected it to the plug to the right of the USB port, (SDA,SCL,+5V, GND, TX6,RX6) and the TX/RX leads are inverted per usual.  I've designated UART6 as GPS in INav and set the baud to 115200.  All seems to be wired and configured correctly.  The magnetometer is discovered by Inav and calibrates as it should. Mag is green in pre-arming checks.  I've checked all appropriate boxes to enable the GPS as usual but the GPS fails to acquire any satellites and displays zero messages.  The GPS icon in the header is red and the flight controller emits a series of fast beeps.  I've tried everything to get this to work but have hit a dead end at every turn.  The GPS itself is healthy as I've tried the same GPS from another working model and it has the exact same issue.  Hoping to get this problem resolved.  I'm not a coder but I've built many multirotors.  I should probably mention that this is a hexacopter.  I realize that there's another target that designates M5 as a led strip pad but because I need M5 for one of my motors I can't use that target.  Pretty sure this is firmware issue and I hope we can resolve it.  Many thanks. 

Here is my CLI dump

    

Entering CLI Mode, type 'exit' to return, or 'help'

# dump

# version
# INAV/OMNIBUSF4PRO 1.9.0 Mar  5 2018 / 00:15:43 (dc4ef594f)

# resources

# mixer
mixer HEX6X

mmix reset

# servo mix
smix reset

# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1000 2000 1500 100 -1 
servo 4 1000 2000 1500 100 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# feature
feature -RX_PPM
feature -VBAT
feature -TX_PROF_SEL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature -FW_LAUNCH
feature -TRACE
feature VBAT
feature GPS
feature BLACKBOX
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED

# map
map AETR5678

# name
name -

# serial
serial 20 1 115200 38400 0 115200
serial 0 0 115200 38400 0 115200
serial 2 0 115200 38400 0 115200
serial 5 2 115200 115200 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 0 1 1900 2100
aux 1 1 0 1100 1250
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 2000
set gyro_sync = OFF
set gyro_sync_denom = 2
set align_gyro = DEFAULT
set gyro_hardware_lpf = 42HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6500
set acc_lpf_hz = 15
set acczero_x = -60
set acczero_y = 72
set acczero_z = -77
set accgain_x = 4087
set accgain_y = 4087
set accgain_z = 4083
set rangefinder_hardware = NONE
set rangefinder_median_filter = OFF
set align_mag = DEFAULT
set mag_hardware = HMC5883
set mag_declination = 0
set magzero_x = -13
set magzero_y = -2
set magzero_z = -11
set mag_calibration_time = 30
set baro_hardware = BMP280
set baro_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set receiver_type = NONE
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 100
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = IBUS
set sbus_inversion = ON
set rx_spi_rf_channel_count = 0
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set sdcard_detect_inverted = ON
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set motor_pwm_rate = 1000
set motor_pwm_protocol = ONESHOT125
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 100
set failsafe_procedure = DROP
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 900
set gimbal_mode = NORMAL
set vbat_scale = 1100
set vbat_max_cell_voltage = 424
set vbat_min_cell_voltage = 330
set vbat_warning_cell_voltage = 350
set battery_capacity = 0
set battery_capacity_warning = 0
set battery_capacity_critical = 0
set battery_capacity_unit = MAH
set current_meter_scale = 265
set current_meter_offset = 0
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_ublox_use_galileo = OFF
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = ALWAYS
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 1000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 5000
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_min_time = 0
set nav_fw_launch_timeout = 5000
set nav_fw_launch_max_altitude = 0
set nav_fw_launch_climb_angle = 18
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = METRIC
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_unit = MAH
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set osd_video_system = 0
set osd_row_shiftdown = 0
set osd_units = METRIC
set osd_stats_energy_unit = MAH
set osd_rssi_alarm = 20
set osd_time_alarm = 10
set osd_alt_alarm = 100
set osd_artificial_horizon_reverse_roll = OFF
set osd_crosshairs_style = DEFAULT
set osd_left_sidebar_scroll = NONE
set osd_right_sidebar_scroll = NONE
set osd_sidebar_scroll_arrows = OFF
set osd_main_voltage_pos = 2060
set osd_main_voltage_decimals = 1
set osd_rssi_pos = 2071
set osd_flytimer_pos = 311
set osd_ontime_pos = 279
set osd_flymode_pos = 2444
set osd_throttle_pos = 2113
set osd_vtx_channel_pos = 200
set osd_crosshairs_pos = 0
set osd_artificial_horizon_pos = 2248
set osd_current_draw_pos = 2145
set osd_mah_drawn_pos = 2177
set osd_wh_drawn_pos = 161
set osd_bat_remaining_capacity_pos = 193
set osd_bat_remaining_percent_pos = 225
set osd_craft_name_pos = 84
set osd_gps_speed_pos = 55
set osd_gps_sats_pos = 2400
set osd_gps_lon_pos = 402
set osd_gps_lat_pos = 384
set osd_home_dir_pos = 366
set osd_home_dist_pos = 33
set osd_altitude_pos = 2049
set osd_vario_pos = 183
set osd_vario_num_pos = 248
set osd_pid_roll_pos = 322
set osd_pid_pitch_pos = 354
set osd_pid_yaw_pos = 386
set osd_power_pos = 47
set osd_air_speed_pos = 163
set osd_ontime_flytime_pos = 2423
set osd_rtc_time_pos = 407
set osd_messages_pos = 2465
set osd_gps_hdop_pos = 320
set osd_main_cell_voltage_pos = 44
set osd_throttle_auto_thr_pos = 70
set osd_heading_graph_pos = 82
set osd_efficiency_mah_pos = 161
set osd_efficiency_wh_pos = 161
set i2c_speed = 400KHZ
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0
set tz_offset = 0
set display_force_sw_blink = OFF

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 5
set fw_i_pitch = 7
set fw_ff_pitch = 50
set fw_p_roll = 5
set fw_i_roll = 7
set fw_ff_roll = 50
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 40
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_mc_heading_p = 60
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set nav_fw_heading_p = 60
set thr_mid = 50
set thr_expo = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
set rc_expo = 70
set rc_yaw_expo = 20
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set manual_rc_expo = 70
set manual_rc_yaw_expo = 20
set manual_roll_rate = 100
set manual_pitch_rate = 100
set manual_yaw_rate = 100

**Comment by shellixyz** [comment]
Sounds like your GPS is not wired correctly. Your config looks good. Red GPS icon and fast beeps means the GPS does not communicate with the FC. Try reversing the RX/TX lines. It is possible the wire labels on the product page are for the FC side so the right wiring is TX->TX and RX->RX.

**Comment by spflyer** [comment]
Well it lights up so it's powered properly and I already tried switching
the TX rx wires and that made no difference. It's wired tx to rx, rx to tx.
I wish it was that simple.  I tried all the usual stuff before I asked for
help.

**Comment by spflyer** [comment]
I also tried switching uarts and same issue

**Comment by spflyer** [comment]
Compass is working so I haven't crossed any of those wires with the GPS

**Comment by shellixyz** [comment]
That's strange. I've got an Omnibus F4 PRO and will soon receive a BN-880 GPS/Mag module. I will see if I can reproduce your issue.

**Comment by spflyer** [comment]
Thank you so much. This is a v2.1. It's a bit different from the pro.  But
I'm cautious to see if you can duplicate the issue.

**Comment by shellixyz** [comment]
In the meantime if you have got a USB-Serial adapter you could check if your GPS is working by trying to connect to it with the u-blox center PC software.

**Comment by spflyer** [comment]
Yes I do have an adapter and I'll try that.

**Comment by shellixyz** [comment]
> This is a v2.1. It's a bit different from the pro

I could be wrong but I think if it has a current sensor then it is really a PRO version. Also your config dump show that you are using the OMNIBUSF4PRO target. Anyway it is the same I've got also from Banggood.

**Comment by spflyer** [comment]
Ok, the one thing that kind of sets this fc apart is that it has 3 tiny
pads for DSM/Ibus connection.  That's where I have my receiver wires
connected.  I guess the 3 pin spectrum plug can also be used for that, at
least the 2 pins for signal and ground but the power is 3 volts.  Anyway, I
elected to use the pads and receiver is working fine.

**Comment by spflyer** [comment]
GPS fires right up in UCenter.  Shows a mess of satellites and my correct position on the map.

**Comment by spflyer** [comment]
OK, I've kinda made some progress with this issue.  It appears to be very similar to issue 2567.  I have discovered that I can indeed get the GPS working and I can get the receiver working but I can't get them both to work at the same time.  Right now I have my receiver soldered to the tiny DSM/IBUS  pads next to the sd holder.  In Inav I have Uart 1 selected as serial receiver and the receiver mode designated as serial and Ibus and it's working fine.  But as soon as I connect and enable the gps on uart 6 nothing works any more and I have to reflash the firmware with a full chip erase to start from scratch.  I've also switched to firmware inav_1.8.0_OMNIBUSF4V3_u3i.hex  as was recommended in the thread for issue 2567.  I've tried connecting the gps to the 4 pin connecter but it's the same issue.  I've gone about as far as my experience can take me.  I'll wait until you get the board and gps and hope you can come up with a solution to this.  Thanks,

**Comment by shellixyz** [comment]
Well that's a start. You probably made a mistake in the issue number as #2567 is about OSD layouts.

Even though I ordered my board from the same link you referred to in your first comment it doesn't look like we got the same one. I can't locate any pads near the SD card slot that could be used to connect a receiver. The one you can see on the left of the SD card slot is the RSSI input.

![top_lowres](https://user-images.githubusercontent.com/4030264/37317896-bbbc7856-2667-11e8-8cba-94f3e14b2957.jpg)

![bottom_lowres](https://user-images.githubusercontent.com/4030264/37317903-c5cacb40-2667-11e8-84b8-b152c6b94f00.jpg)

> In Inav I have Uart 1 selected as serial receiver and the receiver mode designated as serial and Ibus and it's working fine. But as soon as I connect and enable the gps on uart 6 nothing works any more...

Then there is clearly an electrical conflict between the pads you are using for connecting the receiver and UART6. You need to identify precisely the board you got and use the right target. The Omnibus F4 V3 expects the receiver to be connected to UART6 (so you can't use UART6 for the GPS on that board, only the RX) and the Omnibus F4 PRO expects the receiver to be connected to UART1 because they are equipped respectively with an hardware inverter for compatibility with inverted RX serial signal types like S.Bus. You might be able to identify the board by using a multimeter to trace where the RX pad is connected to. Please also take pictures of your board I might be able to identify it. My guess is that you have got an Omnibus F4 V3 and you need to use the dedicated RX pad for the receiver (UART6). Use UART1 or UART3 for the GPS. The issue is that you will need to disconnect the GPS if you want to flash the board if using UART1 and that you won't be able to use a mag if you use UART3 since it shares the same pins for I2C.

**Comment by spflyer** [comment]
This is exactly the board that I have.
https://www.banggood.com/BF3_1_5-Omnibus-F4-V2-Flight-Controller-STM32-F405-MCU-Integrated-OSD-Built-in-5V-BEC-Current-Meter-p-1143258.html?cur_warehouse=CN
If you look at the pictures you'll see 3 pads beside the SD slot.  One is
square and the other two are round.  Above they say gnd, +5v ,dsm/Ibus.
That's where I soldered my receiver wires and it works fine.  It gives
Omnibus F4SD as a target however Inav does not have that firmware
available.

**Comment by spflyer** [comment]
The issue that I meant to reference is 2576.

**Comment by spflyer** [comment]
I've been trying to use the solution outlined in this video but because I'm using ibus I can't use the inverted uart. http://www.fpvtv.co.uk/fpv-equipment/omnibus-f4-pro/2hH7NxOAKns/omnibus-f4-pro-v21-solving-gps-and-receiver-port-wiring-issues-sbus-ppm-inav/

**Comment by shellixyz** [comment]
OMNIBUSF4SD for Betaflight is the same as OMNIBUSF4PRO for iNav. You are overcomplicating things unnecessarily. You don't need to use special pads even with I-BUS you can use the RX input. The inverter is controlled by the FC and iNav knows I-BUS is non-inverted so it will disable the inverter.

**Comment by spflyer** [comment]
I've actually tried that.  I have leads soldered to the traditional rx
inputs.  I'm not sure however that I tried it with Omnibusf4pro firmware.
I hope it's as simple as this.  Snow day here in RI USA so I've got plenty
of time to experiment. I'll try this and let you know.

**Comment by spflyer** [comment]
OK, I did a clean flash of Omnibusf4pro with nothing connected to the board.  Using the traditional reciever connection port the receiver does not work on any uart, but using the leads soldered to the special pads it works fine on Uart 1. Evidently the inversion is not being done by Inav.  I would suppose that's why the special pads were put there.  I'm pretty much back where I started.  This problem seems unique to the Banggood F4 V2.1 board.  I have a Omnibus F3 set up in the traditional way with gps and compass working fine.

**Comment by shellixyz** [comment]
It is a global issue with F4 boards since F4 MCUs don't have integrated inverters on UARTs. You are probably right looking at the target.h file it is very likely the inverter on your board is not controllable since it is an OMNIBUSF4PRO, only some have this functionality. The Omnibus board versions are a mess. Now I don't know where those pads you are using for the RX are connected to exactly and since I don't have the same board I can't check but if you can't use the RX at the same time as the GPS on UART6 they must be linked somehow to UART6.

**Comment by spflyer** [comment]
OK, I've may have found a work around to this issue.  I have both the receiver and GPS working together.  The only way the receiver will work is on uart 1 soldered to the tiny pads.  What I did is connect the GPS to Uart 3 and there is no conflict, both are working.  However, since uart 3 is the traditional connection for the mag, I now have no way to connect it.  I'm hoping there is a way to connect the mag to another uart.  the only pins designated SDA/SDL are now being used by the GPS RX/TX.  Can the mag be connected to any other pins?

**Comment by spflyer** [comment]
I was hoping there was a way to configure another I2C port.  I've got both GPS and receiver working with the GPS on uart 3 but that took away my compass port.

**Comment by shellixyz** [comment]
There is no workaround for that unfortunately. The MCU's hardware I2C port uses these pins you can't do anything about that. It is the way this board has been designed.

**Comment by spflyer** [comment]
So I guess this board isn't going to do what I need it to do.

**Comment by spflyer** [comment]
Sorry about that link.  Not sure how it got in there but I can't edit it

**Comment by shellixyz** [comment]
You should be able to edit comment by clicking on the pen in the top right corner of the comment. If you want to use 2 UARTs and also the I2C bus you need to find a way to use UART1 and UART6 but it is possible you won't be able to without removing components from your board. The only way to know is to trace the tracks on your board to know what is connected where through which components.

**Comment by spflyer** [comment]
Well,I've already invested too much time in this. I've got other boards capable of doing what I need. I'm disappointed but I'm moving on.

**Comment by spflyer** [comment]
Thanks for the tip on deleting that unintended link.

**Comment by spflyer** [comment]
OK, I don't give up easily but this F4 board, and other Omnibus clones I've experimented with don't play nice with Ibus. Inav will not uninvert the receiver connection in the traditional connection pads, ppm/sbus. If you connect the receiver to uart 6 you lose the i2c port and are unable to connect a compass.  If you connect the receiver uart 1 and GPS to uart 6 there is a conflict between those two uarts that will not allow both GPS and receiver to work at the same time.  I switched to a Omnibus F3 and it all went together perfectly.  As an aside, if you're building a hex in inav with an Omnibus F3 then you can't use uart 6 for the receiver.  If you do then motors 5 and 6 pwm connections are reassigned and the motors don't show up.  I connected the receiver to uart 1, rx, +5v, gnd, and the GPS to uart 2.  Compass to i2c of course.  Uart 6 must be empty/unassigned for motors 5 and 6 to show up.  Feel free to close this issue unless you have anything to add.  Thanks for your help.

**Comment by P-I-Engineer** [comment]
you may have a dead battery in your GPS. My gps is taking forever to connect the first time for the day, like 25 minutes. I measured the voltage on the battery on the module and it self drains in minutes. I have a new battery coming to confirm this.

**Comment by spflyer** [comment]
Not a dead battery.  Gps is fine in UCenter and is working fine with an Omnibus F3 board.  Omnibus F4 doesn't play nice with Ibus.

**Comment by trunglp** [comment]
@spflyer: i use "Omnibus Pro F4  v2" and working fine.
I use:
-  ibus connect to  Uart1 (GND, 5V TX1 , RX1 )
- GPS connect to Uart6   (GND, 5V TX6 , RX6 )
-  Compass  connect to i2c  (port share pin Uart3  SCL/Tx3 , SDA/RX3  ) 
If you don't connect Compass  from i2c, you can pullup resistors (1K) on I2C bus 
https://www.youtube.com/watch?v=-zaIE-s8aHQ

**Comment by spflyer** [comment]
That won't work on the v2.1.  I tried that a million times.

**Comment by txaukos** [comment]
I have the Omnibus F4 Pro v2, which I do not know if it's version v2.0 or v2.1. The configuration of trunIp is the one I use with INAV with a UBLOX 7N, and it works.
On the other hand, if I use Betaflight with the same wiring, the GPS works but the magnetometer does not recognize it.
Sorry for my bad English.

**Comment by spflyer** [comment]
If it's 2.1 it will say so on the underside.  V2 might be different but 2.1 wouldn't work for me.

**Comment by bansawelite** [comment]
Totallly agree with @trunglp and @txaukos.
I also have the Omnbus F4 PRO v2 (not v2.1).

GPS on Uart 6
Compass SCL/TX3 and SDA/RX3 pins ( Depending on your compass/GPS module if the compass isn't detected automatically on the omnibus pull-up resistors must be added)
Add a 1-10K resistor between VCC and SCL (if compass is not detected and you've enabled the mag) 
Add a 1-10K resistor between VCC and SDA (if compass is not detected and you've enabled the mag)
I use SBUS on UART1 and have not had a problem!

Note:
It may take a couple of attempts to get the settings to stick in inav. You may need to set RX/GPS option in the SETUP screen multiple times to get it to stick.
In addition I had to use OmnibusF4V3 in the firmware target, despite me having an OmnibusF4 pro. For some reason the OmnibusF4Pro did not work for me. The giveaway to find out whether your using the correct firmware was if you try adjusting the UART settings to RX or GPS and when hitting save if it fails to reconnect each and every time (or after you hit save in general, your probably having a firmware issue).

One additional note to users reading this.. In Betaflight, the GPS works on and off temporarily transitions between 0 satelites 10 sattelites (not interference either as the quad is sometimes just sitting idle). Believe this is a betaflight firmware issue). Compass worked fine in Betaflight for me with pull-ups. 
Inav has worked flawlessly however!
RTH and position hold is a beautiful add on!

**Comment by r3df1v3** [comment]
Hi. I can confirm the findings of spflyer, as I had a similar issue with a Omnibus F4 Pro V3  (ledstripM5) and a Beitian BN-220 GPS. Using a PPM receiver connected to the RX pin and the GPS on UART1, the FC would randomly disconnect from the GPS module, especially when the Radio TX was being used. The FC would beep rapidly and the configurator showed a red GPS icon and no info in the GPS section.
I solved it by connecting the GPS on UART3 (I'm not using a mag). That way, everything works  fine.
It seems that the RX pin of UART1, is shared with the PPM pin.
I hope this helps anyone else having this problem.

**Comment by evildronepilot** [comment]
same thing..... in my case gps on uart 6 ibus on uart 3 no mag..... lousting gps as soon as I plug in the battery
