### ISSUE TITLE
Add Map mode for OSD

### ISSUE THREAD

**Issue by Nandox7** [iNavFlight/inav#2901]
One great feature that is currently mission in the OSD and that is very good for long range flying is the map mode.
MwOSD has more than one type, but having in iNav at least the default radar type would already be very good.

**Comment by FOX1185** [comment]
Good mornibg, it would also be useful to have an indication in osd angle to home to facilitate navigation both inside and outside the mission

**Comment by gmacfpv** [comment]
Will inav introduce radar on the OSD to show overlay of home location relative to aircraft position? Same as vector basically?

**Comment by fiam** [comment]
@gmacfpv We're getting there. First, we need support for multiple OSD layouts controllable by switch, which is almost ready to be added.

Can you post an image of what the radar mode in vector looks like?

**Comment by JonnyFPV** [comment]
@fiam look at this http://www.eagletreesystems.com/image/cache/data/vector-screen-legend-small-900x900.jpg

I think it work like a point moves around the center dot relative to the start position/home position.

**Comment by fiam** [comment]
@JonnyFPV Thanks for the link. The OSDs we support right now don't allow pixel based access, so we're going for a separate screen for the map and radar modes which can be controlled by a switch in the radio.

Eventually we might add an automatic override of the OSD to show map/radar when we detect another aircraft which is likely to crash with you.

**Comment by JonnyFPV** [comment]
Sounds nice :)

**Comment by gmacfpv** [comment]
Sounds really nice!

**Comment by fiam** [comment]
I'm currently implementing map mode for INAV, there's a small preview here: https://www.youtube.com/watch?v=HqDBzzS3MBU

The arrow indicates the position/orientation of the aircraft and you can also add other indicators on top of it, the map will draw around them changing the scale dynamically as needed. PR is in #3178.

**Comment by DzikuVx** [comment]
I think we can close this one

**Comment by ghost** [comment]
Fiam, I like this function.  
But after using it for a while. I have found that the "Direction indicator" and "Scaling indicator" are not absolutely needed.  
And because they are set in fixed positions on the OSD, when the Radar/Map function is selected. They just get in the way of other OSD settings that we what to place in those locations.

Can there be an option in the Radar/Map settings. To remove them if desired? Or be able to at least move them to another location on the OSD?

**Comment by teckel12** [comment]
@kardon18 I would suggest creating multiple OSD layouts and controlling them via a switch.  You then can enable the radar layout with more limited information or your standard OSD layout without radar but with additional information.  Multiple OSD layouts are really powerful.  I have them wired to an unused knob on my transmitter.

**Comment by gmacfpv** [comment]
I'm with @kardon18 on this. No need for direction and scale. It takes up crucial spots on the OSD where most people put things like voltage, rssi, GPS lock. Would be great to use the map/radar alongside these metrics without having to move them to an unusual place for them.

**Comment by teckel12** [comment]
@gmacfpv I agree as well. Distance is better than scale and direction is a duplication as well. No reason for these duplicate readings to be part of radar.
