### ISSUE TITLE
the on inav 1.9.0

### ISSUE THREAD

**Issue by Dhananjaya96** [iNavFlight/inav#2908]
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by Dhananjaya96** [comment]
I am running with AnyFC F7 .and after upgrading to inav 1.9.0 external baro the mag declination is not working .
what I tried . 1 after calibrating compass I changed the mag declination and clicked on save and reboot but its not working .same thing I tried on inav 1.7.3 external baro its working perfectly.

then comes to blackbox .its a cool feature available on 1.9.0. but it also have problem .when you power up and armed your craft no data recorded and showing fatal error 

if you connect it with pc and click on save reboot the after that it works . meaning once power up then connect it with pc click on save and reboot then its work. but in beta flight no need of this once power up black box is ready to do log files

**Comment by shellixyz** [comment]
For the external baro to work you need to flash the ANYFCF7_EXTERNAL_BARO target. What do you mean by "the mag declination is not working" ?

**Comment by Dhananjaya96** [comment]
thank you for reply

**Comment by Dhananjaya96** [comment]
sir I already flash that 1.9.0 anyfc external baro target . still mag declination is not working .I am using hmc5883 compass and there is actual declination of -10 degree . then I open the configuration tab and set mag declination to 10 degree . and then save and reboot .still there is no effect . then I try it using cli tab .nothing happen .

**Comment by Dhananjaya96** [comment]
one more question . previously I am flying my hexacopter  with I nav 1.7.3 external baro . and it feels so solid and rigid in air and return to home is extremely precise but lack of osd and sd card blackbox. but in 1.9.0 anyfc external target sd card blackbox is working for first arming then shows fatal error reboot to retry its manageable and osd looks awesome . but flying experience is not good at all while in return to home machine vibrate a lot .same with poison hold . why this happen
