### ISSUE TITLE
Servo configuration broken

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav#2910]
### Board and Version
Omnibus F3 Pro
1.9.0
INAV/OMNIBUS 1.9.0 Mar  5 2018 / 22:30:20 (dc4ef59)
Configurator 1.9.2

### Behavior
Servo configuration is broken:
a. if anything is edited in "Servos" tab either in "live" mode or edited and saved for any of the servos they "lock-up" - stop responding to TX inputs or any further configurator edits. A board reboot is required.
b. Servo trimming does not work - MID parameter offsets servo endpoints instead of changing its centre position. (Had a look at the code - if I understand correctly channel forwarding disables servo MID setting. Why is MID used to offset servo endpoints then? The only way to set servo horns at right angles and keep uniform servo travel is using extra channels from TX then?)

Tested on 2 boards.

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/WyWnH74x

**Comment by vavisimo** [comment]
I have this issue on omnibus f4 pro v2, i tought that i have somethinf wrongly configured, after every change in servo tab (eg. mid position on one servo) i hit save and the second change cant be made until reseat of usb cable.

**Comment by Arvycka** [comment]
OK...seems to be a configurator related issue.
Flashed back iNav 1.8.0 ant tried with configurator 1.9.2 - servos still freeze after editing.
Tested with configurator 1.8.1 - servos do not lock-up, end points and direction/rates can be edited continuously (MID does not behave as expected)

**Comment by digitalentity** [comment]
This is the issue in between Configurator and firmware (see https://github.com/iNavFlight/inav-configurator/issues/389 for Configurator-related issue).

When "Save" button is clicked in Configurator smix rules are sent to firmware and reloaded regardless of mixer type - thus evvectively disabling servos on unmodified AIRPLANE mixer.

**Comment by digitalentity** [comment]
Fixed by #2938

**Comment by Arvycka** [comment]
Tested, works perfectly, thank you!
