### ISSUE TITLE
ADC RSSI pad assigned to resourceless pin in CLRACINGF4AIR and other STM32F405 based targets

### ISSUE THREAD

**Issue by dimamedia** [iNavFlight/inav#2918]
### Board and Version
[CLRacing F4 Air V2](https://www.clrpowered.com/products/clracingf4-air-v2)
INAV/CLRACINGF4AIRV2 1.9.0 Mar  8 2018 / 06:50:40 (dc4ef594f)

### Behavior
I connected L9R to F4 AIR V2 board with analog RSSI to its dedicated pad and enabled RSSI_ADC. 
But on OSD the RSSI reading shows 27 or 28, even when the transmitter is off.
After some researching found out that the RSSI pad on the board is connected to pin, that has no resource assigned to it.
So technically:

RSSI pad on the board is traced to STM32F405 to pin nr 11 - PC3.
![STM32F405](http://waijung.aimagin.com/hmfile_hash_0f62a7f9.jpg)

In CLRACINGF4AIRV2 target has default: `set rssi_adc_channel = 3`

In the source:
`#define RSSI_ADC_CHANNEL                 ADC_CHN_3`
`#define ADC_CHANNEL_3_PIN               PA0`
`#define UART4_TX_PIN            PA0`

ADC Channel 3 is assigned to PA0, that is actually UART4_TX_PIN and PC3 pin is FREE?! 

So RSSI pad is just a dump pad, with no resource assigned.

### Solution
Move ADC_CHANNEL_3_PIN to PC3.
`#define ADC_CHANNEL_3_PIN               PC3`

As there is no resource remapping possibility in iNav, this should be changed in source.
This problem probably exists also in other STM32F405 based targets.

**Comment by bnn1044** [comment]
the FW is updated and post on www.clrpowered.com under CLRACINGF4AIRV2 products page download the lastest FW.

**Comment by dimamedia** [comment]
Thanks @bnn1044! I've tested it and it worked :)

So, this can be implemented also in other targets having the same symptoms with stm32f405 chip.

I think, this can be fowarded for pull request.

**Comment by shellixyz** [comment]
@dimamedia Can you confirm your modification is working ?

**Comment by dimamedia** [comment]
@shellixyz yes, RSSI signal is passing through to OSD

**Comment by shellixyz** [comment]
The RSSI ADC channel pin has been changed to PC3 (66bddee0062a4c145caa49c1f1abed58866769a8). Fixed.

**Comment by fiam** [comment]
Fixed in #2933, closing.
