### ISSUE TITLE
MAG + OLED Possible?

### ISSUE THREAD

**Issue by CradyArt** [iNavFlight/inav#2921]
Posted this on RC Groups but haven't had a response.

I'm starting with a Matek F722-STD and was wondering if iNAV supports the simultaneous connections of both an SSD1306 OLED display and a HMC5883L mag module 

Thanks!

**Comment by DzikuVx** [comment]
Yes, this is how I2C works, multiple devices can be connected in parallel to single I2C bus

**Comment by CradyArt** [comment]
Thanks for the clarification, DzikuVx

Much appreciated
