### ISSUE TITLE
Current always zero in blackbox log

### ISSUE THREAD

**Issue by StefanRvO** [iNavFlight/inav#2922]
I'm using blackbox logging on the MATEK F722 ( 1.9.0), but is having an issue with the current in the log (amperageLatest) always showing zero. I have current monitoring set up and the consumption shows correctly when viewed through the configurator.
I have also tried logging using betaflight, and here, the value is logged as it should.

iNav blackbox log:
[LOG00012.TXT](https://github.com/iNavFlight/inav/files/1811283/LOG00012.TXT)
Betaflight blackbox log:
[LOG00011_betaflight.txt](https://github.com/iNavFlight/inav/files/1811294/LOG00011_betaflight.txt)

diff:

[inav-13-09-2018_diff.txt](https://github.com/iNavFlight/inav/files/1811308/inav-13-09-2018_diff.txt)

**Comment by shellixyz** [comment]
Please post the full configuration dump. My guess is that you didn't enable the current sensor in the configuration tab. You can see the measured current in the setup tab in the right column "Current draw" and also the the configuration tab in the "current sensor" section.

**Comment by StefanRvO** [comment]
Here is a dump:
[inav-dump-18-03.txt](https://github.com/iNavFlight/inav/files/1822844/inav-dump-18-03.txt)

**Comment by shellixyz** [comment]
Your current sensor have not been calibrated (you are using the default scale and offset). Can you confirm you are seeing current values > 0 in the configurator or OSD ?

**Comment by StefanRvO** [comment]
I don't have any FPV stuff, so i don't know about OSD, but the configurator shows a non-zero current.
![screenshot_20180318_165305](https://user-images.githubusercontent.com/2931145/37567861-469ef5c0-2acd-11e8-8b60-90f1737b8836.png)
I know that it is not calibrated, but would think that some value should be logged regardless.

**Comment by shellixyz** [comment]
Indeed it should. It will be fixed in the next version. In the meantime you can use this fixed build:
[inav_1.9.0_MATEKF722.hex.zip](https://github.com/iNavFlight/inav/files/1822880/inav_1.9.0_MATEKF722.hex.zip)

**Comment by mistyk** [comment]
I've the same problem with Matek F405 could you send us a Fix ? Thanx a lot

**Comment by shellixyz** [comment]
@mistyk Sure: [inav_1.9.0_MATEKF405.hex.zip](https://github.com/iNavFlight/inav/files/1880271/inav_1.9.0_MATEKF405.hex.zip)

**Comment by dereb** [comment]
Hi, could you provide a patch for OmnibusF4 targets too please? (OmnibusF4v5) 

I can see the current draw in OSD, but nothing in the logs.

Cheers

**Comment by shellixyz** [comment]
The patch is available here: #2940 
Fixed binaries for all targets: [iNav_1.9.0_fixed_BB_current_all_targets.zip](https://github.com/iNavFlight/inav/files/1884058/iNav_1.9.0_fixed_BB_current_all_targets.zip)

**Comment by dereb** [comment]
Thank you very much!

**Comment by digitalentity** [comment]
Fix merged. Closing
