### ISSUE TITLE
Twin motor for talon setup

### ISSUE THREAD

**Issue by mrkidvn** [iNavFlight/inav#2924]
Any custom mixer for mini talon with twin motor setup, i'm plan to use matek f405 CTR for my mini talon build

**Comment by shellixyz** [comment]
For 100% yaw mixing:
```
mmix 0 1 0 0 -1
mmix 1 1 0 0 1
```

I think the left motor should be connected on S1 and the right motor should be connected to S7. But don't forget to check before takeoff. See https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md for more information about motor mixing.
