### ISSUE TITLE
Add Bosch BMI160 gyro support

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2925]
Used on BrainFPV Radix RE1

Main issue - update rate and hardware LPF

Currently we have this:
1. LPF-defined update rate (1kHz/8khz update rate)
2. Subsampling ratio (`gyro_sync_denom`) - giving gyro update rates 500Hz/1kHz/2kHz/4kHz/8kHz
3. LPF is defined as a list 256HZ (8kHz rate), 188HZ, 98HZ, 42HZ, 20HZ, 10HZ (1khz rate) - for 1kHz update rate we're free to chose from 10-188HZ

Bosch gyro is different.
1. Update rate and LPF freqnency are linked together - once you change sampling rate your LPF changes as well:
![image](https://user-images.githubusercontent.com/11059099/37468356-8e52a928-28ae-11e8-948c-5098600baf9c.png)
2. Sampling rate is NOT a multiple of 1khz - list of practical update rates is 400, 800, 1600, 3200Hz

Configuring the sensor is not a big issue, main issue - how do we keep this user-friendly. One option is just don't care about LPF and map update rate like this:

| MPU | Bosch |
| ------------- |-------------|
| 500HZ | 400HZ |
| 1000HZ | 800HZ |
| 2000HZ | 1600HZ |
| 4000HZ | 3200HZ |

**Comment by shellixyz** [comment]
I think your solution is fine. A nice touch would just be to explain why the loop time could be different from the specified `gyro_sync_denom` and that the LPF setting is ignored in the FC doc.
