### ISSUE TITLE
F35 Lightning Servo Problem with V1.9

### ISSUE THREAD

**Issue by Painless360** [iNavFlight/inav#2926]
### Board and Version
_Furious FPV F35 Lightening
_INAV/FF_F35_LIGHTNING 1.9.0 Mar  5 2018 / 01:09:23 (dc4ef594f)

### Behavior
* _The servos stop moving after a short time or if you try and change something in the Servo Tab. Servos can be enabled again for a short time by rebooting the FC by either removing all power or rebooting using CLI tab.
* _Power FC, use Manual mode, ensure servos are moving. Simply wait or enter Servo tab and change a few settings with LIVE turned on.
* _Servos should initially move and respond to the radio or to the new centre values as they change in the Servo Tab
* _Servos stop moving but the motor output appears unaffected. Reboot clears.

_Is this a new feature request?_Nope

#### Blackbox logs/Config (.ZIP) where problem occurs
_https://pastebin.com/cTmsdiMn

**Comment by vavisimo** [comment]
same as [https://github.com/iNavFlight/inav/issues/2910](2910)

**Comment by binleo** [comment]
Look like it is from app or fw, because I have the same issue when using Servo tab but when I flying, almost ok

**Comment by digitalentity** [comment]
Fixes to Configurator (https://github.com/iNavFlight/inav-configurator/pull/393) and firmware (#2938) are in place. Closing.

**Comment by Painless360** [comment]
If the fix is in place - please release it..

**Comment by digitalentity** [comment]
@Painless360 just did. Get Configurator 1.9.3 and enjoy!

**Comment by Painless360** [comment]
Thanks Buddy, already updated the video from the weekend and added it my social media feeds! That took a little bit longer to get out than you hoped. Can you pop me those Caipirinha II images you promised on Skype too please?
