### ISSUE TITLE
RC Yaw is reversed in current master

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#293]
Some change between 4db8d9c and 19887ef causes RC Yaw to be reversed (at least for PPM).

This is somewhat disconcerting and probably not intended.

**Comment by digitalentity** [comment]
Thanks for reporting. Is it RC channel or direction of rotation of the aircraft when you command yaw?

**Comment by stronnag** [comment]
It appears to be rotation of the aircraft. I move the stick expecting to yaw left, the machine yaws right. All other RC inputs appear normal (I can fly back 'home' on roll and pitch).

**Comment by digitalentity** [comment]
Thanks. It's probably recent merge of rates in degrees per second. I'll
look into it when I get to my laptop.

**Comment by digitalentity** [comment]
I believe this commit is responsible.
https://github.com/iNavFlight/inav/commit/9032cb846e75e5b42a8e32677226d66609811db1#diff-8424c55cddd22ef29138ff3ddee226a8R172
In code before that rcCommand was negated after lookup, that commit lost the -1 multiplier.
@DzikuVx is this intentional or a bug?

**Comment by DzikuVx** [comment]
Yay, looks like we'lost -1 multiplayer for yaw somewhere there indeed.. Yaw has to be reversed. For next few days i'm unable to fix and test. Anyone else? @martinbudden maybe?

**Comment by digitalentity** [comment]
I can fix it but I can't test it.

**Comment by stronnag** [comment]
Fix it, I'll test it. I can only break stuff.

**Comment by DzikuVx** [comment]
Maybe correct approach would be to negate at lookup table level? There is now a getter for yaw lookup that could do it if I remember correctly

**Comment by DzikuVx** [comment]
My snartphone says it can be done in rcLookupYaw. Probably

**Comment by stronnag** [comment]
My quadcopter says it would be nice it potentially aircraft breaking commits were not made to master until they have been flight tested.

**Comment by digitalentity** [comment]
@stronnag When merging the #204 I was under impression that it's well tested in flight by @DzikuVx, didn't flight-test it myself, sorry :pensive:

**Comment by martinbudden** [comment]
@stronnag , I agree - this commit should have been flight tested. Even a bench test would have picked up this problem.

**Comment by stronnag** [comment]
No problem, there was no damage (other than to my pride from the "walk of shame" to recover the force landed machine). 

As a number of developers branch off master, it would be helpful if we could establish a policy of at least bench tested commits.

**Comment by martinbudden** [comment]
@stronnag , years ago, when I was a relatively inexperienced programmer I had an experience which changed my attitude to testing profoundly.

I had a plumber install a new shower in my flat. He said he had finished the job, so I went in the bathroom and turned the shower on. It leaked. I couldn't believe he hadn't tested it. I realised that I and my colleagues at work sometimes had a similar lackadaisical to testing, so I changed my approach. [Needless to say, I never used that plumber again.]

**Comment by DzikuVx** [comment]
Well, what can I say... But this is true, changes after resolving latest conflicts with Martin's changes were not flight tested, only bench tested. My bad.
pid controller changes were tested, I'm flying it

**Comment by martinbudden** [comment]
@DzikuVx - no worries, we all make the occasional mistake.

**Comment by DzikuVx** [comment]
@martinbudden still, one forgotten -1 a look what happens. I'm expecting more from myself :)

**Comment by DzikuVx** [comment]
Sine it's fixed in #298 , I'm closing it
