### ISSUE TITLE
implementation of ROI - POI

### ISSUE THREAD

**Issue by chris669** [iNavFlight/inav#2931]
Objective of iNav was "improve the current "official" Cleanflight with advanced navigation functions". I think I could be also a perfect solution for photography purposes, so why not adding ROI functionalities?

**Comment by Schalonsus** [comment]
This is requested long time ago, so +1 for adding this option

**Comment by stronnag** [comment]
Duplicate of #154 closing. Please search for old issues and comment there rather than adding new ones,

**Comment by chris669** [comment]
@stronnag, don't worry, will go back to BetaFlight... iNav seems to be EOL.

**Comment by fiam** [comment]
@chris669 Your comment makes absolutely no sense. The scope of this issue is already covered by another older one and there's no good reason to keep multiple open issues for the same feature. If you want to contribute something constructive, do so in #154.

**Comment by Schalonsus** [comment]
nice, one iNav android developer less....
iNav seems really EOL atm, also what a caustically reaction from iNav devs...

**Comment by fiam** [comment]
@Schalonsus ? I'm not sure what you mean by that comment. INAV is definitely not EOL, there's a lot of new stuff coming up for the next release. This issue was closed as a duplicate, not as a WONTFIX.

**Comment by neagron** [comment]
could we please have ROI/POI and circle this would make iNav waypoints so much better and certainly more fun for me,im sorry I cant do any programing

**Comment by steviegeek** [comment]
Hi,
I second this request,

<<could we please have ROI/POI and circle this would make iNav waypoints so much better and certainly more fun for me,im sorry I cant do any programing>>

Thanks in-advance
Steve
