### ISSUE TITLE
motors stop in air osd : aircraft not level 

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#2932]
Hello,

I have just crash my drone, motors stop in air, i don't know why.
All was good as you can see on vidéo link below.
Just one thing can help to found what happened, OSD message : aircraft not level.
I found my drone with nothing broken, i test it and all is ok.
unfortunaly i don't have register black box.
Anyone know what is happened ? 

https://www.youtube.com/watch?v=magwyhLrpxM&feature=youtu.be

Thanks

**Comment by ghost** [comment]
some precisions :

Quadcopter, Inav 1.8, Omnibus F4 pro V3, Gps m8n, lipo 5s 1800 mah, TBS 1450 kv motors, 6" props

**Comment by fiam** [comment]
Which RX are you using?

**Comment by ghost** [comment]
hello,
Frsky r9 slim with last firmware 
2018-02-07 | 180202
Sbus
failsafe was set on RTH.
my drone always has good flight, failsafe ok also

**Comment by fiam** [comment]
@teamnanopirate The problem was not failsafe, it looks like it disarmed mid air. Are you sure you were running the final 1.9 an not a release candidate for 1.9? Please, paste your config dump so we can have all details.

**Comment by fiam** [comment]
@teamnanopirate Take a look at https://github.com/iNavFlight/inav/issues/2827 and see if you can still reproduce the problem

**Comment by ghost** [comment]
thanks, I'm going to look

**Comment by fiam** [comment]
Ah, sorry, didn't realise you said 1.8. As far as we know, there was a problem with the R9 slim but only on a release candidate for 1.9. Still, the most likely culprit seems to be that for some reason (bug in the RX or the FC) the arming channel was lowered for at short amount of time but > 150ms. That caused the aircraft to disarm and then you couldn't arm because the small_angle protection kicked in.

**Comment by sin5678** [comment]
crash as this before ,I am use R9 slim too, what I am fix it is  use "stick Arm" ,do not use "switch  arm"

**Comment by ghost** [comment]
Thank you all for your help, 
I will flash the 1.9 and in the CLI put the variable small_angle = 180
After I'm going to change the setting of the R9M in Taranis 8ch by 16ch. it should work.
Otherwise I'll arm with the sticks.
I'll tell you if it solved the problem.

**Comment by digitalentity** [comment]
I'd say it's a normal disarm. Possibly a momentary glitch in ARM channel - maybe a receiver issue or misconfigured failsafe.

**Comment by OlivierC-FR** [comment]
I've done a lot of tests with the R9 and R9M and R9Slim units, with the current firmwares I consider this system to be highly unreliable, mostly all the modes with telemetry. I've also experienced unexpected failsafes and weird disarms without the failsafe signal being sent proper to iNav over SBUS. Installing back the previous X4R or L9R receivers fixed all the issues on these iNav or Betaflight aircrafts.

**Comment by ghost** [comment]
maybe new Firmware fix it ? 
https://www.frsky-rc.com/r9m/

**Comment by OlivierC-FR** [comment]
Maybe... but for now there's not changelog, so good luck to anybody who wants to tests this. I may do it later this week, but to be honest I'm a bit tired to see my quads fall out of the sky because of the R9, so I'm not in a hurry.

**Comment by digitalentity** [comment]
I guess we can close this. It's definitely related to R9.
