### ISSUE TITLE
Unable to use anything other than a receiver to arm multi rotor 

### ISSUE THREAD

**Issue by kittenl0rd** [iNavFlight/inav#2937]
I would like to use my build as a way point follower but there is no way to arm it without a receiver. I am hoping to do it through telemetry or ground control station (CGS) help much appreciated.

**Comment by shellixyz** [comment]
Even if you want only to guide your craft from the GCS it is best to have a mean to control it manually. You can already arm from the GCS when only using a telemetry radio transceiver but the craft `receiver_type` needs to be set to `MSP` and iNav will only let you arm (get out of failsafe) if it receives at least 5 MSP_SET_RAW_RC commands every second (5Hz). The iNav configurator does not send MSP_SET_RAW_RC commands you will need to modify the configurator or make your own program.
