### ISSUE TITLE
smix no function after reboot 1.9.1/ Matek F722

### ISSUE THREAD

**Issue by Tribal78** [iNavFlight/inav#2939]
Hi,

I´m using a Matek F722 with Inav 1.9.1. I set up some smix rules in the servo tab. After saving I can see the proper function in the Motor tab.
But after a reboot there is no function, although I can see the mixer in servo tab and the cli. Pressing again save in ther servo tab enbales the mixer until the next reboot.

Any ideas?

BR
Sven

**Comment by shellixyz** [comment]
Did you check the custom mixer is selected in the configuration tab after reboot ? We already know there is a bug with the custom mixer configuration in the servos tab. It is possible that when you save the mixing rules it changes temporarily to the custom mixer but the mixer selection is not saved. I will take a look later in the day.

**Comment by Tribal78** [comment]
No.. didn´t checked this. I´ve just tried to find this option but I cannot find someting similar in the configuration tab? Configurator is 1.9.2.

What is the CLI command to enable the mixer?

Thanks!!

**Comment by shellixyz** [comment]
The CLI command for changing the mixer is `mixer`. Used without argument it will show the current mixer. For selecting the custom airplane mixer: `mixer CUSTOMAIRPLANE`.

![mixer_selection](https://user-images.githubusercontent.com/4030264/37568263-fb13436c-2ad2-11e8-8c36-9d8e6b456979.png)

**Comment by Tribal78** [comment]
Okay. But my purpose is to add a new mixer in order to move both ailerons up and down.
Therefore I´ve added some smixer. But as mentioned they work only directly after saving but not after a reboot?
Is there a Special comand to enable These smixer? By typing smix in the CLI they are correctly shown but for some reason they are not working.

Entering CLI Mode, type 'exit' to return, or 'help'

mixer
Mixer: AIRPLANE

smix
smix 0 3 9 97 0
smix 1 4 9 -99 0

**Comment by shellixyz** [comment]
Oh OK now I understand what you are trying to do. For the moment you can't just add mixer rules. You need to select the `CUSTOM AIRPLANE` mixer and write all the rules.

**Comment by Tribal78** [comment]
Thanks for this Information! Properly saved me a lot of time :-)
So it is not possible to use smix while the Mixer AIRPLANE is running?

Is somewhere documented what the AIRPLANE-mixer is doing? So I can use this as a base for my CUSTOM AIRPLANE mixer.

**Comment by shellixyz** [comment]
No it is not possible. Mixers are not editable. It is planned to move mixers to presets but it hasn't been done yet. When it is done you will be able to see the mixing rules for the preset and alter them.

It is documented in the source code ;)

The mixer configuration for the `AIRPLANE` setting is this:
```
smix 0 3 0 100 0
smix 1 4 0 100 0
smix 2 3 14 100 0
smix 3 4 14 -100 0
smix 4 5 2 100 0
smix 5 2 1 100 0
```

**Comment by Tribal78** [comment]
Thanks again! I´ll try this.
