### ISSUE TITLE
Omnibus F4 LED doesn't work

### ISSUE THREAD

**Issue by SpaceKnight42** [iNavFlight/inav#2953]
### Board and Version
Omnibus F4 (https://www.banggood.com/Betaflight-F4-Flight-Controller-STM32-F405-MCU-Integrated-OSD-p-1103940.html?rmmds=myorder)

INav 1.9.2

INAV/OMNIBUSF4 1.9.0 Mar 21 2018 / 15:49:19 (dc4ef594)

### Behavior
* LED-Strip doesn't work if connected to PWM5
* Connect LED Strip Signal to PWM5 Power is coming from under the port of LED-Strip
* LED-Strip light up
* LED-Strip doesn't light up

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/7GnqLciQ

LED Strip : https://www.banggood.com/Matek-8-Bit-WS2812B-RGB-5050-Highlight-LED-for-Naze32-CC3D-p-983608.html?rmmds=myorder

**Comment by VAL72** [comment]
It is very easy to fix the Pin failure of Omnibus f4 pro V2. I do not understand, why everybody tryes to fix it by remapping. The LED connector of the Board is false wired to PD2 Pin of the Processor (Pin 11 counted from right processors Side, closed to DSM connector on the Special board). The right Pin PB6 of the Processor is Pin 7 from left of this Processor Side. There are only 3 Pins between! Take a sharp knife(scalpel), Cut the Cooper in the Board direct closed to Pin PD2. Take of the isolating colour of the Cooper pipethrough next to this Pin. Check the Connection of it to Pin 3 of the LED connector. Solder the free copper. Take a very thin blank copper wire and solder it direct to Pin PB6 of the Processor. Bow the Wire to the prepaired new Pad near to Pin PD2 , direct connected to LED connector). Solder it to this new Pad. It is only 4mm away from Pin PB6! If it is soldered, cut the rest of the wire. Check the new Connection from Pin PB6 to pin3 of the LED connector. 
Work is done!
No Problems!
![IMG_20191226_201031~2](https://user-images.githubusercontent.com/17814965/71489556-6d8c4900-2826-11ea-8b73-ae9f48e8448b.jpg)
