### ISSUE TITLE
Add roll/pitch angles to OSD

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2957]
Having numeric angles of roll and pitch angle in OSD will make it easier to figure out proper board alignment angles for airplanes. @DzikuVx @fiam what do you think?

**Comment by fiam** [comment]
I think it’s good, specially once we have multiple layouts. Users can have one for normal flight and another one configured for tunning (PIDs, these angles, etc)

**Comment by giacomo892** [comment]
Would be nice to add PID outputs too. Useful for example in a wing to check live how much a surface is deflected.

**Comment by shellixyz** [comment]
@giacomo892 For a wing to check the surface deflection the servo outputs would be more useful (requested in #2674). But PID outputs would probably be useful for MRs.

**Comment by shellixyz** [comment]
This has been done the issue can be closed
