### ISSUE TITLE
Blackbox creates log 125 times in 125 folders

### ISSUE THREAD

**Issue by Antiheld86** [iNavFlight/inav#2967]
### Board and Version
Entering CLI Mode, type 'exit' to return, or 'help'

# version
# INAV/MATEKF722 1.9.1 Mar 23 2018 / 21:15:18 (c60386f9)

# 
Compiled from development branch #2963
https://github.com/iNavFlight/inav/files/1843342/inav_1.9.1_MATEKF722.hex.zip

### Behavior
On the SD card the blackbox creates 125 folders and stores the logs in every one of them.
So the logs are stored 125 times.

![logs](https://user-images.githubusercontent.com/4201585/37874616-97102b2c-3032-11e8-8cd8-dadbacb3a65d.gif)

**Comment by DzikuVx** [comment]
I can confirm
