### ISSUE TITLE
GPS SIM33ELA .....is there a chance to get it work

### ISSUE THREAD

**Issue by Der-Modellmann** [iNavFlight/inav#2969]
ive tried a super light GPS Module but it wont show anything.

I connect it with the help of the Datasheet and INAV show the write update rate about 10Hz an number of arrived messages. 
but no 3D fix......
maybe its my fault......the datasheet say that rx0 and tx0 is a NMEA output.........and i set th nmea protocol in INAV an a BAUDRATE about 115200 ......it should be the default baudrate

i hope for help ....thanks

**Comment by digitalentity** [comment]
If INAV detects a GPS and shows 10Hz update rate - no fix is likely a GPS module issue, not the firmware issue.
