### ISSUE TITLE
Add “Disarm motors regardless of throttle value“ switch

### ISSUE THREAD

**Issue by Antiheld86** [iNavFlight/inav#2983]
### Behavior
To avoid accidentally disarm in mid air it would be great to have a Feature wich does not allow disarm when throttle is above a value.

_Is this a new feature request?_
yes

**Comment by shellixyz** [comment]
This already exists. You need to set `disarm_kill_switch` to `OFF`. It won't disarm unless throttle < `min_check`.

**Comment by Antiheld86** [comment]
Thank you

**Comment by Antiheld86** [comment]
I thought there was a Switch in the configuration tab for that before. But probably i think about betaflight. In my opinion it would be nice to have this in the gui.

**Comment by shellixyz** [comment]
It is in the Failsafe tab

**Comment by digitalentity** [comment]
As @shellixyz mentioned - such feature already exists. Closing.

**Comment by Antiheld86** [comment]
In the failsafe tab this Option is disabled in my configurator. The CLI says `disarm_kill_switch=on`

![gui](https://user-images.githubusercontent.com/4201585/38130491-a11399e0-3403-11e8-87b7-596e80deef98.gif)
![cli](https://user-images.githubusercontent.com/4201585/38130492-a146a2f4-3403-11e8-9052-76725677fbbb.gif)

**Comment by fiam** [comment]
That’s a different option. See my comment in #2981.
