### ISSUE TITLE
[iNav 1.1.0 1b83047] Hott Telemetry not working when Display feature is activated

### ISSUE THREAD

**Issue by johnlenfr** [iNavFlight/inav#299]
Hi,

My telemetry doesn't work when I enable DISPAY on my RacingF3 board.

MSP on UART1
GPS on UART2
SerialRX on UART 3
HoTTtelemetry on SOFTSERIAL 2

Is it normal?

**Comment by DzikuVx** [comment]
I would call it SoftwareSerial issue, not telemetry itself. DISPLAY can consume a lot of CPU/bus time and there is not enough for SoftwareSerial.
In my case, I can not put S.Port telemetry on SS1 and MSP on SS2.

**Comment by johnlenfr** [comment]
Ok so if I understand it is normal.
I have to disable OLED feature to have my Telemetry back.

Thanks

**Comment by digitalentity** [comment]
It's a limitation of SoftSerial. Display consumes lots of CPU when updating - this messes up with softserial.
