### ISSUE TITLE
battery warning with full 4s battery

### ISSUE THREAD

**Issue by robschii** [iNavFlight/inav#2991]
Board INAV/OMNIBUSF4PRO 1.9.0 Mar  5 2018

# status
System Uptime: 16 seconds
Current Time: 0000-01-01T00:00:00.000+00:00
**Voltage: 16.43V (4S battery - WARNING)**
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=HMC5883
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
SD card: None inserted
Stack size: 6144, Stack address: 0x10010000
I2C Errors: 0, config size: 3390, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 1, cycle time: 2002, PID rate: 499, RX rate: 49, System rate: 10
Arming disabled flags: ARMSW RX THR CLI

i have now disable the buzzer  but a full battery get a warning!!

vbat_adc_channel = 2
Allowed range: 0 - 4

vbat_scale = 1100
Allowed range: 0 - 65535

vbat_max_cell_voltage = 424
Allowed range: 100 - 500

vbat_min_cell_voltage = 330
Allowed range: 100 - 500

vbat_warning_cell_voltage = 346
Allowed range: 100 - 500

battery_capacity = 2200
Allowed range: 0 - 4294967295

battery_capacity_warning = 1100
Allowed range: 0 - 4294967295

battery_capacity_critical = 1760
Allowed range: 0 - 4294967295

battery_capacity_unit = MAH
Allowed values: MAH, MWH

**Comment by shellixyz** [comment]
Your battery capacity thresholds are not configured correctly. Please read the [battery management documentation](https://github.com/iNavFlight/inav/blob/master/docs/Battery.md#battery-capacity-monitoring)

**Comment by robschii** [comment]
thx
