### ISSUE TITLE
Add presets for 7-8 inch long range quads

### ISSUE THREAD

**Issue by artempolikarpov** [iNavFlight/inav#2995]
There is a such trend now 7-8 inch long range quads. I think it would be useful for many users to add special preset.

Motors are 2306, 2207 but with GPS, mini brushless gimbal or straight HD camera mount.

Now there are:
5 inch racer
5 inch GPS
10 inch standard quad

So it looks like gap for 7-8 inch quads.

**Comment by DzikuVx** [comment]
@artempolikarpov if you can define such a preset in terms of PIDs and filtering, we can easily add it. I do not have such a platform to create a usable definition so some help will be required

**Comment by Dronek** [comment]
It's rather questionable if pilots should be going long range if they rely on a preset to set up their quad. Apart from that I agree with @DzikuVx . Presets should be based on a stable tune. If you have a stable tune then suggest it to be used as a preset.

**Comment by artempolikarpov** [comment]
[7inchGPSQuad.txt](https://github.com/iNavFlight/inav/files/1890389/7inchGPSQuad.txt)
Here is dump from 7inch gps quad. PIDs and filters could be taken from this dump

**Comment by DzikuVx** [comment]
ok, saved. When time will allow then. In a mean time, move to configurator project:

iNavFlight/inav-configurator#404

**Comment by DzikuVx** [comment]
Thannk @artempolikarpov
