### ISSUE TITLE
Switching from GCS_NAV to POSHOLD does not use current position

### ISSUE THREAD

**Issue by iforce2d** [iNavFlight/inav#300]
I have been playing around with the GCS_NAV mode to update the 'special waypoint' for a follow me functionality. I notice that when I switch off the GCS_NAV mode (returning to normal POSHOLD) the quad will keep moving to the 'special waypoint' location. I think it should instead set the current position as the desired position. One of the main reasons for having a distinct GCS_NAV mode was to avoid this behavior, because (to quote eziosoft) "The user may want to have PH ie in panic situation." #103

**Comment by digitalentity** [comment]
GCS_NAV isn't a flight mode, it's an indication that PH position may be updated from the ground. Nevertheless, described behavior is a bug.

**Comment by iforce2d** [comment]
Yes, I noticed that it's not part of the state machine. From an end user's point of view though, it looks and behaves just like a mode :)

**Comment by WaspFPV** [comment]
Maybe add poshold reset to gcs_nav when turning it off?
