### ISSUE TITLE
Feature request: flight mode: stabilised climb and descent 

### ISSUE THREAD

**Issue by craig34a** [iNavFlight/inav#3001]
It would be very handy to have a fixed climb or descent rate for cruise / stabilised flight or even position hold. 

This could be implemented as a setting within the inav app or even by way of a knob channel to change vertical speeds in flight. This feature would work best with an airspeed indicator to avoid a stall.

**Comment by shellixyz** [comment]
You should already be able to do this with the `NAV ALTHOLD` flight mode and a mix in your remote control if it can do it.

**Comment by craig34a** [comment]
That does not work. ALTHOLD is very solid and will not change altitude regardless of elevator or throttle unless you reduce the throttle to less than what's needed to maintain altitude.

**Comment by Dronek** [comment]
> That does not work. ALTHOLD is very solid and will not change altitude regardless of elevator...

You are actually wrong about this. Try pulling the elevator all the way back in ALTHOLD and the plane should be climbing. It will keep the new altitude whenever you let go off the elevator. If that doesn't work then something is off in your settings.

I suspect you're talking about fixed wing.

**Comment by craig34a** [comment]
Thank you. You are right. It does work in Alt Hold.
