### ISSUE TITLE
Feature Request: Camera angle with negative values

### ISSUE THREAD

**Issue by elitak** [iNavFlight/inav#3007]
I don't see the fpv camera angle variable anywhere in iNav 1.9.0. Have I missed it? Also, stock betaflight doesn't allow negative angles, but I think iNav should, as many nose-mounted cameras point downwards.

**Comment by shellixyz** [comment]
Camera angle ? For the servo tilt control ?

**Comment by elitak** [comment]
In my case, for the nose-mounted fpv camera. It points downwards about 10 degrees. In Betaflight, this offsets the artificial horizon.
