### ISSUE TITLE
OSD not working on KFC32F3_INAV because wrong clock for MAX7456

### ISSUE THREAD

**Issue by marbalon** [iNavFlight/inav#3012]
After version 1.8 there is a lot of refactoring and new layers for bus SPI and i2c. But one thing is missing - changing clock before writing to specific device. On this target clock for OSD need to be STANDARD and this is set during initialization, but later there is a MPU6000 initialization and this change clock to FAST and OSD is not working anymore.

So in my opinion we have two solutions:
- remember clock for every device when it is inited, maybe by extending busDevice_t structure and then change it before write/read to device. But I don't know if every SPI device have own structure...
- or remember slowest clock for specific device and never increase it, but IHMO firs solution is more elegant.

Any other suggestion how to fix this problem?

**Comment by digitalentity** [comment]
Yes, the first solution is more elegant. We need to look into it

**Comment by marbalon** [comment]
The temporary simple solution can be #define for specified target eg. MAX_SPI_SPEED.

**Comment by lgojniczek** [comment]
Is there any chance to include this in 2.0?

**Comment by fiam** [comment]
@lgojniczek If someone submits a fix affecting only this target, it can be included in next RC.

**Comment by shellixyz** [comment]
This could be related to the issue with the SDcard on other boards. For example the issue I have with the OmnibusF4PRO board. The SDcard and OSD chip are on the same SPI bus on this board.

**Comment by marbalon** [comment]
I will try t implement simple solution for now with MAX_SPI_SPEED for target - if defined for the board FC use it when to limit SPI speed.

**Comment by lgojniczek** [comment]
Sounds good, thank you

Pt., 6 lip 2018, 15:25 użytkownik marbalon <notifications@github.com>
napisał:

**Comment by fiam** [comment]
Fixed in #3532
