### ISSUE TITLE
Bad Altitude data in LTM Telemetry protocol

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#3024]
Today I have been testing iNav 1.9.0 and using LTM telemetry with my antenna tracker, and I have realized that the altitude is fixed to 48 meters, thus the tilt servo is always pointing the antenna to the horizont. With iNav version 1.8.0 everything seems to be ok.

Unfortunately I had no black box feature activated so it is not possible to demonstrate it. Tomorrow if weather conditions are ok I'll try again.

However I suspect that the issue could come from the latest changes on ltm.c file:

[https://github.com/iNavFlight/inav/commit/d5ba9c4eec2f531d2b84bce7be4530b3e71b039f#diff-16e1e70bcf42ac76edb2bc372b70ff67](https://github.com/iNavFlight/inav/commit/d5ba9c4eec2f531d2b84bce7be4530b3e71b039f#diff-16e1e70bcf42ac76edb2bc372b70ff67)

![altitud](https://user-images.githubusercontent.com/12935392/38527516-64568a02-3c5b-11e8-913a-ab3241ceab97.jpg)

And curioslly ascii code for 0 is 48 ...

Maybe I see ghosts in the dark! Tomorrow I'll try to check it again with blackbox feature active.

**Comment by stronnag** [comment]
On April 9, 2018 11:07:50 PM UTC, "Raúl Ortega" <notifications@github.com> wrote:
>Today I have been testing iNav 1.9.0 and using LTM telemetry with my
>antena tracker, and I have realized that the altitude is fixed to 48
>meters, thus the tilt servo is always pointing the antenna to the
>horizont. With iNav version 1.8.0 everything seems to be ok.
>
>Unfortunatelly I had no blackbox feature actived so it is not possible
>to demostrate it. Tomorrow it weather conditions are ok I'll try again.
>
>However I suspect that the issue could came from the latest changes on
>ltm.c file:
>
>[https://github.com/iNavFlight/inav/commit/d5ba9c4eec2f531d2b84bce7be4530b3e71b039f#diff-16e1e70bcf42ac76edb2bc372b70ff67](https://github.com/iNavFlight/inav/commit/d5ba9c4eec2f531d2b84bce7be4530b3e71b039f#diff-16e1e70bcf42ac76edb2bc372b70ff67)
>
>![altitud](https://user-images.githubusercontent.com/12935392/38527516-64568a02-3c5b-11e8-913a-ab3241ceab97.jpg)
>
>And curioslly ascii code for 0 is 48 ...
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNavFlight/inav/issues/3024

I use LTM multiple times a week on 1.9 without any problems, including correct display of altitude. The generic USE changes have had no effect on the data transmitted.

**Comment by raul-ortega** [comment]
It is not possible to fly today and getting sats indoor is quite dificult becous it is raining. However I'm checking several things. One of them is that 48 m is the altitude of the place where I was flying yesterday, so this altitude seems to be ok before launching the plane, which means that LTM is reporting well altitude at the begining. Thus the point is to figure out why the value is kept fix on the display of the antenna tracker during the flight, and this could be caused by the firmware of the antenna tracker. Therefor I close this issue.
