### ISSUE TITLE
Large font not saved on the OSD

### ISSUE THREAD

**Issue by knputyi** [iNavFlight/inav#3027]
Matek F405-OSD
Inav 1.9

### Uploading large font goes well, save button activated ,the board reboots but, same standard font is saved.
Using auto video format (not pal or ntsc), unit metric.
Thanks, Norbert K.
![inav1 9](https://user-images.githubusercontent.com/38250524/38557423-b200fa74-3cd5-11e8-99e2-57ff669cb49f.JPG)

**Comment by shellixyz** [comment]
Did you check in the video feed ? I don't think the configurator preview will reflect the font you uploaded to the FC because the it has no way of knowing which font is present in the OSD chip

**Comment by knputyi** [comment]
Thanks, my bad, did not checked in feed. Font was changing in the Configurator, behind the font manager during the upload, but came back standard after reboot. In feed it is ok, changed to large. Sorry :(
