### ISSUE TITLE
Add roll_yaw_cam_mix_degrees option from BF

### ISSUE THREAD

**Issue by artempolikarpov** [iNavFlight/inav#3028]
While using iNav in Acro mode found absence of roll_yaw_cam_mix_degrees option.

A lot of pilots from BF are using this option and it will be useful to have such option in iNav for smooth roll and yaw maneuvers.

There is a good explanation
https://www.youtube.com/watch?v=gXeaINFpvow&feature=youtu.be

**Comment by digitalentity** [comment]
Good point. This is only meaningful in ACRO though.

**Comment by digitalentity** [comment]
#3037 is a quick and dirty port of Betaflight's fpv camera angle compensation code. Feel free to test

**Comment by artempolikarpov** [comment]
Thanks!

**Comment by fiam** [comment]
Work is being done in #3037, will probably be in 2.0

**Comment by digitalentity** [comment]
Implemented
