### ISSUE TITLE
Bluetooth Module Not Working with CL_Racing F4 Air V2 Board

### ISSUE THREAD

**Issue by Zangetsu57** [iNavFlight/inav#3035]
I'm using a CL_Racing F4 Air V2 board with a bluetooth (BT) module connected to one of the UARTs.  I'm having issues connecting to the configurator via the BT module. The same BT module works fine with another omnibus board I have in another plane (also running iNav 1.9) so I know it is configured and binded correctly to my pc. I've verified that Tx is connected to Rx and vice-versa.  Additionally, I tried a separate BT module and am getting the same results.

**Comment by JyeSmith** [comment]
When hooked up to a uart that is not uart1 (this is for sbus on the Air) you need to switch on MSP in the Ports tab.

**Comment by Zangetsu57** [comment]
I did turn on MSP.

**Comment by Zangetsu57** [comment]
I ended up getting it to work.  Turned off MSP, saved, turned it back on, saved, and now it works.  Not sure why, but I'll take it!
