### ISSUE TITLE
INav 1.9 MatekF405 CTR CrossFire Failsafe not working 

### ISSUE THREAD

**Issue by jalao** [iNavFlight/inav#3044]
I am currently running Matek 405 CTR using Crossfire Micro. I configured my crossfire failsafe to Cut and FS Pos and tested failsafe in both modes. I entered INAV and set failsafe to RTH. regardless of which option i choose, the moment I switch off my transmitter, the motors cut. I have also logged into CLI and made sure my parameters are set to RTH. Is this an issue or is there a workaround. 

THanks

**Comment by digitalentity** [comment]
Go to CLI, execute dump command copy its output to PasteBin and provide a link to a paste here.
Upload a zipped blackbox log of your test (if available)

**Comment by jalao** [comment]
Thank you. 
I have two drones with the exact similar build. 

Drone 1: https://pastebin.com/FTZByBZq <https://pastebin.com/FTZByBZq>
Drone 2: https://pastebin.com/rAG5LjtG <https://pastebin.com/rAG5LjtG>

No Blackbox logs.

**Comment by jalao** [comment]
Hi. Just checking in to see if you guys have been able to into my data dump to see what’s wrong.

**Comment by jalao** [comment]
Hello.
Can you please provide an update. I lost a drone today because failsafe did not trigger RTH while using crossfire. Can you please, please help....

Thanks

**Comment by Redshifft** [comment]
If you can not get "no Pulse" to trigger FS
or FS POS to switch to FS Mode (selected in flight modes)
You have a non INAV problem and are not setting Crossfire correctly - you have to select FS position then press the enter on the CF RC to set current TX signals into failsafe memory. Then TEST It !!!

If above does not work, set TX to RTH, level mode and some throttle and lock the FS to that configuration. If this works, you did something dumb that is calling disarm over RTH.

**Comment by solmag** [comment]
Hello, I am having the same problem with my crossfire setup. I know that I set it up correctly on my Inav but can somebody please explain how to set it up on crossfire? Maybe I'm doing something wrong. FYI I have set it up on Frsky L9R and it works perfectly. But I'm finding it extremely difficult to make FS RTH work on crossfire. Each time I shut off my transmitter, the motors shut off after about 2 seconds. Any help will be appreciated. Thanks

**Comment by markandkymward** [comment]
One work around is if you have an available channel to broadcast RSSI on your transmitter and use this channel to trigger FAILSAFE and then RTH.  

Steps:
1. Configure LQ to output on your desired channel.  Do this by selecting MICRO or DIVERSITY (depending on the transmitter module) and then select OUTPUT MAP.  Set Dst Chan # to a free channel.
2. In INAV:
  a. Go to RECEIVER tab and set RSSI Channel to the channel you selected above.  Check that you are good by power cycling your transmitter.  You should see that channel drop from ~2000 to ~1000 on the channel you selected.
  b.  Go to the MODES tab and set the FAILSAFE mode to that same channel and put the range at ~900 to ~1300.  I'm not sure where 70% LQ lies on this spectrum but when you hit that LQ, you pretty much need to be turning back.  The 1300 is just a guess, the real number is probably higher than that.  This method will definitely handle a power loss on your transmitter though.  With the crazy range of the XF, this will likely be OK.  If you are planning any hardcore distance flying, you might want to experiment with this.
  c.  Go to the FAILSAFE tab and configure RTH as the default FAILSAFE mode.
  d.  Finally, go to the ADVANCED TUNING tab and configure your RTH details.

This method works well on both my XF diversity and my micro builds.

Hope this helps
