### ISSUE TITLE
NRF24 addition broken MSP_RX_CONFIG MSP message

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#305]
MSP_RX_CONFIG now have different format which messes up Configurator - see https://github.com/iNavFlight/inav-configurator/issues/22

**Comment by digitalentity** [comment]
Introduced by #283

**Comment by digitalentity** [comment]
@martinbudden We either need a new message (i.e. MSP_NRF24_CONFIG) or make changes to configurator to ensure it correctly processes MSP_RX_CONFIG and MSP_SET_RX_CONFIG for both INAV 1.1 and below and INAV 1.2 and above

**Comment by martinbudden** [comment]
We need to change the configurator anyway, to allow the user to select which NRF24 protocol to use (since several are currently supported, and I plan to add more). I'm not in favour of adding a new message, since this is certainly falls within the category of RX configuration.

**Comment by digitalentity** [comment]
@martinbudden then I suggest moving nrf24_protocol to the end of the message to minimize compatibility problems when using old configurator / CF Configurator. What do you think?

**Comment by martinbudden** [comment]
I'm happy with that. I put it where it is for alignment reasons, but I think compatibility reasons are more important.

**Comment by martinbudden** [comment]
Addressed in PR https://github.com/iNavFlight/inav/pull/309

Only briefly tested, so it would be good if someone else can confirm this works.

**Comment by digitalentity** [comment]
I can confirm that it works. Thanks!
