### ISSUE TITLE
BB is not logging to SD card [OMNIBUSF4PRO]

### ISSUE THREAD

**Issue by artempolikarpov** [iNavFlight/inav#3050]
I have INAV/OMNIBUSF4PRO 1.9.0 and set BB logging device - SD card.
But when I reject and browse SD card - there is no log

**Comment by digitalentity** [comment]
Try a different SD card. Not all SD cards work correctly in SPI mode

**Comment by artempolikarpov** [comment]
standard 16gb, fat32, no warning messages in configurator

**Comment by giacomo892** [comment]
Have you enabled logging from the configuration tab? Is the SDCARD recognized?

**Comment by artempolikarpov** [comment]
> Have you enabled logging from the configuration tab? Is the SDCARD recognized? 

Sure - BlackBox enabled as feature, SDCARD is recognized in BlackBox tab

**Comment by giacomo892** [comment]
Note that BB only works when copter is armed.

**Comment by artempolikarpov** [comment]
I know, I made few flights, sdcard is still empty

**Comment by DzikuVx** [comment]
Tested 1.9.1 on Omnibus F4 Pro v2 and all the logs were correctly recorded. So I assume hardware or configuration
