### ISSUE TITLE
Servo midpoints - only first input shows an effect

### ISSUE THREAD

**Issue by DerElch87** [iNavFlight/inav#3051]
Hi there,

When I try to set the midpoints in the Configurator, I can only set one value - then a restart is necessary.
It doesn't matter if this is done in "live mode" or normally and saved.

Only the first input value shows an affect.
Every further input shows no effect till a restart is done.

Board is a Omnibus F3
Issue occurs with INAV 1.9 and I also tested INAV 1.6

### diff

`CONFIGURATOR 1.9.2`

```
# diff

# version
# INAV/OMNIBUS 1.9.0 Mar  4 2018 / 23:17:26 (dc4ef594f)

# resources

# mixer
mixer AIRPLANE

# servo mix

# servo

# feature
feature -CURRENT_METER
feature TELEMETRY
feature PWM_OUTPUT_ENABLE

# beeper

# map

# name

# serial
serial 0 0 115200 38400 0 115200
serial 2 64 115200 38400 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# master
set acc_hardware = MPU6000
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = SERIAL
set serialrx_provider = SBUS
set motor_pwm_rate = 50

# profile
profile 1


# 
```

`
Packet error: 4 I2C error: 0 Cycle Time: 2002 CPU Load: 3% MSP version: 2 MSP load: 0.0 MSP round trip: 71 HW round trip: 51 Drop ratio: 0% 1.9.2`

**Comment by DerElch87** [comment]
Same effect on an CC3D with 1.7.1 working.
Additionally something else is going strange.
When I boot up, the servos react directly on a movement of the FC.

The CC3D has two LEDs, one yellow and one blue one.
Yellow is solid and Blue blinks.
As soon as I click on save I will see in the Configurator log the message

> EEPROM saved

And from this moment on, the blue LED disappears and the same like for the Omnibus.
No reaction anymore for the servos.
The midpoint change is without effect and also the reaction on the FC for movements is completely missing.

**Comment by shellixyz** [comment]
> Only the first input value shows an affect.
> Every further input shows no effect till a restart is done.

This is an issue with configurator 1.9. It will work fine if you are using 1.8. It has already been fixed for the next release.

> When I boot up, the servos react directly on a movement of the FC.

This is probably because your board is in failsafe. And the failsafe method is set to LAND (SET-THR)

**Comment by DerElch87** [comment]
Thanks @shellixyz 
Configurator 1.9.3 doesn't show that issue anymore.

Best regards
