### ISSUE TITLE
Servo Autotrim mode prevents arming

### ISSUE THREAD

**Issue by teknoflyer** [iNavFlight/inav#3053]
i have not seen any documentation saying that autotrim on would be a "navigation not safe" item. i agree that it should lockout the arming function and came across this interaction while try to create a switch setting that would store the values set by autotrim when i land and disarm. i have a taranis D4R PPM receiver and omnibus F4 pro clone FC.   The problem is that with only 8 channels some channels have to do multiple jobs. my 3 position arming switch does - arming , store autotrim and turn off autotrim.  the arm range is 1750 to 2000us and the servo autotrim is active from 1600 to 1900. when i move the switch from middle 1500us to arm at 2000us i found its not an instanous change and autotrim is turned on for 1 to 2 PPM frames. this is just long enough for autotrim to block arming.
 i would like to see autotrim have a 100ms timer that checks the input to see if autotrim is still selected 100ms after it was first detected but before it actually turns that mode ON or OFF.

**Comment by giacomo892** [comment]
AUTOTRIM is meant to be used while flying in level without external turbulence to trim all control surfaces, that's why it prevents arming. To save AUTOTRIM values you just need to land with AUTOTRIM enabled and just disarm the plane then you can disable it.

**Comment by teknoflyer** [comment]
The autotrim function works great and as expected. the problem is related to when using a single channel to do multiple functions which might require autotrim to be active in between two other active switch positions. as you jump from one switch setting to another, autotrim could be turned on or off for a brief time and therefore reset or start a new adjustment. if it had a signal stability check of 100 ms to verify that you wanted it on or off,  the problem would be eliminated. this would require a software change to the FC routine for autotrim.  my actual use is to go from a motor not armed 1500us to an armed 2000us position. then by using mixes and logical switches to arm autotrim by falling back into a range that turns on autotrim but leaves the motor still armed. then when i land i go back to the middle position which now sets it to 1675 instead of 1500 and disarms the motor and stores autotrim. then when the switch is set to 1000us it turns off autotrim so the the settings will stay stored and resets the switch back to an arm only function. its that first jump from 1500 to 2000, that due to the nature of my receiver causes a momentary in between value that turns on autotrim on its way to the motor armed position. i have actually seen the autotrim indicator in the configurator blink on while switching back and forth from 1500 to 2000us.
