### ISSUE TITLE
Feature Request: CLRacing F4S

### ISSUE THREAD

**Issue by bokie1** [iNavFlight/inav#3061]
Hello All!
Is it possible to add CLRacing F4S on one of the targets?
Thanks.

**Comment by BorgQuads** [comment]
Bump for CLF4s HEX

**Comment by JyeSmith** [comment]
Another request from me 😊

**Comment by teells** [comment]
Yes please.

**Comment by dd-rx** [comment]
pretty please ;)

**Comment by bokie1** [comment]
Still no love for this board?

**Comment by tenten8401** [comment]
Have one of these laying around doing nothing, would love to use it with iNav..
Betaflight has a target so I don't imagine it'd be too hard to port over, but I'm not familiar with the process.
