### ISSUE TITLE
PIDs are reset to defaults after PID profile change via OSD

### ISSUE THREAD

**Issue by artempolikarpov** [iNavFlight/inav#3064]
**Prerequisites:**
iNav 1.9.0
FC with OSD like OMNIBUSF4PRO
PID profile 1 is selected, pids are differ from default

**Steps:**

1. Open OSD menu with sticks combination
2. Change PID profile to 2 and Save & Exit
3. Open OSD menu with sticks combination
4. Change PID profile to 1 and Save & Exit

**Actual result:**
PID values are reset to default

**Comment by shellixyz** [comment]
~Confirmed. I can reproduce on 1.9.0. Selecting a profile with a TX stick command also resets the PIDs.~

UPDATE: Sorry my error can't reproduce

**Comment by digitalentity** [comment]
@artempolikarpov I can't reproduce the issue on exact same setup. Can you please record a video (DVR recording to show OSD activity) to demonstrate the issue?

**Comment by artempolikarpov** [comment]
I think I found the source of issue. But I'm not sure is it a bug or "as designed"

When you change PID profile and then open PIDs for edit - PIDs are displayed from previous PID profile - this could be the issue.

If you change PID profile and Save and Exit - pids will be changed after this action.
BUT if you change PID profile and then open PIDs and edit them, then Save and Exit action - your edited pids from previous pid profile will present.

https://drive.google.com/file/d/1rP51WvFcBQ6DrtMyoEeJFZb0lvAwswg-/view?usp=sharing
