### ISSUE TITLE
Feature Request: Summary Screen Fix 1.8

### ISSUE THREAD

**Issue by JDFPV** [iNavFlight/inav#3068]
Ok.. you guys sent me the summary screen fix on a 1.9 hex file which works great. But im having rth issuses on my plane and so is others using 1.9 and there is no resolve for it yet. My request is that a summary screen fix for 1.8 firmware please. I had no issuse at all using 1.8. Please help.

**Comment by DzikuVx** [comment]
Hi, 

We will not release a hotfix for 1.8. You have to wait for 2.0 or try 1.9.1
