### ISSUE TITLE
SBUS and S.Port Telemetry problems when updating from 1.9.0 to 1.9.1 on SPRacing F3 EVO

### ISSUE THREAD

**Issue by MRC3742** [iNavFlight/inav#3069]
Using a working system running 1.9.0 and then updating to the current compiled 1.9.1 version, SBUS and S.Port Telem stop working.

After trying different configurations I must make the following changes in the CLI to repair this.

To get SBUS working I have to "set serialrx_inverted = OFF"  (it was ON in 1.9.0)

To get S.Port working I need to "set telemetry_inversion = OFF"  (it was ON in 1.9.0)
and I also need to"set telemetry_halfduplex = ON"  (although I believe this is a new setting defaulted to ON it was OFF when converted from 1.9.0)

I don't know if these are problems or just needs to be included in the release notes for 1.9.1?

Taranis X9D+ (running 2.2.1)
SPRacing F3 EVO 
X4R-SB  (firmware non_EU_170322 - stock with no inversion hacks)

**Comment by digitalentity** [comment]
We've discussed this and we will replace `telemetry_inversion` with `telemetry_inverted` for 1.9.1. The new parameter will flip the default protocol inversion, so telemetry_inverted = OFF will work for all protocols. telemetry_inverted = ON will invert the default protocol inversion (i.e. will  make non-inverted S.Port or inverted MAVLink) - suitable for custom or hacked receivers.
