### ISSUE TITLE
Add Target MATEKF411

### ISSUE THREAD

**Issue by MATEKSYS** [iNavFlight/inav#3075]
[MATEKF411.zip](https://github.com/iNavFlight/inav/files/1959612/MATEKF411.zip)

Tested it on F411-mini
http://www.mateksys.com/?portfolio=f411-mini#tab-id-7

Thanks

**Comment by digitalentity** [comment]
We'll merge it to 2.0, thanks @MATEKSYS

**Comment by fiam** [comment]
Fixed in #3146
