### ISSUE TITLE
F4 v3 Bus Connections for Servos

### ISSUE THREAD

**Issue by Christianmix** [iNavFlight/inav#3086]
I do not know if the title is correct, but I'll doubt it ....
I have always respected the image that appears in the settings regarding the servos connection, left aleron on FC channel 5 and right aleron on FC channel 4, could I use a Y cable and connect the two on FC channel 4?

**Comment by DzikuVx** [comment]
yes but then autotrim function would not work very well. Bu besides that yes, you can do it
