### ISSUE TITLE
Matek F405 CTR

### ISSUE THREAD

**Issue by Revenger72** [iNavFlight/inav#3092]
Hey.
When will support Matek CTR?

**Comment by Lord-Quake** [comment]
It is supported. Use the file "inav_1.9.1_MATEKF405" for the CTR.

**Comment by Revenger72** [comment]
Thanks for the answer. I'll try. I hope it will not be worse than from the site of MATEK.

**Comment by Lord-Quake** [comment]
I'm using it and haven't found any incompatibilities so far. Let the devs know if you do have any.

**Comment by sin5678** [comment]
so close this issue now ..
