### ISSUE TITLE
NAZA GPS on a Quad with INAV

### ISSUE THREAD

**Issue by Christianmix** [iNavFlight/inav#3093]
Before starting, I want to make it clear that I looked at this link as the link, but it only explains how to do the configuration in inav.
https://github.com/iNavFlight/inav/wiki/GPS--and-Compass-setup

Does anyone have any idea how the compass works on naza gps if it has no connection to the controller? Look at the photo, you only have vcc, ground, tx and rx connection. How do I operate the compass? Does anyone know how it works? I will use an omnibus f4 v3, in a frame tbs discovery.

http://www.landelfm.com.br/uploads/fotos/6304666e0085f41dee757bacac7d5170.jpg

**Comment by stronnag** [comment]
Compass data is part of the NAZA GPS serial protocol. Just connect up the RX/TX and set the compass (`mag_hardware`) to `GPSMAG`.

And then kindly close this support issue.

**Comment by Christianmix** [comment]
Ok, so I solve the connection, but I wanted to understand, let's get my question: Does he have an internal magnetometer / compass and sends the information through the same gps channel or only uses GPS-like addressing and fixed wings?

**Comment by sin5678** [comment]
NAZA GPS Combine compass information and GPS information and send them at same time
