### ISSUE TITLE
FRSKYF3 target

### ISSUE THREAD

**Issue by twistedwings** [iNavFlight/inav#3095]
I can see the target in inav/src/main/target/FRSKYF3
but not in https://github.com/iNavFlight/inav/releases.

**Comment by stronnag** [comment]
No every target gets built for a release, particularly if it is not well supported or tested.

**Comment by stronnag** [comment]
There's 1.9.1 'master' hex at http://seyrsnys.myzen.co.uk/inav_dev/ if you wish to try it. Please report back if it works (or not).

**Comment by twistedwings** [comment]
I will give it a try, thanks

**Comment by twistedwings** [comment]
seems to work so far.
I haven't tested UART1.

**Comment by DzikuVx** [comment]
it is currently released, closing
