### ISSUE TITLE
Missing used timer def in OMNIBUS target

### ISSUE THREAD

**Issue by flybabo** [iNavFlight/inav#3096]
While reviewing the code, I found out that TIM_N(8) is missing at USED_TIMERS defined in OMNIBUS/target.h.
Apparently, TIM8 is used in timerHardware[] @target.c.

**Comment by flybabo** [comment]
I also found out that I2C3_SDA pin is incorrectly defined at drivers/bus_i2c_hal.c.
It must be PC9 not PB4.

**Comment by digitalentity** [comment]
@flybabo good catch. Can you submit a PR to fix it?

**Comment by fiam** [comment]
This is no longer relevant. Since #3120, the targets don't need to list the used timers.
