### ISSUE TITLE
MATEK - F405 CTR - Barometer fails to initialise

### ISSUE THREAD

**Issue by joolskii** [iNavFlight/inav#3101]
After updating from 1.9.0 -> 1.9.1 the Configuration UI indicates that there was a failure to discover/initialise the BMP280 

### Board and Version
MATEK F405-CTR - Genuine 
1.9.1

### Behavior
* UI show an error for the Barometer (BMP280) 
* Install 1.9.1 on a MATEK F405-CTR (and use the latest GUI) check Barometer icon at the top
* As in 1.9.0, the barometer should be discovered and initialised
* The Barometer is not found.

I suspect this is a regression from the F7 Matek fixes, happy to perform more testing/building custom versions.

**Comment by digitalentity** [comment]
Works for me:

**Comment by digitalentity** [comment]
Works for me:
```
# version
# INAV/MATEKF405 1.9.1 Apr 21 2018 / 13:25:29 (03a5c1922)

# status
System Uptime: 26 seconds
Current Time: 0000-01-01T00:00:00.000+00:00
Voltage: 0.2V (1S battery - NOT PRESENT)
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
SD card: Startup failed
Stack size: 6144, Stack address: 0x10010000, Heap available: 1024
I2C Errors: 0, config size: 3516, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 1, cycle time: 1003, PID rate: 997, RX rate: 49, System rate: 9
Arming disabled flags: ACC HWFAIL RX THR CLI
```

Please post more details about the issue - at least CLI dump/diff. Also try flashing with full erase and reconfigure.

**Comment by joolskii** [comment]
Thanks for the update, I'll post up more details later today. Did you perform your install with full erase ?

**Comment by digitalentity** [comment]
@joolskii yes, that's from flashing 1.9.1 MATEK405 target on MatekF405-CTR board with full erase.

**Comment by joolskii** [comment]
# version
# INAV/MATEKF405 1.9.1 Apr 21 2018 / 13:25:29 (03a5c1922)

# status
System Uptime: 74 seconds
Current Time: 0000-01-01T00:00:00.000+00:00
Voltage: 0.0V (1S battery - NOT PRESENT)
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
SD card: Startup failed
Stack size: 6144, Stack address: 0x10010000, Heap available: 1024
I2C Errors: 0, config size: 3516, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 1, cycle time: 1004, PID rate: 996, RX rate: 49, System rate: 9
Arming disabled flags: ACC HWFAIL RX THR CLI

Flashing with full erase resolves the issue, please close issue. 

Thanks for your help.
