### ISSUE TITLE
No PWM in servo output for AnyFC F7 with external baro in 1.9.x

### ISSUE THREAD

**Issue by lo4wai** [iNavFlight/inav#3102]
### Board and Version
ANYFCF7_EXTERNAL_BARO
1.9.x

### Behavior
I'm using the tricoper mixer with tilt servo connected to input 3 as indicated in
https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20AnyFC%20F7.md

The servo does not work in version 1.9.x.  There is no pulse when I connect a oscilloscope to the pin.
However when I downgrade to version 1.8.0, PWM signal is observed and the servo work normally.

**Comment by ryanort** [comment]
Same issue still persists on 2.0 and 2.1.0-RC1 (AnyFCF7)
