### ISSUE TITLE
Rover support

### ISSUE THREAD

**Issue by eephyne** [iNavFlight/inav#3114]
I know there is another issue on the subject but considering the case, I thought it was more useful to open a new one, don't hesitate to close/merge/whatever, if you think not.

I'm currently trying to configure INAV on a rover.
There are a lot of workaround. Some of them was really easy to make and others are dirty.

I opened this issue, to help with the rover support on inav, I have the car to test if you want.

Its a 1/10th (more close of the 1/8),
I have two fpv camera on it (front with yaw gimbal and back) (i use the osd) with 1.2 ghz VTX.
the rc link is done with the FrSky L9R.
the FC is an omnibus f3.
I have a GPS ublox on it (with magnetometer plugged in the fc too).

For now what I needed to do:
For throttle, I need to use 3D mode (reverse esc).
I used mixer customairplane with custom firmware (I just modified the first four output to what I need: 1-3:servos,4:motor)
The 3D mode give me another issue, when I go backward, the steering servo (mixer stabilized Yaw) is reversed. Its a normal behavior for 3D quad but of course not for rc car.
The workaround I did for this one is dirty but in the meantime its working: I autoset the manual mode when I go back. (using the logical switch on the taranis).

I think that all I done right now

I do not really tuned the pid right now, in fact, the car is still on the bench.

In case you asking yourself : why ?
I want to wander around with an fpv car. with this idea in head, I needed gps and osd, wanted also steering gyro stab.
In the end, using an FC seems way more friendly that a minimosd and a gyro.

I'm willing to help.
(I'm also kind of busy, so if I can't test things right away, don't take it wrong)

I know that rover is not a priority, and almost anything that need customization, need a rover mode (like 3d mode that is not adapted to rover). I bet this is not a small piece of code to write, this is why I'm not directly asking for anything here.I'm juste saying "hello, I'm also want rover mode, and I have a rover to test when you have the time and energy to add this functionality).

**Comment by baomin** [comment]
Rover good
