### ISSUE TITLE
Board - Omnibus F4.md -  omnibusf4pro.png has wrong alignment of pwm1-4 on bottom view

### ISSUE THREAD

**Issue by vavisimo** [iNavFlight/inav#3115]
just the PWMs should be reordered
original:
<img width="967" alt="omnibusf4pro" src="https://user-images.githubusercontent.com/32098018/39204480-2fd03938-47f8-11e8-9af1-243e8cc0ad57.png">
new:
<img width="967" alt="omnibusf4pronew" src="https://user-images.githubusercontent.com/32098018/39204662-b913699a-47f8-11e8-88e6-53185c532a43.png">

please edit

**Comment by DzikuVx** [comment]
@skaman82 ?

**Comment by teckel12** [comment]
Fixed in #3161

**Comment by digitalentity** [comment]
Fixed.
