### ISSUE TITLE
Why msp_baudrateIndex isn't always 115200?

### ISSUE THREAD

**Issue by pmarkiewicz** [iNavFlight/inav#3127]
On two targets msp_baudrateIndex is set to 57600, why is this?

**Comment by DzikuVx** [comment]
Good question that probably will never get a answer...

**Comment by fiam** [comment]
@pmarkiewicz I think the designers of those boards intend those UARTs to be used for bluetooth bridges, that's why they set those values by default. But you'd need to ask them for a definitive answer :-)

**Comment by DzikuVx** [comment]
@fiam personally I kind of doubt.

**Comment by fiam** [comment]
@DzikuVx I'm positive about the F35, this is from their manual:

<img width="1468" alt="screen shot 2018-04-27 at 14 35 36" src="https://user-images.githubusercontent.com/41529/39365171-519c8080-4a28-11e8-9ab7-852af65fc74b.png">

As for the other one, MATEKF405SE, I guess we could ask Sampson.
