### ISSUE TITLE
feature request: Blackbox log timestamp

### ISSUE THREAD

**Issue by jelinj8** [iNavFlight/inav#3130]
Would it be possible to save a date/time in a blackbox log? (not to every record, but timestamp the log beginning).
It would be extremely helpful in identifying the log and pairing it with a video recording (in my case for processing in DashWare)
I know that the MCU in flight controllers doesn't have means to track daytime, but we have a GPS. As we have a GPS fix as a condition for arming, we should also be able to get a valid date/time from the GPS.

**Comment by stronnag** [comment]
This has existed for a while now (since iNav 1.8) , e.g.:
```
H Log start datetime:2018-04-23T14:53:40.668+00:00
```

**Comment by jelinj8** [comment]
OK, sorry for that, I haven't noticed that. I am trying to get this from blackbox-log-viewer and blackbox-tools. I'll try to fix that in blackbox-tools and close this one. Thanks.
