### ISSUE TITLE
Pin assignment duplicated

### ISSUE THREAD

**Issue by M3one** [iNavFlight/inav#3133]
In file `inav/src/main/target/OMNIBUSF4/target.h` pin `PA15` is assigned twice:
```
   #define SPI3_NSS_PIN          PA15
   #define MAX7456_CS_PIN          PA15
```
my guess is that `MAX7456_CS_PIN` shall be `PC15`

**Comment by shellixyz** [comment]
This is right SPI3 NSS pin is PA15 and the MAX7456 CS pin is connected to SPI3
