### ISSUE TITLE
flashing inav using eclipse

### ISSUE THREAD

**Issue by amitmanish** [iNavFlight/inav#3136]
I am learning inav codebase and wanted quick modification and flashing capability. I can build inav using eclipse but could not find any guide regarding flashing using eclipse. Is it possible to add plugins to eclipse for flashing inav. I have naze32 board and i was wondering if its possible.

**Comment by DzikuVx** [comment]
I'm affraid noone is using Eclipse over here. AFAIK most devs are using VS Code

**Comment by bansawelite** [comment]
@amitmanish you can both build and debug/flash your code in Eclipse. I have personally used the Segger J-link debugger with Eclipse for live debugging. This however requires that the SWDIO, SWCLK +5v and GND pins are available on the board (You may need to solder wires to get to these pins). This depends on your debug board and protocol of course). Notice the GDB Segger J-link option in eclipse debugging. It will work if you have those four pins connected) and you link to the gdb debugger executable after installing the Segger software.
On the reverse/back of the Naze32rev 6 board there is a 10 pin cortex debug connector. This would allow debugging too as it contains those four pins.

![Naze32 debugging](https://user-images.githubusercontent.com/39121856/39981251-22f937be-5793-11e8-93d2-3d35568ec3d5.png)
![Cortex debug pinout](https://user-images.githubusercontent.com/39121856/39981263-2eeca89e-5793-11e8-9460-215ee846b12d.png)

The Cleanflight team have an article on debugging [here](https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Eclipse.md).
It's a its a bit outdated but still useful. If you can get the build for inav/Cleanflight/betaflight in Eclipse working you've already done 95% of the hard work! The last 5% should be easy for you to setup hardware debugging( I know I had issues with the ARM and build tool path spaces in Windows). I had to install these tools without any spaces.

**Comment by amitmanish** [comment]
Hello guys,
Sorry for not being available. Well i wanted to flash firmware using usb as the inav configurator does. I see that there are firmware uploader files  which uses usart to communicate to bootloader for flashing the firmware. Is it possible to use them.

**Comment by stronnag** [comment]
example using st32flash or dfu-util as appropriate https://github.com/stronnag/mwptools/blob/master/samples/flash.sh Adapt as needed.
