### ISSUE TITLE
Board alligement issue

### ISSUE THREAD

**Issue by sniperxnl** [iNavFlight/inav#3137]
Hai guys

I have a F35 and i have him 270 degree on yaw.
When i do the 6 step calibration and i am on step3, it makes step6 light up, how is this possible, i have changed the yaw alligment

![image](https://user-images.githubusercontent.com/16321561/39409093-47b657ac-4be1-11e8-9922-7b414dbf8f54.png)

**Comment by artusmuc** [comment]
Yes - thats the same for me - you have to calibrate with "original" direction of the FlightController ..

**Comment by artempolikarpov** [comment]
Same for me...

**Comment by sniperxnl** [comment]
that is weird right?

**Comment by artusmuc** [comment]
If your are calibrating a Chinese Clone SPRACING F4 clone without a fight direction arrow - you have to guess some minutes how to calibrate :)

**Comment by sniperxnl** [comment]
@artusmuc

This is not a clone, and there is a mark what the front side it

**Comment by giacomo892** [comment]
Nothing weird here. Board alignment has nothing to do with accelerator calibration. You just need to calibrate towards sky and towards ground then do vertical calibrations in any order you want.

**Comment by artempolikarpov** [comment]
> Nothing weird here. Board alignment has nothing to do with accelerator calibration. You just need to calibrate towards sky and towards ground then do vertical calibrations in any order you want.

But in 1.9.0 calibration was totally ok, whatever direction of FC was

**Comment by stronnag** [comment]
> But in 1.9.0 calibration was totally ok, whatever direction of FC was

AFAIK, this was introduced by the new calibration screen in the configurator. So you now need to calibrate in strict order in the 'natural' geometry of the hardware (not the aircraft).

**Comment by artusmuc** [comment]
This is exactly what i what i want to say stronnag - you have to calibrate as the FlightController is marked - and snipernxl - this was an example that i have the same wrong thinking - independent which board this is. I only want to say that this kind of calbration can be a little difficult when you have mount your FC not in "natural" geometry for example have mounted your FC with -45° 
Stronnag is the it important for calibration to follow the steps 1 to 6 - or can you jump from 2 to 5 and then 3 and 4 ?

**Comment by digitalentity** [comment]
Calibration is always done relative to the flight controller (actually relative to the sensor itself).

**Comment by kamik2** [comment]
might this information should be visible in the configurator - calibration tab.

**Comment by rcabuser** [comment]
I Have the same "problem", and i cannot understand how this will be correct when the position you hold the plane in does not correspond with the results in Inav?????

**Comment by digitalentity** [comment]
@rcabuser et al please read the manual https://github.com/iNavFlight/inav/wiki/Sensor-calibration

> You may find this easier to do more accurately prior to installing the flight controller in your model and this procedure MUST be done referenced to the marked orientation on the board.

@kamik2 please open an issue for this suggection in Configurator issue tracker.

**Comment by rcabuser** [comment]
@digitalentity the model i have it installed in is so small that it's no problem to do the calibration. But i guess i'm just thickheaded when it comes to understanding this, that i should calibrate by the way the direction arrow on the board is pointing??
Inav ask you in point 3 to hold the model on it's side with the right wing down, my board arrow is of course pointing down like i have the plane nose down. If i fly the plane and banking hard to the right and it goes into failsafe, wouldn't the Inav think i'm nosed down then and do corrections according to that??
@sniperxnl have you flown that thing yet?

**Comment by DzikuVx** [comment]
Calibration steps order does not matter besides first one. All the other can be done in any order.
