### ISSUE TITLE
serial receiver cannot be configured on FRSKYF3 

### ISSUE THREAD

**Issue by twistedwings** [iNavFlight/inav#3138]
serial receiver sbus cannot be set via gui.

set receiver_type = SERIAL
set serialrx_provider = SBUS

in CLI works.

**Comment by shellixyz** [comment]
What version of the configurator and firmware are you using ?

**Comment by twistedwings** [comment]
configurator 1.9.3, fw 1.9.1.

**Comment by shellixyz** [comment]
I can't reproduce the issue
