### ISSUE TITLE
OSD Display Altitude with 1 decimal above 10 meters

### ISSUE THREAD

**Issue by artusmuc** [iNavFlight/inav#3141]
### Behavior
Altitude is protocolled in blackbox with a decimal and with telemetry you can have 2 decimals but OSD don't display. 

I think with Betaflight this is possible

_Is this a new feature request?_.  YES

It's a very very "nice to have" for me with playing smaller quads, it this is easy to realize. Under 5 meters it could be relevant if you are at 2,5 meter or at 2 meters.

**Comment by fiam** [comment]
We could add this as an option similar to the digits in the battery voltage
