### ISSUE TITLE
Feature request - distance based RTH altitude

### ISSUE THREAD

**Issue by povlhp** [iNavFlight/inav#3145]
I have a feature suggestion,

Distance based RTH altitude. 

To make it easy to handle, I would suggest:
- Set a minimum RTH altitude, used for any RTH within 100 meters
- Set a distance RTH altitude, used for RTH @ 1000 meters and beyond

I suggested 2x fixed distances to save variable space.

When the plane enters RTH @ 1500 meters, it will go to "distance RTH alt", and fly home.
@ the 1000m mark, it will follow a slope towards the minimum RTH altitide @ home position.

If RTH is entered anywhere between 100 and 1000 meters, it will aim for the slope or climb/descend towards it at max vertical angle.

When I fly nearby / LoS, I want the RTH to be say 30 meters, no reason for 100 meters. But when I fly FPV, I get further away, and it is a problem if RTH goes down to 30m, as I will lose video for a VERY LONG time.

Now I have RTH set at 60 meters, which is really too much nearby, and too low far away. Not from an obstruction point of view, but more related to the time it takes before I get control again.

I fly 1.5km from a glider plane field, but 35m lower than their runway. So having a too high RTH is also too risky for me. And I have a 100m ceiling.

**Comment by fiam** [comment]
@povlhp Doesn't setting the RTH altitude to "At Least" satisfy your use case? It will make the aircraft come back either at the current altitude or the configured RTH altitude, whatever is higher.

**Comment by povlhp** [comment]
The "At Least" would have to be 100m if I sometimes fly far away. (Max allowable altitude)
But if I am close to my own position (LoS), then 100m is complete overkill. 
To get a good radio signal (both video and control), you need higher altitude the further away you are.

Using the calculator, http://www.ringbell.co.uk/info/hdist.htm I should have LoS @ 2.5km from as little as 0.5m altitude. But this is not true for radio signals (Freshnel etc).

I love launching and then park using RTH, while putting on goggles. But of course I could sd a Poshold+althold mode for that. I have that, but not all have switches for 6 flight modes.
