### ISSUE TITLE
Bug in inav_1.9.1_KAKUTEF4V2 VBAT

### ISSUE THREAD

**Issue by Alexamig** [iNavFlight/inav#3148]
There was a bug in inav_1.9.1_KAKUTEF4V2 !!! If you turn on the LEDSTRIP, the battery monitoring stops working, the battery is discharged into a deep drawdown and there is no sound notification !!!

**Comment by mduthilleul** [comment]
Got the same problem here on a Kakute F4 V2 AIO with iNav 1.9.1
Voltage is set correctly at startup / reboot but then never change.

Note: In my case, no led strip is connected

**Comment by PTaki** [comment]
I have same problem. The voltage and current monitoring not working when LED configured.
Kakute F4 V2 AIO with iNav 1.9.1

**Comment by holoduke** [comment]
Here same issue with normal Kakute f4 V2 (non AIO)
Also with ledstrip off no voltage and current monitoring.
