### ISSUE TITLE
Bug - Servo mixer : Control wrong when add new mixer at Servo Tab 

### ISSUE THREAD

**Issue by binleo** [iNavFlight/inav#3152]
Please check out this video to see the issue.
[https://www.youtube.com/watch?v=1C7QSZ4eWBo&feature=youtu.be](url)
almost is OK when i using servo mixer, but when i add a new ruler to use RC Channel.
If i select it is RC channel 5 or 6 7 8, FC will controll wrong.

**Comment by DzikuVx** [comment]
By adding a new servo with number lower than before servo outputs have been shifted. Plus, servo number does not correspond directly with output numbering. 

For 2.0 there will be new servo interface
