### ISSUE TITLE
Accelerometer Calibrationproblem on F3 10DOF

### ISSUE THREAD

**Issue by jonastogo** [iNavFlight/inav#3155]
I installed iNav on my F3 Deluxe yesterday and wanted to calibrate the accelerometer.
iNav is on version 1.9.1.
If I now go through the 6-point method according to the instructions, the calibration does not work.
In step 1 nothing happens after calibration, which means there is no check mark in step 1.
If I do step 2, step 5 is completed.
For all other steps, it is a matter of luck whether anything at all is set to complete.
But if it's never the right thing.
No settings have been changed, i.e. the software is set to factory settings.
Calibration worked perfectly with Cleanflight.
With version 1.9.0 I have the same problem.

Does anyone have an idea and can you help me?

**Comment by artusmuc** [comment]
Yes - since 1.9 you see the result of the calibration and you have to calibration like the Flightcontroller is "natural" marked. There is a normally a white arrow on every FC. This is your natural calibration and this result is shown in calibration tab.

**Comment by jonastogo** [comment]
I did that.

**Comment by jonastogo** [comment]
Okay, I'll try to describe what I did.
For step 1 I laid the Fightcontroller flat on the ground.
The arrow was on the top and pointed away from me.
Then I clicked "Calibrate Accelerometer".
After the calibration was completed, step 1 was not marked as completed.
For step 2 I put the flightcontroller flat on the ground, but with the arrow at the bottom. The arrow continues to point away from me.
After calibration, step 5 was marked as connected and not step 2.
For the remaining steps I put the FC on the edge. The underside then pointed to me.
Nothing happened at any step but step five.
In step 5, step 6 was completed.

I really don't know what I'm doing wrong.

**Comment by jonastogo** [comment]
In the sensor tab, I see the values from all the sensors going crazy.
I compared the values of the sensors on iNav and Cleanflight at the same position of the controller.
iNav Accelerometer:
X: -0.17 , Y: -1.08 , Z: 0.80
Cleanflight Accelerometer:
X: 0.00 , Y: 0.00 , Z: 0.80

iNav Magnetometer:
X: 0.39 , Y:-0.05 , Z: 0.44
Cleanflight Magnetometer
X: 0.40 , Y:0.00 , Z: 0.00

iNav Barometer
Alt: ~-6.5 , Baro: -0.3 - -0.8
Cleanflight Barometer:
Alt: ~-0.4

The sensor data of Cleanflight look relatively precise to me, in contrast to iNav.
So, it looks like iNav can't read the sensors properly.

**Comment by artusmuc** [comment]
Sorry - i don't read your issue word by word :) 

Only an idea - have you made a "full erase" by flashing ?

**Comment by jonastogo** [comment]
No Problem :)
Yes i did a full erase. Is that wrong?

**Comment by jonastogo** [comment]
I've tried multiple version of inav and inav configurator now.
It is not working at all.
The Accelerometer can not be calibrated.
When the Controller is flat, the simulated copter is in an angled position.
The barometer give me crazy results aswell.
Sometimes the Altitude is increasing or decreasing slowly when i dont move the flightcontroller (and no wind), sometimes the altitude value stays at one level.

With Cleanflight everything is working fine, but there is obviously no GPS.

**Comment by artusmuc** [comment]
do you try betaflight ?
no full erase solve sometimes problems:)

**Comment by artusmuc** [comment]
only to exclude a hardware problem

**Comment by jonastogo** [comment]
Betaflight is working fine aswell :)
no full erase does not work.

**Comment by jonastogo** [comment]
I have no ideas any more.

**Comment by digitalentity** [comment]
What board is this exactly and which firmware are you using?

Make sure you use latest Configurator available here: https://github.com/iNavFlight/inav-configurator/releases/tag/1.9.3

First step needs to be in the position that lights up the first checkmark. Betaflight/Cleanflight can't be used as a reference since they don't really calibrate the sensor chip itself.

**Comment by jonastogo** [comment]
I'm using a SP Racing F3 Deluxe
MPU6050 accelerometer/gyro
MS5611 barometer (Deluxe only)
HMC5883 compass (Deluxe only)

I'm using the Configurator Version 1.9.3 with iNav 1.9.1

So when i hold the Controller to check the UAV test, the controller is heavily angled.
When i calibrate, should i hold the controller heavily angled aswell?

**Comment by jonastogo** [comment]
So, i tested little bit more.
It is impossible for me to mark the first step. I tried it like 40-50 times, always in the right order.
In Setup, the simulated Copter is moving constantly with around 0.1 roll per 3 sec und -0.1 pitch per 3 sec.  

What i saw aswell, is that the Barometer sensor is going crazy.
The Altitude is decreasing and increasing over and over again. 
I had altitudes of under -100meter and over 30meter.
The baro-value is constant between -1.8 and -2.1

Thanks for your help

Here is a link for the FC: http://seriouslypro.com/spracingf3

**Comment by digitalentity** [comment]
Please place the FC flat, level and not moving and check the values in Sensors tab (specifically Accelerometer). Post a screenshot here.

**Comment by jonastogo** [comment]
OK, done.
Here are the Screenshots.

These first two picture are done right after flashing inav onto the fc
![inav sensors start](https://user-images.githubusercontent.com/6411004/39663197-1d649ad0-506f-11e8-8291-32a64e28bd95.JPG)
![inav setup start](https://user-images.githubusercontent.com/6411004/39663198-1d7db8a8-506f-11e8-8c35-e656cbeb80dd.JPG)

These picture are done about 1,5 minutes after the first two pictures.
![inav sensors end](https://user-images.githubusercontent.com/6411004/39663210-4d5707d2-506f-11e8-9705-920d370a398b.JPG)
![inav setup end](https://user-images.githubusercontent.com/6411004/39663211-4d6f37f8-506f-11e8-897c-a0f72337bf85.JPG)

Notice the Barometer sensor.
I didnt move the FC at all between the pictures.
The FC is absolutly flat.

Here is a picture of the Sensors in Cleanflight just for compare.
![cleanflight](https://user-images.githubusercontent.com/6411004/39663223-a2e84c56-506f-11e8-9b1b-294de182f06a.JPG)

**Comment by digitalentity** [comment]
You have a faulty accelerometer sensor. Uncalibrated sensor should read roughly zero on X and Y and approximately 1G on Z-axis. In your case a flat FC is reading huge acceleration on Y axis. This means there's likely internal damage to the micro mechanics of the sensor. It's simply unsafe to fly this aircraft.

**Comment by jonastogo** [comment]
In Cleanflight all data is fine without calibrating.
This is confusing to me.
Do you think its possible to cut the chip out and implement a new one?

**Comment by digitalentity** [comment]
Cleanflight doesn't care about sensor data sanity, symmetry and scale, it just records sensor offsets when you press "Calibrate" once. This "calibration" is only valid for one position - being perfectly level, that's it. In all other positions this "calibration" will yield results that don't correlate with reality at all.

Sensor can be replaced if you are good with hot-air soldering machine, but I'd just buy a new (better, preferably F4-based) board.

**Comment by S-T-A** [comment]
I am having problems with the same firmware and configuration but with a colibri race f3 first calibration worked updated firmware and it won't get past first calibration???

**Comment by jonastogo** [comment]
I've just got a new SP Racing F3 Deluxe and it works fine now :)

**Comment by FrozenDroid** [comment]
Can this be closed?

**Comment by digitalentity** [comment]
Confirmed to be  a hardware issue.
