### ISSUE TITLE
Impossible midair arming with mission loaded in case the starting point is far from the craft position.

### ISSUE THREAD

**Issue by Tygrys-1** [iNavFlight/inav#3160]
INav 1.9.1
If I am far from the mission starting point the plane will not arm after loading a mission. It is a safety check and seems ok. But if I accidently disarm the plane in the air and the plane is far from the mission starting point (and the mission is loaded) it will not arm again - which is bad.

So I suggest to refuse a mission start (NAV WP mode) in case when the plane is far from the mission starting point and not refuse the craft arming. At least for FW.

**Comment by Tygrys-1** [comment]
It might apply also to the case when the number of sats falls below the default 6. IMHO it should always allow to re-arm if actually flying and has been disarmed by the switch or sticks.

**Comment by digitalentity** [comment]
Suggestion: modify `nav_extra_arming_safety` setting to have more options: `OFF`, `EACH_ARM` (default), `FIRST_ARM`. The last setting will enforce arming safety for first arming, but will allow re-arming even if checks fail.

**Comment by Tygrys-1** [comment]
This is better than nothing. :-) 
But it is still good to have safety chenck on the ground, and no limits in the air when re-gainng the controll. Maybe re-arming should be enabled unconditionally up to 10 (or so) seconds after a dissarm?

**Comment by ninja-zx11** [comment]
Hi all, Can we rearm  midair on Inav 2.0.1? I accidently disarmed my quad and couldn't rearm it and it fell from the sky.
I now have done set small_angle = 180.Do you guys think i should be able to rearm midair with set small_angle = 180 on Inav 2.0.1?Thanks.

**Comment by shellixyz** [comment]
@ninja-zx11 With `small_angle` set to 180 you should be able to. Unless you're using a GPS and lost the fix.

**Comment by ninja-zx11** [comment]
Thanks for the confirmation!!
