### ISSUE TITLE
Bidirectional serial port will not work on uart6 of Omnibus F4 V3

### ISSUE THREAD

**Issue by lo4wai** [iNavFlight/inav#3170]
I found that functions like FPort or TRAMP VTX control will not work with uart6 on Omnibus F4 v3 FC.  The tx and rx pin for uart6 connect to a inverted chip labelled "L84", I think that the inverter chip cannot support bidirectional serial port on tx.  Functions using separate tx and rx such as GPS on uart6 are fine.

It will be useful if the documentation for the board can mention this.

**Comment by DzikuVx** [comment]
@lo4wai you are wolcome to update docs by yourself

**Comment by Brat-Wurscht** [comment]
@lo4wai: Thank you for sharing your findings. I've run into this issue multiple times and have never figured out the cause
