### ISSUE TITLE
Heading Hold Mode Problem

### ISSUE THREAD

**Issue by KenImhof** [iNavFlight/inav#3177]
iNav Version: 1.9.0

Boards: Two quads with the same issue.  One is running ANYFCF7_EXTERNAL_BARO  and the other is SPRACINGF4EVO.

Problem: When running Heading Hold Mode (Mag Mode) after completing a left turn, the quad will intermittently (about once a flight) yaw back about 180 degrees to the right shortly after completing the turn.  It appears that the stick control to yaw to the left was not registered and the quad yaws back to its previous position that it was in just before starting the left turn.

Mag is properly calibrated and works correctly for all other functions such as RTH and POS-HOLD.

With Heading Hold Mode disabled, this problem does not occur.

I did not capture any logs and was hoping that this is a know or fixed issue.  If logs are required, I should be able to obtain the logs next weekend.

Thanks,

**Comment by DzikuVx** [comment]
@KenImhof please record logs

**Comment by KenImhof** [comment]
[LOG00001.TXT](https://github.com/iNavFlight/inav/files/1993820/LOG00001.TXT)

Attached is the associated log file for the released 1.9.1 version captured earlier today.
At 36.988 seconds, I start the left turn with a position heading of 358.1
At 40.488 seconds, I complete the left turn with a position heading of 191.9
From 40.488 seconds to 43.788 seconds the quad rotates back to the right.
At 43.788 seconds, the heading position is 285.0 all with no yaw input.

I also tried a custom build and doubled the mag update frequency and increased the task priority, which had no impact on this problem.  I will resume looking at the code, but any help would be appreciated.

**Comment by KenImhof** [comment]
Problem fixed.  Pull request #3205 submitted.

**Comment by KenImhof** [comment]
Pull request #4944 submitted.
