### ISSUE TITLE
Current Sensor reporting incorrect amperage but ONLY 40a and above.

### ISSUE THREAD

**Issue by jamestmcneal** [iNavFlight/inav#3180]
### Board and Version
Omnibus F4 pro V3  iNav Firmware 1.9.1

Board purchased here:  
https://2dogrc.com/omnibus-f4-pro-flight-controller-v3-barometer-smart-audio-support.html

INAV Configurator 1.9.3  Firmware Version 1.9.1

### Behavior
Current Sensor reporting incorrect amperage but ONLY 40a and above.
Accurate 0a to 39a.

Watt meter connected, Inav opened to configuration screen to display amperage draw.
Watt meter and inav amperage closely match UNTIL 40a, Inav then resets to 0 and continues to count again.
Example:  watt meter 5a, inav 5a.  watt meter 20a, inav 20a.  wattmeter 35a, inav 35a.
wattmeter 40a, inav 0a.  watt meter 50a, inav 10a.  wattmeter 60a, inav 20a.  etc. etc.

I reverted to firmware 1.8 do NOT have the issue.

**Comment by shellixyz** [comment]
More than likely a duplicate of #3144 and #3124. Please test this build: [inav_1.9.1_current_fix.zip](https://github.com/iNavFlight/inav/files/1955341/inav_1.9.1_current_fix.zip)

**Comment by jamestmcneal** [comment]
Thank You.

 

Thanks,

 

Todd McNeal
