### ISSUE TITLE
 2.0, SBUS from R9 and R9-slim receivers does not work

### ISSUE THREAD

**Issue by OlivierC-FR** [iNavFlight/inav#3185]
_--- 1st aircraft :_ **Matek F405-CTR, receiver Frsky R9-slim**

1: 99% working with 1.9.1 (remaining 1% are some random, and rather rare, mid-air disarms)

2: Flashed iNav 2.0 build 06/05/2018, full erase, dumped the 1.9.1 config, receiver bind is correct (not changed), receiving all telemetry from the FC on the X12.
Issue : The FC receives nothing from the SBUS, no channel moving in the receiver tab.
debug_mode = SBUS in sensor tab show all flatlines. 

3: Flashed with iNav 2.0 build 07/05/2018 provided by alberto, full erase, fresh config, didn't dump the old 1.9.1 settings this time, only checked the serial RX and port are correct (by default they are), same issue, SBUS signal is not seen by the FC.

4: Not touching the hardware, flashed back 1.9.1, SBUS is working as expected.

Dumps : https://www.dropbox.com/sh/fkcvvtakx0hsudj/AACzhUM5l5ynbp5I2HxHs2jsa?dl=0

_---- 2nd aircraft :_ **SP Racing F3, receiver Frsky R9 (full size, diversity)**

1: 100% working with 1.8.0

2: Flashed iNav 2.0 build 06/05/2018, full erase, set serial RX, correct port to SBUS
Same issue : SBUS signal is not seen by the FC.

3 : Not touching the hardware, flashed back 1.8.0, SBUS is working as expected.

https://www.dropbox.com/sh/dpnnfjxkbra5mj7/AAC-2gwUZND3I4xZ-f9Rmjmfa?dl=0

**Both Frsky R9 receivers are flashed with the latest firmware, FCC 29/03/2018**
**Using configurator 1.9.3**

**Comment by fiam** [comment]
I've uploaded a build of 1.9.1 with the SBUS fixes applied on top (#3110 and #3217), so R9 users can use it in the meantime.

[inav_1.9.1_R9_FIX.zip](https://github.com/iNavFlight/inav/files/2014821/inav_1.9.1_R9_FIX.zip)

**Comment by DzikuVx** [comment]
I suppose we can close it now
