### ISSUE TITLE
Axis drift - a persistent problem in fixed wing

### ISSUE THREAD

**Issue by Kaffiflight** [iNavFlight/inav#3186]
All INAV versions
All boards (that I heard of and being used in our forum)
It seems there still is a problem in fixed wing. I noticed this in early 2017, using a Omnibus F3 AIO and the back then latest version. The last one I have tried is 1.7.1. It has been experienced also with the current latest one (1.9.1), but not me. 

When flying more than several seconds in any angle (banked, nose down, nose up) the board with INAV loses its correct zero position, it drifts to the last flying angle. Means flying a longer left turn, makes it stay a bit out of horizontal and leaning to the left now. And vice versa. This behavior also is for nose down or up wich is even more annoying.
Back then I was told it´s a problem with the Omnibus F3. But as I can see now, it´s not. In our German forum (fpv-treff.de) we discuss about INAV and other users have also noticed this, with different hardware and different versions.
You don´t notice it when you use INAV only as flight stabilization (no Horizon mode, only ACRO) or turned down control-paramenters for HOR. You also don´t notice it with short hard turns and mostly flying level, if you leave the board not enough time to to come into a drift. You also don´t notice it when you use RTL, GPS-controlled flight ist not affected.
INAV has come a long way since the start, many features has been added and still are. But this basic function does not work right.
EDIT: I can see this problem has been referred as "Horizon drift" more often by now. But I want to point out it´s not only the horizon that is affected. It´s all axis, but it´s just most obvious while you can see the artificial horizon and banking is done more often and longer than diving or climbing nose up. And finally, depending on the type of plane, you might not realize a slight change on the noseup/nosedown heading, since a lot of planes cover that by changing the speed due to flight physics on their own. You only realize it if you know your plane well without fc-behaviour.
As far as I see INAV now, it´s working well with RTL and flight stabilization (against turbulence) since the first version I´ve tried (1.7), but all modes that affect the level position are still experimental.

**Comment by DzikuVx** [comment]
@Kaffiflight yes, we are aware of this and there are at least several tickets about this:
#1776  #2459  #1481

Since they are all about the same thing, if you do not mind, I will close this one. 

Thanks for your input
