### ISSUE TITLE
Unify flaps handling 

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#319]
As an extension of #307 : unify flaps handling with single flight mode and config option: FLAPS, FLAPERONS, FLAPS + FLAPERON and allow to configure flaps throw with AUX channel

**Comment by sppnk** [comment]
With this future feature and  with separated flaps, we could have 'airbrakes' (spoilerons + flaps). I would like to test that. 

In one of my planes I use separated flaps, and with a potenciometer I regulate the throws of the flaps (with a mixer customairplane setup and an AUX channel for the pot).

**Comment by DzikuVx** [comment]
@sppnk this you can test right now. `flaperon_throw_inverted=ON` and FLAPERON activation on the same AUX that drives flaps

**Comment by sppnk** [comment]
Oh, I didn't realize that. Thks

**Comment by DzikuVx** [comment]
With changes to FLAPERON it can be handled by the mixer now. Closing as obsolete
