### ISSUE TITLE
Custom OSD inputs based on telemetry values.

### ISSUE THREAD

**Issue by malarcky** [iNavFlight/inav#3193]
I think it would be nice to have the option to use custom values of telemetry inputs showed on the OSD, like 3 or 4 custom fields for showing telemetry data from each protocol, like mw power signal from CRSF, or other protocols. These values are actually showing in opentx on the radio transmitter so maybe this will be possible? I dont have the skills to do it.

**Comment by fiam** [comment]
The problem is that there’s no easy way to send those values upstream again. 

For that specific use case, we could add support for extended signal info (SNR, power, update frequency, LQ, etc, ...) but each RX would have to add support for it.

**Comment by malarcky** [comment]
Currently you have the option to send trough one chanenl, RSSI and LQ, maybe this is a thing that TBS would have to add in the firmware?
