### ISSUE TITLE
6 point calibration problem

### ISSUE THREAD

**Issue by rcabuser** [iNavFlight/inav#3199]
### Board and Version Matek F-405 std
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_ 1.9.1

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_ I may be missing something here, i have orientated the board with the arrow pointing to the right in the plane. i changed orientation in Inav to -90 degrees. When i then do the 6 point calibration, first and second step is no problem, but when i do step 3 where the right wing pointing down i get an OK mark on point 6???? seems to me that the -90 degree adjustment i made in Inav has no effect.

* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by digitalentity** [comment]
Please RTFM https://github.com/iNavFlight/inav/wiki/Sensor-calibration

> You may find this easier to do more accurately prior to installing the flight controller in your model and this procedure MUST be done referenced to the marked orientation on the board.
