### ISSUE TITLE
failsafe not activating correctly on cc3d with ppm encoder

### ISSUE THREAD

**Issue by bk79** [iNavFlight/inav#32]
@digitalentity  did you have the chance to try failsafe, while I'm still at ground I was trying to force a failsafe detection but it didn't trigger, throttle was sent to 850 us but the FC sent the motor values to minimum  that's all.

**Comment by digitalentity** [comment]
@bk79 Didn't happen to try the new failsafe (cleanflight#1190) yet, You bug is probably realted to that PR, you sould open an issue on official cleanflight, not this fork.

**Comment by bk79** [comment]
I was imagining that, but since I was using this fork I wanted to be sure that it wasn't related to something changed in the nav code. I'll close it
