### ISSUE TITLE
Servo Mixer Doesn't Save in iNav 1.9.3 Configurator

### ISSUE THREAD

**Issue by Zangetsu57** [iNavFlight/inav#3200]
Hello,

I used the servo mixer in the iNav 1.9.2 configurator and iNav 1.9.0 firmware.  It worked great.  I just upgraded to the iNav 1.9.3 configurator and 1.9.1 firmware.  The servo mixer no longer saves.  Additionally, when I type a smix in CLI, it doesn't work.  Here's an example command that I'm using in CLI for a 10% pitch, 90% roll mix (I wouldn't use this in practice, it's just an extreme example for testing).  The servos are on a flying wing on servo channels 3 and 4.

smix 0 3 5 10 0
smix 1 4 5 10 0
smix 2 3 4 90 0
smix 3 4 4 -90 0

Thank you for any assistance.

**Comment by AnandNL** [comment]
That happens when there already is a mix stored. use reset option first then it will save.

**Comment by Zangetsu57** [comment]
I tried the smix reset command, saved, and then used the servo mixer in the GUI.  Unfortunately it still didn't work.  When I rolled back to the 1.9.2 configurator and 1.9.0 firmware it worked fine.  Maybe I'm still doing something wrong, but did sit there for a couple hours trying different things to get it to work with the latest configurator and firmware.

**Comment by advancetom** [comment]
I have the Same issue inav 1.9.1 configurator 1.9.3

**Comment by advancetom** [comment]
I cannot switch to an older Version due F 405 Wing from Matek only have the 1.9.1 to use no 1.9.0 💩😱

**Comment by AnandNL** [comment]
is it set on custom airplane or just airplane?

**Comment by advancetom** [comment]
Custom Airplane chosed

**Comment by advancetom** [comment]
I tried both custom and normal airplane , but smix in cli dont show values ,same in configurator go to servo tab and normaly you see what mixer is set also nothing.Whats wrong?

**Comment by DzikuVx** [comment]
Just tested with Configurator 1.9.3 and FC 1.9.1 and everything is working correctly.
Select mixer airplane custorm, save and reboot, go to Servos tab, configure servos, save. Disconnect, connect, everything is there:

![01](https://user-images.githubusercontent.com/966811/39965932-0a9a2b92-56a3-11e8-941c-e0d931de07d3.PNG)
![02](https://user-images.githubusercontent.com/966811/39965933-0d6aa11c-56a3-11e8-974d-ff9dea55d19b.PNG)

**Comment by advancetom** [comment]
i found the problem
i set customairplane save reboot
now i have to manually write one smix rule in CLI than it works and it is editable later.
If i try the configurator way it doesnt work :(

**Comment by DzikuVx** [comment]
In an example above, smix was configured only using Servo tab. No CLI commands

**Comment by Zangetsu57** [comment]
I had my mixer set to flying wing.  Could that have been the issue?

**Comment by DzikuVx** [comment]
In 1.9 `smix` can be set only for CUSTOM and CUSTOM_AIRPLANE
