### ISSUE TITLE
Display problem with OSD

### ISSUE THREAD

**Issue by flashez** [iNavFlight/inav#3201]
### Board and Version
It's an Omnibus F3 (with sd), probably pro version because it has barometer.
# version
# INAV/OMNIBUS 1.9.1 Apr 21 2018 / 12:53:03 (03a5c1922)

Getting osd problems with some parameters such as:
- voltage (and cell voltage): displaying weird thing
- flymode displaying only: 100FS100

DVR: https://www.youtube.com/watch?v=6tVS7ITA2r4

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/1xHseGdx

If you have any idea of what is occuring ;)

**Comment by flashez** [comment]
Just found this similar issue: https://github.com/iNavFlight/inav/issues/3135
Gonna try to update the font

**Comment by flashez** [comment]
Ok so basically this is written on the main page: 

> Always load OSD fonts when starting using a new board from the configurator OSD tab to avoid artifacts on the video feed.

**Comment by rcabuser** [comment]
Great thx, that really helped me:-) my OSD screen where covered with the letter "V". did the font upload and now it works great, thx again bro:-)

**Comment by fiam** [comment]
Just updated the wiki to also mention that you should update the font after upgrading INAV, since most versions contain new characters/symbols in the OSD. I guess we can now close this one.
