### ISSUE TITLE
Reversed pith and roll values- Omnibus f4

### ISSUE THREAD

**Issue by Iamsadomaso** [iNavFlight/inav#3211]
Im having issue with omnibus f4 running on inav 1.9.1.
When nose up, values are getting negative and while nose down positive. The same thing goes with roll, changing board or sensor aligment doesn't do annything with this. It was fine before so it's not hardware failure. Anny idea?

**Comment by shellixyz** [comment]
> When nose up, values are getting negative and while nose down positive

That's normal

> The same thing goes with roll

I don't know what you mean by that but roll angle should be negative when rolling left and positive when rolling right.
