### ISSUE TITLE
Led problem using Matek F405 STD 

### ISSUE THREAD

**Issue by rcabuser** [iNavFlight/inav#3212]
### Board and Version
_Board name goes here. Matek F405 STD
_Version of INAV used goes here_  1.9.1

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Not getting led strip working correctly, weird and different pattern every time i power up the aircraft. Used a cheap china board earlier (Omnibus) where the led's worked perfectly.

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by MATEKSYS** [comment]
2812LED is on S5 pad in INAV target.

**Comment by rcabuser** [comment]
Yeah, i'm using the S5 for led.

**Comment by gstyle97** [comment]
Me too, on s5 don't work led.

**Comment by rcabuser** [comment]
Yeah ok, damn irritating:-(

**Comment by MATEKSYS** [comment]
Probably there is sensitivity difference from different 2812LED manufacturer.
Tested it with one of our LED strips just now. works fine.
If your LED strip doesn't work. try to solder LED DIN here, or bridge 2 sides of this resistor.
It is a 200ohm resistor between S5 pad and pin PA15

F405-STD
![20180517221234](https://user-images.githubusercontent.com/23047106/40183074-6f5668dc-5a1f-11e8-8f30-9d73295ce9ec.png)

**Comment by MATEKSYS** [comment]
F405-CTR

![image001 05-17-22-06-03](https://user-images.githubusercontent.com/23047106/40183313-189e9d60-5a20-11e8-9dbd-d09d76078505.jpg)

**Comment by rcabuser** [comment]
Yeah ok, thx for the input. Too bad my board is mounted/buried in my plane now, strange that the led strips i bought worked in my first cheap clone board without a problem.

**Comment by holoduke** [comment]
anyone knows this for the matek F405 WING. I have big issues with bad signal while using long wires (1 meter). I don't know where this resistor is on that board.

**Comment by dangerg** [comment]
This worked for me on the F405-STD
