### ISSUE TITLE
Support for Matek F411

### ISSUE THREAD

**Issue by spleenware** [iNavFlight/inav#3213]
Just wondering if anyone know how to port particular board targets from betaflight over to INav?
It has a Matek F411 target, but sadly none on INav.

**Comment by stronnag** [comment]
It is available in iNav, see the development branch. Experimental 1.9.1hex http://seyrsnys.myzen.co.uk/inav_dev/inav_1.9.1_MATEKF411.hex.gz

**Comment by spleenware** [comment]
Thanks for that. I'll try it out.

**Comment by spleenware** [comment]
I recently setup the dev environment, to have a go at it myself, but for the MATEKF411 target, I'm getting this make error:
make: *** No rule to make target `lib/main/CMSIS/CM4/DeviceSupport/ST/STM32F4xx/stm32f4xx_gpio.c', needed by `obj/main/MATEKF411/stm32f4xx_gpio.o'.  Stop.

**Comment by stronnag** [comment]
Builds OK here

**Comment by fiam** [comment]
@spleenware `rm -fr obj`, then `make MATEKF411`

**Comment by spleenware** [comment]
Thanks @fiam that did the trick (I did try make clean previously, but didn't work)

**Comment by MATEKSYS** [comment]
http://www.mateksys.com/?portfolio=f411-mini#tab-id-7
