### ISSUE TITLE
Idea: auto land mode for MR

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#3214]
When flying FPV/acro sometimes the landing phase is tricky, specially when the surface is hard.
In such cases I usually take off the goggles and finish the landing LOS or just engage RTH which usually lands smoothly.

The drawback of engaging RTH is that it first punches the throttle to do initial climb. This is often not what I really need, specially on very empty battery.

It would be useful to have a landing mode that would be just like RTH, but skipping the initial climb.
Another option would be to skip the climb and also cruise home, just landing the craft where it is.

**Comment by giacomo892** [comment]
I'm playing around a NAV_LAND mode. But you can get a similar behaviour to what you are asking by setting nav_rth_alt_mode = CURRENT

**Comment by krzysztofmatula** [comment]
Yes, but for failsafe/RTH I really prefer AT_LEAST with relatively safe altitude (I use 20m).

For the 2nd idea ("skip the climb and also skip cruise home") - this actually is already available by engaging POSHOLD+ALTHOLD and then descending by lowering throttle.

So, the missing one is the 1st one ("mode that would be just like RTH, but skipping the initial climb").
This one could be also useful in case of getting lost for pointing towards home and starting the cruise.
I think I'd like to have it assigned on a momentary switch as a quick-helper.
