### ISSUE TITLE
Feature request: show "distance left" in osd 

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav#3215]
It would be cool if we can see some info in the osd how far we can go on the used lipo. It should calculate the possible travel distance based on given lipo capacity (the mAh warning setting maybe) and average efficiency during the current flight.

**Comment by skaman82** [comment]
maybe even with the same "gas" icon like in a car
![restkilometer-2933322019638510632](https://user-images.githubusercontent.com/11768024/40003322-547ef83c-5793-11e8-9fad-543fd4a9a9fd.jpg)

**Comment by shellixyz** [comment]
Partially done in #2863 (time). Should not be hard to do.

**Comment by skaman82** [comment]
@shellixyz would be great if you could add this to your PR https://github.com/iNavFlight/inav/pull/2863 if possible

**Comment by fiam** [comment]
Fixed in #2863
