### ISSUE TITLE
RTH should be aborted if the craft does not change its position.

### ISSUE THREAD

**Issue by Tygrys-1** [iNavFlight/inav#3218]
It is when the craft is ie. stuck on the tree or fails to the ground and then loses the RC signal. 
It happened to me that the plane crash landed behind the hill and lost radio signal. It then tried to RTH cutting the grass and doing a mess with the propeller, unloading and heating the battery.

It might also apply to other auto modes.

**Comment by giacomo892** [comment]
You can close this and comment on #2331

**Comment by Tygrys-1** [comment]
I think this is about a problem in the RTH procedure. It has a check if a plane goes in the wrong direction, it does not check if the plane is not going anywhere. The flying/not flying condition discussion is somehow more general.
