### ISSUE TITLE
Transition from RTH to ALTHOLD doesn't reset altitude setpoint

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#322]
I observe that _sometimes_ when enabling the ALT_HOLD the copter starts going up and rotates in the YAW axis relatively quickly (>50 deg/s according to gyro readings). I don't yet have steps to reproduce the issue. It just sometimes happens. 

Before enabling BARO I don't do anything special. The craft is just hovering in HORIZON mode.

See the blacklog log attached at the following points:
- 7:01.886
- 7:24.554

The log reflects the real behavior - altitude increases and heading changes.

I use INAV 1.1

[blackbox_log_2016-06-27_214021.TXT](https://github.com/iNavFlight/inav/files/335942/blackbox_log_2016-06-27_214021.TXT)

**Comment by DzikuVx** [comment]
Could you try similar scenario without MAG mode enabled? It looks like your magnetometer is too close to power lines and is affected by changing mag field generated by them. 

<img width="1169" alt="zrzut ekranu 2016-06-28 o 23 00 38" src="https://cloud.githubusercontent.com/assets/966811/16432290/93181928-3d84-11e6-9c93-53e2e0014023.png">

Cases like above are all over your BB log. Not only where you pointed out.
My theory is that when you enable ALT_HOLD and your throttle is far from hover value, sudden spike in current going into motors causes magnetometer going crazy and causing yaw correction. 

Confirm by disabling MAG_HOLD or/and moving mag further away from power lines.

**Comment by krzysztofmatula** [comment]
Good tip, I'll disable MAG when it happens again and retry.

The log is from 250-sized quad, so all lines are close to the controller... I have to sort it out anyway, so experiments like https://github.com/iNavFlight/inav/issues/301. Finally I plan to find the line to cut on the SPRacingF3 PCB and use MAG that comes together with my M8N, but it's more drastic.

I saw the MAG readings, but I have no comparison how they should look like. Generally the quad keeps heading and most of the time ALT_HOLD works perfectly (despite short glitch at the time it is engaged). 

In the examples I gave the throttle was at a perfect hovering level.

**Comment by DzikuVx** [comment]
> In the examples I gave the throttle was at a perfect hovering level.

Well, not here: 7:24.554. See what is happening with throttle right after you engage ALT_HOLD. There are quite big throttle movements. Maybe baro is not isulated enough? Sponge?

**Comment by krzysztofmatula** [comment]
Baro sensor is insulated properly and usually works very well, giving ALT_HOLD with almost no oscillations. Here, just after changing mode the throttle applied is much over the hovering level and the quad goes up (what baro readings clearly show).

I bet it is the MAG issue, or some other bug in the code. I don't understand how the wrong MAG readings would end up in not keeping the altitude and going up.

**Comment by DzikuVx** [comment]
Going up might be only a side issue here. Yaw jump is rapid and strong, that copter trying to archive rotation rate generates more thrust

**Comment by krzysztofmatula** [comment]
That may be the explanation.

There's one more thing that _may_ cause side effects. 
Switching on BARO with a transmitter switch actually is visible as a quick change over the following modes:
- HORIZON_MODE|MAG
- HORIZON_MODE|MAG|GPS_HOLD
- ANGLE_MODE|MAG|BARO|GPS_HOME
- ANGLE_MODE|MAG|BARO
- HORIZON_MODE|MAG|BARO

I use single AUX for providing BARO, GPS_HOLD and GPS_HOME switches multiplexed to the FC. It looks like someone smoothens the RC channel, which results in the above quick sequence. I've no idea how to disable such smoothing, and whether it on on the transmitter (er9x) or FC side. Nevertheless, I was always having this and it didn't influence ALT_HOLD.

**Comment by krzysztofmatula** [comment]
I reproduced the issue with MAG disabled. See the attached log at 1:31.000.

I was hovering at altitude ~1.6m, then switched on ALT_HOLD. As a result the machine moved up quite rapidly and started to stabilize at altitude >9m.

It looks like it _wants_ to go to such altitude, while I wanted it to stay at 1.6m.

I have the default nav_rth_altitude = 1000 and nav_rth_alt_mode = AT_LEAST - maybe the fact that RTH was active for a fraction of second while engaging ALT_HOLD caused what I observed? It looks more and more like a bug, especially that it happens "sometimes"...

[blackbox_log_2016-07-08_220647.TXT](https://github.com/iNavFlight/inav/files/355060/blackbox_log_2016-07-08_220647.TXT)

**Comment by krzysztofmatula** [comment]
Confirmed!
Changing the nav_rth_altitude to 5m made the ALT_HOLD altitude close to 4m, and not 9m as before!
In the attached new log it occurs at 0:19.100.

Then, I programmed a dedicated switch for engaging ALT_HOLD (without going through RTH for a fraction of second) and - ALT_HOLD worked!. See it at 0:38.806.

Later I used the original switch again (the one that enables RTH for a fraction of second) to enable ALT_HOLD (at 0:53.804) and... it worked as it should. Well, didn't I say the issue manifests _sometimes_ ?

[blackbox_log_2016-07-08_231556.TXT](https://github.com/iNavFlight/inav/files/355130/blackbox_log_2016-07-08_231556.TXT)

**Comment by digitalentity** [comment]
@krzysztofmatula 
Ok, now that I know that you are switching to AltHold through (essentially _from_) RTH explains it. If altitude controller was active (RTH) switching to AltHold mode won't reset current altitude target. This is a bug that needs fixing. Thanks for finding.

**Comment by krzysztofmatula** [comment]
I've jus verified the fix and it solves the problem, but only partially.
My original observation was that the copter goes up _and rotates_.
After this fix the altitude is maintained, but it still rotates (unless I disable mag).
I think similar correction shall be done to HeadingController as well. It looks like it rotates towards the home point and stops. Again, surely result of short RTH.
I can upload a log if necessary, however I think it won't be needed.

**Comment by krzysztofmatula** [comment]
Unfortunately I have no rights to reopen the issue...

**Comment by digitalentity** [comment]
@krzysztofmatula current issue is resolved. Yaw rotation is another issue, please open a new one.
