### ISSUE TITLE
Pls disable TIM_USE_FW_SERVO on S5(PA15) of MATEKF405 target

### ISSUE THREAD

**Issue by MATEKSYS** [iNavFlight/inav#3223]
Targat: MATEKF405
FC related: F405-OSD, F405-AIO, F405-STD, F405-CTR, F405-mini

No TIM_USE_FW_SERVO on S5 pad before 1.9.1.
Someone reported Rudd couldn't work on S6 with 1.9.1.

S5(PA15) is used for Hex-X motor or 2812LED exclusively.
We arranged S6 for RUDD of Airplane

TIM_USE_FW_SERVO on S5 also override FCHUB-W schematic.

Pls disable it. Thanks.

**Comment by DzikuVx** [comment]
PR in place, closing
