### ISSUE TITLE
Calibration problem

### ISSUE THREAD

**Issue by AtaNaS13** [iNavFlight/inav#3225]
### Board and Version
Omnibus F4 pro v2
Inav 8.0

# INAV/OMNIBUSF4PRO 1.8.0 Nov  1 2017 / 06:34:32 (912d1315)

_If it's a custom-compiled firmware please mention this_

### Behavior
I cannot calibrate the accelerometer, i go to the calibration tab, press calibration and without doing anything it sais on the top "Calibration Started" and after a second "Calibration Completed" of course in the pre arming checks the calibration has an X and is red.
The UAV image is moving as i move the FC and in the sensors tab the values change as i move it.

**Comment by shellixyz** [comment]
It is normal. You are using 1.8 so the steps won't be checked until you have calibrated all the positions. Put your FC in position like in the first picture then press calibrate. Wait for the calibration to complete. Repeat for all the other positions.

**Comment by digitalentity** [comment]
@AtaNaS13 this is normal behavior for 1.8.0
As @shellixyz pointed out Calibration positions are not reported by 1.8 firmware. You need to repeat calibration 6 times in 6 different positions.
