### ISSUE TITLE
Add cruise mode

### ISSUE THREAD

**Issue by JonnyFPV** [iNavFlight/inav#3228]
Hello, 

If it’s possible I would like an cruise mode. 

You activate it and the plane or copter flyes in a straight line in current altitude and current heading until you switch it off or failsave kicks in.  It would be nice that you can overright the heading and altitude with sticks ... 

Thank you :)

**Comment by Tygrys-1** [comment]
AFAIK you may combine Altitude Hold with the Heading Hold Mode.

**Comment by Dronek** [comment]
https://github.com/iNavFlight/inav/issues/1416
https://github.com/iNavFlight/inav/issues/1712

**Comment by fiam** [comment]
Fixed in #3311
