### ISSUE TITLE
Parallel RGB LED and soft serial

### ISSUE THREAD

**Issue by bazyl78** [iNavFlight/inav#323]
Isn't it possible to make future change to have both RGB led and serial port? I mean led on rc5  and soft serial on rc7-8. It is very bad now to choose between them on naze32 :(

**Comment by krzysztofmatula** [comment]
Not sure if this is what you are asking, but LED_STRIP and SOFTSERIAL cannot be combined on NAZE because of not enough timers. See: https://github.com/cleanflight/cleanflight/issues/1560
