### ISSUE TITLE
Omnibus F3/F4  (all versions) servo pin# output for Pitch control 2axis Gimbal/BGC2.2 controller

### ISSUE THREAD

**Issue by alanfj** [iNavFlight/inav#3231]
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by alanfj** [comment]
I have an Omnibus F3 v1.1 and an Omnibus F4 v2 and do not know what pin #'s for servo output to use. I have tried motor pins 7&8 on my F3 and motor 5&6 on my F4. Help?

**Comment by DzikuVx** [comment]
You have to wait until INAV 2.0 to make that work on those boards

**Comment by alanfj** [comment]
Thanks for your quick response & heads up! As usual, "You're the Man!" Thanks again. PS: the neweast version, INAV 1.91, is working very well, too.

**Comment by alanfj** [comment]
I'll be patiently waiting. I've got four aerial photography drones w/ these FC's & BGC2.2b camera gimbals waiting for this super upgrade addition.

**Comment by Kerleston** [comment]
I am trying Inav 2 RC4 with Omnibus F3 and Motor 5 and 6 is not assigned in resource map.
I could not do the remap.
