### ISSUE TITLE
BUG?  OSD speeds different units

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#3235]
NOTE: i haven't put a vtx in this so cannot test if it's a configurator bug or not yet, but it's an F35 Lightning FC with 1.9.1 loaded and everything reset to defaults.

Not sure if this bug is in just the configurator or not, but when setting up the speed icon in the OSD, if you select imperial, then the airspeed and the gps speed are both in MPH.

If you set it to "UK" then the air speed is in km/h and the gps speed is in MPH. Unless i'm mistaken, the uk is still on miles per hour for speed. Look in the top right hand corner. the top line is the air speed, the bottom one is the GPS speed and i'm using the "large" font.

![inav 1 91 osd bug](https://user-images.githubusercontent.com/1495297/40254547-e00bd8e0-5ab1-11e8-841b-e9bebb913630.png)

**Comment by fiam** [comment]
@wx4cb Thanks for noticing this. It's just a bug in the preview. The PR for the configurator is in place, so I'm closing this one.
