### ISSUE TITLE
Autotune and fixed_wing_auto_arm incompatibility

### ISSUE THREAD

**Issue by tonyyng** [iNavFlight/inav#3244]
### Board and Version
_Omnibus F3_
_1.9.1_

_INAV/OMNIBUS 1.9.1 Apr 21 2018 / 12:53:03 (03a5c1922)_

### Behavior
* _If you're using the wing_auto_arm option along with AUTOTUNE, there is no way to disarm and use a stick command to save the updated gains._
* You also can't see the flight summary information in the OSD.  That is only available after disarm.

**Comment by shellixyz** [comment]
Yes if you can't disarm the only way to save the tune is to save it with the configurator. Not sure how we can get around this. Maybe a setting for using a channel to save the values ?

**Comment by tonyyng** [comment]
Maybe someone can think of a clever way to disarm.  I realize that you also lose the ability to see the flight summary information on the OSD.  That only comes up after disarming.

I like the idea of automatically arming.   I'm just not sure why automatic arming has to come with not being able to disarm.  

What about automatically disarming if the plane is not moving and throttle is low for some period of time (30s)?  I'm not sure what the best way to determine not moving.  Altitude zero and minor GPS or accelerometer movement?  Or disarm if the aircraft is held upside-down (like the DJI Spark).  This would need some checks to make sure the aircraft isn't actually flying inverted.

**Comment by tonyyng** [comment]
There is already an option called: auto_disarm_delay

Delay before automatic disarming when using stick arming and MOTOR_STOP. This does not apply when using FIXED_WING

Maybe its logic can be modified to support this scenario.

**Comment by shellixyz** [comment]
We can't disarm after `auto_disarm_delay` when throttle is low otherwise it would disarm mid-air when gliding for more than `auto_disarm_delay`. The way it could be done is disarm when a landing/crash is detected.

**Comment by tonyyng** [comment]
What I was suggesting is to use auto_disarm_delay in combination with some other aspect (e.g. altitude).  It doesn't seem realistic to have low throttle for some delay period (e.g 10s), with an altitude less than 3 meters during that delay period.

However, if you can use the auto_disarm_delay after the landing is detected, that would work as well.

**Comment by shellixyz** [comment]
> It doesn't seem realistic to have low throttle for some delay period (e.g 10s), with an altitude less than 3 meters during that delay period.

It is realistic. You can fly with negative altitude relative to home altitude. It happens to me. When you start from a high point it is not uncommon to be flying bellow your position.

**Comment by tonyyng** [comment]
Good point.  It comes back to figuring out a reliable way to determine that the plane is not flying.
How about:
- throttle is zero
- altitude is less than 1m, not changing, 
- aircraft is pointing down for the auto_disarm_period?

**Comment by shellixyz** [comment]
It has been discussed a bit with the dev team. Personally for fixed wing I think a good way would be to use the acceleration values and rate of change in conjunction with the GPS data if it is available and also clever timing.

>  throttle is zero and altitude is less than 1m, not changing

Not really safe IMO

> aircraft is pointing down for the auto_disarm_period?

The plane/wing can be pitched up even after landing

**Comment by tonyyng** [comment]
> It has been discussed a bit with the dev team. Personally for fixed wing I think a good way would be to use the acceleration values and rate of change in conjunction with the GPS data if it is available and also clever timing.

Perfect.
