### ISSUE TITLE
RTH on my S800 Sky Shadow Problem

### ISSUE THREAD

**Issue by jamichx** [iNavFlight/inav#3249]
Hi , I can not figure this one out. I use INav 1.9.0 version. I will post my diff log for you to spot the problem. I am new to FPV and this is my first wing using FPV. Have done some nice long range flights but every time I have to use RTH (which execute perfectly and is tested) my wing will not fly nicely strait but will climb and then drop and climb and then drop and will do this all the time. I have no idea what setting to change to make my wing flying strait. I had altitude mode set to current when this was doing. Now I set it to fixed 100m. The problem is the same. Can anyone help me to set it up properly ? 

This is big problem when I lose video signal few km away and have no extra juice in my battery for this kind of flight to return. I need nice strait flight back home. 

Any help will be much appreciated. 

here is my diff : 

# INAV/OMNIBUS 1.9.0 Mar 4 2018 / 23:17:26 (dc4ef594f)

# resources

# mixer
mixer FLYING_WING

# servo mix

# servo
servo 3 1000 2000 1500 -100 -1 

# feature
feature -TX_PROF_SEL
feature -BLACKBOX
feature MOTOR_STOP
feature GPS
feature AIRMODE
feature PWM_OUTPUT_ENABLE

# beeper

# map
map TAER5678

# name

# serial
serial 0 32 115200 38400 0 115200
serial 1 2 115200 38400 0 115200
serial 2 64 115200 38400 0 115200

# led

# color

# mode_color

# aux
aux 0 0 1 900 1900
aux 1 1 0 1925 2100
aux 2 2 0 1375 1600
aux 3 3 0 1950 2075
aux 4 8 3 1900 2100
aux 5 10 0 900 1100
aux 6 14 6 1900 2100
aux 7 11 4 1925 2100
aux 8 15 6 1300 1700

# adjrange
adjrange 0 0 2 900 1125 15 5
adjrange 1 0 2 1150 1500 16 5
adjrange 2 0 2 1550 1900 18 5
adjrange 3 0 2 1925 2100 19 5

# rxrange

# master
set gyro_sync = ON
set gyro_hardware_lpf = 20HZ
set acc_hardware = MPU6000
set acczero_x = 117
set acczero_y = -67
set acczero_z = -519
set accgain_x = 4081
set accgain_y = 4115
set accgain_z = 4060
set mag_hardware = NONE
set baro_hardware = NONE
set pitot_hardware = NONE
set receiver_type = SERIAL
set rssi_channel = 12
set serialrx_provider = SBUS
set rx_min_usec = 905
set rx_max_usec = 2100
set min_throttle = 1023
set max_throttle = 1945
set failsafe_throttle_low_delay = 0
set failsafe_procedure = RTH
set align_board_yaw = -900
set vbat_scale = 1107
set vbat_max_cell_voltage = 420
set battery_capacity = 2200
set battery_capacity_warning = 660
set battery_capacity_critical = 440
set current_meter_scale = 255
set small_angle = 180
set gps_ublox_use_galileo = FIXED
set nav_extra_arming_safety = OFF
set nav_user_control_mode = CRUISE
set nav_rth_allow_landing = NEVER
set nav_rth_alt_mode = FIXED
set nav_rth_altitude = 10000
set nav_mc_hover_thr = 1700
set nav_fw_cruise_thr = 1700
set nav_fw_min_thr = 1023
set nav_fw_max_thr = 1945
set nav_fw_bank_angle = 45
set nav_fw_climb_angle = 30
set nav_fw_loiter_radius = 4000
set nav_fw_launch_motor_delay = 50
set nav_fw_launch_spinup_time = 150
set nav_fw_launch_min_time = 5000
set nav_fw_launch_timeout = 11550
set nav_fw_launch_climb_angle = 30
set smartport_fuel_unit = PERCENT
set osd_row_shiftdown = 1
set osd_rssi_alarm = 100
set osd_time_alarm = 5
set osd_alt_alarm = 0
set osd_main_voltage_pos = 2104
set osd_rssi_pos = 2081
set osd_flytimer_pos = 2486
set osd_ontime_pos = 470
set osd_flymode_pos = 2369
set osd_crosshairs_pos = 2048
set osd_current_draw_pos = 2168
set osd_mah_drawn_pos = 2199
set osd_wh_drawn_pos = 20
set osd_bat_remaining_capacity_pos = 2231
set osd_bat_remaining_percent_pos = 184
set osd_gps_speed_pos = 2296
set osd_gps_sats_pos = 2465
set osd_gps_lon_pos = 2498
set osd_gps_lat_pos = 2514
set osd_home_dir_pos = 2126
set osd_home_dist_pos = 2209
set osd_altitude_pos = 2273
set osd_ontime_flytime_pos = 375
set osd_messages_pos = 2434
set osd_main_cell_voltage_pos = 2136
set osd_heading_graph_pos = 2090
set osd_efficiency_wh_pos = 100

# profile
profile 2

set fw_p_pitch = 14
set fw_i_pitch = 22
set fw_ff_pitch = 4
set fw_p_roll = 30
set fw_i_roll = 28
set fw_ff_roll = 3
set fw_p_yaw = 0
set fw_i_yaw = 0
set fw_ff_yaw = 0
set tpa_rate = 50
set tpa_breakpoint = 1550
set roll_rate = 55
set pitch_rate = 55
set yaw_rate = 2

#

**Comment by DzikuVx** [comment]
Please take a look here: https://www.youtube.com/watch?v=57bRPuqW_hk

**Comment by jamichx** [comment]
Thank you for the tip will see if that is the culprit. Also another friend from youtube suggested that I need to adjust the cruise throttle value, either by increasing or decreasing it. Now I have something to try and maybe resolve my problem. I will post the result hopefully positive one. Thank you both.
