### ISSUE TITLE
Split up auto-throttle and altitude hold for fixed wing

### ISSUE THREAD

**Issue by FinalFrag** [iNavFlight/inav#3251]
I'd like to suggest  a new feature. Well, splitting up an existing feature actually. This is for fixed wing specifically.

Right now when you activate altitude hold mode, iNav also enables auto throttle. It would be nice to have these on 2 separate modes, so you can have altitude hold, but manual control over throttle/speed.

When I try to do follow footage with a friend, it's hard enough to find each other. When you finally get on the same line (using altitude hold, heading in osd, lots of communication, etc) you want to get as close to each other as possible. But once you click out of AH, it's hard to get closer AND maintain altitude manually. When these 2 features are separate, I could click out of auto-throttle but stay in AH and just increase throttle to get closer.

I understand stalls might become a problem, so maybe let iNav control the minimum throttle value, but give priority to the throttle stick if its above that value?

**Comment by shellixyz** [comment]
I'm going to work on this.

> I understand stalls might become a problem, so maybe let iNav control the minimum throttle value, but give priority to the throttle stick if its above that value?

Yes the idea is for the minimum throttle to still be automatic but to be able to increase it by moving the throttle stick past the mid point (>1500) like it is done in Arduplane. All the auto modes could have the throttle manually adjusted unless in failsafe. Then the throttle would be automatic just like now.
