### ISSUE TITLE
INAV 1.8 no gps arming issue

### ISSUE THREAD

**Issue by JDFPV** [iNavFlight/inav#3270]
I have an omnibus f4 pro board, with no gps. I have no gps selected under the configuration tab, nor any nav flight modes. I can not get this board to arm using 1.8. I do have a arm switch. Please help

**Comment by shellixyz** [comment]
Please post config dump and output of the `status` command

**Comment by teckel12** [comment]
@JDFPV Just a guess: `set nav_extra_arming_safety = OFF`

**Comment by shellixyz** [comment]
`nav_extra_arming_safety = OFF` is not needed if none of the navigation modes are used.

**Comment by JDFPV** [comment]
Thats it. Thanks

**Comment by digitalentity** [comment]
@shellixyz problem might be that firmware doesn't report and Configurator doesn't display modes that are lacking sensors. If you disable GPS in Config you won't see RTH mode, but it still will be configured (this is something we could improve).

**Comment by digitalentity** [comment]
@JDFPV great that you fixed that.

**Comment by shellixyz** [comment]
Indeed might be the reason that's why I wanted to see a dump. How could we improve that ? Show the modes when they are configured even if they should not be shown because of lacking hardware ?

**Comment by digitalentity** [comment]
Good idea. We can also light up those modes in red color in Configurator to grab user attention.
