### ISSUE TITLE
OSD CLI != GUI

### ISSUE THREAD

**Issue by Artyum** [iNavFlight/inav#3273]
Hi, In Configurator 1.9.3 and omnibus F4 v3 I try to setup OSD by using CLI. I noticed that after I run some commands eg:
set osd_home_dir_pos = 720
set osd_home_dist_pos = 3021
I can't see the corresponding attributes in OSD Preview window  anymore.  I've disabled everything else beside above two and they are not there.  I can click on and off switch for Direction and Distance to Home but still no icons in the preview.
Best Regards

**Comment by shellixyz** [comment]
That's because you put them outside of the display area. Do this and you'll see them again (second column, second row):

```
set osd_home_dir_pos = 66
set osd_home_dist_pos = 66
```

**Comment by Artyum** [comment]
That was it, thank you.
