### ISSUE TITLE
Smartport telemetry

### ISSUE THREAD

**Issue by VA3WK** [iNavFlight/inav#3282]
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it
Matek fc F405-wing
_Version of INAV used goes here_
1.9.1
_Use CLI command `version` and put its output here_
INAV/MATEKF405SE 1.9.1 APR 21 2018 /13:46:07 (03a5c1922)
_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
Smartport telemetry stops working anytime after 10-30min. (does not do it with 1.9.0).It also does it with 
a Spracing F3 FC again 1.9.0 works fine.

* _Steps needed to reproduce the problem_
just let it run
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_
No
#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by teckel12** [comment]
@VA3WK I've had this problem due to heat.  When my receiver gets too hot, it stops sending telemetry.  My VTx was generating too much heat and too close to my Rx, which caused the problem on hot days.  I've had this happen on a couple different receivers and different versions of INAV.

I could get telemetry to start working again by simply blowing on the Rx, moving it away from the VTX, or pointing a fan towards my quad.  It's never happened when flying, as with a quad there's lots of natural cooling when flying.

I'd seriously look into an overheating issue, as what you're describing sounds exactly like what I've experienced.

**Comment by VA3WK** [comment]
It works fine with 1.9.0 ,so i don't think its the problem. I tried several boards spracing F3, matek f4-wing Thank for your reply.

**Comment by teckel12** [comment]
@VA3WK Meh.  It's warmer now, so...  I thought this was a problem with last summer's version, till I realized it was just summer causing it.  I'm having no lost telemetry issues with 1.9.1, even when on the bench for a very long time.

**Comment by VA3WK** [comment]
well you are lucky then, i just tested a omnibus f4 pro and after about 10min plus it stops responding to telemetry request from the receiver.(a brand new X8R.) on 1.9.1, re flashed with  1.9.0 and it works fine.

**Comment by teckel12** [comment]
@VA3WK I'll try it with an Omnibus F4 Pro today and get back with you.  I'l running a 2.0 development build, so there could be some differences.

Oh, do all the FC/based telemetry stop at the same time, or is it a few, then worsens till they all stop?  Also, does the X8R telemetry still send when they stop from the FC?  Like is RSSI still sending?

**Comment by teckel12** [comment]
@VA3WK I did get it to fail eventually after over 30 minutes.  I also couldn't get it to recover (ever after putting the quad in the freezer).

I'll need to test this again on a couple different quads and see if I can duplicate it and if there's any similarities to try and isolate the problem.

**Comment by VA3WK** [comment]
Yes sometimes is goes faster i have seen it as short as 9min . I don't think temp makes a difference. i don't know yet why and under what circumstances it stops' if you put a scope to it you see that the receiver is still trying to communicate.  My feeling is that there is some kind of a buffer overrun ,but i am not a programmer so i have to leave that up to the experts. i can see that the telemetry gets slower and slower and the horus first reports "sensor last" and then more and more sensors quit and eventually it reports "telemetry last".

**Comment by VA3WK** [comment]
The RSSI and receiver voltage still work after that.

**Comment by kd2eat** [comment]
Just a "me too" for this problem.  Inav 1.9.1.  I have smartport telemetry coming out of an Omnibus F4 Pro V3 into my Taranis radio via an X8R receiver.  My flight began at 19:14:07.  At 19:26:02 the smartport telemetry in my logs all froze at the same values.  All of the other things - switch positions, sticks, RSSI continued to update.  I was just looking into this and ran into this bug report.

I can't imagine heat is an issue.  My receiver is on out on one wing, the VTX is on the other, FC is in the middle.  This is on a FX-79 Buffalo, so there is about 2 1/2 feet of separation between components.

**Comment by teckel12** [comment]
@kd2eat I've been able to simulate it too, and it's not the issue I've had with an overheating TX like I've had in the past.  The overheating symptoms are different, the sensors go in and out one by one, not all totally off at the same time like this problem.

This is a bug, not sure what's causing it though.

**Comment by VA3WK** [comment]
Just tried Inav 2.0.rc1 on a matek F405-wing and still the same problem i had hoped they would have fixed it but no luck.

**Comment by kd2eat** [comment]
Ya this one is driving me nuts, too.  I may go onto github and do some "diffs" between 1.9.0 and 1.9.1 to see if I see what they wiggled.   Thanks for the heads-up on the 2.0.rc1.

**Comment by fiam** [comment]
I've spotted a couple of places in the smartport driver that could be problematic. I'll post some binaries here to make it easier. Which targets would you guys need to test?

**Comment by kd2eat** [comment]
Alberto, I'm running OMNIBUSF4PRO_LEDSTRIPM5.  I'd be happy to test a build for you.

Mike

**Comment by fiam** [comment]
@kd2eat Please, use the hex attached to this message. @VA3WK You mentioned you have a MATEK F405-WING so I also added a build for you just in case.



[inav_2.0.0_MATEKF405SE_FIX_3282.hex.zip](https://github.com/iNavFlight/inav/files/2142038/inav_2.0.0_MATEKF405SE_FIX_3282.hex.zip)
[inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282.hex.zip](https://github.com/iNavFlight/inav/files/2142039/inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282.hex.zip)

**Comment by VA3WK** [comment]
ok thanks i will try it and let you know.

**Comment by david-ng-hk** [comment]
I am on iNave 1.9.1 + matek f405 wing + R9 slim plus (upgraded fw to non-eu v180329)
I also try R9 min, same problem.

test at home, I put the plane near the window, it got 9 satellite, the temperature is about 30 degree c.
I can see all 18 sensor on my x9d plus, rssi is 100
after 6 minute, I get it back to the air con room 25 degree c, the gps sensor lost.
10 min pass, "inactivity alarm"
26 min, I put it back to the window, gps found again.
go do sth, 43 min pass, and now all sensor in the telemetry screen lost (leaving only first 2 rssi and rxbat)

I am not sure this is problem or not.
I recently try to get the gps show on the map, so I use opentx 2.2.1, enable smart port mirror in serial port  x9d+ battery bay.
I then connect the x9d serial port tx to a smart port inverter (IN), then (OUT) to bluetooth hc-06 rx (57600 baud rate)
I then use EZ-GUI, and in android cat log, search keyword: frsky
I can see many decode frsky crc error.

according to this https://www.jochen-scheib.de/understanding-the-frsky-smartport-protocol/
the telemetry frame is 10 Byte.
and in the cat log, the crc error shows the frame only contain 2 Byte like 7E 16 or 7E B7 or 7E 39 or 7E xx  always start with 7E
the correct frame show on cat log are like 10 7E 1B ,   they are start with 10

after the telemetry sensor gone, I go back to the cat log, only the rssi and rx bat is parser correctly.
other are all 2 Byte crc checksum error like before.

will test @fiam build now, report back later.

**Comment by VA3WK** [comment]
@fiam sorry to report but it failed after 19 min , again all telemetry gone except A2,rssi and rxbat. i think these come from the receiver directly.

**Comment by fiam** [comment]
@VA3WK Thanks for testing it. I’ll take another look at the code and see if I can spot anything else.

**Comment by david-ng-hk** [comment]
I am still testing, so far so good, plane near window, 30 degree c.
x9d inside air con, 25 degree c.
btw, I can not change the plane to "flying wing" using @fiam 's build, no matter what I change, it always show quadcopter.

**Comment by david-ng-hk** [comment]
result, all sensor lost after about 30min. only showing rssi and rxbat.

**Comment by fiam** [comment]
@kd2eat @VA3WK @davidngrc I've made another build with a few more changes. This time I haven't been so optimistic and I've added some debug info, so if it fails it will help us see exactly where.

Once the FC starts, go to the sensors tab and check the debug graph (you might need to enable it). Debug 0, Debug 1 and Debug 2 should be all increasing at least once a second. Once the telemetry stops working, please check back the debug graph and see which Debug values have stopped increasing. Thanks!

[inav_2.0.0_MATEKF405SE_FIX_3282_2.hex.zip](https://github.com/iNavFlight/inav/files/2142398/inav_2.0.0_MATEKF405SE_FIX_3282_2.hex.zip)
[inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_2.hex.zip](https://github.com/iNavFlight/inav/files/2142399/inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_2.hex.zip)

**Comment by VA3WK** [comment]
Ok will do

**Comment by kd2eat** [comment]
Wow, thanks for all the builds.  If someone hasn't reported back before I get to it, I'll try it this evening.

**Comment by VA3WK** [comment]
@fiam  Ok i flashed the file result: i get no telemetry on the radio at all (except the usually 3) i enabled debug in the sensor tab and i only see debug 0 increasing. if i open the debug graph its empty. What am i doing wrong?

**Comment by fiam** [comment]
@VA3WK Probably my fault. I don't have a setup with SmartPort here, so I can't test these builds. I've relaxed some checks and made a new one. Please, give it a try when you have time.

[inav_2.0.0_MATEKF405SE_FIX_3282_3.hex.zip](https://github.com/iNavFlight/inav/files/2142708/inav_2.0.0_MATEKF405SE_FIX_3282_3.hex.zip)
[inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_3.hex.zip](https://github.com/iNavFlight/inav/files/2142709/inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_3.hex.zip)

**Comment by VA3WK** [comment]
ok no problem

**Comment by VA3WK** [comment]
ok result : telemetry stopped working , debug 0 is still counting , debug 1 + 2 stopped. How can i activate the "open debug trace" so that it shows something ?

**Comment by VA3WK** [comment]
BTW. all three sensors ( baro, gyro, accel) are still active.

**Comment by VA3WK** [comment]
@fiam  Ok this is weird i forgot to turn  the unit off after it stopped the telemetry and when i got back to it after about 20min the telemetry was working again but at a very slow refresh rate actually so slow that opentx reported sensor loss. Random sensors would time out and the next time around they would read again. Debug 1 and 2 also counted very slowly.

**Comment by VA3WK** [comment]
@fiam now it stopped again. now also debug 0 counts very slowly like 2 counts the second , debug 1 and 2 stopped again. i don't know if these observations are of any help or if they confuse the issue more.

**Comment by teckel12** [comment]
@fiam BTW, at least with 1.9.1 I was able to reproduce S.Port telemetry failing after 30+ minutes.  I've only been able to duplicate this on the bench, as none of my quads can fly anywhere near 30 minutes.  But, I did duplicate the issue.

**Comment by david-ng-hk** [comment]
@VA3WK  @fiam   I encounter the same thing last weekend on the bench. after 30 min, telemetry stop. then wait for a while. I am not sure how long, but at least 20 min, telemetry will come back again.
I thought it was the R9M, R9 slim and R9 mini problem...

**Comment by fiam** [comment]
@VA3WK That's valuable information. Debug[0] was set up to increase whenever a telemetry request from the RX was received, debug[1] wether the driver decided it was time to try to service a request and debug[2] whenever a sensor frame was sent from FC to RX. If only debug[1] and debug[2] stopped, it means there's a bug between the point where the driver gets the request and when it decides to service it.

Please, give these new builds a try.

[inav_2.0.0_MATEKF405SE_FIX_3282_4.hex.zip](https://github.com/iNavFlight/inav/files/2144466/inav_2.0.0_MATEKF405SE_FIX_3282_4.hex.zip)
[inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_4.hex.zip](https://github.com/iNavFlight/inav/files/2144467/inav_2.0.0_OMNIBUSF4PRO_LEDSTRIPM5_FIX_3282_4.hex.zip)

**Comment by davidngrc** [comment]
@fiam I only get first 2 telemetry in this build,   debug 0 always go up (about 1 second +1), debug 1&2 keep at 0.

1) btw, why can't I change to flying wing in your build?
2) I refresh your first zip, the telemetry came back. (and get sensor lose in about 3 min)
3) I then refresh the inav_2.0.0-rc1_MATEKF405SE.hex   I could not change to flying wing either...

**Comment by david-ng-hk** [comment]
@fiam  I only get first 2 telemetry in this build inav_2.0.0_MATEKF405SE_FIX_3282_4.hex.zip
debug 0 always go up (about 1 second +1), debug 1&2 keep at 0.

btw, why can't I change to flying wing in your build?
I refresh your first zip, the telemetry came back. (and get sensor lose in about 3 min)
I then refresh the inav_2.0.0-rc1_MATEKF405SE.hex I could not change to flying wing either...

**Comment by VA3WK** [comment]
I am back had to have a little sleep. flashed #4 and get no telemetry but debug 0 is counting up.

**Comment by kd2eat** [comment]
@VA3WK Nice job on all the testing!  Thanks from a fellow sufferer.  I had intended to do some testing last night, but some honey-do's chewed up my spare time.  I'm glad someone was able to do it for @fiam.

**Comment by david-ng-hk** [comment]
@fiam , is it possible make a special build base on v2.0 but just roll back the smart port telemetry to v1.9.0?

**Comment by david-ng-hk** [comment]
or... the matek F405-wing has a onboard Blackbox: MicroSD card slot which can store logs.
how about you make a build, write detail log to the sd card? 
(like function call with parameter value and inside the function call capture each line)
(I got 32G and 64G card here)
I am sure other tester here has the same setup, after compare the log, I think we (I meant you ^-^) can find the problem.

**Comment by VA3WK** [comment]
@fiam  did some more testing , reloaded the org hex file and noted all the values like cpu load , msp load etc. and waited till the telemetry quit . there were no changes in those values.

**Comment by VA3WK** [comment]
@fiam  another interesting finding: on the distribution build the telemetry will not come back as it did with your #3 build.

**Comment by david-ng-hk** [comment]
@fiam I just did another test on the inav_2.0.0-rc1_MATEKF405SE.hex
00:00:00 start test
00:35:00 lost all sensors except rssi and rxbat
01:11:00 all came back.

the result is not the same as @VA3WK

**Comment by david-ng-hk** [comment]
just compare the RC1 and RC2 code, only 1 line of GPS code was changed in the telemetry relate files.
so I guest no need to do the RC2 test.

**Comment by fiam** [comment]
No need to redo any tests. There are no changes in RC2 that could fix this.

**Comment by VA3WK** [comment]
@davidngrc  just let it run it will quit again. the timing of this varies greatly.

**Comment by david-ng-hk** [comment]
I was thinking use try and catch the error and found no such thing in C  😅

I saw many   *clearToSend   in the smartport.c file.
maybe there is a bug in some loop, and this value is always set to false for about x minute, so all sensor lost.

**Comment by VA3WK** [comment]
@fiam Is it possible that the inclusion of Fport in march has something to do with this ? The timing is about right .

**Comment by fiam** [comment]
@VA3WK It definitely has, since a lot of smartport.c was changed to accommodate for the shared telemetry code (FPort is kinda SBUS+S.Port in a single stream).

**Comment by davidngrc** [comment]
I modify some code, and testing for 1 hour without telemetry lost (outside, 36 degree c, in a shade)

note 1, the build I am testing is without Tmp2 sensor, because in my previous test, the Tmp2 sensor lost way before all sensor lost. I add back in this build, but haven't test yet.

note 2, please only test sbus+sport, not fport.

[inav_2.0.0RC2_david_1_MATEKF405SE.zip](https://github.com/iNavFlight/inav/files/2151488/inav_2.0.0RC2_david_1_MATEKF405SE.zip)
[inav_2.0.0RC2_david_1_OMNIBUSF4PRO_LEDSTRIPM5.zip](https://github.com/iNavFlight/inav/files/2151489/inav_2.0.0RC2_david_1_OMNIBUSF4PRO_LEDSTRIPM5.zip)

**Comment by david-ng-hk** [comment]
I modify some code, and testing for 1 hour without telemetry lost (outside, 36 degree c, in a shade)

note 1, the build I am testing is without Tmp2 sensor, because in my previous test, the Tmp2 sensor lost way before all sensor lost. I suggest you test the normal version first, if fail, then test the without Tmp2 sensor version.

note 2, please only test sbus+sport, not fport.

[inav_2.0.0RC2_david_1_without_tmp2_MATEKF405SE.zip](https://github.com/iNavFlight/inav/files/2151497/inav_2.0.0RC2_david_1_without_tmp2_MATEKF405SE.zip)
[inav_2.0.0RC2_david_1_without_tmp2_OMNIBUSF4PRO_LEDSTRIPM5.zip](https://github.com/iNavFlight/inav/files/2151498/inav_2.0.0RC2_david_1_without_tmp2_OMNIBUSF4PRO_LEDSTRIPM5.zip)

[inav_2.0.0RC2_david_1_MATEKF405SE.zip](https://github.com/iNavFlight/inav/files/2151499/inav_2.0.0RC2_david_1_MATEKF405SE.zip)
[inav_2.0.0RC2_david_1_OMNIBUSF4PRO_LEDSTRIPM5.zip](https://github.com/iNavFlight/inav/files/2151500/inav_2.0.0RC2_david_1_OMNIBUSF4PRO_LEDSTRIPM5.zip)

**Comment by VA3WK** [comment]
@fiam  yes i know what fport is ,its a nice idea but i think it did not catch on very much , its need pretty well new equipment. I know a lot of people who have X8R etc. receivers which won't work. i wonder if it possible to create a build without fport.

**Comment by VA3WK** [comment]
@davidngrc  i will test

**Comment by VA3WK** [comment]
@davidngrc  Regular one : 1hr and still running

**Comment by VA3WK** [comment]
@davidngrc  2hrs plus and no problem . so what did you do to it ?

**Comment by david-ng-hk** [comment]
Here is the file I modified, it is base on 2.0.0RC2.
My gold was, copy the code in v1.9.0 to 2.0.0RC2, and I found some variable might be overflow, and some variable might never run due to unknown miscalculation.

To anyone who knows the smart port or fport protocol, please compare the two file and help fix it in the real build, I only know very basic C.

[smartport.c_2.0.0RC2.zip](https://github.com/iNavFlight/inav/files/2152118/smartport.c.zip)

**Comment by VA3WK** [comment]
@fiam @davidngrc  I just set up a Omnibus F4 Pro and a XSR receiver with Fport and run it for 1:30 hr. with no problems at all. So i guess the problem is only wit Sport. I guess my choice now is buy new receivers which support Fport or use 1.9.0 on sport.

**Comment by david-ng-hk** [comment]
I had test my inav_2.0.0RC2_david_1_MATEKF405SE.zip for 3 hours without all sensor lost.
could u test it on Omnibus F4 as well? I assume u previously test on F405 Wing?

**Comment by VA3WK** [comment]
It needs a Omnibus F4 pro compiled version of yours i don't have.

**Comment by david-ng-hk** [comment]
I did make one, check above 
inav_2.0.0RC2_david_1_OMNIBUSF4PRO_LEDSTRIPM5.zip

**Comment by Fast-Guy** [comment]
Having this issue too. Using a Matek f405 wing and Inav 2.0 RC2. Will this be fixed in the next release? Or can I use **inav_2.0.0RC2_david_1_MATEKF405SE** now?

**Comment by VA3WK** [comment]
@Fast-Guy @davidngrc did not say if  it is safe to fly. Nobody else seems to be to interested to fix this. i guess Frsky telemetry is not mainstream.

**Comment by bbaldrickk** [comment]
This is a big problem for me as my antenna tracker uses smart port telemetry data and the first sensors that drop out for me all ways seem to be temp 2 then all gps related sensors. Can happen at any time even had it after 5 mins.

**Comment by Fast-Guy** [comment]
@bbaldrickk  temp 1and 2 are the first to drop out for me then GPS.

**Comment by teckel12** [comment]
This seems right up my alley... I'll do testing with the Tmp1 and Tmp2 sensors tonight to isolate the issue.

**Comment by teckel12** [comment]
Okay, it's not the fault of the Tmp1 and Tmp2 sensors. Since those sensors touch many things, I was thinking maybe there was an invalid result causing a failure. Not the case.

I created a build where I totally removed both the Tmp1 and Tmp2 sensors. I ran for a bit over 30 minutes and telemetry failed (seemingly all at once).

I'll try some other things, but just wanted to shift the focus from these two sensors.

**Comment by david-ng-hk** [comment]
@teckel12 I have upload my fixed file above(source included), but need more testing. (I test 3 hours without all sensor lost)

**Comment by teckel12** [comment]
@davidngrc Wasn't that fix just folding old smartport telemetry back in?  That won't work for me.

**Comment by david-ng-hk** [comment]
LOL, at least, it is a temp fix for people who need it😅

**Comment by teckel12** [comment]
I've never lost S.Port while flying, only on the bench, so I'm not sure it's even a problem in the real world.  The loss of F.Port, D-series telemetry, and other changes is just too much to throw it all out.  Looking to fix the problem instead.

**Comment by VA3WK** [comment]
@teckel12  I must disagree with you i have lost it twice while flying, that's how come i became aware of the problem.. I agree with you that it should be fixed and i will do anything i can do to help.

**Comment by teckel12** [comment]
@VA3WK I guess I'm coming from my perspective.  I've only been able to duplicate lost telemetry on the bench after 30 minutes or longer, while my quad only flies for maybe 8 minutes.  With lost telemetry I'd hit 3D hold, review my last telemetry from my transmitter, and bring it home.  Not that I'm trying to make it a non-issue, because it is, it's just not a serious problem (for me) that would cause me to revert to old telemetry code.

**Comment by bbaldrickk** [comment]
Temp 2 for me is dropping out at literaly any time then gps then after 20 to 30 mins everything goes I'm using f405 wing getting 30 mins plus flight time but can't use my tracker because of the data loss

**Comment by VA3WK** [comment]
@teckel12  As i stated before that you are lucky that it only quits after 30 min, with my testing on the bench its anywhere from 5 min to 30 min. for me it's a very serious issue as i can not trust the equipment. I have gone back to 1.9.0, i know its not perfect but it seems to work for what i want. I have tested Fport on 2.0 rc2 and it seems to work, so that will be my other option. I am still hoping that maybe somebody will commit to fix the problem  or in one of the updates it will happen by chance.

**Comment by VA3WK** [comment]
@teckel12   btw. i am flying wing with a much longer flight time than you with your quad. Inav has a very good reputation (up till now) for wing flyers. I would hate to see that change.

**Comment by bbaldrickk** [comment]
I thought s port would have been a lot more popular than it seems to be on inav. As it's so dominant in cleanflight/betaflight

**Comment by fiam** [comment]
Thanks for the feedback and tests, guys. It will be fixed before 2.0 is released, but no one has had time to do so yet.

**Comment by teckel12** [comment]
I'm still looking into it, but it's for sure NOT the fault of anything that the Tmp1 and Tmp2 sensors are accessing. It's possible that they drop first only because they haven't changed, not because there's a problem with anything they are doing.

Anyway, can't be the fault of Tmp1 or Tmp2 as I totally disabled them and telemetry still failed. More to look into...

**Comment by teckel12** [comment]
@bbaldrickk why do you think S.Port isn't popular with INAV? What isn't popular is a 30 minute flight, so very few experience an S.Port drop. And those that do have 30+ min flight times are typically running Crossfire.

**Comment by bbaldrickk** [comment]
@teckel12 I see a lot of people going down the frsky r9 rout like me for long range these days as the price point is so much better than crossfire and for me apart from this telemetry issue it's on par for sure

**Comment by VA3WK** [comment]
@teckel12  Please do not make your test of 30 min failure the norm you are ignoring several report of failure as short as 5 min.

**Comment by Fast-Guy** [comment]
As short as 9min for me.

**Comment by fiam** [comment]
Found an overflow in the Smartport driver that will prevent it from working with S.port (FPort works fine) when uptime goes over 35 minutes and and 47 seconds. Once that duration duplicates, it would work again for the same period. I'll post build for testing later.

**Comment by VA3WK** [comment]
@fiam Great work let me know if i can do anything ,still got the test setup's

**Comment by fiam** [comment]
@VA3WK I haven't had time to let it run for 35 minutes again (it's at 10 minutes now), but if you want to start giving it a try you might use this hex.

[inav_2.0.0_MATEKF405SE_FIX_3282.hex.zip](https://github.com/iNavFlight/inav/files/2173014/inav_2.0.0_MATEKF405SE_FIX_3282.hex.zip)

**Comment by VA3WK** [comment]
@fiam will test and let you know.

**Comment by fiam** [comment]
39 minutes and no sensors lost. I'm prepare a PR now, but I'll let it sit for some more time.

**Comment by VA3WK** [comment]
@fiam 25 min running NO problems

**Comment by VA3WK** [comment]
@fiam  over 1hr now NO PROBLEM

**Comment by fiam** [comment]
@VA3WK 10 minutes away from 2 hours here. Not a single sensor lost. We'll merge the fix as soon as someone tests it with FPort.

**Comment by VA3WK** [comment]
@fiam  give me a moment i will setup with fport and let you know

**Comment by kd2eat** [comment]
Alberto,

That's awesome!  I'll work on getting my FX-79 upgraded to 2.0 RC2. Once 
I confirm it's OK on that build, I'd love a copy of your fix built for 
OMNIBUSF4PRO_LEDSTRIPM5.  I expect to be doing some long flights next 
weekend, so it would be great to have the fix!  :-)

Thanks for the hard work!
Mike

**Comment by VA3WK** [comment]
@fiam Tested Fport on a matekF405SE-wing for 1hr 10min with no problem. Had a bit of a problem to get it to work again, had to for some reason flash the XSR receiver again.

**Comment by teckel12** [comment]
@VA3WK The only time I've experienced a failure in 5 minutes was due to heat.  This issue is unrelated as it's a 35 minute overflow.

**Comment by teckel12** [comment]
@fiam Good job on the overflow fix! I'll test it with S.Port and F.Port tomorrow.

**Comment by VA3WK** [comment]
@fiam I set up sport again and this time hooked up the gps , bluetooth. I found the gps not working it always goes to a default location.

**Comment by VA3WK** [comment]
@teckel12 Of course you are right.

**Comment by fiam** [comment]
@VA3WK I posted a build which used the fake GPS, so it would send the GPS related sensors anyway, just to make sure the fix worked with 19 sensors. The fix will be included in RC3.

**Comment by fiam** [comment]
Fixed in #3536

**Comment by callagga** [comment]
I've just gone to 3.4 but also setup ESC telemetry.  I'm getting the sensor loss warning on my Taranis every minute, and when I look at it, it should the VFAS/Current items that get square brackets around them, so I assume these are the culprits.  These the values I get from ESC monitoring right (set it up in Betaflight to use the ESC for these) so it's almost as if these ESC values don't get passed through the FC back to the Taranis as frequently so trigger the "sensor loss" warning.  Note I do get the values for these past down, so everything seems to be working fine, except for the regular "sensor loss" warning coming through. 

Question - Would my situation be covered by this item?   So then would hopefully be fixed in 3.4.1?
