### ISSUE TITLE
Omnibus Target Question..POssible RTH Issue

### ISSUE THREAD

**Issue by biomedchad** [iNavFlight/inav#3283]
hello,

i am using an official airbot omnibus f4prov3 i purchased from racedayquads.  i have been using the omnibusf4pro target and all is working well excpet rth.  rth will work when i am pointed at certain angle to the homepoint..any other time it dives left and blips from rth to angle.  i have changed multile gps modules and tried this with 1.9 and 1.91 with the 1.9,3 cnfigurator..here is a clip of the ship doing this..thanks

https://www.youtube.com/watch?v=nl9w2vJc92I&feature=youtu.be

**Comment by shellixyz** [comment]
You should check that the 3D representation of your model in the setup tab of the configurator is moving like in reality. Might be a board alignment issue. How is the board oriented in your plane ?
