### ISSUE TITLE
Improvement: Conditional display of GPS coordinates on OSD

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#3287]
On some cases having the GPS coordinates displayed on OSD is not desirable:
- because this takes space and obscures the view
- because we sometimes want to publish recordings, not showing where it has been done

On the other hand, if something goes wrong, being able to check the latest location could help finding the lost machine.

This could be addressed by defining additional OSD layout, automatically enabled e.g. by entering configured flight mode (like RTH) .
What do you think?

**Comment by wx4cb** [comment]
Good idea, however it could be nice to have it assigned to a switch on the transmitter, so that we can enable it when we want.
