### ISSUE TITLE
nav_rth_altitude variable type too small

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#33]
nav_rth_altitude variable is defined as UINT8, which is too small to accommodate practical altitude values in centimeters. Eg., a height value of 20m would be '2000cm', which obviously won't fit into an unsigned char. Changing the definition to UINT16 solves the problem.

**Comment by digitalentity** [comment]
Oops! I was thinking this viable would be in meters when I decided to use
uint8. After that I changed the units but never changed the data type.
Thanks, will fix this asap.

**Comment by digitalentity** [comment]
@csurf 
Fixed, please see 4ebc4a589b5aa697bb01f1ec4ac3b8f97d949403.
