### ISSUE TITLE
Follow-Me-Mode  wanted 

### ISSUE THREAD

**Issue by Seeelefant** [iNavFlight/inav#3310]
### If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.
No
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
MATEKF722
_Version of INAV used goes here_
1.9.1

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_
Yes

I think a Follow-Me-Mode is desirable, in other platforms it is already implemented.

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by DzikuVx** [comment]
Follow me is already possible with software like EZ-GUI or Mission Planner for INAV when _NAV GCS_ mode is enabled
