### ISSUE TITLE
Control deadzone appearing at bottom of Pitch and Roll channels with flying wing mixer

### ISSUE THREAD

**Issue by aubreyrjones** [iNavFlight/inav#3312]
### If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

I don't believe so. I've spent a long time checking radio and servo settings. I may be confused, but I think something's wrong.

### Board and Version
Matek 405-WING
INAV 1.9.1
INAV/MATEKF405SE 1.9.1 Apr 21 2018 / 13:46:07 (03a5c1922)

### Behavior

I have a standard-configuration, two-elevon flying wing **which apparently has poor control resolution in manual mode on the lower half of roll and pitch channels.** 

This is apparent on the bench. If I push forward on the pitch stick, the servos move halfway to their full physical extent as I hit the end of the stick travel (as expected); and if I wiggle the stick near the limit, the servos will wiggle (as expected). **But if I pull back on the stick, servo motion completes before stick motion completes. If I then wiggle around the lower limit, there is a large deadzone where no servo movement occurs. This is not expected.** This same behavior repeats on the roll channel, with the high limit (right roll) having good resolution, and the low limit (left roll) having a very large deadzone.

Near to the center of the stick, there is correct servo movement. The dead zone occurs in the lower 10-15% of the roll and pitch channels (and maybe others, but that's not demonstrated with this mixer).  Note that the defect seems independent in each channel, and even in composite tests shows up in the bottom of each channel separately from the position of any other channel.

I do not believe the servos are misconfigured. If I am at full deflection back, and wiggle roll near stick center, I get linear response from the servo for the rest of its range; and if I'm at full roll left, I can wiggle pitch to get linear servo response. Given that maximum ranges are correct and the motion is coordinated, with deadzone appearing identically across two logical channels and coordinated on two servos (with different ranges and reverses), the motion of the servos themselves seems properly configured.

I'm using Crossfire on a Taranis TX, all with latest firmware. According to the receivers tab the transmitter is sending 988µs to 2011µs, centered at 1500µs, for all channels. I have no expo, curves, or diff set in the transmitter--just linear channels. I see the expected wiggles in the receiver graph and readouts. I get identical behavior both with and without `rxrange` directives.

```
# diff

# version
# INAV/MATEKF405SE 1.9.1 Apr 21 2018 / 13:46:07 (03a5c1922)

# resources

# mixer
mixer FLYING_WING

# servo mix

# servo
servo 3 850 1850 1350 -100 -1 
servo 4 1150 1900 1500 100 -1 
servo 5 1000 1000 1500 100 -1 

# feature
feature -SOFTSERIAL
feature MOTOR_STOP
feature GPS
feature PWM_OUTPUT_ENABLE

# beeper

# map

# name
name Corina

# serial
serial 3 2 115200 38400 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1875 2100
aux 1 10 1 1900 2100

# adjrange

# rxrange
rxrange 0 988 2011
rxrange 1 988 2011
rxrange 2 988 2011
rxrange 3 988 2011

# master
set gyro_sync = ON
set acc_hardware = MPU6000
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set mid_rc = 1582
set serialrx_provider = CRSF
set min_throttle = 1215
set motor_pwm_rate = 50
set failsafe_procedure = DROP
set vbat_max_cell_voltage = 420
set battery_capacity = 5000
set battery_capacity_warning = 1250
set battery_capacity_critical = 500
set deadband = 1

# profile
profile 1

set rc_expo = 1
set rc_yaw_expo = 1
set manual_rc_expo = 1
set manual_rc_yaw_expo = 1

#
```

**Comment by digitalentity** [comment]
Can't reproduce using XSR S.Bus receiver and REVO board. Settings identical to listed except one servo `servo 5 1000 1000 1500 100 -1` - it has min and middle at the same value which is incorrect.

**Comment by aubreyrjones** [comment]
The setting which appears to create the deadband, both in v1.9.1 and `development`, is `mid_rc`. I had thought this affected only the stick midpoint of the throttle channel, but this effect appears in the servo channels.

Resetting `mid_rc` to 1500 yields expected servo behavior in `development` head build.
