### ISSUE TITLE
Delayed OSD

### ISSUE THREAD

**Issue by povlhp** [iNavFlight/inav#3316]
On Omnibus F4, I experience delayed OSD. This is with onboard OSD.
It is like everything is either average of the last 10s, or somewhat delayed.

After landing, speed goes up before dropping. Distance to home goes from 130 to 80m, vertical speed does not settle the first 10 seconds either.
https://youtu.be/j-Gj1-ygebg?t=20s

If vertical speed indicator is not instant, it kills the value of using it a bit.

**Comment by shellixyz** [comment]
Did you manage to fix this issue ? I just experienced the same thing on a new build. Looks like a 10 seconds delay. Unfortunately I don't have logs. The board doesn't have a dataflash chip or SD card slot. Could you post your config ?
