### ISSUE TITLE
G-tune in inav. 

### ISSUE THREAD

**Issue by Jimpa86** [iNavFlight/inav#332]
Have a spracing f3, running newest inav but can't find G-tune. I'm new to quadcopters and this is my first one.  How do I find it/enable it? 

Best regards

**Comment by DzikuVx** [comment]
G-tune is not available in INAV at the moment

**Comment by Jimpa86** [comment]
Ok, then I must have misunderstood. 
Reed these threads and thought it was there. 

https://github.com/iNavFlight/inav/blob/master/docs/Gtune.md

www.rcgroups.com/forums/showthread.php?t=2495732&page=85

**Comment by DzikuVx** [comment]
If you want you can run gtune in cleanflight and then depending on inav version convert on just copy pid values

**Comment by WaspFPV** [comment]
How about bringing back G-tune for F3 targets? I understand it was removed to save space on F1 targets?
I understand F1 targets are too limited to run all features together (if you want your telemetry you need to recompile for your target) but there should be plenty of space for everything on an F3

**Comment by DzikuVx** [comment]
@digitalentity what do you think?

**Comment by Linjieqiang** [comment]
I agree……But it looks hard.
