### ISSUE TITLE
Is there a screen offset setting for the OSD?

### ISSUE THREAD

**Issue by whakru** [iNavFlight/inav#3322]
matek f722
Is there a screen offset setting for the OSD?
As in betaflight: https://github.com/betaflight/betaflight/wiki/OSD-and-CMS-Adjusting-Screen
I have a menu that goes beyond the screen, which can be fixed by what comand?

**Comment by shellixyz** [comment]
There is not. Could you post a screenshot ?

**Comment by whakru** [comment]
Unfortunately at the moment I can not ..
I do not fit inscriptions in the menu on the width (Not all), on the right are cropped ..
And you can not see the menu title from above.
The modes of PAL NTSC do not change anything.
__
К сожалению в данный момент не могу..
У меня не умещаются надписи в меню по ширине (Не все), Справа обрезаются..
И сверху не видно заголовок меню..
Режимы PAL NTSC ничего не меняют.

**Comment by Tygrys-1** [comment]
There is osd_row_shiftdown

**Comment by whakru** [comment]
@Tygrys-1 
What values can he have?

**Comment by Tygrys-1** [comment]
I don't remember values, but when you type in cli:
get osd_row_shiftdown 
you should have the range or list of allowed values, it works for all variables that way.

On my display the topmost row is half visible, so I put gps coordinates there. They are not visible in the gogles, but they are present on the recording on different receiver.

**Comment by teckel12** [comment]
The ability to shift the data on the OSD down would be very helpful as I also have alignment issues.  Horizontal spacing/alignment would also be super beneficial.

Looking at the `osd_row_shiftdown` setting, it's referenced in the ocd header file, but seemingly never used.  I tried setting it to `1` (the only other setting allowed) and I didn't see any changes.  So not sure what if anything it does.

I think I'll look into this further, as it seems like it would be very useful to many people (probably especially us NTSC folks).

**Comment by fiam** [comment]
If anyone has time, I think the best solution would be implementing the same settings as BF. It will be easier for users too.

**Comment by whakru** [comment]
@fiam Yes, that's a good idea  ))

**Comment by teckel12** [comment]
Bad bot!  This is something that's on my list of things to do.

**Comment by teckel12** [comment]
Confirmed that `osd_row_shiftdown` is never used in 2.0 RC6.  Looks like it was started but never finished (or removed accidentally).  As the command already exists, maybe it should do something? 😉

**Comment by gmacfpv** [comment]
I really need this feature. Need to move my whole OSD down a bit.
