### ISSUE TITLE
Random disarm during FS with RTL on.

### ISSUE THREAD

**Issue by driesvandenbroecke** [iNavFlight/inav#3323]
### Board and Version
_Matek F405-OSD
_1.9.1

_INAV/MATEKF405OSD 1.9.1 Apr 21 2018 / 13:26:36 (03a5c1922)

Random disarm when I triggered RTL about 6.5km out. The plane dived fast to the fixed RTL height of 80 meters, which caused me to lose video and RF Signal. It came back at around 4 km, I still had bad image but I moved the sticks so it went from FS to RTL and then back to FS. I saw it was in FS flying home so I didn't touch anything anymore. I waited patiently until I saw for a very short moment the stats on the screen. My aircraft got disarmed by itself around 3.5 km from home/

video of the flight:  [https://youtu.be/fmgIClqqwgY](url)
dump: [https://pastebin.com/QmmiXJ5Q](url)

**Comment by Tygrys-1** [comment]
On weak radio signal there can be false recognition of disarm switch.
See #3248, #3118

**Comment by DzikuVx** [comment]
This issue is (or at least we very strongly belive so) will be fixed by INAV 2.0. Arming channel would have to go into "disarm" value for a period of time to trigger disarm
