### ISSUE TITLE
Navigation modes without baro

### ISSUE THREAD

**Issue by mattyfpv** [iNavFlight/inav#3329]
Hi, on my LR quade I have a FC without barometer, but connected to a GPS. Seems that without a barometer I can't activate things like RTH, altitute hold etc. I don't understand why with my wing I can use those without the baro, but with the quad Inav complains about the lack of the barometer. Is there a way to disable this check?

**Comment by DzikuVx** [comment]
It is only possible on airplanes. All multirotors require barometer since GPS altitude is not reliable enough
