### ISSUE TITLE
Consolidate FrSky and SmartPort telemetry and documentation

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#3340]
## Proposal

With INAV 2.0 and #3116  the FrSky and SmartPort telemetry have been unified to output the same telemetry data.  Well, almost the same, which is the reason for this proposal.

- `smartport_fuel_unit` should be renamed `frsky_fuel_unit` and FrSky D-Series telemetry should use the same logic to output FUEL as S.Port
- It appears the `frsky_unit` setting isn't used at all and should be removed

**Comment by teckel12** [comment]
The proposal has been rewritten after going through the code in detail and making documentation changes (which I'll submit in a PR shortly).

**Comment by teckel12** [comment]
#3712

**Comment by teckel12** [comment]
#3713

**Comment by digitalentity** [comment]
@teckel12 you propose to merge both to 2.0?

**Comment by teckel12** [comment]
#3712 for sure #3713 is kind of finishing off something that was missed in a previous 2.0 RC.

Only only hesitation on #3713 is that I don't have D-Series to test.  But it's code mostly just pulled from S.Port telemetry so there's little that could go wrong.

**Comment by digitalentity** [comment]
Ack
