### ISSUE TITLE
INAV 2.0 disarm on low RSSI

### ISSUE THREAD

**Issue by driesvandenbroecke** [iNavFlight/inav#3343]
### Board and Version
_MATEK F405-OSD
_2.0

# version
# INAV/MATEKF405OSD 2.0.0 Jun  6 2018 / 18:03:47 (f7c2824f)
_
### Behavior
Also a random disarm using 2.0 with openlrs on low rssi

[youtube link to the video]https://www.youtube.com/watch?v=nbJEz2IkpHw(url)

**Comment by fiam** [comment]
@driesvandenbroecke Could you post your config dump? Do you have a blackbox log by any chance?

**Comment by DzikuVx** [comment]
See here: https://youtu.be/nbJEz2IkpHw?t=31s

First model yanks to the right and only then disarms. I very strongly believe that this is due to receiver configuration/dehavior. It just seted arming channel is disarm value and done

**Comment by Artyum** [comment]
I also experienced disarm during flight with lost of controls. I wonder, if in this case it was rx cause then it must generate wrong signals for over 0.5 sec for default inav configuration. If yes then maybe 0.5 sec is too low threshold.
