### ISSUE TITLE
two separate Omnibus F4 Pro's, same issue displaying battery voltage in OSD

### ISSUE THREAD

**Issue by Hyperious** [iNavFlight/inav#3345]
I have 2 Omnubus F4 Pro boards that as far as I can tell are from different batches completely. One I got from Banggood and another from Amazon, yet they still have the same problem in iNav 1.9.1 - the OSD shows 0v even with battery voltage monitoring turned on and running. Oddly enough, I know these boards are working fine since when I roll back to 1.7.x the battery voltage is being displayed just fine in OSD.

I attached the dumps from the planes I have the boards in - a Nano Talon I have for long range, and a Fury Wing I have for aerobatics. No idea why this is happening - current monitoring seems to be unaffected as I get accurate amp draw and amperage used readings just fine.

Any help would be awesome, as I want to get my nano talon working on 1.9.1 ASAP to use the new waypoint features. Thanks!

[nanotalondump.txt](https://github.com/iNavFlight/inav/files/2086619/nanotalondump.txt)
[furywingdump.txt](https://github.com/iNavFlight/inav/files/2086620/furywingdump.txt)

**Comment by shellixyz** [comment]
In both of your config dumps you have `vbat_scale` set to 0. Start with the default value (1100) you should get a reading close to reality then calibrate the voltage to get an exact value. Increasing it increases the voltage reading.

**Comment by Hyperious** [comment]
yup, that was it, now I feel dumb. lol
