### ISSUE TITLE
Failsave during mission.

### ISSUE THREAD

**Issue by Tygrys-1** [iNavFlight/inav#3354]
INav 1.9.1

If the plane is controlled by the RC transmitter and looses RC signal it activates RTH. It is configured to do so and it is ok.
But if the plane is doing an automatic waypoint mission and fly out of the RC range this behavior may be inconvinient, as it breaks the mission. But at that time the plane is driven by the autopilot, not the RC transmitter - so existance of the RC link is not critical. 
Can the extra setting for the RC failsave behavior during the active WP mission be added?

**Comment by DzikuVx** [comment]
Yes, we have a tickets for it: #976 and #1742
As it's a duplicate, I'm closing this one. Thanks
