### ISSUE TITLE
Explicit mag_hardware is ignored if selected chip is not available

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#336]
If selected compass chip is not present, firmware will fallback to auto-detect any other chip which is not safe.

Imagine having a HMC5883 onboard and close to sources on interference (battery, buzzer) and AK8975 on the GPS module (selected explicitly using mag_hardware). 
If external compass fails for some reason INAV will still detect onboard one and will engage RTH/WP. But using an onboard compass might result in fly-away in described case!

**Comment by krzysztofmatula** [comment]
I agree. Additionally the two mags may require different calibration and may have different orientation!

**Comment by WaspFPV** [comment]
this should prevent the onboard mag from being used: https://github.com/iNavFlight/inav/pull/348
