### ISSUE TITLE
F405 OSD+STD LED Strip dont work

### ISSUE THREAD

**Issue by HJOGermany** [iNavFlight/inav#3373]
Hello,
i have got problems with two Versions of Matek F405 Boards.
LED Strips doesn´t run with INAV. Matek can´t help really good.
If i flash BF the LED Strip works.

Here is my diff of the new flashed Test Board.
Must I remap something on the STD Board?
What must i do with the OSD Board?

Best regards from Gemany
HJO

**Comment by Tygrys-1** [comment]
http://www.mateksys.com/?portfolio=f405-std#tab-id-6

**Comment by HJOGermany** [comment]
Yes I know this pages.
I use this solderpads but it doesn't work.
Not the OSD and not the STD

**Comment by Tygrys-1** [comment]
According to the INAV sources the LED strip should be connected to the PA15 -> S5 pad.
The PB6/LED connector is for BetaFlight.

**Comment by HJOGermany** [comment]
Thank you all for help.
Problem was a LED Strip which has good and bad Days.
Use a new one an now my Wing has lights
S

**Comment by sneiman** [comment]
I continue to struggle with a similar issue. Matek F405 Mini. Diatone SW321. Connected to S5, config enables RGB led stip. Resistor bridge in place. Simple color config for the 3 lights at addresses 0, 1, 2. Nothing - no lights, no warmth, no smell, no nothing. 3rd SW321. Any help appreciated

**Comment by DangerD256** [comment]
Same shit, F405 ctr, connected to S5, but it doesn't works...

**Comment by sneiman** [comment]
I finally had success .. by trying 3 different strips. They were all theoretically identical – but 2 didn’t work, or worked intermittently with series diode to get voltage drop. Third one worked as it should – no diode needed.

 

s

**Comment by gsixx8** [comment]
@sneiman was your success having the strip wired to the LED pad on the FC or the S5 pad on the FC?

**Comment by sneiman** [comment]
s5. dont forget to remove the resistor next to it and bridge those 2 pads together

Sent from mobile device - sorry for typos and brevity.

This entire message is confidential. If it isn't intended for you, you may not use it - so please throw it away and forget about it.

On May 13, 2019, at 2:58 PM, Gerel McIntosh <notifications@github.com<mailto:notifications@github.com>> wrote:


@sneiman<https://github.com/sneiman> was your success having the strip wired to the LED pad on the FC or the S5 pad on the FC?
