### ISSUE TITLE
Integer implementation of PID controllers on F1 targets

### ISSUE THREAD

**Issue by WaspFPV** [iNavFlight/inav#342]
for F1 users wishing faster looptimes, is it possible to replace fp_pid by a special version of MWrewrite? It runs faster, and also uses less flash memory than luxfloat. (I started rewriting fp_pid t use more integers andless float, so far that saved enough flash to run frsky and smart port together, and it saves about 60 micros)
Also, it would be nice to have an optional error seeking Dterm for sharper response, like in betaflight and older cleanflight versions.

**Comment by digitalentity** [comment]
I don't want to introduce another PID controller, however implementing an integer version of FP-PID might be a good idea

**Comment by digitalentity** [comment]
Superceded by #412
