### ISSUE TITLE
Quad in ALTHOLD mode jumps when hitting the ground

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#3424]
This is a very old and very annoying issue. If a quad is in ALTHOLD mode and hits the ground hard enough it jumps for several meters before settling down. 

Cause of the issue is likely accelerometer saturating with rapid deceleration from impact.

No workaround exists at the moment.

**Comment by giacomo892** [comment]
I've noticed that too. We haven't a limit in ACC weight during altitude estimation. 

This causes also altitude estimate going mad when a quad "soft" crash on ground. I've seen cases when estiamation drifted about +-100m until baro fusion brought it back to correct value.

**Comment by wx4cb** [comment]
maybe if the last altitude was <= 1ft you could just ignore massive deceleration values?

**Comment by teckel12** [comment]
@wx4cb That would only work if landing in the same location and the barometer is exactly the same as when launching (which is not typically the case).  I almost always show +/- 5 feet when landing in the exact same spot as launch.

**Comment by fluffy** [comment]
When thinking about this, have a read of the "Barometer Ground Effect Compensation" section at https://docs.px4.io/v1.10/en/advanced_config/tuning_the_ecl_ekf.html 

That might be part of what is causing the issues here.
