### ISSUE TITLE
Alignment for AK8975, AK8963 (and MPU9250, which includes an AK8963) seems incorrect

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav#3434]
Update: Turns out this somewhat works right now because we're ignoring the Z axis of the magnetometer, so the correct X/Y alignment can be achieve by flipping the mag alignment (which results in inverted Z axis, but works). Postponing to 2.1.

Reported in comments for  #3413, #3288 and #3398

**Comment by zipray** [comment]
Fiam thank you very much. I have updated the v2.0 RC4 firmware, but nothing seems to have changed.At least in my F3 EVO.In loiter mode the route is asymptotic and getting further and further away.
https://github.com/iNavFlight/inav/issues/3391#issuecomment-404734742
