### ISSUE TITLE
F3 EVO default compass direction of MPU9250 is not correct

### ISSUE THREAD

**Issue by zipray** [iNavFlight/inav#3438]
F3 EVO FC default compass direction of MPU9250 is not correct in Inav 1.9, and it must be set to flip90CW.And the accelerometer, the gyro is not needed

**Comment by fiam** [comment]
@zipray Give this hex a try, please. Let me know if it works properly with the default mag alignment. I did fix a big in the driver and it seems to me the default orientation should now be CW_270 (without flip), but I don't have this board to test it.

[inav_2.0.0_SPRACINGF3EVO_TEST_3434.hex.zip](https://github.com/iNavFlight/inav/files/2134256/inav_2.0.0_SPRACINGF3EVO_TEST_3434.hex.zip)

**Comment by fiam** [comment]
Probably related to #3434

**Comment by zipray** [comment]
Thank you very much for your reply.I updated the firmware.Although it can show the right direction in the GUI configuration, it cannot do a complete accelerometer calibration.Step 3 of the accelerometer calibration will show that step 4 has been completed, and the calibration of step 3 cannot be completed regardless of positioning.In addition, I've updated firmware 2.0 RC2, which can be calibrated, but like version 1.9.1, you must configure the compass as CW90flip.The compass deviation in flight becomes unstable.

**Comment by fiam** [comment]
@zipray the problem is that I suspect not even CW90flip is correct, because the Z axis will be flipped

**Comment by fiam** [comment]
Fixed in #3612, we’ll fix the Z axis in 2.1
