### ISSUE TITLE
osd_crosshairs_style and sidebar_scroll feedback

### ISSUE THREAD

**Issue by Artyum** [iNavFlight/inav#3449]
As for the experimental settings:
set osd_crosshairs_style = AIRCRAFT
set osd_left_sidebar_scroll = GROUND_SPEED
set osd_right_sidebar_scroll = ALTITUDE
For me an aircraft pilot these are nice features. Few remarks: The aircraft crosshair style covers the horizon line that there is two dots on left side and one on right side (screen attached). Would be nice to make it symmetrical :) 
![osd_crosshairs_style](https://user-images.githubusercontent.com/10715547/41877481-b277e43a-78d1-11e8-9492-c36a2764e577.jpg)
The sidebar scrool seems to work but is not very immersive. I think that at some speed ratio due to low vertical res it's hard to distinguish if it's going up or down. Despite that I will leave it enabled.

**Comment by teckel12** [comment]
:+1:

**Comment by fiam** [comment]
@Artyum Note that you can use `osd_sidebar_scroll_arrows` to show the scrolling direction. I'm adding these to the configurator for 2.0, they should be pretty easy with the new settings  MSP API.

**Comment by fiam** [comment]
Fixed by https://github.com/iNavFlight/inav-configurator/pull/533
