### ISSUE TITLE
Issues to be sorted out before 2.0 final release

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#3453]
- [x] 1. Name appears in diff even when it has its default value. 

- [x]  Beeper doesn't sound when trimming level via rc_controls

![image](https://user-images.githubusercontent.com/20860004/41905985-0535e80a-793d-11e8-815b-30b25983853a.png)

**Comment by Artyum** [comment]
Configurator 2.0.0.RC1 Some minor things:
1) In GUI OSD the "Sag Compensated Battery Cell Voltage" and "Fw Min Throttle Down Pitch Angle" control the same icon in GUI.
2) In Mixers panel for Airplane, the servo mixers for flaps are added despite "Has flaps" is disabled.

**Comment by DzikuVx** [comment]
@Artyum please create new tickets in Configurator project for your findings. This way we can keep up what goes where. And one ticket for one problem please. Thanks
