### ISSUE TITLE
Request support for Betaflight F7

### ISSUE THREAD

**Issue by TheRealOrange** [iNavFlight/inav#3463]
This is a feature request. I would like to use the iNav firmware on the relatively new Betaflight F7 board. I know some other boards also have dual gyroscope, but I purchased this before finding out about iNav. If anyone else has custom compiled some firmware, please tell me how. I realise Betaflight is different from iNav and I already purchased the Betaflight board but I am interested in GPS features such as return to home. The supported boards page stated that most F7 boards were supported. I am sorry for the trouble and thank you.

**Comment by CZEMacLeod** [comment]
I made a similar 'mistake' by getting an SPRacingF7 Dual and assuming there would be inav support as many F7 boards are supported and the previous SPRacing boards were supported.
I have been trying to understand the differences between targets for iNav and Betaflight/CleanFlight which do have support for the board, but haven't got very far yet.
The GPS return to home is also the main feature I am looking for.

**Comment by ephemeridis** [comment]
I believe it may be possible to look at the timer channels to motor assigned in the betaflight target file and then look at iNav target file syntax and create a custom target file that dictates the timers specific to the motor outputs.

I haven't tried it yet but I believe betaflight also recently added a rudimentary return to home feature.

**Comment by mchaos** [comment]
I too would like to see betaflightF7 supported...
