### ISSUE TITLE
# sd_info SD card: Startup failed

### ISSUE THREAD

**Issue by spaelectronics** [iNavFlight/inav#3464]
### Board and Version
OMNIBUS F4 Pro v2.1 - [Click Here](https://us.banggood.com/Wholesale-Warehouse-BF3_1_5-Omnibus-F4-V2-Flight-Controller-STM32-F405-MCU-Integrated-OSD-Built-in-5V-BEC-Current-Meter-wp-Usa-1143258.html)
INAV Version 2.0.0 RC1

# version
# INAV/OMNIBUSF4PRO 2.0.0 Jun 26 2018 / 12:13:43 (5db1e1a45)

### Behavior
When I insert SD Card, and goto Blackbox in the Configurator, it displays "Fatal Error. Reboot to retry."
When I run sd_info in CLI, i get: `# sd_info SD card: Startup failed`

I have tried 5 different SD Cards. 
Yes, I have tried formatting them to FAT32 using "SD Card Formatter" software.

Here's the one I purchased specifically to try and solve this problem:
https://www.amazon.com/gp/product/B073K14CVB/

#### CLI Dump
https://pastebin.com/xBGYSjwT

**Comment by giacomo892** [comment]
Cannot reproduce. My SD Card works as expected.

**Comment by shellixyz** [comment]
I also had issues with SD cards on an OMNIBUSF4PRO board. I could only make one work, a small 128MB one. We took a look at the code but it seems related to this particular board since the same SD cards are working fine on other F4 based boards.

**Comment by spaelectronics** [comment]
So there is no way to get it working? I can't keep buying SD cards just to keep trying, lol.

I have one card that "almost works", but it gets stuck on "initializing".

I wonder if the board is causing interference on the SD card lines?

Or maybe it's not getting enough power to run the SD card properly? (Maybe a diode causing voltage drop?)

Here's a question, does the board, or the firmware, handle the pullup/pulldown on the data lines? (If board, maybe it's missing pull up/down resistors?)

Just trying to think of possibilities.

**Comment by shellixyz** [comment]
> So there is no way to get it working?

I didn't manage to get it working. None of the 8/16GB I tried were working and changing the clock freq didn't work either.

> I wonder if the board is causing interference on the SD card lines? Or maybe it's not getting enough power to run the SD card properly? (Maybe a diode causing voltage drop?)

No sure. I guess it could be a power issue. For this the pull-ups of the MCU should be good enough. I don't know how it is wired exactly on the OMBF4PRO boards.
