### ISSUE TITLE
2.0.0-RC1 RC channels missing from the Mixer

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav#3467]
2.0.0-RC1
SBUS 16 ch. RX
Only RC channels 5 to 8 are available in the mixer.
Trims are setup on channels 8 and 9 for "live" trimming in previous iNav versions.
How to forward these channels to servos in the new mixer?

![untitled](https://user-images.githubusercontent.com/25912739/42001578-0f82231a-7a6d-11e8-8b48-ae8770fb8fb7.jpg)

**Comment by DzikuVx** [comment]
@Arvycka please move this issue to Configurator project and close this one. Thanks

**Comment by Arvycka** [comment]
Moved to Configurator project 
https://github.com/iNavFlight/inav-configurator/issues/501
