### ISSUE TITLE
2.0-RC1, MATEKF405SE can not change mixer, always show quadcopter.

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3471]
I am using fc mateksys f405-wing
iNav configurator v1.9.3, in configuration tab, mixer, when I change to flying wing, saved, it will go back to the default quadcopter. I try other mixer, also don't work, it always show quadcopter.
I refresh back to iNav 1.9.1, and saved as flying wing, it work.

**Comment by Tygrys-1** [comment]
In such a casa I'll reset configuration to defaults. There mighy be changes of variables allocations in the flash memory and strange things may happen when using a new version with the old data.

**Comment by david-ng-hk** [comment]
already use “full chip erase” to flash, so it is not relate to old data.

**Comment by shellixyz** [comment]
Only use configurator 2.0 with FW 2.0. The rule is to always use configurator version >= FW version.

**Comment by david-ng-hk** [comment]
sorry for this stupid question, I don't see the 2.0 configurator on google chrome store.
how do I use the 2.0 configurator?

**Comment by Artyum** [comment]
Did you DuckDuckGo? https://github.com/iNavFlight/inav-configurator/releases :)

**Comment by david-ng-hk** [comment]
it work, I had no idea the configurator has a exe version.
thank you.

**Comment by david-ng-hk** [comment]
maybe in the real v2.0 configurator, show a big alarm box, alert the user, they are using v3.0 fw? which might have compatibility problem?

**Comment by shellixyz** [comment]
I think it is planned :+1:

**Comment by DzikuVx** [comment]
Configurator 2.0 is required to work with 2.0 firmware!
