### ISSUE TITLE
2.0.RC1 variables on OSD

### ISSUE THREAD

**Issue by Artyum** [iNavFlight/inav#3472]
Tested "on ground"
Config: gps_min_sats = 5
1. Wait for GPS Fix (5 sats)
Enabling NavCruise mode while disarmed in OSD shows "AIR" (this was NavCruise + AltHold)
2. Arm with a switch
Result: In OSD "Armed" screen the LAT sometimes shows 0.000000, LON is ok.
Enabling NavCruise mode while armed in OSD shows "AH" (NavCruise + AltHold)

**Comment by tgreer** [comment]
This is expected I think? You can't switch to a Nav mode whilst on the ground/disarmed.

**Comment by shellixyz** [comment]
Yes 1 is normal. For 2 I don't know what is going on with the latitude but for navcruise it is also normal it won't engage unless the FC gets a valid heading (speed > 300cm/s).
