### ISSUE TITLE
Neo 8 GPS no data transmission

### ISSUE THREAD

**Issue by chris-hemmings** [iNavFlight/inav#3489]
I have a neo 8m that when connected to u-center, outputs data fine, and locks on, I then connect it to my betaflight f4 flight controller using UART3, GPS Baud rate set to 115200 OR 38400, GPS setup in configuration. And i dont get any data transmitted in the GPS tab.

The only way it will work in ucentre, is if the baud rate is 38400, any other baud rate and it wont work.
I have RX-TX and TX -RX correctly. all tested using u-center.

Uart6 is set to sbus,

This was working before, but for some reason now its not.

Ive also tried to flash the latest betaflight f4 config using inav, but for some reason, my board just wont flash, Ive been out of the scene for about 6 months, and cannot for the life of me get this to work.

Any ideas?

**Comment by Gregmaan** [comment]
I have a different problem what may be related to this:
Min GPS Sat set to 7
With up to 10 sats I get no LAT/Lon values in Configurator or LUA telemetry.
Arming works but I did not get a home point.
Is there a hard coded GPS quality filter (HDOP, PDOP)?
Launching witout homepoint is dangerous...
That could be also bad if we want to rescue the plane/Copter with bad GPS quality...

**Comment by shellixyz** [comment]
@wookie666 Try to reset your module configurations to defaults
@Gregmaan If you got `nav_extra_arming_safety` set to `OFF` it is normal. You can always arm but if no GPS fix then HOME is not set.

**Comment by teckel12** [comment]
@Gregmaan After you get 7+ sats, from your transmitter do a `discover telemetry sensors`.  You may not be seeing LAT/LON in LuaTelemetry if the sensors don't exist, and they don't exist until there's a GPS lock.  See: https://github.com/iNavFlight/LuaTelemetry#from-transmitter for more information on setting up the telemetry sensors for LuaTelemetry.

**Comment by Gregmaan** [comment]
I checked all things again...
Maybe i did not see the home set on OSD at arming, sorry.
But there seems to be a problem with the lua script...
There is a hardcoded filter when HDOP is >2
Thanks

**Comment by chris-hemmings** [comment]
Thanks Shellie. I don't reset them last night using ucenter and it connected straight up. Weird because this GPS was working before and has sit still for 6 months

**Comment by teckel12** [comment]
@Gregmaan There's no hard-coded filter for a HDOP of >2 in Lua Telemetry.  It's not till the next release of Lua Telemetry that it will even know what the HDOP is.  What's making you think there's some hard-coded HDOP filter?

**Comment by Gregmaan** [comment]
@teckel12 When I connect the FC to the configurator I can see HDOP values. If the HDOP is >2 I get a warning on my RC ..Bad GPS and the Lat/lon is blinking(Or before first arm I see no GPS data). If the HDOP is <2 I got the message GPS good and I can see GPS lat/lon.

**Comment by teckel12** [comment]
Nope, LuaTelemetry 1.3.1 thinks GPS is good when INAV sends it information that it has a GPS lock, home lock, and at least 6 satellites. The next release of LuaTelemetry changes this to only look at the GPS fix, basically giving even more control to INAV to determine if there's a GPS lock or not.

If there's logic of GPS lock based on HDOP, it's in INAV. But, I know it's not a HDOP of 2.0 as I get a GPS fix at 4.0, if not higher (that's just the highest HDOP I remember).

We should end this here and finish the conversation in the LuaTelemetry issue.

**Comment by stronnag** [comment]
In iNav, GPS lock status is that reported by the GPS (PVT / nav solution).

**Comment by teckel12** [comment]
And INAV just passes that along via telemetry which LuaTelemetry reports as either a GPS lock or GPS lost.

Probably a coincidence it was right at 2.0 HDOP or maybe your GPS chip only reports a lock at that point. Either way, it's not some arbitrary condition that INAV/LuaTelemetry has set.
