### ISSUE TITLE
MAG shows up connected all the time when using NAZA GPS compass (mag_hardware = 4)

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#349]
When using it with an DJI naza gps and "mag_hardware = 4" the mag show that its connected all the time.

I can physically disconnect the GPS, and even after a reboot of FC it still shows that MAG is connected.

Can confirm issue on both 1.1 and 1.2. And on both Naza32 and spracingf3 with mag physically removed.

**Comment by digitalentity** [comment]
Yes, this bug is known. The problem is that mag is only detected on boot and GPS is detected after that so if using NAZA GPS we don't really know if GPS/MAG is connected at boot and MAG is assumed to be present.

**Comment by digitalentity** [comment]
With hardware failure detection in place we can actually address this bug

**Comment by digitalentity** [comment]
I figure this will be handled by hardware failure detection and unconnected compass will be shown as failing.

I'm buying myself a genuine DJI GPS unit to verify/test/improve support for DJI hardware.

**Comment by oleost** [comment]
@digitalentity Just tested with NAZA GPS.

Unplugging the GPS it will show up as GPS=UNAVAIABLE with red icon on configurator. Cloosing this one as this is fixed now.

EDIT: And the same with mag.

# status
System Uptime: 34 seconds
Voltage: 108 * 0.1V (3S battery - OK)
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=GPSMAG
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, SONAR=NONE, GPS=OK
Stack size: 2048, Stack address: 0x10002000
I2C Errors: 0, config size: 1806, max available config: 4096
System load: 4, cycle time: 2007, PID rate: 498, RX rate: 49, System rate: 9

# 

and then unplugged NAZA GPS:

# status
System Uptime: 69 seconds
Voltage: 109 * 0.1V (3S battery - OK)
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=GPSMAG
Sensor status: GYRO=OK, ACC=OK, MAG=FAILING, BARO=OK, SONAR=NONE, GPS=UNAVAILABLE
Stack size: 2048, Stack address: 0x10002000
I2C Errors: 0, config size: 1806, max available config: 4096
System load: 4, cycle time: 2011, PID rate: 497, RX rate: 49, System rate: 9

#

**Comment by digitalentity** [comment]
@oleost thanks for testing!
