### ISSUE TITLE
Request for remote gain adjustments via aux channel

### ISSUE THREAD

**Issue by Hyprmtr** [iNavFlight/inav#3499]
There’s been a few issues with users complaining about very unstable flight conditions with FW stability modes especially in windy conditions. Of course, many of us already know we need to tune accordingly to our environment and not assume a preset is going to make magic happen in all weather conditions. An idea I have that other autopilots use may be a welcoming addition. 

A simple aux channel on a pot to P, I, or D(FF) roll, pitch, or yaw(selectable) would allow a much more efficient tune without having to land, adjust, test, land, adjust, test,...

If this has been submitted in the past or, has been requested and not enough interest to pursue, please pardon. 

Thank you and good day.

**Comment by Arvycka** [comment]
You can already do that:
https://github.com/iNavFlight/inav/blob/master/docs/Inflight%20Adjustments.md
https://www.youtube.com/watch?v=NtkQ-bf9Ke8&t=347s

**Comment by shellixyz** [comment]
As previously stated it is already possible and a lot of new types of adjustments have been added in 2.0. You can also now see all the adjustable values in the OSD and see which one is being selected for adjustment (blinking). And also display the PID controllers outputs.

**Comment by taileron** [comment]
still trying for a tailsitter having 4 times lower PIDs when flying fast forward and being able to switch back inflight for landing - needs a direct control of the PIDs from an aux channel like a tpa factor to achieve a 20% factor or better a linear control of PIDs in percentage with a tx slider or tx mixer.
Currently the only bad quality workaround is using rate profiles in combination with different tpa rates.
