### ISSUE TITLE
Discussion - Convert AIR_MODE to a feature

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#350]
Continuation of #344.
As AIR_MODE is in general required to have better flight performance we should consider changing it to a feature that can be enabled and be always active. Might also rename to "LOW THROTTLE STABILITY". 
Thoughs?

**Comment by DzikuVx** [comment]
Personally I am against it. I find it useful to disable AIR MODE in some cases while in flight. I do it during landing preparations on my 600m quad.

**Comment by martinbudden** [comment]
I also like the ability to switch AIR_MODE on and off.

**Comment by oleost** [comment]
Maybe name change?

Since if it's not overriding motor stop,  then it's not the same flight
mode as the orginal airmode anymore.
13. jul. 2016 14.42 skrev "Martin Budden" notifications@github.com:

**Comment by digitalentity** [comment]
Maybe split it into two:
AIR MODE for better flight stability and IDLE UP for overriding MOTOR_STOP. What do you think?

**Comment by sppnk** [comment]
Personally, I dont have experience with iNav in multicopters, but for fixed wing, if AIRMODE  is a feature to improve flight, I guess it should be always active, and not configurable anyway.

**Comment by kronosol** [comment]
Airmode can cause crazy behavior of your quad if its enabled while landing, at least it´s not recommend. 
So you will need to disable it befor the quad touches the ground, i have airmode on the same switch as landing gear, so in general im safe.
Edit: The problems with airmode increase with high powered quads. Because the shock from the landing cause a short big answer from the controller and the high power of ESC/Motor cause the flip. I have a quad with a trust to weight ratio of 1/3 and can´t land with airmode.

**Comment by stronnag** [comment]
AIRMODE is already a feature in betaflight (3.0 at least). I always have the mode enabled with iNav, with no adverse results.

**Comment by csurf** [comment]
For FW, so-called "AIRMODE" (full-force PID corrections at low throttle) should be considered necessary functionality that's integrated into FC logic without having to enable it as a separate feature. 

FW aircraft need full PID corrections at _all times_, even when plane is disarmed. Throttle position should have no effect on the amount of PID corrections, except in the special case of TPA, where the user is consciously limiting PID correction at high throttle. However, at low or zero throttle (or even when disarmed), the servos should always correct with full force.  It shouldn't be a requirement to have the motor idling (i.e., overriding & disabling MOTOR_STOP), as there are many times when the pilot may wish to completely kill the motor & glide, yet still have the servos active to stabilize the plane.

The only time PID corrections should be forcibly disabled is when in PASSTHRU mode. This is  pretty much the standard way of doing it in other FC firmwares, but unfortunately it's currently broken in iNav...

**Comment by oleost** [comment]
If you want airmode on at all time simple assign it to an unused aux
channel and leave it activate all the time.

I really like to enable airmode same time as armed, so I gain won't grow
before I'm ready to takeoff.
1. jul. 2016 12.41 p.m. skrev "csurf" notifications@github.com:
