### ISSUE TITLE
Runcam Split 2 control doesn't work with Matek F405-WING

### ISSUE THREAD

**Issue by aidanassimokaitis** [iNavFlight/inav#3503]
Runcam Split 2 control doesn't work with Matek F405-WING.

**Comment by Redshifft** [comment]
Don't feel special, it does not work reliably with most of the other FC's either :)
pickup the USB PWM control module and control it through that - it does work reliably and you can cut off the usb part of it.

**Comment by aidanassimokaitis** [comment]
Thank you I feel relieved :)
