### ISSUE TITLE
V2.0.0 Aircraft diving in Cruise mode

### ISSUE THREAD

**Issue by renatobfa** [iNavFlight/inav#3506]
Its a Omnibus F4 Pro with INAV 2.0.0.

I've succesfuly flown my aircraft in V1.9.1 and in V2.0.0 with Angle + Altitude Mode + Heading Hold, and it worked fine in both versions....

But, in 2.0.0, when I tried to fly in CRUISE mode only (all other flight modes off), the plane kept diving like -2.0 m/s the whole time.

Anyone else had this problem?
![cruise](https://user-images.githubusercontent.com/32551670/42196457-6b00406a-7e54-11e8-97d6-188246926b00.jpg)

**Comment by teckel12** [comment]
I saw this when I upgraded without recalibration. Once I recalibrated, everything was stable. I suggest you recalibrate.  Kinda obvious, but I added it as an issue that should be mentioned when upgrading.

**Comment by renatobfa** [comment]
The first thing i did when I installed V2.0.0 was to calibrate it... So, i dont think thats the problem. Besides, the Angle + Altitude Mode + Heading Hold works fine in V2.0.0, so perhaps the problem is in Cruise mode or some other thing.

**Comment by giacomo892** [comment]
CRUISE mode (2D) doesn't control the altitude. The plane is forced into ANGLE mode so it should behave like ANGLE. Navigation also enable TURN ASSISTANT so it should be able to compensate when banking. 
Do you have a blackbox log?

**Comment by teckel12** [comment]
@renatobfa For me, before I calibrated, my AccZ was always showing it dropping at like 50 feet per second, even when on my bench.  I'd verify that AccZ is zero on the bench as it really sounds a lot like the issue I had.
