### ISSUE TITLE
V2.0.0 Battery voltage doens't show the decimal figure

### ISSUE THREAD

**Issue by renatobfa** [iNavFlight/inav#3507]
It's a Omnibus F4 Pro with INAV 2.0.0.

"Battery voltage" doens't show the decimal figure, it just says "11V" instead of "11.4V"

The "Battery Cell Voltage" works fine, it still shows 2 decimal figures like before, example: "3.83V".
![voltage](https://user-images.githubusercontent.com/32551670/42196361-f69855e6-7e53-11e8-85f6-2cbd39045b1c.jpg)

**Comment by shellixyz** [comment]
This issue has been fixed in RC2
