### ISSUE TITLE
V2.0.0 Scale "XX m" of Radar mode sometimes go crazy

### ISSUE THREAD

**Issue by renatobfa** [iNavFlight/inav#3508]
It's a Omnibus F4 Pro with INAV 2.0.0.

Radar mode, with "aircraft" in the middle and "home" moving, need some ajusting because the scale keeps changing from "320m" to "2.56 km", or "80 m" to "1.28 km" and the "home" icon apears just under the aircraft in those moments... it auto corrects after a few seconds and becames right again..

These 2 pictures below were taken a few seconds apart from each other, and they show the scale going from "320m" to "2.56 km" for a while, and then it comes back to "320 m" again
![radar_mode_scale](https://user-images.githubusercontent.com/32551670/42196305-a33aebf2-7e53-11e8-9f81-51a8d3a2da8f.jpg)

**Comment by fiam** [comment]
@renatobfa could you send me privately a video between 30s after and before the problem? Being able to see how the scale was changing before reaching that value would help to determine the best way to fix the bug.

**Comment by renatobfa** [comment]
@fiam , Hello friend! 

As you asked, i've sent to your email a clip soon before the Radar Mode Bugs occur... they happen 2 times in this clip, but the second time is very brief because I changed the OSD soon after the second time, but it is noticeble.

My guess is that the RADAR Scale goes crasy right when "home" is 90º to the LEFT or RIGHT in relation of the craft..... see for youself.

Keep up the good work. Thanks!

**Comment by fiam** [comment]
@renatobfa Thanks for the video. I've looked at it and I'll fix it as soon as possible.

**Comment by fiam** [comment]
Fixed in #3562
