### ISSUE TITLE
New feature request - Accelerometer on OSD

### ISSUE THREAD

**Issue by Artyum** [iNavFlight/inav#3511]
iNav 2.0 introduced lots of new OSD elements like RC Adjustable values or PID outputs. Could you consider adding to OSD some more variables corresponding to accelerometer reading. One of the reason to do that would be to show how the model is stress, proportional to speed during diving or acrobatics. The most importang would be vertical (Z-axis) g-force. Min and max values would be displayed on OSD summary screen.

**Comment by Artyum** [comment]
In fact i implemented the feature few days ago on devel 2.0.0. All i did, I put just z-axis on osd just to feel sense of it. Actually it was quite suprise to see 3.0g downforce on a loop. The ~2.3kg model weights about 7kg so wings and that plastic screws must withstand. I found it useful and fun feature for acro flying. I leave the developers the judgement if it is worth to add to inav.

**Comment by Artyum** [comment]
https://github.com/iNavFlight/inav/pull/3566

**Comment by shellixyz** [comment]
This feature has been implemented and is going to be available starting from 2.2-RC1, closing
