### ISSUE TITLE
2.0.0RC2 blackbox file timezone incorrect

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3514]
I am in iNav 2.0.0RC2 + MATEK F405 Wing
I set the tz_offset = 480 in CLI which is +08:00 timezone.

but in the blackbox log file (in the sd card), the last modify date, create date of the file
and the data inside the log (view by INAV Blackbox Explorer 3.0.2 )
all showing the time stamp is in 00:00 which is very inconvenience.

**Comment by davidngrc** [comment]
and please add the GPS date time to the black box log as well.
it currently only have the time from power on.

**Comment by david-ng-hk** [comment]
move to here, more detail https://github.com/iNavFlight/inav/issues/3531
