### ISSUE TITLE
Yaw Servo burned while Configuration

### ISSUE THREAD

**Issue by haksarion** [iNavFlight/inav#3517]
### Board and Version
Furious FPV F35 Lightning

Inav 2.0 RC2

### Behavior
* While configuring VTX Via OSD noticed smoke in FPV Feed, then Servo Burned. Never had that before, 
Servo worked well for at least 50 Hours of Flighttime

Just wanted to report this.
Of course it can be the Servo itself but why would it start burning when its not even moving and resting in center position ? 

Greetz Hakan

**Comment by shellixyz** [comment]
What model of servo ? Please post a dump of your config.
