### ISSUE TITLE
feature request GEOFENCE in INAV #62

### ISSUE THREAD

**Issue by JWC1304** [iNavFlight/inav#3524]
Would it be possible to enable geofence in inav soon with some gui? 
Better yet , just using google maps?

**Comment by AnandNL** [comment]
or steer to home after XXXX  meters

**Comment by fiam** [comment]
Duplicate of #62. Please, add your feedback in that issue so we can keep all the comments in one place. Thanks!

**Comment by rhass** [comment]
Geofencing should also support exclusion zones which would prevent flying into specific areas within a geofence. Eg: Buildings, trees, and communications towers.
