### ISSUE TITLE
INAV 2.0.0 RC2 doesn't work with XSR-M S.Port unless smartport_uart_unidir = ON

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#3526]
### Board and Version
Omnibus F4 Pro
INAV/OMNIBUSF4PRO 2.0.0 Jul  6 2018 / 09:28:45 (afc56027)
It's custom compiled, with the only inclusion being #3519, same result with downloaded release RC2 

### Behavior
No S.Port telemetry from INAV from FrSky XSR-M receiver (latest firmware).  Downgraded to INAV 1.9.1 and S.Port telemetry worked again.  Flashed back INAV 2.0.0 RC2 and it didn't work.  Replaced XSR-M receiver with a backup and it still didn't work.  Works fine on other quad running 2.0.0 RC2 (same build) and similar hardware except for different receiver X4R-SB.

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/xp5iaxHC

**Comment by teckel12** [comment]
Got it working, but with a sacrifice.  With 2.0.0 RC2 and the XSR-M/E you need to set `smartport_uart_unidir = ON` for S.Port telemetry to work.  On a different quad with the same firmware, same FC, and almost exactly the same settings, but using an X4R-SB receiver I have `smartport_uart_unidir = OFF`.  Both receivers are connected exactly the same way, to the SBUS port and S.Port connected to soft serial via the ch5/ch6 pads.  With INAV 1.9.1 I had `smartport_uart_unidir = OFF` and bidirectional S.Port worked with the BetaFlight PID Lua Script.

I believe what this means is that with INAV 2.0.0 RC, the XSR-M/E (at least when using soft serial) can't do bidirectional S.Port as well as `smartport_uart_unidir = ON` being required.

**Comment by fiam** [comment]
@teckel12 I've just set up an XSR (note the different RX) with an OMNIBUSF4PRO and it works with S.Port over softwareserial with `smartport_uart_unidir = OFF`. Could you use `DEBUG_TRACE()` to figure out if the port is being open properly and if the S.Port driver is getting the requests from the RX?

**Comment by teckel12** [comment]
@fiam will do... Note that my X4R-SB also works fine with `smartport_uart_unidir = OFF`. Also note that I'm running S.Port via SS in all cases.

**Comment by teckel12** [comment]
@fiam Did a build with DEBUG=GDB and flashed but that's as far as I got.  I was expecting more of log, but it seems that it uses a debugger of some kind?  I've never needed to use a debugger so maybe this is where it's beyond my experience.  I'm old, so I learned to program before we had debugging tools.  I avoid writing bugs, so I've never needed a debugger, I guess till now.

Is this what's needed?: https://gnu-mcu-eclipse.github.io/debug/install/

If so, I could give it a go.  But like I said, I've never used a debugger so my effectiveness would probably be low.

**Comment by fiam** [comment]
@teckel12 Don't worry, you don't need to set up a full-fledged debugger. Use https://github.com/fiam/msp-tool to connect to the FC and it will print debug messages. Then change the code to use DEBUG_TRACE() to print stuff.

**Comment by teckel12** [comment]
:+1: Will give it a go.

**Comment by teckel12** [comment]
Now works fine with 2.0.0 on this quad with the `smartport_uart_unidir = OFF`, so closing...
