### ISSUE TITLE
iNav2.0.0RC2 did not record tz_offset into blackbox & adjust internal date time to tz_offset

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3531]
1. Please record time zone parameter tz_offset into blackbox
2. Please set the internal flight controller date time according to tz_offset
    for example, the blackbox file log "create time" is in time zone 00:00, should adjust to tz_offset

**Comment by fiam** [comment]
Fixed in #3537, will be on RC3.
