### ISSUE TITLE
BUG in driver pwm_output.c

### ISSUE THREAD

**Issue by marbalon** [iNavFlight/inav#3538]
Today I tried to implement new option to start generate PWM for servos after gyro calibration is complete. But when I analyzed PWM on the logic analyzer I found that FC generate spike 16us every restart. My servos generate fast movement and then move to the center. This can be stressful for servos (recently my two servos stop working without any reason) but can be danger for motors also.

Hopefully I found the reason and solution. In pwm_ouptut.c in function pwmOutConfigTimer value is provided for all motors and servos, but in last line CCR value is set to 0.

IHMO pwmOutConfigTimer() don't need to have parameter value, and all PWM should set to 0 at startup and then motorWrite or servoWrite will do the job.

I can make this fix but want to ask other devs - what do you think guys?

Another question is if I want to add feature "enable servos after gyro calibration" should I do this via variable in console or new FEATURE ?

Just two lines in writeServo funtion do the job:

    if (!gyroIsCalibrationComplete())
      zeroServoValue = true;

Stressing servos every restart is really not necessary.

Edit. I think last line with CCR=0 was added by mistake, because this turn off PWM after enabling few lines above with value provided by parameter.

**Comment by fiam** [comment]
Fixed in #3540
