### ISSUE TITLE
inav 2.0.0-RC2 Navigation not safe: Why? After unplugging the USB cable the motors do not start, too.

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#3554]
Omnibus F4V5 with F4V3 firmware
inav 2.0.0-RC2

As soon as I try to add the Mode NAV POSHOLD, then it shows Navigation not safe. Why?

![grafik](https://user-images.githubusercontent.com/25489220/42454151-0690dafa-838f-11e8-8bf3-a34dac057177.png)

![grafik](https://user-images.githubusercontent.com/25489220/42454160-0c4a861c-838f-11e8-8d6c-6fd92b11c1da.png)

**Comment by Ralfde** [comment]
After updating again, problem seem to be gone.

**Comment by stronnag** [comment]
https://github.com/iNavFlight/inav/wiki/%22Something%22-is-disabled----Reasons
