### ISSUE TITLE
Fly Time not counting up after "normal" (not auto) launch 2.0.0 RC2

### ISSUE THREAD

**Issue by kingdraki** [iNavFlight/inav#3559]
### Board and Version
# INAV/OMNIBUSF4PRO 2.0.0 Jun 29 2018 / 12:34:56 (a8415e89c)

### Behavior
After normal hand launch the fly time does not start counting up, stays at 00:00.
Ater auto launch behaviour is as expected.

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/sbPpiHN4

**Comment by shellixyz** [comment]
Duplicate of #3495. Already fixed for RC3.
