### ISSUE TITLE
New Feature to set VTX Power only has 4 Levels. IRC Tramp has 5 Levels of Power

### ISSUE THREAD

**Issue by haksarion** [iNavFlight/inav#3560]
### New VTX Power Feature only has 4 Levels
My IRC Tramp is connected to the F35 via Telemetry Port. In OSD I can easily change channels and VTX Power.
The new Feature to set VTX Power on Arming and Disarming works brilliant, except one little thing.
The IRC Tramp has 5 Power Levels... but Inav only supports 4 Power Levels.
So if I want to set it to highest possible output Power I set "set vtx_power = 5" but only Values from 1 to 4 are allowed.

_Is this a new feature request?_ YES

Greetz

**Comment by fiam** [comment]
@haksarion There are 5 available power levels, from 0 to 4. That allows selecting 5 different power levels.

**Comment by haksarion** [comment]
true, but when I set to 4 (what is the highest number) it will still Power Tramp to only 400mw.
To power it to 600mw I need 5 ;(

**Comment by haksarion** [comment]
RC-Tramp:  0=25mW, 1=25mW, 2=100mW, 3=200mW, 4=400mW, 5=600mW

**Comment by GareFPV** [comment]
for SmartAudio:  0=25mW, 1=25mW, 2=200mW, 3=500mW, 4=800mW
for TBS Unify Nano:  0=25mW, 1=25mW, 2=50mW
for IRC-Tramp:  0=25mW, 1=25mW, 2=100mW, 3=200mW, 4=400mW, 5=600mW

**Comment by fiam** [comment]
Looks like the problem is that the levels are shifted down by 1 somewhere.

**Comment by fiam** [comment]
Fixed in #3564, will be in RC3
