### ISSUE TITLE
v2.0.0 RC2 Intermittent SBUS connection on Matek F405-STD and RadioLink R9DS

### ISSUE THREAD

**Issue by Andreas-Hellberg** [iNavFlight/inav#3563]
### Board and Version
Matek F405-STD BetaFlight STM32F405 Flight Controller 
https://www.banggood.com/Matek-F405-OSD-BetaFlight-STM32F405-Flight-Controller-Built-in-OSD-Inverter-for-RC-Multirotor-FPV-Racing-Drone-p-1141282.html?rmmds=search
v2.0.0 RC2
INAV/MATEKF405 2.0.0 Jun 29 2018 / 12:30:25 (a8415e89c)

### Behavior
When I tested upgrading to INAV 2.0 RC2 the SBUS connection became intermittent.
The board will read the stick positions for 0.5-1s then there will be a period of no changes for 1-2s then it reads the current RC input for 0.5s-1s and repeat. It's the same result when connected via USB and disconnected.

The same hardware works just fine on all previous versions of INAV I have tested (1.9.3, 1.9.0, etc). 
I flashed the board with the "full chip erase" option set to true. I tested going back an forth between 1.9 and 2.0 multiple times. On 1.9 it works just fine, but not on 2.0. 

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/Sypn6ReH

**Comment by giacomo892** [comment]
Perhaps the receiver isn't respecting SBUS timings. 
Can you set debug to `SBUS`and check what happening on the configurator Sensors tab in the debug data?

**Comment by Andreas-Hellberg** [comment]
debug_mode set to SBUS: 
![sbus_debug](https://user-images.githubusercontent.com/41109356/42565734-8ff16d5c-8504-11e8-9733-cf9321df0dbd.gif)

How it looks in the receiver tab:
![sbus_intermittent](https://user-images.githubusercontent.com/41109356/42565745-973f9b9c-8504-11e8-9904-c15a156fe439.gif)

**Comment by giacomo892** [comment]
Seems like the DESYNC_COUNTER increases... then it is an issue the the receiver not respecting SBUS specifications.

**Comment by Andreas-Hellberg** [comment]
Might be, but the receiver works fine in the previous releases with the old SBUS driver.

**Comment by giacomo892** [comment]
Older INAV versions were much more relaxed about SBUS input.
In 2.0 we have introduced a more strict approach when decoding SBUS packet to be sure that all the data is decoded correctly and no channels have invalid data.

**Comment by Andreas-Hellberg** [comment]
To me this is a regression rather than an improvement. But hey I'm a bit biased as this stops me from upgrading.. :) I know I could create my own release and just revert the SBUS commits. Might do that in the future if this issue is closed without an resolution. But it could be that the new SBUS driver excludes more than just RadioLink receivers and that would be less than ideal if so.

**Comment by digitalentity** [comment]
None of the devs has a RadioLink system, so troubleshooting this might be problematic.

**Comment by digitalentity** [comment]
@giacomo892 @fiam I suggest to add this to known issues section and look into it after 2.0 release.

**Comment by giacomo892** [comment]
Added to wiki @digitalentity

**Comment by Andreas-Hellberg** [comment]
I tested reverting PR 3110 (https://github.com/iNavFlight/inav/pull/3110/commits) and built + flashed it. 
That worked so that will have to be my workaround for the time being. 

![sbus_fix](https://user-images.githubusercontent.com/41109356/42602202-ca153860-8568-11e8-83ae-b7373857b44c.gif)

**Comment by giacomo892** [comment]
@Andreas-Hellberg bare in mind you may encounter mid air disarms and any other nasty things.

**Comment by Andreas-Hellberg** [comment]
@giacomo892 I don't see why. As the SBUS code is the same in earlier versions of Inav. But even if you are right I think my frequent crashing tells me that potential software bugs is the least of my problems. :) 

I'll probably have to replace my old RadioLink radio with a FrSky sooner rather than later. But my RadioLink gear have worked fine with, Cleanflight, Betaflight, all previos version of Inav and propitiatory software/hardware from DJI and Tarot. So I still think there is something wrong with the new SBUS driver.

**Comment by giacomo892** [comment]
@Andreas-Hellberg give a shot to RC4 and ply with the sync delay until you see no sync issues on debug data.

**Comment by Andreas-Hellberg** [comment]
@giacomo892 thanks for the reply, I tried changing the SBUS delay from 500,1500,2500 etc up to 10000. Did not see a significant improvement though. The min/max range for the new settings is reversed so I had to fix that before I could test it out. 

![image](https://user-images.githubusercontent.com/41109356/42736972-f9185dc8-886e-11e8-960c-9cda5a2a0b3c.png)

**Comment by giacomo892** [comment]
@Andreas-Hellberg could you PR the fix?

**Comment by Andreas-Hellberg** [comment]
@giacomo892 I tired but I get 403 Access denied when I try and push a branch.

**Comment by giacomo892** [comment]
You need to Fork, commit to your branch and then PR to inav :)

**Comment by fiam** [comment]
@Andreas-Hellberg do you have an oscilloscope to see the frequency of the SBUS signal output by that RX?

**Comment by Andreas-Hellberg** [comment]
@giacomo892 thanks for the help. The tiny PR is now up at https://github.com/iNavFlight/inav/pull/3606 :)
@fiam No I don't have access to a oscilloscope. Any way to log the output via a FC?

**Comment by gppsoft** [comment]
Hello. I have this issue with 1.9.1 and Omnibus F4 Pro V2 + R9DS. Freezes when board connected via USB and battery plugged.

**Comment by Andreas-Hellberg** [comment]
@gppsoft is it just on 1.9.1 or is it all versions? It's a common issue if you have some external component (gps?)  connected to the same UART (TX1/RX1) as the USB port. Then that component will go active once the battery is plugged in an interfere with the USB connection.

**Comment by rollanc** [comment]
Tested inav 2.0 rc4 with radiolink receiver R12DS, bus F4 v3, and sbus does not work for auxiliary channels.

**Comment by digitalentity** [comment]
@rollanc if it works for main channels, but doesn't for AUX - it's likely a radio setup or messed up configuration issue.

**Comment by rollanc** [comment]
No, I have everything perfectly configured, I've already come from Inav 1.6. It must be error in the radiolink ibus frame, why fryski, if that works.

**Comment by happyvalley-lmx** [comment]
I'm also using RadioLink R9DS.
Sbus seems work fine on my omnibus F4V3.

**Comment by JVN2000** [comment]
I am using Radioink R9DS on a OMNIBUS F4PRO V2 and OMNIBUS F3 running inav 2.0, no problems at all.

**Comment by digitalentity** [comment]
Seems this issue is not relevant anymore. Closing.
