### ISSUE TITLE
v2.0.0RC4 omnibus f4 pro clone softserial telemetry not working

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3565]
I connect omnibus f4 pro with sbus + softserial telemetry on CH5 CH6 pad.
30 min ago, same hardware setup, in iNav 1.9.1, the softserial telemetry is working, I will post 1.9.1 diff on the second post.

I build the development build from  https://github.com/iNavFlight/inav/tree/development  (yesterdays source code, after 30min telemetry all lost fix)

# diff all

# version
# INAV/OMNIBUSF4PRO_LEDSTRIPM5 2.0.0 Jul  8 2018 / 14:46:50 ()

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000

# servo mix
smix 0 3 0 50 0
smix 1 3 1 50 0
smix 2 4 0 -50 0
smix 3 4 1 50 0

# servo

# feature
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature RSSI_ADC
feature PWM_OUTPUT_ENABLE

# beeper

# map
map TAER

# serial
serial 0 64 115200 38400 0 115200
serial 5 2 115200 38400 0 115200
serial 30 32 115200 38400 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# osd_layout

# master
set acc_hardware = MPU6000
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = SERIAL
set serialrx_provider = SBUS
set platform_type = AIRPLANE
set model_preview_type = 8
set gps_sbas_mode = AUTO

# profile
profile 1

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

**Comment by david-ng-hk** [comment]
softserial telemetry working on 1.9.1


# diff all

# version
# INAV/OMNIBUSF4PRO_LEDSTRIPM5 1.9.1 Apr 21 2018 / 13:15:03 (03a5c1922)

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mixer FLYING_WING

# servo mix

# servo
servo 0 1000 2000 1500 100 0 
servo 1 1000 2000 1500 100 1 
servo 2 1000 2000 1500 100 2 
servo 3 1000 2000 1500 100 2 
servo 4 1000 2000 1500 100 2 
servo 5 1000 2000 1500 100 2 
servo 6 1000 2000 1500 100 2 

# feature
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature PWM_OUTPUT_ENABLE

# beeper

# map
map TAER

# name

# serial
serial 0 64 115200 38400 0 115200
serial 5 2 115200 38400 0 115200
serial 30 32 115200 38400 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1300 2100
aux 1 1 1 900 1700

# adjrange

# rxrange

# master
set acc_hardware = MPU6000
set acczero_x = 69
set acczero_y = -42
set acczero_z = -530
set accgain_x = 4094
set accgain_y = 4101
set accgain_z = 4086
set mag_hardware = HMC5883
set magzero_x = -29
set magzero_y = -304
set magzero_z = 51
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = SERIAL
set serialrx_provider = SBUS
set vbat_max_cell_voltage = 420
set disarm_kill_switch = OFF
set gps_sbas_mode = AUTO

# profile
profile 1


# profile
profile 2


# profile
profile 3


# restore original profile selection
profile 1

# save configuration
save

**Comment by teckel12** [comment]
@davidngrc Try:  `set smartport_uart_unidir = ON` with INAV 2.0.0.  Also, what receiver do you have?

**Comment by david-ng-hk** [comment]
original smartport_uart_unidir is OFF, after setting it to ON in CLI and save, still not working.
I am using R9 slim+ and x9d+

**Comment by david-ng-hk** [comment]
I also try set telemetry_inverted = ON
save, no new sensor discover, only old rssi and rxbat sensor in x9d+

**Comment by teckel12** [comment]
Try setting the SmartPort telemetry to 57600 instead of Auto.

**Comment by david-ng-hk** [comment]
set, and then try both telemetry_inverted = ON and OFF, no good.
still no new telemetry sensor.

**Comment by davidngrc** [comment]
anyone has the same problem?

**Comment by david-ng-hk** [comment]
I just the 2.0.0RC3, same, no telemetry sensor.

**Comment by david-ng-hk** [comment]
just test the 2.0.0 RC4, same result. no telemetry.
anyone has this issue or just me?
I already try S8R and 2 R9 slim+ receiver already.

**Comment by david-ng-hk** [comment]
@fiam could you help?

**Comment by vavisimo** [comment]
here it works, i Can offer you the dump if you want and you can compare:
# feature
feature SOFTSERIAL
# serial 
![daf](https://user-images.githubusercontent.com/32098018/42735269-51265fa6-8851-11e8-818d-3aca60dc3962.PNG)

serial 0 64 115200 38400 0 115200
serial 2 2 115200 38400 0 115200
serial 5 1 115200 9600 0 115200
serial 30 32 115200 38400 0 115200

set receiver_type = SERIAL
set serialrx_provider = SBUS
set serialrx_halfduplex = OFF

set telemetry_switch = OFF
set telemetry_inverted = OFF
![softser](https://user-images.githubusercontent.com/32098018/42735259-1a591a04-8851-11e8-908e-1176d11505f2.PNG)

**Comment by david-ng-hk** [comment]
please, please send a diff all as text attachment.
what iNav version r u using?

**Comment by vavisimo** [comment]
RC 4, x8r, sbus, Airplane:

# version
# INAV/OMNIBUSF4PRO 2.0.0 Jul 14 2018 / 22:40:31 (f2cf315ad)

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix 0 4 0 100 0
smix 1 5 0 100 0
smix 2 6 2 100 0
smix 3 3 1 100 0

# servo

# feature
feature -TX_PROF_SEL
feature -BLACKBOX
feature -OSD
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature AIRMODE
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 64 115200 38400 0 115200
serial 2 2 115200 38400 0 115200
serial 5 1 115200 9600 0 115200
serial 30 32 115200 38400 0 115200

# led

# color

# mode_color

# aux
aux 0 0 6 1600 2100
aux 1 1 1 1300 1700
aux 2 2 1 1750 2075
aux 3 3 0 1275 1625
aux 4 10 1 900 1200
aux 5 14 5 1600 2075
aux 6 27 7 1600 2100
aux 7 28 0 1725 2100

# adjrange

# rxrange

# osd_layout

# master
set looptime = 2000
set gyro_sync = ON
set gyro_hardware_lpf = 188HZ
set acc_hardware = MPU6000
set acczero_x = 41
set acczero_y = 11
set acczero_z = -54
set accgain_x = 4084
set accgain_y = 4088
set accgain_z = 4081
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set min_throttle = 1000
set max_throttle = 2000
set failsafe_procedure = NONE
set align_board_roll = 13
set align_board_pitch = -18
set vbat_scale = 1120
set current_meter_scale = 280
set current_meter_offset = 3
set platform_type = AIRPLANE
set model_preview_type = 14
set small_angle = 180
set disarm_kill_switch = OFF
set switch_disarm_delay = 150
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set inav_use_gps_velned = OFF
set nav_extra_arming_safety = OFF
set nav_rth_climb_first = OFF
set nav_rth_allow_landing = NEVER
set nav_rth_altitude = 7000
set nav_mc_bank_angle = 45
set nav_fw_min_thr = 1050
set nav_fw_max_thr = 1990
set nav_fw_bank_angle = 45
set nav_fw_climb_angle = 30
set nav_fw_dive_angle = 25
set nav_fw_pitch2thr = 0
set nav_fw_launch_velocity = 100
set nav_fw_launch_accel = 1500
set nav_fw_launch_max_angle = 180
set nav_fw_launch_idle_thr = 1020
set nav_fw_launch_motor_delay = 200
set nav_fw_launch_timeout = 60000
set nav_fw_launch_climb_angle = 20
set osd_units = IMPERIAL
set osd_stats_energy_unit = WH
set osd_coordinate_digits = 1
set osd_estimations_wind_compensation = OFF
set name = Storch

# profile
profile 1

set fw_p_pitch = 20
set fw_i_pitch = 30
set fw_ff_pitch = 15
set fw_p_roll = 20
set fw_i_roll = 30
set fw_ff_roll = 15
set fw_p_yaw = 45
set fw_i_yaw = 5
set fw_ff_yaw = 15
set max_angle_inclination_rll = 600
set max_angle_inclination_pit = 600
set nav_mc_vel_xy_p = 180
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set pitch_rate = 15
set yaw_rate = 9

# battery_profile
battery_profile 1

**Comment by david-ng-hk** [comment]
thank you, I will try after the world cup final😄

**Comment by david-ng-hk** [comment]
indeed it work. I try it on R9 mini.
Thank you.
I will compare why it work, and post here, after that, I will close this issue.

**Comment by david-ng-hk** [comment]
werid... I always do the testing in the following step.
I was sure I did not get the telemetry, but now, I do the test again, the before fail target now all works
inav_2.0.0-rc4_OMNIBUSF4PRO.hex 
inav_2.0.0-rc3_OMNIBUSF4PRO.hex
inav_2.0.0-rc4_OMNIBUSF4PRO_LEDSTRIPM5.hex

the only thing changes is the receiver change from r9 slim+ to r9 mini
but then I test the r9 slim+ with mateksys f405 wing flight controller, telemetry works too.

I now thinking, because in omnibus f4 pro, I combine the RSSI and CH5 and CH6 softserial and 1k resistor into on female servo connector,
and the r9 slim+ rssi and smart port combine into one male connector.
I think it was **not** well connected

then I change to R9 mini, since it does not have a rssi wire, so I only connect one single telemetry wire to the female servo connector in the omnibus f4 pro, and it was well connected.

so the whole thing might just be a "loose wire".
**maybe in the future iNav configurator, we can see which wire (like rssi, sbus, sport) is already connected? if it is, green it? other wise? red it?**

`
1. pre bind the r9 mini with x9d+r9m
2. only sbus and softserial smartport is connected to r9 mini, no other port is connected.
3. falsh new inav_2.0.0-rc4_OMNIBUSF4PRO.hex with "full chip erase" by iNav Configurator 2.0.0RC3
4. "port tab" -> uart1: disable msp, enable serial rx. uart6: sensor set to GPS (even is not connected). save and reboot
5. "config tab" -> sensor mag set to HMC58 (even is not connected)
    enable "motor and servo output", enable "don't spin the motor when armed"
    receiver set to serial-base, provider set to sbus
    enable gps, ground assistance set to auto
    enable current sensor
    battery capacity set to 3200
    enable: "enable cpu base serial ports" and "telemetry output" and "analog rssi input"
    save and reboot
6. now x9d telemetry sreen should show only two sensor, rxbat and rssi which is correct
7. "ports tab", softserial1 telemetry set to smartport, save and reboot.
8. now, you should able to see all 18 sensors in x9d.
`

**Comment by bokie1** [comment]
@davidngrc I tried the steps you suggeted, I still don't get telemetry on my r9 slim on soft serial 1.

**Comment by david-ng-hk** [comment]
@bokie1 I have upload my working iNav 2.0.0RC4 omnibus f4 pro softserial telemetry config file (Flown yesterday), full dump and diff dump.

1) The wiring is
CH6 pad -> wire (better have a soft wire) -> R9 slim telemetry port ( or sport or smart port )
CH5 pad -> wire (better have a soft wire) -> 1k resister -> wire (optional) -> CH6 wire (do not solder to the CH6 pad directly, bad idea)
CH5, CH6 pad can be found here (circle by yellow) https://github.com/iNavFlight/inav/issues/1346#issuecomment-335654194

2) flash your r9 slim to the latest firmware in https://www.frsky-rc.com/r9-slim/ (download section)
  you have to do this, otherwise, might not work.
  here is how to flash it https://www.youtube.com/watch?v=ncrpekEMTyw  (or other method to flash it)

3) the in x9d or what ever transmitter -> in "Model Setup" screen -> scroll down to “Module telemetry", check this option.
   by the way, your x9d should be on OpenTX 2.2.1, if not, flash it https://www.youtube.com/watch?v=Yy9IuJ5ZG5g

4) bind it -> go to x9d ”Telemetry" screen -> scroll down to "discover new sensors"
    it should show 10+ sensors.

[inav 2.0.0RC4_OmnibusF4Pro_SoftSerial_Dump.txt](https://github.com/iNavFlight/inav/files/2241382/inav.2.0.0RC4_OmnibusF4Pro_SoftSerial_Dump.txt)
[inav 2.0.0RC4_OmnibusF4Pro_SoftSerial_Diff.txt](https://github.com/iNavFlight/inav/files/2241383/inav.2.0.0RC4_OmnibusF4Pro_SoftSerial_Diff.txt)

**Comment by bokie1** [comment]
@davidngrc, I have done everything you have listed. Everything was working on 1.9.1 but not on 2.0 rc2,3 and 4.
Also, I put a dump on a thread I created and my diff is almost the same as yours and few differences but nothing that pertains to telemetry.

**Comment by bokie1** [comment]
Entering CLI Mode, type 'exit' to return, or 'help'

# diff

# version
# INAV/OMNIBUSF4PRO 2.0.0 Jul 14 2018 / 22:40:31 (f2cf315ad)

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix 0 0 0 50 0
smix 1 1 0 50 0
smix 2 0 1 50 0
smix 3 1 1 -50 0
smix 4 2 6 100 0
smix 5 3 11 100 0

# servo
servo 0 1000 2000 1500 -100
servo 1 1000 2000 1500 -100

# feature
feature -BLACKBOX
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 64 115200 38400 0 115200
serial 5 2 115200 38400 0 115200
serial 30 32 115200 38400 57600 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1350 2075
aux 1 1 1 1850 2100
aux 2 2 1 1375 1600
aux 3 3 4 1700 2100
aux 4 9 4 1300 1700
aux 5 8 2 1350 1675
aux 6 10 6 1875 2100
aux 7 14 6 1400 1625
aux 8 27 5 1300 1700
aux 9 28 5 1700 2100
aux 10 11 2 1375 1625
aux 11 15 3 1275 1675
aux 12 18 2 1875 2100

# adjrange

# rxrange

# osd_layout
osd_layout 0 0 24 2 V
osd_layout 0 1 8 11 V
osd_layout 0 3 8 6 H
osd_layout 0 4 8 6 H
osd_layout 0 7 20 0 V
osd_layout 0 8 2 0 V
osd_layout 0 9 22 4 V
osd_layout 0 11 15 11 V
osd_layout 0 12 1 4 H
osd_layout 0 13 2 6 V
osd_layout 0 14 23 3 V
osd_layout 0 15 23 6 V
osd_layout 0 20 16 1 V
osd_layout 0 21 2 1 V
osd_layout 0 22 14 3 V
osd_layout 0 23 2 2 V
osd_layout 0 24 10 2 H
osd_layout 0 28 22 11 V
osd_layout 0 30 1 12 V
osd_layout 0 34 10 2 V
osd_layout 0 40 2 3 V
osd_layout 0 44 0 0 V
osd_layout 0 45 0 0 V

# master
set acc_hardware = MPU6000
set acczero_x = 85
set acczero_y = -14
set acczero_z = 79
set accgain_x = 4121
set accgain_y = 4088
set accgain_z = 4058
set mag_hardware = NONE
set mag_declination = -550
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = SERIAL
set rssi_channel = 16
set serialrx_provider = SBUS
set min_throttle = 1100
set max_throttle = 2000
set motor_pwm_rate = 2000
set motor_pwm_protocol = MULTISHOT
set failsafe_procedure = RTH
set align_board_roll = 50
set align_board_yaw = 2700
set vbat_scale = 1110
set current_meter_scale = 423
set platform_type = AIRPLANE
set model_preview_type = 8
set small_angle = 180
set auto_disarm_delay = 30
set gps_sbas_mode = WAAS
set deadband = 7
set yaw_deadband = 8
set nav_min_rth_distance = 5000
set nav_rth_climb_first = OFF
set nav_rth_allow_landing = NEVER
set nav_rth_altitude = 6000
set nav_fw_bank_angle = 30
set nav_fw_loiter_radius = 4000
set nav_fw_launch_velocity = 100
set nav_fw_launch_accel = 1500
set nav_fw_launch_max_angle = 40
set nav_fw_launch_detect_time = 30
set nav_fw_launch_thr = 1900
set nav_fw_launch_motor_delay = 300
set nav_fw_launch_spinup_time = 500
set nav_fw_launch_min_time = 10000
set nav_fw_launch_timeout = 10000
set nav_fw_launch_climb_angle = 22
set smartport_fuel_unit = PERCENT
set osd_video_system = NTSC
set osd_rssi_alarm = 35
set osd_time_alarm = 20
set osd_alt_alarm = 1000
set osd_dist_alarm = 10000
set osd_neg_alt_alarm = 25
set osd_crosshairs_style = AIRCRAFT
set osd_left_sidebar_scroll = GROUND_SPEED
set osd_right_sidebar_scroll = ALTITUDE
set osd_sidebar_scroll_arrows = ON
set osd_coordinate_digits = 10
set name = bokie_s800v2_1

# profile
profile 1

set fw_i_pitch = 11
set fw_ff_pitch = 51
set fw_p_roll = 3
set fw_i_roll = 5
set fw_ff_roll = 35
set fw_p_yaw = 50
set fw_i_yaw = 45
set fw_ff_yaw = 0
set max_angle_inclination_rll = 750
set max_angle_inclination_pit = 750
set rc_expo = 80
set roll_rate = 35
set pitch_rate = 30
set manual_rc_expo = 80
set manual_rc_yaw_expo = 30

# battery_profile
battery_profile 1

set battery_capacity = 2200
set battery_capacity_warning = 880
set battery_capacity_critical = 440

#

**Comment by david-ng-hk** [comment]
1) do you have another receiver? like x8r or x4r or other one that have sport?
try that receiver, if it work, then your r9 slim telemetry might be broken.

2) do not move the wiring, try down grade to 1.91 again.
if telemetry shows up, then its the setting.
if it does not show up, then its the wiring.

**Comment by bokie1** [comment]
I already downgraded back to 1.9.1 and everything is working.
I don't it's the receiver. It could be the settings if the parameters on 2.0rc4 changed.

**Comment by david-ng-hk** [comment]
have you load my config dump to your Omnibus F4 Pro?
just flash a new iNav 2.0.0RC4 with clean setting, 
and copy the content in my dump file, and paste it in CLI, and save.
delete sensor in your x9d telemetry screen, then discovery new, see what happen?

one small thing I did was,
only sbus and its 5v are power from the Omnibus F4 Pro
 all my servo 5v was output from a 5v BEC, cam, vtx are are from another BEC
all the BEC and main battery have capacitor (main battery like 1000u 25v)

**Comment by bokie1** [comment]
Still the same.
