### ISSUE TITLE
Possible scaling problem in blackbox log for VBAT & Amperage

### ISSUE THREAD

**Issue by wilco1967** [iNavFlight/inav#3568]
INAV/MATEKF722 2.0.0 Jul 11 2018 / 18:14:05 (fabd3205e)
(custom compiled latetst development)

Mini Talon airplane. Flies perfect. 
just went up to 5 km altitude.... new record for me... Zero issues !

Only minor problem I see, is VBAT and Amperage in blackbox logs seem off.
The values 'move', but seems to be some kind of scaling problem....

On the OSD everything seems fine.  Telemetry (LTM) also OK. (well... for voltage.... amperage is not available on LTM so can't say).

When full 4S LiIo pack, OSD says 16.8 Volts (correct, was charged to 4.2 / cell). But blackbox log shows only 14.9 Volts.
As the pack drops, the blackbox log also shows the voltage dropping, but consitently showing too low 

I've noticed this in MWP when I tried to play back the blackbox log, but it also is shown wrong in INAV blackbox explorer, as well as in the the blackbox converted to csv file.. (using blackbox_decode tool) 

Similar for amperage draw... OSD is correct, but blackbox shows way off.... 
during launch, I run nearly 30 amps, but blackbox shows about 131 amps. As I back-off the throttle, the value drops, but stays consitently too high (showing about 100 amps, where I pull approx 20).

blackbox log
[https://drive.google.com/open?id=13WnnhZeJqsyv6dKPT7dnzFWOaf0hEM55](url)

dump
[https://drive.google.com/open?id=1UEda83_0mLq2li0yIFjLN_nYm5TLwMI1](url)

I could provide the ground recording, showing OSD information, if required....

**Comment by shellixyz** [comment]
You can use this branch of the BB viewer to display the right voltage/current while we are working to fix it in the main repository: https://github.com/shellixyz/blackbox-log-viewer/tree/voltage_current_fix

**Comment by wilco1967** [comment]
Thanks, but no worries....not needed.

Just noticed it, by accident so created an issue, so it could be cleaned up whenever you guys feel bored...😋
This is minor stuff.... iNav 2.0 is working really well....
Thanks a lot!
