### ISSUE TITLE
iNav 2.0.0 rc2 - IRC Tramp settings

### ISSUE THREAD

**Issue by er9xuser** [iNavFlight/inav#3576]
Hi.

Could you be so kind and add in iNav configurator power level 5 for IRC Tramp power output. Because now numbe 4 is just 400mW and Tramp has 600mW output.

Thanks.

**Comment by fiam** [comment]
@er9xuser can you try with RC3? The problem should be fixed with that one.

**Comment by Chefhandwerker** [comment]
600mW power setting does not work. You can choose it over the OSD. But after leaving the OSD, invalid VTX Power is displayed.
Matek F405 Wing
IRC Tramp Int
Inav 2.0
crosscheck with Betaflight Lua.
With Betaflight Lua you can set 600mW. Sometimes with, sometimes without error in the OSD

**Comment by er9xuser** [comment]
@Chefhandwerker: really? With Betaflight lua?
@fiam: sorry for my late reply...it works with RC3 and RC4.

**Comment by Chefhandwerker** [comment]
Yes, VTX und PID Settings work wellBetaflight Lua. 
VTX LUA from teckel12 also work well
https://github.com/teckel12/Taranis-VTx/releases

**Comment by er9xuser** [comment]
@Chefhandwerker  I'm using crossfire...so can't use LUA on iNav.

**Comment by teckel12** [comment]
@er9xuser I believe you can use the Lua scripts with Crossfire. Maybe not my fork, but I believe the Betaflight Lua Script supports Crossfire too.
