### ISSUE TITLE
New feature request - Flight Path Vector 

### ISSUE THREAD

**Issue by wojciechwas** [iNavFlight/inav#3578]
Could you consider adding this feature please? 

Flight Path Vector is a circular symbol that displays estimated drift angle and flight path angle. 

When shown on OSD it can be very useful instrument to assist on landing approach, general flying and hitting gaps.... 

More info on the flight path vector: 
http://www.flaps2approach.com/journal/2012/7/7/flight-path-vector-fpv-explanation-and-use.html 
http://www.smartcockpit.com/docs/Fokker_100-Flight_Path_Vector_Use.pdf 
https://www.youtube.com/watch?v=wSR0L7FGM4o

**Comment by fiam** [comment]
@wojciechwas That's definitely interesting, but I'm not sure if we can pull it off with the drawing resolution we have in the OSD (12x18 character grid, characters have to be aligned to it).

**Comment by wojciechwas** [comment]
Could it not be displayed in the same way as the artificial horizon? 
The flight path vector circle can be rendered as a bunch of white dots instead of a special character. 
Therefore, the flight-path vector can be allowed to float in the middle of the screen just as the AH, without character grid constraint.

**Comment by wojciechwas** [comment]
More links on how to implement flight path vector: 
https://diydrones.com/profiles/blogs/airspeed-angle-of-attack-sideslip-and-flight-path-vector 
https://people.mpi-sws.org/~bbb/proceedings/rtas14-wip-proceedings.pdf

**Comment by teckel12** [comment]
@wojciechwas I believe with magnatometer data I could calculate the flight path vector in [Lua Telemetry](https://github.com/iNavFlight/LuaTelemetry/wiki) on the new pilot view (glass cockpit).  It wouldn't be heads up, but would show on your transmitter.

![inavx9dpilot](https://user-images.githubusercontent.com/2592128/43596195-96211b74-964c-11e8-83a8-6a71f1feba63.png "Pilot view on Taranis X9D, X9D+ and X9E")

Do you fly Taranis/SmartPort?

**Comment by wojciechwas** [comment]
@teckel12 That would be a good to have feature even on the glass cockpit. 
Would it be fairly straight forward for developers to pull this into the OSD at later stage? 
I manly fly on googles and having the flight path vector on the OSD would be more useful. 
Would be happy to try it out with the pilot view first and so some instrument flying. 
Yes I use X9E and Smartport telemetry.

**Comment by teckel12** [comment]
The problem with on the OSD is the limited "resolution" as everything on the display is just a character which is mapped to fixed locations.  There also can't be two characters in the same spot or one will cover the other or cause flashing.  Basically, the OSD isn't pixel based, it's character based.  This is why the artificial horizon on the OSD is kinda janky.  On the transmitter we have pixel-level control so this isn't a problem.
