### ISSUE TITLE
MOTOR STOP not working in release 2.0.0 RC2

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#3583]
MATEK F405 WING
QUAD X
2.0.0 RC2

Switch arming with feature MOTOR_STOP enabled.

Motors spin at min throttle as soon as the Quad is armed (potential skin remover).
OK in release 1.9.0

[CLI JULY 13.zip](https://github.com/iNavFlight/inav/files/2191115/CLI.JULY.13.zip)

**Comment by DzikuVx** [comment]
> AIRMODE now excludes feature MOTOR_STOP in multicopters

Since those two features are not compatible, when Airmode is enabled, Motor_stop is disabled. If you want to use MOTOR_STOP, disable airmode

**Comment by ghost** [comment]
That did it thanks
