### ISSUE TITLE
Direction to home arrow

### ISSUE THREAD

**Issue by oldrootbeer** [iNavFlight/inav#3587]
Hi. The direction to home arrow is very useful. Just to make it look good on the OSD, if the distance to home is within so many metres, could the arrow become a circle? So at a quick glance you know its above home position. Probably suitable only for MRs. No big deal. Just to make the OSD look better.

**Comment by fiam** [comment]
@oldrootbeer That seems like a good idea. We could make it use a different symbol when you're like < 2m from home.

**Comment by ghost** [comment]
@fiam 
If its not to late for 2.1
How about also allowing the close to Home proximity symbol, to also alert us when the craft is inside 
`failsafe_min_distance`. So will have an idea were the boundary is for a safety reference.

Possibly invert the color of the symbol. 
![096](https://user-images.githubusercontent.com/43928973/50263623-d8b07c00-046a-11e9-92f8-fa7ccc74f327.png)

**Comment by shellixyz** [comment]
I would prefer a separate symbol that is not an arrow. Like a circle with a dot in the center.

**Comment by ghost** [comment]
How about these guys.
![over home location](https://user-images.githubusercontent.com/43928973/50744486-a0d17300-1277-11e9-84e3-ab59f7e6e8ee.PNG)
![over home location 2](https://user-images.githubusercontent.com/43928973/50745069-471f7780-127c-11e9-9567-ac869a3ba6cf.PNG)



@shellixyz   The file is @ [](url)https://github.com/iNavFlight/inav-configurator/issues/605
If you guys what to go with one of them.

**Comment by oldrootbeer** [comment]
Yeah, good. kardon18 is right. Just so that you know your craft will land when you hit fs or 'rth with landing', and not shoot up to the min height for fs / rth before landing.

**Comment by shellixyz** [comment]
Was already done in #4256, closing
