### ISSUE TITLE
Feature request - one-click "save" dump, diff, and screenshots automatically of all config pages

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#3590]
My suggestion is a "one-click" feature in iNav configurator that will auto save a diff, dump, and automatically save screenshots of all config pages (each page to a different jpg file) to a pre-set folder on the computer. This would make upgrading to new firmware less painless.

**Comment by junwoo091400** [comment]
Cool Idea! I really like that. But this is related to a configurator, so I suggest you to go post your idea there :)
 https://github.com/iNavFlight/inav-configurator/issues

**Comment by VoicOfReason** [comment]
Will do!

**Comment by VoicOfReason** [comment]
https://github.com/iNavFlight/inav-configurator/issues/544
