### ISSUE TITLE
iNav 2.0.0 RC3 GPS negative value not shown on OSD

### ISSUE THREAD

**Issue by scrapit85** [iNavFlight/inav#3592]
Since upgrading to RC3 my Longitude no longer shows a negative value.

Tried on an Matek 405 and an omnibus F4 also reset to defaults and only setup the GPS and OSD.

<img width="264" alt="screen shot 2018-07-13 at 17 59 20" src="https://user-images.githubusercontent.com/28651361/42721772-5e89648c-8738-11e8-944e-d3241b7ddb65.png">
<img width="638" alt="screen shot 2018-07-14 at 07 17 30" src="https://user-images.githubusercontent.com/28651361/42721775-6a4c2bba-8738-11e8-8a2b-ee6ddaf8710e.png">

`
# INAV/OMNIBUSF4PRO 2.0.0 Jul 12 2018 / 11:34:15 (81ce75745)

# resources

# mixer

# servo mix

# servo

# feature
feature GPS

# beeper

# map

# serial
serial 0 0 115200 38400 0 115200
serial 5 2 115200 57600 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# osd_layout
osd_layout 0 20 19 15 V
osd_layout 0 21 1 15 V

# master
set acc_hardware = MPU6000
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set gps_sbas_mode = EGNOS
set osd_coordinate_digits = 8

# profile
profile 1

# battery_profile
battery_profile 1

# `

**Comment by fiam** [comment]
Fixed in #3592, will be in RC4
