### ISSUE TITLE
F405-Wing can't talk to any GPS's

### ISSUE THREAD

**Issue by Hyperious** [iNavFlight/inav#3618]
### Board and Version
Matek F405-wing
INAV/MATEKF405SE 2.0.0 Jul 12 2018 / 11:30:25 (81ce75745)

### Behavior
No GPS's work, on any UARTs. I've tried 3 different known-working Neo-M8N's on all the UART's, and none of them talk to the FC. I've made sure the ports tab is set correctly, and that wiring is correct for all of them. the GPS tab shows no packets sent or received either.

Any idea what's wrong?

#### Blackbox logs/Config (.ZIP) where problem occurs
current dump:
[CLI-Dump.txt](https://github.com/iNavFlight/inav/files/2203801/CLI-Dump.txt)

**Comment by lichtl** [comment]
Did you connected lipo to the FC? Some of the 5V rails only provide power when Lipo is connected

**Comment by Hyperious** [comment]
yup, tried both USB power only, and power from a Lipo. I've even hooked all the tested GPS units to a known-working 5v BEC. Still no dice

**Comment by NNygren** [comment]
I'm seeing the same thing.  Using a MatekF405-mini board.  iNav 1.9.1 picked up the GPS just fine and worked in 2 RC1, but I can't get get the GPS to be recognized in iNav 2 RC4.

**Comment by Hyperious** [comment]
I'm sure the software and hardware are the same between the two boards for gps processing, so it doesn't surprise me that other F405-X boards would be having the same problem. Shame though as I need to run 2rc4 since I've been having random disarms with 1.9.1. 

I'll try jumping back to 2RC1 and will see if it talks to the gps, but at this point I think it's either batch hardware related, or there's an issue in inav's specific F405 release.

**Comment by giacomo892** [comment]
I'm using MATEKF405SE and GPS is working fine on latest development.
Must be an issue with your GPS hardware/configuration.

**Comment by ghost** [comment]
That's weird.

I am using a self compiled version of RC4 on a MATEK F405-WING (QUAD platform) and GPS is working perfectly.
I have modified the code to put the motor outputs on S3 - S7 and an external baro on the I2C2 bus, but doubt if that would affect the GPS in any way.

Cosmic rays?

**Comment by ghost** [comment]
Sorry, can't count at this time in the morning.
Motors on S3-S6.

**Comment by Hyperious** [comment]
I got in contact with Matek about it. While they didn't say it directly, I think they had a bad batch of F405-X's. The support member mentioned that a few other owners were experiencing the same issue, and that they'd warranty replace it for me. Hopefully that solves it once and for all.

**Comment by akhanhk** [comment]
@giacomo892 sorry for opening up an old thread, can you verify your FW version and the configurator version.. 

Target : F405SE
I am using config 2.0 rc2 and f/w 1.9.1 - GPS works, no mixer
switch to Config 2.0 rc2 and FW 2.0 rc4 - No GPS, yes mixer.. lol

**Comment by giacomo892** [comment]
1.9.1 doesn't have custom mixer as 2.0.0 :)
GPS works for me on 2.0rc3 configurator and 2.0.rc4 firmware

**Comment by solmag** [comment]
Hello, I just finished building a plane and everything works except the GPS. I'm using the Matek F405-WING. Is there a solution to this problem? I have tried 5 different GPS modules and none of them works with the F405 Wing FC, but they work on other FC. Does anyone know how to fix this issue? I am using Inav 2.0 stable firmware.

**Comment by Hyperious** [comment]
I heard they made a batch where the RX and TX pins were actually switched on
accident. When I RMAed mine, that's probably why it was having problems.

Try switching your uart TX and RX pins to see if that works

**Comment by solmag** [comment]
I will try that. Thanks for the information.

**Comment by geoavia** [comment]
Same problem here :(
FC: Matek F405-Wing (ordered from getFPV)
GPS: Holybro Micro M8N GPS Module (also ordered from getFPV)
Configuator: 2.0.0
Firmware: MATEKF405SE 2.0.0

@Hyperious: 
swapping TX/RX does not work for me. But I kew it wont work, cause gpspassthrough command worked fine, uCenter conects get GPS lock, so GPS itself works perfectly well. So the pinout was correct in my case.

Just can't get GPS working in iNav, therefore compass recognized and working.

**Comment by solmag** [comment]
I was able to solve mine by swapping the UART. I contacted Matek and I was asked to change the UART and after I did it, it started working.

**Comment by solmag** [comment]
I was able to solve mine by swapping the UART. I contacted Matek and I was asked to change the UART and after I did it, it started working.

**Comment by geoavia** [comment]
@solmag can you point me on which uart it worked? I have currently using uart 4, tend to try on 6 - cause it's just aside.
. . .
PROBLEM SOLVED!
UART6 worked, Thank you @solmag! 

Nice to have such a responsive community ;)

**Comment by antidotez** [comment]
I have the same problem on matek f405-wing and bn220 gps. Latest working version of inav is 2.0.1. I tried different ports, different baudrates, but no changes on inav >2.0.1.

**Comment by geoavia** [comment]
@antidotez did ypu check if it (GPS) works in uCenter, u must have gpspassthrough enabled though.

P.S. I have BN220 working fine but on different wing and FC (Matek F411Wing)

**Comment by antidotez** [comment]
Sorry, i forgot to say about it. Yes, it work through "gpspassthrough". 
After version 2.0.1 there were changes in the gps code, maybe this affected? Maybe gps module settings are not correct? Can you send me your bn220 settings?

**Comment by geoavia** [comment]
@antidotez 
sorry for delay... was out of reach of the wing. Forget that I replaced BN220 with Matek SAM-M8Q GPS module on that wing (no particular reason thogh). 
But, to be sure, today repinned (thanks to the fact that connector is same) and reconnected BN220 again for you as it worked before :)

as for settings (nothing special):
- ports: uart 2 (it's F411 wing though)
- it worked on both protocols: UBLOX and NMEA
- tested on baudrates: 9600bps up to 38400bps


pix for reference (NMEA, 9600bps )
https://pasteboard.co/IxP6556.jpg (both leds were flashing)
https://pasteboard.co/IxP6zNF.jpg

I'll post inav cli dump/diff if you wish later.
