### ISSUE TITLE
Which confirmed-working-stable iNav FC's exist with most available UARTS?

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#3621]
To be succinct, I require a lot of UARTs for my long-range quad. My SP Racing F4 EVO doesn't have enough. Can anyone suggest a FC with a lot of UARTs that is confirmed working with iNav? I need about 6-7 ports open for use.

**Comment by fiam** [comment]
The issues are not a forum. Use any of the available official groups/chat roooms.
