### ISSUE TITLE
Feature request: more than 3 MSP ports

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#3622]
Granted, 99% of iNav users won't need 4 MSP ports, but I do, and some others may. 

My requirements:
USB VCP --> MSP PORT 1
UART1 --> MSP PORT 2 (DJI Occusync OSD information)
UART 3 --> MSP PORT 3 (MobileFlight (iPhone APP) data output via TBS Crossfire Micro V2)
(needed) UART 4 --> MSP PORT 4 (OSD for my secondary 5.8ghz Vtx for redundancy)

My current FC doesn't have OSD built-in (SP Racing F4 EVO)

This is just one scenario above. Other users may require 4 MSP's for other reasons.
If F4 boards don't support this because of speed, would an F7 board be capable of 4 MSP's?

**Comment by fiam** [comment]
There are supporterd FCs with up to 7 serial ports. Please, use the Telegram or FB groups for support questions.
