### ISSUE TITLE
akk smart audio issue, maybe?

### ISSUE THREAD

**Issue by P-I-Engineer** [iNavFlight/inav#3625]
smart audio does not appear to be working. I have a akk vtx that is not up to date with the correct smart audio firmware.

is akk smart audio still supported? I'll gladly do my own build if i told what changed.

thank you

Board: matek f405-ctr
vtx: akk x2

dump paste
https://pastebin.com/y923ymf4

**Comment by giacomo892** [comment]
To which pad have you connected the Smart Audio wire?  I'm using an AKK VTX and SA works here.

**Comment by P-I-Engineer** [comment]
it's on TX3, it worked in inav 1.9.3

edit: I compared betaflight akk code to inav 2.0

"serialWrite(smartAudioSerialPort, 0x00);" 
 is missing from inav. I'll try to do a custom build tonight

**Comment by P-I-Engineer** [comment]
how can i clone rc4? Or should i just use the dev branch?

**Comment by fiam** [comment]
@P-I-Engineer Give this hex a try. It's a modified RC4 with a workaround. Let us know if it works for you.

[inav_2.0.0_MATEKF405_FIX_3625.hex.zip](https://github.com/iNavFlight/inav/files/2214071/inav_2.0.0_MATEKF405_FIX_3625.hex.zip)

**Comment by P-I-Engineer** [comment]
working perfect!  thank you

**Comment by fiam** [comment]
Fixed in #3633, will be in RC5
