### ISSUE TITLE
Use CRSF sync byte for telemetry frames

### ISSUE THREAD

**Issue by sirPerna** [iNavFlight/inav#3632]
CRSF over serial should always use a sync byte at the beginning of each frame. To get better performance it's recommended to use the sync byte 0xC8 to get better performance. 

The improvement already made it inside betaflight and can be used as a reference. It would be great if inav could get this improvement as well. 
https://github.com/betaflight/betaflight/pull/6395

**Comment by digitalentity** [comment]
PR ready
