### ISSUE TITLE
2.0.0 RC4 - Omnibus F4Sd/Pro - FC does not see CrossFire

### ISSUE THREAD

**Issue by romanas** [iNavFlight/inav#3637]
Tested with all pre versions, RC3 and RC4, FC can't see Crossfire inputs. Receiver tab shows all at 1500.
Works fine with 1.9.1 iNav.

Tested with clean installs/presets/custom builds RC3.

**diff**
```
# map
map TAER

# serial
serial 0 2048 115200 38400 0 115200
serial 2 2 115200 38400 0 115200
serial 5 64 115200 38400 0 115200
set receiver_type = SERIAL
set rssi_channel = 12
set serialrx_provider = CRSF
```

**Comment by wx4cb** [comment]
have you swapped the TX/RX wires? are you using CSRF? if so have you setup the receiver correctly and also told the FC that you're using CSRF?

i've just put 2.0.0/RC4 on a brand new F405-Wing and it worked first time

**Comment by romanas** [comment]
It works fine with 1.9.1, but when flashing 2.0 RC3 and RC4, nothing happens in receiver tab,

**Comment by CrashTestDummy-CTD** [comment]
Got the same problem...with omnibus fc

**Comment by leeph** [comment]
I have the same issue with a PPM RX. Works fine in 1.9.1 on Matek F722 - flash to 2.0.0 and apply the exact same port & receiver config and there just is no input from the receiver under 2.0.0, RC1, 2, 3 and 4 all tested and no worky.

**Comment by digitalentity** [comment]
@romanas please post complete dump of non-working RC4.

**Comment by digitalentity** [comment]
Tested on OMNIBUSF4 board, Crossfire on UART6. No issues, CRSF working perfectly.

**Comment by romanas** [comment]
While you are there, could you test same setup with 1.9.1 ?

**Comment by digitalentity** [comment]
Already did. Working as well.

**Comment by smaller09** [comment]
I had same problem, if using uart1 for serial rx, will get nothing in receiver tab
#3610

**Comment by digitalentity** [comment]
Regarding CRSF/SBUS on OmnibusF4 PRO boards. Issue confirmed and existing on ALL versions of INAV. It appears that PPM/SBUS input on that board is always inverted regardless of what firmware is asking.

Also, newer Omnibus F7-based and NTX boards have SBUS input always inverted by design.

**Comment by blurcak** [comment]
Hi i have simillar problem iBus+Uart1 (OmnibusF4pro)
Yesterday i made upgrade from 1.9.1 to 2.0.0RC4 and receiver is not working
Reflash to 1.9.1 (inav_1.9.1_OMNIBUSF4PRO.hex) Fullchip erase  RX is ok 
But on 2.0.0RC4 (inav_2.0.0-rc4_OMNIBUSF4PRO.hex) Fullchip erase no movement in receiver tab.
I have OmnibusF4-Pro-0A board RX connected to J5(Uart1) connector.

**Comment by digitalentity** [comment]
@blurcak can you test this hex?

[inav_2.0.0_OMNIBUSF4PRO.hex.zip](https://github.com/iNavFlight/inav/files/2250374/inav_2.0.0_OMNIBUSF4PRO.hex.zip)

**Comment by blurcak** [comment]
Sorry for delay, its working 👍

**Comment by digitalentity** [comment]
@blurcak roger that. Merging the fix!

**Comment by romanas** [comment]
Ok, thanks will try to test your custom hex also.

**Comment by leeph** [comment]
Is this fix in any way applicable to my Matek F722 board and PPM? Because the symptom is exactly the same as what's being described above for Crossfire etc on Omnibus boards...

**Comment by romanas** [comment]
Tested, works with Crossfire, Thanks

**Comment by waveydavey420** [comment]
Same here. Crsf is working good on  1.9.1, but when I switch to 2.0 no Rx. Please help! Matek f405 wing fc

**Comment by teckel12** [comment]
@waveydavey420 I believe you'd need a pre-release flash for the F405 to verify it works or not. You could compile your own for your target (see the cross-linked PR), or wait for the next release.

**Comment by wx4cb** [comment]
That is weird. Im using it with 3 f405 wings using 2 micro and 1 nano receiver without an issue.

If you want, i can post my cli dump in the morning

**Comment by leeph** [comment]
In my testing it's only F7 boards that exhibit the PPM no data issue. F4 boards are unaffected, with otherwise identical setups.
