### ISSUE TITLE
2.0 RC4 Arming issue after CMS save reboot

### ISSUE THREAD

**Issue by lo4wai** [iNavFlight/inav#3642]
After save & reboot from CMS, motors do not spin after arming.  However stat will still appear during disarm.

In 1.9.x, CMS save & reboot produce ESC last startup tone, but in 2.0 RC4, they are gone.

**Comment by giacomo892** [comment]
Are you running BlHeli 32 ESCs?

**Comment by lo4wai** [comment]
Yes, I am running DYS Aria with Matek F405 CTR

**Comment by digitalentity** [comment]
I've seen this issue as well. It seems ESCs get into some weird state when FC is soft-rebooted.

**Comment by lo4wai** [comment]
Reboot in CLI and configurator (MSP I guess) are fine, motors will spin when armed.
I found little difference in code that CLI and MSP delay for 1000ms but CMS only for 200ms

I try to check out RC4 tag as a branch, change it to 1000 and build using docker, but fail with

>$./build.sh MATEKF405
Building target MATEKF405
settings.yaml -> settings_generated.h, settings_generated.c 
%% startup_stm32f40xx.s 
make: *** No rule to make target 'lib/main/CMSIS/CM4/DeviceSupport/ST/STM32F4xx/stm32f4xx_gpio.c', needed by 'obj/main/MATEKF405/stm32f4xx_gpio.o'.  Stop.

I can build the master branch, but seems it is not 2.0RC4

**Comment by giacomo892** [comment]
Using PWM instead of ONESHOT/MULTISHOT makes this work... but PWM is so funny. Still an interesting fact

**Comment by digitalentity** [comment]
Fixed by #3645, closing.
