### ISSUE TITLE
I2C MS4525 speed sensor no data

### ISSUE THREAD

**Issue by Thyristornp** [iNavFlight/inav#3650]
### Board OMNIBUS F4 Pro, Running firmware released on: Jul 14 2018 22:40:31,  INAV, version: 2.0.0
Speed Sensor on chip MS4525, I2C (Addr. 0x28H)

I connected a speed sensor MS4525 to port J10, but INAV configurator can't detect it (I tried AUTO and MS4525 in setup menu). Then, I conncted I2C bus to logic analizer and there is no any data in it. As I can see, flight controller does not sends requests to speed sensor to take data.

**Comment by digitalentity** [comment]
Airspeed is not supported on many boards due to lack of usability.

**Comment by Thyristornp** [comment]
So, as I can understand, UAV speed is independent of speed sensor's value?

**Comment by shellixyz** [comment]
The speed reported in the OSD is the ground speed (GPS 2D speed). You can also display the air speed but it is only used for being displayed on the OSD and by the turn assistant for now.
