### ISSUE TITLE
INAV/KAKUTEF4V2 2.0.0 Jul 14 2018 No battery monitor 

### ISSUE THREAD

**Issue by PTaki** [iNavFlight/inav#3655]
The battery end current monitor not working when LED stript enabled.
Board Kakute F4 V2
Version: INAV/KAKUTEF4V2 2.0.0 Jul 14 2018

**Comment by PTaki** [comment]
![setup2](https://user-images.githubusercontent.com/40797486/43396782-eb31ebbc-9402-11e8-8940-f08a7bd95764.png)
The first measurement is successful after booting. 
Then, this value will no longer change during the flight.

**Comment by johnlenfr** [comment]
Same thing for me.

INAV 2.0.0 / KAKUTEF4V2 / Receiver R9 Slim / Radio Taranis QX7

Also have problems with lua script. No GPS coordinate (but 10+ satelites) and no fix on lua script.
3D fix mode ok in the GUI.

**Comment by pauki40** [comment]
When the LED is enabled, Battery monitor does not work.

**Comment by digitalentity** [comment]
Should be fixed in `development` branch.
