### ISSUE TITLE
Matek F405 STD OSD numbers not displaying

### ISSUE THREAD

**Issue by evmoius** [iNavFlight/inav#3662]
1.9.1
Current draw and RSSI do not display most of the time despite being enabled and visible in the OSD configuration tab.  If I enable "display_force_sw_blink" they appear, but blink which is pretty annoying.  Occasionally they will appear on their own with the blink setting off but probably only 10% of the time. I've updated the font file, made no difference.

**Comment by DeltaVelocity101** [comment]
Have you tried setting your "Analog RSSI signal" to on? Additionally, how confident are you in your hardware from a soldering and reliability perspective?

**Comment by Tygrys-1** [comment]
Are you sure no other OSD element is overlaping their area? Some are bigger than displayed sample.

**Comment by evmoius** [comment]
I'm not using analog RSSI. I have the crossfire outputting link quality on a spare channel. Would enabling analog make any difference? 

As far as reliability goes, I've always had good luck with Matek hardware and always purchased from reputable dealers...I suppose it's always possible to get a dud though. I've been building quads for 4 years now and was soldering for a decade before that so I doubt it's the issue.

I don't think anything is overlapping but I can double check. What's strange is for the first few flights everything worked fine.  I was going to start calibrating my current sensor when this issue started.  Would changing the scale have this effect on it? After comparing the OSD draw value to the actual mAh put back in the battery by the charger I did some math and changed the scale but I did it using the betaflight method:

new_scale = old_scale x (OSD_mAh_consumed / mAh_charged) 

Maybe this is incorrect for inav resulting in a bad value?

**Comment by shellixyz** [comment]
I don't know what's going on with your OSD but make sure there is no collision with another item like previously suggested. You can find more details about the calibration of the current sensor in the [battery management documentation](https://github.com/iNavFlight/inav/blob/master/docs/Battery.md#tuning-using-actual-current-measurements)

**Comment by bforbort** [comment]
I've noticed that OSD elements disappear from my Matek F405 OSD when they go into alarm and try to blink.

@evmoius could you post a diff.  I have a suspicion that your alarm thresholds are very low.

**Comment by teckel12** [comment]
@bforbort Try `set display_force_sw_blink = ON`  I believe this should be `ON` by default for the highest compatibility, but it seems others don't think it's an issue, when it "clearly" is (pun intended).
