### ISSUE TITLE
Eachine TS 215 only has UART3?  Where to connect Mag???

### ISSUE THREAD

**Issue by Jawnv71** [iNavFlight/inav#3666]
This eachine TS215 seemed perfect for an iNav conversion with a barometer and a "Customized Omnibus F4 Flight Controller". It flashed just fine,  alt hold works great, but for the life of me I can't figure where to wire in the Compass SCL/SDA and I can’t get any of the NAV modes without the magnetometer hooked up. Any ideas? Can the SCL and SDA share the tx/rx3 with the GPS? (That foam is over the barometer, BTW) Thanks!

![ts215](https://user-images.githubusercontent.com/21321275/43340709-0f576c2e-9192-11e8-891a-458d54763d2c.JPG)

![2018-07-25 16_09_53-mm3 3 0 model 1](https://user-images.githubusercontent.com/21321275/43340727-1bcde0aa-9192-11e8-8986-ce7d9ce9a5d3.jpg)
![2018-07-25 16_09_24-mm3 3 0 model 1](https://user-images.githubusercontent.com/21321275/43340734-1e1a25bc-9192-11e8-9f4b-b73aa6bed73b.jpg)
![2018-07-25 16_10_16-eachine wizard ts215 fpv racing rc drone spare part customized omnibus f4 flight](https://user-images.githubusercontent.com/21321275/43340740-2142c762-9192-11e8-9c2b-a4b048bb15c5.jpg)

**Comment by shellixyz** [comment]
On F4 boards the I²C bus is often shared with UART3 so if only UART3 is broken out you're screwed.

**Comment by Jawnv71** [comment]
Bummer. Is there a way to get the nav modes on the configuratior without the magnetometer?  Thanks a lot.

**Comment by shellixyz** [comment]
For planes yes but for multi rotors the magnetometer is needed

**Comment by digitalentity** [comment]
DJI NAZA GPS is able to communicate both GPS and compass data via a single UART. I think about a small board to sit between GPS/compass and FC and allow using a single UART
CC: @fiam, @DzikuVx

**Comment by teckel12** [comment]
@digitalentity Doesn't INAV support a direct DJI NAZA GPS and compass over a single UART without any type of conversion? If he's flashed INAV to the FC, he could connect a DJI NAZA GPS to UART3 without any modifications.

That's at least what the INAV docs suggest.

**Comment by Jawnv71** [comment]
Interesting. That sounds like a good idea. Looking at some of the DJI compasses that are available, it appears that there are aftermarket versions with just the four wires. I wonder if there is a clever way to wire that up or if they have some trick piece of hardware in it.

**Comment by teckel12** [comment]
@Jawnv71 according to the INAV docs: https://github.com/iNavFlight/inav/wiki/GPS--and-Compass-setup it shouldn't require anything clever nor any hardware. 

Specifically:

_When using DJI NAZA gps this is not true, DJI NAZA sends compass over serial and does not use the I2C bus)_

And then:
https://github.com/iNavFlight/inav/wiki/GPS--and-Compass-setup#getting-started-with-dji-naza-gps

**Comment by Jawnv71** [comment]
That’s interesting. I still can’t figure out how to wire a 6 wire UBLOX to the 4 wire DJI setup but did find a naza gps for $25 and that’s cheaper than the hassle of swapping FC so I’ll try that.  Thanks again

**Comment by teckel12** [comment]
Yeah, just get a clone DJI NAZA GPS is what I was suggesting. I've even seen actual DJI models for about $35.

**Comment by Jawnv71** [comment]
Yep. That’s the plan. On order. I’ll let you know if it works!  Thanks again!

**Comment by Jawnv71** [comment]
Works like a charm.  Thanks again guys!

**Comment by teckel12** [comment]
@Jawnv71 Now the problem will be how poorly the GPS works with the interference with the Runcam Swift.

**Comment by Jawnv71** [comment]
Oh yea, that came out right away.

**Comment by Dronefpvpassion** [comment]
Bonjour je débute das le fpv et suis aussi détenteur d un ts215.
J aimerai intégrer un beitian n-220 sur mon quad mais étant débutant je n ai aucune idée des soudure a faire.
Merci d avance
