### ISSUE TITLE
Configurator 2.0.RC3 & iNav 2.0.RC4 "Has flaps"

### ISSUE THREAD

**Issue by Artyum** [iNavFlight/inav#3667]
Hi, "Has flaps" for Airplane mixer can't be saved. Also no "Flaps" in Modes.
Regards!

**Comment by shellixyz** [comment]
This has already been fixed: https://github.com/iNavFlight/inav-configurator/pull/546

It will be in the RC4 of the configurator

**Comment by Artyum** [comment]
I thought so, it was already reported and fixed.. so let's wait.
