### ISSUE TITLE
Slack channel link is dead

### ISSUE THREAD

**Issue by expipiplus1** [iNavFlight/inav#3669]
The link to https://inavflight.signup.team/ as found in the readme refuses to connect.

**Comment by shellixyz** [comment]
It has already been updated in the dev branch. The dev branch will be merged in the master branch soon when 2.0 is released. The right link is https://publicslack.com/slacks/inavflight/invites/new. This issue can be closed.

**Comment by expipiplus1** [comment]
Great, thanks!
