### ISSUE TITLE
Feature Request : Autoland in a straight line

### ISSUE THREAD

**Issue by PaulBizard** [iNavFlight/inav#3670]
_Is this a new feature request?_ YES

Hi everybody, just chiming in. I just bought my first INAV flight controller and was wondering if anybody ever considered the "Autoland in a straight line" mode.

See the drawing attached below.
![autoland](https://user-images.githubusercontent.com/20450875/43352974-32dfae2c-922d-11e8-8467-073a2c774695.jpg)

The user would just specify the impact point coordinates, the direction of the landing, the initial altitude, the glide slope and the radius of the two Heading Alignment Cylinders.

Paul

**Comment by hali9** [comment]
Yes. https://github.com/iNavFlight/inav/issues/1814

**Comment by PaulBizard** [comment]
Thanks hali9, I've had a look at the previous idea.

The algorithm I suggest is the following:

1/ Lateral guidance: tangent the nearest cylinder (if inside then head straight until outside of cylinder). Longitudinal guidance: go to the specified altitude.

2/ If aligned with the runway and if at the good altitude then start glide to the runway.

**Comment by david-ng-hk** [comment]
@digitalentity @DzikuVx

Please, please implement this

Look at my close call at iNav 2.0, circle fail safe landing does not work in many of the places we flight.
( OMG, I almost hit a running car )
https://www.youtube.com/watch?v=D_A03HuJ-4s

Best if we could pre-set this "landing strip, start point, end point" in iNav configurator (landing strip 1 & 2 & 3),
then when in fail safe, the plane can make it's own landing direction/speed/... decision according to the wind/battery/... condition

Thank you in advance.

**Comment by teckel12** [comment]
@davidngrc I believe #1814 is basically the same request which is still open. So there's no reason to dilute it by having two issues open.
