### ISSUE TITLE
Softserial not working on Omnibus f4 pro v3 after 2.0rc4 update

### ISSUE THREAD

**Issue by bokie1** [iNavFlight/inav#3672]
I tried updating my omnibus f4 pro v3 to 2.0rc4 from 1.9.1 but telemetry is not working anymore. I have frsky rx on soft serial 1 port. Didn't change anything on the wing, just the fw.
Already tries setting up from scratch, didn't work. Also tried copying diff, didn't work also. 
I have another wing but with omnibus f4 v3, everything still works when I upgraded to 2.0rc4. Only issue I got on omnibus f4v3 after update is the ps, but that's on another thread already.
Any suggestions.

**Comment by teckel12** [comment]
@bokie1 What RX do you have? On one quad with an Omnibus F4 Pro v3 that uses an XSR RX, I needed to `set smartport_uart_unidir = ON` for telemetry to function. With another quad with the same FC and very similar hardware (other than the RX) I could leave this as `OFF` and it would work.

I opened a ticket for this but haven't had time to investigate further.

**Comment by bokie1** [comment]
@teckel12 I have r9 slim.

I tried set telemetry_inverted = ON or OFF
and/or
set smartport_uart_unidir = ON or OFF

Still, nothing.

**Comment by teckel12** [comment]
@bokie1 A `diff` would be helpful.

**Comment by bokie1** [comment]
Entering CLI Mode, type 'exit' to return, or 'help'

# diff

# version
# INAV/OMNIBUSF4PRO 2.0.0 Jul 14 2018 / 22:40:31 (f2cf315ad)

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix 0 0 0 50 0
smix 1 1 0 50 0
smix 2 0 1 50 0
smix 3 1 1 -50 0
smix 4 2 6 100 0
smix 5 3 11 100 0

# servo
servo 0 1000 2000 1500 -100
servo 1 1000 2000 1500 -100

# feature
feature -BLACKBOX
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 64 115200 38400 0 115200
serial 5 2 115200 38400 0 115200
serial 30 32 115200 38400 57600 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1350 2075
aux 1 1 1 1850 2100
aux 2 2 1 1375 1600
aux 3 3 4 1700 2100
aux 4 9 4 1300 1700
aux 5 8 2 1350 1675
aux 6 10 6 1875 2100
aux 7 14 6 1400 1625
aux 8 27 5 1300 1700
aux 9 28 5 1700 2100
aux 10 11 2 1375 1625
aux 11 15 3 1275 1675
aux 12 18 2 1875 2100

# adjrange

# rxrange

# osd_layout
osd_layout 0 0 24 2 V
osd_layout 0 1 8 11 V
osd_layout 0 3 8 6 H
osd_layout 0 4 8 6 H
osd_layout 0 7 20 0 V
osd_layout 0 8 2 0 V
osd_layout 0 9 22 4 V
osd_layout 0 11 15 11 V
osd_layout 0 12 1 4 H
osd_layout 0 13 2 6 V
osd_layout 0 14 23 3 V
osd_layout 0 15 23 6 V
osd_layout 0 20 16 1 V
osd_layout 0 21 2 1 V
osd_layout 0 22 14 3 V
osd_layout 0 23 2 2 V
osd_layout 0 24 10 2 H
osd_layout 0 28 22 11 V
osd_layout 0 30 1 12 V
osd_layout 0 34 10 2 V
osd_layout 0 40 2 3 V
osd_layout 0 44 0 0 V
osd_layout 0 45 0 0 V

# master
set acc_hardware = MPU6000
set acczero_x = 85
set acczero_y = -14
set acczero_z = 79
set accgain_x = 4121
set accgain_y = 4088
set accgain_z = 4058
set mag_hardware = NONE
set mag_declination = -550
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = SERIAL
set rssi_channel = 16
set serialrx_provider = SBUS
set min_throttle = 1100
set max_throttle = 2000
set motor_pwm_rate = 2000
set motor_pwm_protocol = MULTISHOT
set failsafe_procedure = RTH
set align_board_roll = 50
set align_board_yaw = 2700
set vbat_scale = 1110
set current_meter_scale = 423
set platform_type = AIRPLANE
set model_preview_type = 8
set small_angle = 180
set auto_disarm_delay = 30
set gps_sbas_mode = WAAS
set deadband = 7
set yaw_deadband = 8
set nav_min_rth_distance = 5000
set nav_rth_climb_first = OFF
set nav_rth_allow_landing = NEVER
set nav_rth_altitude = 6000
set nav_fw_bank_angle = 30
set nav_fw_loiter_radius = 4000
set nav_fw_launch_velocity = 100
set nav_fw_launch_accel = 1500
set nav_fw_launch_max_angle = 40
set nav_fw_launch_detect_time = 30
set nav_fw_launch_thr = 1900
set nav_fw_launch_motor_delay = 300
set nav_fw_launch_spinup_time = 500
set nav_fw_launch_min_time = 10000
set nav_fw_launch_timeout = 10000
set nav_fw_launch_climb_angle = 22
set smartport_fuel_unit = PERCENT
set osd_video_system = NTSC
set osd_rssi_alarm = 35
set osd_time_alarm = 20
set osd_alt_alarm = 1000
set osd_dist_alarm = 10000
set osd_neg_alt_alarm = 25
set osd_crosshairs_style = AIRCRAFT
set osd_left_sidebar_scroll = GROUND_SPEED
set osd_right_sidebar_scroll = ALTITUDE
set osd_sidebar_scroll_arrows = ON
set osd_coordinate_digits = 10
set name = bokie_s800v2_1

# profile
profile 1

set fw_i_pitch = 11
set fw_ff_pitch = 51
set fw_p_roll = 3
set fw_i_roll = 5
set fw_ff_roll = 35
set fw_p_yaw = 50
set fw_i_yaw = 45
set fw_ff_yaw = 0
set max_angle_inclination_rll = 750
set max_angle_inclination_pit = 750
set rc_expo = 80
set roll_rate = 35
set pitch_rate = 30
set manual_rc_expo = 80
set manual_rc_yaw_expo = 30

# battery_profile
battery_profile 1

set battery_capacity = 2200
set battery_capacity_warning = 880
set battery_capacity_critical = 440

#

**Comment by bokie1** [comment]
I tried the same fw on another omnibus f4 pro v3 board and the same result. So it's not the board. Another thing I tested was the same fw but on a clone omnibus f4 pro v2, lo and behold, everything works. 
I can conclude now that it's only affecting the omnibus f4 pro v3 boards.
I hope someone can take a look at this issue.

**Comment by teckel12** [comment]
@bokie1 I have two omnibus f4 pro v3 and have no trouble with SmartPort telemetry. The only issue I have is with my XSR-M Rx I need to `set smartport_uart_unidir = ON`. I'm thinking that may be the issue you're having too. Maybe that setting doesn't fix your issue, but it could be some kind of timing thing where certain FC or certain Rx have issues.

**Comment by bokie1** [comment]
@teckel12, are you using r9 slim/+/mini rx?

**Comment by teckel12** [comment]
XSR-M and X4R-SB and my FC isn't a clone. A real Omnibus F4 Pro.

**Comment by bokie1** [comment]
Oh ok. Maybe try to replicate it once you have an r9 series rx. It also works with x series rx for me.

**Comment by bokie1** [comment]
It now works on rc6.
