### ISSUE TITLE
AKK Ultimate X2 Smart Audio Problem with F35 Lightning FC

### ISSUE THREAD

**Issue by haksarion** [iNavFlight/inav#3681]
### Board and Version
Furious FPV F35 Lightning FC Full Options
Inav 2.0 RC 4

### Behavior
When I turn on "TBS Smart Audio" on Port 4 in Ports Tab Smart Audio seems to work first but if I try to change any settings in OSD it does not change anything.
Secondly if I use TBS Smartaudio the new Feature that automatically powers VTX Power low and high has only 4 levels.

Greetings Hakan

**Comment by lucaslabs** [comment]
Second this one, also is not working on RC5. Please fix it. 
Thanks!

**Comment by lucaslabs** [comment]
hey @stronnag @fiam what info do we need to provide so you can fix this one? 😃

**Comment by digitalentity** [comment]
2.0-RC6 SA bugs seem to be have common root cause. Tracked in metabug #3753
