### ISSUE TITLE
Feature Request, Show last summary screen in OSD Stick Menu

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3685]
I am on iNav 2.0.0RC4
I just finish a flight, disarm, I saw the summary for few seconds.
and remember I did not press record, so I walk away for my phone to take a photo.

Then I talk to someone...

Came back, the summary still there, but maybe I press/move something or summary timeout, the summary screen is gone.

I then try the “OSD Stick Menu” by 
Throttle stick mid, Yaw stick left, Pitch stick up, Roll stick centered

I found no “last summary option”.
Help...

**Comment by Pairan** [comment]
... got exactly the same problem ... then I arm and disarm and half of the stats are gone :)

so, yes, that would be a nice feature and I would like to have that too.
