### ISSUE TITLE
My F4-CTR flight controller could not open the barometer and direction compass, both icons are lit red.

### ISSUE THREAD

**Issue by chenxianan** [iNavFlight/inav#3686]
Refresh the latest 1.9.1 matekf405 firmware, connect to the GPS and direction compass (beitian BN-880), open the control station to the flight controller to display the direction compass, and the barometer is illuminated red. I have two options to rotate the barometer and direction compass separately in the configuration item. The I2C error in the lower left corner shows the 205.5.200.216 prompt. GPS is useful. After the configuration is correct, the GPS can read the location information. When I don't have a power battery connected, it only lights up red. But I turned off the barometer and direction compass options, I2C shows 000, so I don't understand where it appears. Ask your question, (GPS rx connection controller tx, tx connection rx.sda connection sda, scl connection scl.v5 connection v5, gnd connection gnd)[
![360 20180801233429656](https://user-images.githubusercontent.com/42005363/43535180-dd0cc59e-95eb-11e8-9c69-4b290d5072e1.jpg)
![360 20180801232746646](https://user-images.githubusercontent.com/42005363/43535212-f38fc8e8-95eb-11e8-9fda-40298c8b7b23.jpg)
![Uploading 360截图20180801232641908.jpg…]()
![360 20180801232607886](https://user-images.githubusercontent.com/42005363/43535261-1222855c-95ec-11e8-9b78-ad4dc08bbc1f.jpg)

](url)

**Comment by Tygrys-1** [comment]
Is I2C properly terminated/does it have pullup resistors? 
Edit: It should be, on Matek boards there are 4k7 pullups on SDA/SCL.

You should also not use the LED Strip connection, it is shared with I2C on the board and cannot be used together.

**Comment by Tygrys-1** [comment]
Try connecting the battery. #3688

**Comment by chenxianan** [comment]
问题已经解决，是方向罗盘硬件损害更换之后就没有问题了，而且LED不能悍接在LED位置要焊接在s5的位置
