### ISSUE TITLE
Impossible arm the flying wing with OLED installed

### ISSUE THREAD

**Issue by ERLudovico** [iNavFlight/inav#3687]
I am on iNav 1.9.1
Board: DYS F4 Pro
UART2: RX FrSKY V8fr-ii (with PPM encoder)
UART3: OLED1306
UART6: GPS MTK

The OLED works fine and coexist friendly with GPS and RX.
All the information are displayed without any error.
But I can't ARM the board.
If I turn off the board, detach the OLED to the board and turn the board on, wait GPS got a enough sign, the board can ARM without any issue.
 
Could someone please tell me if this configuration is possible?

**Comment by ERLudovico** [comment]
Any input I appreciate!

**Comment by Tygrys-1** [comment]
Check the wiki on how to get the reason for not arming.
