### ISSUE TITLE
maps inav

### ISSUE THREAD

**Issue by jose-elmacg** [iNavFlight/inav#3691]
Hi, I would like to know if there is any version of inav configurator that does not have openstreet maps. someversion of goglee earth or similar since I can not work the points of the route in the flight field since it has no streets and I need a version with satellite view. or some plugin to change it.
Thank you

**Comment by stronnag** [comment]
This question is a configurator support question, not a FC question; it does not belong in this tracker.

In any case, it's already been answered on RCG 2018-08-01, and the answer is still no.

You can use a 3rd party planner with satellite maps.
