### ISSUE TITLE
BUG: 2.0.0RC4 Incorrect OSD RSSI value if transmitter is power off and use RSSI channel (like channel 16)

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3692]
Actually, I am on the latest development build, just compile it.

For R9 mini, and others, it does not come with a analog RSSI pin/pad.
so it use transmitter (X9D) channel 16 as RSSI value.

How to test?
1. power off your transmitter (X9D)
2. connect your R9 mini to the FC, and setup channel 16 as RSSI channel
3. setup OSD, show RSSI value
4. power up your FC, you will see in OSD, the RSSI value is 49
    which is not correct, it should be 0?

5. if I power on my transmitter (X9D), the RSSI will go back to 99. which is correct.
6. power off my transmitter (X9D) again, now OSD show it is in failsafe mode, but the RSSI still show 99, which is NOT correct, should be 0, right?

**Comment by shellixyz** [comment]
It is displaying 49 when you power up the board without the transmitter on is because the default value of the channels is 1500 and is is still displaying 99 when you power it off because the channel is frozen when in failsafe.

Maybe we should display 0 when in failsafe ?

**Comment by david-ng-hk** [comment]
yes
1) in FS, set the raw RSSI channel value to be 0
or
2) when output to the OSD, then use if RSSI channel is set, then set the OSD rssi value to 0
which one is better?

**Comment by digitalentity** [comment]
Caused by the fact that in 2.0 `rcData` is no longer updated if receiver is in failsafe. Fix pending.

**Comment by digitalentity** [comment]
Fix ready. Closing
