### ISSUE TITLE
Bug: 2.0.0RC4 FPORT telemetry sensor ID incorrect

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3693]
I am using R9 mini with FPORT on a ominibus f4 pro v2 board.

I am connecting a bluetooth module to X9D, and use its sport mirror function to output telemetry to android phone.
after decoding the sport bluetooth data, all the telemetry sensor ID is 0

I did not have such problem while I am using sbus, 
in sbus, the sensor are all different.

**Comment by davidngrc** [comment]
wait, I might be wrong.

**Comment by david-ng-hk** [comment]
the frame type, data ID, and data value are all correct, only sensor is 0, I really think this is a bug.

**Comment by Allerhopp** [comment]
What sensor ID shows X9D telemetry screen?

**Comment by david-ng-hk** [comment]
the sensor id show on X9D are all 1
