### ISSUE TITLE
Feature Request: Convert a video IN from NTSC to video out PAL

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3695]
we may have many different fpv camera.
some have NTSC PAL switch, allow you to switching between them.
some do not come with a hardware switch, hard code to PAL or NTSC

if we set the OSD in iNav, like in PAL format, but the fpv camera is in NTSC format.
then the bottom of the OSD will somehow appear on top, and overlap the content already on top of the OSD.

could we do it in a programming way, convert the video output format?
like in OSD tab,
we choose "PAL", then no matter what the fpv camera setting PAL or NTSC, we will have a PAL video out.
vice versa

**Comment by DzikuVx** [comment]
Hardware lacks such a possibility
