### ISSUE TITLE
NAZE 32 accelerometer in INAV not callibrating

### ISSUE THREAD

**Issue by smayoh** [iNavFlight/inav#3698]
I have a naze32 rev 6 board full version. I have flashed the chip with naze 1.7.3. I click on calibrate accelerometer. After about two seconds it shows calibrate finished but in setup it still shows up as not calibrated. Frustrating!! Tried older versions of naze firmware without any luck. Can anyone assist?

**Comment by giacomo892** [comment]
Have you red this? https://github.com/iNavFlight/inav/wiki/Sensor-calibration

**Comment by digitalentity** [comment]
RTM. Closing.
