### ISSUE TITLE
Can I use the Alt Hold mode for gps? (not barometer)

### ISSUE THREAD

**Issue by whakru** [iNavFlight/inav#3707]
Can I use the Alt Hold mode for gps?
Without barometer, only gps
Matek f722 - I spoiled my barometer when I protected the board.
I would like to have Alt Hold in height, which gives gps

**Comment by shellixyz** [comment]
Only for planes, not multirotors.

**Comment by whakru** [comment]
What about these values?
![mytg62uobje 1](https://user-images.githubusercontent.com/22603145/43788397-f87f4b2e-9a75-11e8-8fe7-bd52e5e21850.jpg)

**Comment by digitalentity** [comment]
Multirotor altitude hold requires barometer.

**Comment by golffer** [comment]
what's recommend number for these 2 weight? QAV 250, Omnibus F4 V3.
When it is 0.35 and 0.2, quadcopter jump up. 
When it is 0.5 and 0, quadcopter drop slowly to ground.
Gonna crazy....

**Comment by giacomo892** [comment]
Leave to default and isolate the barometer better @golffer 
Changing numbers randomly won't help
