### ISSUE TITLE
Motors spins at lowest stick positition when armed ,  even the function is set OFF in config. Omnibus F3CLONE.

### ISSUE THREAD

**Issue by petrweigl** [iNavFlight/inav#3720]
respectively the function "don`t spin the motors when armed" is set ON on configurator
but the motors spins when armed (and the throttle stick is at lowest position)

inav 2.0. RC4
in inav 1.9  works fine

Omnibus F3
inav configurator 2.0 RC3

**Comment by giacomo892** [comment]
airmode have priority over motor stop. Read the documentation please. 
https://github.com/iNavFlight/inav/wiki/2.0.0-Release-Notes
It is even in bold.
