### ISSUE TITLE
Quad flies away after arming pos hold!

### ISSUE THREAD

**Issue by Xnoopeex** [iNavFlight/inav#3721]
My Quad:
4xEmax  Rs2205
OmnibusF4V3
version:
 INAV/OMNIBUSF4V3 1.9.1 Apr 21 2018 / 13:13:58 (03a5c1922)
 
-Alt Hold works with+-1meter
-Arming Pos Hold: 2 sec holding pos and then flying away in one direction!
-mag is far away from metal/power cable

hope someone can help me with my log file and config file.
Thanks in advance
XnoopeeX
[GPS Crash log.TXT](https://github.com/iNavFlight/inav/files/2272196/GPS.Crash.log.TXT)
[log,config txt.zip](https://github.com/iNavFlight/inav/files/2272203/log.config.txt.zip)

**Comment by teckel12** [comment]
Compass not oriented correctly?

**Comment by DzikuVx** [comment]
Such a fly away is compass related. Wrong orientation, damaged unit. Also in your log there is a clear correlation between throttle position and magnetometer readout. That mean mag. sensor is too close to power lines.
