### ISSUE TITLE
Crossfire seems to get stuck in failsafe.

### ISSUE THREAD

**Issue by dustin** [iNavFlight/inav#3729]
### Board and Version
[Omnibus F3](https://www.banggood.com/30-5-30-5mm-Betaflight-Omnibus-STM32F3-F3-Pro-Flight-Controller-Built-in-OSD-BEC-Current-sensor-for-RC-Drone-p-1156615.html)

2.0 RC3

_Use CLI command `version` and put its output here_
INAV/OMNIBUS 2.0.0 Jun 29 2018 / 12:33:58 (a8415e89c)

### Behavior
I encountered a failsafe at distance (6.5km).  The failsafe itself wasn't particularly surprising -- I'm using a crossfire micro RX with an immortal T antenna with vertical polarization.  I was running the crossfire TX at 100mW and rolled the plane.  This caused the signal to drop considerably, taking LQ with it, and then FS kicked in.

Failsafe leveled the plane and started flying it back.

Expected:

Signal to resume and the FC to let me take over again.

Actual:

FC remained in failsafe for just over three minutes before allowing me to take over again.

It appears that the FC was not seeing CRSF for those three minutes.  RSSI on the OSD was stuck at 51 and then started moving around again.  I was able to take over and continue flying my plane for a bit.

Note that the crossfire signal itself was fine.  Except  for the incident that actually induced failsafe, my signal was fine for the majority of the time I was stuck in failsafe.  You can see approximately how this looked in the following image (taken from recorded telemetry on my Taranis).

<img width="1119" alt="companion_log_viewer" src="https://user-images.githubusercontent.com/1779/43998512-11fddaf0-9dac-11e8-80ce-65e6ea3a13d6.png">

Unfortunately, I don't have any blackbox logging for this plane.  This has happened more than once, though (the first time it happened, it took even longer to give me back control).  I'm wondering if, perhaps, there's some CPU starvation or something that's preventing CRSF and FS from coexisting peacefully.

**Comment by dustin** [comment]
It's worth noting that the yellow line in that image is distance.  I was getting telemetry from the FC, but it wasn't recognizing a control signal.

**Comment by digitalentity** [comment]
How is receiver connected? CRSF or SBUS?

**Comment by dustin** [comment]
This is CRSF.  The [config I was using](https://www.evernote.com/l/AAJ2VfCwFzRJk75M9-XV-EbRPMEDqUsF1Wg) is available for perusing.

**Comment by dustin** [comment]
I've replaced the RX and wiring.  I believe it was a local issue.
