### ISSUE TITLE
OMNI NXT F7 orientation problem

### ISSUE THREAD

**Issue by CcLaFleche** [iNavFlight/inav#3731]
Hi,
Thanks for your work but there is a problem with the orientation of this board.

**Comment by shellixyz** [comment]
I think a bit more info would be helpful to fix the issue...

**Comment by CcLaFleche** [comment]
I have to put cw180 accelero and gyro for have correct mouvements in first menu in the configurator but when i armed the multirotor turn down and broke my motors and props.

When i calibrate the accelerometer the figure valided is not the same position of my fc, even if i do it with the default values.

**Comment by digitalentity** [comment]
@CcLaFleche generally you shouldn't touch `align_acc` and use board alignment. By blindly adjusting `align_acc` you created a misalignment between gyro and accelerometer which is the root cause of your issue.

**Comment by CcLaFleche** [comment]
it's the same with the original settings, hence my approach.
I think the original alignment is not good ...
can we choose one of two gyro because I did not succeed.
can we also use an external baro

**Comment by digitalentity** [comment]
The board doesn't have the direction arrow. Make sure you don't touch acc/gyro alignment blindly. Boards that have onboard baro generally can't use external one. You can chose one of two gyros using `gyro_to_use` CLI setting on boards that support the feature.

**Comment by CcLaFleche** [comment]
how can I do so that the controller turns in the same direction as in the configurator WITH the original settings because this is not the case.
With betaflight I do not have this problem.

If I doused the baro, I can use another on scl and sda

the second gyro (32k compatible) doesn't work

**Comment by digitalentity** [comment]
Re board alignment: RTFM - https://github.com/iNavFlight/inav/wiki/Sensor-calibration#board-orientation-and-level-calibration

Re second gyro - open a separate issue and provide relevant details - dump, link to where you purchased the board, photos etc.

**Comment by CcLaFleche** [comment]
If I doused the baro, I can use another on scl and sda ?

**Comment by digitalentity** [comment]
Baro on NXT board is on SPI bus. You can't connect another one to I2C

**Comment by CcLaFleche** [comment]
Pour resumer :
il me faut utiliser un controleur de vol dépourvu de baro mais possédant un I2C

**Comment by CcLaFleche** [comment]
I have to use a flight controller without a baro but with an I2C

**Comment by CcLaFleche** [comment]
Like images are better than words ...
I made 2 videos to illustrate my subject which does not seem to be understood.

https://www.youtube.com/watch?v=Fyg5QAb1zJ8

https://www.youtube.com/watch?v=X7NTtCQ53zQ

**Comment by digitalentity** [comment]
As indicated before - read the docs and set `align_board_yaw` properly. Prior to doing that make sure acc and gyro alignment are at defaults.

**Comment by CcLaFleche** [comment]
i will test 180 yaw for board and fly.
I will comfirm it to you
Could you add programmation for use and external baro for better sensor as BMP280 ?
Why do not use dshot on inav ?

**Comment by CcLaFleche** [comment]
It's ok...
