### ISSUE TITLE
[2.0.0 RC6] Power level on disarm and smartaudio not working

### ISSUE THREAD

**Issue by clemtrinc** [iNavFlight/inav#3734]
Using an omnibus F4 with ledstrip5, tried enabling low power on disarm to always, with a TBS Unify pro v3, triple checked my wiring and option is ON in cli dump, power setting to 1.
When I power the setup, the vtx heats like crazy( probably 800mw).

Even if I change the power setting in the OSD, i can see the change is effective in the OSD but the vtx keeps heating like an oven.

Didn't have any power level issue with 1.9.1.

**Comment by digitalentity** [comment]
@clemtrinc a dump would help

**Comment by digitalentity** [comment]
Can you test if the issue is present on 2.0-RC3?

**Comment by digitalentity** [comment]
2.0-RC6 SA bugs seem to be have common root cause. Tracked in metabug #3753
