### ISSUE TITLE
Inav 1.9.3  Horizon mode -> has limitation on banking angle and can do flips.

### ISSUE THREAD

**Issue by Koestel** [iNavFlight/inav#3735]
Hi,
My Horizon has limitation on banking angle, as soon as I try to take a turn my wing is repositioned flat abruptly. It's no normal in Horizon mode...

Thanks

Koestel

**Comment by Tygrys-1** [comment]
The Horizon mode is a combination of Angle mode near the center of the stick and Acro mode when you move stick further. As bank limits are for Angle mode, they will have no effect on the Horizon. When you move the stick of center position the Acro mode is activated and you can do the flips or other acro stuff.

I found that the transition between modes is not smooth.

**Comment by Koestel** [comment]
Thanks
