### ISSUE TITLE
FPort issue on Matek F405 Wing FC running INav 2.0.0RC6

### ISSUE THREAD

**Issue by Butscut** [iNavFlight/inav#3743]
OK, I have looked everywhere for a solution to this but I simply cannot find one. 

Setup as follows;

R9 mini rx running latest FPort firmware
Matek F405 wing FC 
INav 2.0.0. RC6

Problem is that I simply cannot get the board to recognise the FPort signal as a seria reciever. 
I have attempted connecting the R9 mini FPort pad to the F405 TX2 pad and set the ports tab to serial RX and config tab to FPort but no joy. I have also tried connecting the FPort pad from the RX to the TX2 pad on the FC and set the softserial to serial RX in the ports tab but again no joy. 
I then went mad and tried connecting the RX to UART1 setting this to serial RX and again no joy. 
I subsequently tried all of the above setups with all possible combinations of serialrx_halfduplex ON/OFF and serialrx_inversion ON/OFF. 

NOTHING WORKS!!!!

At worst I get no stick movements at all in the receiver tab, at best I get no movements in the rx tab but I do get a fluttering left hand elevon. 

WTF is going on. 

IS it too much to expect a serial connection between this RX and FC and telemetry. 

FWIW - I have also been unable to get telemetry working through softserial TX2 when the RX was connected as SBUS with the SBUS firmware. 

Any help would be appreciated. 

Note that I have not included a dump of the CLI as I have so many combinations it would be meaningless unless someone wanted to see something specific. 

Please help

**Comment by david-ng-hk** [comment]
could you get it to work in iNav 2.0RC4? or even iNav 1.91?
try the solution on my last post here https://github.com/iNavFlight/inav/issues/3344

**Comment by cmenard** [comment]
I'm using FPort with an R-XSR on 2.0RC6 just fine.  I'm waiting on my R9 mini's to get here.  Make sure to use the uninverted s.port pad on the receiver for the connection.  *update* do the R9 mini's HAVE an uninverted pad like the R-XSR??

**Comment by Butscut** [comment]
@davidngrc 

I was following your thread #3344 with great interest and spent most of last night trying to replicate your setup, but it failed.  I am very keen to understand your exact setup compared to mine as they appear very similar. FYI I have the following;

Matek F405 wing 
UART 1 - Spare
UART 2 - R9 mini (trying to get this working as discussed above)
UART 3 - Smart Audio
UART 4 - GPS
UART 5 - FPV Camera setting Control
UART 6 - Spare
Softserial - Tried using this for Smart Port telemetry with SBUS but had no luck getting it to work either)

Taranis is running OpenTX 2.2.2
Firmware on Taranis R9 module is 180329
Firmware on R9 mini is 180629 (for F.Port) or 180716 (for SBus)

What version of iNav are you running?

@cmenard R9 mini's do not have an uninverted pad like other receivers so this cannot work.

**Comment by cmenard** [comment]
@Butscut you're right.  I plan to use an R9 mini with a @MATEKSYS F411 wing FC.  Just did a custom build with LED as Softserial 2 so I won't lose SmartAudio using Sbus and S.Port.

**Comment by david-ng-hk** [comment]
@Butscut Please note,  http://www.mateksys.com/wp-content/uploads/2018/04/F405-WING_C1.jpg
tx2 pin is NOT UART2
tx2 pin is softserial1

**Comment by Butscut** [comment]
@davidngrc Sorry. My poor explanation. I understand that the TX2 pad is softserial only not UART 2. 

I tried to set up the R9 mini using this http://www.mateksys.com/wp-content/uploads/2018/04/F405-WING_C1.jpg setup / configuration, and whilst I could get the SBus working, telemetry via softserial TX2 pad just wouldn't work. 

Can you please advise what iNav version you are running and what your configuration looks like? Keen to understand how yours is working (on FPort) and mine is not when they appear identical setups

**Comment by chhada** [comment]
I also follow #3344 I'm having similar issue.
I managed to get the receiver to work with inav but i have experience a wired situation. 
All channels shown as they are normally working (roll, pitch value at mid, throttle at the min and so on) but when i move the stick on Taranis nothing move on inav a long wait then it move on inav receiver screen. i continue to experiment with it, i learned that they is some kind of long delay going on. 

RX: R9 mini pin connected to SPORT/FPORT (layout on manual)
I set my Softserial1 to Serial RX (ON) 
Under config tap Fport is selected
CLI set SET serialrx_inverted and SET serialrx_halfduplex to ON 

Confirm Telemetry working/RX haft working(problem address above)

Am i missing something? 
Anything will be a help,

I also order the R9 Slim Plus let try to wire this up, see if it is going to work. If not will back to the X8R Thanks

**Comment by teckel12** [comment]
@chhada Honestly, I've abandoned using FPort with F4 processors. There's no real advantage over inverted SBUS/S.Port that works without an issue. I'll take a stab at F.Port again when I switch to F7 FC that support UART inversion.

**Comment by chhada** [comment]
@teckel12 The tiny footprint and able to work with R9M long range was the hook, i should of research a little more before hand. I thought it is just like plug and play. For now, I hope someone find the problem at it heart and fix it :)

**Comment by david-ng-hk** [comment]
@Butscut the config I am using (the attached dump file in below link), and iNav version are all in the https://github.com/iNavFlight/inav/issues/3344#issuecomment-409627973 

if you can not even get the sbus + sport to work, please follow this video
https://www.youtube.com/watch?v=tRI_z7d2Z6U

if you still can not get it to work, and you know how to set sbus+sport, there is ahigh chance your f405 wing board might be damage.
do you have other board to do the test?

So far, FPORT only work with softseral port without an inverter, that is my test result in https://github.com/iNavFlight/inav/issues/3344

@cmenard so far, no one found a uninverted pin in R9 mini

@chhada that is odd, you get FPORT telemetry, but no stick movement? I had never encouter this.
could you just use the dump file I post? and see what happen? https://github.com/iNavFlight/inav/issues/3344#issuecomment-409627973 
1) open the attached txt
2) copy all the text
3) paste it in CLI, hit ENTER key
4) after that, the board will reboot.
5) now, got stick movement and telemetry?

**Comment by chhada** [comment]
@davidngrc as I went through my sleeplessness night I thought of how I flash the firmware to the R9 MINI, I think I might have flash the regular firmware not an F.port one. I think what I did was I flash both FW once after another, the regular FW might have been flash last. My though at the time that those two are needed. So can you confirm that firmware can be run one at time on the RX board, correct? 

My next bet is when I got home I am going to flash the FW and try it again.

**Comment by Butscut** [comment]
All. Thanks heaps for your suggestions and guidance over the past few days. I finally got this issue fixed, and must sadly report that it was user error that I was fighting. I had inadvertently flashed sbus firmware when trying to get Fport working and visa vera when trying to setup Fport. 
My solution was as initially described using Sbus + Sport telemetry on TX2 softserial. I think with all the mucking around I had also set serialrx_inverted and serialrx_halfduplex to the wrong values. 
It is all now working 100% with full telemetry. 
I have set up the inav LUA script (excellent i must say) and the BF LUA to control things like VTX etc. 
Thanks again for your support. 
Great community. 

Over and out

**Comment by teckel12** [comment]
@chhada Doesn't the R9M work with SBUS too? I thought it did that be default. Most FrSky Rx can do SBUS or FPort.

**Comment by teckel12** [comment]
@Butscut Glad you're enjoying INAV Lua Telemetry. Version 1.4 will be a huge release. Trying hard to get it to work at the same time as a fork of BF Lua that only does VTx control.

**Comment by AndrewBryanScott** [comment]
@Butscut hi man, please help dum it down for me, i have a R9 Mini flashed with fport lbt EU FW, do i connect to the sbs port or the Tx2, Inav 2.0.1 FW on matek F405 Wing. and then run in CLI
set serialrx_provider = FPORT
set serialrx_inverted = ON
set serialrx_halfduplex = ON
how can i be sure the Tx2 is working and i don't have a bum board are the any commands i can run to see if it working. cant get SBUS/Sport working together iether only Sbus work for stick controls. I am at the point where i want to order an R9 MM becuase i am loosing my patience but also worried that wont work.

**Comment by MATEKSYS** [comment]
http://www.mateksys.com/?p=4488 




Matek_Tech
 
From: AndrewBryanScott
Date: 2018-12-01 18:55
To: iNavFlight/inav
CC: MATEKSYS; Mention
Subject: Re: [iNavFlight/inav] FPort issue on Matek F405 Wing FC running INav 2.0.0RC6 (#3743)
@Butscut hi man, please help dum it down for me, i have a R9 Mini flashed with fport lbt EU FW, do i connect to the sbs port or the Tx2, Inav 2.0.1 FW on matek F405 Wing. and then run in CLI
set serialrx_provider = FPORT
set serialrx_inverted = ON
set serialrx_halfduplex = ON
how can i be sure the Tx2 is working and i don't have a bum board are the any commands i can run to see if it working. cant get SBUS/Sport working together iether only Sbus work for stick controls. I am at the point where i want to order an R9 MM becuase i am loosing my patience but also worried that wont work.

**Comment by AndrewBryanScott** [comment]
Thanks Matek but that page done not show using an R9 mini and and F405Wing tried that this morning and no joy.

**Comment by Butscut** [comment]
@AndrewBryanScott 

Wire up as per this..... http://www.mateksys.com/wp-content/uploads/2018/04/F405-WING_C1.jpg

If you are using FPort simply connect the "SPort/FPort" pad on the R9 Mini to any TX pad on the FC. 
set serialrx_provider = FPORT
set serialrx_inverted = OFF
set serialrx_halfduplex = ON

**Comment by Xedos9er** [comment]
@Butscut 
No, that settings are wrong! I´ve done some testing the last few days on my F405Wing and found a working combination. Since I wanted to use F.Port on SBUS Pin with my R9MM, but there´s no way because somebody already mentioned that the SBUS pin has no bidirectional inverter. 
That are my findings:
R9MM S.Port -> SBUS IN on FC = controls ok, but no telemetry (testet with all ON/OFF inverted, halfduplex variants).
R9MM S.Port -> TX2 on FC = Controls + Telemetry working (inverted + halfduplex =ON and SerialRX enabled on softserial1; otherwise not working).

Is there a chance, that f.port will work on FC´s SBUS pin when using the inverted S.Port pin on the R9MM ?

BTW just for info:
TX2 = UART 2 TX when CPU softserial is DISABLED ! Otherwise its´s Softserial 1
SBUS = RX 2 inverted

**Comment by shellixyz** [comment]
> Is there a chance, that f.port will work on FC´s SBUS pin when using the inverted S.Port pin on the R9MM ?

It works with inverted F.Port but you need to connect it directly to the UART TX not the S.Bus pad

**Comment by Xedos9er** [comment]
> > Is there a chance, that f.port will work on FC´s SBUS pin when using the inverted S.Port pin on the R9MM ?
> 
> It works with inverted F.Port but you need to connect it directly to the UART TX not the S.Bus pad

Read carefully, I know that it works on TX, I postet the settings above. But I want to get it working on SBUS Pad

**Comment by teckel12** [comment]
@Xedos9er The SBUS pin is inverted but only one way. You need to use the uninverted UART pins instead.

With an F4 FC, you have restrictions and confusion as you can't control the inversion. Either use the UART pins or get an F7 FC which can do inversion on any port without a hardware inverter.

**Comment by AndrewBryanScott** [comment]
Hi all so I recently gave up on the mini and got an r9 mm funny thing is it works no problem at all me thinks i may have got a broken R9 Mini and that's why nothing worked any way my R9MM is using sbus and TX 2 and I have full control and telemtry.

**Comment by dangerg** [comment]
http://www.mateksys.com/?p=4488

**Comment by Xedos9er** [comment]
I have no more issue. Just get sure running f.port via hardware UART, not softserial!! Running on softserial will have bad glitches and fail-safe issues cause it's to slow.
I deactivated softserial on my f405wing and running f.port via TX2 pin using the "inverted" (hacked) s.port pin out on the R9MM wich is in real uninverted.
Absolutely stable now. In cli turn serial inverted and halfduplex on.

**Comment by teckel12** [comment]
:+1: this can be closed. Never use soft serial for RX (which would include F.Port).
