### ISSUE TITLE
AK8975 compass NOT recognised on Omnibus target

### ISSUE THREAD

**Issue by robertha64** [iNavFlight/inav#3745]
### Board and Version
Omnibus (F3) clone from Banggood
INAV 2.0.0 RC6 and custom compiled actual dev version - both same behavior

### Behavior
When upload new fw and attach GPS compass combo the external compass AK8975 (I2C) is not recognised and turns red.

The same configuration is working on fw 1.8 - compass is recognised and turns blue.

Try do dig in the source and find the AK8975 is not listed in the target.h for Omnibus (and other boards too - so it means this combo and compass will no longer be supported ?

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by shellixyz** [comment]
The AK8975 compass is not enabled in the default OMNIBUS build. Please try this: 
[inav_2.0.0_OMNIBUS_AK8975_mag_support.hex.zip](https://github.com/iNavFlight/inav/files/2295256/inav_2.0.0_OMNIBUS_AK8975_mag_support.hex.zip)

**Comment by robertha64** [comment]
@shellixyz Thank you, there was also issue with mag orientation, which should be fixed by merging this fix:
https://github.com/iNavFlight/inav/commit/29bde7c1eb39ae2daddc202b4aadd8752308374f
![ak8975fix](https://user-images.githubusercontent.com/39700425/44253094-f4222680-a1ed-11e8-80bb-19516dd24025.JPG)

I did test the mag on the 1.8 where it was detected fine, but orientation was wrong so I created issue hoping it will be cured in 2.0.

But when I am looking into actual dev branch on drivers/compass/AK8975.c the fix is not there ??

**Comment by robertha64** [comment]
Could you please build hex with 1.8 for Omnibus target including the fix as on picture above?
As I know everything is working on 1.8 except mag orientation I can test it in flight quickly for changes.

**Comment by digitalentity** [comment]
We are on 2.0 milestone. The fix you are referring to is merged.

**Comment by robertha64** [comment]
Thank you for info. Looking formward to try soon.

**Comment by robertha64** [comment]
@shellixyz I did install FW from the file you compile for me. Setup the config (did finish with mag orientation CW270 flip), test it and its fly without issue ! No more heading change when tilted, no more drift in poshold. Thank you and whole inav team. Great work.
[inav 2 diff.txt](https://github.com/iNavFlight/inav/files/2300140/inav.2.diff.txt)

**Comment by digitalentity** [comment]
@shellixyz can we make it a proper PR and have it merged into 2.1?

**Comment by fabio-hora** [comment]
Hi @shellixyz Could you please make this change for OmnibusF4V3 as well? Or perhaps generate a compiled version? Thank you very much!

**Comment by shellixyz** [comment]
Fix merged, closing

**Comment by robertha64** [comment]
I did check both development and master - AK8975 is commented out in target.h for OMNIBUS (not OMNIBUSF4). Probably because flash is nearly full. But this is no more issue for me as now I can build customized hex myself (did comment out other mags in target.h and left there AK8975 and QMC5883.

If anyone need the same adjustment just let me know and I could make the hex for you.

**Comment by AndresCL** [comment]
@robertha64
Can you let me know the path of the file you changed pls?

**Comment by robertha64** [comment]
inav / src / main / target / OMNIBUS / target.h 

its from master branch - unchanged, as I build it from local copy of the repository
