### ISSUE TITLE
PPM not working in iNav 2.0 any RC, working in 1.9.1

### ISSUE THREAD

**Issue by leonvuksic** [iNavFlight/inav#3746]
### Board and Version
Matek F722 STD
iNav 2.0 RC 1/2/3/4/5/6

### Behavior
PPM not working
Select PPM signal in Configuration, save and reboot, go to reciver tab

Tested and working in 1.9.1.

Could be configurator issue but I wouldn't speculate

**Comment by leonvuksic** [comment]
Any news soon?

**Comment by teckel12** [comment]
@leonvuksic Are you doing a full erase when going from 1.9.1 to 2.0.0 final?  Also, you should post a `diff` so it can be diagnosed further.

**Comment by leonvuksic** [comment]
yes, I will test the 2.0 final build now and post results :)

**Comment by leonvuksic** [comment]
Working in 2.0 final version, closed 👍
