### ISSUE TITLE
Status of compatibility with Flytron 10Hz GPS module V2 GPS

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav#3748]
I apologize if this should be posted elsewhere, but since it may not be compatible, I wanted to see how feasible it would be to implement compatibility.

Will this GPS work with iNav PNP?

http://www.flytron.com/osd-headtrackers/15-simpleosd-gps-module.html

**Comment by teckel12** [comment]
@VoicOfReason Probably no way to know if it doesn't say what GPS module it's using. It's probably BLOX, but that's a guess. And if it is, it may not be programmed correctly for INAV, so you may need to program it correctly first.

**Comment by stronnag** [comment]
"Standart MTK Commands for settings" --- whatever a Standart is. I tend not to buy stuff like that. But we dont' support MTK well, it at all.

**Comment by VoicOfReason** [comment]
Got it. Feel free to close this thread. Turns out this was a GPS module
from 2010.
