### ISSUE TITLE
smart audio on TX4 on MATECK F405 OSD not working any longer in 2.0.0.RC6

### ISSUE THREAD

**Issue by Sil20** [iNavFlight/inav#3752]
### Board and Version
Mateck F405OSD

### Behavior
After upgrading from RC3 to RC6 :
Havind saved a Diff command to put back all parameters
The VTX Smart audio interface was not working any longer.

After flashing back to RC3:
The VTX Smart audio interface was working normally

I did not try RC4 and RC5.

Here the file resulting from the diff command in RC.
[ZOHDDart_INave2.0.txt](https://github.com/iNavFlight/inav/files/2294123/ZOHDDart_INave2.0.txt)

**Comment by digitalentity** [comment]
Which TX are you using?

**Comment by digitalentity** [comment]
2.0-RC6 SA bugs seem to be have common root cause. Tracked in metabug #3753
