### ISSUE TITLE
Feature Request: Smaller OSD font

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav#3757]
I saw those APM osd font size is smaller, but clear, like in this video
https://www.youtube.com/watch?v=37XdJan88BA

compare to the osd font in iNav, the font is much bigger
https://www.youtube.com/watch?v=Bm8SyZ9BTPc

could we have a smaller osd font?
so we could see more of the view rather than the info?

**Comment by shellixyz** [comment]
You can't have such a small font with the character based OSD present on the current FCs.

**Comment by digitalentity** [comment]
That's probably PlayUAV OSD which is not based on 7456 chip. We lack hardware to have that kind of font.
