### ISSUE TITLE
Feature Request: Switched Output on Servo Pin

### ISSUE THREAD

**Issue by twistedwings** [iNavFlight/inav#3758]
I would like to have a switchable output for controlling peripherals.
ChannelX > 1500usec: Output High
ChannelX < 1500usec: Output Low

**Comment by Tygrys-1** [comment]
Nice to have, but without resource allocation may be hard to achive.
The betaflight have something like that.
You may also look for "rc switch" on the net, this one you connect to the analog channel and it is doing the magic. :-)
