### ISSUE TITLE
Feature Request. Acceleration in OSD.

### ISSUE THREAD

**Issue by oldrootbeer** [iNavFlight/inav#3763]
Probably more of a Betaflight thing, but is it possible to have acceleration in OSD and blackbox? Could be useful in tuning a UAV mechanically (xy weight distribution etc).

**Comment by teckel12** [comment]
@oldrootbeer Do you mean accelerometer x, y, z data? Not sure it it would really be useful, or fast enough either.

**Comment by oldrootbeer** [comment]
No. I mean acceleration. How quick a speed is achieved. m/s/s. Just the speed increase or decrease taken from gps and calculated with time?

**Comment by oldrootbeer** [comment]
A poorly balanced quad may have better acceleration in one direction, and not in the other.

**Comment by teckel12** [comment]
@oldrootbeer Then again, it could just be the wind.

**Comment by oldrootbeer** [comment]
Yeah good point. Then dynamic PID's... Be nice to have the stats though. Doesn't matter too much. Just an idea to progress INAV.

**Comment by teckel12** [comment]
@oldrootbeer I believe the raw accelerometer data would provide this.  That's what the sensor is for. But really, on its own it doesn't tell you much on its own, and typically acceleration is quicker than the OSD can display, so you'd probably end up seeing 'old' data that would give you false information as a result.
