### ISSUE TITLE
V2.0.0 servo mix not working properly with camstab

### ISSUE THREAD

**Issue by TasiPeter** [iNavFlight/inav#3770]
## Current Behavior
When using CAMSTAB mode the servo gimbal is not moving enough. Using the mixer tab I added a new servo mix, with the input of Gimbal Pitch, weight is 100, as well as the speed. In previous versions the camstab function moved the servo just enough, but with the version 2.0.0. it barely moves. 

## Steps to Reproduce
1. Upgrade to V2.0.0
2. Enable CAMSTAB mode
3. Add a new mix for a servo, with the input of Gimbal Pitch
4. Tilt the board, the servo will barely move

## Expected behavior
The servo should move in its full range during a 180° tilt.

## Suggested solution(s)
I think it would be handy to have some sort of multiplier on the input value. Or just simply increase the range of the Gimbal Pitch input value.

## Additional context

https://pastebin.com/DyGgxMNF
---

- FC Board name and vendor: INAV/OMNIBUSF4PRO_LEDSTRIPM5 2.0.0 Aug  8 2018 / 18:28:17 (1c3b41527) (banggood)
- INAV version string: V2.0.0-RC3

**Comment by DzikuVx** [comment]
@TasiPeter in your dump you have

```
smix 0  0           12              100     100
```

and that limits full servo sweep to 1 second. Read about speed over here https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md change to speed 0 and then check

**Comment by TasiPeter** [comment]
Hello @DzikuVx !

Thank you for your fast response. The problem here is not the speed, but the servo range. If I use an RC channel as an input for the servo, I can sweep the servo in its full 180° range. But with the Gimbal Pitch input even if I move the board 360° around, the servo moves around 20°. 

(Just to be sure, I checked the behaviour with speed set to 0, but nothing changed.)

**Comment by DzikuVx** [comment]
I think you are misusing CAMSTAB. With weight 100, CAMSTAB scales from range -180 to 180 deg of FC attitude to -360 to 360 us or servo output. that mean, 1 deg of FC means 2us of servo travel. This is how it's supposed to work. You might want to bump weight 200 to get 1us per 1deg

**Comment by blurcak** [comment]
There is "Parse error" if u try 126+ for "weigh" or "rates". The "125" can be changed only via CLI.

**Comment by hali9** [comment]
I confirm, servo_tilt does not work correctly.
Signal GIMBAL_PITCH and GIMBAL_ROLL have to small range.
In servo.c in servoMixer() is: 
```
input[INPUT_GIMBAL_PITCH] = scaleRange(attitude.values.pitch, -1800, 1800, -360, +360);
input[INPUT_GIMBAL_ROLL] = scaleRange(attitude.values.roll, -1800, 1800, -360, +360);
```
And should be:
```
input[INPUT_GIMBAL_PITCH] = scaleRange(attitude.values.pitch, -1800, 1800, -1000, +1000);
input[INPUT_GIMBAL_ROLL] = scaleRange(attitude.values.roll, -1800, 1800, -1000, +1000);
```
Because if I tilt my quad 90 deg, servo should also tilt 90 deg, but full servo range is 180deg=1000 =>[1000,2000], so servo 90deg=500.
So 360deg=2000 => [-1000,1000].

After that It should be multiplied by rate and limited by min max.

**Comment by andrewnewton** [comment]
Yes I'm getting 90º servo movement with 360º board roll rotation. Option of 1 to 1 ratio would be excellent

**Comment by digitalentity** [comment]
Fixed
