### ISSUE TITLE
How to use MSP_RC and MSP_SET_RAW_RC?

### ISSUE THREAD

**Issue by 09Ria09** [iNavFlight/inav#3771]
I have this project which consists of a SPRACINGF4EVO and a Raspberry Pi Zero, but I have a few problems with MSP_SET_RAW_RC and MSP_RC. My first problem is that when using MSP_SET_RAW_RC the drone doesn't do anything and the second one is that when I send MSP_RC I get values(first 8 values: `2250 2250 2250 2250 0 0 0 0`) which aren't between 1000 and 2000.
Here is my code in Python:

    def setRawRC(self, roll, pitch, yaw, thrust):
        self.sendMessage(self.MSP_SET_RAW_RC,
                         # [roll, pitch, thrust, yaw, 0, 0, 0, 0]
                         [1500, 1500, 1000, 2000, 1000, 1000, 1000, 1000],
                         [2, 2, 2, 2, 2, 2, 2, 2])
        self.ser.timeout = 0.03
        print(struct.unpack('<3sBBB', self.ser.read(6)))
        self.ser.timeout = None
        self.sendMessage(self.MSP_RC, [], [])
        self.ser.read(3)
        databytes = struct.unpack('<B', self.ser.read())[0]
        self.ser.read(1)
        d1 = struct.unpack('<h', self.ser.read(2))[0]
        d2 = struct.unpack('<h', self.ser.read(2))[0]
        d3 = struct.unpack('<h', self.ser.read(2))[0]
        d4 = struct.unpack('<h', self.ser.read(2))[0]
        d5 = struct.unpack('<h', self.ser.read(2))[0]
        d6 = struct.unpack('<h', self.ser.read(2))[0]
        d7 = struct.unpack('<h', self.ser.read(2))[0]
        d8 = struct.unpack('<h', self.ser.read(2))[0]
        self.ser.read(21)
        print(str(databytes) + ' ' + str(d1) + ' ' + str(d2) + ' ' + str(d3) + ' ' + str(d4) + ' ' + str(d5) + ' ' +
              str(d6) + ' ' + str(d7) + ' ' + str(d8))

And here is `sendMessage`:

    def sendMessage(self, message_type, data, dnob):  # dnob - data: number of bytes
        log('   sending message to FC with message type: ' + str(message_type))
        # making the output
        length = len(data)
        output = ctypes.create_string_buffer(512)

        # Documentation: https://docs.python.org/3/library/struct.html
        struct.pack_into('<3sBB', output, 0, self.header, length, message_type)

        for i in range(0, length):
            if dnob[i] == 1:
                struct.pack_into('<B', output, 5 + i, data[i])
            elif dnob[i] == 2:
                struct.pack_into('<h', output, 5 + i, data[i])
            elif dnob[i] == 4:
                struct.pack_into('<i', output, 5 + i, data[i])

        # sending the data
        for i in range(0, 5 + length):
            self.ser.write(output[i])
        self.ser.write(struct.pack('<B', xor(output, 3, 5 + length)))

Here is what I get when I execute `status` in the CLI:

System Uptime: 22 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.8V (1S battery - NOT PRESENT)
CPU Clock=168MHz, GYRO=MPU6500, ACC=MPU6500, BARO=BMP280
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
SD card: None inserted
Stack size: 6144, Stack address: 0x10010000, Heap available: 936
I2C Errors: 0, config size: 3509, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = none
  AIRSPEED : configured = none, used = none
System load: 15, cycle time: 128, PID rate: 7812, RX rate: 49, System rate: 9
Arming disabled flags: RX CLI

Here is what I get when I execute `bootlog` in the CLI:

Time Evt            Description  Parameters
   3:  0          CONFIG_LOADED 
   3:  1       SYSTEM_INIT_DONE 
 204: 19   TIMER_CHANNEL_MAPPED  (2, 1, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (3, 2, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (4, 3, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (5, 4, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (6, 5, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (7, 6, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (8, 7, 0, 2)
 204: 19   TIMER_CHANNEL_MAPPED  (9, 8, 0, 2)
 204:  2          PWM_INIT_DONE 
 705:  3       EXTRA_BOOT_DELAY 
1355:  9         GYRO_DETECTION  (7, 0, 0, 0)
1846: 10          ACC_DETECTION  (8, 0, 0, 0)
1947: 11         BARO_DETECTION  (4, 0, 0, 0)
1947: 20        PITOT_DETECTION  (0, 0, 0, 0)
1947: 12          MAG_DETECTION  (0, 0, 0, 0)
1947:  4       SENSOR_INIT_DONE 
3450:  8           SYSTEM_READY 

Here is what I get when I execute `dump` in the CLI:

# version
# INAV/SPRACINGF4EVO 2.0.0 Aug  8 2018 / 18:20:51 (1c3b41527)

# resources

# mixer

mmix reset

mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mix
smix reset

# servo
servo 0 1000 2000 1500 100
servo 1 1000 2000 1500 100
servo 2 1000 2000 1500 100
servo 3 1000 2000 1500 100
servo 4 1000 2000 1500 100
servo 5 1000 2000 1500 100
servo 6 1000 2000 1500 100
servo 7 1000 2000 1500 100

# feature
feature -THR_VBAT_COMP
feature -VBAT
feature -TX_PROF_SEL
feature -BAT_PROF_AUTOSWITCH
feature -MOTOR_STOP
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature -FW_LAUNCH
feature -TRACE
feature VBAT
feature PWM_OUTPUT_ENABLE

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED

# map
map AETR

# serial
serial 20 1 115200 38400 0 115200
serial 0 64 115200 38400 0 115200
serial 1 0 115200 38400 0 115200
serial 2 0 115200 38400 0 115200
serial 3 0 115200 38400 0 115200
serial 4 0 115200 38400 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 1 0 1675 1725
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 125
set gyro_sync = ON
set align_gyro = DEFAULT
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set gyro_stage2_lowpass_hz = 0
set vbat_adc_channel = 1
set rssi_adc_channel = 3
set current_adc_channel = 2
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6500
set acc_lpf_hz = 15
set acczero_x = -7
set acczero_y = -23
set acczero_z = -24
set accgain_x = 4091
set accgain_y = 4093
set accgain_z = 4088
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set mag_calibration_time = 30
set align_mag_roll = 0
set align_mag_pitch = 0
set align_mag_yaw = 0
set baro_hardware = BMP280
set baro_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set receiver_type = MSP
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_min = 0
set rssi_max = 100
set sbus_sync_interval = 3000
set rc_smoothing = ON
set serialrx_provider = SBUS
set serialrx_inverted = OFF
set rx_spi_rf_channel_count = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set sdcard_detect_inverted = ON
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set motor_pwm_rate = 8000
set motor_accel_time = 0
set motor_decel_time = 0
set motor_pwm_protocol = MULTISHOT
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 0
set failsafe_procedure = SET-THR
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set vbat_scale = 1100
set current_meter_scale = 400
set current_meter_offset = 0
set current_meter_type = ADC
set bat_voltage_src = RAW
set cruise_power = 0
set idle_power = 0
set rth_energy_margin = 5
set thr_comp_weight =  1.000
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set platform_type = MULTIROTOR
set has_flaps = OFF
set model_preview_type = 3
set fw_min_throttle_down_pitch = 0
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 330
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set switch_disarm_delay = 250
set gps_provider = UBLOX
set gps_sbas_mode = NONE
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_ublox_use_galileo = OFF
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_allow_dead_reckoning = OFF
set inav_reset_altitude = FIRST_ARM
set inav_reset_home = EACH_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_xy_flow_p =  1.000
set inav_w_xy_flow_v =  2.000
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.100
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_overrides_motor_stop = ON
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = ALWAYS
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_max_terrain_follow_alt = 100
set nav_rth_altitude = 1000
set nav_rth_home_altitude = 0
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 5000
set nav_fw_cruise_speed = 0
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_min_time = 0
set nav_fw_launch_timeout = 5000
set nav_fw_launch_max_altitude = 0
set nav_fw_launch_climb_angle = 18
set nav_fw_cruise_yaw_rate = 20
set nav_fw_allow_manual_thr_increase = OFF
set telemetry_switch = OFF
set telemetry_inverted = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = METRIC
set frsky_vfas_precision = 0
set frsky_pitch_roll = OFF
set report_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_unit = MAH
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set i2c_speed = 400KHZ
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set name = DronePi
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0
set stats_total_energy = 0
set tz_offset = 0
set tz_automatic_dst = OFF
set display_force_sw_blink = OFF
set vtx_halfduplex = ON
set vtx_band = 4
set vtx_channel = 1
set vtx_power = 1
set vtx_low_power_disarm = OFF
set vtx_freq = 5740
set vtx_pit_mode_freq = 0

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 5
set fw_i_pitch = 7
set fw_ff_pitch = 50
set fw_p_roll = 5
set fw_i_roll = 7
set fw_ff_roll = 50
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  1.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_windup = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 40
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_mc_heading_p = 60
set nav_fw_pos_z_p = 40
set nav_fw_pos_z_i = 5
set nav_fw_pos_z_d = 10
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set nav_fw_heading_p = 60
set thr_mid = 50
set thr_expo = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
set fw_tpa_time_constant = 0
set rc_expo = 70
set rc_yaw_expo = 20
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set manual_rc_expo = 70
set manual_rc_yaw_expo = 20
set manual_roll_rate = 100
set manual_pitch_rate = 100
set manual_yaw_rate = 100

# battery_profile
battery_profile 1

set bat_cells = 0
set vbat_cell_detect_voltage = 430
set vbat_max_cell_voltage = 420
set vbat_min_cell_voltage = 330
set vbat_warning_cell_voltage = 350
set battery_capacity = 0
set battery_capacity_warning = 0
set battery_capacity_critical = 0
set battery_capacity_unit = MAH

**Comment by giacomo892** [comment]
You need to change your serialrx provider in order to MSP RC to work.

**Comment by 09Ria09** [comment]
I did: 
![msp rx](https://user-images.githubusercontent.com/25712177/44343299-3ec5cc00-a496-11e8-9657-63c5c3bcccad.PNG)
And on the ports tab, each time I try to change USB VCP Serial RX to ON it changes into this state(note that UART1 MSP was turned to OFF and UART2 Serial RX was turned to OFF):
![ports](https://user-images.githubusercontent.com/25712177/44343495-bf84c800-a496-11e8-9627-832ed81e1b63.PNG)

**Comment by giacomo892** [comment]
why do you want to use USB port to comunicate with the RPI? Just use another UART. Note that you don't need SERIAL RX if you are using MSP_RC!

**Comment by 09Ria09** [comment]
I use the USB port because it's easier and I already use UART on my RPI. The MSP connections works correctly but I still don't know how to make MSP_SET_RAW_RC to work, or at least MSP_RC.

**Comment by shellixyz** [comment]
@09Ria09 I stated previously by @giacomo892 you only need MSP to be enabled on the port not `Serial RX` to use `MSP_SET_RAW_RC`

**Comment by stronnag** [comment]
Works perfectly as long as one addresses the minimum update rate:

* Configurator on /dev/ttACM0
* `receiver_type = MSP`
* run the ruby script at http://sprunge.us/an6uAV against another MSP port (/dev/ttyUSB0, 3DR in my tests)
* enjoy watching the serial channels dance around in the configurator

**Comment by 09Ria09** [comment]
@giacomo892 @shellixyz I changed the ports so it looks like this: 
![ports 2](https://user-images.githubusercontent.com/25712177/44399270-a2600000-a54f-11e8-821e-1dbe484c82c6.PNG) , but `MSP_SET_RAW_RC` still doesn't work, and `MSP_RC` still returns values which aren't between 1000 and 2000(first 8 are: `2250 2250 2250 2250 0 0 0 0`)

**Comment by 09Ria09** [comment]
any ideas?

**Comment by 09Ria09** [comment]
I will try to see if this works with cleanflight or betaflight.

**Comment by 09Ria09** [comment]
MSP_RC work correctly in Cleanflight and Betaflight, but MSP_SET_RAW_RC still doesn't work. I already set receiver mode to MSP RX Input. What is wrong? I've changed my code so I can test it using my PC. Here it is:
```
from serial import Serial
import struct
import ctypes

MSP_SET_RAW_RC = 200
MSP_RC = 105

header = b'$M<'
ser = Serial('COM3', baudrate=115200)


def xor(data, startingPoint, bEndPoint):
    result = 0
    for i in range(startingPoint, bEndPoint):
        result ^= ord(data[i])
    return result


def sendMessage(message_type, data, dnob):  # dnob - data: number of bytes
    print('   sending message to FC with message type: ' + str(message_type))
    # making the output
    length = len(data)
    output = ctypes.create_string_buffer(512)

    # Documentation: https://docs.python.org/3/library/struct.html
    struct.pack_into('<3sBB', output, 0, header, length, message_type)

    for i in range(0, length):
        if dnob[i] == 1:
            struct.pack_into('<B', output, 5 + i, data[i])
        elif dnob[i] == 2:
            struct.pack_into('<h', output, 5 + i, data[i])
        elif dnob[i] == 4:
            struct.pack_into('<i', output, 5 + i, data[i])

    # sending the data
    for i in range(0, 5 + length):
        ser.write(output[i])
    ser.write(struct.pack('<B', xor(output, 3, 5 + length)))


sendMessage(MSP_SET_RAW_RC,
            [1500, 1500, 1500, 1000],
            [2, 2, 2, 2])
ser.timeout = 0.03
# ser.read(6)  # skipping the response check for a lower latency

print(struct.unpack('<3sBBB', ser.read(6)))
ser.timeout = None

sendMessage(MSP_RC, [], [])
ser.read(3)
databytes = struct.unpack('<B', ser.read())[0]
ser.read(1)
d1 = struct.unpack('<h', ser.read(2))[0]
d2 = struct.unpack('<h', ser.read(2))[0]
d3 = struct.unpack('<h', ser.read(2))[0]
d4 = struct.unpack('<h', ser.read(2))[0]
d5 = struct.unpack('<h', ser.read(2))[0]
d6 = struct.unpack('<h', ser.read(2))[0]
d7 = struct.unpack('<h', ser.read(2))[0]
d8 = struct.unpack('<h', ser.read(2))[0]
ser.read(21)
print(str(databytes) + ' ' + str(d1) + ' ' + str(d2) + ' ' + str(d3) + ' ' + str(d4) + ' ' + str(d5) + ' ' +
      str(d6) + ' ' + str(d7) + ' ' + str(d8))'
```

**Comment by stronnag** [comment]
Still works perfectly here, script referenced above modified to print MSP_RC results:
```
./msp_set_rc.rb -d /dev/ttyACM0 
dev /dev/ttyACM0 115200
[
    [0] 231,
    [1] 3,
    [2] 0,
    [3] 2147483708
]
Tx: 1507,1582,1564,1581,1017,1442,1663,1969
Rx: 1507,1582,1564,1581,1017,1442,1663,1969

Tx: 1533,1581,1599,1500,1017,1442,1663,1969
Rx: 1533,1581,1599,1500,1017,1442,1663,1969

Tx: 1585,1515,1527,1599,1017,1442,1663,1969
Rx: 1585,1515,1527,1599,1017,1442,1663,1969

Tx: 1537,1564,1555,1543,1017,1442,1663,1969
Rx: 1537,1564,1555,1543,1017,1442,1663,1969

Tx: 1515,1560,1551,1543,1017,1442,1663,1969
Rx: 1515,1560,1551,1543,1017,1442,1663,1969

Tx: 1570,1516,1599,1591,1017,1442,1663,1969
Rx: 1570,1516,1599,1591,1017,1442,1663,1969

Tx: 1522,1506,1540,1573,1017,1442,1663,1969
Rx: 1522,1506,1540,1573,1017,1442,1663,1969

Tx: 1552,1524,1570,1528,1017,1442,1663,1969
Rx: 1552,1524,1570,1528,1017,1442,1663,1969

Tx: 1580,1576,1513,1546,1017,1442,1663,1969
Rx: 1580,1576,1513,1546,1017,1442,1663,1969

Tx: 1535,1513,1567,1502,1017,1442,1663,1969
Rx: 1535,1513,1567,1502,1017,1442,1663,1969

Tx: 1586,1523,1559,1527,1017,1442,1663,1969
Rx: 1586,1523,1559,1527,1017,1442,1663,1969

Tx: 1560,1519,1523,1509,1017,1442,1663,1969
Rx: 1560,1519,1523,1509,1017,1442,1663,1969

Tx: 1587,1518,1516,1522,1017,1442,1663,1969
Rx: 1587,1518,1516,1522,1017,1442,1663,1969

Tx: 1505,1522,1518,1511,1017,1442,1663,1969
Rx: 1505,1522,1518,1511,1017,1442,1663,1969
```
There is no problem with iNav.

**Comment by 09Ria09** [comment]
@stronnag I don't know ruby, so can you tell me how to set it up(what libraries to install, etc...)

**Comment by stronnag** [comment]
iNav issues are for firmware bugs, not 'teach me how to programme''

**Comment by 09Ria09** [comment]
@stronnag you posted a script which isn't in python, and when I ask you to tell me how to use it, you respond like a douche...

**Comment by 09Ria09** [comment]
bump? I wonder if I would be implementing MSP V2 instead of V1, would MSP_SET_RAW_RC work?
