### ISSUE TITLE
Again Pos hold problems, MAG is far away from all interference

### ISSUE THREAD

**Issue by Xnoopeex** [iNavFlight/inav#3772]
Hi,
it's a 250 Peon Quad.
Ive already post my inav log here. There was haevy interference between mag and power lines.
Now my mag is far away from all, (on a large plastic pipe).
[LOG00016.TXT](https://github.com/iNavFlight/inav/files/2302560/LOG00016.TXT)
I can't see any interference with power lines on my log anymore.
I will attach my log file here.
Hope someone can help.
Thanks a lot!
Noah Kunz,
Germany
[LOG00016.TXT](https://github.com/iNavFlight/inav/files/2302566/LOG00016.TXT)

**Comment by Gazzibllion** [comment]
Not sure if my problem is the same as yours, but I've already lost a quad with Mag issues, thought at first the GPS came off. Rebuilt it, identical build except for ESC's. Had a few flights and RTH, Loiter all fine. Then had another flight back to back, hit loiter and it went bucketing. Regained control, and flew back home manually, but stupidly, I started to follow the home arrow and only when it was too late I saw my home distance had increased massively. Lost VTX managed to kill the quad and recover it 2 km away this time.

Went through the DVR footage and the mag was wrong to start with. Compass was wrong and home arrow always pointed  NW, so there was no chance it would ever RTH properly. Now... this is the exact same build and two identical incidences that were intermittent.

Happy to post the DVR footage of the first successful flight and then the one where it was not OK. Take off from the same place, you can see the compass heading was different.  

Sorry I have no black box logging unfortunately, but the DVR paints a great picture.

Inav 1.9.1
FC: Matek 405 CTR
GPS: Beitian BN-880 (On a GPS Mast 10-12cm high)
