### ISSUE TITLE
Feature Request: Extend throttle PID attenuation (TPA) with GPS speed PID attenuation

### ISSUE THREAD

**Issue by konraddi** [iNavFlight/inav#3773]
When diving down a hill, the throttle usually is zero. 

That means that TPA does nothing in this case. The flying speed gets very high and the PIDs stay too high and do not get reduced.

Is it possible to modify the TPA function or add an additional similar function for (GPS)-speed PID reduction to cover those scenarios? 

The "airspeed" should not only be defined by horizontal speed but be calculated as a combination of horizontal and vertical diving speed (is it a² + b² = c²?)

Thanks,
Konrad

**Comment by digitalentity** [comment]
Attenuation to GPS speed is not feasible as it has no relation to actual speed relative to the air. Discussed a number of times before.
