### ISSUE TITLE
SPracing F3 crashes with INAV 2.0

### ISSUE THREAD

**Issue by skorokithakis** [iNavFlight/inav#3777]
## Current Behavior

I just flashed 2.0 onto my Eachine Wizard x220 and tried to perform some flips in horizon mode with airmode on. As I did some flips, on the last one the quad started to lose altitude and fall in a spiral. Luckily, it fell on some bushes and didn't break.

I started it up again and tried to see what happened, did a flip and, as it returned to level, it started to spiral out of control again, but this time with more throttle and jumped over my head onto the building behind me.

This never happened with Betaflight, and this is the first time I tried to fly with INAV.

## Steps to Reproduce
1. Flash INAV 2
2. Do a few barrel rolls
3. Quad will spiral out of control

## Expected behavior

Quad does not spiral out of control.

## Suggested solution(s)

Not sure

## Additional context

https://www.pastery.net/znvrma/

---

```
# version
# INAV/SPRACINGF3 2.0.0 Aug 19 2018 / 21:15:55 (dbdd1656a)
```

**Comment by giacomo892** [comment]
Have you missed the issue template perhaps?

**Comment by skorokithakis** [comment]
Hmm, where is the template? One didn't appear when filing the issue.

**Comment by giacomo892** [comment]
![image](https://user-images.githubusercontent.com/20860004/44455810-3f2da680-a5ff-11e8-84b2-907173dad9df.png)

**Comment by skorokithakis** [comment]
![screenshot_firefox_beta_20180822-123443](https://user-images.githubusercontent.com/23648/44455888-e1518c80-a607-11e8-96d3-e49903fc4dbd.png)

**Comment by skorokithakis** [comment]
Updated, thanks.

**Comment by giacomo892** [comment]
Check if ESC are calibrated. BF and INAV uses different ranges.

**Comment by skorokithakis** [comment]
Done, thanks. This might be a PID tuning/parameter issue, but I haven't found a way to restore my good Betaflight config and I don't know enough to configure it from scratch.

**Comment by giacomo892** [comment]
Would be nice if you record a blackbox log into che flash chip and post it here.

**Comment by skorokithakis** [comment]
I would, but I don't have much flying room now and I narrowly avoided breaking the quad the first time around... Maybe the PID values were inappropriate for my quad.

**Comment by pDR8iLQ4go** [comment]
Maybe I have the same problem with a SP Racing F3 and INAV 2.0.0. My copter crashed two times, I do not know why. Using the previous INAV Version was fine for some months.
