### ISSUE TITLE
ClRacingF4 Inav 2.0 issue

### ISSUE THREAD

**Issue by kuruption** [iNavFlight/inav#3785]
I can flash inav 2.0 to the CLracingf4 flight controller but the configurator will not connect to the board after, reinstalled inav 1.9.1 and it connects without an issue.. Please fix this issue thank you

**Comment by teckel12** [comment]
@kuruption What version of the configurator are you running? Also, did you try closing the configurator and/or rebooting?

**Comment by kuruption** [comment]
using the newest version INAV-Configurator_win32_2.0.0 try it on 2
computers and 1 laptop with same result wouldnt connect, on the omnibus f4
i have it connects fine just the CLRacing boards its not working

**Comment by teckel12** [comment]
@kuruption Seems there's 3 versions of the CLRACINGF4AIR board, V1, V2 and V3.  There's significant differences between the timers and ports used on each of these.  Are you sure you're using the correct target for your FC?

**Comment by kuruption** [comment]
I have a version 2 board and been using it on a wing for the past couple of
weeks with 1.9.1 when i flashed to 2.0 in wont connect on none of my
computers i had to flash back to 1.9.1 and spend an hour redoing all the
settings i flashed it with the right target but what i can do is try the
other ones and see maybe they mixed up the target names. but it doesnt work
with the proper target
