### ISSUE TITLE
Compass not recognized on OMNINXT F7

### ISSUE THREAD

**Issue by CaptainYags** [iNavFlight/inav#3786]
## Current Behavior
I'm using this M8N GPS compass combo
https://smile.amazon.com/gp/product/B06XR6JHDW/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1
The compass is supposedly a 5883 clone

iNav version INAV/OMNIBUSF7NXT 2.0.0 Aug 20 2018 / 19:15:39 (dbdd1656a)

The GPS works, and is connected to Tx\Rx6. The MAG is connected to SCL\SDA. The MAG is not recognized in AUTO or by manually selecting HMC5883 or QMC5883.  I have previously used this same MAG on an OMNIBUS F3 in iNav successfully.

I saw that some F7 boards need pull-up resistors, so I connected 2200 ohm resistors from the 3.3v pad on the FC to the SCL\SDA pads on the FC.  It didn't work.

Is there anything else I can try?  Could there be something missing in the firmware?

**Comment by CaptainYags** [comment]
Is there some way I can test if the I2C is working on my board?  Is it supported in the code yet?

**Comment by ninja-zx11** [comment]
I can confirm that genuine hmc5883 from drotek works okay with omninxtF7(OmniNXTF7
INAV/OMNIBUSF7NXT 2.0.0 Jul 14 2018 / 22:41:52.

I selected auto and it correctly recognised the compass automatically.It could be your hardware.

Are you feeding your GPS/Compass module with 5v?According to your Amazon link,It should be connected to 3.3v.Try to feed it from 3.3v pad on the omninxtF7.

**Comment by CaptainYags** [comment]
I think it means that the chip is 3.3v, but that there's a voltage regulator onboard. It's originally for an APM system, which is entirely 5v. It worked at 5v on my APM and on my F3. GPS is working on the OMNINXT, just not the compass.

If yours works, maybe I just need a different compass module for now. On a side note, how do you like the built in barometer? I heard recent rumors that it wasn't very good for alt hold

**Comment by ninja-zx11** [comment]
Regarding inbuilt baro, allready created an issue here:
https://github.com/iNavFlight/inav/issues/3697

Yes it doesn't look precise but I never tried flying.I just bench tested it.May be it's okay for flying.

Just for curiosity,you can try feeding your GPS 3.3v.Did you open it up and check the 3.3v regulator?It could be a different design.After all all Fake Chinese modules with poor quality.

**Comment by CaptainYags** [comment]
To wrap this up, when I unmounted my GPS for another project, I saw that the MAG chip got knocked off in a crash.  Oops!  Been trying other boards, so I can't comment on the baro
