### ISSUE TITLE
Blackbox doesn’t record

### ISSUE THREAD

**Issue by spacyje** [iNavFlight/inav#3792]
Hello,
I don't understand why my blackbox doesn't record anything.  When I get this screen on the configurator normally it's okay, right?
![2538f84b-3b1b-4337-8e84-7956c3cf402f](https://user-images.githubusercontent.com/42523782/44607542-4fe94280-a7e0-11e8-9423-cfec2cd7c3e6.jpeg)

- feature blackbox enabled
- device sdcard 
- switch mode blackbox on
- sdcard SDHC CLASS6 8Go

I only have the freespa.ce file that is empty.

**Comment by teckel12** [comment]
@spacyje My configurator looks different (shows space used and free on SD card).  Also, the "Filesystem starting..." message sounds like it's trying to access the card but it can't.

Try a different SD card or reformat the card as FAT32 with the [SD Memory Card Formatter](https://www.sdcard.org/downloads/formatter_4/).

**Comment by david-ng-hk** [comment]
@spacyje just finish a flight in iNav 2.0 official, the blackbox works fine, I am using a 32G class 10 SD Card (some unknown chinese brand)

@teckel12 I use the iNav log viewer in https://github.com/iNavFlight/blackbox-log-viewer
I could not get the gps coordinates, nor the gps time display in the viewer.
Could you?
I remember @fiam modify some gps related info in the blackbox on https://github.com/iNavFlight/inav/issues/3531
and
https://github.com/iNavFlight/inav/issues/3516
