### ISSUE TITLE
Add support for Memsic MMC5883MA magnetometer which is P2P compatible with Hmc5883

### ISSUE THREAD

**Issue by ninja-zx11** [iNavFlight/inav#3793]
Please add support for MMC5883MA as it performs even better than HMC5883.

Comparison done here: http://www.diva-portal.se/smash/get/diva2:1169027/FULLTEXT01.pdf

Driver already present in ardupilot Px4 firmware
: https://github.com/traxxas/PX4Firmware/commit/89fe5e7bdf7a91a5bed7a6c88f35a5b56dcbff98#diff-8989715f5461b08efdb89011d2e99b5c

![mag](https://user-images.githubusercontent.com/37225379/44610405-d6862b80-a7b0-11e8-8b94-a5358d880806.png)

**Comment by digitalentity** [comment]
Are there any GPS modules with this chip?

**Comment by ninja-zx11** [comment]
Small breakout boards are available from digikey which can be placed inside existing GPS puck housing I guess.Really frustrated from the bad performance of fake compass chips.As it's P2P compatible with hmc5883,I would just solder it in place of existing fake hmc5883.

**Comment by digitalentity** [comment]
Ordered a sample to evaluate

**Comment by ninja-zx11** [comment]
My board came today.It can be easily installed/glued inside a gps puck by removing the pin headers from the compass board.

Is it possible to have a temporary hex file with mmc5883 driver for omninxtF7 board to test this  compass board?I mean just for testing on the bench.Thanks.
