### ISSUE TITLE
Inav 2.0.0 rc5+ sbus NOT WORK on SP4RACINGF4EVO

### ISSUE THREAD

**Issue by ZioMeme** [iNavFlight/inav#3796]
## Steps to Reproduce
1. iNav 2.0.0 rc5, rc6, stable
2. Flight Controller SP4RACINGF4EVO

## Expected behavior
SBUS (FRSky X series RX) doesn't work, NO channel is read.
iNav 1.9.1 to 2.0.0rc4 works correctly

**Comment by david-ng-hk** [comment]
try my fport here
https://github.com/iNavFlight/inav/pull/3723

[inav_2.0.0_official_SPRACINGF4EVO_SoftSerial1.zip](https://github.com/iNavFlight/inav/files/2322464/inav_2.0.0_official_SPRACINGF4EVO_SoftSerial1.zip)

**Comment by ZioMeme** [comment]
If I understand correctly, you utilize PWM5 and PWM6 as softserial, is it true?
I utilize SP4EVO on a Hexa, so PWM5/6 is already busy...
Thanks,
Emanuele
