### ISSUE TITLE
Inav 2.0.0 IRC Tramp 600mW setting do not work

### ISSUE THREAD

**Issue by Chefhandwerker** [iNavFlight/inav#3799]
600mW power setting does not work. You can choose it over the OSD. But after leaving the OSD, invalid VTX Power is displayed.
 Matek F405 Wing
 IRC Tramp Int
 Inav 2.0
 crosscheck with Betaflight Lua.
 With Betaflight Lua you can set 600mW. Sometimes with, sometimes without error in the OSD

**Comment by johnlenfr** [comment]
Same thing for the Atlalt HV 25-600mW

INAV 2.0.0 / Holybro Kakute F4 V2 Flight controller / Atlalt HV 25-600mW 40CH VTX  / Tekko32 35A 4 In 1 Blheli 32 ESC

More infos on harware here :

[http://www.holybro.com/product/48](http://www.holybro.com/product/48)

[https://www.rcgroups.com/forums/showthread.php?3048970-Holybro-Kakute-F4-V2-FC-Atlalt-HV-25-600mW-40CH-VTX-Tekko32-35A-4-In-1-BLHeli-32](https://www.rcgroups.com/forums/showthread.php?3048970-Holybro-Kakute-F4-V2-FC-Atlalt-HV-25-600mW-40CH-VTX-Tekko32-35A-4-In-1-BLHeli-32)

**Comment by JonnyFPV** [comment]
Same issue for me :(

**Comment by edlabh** [comment]
Same here

**Comment by BobbyCephy** [comment]
in src\main\drivers\vtx_common.h is written:
#define VTX_SETTINGS_MIN_POWER       1
#define VTX_SETTINGS_MAX_POWER      (VTX_SETTINGS_POWER_COUNT - 1)

it has to be replaced with:
#define VTX_SETTINGS_MIN_POWER       1
#define VTX_SETTINGS_MAX_POWER      VTX_SETTINGS_POWER_COUNT

in order to get the correct number of power levels from 1 to VTX_SETTINGS_POWER_COUNT

**Comment by BobbyCephy** [comment]
try this:
[inav_2.0.0_KAKUTEF4V2_VTX_POWER_FIX.hex.zip](https://github.com/iNavFlight/inav/files/2409019/inav_2.0.0_KAKUTEF4V2_VTX_POWER_FIX.hex.zip)
[inav_2.0.0_MATEKF405SE_VTX_POWER_FIX.hex.zip](https://github.com/iNavFlight/inav/files/2409020/inav_2.0.0_MATEKF405SE_VTX_POWER_FIX.hex.zip)

**Comment by gregm412** [comment]
I'm having a similar problem. My board is furious f35 and furious stealth long range 700mw vtx. Inav 2rc4 worked for me but stable 2.0 doesn't change power level. If I choose power level 3 it will go to 200mw all other power options do nothing. My vtx goes from 25mw 200mw and 700mw.

**Comment by er9xuser** [comment]
Again the same problem. iNav 2.0.1 IRC Tramp settings.

MatekF405-STD IRC Tramp HV

Tramp has 5 levels but one can choose only 4. It was working in 2.0.0. rc2, rc3, rc4...why this is again broken?

And why can't I set VTX settings on Caonfiguration tab...before it was possible? I think we are downgrading now...not upgrading.

**Comment by teckel12** [comment]
I believe 2.0.1 was a emergency release for GPS issues. The next release will support level 5. For now, you can either compile your own or set the value to 4.

**Comment by DzikuVx** [comment]
#4008
