### ISSUE TITLE
Unable to rearm inflight INAV 2.0.0

### ISSUE THREAD

**Issue by konraddi** [iNavFlight/inav#3801]
I had some issues rearming my ASW 28 inflight. The first time it worked, the second time in the same flight sortly after INAV did not let me rearm (said roll/pitch not centered which is not true because they were centered and at the same position as the first time when it worked).

Before I tried to rearm the second time, I switched in and out of the launch mode (which when activated also prevents to rearm inflight!), maybe that has something to do with this strange behaviour? 

Please see attached Logs and Diff.

Thanks,
Konrad

[Diff ASW28 v7 iNav 2.0.0.txt](https://github.com/iNavFlight/inav/files/2321348/Diff.ASW28.v7.iNav.2.0.0.txt)

[LOGS ASW 28.zip](https://github.com/iNavFlight/inav/files/2321349/LOGS.ASW.28.zip)

**Comment by giacomo892** [comment]
Have you applied some trim during flight?

**Comment by konraddi** [comment]
No trims. Disarming and rearming worked around 10 seconds before, just no more the second time I disarmed and wanted to rearm.

**Comment by shellixyz** [comment]
Make sure your R/P channels are close to 1500 (+-10) when you release the sticks. You won't be able to arm with launch mode if your roll or pitch channels are more than `pos_hold_deadband` away from 1500.

Also make sure you set `small_angle` to 180 to be able to rearm in the air in any position.

**Comment by konraddi** [comment]
mall_angle is set to 180. The roll/pitch/yaw is at 1499-1500 with sticks centered.
