### ISSUE TITLE
report_cell_voltage gets wrong attribute after update to 2.0

### ISSUE THREAD

**Issue by jreis1** [iNavFlight/inav#3802]
It happened to me and to other inav user. 

After updating to RC2.0:

report_cell_voltage takes the value of  "VALUE 5",  while valid setting would be "ON" or "OFF". 
Therefore, it is impossible to arm the aircraft. 

![pic](https://user-images.githubusercontent.com/25162166/44627259-8dee7f80-a922-11e8-9d42-feb80107271d.png)

Solution is to manually set report_cell_voltage = OFF.

Happened in : Matek F405 CTR FC and Matek 405 Wing.

**Comment by shellixyz** [comment]
Please read the release notes: https://github.com/iNavFlight/inav/wiki/2.0.0-Release-Notes

When upgrading a full chip erase (when flashing) / `defaults` from CLI is advised. Be sure to backup your configuration and restore it wisely.

**Comment by digitalentity** [comment]
Full erase and re-configuration is advised when upgrading to 2.0. Closing.
