### ISSUE TITLE
osd remaining percent based on sag compensated voltage

### ISSUE THREAD

**Issue by tiriad** [iNavFlight/inav#3803]
Actual Behavior

The OSD shows the remaining percentage of the battery based on the raw voltage

Desired Behavior

Be able to choose  the remaining percentage  of the battery  shown on the OSD based on raw or sag compensated voltage  or only use sag compensated voltage (i think it would be a more useful value) when no other battery specification is configured  to avoid fluctuations in reading

**Comment by teckel12** [comment]
@tiriad I believe there's a switch to do this. I'm fairly sure I had it turned on but didn't like it so I turned it off (as I have a current sensor which is more useful as a "fuel" indicator).

**Comment by shellixyz** [comment]
It is not possible in 2.0. It will be possible in the next release by setting `bat_voltage_src` to `SAG_COMP`.

**Comment by tiriad** [comment]
It is good to know that later on you will be able to activate this feature thanks for your work.
