### ISSUE TITLE
OSD show wrong GPS coordinates

### ISSUE THREAD

**Issue by alterfettersack** [iNavFlight/inav#3818]
Hi in the INAV configurator SW the GPS reading is correct,
but in my  googles showed via OSD not.
It shows me an location an hour away...
Any hints or suggestions??

THX

**Comment by shellixyz** [comment]
You are using 2.0 final ?

**Comment by alterfettersack** [comment]
Jop...

# version
# INAV/OMNIBUSF4PRO 2.0.0 Jul 14 2018 / 22:40:31 (f2cf315ad)

**Comment by alterfettersack** [comment]
screenshots:

https://ibb.co/iVr8L9
https://ibb.co/i8FqYU

**Comment by alterfettersack** [comment]
screenshots:
https://ibb.co/iVr8L9
https://ibb.co/i8FqYU

**Comment by shellixyz** [comment]
What are the good / displayed coordinates ?

**Comment by alterfettersack** [comment]
This ones are correct: https://ibb.co/i8FqYU

Problem if i loose my plane and have still video i cant find it :/

THX

**Comment by teckel12** [comment]
@alterfettersack So the latitude is correct but the longitude is incorrect?  Confused by the `X`.  Are you trying to hide your location or are you trying to highlight the latitude?

**Comment by alterfettersack** [comment]
X is to hide my location, the problem is the longitude.
Latitude is correct.

It should show 13.0045 and it is showing 13.4449

**Comment by fiam** [comment]
You’re running a release candidate. It’s a know bug and it was fixed in 2.0 final.

**Comment by teckel12** [comment]
I wonder if setting `osd_coordinate_digits` to `8` if that would change anything?:

`set osd_coordinate_digits = 8`

**Comment by alterfettersack** [comment]
FW updated, tested and now it works :D

Thank you very much !!!

**Comment by fiam** [comment]
Closing, this was indeed fixed in 2.0.
