### ISSUE TITLE
PPM not working in iNav 2.0.0 stable, working in 1.9.1

### ISSUE THREAD

**Issue by Nobatgeldi** [iNavFlight/inav#3825]
Board and Version
Matek F722 STD

INAV 2.0.0 stable release on Aug 20 2018

iNav 1.9.1 receiver
![inav 1 9 1](https://user-images.githubusercontent.com/11710280/44815319-df7b6080-abe7-11e8-8f37-60e746f290a9.png)

iNav 2.0.0 receiver
![inav 2 0 0](https://user-images.githubusercontent.com/11710280/44815320-df7b6080-abe7-11e8-89ad-af6374ab12db.png)

Behavior
PPM not working
Select PPM signal in Configuration, save and reboot, go to reciver tab

Tested and working in 1.9.1.

Could be configurator issue but I wouldn't speculate

**Comment by shellixyz** [comment]
Confirmed, I can reproduce the issue. Tested with a IA6B receiver. Working with 1.9.1, not working with 2.0.0.

**Comment by toff74** [comment]
it's the same problem for me with yupif7 and 2.0.0

**Comment by stronnag** [comment]
Works here (SPRF3, crappy Redcon DSMX RX).

**Comment by shellixyz** [comment]
F7 only maybe then

**Comment by ShikOfTheRa** [comment]
I am running PPM on 2.0.0 stable. on F405SE 
Working OK

**Comment by tobimai** [comment]
Also not working on my Omnibus F3 Pro, using Spektrum AR610 receiver with PPM encoder. 
I will edit/delete the comment when I found a problem.

**Comment by digitalentity** [comment]
Seems F7-specific. I need to find an F7 board to debug

**Comment by leeph** [comment]
Confirmed this bug as well on Matek F722 and LemonRX PPM receiver, running iNav 2.0.0 stable. Tried with the Serial RX switch on and off (Matek site states it should be off) but all channels report '0' in either case.

If I plug the same receiver into my Matek F405-Wing and setup for PPM RX input, everything works as expected (also running iNav 2.0.0 stable) so bug seems to be F7 specific.

**Comment by LucaBertuolo** [comment]
Same problem in Omnibus F3 AIO, switched back to 1.9.*

**Comment by sniperxnl** [comment]
Also not working on F35

**Comment by nanoperry** [comment]
same problem i have matek f722 with ezuhf ppm reciever in 191 its working but no mixer in inav2.0
when i put firmware 2.0 then no ppm but then i have mixer
what must i do what am i doing wrong

**Comment by happyvalley-lmx** [comment]
Same problem in Omnibus F4 V3...

**Comment by nanoperry** [comment]
when is the problem fixed we here nothing big problem i think

**Comment by sramula** [comment]
Same problem on my Omnibus F4 PRO V2 (from Gearbest-maybe clone, but led strip works on dedicated conector). I use PPM encoder, on firmware OMNIBUSF4PRO v 1.9.1 signals works, on 2.0 there is no signal from reciever.

**Comment by chinaling** [comment]
Same problem for me.
1.9 works, 2.0 does not show receiver when setting as PPM
using Matek F722 board firmware.

However my board is not a Matek board it's
https://www.aliexpress.com/item/F722-F7-Flight-Controller-With-OSD-Barometer-Built-in-5V-3A-BEC-For-RC-Drone-Support/32944307725.html?spm=2114.search0104.8.50.b3257c63CskxCU


**Further information**
Looking at CLI Dump and comparing Features for 1.9 and 2.0
1.9 contains  feature -RX_PPM, version 2.0 does not.  I assume that I would need to know how to build and compile a release to include a 'feature'.

**Comment by digitalentity** [comment]
F7 PPM issues fixed in #4021

**Comment by turker17** [comment]
Is there a solution to the problem of matek f722 ppm or ibus????

**Comment by chinaling** [comment]
Today I have reloaded Inav for M722 today using current stable versions.
 MultiWii API version received - 2.2.0
2018-11-23 @ 09:46:07 -- Flight controller info, identifier: INAV, version: 2.0.1
2018-11-23 @ 09:46:07 -- Running firmware released on: Oct 31 2018 19:27:11
2018-11-23 @ 09:46:08 -- Board: MKF7, version: 0

The release date is Oct 31 and the fix was reported as fixed on Nov 18.
This implies that the release is not available in the stable version.
I do not know if there is a later release of firmware or how it may be accessed.  I will be waiting until the next official release.

**Comment by shellixyz** [comment]
Should be fixed in the development version. You can try this: 
[inav_2.1.0_MATEKF722.hex.zip](https://github.com/iNavFlight/inav/files/2611194/inav_2.1.0_MATEKF722.hex.zip)

**Comment by chinaling** [comment]
Just tried this development version and it works.  
ie PPM signal input on Serial RX/UART 2 using RX PPM input shows up on the receiver.

thanks to developers.

**Comment by SIM34ssimen** [comment]
> same problem i have matek f722 with ezuhf ppm reciever in 191 its working but no mixer in inav2.0
> when i put firmware 2.0 then no ppm but then i have mixer
> what must i do what am i doing wrong

I have 2 Radio controllers, one is Devention and another one is flysky. The flysky is working when using ppm.
, but Devo does not detected when using matek f722

**Comment by giacomo892** [comment]
@SIM34ssimen have you tried the 2.1.0 firmware provided by @shellixyz few posts above?

**Comment by SIM34ssimen** [comment]
yes I did and it works. Thank you very much.

**Comment by sniperxnl** [comment]
I have a F35 with a EZUHF nano and it is still not working, is there a solution yet?

**Comment by shellixyz** [comment]
@sniperxnl Please try this dev build (3dc3158ac) : [inav_2.1.0_FF_F35_LIGHTNING.hex.zip](https://github.com/iNavFlight/inav/files/2663318/inav_2.1.0_FF_F35_LIGHTNING.hex.zip)

**Comment by SIM34ssimen** [comment]
On the computer, ppm rx was working. When I took the quad out and try to arm, there was nothing happened. When I  use fw.1.9.1 it armed, I  switched back to 2.01 it still doesn't arm. Now I have to use 1.9.1firmware. Please fix this problem. Ps. blheli ESCs or not detected matekf722 when using   
Inav 2.0 or 2.1.0

**Comment by giacomo892** [comment]
@SIM34ssimen will be fixed in 2.1

**Comment by walney-reptiles** [comment]
FC Matek-F411 ppm not working in 2.0.0 - 2.1.0 anyone got a fix for this?

**Comment by lorenz4672** [comment]
Also same problem with omnibus F4 V3, ppm does not work at version 2.1.0.
Will there be a fix soon ?
