### ISSUE TITLE
RC RX LINK LOST using FPort + softserial Inav 2.0

### ISSUE THREAD

**Issue by zingaros** [iNavFlight/inav#3830]
## Current Behavior
I setup a wing with the R9 slim with the FPort firmware and using soft serial on a mateck f405 osd
After a few min of flight, consistently I lost control of the plane (rth + total loss of controls) depite an rssi >80)

## Additional context
here is my config file https://pastebin.com/SkP13Auk

---
- FC Board name and vendor: Matek F405 OSD
- INAV version string: INAV/MATEKF405OSD 2.0.0 Aug 20 2018 / 19:20:20 (dbdd1656a)

**Comment by zingaros** [comment]
New findings. Might be wiring issue

**Comment by giacomo892** [comment]
Are you using a soft serial as RX input port?!?!

**Comment by zingaros** [comment]
Yes: is it a bad idea?
