### ISSUE TITLE
Matek F405 Wing wrong Data with I2C MS4525 Airspeed Sensor

### ISSUE THREAD

**Issue by Tim2309** [iNavFlight/inav#3832]
## Current Behavior
I have a Matek F405 Wing FC and 2 Different MS4525 Airspeed Sensors, if I connect it correctly like Matek says my airspeed sensor will increase the value up to 11799cm/s.
I tested it with 5V and 3.3V, the same problem.
I contaced the Matek support and they send me a modified (remapped) firmware, so I can test the sensor on I2C1 instead of I2C2 pads. All 3 sensors work but I have to use 3.3v with 5v it won't work.(no problem for me)

Then I tested it again with original firmware and on I2C2 with the initial problem. 
Matek send me a new FC because they thought my I2C2 port is broken.
Today I received the new FC and connected everything, after powering up the sensor is still at maximum value...

Now I think it's a bug on the I2C2 port because it work on I2C1.
Here is the modified Firmware, it was the last beta version.
[inav_2.0.0_MATEKF405SE.hex.zip](https://github.com/iNavFlight/inav/files/2342386/inav_2.0.0_MATEKF405SE.hex.zip)

<img width="1538" alt="bildschirmfoto 2018-09-01 um 14 31 16" src="https://user-images.githubusercontent.com/30231962/44946327-b4b52600-adfa-11e8-9611-f7ec3567fe24.png">

## Steps to Reproduce

1. Connect Airspeed Sensor on I2C2 and 3.3v
2. Look into sensor tab in inv configurator

## Expected behavior
The Airspeed should be near 0cm/s

## Suggested solution(s)
Compare I2C1 and I2C2 and please fix the bug.
I can test everything and can provide all infos/logs you need.

- FC Board name and vendor: Matek F405 Wing
- INAV version string: INAV/MATEKF405SE 2.0.0 Aug 20 2018 / 19:22:34 (dbdd1656a)

**Comment by digitalentity** [comment]
Odd. I don't have MS4525 at hand. Will get some and test.
@MATEKSYS - can you send me changes you did to remap to I2C1?

**Comment by Tim2309** [comment]
I could give you access to the flight controller and airspeed sensor on inav over teamviewer or vnc if it help you.
I can send you details via email if you like.

Answer of Matek what has been changed:
„I swaped MS4525 definition to I2C1
default is on I2C2  https://github.com/iNavFlight/inav/blob/development/src/main/target/MATEKF405SE/target.h#L79 „

**Comment by digitalentity** [comment]
I'll probably need access to actual hardware to check if I2C communication is working normally.

**Comment by Tim2309** [comment]
Maybe I can help you but probably I would need a oscilloscope? I only have a quality multimeter.

Pull up resistors where tested before without luck.

**Comment by digitalentity** [comment]
I'll order needed parts next week, but if you are located in EU you can send me one sensor if you have a spare one. I should have one F405-WING in my cabinet somewhere.

**Comment by Tim2309** [comment]
I‘m in the EU, i‘ve got one spare sensor without the tube.

**Comment by MATEKSYS** [comment]
@digitalentity  in that modified Firmware, just  #define PITOT_I2C_BUS       BUS_I2C1
https://github.com/iNavFlight/inav/blob/development/src/main/target/MATEKF405SE/target.h#L79

MS4545 works fine on I2C2 rail of my F405-WING board with INAV either Ardupilot(ChibiOS)

**Comment by Tim2309** [comment]
Hi,
@MATEKSYS @digitalentity 
I found the bug, if you set "runcam device" to any uart, the airspeed sensor doesn't work anymore on I2C2.
Reproduced it on both FCs.

**Comment by digitalentity** [comment]
@Tim2309 ok, this might shed some light on the issue. I'll dig into the code - maybe I'll be able to find the problem.

**Comment by Tim2309** [comment]
2.1.0 work with camera control, but the down command in the camera control doesn't work, up works fine.

**Comment by digitalentity** [comment]
Works fine #3977
