### ISSUE TITLE
Add climb and descent angle in degrees for winged craft

### ISSUE THREAD

**Issue by AIRBOZ** [iNavFlight/inav#3837]
Would it be possible to have an OSD option for the climb and descent angle expressed as degrees positive or negative to zero (level), in addition to the visual and numeric options already implemented?

**Comment by teckel12** [comment]
@loflyfpv I know it's possible as the pitch value is already exposed. Just a matter of attaching the value to a new OSD option. I'm surprised it doesn't already exist actually.

**Comment by AIRBOZ** [comment]
@teckel12 I'm guessing the conversion from pitch value to degrees would be simple too.

**Comment by digitalentity** [comment]
Pitch on OSD is expressed in degrees.

**Comment by AIRBOZ** [comment]
@digitalentity i'll check that this evening. i must confess that i've never used the pitch, roll and yaw in the osd and didn't think to try them before posting.
