### ISSUE TITLE
OSD confirmation message when settings are saved with sticks

### ISSUE THREAD

**Issue by AIRBOZ** [iNavFlight/inav#3838]
Would it be possible to implement a confirmation message on the OSD screen when settings have been successfully saved with the sticks?

**Comment by mattyra** [comment]
This should be easy to do and should be implemented.

**Comment by digitalentity** [comment]
@mattyra PRs are welcome 😄 
To implement this thing properly we'll likely need a message bus. @fiam ?

**Comment by wx4cb** [comment]
> @mattyra PRs are welcome 😄
> To implement this thing properly we'll likely need a message bus. @fiam ?

couldn't you just use a standard system message like in the warnings (throttle not low, unable to arm etc)

**Comment by teckel12** [comment]
@wx4cb I think the difference is that this would be a temporary message that would display for a couple seconds instead of an error message that's displayed till the error has ended. So a message system would need to be created to pre-empt an error.

**Comment by breadoven** [comment]
Closed by https://github.com/iNavFlight/inav/pull/8439 ?

**Comment by MrD-RC** [comment]
Yes. That could close it if stick commands use save and notify. If not, it could be added easily.
