### ISSUE TITLE
BLACKBOX DOSN'T WORK

### ISSUE THREAD

**Issue by CcLaFleche** [iNavFlight/inav#3841]
On OMNI NXT F7 = working but impossible to extract (progression bar stay at the minimum)
MATEK F722 = Fatal error SDCARD
OMNIBUS F7 V1 = start filesystem... to the infinity !

A part of the best FC for MC aren't completly fonctionnal.

F405 AIO : works fine !

**Comment by CcLaFleche** [comment]
Hi !
I'm trying Inav 2.0 on my MATEK STD F722.

SD card does not initialized. I'm using BF firmware on the same card for initialize her but the blackbox does't work : there is not log created...

**Comment by digitalentity** [comment]
Duplicate of #3940
