### ISSUE TITLE
Add to OSD menu GPS coords

### ISSUE THREAD

**Issue by rozhkovets** [iNavFlight/inav#3847]
Add the current GPS coordinates to OSD menu, for example, in the subsection "misc". This can help in fast searching after crash, when there is a good video signal, but you can not hear the buzzer.

**Comment by Tygrys-1** [comment]
There are the Longitude and Latitude OSD items in the GPS section. 
I have checked now the Inav 2.0, but they were there in erlier versions too.

It saved my craft once or twice, even when no video (battery depleted), but I have found the last position on the recording, searched for it on the map and estimated the possible landing area.

**Comment by rozhkovets** [comment]
I understand you, I know about such a function. In my opinion, the coordinates on the screen take up a lot of space and overlap the review. of course, after crash you can go into the OSD menu (main - osd - layouts - gps ...) and enable them, but it's long and uncomfortable

**Comment by teckel12** [comment]
@rozhkovets In 2.0.0 there's 4 OSD views. I create multiple views so at different times doing different things I can switch the view. I have it controlled by an unused knob on my transmitter. One view can include GPS info.

**Comment by Tygrys-1** [comment]
I'm out of unused knobs due to many INAV modes and features :-)
But yes, I used one for OSD switch.

**Comment by Tygrys-1** [comment]
> I understand you, I know about such a function. In my opinion, the coordinates on the screen take up a lot of space and overlap the review.

I have a little incompatibility between the camera and googles area of view. If I put the coordinates at the ftopmost line they are only partialy visible in googles. But on the recording they are complete. So I dosen't have this problem. :-)
For earlier INAV version I think that they are shown for a short time after arming.

**Comment by giacomo892** [comment]
I think displaying the coordinates on the video just after a crash reduces the possibility of finding the crashed model due to having it's coordinates down to almost zero.
It's very likely 5.8G video range at ground level is very poor, also antenna could be damaged and battery ejected after a crash

**Comment by wx4cb** [comment]
@Tygrys-1 
> For earlier INAV version I think that they are shown for a short time after arming.

they still are shown when you arm.
