### ISSUE TITLE
Disarm delay

### ISSUE THREAD

**Issue by oldrootbeer** [iNavFlight/inav#3848]
Hi. Whilst bench testing my motors, I went to disarm. I didn't hold the switch for long enough, and quite rightly, it did not disarm. However, I have blackbox set to record on the arm switch. The blackbox data suggests that there was no recording when the disarm was enabled briefly.
Does this mean that other modes, e.g. turn assist etc will briefly disable if the arm / disarm switch is accidentally pressed for a short while?
Obviously, while ambling around taking photos, then 0.2 seconds wont make a difference. But to someone who is 'kickin the split s', could be a problem.

**Comment by digitalentity** [comment]
Set `switch_disarm_delay` to delay you need before disarming. Shorter delay increases the chance of unintended disarming if failsafe is not set up properly. It should be safe to reduce to 100ms though.

**Comment by digitalentity** [comment]
If you have some other modes set up on the same switch as arming (which is generally a bad idea) - they will disable before machine is actually disarmed.

**Comment by oldrootbeer** [comment]
Thank you. So its a bad idea to have other modes on the arm switch. I have angle, turn assist and blackbox. I will look into a better way...
