### ISSUE TITLE
Integration with SoftRF in OSD

### ISSUE THREAD

**Issue by Tdogb** [iNavFlight/inav#3849]
**Goal:** Show multiple UAVs on OSD map.

**Purpose:** To aid in locating other pilots for formation flying (useful for small fixed wing formation),  and to aid in locating lost models.

**Proposal:** SoftRF, an open source aviation proximity awareness system, integrated into the iNav OSD map in order to show the location of fellow pilots and full size aircraft. 

**Implementation:** A map display similar to the one seen on the closed source TBS FLARM system. [Video](https://www.youtube.com/watch?v=W65ooyvrktg) [Product page](http://team-blacksheep.com/products/prod:flarm_aviation)

**What this would require:** iNav would have to receive multiple GPS coordinates, altitude, etc. and display on the OSD and adjust map scaling accordingly. SoftRF receiver would have to be updated in order to output data in an iNav readable format. If the amount of traffic exceeds the amount iNav can read at a time, only UAV traffic would be shown, along with closest aircrafts (This could implemented on the SoftRF module rather be than iNav fc)

**Why do I think SoftRF integration would be useful?:** SoftRF is not only able to track UAVs, but also full size aircraft allowing pilots to be more aware as they fly. SoftRF can interface with groundstations in order to provide detailed information. SoftRF can interface with android/ios navigation software, which allows pilots to see current winds, terrain, and weather around the UAV and determine a new course of action if necessary. SoftRF is being actively developed and is open source! Learn more about SoftRF here: [https://github.com/lyusupov/SoftRF](https://github.com/lyusupov/SoftRF)

**What does this mean for pilots?:** Pilots will no longer have to fly circles looking for one another (e.g. when me and my friends are trying to fly 3 person formation with 800mm wings). Locating models, especially at long range would be far easier especially in a situation in which UAV crashes during RTH after video link has dropped (Especially important during proximity mountain flying). Second UAV could be used to locate crashed model. 

If anyone is willing to make this a reality, I would be more than happy to bench test, and flight test this system!

Thanks,
Tanner Beard

**Comment by digitalentity** [comment]
Interesting. nRF905 should be fairly easy to interface on boards that have SPI available on some connector. Since it's open source and LGPL it should be possible to integrate into INAV.
