### ISSUE TITLE
INAV 2.0.0 LED strip turn indicator issue - Left turn not working

### ISSUE THREAD

**Issue by simtcrom** [iNavFlight/inav#3851]
## Current Behavior
LED strip, Left(W) turn indicator function not working.
I Also found that, whether you set direction or not, they will blink only and always when roll stick moves right or down. And will not blink when roll stick move left or up.

## Steps to Reproduce

1.Set led 0,1 as right (E). LED 6,7 as left (W).
2.Move roll stick to right and right indicator works. Move roll stick to left and left indicator don't work.
3.Though right indicators are set to blink only for right turn, they are blinking when stick moves down.
4.Remove all directions (W, E etc.) from LEDs and simply move roll stick right and down. They will blink. move Roll stick left or up LEDs wont blink

## Expected behavior
Right indicator should work only when roll stick move to right. Left indicator should work when roll stick moves left.

## Suggested solution(s)
I don't know. Code issue?

## Additional context
I confirmed that 6,7 leds are good. I can make them work on any other function. I also tried to set 0,1 LEDs to left (W) and not working.
Some issue with left (W).
Made a video of this issue. https://youtu.be/j0qOjHyPDNc

---

- FC Board name and vendor: Omnibus F4 pro v2 (clone)
- INAV version string: INAV/OMNIBUSF4PRO_LEDSTRIPM5 2.0.0 Aug 20 2018 / 19:11:29 (dbdd1656a)

**Comment by artusmuc** [comment]
Nice your LED-strips are working. I have found some which are not working - and only one kind which are working with my Matek 405-mini.

**Comment by simtcrom** [comment]
> Nice your LED-strips are working. I have found some which are not working - and only one kind which are working with my Matek 405-mini.

So, in your working one, are you able to set turn indicators for left or up direction?

**Comment by simtcrom** [comment]
Any one else able to test this?
Just wanted to make sure its bug indeed,
My friend had same issue on inav 2.0.0 and same led strip worked fine for him on betaflight,

**Comment by artusmuc** [comment]
I will test this next week - i had tried this function a time a ago with an omnibus F4 - and it worked not as expected.

**Comment by simtcrom** [comment]
> I will test this next week - i had tried this function a time a ago with an omnibus F4 - and it worked not as expected.

Did you get any time to test this?

**Comment by artusmuc** [comment]
Hello,
Sorry for delay - i have a lot trouble with my motors (vibration) - and i spend now a lot of time to rewind other motors to replace them. (Rewind is done now - and i have to assemble them next week)  

I have also some problems with LEDStrips - some are working - some not - and i really dont know why - so i am glad if they are switching on - and yes i have tested some month ago this orientation function - and i was not very successful. 
Now i have made a short test : in Configurator set Indicator - Orientation - "E" "W" - result 1 LED is on in a not defined color - the other is off - and they are blinking both when i move to the left or to the right. 

I dont know why one led is of and the other is on - and why both are blinking ...

**Comment by simtcrom** [comment]
> Hello,
> Sorry for delay - i have a lot trouble with my motors (vibration) - and i spend now a lot of time to rewind other motors to replace them. (Rewind is done now - and i have to assemble them next week)
> 
> I have also some problems with LEDStrips - some are working - some not - and i really dont know why - so i am glad if they are switching on - and yes i have tested some month ago this orientation function - and i was not very successful.
> Now i have made a short test : in Configurator set Indicator - Orientation - "E" "W" - result 1 LED is on in a not defined color - the other is off - and they are blinking both when i move to the left or to the right.
> 
> I dont know why one led is of and the other is on - and why both are blinking ...

So I guess there is some issue with led strip functionality code. Hope one of the developer look in to it soon.

**Comment by teckel12** [comment]
@simtcrom It's been broken for years. Turn indicators really are not useful anyway. I just do white changing to red flashing for battery warnings. This gives me orientation and when to fly back, the only two things really needed. I wouldn't bother with turn and other features, just not useful for a navigation model. Turn lights are for racing drones, and there's different firmware for that.

**Comment by simtcrom** [comment]
> @simtcrom It's been broken for years. Turn indicators really are not useful anyway. I just do white changing to red flashing for battery warnings. This gives me orientation and when to fly back, the only two things really needed. I wouldn't bother with turn and other fearures, just not useful for a navigation model. Turn lights are for racing drones, and there's different firmware for that.

Got it. Thank you.

**Comment by julienguegan** [comment]
I also have the exact same problem ... **If someone have a solution, please make a sign !** _(not sure if it is related but I don't quite understand the thing about direction north,south,west,east,down and up of the LED ... Is it useful in some way ?)_

**Comment by jpci** [comment]
I have the same problem. I have two 2812 Matek led strip with 8 leds each one . If I try this:

```
# led
led 0 8,0::COI:6
led 1 9,0::COI:6
led 2 10,0::COI:6
led 3 11,0::COI:6
led 4 12,0::COI:6
led 5 13,0::COI:6
led 6 14,0::COI:6
led 7 15,0::COI:6
led 8 7,0::COI:6
led 9 6,0::COI:6
led 10 5,0::COI:6
led 11 4,0::COI:6
led 12 3,0::COI:6
led 13 2,0::COI:6
led 14 1,0::COI:6
led 15 0,0::COI:6
```

Led 0 to 7 turn on ok when I turn stick right or up. If I turn stick left only led 15 ligths. If I turn stick down, nothings happens. But all led do the larsson scanner without problems in any colour.
If anybody needs more information doesn´t hesitate to contact.

**Comment by SplinterII** [comment]
> 

Same issue here!
