### ISSUE TITLE
Failing to set home point while arming

### ISSUE THREAD

**Issue by danarrib** [iNavFlight/inav#3854]
## Current Behavior
This is a DVR showing a possible bug in Inav 1.9.1 (maybe 2.0 has the same bug).

https://youtu.be/1Qb0JSe7j94

I arm and disarm the FC several times. On the first attempts, it shows 6 satellites and correct GPS coordinates. But when I arm, the ARM screen show latitude with ZEROS. Longitude is ok. On the third time, it has 9 satellites and HDOP 1.8, still fails to set the home point.

I really don't know how exactly this happen, but it happen sometimes. Maybe it is something related to the aircraft position... All the times I armed and it failed to set the home point, aircraft has been hold with nose upwards... And when I rearmed it mid-flight, it was kinda leveled.

## Steps to Reproduce
I really don't know exactly what I did... Just held the aircraft nose up and switched the arm switch.

## Expected behavior
Home point must be set correctly.

## Suggested solution(s)
Don't know. Maybe a sanity check: If GPS is 3D fix and (Lat = 0 OR Lon = 0), something is wrong. Don't allow arming.

## Additional context
diff = https://pastebin.com/kxjLkSUq
dump = https://pastebin.com/Y31Kivgg

---
- FC Board name and vendor:
Matek F722-STD

- INAV version string:
INAV/MATEKF722 1.9.1 Apr 21 2018 / 13:43:00 (03a5c1922)

- Aircraft:
Mini Drak (ish). Custom made forward swept wing airplane.

**Comment by OlivierC-FR** [comment]
I'll let a dev confirm but I'm fairly sure it is fixed in 2.0, because I remember I also had it in a 2.0 RC, and then it was fixed and gone in 2.0 final
