### ISSUE TITLE
Are there any documentation explaining each field in blackbox log?

### ISSUE THREAD

**Issue by simtcrom** [iNavFlight/inav#3857]
Are there any documentation explaining each field in blackbox log?

**Comment by Ralf-W** [comment]
I just added some explanations to the wiki page
https://github.com/iNavFlight/inav/wiki/INAV-blackbox-variables

**Comment by simtcrom** [comment]
> I just added some explanations to the wiki page
> https://github.com/iNavFlight/inav/wiki/INAV-blackbox-variables

Thank you.
