### ISSUE TITLE
OSD power last digit over 1000W doesn't clear

### ISSUE THREAD

**Issue by putimir** [iNavFlight/inav#3861]
I'm getting this issue:

I have displayed power output in my OSD (along with A), and when the number in watts exceeds 1000w and then drops below 1000, the last digit, that was displayed as the part of a number over 1000, remains visible. For example, 539w would display 5396 (if the last digit was 6) 

![image](https://user-images.githubusercontent.com/33059362/45537188-d7d0d400-b803-11e8-863a-1cf5129a70b1.png)

![image](https://user-images.githubusercontent.com/33059362/45537285-1a92ac00-b804-11e8-8b50-ff30b8e5e756.png)

![image](https://user-images.githubusercontent.com/33059362/45537314-3007d600-b804-11e8-939f-9a68c7670eb0.png)

It is reproducible, at least with my config.

**Comment by shellixyz** [comment]
Fixed by #6796, closing
