### ISSUE TITLE
FEATURE REQUEST: DSHOT Support

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#3862]
## Current Behavior
Currently only supported ESC protocols are brushed, pwm, oneshot, multishot. This was already referenced in other posts, but just closed)

## Desired Behavior
support dshot 300/600/1200 for more modern brushless ESCS such as BLHeli_32 escs.

## Who does this impact? Who is this for?
All users especially multi rotors which will be more responsive

**Comment by digitalentity** [comment]
Duplicate of #1393
