### ISSUE TITLE
I get a different current value in OSD and S.Port Telemetry and this gives me different mah used in osd and on the taranis. why is this?

### ISSUE THREAD

**Issue by access3424** [iNavFlight/inav#3863]
Board is Kakute F4V2.
I have calibrated the current reading that comes out of s.port and it is spot on but the current reading going to the OSD is off giving different mah values

**Comment by wx4cb** [comment]
maybe related tot his?

https://github.com/iNavFlight/inav/issues/3853

**Comment by shellixyz** [comment]
Please test 2.1.0-RC2 and report whether the issue is still present or not
