### ISSUE TITLE
Unable to choose higher than 7 for servo in mixer FT405 wing

### ISSUE THREAD

**Issue by nosredna000** [iNavFlight/inav#3865]
![capture](https://user-images.githubusercontent.com/19562046/45589701-2790c780-b8f8-11e8-8938-dd015c90a9b1.PNG)

## Steps to Reproduce

1.  External PWM Servo Driver ON
2.  Mixer tab will not allow assigning of servo higher than 7.  FT405 wing has 9 S9

## Expected behavior
Unable to select anything higher than 7

## Suggested solution(s)
Show me how I'm dumb and looking over the right check box lol :)

## Additional context

CLI dump
https://pastebin.com/Ai0iACfX
---

- FC Board name and vendor: FT405 
- INAV version string: # INAV/MATEKF405SE 2.0.0 Aug 20 2018 / 19:22:34 (dbdd1656a)

**Comment by Tygrys-1** [comment]
You may try that in CLI
It might be a configurator problem.

**Comment by nosredna000** [comment]
Could u give me a quick how to? I tried a few things before making my post but was unable to get anything.  Sorry for being vague bc im on mobile.

**Comment by Tygrys-1** [comment]
I'm afraid that INav has only 8 servo slots numbered from 0 to 7, 
So no magic here. If you have the radio with PWM outputs you may connect servos directly.

Maybe you can try the Servo number 2?

For the manual servo configuration use the SMIX CLI command. Here is the [manual](https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md)

**Comment by nosredna000** [comment]
Got it figured out.. the servo naming was confusing me.. Starting with Servo0 etc.
