### ISSUE TITLE
Omnibus F4 Will Not Power On.

### ISSUE THREAD

**Issue by Hopalonger** [iNavFlight/inav#3873]
Was Setting Up an Omnibus F4 Pro and got the Receiver Working then powered off and came back the receiver was not detected. I rebooted the Board and plugged in the lipo to make sure the board had power. It worked fine then During a reboot Inav Said Something along the line of "Fatal Error, Can not proceed with Reboot". Now the FC does not show any signs of life. I checked the regulators and they are producing the 3v3 that is expected and close to 5v. Any Suggestions on what I should do to fix this? If not what about a replacement FC for cheap?

**Comment by teckel12** [comment]
@Hopalonger You can't brick it, just reflash the firmware.

**Comment by Hopalonger** [comment]
@teckel12 The board has no Led and does not show up in device manager like it used to.

**Comment by teckel12** [comment]
@Hopalonger Ah! Sounds like something popped.

**Comment by shellixyz** [comment]
Looks like a hardware failure, closing
