### ISSUE TITLE
Bidirectional Mavlink

### ISSUE THREAD

**Issue by pilotnbr1** [iNavFlight/inav#3880]
Does INav support mavlink channel override? To what degree is mavlink implemented? 

Currently I am flying an omnibus F3 via a raspberry pi zero running an Ez-Wifibroadcast image. I have no traditional receiver onboard- the pi simply forwards sumd control to a uart on the F3. Due to serial port limitations of the pi, It would be better if I could use mavlink instead of sumd as I would have more of a bidirectional link.

**Comment by pilotnbr1** [comment]
Bump...

**Comment by pilotnbr1** [comment]
Not everyone at once now

**Comment by digitalentity** [comment]
> Does INav support mavlink channel override? 

No

> To what degree is mavlink implemented?

Telemetry reporting. Waypoint upload (to some degree)

**Comment by shellixyz** [comment]
@pilotnbr1 Why not use MSP ? Native bidir proto

**Comment by pilotnbr1** [comment]
I am considering MSP but it would require more work on my side. We would have to update ez-wifibroadcast to mspv2 (although the current mspv1 seems backwards compatible) whereas mavlink is ready to go. MSP seems less supported with GCS and the current EZ-Wifibroadcast osd does not read msp telemetry.

**Comment by digitalentity** [comment]
@pilotnbr1 MSP would require work on your side, MAVLink will require work on INAV side. Seems nobody is interested in extending MAVLink beyond minimal implementation, you have two choices:

 1. Either implement MSP support for Ez-Wifibroadcast;
 2. Or implement MAVLink improvements for INAV.

**Comment by datamann** [comment]
Please consider adding MAVLink to INAV. 
Adding MSP support to Ez-Wifibroadcast will only benefit that project but adding MAVLink to INAV will benefit all INAV/Ardupilot users.

**Comment by pilotnbr1** [comment]
Yes... I like INav but may go to ardupilot (with my compatible INAV hardware) because of better mavlink support. Like it or not MAVLink seems to be the de facto standard and more widely supported with GCS software
