### ISSUE TITLE
Problem with Inav 2 and omnibus F4 v3 PRO not ARMED

### ISSUE THREAD

**Issue by lumiror** [iNavFlight/inav#3881]
I have a problem with Inav 2 and Omnibus F4 v3 PRO because not armed. I suspect an engine driver problem because I can not connect to BLHeliSuite and control and setup motors. In version 1.91 everything works correctly. Do you know where to be a problem?
![blheli suite](https://user-images.githubusercontent.com/33359116/45929347-a1f0c580-bf50-11e8-8aff-15b5a9fc70a5.jpg)

**Comment by coffeerunhobby** [comment]
~~I might have the same problem. If the sensor is ICM20608 it is confirmed, if not I will open another issue.~~
![42278392_2683652574993979_2925813678601142272_o](https://user-images.githubusercontent.com/28801208/45940900-60115f00-bfe4-11e8-9ad9-59950e58e068.jpg)
![42301754_2683666188325951_6388304737975926784_n](https://user-images.githubusercontent.com/28801208/45940905-656ea980-bfe4-11e8-851e-fd5f52424a0d.jpg)
Later edit: It is not the same problem. I opened another issue.

**Comment by coffeerunhobby** [comment]
~~P.S. The board is this: //www.banggood.com/HAKRC-Omnibus-F4-V3-Flight-Controller-OSD-w-5V-3A-Power-Distribution-Board-for-RC-Drone-FPV-Racing-p-1284817.html~~
Later edit: It is not the same problem. I opened another issue.

**Comment by lumiror** [comment]
Not this one https://www.aliexpress.com/item/FLIP-32-F4-OMNIBUS-V3-PRO-Flight-Controller-Board-w-Baro-built-in-OSD-For-RC/32827160882.html?spm=2114.search0604.3.28.1fc84f8fKNrvGf&ws_ab_test=searchweb0_0,searchweb201602_5_10065_10068_10059_10884_10887_10696_100031_10084_10083_10103_10618_10307_10820_10821_10303,searchweb201603_45,ppcSwitch_2&algo_expid=248675c1-6289-4347-aae1-8eeb151882f4-4&algo_pvid=248675c1-6289-4347-aae1-8eeb151882f4&priceBeautifyAB=0 
or better here 
http://www.readytoflyquads.com/flip-32-f4-omnibus-v2-pro

**Comment by coffeerunhobby** [comment]
Can you post the 'status' CLI text here. Like I have in the picture above.. It will help the devs.

**Comment by lumiror** [comment]
I'll send, but after the afternoon

**Comment by lumiror** [comment]
Here it is
![status](https://user-images.githubusercontent.com/33359116/45962645-a3d68980-c021-11e8-877d-2febb98199fe.jpg)

**Comment by coffeerunhobby** [comment]
You see "Arming disabled flags: RX CLI" ? You can ignore CLI as it is about that screen.
The problem is the RX. From the documentation here https://github.com/iNavFlight/inav/wiki/%22Something%22-is-disabled----Reasons
"The RC link is not detected (RX not detected)"

**Comment by lumiror** [comment]
I already know where the problem is, I have not set up a new mixer function. Now it's working
