### ISSUE TITLE
Inav custom Version with UART1 MSP tuned on.

### ISSUE THREAD

**Issue by simtcrom** [iNavFlight/inav#3882]
Hello,

I broke micro usb port on omnibus F4 pro v2 and I am trying to regain ability to connect to computer back using ftdi adapter.
I guess for this to work, MSP should be turned on any UART.
Is there a way I can do a custom build where MSP is turned on default on UART1?
Target - OMNIBUSF4PRO_LEDSTRIPM5

Thanks.

**Comment by datamann** [comment]
Take a look at this video
https://youtu.be/5VmhoyL6Z7Q

**Comment by simtcrom** [comment]
> Take a look at this video
> https://youtu.be/5VmhoyL6Z7Q

I had seen that video. And it is betaflight.
I want INAV.

**Comment by lumiror** [comment]
And why do not you fix it?
![usb](https://user-images.githubusercontent.com/33359116/45931069-8f828600-bf68-11e8-84cd-5499e0e85fd9.jpg)

**Comment by simtcrom** [comment]
> And why do not you fix it?
> ![usb](https://user-images.githubusercontent.com/33359116/45931069-8f828600-bf68-11e8-84cd-5499e0e85fd9.jpg)

I attempted to. But they keep coming closer and getting short. Now the pads are gone too. So I don't know if there is a way to solder it.

**Comment by lumiror** [comment]
Are these 4 pads damaged?
![usb fix](https://user-images.githubusercontent.com/33359116/45931262-e2aa0800-bf6b-11e8-87de-400b5f6db614.jpg)

**Comment by simtcrom** [comment]
> Are these 4 pads damaged?
> ![usb fix](https://user-images.githubusercontent.com/33359116/45931262-e2aa0800-bf6b-11e8-87de-400b5f6db614.jpg)

Those 4 pads you have highlighted are not damaged. By the way mine is omnibus F4 pro v2 (clone) Target - OMNIBUSF4PRO_LEDSTRIPM5

![img_0083](https://user-images.githubusercontent.com/6823535/45931299-ecdaff00-bf89-11e8-8e31-01d9cc8c91be.JPG)

**Comment by lumiror** [comment]
so that soldering

**Comment by simtcrom** [comment]
> so that soldering

Could you please explain the pinout?
Micro usb has 5 wires.

![img_0083](https://user-images.githubusercontent.com/6823535/45931440-e0f03c80-bf8b-11e8-8681-5aab36431b05.JPG)

**Comment by lumiror** [comment]
I do not remember it, look at the internet. You need only  4 wires, the fifth is grounding (do not need to connect)

**Comment by simtcrom** [comment]
> I do not remember it, look at the internet. You need only 4 wires, the fifth is grounding (do not need to connect)

Is it safe to assume first and last pads are 5v and gnd respectively? if so I could try other two wires straight and if not work swap around?

![xxefq](https://user-images.githubusercontent.com/6823535/45931588-ac7d8000-bf8d-11e8-9404-2e71fd604af4.jpg)

**Comment by lumiror** [comment]
So
![usb](https://user-images.githubusercontent.com/33359116/45931813-6f0bf900-bf73-11e8-8008-ef5223ef7148.jpg)

**Comment by simtcrom** [comment]
> So
> ![usb](https://user-images.githubusercontent.com/33359116/45931813-6f0bf900-bf73-11e8-8008-ef5223ef7148.jpg)

I wired it like this way and tried connecting. FC got powered up, but computer says "Unknown USB device". Before I broke USB, it was getting detected correctly.

**Comment by simtcrom** [comment]
I had to invert D- and D+ and that fixed issue.
Still trying to make the wires stick to the pads.

**Comment by lumiror** [comment]
try to soldering here
![usb](https://user-images.githubusercontent.com/33359116/45939116-58e05600-bfd0-11e8-9c38-568aec19c822.jpg)

**Comment by simtcrom** [comment]
> try to soldering here
> ![usb](https://user-images.githubusercontent.com/33359116/45939116-58e05600-bfd0-11e8-9c38-568aec19c822.jpg)

I did the original way you suggested and put hot glue on it. Its working now. 
If it ever come off, I shall attempt this way. Thanks a ton, you saved my work.

**Comment by simtcrom** [comment]
Used the pads lumiror suggested and all good now.
