### ISSUE TITLE
Update "Something is disabled Reasons" Documentation to include flag "SETTINGFAIL"

### ISSUE THREAD

**Issue by Ryanf55** [iNavFlight/inav#3885]
## Current Behavior

In CLI, if status is requested, the flag of "SETTINGFAIL" may appear. It is not listed in the wiki:
https://github.com/iNavFlight/inav/wiki/%22Something%22-is-disabled----Reasons

## Desired Behavior
Include reasons for "SETTINGFAIL" to occur and how to fix time in the wiki.

## Who does this impact? Who is this for?
Anyone who uses the documentation for iNAv.

Note: I was not able to figure out how to make a proper pull request for the documentation, otherwise I would have done it there.

**Comment by stronnag** [comment]
The wiki is not usually considered a subject for issues as any user can open a github account and fix out of date wiki pages.

As it happens, the wiki has been updated as a result of (presumably) you asking the same question today on RCG.

**Comment by Ryanf55** [comment]
Thanks for the quick reply; I'll be sure to try to edit the wiki in the future. 

(Yes, it was me on RCG)
