### ISSUE TITLE
Is it possible to limit throttle according to the programmed max current?

### ISSUE THREAD

**Issue by ninja-zx11** [iNavFlight/inav#3888]
If possible.please add feature to limit throttle according to the programmed max amps.This feature will be useful while using LiIon 18650 batteries(having max 20A capacity).Lets say we program inav not to go more than 20 amps and then we can use LiIon 18650 batteries safely within their limit without damaging them on a long range quad.

**Comment by teckel12** [comment]
@ninja-zx11 Are you saying you want to limit the max peak amp current or the max mAh capacity? If I wanted to limit peak amps, I would use a current limiter circuit. Or even better, just use motors that combined wouldn't draw more than 20 amps.

**Comment by ninja-zx11** [comment]
@teckel12  Yes i meant to limit max peak amp current by the firmware but only if someone wants to use LiIon 18650 batteries.This feature would be useful if someone wants to use the same drone for sport flying with Lipo and long range flying using LiIon battery.Yes that's another option of using current limiting circuit but i have no idea how much weight its gonna add.

**Comment by teckel12** [comment]
I'm not sure what INAV could do to limit the current.  If a current sensor is installed (and properly calibrated) INAV wouldn't know it's over current till it was.  But even then, what motor would it reduce and by how much to keep it at a certain level?  I'm sure most things are not linear where this type of calculation would even be possible.  Seems like a lot of trial and error and swinging back and forth to even get close.

Honestly, a current limiter seems like the correct way to go.  Then just let INAV fly within the capabilities of the current supplied.

**Comment by shellixyz** [comment]
It is not possible for the moment

**Comment by ninja-zx11** [comment]
@shellixyz No worries and thanks for the comment.

@teckel12 Will try to find some current limiting device.Do you have any device in mind that i can buy?Thanks.

**Comment by shellixyz** [comment]
Until there is a way to limit the throttle automatically in the firmware to stay under a specified power your best bet I think is to find the max throttle to stay bellow your limit and set that as the maximum command for the ESC.

**Comment by teckel12** [comment]
@shellixyz And even more improbable and complicated when dealing with a quad.

**Comment by Dronek** [comment]
> I'm not sure what INAV could do to limit the current. If a current sensor is installed (and properly calibrated) INAV wouldn't know it's over current till it was. But even then, what motor would it reduce and by how much to keep it at a certain level?

A similar functionality is available for fixed wings in ArduPlane. You can set a maximum power level and the FC will ignore higher throttle values after this power level (current * voltage) is reached. I can imagine that a similar approach could work for quads as well. I.e. not dealing with individual throttle values for each ESC but with the pilot's throttle value while monitoring total current draw.

However, I agree that choosing less power hungry components (motors) would probably be more beneficial in terms of efficiency for a long-range quad.

**Comment by danarrib** [comment]
Ok, let me resurrect this topic, as I found that such feature would be nice to have.

When an airplane is not flying, being held still by someone, if you throttle it's motor to, let's say, 50%, it'll spin the prop and produce some thrust, spending, let's say, 20 amps.

But if the airplane is already flying, let's say at 50 km/h airspeed, then the same 50% of throttle will burn a lot less current, as the air is already moving and ESC will not have to work hard to keep that throttle value.

It would be nice if INAV can limit the current consumption and lower the throttle until a safe current consumption value is reached. It's useful to avoid burning ESC that are underrated for the motor, or power wires that are thinner thus unable to provide the necessary current that the rest of the power system is capable of draw. 

Both situations are very common on long-range efficiency-hunting small aircrafts. Like the guy who uses a 6 amp ESC with a motor that at full throttle, can draw 30 amps. Another use is to make easier to test "maximum speed with current cap", so the airplane will take longer to reach it's maximum speed, but will never exceed it's max current specification to do so.

This can be a Flight mode that pilot can enable or disable in-flight. So if he needs all the amps, then he can disable this mode and INAV will not cap the throttle value based on current consumption.

**Comment by expipiplus1** [comment]
For anyone finding this: current sensor equipped ESCs with blheli32 supports current limiting. Not sure about AM32 at the moment.

**Comment by shellixyz** [comment]
This has been implemented in #6929

**Comment by ninja-zx11** [comment]
Thanks for your work!!
