### ISSUE TITLE
Mass Storage Device (MSC) Support

### ISSUE THREAD

**Issue by ZinhoRacing** [iNavFlight/inav#3889]
## Current Behavior
Not supported yet, available in betaflight 3.5

## Desired Behavior
Mass storage device support allows the micro SD card or the flash chip of your flight controller to be mounted as an external storage device on your PC. This allows for easy drag / drop download of log files.

## Suggested Solution
Merge from betaflight?
I don't have the skills to do it :(

## Who does this impact? Who is this for?
Every body.

**Comment by teckel12** [comment]
I can't even flash my FC half the time without pressing the boot button (which has worn off on a few FC).  I say we get flashing working 100% before we complicate things with MSC support (which is just as easy to pop the SD card out and stick in your computer anyway).

**Comment by ZinhoRacing** [comment]
On my side, I can't acces the SD Slot without removing the FC from the plane ...
No big issue with flashing (Matek F405 wing / windows10 / standalone configurator).
But fair enought. I thought it would not impact flashing or so.

**Comment by stronnag** [comment]
Duplicate of #1336

**Comment by fiam** [comment]
I we mark this one is a duplicate, should we reopen the original one?

**Comment by stronnag** [comment]
I think so, that is where all the history is, so users may understand that this is not just a trivial port from βF.

**Comment by fiam** [comment]
Ack. Please, continue the discussion on #1336. Thanks!
