### ISSUE TITLE
Cannot see motor 5 and 6 in resource list

### ISSUE THREAD

**Issue by access3424** [iNavFlight/inav#3896]
Im running iNav 2.0 on a kalute f4v2 and want to configure the board for a hexacopter but can only see motor 1-4 in resource. Please help

**Comment by shellixyz** [comment]
AFAIK the KakuteF4v2 only has 4 outputs

**Comment by access3424** [comment]
@shellixyz well thats a bummer. Is there no workaround for such a problem?

**Comment by shellixyz** [comment]
You can use pads made for something else if you got some free ones but you will need a custom build

**Comment by access3424** [comment]
@shellixyz you mean modify the hex file?

**Comment by teckel12** [comment]
@access3424 Technically, modify the source code and compile to a custom HEX file.

**Comment by access3424** [comment]
@teckel12 whats the best way to do that? I hear there are alot of options

**Comment by datamann** [comment]
I just setup my dev environment using docker. It's fairly easy.

**Comment by teckel12** [comment]
The other instructions are wrong in at least one place (I should probably fix that). So maybe Docker is the "easy" way, although I don't find Docker that easy.

**Comment by access3424** [comment]
@teckel12 which method would you sudjest?

**Comment by teckel12** [comment]
Probably Docker because other people say it's easier.

**Comment by datamann** [comment]
Tip: Run all commands from powershell (if you are using windows of course)
1: Register an account at docker.com and download https://www.docker.com/products/docker-desktop
2: After installing docker desktop make sure that you login to docker desktop with the docker.com account. Try to run "docker login" from command line (powershell).
3: Download docker image "flyandi/docker-inav" with command "docker pull flyandi/docker-inav"
4: Download source code e.g. https://github.com/iNavFlight/inav/archive/master.zip and unzip to e.g. "c:\inav"
5: run "cd c:\inav"
6: run command "docker run --rm -v //c/inav:/home/src/ flyandi/docker-inav make TARGET=OMNIBUSF4V3". Replace "OMNIBUSF4V3" with the firmware to your FC.

From now on you can do changes to INAV code (Tip: Visual Studio Code is free) and run command 6 to compile a hex file.
Note that after compilation the hex file is stored here: "c:\inav\obj\inav_2.0.0_OMNIBUSF4V3.hex"

Hope I got all steps....

**Comment by access3424** [comment]
@datamann thank you for your help! I managed to set up docker but there is little to no support as to how to modify the targets. All i want is to add motors 5 and 6. How do i do that?

**Comment by teckel12** [comment]
@access3424 It would greatly help if you had a basic understanding of microcontroller resources and a bit of programming experience. It's not just a resource remapping like in Betaflight.  It may require a lot of trial and error or maybe finding someone with the same FC that could help.

**Comment by access3424** [comment]
@teckel12 i do have programming experience but i cant find any support for this. do you have any material? some links?

**Comment by datamann** [comment]
I have had programming as an Hobby since 1995 but I don't call my self a programmer or a developer. I do hover study this field at the moment and I have  bought some courses from Udemy (Not expensive at all). I will post the links soon... My goal is not to become as good as developers here working with INAV because they are very good. I do wish that they could create a course posted on Udemy about the INAV code structure,  I would buy it that's for sure 😊😊

**Comment by datamann** [comment]
Here is the Udemy courses I have bought  and will work with. It's probably overkill but it's ok for me if I learn something. 

https://www.udemy.com/share/1004UGA0IddVZUQXQ=/

https://www.udemy.com/share/100xyeA0IddVZUQXQ=/

https://www.udemy.com/share/100jjCA0IddVZUQXQ=/

https://www.udemy.com/share/1008vcA0IddVZUQXQ=/

https://www.udemy.com/share/10052cA0IddVZUQXQ=/

https://www.udemy.com/share/1006wiA0IddVZUQXQ=/

**Comment by teckel12** [comment]
@access3424 If you're looking for target-specific documentation on setting up the resources, I don't believe any such information exists.  I'd look at the target files in INAV and Betaflight and that will be a good start on what to change.  Having a little insight into microcontroller resources would also be helpful.  Look for documentation on the STM32F405

**Comment by datamann** [comment]
@teckel12 It would be nice if you could take look at these Udemy courses and tell me if they will bring me in the correct direction...
