### ISSUE TITLE
Compass heading on Oled display

### ISSUE THREAD

**Issue by YvoNoordzij** [iNavFlight/inav#3898]
Feature request:

The Oled display feature in iNav currently displays all GPS related info. 

Is it possible to add the compass heading?  To be able to check all navigation related info in one view.

Yvo

**Comment by teckel12** [comment]
@YvoNoordzij To be clear, heading is not known if you only have a GPS. Heading is not part of the GPS info. The only time you can get heading from GPS is if you're flying FW and the model is moving. On the ground (when you'd be looking at the OLED) the GPS doesn't have a heading.

If you want heading when not moving, you'd need a magnatometer.

**Comment by YvoNoordzij** [comment]
I know... Ok, had to add: When a magnetometer is present and active. Which is in my case... And many I think.
