### ISSUE TITLE
Variable speed I2C and SPI

### ISSUE THREAD

**Issue by jflyper** [iNavFlight/inav#390]
Not all devices are created equal. For SPI, some can talk at 15+MHz while others can only talk at 4MHz and slower. Similar on I2C; some can talk at 1MHz/800KHz, majority can talk at 400KHz, and rest can only talk at 100KHz. The situation I2C gets more complex because there are devices that can actually listen to faster clock, but can only talk at slower speeds. Another complication is that when stretching buses the clock should generally be lowered.

It is nice to see if bus clock can be adjusted for a device that is being accessed. May be an additional parameter to i2cRead/Write/WriteBuffer(), or an object describing the device specific context for bus access, for (an extreme) example:  { bus_type, bus_instance, bus_clock, device_address }.

This enhancement will broaden the design space for device placement on shared buses, and will probably be a great addition for the iNav-FC which explicitly supports multiple devices on the external SPI.

**Comment by jflyper** [comment]
@savaga Is this already supported in sirinfpv code?

**Comment by savaga** [comment]
No, it's not. The sirinfpv has all devices connected to different buses (3 SPI and one soft spi for vtx).

**Comment by digitalentity** [comment]
Variable speed I2C is not possible - all devices are listening to the bus and processing data. If some device is unable to read data at some extreme speed it will likely cause corruption of data, received by that device, which, in turn, may cause the device to malfunction (treat received corrupted data as a register write or register read). Similarly for SPI.

**Comment by jflyper** [comment]
@digitalentity You are correct for I2C, but what about SPI? Authentic (correctly implemented) SPI devices are not listening to the bus unless selected, do they?
