### ISSUE TITLE
MATEKF405SE (Wing)

### ISSUE THREAD

**Issue by access3424** [iNavFlight/inav#3904]
Is it possible to edit target.c to get 4 motor outputs and the rest as servos? This is the stock configuration

 { TIM4, IO_TAG(PB7),    TIM_Channel_2, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM4,  TIM_USE_MC_MOTOR  | TIM_USE_FW_MOTOR },  //S1
    { TIM4, IO_TAG(PB6),    TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM4,  TIM_USE_MC_MOTOR  | TIM_USE_FW_MOTOR },  //S2
    { TIM3, IO_TAG(PB0),    TIM_Channel_3, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR  | TIM_USE_FW_SERVO },  //S3
    { TIM3, IO_TAG(PB1),    TIM_Channel_4, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR  | TIM_USE_FW_SERVO },  //S4
    { TIM8, IO_TAG(PC8),    TIM_Channel_3, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM8,  TIM_USE_MC_MOTOR  | TIM_USE_FW_SERVO },  //S5
    { TIM8, IO_TAG(PC9),    TIM_Channel_4, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM8,  TIM_USE_MC_MOTOR  | TIM_USE_FW_SERVO },  //S6
    { TIM12, IO_TAG(PB14),  TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM12, TIM_USE_MC_SERVO  | TIM_USE_FW_SERVO },  //S7
    { TIM12, IO_TAG(PB15),  TIM_Channel_2, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM12, TIM_USE_MC_SERVO  | TIM_USE_FW_SERVO },  //S8
    { TIM1, IO_TAG(PA8),    TIM_Channel_1, 1, IOCFG_AF_PP_PD, GPIO_AF_TIM1,  TIM_USE_MC_SERVO  | TIM_USE_FW_SERVO },  //S9

For example use Timers 4 and 3 for motor 1-4 and the other timers for the servos?

**Comment by b14ckyy** [comment]
Do you want it to use for a copter? 
then it should work just to load a Copter Mixer. So the right motors go to the S1 and S2 ports and the left Motors to the first 2 Servo outputs S3 and S4.

**Comment by access3424** [comment]
Thanks! Actually thinking for a hexacopter but i suppose its the same thing
