### ISSUE TITLE
add: Crossfire telemetry delivers RSSI / LQ 

### ISSUE THREAD

**Issue by Guillesan** [iNavFlight/inav#3907]
## Current Behavior

 Crossfire telemetry delivers RSSI / LQ on the same channel, it would be possible to obtain this separate data in the OSD. It would also be reasonable to be able to have the flight condition RFM2,1,0 (150 hz, 50 hz, 4hz). a greeting

## Desired Behavior
The RX Crossfire delivers RSSI / LQ by a single channel, to decide on the configuration. Inav could separate these two data, very relevant for me, to be able to present in the info in OSD.

## Who does this impact? Who is this for?
All TBS Crossfire users

**Comment by StewLG** [comment]
Guillesan, I think that currently the only way to get RSSI and LQ would be to put each of these on a different Crossfire channel. I don't think the Crossfire receiver protocol supports RSSI and LQ, which frankly is a major oversight on TBS's part.

If you are asking for an independent display of LQ in addition to RSSI, that could be done, and it would work for all receivers that break out LQ and RSSI on to channel values. 

I don't think there is any way to access the refresh rate (?) "RFM2,1,0 (150 hz, 50 hz, 4hz)". If TBS can display this on their OSDs, the are doing it via proprietary means.

People should correct me if I've gotten any thing wrong.

**Comment by wx4cb** [comment]
@StewLG you can setup (in the full module at the least) what channel has rssi and what has lq, you can even setup a channel that both has RSSI/LQ on the same channel, in fact that's usually how it's recommended to be setup. personally I just LQ and have an FMD and LQ alarm setup in my taranis.

As far as the FMD (0/1/2) i don't believe that's available outside of the transmitter module. The way i have mine setup is if it drops down to FMD-1 for more than 5 seconds then it plays a sound.

**Comment by KnuckleUpFPV** [comment]
The rfmd mode is sent over i2c. I think inav would be able to see the data stream from the crossfire and decode the information to be overlayed in the osd. From what I understand there is a buddy radar in the works, much like the tbs flarm setup. This would make inav very much like the core pro osd. Which would be amazing.

**Comment by wx4cb** [comment]
interesting... if it's on I2C, it MAY be possible to setup support for the BST port which (IIRC) is the name that TBS use for I2C. I might setup a spare micro rx bst port and hook it up to my Raspberry PI see what it sees.

**Comment by KnuckleUpFPV** [comment]
Yes bst port is just i2c. Should be able to see data like any other i2c device sends. You can use non tbs gps with the core pro if you use a serial to i2c converter, or a gps that is i2c compatible.

**Comment by wx4cb** [comment]
guess i have some work to do then :P LOL

**Comment by wx4cb** [comment]
well quick test... I see it on my bus: 

root /dev/pts/0:~ >i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 04 05 06 07 -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --

**Comment by KnuckleUpFPV** [comment]
Nice work

**Comment by wx4cb** [comment]
OK without any help from tbs (got a message to trappy waiting) i can't really go any further than this, i've tried dumping using i2cdump but i'm not getting any data from them as yet. 

Also, from what I can tell from threads on the pixhawk github, the only data is gps data and altitude/attitude, which we can already get from crsf. At least that's all that supports.

you could theoretically put FMD on a channel the same way you can put LQ on a channel using a taranis which might be the only way to get it atm

**Comment by KnuckleUpFPV** [comment]
Thats definitely a solution. Feeding it over a channel.

**Comment by wx4cb** [comment]
I tried doing it in the mixer with having a channel and multiplying the FMD but i couldn't figure it out, so the easy way to do it, which appears to work (untested) is I have the following:

Logical Switches:

L20 a=x RFMD 0 delay 0.3
L21 a=x RFMD 1 delay 0.3
L22 a=x RFMD 2 delay 0.3

Special Functions:

S20 L20 Override CH 10 -100
S21 L21 Override CH 10 0
S22 L22 Override CH 10 100

Now what I don't know is what telemetry appears on the CRSF side of things, i'm assuming it's just the channels and no actual telemetry is present there (hence the BST request) as all the FMD and rssi/LQ stuff is handled by the receiver.

PS. i'm still waiting on trappy to answer :D

**Comment by KnuckleUpFPV** [comment]
Wouldnt it be easier to set the rfmd to 1000 1500 2000. So if it see's rfmd2 then the aux channel would be at 2000. If its in rfmd1 it would be at 1500. And rfmd0 would be at 1000. But I'm not sure if the rfmd0 even works anymore. I think once its in rfmd1 it hangs there until failsafe. I believe the older firmwares would go all the way down but you had no actual crontrol. You could send mavlink messages and thats it. Im not positive on that though. I just remember reading somewhere that in 4hz mode control was limited. Minimum data being transmitted. The next thing to think about is this requires telemetry from the rx being sent back to the transmitter. Once out of range of the rx telemetry the osd would have to be able to freeze on the last received data. Which is still incredibly far. Ive gone over 5 miles and still in rfmd2 with full telemetry. So it wouldn't be an issue until way far out.

**Comment by wx4cb** [comment]
Thats what it dows.. -100/0/100 in the taranis is 1000-2000

**Comment by wx4cb** [comment]
I have no way to test range because of where I live. But i would assune the if it goes down (rx tele) then it would go to 0

**Comment by KnuckleUpFPV** [comment]
Im sorry man. When I looked the first time it looked as if you had set a range instead of setting the exact number. And you dont need to test range. You can do it right next to the quad or plane. Just go into crossfire lua and set force telemetry. That will immediately put it into rfmd1. If you lose rx telemetry it won't effect the transmitter. It would be pointless to have 2w if that was the case. It will hang in rfmd1.

**Comment by wx4cb** [comment]
oh ok cool.... i'll check that out and see, b ut theoretically it should work.. right now i'm reeling from destroying 4 planes this morning in user errors.

**Comment by KnuckleUpFPV** [comment]
Damn sorry to hear that.

**Comment by wx4cb** [comment]
@KnuckleUpFPV 

ok testing the settings that I did above in the taranis with the special functions etc, we can get FMD to the FC on a spare channel just like we do with the RSSI/LQ.

When it's RFMD 1 then the channel output is 1500, RFMD 2 is 2000. Now how to put that into the OSD, I don't know how to do.

**Comment by wx4cb** [comment]
question for @digitalentity  @shellixyz....

in https://github.com/iNavFlight/inav/blob/master/src/main/telemetry/crsf.c you have the FMD and power output defined already, but you're not pushing them by the look of it in processCrsf.

Is this because you're not getting them from anywhere?

**Comment by wx4cb** [comment]
it  looks like you're already getting it as part of the receiver frame (https://github.com/iNavFlight/inav/blob/dbdd1656a84ee4f09ebc14b4c0b86a9476a48f46/src/main/rx/crsf.c ) :

There's this at the top of the file

struct crsfPayloadLinkStatistics_s {
    uint8_t     uplinkRSSIAnt1;
    uint8_t     uplinkRSSIAnt2;
    uint8_t     uplinkLQ;
    int8_t      uplinkSNR;
    uint8_t     activeAntenna;
    uint8_t     rfMode;
    uint8_t     uplinkTXPower;
    uint8_t     downlinkRSSI;
    uint8_t     downlinkLQ;
    int8_t      downlinkSNR;
} __attribute__ ((__packed__));

Then at line 199 you process the link stat frame as looks like you are injecting the LQ into channel 17 So THEORETICALLY, we could get that out if you're already processing that frame.

            // Inject link quality into channel 17
            const crsfPayloadLinkStatistics_t* linkStats = (crsfPayloadLinkStatistics_t*)&crsfFrame.frame.payload;
            crsfChannelData[16] = scaleRange(constrain(linkStats->uplinkLQ, 0, 100), 0, 100, 191, 1791);    // will map to [1000;2000] range


Or am I mis reading this?

**Comment by shellixyz** [comment]
I don't know much about CRSF, @digitalentity wrote the CRSF RX handling code but looks like if you export `linkStats` you should be able to use whatever data you want to use from the `crsfPayloadLinkStatistics` struct providing it is really populated. If I understand correctly you want `rfMode` and `uplinkTXPower` ? You should be able to test easily if these members are populated by using the debug variable or `DEBUG_TRACE`.

> you have the FMD and power output defined already, but you're not pushing them by the look of it in processCrsf.

Why would you want to push RFMD and into `processCrsf` (that's handling the telemetry) ?

**Comment by wx4cb** [comment]
@shellixyz  that's why i was asking. wasn't sure if it's pushing it to the transmitter from the receiver (which didnt make sense) - was just typing thoughts as I perused the code.

yes, we need rfMode and TXPower. now MY question is, how do you use the debug_trace stuff ?

**Comment by digitalentity** [comment]
Frankly, CRSF stuff was mainly ported from Betaflight. Link statistics frame (`crsfPayloadLinkStatistics_s`) is parsed, but after I wrote that code I realised, that CRSF receivers don't send it to the FC. TBS told me that eventually it would be sent, so I kept the code, however looks like they never fixed it.

**Comment by wx4cb** [comment]
ok so it's not actually populated with anything then ?

and if not, how difficult is it to add a CLI variable (maybe) to say FMD is on XYZ channel? same as what's done with the RSSI atm?

**Comment by KnuckleUpFPV** [comment]
Maybe this alpha code of 2.87 crossfire pushes it to the fc. If i get time tonight I will try and take a look.

**Comment by shellixyz** [comment]
@wx4cb 

> now MY question is, how do you use the debug_trace stuff ?

In this case it would be easier to populate the debug array. `#include <build/debug.h>` then `debug` is a 4 cell `int` array. You can visualize its contents in the sensors tab of the configurator. For DEBUG_TRACE all you need to do is call `DEBUG_TRACE_SYNC(format, ...)`. The args are the same as `printf`. Then use [msp-tool](https://github.com/fiam/msp-tool) to display the messages.

**Comment by wx4cb** [comment]
@shellixyz 

So, increase DEBUG16_VALUE_COUNT to 5, 

add (for example)    DEBUG_CRSF to the enum debugType_e (where would I define this though?)

and then I could (in rx/crsf.c) put something line

DEBUG_TRACE_SYNC("Got LinkStat Packet: LQ=%d", constrain(linkStats->uplinkLQ, 0, 100))

??

**Comment by shellixyz** [comment]
@wx4cb I would do it like that for example:

```
diff --git a/src/main/rx/crsf.c b/src/main/rx/crsf.c
index 04c0a83b0..72e3d71cd 100755
--- a/src/main/rx/crsf.c
+++ b/src/main/rx/crsf.c
@@ -207,6 +207,8 @@ STATIC_UNIT_TESTED uint8_t crsfFrameStatus(rxRuntimeConfig_t *rxRuntimeConfig)
             // Inject link quality into channel 17
             const crsfPayloadLinkStatistics_t* linkStats = (crsfPayloadLinkStatistics_t*)&crsfFrame.frame.payload;
             crsfChannelData[16] = scaleRange(constrain(linkStats->uplinkLQ, 0, 100), 0, 100, 191, 1791);    // will map to [1000;2000] range
+            debug[0] = linkStats->rfMode;
+            debug[1] = linkStats->uplinkTXPower;
 
             // This is not RC channels frame, update channel value but don't indicate frame completion
             return RX_FRAME_PENDING;
```

Then you only need to monitor the debug array from the configurator's sensors tab. Just make sure the `debug_mode` setting is set to `NONE`.

**Comment by wx4cb** [comment]
im assuming debug_mode is the little check boxes ?

**Comment by wx4cb** [comment]
so i tried adding those and also some DEBUG_TRACE_SYNC calls but msp tool isn't showing anything other than the board bootup. is there something i'm supposed to do to "turn on" that trace?

**Comment by shellixyz** [comment]
No I mean `debug_mode` the firmware setting. `set debug_mode = NONE`. Otherwise the values you put in the debug array will be overwritten.

For DEBUG_TRACE IIRC msp-tool should configure everything. Launch it then reboot the board by pressing r.

**Comment by wx4cb** [comment]
yea in that case, debug_mode is already none

as for msp-tool, i do that, it disconnects cus the board reboots and discos the usb, but as soon as i hear it come back, i start it and i get the accel calibration messages, but then nothing after.

BTW, trappy is going to try and get me the info that we may need, but he did say that it would be better to look at the CRSF packets. he said he'd get back to me this week.

**Comment by shellixyz** [comment]
@wx4cb Why are you not doing it with the `debug` variable ?

**Comment by wx4cb** [comment]
i have done both @shellixyz and I just get a flat line in the sensors tab. I even tried physically going "debug[2] = 1" and i still get a flat line at zero.

I have set debug=none in the CLI, and i unticked everything from the sensors tab EXCEPT debug

	    // WX4CB - Add debug lines to see what data we're getting from the CRSF frame
	    DEBUG_TRACE_SYNC("CRSF LQSTAT PACKET");
	    DEBUG_TRACE_SYNC("RFMD: %d", linkStats->rfMode);
            DEBUG_TRACE_SYNC("UPWR: %d", linkStats->uplinkTXPower);

            debug[0] = linkStats->rfMode;
            debug[1] = linkStats->uplinkTXPower;

**Comment by shellixyz** [comment]
That's strange. I guess your code is never executed then.

```
diff --git a/src/main/fc/fc_core.c b/src/main/fc/fc_core.c
index 09ab4a0a9..161831a7e 100755
--- a/src/main/fc/fc_core.c
+++ b/src/main/fc/fc_core.c
@@ -707,6 +707,11 @@ void taskMainPidLoop(timeUs_t currentTimeUs)
     cycleTime = getTaskDeltaTime(TASK_SELF);
     dT = (float)cycleTime * 0.000001f;
 
+    debug[0] = 1;
+    debug[1] = 2;
+    debug[2] = 3;
+    debug[3] = 4;
+
     if (ARMING_FLAG(ARMED) && ((!STATE(FIXED_WING)) || (!isNavLaunchEnabled()) || (isNavLaunchEnabled() && isFixedWingLaunchDetected()))) {
         flightTime += cycleTime;
     }
```

![capture d ecran de 2018-12-02 23-51-37](https://user-images.githubusercontent.com/4030264/49346072-5a439400-f68d-11e8-82d5-cbedfa08d894.png)

**Comment by wx4cb** [comment]
that's what I was thinking. let's see what trappy can come up with i guess.

i'm wondering if i can put in the following whether it would work as it's a uint:

DEBUG_TRACE_SYNC("CRSF Frame Type: %d", crsfFrame.frame.type);

above this line

if (crsfFrame.frame.type == CRSF_FRAMETYPE_RC_CHANNELS_PACKED)

**Comment by shellixyz** [comment]
`crsfFrameStatus()` should be executed at 50Hz as soon as you set `serialrx_provider` to `CRSF`.

I guess the only explanation then is that  the receiver never sends a `CRSF_FRAMETYPE_LINK_STATISTICS` type frame as I imagine you put your code inside `else if (crsfFrame.frame.type == CRSF_FRAMETYPE_LINK_STATISTICS) {`

**Comment by wx4cb** [comment]
exactly where I put it. I was figuring the same thing.

**Comment by shellixyz** [comment]
> i'm wondering if i can put in the following whether it would work as it's a uint:
> DEBUG_TRACE_SYNC("CRSF Frame Type: %d", crsfFrame.frame.type);

Should work yes
