### ISSUE TITLE
INAV 2.0 Matek F411 FC Disarming in Flight!

### ISSUE THREAD

**Issue by JDFPV** [iNavFlight/inav#3913]
INAV 2.0 Matek F411 FC Disarming in Flight! Mini AR Wing

 Using INAV 2.0 on a Matek F411 FC. Default settings for the 600mm wing presets. I also followed the steps to enter the commands in the cli from the inav wiki fixed wing page. So after launch around 4 minutes into flight i was feeling everything was going well... Then all or a sudden i see the stat screen and have 0 control over the plane. So i flipped the disarm switch, lowered the throttle and flipped the switch to arm and i regain control. So i was puzzled thinking my radio signal had dropped out and some how failsafe didn't kick in.. Which i had confirmed that failsafe did work when i tested it on the bench. So i kept flying just to see if it would happen again. 6 minutes later the stat screen popped back up again. So i repeated the step as mentioned before to regain control and i could not get any response out of the FC causing my wing to crash. So i took it home thinking the rx for radio control went bad and installed a new one. And i went over all the setting in inav. Everything looked ok. Next day, same thing happened again but i regain controlled and landed. Bug possibly or glitch?? Video link below of osd footage of flight.

https://youtu.be/KScxmxyXUL4

 # dump

# version
# INAV/MATEKF411 2.0.0 Aug 20 2018 / 19:23:35 (dbdd1656a)

# resources

# mixer

mmix reset

mmix 0 1.000 0.000 0.000 0.000
mmix 1 1.000 0.000 0.000 0.000

# servo mix
smix reset

smix 0 3 0 50 0
smix 1 3 1 50 0
smix 2 4 0 -50 0
smix 3 4 1 50 0

# servo
servo 0 1000 2000 1500 100
servo 1 1000 2000 1500 100
servo 2 1000 2000 1500 100
servo 3 1000 2000 1500 -100
servo 4 1000 2000 1500 100
servo 5 1000 2000 1500 100
servo 6 1000 2000 1500 100
servo 7 1000 2000 1500 100

# feature
feature -THR_VBAT_COMP
feature -VBAT
feature -TX_PROF_SEL
feature -BAT_PROF_AUTOSWITCH
feature -MOTOR_STOP
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature -FW_LAUNCH
feature -TRACE
feature VBAT
feature TX_PROF_SEL
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature TELEMETRY
feature CURRENT_METER
feature AIRMODE
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED

# map
map AETR

# serial
serial 20 1 115200 38400 0 115200
serial 0 64 115200 38400 0 115200
serial 1 2 115200 38400 0 115200
serial 30 0 115200 38400 0 115200

# aux
aux 0 0 3 1175 1350
aux 1 2 0 1000 1175
aux 2 3 0 1400 1600
aux 3 8 1 1875 2000
aux 4 19 0 1850 2025
aux 5 35 0 1425 1600
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 2000
set gyro_sync = ON
set align_gyro = DEFAULT
set gyro_hardware_lpf = 188HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set gyro_stage2_lowpass_hz = 0
set vbat_adc_channel = 1
set rssi_adc_channel = 0
set current_adc_channel = 2
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6000
set acc_lpf_hz = 15
set acczero_x = 80
set acczero_y = -13
set acczero_z = -359
set accgain_x = 4116
set accgain_y = 4082
set accgain_z = 4031
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set mag_calibration_time = 30
set align_mag_roll = 0
set align_mag_pitch = 0
set align_mag_yaw = 0
set baro_hardware = NONE
set baro_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf = 0.600
set pitot_scale = 1.000
set receiver_type = SERIAL
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_min = 0
set rssi_max = 100
set sbus_sync_interval = 3000
set rc_smoothing = ON
set serialrx_provider = SBUS
set serialrx_inverted = OFF
set rx_spi_rf_channel_count = 0
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set min_throttle = 1000
set max_throttle = 2000
set min_command = 1000
set motor_pwm_rate = 400
set motor_accel_time = 0
set motor_decel_time = 0
set motor_pwm_protocol = STANDARD
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 0
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = -5
set align_board_pitch = -12
set align_board_yaw = -900
set vbat_scale = 1100
set current_meter_scale = 423
set current_meter_offset = 0
set current_meter_type = ADC
set bat_voltage_src = RAW
set cruise_power = 0
set idle_power = 0
set rth_energy_margin = 5
set thr_comp_weight = 1.000
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set platform_type = AIRPLANE
set has_flaps = OFF
set model_preview_type = 8
set fw_min_throttle_down_pitch = 0
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 180
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 60
set switch_disarm_delay = 250
set gps_provider = UBLOX
set gps_sbas_mode = NONE
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_ublox_use_galileo = OFF
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_allow_dead_reckoning = OFF
set inav_reset_altitude = FIRST_ARM
set inav_reset_home = EACH_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p = 3.500
set inav_w_z_surface_v = 6.100
set inav_w_xy_flow_p = 1.000
set inav_w_xy_flow_v = 2.000
set inav_w_z_baro_p = 0.350
set inav_w_z_gps_p = 0.200
set inav_w_z_gps_v = 0.100
set inav_w_xy_gps_p = 1.000
set inav_w_xy_gps_v = 2.000
set inav_w_z_res_v = 0.500
set inav_w_xy_res_v = 0.500
set inav_w_acc_bias = 0.010
set inav_max_eph_epv = 1000.000
set inav_baro_epv = 100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_overrides_motor_stop = ON
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = ALWAYS
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_max_terrain_follow_alt = 100
set nav_rth_altitude = 12192
set nav_rth_home_altitude = 0
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1500
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1800
set nav_fw_bank_angle = 35
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 7
set nav_fw_loiter_radius = 5000
set nav_fw_cruise_speed = 0
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_min_time = 0
set nav_fw_launch_timeout = 5000
set nav_fw_launch_max_altitude = 0
set nav_fw_launch_climb_angle = 18
set nav_fw_cruise_yaw_rate = 20
set nav_fw_allow_manual_thr_increase = OFF
set telemetry_switch = OFF
set telemetry_inverted = OFF
set frsky_default_latitude = 0.000
set frsky_default_longitude = 0.000
set frsky_coordinates_format = 0
set frsky_unit = METRIC
set frsky_vfas_precision = 0
set frsky_pitch_roll = OFF
set report_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_unit = MAH
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set osd_video_system = AUTO
set osd_row_shiftdown = 0
set osd_units = IMPERIAL
set osd_stats_energy_unit = MAH
set osd_rssi_alarm = 20
set osd_time_alarm = 100
set osd_alt_alarm = 2134
set osd_dist_alarm = 48280
set osd_neg_alt_alarm = 5
set osd_artificial_horizon_reverse_roll = OFF
set osd_crosshairs_style = DEFAULT
set osd_left_sidebar_scroll = NONE
set osd_right_sidebar_scroll = NONE
set osd_sidebar_scroll_arrows = OFF
set osd_main_voltage_decimals = 1
set osd_coordinate_digits = 9
set osd_estimations_wind_compensation = ON
set i2c_speed = 400KHZ
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set name =
set mode_range_logic_operator = OR
set stats = ON
set stats_total_time = 1016
set stats_total_dist = 13835
set stats_total_energy = 12427
set tz_offset = 0
set tz_automatic_dst = OFF
set display_force_sw_blink = OFF
set vtx_halfduplex = ON
set vtx_band = 4
set vtx_channel = 1
set vtx_power = 1
set vtx_low_power_disarm = OFF
set vtx_freq = 5740
set vtx_pit_mode_freq = 0

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 15
set fw_i_pitch = 40
set fw_ff_pitch = 15
set fw_p_roll = 15
set fw_i_roll = 30
set fw_ff_roll = 15
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 600
set max_angle_inclination_pit = 600
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight = 1.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed = 1000.000
set fw_turn_assist_yaw_gain = 1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_windup = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 40
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_mc_heading_p = 60
set nav_fw_pos_z_p = 40
set nav_fw_pos_z_i = 5
set nav_fw_pos_z_d = 10
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set nav_fw_heading_p = 60
set thr_mid = 50
set thr_expo = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
set fw_tpa_time_constant = 0
set rc_expo = 70
set rc_yaw_expo = 20
set roll_rate = 40
set pitch_rate = 15
set yaw_rate = 20
set manual_rc_expo = 70
set manual_rc_yaw_expo = 20
set manual_roll_rate = 100
set manual_pitch_rate = 100
set manual_yaw_rate = 100

# battery_profile
battery_profile 1

set bat_cells = 0
set vbat_cell_detect_voltage = 430
set vbat_max_cell_voltage = 420
set vbat_min_cell_voltage = 250
set vbat_warning_cell_voltage = 275
set battery_capacity = 0
set battery_capacity_warning = 0
set battery_capacity_critical = 0
set battery_capacity_unit = MAH

#

**Comment by teckel12** [comment]
@JDFPV The video says that you disarmed by `SWITCH`.

**Comment by teckel12** [comment]
@JDFPV I would `set disarm_kill_switch = OFF` so the kill switch is disabled unless the throttle is also low.  With this set to `ON`, the kill switch works no matter what the throttle position.

**Comment by digitalentity** [comment]
@JDFPV what radio system are you using? Some radio systems (most notable FrSky R9) are known to send random channel values on some occasions. 

INAV 2.0 uses a lot of fixes to make RC link more reliable, but you should not rely on firmware to fix otherwise broken hardware.. You can try setting `sbus_sync_interval = 1500`, it will make INAV work correctly with receivers violating SBUS standard. Disabling `disarm_kill_switch` is also a good idea to make sure you don't accidentally disarm while throttle is above zero. 

From video this looks like genuine switch disarm - my guess is that it's a flaky radio hardware.

**Comment by JDFPV** [comment]
i'm using dragonlink v2 on a devo 10 radio. Been using it for years with 0 problem. And actually i flew my other plane after this and it has the say profile settings same disarm switch and it works fine. But i will try the set disarm_kill_switch = OFF.

**Comment by digitalentity** [comment]
It may be a problem with particular receiver. I assume each of your planes have it's own receiver.

**Comment by JDFPV** [comment]
Each plane uses a micro Dragonlink. 3 planes have inav 2 has fy41ap lite flight controllers.

**Comment by JDFPV** [comment]
All other planes work fine with inav. Using 1.8 on the Nano Goblin. Using 1.9.1 on my fx79.

**Comment by digitalentity** [comment]
The only thing we can conclude from your video - FC was disarmed by a switch. Without BB log it's hard to troubleshoot any further. Since MATEK411 doesn't have the onboard flash, using old good OpenLog is the only option here.

**Comment by JDFPV** [comment]
And I actually changed the rx on the 2nd flight.

**Comment by JDFPV** [comment]
what is OpenLog ?

**Comment by giacomo892** [comment]
@JDFPV  https://www.sparkfun.com/products/13712 Serial logging device.

**Comment by JDFPV** [comment]
I totally dont have space for it in the plane I'm having trouble with. I will test fly it with the changes made this weekend and I will report back to you guys. Thanks

**Comment by JDFPV** [comment]
Problem solved. The internal 5v 3a bec on the brand new matek f411 board went bad. Causing the rx to go nuts with over voltage. Thanks INAV!
