### ISSUE TITLE
Migrate to threaded scheduler

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#3915]
Allow low-priority tasks to yield.

Current scheduler assumes that each task iteration will finish in much less than one gyro/pid cycle time. Full-graphic OSD, some operations on character OSD, complex position estimation/navigation code is quite time-consuming and in some cases will cause significant cycle time jitter. 

Migration to full RTOS preemptive scheduler is likely an overkill, something like coroutines should be enough.

**Comment by StewLG** [comment]
I believe I am suffering from just these performance issues with this iNav related work:

https://github.com/StewLG/CraftServices/

I get incomplete frame draws when (for example) too many waypoints are drawn on the radar screen.

**Comment by digitalentity** [comment]
Partly done in #3962. Protothreads/coroutines could be seamlessly integrated into current scheduler and eventually replace the scheduler.

**Comment by Linjieqiang** [comment]
@digitalentity What about use FreeRTOS with INAV?

**Comment by digitalentity** [comment]
@Linjieqiang INAV was not designed to be thread-safe. RTOS will create more problems that it will solve at the moment.

**Comment by Linjieqiang** [comment]
Okay. Thanks.
