### ISSUE TITLE
OMNINXT F7 can't load fonts or read logs

### ISSUE THREAD

**Issue by CaptainYags** [iNavFlight/inav#3916]
Airbot OMNINXT F7
iNav version INAV/OMNIBUSF7NXT 2.0.0 Aug 20 2018 / 19:15:39 (dbdd165)

The board/configurator hangs when I do either of:
-Try to download blackbox data
-Try to upload a font for the OSD

**Comment by CaptainYags** [comment]
I tried flashing the board to Betaflight, and with Betaflight I can download the blackbox and upload fonts.  After that I flashed back to iNav, and I can't upload/download again.

**Comment by VladimirShakhov** [comment]
I confirm the problem - the font in the osd does not load.

**Comment by Rclay11541** [comment]
I too confirm. ODD does not function, upon attempting  to load a different  font as a work around, I also can confirm  the FC hangs indefinitely.

**Comment by digitalentity** [comment]
What OS are you using? MacOS?

**Comment by VladimirShakhov** [comment]
I'm using win7 64bit.

**Comment by Rclay11541** [comment]
I'm using Win 7, 64 bit as well.

Further, the new update to INAV 2.1 has caused an error in RTH. Exact same settings and in version 2.0 RTH works excellent. In V2.1 it goes off in a random direction and at times upon engaging RTH shoots way up at max throttle in altitude....other times it's a slow accent.

**Comment by Rclay11541** [comment]
Further OSD still doesn't function in v2.0.1 or v2.0.0

**Comment by Rclay11541** [comment]
Hey Vladimir - I figured out how to change fonts...

1) Go to Config tab and DISABLE the OSD.
2) Go back to OSD, now you can change fonts.
3) Go to Config tab and ENABLE the OSD.

**Comment by VladimirShakhov** [comment]
unfortunately, the osd does not work (((

**Comment by Moris644** [comment]
OSD does not work!

**Comment by digitalentity** [comment]
Fixed by #4026
