### ISSUE TITLE
Inav VTX 

### ISSUE THREAD

**Issue by cheetah2k** [iNavFlight/inav#3924]
## Current Behavior
Using a Furious FPV Stealth LR 700mw vtx.  It uses the tramp setting in configuration.  It has 25/200/500/700mW modes.  To select 700mw in the iNAV OSD you need to select 600 value.  When I select the 600 Value it throws up an error message and cannot fly.

## Steps to Reproduce
Select 600mW under the VTX settings in OSD

## Suggested solution(s)
In iNAV when 600mW is selected it make the VTX power = 5 (refer below)

vtx_power = 5
Allowed range: 1 - 4

Allow the max range VTX power to be = 1-5

**Comment by DzikuVx** [comment]
fixed in #4008
