### ISSUE TITLE
Waypoint mission not working out of manual RTH

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#3934]
## Current Behavior

When in manual RTH via mode switch, direct jump to WP Nav Mode puts fixed wing into Acro Mode. 

## Steps to Reproduce

1. Setup One channel for modes with 3 or more steps and upload a mission
2. Start flying
3. set to RTH
4. switch to NAV WP directly from RTH

Result: Plane will go into Acro Mode
- Log reports NAV WP is active but OSD shows Acro

Workaround for me: If I use loiter and switch the 3-pos switch from 1 to 3 through the cruise mode (explanation below) it works.

## Expected behavior
On a single Mode Channel, it should be possible to switch between all modes directly Independent from order. I want to start a Mission from Home Point by having the RTH Circle as start state. 

## Additional context
My Mode CLI:

```
# aux
aux 0 0 0 1700 2100
aux 1 1 2 1100 1300
aux 2 3 2 1500 1900
aux 3 9 2 1500 1700
aux 4 8 2 1300 1500
aux 5 19 2 1900 2100
aux 6 35 2 1700 1900
aux 7 28 1 1700 2100
aux 8 32 4 1175 1475
aux 9 33 4 1475 1800
aux 10 34 4 1800 2100
```

I Use Following Switch Config on my Flysky i6

SWC (3-pos) + SWD (2-pos) mixed together to channel 7. So I have 6 Positions:

```
|----------|----------|----------|----------|----------|----------|
|   ACRO   |   ANGLE  |  RTH     | POS HLD  | CRUISE   |   WP
                                   ALT HLD  | ALT HLD 
```

My usage: The 3-pos switch changes between my main flight modes. Acro, Angle and RTH
The 2-pos switch is an alternate-switch to secondary modes. In Acro I use the second switch to "park" the craft mid air. In Angle mode I use it to switch to cruise for longer flights so I can leave the sticks. And RTH is used as a starting point for missions so I don't get weird entrance angles. 

So usually I switch from RTH, when it loiters, into NAV WP mode. This worked fine on 1.9.1. 

LOG where it happens (The log shows NAV WP Mode but you can see that it does not control the plane and the OSD shows AIR Mode) at 6:35

[LOG00024.zip](https://github.com/iNavFlight/inav/files/2498314/LOG00024.zip)

DUMP:
[Main 3 INAVMATEKF405SE 2.0.0 Aug 20 2018  192234 (dbdd1656a).txt](https://github.com/iNavFlight/inav/files/2498328/Main.3.INAVMATEKF405SE.2.0.0.Aug.20.2018.192234.dbdd1656a.txt)

---

- FC Board name and vendor: Matek F505 Wing
- INAV version string: # INAV/MATEKF405SE 2.0.0 Aug 20 2018 / 19:22:34 (dbdd1656a)

**Comment by stronnag** [comment]
I took the liberty of replaying the log https://youtu.be/Pnb75RppDBY and i'm not sure I understand the problem.

* You have a mission with 9 WPs loaded, validated.
* Prior to initiating the mission, the RTH on FAILSAFE looks excellent, taking the aircraft home until aborted.
* You enter the first WP mission just prior to 2 minutes, from **PH** mode. We don't have the mission file to validate, but it appears to fly a plausible mission up / down the brown area of the field. Constrained by not  without mission file to compare, the FC seems to control the aircraft well. Turns are clean.
* The second mission invocation (again, from **PH** mode), it manually aborted just as the craft is starting to turn to the first (SE) WP (=> cruise mode)

For completeness, here's what the BB log gives as the state transitions:
```
$ inav_modes.rb LOG00024.TXT 
LOG00024.TXT: INAV 2.0.0 (dbdd1656a) MATEKF405SE
Iteration	Time(s)	Elapsed(s)	State
        0	 840.6	(   0.0)	nav_state_launch_wait (26)
     5635	 846.3	(   5.7)	nav_state_launch_in_progress (28)
    10634	 851.3	(  10.7)	nav_state_idle (1)
    13152	 853.8	(  13.2)	nav_state_poshold_3d_in_progress (7)
    36384	 877.1	(  36.5)	nav_state_idle (1)
 907.5	(  66.9)	F/S=RETURN_TO_HOME (1530,1581,1501,1676);(1,0)
    66669	 907.5	(  66.9)	nav_state_rth_head_home (10)
 908.8	(  68.2)	F/S=IDLE (1388,1469,1500,1726);(1,1)
    67990	 908.8	(  68.2)	nav_state_idle (1)
 911.4	(  70.8)	F/S=RETURN_TO_HOME (1445,1501,1501,1730);(1,0)
    70575	 911.4	(  70.8)	nav_state_rth_head_home (10)
 930.0	(  89.4)	F/S=IDLE (1471,1264,1500,1650);(1,1)
    89100	 930.0	(  89.4)	nav_state_idle (1)
 932.6	(  92.0)	F/S=RETURN_TO_HOME (1453,1283,1500,1669);(1,0)
    91639	 932.6	(  92.0)	nav_state_rth_head_home (10)
 934.1	(  93.5)	F/S=IDLE (1425,1202,1500,1704);(1,1)
    93159	 934.1	(  93.5)	nav_state_idle (1)
   109952	 951.0	( 110.3)	nav_state_poshold_3d_in_progress (7)
   110912	 951.9	( 111.3)	nav_state_cruise_2d_in_progress (30)
   111008	 952.0	( 111.4)	nav_state_waypoint_in_progress (17)
   239258	1080.7	( 240.1)	nav_state_waypoint_finished (20)
   317952	1159.7	( 319.1)	nav_state_poshold_3d_in_progress (7)
   319680	1161.4	( 320.8)	nav_state_idle (1)
1210.9	( 370.3)	F/S=RETURN_TO_HOME (1552,1315,1500,1631);(1,0)
   368985	1210.9	( 370.3)	nav_state_rth_head_home (10)
1226.0	( 385.4)	F/S=IDLE (1501,1171,1500,1584);(1,1)
1228.9	( 388.2)	F/S=RETURN_TO_HOME (1501,1500,1499,1584);(1,0)
1232.6	( 392.0)	F/S=IDLE (1501,1401,1500,1584);(1,1)
   393792	1235.8	( 395.2)	nav_state_idle (1)
   395136	1237.1	( 396.5)	nav_state_rth_head_home (10)
   395936	1237.9	( 397.3)	nav_state_althold_in_progress (3)
   396000	1238.0	( 397.4)	nav_state_idle (1)
   397120	1239.1	( 398.5)	nav_state_poshold_3d_in_progress (7)
   401952	1244.0	( 403.4)	nav_state_waypoint_in_progress (17)
   404416	1246.5	( 405.8)	nav_state_cruise_2d_in_progress (30)
   404448	1246.5	( 405.9)	nav_state_poshold_3d_in_progress (7)
   405152	1247.2	( 406.6)	nav_state_idle (1)
   485891	1328.2	( 487.6)	end of log
Disarmed by: SWITCH
```

What am I misinterpreting?

**Comment by b14ckyy** [comment]
Sorry. My Fault... uploaded wrong log. That was the last flight as i figured out that it works when coming from loiter/cruise mode. Check this one at 0:27. I switched to RTH before and then directly into WP NAV. But the plane goes into AIR Mode. 

Never tried that Blackbox replay before. Should test it too. I Only have Ubuntu on my Notebook because of MWPTools :D 

[LOG00023.zip](https://github.com/iNavFlight/inav/files/2498382/LOG00023.zip)

**Comment by stronnag** [comment]
Here, I see no attempt to enter WP mode:
```
$ inav_modes.rb /tmp/LOG00023.TXT 
LOG00023.TXT: INAV 2.0.0 (dbdd1656a) MATEKF405SE
Iteration	Time(s)	Elapsed(s)	State
        0	 127.6	(   0.0)	nav_state_launch_wait (26)
     7721	 135.3	(   7.7)	nav_state_launch_in_progress (28)
    11523	 139.2	(  11.6)	nav_state_idle (1)
    13504	 141.1	(  13.6)	nav_state_althold_in_progress (3)
    13536	 141.2	(  13.6)	nav_state_rth_head_home (10)
    20784	 148.4	(  20.9)	nav_state_cruise_2d_initialize (29)
    27392	 155.1	(  27.5)	nav_state_idle (1)
    52288	 180.1	(  52.5)	nav_state_cruise_2d_in_progress (30)
    52576	 180.4	(  52.8)	nav_state_poshold_3d_in_progress (7)
    89632	 217.5	(  90.0)	nav_state_idle (1)
   192064	 320.3	( 192.7)	nav_state_althold_in_progress (3)
   192096	 320.4	( 192.8)	nav_state_rth_head_home (10)
   233279	 361.7	( 234.1)	nav_state_cruise_2d_initialize (29)
   244416	 372.9	( 245.3)	nav_state_althold_in_progress (3)
   244544	 373.0	( 245.4)	nav_state_idle (1)
   248128	 376.6	( 249.0)	nav_state_althold_in_progress (3)
   248608	 377.1	( 249.5)	nav_state_cruise_2d_in_progress (30)
   258586	 387.1	( 259.5)	nav_state_cruise_2d_adjusting (31)
   258708	 387.2	( 259.6)	nav_state_cruise_2d_in_progress (30)
   270376	 398.9	( 271.3)	nav_state_cruise_2d_adjusting (31)
   280128	 408.7	( 281.1)	nav_state_cruise_2d_in_progress (30)
   283639	 412.2	( 284.6)	nav_state_cruise_2d_adjusting (31)
   284191	 412.8	( 285.2)	nav_state_cruise_2d_in_progress (30)
   286016	 414.6	( 287.0)	nav_state_poshold_3d_in_progress (7)
   288512	 417.1	( 289.5)	nav_state_idle (1)
   291136	 419.8	( 292.2)	nav_state_althold_in_progress (3)
   313344	 442.0	( 314.5)	nav_state_idle (1)
 476.6	( 349.0)	F/S=RETURN_TO_HOME (1384,1239,1501,1625);(1,0)
   347775	 476.6	( 349.0)	nav_state_rth_head_home (10)
 479.4	( 351.9)	F/S=IDLE (1450,1337,1500,1627);(1,1)
   350606	 479.4	( 351.9)	nav_state_idle (1)
 487.9	( 360.3)	F/S=RETURN_TO_HOME (1613,1697,1500,1627);(1,0)
   359025	 487.9	( 360.3)	nav_state_rth_head_home (10)
 495.0	( 367.4)	F/S=IDLE (1558,1501,1500,1634);(1,1)
   366127	 495.0	( 367.4)	nav_state_idle (1)
   395808	 524.8	( 397.2)	nav_state_althold_in_progress (3)
   440128	 569.3	( 441.7)	nav_state_idle (1)
 588.3	( 460.7)	F/S=RETURN_TO_HOME (1448,1501,1501,1433);(1,0)
   459078	 588.3	( 460.7)	nav_state_rth_head_home (10)
   529224	 658.7	( 531.1)	nav_state_cruise_2d_initialize (29)
 684.0	( 556.4)	F/S=IDLE (1501,1551,1500,1435);(1,1)
   554448	 684.0	( 556.4)	nav_state_idle (1)
   613177	 742.9	( 615.4)	end of log
Disarmed by: SWITCH
```

(which may well be your point, but there is no WP attempt in the log).

**Comment by stronnag** [comment]
I also have this 'back of my mind' feeling that RTH -> WP is a no longer a valid transition in 2.0. Let me see if I can rationalise that.

**Comment by b14ckyy** [comment]
Yes that's exactly my point. I have uploaded missions via Mission Planner for inav on android and via MWP tools. Even via INAV configurator. And then downloaded them again to make sure they are saved.  But never worked (until the last flight where i activated it from PH instead of man RTH before). 

Here is another one (short log). In the Blackbox explorer you can clearly see that i switched to NAV WP ON via switch but it activates manual state at 00:20. And then I even landed in this mode without any further mode change. Blackbox replay in MWP does not work right now for me... seems that i missed to install the BB viewer. 

The last long log where the WP mission worked, was only by accident because a few flights before i also uploaded the same mission to the EEPROM so it was still saved after battery change. 
[LOG00020.TXT](https://github.com/iNavFlight/inav/files/2498392/LOG00020.TXT)

> I also have this 'back of my mind' feeling that RTH -> WP is a no longer a valid transition in 2.0. Let me see if I can rationalise that.

That would be bad. I like that way to autolaunch, just flick a switch to get in start position and flick another switch to go on the mission, without even touch the sticks one time. Just for landing.

**Comment by stronnag** [comment]
My `back of the mind' itch is that #3448 is the reason for this new behaviour and the answer is "don't do that then", particularly as entering WP from other modes (Acro, Horizon, Angle, PH) works. It also seems reasonable to me (though only flying iNav on MR) that trying to enter WP from RTH is 'weird';  but that's just my biased (and weird) opinion.

Ultimately the nav state machine is complex enough as it is, and we may well have to constrain behaviours to 'reasonable', for some random definition of 'reasonable'. But I'm speculating, you need one of real experts to jump in for a definitive opinion.

**Comment by b14ckyy** [comment]
Ok thank you for checking back. At least I have an answer now and a workaround… I'll use POSHOLD and then Mission, so I only have to rethink to first switch SW4 and then SW3 instead of 3 > 4. Then it works fine. 

But if any of these experts could look into it anyway some time, that would be nice :)

I understand that it doesn't make sense on an copter but on a plane it is useful. 

I also could just switch the mode positions (making WP NAV on SW3 position 3 and use RTH as my "alternate mode" via SW4 but then, in an emergency scenario like dropped video or so, i need to remember to bring both switches into down position if coming from other modes. During a mission itself, RTH is unlikely needed for emergency. 

One more thing (i can open a feature request if it makes sense): 

Would it be possible to implement a feature, to temporary disable Failsafe RTH while in WP Mode? 
As you can see I have about 700 or 800m maximum range with my remote and 1km in complete open areas. I'd like to do some autonomous long range missions like 5km out and back in completely unpopulated areas of course where I won't be able to get that range with legal transmitters. But I wouldn't fly with completely disabled FS in manual mode.

**Comment by wilco1967** [comment]
> Would it be possible to implement a feature, to temporary disable Failsafe RTH while in WP Mode?
As you can see I have about 700 or 800m maximum range with my remote and 1km in complete open areas. I'd like to do some autonomous long range missions like 5km out and back in completely unpopulated areas of course where I won't be able to get that range with legal transmitters. But I wouldn't fly with completely disabled FS in manual mode. <

You could simply set your failsafe to 'DO NOTHING', rather then RTH
This works fine when flying a WP mission, or some other stabilzed mode. However, if you fly in manual, and you shutdown the transmitter (or fly out of range), it will still 'do nothing', i.e. it might roll over and crash..... 
It would be nice it we would have an option to 'do nothing' and continue on a WP mission, while we were in an active WP mission, and RTH if we were in any other mode than WP....
But that hasn't been done yet...

I've mine set to do nothing for a while now, and although there is a risk, you usually don't loose signal for more than a few seconds. So you should be able to activate a manual RTH across, if you've lost signal for a few moments.... (But not if you flew behind a hill or so....)

**Comment by shellixyz** [comment]
@b14ckyy There is already a feature request about this: #2972
