### ISSUE TITLE
Low freq wobble

### ISSUE THREAD

**Issue by access3424** [iNavFlight/inav#3935]
After changing FC on my 500mm quad there is a low frequency wobble even in acro mode. Tried all sorts of tuning with high and low P and D gains and with heavy filtering on and off.

The excact same quad with kakutef4 had no issues. Introduced the matekf405wing and cant remove this wobble

**Comment by rb1205** [comment]
Low freq wobbling **usually** means too high I factor. But we'll need a log to say anything more.

**Comment by access3424** [comment]
Well logging doesn’t work because the matekf405wing is especially picky on what sd you put in. So far cant make it work on any sd i used

**Comment by b14ckyy** [comment]
Try formatting with https://www.sdcard.org/downloads/formatter_4/

Do not use SD bigger than 8GB

**Comment by DzikuVx** [comment]
low freq wobble is either too much Igains or a gyro LPF is too low (for example 42Hz)

**Comment by access3424** [comment]
Whats the difference between the two gyro LPFs? The one in the configuration tab and the one in the PID tunning tab? It sais the one is hardware and the other software but what does this mean for me nd at what values should they be for lets say a 12’ quad.
