### ISSUE TITLE
Incorrect Vtx power settings

### ISSUE THREAD

**Issue by dovcharov** [iNavFlight/inav#3938]
Good day, support.

I have FuriousFPV Stealth LongRange VTX, which has 4 power modes: PIT mode, 25mw, 200mw, 700 mw (600 mw setting in OSD). It is managable via IRC Tramp protocol. I'm on Inav 2.0 firmware, target MatekF722

When I set power via new feature (set larger output power on first arm, i get incorrect settings. Configurator allows to select values from 1 to 5, and in CLI i can select values **1** to 4. 

When I set 1 or as settings in CLI, I get 25 mw on arm. When I set 3 - I get 200 mW. When I set 2 or 4 - i get last valid setting selected on VTX (since FuriousFPV Stealth does not have 100 mw or 400 mw settings).
And, since there's no 5 option anymore, I get VTX settings error when I select 5 via configuration tab in Inav configurator. I also cannot set 5 via command line. 
Worst thing is when I set 600 mW via OSD, I get Unable to Arm error - invalid VTX settings. I have to use a workaround: set 600 mW via OSD, save, and then set 400 mW. This way, iNav thinks the setting is valid (4) but VTX sets last good setting (600 mW)

Please fix this back. Return setting 5 in CLI please.

**Comment by rb1205** [comment]
I have a IRC TRAMP and I second this: the 600 mW setting, which sets vtx_power to 5, causes the FC to prevent arming due to invalid setting.

**Comment by paultbg** [comment]
The same (or very similar) problem on Matek 411 wing w/ inav 2.0 paired with Atlatl HV 2 operated via Smartaudio. The power levels displayed on the OSD do not match the manual. Then on the largest available power (600mw) I can't arm anymore. The biggest power where I can arm is 400mw.

**Comment by teckel12** [comment]
See #3564 found via a search for "VTx power"

**Comment by DzikuVx** [comment]
fixed in #4008
