### ISSUE TITLE
pos_hold_deadband influence the behavior of cruise mode

### ISSUE THREAD

**Issue by kronosol** [iNavFlight/inav#394]
I´ve set pos_hold_deadband to 100cm.
I needed almost 25% of stick deflection to produce a reaction of the FC.
Maybe it´s because of the way cruise mode influence the PID controller?
At the moment i have no time, but i will try to upload a blackbox log till the end of the week.

**Comment by digitalentity** [comment]
pos_hold_deadband is not in cm, it's in R/C command units and it's applied
to your sticks _after_ the expo. You can set it as low as zero to have
instant response.

**Comment by WaspFPV** [comment]
shouldn't deadbands be applied before the expo? I thought they existed to avoid radio jitter?

**Comment by DzikuVx** [comment]
According to the code, it is applied before expo

```
stickDeflection = constrain(rawData - masterConfig.rxConfig.midrc, -500, 500);
stickDeflection = applyDeadband(stickDeflection, deadband);
return rcLookup(stickDeflection, rate);
```

**Comment by digitalentity** [comment]
@DzikuVx @kronosol @andre92
R/C deadbands (deadband, yaw_deadband) are applied before expo.
NAV deadbands (alt_hold_deadband, pos_hold_deadband) are applied after expo in navigation code.

**Comment by kronosol** [comment]
@digitalentity okay, but the wiki say´s it´s the deadband in cm.
[https://github.com/iNavFlight/inav/wiki/6.-iNav-CLI-variables](https://github.com/iNavFlight/inav/wiki/6.-iNav-CLI-variables)

> pos_hold_deadband Input in [cm]   10  250
> alt_hold_deadband   Defines the deadband of throttle during alt_hold [cm]   10  250

Edit: Link didn´t work

**Comment by digitalentity** [comment]
@kronosol fixed, thanks.
