### ISSUE TITLE
Please, Repair BlackBox Fonctionnality on several FC

### ISSUE THREAD

**Issue by CcLaFleche** [iNavFlight/inav#3940]
It's important for fine setting in acro mode and GPS/MAG... It never work on matek f722 !

Thanks.

**Comment by rb1205** [comment]
I fly a matek f722 and it has a working logging. It's very picky on the SD cards you use tho, it didn't work with the SD i was using with the SP3Evo I had before, and out of 3 other SD cards I had around it worked with only one (the most expensive ofc), a sandisk ultra 16gb A1, like [this](https://ae01.alicdn.com/kf/HTB1TKG2foFWMKJjSZFvq6yenFXa5/SanDisk-Ultra-Memory-Cards-16GB-98MB-S-micro-SD-Card-microSDHC-microSD-UHS-I-tf-card.jpg_640x640.jpg) one

**Comment by DzikuVx** [comment]
I use F722-STD on two of my quads and in both cases logging on SD work. And yes, Sandisk Ultra 16GB is confirmed to work

**Comment by CcLaFleche** [comment]
I will try your card...
What is the probleme for the NXT F7 ?

**Comment by sno1957** [comment]
NXT F7 will not save. brings up save window and then gets stuck on the progression bar 0bytes moved.  file was created. i have the 2.1.0 hex loaded that readdresses the SPI for the OSD fix.
