### ISSUE TITLE
ESC Signal Issue on  OMNIBUSF4 V6 (FIREWORKSV2 target)

### ISSUE THREAD

**Issue by Hanni1312** [iNavFlight/inav#3944]
## Current Behavior
Hi Guys,

I guess i found a bug on the OMNIBUSF4 V6 that uses the FIREWORKSV2 Target?

I am fiddling around with this for some hours now. I use a kiss esc in my nano goblin and have recently added the OMNIBUS board to use INAV with it.

But what ever I try the ESC doesn't get a signal as long as I use the flying wing mixer. Today I found out that after switching it to Multirotor Mode it works. Esc initializes and gets signal, no problem! Tested with PWM Oneshot 125 and 42 aswell as the D-Shot up to 1200.

I tried the two boards that i have (both are Omnibus F4's one is the Nano and the other one a normal sized) . If i use a kiss fc or a servo tester with that same esc it works. So esc is fine. 

I even build new FireworksV2.hex with the development branch and this also doesnt work with all the plane mixers.

I am new to INAV but i asked i friend that uses it for a long time and he also could not get it to work. 

## Steps to Reproduce
Pretty much everything i tested is decribed above!

## Expected behavior

Motor running in Airplane mixer

## Suggested solution(s)

See if there is a bug

## Additional context

https://pastebin.com/TSrbNax4

---
- FC Board name and vendor:

My Airbot 
Omnibus F4 V6
Omnibus F4 Nano V6

- INAV version string:

# INAV/FIREWORKSV2 2.1.0 Oct 21 2018 / 21:10:19 (db738810a)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

# INAV/FIREWORKSV2 2.0.0 Aug 19 2018 / 21:25:18 (dbdd1656a)

**Comment by digitalentity** [comment]
Fix ready, closing
