### ISSUE TITLE
Omnibus F4 V6 (FIREWORKSV2) ESC4 does not start

### ISSUE THREAD

**Issue by dl1bg** [iNavFlight/inav#3958]
## Current Behavior
After running the F4 V6 for some days with Betaflight 3.5.1, I switched over to inav 2.0.0.
But, motor 4 does not work properly with inav. In the “Motors” tab, I can start the motors as usual, but motor 4 starts not before 1470. From this level in, it seems to react very agressively.

Configuration:
    Omnibus F4 V6 (Unmannedtech, some weeks old)
    Racerstar REV35 BLHeli rev16.5
    inav 2.0.0, inav configurator 2.0.0
    "5" GPS" configuration

What I have tried:
    memory erase during update, default in CLI
    switch back to Betaflight: motor 4 works
    Multishot, Oneshod, Detault: all the same
    tried version 2.0.0 and modified version from
    https://www.dronetrest.com/t/i2c-magnetometer-not-working-on-omnibus-f4-v6/7005/9
    -> the same
    disabled all serial ports, soft serial etc: the same

## Steps to Reproduce
n. a.

## Expected behavior
n. a.

## Suggested solution(s)
n. a.

## Additional context
I also switched back to Betaflight, success.
Did work with inav 1.9 and Omnibus F4 V3, same ESC.

- FC Board name and vendor: Omnibus F4 V6 (Airbot)
- INAV version string: INAV/FIREWORKSV2 2.0.0 Sep 21 2018 / 00:42:55 (174540a)

**Comment by digitalentity** [comment]
Fix ready, closing
