### ISSUE TITLE
Relative Mission Waypoints

### ISSUE THREAD

**Issue by nik012003** [iNavFlight/inav#3968]
## Current Behavior
Right now we can only create points with fixed GPS coordinates.
## Desired Behavior
I'd like iNav to have a "Relative Waypoint" Option: we define all the Waypoints in relation to a 0 position(home point).
## Suggested Solution
We could add a flag on the Waypoint which tells us if it is Relative or Static, then we would need to calculate its position based on the home point. 
## Who does this impact? Who is this for?
It is for people who want to reuse their mission in different spots.

**Comment by rickgode** [comment]
This is a FANTASTIC idea.  It's how the Cyclops Tornado handles their waypoints.  Most of the flying fields I fly at have North/South runways so I'm usually facing the same direction.  Relative waypoints would be able to transfer from field to field without having to re-input them.

Ricky

**Comment by hali9** [comment]
> We could add a flag on the Waypoint which tells us if it is Relative or Static

We do not need add flag. 
Only add a new action for example 2. (now is 1 for waypoint an 4 for rth). 
Inav always checks the correctness of the action.

> we would need to calculate its position based on the home point.

It may be better to calculate the next point based on the previous one.
And the first to calculate based on the current position.

It can be very easy to do.
We can store distance in lat, and angle course in lot. We do not touch other parameters.
And when inav load mission from non-volatile if is good gps fix we can recalculate mission.
If is not good gps fix, we cannot calculate mission and mark it as invalid (as failed load mission).

After successful load (and recalculating) misson it can be save as normal mission.

Example:
```
wp 0 2 100 90 1000 0 0 #fly 100m course 90 degrees
wp 1 2 200 270 1000 0 0 #and then fly 200m course 270 degrees
wp 2 4 0 0 1000 0 165 #normal RTH
```
We can also prevent distance to nav_wp_safe_distance for security.

**Comment by stronnag** [comment]
As iNav follows the MSP waypoint specification https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages (in part at least), it would be less confusing to define a new relative WP enumeration .
