### ISSUE TITLE
ASGARD32F4 MAG

### ISSUE THREAD

**Issue by cpusmith** [iNavFlight/inav#3969]
For the ASGARD32F4 if the #define USE_MAG and the rest of the MAG entries are commented out in the target.h file does that mean that magnetometers can't work with the board?

**Comment by digitalentity** [comment]
ASGARD32F4 doesn't have I2C broken out - thus it's impossible to connect an external compass

**Comment by cpusmith** [comment]
Thanks.  Do you mean that the code doesn't have it broken out or the physical hardware doesn't?

If it's the code how can I fix it?

**Comment by teckel12** [comment]
@cpusmith The FC doesn't have i2c pins, so it's a physical limitation of the board.

**Comment by KnuckleUpFPV** [comment]
You should still be able to use uart 3. I havent found a board without i2c broken out that doesnt work on uart3.

**Comment by KnuckleUpFPV** [comment]
Yeah just looked it up. I2c is available on uart3 for your board.

**Comment by KnuckleUpFPV** [comment]
https://store.myairbot.com//media/iverve/uploadpdf/1521040968_80095-Asgard32-F4.pdf

**Comment by shellixyz** [comment]
UART3 is not shared with I²C on this board. If you can find where the SDA/SCL pads are connected to the MCU on this board we can enable I²C support.

**Comment by KnuckleUpFPV** [comment]
I just looked it up. It shows iic which is i2c on uart3

**Comment by KnuckleUpFPV** [comment]
Check the link provided. It shows iic on uart3

**Comment by digitalentity** [comment]
On ASGARD32F4 UART3 is on pins PC10/PC11, there is no I2C bus available on those pins on STM32F405 processor:

![image](https://user-images.githubusercontent.com/11059099/48369764-bc752e80-e6b7-11e8-955c-b584ffee74d2.png)

Source of truth for hardware availability is CPU datasheet, board manufacturers may be wrong.
There is no point in flogging a dead horse here, there is no I2C available on this board.

**Comment by KnuckleUpFPV** [comment]
I cant post the image from my phone but it clearly says it on the provided link of the manual.

**Comment by KnuckleUpFPV** [comment]
SBUS UART1 Hardware inverter
DSM2 UART1 Jumper over the inverter
Smart Audio VTX UART2
Smartport ANY Inverters needed
ESC Telemetry UART4 Connected
IIC UART3
SPARE UART UART5 UART6

**Comment by KnuckleUpFPV** [comment]
According to the manufacturer's website the stm32f405 rgt6 which is the chip on the asgard has i2c connected to uart3. This is the datasheet specific to the rgt6. All 180 pages or so for this specific chip.

**Comment by KnuckleUpFPV** [comment]
http://pdf1.alldatasheet.com/datasheet-pdf/view/510007/STMICROELECTRONICS/STM32F405RGT6.html


please see page 59

**Comment by digitalentity** [comment]
Once again. 

STM32F405RGT6 datasheet (https://www.st.com/resource/en/datasheet/dm00037051.pdf).

page 52:
![image](https://user-images.githubusercontent.com/11059099/48374404-103a4480-e6c5-11e8-86fe-1efc758c3847.png)
UART3 shared with I2C is on pins PB10 & PB11

page 53:
![image](https://user-images.githubusercontent.com/11059099/48374449-3829a800-e6c5-11e8-9ddc-134d846c5556.png)
UART3 is on pins PD8 & PD9. Not shared with I2C

Page 56:
![image](https://user-images.githubusercontent.com/11059099/48374502-5ee7de80-e6c5-11e8-8cb6-986203277ea8.png)
UART3 is on pins PC10 & PC11. Again, not shared with I2C. This is what we have on ASGARDF4 board.

**Comment by KnuckleUpFPV** [comment]
From the link you just posted page 63 says otherwise. Its the same chip used on the matek and dys boards. Dys doesnt have i2c broken out either. Yet its still connected to uart3

**Comment by digitalentity** [comment]
@KnuckleUpFPV on ASGARDF4 UART3 is wired to pins PC10 & PC11. Your reference to page 63 is irrelevant. Please stop bragging, you're not going to get I2C working on that board - there is NO hardware possibility unless you solder directly to CPU pins.

**Comment by KnuckleUpFPV** [comment]
Its not bragging bud. Its the truth. Its the same chip. It works.

**Comment by digitalentity** [comment]
@KnuckleUpFPV if you genuinely belive that it works - feel free to create your own firmware for ASGARDF4.

**Comment by KnuckleUpFPV** [comment]
I dont need it. Its the guy that opened this. Just making him aware. If he wants to compile his own version then he is set.

**Comment by datamann** [comment]
If you are using target ASGARD32F4 then I2C are mapped to:
// I2C
#define USE_I2C
#define USE_I2C_DEVICE_2
#define I2C2_SCL                PB10
#define I2C2_SDA                PB11

And UART3:
#define USE_UART3
#define UART3_RX_PIN            PC11
#define UART3_TX_PIN            PC10
ref.
https://github.com/iNavFlight/inav/blob/master/src/main/target/ASGARD32F4/target.h

But if there are no pads to connect to then it won't work... unless it's possible to use SWC and SWD pads...

**Comment by digitalentity** [comment]
@datamann exactly my point. PB10 and PB11 are not broken out on this board and PC10 & PC11 don't have I2C mapped to them. The bullet proof fact that some people fail to understand.

**Comment by digitalentity** [comment]
@KnuckleUpFPV please stop misleading people. There is no possibility to use I2C on this board unless you solder directly to CPU pins. I recommend you to refrain from further comments on this thread.

**Comment by KnuckleUpFPV** [comment]
Im not misleading anyone. Its the same chip as the matek and dys. The dys isnt broken out, but i2c works on uart 3. Its no different than using a board with them broken out. If you have something on the  i2c pads uart3 becomes unusable. I get it you have to stick up for each other. But it works. Its the same chip. I can show you the same chip on the dys f4 with gps on uart3. The datasheet posted says i2c is available on uart3. I was told the exact same thing about the dys f4. There are no scl or sda pads broken out so no i2c. Then i found an rcgroup post that stated i2c is almost always on uart3. Low and behold its connected and works. Just like you can use the scl and sda pads on the matek as uart3 and vice versa. This chip supports i2c on uart3.

**Comment by shellixyz** [comment]
> This chip supports i2c on uart3.

Yes it does but only if the board is using PB10/PB11 for UART3 but this board is not, it is using PC10/PC11 for UART3 as stated by @digitalentity

**Comment by KnuckleUpFPV** [comment]
The uart is connected to pb10/11, pc10/11. You can use i2c because the uart is on all 4 pin assignments.

**Comment by digitalentity** [comment]
You don't seem to get the simple fact that there is more than one option to
connect UART3 to the CPU, but not all of those options allow UART3/I2C
sharing.

On OMNIBUS and variants it's possible to share, on ASGARDF4 it's not
possible to share. All complaints go to CPU manufacturer.

Am Mo., 12. Nov. 2018, 23:07 hat KnuckleUpFPV <notifications@github.com>
geschrieben:
