### ISSUE TITLE
Support for ArkBird Airspeed sensor

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#3980]
## Suggested Solution
Reverse-engineer protocol and add support to INAV for ArkBird 2.0 Airspeed sensor.

## Who does this impact? Who is this for?
Airplane users.

## Additional context
Sensor is reasonably cheap to be widely affordable for hobby pilots
Buy at https://www.aliexpress.com/item/-/32862335603.html

**Comment by david-ng-hk** [comment]
plus one for this
