### ISSUE TITLE
iNav 2.0 VTX settings don't save

### ISSUE THREAD

**Issue by craig34a** [iNavFlight/inav#3983]
Boxcam VTX has no half duplex / tramp features. 
OSD shows "Invalid settings vtx_power"
Craft is not arming
Changing settings via CLI  does not save. 

Dump shows: 

set vtx_halfduplex = ON
set vtx_band = 3
set vtx_channel = 1
set vtx_power = 5
set vtx_low_power_disarm = UNTIL_FIRST_ARM
set vtx_freq = 5705
set vtx_pit_mode_freq = 0

Trying to change these vtx settings will not save. 
set vtx_low_power_disarm =OFF 
for example does not result in any change. 

These settings prevent arming of craft. 

What to do? 

Flight controller F-35 lightning
VTX Boscam TX 832 5.8GHz 600 mW

**Comment by teckel12** [comment]
I believe the solution is to `set vtx_power = 4` or compile the development build, as it's been fixed in the next release.

**Comment by gregm412** [comment]
@teckel12. I have the same problem with the f35 and the furious stealth vtx. Can you compile the development build for the f35 or point me in the right direction to do so. Thank you.

**Comment by teckel12** [comment]
@gregm412 Setting `vtx_power` to `4` would at least work and verify the development HEX would fix the problem.

**Comment by teckel12** [comment]
@gregm412 Also, it's always nice to give the EXACT target name when you want someone to compile something for you.  There's so many FC and variations that many times I build a HEX only to find out it's not what you want.  Always specify the exact target.  In this case, I can only assume you mean the `FF_F35_LIGHTNING` target?

[inav_2.1.0_FF_F35_LIGHTNING.hex.zip](https://github.com/iNavFlight/inav/files/2550752/inav_2.1.0_FF_F35_LIGHTNING.hex.zip)

**Comment by DzikuVx** [comment]
fixed in #4008
