### ISSUE TITLE
servo for camera/servo pour caméra

### ISSUE THREAD

**Issue by diiity** [iNavFlight/inav#3991]
Hello,

I have a MATEK F405 SDT card with INAV 2.0.

I would like to rotate the camera in the up and down direction with a potentiometer.

I soldered on the S6 pin but nothing happens, I think it is necessary to activate a uart or sofserial but in what configuration?

cordially

Diiity
![capture](https://user-images.githubusercontent.com/43235737/48078460-c8f61480-e1e9-11e8-98bd-d5d963a212fc.JPG)

Bonjour,

Je possède une carte MATEK F405 SDT  avec INAV 2.0.

Je voudrais faire pivoter la caméra dans le sens haut et bas avec un potentiomètre.

J'ai soudé sur le pin S6 mais rien ne se passe, je pense qu'il faut activer un uart ou un sofserial mais dans quelle configuration?

Cordialement

Diiity

**Comment by wx4cb** [comment]
no you need to setup in the mixer. Here's how i have my pan servo setup in my mini talon. It's on channel 7, the other channel is the one for my flashing lights. don't remember exactly how it shows up in the mixer tab, but if you poaste these in, the cli and save then go back to the mixer tab, you'll see the two at the bottom say something like "RC Channel 6" "RC Channel 7"

Then on the taranis i just setup another input etc for the slider

# servo mix
smix 0 2 0 -100 0
smix 1 3 0 -100 0
smix 2 4 1 100 0
smix 3 5 1 -100 0
smix 4 4 2 100 0
smix 5 5 2 100 0
smix 6 6 10 100 0
smix 7 7 11 100 0
 
# servo
servo 2 1000 2000 1476 -100
servo 3 1000 2000 1476 -100
servo 4 1000 2000 1476 100
servo 5 1000 2000 1522 100
servo 6 1000 2000 1422 -100

**Comment by wx4cb** [comment]
Also, i believe that if you have soft serial set, then S6 is used for that so you might want to find a different servo channel. If you don't need soft serial at all then i would disable it

**Comment by diiity** [comment]
Merci d'avoir répondu.

Thank you for answering. Is it necessary to configure because I see that servo 0 has taken the place of motor1
Est ce comme cela qu'il faut configurer car je vois que servo 0 a pris la place de motor1
![capture](https://user-images.githubusercontent.com/43235737/48081683-e37fbc00-e1f0-11e8-96b8-367a7f53fb95.JPG)

**Comment by wx4cb** [comment]
you are using the quad mixer which im not sure about, i'd have to defer that to someone else, what you could try is pasting in what my servo mix is and see what happens. it's not going to hurt as you can always just reload the mixer

**Comment by diiity** [comment]
as the servo is noted s1 in the servo tab, I connected it to S1 of the F405 but it still does not move. The mixer motor 1, 2 etc ... used for what?

**Comment by wx4cb** [comment]
what aircraft are you running? a quad ? a fixed wing?

**Comment by diiity** [comment]
Sorry, I forgot to specify it, it's a quadri.

I just tried by removing all the mixer motor, in this case there is more engine.

**Comment by diiity** [comment]
Can I send you the doc of the F405 SDT?

**Comment by stronnag** [comment]
For multirotors, the firmware defines a single servo, on S1 with `inav_x.y.z_MATEKF405.hex` and S6 with `inav_x.y.z_MATEKF405_SERVOS6.hex`.

**Comment by diiity** [comment]
Ah, I do not know what firmware is in my F405 SDT.

But if I put on S1 or S6, I have nothing

**Comment by diiity** [comment]
Here is my config horus X10:
![capture](https://user-images.githubusercontent.com/43235737/48084967-5856f400-e1f9-11e8-8415-b77abc2de2dd.JPG)

![capture0](https://user-images.githubusercontent.com/43235737/48084981-60169880-e1f9-11e8-96c6-fe14353f4113.JPG)

**Comment by wx4cb** [comment]
if you go into the CLI and type version (failing that, do a "diff" and look
at the first line) that should tell you what is burned on the flash

**Comment by diiity** [comment]
Here in doing "version"
INAV/MATEKF405OSD 2.0.0 Aug 20 2018 / 19:20:20 (dbdd1656a)

**Comment by stronnag** [comment]
Wrong firmware then ....

**Comment by diiity** [comment]
What should be the good version?
And is it possible to change it?

**Comment by stronnag** [comment]
That you were told a few posts above https://github.com/iNavFlight/inav/issues/3991#issuecomment-436350980

Just use the servo6 version (with the servo on S6). You need to reflash the board.

If you have a STD board, do NOT use the obsolete OSD firmware.

**Comment by diiity** [comment]
Ok thanks for your help.

I change the firmware and I want to know that I can

**Comment by diiity** [comment]
> On vous a dit quelques articles au-dessus de [# 3991 (commentaire)](https://github.com/iNavFlight/inav/issues/3991#issuecomment-436350980)
> 
> Utilisez simplement la version servo6 (avec le servo sur S6). Vous devez reflasher le tableau.
> 
> Si vous avez une carte STD, n'utilisez PAS le micrologiciel OSD obsolète.

I'm sorry but I do google translation that's why I did not understand the first time
