### ISSUE TITLE
GPS autoconfig is not respected on 2.0.1

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#3992]
## Current Behavior
GPS autoconfig is applied to UBLOX/MTK modules regardless of `gps_auto_config` setting.

## Suggested solution(s)
Check for `gps_auto_config` setting when applying configuration.

## Additional context
- INAV version string: 2.0.1

**Comment by stronnag** [comment]
Seems like a win to me :)

**Comment by digitalentity** [comment]
And it's fixed. Probably shortest-living bug ever.
