### ISSUE TITLE
NEW VTOL model type

### ISSUE THREAD

**Issue by Jahnkeanater** [iNavFlight/inav#3998]
Tom Stanton made a VTOL airplane that transitions to forward flite.
https://www.youtube.com/watch?v=gPEeCjVrTBw

When in a hover the motors control roll and a single servo controls only pitch.
When in forward flite the motors control yaw slightly and the pitch servo is locked at a certain angle.

This requires 2 different mixers and a slow transition between flight modes.

**Comment by Riffer** [comment]
Isn't this something we could do in the transmitter?
