### ISSUE TITLE
target.h file is changed and is harder to change it to fit F1 target.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#400]
Hi, is there any spesific reason for going for #undef instead of having #define in target.h and then simple comment out the lines you dont need?

See there is an mix for #define and #undef now.

Old way: https://github.com/iNavFlight/inav/blob/334a16ec745255904c0e787478f9bc98ab498b34/src/main/target/NAZE/target.h

New way: https://github.com/iNavFlight/inav/blob/master/src/main/target/NAZE/target.h

Makes it "harder" to compile example FrSky version: http://www.rcgroups.com/forums/showthread.php?t=2495732&page=320#post34463103

This time I had to look at the old target.h file to find the name of the GPS drivers I did not need, and then add it as undef..

If there is a good reason just close this :+1:

**Comment by martinbudden** [comment]
#defines that are (generally) common to all targets are defined in `target/common.h`. Overall this keeps the `target.h` files more compact and easier to maintain.
