### ISSUE TITLE
Matek F405 controller

### ISSUE THREAD

**Issue by Charles57** [iNavFlight/inav#4004]
Hello my name is Charles and recently purchased this at a local hobby store. When I  calibrate using INAV configurator the quad is straight and flat like normal but it you wait about 20 seconds you will see the quad yaw right about 5 degrees still staying flat. just like on a clock-  after 20 minutes the drone has turned around completely. So say if the quad is facing the 3 oclock position I pick up the quad and move it around it will go in the right direction but the problem is its pointing in the wrong direction. 

1 I have the Matek F405 STD controller
2 Holybro Micro M8N gps module
3 S500 quad on amazon
4 Cheap 1045 props
5 hobbypower 2212 920K brushless motors
6 Simon K 30 amp speed controls
7 Power module soldered on a distribution board
8 some kind of ubec the hobby store soldered on
9 It has OSD with a Quanum DIY FPV Goggle V2 Pro
10 Quanum RC540R 5.8GHz 40CH Race Band FPV Diversity Receiver
11 cheap eachine camera

Ive also tried plugging in the gps first wait to get satelites then reconnect and recalibrate in the configurator. The quad will be flat but angled clockwise about 30 degrees (not straight) if you move it around and stop the quad will keep rotating around until you set it down then it goes back to that 30 degree position.
 A couple things I did was separate the receive  from controller, wrapped foil around wires and foil between power module and controller to see if there was magnetic interference - no change. I have on figured inside the house and outside - no change. Here are some pics. Im leaning toward bad accelerometer or bad soldering Can you help thanks

**Comment by teckel12** [comment]
@Charles57 Sounds like a classic case of the compass orientation being incorrect. In the configurator you set the compass orientation and flip. If that's wrong, it will do exactly as you describe. Also, once you get it set correctly, be sure to calibrate the compass away from any electromagnetic fields (computers, cars, etc).

**Comment by Charles57** [comment]
Thanks for the info I forgot I had this posted

**Comment by teckel12** [comment]
@Charles57 close if you wish.
