### ISSUE TITLE
Motors Spin up to 1500 at Zero throttle

### ISSUE THREAD

**Issue by Hopalonger** [iNavFlight/inav#4005]
I am working on my quad. I am using an SP racing F3 Flight Controller running the latest version on Inav. I am using the 10" general Purpose Preset and have not altered any settings except for setting up my receiver since install. I installed it today. When I arm my quad all of the motors fire right up at 1075ms. When I attempt to take off with the props on if I move the throttle below the minimum value of  1075 the drone starts to wobble and spin on the ground without taking off even at full throttle. I plugged it in and looked at the motors tab when I did this same process and once I go over the minimum throttle threshold. Motors 1 and 4 are spinning at 1500ms while 2 and 3 are at around 1100ms. I know the PID look is running because when I tilt the drone it does have the motors respond by raising or lowering the throttle. Any help on making it so motors 1 and 4 would not start at 1500ms would be great.

**Comment by teckel12** [comment]
@Hopalonger Have you calibrated the ESCs?

**Comment by wx4cb** [comment]
that's normal if it's on the bench. same thing applies with betaflight.

**Comment by DzikuVx** [comment]
on a bench without propellers control loop is broken and it is normal behavior of Iterm winding up since UAV is unable to correct position (has no propellers after all)
