### ISSUE TITLE
Target Request Airbot Asgard32  F7

### ISSUE THREAD

**Issue by davidabevan** [iNavFlight/inav#4016]

**Comment by digitalentity** [comment]
Already in progress

Am Do., 15. Nov. 2018, 23:59 hat Dave Bevan <notifications@github.com>
geschrieben:

**Comment by davidabevan** [comment]
Excellent. Many thanks.

**Comment by digitalentity** [comment]
Done, closing

**Comment by davidabevan** [comment]
Brilliant will load it in tommorow the new model has been tested on
Betaflight and flys well. I will report any issues if thats ok.
Many thanks indeed.
