### ISSUE TITLE
Access BlackBox SDCard from computer (Matek F722-STD)

### ISSUE THREAD

**Issue by Frontier314** [iNavFlight/inav#4019]
## Current Behavior
Accessing logs on the installed SD card on a flight controller like Matek F722-STD, requires removing the card from the slot. This is inconvinient for builds where the flight controller is inside a shell (i.e like this hexacopter: https://www.thingiverse.com/make:554274).

## Desired Behavior
To access the contents of the SD Card from the computer, like Betaflight 3.5 does.

## Suggested Solution
Cherry-pick (if possible) the SD card code from Betaflight 3.5.

## Who does this impact? Who is this for?
All users.

Thank you.

**Comment by wx4cb** [comment]
Same thing applies for the Matek 405 Wing controller as it's on the bottom of the board.

**Comment by ghost** [comment]
It is actually a problem with all FCs, regardless of where the reader is mounted.
It has been reported numerous times in the past but obviously not considered important by the devs.
Apart from the access problem, the reader/chip is not going to last very long if it is removed and inserted after every flying session.
Currently the only solution is to switch to Betaflight or Ardupilot.

**Comment by shellixyz** [comment]
Duplicate of #1336

**Comment by shellixyz** [comment]
Closing since there is another issue for this feature request
