### ISSUE TITLE
INav PID Settings AltHold oscillating Problem

### ISSUE THREAD

**Issue by chief2811** [iNavFlight/inav#4020]
Hi everyone,

I recently finished my cooter build with inav. But I got several problems with navigation modes e.g althold and poshold. 

When I switch to althold the quad is jumping up and down. I mean it stays at a certain altitude but it jumps around this point +-10cm very fast with power. It oscillates around this certain altitude. 

I found out that it hast to do with BARO Sensor on my Omnibus F4 Pro v3 because when I disable BARO and just use althold with gps it doesn’t jump up and down. But in this case althold is not working well. 

Same for poshold.  I did some troubleshooting but I didnt come along. I also mixed up this problem with Toilette bowling. But unless I do not have a working althold I couldn’t have toilette bowling. at least I found out that my magnetometer was misaligned. But this was also Kit the cause for my problem. So I went on on some PID things. But here is where I’m lost. I don’t know what to do in here! My F4 Pro came with Betaflight 3.4 and the default PIDs worked for this copter perfectly. So I wrote them down and flashed inav to the F4 and just put the PIDs in there which I wrote down earlier. So in angle and horizon the copter is fine for me. But when I switch to althold I got this particular problem. 

What’s the cause for this problem? 

Anybody an idea? 

Thanks in advance

**Comment by wx4cb** [comment]
If ypu have an onboard baro, you have to cover it with a bit of open cell
foam. Its the pressure differences from the propwash

**Comment by chief2811** [comment]
Dude many thanks for that advice. It helped me a lot. 

Although it was windy today I tried a couple of flights with covered BARO. 

Quad now try’s to hold its altitude. Basically it works. But I have to have at least 1500 stickinput throttle. When I have less than 1500 e.g. 1490 or so, the quad is slowly descending. When I have at least 1500 the quad stays at this altitude. PosHold is working good as well. I mean it was windy and it was like 45deg on Roll to fight the wind. But all in all it stays where it should; as long as the throttle stick is more than 1500. 

Anybody an idea how to set that up correctly? 

So far I figured out that hover throttle is almost 1500 I could not determine so exactly because up and down going quad. But I was always around 1500 and middle position of stick. So I put 1500 as hover throttle in inav.

**Comment by wx4cb** [comment]
sounds like you're doing good now then. what I would do is try it on a calm day and see how you go. whatever your throttle position is to hold it in a regular hover, set that to the hover throttle. this is obviously going to change as wx conditions change but it's a great starting point.

you could also try tuning the pids for it a little. i don't have inav on a quad so i cannot help with that side.
