### ISSUE TITLE
inav barometer bmp 280 not working on any fc f7 external baro targets

### ISSUE THREAD

**Issue by Dhananjaya96** [iNavFlight/inav#4027]
on upgrading inav 2.0 to 2.1 barometer indicator turns to red and its already connected 

## Steps to Reproduce

1.after flashing inav 2.0 on anyfc f7 under configuration tab setting baro as bmp 280 .
  baro indicator turns to blue color.
2.everything is working perfectly mag baro sonar gps on inav 2.0
3.then upgrading to inav 2.1 to test breaking mode .after flashing firmware on fc all the indicator turns blue except barometer . then check it on configuration tab .and once again set it to bmp280 and save and reboot.
4.still nothing happen .baro is still red.

## Expected behavior
bmp280 is a great barometer . I tested it on anyfc f7 from 1.7 to 2.0 every version on inav its working perfectly .

## Suggested solution(s)
please add bmp 280 targets .

cli data of inav 2.1 resources 

https://pastebin.com/Pz0t0Z1a

dump data 

https://pastebin.com/KnpSq5GV
---

# version
# GCC-7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]- FC Board name and 

vendor: banggood

- INAV version string:
# INAV/ANYFCF7 2.1.0 Sep 22 2018 / 21:53:31 (507b832)

**Comment by shellixyz** [comment]
You need to flash the `ANYFCF7_EXTERNAL_BARO` target if you want to use an external I²C barometer
