### ISSUE TITLE
Fixed Wing Output Mapping in Inav 2.0 ?

### ISSUE THREAD

**Issue by XenXwing** [iNavFlight/inav#4028]
Hi
Newbie here and have question about Mix > Output Mapping on Inav 2.0
My very first Fixed wing set up with F3 Colibri V2, soldered S1, 3, 4. 
 - S1 Motor
 - S2 Empty
 - S3 Servo 3
 - S4 Servo 4

But my result was that only one servo (left) is working..
When I check Mix Tab, mapping seems to be wrong and I do not know what should I do?

Please check my attachment, showing Inav Mix tab.
thanks
![inav](https://user-images.githubusercontent.com/45220140/48816512-cc5ed380-ed85-11e8-8d05-ee6d87b96be3.JPG)

**Comment by shellixyz** [comment]
This target only supports one motor output so the output mapping table is right you need to connect the servos to ouputs 2 and 3.

**Comment by XenXwing** [comment]
Thanks

> This target only supports one motor output so the output mapping table is right you need to connect the servos to ouputs 2 and 3.

**Comment by DzikuVx** [comment]
since there is nothing else to do, I'm closing. Thanks

**Comment by 666satyr666** [comment]
Please tell me how you doing it @XenXwing.
I got a unique case so my FC only remaining 3 servo output, just like what I need for flying wing. But I can't remapping those pin. I need to be just like what you set in here.
I need pin #1 for motor and pin #2 & #3 fro servos.
