### ISSUE TITLE
Record way points while flying.

### ISSUE THREAD

**Issue by simtcrom** [iNavFlight/inav#4033]
## Current Behavior
Way points has to be saved before flying.

## Desired Behavior
While flying when reach a place, flip a switch and the 1st point is saved. Go to next point flip switch reverse and the 2nd point is saved and so on..
Then later replay this mission.

## Suggested Solution
I don't know.

## Who does this impact? Who is this for?
Any one who use INAV for way point mission.

## Additional context
None.

**Comment by breadoven** [comment]
Closed by https://github.com/iNavFlight/inav/pull/6967.
