### ISSUE TITLE
INAV v2.01 fail in RTL set altitude 

### ISSUE THREAD

**Issue by kamelkungen** [iNavFlight/inav#4041]
## Current Behavior

Plane doesn't decrease altitide on its way home in RTL mode. 
This issue come up after upgrading to latest release v.2.01
This feature worked in previous verison and all settings are the same. Diff all was done during upgrade.

## Steps to Reproduce

set nav_rth_alt_mode = FIXED
set nav_rth_altitude = 10000
set nav_fw_loiter_radius = 10000

1.if RTL and alt < 100m // works fine plane climb to 100m
2.if RTH and alt > 100m plane keeps current alt // bug ?? 
3.
4.

## Suggested solution(s)

fix bug and new release

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by wx4cb** [comment]
duplicate of this: https://github.com/iNavFlight/inav/issues/3918 - make sure they're different
