### ISSUE TITLE
OSD flight modes

### ISSUE THREAD

**Issue by RCnator** [iNavFlight/inav#4042]
## Current Behavior

When activating different flight modes there is only a limited number of flight modes displayed by the OSD and the name displayed often remains the same when flipping the flight mode switches.
## Desired Behavior

I would like to have more different names showing up in the OSD for the most common flight modes and flight mode combinations.
## Suggested Solution
Add more flight mode names for the OSD in 2.1

## Who does this impact? Who is this for?
All users

**Comment by fiam** [comment]
Could you clarify which flight modes do you find missing from the OSD? Note that some modes and modifiers need the "System Messages" indicator visible in order to be displayed.

**Comment by teckel12** [comment]
I would agree, the OSD flight modes + system messages seem very complete.

**Comment by ghost** [comment]
GPS modes appear as ACRO, until a lock occurs. 

I would find it better if the selected mode was shown, regardless of the GPS state.
If there in NO lock. Then the function can not be carried out. At least you would know what mode you should be in. 
Then look at the 'System Messages' to find the problem.

**Comment by RCnator** [comment]
Thanks for the replies, though I am not sure I fully understand them linguistically.

I worked with this a month ago but I believe "System Messages" was activated. I am uncertain about gps fix at that specific test moment and I don't remember which specific flight modes I felt were missing but I have 9 switch combinations (or flight modes) but there was only like 3 different flight mode names that got displayed so the feature appeared incomplete in general to me.  I will test again when I get the opportunity (about a month from now) but I doubt it will suddenly display 9 different modes and I thought 2.1 would already be out by then.

**Comment by shellixyz** [comment]
That's all the flight modes iNav displays on the OSD:
![image](https://user-images.githubusercontent.com/4030264/49239239-7bdd1b00-f402-11e8-8f5a-7ce62dfb3fa0.png)

**Comment by MrD-RC** [comment]
> That's all the flight modes iNav displays on the OSD:
> ![image](https://user-images.githubusercontent.com/4030264/49239239-7bdd1b00-f402-11e8-8f5a-7ce62dfb3fa0.png)

ACRO is missing from that list. Also, should AIR even be on there, as it's really a flight mode modifier rather than a flight mode in it's own right.
