### ISSUE TITLE
Failsafe auto nav fixedwing crash procedure

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#4066]
I have a question to anyone who knows. Or to the person who wrote the code surrounding this.

When a failsafe occurs with a fixedwing. And the plane proceeds to return to home.
What will happen if the plane crashes along the way, due to unforeseen circumstances.

Will the motor Disarm in auto navigation, at the instant the plane crashes?
Or will the motor continue to keep running, thinking that it is still returning to home? Not knowing that it is on the ground. 
And potentially burn-out the ESC, or even set the plane on fire. 

I can't find the answer to this question. And I can't work out a safe way to test if a function does exist for fixed wing; to prevent this issue happening.  Like auto disarm, that occurs on landing with the iNav multicopters.

**Comment by shellixyz** [comment]
For the moment if the plane crashes during RTH or RTH is engaged after the plane has crashed because it is defined as the FS procedure the plane will try to go home even on the ground. Most ESCs have low RPM protection so even if the prop is blocked it should not set the motor / ESC / plane on fire but you should try to get to the plane to disconnect the battery or get close enough with the remote control to disarm as quickly as possible.

To prevent that flying detection heuristics are needed and it is not a trivial task. It will be implemented in the future. See #2331.

**Comment by ghost** [comment]
Thanks for the lead @shellixyz 
As least I know now, that the issue still remains.

As you pointed out. The only saving grace is ESC's with stall protection. But not all Fixed Wing ESC's have this.

After reading through the other issues related to this. 
It is obvious to see, that the implementation of such a function is more difficult with a Multirotor, than for a fixed wing.
I brought the issue up, with respect to fixed wings. Because fixed wings are more likely to be flown at greater distances. Which the likelihood of a RX failsafe condition occurring, with no chance of getting the signal back; is there. So manually disarming the FC is not an option.

For a fixed wing. I can't see any reason that GPS data could not be used to command the FC, that its on the ground, and no longer in the air.  
Because many of these functions are already reliant on GPS anyway.

***nav_rth_climb_ignore_emerg**
***nav_rth_abort_threshold**

In my thinking. 
Why can't the concept of - **nav_rth_abort_threshold** be extended to take into account whether the plane is in motion or has crashed.
A shock measurement from the accelerometer at the point of impact or touch down. Would surely be greater than anything it would experience during flight. This too could be used injunction with GPS data.
Then the FC would disarm after the GPS condition has been present for a short period of time.

Some may argue that a fixed wing can hold position in a strong head wind. 
But this check function should only be implemented in auto navigation modes.
