### ISSUE TITLE
New landing scenario for fixed wing

### ISSUE THREAD

**Issue by iHardRock** [iNavFlight/inav#4070]
## Current Behavior
Now auto landing is just like a "circular descent to reach the ground with safe speed". It's better than nothing, but not safe because you can't excactly know when and where aircraft will touch the ground. Also you need space bigger than loitering radius, with no trees and other objects. For example at this video aircaft was in few meters from the tree, is was just a luck :)

https://www.youtube.com/watch?v=3KgxShjWvQg

## Desired Behavior
Much better way to land - is do it in opposite side of takeoff, like real planes do.

## Suggested Solution
Landing screnario may be implemented as set of waypoints, where first endpoint is located at safe altitude (may be same with loitering altitude), second one - descent point where slowdown vertical velocity (cli: nav_land_slowdown_minalt / nav_land_slowdown_maxalt) and third one where aircraft must touch the ground and disable motors / disarm. 
All points may be calculated automatically after takeoff. 
One significant moment: aircraft must store takeoff direction and do landing at this direction but in opposite side.
Takeoff direction also may be calculated automatically as vector between arm (home) position and position at few seconds after takeoff.

Proposed settings:
nav_land_glidepath_start_distance - Distance from home where aircraft must start moving straight to home position. If distance bigger than  loitering radius, then aircraft should go to this point and then turn to the home point.

nav_land_glidepath_start_altitude - As above, but  altitude

nav_land_slowdown_minalt - As now
nav_land_slowdown_maxalt -As now

nav_landing_speed - Vertical velocity when touch the ground

With nav_land_slowdown_maxalt & nav_landing_speed you may calculate distance from home for this point.
So between glidepath start and slowdown points aircraft moving straight with calculated dive angle. Afte reaching slowdown point it keep go straight but with nav_landing_speed vertical velocity and softly touch the ground with predictable trajectory.

## Who does this impact? Who is this for?
This feature for all fixed wings. In case of emergency (complete lost of radio control for example) it may save the aircraft and environment with higher probability.

## Additional context
If navigation is not possible (i.e. no GPS), current landing scenario may be applied. Better than nothing :)

**Comment by giacomo892** [comment]
See #1814
