### ISSUE TITLE
Add functionality to mission planner

### ISSUE THREAD

**Issue by Vlad1384** [iNavFlight/inav#4071]
Add to the mission planner: 1. the ability to fly around a point with a given radius and number of circles, with the ability to change the position of the quadcopter (front, side or back). 2. Add the ability to set the quadcopter position when flying from point to point (front, side or back). 3. Add an automatic yaw rotation when flying from one point to another.
Increasing the capabilities of the functional in the mission planner will give the opportunity to use Inav for example for video shooting, which will increase the popularity of both beginners and advanced users.

**Comment by stronnag** [comment]
Please note that:
* The FC aspects of this are already covered in #154 (SETPOI, SETHEAD, JUMP)
* The mission planning aspects are already provided by third-party mission planners (ezgui, mwp at least)
* There is a [separate github repository](https://github.com/iNavFlight/inav-configurator) for configurator feature request.
