### ISSUE TITLE
Omnibus F4 pro v2 (clone) softserial for ESP8266 Wifi module question.

### ISSUE THREAD

**Issue by simtcrom** [iNavFlight/inav#4073]
Hello,

In Omnibus F4 pro v2 (clone), I have 3 UARTs and they are used as below,

UART1-IBUS Rx
UART3-Compass SCL/SDA
UART6 -GPS

I see two pads above MOTO_VCC and as per https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md I assume they are CH5 and CH6 used for Softserial.
Can these pads be used to connect ESP8266 Wifi module by enabling softserial in INAV configurator?
As per documentation, it is a "uni-directional port mapped to UART6-TX pin. When enabled, the UART6 is still available as hardware port but it's then RX-only port" Does that mean, GPS connected to UART6 will have issues?

Thanks.

**Comment by teckel12** [comment]
@simtcrom If your board looks like that, it's not a pro model. With the pro you connect the battery straight to the FC and it has a current sensor. The pic link you posted is a standard model.

The document you listed is very detailed about soft serial. But you first need to identify the board correctly, which it doesn't appear that you are.

**Comment by simtcrom** [comment]
> @simtcrom If your board looks like that, it's not a pro model. With the pro you connect the battery straight to the FC and it has a current sensor. The pic link you posted is a standard model.
> 
> The document you listed is very detailed about soft serial. But you first need to identify the board correctly, which it doesn't appear that you are.

It is a pro board (but clone, not blue color) for sure. It has current sensor built in and I can connect lipo directly to the FC. I could not find INAV wiki for pro board, I thought PRO board also described in the non-pro page bottom. 
Here is the link to my exact FC, [https://robu.in/product/omnibus-f4-v2-pro-flight-controller/](url)

**Comment by shellixyz** [comment]
You can use softserial on CH5 (RX) / CH6 (TX). It is not shared with UART6 on the OMNIBUSF4PRO board. You will probably not be able to use all the baud rates though due to the limitations of the software serial ports.

**Comment by simtcrom** [comment]
> You can use softserial on CH5 (RX) / CH6 (TX). It is not shared with UART6 on the OMNIBUSF4PRO board. You will probably not be able to use all the baud rates though due to the limitations of the software serial ports.

I assume by mentioning "OMNIBUSF4PRO " you referred the target and which is for Omnibus F4 Pro.
I am running "OMNIBUSF4PRO_LEDSTRIPM5" which is for Omnibus F4 Pro clones.
Does that make any difference on soft serial?

**Comment by shellixyz** [comment]
It doesn't make a difference

**Comment by simtcrom** [comment]
I am planning to 

> It doesn't make a difference

My intention of adding wifi module is, for connecting to quad using phone via EZ-GUI for uploading missions, changing settings etc. And also connecting to INAV configurator in windows wireless.
I am planning to follow http://ez-gui.com/manual/multiwii-clearflight-wifi-to-ezi-gui-how-to/
And planning to buy https://robu.in/product/latest-esp-12f-esp8266-wifi-module-ap-station-remote-serial-wireless-iot-board/
Any idea if it will be compatible?

**Comment by teckel12** [comment]
@simtcrom If you have a Pro board, the images and documentation show exactly how to do it, specifically:

https://raw.githubusercontent.com/iNavFlight/inav/master/docs/assets/images/omnibusf4pro_ss.jpg

I've used a Bluetooth adapter to communicate with EZ-GUI. That works. Not sure about doing wifi as I've never tried that.

**Comment by simtcrom** [comment]
While I wait for [ESP-12F ESP8266](https://robu.in/product/latest-esp-12f-esp8266-wifi-module-ap-station-remote-serial-wireless-iot-board/) and [PL2303 Usb To Rs232 Ttl Converter Adapter](https://www.amazon.in/gp/product/B00UZERG94/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1) I was trying to find out the connection diagram to flash [esp-link](https://github.com/jeelabs/esp-link) firmware which is needed for ez-gui to work.
I could not find much details for ESP-12F. Whatever available is either for older modules or using arduino.
Based on my research, I did couple of wiring diagrams, can some one please confirm which one is good.
![connection_ftdi](https://user-images.githubusercontent.com/6823535/49824461-257bbf00-fda8-11e8-91db-ed352878fe19.jpg)
![connection_ftdi-antony cartwright](https://user-images.githubusercontent.com/6823535/49824462-26145580-fda8-11e8-9aca-fb18aa974854.jpg)
![connection_ftdi-esp-link](https://user-images.githubusercontent.com/6823535/49824463-26145580-fda8-11e8-9aef-a5761b303cc0.jpg)
![connection_ftdi-makerstream](https://user-images.githubusercontent.com/6823535/49824464-26145580-fda8-11e8-9b6d-34f4af4a73f7.jpg)
![connection_ftdi-pawel spychalski](https://user-images.githubusercontent.com/6823535/49824465-26acec00-fda8-11e8-913a-61c3ecf276ca.jpg)

**Comment by simtcrom** [comment]
I was able to flash esp-link successfully.
here is a video I did explaining how to flash firmware (esp-link)

[https://youtu.be/CEZ2gTZp8X8](url)

Now softserial is not working. I tested with UART6 and it connect to ez-gui successfully. But not with soft serial.

**Comment by simtcrom** [comment]
I changed the baud rate and its working.
Thank you.

**Comment by simtcrom** [comment]
I changed the baud rate and its working.
Thank you.

**Comment by RichardAnkur** [comment]
Hello simtcrom
I have the same flight controller board and I had also ordered it from robu.in
I have connected my GPS and compass on UART 6 and UART 3 and I am using a flysky fs i6x transmitter and fs iA6B receiver which is connected to sbus/ppm pin. The firmware which I had uploaded is the omnibus f4pro...and not that ledstrip one.
And now I have connected my HC06 Bluetooth module to UART 1.
The problem is that when I plug in the battery and connect the bluetooth with EZ GUI app it works perfectly but as soon as I turn on my transmitter.....the female voice from EZ GUI tells data not received.
Can you suggest me a solution.

**Comment by RichardAnkur** [comment]
My Bluetooth is set at 11260 baud

**Comment by simtcrom** [comment]
> Hello simtcrom
> I have the same flight controller board and I had also ordered it from robu.in
> I have connected my GPS and compass on UART 6 and UART 3 and I am using a flysky fs i6x transmitter and fs iA6B receiver which is connected to sbus/ppm pin. The firmware which I had uploaded is the omnibus f4pro...and not that ledstrip one.
> And now I have connected my HC06 Bluetooth module to UART 1.
> The problem is that when I plug in the battery and connect the bluetooth with EZ GUI app it works perfectly but as soon as I turn on my transmitter.....the female voice from EZ GUI tells data not received.
> Can you suggest me a solution.

I don't know if it matters. In my case,

-  iA6B is wired to UART1 and enabled Serial Rx in ports tab. Also it is configured as IBUS protocol.
- ESP8266 Wifi module is wired to soft serial ports and enabled MSP for soft serial in ports tab.
- compass and gps is wired same way as yours.

Attaching screenshot of ports tab,
![ports](https://user-images.githubusercontent.com/6823535/50720209-9fb11200-10ce-11e9-92a8-7c75ccea2618.jpg)

Btw,
I was able to connect using EZ GUI (android) and Mobile Flight (ios).

**Comment by RichardAnkur** [comment]
I can see in inav configurator that there is USB vcp.....UART 1.....uart2.   ....and UART 6 but there is no softserial 1.

**Comment by RichardAnkur** [comment]
You GPS is working at 38400 but I for mine baud rate is 11560 and added two 4.7 kohm resistance from scl to vcc and vcc to SDA. Kind of working never tested in for waypoint will there be any issue.
My GPS is ubox neo m8n from robu.in

**Comment by RichardAnkur** [comment]
Did you add any resistant to gps like mine?

**Comment by simtcrom** [comment]
> I can see in inav configurator that there is USB vcp.....UART 1.....uart2. ....and UART 6 but there is no softserial 1.

as I mentioned earlier, I use my soft serial pads for wifi module. Thats why I have soft serial (you got enable it in configurator)

**Comment by simtcrom** [comment]
> DA. Kind of working never tested in for waypoint will there be any issue.
> My GPS is ubox neo m8n from robu.in

I have the same GPS, And yes I have added 4.7kohm pull up resistors for SCL and SDA.
You can increase the baud rate, since we both use same module, it should work on higher speed.
I have tested way points and RTH and all worked great.

**Comment by RichardAnkur** [comment]
For soft serial I should use the two pads above moto_vcc connecting RX of fc to tx of Bluetooth and tx of fc to RX of Bluetooth...... Running GPS(UART 6) at 38400 and softserial at 115600.... That's is what you are suggesting.. Right

**Comment by simtcrom** [comment]
> For soft serial I should use the two pads above moto_vcc connecting RX of fc to tx of Bluetooth and tx of fc to RX of Bluetooth...... Running GPS(UART 6) at 38400 and softserial at 115600.... That's is what you are suggesting.. Right

exactly.
But not sure what baud rate you should set for BT module. Try one by one.

**Comment by RichardAnkur** [comment]
And also I should use omnibus f4proledstripm5 firmware...I have omnibus f4 pro v2 black board with current sensor

**Comment by simtcrom** [comment]
> firmware

you can use omnibusf4pro target itself  unless you use led strip.
if led strip needed use the one you mentioned.

**Comment by teckel12** [comment]
@RichardAnkur The LED strip target is for clones that didn't route the LED strip pin correctly. If you have a non-clone, you don't need to use the LED target at all.  I have a few Omnibus F4 Pro FC (non-clones) and I run all with the non-LED strip target and run LEDs on all.

**Comment by simtcrom** [comment]
> @RichardAnkur The LED strip target is for clones that didn't route the LED strip pin correctly. If you have a non-clone, you don't need to use the LED target at all. I have a few Omnibus F4 Pro FC (non-clones) and I run all with the non-LED strip target and run LEDs on all.

His and mine are clones (non blue colour ones) bought from same hobby shop.

**Comment by RichardAnkur** [comment]
@simtcrom are you fully sure that we both have a clone board. You have also bought it from robu.in
I also had a doubt but was not sure

**Comment by simtcrom** [comment]
> @simtcrom are you fully sure that we both have a clone board. You have also bought it from robu.in
> I also had a doubt but was not sure

I am sure mine is a clone 😀
