### ISSUE TITLE
Do not use THR during RTH if THR during activation was low

### ISSUE THREAD

**Issue by ABLomas** [iNavFlight/inav#4077]
Now when #3195 was closed we can move on. Currently RTH won't use THR if it was activated when throttle is low.
Need to add this to failsafe logic, too, as it covers only part of use cases (still you can end in tree if you do landing far away from you, etc).
My suggestion - nav_ignores_motorstop having three values:
![setting_flowchart](https://user-images.githubusercontent.com/8989151/49698933-332c1b80-fbd3-11e8-9f20-986137411308.png)

Settings are completely safe - current behavior does not change (needs to be set in CLI), also you can allways initiate "normal" RTH by moving throttle a little up + switch.

**Comment by romanas** [comment]
Good, im always in with RTH without motor! The best future ever! =)
