### ISSUE TITLE
Show waypoint mission progress on OSD

### ISSUE THREAD

**Issue by TrueMuMa** [iNavFlight/inav#4078]
## Current Behavior
Don't display on OSD current progress of distance to the next point and current point number

## Desired Behavior
Display on OSD current progress of distance to the next point and current point number

## Suggested Solution
Add new values to string "SYSTEM MESSAGE"

## Who does this impact? Who is this for?
For all users who use Waypoint mission

**Comment by breadoven** [comment]
Closed by:

https://github.com/iNavFlight/inav/pull/6215
