### ISSUE TITLE
FF F35  lightning with R9M and R9 mm receiver NO TELEMETRY

### ISSUE THREAD

**Issue by effysh** [iNavFlight/inav#4079]
Hi i am using furiusfpv F35 fc 
 with 1.9.1 firmware with no problem and all telemetry sensors are working and sending values to my horus tx with R9M module and R9 mm receiver
the problems start when i upgrade the F35 fc firmware throw the inav configurator to the latest firmware which is 2.01  and TELEMETRY from F35 stop to work throw S.PORT and only RSSI and RECEIVER BATT works 
my opentx is 2.2.2 
and the only thing i didn't test is the latest firmware of the R9m and its r9 receiver maybe this is the problem...
any help will be great

**Comment by teckel12** [comment]
@effysh There were changes for port inversion between 1.9.1 and 2.0.1.  The R9 MM has both inverted and non-inverted pins.  Then there's the issue of the FC, I assume it has an SBUS port that's inverted.  With the R9 MM, it's best to use a UART that's not inverted on the FC and the non-inverted pins on the R9 MM.

In addition, posting your INAV `dump all` would help further.

**Comment by effysh** [comment]
Thanks teckel12
You were right i just did:
smartport_uart_unidir = ON on cli
Telemetry now works

**Comment by shellixyz** [comment]
Fixed, closing
