### ISSUE TITLE
Feature request: MSP RX override

### ISSUE THREAD

**Issue by shellixyz** [iNavFlight/inav#4084]
Feature request by Chris Haskins. The goal is to be able to override the channels from the configured RX with values received through MSP. This is to guide their software engineer for implementing the feature.

This is what I would do:
- Add a flight mode `MSP OVERRIDE` that when activated overrides the configured RX: `fc/fc_msp_box.c`, `fc/rc_modes.h`
- Add a setting in `rxConfig_t` to chose which channels are overridden like `msp_override_channels`: `fc/settings.yaml`, `rx/rx.h`, `rx/rx.c`
- Override the the channels with the values received from MSP when the `MSP OVERRIDE` flight mode is enabled: `rx/rx.c`

MSP channel values are stored in `rx/msp.c`: `uint16_t mspFrame[]`

**Comment by giacomo892** [comment]
What about adding a setting that will allow MSP_RX to always override any other RX protocol if  is being received by the FC?

**Comment by shellixyz** [comment]
Why not if it has some usage but I think in this case they need to be able to override MSP control (robot) with a standard human operated remote control.

**Comment by pilotnbr1** [comment]
It would be nice if an rc override was available. I was hoping for mavlink but msp would be good too

**Comment by shellixyz** [comment]
Feature merged, closing

**Comment by federicohyo** [comment]
Is this feature still available in inav 2.5.0 ? I don't see a flight mode MSP OVERRIDE ... am I missing something?

**Comment by stronnag** [comment]
Not enabled at build time by default. You need to build firmware with:

```
make TARGET=FOO OPTIONS=USE_MSP_RC_OVERRIDE=1
```

or remove the comment  prefix in `src/main/target/common.h`

**Comment by federicohyo** [comment]
Thank you! I see the flight mode now. Interestingly it is not listed in this page -> https://github.com/iNavFlight/inav/wiki/Modes  It is a hidden features, nevertheless very useful.

**Comment by gemSquared** [comment]
Yay! Finally some light on my autopilot problems!

So let's see. After building firmware, just set up transmitter as usual (SBUS not MSP; or is there another mode added?), set up the override mode AUX channel, and send MSP_SET_RAW_RC?

Also how to tell if control is given to transmitter or MSP? Will the override mode enable when the AUX channel is set but no MSP is sent? Are there any indicators (OSD, LED strip, beeper)?

**Comment by federicohyo** [comment]
Hi gemSquared,

I have tested this feature with the latest inav 2.5. It works OK. You need to take into account that you need to have a free UART and configure it for MSP. Please note, if the MSP message contains invalid channel data or is sent at less than 5Hz, channel values fall back to the normal RC channel values automatically. In addition, you can select which channel to override via the MSP by selecting the right  msp_override_channels bitmask in src/main/rx/msp_override.c . 

When switching flight mode to MSP_OVERRIDE, you will hear a bit. It is just as any other flight mode, I am using a switch on my Radio to switch flight mode.

Will the override mode enable when the AUX channel is set but no MSP is sent? No, behavior is to switch to RC channels automatically.

**Comment by gemSquared** [comment]
Well okay then! Thanks much! :D 

I assume USB probably will work for MSP right?

I think I'll set up the override on a momentary toggle on my TX first actually.

**Comment by federicohyo** [comment]
I also had the same impression, MSP should also work on USB. However, when I have been testing it via USB Virtual Com Port (VCP), it wasn't reliable as a much as using a dedicated UART. Maybe it is related to my flight controller... I am not sure. Let me know if it works for you.
