### ISSUE TITLE
R9m and r9mini

### ISSUE THREAD

**Issue by micito** [iNavFlight/inav#4085]
instead I have this problem, at 25mw of power with telemetry version fw ldb eur.the rssi signal I see it in osd, instead if I change power type 500mw without telemetry ldb fw I do not see more rssi signal ... how can it be? with signal sbus?

**Comment by rb1205** [comment]
Really looks like an issue with R9 mini.

**Comment by micito** [comment]
😫and the problem fw r9mm...

**Comment by DzikuVx** [comment]
This is not INAV issue, I'm affraid we will not help
