### ISSUE TITLE
Public slack link directs to insecure website

### ISSUE THREAD

**Issue by jaxxzer** [iNavFlight/inav#4089]
https://publicslack.com/slacks/inavflight/invites/new

This website does not have a known certificate, my browser tells me I should leave.

**Comment by wx4cb** [comment]
looks like the SSL certificate expired today: 

NET::ERR_CERT_DATE_INVALID
Subject: publicslack.com

Issuer: Let's Encrypt Authority X3

Expires on: Dec 17, 2018

Current date: Dec 17, 2018

**Comment by fiam** [comment]
We deprecated slack in favor of telegram a few months ago. Where is that link found? We need to remove all references to slack to avoid confusion.

**Comment by jaxxzer** [comment]
https://github.com/iNavFlight/inav/blame/master/README.md#L55

**Comment by fiam** [comment]
Thanks for the heads up. I was under the impression that it had been removed in the development branch and it would be updated on the next major release, but it's not the case. I'll remove it.

**Comment by DzikuVx** [comment]
OK, it was removed in `development` and is waiting for deployment so I'm closing this one. Thanks
