### ISSUE TITLE
inav keeps telling me "you need to upgrade firmware before using configuration tab"

### ISSUE THREAD

**Issue by howlingj** [iNavFlight/inav#4093]
I am trying to set up a receiver on my omnibus f4 v2.1 but every time i change anything in any one on the tabs when i reboot it is says "you need to upgrade firmware before using (tab i tried to change) tab"
I have flashed the board to the latest available firmware (v2.0.1) for the omnibus f4 pro

**Comment by digitalentity** [comment]
What Configurator version do you have?

**Comment by howlingj** [comment]
the original issue was in 2.0.0 but i have since tried 1.9.3 which gave me the same issue

**Comment by rb1205** [comment]
What version is the configurator, not the firmware. You might be using an old configurator version, try uninstalling it and installing back again. It doesn't auto update.

**Comment by howlingj** [comment]
my configurator is version 2.0.0 and i have tried the configurater version 1.9.3 
I beleive version 2.0.0 is the latest

**Comment by howlingj** [comment]
![image](https://user-images.githubusercontent.com/39908851/50151561-2a190980-02b9-11e9-9ae2-6d3b17bf7b13.png)

**Comment by shellixyz** [comment]
Please try the latest version of the configurator and open a new in the configurator project if you still have an issue:
https://github.com/iNavFlight/inav-configurator/issues/new
