### ISSUE TITLE
FOXEERF405 Target

### ISSUE THREAD

**Issue by jaime222** [iNavFlight/inav#4095]
Hi I would like you to add this new target to INAV. 

Thank you!

**Comment by digitalentity** [comment]
Are you willing to donate a board to one of the developers for testing the new code?

**Comment by jaime222** [comment]
If I send you one board to test the new code, how many time do you estimate you will release an INAV version for that board?

If is something less than 1-2 months I will send it to you today.

Thanks
________________________________
De: Konstantin Sharlaimov <notifications@github.com>
Enviado: miércoles, 19 de diciembre de 2018 9:03
Para: iNavFlight/inav
Cc: jaime222; Author
Asunto: Re: [iNavFlight/inav] FOXEERF405 Target (#4095)


Are you willing to donate a board to one of the developers for testing the new code?

**Comment by DieHertz** [comment]
Is Foxeer advertising this board as iNav-compatible? If so, you should seek their support for adding it into iNav.

It's nice that your are willing to donate a board, but for adding support it's a necessary condition, not a sufficient one.

**Comment by jaime222** [comment]
I thougth all the betaflight boards had also an INAV target, so I bought one of these FC to my AR Wing. When I tried to flash it with INAV after solder and install everything on my wing I realized I was wrong. Now I prefer to donate the other board that I have than solder everything again haha. 

There is a possibility that a board is not compatible with inav? Why? I thought that the boards that dont have INAV target were beacause the code was not developed yet for those boards, not that those boards might be not compatible with INAV.

Than you!

**Comment by shellixyz** [comment]
@jaime222 This board is compatible compatible with iNav. I added the support for the MPU used on this board recently and since Betaflight already got a target written for it, it should be easy to port. We only need a board to be able to test the new target, it is much easier for us this way. It can be done in less than 2 months no problem, should be done in less than 1.

**Comment by jaime222** [comment]
nice! then let me know where should I send it, so you can release an INAV version for it as soon as possible :)

**Comment by shellixyz** [comment]
@jaime222 Could you connect to Telegram so that I can give you my address ?

**Comment by shellixyz** [comment]
https://t.me/INAVFlight

**Comment by digitalentity** [comment]
@jaime222 @shellixyz if you didn't arrange anything yet, I will probably get the board supported over Christmas holidays.

**Comment by shellixyz** [comment]
Ok :+1:

**Comment by KnuckleUpFPV** [comment]
Very excited for this. Vertical mounted in my new nano goblin. Thank you digitalentity.

**Comment by digitalentity** [comment]
Targets are in progress. I'm closing this issue
