### ISSUE TITLE
Feature request: BME680 barometer support

### ISSUE THREAD

**Issue by TheSoundMan000** [iNavFlight/inav#4101]
Hi all,
Attempting to use a 680 variant of the bosche environment sensors on my drone. It runs the ANYFC F7 target with the external barometer enabled. Unfortunately I've just discovered that inav doesn't support the 680... Given it has much the same interface (different addresses on the data registers so far as I can tell) I would presume someone in the community has already has this modification laying around somewhere? Unfortunately I don't have access to a suitable laptop or internet to get a build environment going so I'm stuck (no other barometers handy and christmas mail will be a long way off)

I'm surprised no one else has needed this sensor, it would be great to get it working and add it to the list. Thanks for any help!

**Comment by shellixyz** [comment]
This barometer isn't supported yet
