### ISSUE TITLE
Multirotor failsafe flip over

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#4102]
I'm having an issue with a quad build.  
One in five times that Failsafe is engaged, the quad will flip over, as it orientates itself for home; before it starts to climb to RTH fly home altitude.
Because it doesn't do it every time. I am having trouble tracking down why it is doing this.

It does right itself, if it has enough altitude. Otherwise if its to low, it crashes.

I thought it may have been to do with the quad trying to stop before it climbed. But the speed the quad is traveling before failsafe is engaged, seems to make no difference. 
I have also tried the multirotor braking mode code. With no difference to the outcome.

Has anyone else experienced this. Or has any idea what causes it?

Below are the 'DIFF' settings and a short clip from the logger. To show what is happening.

[Failsafe flip out.zip](https://github.com/iNavFlight/inav/files/2705709/Failsafe.flip.out.zip)

[NightHawk OmnibusF4 Pro.txt](https://github.com/iNavFlight/inav/files/2705717/NightHawk.OmnibusF4.Pro.txt)
![nav settings](https://user-images.githubusercontent.com/43928973/50380502-2a504500-06bd-11e9-95b7-c13d41770c97.PNG)
![rth landing settings](https://user-images.githubusercontent.com/43928973/50380503-2a504500-06bd-11e9-8c75-a2416cd08e82.PNG)

**Comment by giacomo892** [comment]
is AIRMODE enabled when the copter enters FS?

**Comment by ghost** [comment]
> 
> @giacomo892  
> is AIRMODE enabled when the copter enters FS?

Thanks for your reply.
Yes. AIRMODE is enabled, and selected with failsafe mode. I had read or heard that it should be enabled with Failsafe. Is that correct?
I was in AIRMODE while switching to Failsafe test. Because I very rarely fly in any other mode.

I also noticed something else I had enabled. I had Altitude Hold selected in the same position as Failsafe too.
I turned that OFF. Then did 9 different Failsafe tests on 2 different flights. And it didn't flip over at all.
So it looks like that must have be the cause.
