### ISSUE TITLE
Problems clearing Navigation Safe flag with no GPS

### ISSUE THREAD

**Issue by RichMacf** [iNavFlight/inav#4105]
I have a faulty GPS, and wanted to fly without it, but couldn’t clear the Nav unsafe disable flag.

I disabled GPS in Config, and RTH in Failsafe. The Nav Poshold and RTH modes disappear in the Modes page. But I still get a Nav unsafe flag, which is annoying.

The problem is that the CLI aux entries still exist for the Poshold and RTH modes,  #8 and #9, even if GPS is disabled, and the modes page doesn’t show them. These aux entries seem to throw up the disable flag. It’s confusing that the modes still exist when not visible in the UI. It’s necessary to enable GPS in order to delete the modes.

One firmware solution is to delete the aux entries when GPS is disabled. Or to show the modes in the Modes page if the aux entry exists, so they can be easily deleted. Or the disable flag doesn’t check the aux entries if GPS is disabled.

OMNIBUSF4PRO 2.0.1
Omnibus f4 Pro V3
INAV config 2.0.0

**Comment by teckel12** [comment]
@RichMacf What about turning off extra arming safety?

**Comment by laurentopia** [comment]
> 
> 
> @RichMacf What about turning off extra arming safety?

how do you do that?

**Comment by teckel12** [comment]
@laurentopia Search for `nav_extra_arming_safety`. In CLI, `nav_extra_arming_safety = OFF`
