### ISSUE TITLE
Disable feature(s) by default on F3 processor

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#4108]
The F3 processor is running out of memory to compile INAV with everything enabled. Decide on one or more seldomly used or not very useful features that can be disabled by default. The advantage of finding two or more to disable is that one could be enabled and it may still compile for a custom build. 

Starting off the suggestion list...

* OLED display

F3 pilots (if there's any still out there) what could you live without?

**Comment by wx4cb** [comment]
CPU based SPI? 
Sonar?
External PWM driver?

Those are at least three i have never used - even on F3 boards

**Comment by b14ckyy** [comment]
LED Control?
Optical Flow driver? (was it ever used?)
Some OSD Items removed, if this helps?

**Comment by teckel12** [comment]
Sonar and optical flow are two really good seldomly used features for sure. Not sure how much memory they use, but a good place to look.

I'll create a few builds with these and OLED disabled and see what the result is.

**Comment by Tygrys-1** [comment]
I do find the LED strip usefull. If the plane or a drone is to be used LOS without the OSD it is a good indicator of the model status like GPS sats or battery condition. It is also good for knowing the orientation and position of the model in i.e. twilight conditions.

**Comment by wx4cb** [comment]
yea i wouldn't turn off LED strip personally. all my birds have leds on of some form.

**Comment by b14ckyy** [comment]
Makes sense. 
What about future features? As I remember you plan D-Shot support. This for example could be skipped for F3 targets to save memory for other useful stuff. With lower PID loops it doesn't really make sense and if someone really needs turtle mode, i doubt that those persons would stay with F3 boards.

**Comment by teckel12** [comment]
OLED is not LED strip. OLED is a display, not lights. LED strip is not even being considered.

**Comment by teckel12** [comment]
@b14ckyy Future features would also be considered as they're added. DSHOT for example is on a board BT board basis already.

**Comment by teckel12** [comment]
Sonar and optical flow are already disabled on the F3 by default. Adding OLED (not LED strip) seems to be the logical next option.

**Comment by shellixyz** [comment]
Some ideas (compiled with GCC 7.1.0):

//#define USE_PWM_SERVO_DRIVER
//#define USE_PWM_DRIVER_PCA9685
=> saves 716 bytes. I guess almost nobody uses this, it is only for big planes.

//#define USE_PITOT
//#define USE_PITOT_ADC
=> saves 1424 bytes. Who is using a Pitot ? But maybe not the best to remove

//#define USE_SERIALRX_SUMD
//#define USE_SERIALRX_SUMH
//#define USE_SERIALRX_XBUS
//#define USE_SERIALRX_JETIEXBUS
=> saves 1696 bytes. Exotic serial protocols.

//#define USE_DASHBOARD
//#define USE_OLED_UG2864
//#define DASHBOARD_ARMED_BITMAP
=> saves 3204 bytes. That's not needed at all IMO.

//#define USE_MSP_DISPLAYPORT
=> saves 400 bytes. Display export through MSP. No use for a vast majority I would guess.

//#define USE_GPS_PROTO_NMEA
//#define USE_GPS_PROTO_NAZA
//#define USE_GPS_PROTO_MTK
=> saves 3240 bytes. Isn't almost everybody using Ublox modules ?

Potential flash space saved: 11148 bytes (almost 11KB) or 4.35% of the whole flash space on F3

**Comment by teckel12** [comment]
@shellixyz I'd be good with all but maybe the pwm servo and pitot?  Give some breathing room for more modern/popular features. And a custom build could always turn a few of these on without running out of memory still.

**Comment by hali9** [comment]
There are also not used in a normal flight
//#define USE_DEBUG_TRACE
//#define USE_BOOTLOG
//#define BOOTLOG_DESCRIPTIONS
//#define USE_STATS

And maybe:
#define USE_RCDEVICE
#define NAV_AUTO_MAG_DECLINATION - instead it is mag_declination

And this can be enabled:
#define CLI_MINIMAL_VERBOSITY
#define SKIP_TASK_STATISTICS
#define SKIP_CLI_COMMAND_HELP
#define SKIP_CLI_RESOURCES

**Comment by teckel12** [comment]
@digitalentity :+1:
