### ISSUE TITLE
Convert PID, Navigation and IMU math to fixed point

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#412]
A possible performance booster?

**Comment by DzikuVx** [comment]
Yes, but not all. I would leave all Dterm connected parameters variables float, all Iterm connected fixed point where possible. And I have no opinion on Pterm

**Comment by digitalentity** [comment]
Why keep D-term float point? Q16 have accuracy of ~0,00001, do we need more accuracy?

**Comment by DzikuVx** [comment]
OK, I thought you wanted to go integer or smth like 2 decimal places. With 6 decimal places, I do not care

**Comment by digitalentity** [comment]
No, I want to do a fixed point (libfixmath actually).

**Comment by martinbudden** [comment]
I think it is definitely worth experimenting with this. I presume your plan is to have two versions of the PID, one fixed point and one floating point, but otherwise identical?

**Comment by digitalentity** [comment]
@martinbudden one code, and a compile-time option to expand the code to float point or fixed point

**Comment by martinbudden** [comment]
Yep, that works for me.

**Comment by digitalentity** [comment]
I'm scheduling this for 1.3 - it would be a big space saver for F1 targets.

**Comment by DzikuVx** [comment]
With F1 dead I do not see how we can get anything from it. So closing as obsolete
