### ISSUE TITLE
KakuteF7 - Increase loop time to 4kHz causes CPU reported at 1000%+

### ISSUE THREAD

**Issue by andcarey** [iNavFlight/inav#4121]
Enabling Loop Time at 4kHz causes CPU load

```
# version
# INAV/KAKUTEF7 2.1.0 Dec 15 2018 / 18:01:45 (9433810b9)
# GCC-8.2.0


# diff

# version
# INAV/KAKUTEF7 2.1.0 Dec 15 2018 / 18:01:45 (9433810b9)
# GCC-8.2.0

# resources

# mixer

# servo mix

# servo

# feature

# beeper

# map

# serial

# aux

# adjrange

# rxrange

# osd_layout

# master
set looptime = 250
set gyro_hardware_lpf = 256HZ
set acc_hardware = ICM20689
set mag_hardware = HMC5883
set baro_hardware = BMP280
set pitot_hardware = NONE

# profile
profile 1


# battery_profile
battery_profile 1


# status
System Uptime: 45 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.0V (1S battery - NOT PRESENT)
CPU Clock=216MHz, GYRO=ICM20689, ACC=ICM20689, BARO=BMP280, MAG=HMC5883
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
SD card: None inserted
Stack size: 6144, Stack address: 0x20010000, Heap available: 1568
I2C Errors: 0, config size: 4051, max available config: 32768
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 1042, cycle time: 389, PID rate: 2570, RX rate: 24, System rate: 4
Arming disabled flags: OVRLD COMPASS ACC RX CLI<!-- Use CLI 'version' command to get version string 
```

- FC Board name and vendor: KakuteF7
- INAV version string:2.1.0 (from development)

**Comment by teckel12** [comment]
I have about 10-15% load with 4k and a F722 (Matek F722SE).  Are you getting I2C errors?

**Comment by andcarey** [comment]
Sorry, how do I tell if I'm getting I2C errors?

**Comment by rrk1** [comment]
A counter in the bottom of configurator window while connected, also visible in the result of status CLI command.

**Comment by andcarey** [comment]
OK thanks, the status output in the original issue shows zero errors and that was with no compass connected.
```
I2C Errors: 0, config size: 4051, max available config: 32768
```
I'll also check again now that I have compass connected via I2C.

**Comment by DzikuVx** [comment]
The next version of INAV will come with F7 CPU optimizations that should solve those kinds of problems

**Comment by KissmanCZ** [comment]
still same problem with 2.2.1 :(

**Comment by teckel12** [comment]
@KissmanCZ Interesting, I don't have problems running 4k on the Matek F722SE. Be sure to check for I2C errors and post your diff as it could be another setting causing it.

**Comment by KissmanCZ** [comment]
45x I2C errors :( i will send output of diff when i will be with my board... but i am testing without any peripherals and on default settingsof board (KakuteF7).

**Comment by thundead** [comment]
Same issue here, kakute f7 aio, can't run looptimes >2khz. Tested a kakute f4, no issues

**Comment by teckel12** [comment]
@KissmanCZ There's on-board I2C components (barometer and probably accelerometer).

**Comment by thundead** [comment]
Onboard Baro, Acc is read via SPI as far as I'm aware. (ICM20689). I've attached my Diff file (running 2kHz here).

2Khz - CPU is around 16%, 4Khz - CPU goes over 1000% 

Think this should be re-opened as a bug / issue, unless we're all missing something ?

[INAV_cli_DOMO_20190708_080920.txt](https://github.com/iNavFlight/inav/files/3367071/INAV_cli_DOMO_20190708_080920.txt)

**Comment by DzikuVx** [comment]
If I2C baro or mag is enabled, then max all boards can do is around 2K. Time required to get data from I2C device is longer than time available between PID loops.
It is not a bug, it's a hardware limitation and as such will not be re-opened @thundead 
You can run faster looptimes if you disable barometer

**Comment by rrk1** [comment]
But.... Disabling baro pretty much negates all INAV navigation advantages, and one can just run BF instead, which is easily capable of 8+ K looptimes.

The better idea is to finally move I2C communication in a separate async thread, the task for baro and mag is very low-frequency anyway, also I2C timeouts won't stall main loop any more. No need for extra CPU power  for this, just somewhat better scheduling, as I2C I/O is hardware-assisted.

Sorry, can not help here with a code, as I'm more a hardware guy.

**Comment by DzikuVx** [comment]
@rrk1 I will tell you a secret... you do not need 8k to have a nicely flying quad. 2k is mostly enough.
There are no threads in INAV and I2C driver is synchronous.

**Comment by KissmanCZ** [comment]
@rrk1 i like your idea, but I think there must be reason, why this is not done in the past...

**Comment by rrk1** [comment]
Or may be, just make I2C driver non-blocking in a current cooperative model. Something like when there is next time to read baro or mag, the driver code will just bump I2C hardware registers initiating I/O and right immediately return control back to the main loop. On the next loop in the driver we can poll registers if data is ready, okay, if not, again immediately release the CPU and pass to next loop until we consider no data as I2C timeout. 

So, driver code will consist of some easy flags/branches, never blocking, consuming just a few microseconds of CPU of each loop.

**Comment by johanvandyck** [comment]
Matec722SE and default preset "performance 5 inch quad" settings: 8/4/4kHz settings by default: I'm facing the same issue: cpu is fine (around 15%) but suddenly i2c errors are noted and cpu around 1100%. Only reboot solves it. i2C is reading out the default barometer.

Is something changed between inav 2.1.1 and 2.4.1 which make preset of "5'' performance" in combination with 4kHz working? Or should I stick with 2kHz.
(I'm new to inav and like to keep default settings for now).

Attachment=> my settings cli_diff. I think these are the most important:
set looptime = 250
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 100
set gyro_lpf_type = PT1
set gyro_notch1_hz = 200
set gyro_notch1_cutoff = 100
set gyro_stage2_lowpass_hz = 220
set acc_hardware = MPU6000
[cli_diff_all.txt](https://github.com/iNavFlight/inav/files/4577180/cli_diff_all.txt)

**Comment by DzikuVx** [comment]
@johanvandyck with I2C enabled it's recommended to stick with either 2kHz or overclocking I2c to 800kHz. See https://youtu.be/hEx174fj12E

**Comment by johanvandyck** [comment]
Hi

For me, your workaround is not working.
test:
- i2c_speed = 800khz
- pid loop time = 4 khz
- dshot 300 or dshot600
- baro, gps and compass. No softserial used.
--> in cli, tasks is showing baro around 90µs ->ok. Other values are comparable to your video.
However, cpu is peaking to 1600% after a few seconds of fly time. Not yet clear to me, but @arming cpu jumps imediately between 95 and 100%: too high for me.

If pid loop time = 2Khz everything is working fine. (i2c staid 800kHz, forgot to reset)

I hope Inav find another in depth solution soon. For now, I'll be stuck to pid = 2khz.
