### ISSUE TITLE
OSD turn coordinator

### ISSUE THREAD

**Issue by GhostRiderRC** [iNavFlight/inav#4135]
Hello,
Would it be possible and is someone willing to add a turn coordinator to the OSD?
Just like a yaw string on a cockpit canopy but digital for when there is no elegant solution or on a mc.

https://en.wikipedia.org/wiki/Turn_and_slip_indicator

**Comment by digitalentity** [comment]
The fact is, that maintaining a perfect coordinated turn is what contributes a lot to #1776. Since we started to use `TURN_ASSIST` mode all turns with it enabled became more or less coordinated.

**Comment by GhostRiderRC** [comment]
So the coordinated turn makes the acc think it's flying level and therefore it is impossible (without an extra gyro canted 30º) to meassure? 
Is it possible to use the error (where the acc thinks it's level) to determine if the turn is coordinated?

I have a glider with the cam inside the cockpit and a yaw string. I have turn assist enabled when I use the rudder stick to pan the cam and it helps somewhat but not enough. I don't have an airspeed indicator.

On gliders it makes a big difference in efficiency/maintaining altitude on multicopters it just looks cool.

**Comment by shellixyz** [comment]
@GhostRiderRC In 2.2 you will have the possibility to display lateral g-force on the OSD. I think you can use this to make coordinated turns manually.

Yes there is an issue currently with the artificial horizon going to 0 roll when doing coordinated turns. We're trying to solve the issue.
