### ISSUE TITLE
No osd after font upload

### ISSUE THREAD

**Issue by mfish33** [iNavFlight/inav#4140]
I am using the Matek f405ctr and was having dashed lines across my osd.  To fix this I tried a font upload but I didn't have the battery plugged in.  Now my osd does not show up at all even after multiple tries to upload the font with the battery and even completely re-uploading inav.

**Comment by teckel12** [comment]
@mfish33 Flash INAV with a complete memory wipe as well?

**Comment by mfish33** [comment]
Yeah I tried it.  Did not change anything.

**Comment by teckel12** [comment]
@mfish33 Uploading the font is the correct solution for fixing the dashed lines across the screen problem. Battery disconnected should make no difference (I almost always update my FC including the font with no battery attached).

I would suggest flashing Betaflight (with full wipe) and the Betaflight font to see what happens. If it still doesn't work, maybe the OSD chip is trashed.

**Comment by mfish33** [comment]
All of a sudden it started working again.  No clue why just rolling with it.  Thanks for all the help.
