### ISSUE TITLE
Inav 2.0.1 when Bluetooth is connected to EZ GUI and when transmitter is on no signal is received

### ISSUE THREAD

**Issue by RichardAnkur** [iNavFlight/inav#4151]
Hello 
I have the omnibus f4 pro v2 flight controller board (black one) which I had ordered from https://robu.in/product/omnibus-f4-v2-pro-flight-controller/
I have connected my ublox neo m8n GPS and compass on UART 6 and UART 3 and I am using a flysky fs i6x transmitter and fs iA6B receiver which is connected to sbus/ppm pin using ppm.The firmware which I had uploaded is the omnibus f4pro...and not that ledstrip one.
And now I have connected my HC06 Bluetooth module to UART 1.
The problem is that when I plug in the battery and connect the bluetooth with EZ GUI app it works perfectly but as soon as I turn on my transmitter.....the female voice from EZ GUI tells data not received.
Suggest me a solution

**Comment by wx4cb** [comment]
what do you have active for that port? I had a similar issue with mobileflight thinking i had to have mavlink and msp on the same port. when the aircraft was armed the msp stopped and mavlink took over. 

this was incorrect and i just needed msp on that port.

**Comment by RichardAnkur** [comment]
At UART 1 i had connected my Bluetooth module and msp is activated on that port with a baud rate of 11260.
When the transmitter is off it EZ GUI APP works fine....I can upload the waypoint but as soon I I turn on my transmitter the connection with Bluetooth is lost and I am unable to see the live status of waypoint 
....
how the quad is crossing the way points and completing the mission.
The receiver is connected to the sbus/ppm which is j7 on omnibus f4 v2 pro (black color board).

**Comment by wx4cb** [comment]
i would suggest trying a different uart it sounds like uart 1 is also the one used for PPM maybe? I use sbus & crsf so not sure which port the ppm input is on

**Comment by RichardAnkur** [comment]
My UART 6 and UART 3 is reserved for GPS. Only UART 1 is free

**Comment by wx4cb** [comment]
have you tried soft serial?

**Comment by RichardAnkur** [comment]
Means you are telling me to use the two pins RX and tx above moto_vcc .......
Connect RX from Bluetooth to tx in fc and tx from Bluetooth to RX in fc......and then I will get a additional option below uart6 named softserial....

**Comment by wx4cb** [comment]
not sure which pins they are on that board, but it's either that or you unsolder the gps temporarily to try that uart. it sounds a lot like that ppm and uart 1 pins are on the same port. but not having that board, i'm clutching at straws

**Comment by shellixyz** [comment]
If you want to use UART1 on the Omnibus F4 PRO v2 for something else than S.Bus you need to use PPM for the receiver and remove the S.Bus jumper.

![omnibusf4pro_v2_sbus_jumper](https://user-images.githubusercontent.com/4030264/50737936-a7f07680-11ce-11e9-9743-4111f6fe8cc2.jpg)

**Comment by DzikuVx** [comment]
The solution by @shellixyz is a correct one, it is even mentioned in the docs: https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20Omnibus%20F4.md

Closing, thanks guys

**Comment by RichardAnkur** [comment]
Yes @shellixyz is correct but  now I have connected my Bluetooth to the softserial pad and receiver to UART 1 and it working perfectly.
Thank you for helping me out
