### ISSUE TITLE
Omnibus F4 V6 dose not see serial Spektrum receiver 

### ISSUE THREAD

**Issue by montageu** [iNavFlight/inav#4174]
I am having a struggle with the receiver communication with the FC.  Running a spectrum FPV racing serial receiver wired to 3V3 and TX1 the protocol set in either I-nav or Betaflight (have flashed both trying to resolve this) the Serial Receiver on UART1 and speksat / Spektrum2048 I get nothing @ the Transmitter Tab at all. I have tried other cables / different receivers to no avail. CPU based serial ports are disabled.
Am I missing something simple, I cannot find any assistance on other the WEB / Forums etc.

**Comment by robertgosz** [comment]
Have you tried to connect the receiver to the RX pin ? SRXL protocol/telemetry is not supported in iNav yet.
