### ISSUE TITLE
Blackbox downloading not working on MATEKF722 mini

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#4175]
As reported by @MATEKSYS downloading BB from onboard flash on MATEKF722 MINI hangs. 
At the moment I'm not sure if this is a firmware or Configurator issue.

**Comment by MATEKSYS** [comment]
I tried F405-mini which use WINBOND 25Q256 also, BB can be downloaded

**Comment by digitalentity** [comment]
So it's F7-only. I'll check if I have any F7 board with onboard flash memory.

**Comment by digitalentity** [comment]
Fix ready
