### ISSUE TITLE
2.1.0 RC1 Build error 336

### ISSUE THREAD

**Issue by wrenfpv** [iNavFlight/inav#4179]
## Current Behavior
I try to build following the steps in "Building in windows".

## Steps to Reproduce
1. Installed Cygwin, GNU ARM Toolchain, and Setup Ruby.
2. Opened the Cygwin-Terminal
3. cd /cygdrive/c/dev
    git clone https://github.com/iNavFlight/inav.git
4. cd inav
    make TARGET=MATEKF405SE

## Expected behavior
Within a few moments I should have the binary ready.

## Suggested solution(s)
I think the windows build documentation is not updated, anyone can help?

## Additional context
c:/dev/gcc-arm-none-eabi-8-2018-q4-major-win32/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: C:\cygwin64\tmp\ccOhMlxOdebugobjtem: invalid string offset 143654912 >= 22975072851462314 for section `(null)'
C:\cygwin64\tmp\ccp3TJMSdebugobjtem: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status
lto-wrapper.exe: fatal error: C:\Dev\gcc-arm-none-eabi-8-2018-q4-major-win32\bin\arm-none-eabi-gcc.exe returned 1 exit status
compilation terminated.
c:/dev/gcc-arm-none-eabi-8-2018-q4-major-win32/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:336: obj/main/inav_MATEKF405SE.elf] Error 1

---

N/A
- FC Board name and vendor: N/A
- INAV version string: N/A

**Comment by datamann** [comment]
@wrenfpv
Another alternative could be to use docker
https://github.com/iNavFlight/inav/issues/3896#issuecomment-426416539

**Comment by tiriad** [comment]
Also create a virtual machine and install linux to build the version from there with the manual for that platform

**Comment by digitalentity** [comment]
Yes, there seem to be a bug in gcc 8.2.1 under windows. Earlier versions compile fine
