### ISSUE TITLE
Use "set nav_use_midthr_for_althold = ON" prevent Althold from working

### ISSUE THREAD

**Issue by SaschaIoT** [iNavFlight/inav#4182]
## Current Behavior
If I use "set nav_use_midthr_for_althold = ON" Althold do nothing (with throttle Stick in middle position). Copter not hold altitude, falling down to earth.

## Expected behavior
If I use "set nav_use_midthr_for_althold = ON" and has throttle stick in middle position (1500us) it holds altitude (like it does with "set nav_use_midthr_for_althold = OFF" if I activate Althold with mid throttle (1500us).

## Additional context
[diff all](https://pastebin.com/EvugGJD0)

---

- FC Board name and vendor: [Graupner OmniNXT F7](https://www.graupner.com/Flight-Control-OmniNXT-F7-mit-OSD-BF/48377.NXT/)
- INAV version string: INAV/OMNIBUSF7NXT 2.0.1

**Comment by rb1205** [comment]
I use nav_use_midthr_for_althold  all the time and it works just fine. Your problem is probably somewhere else.

**Comment by SaschaIoT** [comment]
Thanks for the hint, I check it again next days.

**Comment by SaschaIoT** [comment]
I see in Blackbox that my real hover throttle is about 1600. Before that I adjusted the hover throttle to 1480 in iNav Configurator, because it jumps on start.

Tomorrow I set hover throttle to 1600 with "set nav_use_midthr_for_althold = ON" and see if it works. To prevent jump on launch I set min_check higher as the throttle on arming/launch so that prepare for take off logic is applied (I thinks this prevent jumps on arming).

Closing for now - reopening if not works.

**Comment by SaschaIoT** [comment]
Set hover throttle to 1600 with "set nav_use_midthr_for_althold = ON" does not work, not holding altitude. Maybe some developer can see in posted "diff all" what I am doing wrong. As a workaround I use "set nav_use_midthr_for_althold = OFF" and start ALTHOLD with 1500.

**Comment by digitalentity** [comment]
@SaschaIoT can you share your blackbox log?

**Comment by SaschaIoT** [comment]
@digitalentity [Here](https://1drv.ms/t/s!AuEAVAM5kHpu8VHgssQFFtXFUZp6) is my Blackbox with "set nav_use_midthr_for_althold = ON". If I only change it to "set nav_use_midthr_for_althold = OFF" and activate ALTHOLD at 1500 all working fine.

**Comment by SaschaIoT** [comment]
With iNav 2.1 RC3 I have same bug. Maybe I doing something wrong, but don't know what.

**Comment by SaschaIoT** [comment]
Many thanks to @shellixyz and @giacomo892. They helped me to solve the issue. I have to change min throttle to 1150, max throttle to 1850, min command to 1000 and min_check to 1100 in iNav Configurator (Default values). After that it works perfectly 👍 It seems that iNav can not handle changes in these settings, so let it default and it works great.

**Comment by shellixyz** [comment]
It does handle changing these settings. It is just that if you want your quad to hold altitude at 1500 and 1500 is not in the middle between min_throttle and max_throttle you have to adjust thr_mid so that it is.

**Comment by shellixyz** [comment]
For example if you have min_throttle set to 1150 and max_throttle set to 2000. 1000+((2000-1000)+(1150-1000))/2 = 1575, not 1500. mid_thr would need to be set to 41%. 1150+(1000−150)×41/100 = 1500

**Comment by SaschaIoT** [comment]
@shellixyz  Ok great, thanks for explanation 👍

**Comment by Ravid824** [comment]
@shellixyz,   you explained above how to set the ALT Hold values so ALT Hold will work properly when "set nav_use_midthr_for_althold = ON. All was clear until latest releases (I am on 2.4) when min_throttle  was changed to throttle_idle. In release 2.4 still min_throttle still exist and shows 
# get min_throttle
fw_min_throttle_down_pitch = 0 !!!!

Can you please explain the relations between the new parameters and how to set the value nav_mc_hover_thr properly. (example will be helpful). 
set nav_use_midthr_for_althold = OFF works OK but I prefer to use it when it is ON.
Thank you
