### ISSUE TITLE
Matek F405 Wing Dshot

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#4184]
Cannot enable DSHOT on the latest RC on a matek F405 Wing. using blheli32 escs on an S1100 wing.

I'm assuming that dshot support is disabled on this FC?

**Comment by stronnag** [comment]
Another support question, from https://www.rcgroups.com/forums/showpost.php?p=40870461&postcount=23323

**RC1 DSHOT targets**

* ASGARD32F4
* ASGARD32F7
* COLIBRI_RACE
* FIREWORKSV2
* FOXEERF405
* FOXEERF722DUAL
* MATEKF405
* MATEKF722
* MATEKF722SE
* OMNIBUSF4
* OMNIBUSF7NXT
* REVO

**Comment by stronnag** [comment]
Above list added to RC1 release note.

**Comment by wx4cb** [comment]
@stronnag thanks I can't get on rc groups from work
