### ISSUE TITLE
Enabling RX_MSP feature

### ISSUE THREAD

**Issue by tykimseoul** [iNavFlight/inav#4198]
Hi, I am trying to enable the MSP feature in the configurator.
My goal is to use the MSP protocol to make the flight controller and a Raspberry Pi communicate.

#### Configurator Version : 2.0.0

I found some CLI commands for enabling MSP:
```
feature RX_MSP
set receiver_type = MSP
save
```
So I tried it:
![image](https://user-images.githubusercontent.com/10570566/51083502-b30f4d80-175e-11e9-9e78-e89cfccd1654.png)
then I saved and rebooted.

But when I reconnect and check features again, it does not list RX_MSP.
I think this might be why SET_RAW_RC command does not work.

Any ideas will be appreciated.

**Comment by stronnag** [comment]
https://github.com/stronnag/msp_set_rx

**Comment by tykimseoul** [comment]
@stronnag Thanks for your suggestion.
However, I have already checked out the link and did not succeed.

To elaborate on my issue, I have implemented the msp protocol and sent out the SET_RAW_RC command successfully.
I have even got a response with the same command code (code 200), which I believe is an expected result.
The only problem is that the motor does not spin.
So I was wondering if the feature RX_MSP of the configurator was the reason.

Shouldn't the RX_MSP feature stay even after I reboot?

Thanks

**Comment by stronnag** [comment]
`FEATURE RX_*` was removed in iNav 1.8 (as stated on the previous link) and in the 1.8 release notes.

**Comment by tykimseoul** [comment]
But the feature RX_MSP command still works.
It does not give an error and even gets listed in feature.
Do you mean that the command will have no effect?

**Comment by stronnag** [comment]
Read the release note; draw your own conclusion ....

**Comment by shlapion** [comment]
@tykimseoul  I am also working with RPi and iNav. Flight controller, in my case Matek F722 and RPi communicate just fine. 
The issue i had was to send the MSP commands to the FC with a high enough frequency such that it does not go into failsafe mode.
Would be more than happy to assist you in solving your problem.

**Comment by tobetz** [comment]
@tykimseoul and @shlapion: Did you solve this problem? I would also like to control a copter with the RPi, and I am pretty much stuck where @tykimseoul was left. The feature RX_MSP is turning itself off. I have recompiled the firmware to enable MSP over UART. All no luck. I can send commands and get the 200 back, but I cannot arm and control the copter. 
The commands are sent with about 10Hz I think, but I have not perfectly measured. Any ideas how to convince the FC to answer. 

PS: I have a CC3D, and tried iNav and betaflight

**Comment by stronnag** [comment]
> The feature RX_MSP is turning itself off. I have recompiled the firmware to enable MSP over UART. All no luck. I can send commands and get the 200 back, but I cannot arm and control the copter.
> The commands are sent with about 10Hz I think, but I have not perfectly measured. Any ideas how to convince the FC to answer.
> 
> PS: I have a CC3D, and tried iNav and betaflight

Notwithstanding that CC3D is long not supported, if you patch in `RX_MSP` it works just fine ... as long as you rigorously apply the required arming and update conditions (https://github.com/stronnag/msp_set_rx#caveats)

Here we go ....

```
$ ./msp_set_rx -A 5
2020/01/12 11:00:01 Using device /dev/ttyACM0
INAV v1.7.3 CC3D (772e015f) API 2.0
...
Rx: [1500 1500 1500 1000 1001 1442 1605 1669] (00300) unarmed Quiescent
Tx: [1500 1500 1500 1000 2000 1442 1605 1669]
Rx: [1500 1500 1500 1000 2000 1442 1605 1669] (00301) unarmed Arming
Tx: [1500 1500 1500 1000 2000 1442 1605 1669]
Rx: [1500 1500 1500 1000 2000 1442 1605 1669] (00302) armed Arming
...
Tx: [1500 1500 1500 1000 2000 1442 1605 1669]
Rx: [1500 1500 1500 1000 2000 1442 1605 1669] (00311) armed Min throttle
...
Rx: [1500 1500 1500 1000 2000 1442 1605 1669] (01500) armed Min throttle
Tx: [1500 1500 1500 1000 1000 1442 1605 1669]
Rx: [1500 1500 1500 1000 1000 1442 1605 1669] (01501) armed Dis-arming
Tx: [1500 1500 1500 1000 1000 1442 1605 1669]
Rx: [1500 1500 1500 1000 1000 1442 1605 1669] (01502) armed Dis-arming
Tx: [1500 1500 1500 1000 1000 1442 1605 1669]
Rx: [1500 1500 1500 1000 1000 1442 1605 1669] (01503) unarmed Dis-arming
...
Tx: [1500 1500 1500 1000 1001 1442 1605 1669]
Rx: [1500 1500 1500 1000 1001 1442 1605 1669] (01511) unarmed Quiescent
```
