### ISSUE TITLE
Matek F722 std locked when powered from usb

### ISSUE THREAD

**Issue by robiu** [iNavFlight/inav#4209]
## Current Behavior

unable to connect to GUI, communication started but not continue

## Steps to Reproduce
1. connect usb port of computer to flight controller, connected with a gps beitan 880 and Magnetometr and powered up from pcb flight controller, do not connect battery
2. try to connect to GUI using Inav configurator
3. the system hangs and the GUI go in timeout 

## Expected behavior
connecting to gui for configuration etc..

## Suggested solution(s)
The problem disappear if before connect to usb cable connect the battery ti flight controller or if disconnect gps before connect usb. 
 Try to put a delay in a source code before pcb flight controller start send a command of configuration to gps beitan 880 and delay from command to command and/or add a capacitor directly to the power line of microcontroller 
- FC Board name and vendor:Matek f722 STD, but appear (not verified) to be common problem to kakute f7
- INAV version string: 2.01 and 2.1

**Comment by DzikuVx** [comment]
Hi, it's not powered I2C device issue: https://www.youtube.com/watch?v=W1vLTbvea3A
