### ISSUE TITLE
Airbot NOX support

### ISSUE THREAD

**Issue by mooiweertje** [iNavFlight/inav#4214]
I've created a new target for my NOX compliant board. I'd like to share it so it can be part of the next release. Can I just push it ?

**Comment by teckel12** [comment]
@mooiweertje Create a pull request to the development branch.  Additional information: https://github.com/iNavFlight/inav/blob/master/docs/development/Development.md

**Comment by mooiweertje** [comment]
First time doing this but I think I succeeded.

**Comment by mooiweertje** [comment]
Done: https://github.com/iNavFlight/inav/pull/4216

**Comment by shellixyz** [comment]
PR to add the board staging, closing

**Comment by mooiweertje** [comment]
I created a version where GPS can be connected to PPM and LED via Soft Serial 2

[jnav_5.0.0.0_NOX.zip](https://github.com/iNavFlight/inav/files/9735545/jnav_5.0.0.0_NOX.zip)
