### ISSUE TITLE
Inav 2.1.0 conf + F405-wing - S9 servo output

### ISSUE THREAD

**Issue by jreis1** [iNavFlight/inav#4223]
Hey there, 

Inav Configurator 2.1.0, Inav 2.0.1,  matek F405-wing. 

How can I activate (use) output S9 in matek board?
Instruction in Matek website are quite clear and say to enable: "Forward aux channels to servo output", as follows:
![image](https://user-images.githubusercontent.com/25162166/51379636-c6783b00-1b07-11e9-8102-ea0a75ff5da3.png)

However, this option is no longer available in the current GUI version. 

If I go to mixer Tab, and try to had a new servo, it is indeed added to the servo list: 
![image](https://user-images.githubusercontent.com/25162166/51379782-2242c400-1b08-11e9-857f-656669b74094.png)

but as soon as I save&reboot, and return back to the servo mixer tab, the newly added servo is no longer in the list:

![image](https://user-images.githubusercontent.com/25162166/51379839-47373700-1b08-11e9-90ca-7b8dd6d07996.png)

Any ideias?

**Comment by shellixyz** [comment]
Looks like a bug

**Comment by jreis1** [comment]
> Looks like a bug

Hey, 
I've found solution for this.  I had to clear all the servo mixing, and add the servos again to the list (using add new mixer rule),  this time starting by Servo 0, up to Servo 6.

**Comment by shellixyz** [comment]
Good news that you found a solution but still it is a bit strange

**Comment by DzikuVx** [comment]
Firmware allows for max 8 servos indexed from 0 to 7. I see you had index 8 so it was rejecting it.
