### ISSUE TITLE
Inav 2.1 RC , with F722 STD and OSD lines

### ISSUE THREAD

**Issue by Papipapito** [iNavFlight/inav#4229]
Hello

I updated my 2.o Inav to 2.1, and all work, i have F722 STD (Multishot into esc)

But Now I activated OSD , the osd Show a line into the screen, I upload the fonts to solve:

![img_4089](https://user-images.githubusercontent.com/45603981/51425445-81720880-1bdc-11e9-802f-890b3714f1d2.jpg)

But , when uploading, the system Hang at 301/302 , every font tested

![captura de pantalla 2019-01-19 a las 9 52 50](https://user-images.githubusercontent.com/45603981/51425449-98185f80-1bdc-11e9-9acc-0107d84c49bf.png)

When force restart the Controller, the lines are solved, but OSD show error

![img_4090](https://user-images.githubusercontent.com/45603981/51425457-b0887a00-1bdc-11e9-9dea-f2ab7ba0bc28.jpg)

Any Idea To solve?

**Comment by teckel12** [comment]
@Papipapito Did you do a full wipe when flashing?

**Comment by giacomo892** [comment]
use windows/linux and load the font again

**Comment by Papipapito** [comment]
Hello
 
I updated the de fonts with windows, and work

Thankyou
