### ISSUE TITLE
Rx input broken on quanton target

### ISSUE THREAD

**Issue by PTDreamer** [iNavFlight/inav#4237]
PWM and PPM Rx input has been broken on quanton since e4f31fb. The pins are being configured as regular inputs instead of AF.
I was going to open a pull request with the simple fix but I see those files were heavily refactored on the dev branch, haven't taken the time to see if the issue is still there.

Thanks

**Comment by shellixyz** [comment]
Quanton target ? I don't see it or anything close

**Comment by PTDreamer** [comment]
https://github.com/iNavFlight/inav/tree/master/src/main/target/COLIBRI

It shares the target definitions with "Colibri" since it is basically the same hardware on a different form factor.

**Comment by shellixyz** [comment]
I don't have one of these boards. Please try 2.1.0-RC2 and report whether the issue is still there or not.

**Comment by shellixyz** [comment]
Have you been able to confirm the issue is still present in 2.1.0 ? If you know how to fix the issue please submit a pull request.
