### ISSUE TITLE
INAV wont load after flash on RXSR-FC (OMNIBUS F4 Fireworks V2)

### ISSUE THREAD

**Issue by TIMO88D** [iNavFlight/inav#4239]
## Current Behavior
RXSR-FC (OMNIBUS F4 Fireworks V2) will not open in inav

## Steps to Reproduce
have a RXSR-FC (OMNIBUS F4 Fireworks V2)
1. enter boot mode on FC by holding button
2. Connect to windows 10 pc via usb (ensure correct driver is elected through Zadig (winusb for stem32))
3. use Inav configurator to flash FireworksV2 Firmware succefully
4.  reboot fc
5. attempt to connect through correct com Chanel (3 for me)
6. "Serial port successfully opened ID:1"
7. "no configuration received within 10 seconds, communication falied"
8. give up, re flash betaflight, open bug issue. 

## Expected behavior
Flash will work, but Inav configurator will not be able to open a serial connection

## Suggested solution(s)
Unknown

## Additional context

---

not possible

- FC Board name and vendor:
RXSR-FC (OMNIBUS F4 Fireworks V2) 

- INAV version string:
Inav configurator 2.1.0, FrieworksV2 firmware 2.0.1

**Comment by flyingbandit** [comment]
Same behaviour with omniNXT f7

**Comment by bchristal** [comment]
Same issue with Matek F22 and Omnibus F4. The Omnibus F4 connects fine with Betaflight. 

Windows 10
CP210x USB to UART Bridge Virtual COM Port Windows 10 Universal (v10.1.4) - Installed

![image](https://user-images.githubusercontent.com/11396110/52169624-6a193c00-2701-11e9-8fb5-f73989096dfe.png)


Device Manager:
![image](https://user-images.githubusercontent.com/11396110/52169597-f9721f80-2700-11e9-909e-6724d5e2b520.png)

**Comment by PHMT** [comment]
Same behavior (and error) as the OP.  Trying to use 2.1 on the Kakute F7 (non-AIO version) using INAV configurator 2.1.4.  Re-flashing Betaflight 4.0 works just fine.

Edit:  Never mind.  My issue looks like it was a driver problem.  I went back and re-flashed iNav and now iNav connected just fine after the flash.  I spent hours yesterday and iNav would not connect.  Now it did.  What changed was in between, I had given up on iNav and flashed Arducopter and had downloaded Mission Planner.  When Mission Planner installed, I noticed that it installed/re-installed some drivers and one of them was a STM driver.  What ever drivers I had previously worked just fine for Betaflight, but apparently not iNav.  I suspect that at least one of the drivers installed by Mission Planner was also what iNav needed.  So now it works.

**Comment by Mougs** [comment]
> ## Current Behavior
> RXSR-FC (OMNIBUS F4 Fireworks V2) will not open in inav
> 
> ## Steps to Reproduce
> have a RXSR-FC (OMNIBUS F4 Fireworks V2)
> 
> 1. enter boot mode on FC by holding button
> 2. Connect to windows 10 pc via usb (ensure correct driver is elected through Zadig (winusb for stem32))
> 3. use Inav configurator to flash FireworksV2 Firmware succefully
> 4. reboot fc
> 5. attempt to connect through correct com Chanel (3 for me)
> 6. "Serial port successfully opened ID:1"
> 7. "no configuration received within 10 seconds, communication falied"
> 8. give up, re flash betaflight, open bug issue.
> 
> ## Expected behavior
> Flash will work, but Inav configurator will not be able to open a serial connection
> 
> ## Suggested solution(s)
> Unknown
> 
> ## Additional context
> not possible
> 
> * FC Board name and vendor:
>   RXSR-FC (OMNIBUS F4 Fireworks V2)
> * INAV version string:
>   Inav configurator 2.1.0, FrieworksV2 firmware 2.0.1

Same problem with Inav configurator 2.2.1

**Comment by Mougs** [comment]
Hello,
Nobody have a solution for this communication problem?
