### ISSUE TITLE
2.1 RC1 Smart audio on F35 Lightning with AKK not working

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#4244]
Latest RC candidate with F35 FC Full options.

AKK x2 ultimate hooked up and working, hooked up the smart audio to UART 4 and set to TBS (also tried tramp) and all the other baud rate options aren't working.

Seems to be the same as the following
https://github.com/iNavFlight/inav/issues/3753
https://github.com/iNavFlight/inav/issues/3681
https://github.com/iNavFlight/inav/issues/3625

This was fixed in 2.0 if i remember correctly, but i've tried 3 akks and also the RDQ mach2/3 which are effectively the same (iirc) and they all just get scrambled displays on the 7 segment display on board.

any method to change it via the osd fails, just says the stats page where it's trying to send etc.

Any thoughts as to where to check, the VTX SA works on betaflight.

**Comment by fiam** [comment]
It's probably the bug fixed in #4231

**Comment by wx4cb** [comment]
Cool. Cant wait for rc2 hehe

**Comment by shellixyz** [comment]
Please report if RC2 fixed the issue

**Comment by wx4cb** [comment]
will do.. i'll put rc2 on the board today as im planning on maidening my 3rd MT this weekend.

**Comment by wx4cb** [comment]
just tried it on 2 new AKK vtxs on 2 different f35's (one crashed one brand new) and all i get is a garbled LED display. turn off smart audio and the display reverts back to "normal"
![20190202_082600](https://user-images.githubusercontent.com/1495297/52164754-79c65f80-26c4-11e9-817e-9f32b036bbc6.jpg)
![20190202_082601](https://user-images.githubusercontent.com/1495297/52164755-7a5ef600-26c4-11e9-874b-b743bff138c4.jpg)
![20190202_082608](https://user-images.githubusercontent.com/1495297/52164756-7a5ef600-26c4-11e9-87ef-2c8cd39e261a.jpg)
![20190202_082615](https://user-images.githubusercontent.com/1495297/52164757-7a5ef600-26c4-11e9-989b-e28ad97f91ed.jpg)
![20190202_082632](https://user-images.githubusercontent.com/1495297/52164758-7a5ef600-26c4-11e9-9264-198f836aaf35.jpg)

**Comment by dangerg** [comment]
Same issue here. I have tried both the AKK and the TX805. I will try with other boards.

**Comment by dangerg** [comment]
FYI: Tried the same AKK and TX805 on a F4 flight controller with no problems. It appears to be a problem with the F35 and smart audio.

**Comment by sniperxnl** [comment]
Hi Guys,

Any news on this?
we have a customer with a F35 and AKK vtx and don't get it working.

**Comment by sniperxnl** [comment]
Any news here guys?

**Comment by dangerg** [comment]
Try softserial.

**Comment by bigbear2001** [comment]
For TX4, try changing this resistor from 1 KOhm to 100 Ohm. It helped me solve this problem on Wing FC 10 DOF
![TX4_2](https://user-images.githubusercontent.com/57317994/71503007-c8f12200-288c-11ea-99c4-da42243e42fd.jpg)

**Comment by datamann** [comment]
I have the same issue, AKK Smart Audio on TX4 on FC Wing. @bigbear2001 I will try the same to see if it helps.

**Comment by dangerg** [comment]
> I have the same issue, AKK Smart Audio on TX4 on FC Wing. @bigbear2001 I will try the same to see if it helps.


> For TX4, try changing this resistor from 1 KOhm to 100 Ohm. It helped me solve this problem on Wing FC 10 DOF
> ![TX4_2](https://user-images.githubusercontent.com/57317994/71503007-c8f12200-288c-11ea-99c4-da42243e42fd.jpg)

This is so small. I was eventually able to get my 100 ohm resistor on there... Still no luck with smartaudio on TX4.  Has anyone had luck with smartaudio on this board? I have given up and just set it to full powers with a heat sink.

**Comment by modwadd** [comment]
Hello, I head the same issue.
if the vtx is enabled the signal on tx4 loks good, but if  the tx804 V2.0 is powered up the signal is going down to low much to slow (i measured it by an osci), the vtx could not red the command. Not shure if the resistor is a pull down, but if yes I could imagin that it heps.

Unfortunatly i distroy my WING FC controller during measurment. Due to that I don't have pciturs.
I could also imagin that there migt be a SW controllible pull down which could solve the issue too.

On an old SP racing F3 the same VZX works, the singnals on the osci look a lot better.

**Comment by activa73** [comment]
@datamann Hello, I have the same issue than you with myWING FC and smart audio on TX4. Have you try to change the resisitor from 1k to 100 ohm? And it is work?
@dangerg Hello can you confirm it is work, please?
BR

**Comment by activa73** [comment]
I confirm Smart audio works after changing resitor from 1k to 100 ohm. The size is 0402.

With 1kohm : waveform uC side
![TEK00001](https://user-images.githubusercontent.com/11349085/81606901-24532500-93d4-11ea-9544-4d0590a424e7.jpg)
With 1kohm : waveform TX4 pin side
![TEK00003](https://user-images.githubusercontent.com/11349085/81607017-48af0180-93d4-11ea-91f2-d27baca35977.jpg)
With 100 ohm : waveform uC side
![TEK00005](https://user-images.githubusercontent.com/11349085/81607058-56fd1d80-93d4-11ea-9b84-02862566dbe8.jpg)
With 100 ohm : waveform TX4 pin side
![TEK00004](https://user-images.githubusercontent.com/11349085/81607073-5fedef00-93d4-11ea-8632-1db8b8278967.jpg)

**Comment by modwadd** [comment]
Good to know, thanks for the effort to do the measurement.

**Comment by dangerg** [comment]
Thanks for the great work.

**Comment by activa73** [comment]
No problem thank you for the solution.

**Comment by UnchartedBull** [comment]
Can confirm that this works with 150 Ohm as well. You can also use a „normal“ resistor and solder one end to tx4 and the other to the side of the 1k resistor that is closer to the CPU. Just in case you don‘t want to desolder this tiny resistor (electricity will always use the path of least resistance) plus it is easily reversible :). Thanks for the info guys!

![50E43428-B3AE-4716-98FC-BF8FD27FF589](https://user-images.githubusercontent.com/19818061/88311127-d0888480-cd10-11ea-8ae3-6c2073d88d7c.jpeg)

**Comment by hallskelet** [comment]
Спасибо вам огромное за описание этой проблемы. Производитель не даёт схему этой платы и без вас я бы ещё долго искал проблему.

**Comment by andrushm** [comment]
Helpful even in 2024! Thanks!
