### ISSUE TITLE
Personalization name of the model dissapears from 2.0 to 2.1.0 and 2.1.1  configurator for matek 405d

### ISSUE THREAD

**Issue by fmartinezo** [iNavFlight/inav#4248]
## This is a 2.0 screen
![imagen](https://user-images.githubusercontent.com/38476783/51537567-34499d00-1e4f-11e9-85da-6cdbb9bfd2d8.png)
This is a 2.1.0 
![imagen](https://user-images.githubusercontent.com/38476783/51537711-91dde980-1e4f-11e9-9389-63a7439aa299.png)
This is a 2.1.1
![imagen](https://user-images.githubusercontent.com/38476783/51537759-b5a12f80-1e4f-11e9-99d5-83f87a2b1e86.png)
 

## Steps to Reproduce
1. start configurator 
2. go to config page
3. scroll down

- FC Board name and vendor: matek 405 ctr
- INAV version string: # version
# INAV/MATEKF405 2.1.0 Jan 22 2019 / 09:41:21 (7bdd5967e)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by teckel12** [comment]
@fmartinezo I noticed this too, but figured it was just moved and didn't care enough to go looking.

**Comment by fmartinezo** [comment]
I understand that you do not care too much, but from what I've looked at it has simply disappeared from the configurator. However, it can be accessed from cli.

**Comment by fmartinezo** [comment]
@teckel12 I remind you that the inav telemetry lua parameterizes the models by the name and if people do not see where to put the name or do not know how to do it, they will not be able to parameterize the models. So it is very important that the place where the name is placed reappears in the configurator

**Comment by teckel12** [comment]
@fmartinezo I think you misunderstood my message. I didn't mean that it shouldn't be fixed, I just meant I didn't have the time to go looking for it at that time so I just entered it in the CLI. 

Also, because this is a configurator issue, you should post this issue in that repo, not here.

**Comment by fmartinezo** [comment]
It is already open in configurator.
