### ISSUE TITLE
NAZE target hangs on boot randomly (other F1 targets might also be affected)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#425]
as title, current master fails to boot on flip32 (blue light only). Not sure when this happened, as I mostly fly F3.

It also does not build with gcc 4.9, ok with 6.1

I found a naze hex 57a3320 (mid July), that boots OK and detects all sensors.

On last week's backup, I find  27822a5 (c. 29th July). That boots OK too, but fails to detect the baro (the mag is physically removed).

The test regime appears to have failed for F1.

**Comment by digitalentity** [comment]
Ok, I have a flip somewhere, I'll find it and find the exact commit that broke stuff

**Comment by digitalentity** [comment]
Ref. baro: MS5611 was for some reason removed in affffb7ef1744bbe120baf56847f48cecb4d460c. @martinbudden can you shed some light why? :smile:

**Comment by digitalentity** [comment]
Naze (Flip) boot issues introduced by 0489eb8b0840719277450a8d15bb6f1d5e6f62be

**Comment by digitalentity** [comment]
Once I remove SONAR support from NAZE target it starts working again. Apparently SONAR support is broken in new IO

**Comment by digitalentity** [comment]
More info - `#define SONAR` and `#define USE_RX_NRF24` can't co-exist. Once I undef either of them NAZE boots and works fine. @martinbudden can you have a look?

**Comment by digitalentity** [comment]
No, it's deeper than that. Something is terribly wrong - board boots once in a while, the other time it hangs before detecting sensors. Possibly some race condition?

I'm now certain, that SONAR has nothing to do with this bug. Board with disabled SONAR just hung on boot for 3 times in a row and on 4th try booted and worked fine.

**Comment by digitalentity** [comment]
Ok, I can't find a place where it can hang anywhere in the code. I need to hook up my JTAG and see where it's stuck.

**Comment by digitalentity** [comment]
Ok, we are falling into `HardFault_Handler` from somewhere inside `SetSysClock`. Very interesting.

**Comment by digitalentity** [comment]
HFSR = 0x40000000 (Indicates a forced hard fault, generated by escalation of a fault with configurable priority that cannot be handles, either because of priority or because it is disabled)
UFSR = 0x0001 (the processor has attempted to execute an undefined instruction)

How is this possible?

**Comment by digitalentity** [comment]
Board now boots fine on each occasion. I'm even more confused.

**Comment by jflyper** [comment]
Unexpected, sporadic interrupt diving into random location?

The location of the instruction should stacked as exception return address...

**Comment by martinbudden** [comment]
@digitalentity MS5611 was removed as a ROM-saving measure. I erroneously assumed it was only used as an external barometer - I hadn't realised Flip32 used it. Sorry about that.

There is also en error in the current code in that   `EXTIInit();` is not called in`main.c` - this might be the root of this problem.

I have noticed that the order initialisation differs between iNav and betaflight - that may be problematic.

Can you try out https://github.com/iNavFlight/inav/pull/422 "New IO for UARTs, LED_STRIP and BIND_PIN " which has `EXTIInit` and see if this fixes the problem (I don't have a Flip board).

**Comment by digitalentity** [comment]
I've put the `EXTIInit()` into `init()` but it didn't solve the problem. Board randomly crashes to HardFault from `SetSysClock()`.

**Comment by martinbudden** [comment]
For F1 boards SetSysClock is defined as `void SetSysClock(bool overclock)` , probably not the problem, but odd that the compiler is not picking this up.

**Comment by digitalentity** [comment]
Thanks for the hint. It appears that `SetSysClock` is called twice - from `init()` and from `systemInit()`, maybe this is the cause.

**Comment by digitalentity** [comment]
F1 target clock initialisation tried to boot the board on HSI if HSE fails. I wonder if there is a target without an XTAL that actually requires this code or it can be safely dropped?

**Comment by digitalentity** [comment]
IMO it was the doubled call to `SetSysClock()`, at least power-cycling the board 50 times didn't result in a single hangup.

**Comment by martinbudden** [comment]
I love it when things can be debugged by reading the code.

**Comment by digitalentity** [comment]
It took me two hours with debugger trying to figure out why SetSysClock() hardfaults, while I should have greped the source and checked for doubled calls...
I'm testing this on CC3D, NAZE and SPRacingF3, will merge after testing.

**Comment by digitalentity** [comment]
Fixed

**Comment by stronnag** [comment]
@martinbudden you should upgrade the compiler, gcc 6.1 does catch the harmless declaration mismatch. 
https://github.com/iNavFlight/inav/pull/420#issuecomment-237671066

**Comment by martinbudden** [comment]
@stronnag , you're right, thanks. Upgrading the compiler has been on my todo list for a while now...
