### ISSUE TITLE
OSD Tab Blank in iNav Configurator (version 2.1.1)

### ISSUE THREAD

**Issue by Lightman500** [iNavFlight/inav#4253]
## Current Behavior

Clicking on OSD tab in configurator shows a blank window.  Yet, I see default OSD parameters in video (goggles).  There is no way to configure the OSD display. I am running Furious F35 Lighting flight controller.
## Steps to Reproduce

1.invoke iNav configurator
2.Select OSD Tab
3.View blank window
4.

## Expected behavior

I expected to see the virtual OSD display and parameters to select and move around display
## Additional context

---

Running iNav Configurator 2.1.1; Firmware: iNav 2.0.1; Board FF35
- FC Board name and vendor:
- INAV version string:

**Comment by ghost** [comment]
https://github.com/iNavFlight/inav-configurator/issues/659

**Comment by DzikuVx** [comment]
yes, duplicate of iNavFlight/inav-configurator#659
