### ISSUE TITLE
Increase servo travel for RC channels

### ISSUE THREAD

**Issue by Fluburtur** [iNavFlight/inav#4254]
**Issue:**
I have a camera mounted on a servo, it does not rotate enough (servo has unused mechanical travel)

**What I want:**
Being able to increase the travel of RC channel servos

This is the CLI line for that particular servo:
servo 7 1000 2000 1500 -125

Would I be able to change that using a CLI command? I looked at the list of commands and didn't find any that seems to control that.

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/51746440-6d2f7f00-20a6-11e9-8613-5ef6d19adb0f.png)

What about min and max for each servo? it allows values beweend 750 and 2250
