### ISSUE TITLE
Incorrect position of fixed OSD elements in PAL mode

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav#4268]
## Current Behavior

fixed OSD elements - AHI, Crosshair, sidebars are shown one line higher in inav 2.1-RC2 OSD PAL mode compared to Inav 2.0 

## Steps to Reproduce
1. Open OSD tab in configurator and setup a layout in PAL mode.
2. Compare to the actual layout on the screen - Croshair position on the screen does not match position in the configurator preview:

![2](https://user-images.githubusercontent.com/25912739/51788260-72fb9200-2184-11e9-8b8f-6468019505f1.jpg)

## Expected behavior
Fixed OSD elements in PAL mode are supposed to move down by one line in PAL mode compared to NTSC mode:

![1](https://user-images.githubusercontent.com/25912739/51788232-42b3f380-2184-11e9-841a-816e0db8a6ec.jpg)

## Suggested solution(s)
It would appear that video format change to PAL is ignored regarding the position of the fixed OSD elements.

---
INAV/MATEKF405SE 2.1.0 Jan 26 2019 / 13:05:51 (506c64f)
GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by OlivierC-FR** [comment]
I digged a bit, in io/osd.c:96
IS_DISPLAY_PAL (displayScreenSize(osdDisplayPort) == VIDEO_BUFFER_CHARS_PAL) 
.. is always 390 == 480, so whatever the video system is set to, it always goes to NTSC.
The issue is somewhere in drivers/max7456.c that was rewritten, didn't have time to dig more.
Nor the knowledge anyway.

**Comment by Arvycka** [comment]
Seems to have been fixed.

**Comment by fiam** [comment]
@Arvycka Can you test the patch? I can build a binary for you if needed.

**Comment by Arvycka** [comment]
I just did - Both PAL and NTSC. It's as was before 2.1. AHI block moves to line 7 (8th line) for PAL as is drawn on line 6 for NTSC.

**Comment by fiam** [comment]
Thanks, perfect!
