### ISSUE TITLE
Fortini F4 rev. 3 support

### ISSUE THREAD

**Issue by krzysiu4** [iNavFlight/inav#4270]
Hi,

I have Fortini F4 rev. 3 board and after flashing Inav I can't connect to Inav's Configurator. There was only option to choose "Fortini F4" while flashing, but I suspected that it's the same as "Fortini F4 rev. 3". Or maybe not and there is no support for Fortini F4 rev. 3 but only Fortini F4? If so, is there any chance that it will be added in future releases?

Thanks in advance

**Comment by sniperxnl** [comment]
The Rev3, have a diffrent pint out, The Fortini that is avalible is for the Rev2 version

**Comment by koutstom78** [comment]
Any news for the REV3  target ?? thanks in advance!!
