### ISSUE TITLE
Matek f405ctr GPS issues

### ISSUE THREAD

**Issue by Ferris75** [iNavFlight/inav#4271]
Hi all, new to this hobby and have a matek f405 ctr with led on pin s5 but cannot connect GPS. Have GPS added as per the matek website image however mag and baro working but GPS in red in Inav. Wondering if I have a configuration issue due to on board baro on the fc board. So frustrated that there's nothing clear out there to help on this, anyone got any suggestions on what to do. I can screenshot ports (GPS on uart3) baro and mag workig GPS has fix on location but showing as red in inav. Thanks in advance.

**Comment by laurentopia** [comment]
fix type = 3D?
in case you're missing something, my setting for the BN880 is
in ports : UART4 sensors = GPS
in configuration : GPS = on, protocol = UBLOX, ground assist = Autodetect
*connect battery and marvel at the blue GPS

**Comment by Ferris75** [comment]
That doesn't work either. I think I have issues with my port settings or similar but just can't work it out. There's no wiring diagrams out there with comprehensive details on the matek board.

Does someone have any experience e with the f405ctr and a radiolink se100 and inav showing as red.

Tha ks for the reply lautentopia but not sure what you mean. I had GPS on uart 3 set up for GPS but just no GPS fix and not showing in GPS tad of inav.

**Comment by Ferris75** [comment]
Hi Laurentopia, so i have changed this to Uart4 and yes i now have a gps fix showing in GPS tab of Inav. Only issue i have now is that the GPS does not seem to be showing any led's other than power on (1 green led) but 3d frix in GPS... well confused now!!
![img_20190127_084858](https://user-images.githubusercontent.com/47064939/51798823-90763d80-2210-11e9-846e-fedb04f8c795.jpg)

**Comment by shellixyz** [comment]
Check that both the TX and RX wires from your GPS are connected to the chosen UART. GPS RX -> FC TX and GPS TX -> FC RX. Then all you should need to do is chose GPS in the sensors drop-down list of the ports tab for the chosen UART. Please post a file containing a dump of your configuration

**Comment by Ferris75** [comment]
Hi shellixyz, got it working now on uart 4 and getting a GPS fix quite easily. I now have another issue in that I have bad oscillation when trying to land. Do I have to reduce the pid levels for GPS or normal pitch/roll etc and are there any guides to help with that? Sorry for all the questions first build..

**Comment by laurentopia** [comment]
I'd like to know that as well. 
What GPS is this?

**Comment by Ferris75** [comment]
It is a radiolink se100 I have it mounted on the top plate and I'm getting great results just having some bad oscillation and I think I need to adjust the pid values. Thanks

**Comment by shellixyz** [comment]
@Ferris75 There is no guide for that. What you can do is open your blackbox log with BB viewer to check what is causing the oscillations. The output of all PID controllers are now present in the logs. Attitude PID outpus are `axisP`, `axisI` and `axisD`. Navigation PID outputs are `mcPosAxis*` and `mcVelAxis*`.
