### ISSUE TITLE
OSD page is blank

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#4272]
## Current Behavior
OSD tab is blank, only documentation button appears

## Steps to Reproduce
connect f405-ctr
set it up so all sensors are blue

## Expected behavior
OSD shows up in the OSD page

---
- FC Board name and vendor:
f405-ctr, matek
- INAV version string:
INAV/MATEKF405 2.1.0 Jan 22 2019 / 09:41:21 (7bdd5967e)
GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by laurentopia** [comment]
it's a configurator 2.1.1 bug, solution: revert back to 2.1.0
2.1.0 is also faster, 2.1.1 shoulnd't have been released

**Comment by flyingbandit** [comment]
Same have this on any firmware 2.*

Matek f405 Wing & kakute f4 v2

**Comment by laurentopia** [comment]
It's not a firmware issue, it's a configurator bug. Downgrade to 2.1

**Comment by DzikuVx** [comment]
This is a duplicate of iNavFlight/inav-configurator#659
