### ISSUE TITLE
Betaflight F4 (BFF4) Motor 1 not responding in 2.1 RCs

### ISSUE THREAD

**Issue by trekki1978** [iNavFlight/inav#4295]
Hi,
I'm using BFF4 board and flashed 2.1.0-RC1 and also RC2 and found out that Motor#1 does not respond.
After rolling back to version 2.0.1 all Motors work fine.

Marco

**Comment by shellixyz** [comment]
Please post a config dump

**Comment by trekki1978** [comment]
[INAV_cli_20190202_235955.txt](https://github.com/iNavFlight/inav/files/2824964/INAV_cli_20190202_235955.txt)
I reflashed 2.1.0 RC2 and configured the copter to get this dump file. Still no reaction from motor#1. 
ESC#1 does not show start beeping. ESCs and motors #2, 3 and 4 work fine.

**Comment by shellixyz** [comment]
This should fix your issue, please try and report whether the issue is still there: 
[inav_2.1.0_BETAFLIGHTF4.hex.zip](https://github.com/iNavFlight/inav/files/2923615/inav_2.1.0_BETAFLIGHTF4.hex.zip)

**Comment by trekki1978** [comment]
Hi,
with this hex file all motors work fine.
But due to another issue with the external Baro I still have to use a customized 2.0.1 firmware on my BFF4.

Thanks so far
Marco

**Comment by shellixyz** [comment]
Good to know that at least the motors work now, thank you for the feedback. I see that you already have an issue open for the baro so look there for a follow up on the issue.
