### ISSUE TITLE
FEATURE REQUEST: GEOFENCE

### ISSUE THREAD

**Issue by hugsgui** [iNavFlight/inav#4297]
Hi Inav Devs!

I'm a professional pilote and I'd really like to use my INAV setup in my job instead ardupilot, but to match french law, I need geofence!

So could you please add a mode to lock home distance and altitude with some tunable parameters, and with the ability to activate it with a switch, even a way to trigger RTH by crossing the limits would be fine! 

So much thanks for the current work!

**Comment by giacomo892** [comment]
See  #62 

We can close this
