### ISSUE TITLE
Matek F411 Dshot issue

### ISSUE THREAD

**Issue by 0higgins0** [iNavFlight/inav#4298]
## Current Behavior

Choosing any Dshot profile causes red Settings Validated.  
## Steps to Reproduce

1.Choose any Dshot esc level
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by giacomo892** [comment]
DSHOT is not enabled on Matek F411 yet

**Comment by 0higgins0** [comment]
thank you
