### ISSUE TITLE
Calibrating accelerometer MatekF722

### ISSUE THREAD

**Issue by alessandro-neri** [iNavFlight/inav#4299]
Hello, I have a MatekF722 and I can't calibrate the accelerometer. The steps 1 and 2 succeede but the step 3 doesn't work. Once the step 3 fails it seems that the calibration process crashes and I have to retry doing the calibration of the step 2 and 3, not only step 3. I tried with version 2.0.0 and 2.0.1. 
(I am calibrating the accelerometer relative to the board not relative to the model. I have read the sensor calibration documentation.)
How do I solve the problem?
Thank you.

**Comment by shellixyz** [comment]
I can't reproduce the issue (2.1-RC2 and latest configurator)

**Comment by iturner6168** [comment]
I have two F722s which have had 2.0.0, 2.0.1 and 2.1.0 RC2 running and flying. No accelerometer issues at all so far. Which configurator version are you using? I also did my first cal with just the loose board plugged into USB without issues. Can you explain specifically what you mean by doesn't work?  i.e nothing happens, it locks up? Try doing the steps out of order. Ie do step 1 and then 4 then 3. It doesn;'t matter as long as you complete all 6 steps.

**Comment by DzikuVx** [comment]
I'm also unable to reproduce so I suspect it's either user or hardware error
