### ISSUE TITLE
GPS - Use HDOP and VDOP for navigation, expose in blackbox and MSP

### ISSUE THREAD

**Issue by alvins82** [iNavFlight/inav#43]
Currently cleanflight users the number of satellites as an indicator of 'GPS health'. HDOP is a better measure of this and has been adopted by other FC platforms.

Cleanflight already has HDOP in the GPS struct (https://github.com/cleanflight/cleanflight/blob/27db9ad0fe9a4d8abc05c59db201b8944324eea4/src/main/io/gps.h#L104) but it doesn't seemed to be used or exposed. 

Ticket is two things -
- expose HDOP in MSP so it is able to be shown in the cleanflight configurator
- log HDOP in blackbox logging

**Comment by digitalentity** [comment]
Current NMEA GPS driver does not seem to update HDOP. Tasks to do in this ticket:
- update GPS driver to receive HDOP and VDOP
- expose HDOP to MSP and configurator
- log HDOP to blackbox
- use HDOP/VDOP for position estimation (trust GPS less if position is inaccurate)

**Comment by skaman82** [comment]
@digitalentity Could you expose also some other things to MSP so we can do that?

<img width="153" alt="bildschirmfoto 2015-11-05 um 21 09 55" src="https://cloud.githubusercontent.com/assets/11768024/10980556/e2f458c6-8402-11e5-85de-fe8da366d1af.png">

**Comment by digitalentity** [comment]
@skaman82 How deviations are calculated?

**Comment by skaman82** [comment]
@digitalentity no clue, I thought you knew... ;-)

**Comment by digitalentity** [comment]
Will have to look at TC's code then :-D

**Comment by marksev1** [comment]
https://github.com/multiwii/baseflight/blob/305a2fbff4cac019c382a8f86e020a58a50f8a3e/src/gps.c

Mention of DOP is in Line 44, Line 1276, comments in L 1357, L 1361, L 1487.

Maybe the deviation is calculated in the BF configurator?

**Comment by digitalentity** [comment]
HDOP/VDOP in the form of absolute accuracy values (EPH/EPV) are exposed to blackbox now (5a47299). 
For UBLOX and NAZA GPS these are true accuracy values in cm;
For NMEA and I2C-NAV GPS modules these are HDOP*10 values (base accuracy assumed 1m)

**Comment by bk79** [comment]
Hdop and vdop are almost useless in terms of accuracy since they can be
very high in value but if you don't have enough satellites the accuracy is
less than having low hdop/vdop with lots of satellites
Il 18/gen/2016 08:37 AM, "Konstantin Sharlaimov" notifications@github.com
ha scritto:

**Comment by digitalentity** [comment]
@bk79 
DOP is not accuracy, it's **dilution of precision**, meaning low DOP = high accuracy.
Moreover I'm not using and don't intend to use HDOP/VDOP for navigation. I'm using absolute accuracy (if reported by the module). At the moment only UBLOX and NAZA are reporting true accuracy values.
