### ISSUE TITLE
2.1 RC2 Decoded log files are corrupted at the end

### ISSUE THREAD

**Issue by OlivierC-FR** [iNavFlight/inav#4300]
After being decoded, the last line of the main log contains garbage values, and the last 10% of the line for the GPS are also very wrong.
Below are the 2 CSV exports, and also the source log.
Same result with the iNav decoder, and an old Cleanflight decoder that worked fine with all previous iNav releases.

Blackbox is set as follow :

set blackbox_rate_num = 1
set blackbox_rate_denom = 100
set blackbox_device = SDCARD

Full dump for the FC, a Matek F405-SE : https://www.dropbox.com/s/ka1x6qjkhqgmw9r/DXL.dump.txt?dl=0

![sans titre-2](https://user-images.githubusercontent.com/25566932/52165296-1ad20c00-26ff-11e9-8303-94e46e8adfa2.jpg)

![sans titre-3](https://user-images.githubusercontent.com/25566932/52165297-1c033900-26ff-11e9-84d1-355c418b0211.jpg)

[LOG90002.zip](https://github.com/iNavFlight/inav/files/2824496/LOG90002.zip)

**Comment by OlivierC-FR** [comment]
Decoded files : [logs.zip](https://github.com/iNavFlight/inav/files/2824502/logs.zip)

**Comment by ZeSly** [comment]
The end of the log is corrupted but we have the entire flight. Looking at the end of the GPS trace, we see the landing and we also see when you get the plane and walked with it. It makes me thinking that you unplugged the battery while still armed, hence the corruption of the file. The last line of a valid log don't have the ARM flags. The latest valid lines of your log have the ARM flag.

blackbox_decode decodes the GPS frames even if the main frames are corrupted. I fixed that, check it here : 
https://drive.google.com/open?id=1lq8J2O9vltt7rcJ82CvAEN8AgGom4Nbm

**Comment by stronnag** [comment]
@ZeSly If you have fixed a bug in the blackbox tools, a PR would nice ....

**Comment by OlivierC-FR** [comment]
Good catch, indeed looks like I forgot to disarm. Before I close this report I'll double-check on the bench.
Side note, the blackbox logging on/off control is on the same switch as the arming.

**Comment by giacomo892** [comment]
It is not suggested to have other modes on the arming switch beside the ARM one

**Comment by OlivierC-FR** [comment]
Closing, plane was unpowered while stil armed
