### ISSUE TITLE
v2.0.1 NMEA protocol doesnt work anymore

### ISSUE THREAD

**Issue by rkolaczek** [iNavFlight/inav#4301]
## Current Behavior
Inav v2.0.1 looks like nmea doesnt work anymore, got "gps failure" in 2 planes (kfc32f3 with drotek m8n and matekf405wing with another drotek m8n)

After change to ublox protocol it works as expected in both planes

PS: It worked well with Inav v2.0.0 (possible commit that break nmea protocol: 633bbda2ae45cca021de669673a3bfe67dcae0b8)

## Steps to Reproduce
1. flash 2.0.1, setup gps with nmea protocol
2. power on plane, wait till gps led will start blinking and shows satelites in osd
3. notice message "gps failure" in osd
4. hardware health also blinks in inav configurator

## Expected behavior
Please make nmea work again :)

## Suggested solution(s)
fix commit that most likely introduced an error in commit hash: 633bbda2ae45cca021de669673a3bfe67dcae0b8

## Additional context
Dragonlink users uses nmea protocol to send gps coordinates to the ground in the most efficient way

Confirmed on 2 setups:
1. kfc32f3 board with drotek m8n gps (worked well with inav 2.0.0)
2. matek f405wing with another drotek m8n gps (also worked well with inav 2.0.0)

**Comment by digitalentity** [comment]
Please check the 2.1-RC*

**Comment by digitalentity** [comment]
Verified that NMEA GPS work on `development` branch
