### ISSUE TITLE
Scrolling side bars

### ISSUE THREAD

**Issue by oldrootbeer** [iNavFlight/inav#4303]
Hi.
Is it just me, or do the scrolling side bars scroll the wrong way when ascending / descending? Shouldn't they scroll down with ascension and vice versa?

**Comment by teckel12** [comment]
@oldrootbeer You mean OSD variometer? Up is up and down is down. It's just you if you think up should show down and vice versa.

**Comment by oldrootbeer** [comment]
No. I mean the side bars. Not the Vario. I mean these:
![sidebars](https://user-images.githubusercontent.com/38378784/52176081-bc139d80-27a5-11e9-97b6-201f7b736185.JPG)

**Comment by DzikuVx** [comment]
This is artificial horizon and it should follow the real horizon. If you nose up, AHI goes down. It's fine as it is right now

**Comment by oldrootbeer** [comment]
Well I thought I'd try anyway. If the side bars had numbers, eg 10m, 20m etc, to indicate height, they would scroll the other way... Close if you wish.
![sidebars](https://user-images.githubusercontent.com/38378784/52176200-3690ed00-27a7-11e9-9ffe-fa4bbd252d07.JPG)

**Comment by shellixyz** [comment]
Indeed I think it would make more sense if the sidebar moved the other way for altitude

**Comment by teckel12** [comment]
@shellixyz I'll have to take a look, I assumed it moved the same way a glass cockpit attitude display worked.

**Comment by oldrootbeer** [comment]
Only if it's do'able, perhaps have the altitude in 10's of meters on the side like the above pic. Also angle the side bars wrt roll. Not sure if that is easy to code. But would look spot on.

**Comment by teckel12** [comment]
@oldrootbeer The problem with changes like you're suggesting is that the OSD is all character based and you can't have characters on top of each other.  So, tilting the side bars would 1) look ugly 2) lose the visibility of a scrolling sidebar 3) probably overwrite other characters.

Trying to do a glass cockpit display with just characters is challenging, and a few sacrifices need to be made.  While your suggestion is sound, it really should be reserved for a future pixel-based OSD (which oddly enough INAV started working on just yesterday).

I'll have to check the scrolling side bars on the OSD.  But, altitude should scroll down when going up and the speed should scroll down when going faster.  This is the traditional direction for glass cockpit displays.  

Example from INAV Lua Telemetry:

![inavhorus](https://user-images.githubusercontent.com/2592128/52508964-6899b900-2bc4-11e9-959f-949ae0c2c66d.png)

**Comment by oldrootbeer** [comment]
Understood. Should look great if you pull it off.

**Comment by teckel12** [comment]
@oldrootbeer I'll look into adding small altitude/speed numbers next to the side bars. But I think it will make it too wide, and lots of pilots put the altilutude/speed/vertical speed to the left or right side of the side bars. But, maybe with the small numbers next to the side bars, the actual altutude/speed won't be as needed? I'll look at the code/screen layout.

**Comment by shellixyz** [comment]
@teckel12 Any news about this ? Reversing the direction of the altitude side bar would already be a nice improvement.

**Comment by teckel12** [comment]
@shellixyz I'll need to check, I thought the dots crawled down when you gained altitude.
