### ISSUE TITLE
AnyFC F7 motor output problems when LED strip turned on 2.1, No Servo Output 2.0 onwards

### ISSUE THREAD

**Issue by ryanort** [iNavFlight/inav#4309]
Motor output mapping for multirotors based on https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20AnyFC%20F7.md changed on FW 2.1 RC1 and RC2, only motor 1 and 3 are working when using these FWs.  All motor output working on FW 2.0.1.

Servo output for multirotors based on https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20AnyFC%20F7.md not working starting FW 2.0.  Tested to be still working on FW 1.8 & 1.9.

**Comment by ryanort** [comment]
tried it again on 2.1.0 RC2 and RC3 and found out that motor output mapping is ok but not if LED strip support is turned on

**Comment by ryanort** [comment]
still no go on 2.1 final release.

**Comment by DzikuVx** [comment]
Servo output will be fixed in #4494
PLease do not use LED strips with this board currently

**Comment by ryanort** [comment]
Excellent. Thanks!

**Comment by DzikuVx** [comment]
We will not fix the LED problem as the boards is not popular and outdated

**Comment by ryanort** [comment]
That's unfortunate.  I was looking forward to getting the led working as well with the servo gimbal.

**Comment by 2T-GT** [comment]
I got the same issue, enable the LED strip and motor 4 and 2 turned off. I thought I was being cleaver by adding the LEDs , but it tuned the quad into a lawnmower when I throttled up with only 2 motors :-). 
I was hoping the F7 boards were new enough that lack of support was not going to be a issue when I built this machine 2 years ago. 
would the Matek F722-SE be a supported replacement board?
Got to give the dev team credit, I put the toolchain on my machine and tried move ports, I'm well in over my head with this and my level of understanding C.

**Comment by golddragon007** [comment]
@DzikuVx Because it's old hardware it doesn't mean it is a bad too and shouldn't be supported. I selected in the past this controller because it had the possibility to use it with octocopter and LEDs. But please then tell another controller which is supported, it's F7 or better and I can put tons of sensors on it like on this and can be used with octocopter too.
