### ISSUE TITLE
Flashing problem Matek F405-STD

### ISSUE THREAD

**Issue by devdeven** [iNavFlight/inav#4310]
Hello

I am unable to flash the Matek F405-STD with Configurator 2.1.1. It downloads the firmware online when I go to press Flash Firmware I get "USB Device successfully closed" 

I am using a MacBook Pro running OSX 10.13.6

Am I doing something wrong? I can flash different version of Betaflight on the FC fine using the BF configurator.

**Comment by devdeven** [comment]
Just tested flashing with configurator 2.0.0. 
Flashing successful

**Comment by teckel12** [comment]
@devdeven I'd open an issue in the  configurator repo.

**Comment by devdeven** [comment]
Opened in the configurator repo :)
