### ISSUE TITLE
 connect to the KAKUTE F7 with a Jtag and debug the code step by step?

### ISSUE THREAD

**Issue by mandelyoni** [iNavFlight/inav#4311]
Hi, was anyone able to connect to the KAKUTE F7 with a Jtag and debug the code step by step?

**Comment by shellixyz** [comment]
I never tried. Do you really need it ? For most cases there are easier ways to do debugging with iNav:

- The debug array (8 * int32) you can watch from the sensors tab in the configurator
- DEBUG_TRACE calls, it is like `printf` e.g `DEBUG_TRACE_SYNC("message %d", val)` and connect to the board with [msp-tool](https://github.com/fiam/msp-tool) to display the debug messages

**Comment by mandelyoni** [comment]
Thank you very much !
