### ISSUE TITLE
Inav on Matek F411 wing

### ISSUE THREAD

**Issue by rcabuser** [iNavFlight/inav#4312]
I'm not getting correct Rssi readings, i only get 80% as max.  I'm running a Matek F411 wing on Inav 2.1

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by shellixyz** [comment]
#3919

**Comment by rcabuser** [comment]
Why did you close it? i'm not getting any help by #3919

**Comment by shellixyz** [comment]
Because of the non-descriptive title, empty content and empty template left in place. No mention of the RX, target used, way of getting RSSI in the FC and no configuration. We can't help
