### ISSUE TITLE
2.1.0 RC1 Matek F411 Wing Configurator Soft Serial Port Ambiguity

### ISSUE THREAD

**Issue by juichi** [iNavFlight/inav#4314]
## Current Behavior
After Flashing the Matek F411 Wing with the 2 soft serial target, the configurator lists the following:

USB VCP
UART1
UART2
SOFTSERIAL2
UART1

It is unclear which selection refers to the softserial1 port.  I have attempted several configurations using one of the duplicated UART1 ports and could not get 2 softserial ports to function.

## Steps to Reproduce

1.  Flash Matek 411-Wing with 2.1.0 RC1 2 softserial target
2.  Connect the board to the configurator

## Expected behavior

The configurator should present the following for the serial ports:

USB VCP
UART1
UART2
SOFTSERIAL1
SOFTSERIAL2

**Comment by shellixyz** [comment]
Fixed. Thank you for reporting the issue. 2.1-RC3 will work as expected. In the meantime please use this build: [inav_2.1.0_MATEKF411_SFTSRL2.hex.zip](https://github.com/iNavFlight/inav/files/2829178/inav_2.1.0_MATEKF411_SFTSRL2.hex.zip)
