### ISSUE TITLE
what is the meaning from EXPO

### ISSUE THREAD

**Issue by wetskindiver** [iNavFlight/inav#4316]
I know EXPO from my Futaba RC  transmitter If I adjusted  -30 % than I  reduced the rudders movement around the middle of the stick otherwise  +30%  would enlarge them
In INAV is in the  receiver setting the default value  0.70, but what exactly does that mean, is that corresponds to the above -30% or what ?? and is100 no EXPO ??

Unfortunately, the picture is not always updated, that would help

**Comment by shellixyz** [comment]
It is like on your radio but only for reducing movements around the middle of the stick. 30 is the same thing as -30 on your radio. You can see the effect of the expo values on the graphs in the receiver tab:
![image](https://user-images.githubusercontent.com/4030264/52230247-3122c800-28b7-11e9-9e25-05e80517eafa.png)

**Comment by wetskindiver** [comment]
THX for your answer, but is not 100% clear for me Means 0,70 -70% EXPO ??
And what is the difference from RC EXPO to Manual RC EXPO I was thinking that EXPO only works in MANUAL Mode, not in HOR or ANGLE

**Comment by shellixyz** [comment]
Yes 0.70 = -70% expo. Manual RC expo is only applied in manual mode. RC expo is applied in all the other modes: ACRO/RATE, ANGLE, HORIZON, ...

**Comment by wetskindiver** [comment]
Ok now I have understood it thanks for explanation
