### ISSUE TITLE
Long term altitude drift in 2.1.0 RC2

### ISSUE THREAD

**Issue by iturner6168** [iNavFlight/inav#4328]
Noted random altitude drift when in PosHold occasionally changing by 5 meters in 15 meters before recovering. Nothing changed in the conditions which were flat calm.  I had noticed when watching the baro trace in the sensors tab that the baro seemed to be much noisier in 2.1.0 than on the same quad on 2.0.0.  I set out to do a more formal test outlined below.

**Comment by iturner6168** [comment]
To observe the altitude drift more systematically I did a long term PosHold test with Blackbox enabled as follows:  440mm quad. Matek F722, AUW 1280grams. 5200 mAh 4S battery. 2.1.0 RC2. Throttle hover 1475.
Conditions were perfect with zero wind. I entered PosHold at the previously measured throttle level for hover, (from prior Blackbox run) 44% and noted that the output throttle level as displayed on the OSD was approximately equal. Altitude was noted as 20 meters. Performed 360 degree very slow pans and some medium speed traverses. After approximately 11 minutes of flying, the altitude as displayed on the OSD dropped smoothly to 15 meters. At 12 mins it recovered to 19 meters until 13:46 minutes it began to climb slowly to 32 meters then more quickly it climbed to 41 meters over the next few minutes.  . The manual throttle was not touched and remained close to the output throttle value as displayed by the OSD and supported by the Blackbox data. Another anecdotal comment is that the baro/altitude behavior on the bench running 2.0.0 on the same quad seems to be more repeatable than on 2.1.0 when raising and lowering the quad from bench to floor to head height. 
I have the blackbox file but it is 1:1 and 90MB so cannot attach here but it is totally boring and supports the information I have outlined here. 
IT Feb 7th

**Comment by giacomo892** [comment]
Please load the blackbox somewhere else and be kind to mark down the interesting points (make a list here) so we can take a look, thanks!

**Comment by iturner6168** [comment]
Here is a link to the file. 
https://1drv.ms/t/s!AoicfdMhmJABj4tyUqEph9gixVetQQ
Key times in the BB file are:
Stable altitude of 20 meters after engaging PosHold for the first 10 minutes then...
11:19 mins start of first un expected change of altitude from 20m - (change was showing in the OSD feed)
11:35 mins drop from 20 to 15 meters
12:50 mins at 16 meters
13:46 mins at 32 meters
15.39 mins at 41 meters
20:00 mins at 25 meters prior to disabling PosHold

**Comment by giacomo892** [comment]
When the quad climbs at around 13 minutes you are throttling it up :)

During other moments the altitude gently (perhaps with some lag) what baro reports. So check if your baro works and it is well shielded.

**Comment by iturner6168** [comment]
I don't see that at all. Looking at rcCommand(throttle) using Blackbox V3.02, rcCommand(throttle) only  varies from 45% by 1% as I flew around for the 13 minutes prior to the climb, and only goes as high as 47% at the end of the climb from 20m to 31.8m. If you look at the log starting at 13.32 mins, (altitude = 20.1m) the throttle stays at 45% until 13.59 mins when the altitude = 28m. At 13.59 there is a small increase of throttle to 47% for a brief period but the quad had already climbed 8m before that.  I suspect that was when I first reacted to the altitude change and touched the throttle stick.  I have: pos_hold_deadband = 40 and alt_hold_deadband = 40. Surely the throttle deadband should take care of such small variations as 1% anyway? Should I set the deadband value higher?  Can you give me an idea of the scale of the effect of alt_hold_deadband?
 I have flown this quad using 2.0.0 since last September without any symptoms of a baro issue. I have it well covered with foam and it is 10cm away from the nearest prop tip.

**Comment by iturner6168** [comment]
I have resolved what happened. I was in PosHold AND flying around for over 15 minutes which required me to maneuver and still maintain a value of throttle that remained within the Althold deadband. Since we don't use centering throttles I drifted slightly out of the deadband on a couple of occasions. This problem should be closed.

**Comment by digitalentity** [comment]
@iturner6168 thanks for letting us know
