### ISSUE TITLE
Impossible to activate DSHOT

### ISSUE THREAD

**Issue by BariMc** [iNavFlight/inav#4344]
Hello,
I have a Kakute F7 and can not activate the DSHOT with version Inav 2.1 RC3, the same for the RC1 and RC2. When I try to activate it and I save and restart, the DSHOT is not taken into account and it restores the default esc settings. Do you have a solution ?
Thank you

**Comment by DzikuVx** [comment]
Release notes states that:

DSHOT is enabled on following targets:

AIRBOTF4
ASGARD32F4
ASGARD32F7
COLIBRI_RACE
FIREWORKSV2
FOXEERF405
FOXEERF722DUAL
MATEKF405 (CTR, STD, not WING)
MATEKF722
MATEKF722SE
OMNIBUSF4
OMNIBUSF7NXT
REVO

**Comment by BariMc** [comment]
Thank you for this quick response, is this definitive or will be good in version 2.1 stable?

THX

**Comment by DzikuVx** [comment]
Probably none of te devs have tis board to test if it does not break anything
