### ISSUE TITLE
FC KAKUTE F7 compatible

### ISSUE THREAD

**Issue by BariMc** [iNavFlight/inav#4345]
Hello,

in the version Inav 2.1 stable kakute F7 will be compatible with the DSHOT?

Thank you

**Comment by teckel12** [comment]
@BariMc As stated in #4344 probably not as none of the devs have this board for testing. If you'd like to create a custom build and test, that may help. But creating multiple issues on the same answered question won't help.

**Comment by BariMc** [comment]
Ok thank you and sorry
