### ISSUE TITLE
"Formation Helper" mode

### ISSUE THREAD

**Issue by SimplyKot** [iNavFlight/inav#4353]
## Current Behavior
There is no any "Formation Helper" (FH) mode.

## Desired Behavior
Display on the OSD screen of the approximate position of other UAVs from the formation.

## Suggested Solution
The UAV controllers exchange packets containing a unique identifier, GPS coordinates and GPS height via UART using LORA (if only two UAV are in formation) or mesh network (for tree or more UAV in formainon) 
On the OSD, the approximate direction to the specified point in space is displayed.

## Who does this impact? Who is this for?
All users flying formation or together

**Comment by Pairan** [comment]
Have a look ...
#3626 
#4112

**Comment by SimplyKot** [comment]
Exactly what I need!
Thank you.
