### ISSUE TITLE
HAKRC Omnibus F4 V3 receiver and gps problem

### ISSUE THREAD

**Issue by Mrowkarz** [iNavFlight/inav#4356]
Hi!
I bought this FC and it came with Inav 1.9.1 (probably preconfigured) but as it came I updated it to latest Inav and now I have problem. I bought it on Banggood, where you can see how it should be wired as it comes (with preinstaled Inav) https://www.banggood.com/HAKRC-Omnibus-F4-V3-Flight-Controller-OSD-w-5V-3A-Power-Distribution-Board-for-RC-Drone-FPV-Racing-p-1284817.html?rmmds=myorder&cur_warehouse=CN
But now this wiring is not working (only servos works). When I connect BN-220 GPS as it is shown on images the GPS is powered, bud Inav can't detect in on any UART, the same with receiver (Fr Sky R9MM). I was searching in google, but I couldn't find the answer. 
Could you help me please?

**Comment by teckel12** [comment]
@Mrowkarz Did you save the original dump? What was the target specified at the top of the dump?
