### ISSUE TITLE
can not calibrate accelerometer Omnibus F4Pro in FW 2.1.0

### ISSUE THREAD

**Issue by SonAndDadFPV** [iNavFlight/inav#4359]
## Current Behavior
Flight controler works perfect on FW 2.0.1 (airplane mode, no compass)
When I update (via DFU) to 2.1.0 (Omnibus F4Pro), I can not calibrate accelorometer. It only does first step (FC horizontal) but when I hold the fc in the other directions and push calibrate button, I only hear a beep but the pictures do not light up and accelerometer does not calibrate. When I reboot the 2.0.1 firmware, all is back in order  

## Steps to Reproduce

1.update to FW 2.1.0
2.try to calibrate accelerometer
3.
4.

## Expected behavior
I need all 6 steps of calibration to light up, only first step is lit

## Suggested solution(s)
need calibration

## Additional context

---

# version
# INAV/OMNIBUSF4PRO 2.1.0 Feb 10 2019 / 16:27:49 (0d3d0ff30)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

- FC Board name and vendor: Omnibus F4 Pro (SD) from Banggood
- INAV version string:

**Comment by ghost** [comment]
I did a Re-flash of my Airbot Omnibus F4Pro, with 2.1 RC3; to confirm your calibration issue.

I also noticed that the _Inverted horizontal calibration_ (step 2) was much more difficult to get right.

I found it easier to do Step 1 then Steps 3, 4, 5, 6. And go back and do Step 2 last.  But it did require VERY precise inverted horizontal alignment of the FC board, before it would complete step 2.

I went back and did the same with 2.1 RC2. And it did not need anywhere near the same precision horizontal alignment of the board in step 2.
