### ISSUE TITLE
İNAV SERVO MİXER- HELP

### ISSUE THREAD

**Issue by xmrtg70** [iNavFlight/inav#4362]
hello. I have a DYS F4 PRO V2 control card. S5 and S6 have connected to servo SG90 but can not control. how do I make the settings. How should servo mixer settings be? kumandadan atamak istediğim kanal 10.
![mixer](https://user-images.githubusercontent.com/47568406/52725201-c7df3b00-2fc1-11e9-81ce-89220be00222.png)
![mixer 2](https://user-images.githubusercontent.com/47568406/52725211-cca3ef00-2fc1-11e9-9937-b544cdb96b38.png)
![mixer 3](https://user-images.githubusercontent.com/47568406/52725222-d0377600-2fc1-11e9-82b7-7e94eed060ed.png)

**Comment by DzikuVx** [comment]
https://www.youtube.com/watch?v=0cLFu-5syi0

**Comment by xmrtg70** [comment]
these settings are not available for the quadcopter. I could not
