### ISSUE TITLE
Resouce Remapping?

### ISSUE THREAD

**Issue by anil1112** [iNavFlight/inav#4365]
Hello, I need to change my motor resources.
Because some pin is broken, and I need to connect other pin.
my motor 2 pin : B01 and is broken. 
I want to connect this motor to A01. 
How can I do this?

![inav remap](https://user-images.githubusercontent.com/47625882/52774151-af1c6700-304d-11e9-8071-c5f8e8c1577e.jpg)

**Comment by DzikuVx** [comment]
No resource remapping see #1145

**Comment by anil1112** [comment]
> No resource remapping see #1145

why is this not possible with inav? I can change resource remapping with betaflight.

**Comment by flythebluesky** [comment]
I just built a 7" specifically for INAV, and now I find out it is not possible to remap motors? So your FC and ESC's must always face forward???

**Comment by digitalentity** [comment]
@flythebluesky look into board alignment and motor mixer. You can place your board in any way you want and you can configure your motor mixer to match the ESC connections.

**Comment by digitalentity** [comment]
I'm locking down this issue to avoid noise. Community support is available via https://t.me/INAVFlight
