### ISSUE TITLE
Option to switch off OSD stats on disarm

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#4375]
## Current Behavior
Stats appear on disarm

## Desired Behavior
No stats option

## Suggested Solution
Add a CLI option to turn this off

## Who does this impact? Who is this for?
When tuning a quad these get in the way because flipping a switch on the TX don't remove the stats so you have to wiggle the stick to get them off the view

## Additional context
CLI option would be good, I don't use stats, that's what OSD options are for, alternatively generalize the turn off of stats display to all TX switches, not just sticks.

**Comment by shellixyz** [comment]
Just push the pitch stick to go back to the active layout. This doesn't need a new setting.
