### ISSUE TITLE
VTX don't work with Matek F405 and iNAV 2.1 RC3

### ISSUE THREAD

**Issue by HenriQBR** [iNavFlight/inav#4378]
Friends ... does anyone give me advice?
I'm using an FC Matek F405 with integrated OSD. But I can not get the video streamed to the VTX. If I connect the camera directly in vtx works perfectly, but if I turn on the controller to have the OSD I do not have the video.
Do I have to enable something on iNAV?

**Comment by DzikuVx** [comment]
You might want to verify if both Camera and FC with OSD are configured for the same system: PAL/NTSC. If both are the same it might be either faulty connection or damaged hardware. There are no other special options in INAV to set it up
