### ISSUE TITLE
Motors start to spin even when 'don't start to spin when armed' toggle is activated

### ISSUE THREAD

**Issue by viktortrass** [iNavFlight/inav#4399]
Hello I have a problem with iNAV, I have flashed last version to Matek F405 STD and all seems works great except when I arm the drone motors start to spin even when toggle of 'don't start motos when arm' is activated, why?
Another problem is when I throttle up it seems to speed up but when I throttle down is still accelerated. thanks and sorry for my bad english

**Comment by DzikuVx** [comment]
Airmode overrides Motor_stop on multirotors
