### ISSUE TITLE
Enabling POSHOLD winthout ALTHOLD causes altitude (throttle) drop.

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#44]
Opened per this comment: https://github.com/digitalentity/cleanflight/issues/1#issuecomment-146441853
@bk79, can you please clarify if you activate ALTHOLD+POSHOLD or only POSHOLD mode?

**Comment by bk79** [comment]
@digitalentity PH only, if I enable AH it will work or if I enable at+PH it works, btw if I disable AH during PH but with ANGLE enabled Altitude is kept

**Comment by digitalentity** [comment]
Closed via 21f142cba7205921dda960ae7ac99af5cff11f99
