### ISSUE TITLE
Matek F722-SE fails during Run-time calibration with analog rssi input enabled

### ISSUE THREAD

**Issue by ericogr** [iNavFlight/inav#4406]
## Current Behavior

Matek F722-SE fails during Run-time calibration.

## Steps to Reproduce

1. Reset settings (run-time calibration works fine)
2. Enable analog rssi input (run-time calibration does not work anymore)

## Expected behavior
run-time calibration working

## Additional context
You can setup, calibrate model with radio transmitter on but it doesn't work anymore.
Aparently values read from rssi are ok.
[PasteBin](https://pastebin.com/rgGtyQ6v)

- INAV/MATEKF722SE 2.1.0 Feb 10 2019 / 16:42:36 (0d3d0ff30)
- GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by digitalentity** [comment]
Check the latest release please

**Comment by ericogr** [comment]
updated to latest version:

- INAV/MATEKF722SE 2.1.0 Feb 25 2019 / 17:01:07 (65b0ec142)
- GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**I have the same issue :(**

# status (CLI)
System Uptime: 206 seconds
Current Time: 2019-02-26T21:00:46.342+00:00
Voltage: 11.27V (3S battery - OK)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883, PITOT=ADC
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
SD card: Startup failed
Stack size: 6144, Stack address: 0x20010000, Heap available: 1440
I2C Errors: 45, config size: 4693, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = ADC 3
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = ADC 4, used = ADC 4
System load: 4, cycle time: 1003, PID rate: 997, RX rate: 55, System rate: 9
**Arming disabled flags: CAL CLI**

**Comment by ericogr** [comment]
[SOLVED]
I found my fault ... in the default configuration of sensors, "pitot tube" comes configured for ADC. I didn't have this sensor and had not noticed it. I set it to none and the calibration was successful.
