### ISSUE TITLE
Inav 2.0.1 gone arrow dissapers 

### ISSUE THREAD

**Issue by skinnyguyfpv** [iNavFlight/inav#4412]
I have recently installed a mate f405-std and bn180 GPS everything is fine apart from my home arrow blinking then when I arm I'm left with a small line that blinks so can't tell were home is I've been ripping my hair out, I have a 3d fix and 15-16 sats

**Comment by krzysztofmatula** [comment]
Did you upload the current OSD font?

**Comment by skinnyguyfpv** [comment]
Yeah Mate, I've installed 3 planes with inav now and have been very successful but this one for some reason is rather hard, I'm thinking it might be a bad gps the reason I say that is it says it has a 3d fix but in inav configurator there is no map, i have played arround with gps settings and diffrent baud rates etc what are your thoughts?

**Comment by skinnyguyfpv** [comment]
The arrow Looks the same as thread #2186 but my arrow is on its own in the screen so no overlapping

**Comment by shellixyz** [comment]
Please make a short video of the issue if possible

**Comment by shellixyz** [comment]
Also you should now upgrade to 2.1.0. Issues in previous versions won't be fixed.

**Comment by jm-wijnholds** [comment]
I have exactly the same problem. When disarmed the home arrow is blinking, when arming it changes to a blinking line. 

I also noticed that I can’t enable RTH and launch. I have enough satellites. 

Some ideas what the problem might be?

**Comment by teckel12** [comment]
@jm-wijnholds Number of satellites does not mean you have a GPS lock. You can have 10 satellites but not a lock. The "big myth" is that # sats = GPS lock, which is not at all true.

Try turning on extra arming safety and wait for a GPS lock and then see what happens.

**Comment by ucakar** [comment]
Hello,

I have same problem, is there any solution?

Just after arm the flashing go home arrow turns into blinking line and when I switch to RTH mode nothing happens??

Thanks,

Andrej

**Comment by wizard220s** [comment]
I have the same problem with two different F4  ( Matek 405 STD and Omnibus F4 V3) the arrow and the number of  sats has dissapear and RTH do not workn althought all is in blue ( Mag GPS Baro Etc)

**Comment by wizard220s** [comment]
I forgot to comment that it happens with INAV 2.5 also

**Comment by wizard220s** [comment]
The GPS is BN 880 
I have reviewed all cli without success.
Please help!
