### ISSUE TITLE
?Wing - Is it "safe" to tune PIDs in-flight?

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#4418]
Okay, I know this maybe sounds very strange.... but... 

Autotune is a good thing to get starting values but the issue here is, that these sharp maneuvers need higher speeds and if INAV tunes for these high speed (in my case about 60-70km/h), it will be still very sluggish when flying slower (cruise is 40-50 on my AR wing). When flying fast it is rock solid.

So. I know there was a warning somewhere in the configurator for chaning PID/PIFF values in flight via wireless connection. But what about OSD? 

My Idea is to configure a long mission with a lot of waypoints and make sure the plane flies a zig-zag course. And Meanwhile I would have time enough to go into the OSD and change the PID values to see how the plane behaves. Does this work? are the values applied in realtime or only on save? I already know that I can stick save in flight when using autotune (and at a very save height) but it will cut the throttle for a few seconds. 

I know there is always a risk I need to be aware of, just asking if this is possible anyway ;)

**Comment by giacomo892** [comment]
Hello. This is not the right place to ask such questions. Please use Facebook or Telegram group.
Anyway tuning in flight with in-flight adjustments is safe until you know what you are doing.
