### ISSUE TITLE
GPS not working when flight battery is plugged in

### ISSUE THREAD

**Issue by tdx0601** [iNavFlight/inav#4428]
I have my gps (bn880) connected to uart 1 on my omnibus f4 pro. This setup worked fine for a couple minutes. But then when the battery is plugged into the 4 in 1 esc the GPS icon turned red. I have also enabled GPS passthrough to test the GPS in ublox ucenter. When the battery is plugged in all the data stopped updating.

**Comment by shellixyz** [comment]
Seems clearly to be an hardware issue. Please use the Telegram's iNav channel, RC Groups forums or Facebook's iNav groups for such questions.
