### ISSUE TITLE
UK Units

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#4443]
In UK aviation, 

height is measured in feet, 
distance in metres/km, and 
UK speed is generally measured in mph.  

I know, it is weird - but that is how it is.   I raised an issue a couple of years back which got looked at and closed.  But in the latest versions of iNav configurator I can not see a way of setting that set of units.
In any case perhaps the best of way of tackling this is to allow the user to set whatever units they wish for each metric.

Perhaps add a fourth option to the dropdown which enables specific setting of the units for each metric ?
 
See
https://github.com/iNavFlight/inav/issues/1853

thanks.

**Comment by shellixyz** [comment]
You can select "UK units" in the OSD tab. The altitude uses metric units though. It will be fixed in the next release.

![image](https://user-images.githubusercontent.com/4030264/53699557-e62e9e80-3de9-11e9-9723-f1dcefda377c.png)

**Comment by MartinHugh** [comment]
shellixyz. Many thanks.

**Comment by wx4cb** [comment]
just as an aside - those of us old enough still use feet/miles for distance :D even in aviation :D none of this european stuff :D

**Comment by shellixyz** [comment]
Fix merged in the development branch, closing
