### ISSUE TITLE
In AH mode the throttle shouldn't be increased to compensate for altitude loss until the MR is upright

### ISSUE THREAD

**Issue by shellixyz** [iNavFlight/inav#4450]
## Current Behavior

Enabling AH while the MR is upside down will make the motors spin at full speed making it drop altitude very quickly until it is upright again

## Suggested Solution

Don't increase the throttle to compensate for altitude loss until the MR is upright (roll < 90°)

**Comment by giacomo892** [comment]
See #1793

**Comment by shellixyz** [comment]
Good catch
