### ISSUE TITLE
Cannot save waypoints to EEPROM on Matek F405 Wing FC

### ISSUE THREAD

**Issue by PaulWieland** [iNavFlight/inav#4456]
## Current Behavior
When creating waypoints in the iNav GUI, they do not appear to save. Using Matek F405 Wing, iNav 2.1.0 & GUI 2.1.4.

## Steps to Reproduce

1. Create waypoints in the mission planner
2. Click save to EEPROM

## Expected behavior
When loading from EEPROM no waypoints are displayed

- FC Board name and vendor: Matek F405 Wing
- INAV version string: Version 2.1.0

**Comment by shellixyz** [comment]
I can't reproduce the issue, working fine here configurator version 2.1.4 and FW 2.1.0. Remember that you have to save the WPs to FC before saving them to EEPROM.
