### ISSUE TITLE
Auto Trim - possible to do this on the ground

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#4460]
As I understand it, AutoTrim effectively tells the FC on an aircraft which has been trimmed out in manual mode, what the zero stick channel values are.

Whilst this can be a benefit to allow this in the air (if retrimming is required whilst flying, making resetting FC zero stick values necessary), it would be nice to allow this on the ground.

I note that some stabilsers (like the A3) actually automate this and read stick values when powering up, and the Vector allows trim incorporation at any time, in the air or on the ground.

Given a situation that an aircraft is trimmed out for manual flight on the ground, is it not possible to allow autotrim settings to be made on the ground ?

Thanks.

**Comment by DzikuVx** [comment]
No. Autotrim determines zero servo positions and it can be done only in the air while flyinng. Radio should be trimmed to always give 1500us when sticks are centered

**Comment by MartinHugh** [comment]
thanks.
