### ISSUE TITLE
MSP v2 python library?

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#4465]
not strictly an "issue"

but does anyone know where I may be able to procure a python library for MSP v2 ?

the only one's i've found only support MSP V1.

I'm trying to write some code to talk to the flight controller and would prefer NOT to use mavlink :D

maybe @stronnag might be able to help.

**Comment by giacomo892** [comment]
Please use telegram, facebook or rcgroups for such requests. You can find all the references in the manual.

Closing

**Comment by wx4cb** [comment]
@giacomo892 there is nowhere in the wiki other than these two pages (which describe the frames and inave specific changes) that describe the MSP V2 protocol.

that's the issue. There is also nothing that i can find in the "developer info" pages either

https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages
https://github.com/iNavFlight/inav/wiki/INAV-MSP-frames-changelog

**Comment by giacomo892** [comment]
In open source projects there is a big rule that stands above everything else: 
_the source code is the best manual you can get_

**Comment by fiam** [comment]
@wx4cb 
https://github.com/iNavFlight/inav/wiki/MSP-V2

**Comment by wx4cb** [comment]
@fiam  thank you. that's all i was asking for :D

**Comment by annoyinganime** [comment]
@wx4cb did you manage to make it work? I'm also trying to implement one, but for some reason it doesn't work

**Comment by ricardodeazambuja** [comment]
@wx4cb and @annoyinganime, I developed a Python library that supports MSP V2 so you may want to have a look:
https://github.com/thecognifly/YAMSPy
