### ISSUE TITLE
Bypass sat count or turn off GPS altogether if desired

### ISSUE THREAD

**Issue by rcjarvis** [iNavFlight/inav#4489]
## Current Behavior
<If flying indoors on some occasions or if gps is not required for a safe flight. GPs count can keep us from enjoying a quick flight. Setting gps count to 1 or 0 would render the gps use unsafe.
## Desired Behavior
Toggling a switch to either bypass sat count or bypass the gps altogether ( bypassing gps would be best)

## Suggested Solution
Making it possible to take off when no sat are available but keeping the gps option when possible/needed

## Who does this impact? Who is this for?
All users using GPS navigation on small quads or planes who enjoyoccasionnal flying indoors
## Additional context
When problems occur, for better troubleshooting etc...

**Comment by teckel12** [comment]
@rcjarvis I actually kinda like this. But I would allow the extra arming safety to be turned on or off via a switch. That would resolve the GPS lock as you suggest, but also the angle etc. Basically, flip a switch, arm when you want overriding extra arming safety. I'd use this often.

**Comment by rcjarvis** [comment]
Thanks for considering, and thanks Tim for answering my other post... These stick functions are awesome !

**Comment by malckris** [comment]
I test/fly/play in my barn when the weather is not cooperating (usually too much wind)... I just change  "nav_extra_arming_safety" for indoor flight... for convenience I put wifi card on the copter so a change is real quick via my phone... controlling this setting with a switch as teckel12 says would be great...

**Comment by DzikuVx** [comment]
will be done as part of #4474

**Comment by rcjarvis** [comment]
Thanks for considering Pawel !



Le 13 avril 2019 à 03:57, Paweł Spychalski <notifications@github.com> a écrit :



will be done as part of #4474
