### ISSUE TITLE
DHT22 humidity/temp sensor support

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#4492]
Having humidity in the OSD can be helpful when flying near the dew point. 
DHT-22 protocol is relatively simple and can be implemented with a Timer or EXTI.

**Comment by Jetrell** [comment]
It would give us an idea when the camera lens is about to fog up.

**Comment by Tygrys-1** [comment]
Can't they be directly connected to I2C?

**Comment by shellixyz** [comment]
@Tygrys-1 They can't. It is using a special 1-wire protocol.
