### ISSUE TITLE
inav CRUISE Mode selection

### ISSUE THREAD

**Issue by steviegeek** [iNavFlight/inav#4495]
@digitalentity
Unless I'm mistaken, often these days :)  Cruise mode can only be activated via the configurator.
Is it / Would it, be possible to have this on a channel/switch ?
Then when enabling Braking mode, Cruise mode can also be enabled.
I'm thinking of MR's
Thanks
Steve

**Comment by DzikuVx** [comment]
Not yet, but mechanism that allows for such a behavior is being built currently
