### ISSUE TITLE
How To Use The Benewake TFmini 

### ISSUE THREAD

**Issue by CradyArt** [iNavFlight/inav#4496]
I have a couple of questions about using the Benewake TFmini with iNAV and can't seem to locate any comprehensive documentation.  My setup is a Bixler 3 with a Mateksys F405 WING fc and I'm hoping to use the TFmini for terrain following and landings.

1) Is the TFmini actually supported in iNAV and if so could someone please point me toward step-by-step instructions on the installation and setup
2) If it is supported, which interface is required: UART or I2C 

Thanks!

**Comment by shellixyz** [comment]
You just need to connect it to an UART, enable "Rangefinder" as sensor in the ports tab for the right UART then set `rangefinder_hardware` to `BENEWAKE`. It will work like any other rangefinder in iNav. I don't think rangefinder are used for fixed wing models though.

**Comment by CradyArt** [comment]
Not working for me =(  I just get a red Sonar icon.  Connections are correct but it isn't being recognized

**Comment by DzikuVx** [comment]
I checked today and it is working when connected to free UART

**Comment by CradyArt** [comment]
Thanks, Pawel.  I'm trying to test the TFmini using an Arduino to see if it's possibly defective.  Question:  Did you need to use a level shifter?

**Comment by DzikuVx** [comment]
No level shifters. Both TFmini and STM32 are 3.3V

**Comment by CradyArt** [comment]
Thanks

**Comment by CradyArt** [comment]
Looks like my TFmini is DOA  ='(  Hopefully I'll get a functional replacement

Thanks guys!

**Comment by DzikuVx** [comment]
Too bad. Closing then

**Comment by rparts1** [comment]
how do i get benewake tf mini to show up on OSD using f722 wing ? have it working but not showing up on OSD

**Comment by zied923** [comment]
> I have a couple of questions about using the Benewake TFmini with iNAV and can't seem to locate any comprehensive documentation. My setup is a Bixler 3 with a Mateksys F405 WING fc and I'm hoping to use the TFmini for terrain following and landings.
> 
> 1. Is the TFmini actually supported in iNAV and if so could someone please point me toward step-by-step instructions on the installation and setup
> 2. If it is supported, which interface is required: UART or I2C
> 
> Thait have to be powred  from the battry to work
