### ISSUE TITLE
IST8310 MatekF405 v2.1

### ISSUE THREAD

**Issue by Gral67** [iNavFlight/inav#4498]
## Steps to Reproduce

1.
2.
3.
4.

## Expected behavior
Hello.In firmware 2.1 Matek F405, the compass IST8310 is not detected. In firmware 2.0 and 2.0.1, the compass is determined successfully.

## Additional context

---

- FC Board name and vendor:MatekF405-ctr
- INAV version string:2.1

**Comment by shellixyz** [comment]
Confirmed. Tested with F405-CTR/IST8310. Works fine with 2.0.1 but not with 2.1

**Comment by shellixyz** [comment]
Please try this build it should fix your issue: [inav_2.1.0_MATEKF405.hex.zip](https://github.com/iNavFlight/inav/files/2985891/inav_2.1.0_MATEKF405.hex.zip)

**Comment by DzikuVx** [comment]
Since #4523 is merged, I'm closing this one
