### ISSUE TITLE
betaflight 3.0 'diff' and 'diff all' CLI commands

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#450]
The new betaflight 'diff' and 'diff all' commands greatly simplify configuration management by only saving CLI values that are not default. 

Please consider porting / implementing in iNav; it saves a lot of backup / restore troubles.

**Comment by oleost** [comment]
f9354e53b3b41c71e0982ef65b01b26474d7af

**Comment by digitalentity** [comment]
https://github.com/betaflight/betaflight/pull/883
https://github.com/betaflight/betaflight/pull/1032
https://github.com/betaflight/betaflight/pull/1037
