### ISSUE TITLE
RC Switch on servo or motor channel, to be set in the mixer tab or cli.

### ISSUE THREAD

**Issue by Tygrys-1** [iNavFlight/inav#4505]
Sometimes there is a need to drive lights or other on/off device on the model. Today we need the external "RC switch" device, which will convert the PWM to the on/off output state. As there are often spare servo or motor outputs on the FC, can they be used to just output the on/off state instead of the PWM? Something like the PINIO of the Betaflight? Can it be set via the mixer configuration?

Combined with the planned (Paweł Spychalski mentioned it) conditional mixer this will have the potential to do some advanced model logic like releasing something at a given altitude or flashing the lights when achiving Mach 1 speed ;-)

**Comment by DzikuVx** [comment]
There is something like that. @shellixyz did that https://github.com/iNavFlight/inav/blob/master/docs/Lights.md 
but it requires custome build and hardware
