### ISSUE TITLE
dshot protocol no apply

### ISSUE THREAD

**Issue by jordimulet** [iNavFlight/inav#4506]
## Current Behavior

As of version 2.1.0, the dshot protocol is allowed.
When selecting the option of dshot in esc protocol and saving and reboot, the change has not been saved and the esc does not recognize the protocol.
## Steps to Reproduce

1. Select dshot150 in esc protocol
2. save and reboot
3. The saved esc protocol is standard

## Expected behavior

the esc protocol was dshot150

## Additional context
https://pastebin.com/M6mSgpPW

---

- FC Board name and vendor: kakuteF7
- INAV version string: 2.1.4

**Comment by shellixyz** [comment]
DSHOT isn't enabled on the KakuteF7. Please read the release notes: https://github.com/iNavFlight/inav/wiki/2.1.0-Release-Notes#dshot
