### ISSUE TITLE
Enchancement - BlackBox

### ISSUE THREAD

**Issue by xdigyx** [iNavFlight/inav#451]
Blackbox to save data in onboard 2MB flash. At the moment it seems not to be available.

**Comment by oleost** [comment]
More details?

**Comment by Ralf-W** [comment]
@xdigyx  You have to activate internal flash via CLI at the moment:
set blackbox_device = SPIFLASH  # instead of SERIAL
set blackbox_rate_num = 1
set blackbox_rate_denom = 2
This will make it work and store every second value.

**Comment by xdigyx** [comment]
THX Ralf. So just GUI must be updated.
Unfortunately also there is not a word about this in docs (neither CLI/BBox), so I let myself to update https://github.com/iNavFlight/inav/wiki/INAV-blackbox-variables
please verify/correct as required.

**Comment by DzikuVx** [comment]
@xdigyx but everything is in docs: https://github.com/iNavFlight/inav/blob/master/docs/Blackbox.md

Issue closed
