### ISSUE TITLE
Airspeed Sensor / Pitot Tube Recommendations?

### ISSUE THREAD

**Issue by CradyArt** [iNavFlight/inav#4511]
Can anyone recommend a solid airspeed sensor?  I'm looking to add an airspeed sensor and pitot tube to my Bixler 3 build with the Mateksys F405 WING FC and not sure if an analog or digital sensor would be preferable

Thanks!

**Comment by shellixyz** [comment]
The easiest is to use a digital airspeed sensor like this one (MSS4525, option C): https://inavflight.com/shop/s/bg/1371068

You can also use an analog one if your FC has got a free analog input but you also need to add a resistor divider to the output of the sensor to make sure the output never goes above 3.3V

**Comment by CradyArt** [comment]
Cool.  Thanks, Michel
