### ISSUE TITLE
Servo logging breaks Blacbox logs

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#4512]
@hali9 apparently 6a5e1b18b891a69d7db862d8130cacb695fee4fa breaks blackbox logs if servos are not used, for example on quadx configuration. Logs are written but file is not decoded by both `blackbox_decoder` or Blackbox Explorer.

Not sure what causing it, 6fcea591b477af91177f47b4ff85890bf63f3899 is working fine, 6a5e1b18b891a69d7db862d8130cacb695fee4fa causes 
decoding failure. Example log attached

[LOG00003.TXT](https://github.com/iNavFlight/inav/files/2974152/LOG00003.TXT)

**Comment by DzikuVx** [comment]
Interesting, it fails only on one FC: MatekF722, on OmnibusF4 works fine

**Comment by hali9** [comment]
I have set the condition always unnecessarily.
should be isMixerUsingServos()

**Comment by DzikuVx** [comment]
@hali9 it's not this. I'm experimenting with it for a while. I changed condition, prediction and conditions. And I'm able to reproduce it every time now on every flight controller.
It's either something I'm completely missing and is obviously stupid or some deeper problem.
To reproduce you just need to set QuadX and leav ot running for a minute

**Comment by hali9** [comment]
@DzikuVx I do patch-2 https://github.com/iNavFlight/inav/compare/development...hali9:patch-2
I tested it witch set mmix and without mmix on quadx and it works (I still use SPRacingF3).

**Comment by DzikuVx** [comment]
I will test tomorrow then.

sob., 16 mar 2019, 22:40 użytkownik hali9 <notifications@github.com>
napisał:

**Comment by DzikuVx** [comment]
OK, fixed in #4516 Thanks @hali9
