### ISSUE TITLE
OmnibusF7NXT 2.1.0 - Navigation is Unsafe

### ISSUE THREAD

**Issue by Rclay11541** [iNavFlight/inav#4514]
[blackbox_log_2019-03-16_173551.TXT](https://github.com/iNavFlight/inav/files/2974545/blackbox_log_2019-03-16_173551.TXT)
## Current Behavior
The firmware update for the OmnibusF7NXT 2.1.0 vs 2.0.1 has an error.
With 2.1.0 OSD & Blackbox now work, however, I'm getting an arm error of **Navigation is Unsafe**. No hadware changes or setting changes, under the old version I didn't get this error.

See issue #4012 

---

# version
# INAV/OMNIBUSF7NXT 2.1.0 Feb 25 2019 / 16:57:11 (65b0ec142)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

Dump:
[INAV_cli_Long_Range 5_DUMP.txt](https://github.com/iNavFlight/inav/files/2975794/INAV_cli_Long_Range.5_DUMP.txt)

On Power Up --- CLI with Runtime & Navigation is Unsafe:
[INAV_cli_Long_Range 5 Nav & Runtime.txt](https://github.com/iNavFlight/inav/files/2975795/INAV_cli_Long_Range.5.Nav.Runtime.txt)

5 Mins after Power Up - Runtime error goes away, only Navigation is Unsafe remains:
[INAV_cli_Long_Range 5 Nav Only.txt](https://github.com/iNavFlight/inav/files/2975796/INAV_cli_Long_Range.5.Nav.Only.txt)

6 Mins after Power Up - turned on Radio, still getting Navigation is Unsafe:
[INAV_cli_Long_Range 5_Nav Only - Turned Radio on too.txt](https://github.com/iNavFlight/inav/files/2975799/INAV_cli_Long_Range.5_Nav.Only.-.Turned.Radio.on.too.txt)

**Comment by shellixyz** [comment]
Please post the output of the status command run from the CLI

**Comment by Rclay11541** [comment]
Added the CLI Status files above.

**Comment by shellixyz** [comment]
Well if the status command displays only CLI as arming disabled flags it means you can arm once you get out of the CLI. If the gyro runtime cal takes a long time maybe your gyro is noisy (or you're moving the FC). Remember that you need to keep the FC still for something like 10s after powering it up. If you were keeping it still you should check the values reported by the gyro in the sensors tab.

**Comment by shellixyz** [comment]
You can refer to this document for the meaning of the arming disabled flags:
https://github.com/iNavFlight/inav/wiki/%22Something%22-is-disabled----Reasons

**Comment by Rclay11541** [comment]
Hi, I think you may have prematurely closed the ticket. The reason the ticket was opened is because arming is being prevented even though there are no flags.

You can see there's a number of I2C errors with the new firmware versus none with the earlier version. The main difference is the SPI was modified between versions to correct the issue with the Blackbox hanging. My thoughts are there may have been unintended consequences during code modification.

Please re-open the issue. Happy to test hex files if you have any you like to be tested.

**Comment by shellixyz** [comment]
What is happening when you are trying to arm?

**Comment by Rclay11541** [comment]
Hi, first thanks for helping with this. I really appreciate it!

So after getting a good GPS lock the OSD is flashing "Sensors Calibrating". When i try to arm simply nothing happens. I included the Blackbox logs above. I wasn't able to see anything odd, but I'm a beginner when it comes to code.

**Comment by Rclay11541** [comment]
Perhaps the real issue is runtime when in the field? Any thoughts as to why it would take so long for the runtime checks to settle down under the new code?

**Comment by Rclay11541** [comment]
Ah ha! Ok so here's what's going on. Under the old firmware GPS would take forever to get a good lock. With the new firmware it takes less than 30 secs. So I think the long GPS lock time was masking an underlying issue. It takes between 5 & 10 minutes for Runtime to clear...even with very carefully powering up the quad and letting it sit. 

I just powered it up and let it sit for about 10 minutes, the runtime error finally cleared and I was able to arm. The problem is that a **significant amount** of battery life is being used to clear the runtime.

Is this maybe an issue with the Barometer showing up as FAKE? I see in the new firmware there's a new CLI Command "baro_cal_tolerance = 150" Is this maybe the issue? I'd be happy to try changing these values but I'm sure it was added and set at default to 150 for a good reason. 

Attached the blackbox file below.
[blackbox_log_2019-03-17_LONG wait to clear runtime.TXT](https://github.com/iNavFlight/inav/files/2975990/blackbox_log_2019-03-17_LONG.wait.to.clear.runtime.TXT)
![Baro FAKE](https://user-images.githubusercontent.com/44800056/54501110-9e376d80-48f9-11e9-8b73-59629d0e98d7.JPG)
![BARO CLI](https://user-images.githubusercontent.com/44800056/54501154-ec4c7100-48f9-11e9-8af2-e8adb37324ad.JPG)

**Comment by Rclay11541** [comment]
Note there are two Barometers on the OmnibusF7NXT board: MPU6000 and a ICM20608. I don't see either of those listed as options in the CLI.

**Comment by Rclay11541** [comment]
see #3697

**Comment by shellixyz** [comment]
Try to increase the baro_cal_tolerance setting. Try `set baro_calibration_tolerance = 500`

**Comment by shellixyz** [comment]
Indeed the barometer recognized as FAKE is not good. The fake barometer driver is only giving constant pressure and temperature though so it should not be an issue for the calibration

**Comment by Rclay11541** [comment]
Hi Shellixyz,

Thanks very much, setting to 500 really reduced the barometer calibration time.

Just so I understand, why is it showing as FAKE? What does it mean when it's showing as FAKE? Is it recognizing the barometer at all, or is it just using the GPS?

Thanks again very much for all your help!

**Comment by shellixyz** [comment]
I just realized it is displaying FAKE in the configurator but is really LPS25H. It is a bug in the configurator. 500 is probably a bit much for `baro_calibration_tolerance` try to lower it as much as you can while keeping the calibration time acceptable
