### ISSUE TITLE
Add special arm switch combo to bypass small_angle and unsafe nav checks

### ISSUE THREAD

**Issue by shellixyz** [iNavFlight/inav#4515]
The idea is to be able to arm if the model is out of reach (in a tree for example) or just when you know what you are doing and really want to arm.

Alberto suggested switching arm on/off quickly or something like keep switch on for 5 seconds then off for 1 then on.

**Comment by teckel12** [comment]
@shellixyz Great idea! I like the quick arm/disarm/arm trigger. Long arm wouldn't work if arming is via switch, no?

**Comment by Jetrell** [comment]
Good idea @shellixyz 
Would you also agree that Turtle mode https://www.youtube.com/watch?v=3LL2caB3r88 
could also be a variant along with this, now that inav has Dshot?

**Comment by laurentopia** [comment]
A Savior!
Someone suggested another way to trigger bypass-arm with 5 or 10 successive arm-disarm. That one won't be done by the user by mistake and it is easy to remember and perform. 
I wonder if it could happen as a result of an R9 glitch, though.

**Comment by DzikuVx** [comment]
This is another case for logic conditions and global functions I'm
currently working on.

niedz., 17 mar 2019, 05:12 użytkownik laurentopia <notifications@github.com>
napisał:

**Comment by shellixyz** [comment]
Done in 2.2.0, closing
