### ISSUE TITLE
sp racing f3 works but not connect pc

### ISSUE THREAD

**Issue by oguzhantasdemir** [iNavFlight/inav#4522]
my sp racing f3 work with last setting. no connect pc and not install new fw. i tried many method. but not connect. only connect via debug port(swd). i think my uart1 inverter is broken. i have an idea. if make msp in uart2, i can connect to pc with ftdi adapter via uart2 port. and sorry my bad English 😅

**Comment by oguzhantasdemir** [comment]
why closed my issue?

**Comment by shellixyz** [comment]
Why not ?

**Comment by oguzhantasdemir** [comment]
I have a problem. is not it?

**Comment by shellixyz** [comment]
Is your issue a bug or feature request ?

**Comment by oguzhantasdemir** [comment]
not both. please read my first article.

**Comment by shellixyz** [comment]
Then sorry but it is not the right place to post about your problems. Github "issues" are for reporting bugs and asking for new features. This is not a support forum.

**Comment by oguzhantasdemir** [comment]
i am sorry. i didnt now. thank you so much.

**Comment by shellixyz** [comment]
No problem. Please join [iNav's Telegram channel](https://t.me/INAVFlight) if you want live help.
