### ISSUE TITLE
Pit mode -> arm  -> power level 2 or 3 ->  disarm -> pit mode

### ISSUE THREAD

**Issue by romko1** [iNavFlight/inav#4525]
Hello,
I have  VTX  AKK FX3, FC MatekF405 mini.
At the moment it works for me as follows: I set up the OSD pit mode (OP MODEL = RACE) - restart the FC, it's still pit mode. If I do ARM it goes to the set VTX transmit power but then when I do disarm it just decreases the power to 1 (transmiter power is 25mW, not pit mode = 0.01mW).

I use inavflight where I set:
set vtx_halfduplex = ON
set vtx_band = 5    //race
set vtx_channel = 3
set vtx_power = 3
set vtx_low_power_disarm = ON
set vtx_freq = 5732
set vtx_pit_mode_freq = 5732

When I first do the ARM it switches to the desired transmit power. 
However, if I do a disarm it will not go into P (pit mode) but will decrease the power to 25mW (flashed 1). 
When I look through the OSD to the VTX AKK FX3 so the pit mode is deactivated - the OP model is FREE again.

I want to make VTX go to pit mode after disarm -> P flashed.
Can you please tell me how to do this?

Thank you.

**Comment by BradB111** [comment]
I believe this is a limitation to the Smart audio protocol for Smart Audio <=2.0 

The new TBS Vtxs support this with Smart Audio 2.1

Hope this helps.

EDIT(to better explain the limitation): The limitation exists where the Vtx can be powered up in pit mode and the user can take it out of pit mode however it will not accept a smart audio command to put it back into pit mode after the Vtx switches to a higher transmit power.

**Comment by romko1** [comment]
So is it possible that VTX AKK FX3 only supports smartaudio protocol <=2.0?

**Comment by BradB111** [comment]
AKK as far as I'm aware don't use an official implementation of Smart Audio (the reason for the AKK patch on betaflight for example) 
some basic info on this can be found here: https://github.com/betaflight/betaflight/issues/5086

Also taken from Betaflight 3.3 release notes: "_The SmartAudio protocol implementation has been updated to be fully compliant with the SmartAudio specification. First generation AKK / RDQ VTX devices have a bug in their SmartAudio protocol implementation, causing them to fail to work with the SmartAudio protocol as implemented by Betaflight 3.3 (and KISS / RaceFlight). In order to not leave the owners of these VTX devices stranded, a branch off the Betaflight 3.3 maintenance branch has been created with a fix for these devices in it. This branch will be updated for all 3.3 patch releases._"

**Comment by romko1** [comment]
yes that applies to betaflight, but I didn't find some patch for inavflight to get back to pit mode via disarm.
I currently have inav v.2.0.1 installed on that quadcopter..

**Comment by BradB111** [comment]
> yes that applies to betaflight, but I didn't find some patch for inavflight to get back to pit mode via disarm.
> I currently have inav v.2.0.1 installed on that quadcopter..

What i'm saying is its not even 'smart audio' its a vtx that happens to accept old smart audio commands so i wouldn't expect it to work any time soon (if at all). 

If your smart audio works to change channel then iNav either; 
1. has the patch already or 
2. iNav isnt fully compliant with the official TBS standard (using the old implementation). 
(maybe someone else can clarify this i haven't been following iNav for that long)

Putting the vtx into pit mode doesn't work on (as far as I know):

- TBS Vtxs running Smart Audio <=2.0
- other Vtxs running Smart Audio <=2.0
- AKK Vtxs patch
- AKK Vtxs using the old smart audio implementation

The Only Vtxs that will support what you are looking for (putting the Vtx back into pit mode after being taken out of pit mode) are these:
- https://www.team-blacksheep.com/products/prod:unify_pro_hv_race2_m
- https://www.team-blacksheep.com/products/prod:tbs_unify_evo
- https://www.team-blacksheep.com/products/prod:unifypro32_nano
- Other Smart audio 2.1 Vtxs although I'm not aware of any.

Also just to clarify as this is a Smart Audio limitation it will not work on any current Firmware (BF/BuF/RF/FL1/iNav/Kiss/...). I only linked Betaflight as its the only place it seems to be very well documented.

**Comment by romko1** [comment]
Oh, I understand how you thought it was. I have a new vtx and I thought the pitmode transition from it to it will work.

**Comment by romko1** [comment]
I wrote to support AKK and their response: The case is not related with the vtx.

**Comment by BradB111** [comment]
You need one of those vtxs I linked above, and you need to make sure smart audio 2.1 feature set is supported on iNav and I don't think it is currently. 

AKK DOES NOT support the official smart audio protocol. Certainly not 2.1 which is required for your use case.

**Comment by padcom** [comment]
I just bought the PRO32 Nano VTX, configured as per the example stated in the first comment and PIT mode is _NOT_ automatically engaged when disarming. INAV 2.2.0 RC-2 on Matek F405-WING (MATEKF405SE target). Any idea how to get it to work? Or how to engage the pit mode manually?

```
# get vtx_halfduplex
vtx_halfduplex = ON
Allowed values: OFF, ON


# get vtx_band
vtx_band = 4
Allowed range: 0 - 5


# get vtx_power
vtx_power = 1
Allowed range: 1 - 5


# get vtx_low_power_disarm
vtx_low_power_disarm = ON
Allowed values: OFF, ON, UNTIL_FIRST_ARM


# get vtx_freq
vtx_freq = 5880
Allowed range: 0 - 5999


# get vtx_pit_mode_freq
vtx_pit_mode_freq = 5880
Allowed range: 0 - 5999
```
