### ISSUE TITLE
FC heading constantly increase/decrease

### ISSUE THREAD

**Issue by ucibar** [iNavFlight/inav#4526]
Hello,
I have Matek F405-WING and The heading value keeps increasing or decrease without the quad moving. There is a no GPS or compass. Ony Gyro and Acclerometer. This is normal or my is gyro broken?

**Board:** Matek F405-WING, **iNav Version:** MATEKF405SE-2.1.0, **iNav Configurator:** 2.1.4

**Comment by uCibar** [comment]
#2594

**Comment by giacomo892** [comment]
Perfectly normal.
Please use Facebook or Telegram for such questions.
