### ISSUE TITLE
Gps navigation without compass

### ISSUE THREAD

**Issue by FlyR9** [iNavFlight/inav#4552]
Hello, i just got amazed how the gps-rescue mode work well in betaflight with only a gps, i would like know if the inav's feature can be used in the future without compass/magnetometer (i think it's obvious the precision is less without compass but if it can save the quad with an rth it can be really nice).

Thank you for the answers ^^

**Comment by giacomo892** [comment]
We already have opened issues for this like https://github.com/iNavFlight/inav/issues/4228

Closing.
