### ISSUE TITLE
Max bank angle in Angle mode

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#4564]
I notice a newly set up flying wing that the maximum bank angle is very slight, like around 30-40 degrees.   What setting should I use to increase this (to say 60 or 80 degrees)

Thanks

**Comment by shellixyz** [comment]
https://github.com/iNavFlight/inav/wiki/Fixed-Wing-Guide#step-4-replace-default-values

**Comment by MartinHugh** [comment]
@shellixyz thanks. Cant believe I missed these angle_inclination settings. I did all of the others but for some reason these two appear to be still at defaults.

**Comment by MartinHugh** [comment]
Actually - I confirmed this by looking at the last diff I had.

But on checking the FC itself - these were set to 600 in both cases.

Also checked that all the other settings referenced had been set to sensible values

What can I check next?

Do I need to recreate another issue now this one is closed ?
