### ISSUE TITLE
FC F35 compass erorr!!

### ISSUE THREAD

**Issue by letruong6006** [iNavFlight/inav#4574]
hello, can someone help me? I am using the FC furiousvF35 for X-UAV talon. I noticed the circuit of the circuit was only in the wrong direction. I checked it with the compass direction of the phone with the direction of the FC circuit. (confirm the direction of the phone is correct). But the direction of the circuit is different, I'm sure the direction of FC is only wrong, I tried calibrate compass many times but the result is still the same. Board and Sensor Alignment parameters are default. what should i do? :(

**Comment by letruong6006** [comment]
![56162470_1824814447665104_5098694709467938816_n](https://user-images.githubusercontent.com/48900198/55561202-f523ac00-571b-11e9-89e9-6eecddf2d740.jpg)
![56398316_1824814287665120_8743931490506637312_n](https://user-images.githubusercontent.com/48900198/55561204-f523ac00-571b-11e9-99ed-e622f844e719.jpg)
![56544628_1824814177665131_2551854015759515648_n](https://user-images.githubusercontent.com/48900198/55561205-f5bc4280-571b-11e9-9a82-ce178977f1cf.jpg)

**Comment by teckel12** [comment]
@letruong6006 Is your flight controller pointed forward? Is the compass on the GPS module or on the FC?

**Comment by wx4cb** [comment]
the flight controller is 180 degrees out if the pins are pointing to the front of the aircraft (hard to tell which direction it's installed). Also, you don't need the compass on a fixed wing so you can disable it.

**Comment by letruong6006** [comment]
> @ letruong6006 Bộ điều khiển chuyến bay của bạn có hướng về phía trước không? Là la bàn trên mô-đun GPS hoặc trên FC?

The controller flies forward. The compass is definitely on FC. GPS does not have a compass. I had some great flights with stable parameters. but something made it go wrong. while RTH flies around on his head. It has fallen. and then the compass is no longer accurate

**Comment by letruong6006** [comment]
> bộ điều khiển bay lệch 180 độ nếu các chân chỉ về phía trước máy bay (khó có thể biết được nó được lắp theo hướng nào). Ngoài ra, bạn không cần la bàn trên một cánh cố định để bạn có thể vô hiệu hóa nó.

How to turn off the compass with CLI? My plane crashed after an accident. I took the plane in my hand and walked about 50m. The arrow pointing to the house is misleading, even if I move it to the home position, it points in a different direction, all parameters are not changed as before the accident. What can I do?

**Comment by wx4cb** [comment]
Turn it off in the configuration tab. Set magnetometer to none

**Comment by teckel12** [comment]
@letruong6006 In the configurator, just above where you circled the alignment, you can set compass/magnatometer to none.

**Comment by letruong6006** [comment]
Red circle arrow below. does it work when i turn off the compass? I really need it to be able to control in the foggy days
![image](https://user-images.githubusercontent.com/48900198/55598960-9e4fbe00-577f-11e9-8ea7-2cc4e0fade7e.png)

**Comment by wx4cb** [comment]
Yes it will work fine as it will come from the gps

**Comment by teckel12** [comment]
@letruong6006 Since there's always forward movement with fixed wing, heading is calculated by using GPS coordinates.

Multi-rotor needs a compass because it can be totally stationary, so direction can't be calculated with just GPS.

So as long as your fixed wing is moving forward, it will have accurate heading.

**Comment by letruong6006** [comment]
I will try it today. Thank you Teckel12 and wx4cb very much :)
