### ISSUE TITLE
new OSD functions

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#4576]
The inav software is very good.

Feature request:
When the airplan main functions like ports RX signal are set, sometimes additional settings need to be done on the flying field without having a PC available.
It's sometimes needed to add and delete mixers and to adjust the weight.
Also it's needed to change the servo trim or servo travel.
It would be very nice, if these setting would be also possible in a OSD submenu, so there is no PC needed on the flight field. Also sometimes the USB plug is not easy to reach.
![grafik](https://user-images.githubusercontent.com/25489220/55567982-12964d00-56ff-11e9-9ca2-8be3b934beec.png)
![grafik](https://user-images.githubusercontent.com/25489220/55568001-1aee8800-56ff-11e9-9c53-8721cb5eddd1.png)

It would be a really nice feature for one of the future inav updates.

I wish also the CMS-HoTT mode will be included to the future versions.

**Comment by fiam** [comment]
@Ralfde Check https://github.com/iNavFlight/inav/pull/4616 for CMS over HoTT

**Comment by Scavanger** [comment]
See #4724
