### ISSUE TITLE
Manual throttle launch mode

### ISSUE THREAD

**Issue by brassman84** [iNavFlight/inav#4578]
## Current Behavior
An alternative launch mode for people who are unsuccessful with the current auto launch or who thinks auto launch is to dangerous.

## Desired Behavior
a mode simular to horizon/angle mode but with the nav_fw_launch_climb_angle active so the plane climbs instead of leveling out, throttle is controlled manualy. Also it could be timed using nav_fw_launch_timeout.

## Who does this impact? Who is this for?
This feature would be for fixed wing only.

**Comment by P-I-Engineer** [comment]
make a mix on a switch in your radio for up elevator, now launch with that on and in angle mode.

**Comment by michaelvanderhoek** [comment]
agree with PI engineer. I also launch my wing with a switch on elevator.

**Comment by shellixyz** [comment]
Duplicate of #3858, closing
