### ISSUE TITLE
Numbered waypoints

### ISSUE THREAD

**Issue by brassman84** [iNavFlight/inav#4579]
## Current Behavior
As for now when flying WP missions OSD will just say "en route to waypoint".

## Desired Behavior
Instead It would be really cool if it would say en route to waypoint 1, 2, 3 ect.
And mabey also "Mission compleated, RTH" when the last WP is reached, RTH only if RTH activated for the mission ofcorse.
This would make DVR recorded missions more fun to watch.

## Who does this impact?
This could be used for all types of airframes.

**Comment by breadoven** [comment]
Closed by various PRs.
