### ISSUE TITLE
WingFc 10 DOF don't save DSHOT settings

### ISSUE THREAD

**Issue by daveleonelizzi** [iNavFlight/inav#4580]
## Steps to Reproduce

1.in iNav configurator 2.1.4 on Windows 7 64 bit I enter in configuration tab
2. Select DSHOT as motor protocol
3.save and reboot
4.I can't save this setting on my iNav

## Expected behavior
I have a WingFc flight controller from banggood with the latest version of iNav. I hav also a DSHOT compatible ESC in my plane so I decided to use it.
I tried so many times to save this setting but nothing has the results I want.

Any ideas? 

Thank you so much to everyone who help me

**Comment by stronnag** [comment]
Read the release notes, in particular the section on DSHOT.
