### ISSUE TITLE
Akk omnibus f4 no servo outputs

### ISSUE THREAD

**Issue by Lostigli** [iNavFlight/inav#4584]
hello I have an omnibus f4sd from AKK but on all PWM pins (except the SBUS port) are not getting 5v; they are only getting 2.75v which is not enough for the servos. 
 
please help thanks Lorenzo

![f4](https://user-images.githubusercontent.com/49344164/55671185-7cdcf800-588d-11e9-8819-837c2b346849.png)

**Comment by DzikuVx** [comment]
This is not INAV thing for sure. Those pins are probably powered only when battery is connected to Vbat.
