### ISSUE TITLE
 FC F35 lightning is not connected to INAV!

### ISSUE THREAD

**Issue by letruong6006** [iNavFlight/inav#4586]
I found no OSD on the screen, the OSD test in inav was activated. I tried to turn it on but it did not work, I upgraded the software from 1.9.1 to 2.1.0, flash finished, I unplug it and reconnected. and FC cannot connect INAV. The software update process is not interrupted. What can I do?
![1](https://user-images.githubusercontent.com/48900198/55683869-cfdaac00-596e-11e9-93d8-323ceac1137c.PNG)
![2](https://user-images.githubusercontent.com/48900198/55683870-cfdaac00-596e-11e9-8cae-e1dee21a1324.PNG)
![3](https://user-images.githubusercontent.com/48900198/55683871-d0734280-596e-11e9-8d2f-c3a29b5a36ae.PNG)
![image](https://user-images.githubusercontent.com/48900198/55683891-1defaf80-596f-11e9-87aa-e951a3b77c9b.png)

**Comment by sniperxnl** [comment]
![F35 boot pins](https://user-images.githubusercontent.com/16321561/56419227-d257d280-6299-11e9-9ea9-a0a99bce69ff.JPG)

These 2 small pins are to get it back in DFU
