### ISSUE TITLE
FFPV VTX control OSD menu appearance 

### ISSUE THREAD

**Issue by vicdzen** [iNavFlight/inav#4588]
## Current Behavior
<a href="http://tinypic.com?ref=2afbxqa" target="_blank"><img src="http://i63.tinypic.com/2afbxqa.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Wrong Page name and invisible band in **Band** line
## Steps to Reproduce
Just move to Features -> FFPV VTX in OSD menu

## Expected behavior
Correct and visible information in OSD menu page 

## Suggested solution(s)
Page name should be something like **FFPV VTX**
Band line should indicate band name ("2.4G A" or "2.4G B")

## Additional context

---

- FC Board name and vendor: Matek F411 wing
- INAV version string: 2.1.0
- VTX FW version: VTX2G4_FCC 05 Apr 2019

**Comment by vicdzen** [comment]
Also [This one](https://github.com/iNavFlight/inav/issues/4510) is related to FFPV protocol

**Comment by KeenFPVer** [comment]
I have same issue using same FC and FFPV VTX2.4
Mine also does not change power every time I can see this by performance and he RED LED on the VTX does not blink 3X for 500mW
![VTX FFPV issue](https://user-images.githubusercontent.com/51330196/60812569-b7ef1000-a189-11e9-8ef8-44f8a648be86.PNG)
