### ISSUE TITLE
 [F35 FC] OSD does not display on the screen

### ISSUE THREAD

**Issue by letruong6006** [iNavFlight/inav#4590]
I used the Fc F35 circuit, some of the previous flights were great but suddenly OSD was not displayed on the screen, no parameters were changed before, OSD in INAV is still activated, the latest version 2.1 .0. I need help
![image](https://user-images.githubusercontent.com/48900198/55692634-23331580-59d4-11e9-95ad-c1adf9eee668.png)

**Comment by parchedpacha** [comment]
I recently had this issue, and I solved it by uploading a new font file. Maybe that will work for you too? if it doesn't work immediately try rebooting after the upload is completed.

**Comment by shellixyz** [comment]
If it was working before and nothing changed in the software then it seems to me that it can only be a hardware issue
