### ISSUE TITLE
compass not recognized omnibus f4 pro v4 corner

### ISSUE THREAD

**Issue by H4R0** [iNavFlight/inav#4593]
Hi,

i know there are a lot of related threads and i already tried everything to get the compass working.

I set i2c speed to 100KHZ and also added pull-ups from uart3 rx/tx to 3.3v using 4.7kΩ resistors. Also tried switching tx/rx. The inverter on uart3 is disabled.

The compass is still not detected.

The board pin-out does not mention sda/scl on uart3 so i guess its just not exposed on the flight controller. (The built-in barometer works fine)

My question right now is, are there standalone compass that use uart instead of i2c ? 

Or another GPS module that does gps and compass over uart ?

I really dont want to replace the fc if possible.

Flightcontroller omnibus f4 pro v4 corner:
http://aliexpress.com/item/name/32841366927.html

GPS & MAG Beitian BN-880: 
http://banggood.com/name-p-971082.html

INAV/OMNIBUSF4PRO 2.1.0 Feb 25 2019 / 16:53:27 (65b0ec142)
GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

Full diff:
https://pastebin.com/fv32VUhg

**Comment by shellixyz** [comment]
I think that you can use a NAZA GPS, it has both the GPS and compass available through an async serial port, you only need one UART for both: https://inavflight.com/shop/s/bg/1332989

Set `gps_provider` to `NAZA`

**Comment by H4R0** [comment]
Great thanks for the quick reply ! You made my day.

This is exactly what i was hoping for.

In addition i have another uart free that i can use for smart audio.
