### ISSUE TITLE
SmartAudio 2.1 compatibility

### ISSUE THREAD

**Issue by ChristianFFB** [iNavFlight/inav#4594]
## Current Behavior
Smartaudio 2.1 not working (New TBS VTX like EVO)
## Desired Behavior
Smartaudio compatibility is added

See solution from Betaflight: https://github.com/betaflight/betaflight/issues/7336

**Comment by digitalentity** [comment]
@ChristianFFB fixed in https://github.com/iNavFlight/inav/pull/4596, please test if possible.
