### ISSUE TITLE
inav accelerometer calibration   Matek F405 (new) , Matek GPS

### ISSUE THREAD

**Issue by Eski1985** [iNavFlight/inav#4598]
Hi everybody.

Creat this account , becouse i think this is the only place where i can find help.
I know i know that should be moust simple step to do but for some reason i cannot calibrate my accelerometer.

I have got  Matek F405 Wing  ( new ) + GPS matek 
Radio Link Frsky R9M  

![Nowy obraz mapy bitowej (2)](https://user-images.githubusercontent.com/49558982/56037293-d5494500-5d26-11e9-9da6-f470c7511453.jpg)

If you take a look on that picture , on the right side is accelerometer is calibrate but on the top is still on red. 

Also when i moving the plane in the Inav my plane (that arrow ) don't move at all. 

Magnetometer is OFF 

any chance someone can help me  ?

Thank You
Eski

**Comment by DzikuVx** [comment]
The red mark in the top means that accelerometer was not detected, not that is is not calibrated. Restore defaults, check acc hardware on Configuration page. If still no luck, that might indicate hardware failure

**Comment by Eski1985** [comment]
DzikuVX Thank you , it was set up MPU6500 , where should be MPU6000 is working fine ;)
