### ISSUE TITLE
Throttle value in OSD

### ISSUE THREAD

**Issue by rockyleenj** [iNavFlight/inav#4600]
Even change the throttle_min in configuration, the OSD throttle value show wrong number.
Use SBUS receiver, the actual throttle range is from 1100 - 1900.
But the OSD calculation based on 1000-2000.
And system keep report that "Throttle is not low".

**Comment by DzikuVx** [comment]
You have to change throttle range in radio to use 1000-2000. Or try using rxrange command like described in https://github.com/iNavFlight/inav/blob/master/docs/Rx.md

**Comment by rockyleenj** [comment]
Many thanks and it fixed my problem.
