### ISSUE TITLE
CAN WE ADD EXTERNAL BARO AND GPS/MAGNETOMETER TO DALRC -F405-AIO FC? ON THE BOARD THERE IS SCA AND SDL --CAN WE CONNECT BOTH BARO AN MAGNETOMETER TO SAME I2C PADS? DALRC F405 IS SUPPORTED IN INAV SO PLEASE LET ME KNOW HOW TO SET THIS ALL UP

### ISSUE THREAD

**Issue by christm45** [iNavFlight/inav#4618]
For immediate help, just ask your question on one of the following platforms:

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

You can also read public documentations or watch video tutorials:

* [Official documentation](https://github.com/iNavFlight/inav/tree/master/docs)
* [Official Wiki](https://github.com/iNavFlight/inav/wiki)
* [Video series by Painless360](https://www.youtube.com/playlist?list=PLYsWjANuAm4qdXEGFSeUhOZ10-H8YTSnH)
* [Video series by Paweł Spychalski](https://www.youtube.com/playlist?list=PLOUQ8o2_nCLloACrA6f1_daCjhqY2x0fB)

**Comment by giacomo892** [comment]
It's funny how you posted the solution in the actual place for the question. Closing.
