### ISSUE TITLE
INAV Flight Modes Wiki Page Link Error

### ISSUE THREAD

**Issue by KFNCOLO** [iNavFlight/inav#4619]
Clicking on the INAV Github Wiki Page Link for "INAV Flight Modes" under Additional Information just brings up a blank "Create New Page". I'm pretty sure I remember in the past there being actual information and a description on the flight modes. Could the Github page link messed up, or is it my computer, or memory?

**Comment by teckel12** [comment]
@KFNCOLO Fixed.  Someone changed the title, which changes the link.
