### ISSUE TITLE
'Accelerometer calibrated' Fail

### ISSUE THREAD

**Issue by AdamGFPV** [iNavFlight/inav#4620]
Any idea why i might be getting an X on the 'Accelerometer Calibrated' checks. I've ran the 6 point calibration multiple times and the error remains. I re-flashed the board with full chip erase and still no luck. Sensor tab shows movement as it should be. 
iNav v2.1.0
Configurator2.1.4
Board: Matek F722-WING

Thanks

**Comment by giacomo892** [comment]
Post a diff from CLI thanks

**Comment by putimir** [comment]
Same here, brand new board, no other settings...it just not gets values in...Inav 2.2.1. I have done 15 wings, ALL on Matek FCs, but this is a first one...
