### ISSUE TITLE
iNav CLI Flight Mode aux command info/update

### ISSUE THREAD

**Issue by cb9501** [iNavFlight/inav#4622]
Hi,
Unless I am missing something, it appears the only way to change modes without a pc is to use cli through the Mission Planner for iNav app.  In working through this process I figured out a couple things:
The wiki page for flight modes CLI aux commands here:
https://github.com/iNavFlight/inav/wiki/Modes
states that the syntax for using the CLI aux command is:
AUX channel index (AUX1 = 0, AUX2 = 1,... etc)
but it appears that it's actually AUX index = RC CHANNEL+5, in other words the example:
"Configure AUX range slot 0 to enable ARM when AUX1 is within 1700 and 2100.
aux 0 0 0 1700 2100"
should actually say:
Configure AUX range slot 0 to enable ARM when AUX5 is within 1700 and 2100.

Last, the modes list at the top of the page seems to be incorrect.  It appears the mode list should be:
0=ARM
1=ANGLE
2=HORIZON
3=ALT HOLD
4=HEADING HOLD
5=HEAD FREE
6=HEAD ADJ
7=CAM STAY
8=RTH
9=POS HOLD
10=MANUAL
11=BEEPER
12=?
13=?
14=NAV_LAUNCH
15=OSD SW
16=?
17=BLACKBOX
18=FAILSAFE
19=NAV WP
20=?
21=HOME RESET
22=GCS NAV
23=?
24=KILLSWITCH
25=SURFACE
26=TURN ASSIST
27=SERVO AUTOTRIM
28=AUTOTUNE
29=CAM CTRL1
30=CAM CTRL2
31=CAM CTRL3
32=OSD1
33=OSD2
34=OSD3
35=CRUISE
36=?
37=?
38=?
39=FPV ANGLE MIX
40=LOITER CHANGE

**Comment by shellixyz** [comment]
Auxiliary channels are the channels that are not roll/pitch/yaw/throttle, so starting with channel 5. The documentation might not be clear but it is exact.

Mode IDs:
ARM = 0
ANGLE = 1
HORIZON = 2
NAV ALTHOLD = 3
HEADING HOLD = 5
HEADFREE = 6
HEADADJ = 7
CAMSTAB = 8
NAV RTH = 10
NAV POSHOLD = 11
MANUAL = 12
BEEPER = 13
LEDLOW = 15
LIGHTS = 16
OSD SW = 19
TELEMETRY = 20
AUTO TUNE = 21
BLACKBOX = 26
FAILSAFE = 27
NAV WP = 28
AIR MODE = 29
HOME RESET = 30
GCS NAV = 31
FPV ANGLE MIX = 32
SURFACE = 33
FLAPERON = 34
TURN ASSIST = 35
NAV LAUNCH = 36
SERVO AUTOTRIM = 37
KILLSWITCH = 38
CAMERA CONTROL 1 = 39
CAMERA CONTROL 2 = 40
CAMERA CONTROL 3 = 41
OSD ALT 1 = 42
OSD ALT 2 = 43
OSD ALT 3 = 44
NAV CRUISE = 45
MC BRAKING = 46
USER1 = 47
USER2 = 48
LOITER CHANGE = 49
