### ISSUE TITLE
Remove MOTOR_STOP on Multirotors

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#4633]
**MOTOR_STOP** on multirotors is harmful and dangerous. Remove support for it when multirotor or tricopter platform type is selected

**Comment by tgreer** [comment]
I agree with this, there is 0 reason really for this feature in a multi. It's just a large risk.

**Comment by digitalentity** [comment]
Given our plans to remove stick arming (#4583) - uses of `MOTOR_STOP` on multirotors become very limited.

**Comment by digitalentity** [comment]
Removed!
