### ISSUE TITLE
tricopter cc3d revo

### ISSUE THREAD

**Issue by ricardovalmeida** [iNavFlight/inav#4645]
![Sem título](https://user-images.githubusercontent.com/34948101/56761618-2a984400-6774-11e9-8310-57a9c98b6e0d.png)
hi dear friends
I mounted a tricopter using the cc3d revo board.
I wish I could use the s4 output to trigger a location buzzer. Output s4 does not accept servo mix, motor mix only. this can be changed to use the s4 output with servo mix.
thank you.
Ricardo Almeida.

**Comment by DzikuVx** [comment]
No, this is not possible, pins can not be assigned at will. 
Full explanation over here https://www.youtube.com/watch?v=v4R-pnO4srU

**Comment by ricardovalmeida** [comment]
![20190428_121009](https://user-images.githubusercontent.com/34948101/56866477-f27d4500-69af-11e9-8cdd-4db7d2a00e12.jpg)
![20190428_121025](https://user-images.githubusercontent.com/34948101/56866484-0c1e8c80-69b0-11e9-985b-0a25140cbd80.jpg)
[Tricoptero.zip](https://github.com/iNavFlight/inav/files/3125134/Tricoptero.zip)

ok thank you.
I tested my tricoptero Saturday 27/04/2019.
the tricoptero flew very well the original PID parameters worked very well, I had to make adjustments only in the PID, Roll, Pitch, Yaw.
Would you have any suggestions on how to put the location buzzer,
Thank you.
If someone wants to mount a tricopter like my follows photos and construction files I made it in the 3D printer.
