### ISSUE TITLE
IBUS Telemetry: Temperature displays wrongly

### ISSUE THREAD

**Issue by georgekucher** [iNavFlight/inav#4654]
## Current Behavior

After updating to version 2.1, FC temperature displayed on my transmitter shows from ~3.1 to ~4.3. It wasn't so before, when I was on 2.0.
![viber image 2019-04-28 , 00 23 27](https://user-images.githubusercontent.com/14803952/56855399-26744e00-694f-11e9-9060-b8e545ad4471.jpg)

## Steps to Reproduce

1. Upgrade to 2.1
2. Enable IBUS telemetry.
3.
4.

## Expected behavior

Temperature shows reasonable values. 
## Suggested solution(s)

Fix this issue)
## Additional context

[Dump](https://pastebin.com/VW3zqf43)
---

- FC Board name and vendor: INAV/MATEKF722 2.1.0 Mar 24 2019 / 22:52:35 (65b0ec142)
- INAV version string: GCC-7.1.0

**Comment by shellixyz** [comment]
This is a know issue. It has been fixed already in 2.2 dev. Thanks for the report

**Comment by georgekucher** [comment]
Thanks @shellixyz 
Could you please provide a link to it?

**Comment by shellixyz** [comment]
A link to a build of 2.2 dev or a link to the PR of the fix ?

**Comment by georgekucher** [comment]
To the reported bug

**Comment by georgekucher** [comment]
Or there wasn't?

**Comment by shellixyz** [comment]
It is #4504

**Comment by georgekucher** [comment]
ohh. I was looking in issues. thanks.
btw which temperature (what unit) is sent to ibus?

**Comment by shellixyz** [comment]
It is decidegrees centigrade (with an offset because the radio expects an unsigned integer)

**Comment by georgekucher** [comment]
no, I mean is it imu or baro or any else temperature))

**Comment by shellixyz** [comment]
Baro temperature if there is one or gyro temperature otherwise

**Comment by georgekucher** [comment]
thanks)
