### ISSUE TITLE
PH rcCommands strange readings

### ISSUE THREAD

**Issue by xdigyx** [iNavFlight/inav#467]
Today by chance I noticed that in PH mode after I moved pitch/roll stick a bit more and release it then my copter bounces like it would be too high I gain. I did check the same stick movement in angle mode and no bounces here.
Made a log and viewed it to see PID reaction, but noticed that after main stick movement there are another stick oscillating movements which I did not do. These can be seen as rcCommands roll/pitch depending on what movement had been done.

Do you have it too?
FW ver 1.1.

**Comment by bk79** [comment]
Bounces like breaks and get back?

Il 15/ago/2016 18:22, "xdigyx" notifications@github.com ha scritto:

**Comment by xdigyx** [comment]
Say more like oscillations. The stick movements were made for a short time 0.5-1s so the model actually does not move much, just about to change it's inclination.
![pic](https://cloud.githubusercontent.com/assets/6666245/17674610/9924ab2a-6326-11e6-8376-e4fe91932d25.jpg)

**Comment by digitalentity** [comment]
This is normal. PH works by overriding stick input.

**Comment by DzikuVx** [comment]
@xdigyx could you publish BBlog of that exact case. I have an theory here I want to confirm
