### ISSUE TITLE
Not able to use more than two Servos 

### ISSUE THREAD

**Issue by pfzetto** [iNavFlight/inav#4673]
Hey,
I've built a Quadcopter with an F3 Flight Controller Deluxe and INav. Now I want to set up a gimbal next to my retractable landing gear. Why are my Servo outputs starting at s7 when s5 and s6 are empty??
![grafik](https://user-images.githubusercontent.com/45522985/57155011-97e24f80-6dda-11e9-9b4f-b817176ab3a7.png)

Thanks for any help.

**Comment by digitalentity** [comment]
Because you can not randomly assign motors and servos around to any outputs. Outputs S3-S6 of this board can **all** be either motors or servos - this is a hardware limitation.
