### ISSUE TITLE
F405 wing OSD lacks parameters

### ISSUE THREAD

**Issue by letruong6006** [iNavFlight/inav#4674]
I am using F405 Wing. INAV 2.1.4, has updated the latest software for Fc. when i enter the OSD section. I don't see the arrow indicating the direction of the home, the distance of the home, the GPS parameter .... what is the error? I need help
![image](https://user-images.githubusercontent.com/48900198/57172073-53d86480-6e45-11e9-959f-28397fd5e2bd.png)
![image](https://user-images.githubusercontent.com/48900198/57172075-5cc93600-6e45-11e9-81d7-b03ea12292cf.png)
![image](https://user-images.githubusercontent.com/48900198/57172080-6357ad80-6e45-11e9-8199-20f6153e4b70.png)

![image](https://user-images.githubusercontent.com/48900198/57172084-6e124280-6e45-11e9-8148-f64fbd64b462.png)

**Comment by letruong6006** [comment]
![image](https://user-images.githubusercontent.com/48900198/57172088-900bc500-6e45-11e9-9fd6-0c3cbb300f1e.png)

**Comment by letruong6006** [comment]
![image](https://user-images.githubusercontent.com/48900198/57172162-964e7100-6e46-11e9-9793-1779597c128a.png)

**Comment by shellixyz** [comment]
![image](https://user-images.githubusercontent.com/4030264/57179610-d7af4280-6e7f-11e9-91b6-7a0f86e81c8d.png)

**Comment by letruong6006** [comment]
thank you shellixyz. I found them in OSD
