### ISSUE TITLE
Poshold constantly overshooting

### ISSUE THREAD

**Issue by pfzetto** [iNavFlight/inav#4678]
Hey,
My Copter has now a working and uninfluenced magnetometer. For a few minutes I tried using POSHOLD for the first time. The Copter corrected itself but was overshooting the target every time. 
My PIDS:
![grafik](https://user-images.githubusercontent.com/45522985/57181796-b444c180-6e98-11e9-83bd-bebaa46052ed.png)

Thanks

**Comment by giacomo892** [comment]
Without providing any details it's hard to tell. Try to dial in the Position/Velocity XY and join telegram / facebook for better support.
