### ISSUE TITLE
Profile include Servo settings

### ISSUE THREAD

**Issue by pfzetto** [iNavFlight/inav#4685]
I would like to be able to save Servo Settings in Profiles to overcome Flight Controller with just a few Servo ports, to get multiple settings for different scenarios

**Comment by DzikuVx** [comment]
Servo settings on servo mixer? INAV 2.2 will have a mechanism that will allow to switch mixer rules on/off with a rc channels and other inputs. On the other hand, servo settings (min/max/middle) are profile independent. Please wait until 2.2 and check if that suits your needs
