### ISSUE TITLE
Extend blackbox flight modes

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#469]
Catch up with Betaflight how flight modes are saved in BB logs. See 6343da6f091dde3e5eec2cad1ac054840166a489
- [x] cleanup unused box modes (GOVERNOR, LEDMAX, more?)
- [ ] change `rcModeActivationMask` to uint64_t
- [ ] in blackbox , send `rcModeActivationMask` instead of `flightModeFlags`
  - [ ] remember to send 64 bits
- [ ] merge iNavFlight/blackbox-log-viewer#2

**Comment by digitalentity** [comment]
Keep in mind that MSP_STATUS also returns current active box modes (similar to `rcModeActivationMask`) and it's 32-bit integer. Should be deprecate MSP_STATUS or break compatibility with CF/BF?

**Comment by stronnag** [comment]
MSP_STATUS is used by ground stations (and presumably OSDs). Please don't break it .... at least without lots of warning.

**Comment by DzikuVx** [comment]
I belive we already have this covered in latest versions
