### ISSUE TITLE
Permanent AIRMODE means stabilisation in MANUAL mode ?

### ISSUE THREAD

**Issue by Bogdanu2018** [iNavFlight/inav#4691]
Permanent AIRMODE means stabilisation in MANUAL mode ?
Is there any impact on MANUAL mode if I activate Permanent AIRMODE ?
I'm asking because my plane is flying very out of trim in MANUAL mode even if the elevons are trimmed straight on plane. I had Permanent airmode on and maybe because bad board position the fc tries to stabilize wrong my plane in MANUAL mode ?
I have F405 Matek WING FC with last INAV.
Thank you!

**Comment by DzikuVx** [comment]
Manual mode does not use stabilization at all so it's not relevant

**Comment by Bogdanu2018** [comment]
So in Manual mode the plane should fly by itself and Permanent AIRMODE is only permanent for stabilisation modes ? Is that correct ?

**Comment by Bogdanu2018** [comment]
I'm asking because my plane doesnt fly leveled in MANUAL mode and just wanted to be sure is a plane issue not the flight controller interacting somehow

**Comment by giacomo892** [comment]
MANUAL mode is just pilot inputs forwarded to the surfaces / motors.

**Comment by dovichino** [comment]
I did my first flight yesterday with inav. I also fly in manual and I just see that I have this feature activated but I do not know what it means on an plane. I find that my plane is flying very badly, crookedly, it turns strangely since I have the flight controller.
