### ISSUE TITLE
Re-assess barometer weight and logic for altitude fusion

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#4692]
When accelerometer weight is reduced by #4681 or manually, barometer influence is not enough to maintain altitude consistently and reliably. 

TODO:

- Re-evaluate barometer weight and find a better default
- Re-evaluate barometer fusion into altitude (possibly extract climb rate from the raw data and correct velocity from that data separately).

**Comment by shota3527** [comment]
@digitalentity 
Is #4681 a good fix for the problem? 
It is not reducing the accelerometer weight but set the measured acceleration to 0. Which means velocity/position estimation by accelerometer is also 0. Then value from accelerometer and baro is fighting with earth other.
