### ISSUE TITLE
NAV - When in POSHOLD stick input is moving the quead slower than in normal ANGLE

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#47]
Reported by @skaman82, confirmed.

**Comment by skaman82** [comment]
I also noticed this in RTH mode

**Comment by digitalentity** [comment]
Yes, it's the same issue. Position in POSHOLD and RTH is controlled by the same code (XY-position controller) and pilot input is treated the same way in both modes.

**Comment by digitalentity** [comment]
@skaman82 
Should be fixed in ad4b1dc865485a74451075323260b0f81f9a1c2a. Will be included in today's **1012** buid. Feel free to reopen the issue if issue will persist.
