### ISSUE TITLE
Implement Jeti Ex Bus Code from BF?

### ISSUE THREAD

**Issue by RoadyFPV** [iNavFlight/inav#4711]
Is it possible to implement the Jeti Ex Bus Code from BF to Inav?

In BF Ex Bus works great with Telemetry.

**Comment by shellixyz** [comment]
What's the issue with the JetiEx in iNav ?

**Comment by RoadyFPV** [comment]
I don't recieve telemetry values
on bf 4.0 there is a new optimized ex bus code

**Comment by bangkokpete** [comment]
Yes, great feature. all telemetry values are send back to the jetimtransmitter. (incl. GPS data etc.)would be super, if we could get this for INAv as well. Connection via TX2 on my F722SE for telemetry send down to transmitter.
thanks
Peter

**Comment by RoadyFPV** [comment]
Hi,
have a coder time to implement this before it closed from bot?
The code works great for telemetry. I use it on betaflight for month without any issue.

It would be nice to have telemetry in inav.

**Comment by teckel12** [comment]
@RoadyFPV It may not only be time to do it.  It could also be the lack of hardware to actually test the code.  It typically doesn't work well to try to code something without the hardware to test.  therefore, this will probably require someone with the hardware to write the code (which includes porting it from Betaflight).

**Comment by RoadyFPV** [comment]
Testing would not be a problem. Unfortunately, I can not write any kind of code.
Hardware i can to test is Omnibus F7 v2 and Matek F722se.

Maybe that would be helpful

**Comment by teckel12** [comment]
@RoadyFPV The hardware really needs to be in possession of the programmer to develop.  It makes any task 100x more complicated when the hardware isn't available to the developer.  This is what I mean by "lack of hardware to actually test".  This is probably one of those issues where someone with this hardware needs to be inspired to write the code.  Shy of that, it's not likely.

**Comment by Christoph-Hofmann** [comment]
a friend of mine has the same Problem, the telemetry is not working :-( on jeti
