### ISSUE TITLE
support for: MATEK F411 one   SPI receiver

### ISSUE THREAD

**Issue by X-FOOT** [iNavFlight/inav#4719]

**Comment by X-FOOT** [comment]
i would like to ask for support for the "matek F411 one" flightcontroller. it has a integrated SPI receiver witch works with the Frsky_X protocol. Betaflight 4.0 has it already integrated in there firmware. I hope someone can do that for inav too, so i can use this board.

**Comment by X-FOOT** [comment]
also Frsky_D protocol (taranis D8 mode) for spi receiver. As this works the best

**Comment by diego0815** [comment]
Are there any news regarding this feature request? It sounds like a good feature to me, especially also for fixed wings.

But it seems the SPI framework in inav seems to be incomplete right now?
