### ISSUE TITLE
OLED Connection?

### ISSUE THREAD

**Issue by kerrycorcoran** [iNavFlight/inav#4726]
**Geekcreit® 0.96 Inch 4Pin White IIC I2C OLED Display Module 12864 LED For Arduino OLED Board** (https://us.banggood.com/Wholesale-Warehouse-0_96-Inch-4Pin-White-IIC-I2C-OLED-Display-Module-12864-LED-For-Arduino-wp-Usa-958196.html?akmClientCountry=America&rmmds=myorder)
**Matek Systems F405-WING Flight Controller** (https://us.banggood.com/Wholesale-Warehouse-Matek-Systems-F405-WING-New-STM32F405-Flight-Controller-Built-in-OSD-for-RC-Drone-wp-Usa-1292190.html?akmClientCountry=America&rmmds=myorder)

I have connected

- 5v (OLED) to 5v (Flight Controller)
- GND (OLED) to GND (Flight Controller)
- SCL (OLED) to CL2 (Flight Controller)
- SDA (OLED) to DA2 (Flight Controller)

and enabled OLED in Inav.

When I power the flight controller I don't get any activity or display on the OLED.

Any insight appreciated.

**Comment by giacomo892** [comment]
This is not a channel to ask for support.

Use Facebook and Telegram the next time. As for matek wiring guide. Use I2C1 bus.

![image](https://user-images.githubusercontent.com/20860004/58078430-041ccb80-7baf-11e9-9c0c-752969ac93ea.png)
