### ISSUE TITLE
Convert to parameter groups

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#473]
Dependent on issue https://github.com/iNavFlight/inav/issues/472 -Preparation for conversion to parameter groups

**Comment by digitalentity** [comment]
Looks like #472 is done. Unblocking.

**Comment by digitalentity** [comment]
@martinbudden what's the progress of this?

**Comment by martinbudden** [comment]
I haven't done any work on this for a while. All the preparatory work has now been done, so getting it finished should not be too much work. Probably several evenings of solid work.

**Comment by digitalentity** [comment]
Take your time, we'll probably release 1.4 without PGs, I don't see this as a big issue.

**Comment by martinbudden** [comment]
One of the motivations was making it easier to port code over from Cleanflight. But now iNav and betaflight are ahead of Cleanflight in most areas that is less important.

I'll probably do PGs in betaflight first, since there are some guys actively working on the configurator there, and also there is more flight testing. Once that is done, porting to iNav should be very straightforward (although there will be adding new iNav specific PGs).

**Comment by DzikuVx** [comment]
@martinbudden can we assume this is done and ticket can be closed?

**Comment by martinbudden** [comment]
Yes, we can close.
