### ISSUE TITLE
Servo moving on its own 

### ISSUE THREAD

**Issue by Insanity22** [iNavFlight/inav#4732]
Hi, I am new to Inav, I build a S800, but the servers are rising the aileron to full extend slowly, I have air mode off and in manual, but particle the right servo is rising. 
When I plug out and in the battery the servers reset but slowly rising... 
Using last Inav on a F4prov3, any ideias, already changes the servos.
Thanks

**Comment by giacomo892** [comment]
Hi. This is not a channel to ask for support.
Use Facebook and Telegram the next time. 

If servo move in manual you either have your radio not configured correctly, using the wrong pad on the FC or mixing issues.
