### ISSUE TITLE
Port notch filter from Betaflight

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#474]
Port notch filter from betaflight 86626acbdf118f783188e8ae42fdfea985d53e52

**Comment by martinbudden** [comment]
@DzikuVx , did you have a pull request for this?

**Comment by DzikuVx** [comment]
No, it's only a reminder

czw., 8.09.2016, 20:14 użytkownik Martin Budden notifications@github.com
napisał:

**Comment by martinbudden** [comment]
OK.

**Comment by digitalentity** [comment]
Supporting code for notch filter done. Now we need core to actually apply it to gyro data.

**Comment by digitalentity** [comment]
Guys, what do you think? Is this worth pushing into 1.4?

**Comment by DzikuVx** [comment]
I see no reason to do it

wt., 15.11.2016 o 15:23 użytkownik Konstantin Sharlaimov <
notifications@github.com> napisał:

**Comment by martinbudden** [comment]
Yes, postpone this to 1.5. Let's get 1.4 out the door.

**Comment by miradarya** [comment]
As this currently doesn't seem to be linked to any milestone, I was wondering if there are still plans to implement the notch filter. I personally think that large quads using inav would benefit greatly from notch filtering due to requiring more D but being noisier at the same time.
