### ISSUE TITLE
Mistake in documentation?

### ISSUE THREAD

**Issue by EnsignCrasher** [iNavFlight/inav#4744]
Was reading through this page: https://github.com/iNavFlight/inav/wiki/Tune-INAV-PIFF-controller-for-fixedwing

In the end, there is a short abstract telling: 

> If your plane over corrects when RTH is engaged, try increasing nav_fw_pos_xy_p and/or increasing nav_fw_pos_xy_i. Good values to start: "set nav_fw_pos_xy_p = 50"; "set nav_fw_pos_xy_i = 5". Also you can lower "nav_fw_pos_xy_d". The behaviour of the plane is very different with or w/o wind, so it is necessary to test and tweak parameters in both scenarios.

Shouldn't that be, "if your plane corrects not enough when RTH is engaged, try increase...."?
Was just a little confusing to me

**Comment by digitalentity** [comment]
No, this is correct. If the plane overshoots when turning (symptom is a wave-like flight path) - it means there is not enough P and I to turn. When P & I are too high the symptom is fast wandering left-right by a small amount (less than 5 deg).

**Comment by EnsignCrasher** [comment]
Ah, very good explanation :)
I would say, copy-pasteable for the documentation!

**Comment by EnsignCrasher** [comment]
If its ok for you, i can make a PR from it

**Comment by digitalentity** [comment]
Absolutely!

**Comment by EnsignCrasher** [comment]
ah didn't even need a PR for wiki pages ;)
