### ISSUE TITLE
iNav 2.2.0 RC1 Release notes missing key info for Mixer

### ISSUE THREAD

**Issue by noagendafpv** [iNavFlight/inav#4762]
**Current Behavior**
iNav 2.2.0 release notes say to get Diff from current iNav, then paste it once 2.2.0 is flashed. The iNav 2.1.0 mixers in CLI are not compatible with iNav 2.2.0.

**Desired Behavior/Suggested Solution**
Correct the release notes to state that the Mixer in the DIFF either needs edited to add the new CLI Mixer rules. Or to state that the Mixer needs to be redone after flash to iNav 2.2.0

**Who does this impact? Who is this for?**
All newer users that will try to upgrade only by pasting their DIFF, without going in and checking their iNav settings before trying to fly.

**Comment by giacomo892** [comment]
Closing. fixed by #4763
