### ISSUE TITLE
2.2 RC1 - RGB LED Strip Control broken on Matek F405SE

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#4783]
## Current Behavior
RGB LED Control seems not to work on Matek F405SE (Wing) - LEDs just randomly flashing or flickering.

## Steps to Reproduce
1. Setup RGB LEDs on a F405SE Wing with INAV 2.2 RC1
2. Power on board
3. if some LEDs will power up at all (depends on the LEDs) they will randomly shining or flickering

4. all fine when flashing back to 2.1 
5. same with scratch setup LEDs or restoring LED settings from 2.1

## Expected behavior
LED control behavior should be the same as in 2.1?

## Suggested solution(s)
Check for LED control output on Matek F405SE Wing

## Additional context
Tested and confirmed this with 2 flight controllers and 2 known good sets of RGB LEDs. 

INAV 2.1 on spare board and spare LED stripe: https://1drv.ms/v/s!Ar6QsGgoXRgqnMNYSTStjI25cHZJzw
INAV 2.2 on same board and same LED stripe: https://1drv.ms/v/s!Ar6QsGgoXRgqnMNZpxHEp5onqrXnrw

---

- FC Board name and vendor: INAV/MATEKF405SE 2.2.0 May 26 2019 / 19:56:35 (a713b63e4)
- INAV version string: GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by b14ckyy** [comment]
Still the same in RC2

**Comment by digitalentity** [comment]
Fixed by #4805. Closing
