### ISSUE TITLE
2.2 RC1 CMS cannot change the FF values on fixed wings

### ISSUE THREAD

**Issue by OlivierC-FR** [iNavFlight/inav#4788]
... instead it shows the lines for P+I+D as if it was a multirotor, instead of P+I+FF.
https://www.dropbox.com/s/u7cq3l3zptzyeiv/ARwing.dump.txt

**Comment by b14ckyy** [comment]
You need the configurator 2.2 too.

**Comment by OlivierC-FR** [comment]
CMS is the OSD menu, Configurator version is not involved !

**Comment by digitalentity** [comment]
Fix merged.
