### ISSUE TITLE
Integrating Smart Battery Batmon interface for iNav

### ISSUE THREAD

**Issue by echoGee** [iNavFlight/inav#4799]
We are working on a smart battery interface, Batmon, which is a kit connected to each battery.
![Batmon Image](https://storage.ning.com/topology/rest/1.0/file/get/641584426?profile=original)

**Batmon features:** 

1. Inbuilt Coulomb counting for accurate power draw (and hence power remaining) for the cells
2. Accurate monitoring of individual cell voltage ( precise to 50mV or better) 
3. Onboard temperature monitoring
4. 9gm weight 
5. Connects to Pixhawk i2c bus with stock firmware to read total battery voltage, temperature, current. Custom pixhawk firmware enables monitoring cell voltages and many other battery parameters.
6. Onboard cell balancing. 
7. Switchable low-power led display for convenient display of battery vitals (~3mA / 40V with display on)
8. Delayed automatic discharge of batteries to voltage safe for storage to enhance battery life. 

We want to discuss good methods for integrating Batmon into iNav echosystem. Is there a good team/forum to discuss this ?

**Comment by shellixyz** [comment]
Very nice. Here is the right place to discuss. You can also join [iNav's Telegram channel](https://t.me/INAVFlight) where all developers are present.
