### ISSUE TITLE
Chance Voltage / Current Scaling without Reboot

### ISSUE THREAD

**Issue by FPVZaphod** [iNavFlight/inav#4802]
## Current Behavior
Changing the values for voltage- / current scaling or offset requires FC reboot

## Desired Behavior
Instantly use changed battery settings when changing them, or at least after pressing "Save", but without FC reboot

## Suggested Solution
And "Update" Button for the battery settings, enabling the new values instantly. Or an own "Power / Battery" Tab in the Configurator, which does't require a restart.
Maybe also the possibilty to update the values by CLI without reboot, until the Current Sensor Calibration finished. Then save and reboot.

## Who does this impact? Who is this for?
It will speed up the current sensor calibration, because there is no need to restart and reconnect the FC.

**Comment by teckel12** [comment]
This would be a very handy feature.
