### ISSUE TITLE
GSM SMS telemetry: negative coordinates are not displayed correctly

### ISSUE THREAD

**Issue by shellixyz** [iNavFlight/inav#4806]
The decimal part starts with `-` and the coordinates with 0 integer part are displayed as positive.

Reported there: https://github.com/iNavFlight/inav/pull/4388#issuecomment-500162800

**Comment by shellixyz** [comment]
We might want to use the +code instead of coordinates as suggested by @fiam

**Comment by mistyk** [comment]
Yes +code chould be easier to manage and link should be shorter for additionnal infos
