### ISSUE TITLE
In the latest Inav 2.2 RC2  , the voltage scale shifted 1 decimal.   voltage scale:110 needs to be 1100 to get correct readment

### ISSUE THREAD

**Issue by X-FOOT** [iNavFlight/inav#4811]
## Current Behavior
instead of voltage scale:110  now i nead to change it to voltage scale: 1100 to get the correct voltage readment

## Steps to Reproduce

1. I changed from inav 2.1 to 2.2 RC2
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by shellixyz** [comment]
That's normal it has been changed since 1.9. Now you have 10 times more precision. Just multiply your old scale by 10 if you want to use it

**Comment by X-FOOT** [comment]
ok, i did that. thanks
