### ISSUE TITLE
`diff` doesn't output differences in battery profile 2 & 3

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#4827]
## Current Behavior
`diff` doesn't list battery profile 2 & 3 changes

## Steps to Reproduce
1. Change battery profile 2 & 3
2. `save`
3. `diff`
4. Doesn't list changes to battery profile 2 & 3

## Expected behavior
`diff` should list all changes to defaults, unless I'm mistaken.  I didn't check to see if profile changes were being listed with `diff`.

- MATEKF722SE
- 2.2.0-RC2

**Comment by shellixyz** [comment]
You need to use `diff all` if you want the diff to include all profiles and battery profiles

**Comment by teckel12** [comment]
Perfect!  `diff all` from now on.
