### ISSUE TITLE
Aileron differential Mixer for fixed wing

### ISSUE THREAD

**Issue by ShawnzAZ** [iNavFlight/inav#4834]
## Current Behavior
Currently you can set the weight of the servo but not independently for each side of center.

## Desired Behavior
It would be nice if the mixer could allow Center to full right to have full throw one direction and X% throw going the other direction from center.

## Suggested Solution
I would suggest the servo weight for each direction that would default to 100% both directions.  I should be able to weight the servo for say 100% throw in the up direction and maybe 50% (or whatever value is input) throw when moving down from center, per servo.

This would obviously only work with each aileron on it's own output.

## Who does this impact? Who is this for?
This is especially useful for flat bottom or semi-symmetrical airfoils to combat adverse yaw.   For models such as the Skyhunter that do not have a rudder it will help to better coordinate the turns and make the craft fly more efficiently.

## Additional context
There are ways to do this mechanically, but many users are used to doing this in their radio's mixer.   It would be nice to be able to accommodate in Inav.

It might also work with the current mixer to simply offset the serve center position and adjust the aileron push rod to center the control surface.   I do something similar in the INav 2.1 mixer to leverage the flaperon mix with conventional flaps.   I just set the 'center' to 1000, setup the linkage to 'flaps up' at this servo position and use a weight of 200 for full servo deflection for 'flaps down'.  I just don't know if auto trim will play nice with this.

**Comment by DzikuVx** [comment]
It can be already done with either:
* changing servo min/max parameters which will cause servo output to be scaled between center and min/max
* use of INAV 2.2 Logic switches and creating separate rules when rule input is >= or < center
