### ISSUE TITLE
Stabilized Throttle on Servo output instead of motor output

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#4840]
Stabilized Throttle mixed to a servo channel does not work any more at inav 2.2 RC2.
If I set the same servo to the RC throttle, then it works.

At a earlier 2.2 test version it worked.

Is this a bug or should stablizied throttle only work to motor outputs now?

**Comment by DzikuVx** [comment]
@Ralfde stabilized throttle is taken from the first motor. If no motors are configured, stabilized throttle will not work. This is kind of stupid I agree

**Comment by Ralfde** [comment]
Thanks for the answer. Could this be maybe changed in the future?

**Comment by DzikuVx** [comment]
It will be fixed in a next INAV rease and motor mixer will not be required for STABILIZED_THROTTLE to work
