### ISSUE TITLE
Custom OSD fonts (in case that some find them usefull) [NOT an ISSUE]

### ISSUE THREAD

**Issue by FasaArg** [iNavFlight/inav#4845]
<img width="271" alt="small" src="https://user-images.githubusercontent.com/20319132/59558004-16c3ce00-8fbe-11e9-9703-e4f5cdc63370.png">
<img width="272" alt="big" src="https://user-images.githubusercontent.com/20319132/59558005-16c3ce00-8fbe-11e9-9f1d-09be62eaa102.png">

https://youtu.be/DyJLByED9rI

[INAV FONTS.zip](https://github.com/iNavFlight/inav/files/3293735/INAV.FONTS.zip)

**Comment by teckel12** [comment]
:+1:

**Comment by DzikuVx** [comment]
@FasaArg I have to close this one since fonts are managed by configurator. I invite you to add them to configurator projects

**Comment by cmanley** [comment]
Uh, there are 30 characters horizontally. How can the center marker be in the center?
