### ISSUE TITLE
Additional flight mode: physical limits with minimum & maximum altitude, maximum range etc

### ISSUE THREAD

**Issue by brandtaucher** [iNavFlight/inav#4847]
## Current Behavior
Currently the only mode to hold the altitude is altitude hold. However, this does not always give the desired security.

## Desired Behavior
It would be desirable that you can generally activate a minimum height that is not undercut.

## Suggested Solution
There should be a new mode "Minimum_Altitude_Mode", which acts as an additional mode on all other modes. He should never fall below a set height when activated via a switch. Once the minimum height is reached, it will continue to fly at the minimum altitude. You can specify a throttle setting that will help maintain this altitude (Minimum_Altitude_Throttle).

## Who does this impact? Who is this for?
For example, "Minimum_Altitude_Mode" is possible in Parrot Disco. But it is also useful in all multicopters. It helps with the following scenarios:
1. Beginners have more security
2. Aerobatics has an additional safety net
3. More security with fpv flight (perspective is sometimes misleading)
4. Altitude hold is improved. Due to variations in altitude, Altitude Hold may cause you to lose too much altitude.
5. etc

## Additional context
The text was generated using google translator. I hope you can understand everything. Please excuse.
Thank you!

**Comment by nkorls** [comment]
and maximum distance limit
and rth after input has not changed for more than 10s

**Comment by brandtaucher** [comment]
New name: Mode: phsyical limits

1. Minimum Altitude: in case - hold min. altitude 
2. Maximum Altitude: in case - hold max. Altitude
3. Maximum Range: in case - RTH
4. No pilot reactions: in case - RTH

**Comment by mickey2011** [comment]
Maybe needs to be part of/merge with 4442

**Comment by brandtaucher** [comment]
4442 is included in this. Physical Limits is an additional Feature for all modes.

**Comment by brandtaucher** [comment]
4442 is included in this. Physical limits is an additional function to all modes.

**Comment by ghost** [comment]
I don't think there should be a new mode. Instead of that, there could be new optional settings for the altitude hold mode as you stated.

**Comment by brandtaucher** [comment]
Nice that you are dealing with it. But you did not understand what it is about. If minimum altitude is enabled, you will not be able to land, etc. Therefore, it is necessary that there is a status that you can deactivate again.
Besides, it's not just about the altitude, but also the distance.

**Comment by goodshort** [comment]
Interesting request, I'm following! I recently crashed into bramble trees and such feature would have save my legs. I could see it used as well while flying over water.
