### ISSUE TITLE
can't calibrate BN-880's magnometer (HMC5883)

### ISSUE THREAD

**Issue by goodnerdboy** [iNavFlight/inav#4856]
## Current Behavior
Mag's icon stays red and the calibration doesn't feed the calibration's parameters

## Steps to Reproduce
1. Install BN-880 on Foxeer F722dual
2. Setup ports, configuration, etc
3. As the auto mode of mag doesn't work, force it to HMC5883
4. try to calibrate

## Expected behavior
A correct calibration happens.
For information, if it can help, these steps work with Betaflight 4.0.3. At least it shows it is not a faulty mag.

## Suggested solution(s)
Unfortunatly i have no clue sorry.

## Additional context
As i wrote above, the steps work in Betaflight 4.0.3 and the readings from the mag look correct. This probably means the mag is not faulty and the connections are correct.

https://pastebin.com/zmkBp7Rr
---

- FC Board name and vendor:
# INAV/FOXEERF722DUAL 2.2.0 Jun 18 2019 / 14:57:00 (5e5551bd3)
- INAV version string:
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by digitalentity** [comment]
Please provide a wiring diagram showing how compass is connected

**Comment by goodnerdboy** [comment]
Hi.
I followed the wiring diagram provided by Foxeer.
Here it is :

![](https://oscarliang.com/ctt/uploads/2018/11/Foxeer-F722-Dual-Flight-Controller-fc-connection-wiring-diagram.jpg)

**Comment by digitalentity** [comment]
Thanks. Will investigate. Fortunately I have an FC at hand

**Comment by goodnerdboy** [comment]
Many thanks!
Tell me if I can be of any help.

**Comment by goodnerdboy** [comment]
Hi @digitalentity 
Did you have anytime to investigate this ?
Is there any way I can help?

**Comment by goodnerdboy** [comment]
So this target declares the Baro on i2c 1 and Mag on i2c 2.
Unfortunately only i2c 1 is associated to pins, so I guess this target allows to connect an external barometer but not a compass.

**Comment by goodnerdboy** [comment]
Should it be modified to match the manufacturer’s wiring diagram or is it purposely like that?

**Comment by goodnerdboy** [comment]
Hello.
Any update on this one?

**Comment by digitalentity** [comment]
Please test this hex

[inav_2.2.1_FOXEERF722DUAL.zip](https://github.com/iNavFlight/inav/files/3356764/inav_2.2.1_FOXEERF722DUAL.zip)

**Comment by goodnerdboy** [comment]
It seems to work so far, I was able to set it up and calibrate it.
Thanks :)

**Comment by digitalentity** [comment]
Thanks for testing. Fixed by #4908
