### ISSUE TITLE
DALRC F722 DUAL Firmware ?

### ISSUE THREAD

**Issue by SlavkoYT7SED** [iNavFlight/inav#4860]
Is there any chance that firmware for DALRC F722 DUAL STM32F722RGT6 F7 Flight Controller will soon be available?
Thank you !

**Comment by SlavkoYT7SED** [comment]
Is there any chance that firmware for DALRC F722 DUAL STM32F722RGT6 F7 Flight Controller will soon be available?
Thank you !

**Comment by SlavkoYT7SED** [comment]
Is there any chance that firmware for DALRC F722 DUAL STM32F722RGT6 F7 Flight Controller will soon be available?
Thank you !

**Comment by digitalentity** [comment]
@SlavkoYT7SED 
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
