### ISSUE TITLE
Changed definition of MAVLINK breaks stuff

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#488]
Changing the definition in a gratuitously incompatible way

```
FUNCTION_TELEMETRY_MAVLINK   = (1 << 9), // 512
```

from the prior 256 **without announcement** breaks lots of stuff:
- Working configurations
- Configurator does not show it 
- Setting the old value (e.g. 257) wipes serial settings

Is it too hard to make these changes in a backwards compatible fashion ?

http://www.rcgroups.com/forums/showpost.php?p=35534914&postcount=7719

**Comment by digitalentity** [comment]
@martinbudden what's FUNCTION_PASSTHROUGH ?

**Comment by martinbudden** [comment]
@digitalentity , I presume it is to do with serial passthrough, that is the ability to reprogram the ESCs via the configurator. I also presume it was added by betaflight, but why it was not added on the end, I don't know

**Comment by stronnag** [comment]
Ah, so we have a real mess if this is embedded in the closed source bllheli application?  And maybe have no choice other than an ABI break in iNav?

**Comment by digitalentity** [comment]
I suggest we merge #489 to keep things backward compatible and look at `FUNCTION_PASSTHROUGH` when we start to actually merge it into INAV. I'm going to stick to [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) for now - passthough works fine wighout it so we probably don't need the `FUNCTION_PASSTHROUGH`, at least not yet.

**Comment by stronnag** [comment]
Indeed, the patched Cf configurator that embeds the BLHELI protocols for flashing / configuring ESCs works with MAVLINK == 256.

**Comment by digitalentity** [comment]
Thus I don't see a reason to keep `FUNCTION_PASSTHROUGH` breaking the established ABI.

**Comment by digitalentity** [comment]
Merging #489

**Comment by martinbudden** [comment]
Agreed. It's annoying that `FUNCTION_PASSTHROUGH` was not added in a compatible way.

It's all probably going to be moot soon anyway - there is a blheli-configurator under development which would supersede passthrough anyway.
