### ISSUE TITLE
BB error with Matek F722-SE

### ISSUE THREAD

**Issue by xabc1** [iNavFlight/inav#4890]
## Current Behavior
Having this error when opening the logs.

[![image](https://user-images.githubusercontent.com/38560024/60392484-4d5d2500-9b36-11e9-8d4e-ece78a7ee346.png)
](url)

Inav Firmware: Inav 2.2
FC: MatekF722SE
BB: Inav BB 2.3

Debug_mode GYRO is enabled.
[LOG00011_MatekF722SE.TXT](https://github.com/iNavFlight/inav/files/3342542/LOG00011_MatekF722SE.TXT)

I used another FC, this time Kakute F7 with the same setup and Debug_mode GYRO is also enabled. No problem in opening the logs.
[LOG00007_KakuteF7.TXT](https://github.com/iNavFlight/inav/files/3342547/LOG00007_KakuteF7.TXT)

**Comment by stronnag** [comment]
This is not  a firmware issues, it's a viewer issue, already fixed in the iNav blackbox tools https://github.com/iNavFlight/blackbox-tools/pull/9

A separate issue already exists for the iNav BB viewer https://github.com/iNavFlight/blackbox-log-viewer/issues/36

**Comment by stronnag** [comment]
fixed by https://github.com/iNavFlight/blackbox-log-viewer/pull/37
