### ISSUE TITLE
Add support for PX4FLOW (optical flow and rangefinder sensor)

### ISSUE THREAD

**Issue by SaschaIoT** [iNavFlight/inav#4905]
PX4FLOW seems to be the best available optical flow sensor on the market. It has an optical flow sensor and a Maxbotix MB1043 HRLV-MaxSonar-EZ4 directly attached.

Implementation suggestions:

It has an easy I2C interface, you can get with single I2C-call optical flow and sonar readings. Implement Optical Flow sensor driver and write rangefinder reading in atomic variable. In the Rangefinder driver read this variable and return. Use QGroundControl software to see optical flow image/video and make camera picture sharp.

[PX4FLOW informations](http://ardupilot.org/copter/docs/common-px4flow-overview.html)
[Firmware for PX4FLOW](https://github.com/priseborough/px4flow/tree/klt_flow)
[PX4FLOW Optical Flow code](https://github.com/chobitsfan/ardupilot/blob/px4flow_sonar/libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.cpp)
[PX4FLOW Rangefinder code](https://github.com/chobitsfan/ardupilot/blob/px4flow_sonar/libraries/AP_RangeFinder/AP_RangeFinder_PX4FLOW.cpp)

[Holybro PX4FLOW](http://www.holybro.com/product/px4flow/)

![PX4FLOW](https://user-images.githubusercontent.com/15450213/60756671-b0e8c600-a000-11e9-8aa2-a8a35a679e87.jpg)

[YouTube: PX4FLOW](https://www.youtube.com/watch?v=GgbhTXYg94s)

**Comment by vyalyh-oleg** [comment]
Hi. Could you kindly provide at least approximate schedule/firmware_version when the work on on support of this sensor is planned to start over.
Thanks.
