### ISSUE TITLE
inav 1.2rc2 does not define target max waypoints for SP EV

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#491]
Appear not to be picking up target defines. Max 15 on all platforms.

**Comment by digitalentity** [comment]
Not sure I can confirm the issue. The #define from target.h is the one being used in compilation. What target did you check?

**Comment by stronnag** [comment]
Apologies, EVO. Where it is missing. Other than that. EVo is now working well on all nav modes. No evidence of #431 on that target on my tricopter.

**Comment by digitalentity** [comment]
@stronnag do you have a spare SPRacingF3 to try replacing on your quad and see if #431 is still there? Same setup, same board family, but with a board from different batch.

**Comment by stronnag** [comment]
I have the quad here too. Still affected on the gps-debug branch. I'll reflash master and try that and report all findings in #431 when I get home.

**Comment by digitalentity** [comment]
Thanks

**Comment by digitalentity** [comment]
Fixed
