### ISSUE TITLE
mamba F405 more Mixer options

### ISSUE THREAD

**Issue by distractedfpv** [iNavFlight/inav#4919]
At the Moment it is only possible to use 2 Motors and 2 Servos or less, no other options.
This doesnt allow any kind of Airplane, Wing with a moving Camera or tricopter.

Mapping the 4 outputs like i want, so we can use the 4 outputs would be highly benefical.
As i understand those signal outputs this should be possible.

**Comment by DzikuVx** [comment]
This topic was already discussed multiple time the answer is: due to hardware design and timer assignments it is not possible to have any other configuration on this board than the one that are available.

You can watch why this is how it is here: https://www.youtube.com/watch?v=v4R-pnO4srU
