### ISSUE TITLE
Mamba405 - xm+ Sbus not working

### ISSUE THREAD

**Issue by distractedfpv** [iNavFlight/inav#4927]
mamba405 and xm+ not working

i have nothing changed on the hardware, in betaflight 4.0 everything works as intended. 
when i flash one of the two inav firmwares for the fc it shows random things on the receiver pad.
Port tab is correct, config tab is on sbus. 
so far i tried all combinations of:

firmware 
serialrx_inverted 
serialrx_halfduplex

the only time i got it to work was when i used the hardware uninverted sbus, but this pin is basically not useable because its not ment to be used and way too small, also as said in betaflight it works just fine with serialrx_inverted and serialrx_halfduplex set to OFF

**Comment by distractedfpv** [comment]
The Solution is here! well half of it
https://github.com/iNavFlight/inav/issues/4262#issuecomment-464488277

if i flash those .hex files sbus works like intended.

But this firmware doesnt allow servos so kwads only.
also i couldnt reflash after this firmware and needed to do a full chip erase.

So still not able to get a sbus mamba wing

**Comment by digitalentity** [comment]
Should be fixed by #4936. Firmware for testing is available in that PR
