### ISSUE TITLE
OmnibusF4: No dataflash chip found in 2.2.0/2.2.1

### ISSUE THREAD

**Issue by aquaforum** [iNavFlight/inav#4933]
In version 2.2.х the blackbox does not work because the firmware does not see the flash memory chip.
in version 2.1.0 there is no problem.

version
INAV/OMNIBUSF4 2.1.0 Feb 25 2019 / 16:53:02 (65b0ec142)
GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by digitalentity** [comment]
I don't have any OMNIBUSF4 board with a dataflash chip. Which board are you using?

**Comment by aquaforum** [comment]
this board
https://www.gearbest.com/flight-controller/pp_623876.html?wid=1433363
