### ISSUE TITLE
support "rssi_src_frame_errors"

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#4938]
## Current Behavior
Rssi can only be gained by consuming a channel or connecting a rssi pad

## Desired Behavior
count the lost packets like in betaflight = no consumed channel, no difficult setup and a pretty good way to indicate signal quality

## Who does this impact? Who is this for?
everyone who does long range ;-)

**Comment by digitalentity** [comment]
Implemented in #4941
