### ISSUE TITLE
How to connect an external PINIO for MATEKF722mini in Inav 

### ISSUE THREAD

**Issue by romko1** [iNavFlight/inav#4940]
Hello,
I need advice on changing the PINIO in the latest INAV.
I have FC MatekF722mini, which has two PINIOBOX defined:
C08: PINIO1 OUT
C09: PINIO2 OUT
The PINIO is used as follows:
![pinio_setting](https://user-images.githubusercontent.com/34416051/61199701-1dd61d00-a6df-11e9-80fc-d8768c6d671e.jpg)

I want to add an external PINIO to power off the camera. [https://www.banggood.com/Tinys-RealPit-VTX-Power-Switch-5V-28V-1A-for-FPV-Transmitter-p-1401301.html?rmmds=search&cur_warehouse=CN](url)
However, when I connected it to an unused TX pin, and chose eg. RunCam device, so it didn't work like I wanted.
If I connected PINIO physically to pin S6 (B03) and modified it in FW - target.h, it worked (power off the camera) but it also turned off VTX and I don't want it because I use TBS SmartAudio.
![target_h](https://user-images.githubusercontent.com/34416051/61199708-2890b200-a6df-11e9-8200-25bca4de4b21.jpg)

Can you please advise me where to change to VTX not disconnect, ie. it did not disconnect the VBAT power supply for VTX,  because I have the camera connected to + 5V and I only disconnect it via external PINIO. Thank you.

**Comment by romko1** [comment]
Problem solved by firmware modification.

**Comment by whoim2** [comment]
> Problem solved by firmware modification.

Hello! Im try compile my target as you for pinio functions

> //PINIO - DAC
#define USE_PINIO
#define USE_PINIOBOX
#define PIN03_PIN PA8
#define PIN04_PIN PA4 // DAC
//END PINIO

but its not work, am use USER1/USER2 modes, CAMERA ON and etc, at pin PA4/PA8 not any changes in levels. You may help?

**Comment by Inv3nt0r1** [comment]
> Problem solved by firmware modification.

Can you tell what you did to resolve this?

**Comment by cryptictuna** [comment]
can you upload custom hex ?
