### ISSUE TITLE
Matek F722MINI 8 motor outputs 

### ISSUE THREAD

**Issue by FLDataTeK** [iNavFlight/inav#4942]
I have a Matek F722mini and I am wanting to setup a X8 Octo configuration, but iNav says it doesn't have enough PWM drivers/timers.  But if I switch to betaflight it works just fine. I have looked at the targets for inav and betaflight 3.5.2 and they are the same as far as the pins and timers. 

Is this something that could be overcome if resources are an issue like disabling LED pins or other stuff that is not being used? I do need to use GPS and Baro (external on I2C) and MAG (I2C also) and a serial RX. 

iNav target: 

/*
 * This file is part of INAV.
 *
 * INAV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * INAV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with INAV.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>

#include "platform.h"

#include "drivers/bus.h"
#include "drivers/io.h"
#include "drivers/pwm_mapping.h"
#include "drivers/timer.h"
#include "drivers/pinio.h"

BUSDEV_REGISTER_SPI_TAG(busdev_mpu6000,     DEVHW_MPU6000,      MPU6000_SPI_BUS,    MPU6000_CS_PIN,     MPU6000_EXTI_PIN,       0,  DEVFLAGS_NONE);
BUSDEV_REGISTER_SPI_TAG(busdev_mpu6500,     DEVHW_MPU6500,      MPU6500_SPI_BUS,    MPU6500_CS_PIN,     MPU6500_EXTI_PIN,       1,  DEVFLAGS_NONE);

const timerHardware_t timerHardware[] = {
    DEF_TIM(TIM3, CH1, PB4,   TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S1   UP1-2   D(1, 4, 5)
    DEF_TIM(TIM3, CH2, PB5,   TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S2   UP1-2   D(1, 5, 5)
    DEF_TIM(TIM3, CH3, PB0,   TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S3   UP1-2   D(1, 7, 5)
    DEF_TIM(TIM3, CH4, PB1,   TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S4   UP1-2   D(1, 2, 5)

    DEF_TIM(TIM2, CH1, PA15,  TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S5   UP1-7   D(1, 5, 3) - clash with S2
    DEF_TIM(TIM2, CH2, PB3,   TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S6   UP1-7   D(1, 6, 3)

    DEF_TIM(TIM4, CH1, PB6,   TIM_USE_MC_SERVO | TIM_USE_FW_MOTOR, 0, 0),   // S7   UP1-6   D(1, 0, 2)
    DEF_TIM(TIM4, CH2, PB7,   TIM_USE_MC_SERVO | TIM_USE_FW_MOTOR, 0, 0),   // S8   UP1-6   D(1, 3, 2)

    DEF_TIM(TIM1, CH1, PA8,  TIM_USE_LED, 0, 2),                            // LED          D(2, 6, 0)

    DEF_TIM(TIM9, CH2, PA3,  TIM_USE_PPM, 0, 0),                            // PPM, RX2

    DEF_TIM(TIM5, CH3, PA2,  TIM_USE_PWM, 0, 0),                            // TX2 & softserial1
};

const int timerHardwareCount = sizeof(timerHardware) / sizeof(timerHardware[0]);

Beta flight target : 

/*
 * This file is part of Cleanflight and Betaflight.
 *
 * Cleanflight and Betaflight are free software. You can redistribute
 * this software and/or modify this software under the terms of the
 * GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Cleanflight and Betaflight are distributed in the hope that they
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>

#include "platform.h"
#include "drivers/io.h"

#include "drivers/dma.h"
#include "drivers/timer.h"
#include "drivers/timer_def.h"

const timerHardware_t timerHardware[USABLE_TIMER_CHANNEL_COUNT] = {

    DEF_TIM(TIM3, CH1, PB4,   TIM_USE_MOTOR, 0, 0),   // S1   UP1-2
    DEF_TIM(TIM3, CH2, PB5,   TIM_USE_MOTOR, 0, 0),   // S2   UP1-2
    DEF_TIM(TIM3, CH3, PB0,   TIM_USE_MOTOR, 0, 0),   // S3   UP1-2
    DEF_TIM(TIM3, CH4, PB1,   TIM_USE_MOTOR, 0, 0),   // S4   UP1-2

    DEF_TIM(TIM2, CH1, PA15,  TIM_USE_MOTOR, 0, 0),   // S5   UP1-7
    DEF_TIM(TIM2, CH2, PB3,   TIM_USE_MOTOR, 0, 0),   // S6   UP1-7
    DEF_TIM(TIM4, CH1, PB6,   TIM_USE_MOTOR, 0, 0),   // S7   UP1-6
    DEF_TIM(TIM4, CH2, PB7,   TIM_USE_MOTOR, 0, 0),   // S8   UP1-6

    DEF_TIM(TIM1, CH1, PA8,  TIM_USE_LED, 0, 2),   // LED DMA2-3

    DEF_TIM(TIM9, CH2, PA3,  TIM_USE_PPM, 0, 0),   // PPM, RX2
    DEF_TIM(TIM9, CH1, PA2,  TIM_USE_PWM, 0, 0),   // TX2
    DEF_TIM(TIM5, CH2, PA1,  TIM_USE_PWM, 0, 0),   // RX4  
    DEF_TIM(TIM5, CH1, PA0,  TIM_USE_PWM, 0, 0),   // TX4

};

**Comment by MATEKSYS** [comment]
INAV uses normal DMA,  S5 DMA conflict with S2.   so use multishot for Hex/Octo copter
8 PWM need 8 difference DMA/Stream

BF uses burst DMA,  8 PWM need just 3x  TIM_UP,  no confliction between S1 ~S8 Dshot, 
BF RPM filter use normal DMA,  S5 DMA conflict with S2 also
