### ISSUE TITLE
MATEK F411-WING Softserial RX 

### ISSUE THREAD

**Issue by CSMachineCo** [iNavFlight/inav#4947]
## Current Behavior
Softserial RX on the LED pad does not appear to work in firmware: MATEKF411_FD_SFTSRL version 2.2.1.  

EDIT: Softserial RX kinda works using the NMEA protocol for GPS.  It seems to burst receive messages every 5-10 seconds which is not very useful.  

![Screenshot 2019-07-16 at 7 15 26 PM](https://user-images.githubusercontent.com/52946032/61336606-f32fb580-a7ff-11e9-916e-abeb2425e45e.png)

## Steps to Reproduce
1.Configure Softserial port for GPS @19200 buad
2.Plug GPS TX in to PAD LED and GPS RX into PAD ST1

## Expected behavior
Receive GPS data as indicated in inav configurator.

## Additional context
Tested GPS connectivity using hardware UART 2 configured with same baud and it works as expected.  Tested with 3DR radio and produced same behavior.  Tested with firmware version 2.2.0 and produced same behavior. GPS device is BN-880.

- FC Board name and vendor:
MATEK F411-WING
- INAV version string:
# version
# INAV/MATEKF411_FD_SFTSRL 2.2.1 Jul  3 2019 / 22:53:44 (a6d847482)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by padcom** [comment]
I am seeing the exact same behavior. I was hoping the software serial port would be good enough to drive the GPS in UBLOX7 mode but in fact it is unusable even in NEMA mode. The systems shows "GPS Failure" every few seconds.

**Comment by stronnag** [comment]
We've known since c. 2015 that receiving on soft serial is unreliable. Nothing new here. Don't do it.

**Comment by CSMachineCo** [comment]
If it's not a supported function, then it probably should be removed/prevented from/in the configurator...  I don't know how to move issues between projects on GitHub so I'm closing it here. If someone else wants to move it to the configurator, have at it.

**Comment by stronnag** [comment]
It is a supported function; just not for your use case.

**Comment by padcom** [comment]
OK - can you state what is it supported for? I mean if it is supported for something it'd be great to have it listed so that we don't try to use the software serial port for things that it is not intended to do. I was pretty sure if 19200 is the max baud rate then it doesn't matter what is actually transmitting on this port unless it is conforming to the 19200 8N1 protocol.

**Comment by stronnag** [comment]
> OK - can you state what is it supported for? I mean if it is supported for something it'd be great to have it listed so that we don't try to use the software serial port for things that it is not intended to do. 

Extant documentation, https://github.com/iNavFlight/inav/blob/master/docs/Serial.md, specifically:

"UART is the most efficient in terms of CPU usage. SoftSerial is the least efficient and slowest, SoftSerial should only be used for low-bandwidth usages, such as telemetry transmission"
