### ISSUE TITLE
Enable surface tracking for waypoint mode

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#4950]
## Current Behavior
`SURFACE` modifier is ignored for RTH and WP mode.

## Desired Behavior
Create a CLI setting `nav_allow_terrain_following` with settings `MANUAL` (only ALTHOLD/POSHOLD), `RTH` (manual or RTH mode), `WP` (manual or WP mode), `ALL` (all navigation modes).

**Comment by pogopo789** [comment]
Is there any news on this feature? This feature would be great for drones to move outdoors at a low altitude where sonar is triggered.
