### ISSUE TITLE
Board Alignment

### ISSUE THREAD

**Issue by drifter1949** [iNavFlight/inav#4955]
## Current Behavior
After mounting flight controller at for example  90 degrees Right Yaw and making the change in "Board and Sensor Alignment", then the Roll and Pitch settings don't correspond to the new board alignment. I have to change pitch settings to change roll and change roll settings to change pitch. 
 
## Steps to Reproduce
1.Rotate and Mount Flight Controller 90 degrees clockwise to the normal direction.
2.Change the settings in "Board and Sensor Alignment" to correspond to this change :- 90 Yaw Degrees.
3.Raise the nose of your Airplane for example 3 Degrees and try to level out the settings to 0 Degrees.
4.It is possible by using the Roll settings instead of pitch but is confusing.

## Expected behavior
I expected the settings to correspond to the appropriate control.

## Suggested solution(s)
If possible, please rectify this situation.
## Additional context

# dumphttps://pastebin.com/0Dx35ugK

# version
# INAV/FF_F35_LIGHTNING 2.2.1 Jul  3 2019 / 21:40:58 (a6d847482)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

---

- FC Board name and vendor:
- INAV version string:
# version
# INAV/FF_F35_LIGHTNING 2.2.1 Jul  3 2019 / 21:40:58 (a6d847482)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by digitalentity** [comment]
All alignment settings in INAV are relative to the **board**, not the **aircraft**, so this is working as intended.

**Comment by drifter1949** [comment]
Thank you.
