### ISSUE TITLE
CL Racing F4 Air V3 Target Missing

### ISSUE THREAD

**Issue by umdpru** [iNavFlight/inav#4959]
I see the CL Racing F4 Air V3 Target in the master but it's not being compiled? How come?

**Comment by bnn1044** [comment]
I am not sure why the target file is not included in the release. the code is in the master. 
@digitalentity  may know?

thanks.

**Comment by keithluneau** [comment]
I'd like to see this sorted out too, I have this board here waiting for firmware right now. I would attempt to compile it myself but that's a bit outside my comfort zone if I'm being totally honest... lol I wouldn't know where to start.

**Comment by teckel12** [comment]
@keithluneau @umdpru Since I was already doing some compiling anyway, here's the firmware for the CLRACINGF4AIRV3:

[inav_2.2.1_CLRACINGF4AIRV3.zip](https://github.com/iNavFlight/inav/files/3487049/inav_2.2.1_CLRACINGF4AIRV3.zip)

**Comment by keithluneau** [comment]
Thanks! I also found it here for download - https://cl-racing.myshopify.com/pages/support

**Comment by mueller2030** [comment]
Hi, 
Is there an updated version of this target? i have a new  CLRACINGF4V3 and the target is not provided in the drop down menu as well as on the clracing website, they are both out dated and wont run on the latest INAV config
thanks
