### ISSUE TITLE
Artificial Horizon wrong movement?!

### ISSUE THREAD

**Issue by methisto** [iNavFlight/inav#4963]
Hi Guys!
Edit: OK first issue solved...

And another issue: I have a XM+ receiver, and its really "swamping" When i move the Radio (QX7) more far away, but when im just about 1m away it loses connection, on my Tyro99 also with XM+ i dont have this issue!

And: 

I calibrated the accelerometer...when i go to the setup tab an put a water spirit level on the wing its about 1-3 degree not in level...could this be a problem in angle mode?

Any suggestions?
Thanks!

**Comment by giacomo892** [comment]
Not the right place to ask such questions. 
You can use board allignment to level out the board after the calibration.

**Comment by digitalentity** [comment]
@methisto you would get responses from a bigger community here https://t.me/INAVFlight
