### ISSUE TITLE
Bad behavior in ALTHOLD mode, 2.2.1, MATEK F405-CTR

### ISSUE THREAD

**Issue by xrife** [iNavFlight/inav#4966]
Hi!

I'm a newbie. Faced a problem in ALTHOLD mode after set throttle stick turns to the lowest position.

## Current Behavior
It is strange that, with the gas turned off and no acceleration, the baro height continues to increase, although this was not so visually.

After raising the stick of gas to small values, the motors begin to roar and the quad rushes up.

## Expected behavior
After returning the throttle stick from the lower position, the quad should change the target altitude value or go towards it slowly, as specified in the settings.

## Additional context
[pastebin](https://pastebin.com/ajbC67Ni)

- FC Board name and vendor: MATEK F405-CTR
- INAV version string: 2.2.1

**Comment by xrife** [comment]
[LOG00054.TXT](https://github.com/iNavFlight/inav/files/3422465/LOG00054.TXT)
![image](https://user-images.githubusercontent.com/45541318/61718953-a2bed780-ad6c-11e9-9a94-c9a4e71f6e72.png)

**Comment by xrife** [comment]
It looks like #4925 
What do you think? What could be the solution in my case?

**Comment by teckel12** [comment]
@xrife I believe this is typically caused by vibrations.  Is your FC hard or soft mounted?

**Comment by xrife** [comment]
> @xrife I believe this is typically caused by vibrations. Is your FC hard or soft mounted?

Soft mounted as recommended.

Modes ANGEL and HORIZON and ACRO (without ALTHOLD) work fine even at maximum throttle. The current problem occurs when the gas is turned on after it is turned off in flight with ALTHOLD&ANGEL.

**Comment by teckel12** [comment]
@xrife Keep in mind that althold and poshold works fine for me no matter what I do with the throttle. 

Personally, I would set `nav_use_midthr_for_althold` to OFF and set `nav_mc_hover_thr` to your correct mid throttle position.

By doing this, no matter your throttle position, when you enable althold/poshold it locks that altitude. Then, your throttle stick controls the altitude based on the original throttle stick position.

Also, it may be easier to look at your settings if it you just did a `diff` as it's difficult to see your unique settings by dumping all settings.

I any case, looking at hardware vibrations or settings as INAV itself is working just fine with alt and pos hold.

**Comment by xrife** [comment]
@teckel12 Thank you for your experience and comments.

My settings now by `dump diff` [https://pastebin.com/6aEwb3xD](https://pastebin.com/6aEwb3xD)

I'll try set `nav_use_midthr_for_althold` to OFF and `set nav_mc_hover_thr` to my correct mid throttle position and share my experience.

**Comment by xrife** [comment]
Hi!

I conducted an experiment with these settings, but got the same result.
Maybe my problem is in my settings? If someone shares their settings, I can check the work.

![image](https://user-images.githubusercontent.com/45541318/62424450-501fdc80-b6d7-11e9-8e1a-7e31e34f1ac7.png)
[LOG00094.TXT](https://github.com/iNavFlight/inav/files/3464949/LOG00094.TXT)

I can assume that the problem is in my settings, since accelerations coincide with visual observations. But the speed and position do not coincide with the acceleration integral and visual observation.

**Comment by xrife** [comment]
@teckel12 The problem only appears when AIRMODE is disabled. If AIRMODE is enabled, then ALTHOLD works fine.

**Comment by teckel12** [comment]
@xrife I always have airmode enabled (enabled via the arm switch).

I can try to set it via a different switch and see if I can duplicate your issue.

**Comment by xrife** [comment]
@teckel12 I switched AIRMODE to a debug switch to turn off the motors in flight without DISARM.

I will be glad if you try this for your setup in order to understand where to go next.

**Comment by gilglecio** [comment]
I have the same problem, I also use this controller, I am a week looking for solution, my drone is varying in ALT HOLD one meter up and one meter down
