### ISSUE TITLE
Have an option to right justify craft_name in OSD

### ISSUE THREAD

**Issue by tonyyng** [iNavFlight/inav#4973]
## Current Behavior

When you place the craftname on the right side of the display, the first character can't be any further right than about 12 characters from the right edge of the screen
```
[ C R A F T _ N A M E ] |<- right edge
   +  W + | + N + | + E |<- right edge
```

And this appears in the OSD as follows:
```
ABCDE                |<- right edge
+  W + | + N + | + E |<- right edge
```
The configurator lets me specify a name that has leading spaces, so I can work around it by putting spaces at the beginning of the name, which then appears as:
```
               ABCDE |<- right edge
+  W + | + N + | + E |<- right edge
```

However, this doesn't work well with the CLI handling of the value.
```
# set name
name =      ABCDE
Max. length: 16

# Try to specify a name with leading spaces
# set name =      ABCDE

# set name
name = ABCDE
Max. length: 16
# Nope.  Saved without the leading spaces
```

## Desired Behavior

```
               ABCDE |<- right edge
+  W + | + N + | + E |<- right edge
```
## Suggested Solution

Allow the OSD Craft Name to be positioned so that it is partially displayed on the screen:
```
           [ C R A F T _|<- right edge
  +  W + | + N + | + E  |<- right edge
```
Or allow the CLI to specify a string with leading spaces.
Or have a separate OSD element which is the craft_name, right justified.

## Who does this impact? Who is this for?

All Users

**Comment by LitterBugs** [comment]
I totally agree.  This is SO annoying!

**Comment by tonyyng** [comment]
Merged
