### ISSUE TITLE
2 Steps Auto Launch 

### ISSUE THREAD

**Issue by Lukasz9B** [iNavFlight/inav#4975]
## Current Behavior
After ramp up, throttle is constant for entire Auto Launch.

## Desired Behavior
Full throttle is desired for heavy wings during first phase of acceleration/throw when it is difficult to stabilize. It would be good if wing will reduce throttle after specific time or altitude. I launch my wing by shake, wait for motor to spin up and throw aft above head. This feature could be called Boost

Example:
Auto launch throttle boost 2000 -
Duration 5s 

Reduce auto launch throttle to 1700 for rest of Auto Launch time.

**Comment by giacomo892** [comment]
Already requested in #2885 
closing.
