### ISSUE TITLE
My plane turns to left!

### ISSUE THREAD

**Issue by methisto** [iNavFlight/inav#4983]
ok

**Comment by DerElch87** [comment]
Are you serious?

> Don't know if that question is right here but i want to ask u guys before i take the next flight!?

The question is definitely not right here.
If you need help for such basic things, ask in one of the thousands available communities!

> Think the board alignment should be ok but not sure

Pretty sure it's not.

Issues or topics like this prevent the really good developers here from doing useful things, like bringing new features, improve the software etc...

Please close this topic!
