### ISSUE TITLE
Offset in FC position

### ISSUE THREAD

**Issue by holoduke** [iNavFlight/inav#4984]
I try to find and answer related to proper aligning a flight controller.
For a bigger fixed wing (200cm) I would like to position my matek 405 wing a bit to the rear. About 25-30cm backwards from CG.
Would this lead to issues? GPS is located near CG. I see that there is no option to set a longitudinal/latitudinal offset for the FC in the configurator. Is there maybe some hidden command?

**Comment by teckel12** [comment]
@holoduke Why would it be wrong to have the flight controller in the rear?  Are you thinking an adjustment in GPS latitude/longitude would be required for 25cm when a GPS is only accurate to maybe 100cm at best?  Maybe I'm confused by why you believe it would be a problem to have your GPS and flight controller not on top of each other.  I've never had my GPS in the same location as my flight controller.

**Comment by holoduke** [comment]
I mean when FC is not in cg, the lateral and vertical movements are more severe and might confuse the FC. If I am right

**Comment by teckel12** [comment]
@holoduke I would think closer to COG the better, but I believe it doesn't make much difference if it's a small amount off.  The angles would all be the same no matter where you position the FC.  The only difference would be a slight altitude change if not at the COG.  But I can't imagine an inch here or there would make a difference or even be detectable.  FW pilots would need to confirm this however.

The correct FC orientation and and proper COG balancing, however, would be very important.

**Comment by teckel12** [comment]
@holoduke This issue system is for INAV issues. For assistance you should use the support channels (like Telegram). See the main readme page for support links.

**Comment by DzikuVx** [comment]
There is no need to offset anything. Perfect position for FC is CoG but both gyro and accelerometer will work if not in CoG. For GPS it does not matter at all with the scale RC works with
