### ISSUE TITLE
ARWING 900 PIFF  values - I just cannot seem to tune into that "sweet spot"? 

### ISSUE THREAD

**Issue by shresthanator** [iNavFlight/inav#4995]
Despite my best efforts, I have been unable to tune into a good PIFF setting on my wing (a popular ARWING 900 model). 

It is my understanding that normally, for a wing, you would use the following range of values: 

P = 5 -10 
I = 15- 25
FF = 15-50 

After watching a number of instructional videos on the topic, and reading "build" posts on popular RC forums (for similar builds to my own). I initially tried the following settings: 

**Pitch:**
set fw_p_pitch = 7
set fw_i_pitch = 15
set fw_ff_pitch = 70

**Roll:**
set fw_p_roll = 5
set fw_i_roll = 15
set fw_ff_roll = 30

From my very limited understanding of the controls theory behind this, I understand that these values have to do with the higher roll authority than pitch authority. 

-----------------------------------------

I took off in "Angle" mode - and it flies around pretty stable in angle mode (though docile). I am most comfortable in "horizon mode" - but the issue is when I take it out of the "angle" mode 
into "horizon" mode, it has a nasty tendency to roll over. It almost feels as though, up to a certain bank angle it is fine, but once a certain threshold has been crossed....it immediately flips over and nose dives into the ground. I have tinkered with a range of PIFF values (from the lower to higher end) - but I can't seem to get away from a "twitchy" tendency on the roll axis. I am aware of the new "autotune" 
feature, but I feel a bit reluctant to use it because of a bad experiences I've had with my previous build. 

Can anyone please advise?

**Comment by giacomo892** [comment]
https://github.com/iNavFlight/inav/wiki/Fixed-wing-guide
https://github.com/iNavFlight/inav/blob/0aee83fbd1af2d7595152265170eb44c18189ea7/docs/INAV_Fixed_Wing_Setup_Guide.pdf

rollover tendency, check GC and speed. you are stalling
