### ISSUE TITLE
Probleme with BTRX on jumper 16 2.23 - F4 f35 clone - inav 2.21 - Crossfire micro + nano and  inav script 1.71 on t16

### ISSUE THREAD

**Issue by dovichino** [iNavFlight/inav#4998]
Hi,

I have a problem with the btrx on my radio. On inav and in telemetry I see the voltage of my battery but impossible to have on the script inav. I start then maybe I made a bad adjustment?

![WhatsApp Image 2019-08-06 at 17 38 51](https://user-images.githubusercontent.com/52896887/62585331-9718f800-b8b8-11e9-8126-42072aa2e73c.jpeg)
![WhatsApp Image 2019-08-06 at 17 35 17](https://user-images.githubusercontent.com/52896887/62585336-9e400600-b8b8-11e9-9b8c-516762532e68.jpeg)
![inav tel](https://user-images.githubusercontent.com/52896887/62585390-d3e4ef00-b8b8-11e9-9d77-e4f2a87af1a9.jpg)

![WhatsApp Image 2019-08-06 at 17 35 17(2)](https://user-images.githubusercontent.com/52896887/62585354-b152d600-b8b8-11e9-91de-d2647f70638a.jpeg)

**Comment by wx4cb** [comment]
make sure you're running the development version, then delete and rediscover the sensors. there's documentation in the wiki to download and install the dev version.

**Comment by dovichino** [comment]
Thanks for your help !
i have the last version 1.71. 
It's a new install, i bought my crossfire today. 
we can see the sensor work in telemetry,12.3v but dont work in the main panel.
I was delete and discover 5 times...
I do not understand.

**Comment by wx4cb** [comment]
the latest DEV version is 1.7.2
https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build

**Comment by dovichino** [comment]
ok thx i try that

**Comment by dovichino** [comment]
I am in 1.72 and always the same problem after delete and discover the telemetry

**Comment by teckel12** [comment]
@dovichino You should open an issue in the lua telemetry repo, not here in INAV. This is not at all related to INAV. Also, I'm the author of the Lua Telemetry script, so I'll personally be looking into this.

**Comment by teckel12** [comment]
@dovichino Quickly looking into this, it seems you renamed the sensor. It should be `RxBt` but you renamed it `BtRx`. So that's why it can't find the voltage. Don't change sensor names.

If you're still having a problem, please open an issue in the correct repo (INAV Lua Telemetry).

**Comment by dovichino** [comment]
A big thank you for your help!

I had not renamed RxBt to BtRx, it's the telemetry that says that name. I just rename it and it works except that if I delete and I discover again it is renamed BtRx and not RxBt. I am french can be a problem related to translation?  i Have a french 2.23 firmware.

**Comment by dovichino** [comment]
I just flashed with firmware 2.23 EN and I RxBt when I do discover.

So this comes from the firmware translation

**Comment by digitalentity** [comment]
Wrong repository
