### ISSUE TITLE
NAV - Switch from NEU to more conventional NED coordinate system

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#50]
@ledvinap managed to convince me that this would be a good idea :smiley: 
This, however, will stay blocked until "Flyable" milestone is reached.

**Comment by ledvinap** [comment]
I just like my rotation counterclockwise ;-)

**Comment by digitalentity** [comment]
Just use (-heading) everywhere :smirk:

**Comment by martinbudden** [comment]
@digitalentity , this is an old one. What's the status here?

**Comment by digitalentity** [comment]
It's still relevant but nothing has been done here and I doubt we'll ever close this. Lets, however, keep it open to be aware of the possible improvement.
