### ISSUE TITLE
hi i'm new to this  so patience please my naze32 rev6 not holding position it holds alt and level but wanders of to werever

### ISSUE THREAD

**Issue by harryaruba** [iNavFlight/inav#500]

**Comment by oleost** [comment]
Hi.

Please start here, and read trough the wiki. https://github.com/iNavFlight/inav/wiki

If you still dont figured it out after reading trough the wiki, you can go to the rcgroups thread for user support. http://www.rcgroups.com/forums/showthread.php?t=2495732

Please close this Issue.

**Comment by WaspFPV** [comment]
Does the copter stay perfectly level and drift with the wind, or does it fly off into a direction that is not home?
In the first case, gps may not be activated properly.
In the second case, check that your compass is working properly and is calibrated. GPS needs to know what is the right direction to go, or it will fly in a wrong direction.
