### ISSUE TITLE
better description of terrain/surface mode

### ISSUE THREAD

**Issue by humanoid2050** [iNavFlight/inav#5004]
So I've got terrain following turned on and holding altitude nicely. I'm using a MS5611 barometer and a VL53L0X rangefinder (small indoor quad so lighting isn't an issue). I launch with both NAV_ALTHOLD and SURFACE modes enabled. I also have set `nav_use_midthr_for_althold=ON`. 

My questions is this: how does above-ground-level altitude control actually work from a pilot perspective? It appears that the height set-point is determined by mapping the full range of the throttle to the range specified by  `nav_max_terrain_follow_alt`. i.e. zero throttle lands the quad, 50% throttle is half height, and 100% throttle puts it at the value of  `nav_max_terrain_follow_alt`. Is this accurate? I assumed that it would be the same as baro controlled altitude, with 50% throttle hovering, and greater/lesser amounts controlling decent/ascent rate.

**Comment by pDR8iLQ4go** [comment]
@humanoid2050: I can confirm that! It took me a while to understand what the expected behavior of SURFACE mode is. I was wondering as well, why my copter was hovering a about 1m (100cm). But then I found the parameter nav_max_terrain_follow_alt!
