### ISSUE TITLE
No ALTHOLD ?

### ISSUE THREAD

**Issue by artusmuc** [iNavFlight/inav#5019]
Hello,

I have a Quad with a Matek Mini MAG and Baro

I dont see "INAV ALTHOLD" Mode 

Is it no more possible to set "ALTHOLD" with INAV 2.2.1 ?

**Comment by teckel12** [comment]
@artusmuc Yes, there's alt hold. Where don't you see this? Do you have your flight controller configured as having a barometer?  Maybe a CLI diff would be helpful?

**Comment by artusmuc** [comment]
Hello,

Thank you for your help. Yes flight controller is configured - altitude is displayed correctly in OSD.

But i did not see ALTHOLD to configure on a switch  in MODES

**Comment by artusmuc** [comment]
Now . I am happy . I have connected to battery .. then with USB .. and suddly i am able to configure :)
