### ISSUE TITLE
Matek f411 Wing - no ARMING possible - iNav 2.2.1

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#5020]
## Current Behavior
Not able to arm with stick combo, tried nav_extra_arming_safety ON and OFF
RX PPM
## Steps to Reproduce
try to arm by stick arming

## Expected behavior
FC arming

## Suggested solution(s)
fix code

## Additional context
https://pastebin.com/x7HbdH75

---
- FC Board name and vendor: Matek f411 wing
- INAV version string:  INAV/MATEKF411 2.2.1 Jul  3 2019 / 22:50:30 (a6d847482)

**Comment by stronnag** [comment]
This is a feature, as described in the release notes https://github.com/iNavFlight/inav/releases/tag/2.2.1

**Comment by Schalonsus** [comment]
ups...totally missed that
Thanks for help
