### ISSUE TITLE
Crossfire Nano Diversity Receiver and Full Size Crossfire Transmitter not working with Inav 2.2.1 on Matek F411 Wing when updating Crossfire Transmitter to from 2.93 to 2.95

### ISSUE THREAD

**Issue by JWWFPV** [iNavFlight/inav#5021]
## Steps to Reproduce

1. Update Crossfire Transmitter firmware from 2.93 to 2.95
2. Update Crossfire Nano Diversity Receiver
3. Crossfire nano diversity receiver does not connect to flight controller yet it is bound to transmitter.
4.  When I roll back Transmitter firmware to 2.93 and update receiver, everything works properly with flight controller.

## Additional context

---

- FC Board name and vendor: Matek F411 Wing
- INAV version string:  INAV/MATEKF411 2.2.1 Jul  3 2019 / 22:50:30 (a6d847482)

**Comment by teckel12** [comment]
@JWWFPV In the future, when opening an issue, please use the subject field and body appropriately, keeping the subject concise and filling out the body information for your issue details.

**Comment by teckel12** [comment]
@JWWFPV Try Crossfire v3.0, I'm running it without any issues.

**Comment by JWWFPV** [comment]
I will follow proper procedure on next post.  Thanks.  

 

I am using the TBS Agent to update my crossfire transmitter and it only shows 2.95.  Any tip on how to get 3.0?

 

 

John W. Wade II

5196 Candlewood Dr.

Fayetteville, NY  13066

(315) 569-6194 Cell

**Comment by JWWFPV** [comment]
I see it now….  I did not have Beta versions available.  I am updating now and will report if that fixes my issue.

 

Thanks.

 

John W. Wade II

5196 Candlewood Dr.

Fayetteville, NY  13066

(315) 569-6194 Cell

**Comment by JWWFPV** [comment]
Update to 3.0 corrected issue.

 

Thanks

 

 

John W. Wade II

5196 Candlewood Dr.

Fayetteville, NY  13066

(315) 569-6194 Cell

**Comment by JWWFPV** [comment]
Update to version 3.0 corrected issue.

Thanks.
