### ISSUE TITLE
F4 NOXE DSHOT

### ISSUE THREAD

**Issue by artusmuc** [iNavFlight/inav#5046]
## Steps to Reproduce

1. F4 NOXE DSHOT not available 4in1 ESC BS-28A 
2.
3.
4.

## Expected behavior

I try to select DSHOT protocol for this ESC but this will not accepted - fallback to Standard

I have checked this with Betaflight - and there is working. 

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by FlyR9** [comment]
Maybe you should try to fly on multishot protocol the dshot looks no 100% reliable: [https://github.com/iNavFlight/inav/issues/5055#issuecomment-531421772](url)

**Comment by digitalentity** [comment]
Which target do you use?
