### ISSUE TITLE
Angle mode strange return to horizon

### ISSUE THREAD

**Issue by xdigyx** [iNavFlight/inav#505]
Recently while flying in angle mode I have noticed that while I try to lean my hexacopter 680 to one side then it's moving smoothly which is as it should (pids follows rcCommand strainght away):
![1](https://cloud.githubusercontent.com/assets/6666245/17942911/adf9342a-6a39-11e6-9ce8-e0424ae8771f.jpg)
however after releasing pitch/roll stick, at the first stage my copter is rapidly moving back to level and it can be seen that PIDs reaction is delayed approx 100ms of rcCommand and raises very fast. Although I should have done it gently and I did not, I believe is not quite as it supposed to be...
![2](https://cloud.githubusercontent.com/assets/6666245/17943115/654c3f8c-6a3a-11e6-839a-ca7cad7e3c42.jpg)

Anyone got same effect?

**Comment by digitalentity** [comment]
Do you have the complete log?

**Comment by xdigyx** [comment]
Sent on your email

**Comment by xdigyx** [comment]
To be more precised, it's FW 1.1. On 1.2 R4 is much better:
![1](https://cloud.githubusercontent.com/assets/6666245/18143431/454049e4-6fc2-11e6-97a0-6dad267fa304.jpg)

**Comment by DzikuVx** [comment]
@xdigyx there is an LPF filter on ANGLE and HORIZON modes. Its cutoff frequency is set by LEVEL I parameter. If it's low, it can induce delay like you described.

**Comment by xdigyx** [comment]
Sorry, but I can't catch you... sorry for my newbie questions:  What's  reducing the delay?  what LPF filter, or level I gain or cut-off freq filter (which one)?

**Comment by DzikuVx** [comment]
INAV uses low pass filter in ANGLE and HORIZON modes to "smoothen" difference of target and current inclination. Cutoff frequency of this filter is set by LEVEL_I parameter. Default LEVEL I 15 means that cutoff is set at 15Hz. 
The lower the cutoff, the longer the delay filter introduces and smoother is leveling in those modes.

**Comment by xdigyx** [comment]
OK, got it now. So just the question why (or rather if it's normal) there were no delays while increasing inclination, but there were while decreasing/levelling... Was level i gain rescalled 1.1 vs 1.2? Asking because either for 1.1 & 1.2 I had default LVL I gain.

**Comment by oleost** [comment]
There is no I gain for level mode. 

The I gain is in reality cutout frequency

**Comment by DzikuVx** [comment]
How it behaves depends how fast you move a stick.  Usually, pilots release them faster than they set inclination. 
This value was not rescaled, but 1.2 changed many things, including how sticks behave. Inclination change is smoother now, so delay might not be visible

**Comment by xdigyx** [comment]
Thanks for explanation.
So either it could be omitted and issue closed or maybe defaults are not properly set.

**Comment by digitalentity** [comment]
@xdigyx, defaults are sane and good enough to get you in the air on most aircrafts, to get your machine flying perfectly you'll have to spend some time fine-tuning it.

Since you issue was related to 1.1 and 1.2 really changed flight dynamics code a lot, I think we can close this.
