### ISSUE TITLE
Inav gps mission oscilation in altitude

### ISSUE THREAD

**Issue by purpletreee** [iNavFlight/inav#5053]
Hello Guys, 
I have a problem. In angle mode my nano talon is total stable and no oscilations. But when I start a gps mission it works, it follows the path, but there are always oscilations in the height. I set the altitude to 120 meters and it oscilates from 116 to 125 meters. And the motor throttle is oscilating to probably to correct the altitude. All this oscilations are bad for my rx signal, because when ever the plane is pitching up the angle of the antenna doesnt match my antenna I think. I am not sure if this has something to do with PIDs or PIFFs, and so I dont want to mess up any settings.
EDIT: I dont think it has something to do with GPS because in RTH it holds the altitude acurately

**Comment by wx4cb** [comment]
try adjusting your cruise throttle a little bit, also. make sure you run it through an auto tune etc

**Comment by purpletreee** [comment]
thank you i will try that tomorrow
