### ISSUE TITLE
Intalling inav

### ISSUE THREAD

**Issue by jeffwhu** [iNavFlight/inav#5062]
Hi

Im having trouble downloading and running to my windows10 pc, I can download the file but it wont run unless i "run as administrator" but will not stay loaded on my pc without having to do the same every time i want to use the inav confiurator which can get irritating, How can i get the configurator permanently on my pc without having to run as administrator???

Regards

Jeff

**Comment by teckel12** [comment]
I suggest asking for support on Telegram here:  https://t.me/INAVFlight

Also, this issue was opened for INAV when it should have been opened for INAV configurator (the software you're having an issue with):  https://github.com/iNavFlight/inav-configurator/issues
