### ISSUE TITLE
 Problem with RTH throttle (iNAV)

### ISSUE THREAD

**Issue by maverick-2009** [iNavFlight/inav#5064]
Hi. I’m using a Matek F405 Wing for my Nano Talon FPV plane with the last iNAV firmware.

Now the Problem:

I’m testing the RTH function in my stand and sometimes when I active the RTH function the throttle goes to 0% and sometimes it works fine, going to 100%. Why sometimes the throttle don’t work and sometimes it’s works. Is This because the minimum distance for RTH configuration? Because when i put the minimum distance for RTH in “0”, the problem is the same.
Someone can help me?

**Comment by Jetrell** [comment]
`nav_extra_arming_safety = off ` will allow you to test the throttle without a GPS lock.
Although, if you are going to do a ground test. It is better to have a GPS lock and briskly walk with the model(no props on), so that iNav thinks the model is moving.
