### ISSUE TITLE
DALRC F722 DUAL STM32F722RGT6 F7 Flight Controller

### ISSUE THREAD

**Issue by SlavkoYT7SED** [iNavFlight/inav#5080]
Respected !
I would have one question and whether this will be firmware for
DALRC F722 DUAL STM32F722RGT6 F7 Flight Controller
Thank you, all the best
Slavko

**Comment by teckel12** [comment]
@SlavkoYT7SED Seems there's been a target for it for quite some time, see:

https://github.com/iNavFlight/inav/tree/master/src/main/target/DALRCF722DUAL
