### ISSUE TITLE
Can't setup servo gimbal on S5/S6 output

### ISSUE THREAD

**Issue by DangerD256** [iNavFlight/inav#5083]
Added two servos in mixer tab:
![image](https://user-images.githubusercontent.com/17032489/65392895-c01b1c80-dd82-11e9-8530-5e4f25d7c019.png)
But as you can see Servo 0 replaced Motor 1

![image](https://user-images.githubusercontent.com/17032489/65392904-ef318e00-dd82-11e9-9eb9-c32d526c7161.png)
Here output is also S1 and no output for second servo.

I need to put servo gimbal to S5/S6 output, how can i do that?

**Comment by DzikuVx** [comment]
The board you are using does not support 4 motors and 2 servos configuration. Not every output can be used as servo/motor. Servo 2 was not assigned since board has no valid output for it and servo 1 can not be used together with first motor.
Since you did not reported board name, we can not advise further

**Comment by DangerD256** [comment]
Matek F405 CTR, previous firmware was Arducopter and everything worked well with S5/S6
Do i need to open request again as current is already closed?

**Comment by DzikuVx** [comment]
INAV supports only 1 servo in multirotor mode on this board by default due to timer conflicts with other functions

**Comment by DangerD256** [comment]
> INAV supports only 1 servo in multirotor mode on this board by default due to timer conflicts with other functions

I don't need WS2812, i need gimbal)

**Comment by ysoldak** [comment]
I don't know if I'm doing something wrong, but there is a simple fix to have a servo on S5 for this board.

See https://github.com/ysoldak/inav/commit/2094e9870bf68eb8bc9a509fe6c5057b156b249f

Keep in mind though, this feature seem like was explicitly removed from iNav by request from Matek themselves ( see https://github.com/iNavFlight/inav/issues/3223 ), for whatever reason. So this can screw up timers or whatever low level stuff they have there. Works for retractable landing gears on my foamy though...

**Comment by DangerD256** [comment]
> See [ysoldak@2094e98](https://github.com/ysoldak/inav/commit/2094e9870bf68eb8bc9a509fe6c5057b156b249f)

Made this change, compiled target SERVO_S6, but S5 still not shown in outputs...
![image](https://user-images.githubusercontent.com/17032489/73936455-9145b300-48eb-11ea-8f43-b970437e7829.png)

**Comment by ysoldak** [comment]
Don't know, mate, it did the trick for me.... Can send you the binary to try, perhaps. PM me.

**Comment by DangerD256** [comment]
> Don't know, mate, it did the trick for me.... Can send you the binary to try, perhaps. PM me.

Yeap, please share binary
