### ISSUE TITLE
Matek F405 CTR Servo gimbal (add servo S5 output)

### ISSUE THREAD

**Issue by DangerD256** [iNavFlight/inav#5084]
![image](https://user-images.githubusercontent.com/17032489/65415226-019cdd80-ddfe-11e9-85f4-66d3491ec964.png)
Currently only S6 is supported as servo output, is there any way to enable S5?

Prevously i used Arducopter on same Matek F405 CTR and gimbal worked well using S5/S6 outputs...

**Comment by DangerD256** [comment]
>I2C requires that the WS2812 led strip is moved to S5, thus WS2812 is not usable on hexcopter and similar.

I don't need WS2812, i need gimbal)

**Comment by Pete-Slater** [comment]
I too would like this. Need manual gimbal pitch and also output to raise landing skids

**Comment by DangerD256** [comment]
> I too would like this. Need manual gimbal pitch and also output to raise landing skids

Use arducopter firmware, works fine, flies well, 2axis servo gimbal works fine

**Comment by DangerD1024** [comment]
The problem is that servo S6 also doesn't work...
