### ISSUE TITLE
Fix target SpeedybeeF4 timers for fixed wing

### ISSUE THREAD

**Issue by gamaxgbg** [iNavFlight/inav#5089]
Hello. Please fix the target SpeedybeeF4 for fixed wings.

It is using the same timer (TIM8) for both motors and servos from S1 to S4.

    DEF_TIM(TIM5, CH4, PA3,  TIM_USE_PPM,                                            0, 0), // PPM

    DEF_TIM(TIM8, CH1, PC6,  TIM_USE_MC_MOTOR                    | TIM_USE_FW_MOTOR, 0, 0), // S1  UP(1,2)
    DEF_TIM(TIM8, CH2, PC7,  TIM_USE_MC_MOTOR                    | TIM_USE_FW_MOTOR, 0, 1), // S2  UP(2,1)
    DEF_TIM(TIM8, CH3, PC8,  TIM_USE_MC_MOTOR                    | TIM_USE_FW_SERVO, 0, 1), // S3  UP(2,1)
    DEF_TIM(TIM8, CH4, PC9,  TIM_USE_MC_MOTOR                    | TIM_USE_FW_SERVO, 0, 0), // S4  UP(2,1)
    DEF_TIM(TIM2, CH1, PA15, TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO, 0, 0), // S5  UP(1,7)
    DEF_TIM(TIM1, CH1, PA8,  TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO, 0, 0), // S6  UP(2,5)

    DEF_TIM(TIM4, CH3, PB8,  TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO, 0, 0), // S7  D(1,7)!S5 UP(2,6)
    DEF_TIM(TIM4, CH1, PB6,  TIM_USE_LED,                                            0, 0),   // LED D(1,0) UP(2,6)

Suggestion: get rid of PPM (nobody who has this FC will ever use that) and put FW_MOTOR to PPM and S7 pin.

Actually if resource remapping were a thing i wouldn't need to bother you. I had to flash Betaflight for my plane to actually fly with it, because there i can remap the motors and servos, but who knows why this isn't a thing... I don't and will never understand...

Thanks.

**Comment by DzikuVx** [comment]
Fixed in INAV 2.4
