### ISSUE TITLE
2.2.1 no longer support blackbox logging on matek f405-ctr

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#5094]
![image](https://user-images.githubusercontent.com/26075468/65794157-64eb8000-e11c-11e9-9b1a-390684ab9ea3.png)

# version
# INAV/MATEKF405 2.2.1 Jul  3 2019 / 22:31:06 (a6d847482)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by stronnag** [comment]
Possibly you just didn't enable `FEATURE BLACKBOX` ....

**Comment by laurentopia** [comment]
you're right, I assumed it was on by default.
