### ISSUE TITLE
Inav some times forgets to add a field in the blackbox .txt

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#5095]
causing inav BB explorer and pidexplorer to freak out (betaflight log viewer has no problem with it)
![image](https://user-images.githubusercontent.com/26075468/65804836-2368ce00-e138-11e9-9c09-9b9fc81a3c16.png)

the attached file is an example where the bb cannot be read properly by inav bb explorer
the subsequence arms produced good files so it's a transient problem maybe?

[LOG00001.zip](https://github.com/iNavFlight/inav/files/3664658/LOG00001.zip)

![image](https://user-images.githubusercontent.com/26075468/65804819-12b85800-e138-11e9-9652-080903375546.png)

**Comment by metametaclass** [comment]
![image](https://user-images.githubusercontent.com/1159369/65805202-496c8d80-e18d-11e9-87b3-b75990b7352e.png)
Difference between bad and good log files

**Comment by stronnag** [comment]
Possibly excessive loop time / log rate (500, 1/1). Hardware can't keep up. 
Can you log consistently at lower rates?

**Comment by DzikuVx** [comment]
Too fast loggings is the most probable reason

**Comment by laurentopia** [comment]
The SD does 12 MB/s write, what do you recommend log% for this loop time?

![image](https://user-images.githubusercontent.com/26075468/66524081-46836e00-eaa6-11e9-835a-14cde85c6ee5.png)
