### ISSUE TITLE
Remove output 2 as motor and make it a servo output

### ISSUE THREAD

**Issue by Jonny360** [iNavFlight/inav#5107]
Currently output 1 and 2 are motor outputs. On 4 motor output boards like the betaflight f3 and f4 boards this means that you cannot use them to setup a plane with 1 motor and 3 servos (elevator, rudder, ailerons). This is a very common setup. Much more common than ever having a plan with 2 motors is. It seems to me that if resource management is not going to be a user adjustable option it makes more sense to have basic plane layouts be the default instead of dual motor layouts. 

Please change output 2 to be a servo output instead of a motor output and put motor 2 further down the line of outputs like output 5+.

**Comment by DzikuVx** [comment]
Short answer: this is not possible on majority of the boards due to hardware limitations of assigned timers and resource mapping from BF is not really solving those issues. BetaF4 already uses one motor and 3 servos for example.

Long answer https://www.youtube.com/watch?v=v4R-pnO4srU
