### ISSUE TITLE
VL53L1X 400cm rangefinger

### ISSUE THREAD

**Issue by whoim2** [iNavFlight/inav#5109]
This lowcost sensor pin-to-pin compatible with supported L0X. But have longer range - 400cm in ideal conditions.

**Comment by digitalentity** [comment]
I have tested L1X and in real-world conditions (over mate flooring etc) it doesn't behave much better than L0X. Still, might be useful.

**Comment by nathanjel** [comment]
I have submitted PR #6572 to enable VL53L1X rangefinder support.
The maximum usable range, given a reasonable timing budget of 33ms, is 310cm.
