### ISSUE TITLE
Can I fly 

### ISSUE THREAD

**Issue by LawrenceLDJr** [iNavFlight/inav#5113]
## Current Behavior
Disabled Synchronize looptime with gyroscope, it's off at startup, I enabled it and reboot and it's turned off.

## Steps to Reproduce
1.Install INav 4.2.1
2.New Airbot F4 V6, Tyhpoon 30A 4 in 1 ESC
3.Choose synchronize looptime with gyroscope 
4.Every reboot of INav deselects this option

## Expected behavior
My X220S has this option enabled and flies great. I enable this option with this quad and it switches off on every reboot. I have ESCs calibrated, Multishot 2k, gyro lpf 256hz, flight control looptime 2k, same settings as the X220S. Synchronize looptime won't stay enabled. Gyro, accel, mag, baro, gps all blue, all calibrated.

## Additional context

---

- FC Board name and vendor: Airbot F4 V6, Amazon LEACO
- INAV version string: 2.2.1

**Comment by DzikuVx** [comment]
`Every reboot of INav deselects this option`
That mean option is not supported by hardware. It's still safe to fly

**Comment by LawrenceLDJr** [comment]
Thx Pawel... gonna try in a few minutes... 
    On Thursday, October 3, 2019, 06:27:38 AM CDT, Paweł Spychalski <notifications@github.com> wrote:  
 
 
Every reboot of INav deselects this option
That mean option is not supported by hardware. It's still safe to fly
