### ISSUE TITLE
Option to chop off the first four digits of the plus code, since they're optional

### ISSUE THREAD

**Issue by skorokithakis** [iNavFlight/inav#5114]
## Current Behavior
Currently, INAV shows more than 10 digits of a plus code. The first four digits are optional and can be omitted by specifying a general location (like the city you're flying near).

## Desired Behavior

Adding an option to not show the first four digits would make the plus code display much shorter and more convenient.

## Who does this impact? Who is this for?
Anyone who uses plus codes could benefit from this.

**Comment by LawrenceLDJr** [comment]
You can choose the amount of digits you desire...!

**Comment by skorokithakis** [comment]
Yes but it doesn't go lower than ten and you can't cut off the first four, so you lose accuracy.

**Comment by avsaase** [comment]
I second this request. The plus code could be significantly shortened. Added benefit is that your location is at least somewhat obscured when posting DVR footage online.

**Comment by avsaase** [comment]
Just commenting again in the hope that one of the devs see it. I think this should be very easy to implement, but I don't have any experience with this programming language so I cannot really help myself.

**Comment by avsaase** [comment]
I managed to figure out how to do this. See the above linked PR.
