### ISSUE TITLE
Support for New Target Airbot F7, uses ICM20602 Gyro

### ISSUE THREAD

**Issue by mikeboon** [iNavFlight/inav#5115]
## Current Behavior

Currently there is no Target for Airbot F7. Not to be confused with Omnibus F7.
Airbot F7 uses the newer ICM20602 Gyro.

## Who does this impact? Who is this for?

Any one who wish to use Airbot F7 FC on iNav.

**Comment by DerElch87** [comment]
[https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md](url)

The same discussion was made some days ago with somebody elso, but another board. Please have also a look there:
[https://github.com/iNavFlight/inav/issues/5110](url)
