### ISSUE TITLE
Flip over after crash aka turtle mode

### ISSUE THREAD

**Issue by DangerD256** [iNavFlight/inav#5126]
Can't find such request here
Any plans to add it from betaflight?

**Comment by marianomd** [comment]
This is particularly useful also when drone ends hanging from a tree.

**Comment by Vasilifpp** [comment]
The last thing I miss on inav..

**Comment by LeoNorw** [comment]
Just wanted to join in and support the request for Turtlemode.

**Comment by gbbulciolu** [comment]
+1

**Comment by evilphish** [comment]
Same here. Especially with a firmware like INAV that is sort of geared towards longer range flying this should be a must-have. I guess chances are that INAV users end up flipped over further from home far more often than others ;)

So: +1

**Comment by TimJC513** [comment]
The lack of turtle mode is keeping me from using INAV on my 7" quad.

I'd also love to see dshot beacon supported, which would benefit multirotor and fixed wing.

**Comment by gigapoc** [comment]
Same here, only thing preventing me to switch to iNav ! +1 !

**Comment by avaninder** [comment]
Same here. Would like turtle mode on inav!

**Comment by almumen** [comment]
Is turtle mode still not available?

**Comment by almumen** [comment]
> Is turtle mode still not available?

Sorry, just figured out from below progress bar that it is going to be a future development.

**Comment by JohnRambo7039** [comment]
My plane crashed into the house three days ago, and it was belly up...
This is a very important function, hope can be achieved!!!

**Comment by Vitaly591** [comment]
I need this feature.

**Comment by Larsaeaeae** [comment]
Me too! :)

**Comment by UweHeim** [comment]
+1 to set higher priority on this. schouldn't be rocket science. is the slow approach on this to save memory for the still supported F3? or any other concerns? would be nice to see some kind of feedback on why this seems to have no significant priority since 2019...

**Comment by avsaase** [comment]
This is resolved in #6685 so this issue can be closed.
