### ISSUE TITLE
[Fixed Wing] Return to home doing strange things when loitering around home

### ISSUE THREAD

**Issue by purpletreee** [iNavFlight/inav#5131]
Hello Friends,
I just set up a Nano talon with an f4 flight controler to run inav. Now I work on tuning it. Problem I have at the moment is Return to home is doing strange things when it sould loiter around home, it isnt really doing circles at all. And sometimes it has a Spiral of death. I done some autotune just before. Here is my diff and dump
[diffdump.txt](https://github.com/iNavFlight/inav/files/3720863/diffdump.txt)
I will atttach a video showing the problem in a second

**Comment by Jetrell** [comment]
@purpletreee Setup support is more often found on the iNav RCgroups thread. 
Your question is being answered by someone on RCG at present, who also had the same issue with a Nano Talon. 
https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project/page1653/#24792
https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project/page1663/#24936
