### ISSUE TITLE
quad 2.2.1 had good gps flew awaycrazy on first test of rth quad was not found . cant afford to build another even was using dragonlink shut off rth switch still could not get control never found .i trusted you it failed. thanks for losing my only quad

### ISSUE THREAD

**Issue by that1jim** [iNavFlight/inav#5150]
## Steps to Reproduce

1.cant reproduse it flew away doig flips and crazy shit and never found . to poor to build again. had flown on betaflight for sometime and dragonlink without a glitch. 3rd flight on inav invocked rth for test shutoff 2 seconds later it was no loger controlable lost never found
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by Jetrell** [comment]
Do you have your `Diff All` settings? 
What GPS unit did you used? 

Any information would be helpful to get an idea of what went wrong.

**Comment by giacomo892** [comment]
You could have taken control just by switching bad to ANGLE/ACRO/HORIZON.
Thanks for having read all the docs.
