### ISSUE TITLE
Motor mapping overwritten by new servo

### ISSUE THREAD

**Issue by gvet** [iNavFlight/inav#5151]
Motor mapping of motor 6 in hexacopter setup is overwritten by servo if I add a new servo on the mixer tab.

I expected servo 0 to be added to S7 but it is mapped to S6

-Hardware: Hexacopter setup on Matek F722 STD
-inav V2.2.1
-Inav Configurator 2.3.0 RC2

![Matek_F722_MixerTab](https://user-images.githubusercontent.com/18708524/67162945-b547ad80-f369-11e9-900f-4be0b2c97562.png)

**Comment by DzikuVx** [comment]
Use target `MATEKF722_HEXSERVO` instead.
