### ISSUE TITLE
BLheli_32 ESC "Auto Telemetry" and Temperature

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav#5165]
This issue references #2710 
The flight controller normally requests telemetry data from the ESC. 
But if `Auto Telemetry` is enabled in the BLheli_32 suite. The ESC will send out telemetry data to the FC at set intervals. 
This is useful if we want to use an analog ESC control protocol(multishot), instead of digital(Dshot).
This feature is more applicable to Fixed-wings, than Multi-rotors. Because the data from multiply ESC, being sent at the same time may get corrupted.

Plus output - `ESC temperature` with configurable maximum alarm set point.

![Auto telemetry](https://user-images.githubusercontent.com/47995726/67625141-c0c53800-f885-11e9-822e-48b7939bd02d.PNG)

**Comment by digitalentity** [comment]
Damn, I forgot about this one :scream:

**Comment by Jetrell** [comment]
@digitalentity 

> 
> 
> Damn, I forgot about this one 

These things happen :-)

**Comment by digitalentity** [comment]
#5674 created
