### ISSUE TITLE
Problems with Flysky receivers (FS - iA6B and FS - A8S) on Matek 405 wing

### ISSUE THREAD

**Issue by Garabuyo** [iNavFlight/inav#5172]
## Steps to Reproduce

1. Connect Flight Controller to PC by USB port
2. Open INAV
3. Click on Connect
4. Conect the receiver "FS-A8S" to FC (Those steps are identical like the manual)
5. Connect black cable to pin **G** of FC
6. Connect red cable to pin **4.5** of FC
7. Connect withe cable to pin **Sbs** of FC
8. Connect yellow cable to pin **T2** of FC. Led on receiver is flashing.
9. Bind the receiver and radio (in this case we can bind the receiver by pressing the BIND botton)
10. Led on Receiver is now freeze.
11. Go to INAV and setup like this [http://www.mateksys.com/?portfolio=f405-wing#tab-id-3]
12. Now go to configuration in INAV and set Receiver Mode on Serial based receiver (Speksat, SBUS, SUMD) and then set Serial Receiver Provider on IBUS.

13. Radio (FS-i6x):

**Output mode:**

PWM
PPM -> OK

**Serial**  

i-BUS-> OK
S. BUS  

Now I move sticks on Radio and I can´t see nothing on INAV (Radio tab).

## Expected behavior

A response between the radio vs Inav in receiver Tab in all chanels
## Suggested solution(s)

I dont Know
## Additional context

---

- FC Board name and vendor: FLIGHT CONTROLLER F405-WING (Matek Systems)
- INAV version string: 2.2.1

**Comment by breadoven** [comment]
No iNav bug simply down to your connections being wrong.

Use IBUS or PPM, don't use both together. Guessing Sbs pin is for SBUS only so won't work with iBUS.

Disconnect the PPM and either set the transmitter to SBUS if you use the Sbs pin or connect the White wire to a Rx pin on the FC if you want to use iBUS. T2 won't work it's for Transmitting from the FC not receiving, use R2 instead.
