### ISSUE TITLE
Optical flow support on spracing f3?

### ISSUE THREAD

**Issue by suraj022** [iNavFlight/inav#5174]
I've been trying to add optical flow sensor (CX-OF) to my spracing f3 flight controller running INAV 2.2.1 latest firmware.

CX-OF I'm using is a cheap clone bought from here [https://www.aliexpress.com/item/33005508643.html?spm=a2g0o.productlist.0.0.cb302635OmNp0c&algo_pvid=b65a61b6-9e68-459e-9f07-05e8c2c0738d&algo_expid=b65a61b6-9e68-459e-9f07-05e8c2c0738d-0&btsid=7dd632fa-9f98-4ebf-b2b3-fb29a0c30390&ws_ab_test=searchweb0_0,searchweb201602_10,searchweb201603_52](url)

I've tried to select CX-OF from the list of sensors in optical flow. but it seems to disable it once I reboot the FC. Note that I've also enabled HCSR-04 rangefinder (which works fine).

I've also tried to select "optical flow" mode on UART2 in ports menu without luck

Is there anything Obvious I'm missing? there doesn't seem to exist any sort of tutorial on this topic.
 Are optical flow sensors deprecated in INAV firmware?

**Comment by DzikuVx** [comment]
All F3 boards are end-of-life and they will not receive any new functions due to limited memory and flash
