### ISSUE TITLE
Compass can't be calibrated

### ISSUE THREAD

**Issue by GGYHCLZ** [iNavFlight/inav#5176]
My  Board  is   Matek F405.

My Compass can't be calibrated.
But  if  i  use   BETA  Firmware.
The  Compass   can   worked  very   well.

**Comment by GGYHCLZ** [comment]
![QQ截图20191030164956](https://user-images.githubusercontent.com/49911264/67842668-8f729380-fb35-11e9-8564-23dc8418eddb.png)

**Comment by GGYHCLZ** [comment]
![QQ截图20191030164853](https://user-images.githubusercontent.com/49911264/67842684-98636500-fb35-11e9-8e9b-f82cf94edd8c.png)

**Comment by GGYHCLZ** [comment]
After Save  And  Rebort

![QQ截图20191030164923](https://user-images.githubusercontent.com/49911264/67842709-a913db00-fb35-11e9-8162-2fa951f3659e.png)

**Comment by GGYHCLZ** [comment]
![QQ截图20191030164937](https://user-images.githubusercontent.com/49911264/67842869-f132fd80-fb35-11e9-8e81-c73e7580264b.png)

**Comment by GGYHCLZ** [comment]
After  calibrated
![calibrated](https://user-images.githubusercontent.com/49911264/67844337-8931e680-fb38-11e9-83f4-534b12150388.png)

**Comment by GGYHCLZ** [comment]
![QQ截图20191030171534](https://user-images.githubusercontent.com/49911264/67844556-ecbc1400-fb38-11e9-9f76-47606daf42d8.png)

**Comment by GGYHCLZ** [comment]
![QQ截图20191030170000](https://user-images.githubusercontent.com/49911264/67844896-8257a380-fb39-11e9-8651-1ee7d0c5879e.png)
![IMG_20191030_170124](https://user-images.githubusercontent.com/49911264/67844904-85529400-fb39-11e9-9161-19eaa3538e70.jpg)

**Comment by GGYHCLZ** [comment]
![IMG_20191030_170545](https://user-images.githubusercontent.com/49911264/67844982-a1563580-fb39-11e9-90cf-f35de8e05768.jpg)
![QQ截图20191030170601](https://user-images.githubusercontent.com/49911264/67844999-a9ae7080-fb39-11e9-94f9-28199ff18e31.png)

**Comment by GGYHCLZ** [comment]
![IMG_20191030_170336](https://user-images.githubusercontent.com/49911264/67845042-baf77d00-fb39-11e9-971f-8be271a55a32.jpg)
![QQ截图20191030170425](https://user-images.githubusercontent.com/49911264/67845051-c0ed5e00-fb39-11e9-9aa6-f59cc51be4a9.png)

**Comment by GGYHCLZ** [comment]
![IMG_20191030_170224](https://user-images.githubusercontent.com/49911264/67845098-d498c480-fb39-11e9-9f37-f0c64f031971.jpg)
![QQ截图20191030170200](https://user-images.githubusercontent.com/49911264/67845233-19246000-fb3a-11e9-9406-d45f78444666.png)

**Comment by GGYHCLZ** [comment]
I use it

![QQ截图20191031184452](https://user-images.githubusercontent.com/49911264/67940517-ca94c580-fc0e-11e9-995d-09267d88d2ce.png)

**Comment by DzikuVx** [comment]
this is fixed in 2.5
