### ISSUE TITLE
Logic Condition Precedence

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav#5180]
Simple question ... is there any order of precedence with Logic conditions ? i.e. would LC 0 take precedence over LC 1 for the following example or visa versa or something else ?:

LC 0 = Channel 1 < 1800
LC 1 = Channel 1 < 1500

Which LC is used at 1400 ?

**Comment by DzikuVx** [comment]
LCs are independent to each other and evaluated by order. 
In this example both will evaluate as `true`
