### ISSUE TITLE
HAL: Unify sensor interface

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#519]
Currently each sensor uses it's own interface for detection, init, configuring and reading. I think we need to unify this. Possibly each sensor driver should expose a method table allowing the following:

```
bool detect(void);
bool init(void * initParams);  // initParams are sensor-dependent
bool setParam(int paramId, int paramValue);  // sensor dependent data
bool read(void * buf);  // sensor-dependent data
void poll(void); // a method to be called periodically by a task to allow driver to do something in the background
```

All current sensors (ACC, GYRO, MAG, BARO, RANGEFINDER, GPS) should be converted to use this framework.

Thoughts?

**Comment by Linjieqiang** [comment]
Great for coding .

**Comment by martinbudden** [comment]
Currently in `drivers/sensors.h` we have:

```
struct acc_s;
typedef bool (*sensorInitFuncPtr)(void);                    // sensor init prototype
typedef bool (*sensorReadFuncPtr)(int16_t *data);           // sensor read and align prototype
typedef void (*sensorAccInitFuncPtr)(struct acc_s *acc);    // sensor init prototype
typedef void (*sensorGyroInitFuncPtr)(uint8_t lpf);         // gyro sensor init prototype
typedef bool (*sensorInterruptFuncPtr)(void);               // sensor Interrupt Data Ready
```

We can unify these by using some `void *` parameters, but personally I'd prefer to keep the minor differences and retain the type checking.

Also it's difficult to virtualise the `detect` function, since the function pointers are set in the `detect` function. Also virtualising the `detect` function, just so that it can be used once in `sensors/initialisation.c` will actually make the code more complicated and difficult to read.

**Comment by digitalentity** [comment]
I don't see a point in having a separate `sensorInitFuncPtr`, `sensorAccInitFuncPtr` and `sensorGyroInitFuncPtr`. 
Also, baro init it handled within `detect()` method which is not very straight-forward.

My idea might be too general, but what I really want to do it to make all sensors respect the detect -> init -> read chain without hiding parts of it.

**Comment by martinbudden** [comment]
Yes, I agree about the detect -> init -> read chain.

**Comment by martinbudden** [comment]
And I agree we should work on tidying this up.

Baro detection/initialisation should be changed to follow the pattern. I've just had a look, and it's not entirely straightforward and will require testing.

**Comment by jaecktec** [comment]
How about the [Adafruit unified sensor library](https://learn.adafruit.com/using-the-adafruit-unified-sensor-driver/introduction) kind of style?

**Comment by martinbudden** [comment]
I had an email github notification from @jaecktec which seems to have been lost by github.

They suggested using the style of the Adafruit unified sensor library -https://learn.adafruit.com/using-the-adafruit-unified-sensor-driver/introduction

This is certainly worth looking into.
