### ISSUE TITLE
NAV - Use incremental PIDs

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#52]
I've been told that incremental PIDs are better. Description here - http://www.flightgear.org/Docs/XMLAutopilot/node3.html
This needs to be looked into.

**Comment by digitalentity** [comment]
Looks like there is an implementation of such PID controller in librepilot: https://github.com/librepilot/LibrePilot/blob/next/flight/libraries/math/pid.c#L148

**Comment by bk79** [comment]
to me doesn't look the same, or probably I read it wrongly, in small terms it works like OUTPUT=OUTPUTpreviouscan + ((PIDoutnow-PIDoutpreviousscan)

**Comment by digitalentity** [comment]
I didn't go deep into incremental PIDs yet. Might be different approaches to the same problem. This will take some time to look into.
