### ISSUE TITLE
Compiling problem with Windows 64bit and Cygwin for inav 2.3.0-RC2

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav#5207]
I run into the following problem, when I want to compile the actual firmware:
Could anybody help how to solve the problem?

![grafik](https://user-images.githubusercontent.com/25489220/68997317-51030580-08a5-11ea-93c4-2595d722af95.png)

**Comment by stronnag** [comment]
Use Linux, MacOS, a Linux VM or WSL. 
Windows 64bit, cygwin and the 32bit cross compiler get very confused. We cannot fix that breakage.

**Comment by Ralfde** [comment]
oh. It worked until 2.3.0-RC1

**Comment by DzikuVx** [comment]
Like stronnag wrote, do not use cygwin. on windows 10 just use WSL https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20with%20Linux%20Subsystem.md
