### ISSUE TITLE
All receiver inputs suddenly drop below 1000 and go back to normal

### ISSUE THREAD

**Issue by shabbirun** [iNavFlight/inav#5210]
I have the latest 2.2.1 on a Mamba F405 FC set up on a wing. I am using an r9mm receiver using FPORT on TX3.

After about 5-10 seconds of giving inputs, all the inputs in the RX tab go to zero for a few seconds and then go back to normal. This causes the servos to move erratically and lock up until the link is back.

This happens when connected to the configurator as well as in flight.

I am using an r9mm with FPORT because my XM+ did not work - all the values were erratic even though it was wired up correctly. I am not sure if it is an issue with the board/firmware or the receiver.

- FC Board name and vendor: Mamba F405
- INAV version string: 2.2.1

Any help is appreciated. Thank you

**Comment by DzikuVx** [comment]
This looks like a receiver-transmitter problem, not INAV related. Check for failsafes, radio configuration and so on
