### ISSUE TITLE
Matek F765-WING RTH/HOLD issue (firmware 2.3.0)

### ISSUE THREAD

**Issue by Airscrew** [iNavFlight/inav#5213]
Video of issue: [https://youtu.be/G5Tb-D_dYXM](url)
Dump is here: [https://pastebin.com/ncKskEMD](url)
BlackBox file of flight here: [https://fex.net/s/nkazdxs](url)

servo 0 - roll
servo 1 - flaps
servo 2 - yaw
servo 3 - pitch

The plane is an Sonic model binary 1200 with 4 channels (aileron+elevator+rudder+motor). Using Matek F765 Wing (firmware 2.3.0 Oct 28 2019).

**Comment by DzikuVx** [comment]
BBlog does not exists. From the video it looks like a stall. Increase cruise throttle
