### ISSUE TITLE
Support Kakute F7 HDV

### ISSUE THREAD

**Issue by sebaszz** [iNavFlight/inav#5221]
## Current Behavior
Hi,

Is the FC kakute F7 HDV (DJI version) supported for Inav? 

I tried to get it working with the latest stable and unstable version firmware.
Flashing went ok but after I couldn't connect anymore to the controller. 
Also after rebooting Inav configurator (2.3.2) and FC.

Flashed to BF, no issues.
Tried again to Inav same connection issues.

**Comment by DzikuVx** [comment]
Please try `2.3` that is avalable under "Show unstable releases"

**Comment by sebaszz** [comment]
tried a couple of times without success. Other suggestions?

![12345](https://user-images.githubusercontent.com/31382488/69578367-a12e4600-0fd0-11ea-89df-e5e57175c43d.PNG)

**Comment by DzikuVx** [comment]
I will contact Holybro

**Comment by sebaszz** [comment]
thank you!

**Comment by myhrmans** [comment]
Any success on this?

**Comment by DzikuVx** [comment]
not really, INAV devs have no hardware to test. You might help by contacting Holybro with a request to help as well

**Comment by sebaszz** [comment]
I will contact them

maybe a noob question but can the hardware data not retrieved from the betaflight firmware file?

**Comment by myhrmans** [comment]
I also contacted them, they have contacted you iNav so hopefully this can be solved.

**Comment by wahightower** [comment]
This does not appear to be a Feature Request rather a bug.  I have the same problem.  Cannot connect Kakute F7 to Inav using Inav configurator 2.3.2 and Kakute F7 target 2.3.0.  No problem connecting to Betaflight.

**Comment by DzikuVx** [comment]
HDV is currently not supported. It should be supported in a next few weeks.

sob., 7 gru 2019, 14:12 użytkownik wahightower <notifications@github.com>
napisał:

**Comment by wahightower** [comment]
Thanks for the response.  Look forward to a new target.

**Comment by TiTTaN40** [comment]
I have the same problem, I'm looking forward to MAJ

**Comment by DzikuVx** [comment]
@TiTTaN40 @wahightower @myhrmans @sebaszz 
[inav_2.3.0_KAKUTEF7HDV.zip](https://github.com/iNavFlight/inav/files/3963958/inav_2.3.0_KAKUTEF7HDV.zip)

The hex file for Kakute F7 HDV is in the attachment. Please check if it's working correctly

**Comment by wahightower** [comment]
Connects and configures.  Have not flown yet.  Thanks for the work you do.

**Comment by TiTTaN40** [comment]
It's awesome,
Bravo to the programmers.
Someone to test the OSD on DJI Glasses

**Comment by DzikuVx** [comment]
@TiTTaN40 on the topic of DJI OSD, nothing changed really

**Comment by sebaszz** [comment]
Working for me as well.  haven't flown yet. 

Thanks!

**Comment by DzikuVx** [comment]
HDV target is now available in configurator for flashing

**Comment by cristian893** [comment]
Hi guys, 
I want to build a custom firmware on Kakute F7 HDV, but I don't have the target files for this version. 
Do you know where I can find them?

Thanks!

**Comment by giacomo892** [comment]
Is KAKUTEF7 HDV is just a variant

**Comment by blaireau2fr** [comment]
Hi all,
I try to use a KAKUTE F7 HDV on an airplane but I can't flash the firmware (MAC).  Mode DFU is ok, I tried to load firmware online and from local but when I click on "flash firmware" nothing appears... (I have no pb on BF so my cable and drivers should be ok).
Do you have any idea about what I can do to solve my problem?

**Comment by redjacketKR** [comment]
Is custom OSD work in new 1.0.0.5 firmware?

**Comment by myhrmans** [comment]
@redjacketKR not quite, think it still needs some work. Can write a list later tonight what is working and not

**Comment by redjacketKR** [comment]
Thank you for replying. I wanted to move from betaflight due to position/altitude hold and RTL.
But I guess I have to wait a little more.

**Comment by Some-Won-1** [comment]
And now... Katute H7 Bluetooth same issue and using Configurator 4.1. Version 5.0 is out, but no files to load into this thing.
