### ISSUE TITLE
GPS No data

### ISSUE THREAD

**Issue by DJP0P** [iNavFlight/inav#5232]
Hello I have a problem with gps BN-220 it is wired right it lights up it show up blue in INAV but in GPS tab doesnt show location data cant lock and shows 0 sats in osd. I tryed UBLOX, NMEA, UBLOX7 it is blue on UBLOX7 and UBLOX then I tried all the baud rates nothing helped. Swapping uarts didnt helped. I have Matek F411-Wing FC
![dsfsfsfs](https://user-images.githubusercontent.com/58330381/69865013-7843d480-12a0-11ea-9e5f-ff8a5adfdb47.png)
![Komentár 2019-11-29 104251](https://user-images.githubusercontent.com/58330381/69865014-7843d480-12a0-11ea-89b1-9309de46a839.png)
![Komentár 2019-11-29 110435](https://user-images.githubusercontent.com/58330381/69865015-78dc6b00-12a0-11ea-8d9f-33472c4a0a34.png)

**Comment by Jetrell** [comment]
@DJP0P It has plenty of `Timeouts`.  Do you have another GPS unit to test it with?

**Comment by DJP0P** [comment]
Defective GPS unit
