### ISSUE TITLE
use only the tfmini lidar 

### ISSUE THREAD

**Issue by ThijnLans** [iNavFlight/inav#5241]
is it possible to use only the lidar and turn off the barometer because of the lidar cabI use to 12 meter

**Comment by digitalentity** [comment]
Lidar is not reliable enough. We need something that is not dependent on distance to the surface to cover the gaps in lidar data.

**Comment by ThijnLans** [comment]
> Lidar is not reliable enough. We need something that is not dependent on distance to the surface to cover the gaps in lidar data.

so it is not possible becouse i make a inside drone and I don;'t have a gps and I will turn on the baro on if the lidar is broken or won't work

**Comment by ThijnLans** [comment]
and is it possible to see the alt m from the lidar on the osd screen

**Comment by thijn1234** [comment]
> Lidar is not reliable enough. We need something that is not dependent on distance to the surface to cover the gaps in lidar data.
