### ISSUE TITLE
Improved cruise mode

### ISSUE THREAD

**Issue by artemsh** [iNavFlight/inav#5245]
## Current Behavior
When flying in the "cruise" mode, and changing the position of the pitch sticks, there is an increase or decrease in throttle according to the formula nav_fw_cruise_throttle - (nav_fw_pitch2thr * pitch_angle), after releasing the sticks, the fixed wing returns to a straight flight.

## Desired Behavior
When raising or descending the wing, you have to constantly hold the sticks, which can be tiring during long flights. When using only throttle, the speed of ascent and descent is slow.

## Suggested Solution
In "cruise" mode, using pitch sticks, decrease or increase trim the pitch angle, the flight controller should strive to maintain this angle, within the parameters (nav_fw_min_thr, nav_fw_max_thr, nav_fw_climb_angle, nav_fw_dive_angle, nav_fw_pitch2thr). For more active lifting it is necessary to activate the servos, to the detriment of speed. It may be necessary to limit the maximum and minimum altitude. I would also like to have in the "cruise" mode the ability to change the nav_fw_cruise_thr throttle stick within the specified limits, for greater efficiency.
## Who does this impact? Who is this for?
All inav users performing long fixed wing flights.

**Comment by CMFischer** [comment]
In my radio mixes (not Inav mixes) I add a POT & switch to the elevator inputs.  Turn on switch, adjust POT to add or subtract from elevator setting.  Good for long climbs or descents.
