### ISSUE TITLE
Units measure change

### ISSUE THREAD

**Issue by pincorr** [iNavFlight/inav#5246]
## Current Behavior
Speeds and distances use centimeter as unit of meaure. 

## Desired Behavior
Change all variable that requires the input in centimeter, into variables that request meter as unit of measure 

## Suggested Solution
change input from cm.or cm/s to m. or m/s

## Who does this impact? Who is this for?
This impacts the safety, since an erroneus input of cm , due to conversion meters to cm, can bring to an unexpected response of the machine.

**Comment by DzikuVx** [comment]
This will not happen without overall rewrite of all of navigation. Internal unit are `cm` and this will rather ot change
