### ISSUE TITLE
Can't Calibrate  Accelerometer

### ISSUE THREAD

**Issue by uakc** [iNavFlight/inav#5252]
Can't Calibrate  Accelerometer after 3rd step setup keep on reverting back to 1st step.
my board Matek F405-STD
https://youtu.be/AOEnNNUL19A

**Comment by whoim2** [comment]
Try reflash with full erase chip

**Comment by uakc** [comment]
tried that a few times.. no luck.. maybe F405-STD not supported..

**Comment by whoim2** [comment]
> tried that a few times.. no luck.. maybe F405-STD not supported..

Supported 100%, my friend use 2.2.1 inav on this FC and have gps/compass, worked perfectly.
Try calibrate from sticks.

**Comment by uakc** [comment]
what do you mean "Try calibrate from sticks. "  how ?

**Comment by whoim2** [comment]
> what do you mean "Try calibrate from sticks. " how ?

![Без названия (1)](https://user-images.githubusercontent.com/13419599/70174209-8309c980-16e5-11ea-9473-491e30e870ac.png)

**Comment by whoim2** [comment]
Also, you may trying calibrate from speedybee software on android, from usb or bt
