### ISSUE TITLE
Add LED Strip Support on Kakute F7 aio

### ISSUE THREAD

**Issue by ilya-88** [iNavFlight/inav#5271]
In betaflight, the LEDs work and switch the light. but I ran into the problem of complete non-robot ability ... help solve this issue. this board isn’t so bad as not to add features to it. or do I need to perform as Greta Tintin Eleonora Ernman Thunberg to pay attention to me ???

**Comment by MaxLansing** [comment]
i would like to second that request, same with the Kakute F7 V1.5, works on BF, in inav it shows 0 LEDs remaining. Any chance to get that working? thx to all of you.
