### ISSUE TITLE
Custom firmware v.2.3.0 for MATEKSYS

### ISSUE THREAD

**Issue by romko1** [iNavFlight/inav#5291]
Hello,
Santa brought me the Christmas TBS Micro RX and Nano TX for both of my drones.
I have an older version FW 2.2.1 for MATEKF405 and MATEKF722mini 
I have modified FW for TARGET - MATEK405: target.c and target.h and for TARGET - MATEKF722: target.h.
However, I wanted to create a new custom FW v.2.3.0, but when Linking MATEKF405 crashes the compilation.
Please someone to compile my own FW for the MATEKF405 and MATEKF722mini board.
_Modification for MatekF722mini target.h: (mod line 182)_
#define AIRSPEED_ADC_CHANNEL           ADC_CHN_4

// *************** PINIO ***************************
#define USE_PINIO
#define USE_PINIOBOX
#define PINIO1_PIN                  PC8 // VTX power switcher
#define PINIO2_PIN                  **PB3 // Camera on/off**

// *************** LEDSTRIP ************************
#define USE_LED_STRIP

****************************************************************************************************
_Modification for MatekF405 target.c: (mod line 36)_
#endif
    DEF_TIM(TIM8, CH2, PC7,  TIM_USE_MC_MOTOR |                    TIM_USE_FW_SERVO, 0, 1), // S2  UP(2,1)
    DEF_TIM(TIM8, CH3, PC8,  TIM_USE_MC_MOTOR |                    TIM_USE_FW_SERVO, 0, 1), // S3  UP(2,1)
    DEF_TIM(TIM8, CH4, PC9,  TIM_USE_MC_MOTOR |                    TIM_USE_FW_SERVO, 0, 0), // S4  UP(2,1)

    DEF_TIM(TIM2, CH1, PA15, TIM_USE_PWM                                           , 0, 0), // S5  UP(1,7) - smartaudio VTX

#ifdef MATEKF405_SERVOS6

_Modification for MatekF405 target.h (mod line 122)_
#define USE_SOFTSERIAL2
#define SOFTSERIAL_2_TX_PIN      **PA15  //smartaudio VTX - S5**
#define SOFTSERIAL_2_RX_PIN      NONE  //free

Thank you.
R

**Comment by romko1** [comment]
Hello,

I followed this procedure: 
https://github.com/iNavFlight/inav/blob/master/docs/development/Generic_Linux_development.md
and I still have a problem with Linking MATEKF405 :(

Please help. Thank you.
R

**Comment by stronnag** [comment]
If you actually posted the compiler and  linker output then maybe someone can help you. Just saying it doesn't work is pointless.

**Comment by romko1** [comment]
Sorry, here are 2 print-screens:
![pb_compilation](https://user-images.githubusercontent.com/34416051/71532876-e73f3800-28f5-11ea-81c9-243167d7d36b.jpg)
.
.
.
.
![pb_compilation_2](https://user-images.githubusercontent.com/34416051/71532832-9af3f800-28f5-11ea-98f2-0aa2675089d5.jpg)

**Comment by stronnag** [comment]
Don't use a native Windows environment, it can't cope with a 32bit cross compiler in a 64bit run time.
Use Linux,  WSL or a Linux VM.

**Comment by romko1** [comment]
@stronnag thank you for the guidance, but I do not currently have Linux available and W10. Can you generate the hex files, please? Thank you.

**Comment by datamann** [comment]
Everyone with W10 can have Linux available. Just follow this easy to follow instructions.
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20with%20Linux%20Subsystem.md

**Comment by romko1** [comment]
@datamann thank you, according to this procedure I created new firmware 2.3.0, but I had two warnings there. is it something important or is it OK?
Thank you for your response.
![compilation_custom_FW](https://user-images.githubusercontent.com/34416051/71640840-54eeb980-2c92-11ea-800b-da0170ebd096.jpg)
