### ISSUE TITLE
[Multirotor] Motors stop spinning while armed

### ISSUE THREAD

**Issue by sare** [iNavFlight/inav#5294]
https://www.youtube.com/watch?v=I1mlmKhLJi8

I flashed iNav 2.3 to my Multirotor and have some strange issues:
When I arm, the motors start spinning and after a few seconds, they just stop spinning (as if it failsafes), although the quad is still armed. When I disarm, they briefly start spinning before the quad disarms. (See Video) I basically just used the 3-7 inch multirotor preset, only modified by using "set yaw_motor_direction = -1" to be able to run reversed props direction. I think this might be the problem, because I was able to launch the quad with this setting (and it spinned to the moon), without this random stop. But I only have a little bit of fixed wing experience with iNav and want to be sure.
The setup is a Matek F722SE with Airbot Wraith V2 and Racerstart 2508 1200kV motors, the quad flew fine on Betaflight 4.1.1 before, so I would rule out a hardware failure.

**Comment by OlivierC-FR** [comment]
> 
> 
> https://www.youtube.com/watch?v=I1mlmKhLJi8
> 
> I flashed iNav 2.3 to my Multirotor and have some strange issues:
> When I arm, the motors start spinning and after a few seconds, they just stop spinning (as if it failsafes), although the quad is still armed. When I disarm, they briefly start spinning before the quad disarms. (See Video) I basically just used the 3-7 inch multirotor preset, only modified by using "set yaw_motor_direction = -1" to be able to run reversed props direction. I think this might be the problem, because I was able to launch the quad with this setting (and it spinned to the moon), without this random stop. But I only have a little bit of fixed wing experience with iNav and want to be sure.
> The setup is a Matek F722SE with Airbot Wraith V2 and Racerstart 2508 1200kV motors, the quad flew fine on Betaflight 4.1.1 before, so I would rule out a hardware failure.

what the ESC protocol set to ?
If its DS1200, try DS600 or DS300
