### ISSUE TITLE
Lua PID tuning

### ISSUE THREAD

**Issue by Kalveo** [iNavFlight/inav#5302]
Is it possible to change the PID parameters from the radio using Lua scripts in the same manner as for Betaflight?

**Comment by simtcrom** [comment]
I am also looking for similar feature.
Also looking for a way to change VTX power, band, channel using lua on taranis.

**Comment by machadofelipe** [comment]
@simtcrom, this is under development in LuaTelemetry: https://github.com/iNavFlight/LuaTelemetry/issues/157

@Kalveo, I think there is no LuaScript to change PIDs in iNav. 

Lua scripts are not topics for this iNav repo, I think.
