### ISSUE TITLE
Holybro Kakute F7 V1.5 - Request for official target

### ISSUE THREAD

**Issue by MaxLansing** [iNavFlight/inav#5304]
## Current Behavior

Only works with 2.3.0 RC with (for me unknown) fix from Pawel

## Desired Behavior

Make it an official target, please.
We got more of this boards around would like to fly them with iNAV

## Suggested Solution

If possible make it an official target. please.
I would like to at least provide testing as far as i am capable to.

## Who does this impact? Who is this for?

Everyone using Holybro F7 V1.5 boards (mini, AiO, std.)

## Additional context

Whatever Pawel did to make it happen for me (thx again), it works well with all features as far as i tested (GPS, Waypoint Missions etc..) the only thing not working atm is LED support.

Pawels touchup:
https://github.com/iNavFlight/inav/issues/5203#issuecomment-553060706

Current Setup, Prototype 5-6" Quad running on 3S:
Holybro Kakute F7 V1.5
Tekko F3 BLHeli32 ESC
AtlAtl V2 VTX
BN880
FrSky SBUS receiver w/telemetry

**Comment by DzikuVx** [comment]
There is no need for separate target. Just flash INAV 2.3 KakuteF7 target and done. 
Separate target is needed only for HDV variant
