### ISSUE TITLE
F3 targets still supported?

### ISSUE THREAD

**Issue by Riffer** [iNavFlight/inav#5306]
Release 2.1 announced the removal of F3 targets, but they are still there. Did you remove features to keep the size small enough? I am asking, because I have an older wing on my table, that had 2.0.0. running and is now on 2.3.0.

**Comment by digitalentity** [comment]
We will follow the same approach as with F1 targets. 

We'll keep F3 targets around as long as we can without disabling support for things required for navigation. We might disable support for less important features (DShot; less common control protocols like SUMH; not common telemetry - MAVLink, HOTT etc; NMEA GPS; logging etc). 

A point of no return would be passed once we'll have to limit more important features like reduce number of waypoints, support for common protocols - IBUS, CRSF etc. We're not yet there, but we're getting close.
