### ISSUE TITLE
Implement boot logging facility

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#531]
I think we need a way to troubleshoot boot process. How about dedicate some RAM to record an event log from powering up to entering main loop?
Log should be plain binary and contain the following:
- Timestamp (ms since boot) [uint32_t]
- Event code [uint16_t]
- Event parameters (dependent on event code) [uint16_t]x4 ?

Each record will be about 14 bytes, I think we can easily dedicate 1KB to store boot events.
The log itself will be displayed in human readable form by a `bootlog` CLI command.

Log should include successful sensor detections, successful/failed sensor initialisation, PWM channel allocation etc.

Having such a log will help us troubleshoot and profile boot process.

Thoughts?

**Comment by martinbudden** [comment]
Yes, this is a good idea. Might as well make the record 16 bytes: the extra memory is insignificant and it will make hex dumps much easier to read.

**Comment by digitalentity** [comment]
Hm... Actually we might want to make a boot log being dumped into blackbox for easier analysis. 
However, let's implement it first.

**Comment by digitalentity** [comment]
This is how bootlog looks. PR to follow
![image](https://cloud.githubusercontent.com/assets/11059099/18083938/afabf8e4-6ee8-11e6-8e43-1abc1f33ded4.png)

**Comment by xdigyx** [comment]
NAZE32 rev5 does not recognize the command

**Comment by stronnag** [comment]
Nor does any other flight controller not build from the correct branch.

```
# bootlog
Time Evt Parameters
   0:  0 
   0:  1 
 500: 18  (0, 0, 0, 0)
 500: 18  (1, 1, 0, 2)
 500: 18  (2, 2, 0, 2)
 500: 18  (3, 3, 0, 2)
 500: 18  (4, 4, 0, 2)
 500: 18  (5, 5, 0, 2)
 500: 18  (6, 6, 0, 2)
 500: 17  (7, 6, 0, 1)
 500: 17  (8, 6, 0, 1)
 500: 17  (9, 6, 0, 1)
 500: 17  (10, 6, 0, 1)
 500:  2 
 636:  9  (2, 0, 0, 0)
 752: 10  (3, 0, 0, 0)
 767: 11  (3, 0, 0, 0)
 767: 12  (2, 0, 0, 0)
2025: 13  (0, 0, 0, 0)
2025:  4 
2526:  8 

# version
# INAV/NAZE 1.2.0 Aug 31 2016 / 20:14:44 (d963186)
```

Are you Timecop in disguise?

**Comment by xdigyx** [comment]
lol, no!

I used FW1.2 RC4 for Naze. If this one is not correct then...

**Comment by stronnag** [comment]
you need the boot-logging branch

**Comment by xdigyx** [comment]
oh.. ok, I thought it's already in 1.2 RC4 which is available on Chrome -> inav cfg tool
