### ISSUE TITLE
Which target for Mamba F722?

### ISSUE THREAD

**Issue by hsucalvin** [iNavFlight/inav#5310]
Hi, I see mamba f722 stack is listed in recommended hardwares on this page(https://github.com/iNavFlight/inav-configurator/releases), but cannot find the target in the firmware list.
There's only one for Mamba F405.

So which target firmware should I choose for mamba f722?

**Comment by Jetrell** [comment]
@hsucalvin It isn't available in 2.3. It will be in 2.4.   #5231

**Comment by hsucalvin** [comment]
> @hsucalvin It isn't available in 2.3. It will be in 2.4. #5231

I see. thanks
