### ISSUE TITLE
Is any utility like Pidtoolbox available for iNav?

### ISSUE THREAD

**Issue by Improg** [iNavFlight/inav#5316]
I need to view response charts for my quad. Pid Analyzer don't work with iNav 2.3.0, flying iNav 2.1.0 some strange errors occurs, so I can't set up pids for old version instrumentally and then change to new one. Pidtoolbox don't work with 2.3.0 too as with 2.1.0 don't work. How can I get response charts (roll, pitch, yaw) for the latest iNav 2.3.0?
If no exists, is there an ability to convert blackbox from 2.3.0 format down to 2.1.0 to use Pid Analyzer? Or, convert to betaflight format for Pidtoolbox?

**Comment by DzikuVx** [comment]
https://github.com/Plasmatree/PID-Analyzer works

**Comment by Improg** [comment]
Don't work with 2.3.0 log.

**Comment by DzikuVx** [comment]
Tested last week and worked nicely

**Comment by Improg** [comment]
> Tested last week and worked nicely

Found, that blackbox_decode doesn't work, and thus Pid Analyzer, based on it. Don't know, why.

**Comment by DzikuVx** [comment]
Try this version: https://github.com/iNavFlight/blackbox-tools/releases

**Comment by Improg** [comment]
Checked - I used 0.4.3 version. Now it works with 0.4.4. Thanks!
