### ISSUE TITLE
Major Issue - Matek F411 Wing with Matek F411 RSSI Board Target

### ISSUE THREAD

**Issue by Zangetsu57** [iNavFlight/inav#5321]
Hello,

First off, this is the first time I've used the Matek F411 wing, but I've used the Matek F405 Wing in several builds.  With iNav 2.3, it appears that when the Matek F411 RSSI target is selected, the board often doesn't boot properly when powered on.  It seems to boot only around 1 out of 10 times.  This is evident as a camera video feed is visible, but the OSD never appears.  Additionally, servo input does not work.

I tried the Matek F411 target with iNav 2.3, and it boots on a more consistent basis, but failures do occur.  

I scaled back to iNav 2.2.1 with the Matek F411 RSSI target.  It works more consistently than iNav 2.3, but boot failures still occur.

I tried the iNav 2.2.1 MatekF411 (stock) target and I had 30/30 consistent boots.  I then tried iNav 2.3 with the MatekF411 (stock) target, and had boot problems.  This leads me to believe it isn't a hardware issue.

It's possible that I have a defective board, but don't have another one to try.

**Comment by giacomo892** [comment]
What are the LEDs on the board showing when it is not booting? Do they have a pattern?
https://github.com/iNavFlight/inav/wiki/Blinkenlights

**Comment by Zangetsu57** [comment]
Thanks for the reply.  They do blink, but I don't recall the pattern.  I'll check tomorrow and report back.  I used iNav 2.2.1 some more since the original post and it seems fine with the default Matek F411 target, but the RSSI version has issues (which is unfortunate, because Rlink only supplies analog RSSI).

**Comment by Jetrell** [comment]
@Zangetsu57 What you have described sounds like an issue that is still present with the F411-wing firmware.    
Make sure - `osd_video_system = AUTO` 
Do not have it set to- ` PAL` or `NTSC`

**Comment by Zangetsu57** [comment]
Thanks Jetrell, I made the change to AUTO and can confirm that the problem described above is resolved for both iNav 2.2.1 and 2.3!
