### ISSUE TITLE
INAV 2.3

### ISSUE THREAD

**Issue by robohippy** [iNavFlight/inav#5329]
Hi i have a Matek 722SE FC and a SIM800L. Is there a wiring diagram and setup guide so i can isntall it ?

**Comment by giacomo892** [comment]
It's using serial. So 3.3v GND TX RX
Then check:
https://github.com/iNavFlight/inav/blob/master/docs/Telemetry.md

Also kindly don't use github issues tool to ask for help, we have telegram, facebook and forums.
