### ISSUE TITLE
Support pinio/servo for camera shutter release in missions

### ISSUE THREAD

**Issue by whoim2** [iNavFlight/inav#5331]
Need camera shutter release in missions

## Suggested Solution
In mission planning add modes user1/user2 for pinio, with pressed timing, or similar mechanism with servo.
Need stopping on point for this.

**Comment by DzikuVx** [comment]
With INAV 2.5 it is possible with the help of Logic Conditions and Global Variables (programming tab in configurator)

```logic 0 1 -1 19 0 0 0 1 0
logic 1 1 -1 2 5 0 0 50 0
logic 2 1 -1 12 4 1 0 0 0
logic 3 1 -1 2 5 0 0 55 0
logic 4 1 3 18 0 0 0 0 0
logic 5 1 1 18 0 1 0 500 0
logic 6 1 2 18 0 1 0 -500 0
logic 7 0 5 0 0 0 0 0 0
logic 8 0 -1 0 0 0 0 0 0
logic 9 0 -1 0 0 0 0 0 0
logic 10 0 -1 0 0 0 0 0 0
logic 11 0 -1 0 0 0 0 0 0
logic 12 0 -1 0 0 0 0 0 0
logic 13 0 -1 0 0 0 0 0 0
logic 14 0 -1 0 0 0 0 0 0
logic 15 0 -1 0 0 0 0 0 0
```

The snippet above assigns servo position to GVAR1: sets 500 every 5s for a 0.5s
Then, using mixer, GVAR1 can be assigned to any servo you wish and thus provide a configurable trigger
