### ISSUE TITLE
Driver for OPTICAL FLOW & LIDAR SENSOR 3901-L0X

### ISSUE THREAD

**Issue by NitinJSanket** [iNavFlight/inav#5337]
Hi,
Thanks for your wonderful work.
I was going through the Matek systems products page and found this: http://www.mateksys.com/?portfolio=3901-l0x#tab-id-1 and I'm very interested in supporting this with ArduPilot. I contacted Matek systems requesting the source code of the driver and they routed me to the iNAV group.

Is there a way I can get the source code for the driver of this sensor? 

Thanks,
Nitin

**Comment by digitalentity** [comment]
The source code for all of the drivers for supported hardware is in this source tree and available under GPLv3.
