### ISSUE TITLE
Obstacle avoidance with Inav, when?!

### ISSUE THREAD

**Issue by Multinnov** [iNavFlight/inav#5343]
Hi,

My question is very simple, do you know when Inav will implement, obstacle avoidance option?

Thank you

regards

**Comment by giacomo892** [comment]
This is not the place for such questions. Ask in the community chat / group. Thanks

**Comment by Multinnov** [comment]
Hi, ok, where is the chat link ?

 

Thanks

 

 

Regards

 

 

 

De : giacomo892 <notifications@github.com> 
Envoyé : jeudi 23 janvier 2020 12:25
À : iNavFlight/inav <inav@noreply.github.com>
Cc : multinnov <multinnov@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [iNavFlight/inav] Obstacle avoidance with Inav, when?! (#5343)

 

This is not the place for such questions. Ask in the community chat / group. Thanks

**Comment by Multinnov** [comment]
Hello,

 

I would like to know where can I find the class diagram of INAV ?

 

Thank you

 

 

Regards

Maxime BIGNARD

07 70 10 55 28

 <http://www.multinnov.com/> www.multinnov.com

 <https://www.linkedin.com/company/19113690/admin/> Linkedin



 

 

 

De : giacomo892 <notifications@github.com> 
Envoyé : jeudi 23 janvier 2020 12:25
À : iNavFlight/inav <inav@noreply.github.com>
Cc : multinnov <multinnov@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [iNavFlight/inav] Obstacle avoidance with Inav, when?! (#5343)

 

This is not the place for such questions. Ask in the community chat / group. Thanks
