### ISSUE TITLE
DISABLE NAVIGATION FIRST

### ISSUE THREAD

**Issue by Sufy561** [iNavFlight/inav#5345]
hello , I am contacting you because I am having an issue with the inav plane that I've recently built: with everything as it should be , I used to be able to arm and fly . 1 week ago my F765 decided not to arm , it had 12 satellites , and everything was as it used to be , I hadn't changed a single thing since I last flew it , but a message popped up on the osd which said: DISABLE NAVIGATION FIRST - UNABLE TO ARM . I have no idea on what could be going on .
This issue popped out of nowhere , and I had never seen it before . Now I can't fly anymore . 
Thank you 
Sufyan

**Comment by giacomo892** [comment]
https://lmgtfy.com/?q=cannot+arm+inav

**Comment by alhimik1986** [comment]
It means that you cannot to arm using NAV_POSHOLD mode. You must switch off it first, then arming, take off and then switch on the NAV_POSHOLD mode.

**Comment by frangarma** [comment]
> It means that you cannot to arm using NAV_POSHOLD mode. You must switch off it first, then arming, take off and then switch on the NAV_POSHOLD mode.

Hi, by the way, I had the same problem taht Sufy561, and following your advice _"You must switch off it first, then arming, take off and then switch on the NAV_POSHOLD mode." I can see in OSD that pass from ANGL mode to AIR mode, I mean, I switching in ARM mode, if I up the throttle unitil 1400 (more or less that is empiric) and I switching the switch mode to NAV POSHOLD, I can see into OSD that pass from ARM to AIR mode (note that all this testing has been made in my desktpo not flying), that is correct? Shouldn't I see the NAV POSHOLD into OSD? 
Thanks for your help

**Comment by gubernatorAtik** [comment]
I had the same problem. This was visible because I left the RHT key active on the remote and I disabled it. . All is good now

**Comment by LAFlyer** [comment]
I have this same problem.  
is RHT key return to home?
My Arm and Return To Home are opposite positions of same switch.
Up is Arm. Mid is Disarm and Down is RTH.  All show correct in Modes page of Configurator.

**Comment by MrD-RC** [comment]
> I have this same problem.
> is RHT key return to home?
> My Arm and Return To Home are opposite positions of same switch.
> Up is Arm. Mid is Disarm and Down is RTH. All show correct in Modes page of Configurator.

That is a bad switch setup. Have arm on its own 2 way switch. The model still needs to be armed for RTH to work. 

This is not an issue. This is working as intended.

**Comment by LAFlyer** [comment]
Thanks Pawel, but I discovered while I was getting the "Disable Navigation First" warning that RTH activates motor arming.  I had not saved the mode setup when I was testing.  I borrowed the switch setup from Painless360.  Thanks Lee. 
All is well now.

**Comment by Szczery-FPV** [comment]
The only solution that comes to my mind is...
If you use the RC ELRS link, change the speed in "Hz" to a lower one, i.e. from 250Hz down, otherwise you only have 8 channels.
You can use speeds from 50 to 250Hz.
