### ISSUE TITLE
DJI FPV OSD Not working on INAV 2.4.0-RC1 / Matek F722-STD

### ISSUE THREAD

**Issue by CrazyFlutter** [iNavFlight/inav#5364]
DJI FPV OSD Not working.
I have:
Turn ON MSP on correct uart (4 in my case)
Turn ON OSD and Telemetry,
Downloaded fonts
Put some components on the OSD (the ones working on BF) etc...
Wasn't able to get any OSD in the googles? (latest DJI firmware in both air unit and googles).
The air unit detects the arming normally.

To make sure all is wired and working correctly I loaded BF and did the same as above and got directly the OSD working.

Board:  Matek F722-STD
# version
# INAV/MATEKF722 2.4.0 Jan 22 2020 / 23:48:12 (4a8707e68)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by giacomo892** [comment]
you don't need to enable MSP, but DJI in peripherals
