### ISSUE TITLE
Where is the CRSF telemetry option

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#5365]
I am using Configurator 2.4.0 RC2 with an F411 Wing FC.

I would like to connect this this board to my Crossfire Nano RX over Crossfire.

However, when I try to choose a Telemety protocol for any of the UARTs, CRSF is not an option.

The only available options are :

    (Disabled)
    FrSky
    HoTT
    SmartPort
    LTM
    MAVLink
    IBus
    GSM SMS

What am I missing ?

Thanks.

**Comment by UltraWhiteAngel** [comment]
Did you tried using the MAVLink option, as Crossfire is capable of that.
