### ISSUE TITLE
VTX settings are not written to VTX when using a power switch

### ISSUE THREAD

**Issue by jj-uk** [iNavFlight/inav#5372]
iNav 2.3.0 (https://github.com/iNavFlight/inav/releases/download/2.3.0/inav_2.3.0_MATEKF722SE.hex)

Matek F722-SE Wing with "vsw" power switching via "USER 1" modes. (http://www.mateksys.com/?portfolio=f722-wing#tab-id-4)

Matek VTX-HV (http://www.mateksys.com/?portfolio=vtx-hv#tab-id-5)

I have my VTX on a power switch (USER 1) so that the VTX is not powered when the flight controller boots.

## Current Behavior

It appears the iNav writes the VTX freq, power and channel information to the VTX when the flight controller boots, and not ever again.
As a result, the VTX settings are never written to the VTX. This is my observation.

## Steps to Reproduce
Power the VTX via the vsw pin on th flight controller.
Set up user 1 so that the vtx is not powered up when the flight controller boots.

## Expected behavior
The vtx settings are written to the vtx when the vtx is powered on.

## Suggested solution(s)
A solution would be:

USER 1 not configured:
Write the VTX settings after flight controller boot.

USER 1 configured:
When USER 1 changes from ACTIVE to NON-ACTIVE (e.g. changes from blue to grey in the configurator modes), wait 2-3 secs for the vtx to power up then write settings to the vtx.

or maybe write the vtx settings each time the FC is armed. This would assume that the vtx is powered up at the time of arming. Writing periodically when armed would be a bad idea in case the vtx received invalid data and changed channel whilst flying etc.

**Comment by b14ckyy** [comment]
As a workaround you could use the "Low power on Disarm" Feature in configuration tab and set t to FIRST_ARM or ALWAYS. In this case the the Smart Audio Control Package is sent to the VTX again when you arm the plane to set the power level to the desired one. 

Why not using this feature in general? This will keep the VTX at a low 25mW power level when disarmed and waiting for GPS and power up to your desired power level on arm?

**Comment by jj-uk** [comment]
This remains an issue.
