### ISSUE TITLE
INAV 2.4RC2 RPM OSD bug - 42k

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#5374]
OSD RPM element displays 42k right after crossing 8k display.
Verified on 3 UAVs. Seems like its only OSD formatting since ERPM data is received correctly from the ESCs

https://youtu.be/JLsJgBLyRm8

![image](https://user-images.githubusercontent.com/966811/73609949-d196ef80-45d2-11ea-8d6b-d3d717b7fcf0.png)

[LOG00003.TXT](https://github.com/iNavFlight/inav/files/4144339/LOG00003.TXT)

**Comment by digitalentity** [comment]
`DEBUG_ERPM` values are set right after decoding in `escSensorDecodeFrame`, while OSD consumes averaged data via `escSensorGetData`. Averaging is using `escSensorData_t` as accumulator, but we have `int16_t` for rpm value.

8k * 4 motors = 32k. beyond that `int16_t` overflows and goes negative which messes up the OSD code.

Fix pending
