### ISSUE TITLE
Bump the GCC version to latest stable

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#5382]
Per report by @hydra:

```
so just trying to compile iNAV, and I'm getting linker errors when using GCC 8.2.x
root cause is this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88422
```

Upping the version to at least 8.3.1 fixes the linking errors.

**Comment by hydra** [comment]
9.2.1 is currently latest stable release.

Version 9-2019-q4-major

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
