### ISSUE TITLE
Matek F405-CTR + Quad + Servo S6

### ISSUE THREAD

**Issue by DangerD256** [iNavFlight/inav#5397]
Trying to make at least one working servo for camera Tilt.

![image](https://user-images.githubusercontent.com/17032489/74132533-7460f680-4bef-11ea-9dd8-abf4b55c63b9.png)

The problem is that there's no PWM signal on S6, tested also with PWM tester.
With arducopter firmware both S5 S6 works fine for gimbal

**Comment by DzikuVx** [comment]
INAV on this board allows only to use one servo on S6 in multirotor configuration and only when target MATEKF405_SERVOS6 is used. You are trying to assign two servos. S5 is reserved to LED strips

**Comment by DangerD1024** [comment]
> INAV on this board allows only to use one servo on S6 in multirotor configuration and only when target MATEKF405_SERVOS6 is used. You are trying to assign two servos. S5 is reserved to LED strips

What? I'm using only S6 and it doesn't output PWM.
