### ISSUE TITLE
What happens when a prop fails?

### ISSUE THREAD

**Issue by abusr** [iNavFlight/inav#5403]
I'm surprised not to find something relevant. Maybe I wasn't lucky searching. I was trying to find the behavior of a quad with inav when a prop/motor fails. Does inav cover this case?

**Comment by giacomo892** [comment]
Drone will spin out of control and crash

**Comment by abusr** [comment]
Provided sufficient thrust from the remaining engines why isn't it possible for the quad to land, even in a spinning condition? This could help limiting the total damage a bit, or not?

**Comment by giacomo892** [comment]
It would be possible using advanced algorithm to land when spinning.

**Comment by rsilk1949** [comment]
Build a hex copter ;)

**Comment by DzikuVx** [comment]
Quadcopters need 4 motors and propellers to be working to maintain stability. This is the "hardware limitation" that can not be fixed by any software. 4 actuators are required to balance roll pitch yaw and thrust
