### ISSUE TITLE
FlySky I-Bus receiver not working

### ISSUE THREAD

**Issue by raoul596** [iNavFlight/inav#541]
Is it possible to connect a receiver via Ibus and a GPS at the same time to a Flip32?

**Comment by digitalentity** [comment]
Yes, it's possible. GPS to SoftSerial and IBUS to UART2.
Please also consider using RCG thread or Gitter chat for support.

**Comment by raoul596** [comment]
I have found a problem by connecting Ibus to my flip32. All the channels are "glitching" I also tried it with Cleanflight, but there it works perfectly fine. What am I doing wrong or is it a software problem?

**Comment by digitalentity** [comment]
I don't have a FlySky TX anymore. 
Can somebody confirm the bug with iBus?

**Comment by bk79** [comment]
Serialrx works good on spf3vdeluxe

Il 01/set/2016 11:14, "Konstantin Sharlaimov" notifications@github.com ha
scritto:

**Comment by raoul596** [comment]
Here a screenshot. My sticks are in the center position.

![inav v1 1 ibus glitch](https://cloud.githubusercontent.com/assets/19370512/18162272/ec183132-7035-11e6-85ad-7abf3fd8fdc1.png)

**Comment by digitalentity** [comment]
Not SerialRX in general. I can confirm that S.Bus is working good as well. It's the IBUS receiver I'm concerned about.

**Comment by raoul596** [comment]
Its a FS-IA10b with the flysky FS-I6S transmitter

**Comment by nibborg** [comment]
At this moment the  FS-IA10b on my 250 quad with SPRACINGF3 + 1.2-RC5 its working ok. No issues with the Rx using iBus.

**Comment by raoul596** [comment]
The problem is solved in Inav V1.2, thanks!

**Comment by DzikuVx** [comment]
Great to hear it's working. Closing
