### ISSUE TITLE
add option to map yaw to mode change for flying wings

### ISSUE THREAD

**Issue by uotw** [iNavFlight/inav#5410]
## Current Behavior

- when a flying wing is selected, the yaw receiver channel is not used to control flight
- there is currently no way to control mode selection using the the yaw channel

## Desired Behavior
- in the pulldown menu for the modes, yaw should be an option

## Suggested Solution
- map the yaw channel to an aux index

## Who does this impact? Who is this for?
- this is for flying wing users who only have a 4-6 channel radio and would like to have more control over flying modes. 
- For instance, I could use my Spektrum DX6 in the following way: set yaw travel to 0, then set a 3 position switch in the mixer to mod the yaw output.

I can't think of a reason you'd want to map any other receiver outputs to flight modes

**Comment by DzikuVx** [comment]
YAW RX input has various uses in INAV like OSD selection, stick commands and so on. It was discussed before a few times and it will not be changed as is affects very little users and requires a major changes in the code
