### ISSUE TITLE
Development in Eclipse

### ISSUE THREAD

**Issue by vegasergio2851** [iNavFlight/inav#5413]
Hi everyone,

I am working on a project in which I want to program a flight controller with iNav code. My goal is to use eclipse to add some code to iNav and flash it to the controller.  I have a Luminier LUX F7 Ultimate Flight Controller. I am trying to set up eclipse IDE with the instructions in the inav/docs/development folder but I am unsuccessful in building the project. I am stuck in configuring the debugging configurations. Any help or tips would be greatly appreciated!

Thank you!
I can provide screenshots of my setting or any additional information that is needed

**Comment by DzikuVx** [comment]
Eclipse is deprecated. We suggest to use Visual Studio Code
For debugging, please refer to https://github.com/iNavFlight/inav/blob/master/docs/development/Hardware%20Debugging.md

**Comment by vegasergio2851** [comment]
Thank you!
