### ISSUE TITLE
Add AltHold mode with just sonar detected for <2m

### ISSUE THREAD

**Issue by btandrei** [iNavFlight/inav#5415]
## Current Behavior

You cannot use Sonar/Lidar driven AltHold mode without also having a Baro attached, AltHold mode is not visible with just Sonar attached. AltHold mode is necessary in order to use Surface mode with an optical flow sensor.

## Desired Behavior

AltHold mode is available with just Sonar/Lidar attached for under 2m height.

## Suggested Solution

Make AltHold mode available with just Sonar/Lidar attached for under 2m height, and disable AltHold mode for more than 2m height and just use Angle mode.

## Who does this impact? Who is this for?

This would be very useful for most small quads 1-5inch which don't have a Baro but you can easily attach an Matek OpticalFlow & Lidar sensor and get Position/Surface and Altitude hold active <2m, or in case of a emergency, or if you'll flying very low on path in the woods, etc.

**Comment by digitalentity** [comment]
Barometer is required to cover gaps in sonar.

Imagine a scenario when sonar looses signal. Without barometer to keep the altitude it's impossible to select a safe throttle and avoid uncontrolled and unexpected behavior.
