### ISSUE TITLE
Change S2 pad signal mmix to smix Matek F411-WING

### ISSUE THREAD

**Issue by OpticHeave** [iNavFlight/inav#5418]
## Current Behavior
Matek F411-WING S2 pad can only be used as Motor 2 output in the mixer tab

## Desired Behavior
Be able to servo output from S2 to S7 pad

## Suggested Solution
Change S2 pad output from motor (mmix) to servo (smix)

## Who does this impact? Who is this for?
It will allow Matek F411-WING users flying on a single motor to use 4 surface servos and additionally a 2-axis gimbal.

## Additional context
I use my Matek F411-WING on a Talon GT Rebel (V-Tail) and want to add a 2-axis gimbal using S2 for gimbal pan and S7 for gimbal tilt

![image](https://user-images.githubusercontent.com/61162817/74681773-87159580-51c4-11ea-9d3f-c42a3dca5121.png)

**Comment by DzikuVx** [comment]
Sorry mate, but this is not possible. S1 and S2 share the same Timer and as such have to be assigned to the same role. Hardware limitation
