### ISSUE TITLE
ver 2.4  matek  f722 standard osd problem

### ISSUE THREAD

**Issue by stevereed66** [iNavFlight/inav#5428]
## Current Behaviour 1.4 stable
1. osd  vertical speed  graphic ie  ^V  does not display on osd all fonts tried,  numeric works fine
2. osd menu pid tuning  alt i  is 0 and does not see value  nav_auto_climb_rate

## Steps to Reproduce

1. look at osd
2.
3.
4.

## Additional context

---

2.4 latest stable

- FC Board name and vendor:
 matek  f722 standard

**Comment by Jetrell** [comment]
Are you saying that your still using iNav 1.4 firmware?

Firmware and Configurator software should be used together. 

When functions are added between releases, it also means the fonts are upgraded to suit.
This may cause certain font characters to be positioned in the wrong location on the OSD. As it would be if you're using 2.4 fonts on old 1.4 firmware.
