### ISSUE TITLE
Motor output S5 does not work on Matek F722SE 

### ISSUE THREAD

**Issue by Base-0ne** [iNavFlight/inav#5432]
Hi,
I'm using an Matek F722SE Flight controller with Inav 2.4 for an Hexacopter build. (Hexa-X)
With this setup Motor 5 will not work. i switched motor 5 and 6 on the FC and then Motor 6 wouldn''t move. 
I tested this on 2 FC''s (Brand new MatekF722SE) both has the same problem.
When installing Betaflight on the FC all motors work.

Is there an fix for this problem?
Or do i have to experiment with older Inav versions?

I hoped to remap the motor 5 to S7 but thats not posible in Inav 
(i did not have to do this in Betaflight)

[Dump 19-02 Hexacopter F722SE.txt](https://github.com/iNavFlight/inav/files/4231706/Dump.19-02.Hexacopter.F722SE.txt)

[INAV_cli_20200220_164643_Resource_MatekF722SE.txt](https://github.com/iNavFlight/inav/files/4231725/INAV_cli_20200220_164643_Resource_MatekF722SE.txt)

**Comment by JeanFPV** [comment]
http://www.mateksys.com/?p=5159#tab-id-7
INAV Target Tips
S5 doesn’t work for Hex/Octo motor due to normal DMA confliction if Dshot is selected
Use multishot for Hex/Octo copter
BF uses burst DMA, no confliction between S1 ~S8 Dshot

**Comment by FabianSchwartau** [comment]
Don't know exactly, but does https://github.com/iNavFlight/inav/commit/60c13ef71bc07aeb7354127aeada8bf49c61d82f fix that?

**Comment by DzikuVx** [comment]
For hexa in INAV you can not use DSHOT on this board. Use Multishot instead

**Comment by Base-0ne** [comment]
Thank you very much! I will put it on Multishot.

**Comment by Sebbb** [comment]
Can somebody explain me what the background is? I don't understand what "normal DMA confliction" means. Am I able to get S5 working with DSHOT if I compile the firmware myself and e.g. assign a different timer? Or to use a different pin than S5 to get 6 DSHOT outputs?
