### ISSUE TITLE
Inav wont load in chrome.

### ISSUE THREAD

**Issue by Ziov** [iNavFlight/inav#5445]
I'm unable to get inav working through chrome and Edge, loading the extension gives text but nothing else 'see attachment' 

I've uninstalled and reinstalled, restarted pc and installed drivers but nothing. 

Any idea's? 
![DSC_0132](https://user-images.githubusercontent.com/61436485/75194423-fef93800-574f-11ea-8c5f-36dc41cac246.JPG)

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav-configurator#building-and-running-inav-configurator-locally-for-development-or-linux-users

Running inside Chrome is obesolete and not fully supported. Use `npm start` instead or just use compiled release https://github.com/iNavFlight/inav-configurator/releases
