### ISSUE TITLE
Implement runtime waypoint attributes

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#5451]
In order to improve #5439 and fix a side effect of this implementation, aka incorrect jumps saved to EEPROM in the case the user triggers a save after the mission has been ran.

Once @digitalentity addressed this, I can introduce the fixes needed to JUMP WP type.

**Comment by stronnag** [comment]
Then we can decide whether inner jumps repeat from the beginning ...

**Comment by danarrib** [comment]
There is some documentation on how to test this new WP JUMP feature? What exactly it does?

**Comment by stronnag** [comment]
https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages
https://www.rcgroups.com/forums/showpost.php?p=43907283&postcount=481
