### ISSUE TITLE
Tramp protocol, new VTX handling, "Low power until armed" power level handling

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#5471]
## Steps to Reproduce
1. Latest development with #5461 
1. Matek HV-VTX
1. Tramp protocol configured
1. "Low power until armed" to anything besided "Disarmed"
1. Arm

## Current behavior
* VTX selects correct power level
* Power level LED keeps blinking
* VTX reboots when saving new configuration every 15 seconds forever

## Expected behavior
* VTX selects power level
* VTX reboots only once

**Comment by digitalentity** [comment]
Weird. I don't have a HV-VTX, but I checked on another Tramp-compatible VTX and power level is sent to the VTX just once, as expected, no repeating every 15 seconds.

 #5461 changed the VTX polling schedule a bit, this could have triggered some edge case. I guess it's time to get that VTX.

**Comment by digitalentity** [comment]
Actually, Tramp protocol itself is a mess. I should consider refactoring it.

**Comment by digitalentity** [comment]
@DzikuVx can you please test https://github.com/iNavFlight/inav/pull/5575?

**Comment by DzikuVx** [comment]
seems to be fixed by #5575
