### ISSUE TITLE
3CH configuration for Angle mode

### ISSUE THREAD

**Issue by GhostMaster9** [iNavFlight/inav#5484]
Hi, just want to make sure im making the correct configuration for a airplane with only yaw and pitch.

https://i.imgur.com/45mfQJy.jpg

im using inav 2.4.0, and ive tryed before with stabilized roll using yaw and ive had very bad results.

Thank you very much.

**Comment by DzikuVx** [comment]
yes, this is the correct mixer but currently NAV modes will not work since airplane NAV navigates using roll only. It will change in INAV 2.5
