### ISSUE TITLE
Weird Horizontal Drifting with Mag active

### ISSUE THREAD

**Issue by fuleinist** [iNavFlight/inav#5488]
## Current Behavior
My F4 FC is having a weird horizontal drifting only with Magnetometer as per below:
Mag Disabled(Normal): https://share.getcloudapp.com/DOu8qbNL
Mag Enabled(Abnormal): https://share.getcloudapp.com/4gumndk9
Could this cause by a faulty Magnetometer?

## FC Board name and vendor:
 INAV 2.4.1
 INAV/FF_F35_LIGHTNING 2.4.0 Feb 11 2020 / 21:31:47 (bcd4caef9)
 GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by giacomo892** [comment]
It is caused by bad mag allignment.
