### ISSUE TITLE
bidirectional dshot

### ISSUE THREAD

**Issue by MastroDado** [iNavFlight/inav#5498]
It's possible to implement bidirectional dshot like betaflight? It is the last thing is missing to me before making the switch, please please please.
I would like to use inav on all of my crafts.

**Comment by giacomo892** [comment]
Quick how to fill a feature request:

![Schermata 2020-03-11 alle 14 53 19](https://user-images.githubusercontent.com/20860004/76424279-4f0b0800-63a8-11ea-88e1-5955a509c546.png)

![Schermata 2020-03-11 alle 14 54 14](https://user-images.githubusercontent.com/20860004/76424283-5205f880-63a8-11ea-8a81-968f7d4eee0a.png)

Closing as invalid
