### ISSUE TITLE
Autolaunch throttle voltage based settings

### ISSUE THREAD

**Issue by brassman84** [iNavFlight/inav#5510]
## Current Behavior
The autolaunch throttle setting is universal and has to be changed depending on what cell count you are using. A launch throttle calibrated for 6s will crash the plane if you use a 4s.
I like to fly fast with a small 6s pack but sometimes I want to have longer flight times and go with a higher mah 4s pack.

## Desired Behavior
The possibility to set different launch throttle values for 2s, 3s,4s,5s and 6s(mabey even higher). Not automatic values scaled by voltage but  four actual launch throttle settings manually calibrated for each cell count and used depending on the readings from the automatic cell detection feature already in place

## Suggested Solution
Always active, default value should be the same for all cell counts to not cause any problems for people who have issues with the automatic cell count detection

## Who does this impact? Who is this for?
Airplanes only, anyone who uses autolaunch and want to run different cell counts in one plane.

**Comment by peteoz** [comment]
if this is considered then it would also make sense to allow variable cruise throttle for navigation modes based on number of cells we are running.

for example on my Nano Goblin I run 2S, 3S, 4S & 5S batteries, every time I change between different battery type I need to go to iNav settings and modify  "nav_fw_launch_thr" as well as "nav_fw_cruise_thr" values.

that means dragging along laptop every time I go fly.

**Comment by brassman84** [comment]
Thats a great idea Peteoz👍I too have the same issue with using cruise mode

**Comment by brassman84** [comment]
Also just to clearify the reason why you dont want a automatic scaling for this stuff, when switching from 4s to 6s you most likely have to switch to a different propeller too

**Comment by swissfreek** [comment]
Not necessarily. Would be nice to have an automatic switcher like Betaflight does so you can fly with either pack and not have to change a bunch of settings.

**Comment by peteoz** [comment]
from 2S to 5S I don't change propeller
