### ISSUE TITLE
Matek F405-CTR + Quad + Servo S6

### ISSUE THREAD

**Issue by DangerD1024** [iNavFlight/inav#5514]
Reopening issue, Servo S6 still doesn't output any PWM, tested with servo tester. Using MATEKF405_SERVOS6 firmware.
![image](https://user-images.githubusercontent.com/4560434/77103375-f8926f00-6a22-11ea-9309-ca935752b340.png)

**Comment by DangerD256** [comment]
A bit weird, Servo S6 is nobody using at all?

**Comment by AlexeyII** [comment]
I would like to understand how to assign a servo to S6. I'm interested!

**Comment by DangerD1024** [comment]
> I would like to understand how to assign a servo to S6. I'm interested!

You need to add it to servo mixer than you can assign rc channel or make automatic stabilization (for servo gimbal)
But unfortunately servo is not working on S6 this board, works fine if you will flash arducopter. (On arducopter you can even use it on S5 so you will have two servos)

**Comment by craigmunday** [comment]
Hi @DangerD1024 , I also have a Matek F405 CTR flight controller and just tested the S6 pad with the MATEKF405 SERVOS6 2.5.1 target.  I can see a valid PWM signal on the oscilloscope for S6.  It seems to be working.

**Comment by DangerD1024** [comment]
> Hi @DangerD1024 , I also have a Matek F405 CTR flight controller and just tested the S6 pad with the MATEKF405 SERVOS6 2.5.1 target. I can see a valid PWM signal on the oscilloscope for S6. It seems to be working.
> 
> Here is the LOW signal
> ![RIGOL Print Screen29-07-2020 11_21_52 PM 717](https://user-images.githubusercontent.com/20749266/88805490-8f054700-d1f2-11ea-9c10-92fd7bde2be0.jpeg)
> 
> Here is the HIGH signal
> ![RIGOL Print Screen29-07-2020 11_24_20 PM 047](https://user-images.githubusercontent.com/20749266/88805605-b5c37d80-d1f2-11ea-8029-12a700d815f6.jpeg)

You have quadcopter in mixer or for plane?

**Comment by craigmunday** [comment]
Here is my mixer configuration for my quadcopter:
<img width="949" alt="S6Issue" src="https://user-images.githubusercontent.com/20749266/88889214-21edc200-d283-11ea-99d7-2456b2c12fd8.png">
