### ISSUE TITLE
Post-flight stats are not displayed in Pixel OSD

### ISSUE THREAD

**Issue by nmaggioni** [iNavFlight/inav#5523]
## Current Behavior

When using FrSky's Pixel OSD, stats are not displayed when disarming: the screen stays empty until the sticks are wiggled or the stats panel times out.

## Steps to Reproduce
1. Install the Pixel OSD.
2. Enable stats.
3. Arm.
4. Disarm.
4. Notice how the screen stays empty for a couple of seconds instead of displaying post-flight stats.

- FC: Matek F405 Wing, FrSky Pixel OSD (non-mini)
- INAV version: v2.4.0 (bcd4cae)

---
@fiam

**Comment by giacomo892** [comment]
Fixed by #5533
