### ISSUE TITLE
request for keep the waypoints instead of getting it from eeprom everytime new fly.

### ISSUE THREAD

**Issue by xixijoe** [iNavFlight/inav#5529]

**Comment by DzikuVx** [comment]
1 - please try to create tickets with title and body, not only with title
2 - waypoints altready can be stored in EEPROM

**Comment by xixijoe** [comment]
1,Okay body and title.
2,Yes, eeprom can be stored. The problem is you need to get it from eeprom everytime new fly.This is not a convenient.

**Comment by stronnag** [comment]
> 2,Yes, eeprom can be stored. The problem is you need to get it from eeprom everytime new fly.This is not a convenient.

Moving one stick to a specific position for c. 1 second is hardly inconvenient.

**Comment by xixijoe** [comment]
yes thank you....

**Comment by xixijoe** [comment]
stick command not funtional when arm switch is assigned. and arm swith is recomanded.......not convenient.

**Comment by stronnag** [comment]
You cannot load WPs when armed: period.
When unarmed, the stick loading works. with arming assigned to a switch.

**Comment by xixijoe** [comment]
I tried. it looks works. I will bring it on the field next time flying. Thank you for your sharing.

**Comment by xixijoe** [comment]
It works, thank you
