### ISSUE TITLE
Matek F411 Wing Mixing

### ISSUE THREAD

**Issue by Donny228** [iNavFlight/inav#5530]
Wing Mixing **HELP**

Currently using INAV 2.4x and setting up mini AR Wing
All flight controls are correct minus when pulling up elevator the right aileron goes down. Currently all mixing is exactly the way the mates web site suggests but I notice there is no gimbal setting on the newer version of INAV

**Comment by DzikuVx** [comment]
https://www.youtube.com/watch?v=lkn9t7WBHNY
