### ISSUE TITLE
When armed, the motor on my fixed wing would not spin up

### ISSUE THREAD

**Issue by Bob15Wet** [iNavFlight/inav#5534]
## Current Behavior
After configuring iNav 2.4.0 on a Matek F722-Wing on a fixed wing aircraft, all functions were working as expected except that when the aircraft was armed, the motor would not run. After several hours of investigation, the problem was that iNav would not run the motor if the throttle channel output from the receiver was less than 880 usec while in the disarmed state.

##Background
I had an unstabilized aircraft to which I added the F722-Wing. Prior to adding the flight controller (FC), i had a throttle cut switch which, when active, changed the transmitter's throttle output to 870usec. When I added the FC, I used the same switch for Arm/Disarm, but did not remove the Throttle Cut setup from the transmitter. When I armed the FC, everythig worked perfectly except that the motor would not run. It did run when manually activated on the iNav Output Tab

## Steps to Reproduce
1. Set the transmitter output to 1000 to 2000 usec on the Throttle channel.
2. Assign Throttle Control to a switch on the transmitter. Adjust Throttle Control settings so that the transmitter output is 870usec when Throttle Control is active.
3. Assign the Throttle Control switch to a transmitter RF channel. Configure iNAV to use that channel for arming, with the Disarm state being the same as Throttle Cut ON.
4. Boot up the system in the Disarmed state. Switch from Disarm (Throttle Control ON) to Arm (Throttle Control OFF). All will work, except motor will not run.

## Suggested solution(s)
Change the code, OR warn Users NOT TO USE THROTTLE CONTROL

---

# version
# INAV/MATEKF722SE 2.4.0 Feb 11 2020 / 22:53:38 (bcd4caef9)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

- FC Board name and vendor:
Matek F722-Wing

**Comment by DzikuVx** [comment]
This is correct behavior.  880 is the lowest pulse length that is considered as valid. I suggest to modify your OpenTX script to never outpuit less than 880.
