### ISSUE TITLE
OMNIBUS GPS not working

### ISSUE THREAD

**Issue by Jonas18175** [iNavFlight/inav#5537]
I'm not sure if its a bug.

I try to configure my Omnibus F4 Flight Controller  (LED STRIP) with INAV.
While configuring i notice that the GPS is Red. I configured the right serial port with the right baudrate and setup in configuration the gps with UBLOX Protocol. Previously i had flashed Betaflight on this Controller, i setup the GPS and it worked, but in INAV not. I have no idea what can i do, have i missed something? It is a bug? Exist a GPS Debug?

**Comment by DzikuVx** [comment]
Check if both lines TX and RX are correctly wired and you are using a correct UART. Also, remember that UART3 is shared with I2C
