### ISSUE TITLE
Feature request: Fixed-wing servo trim function.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#555]
New flight mode which is called "Airplane trim toogle".
- Requirres passtrough mode enabled.
- Requirres throttle to be below min_throttle

When it toggles on then off:
- Set current servo output as new servo center.
- Give user feedback with twitching ailerons and / or beeper / LED.

Procedure to use this:
1. Trim the airplane in air when flying in passtrough mode using your TX.
2. Land the airplane.
3. Toggle the "Airplane trim toogle" while still "passtrough" is active and sticks are centered.
4. Reset your trim to zero on your TX

**Comment by oleost** [comment]
Todays solution is either to trim in passtrough mode, and then land and try to replicate current servo position when hooking up to and computer. Or using the method explained here http://www.rcgroups.com/forums/showpost.php?p=35059861&postcount=6741

**Comment by oleost** [comment]
Original request http://www.rcgroups.com/forums/showpost.php?p=35636569&postcount=7921

**Comment by robert-b** [comment]
the procedure sucks.
level the plane: https://www.eflight.ch/pi/Schwerpunktwaage-MPX693054.html
get the offsets - save them - done.

implementation tooks 20 minutes ...

**Comment by digitalentity** [comment]
@oleost sounds like a good idea to me.
@robert-b level plane doesn't mean level flight.

**Comment by robert-b** [comment]
yes, i start to understand your view.
it's a two step 'calibration' schema.
and i already have it running.

**Comment by oleost** [comment]
As an addition if possible, make use of LED / BEEPER or / and twitching of ailerons as an confimation of trim succesfully applied.

**Comment by oleost** [comment]
@digitalentity Postpone to 2.0?
