### ISSUE TITLE
Return to Home is not working on Matek F722-SE

### ISSUE THREAD

**Issue by maponarooo** [iNavFlight/inav#5553]
## Current Behavior
Yesterday I experienced a crash in flight. No matter how I look at it, I don't know why it crashed. What is the reason?
[<img src="https://drive.google.com/uc?export=view&id=1UbgI97Lz9QpeMxkshhIaVkWUOo8pImiM"  onerror="this.style.display='none'" /><br>](url)

iNav 2.4
Frame : XL8
FC : Matek F722-SE
VTX : AKK Race Ranger
ESC : RacerStar 35A BLHeli_S

Mov and Log files... Here.

https://drive.google.com/drive/folders/1ZNoh65GAryoJlF5pgeDS_ha1tb5Lj5t1?usp=sharing

# diff all

# version
# INAV/MATEKF722SE 2.4.0 Feb 11 2020 / 22:53:38 (bcd4caef9)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mix

# servo

# logic

# gf

# feature
feature -AIRMODE
feature DYNAMIC_FILTERS
feature SOFTSERIAL
feature GPS
feature LED_STRIP
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 2 115200 115200 0 115200
serial 2 2048 115200 115200 0 115200
serial 3 1 9600 115200 0 115200
serial 5 1 115200 115200 0 115200
serial 30 32 115200 115200 0 115200

# led
led 0 6,5::CNW:4
led 1 7,5::CNW:4
led 2 6,6::CNW:4
led 3 7,6::CNW:4

# color

# mode_color

# aux
aux 0 0 1 900 1300
aux 1 1 3 900 1300
aux 2 20 3 1700 2100
aux 3 3 0 1300 2100
aux 4 24 0 1700 2100
aux 5 9 0 1300 2100
aux 6 8 2 1700 2100
aux 7 19 4 1700 2100
aux 8 21 4 1300 1700
aux 9 36 5 1700 2100
aux 10 11 1 1700 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 13 3 V
osd_layout 0 1 1 5 V
osd_layout 0 3 8 6 H
osd_layout 0 4 8 6 H
osd_layout 0 7 2 1 V
osd_layout 0 8 1 12 V
osd_layout 0 9 1 6 H
osd_layout 0 10 2 0 V
osd_layout 0 11 2 11 V
osd_layout 0 12 1 6 V
osd_layout 0 13 24 5 V
osd_layout 0 14 8 3 V
osd_layout 0 15 24 6 V
osd_layout 0 20 19 0 V
osd_layout 0 21 19 1 V
osd_layout 0 22 14 5 V
osd_layout 0 23 17 3 V
osd_layout 0 27 23 7 V
osd_layout 0 30 1 9 V
osd_layout 0 40 24 2 V
osd_layout 0 105 10 0 V

# master
set looptime = 500
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 90
set gyro_lpf_type = PT1
set gyro_stage2_lowpass_hz = 175
set dyn_notch_min_hz = 130
set acc_hardware = MPU6000
set acczero_x = 113
set acczero_y = -5
set acczero_z = -116
set accgain_x = 4101
set accgain_y = 4108
set accgain_z = 4031
set rangefinder_hardware = MSP
set opflow_hardware = MSP
set opflow_scale =  9.844
set align_mag = CW270FLIP
set mag_hardware = QMC5883
set magzero_x = -768
set magzero_y = 164
set magzero_z = -162
set baro_hardware = BMP280
set pitot_hardware = NONE
set rssi_channel = 16
set motor_pwm_rate = 16000
set motor_pwm_protocol = DSHOT600
set throttle_idle =  10.000
set failsafe_procedure = RTH
set failsafe_min_distance = 2000
set model_preview_type = 3
set applied_defaults = 2
set gps_provider = UBLOX7
set gps_sbas_mode = AUTO
set mc_airmode_type = THROTTLE_THRESHOLD
set nav_extra_arming_safety = ALLOW_BYPASS
set nav_auto_speed = 1000
set nav_manual_climb_rate = 100
set nav_landing_speed = 150
set nav_emerg_landing_speed = 300
set nav_min_rth_distance = 1000
set nav_rth_altitude = 2000
set nav_mc_bank_angle = 40
set nav_mc_hover_thr = 1350
set telemetry_inverted = ON
set osd_video_system = NTSC
set osd_rssi_alarm = 50
set osd_alt_alarm = 150
set osd_dist_alarm = 2000
set name = iNAV-XL8
set vtx_power = 5
set vtx_low_power_disarm = UNTIL_FIRST_ARM

# profile
profile 1

set mc_p_pitch = 30
set mc_i_pitch = 50
set mc_d_pitch = 25
set mc_p_roll = 30
set mc_i_roll = 50
set mc_d_roll = 25
set mc_p_yaw = 60
set mc_i_yaw = 50
set mc_p_level = 30
set max_angle_inclination_rll = 400
set max_angle_inclination_pit = 400
set dterm_lpf_hz = 80
set use_dterm_fir_filter = OFF
set nav_mc_vel_z_p = 150
set nav_mc_vel_z_i = 250
set nav_mc_vel_z_d = 25
set nav_mc_pos_xy_p = 80
set nav_mc_vel_xy_p = 50
set nav_mc_vel_xy_i = 40
set nav_mc_vel_xy_d = 60
set d_boost_factor =  1.500
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set rc_yaw_expo = 70
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 50

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

# 

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
According to the blackbox log, here it what happened:

1. at 2:55 UAV started to loose altitude from approx. 56m
1. at 2:58 at 24m (32m altitude lost in 3 second, we can assume UAV was falling down) gyros recorder UAV hit something, probably a branch
1. UAV was already tilted to the left and my assumption is that from around 2:47 (RSSI and DVR based) you were already flying blind from 2:52
1. Failsafe was never activated (link was active)
1. RTH (manual) was activated at 2:58 after loosing already 40m and after first recorder hit on something
1. from 2:59 there is a series of tumblings
1. tumblings stop at 3:07 and we have to assume UAV is on the ground

This looks like a pilot error:
1. Pilot activated RTH manually 6 seconds after loosing FPV feed and when UAV already lost 40m of altitude
1. Failsafe was never triggered
1. RTH activated after first hit into something, probably a branch
