### ISSUE TITLE
F4Omnibus: servo on PB1

### ISSUE THREAD

**Issue by dybiusz** [iNavFlight/inav#5565]
Dear All,

First of all thank ShikOfTheRa ; namirda ; DzikuVx for help by previous post -> Eventually I have instaled UBUNTU...

Problem: 
I have issue with omnibusF4Pro: trying  to have 5 servos and only one motor since my glider has only one. There is problem because despite of changing of line no.40 from target.c from :

"DEF_TIM(TIM3,  CH4, PB1,  TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR,               0, 0), // S2_OUT D1_ST2"

onto :
"DEF_TIM(TIM3,  CH4, PB1,  TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO,               0, 0), // S2_OUT D1_ST2"

and set motor for 50hz (Inav configurator) , engine on PB0  does not work - not even indicate start when I plug battery , but servo on PB1 work as expected.
What shall I do?

Best regards, 

Marcin

**Comment by DzikuVx** [comment]
This will not work like that I'm afraid. TIM3 is already used by PB0 and you would have to hack pwm_assignment logic to make the change
