### ISSUE TITLE
Add 'Current Waypoint' as logic condition operand

### ISSUE THREAD

**Issue by FelixvdDonk** [iNavFlight/inav#5573]
##  Desired Behavior
I would like the ability to deploy a parachute at a specific waypoint. Basically the end of a waypoint flight so that the airplane can safely land by itself.

## Suggested Solution
It would be very nice if the subsection 'flight' in the logic condition drop down menu would be supplemented with 'Current Waypoint' as a logic operand

 (the definition of 'Current Waypoint' in my mind is the waypoint number that has been reached, not the one it's flying towards. Perhaps the naming could be better). 

Adding this would then allow me to set logic settings like these: 

- if 'current waypoint' > 40'  then Throttle = 0% (shuts of motor during parachute deployment)
- If 'Throttle' < 5%'  then servo 6 = 2000us ( opens hatch and deploys parachute)

## Who does this impact? Who is this for?
Both fixed wing and VTOL community

**Comment by FelixvdDonk** [comment]
I might be able to implement this feature myself if somebody could supply me with a bit more explanation on the source code for logic conditions.

**Comment by fremebondo** [comment]
Hi, I am trying something similar in #5854 (which may be closed) where I suggested a way to go, but I did not tested yet due to weather.
