### ISSUE TITLE
no motor output for omnibus nano v7 on flying wing

### ISSUE THREAD

**Issue by msyafiq227** [iNavFlight/inav#5574]
## Current Behavior
no motor output for omnibus nano v7 on flying wing
no signal been release on output s1 and s4

## Desired Behavior
need to map motor output on s1

## Who does this impact? Who is this for?
for omnibus nano v7 user that use on a fixed wing

**Comment by Woga65** [comment]
@msyafiq227 
S1+S3 and S2+S4 need to have the same protocol.
So if you have an ESC attached to S1, the protocol need to be „STANDARD“ (pwm) and the rate need to be the same as setup for the servos.

I have configured the S3 output for a second motor now so flying wing should work with the new hex-file.

Possible configurations inside the target file are:

1) S1+S3 = ESC, S2+S4 = servos, LED pin = LED
2) S1+S3 = ESC, S2+S4 = servos, LED pin = servo
3) S1-S4 = servos, LED pin = ESC
4) leave it as is and set protocol and motor rate to match the servos.

I opted for variant 1) and uploaded a new omnibusf4nanov7 hex file.
https://github.com/Woga65/inav/releases
