### ISSUE TITLE
configurator and osd select the wrong frequents for vtx (looklike its swapped)

### ISSUE THREAD

**Issue by modwadd** [iNavFlight/inav#5583]
## Current Behavior
FC: MatekF765
FTX: echine tx805 v2.0
inav: 2.4.0
If I chous Band A channel **1** the transmitter switxch tol Band A channel **8**!
If I chouse Band A channel **8** the transmitter switxch tol Band A channel **1**!

on Band B it works korrect ! I will take some pictures.
## Steps to Reproduce

1. Setup FC an xtx
2.Powert up and tune vrx to get picture (including chosen channel displayed in osd))
3.Set channel via configurator or OSD, channel is switche but on wron channel.
4.

## Expected behavior

Channel which ist choosen in OSD or configurator is choosen (send to ) vtx to change to
## Suggested solution(s)

look like ther is an index issue on the channel table.
the table in vtx_string.c is correct.
## Additional context

---

- FC Board name and vendor: Matek Systems FC F765 Wing
- INAV version string:INAV/MATEKF765 2.4.0 Feb 11 2020 / 23:09:10 ( bcd4caef9 )

**Comment by modwadd** [comment]
[INAV_cli_20200408_212419_f765_v2ok.txt](https://github.com/iNavFlight/inav/files/4462847/INAV_cli_20200408_212419_f765_v2ok.txt)

**Comment by DzikuVx** [comment]
Are you sure the problem is not on the VTX side?

**Comment by modwadd** [comment]
Hm, on vtx.
Not shure I have only the tx805 yet.
If you like I could do a video of the OSD ant the video RX  wilth oled.

An second Smart Audio VTX (RUSH Tank Racing VTX 5.8G Smart Audio Video Transmitter) is "in transit", I could compare it on arrival. 

BR

**Comment by modwadd** [comment]
Hello,
I figured out the issue now.
With a secont SA VTX the issue is the same.
But its not a bug in the iNav its in my Quantum 5.8 Diversety rceiver, it displais for band A the channels wrong. (channel 8 to 1 not 1 to 8)

BR
