### ISSUE TITLE
inav will not accept set vtx_freq = 2510 in cli

### ISSUE THREAD

**Issue by iCryWhenIwii** [iNavFlight/inav#5588]
Hi

I am trying to set up a Furious 2.4 vtx on a Mateksys F411 FC in the softserial as the 2 ports are being used by GPS and receiver.
I cannot get cli to accept set vtx-freq = 2510 to allow OSD to work.  I can get video feed if I bypass the FC and connect camera directly to VTX so I know individual componants are working.

I have tried the following command lines;

serial 30 131072 115200 115200 0 115200
set vtx_halfduplex = ON
set vtx_band = 1
set vtx_channel = 8
set vtx_power = 4
set vtx_low_power_disarm = ON
set vtx_freq = 2510 
vtx_ffpv24g.c

Everything is accepted apart from set-vtx, this defaults to 5725 no matter what I do :(

sub note - I have exactly the same setup on a long range quad using Betaflight and have no problems at all and I do wnat Smartaudio or any fancy stuff...just want video feed with OSD

Thanks in advance

**Comment by DBetic-Pilot** [comment]
Just looking at the CLI editor, try setting vtx_band = 0 and then setting your vtx_freq =2510.  It appears that vtx_freq is only used when vtx_band is set to 0, and otherwise is only looking for the 5.8 GHz bands.
