### ISSUE TITLE
Omnibus F4V3 Broken support for PPM receiver when softserial target selected 

### ISSUE THREAD

**Issue by robertha64** [iNavFlight/inav#5594]
## Current Behavior
Case 1: When flashed OmnibusF4V3 target to F4V3 board, PPM is working on SBUS/PPM pin.
Case2: When flashed the same board with Omnibus F4V3 S5S6_SS, Omnibus F4V3 S5_S6_2SS or Omnibus F4V3 S6_SS the PPM input is not working.

resource output case1:
 resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: MOTOR4 OUT
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: FREE 
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: FREE 
A15: OSD CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B02: FREE 
B03: BARO CS
B04: BEEPER OUT
B05: LED1 OUT
B06: FREE 
B07: SDCARD IN
B08: PPM IN
B09: FREE 
B10: I2C2 SCL
B11: I2C2 SDA
B12: SDCARD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE 
C01: FREE 
C02: ADC CH2
C03: FREE 
C04: MPU EXTI
C05: FREE 
C06: SOFTSERIAL1 UART TX
C07: FREE 
C08: INVERTER OUT
C09: INVERTER OUT
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: FREE 
C14: FREE 
C15: FREE 
D00: FREE 
D01: FREE 
D02: FREE 
D03: FREE 
D04: FREE 
D05: FREE 
D06: FREE 
D07: FREE 
D08: FREE 
D09: FREE 
D10: FREE 
D11: FREE 
D12: FREE 
D13: FREE 
D14: FREE 
D15: FREE 

# 

resource output case2:
resource
IO:
----------------------
A00: FREE 
A01: SOFTSERIAL1 UART TX/RX
A02: MOTOR4 OUT
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: SOFTSERIAL2 UART TX/RX
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: FREE 
A15: OSD CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B02: FREE 
B03: BARO CS
B04: BEEPER OUT
B05: LED1 OUT
B06: FREE 
B07: SDCARD IN
B08: FREE 
B09: FREE 
B10: I2C2 SCL
B11: I2C2 SDA
B12: SDCARD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE 
C01: FREE 
C02: ADC CH2
C03: FREE 
C04: MPU EXTI
C05: FREE 
C06: FREE 
C07: FREE 
C08: INVERTER OUT
C09: INVERTER OUT
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: FREE 
C14: FREE 
C15: FREE 
D00: FREE 
D01: FREE 
D02: FREE 
D03: FREE 
D04: FREE 
D05: FREE 
D06: FREE 
D07: FREE 
D08: FREE 
D09: FREE 
D10: FREE 
D11: FREE 
D12: FREE 
D13: FREE 
D14: FREE 
D15: FREE 

# 

## Steps to Reproduce

1. Program Omnibus F4V3 board (will work the same way also on Omnibus F4Pro board) with Omnibus F4V3 FW - check PPM - should work 
2. Program Omnibus F4V3 or F4PRO board with F4V3 S5S6_SS or F4V3 S5_S6_2SS FW - ckeck PPM - will not work
3.
4.

## Expected behavior
There is no reason why softserial on A1(M5) and A8(M6) will disable PPM on B08
## Suggested solution(s)
Revert latest changes to target.c for Omnibus F4, as I believe it did work correctly some time ago 

## Additional context

---

- FC Board name and vendor:
Omnibus F4V3 and Omnibus F4PRO both from Banggood
- INAV version string:
 
# INAV/OMNIBUSF4V3_S6_SS 2.2.1 Jul  3 2019 / 22:15:59 (a6d847482)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

**Comment by robertha64** [comment]
I think is broken because of this change, because when I build user fw with change reverted, PPM is working.
![image](https://user-images.githubusercontent.com/39700425/79635832-a05ea200-8173-11ea-8a8a-e745ac35560e.png)

**Comment by tiriad** [comment]
I tried the variant Omnibus F4v3 S5 S6  2SS and detects PPM in PB8, that change you indicate was made so that all variants Omnibus F4v3 were compatible with PPM and not make the code repeited use. Try to test if there is any configuration that you have not taken into account.
And please update your version to inav 2.4.0, your version 2.2.1 had that problem.

target.h
![Captura](https://user-images.githubusercontent.com/42714516/79701300-3aba0500-829c-11ea-9d5a-3a2abc81548d.JPG)
target.c
![Captura](https://user-images.githubusercontent.com/42714516/79701328-7785fc00-829c-11ea-9cc2-f22d8d16f22d.JPG)
![Captura](https://user-images.githubusercontent.com/42714516/79701387-faa75200-829c-11ea-9473-ed587c6e1960.JPG)

**Comment by robertha64** [comment]
I did try 2.4 now (S4S6_SS), PPM is there but no softserial on A01 and/or A08.


Whats wrong ? 

![S5S6](https://user-images.githubusercontent.com/39700425/80091772-f1024080-8561-11ea-96f3-247177888fb6.JPG)

![image](https://user-images.githubusercontent.com/39700425/80091898-2c9d0a80-8562-11ea-8a3f-219cf7c78f2b.png)

**Comment by digitalentity** [comment]
Too many different OMNIBUS F4 clones I guess... I'll have a look

**Comment by tiriad** [comment]
@robertha64 I tried again, the softserial will appear when you activate a peripheral, sensor or any other output/input
![Captura](https://user-images.githubusercontent.com/42714516/80098837-cd44f780-856d-11ea-8c12-50b981afad91.JPG)


> Too many different OMNIBUS F4 clones I guess... I'll have a look

@digitalentity I think it's not a code problem, it's a firmware configuration problem

**Comment by robertha64** [comment]
I believe I did activate SmartPort for Softserial1 but no sign of softserial in resources, I will try again later.

**Comment by tiriad** [comment]
> I believe I did activate SmartPort for Softserial1 but no sign of softserial in resources, I will try again later.

For set SmartPort also remember to activate first enable Telemetry (feature telemetry in cli)
https://github.com/iNavFlight/inav/blob/master/docs/Telemetry.md

**Comment by robertha64** [comment]
Good catch, SmartPort was correctly setup on softserial, but telemetry not activated, now is fine. Closing.
![image](https://user-images.githubusercontent.com/39700425/80205962-d3011280-862b-11ea-9fcc-bca9feffc8ff.png)
