### ISSUE TITLE
NAV - Improve sonar support (terrain following)

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#56]
There is a problem with sonar mode. It works relatively well as long as surface is flat and altitude measured my baro and sonar is similar. As soon as surface distance and baro altitude gets significatly (several meters) different there are problems with transitioning between baro and sonar.

Position estimator and AH mode need to be reworked to do proper terrain-following with sonar and seamlessly (without jumps or falls) transition to baro if sonar gets out of range.

**Comment by digitalentity** [comment]
Some support done. Bug fixes still required.

**Comment by DzikuVx** [comment]
@digitalentity I suppose this is done, right?

**Comment by digitalentity** [comment]
Yes, closing.
