### ISSUE TITLE
Add logical switches to motors mixer

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#5606]
Currently, logical switches are only available on servos in the mixer. It would be handy in certain situations to be able to control the motors in a similar way. 

An example could be if you have a twin motor aircraft and you want to have differential thrust, but only in certain situations. I have someone who would like differential thrust to assist when taxing the plane, but in the air does not want it at all. 

My suggested solution is to add an “active” column to the motors entries. This would allow the user to choose the logical switch to determine when this motor is active. Also it would need the motor column to be selectable. I would suggest a drop down list, with only the number of motor outputs available shown.  

This would effect advance airplane users mostly. But it could also have advantages to rovers, perhaps rovers with tracks?

**Comment by kniuk** [comment]
I would love such feature. However that would affect yaw PIFF effectiveness. So we should take that into consideration.

**Comment by DzikuVx** [comment]
There is a plan to do something like that but as a "secondary motor mixer bank" that can be switched in flight. However, I can not give any estimates on the timeline
