### ISSUE TITLE
No DSHOT support?

### ISSUE THREAD

**Issue by VICLER** [iNavFlight/inav#5612]
Hello! I can not set DSHOT on inav 2.4.0 (Configurator v2.4.1). Inav resets DSHOT to standard pwm protocol after "save and reboot". Am I missing something? I have kakute F4v2 and DALRC Engine 40A 
with Blheli 32. On earlier versions of inav I had the same issue. Setting DSHOT in betaflight works fine.

**Comment by DzikuVx** [comment]
DSHOT on Kakute F4 will be supported in upcoming INAV 2.5
