### ISSUE TITLE
Orbit or Roll side waypoint

### ISSUE THREAD

**Issue by a-425** [iNavFlight/inav#5631]
## Current Behavior
Waypoint only can cruise / fly with Front forward. and Unable to do orbit by waypoint (automatic)

## Desired Behavior
I'll be glad if it could fly in WP mode to do Orbit automatically. And also if maybe possible fly with Roll direction.

## Suggested Solution
On Orbit mode, maybe it will looks like regular waypoint, but heading is set for specific point. So I think it will be able to do Fly in roll direction as well

## Who does this impact? Who is this for?
Maybe this will only work for MC users

## Additional context
Thanks

**Comment by stronnag** [comment]
Duplicate of #154 (SET_POI / SET_HEAD) functionality
