### ISSUE TITLE
INAV 2.4.0 - log file truncated?

### ISSUE THREAD

**Issue by LukaszFro** [iNavFlight/inav#5633]
I have updated Matek F405-CTR to INAV 2.4.0, target MATEKF405_SERVOS6 because I intended to use a "servo gimbal" on my quad.
Previous SW was 2.3.0, target MATEKF405.
Since that my log files are truncated. The longest one has about 4 MB and contains 27 seconds of flight. My SD-card is Goodram 8 GB class 10. I had no problems with it until recent INAV update.
Tried to find any options for it in INAV Configurator logging tab but without success
Attaching the logs. First "0065" is from version 2.3 for reference.
Is it my card problem, config problem or INAV bug?
[logs_truncated.zip](https://github.com/iNavFlight/inav/files/4538289/logs_truncated.zip)

**Comment by giacomo892** [comment]
Truncated logs usually mean two things:

1. Slow SD Card
2. Logging too fast
