### ISSUE TITLE
BN-880 magnetometer INAV setup

### ISSUE THREAD

**Issue by kibinek** [iNavFlight/inav#5637]
Please, I need help. I have BN-880 GPS module with magnetometer placed on my quad like on pic below:
[http://kibinek007.sweb.cz/fpv/dwarf/dwarf_gps_mount.jpg](url)
Please, what shall be the setup of INAV variables:
**align_mag
align_mag_roll
align_mag_pitch
align_mag_yaw**
I tried perhaps all combinations, but then, when I pitch with quad for cca 30° back and forth, the nose of 3D model of quad in INAV Setup page moves not only from bottom to top, but also from left to right. I am getting insane...

**Comment by giacomo892** [comment]
This is not a support channel.
Please join our communities on Telegram, Facebook or rcgroups.
