### ISSUE TITLE
New Target SP RACING H7 ZERO

### ISSUE THREAD

**Issue by rgp1942** [iNavFlight/inav#5638]
Please add new flight controller SP RACING H7 ZERO, which contains the new BMP388 barometer, which is twice as accurate as the BMP280 barometer.
http://seriouslypro.com/spracingh7zero

This provides the best solution yet for effective altitude hold.

I'm sure SP RACING will provide all the needed information to create a new target.
https://shop.seriouslypro.com/contact/

**Comment by digitalentity** [comment]
Duplicate of #5212

**Comment by hydra** [comment]
@digitalentity I can help with the target definition once processor support is underway.

@rgp1942 I fully agree that the SPRacingH7ZERO makes for a GREAT iNAV board.
