### ISSUE TITLE
New Flight Controller MATEK F405-MINI

### ISSUE THREAD

**Issue by rgp1942** [iNavFlight/inav#5639]
Please add new flight controller MATEK F405-MINI.
http://www.mateksys.com/?portfolio=f405-mini
email: Service@mateksys.com

I want to add a BMP388 barometer to this FC via I2C and use it for altitude control in INAV for a 110mm "Cinewhoop" (not racing, but camera).  There is no existing target in INAV for this FC.  If I can use another existing target please let me know.

Thank you!

**Comment by giacomo892** [comment]
MATEKF405 target
