### ISSUE TITLE
INAV 2.4.1 - I2C External Compass Problem

### ISSUE THREAD

**Issue by TheNewbFlyer** [iNavFlight/inav#5643]
I have looked through dozens of threads and videos, and I cannot seem to find the problem. 

Seriously Pro F3 Acro Flight Controller
Betian 880 GPS with internal compass
INAV 2.4.1

At the bottom: "I2C error: 1"
Mag icon is red
GPS icon is blue (and GPS is working correctly) 

How do I know if I've configured something wrong, or if I need to add some resistor pickups like I've read about? (is there even a way to tell?)

**Comment by DzikuVx** [comment]
GPS module has to be powered, I2C lines SDA and SCL have to be connected . If it still does not work, try lowering i2c_speed parameter via the CLI
