### ISSUE TITLE
Speedy Bee F7 AIO

### ISSUE THREAD

**Issue by adventureman82** [iNavFlight/inav#5656]
## Current Behavior
I do not see a target for the Speedybee F7 AIO FC

## Desired Behavior
Build a target for the Speedybee F7 AIO FC

**Comment by digitalentity** [comment]
Please have a look at the [INAV new hardware policy](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md) for conditions needed to add a new target

**Comment by rickcote0041** [comment]
Is the speedybee f7 aio iNav target in development and if so is there an estimated availability yet?
