### ISSUE TITLE
"Unable to Arm / Sensors Calibrating" needs to be more verbose after a time

### ISSUE THREAD

**Issue by FireNWater** [iNavFlight/inav#5686]
## Current Behavior
When the FC cannot arm due to a sensor problem, the OSD message "Unable to Arm / Sensors Calibrating" shows on the OSD.

## Desired Behavior
Since the flight vehicle could have many sensors, I would like the message to show which sensor is currently keeping the system from arming.

## Suggested Solution
After a period of time, perhaps 30 to 60 seconds, add text to the OSD error message to identify which sensor is preventing the system from arming .

## Who does this impact? Who is this for?
All users.

## Additional context
This feature would greatly enhance troubleshooting, especially at the field.

**Comment by FireNWater** [comment]
When the FC cannot arm due to a sensor problem, the OSD message "Unable to Arm / Sensors Calibrating" shows on the OSD.  Since the flight vehicle could have many sensors, I would like the message to show which sensor is currently keeping the system from arming.  This would greatly enhance troubleshooting, especially in the field.

**Comment by Pairan** [comment]
Had the same in the field lately ... "Unable to Arm / Sensors Calibrating" and then sometime later "RIGHT PITCH NOT CENTERED" ...

I had connected a 4s instead of a 3s battery ... changing that solved my problem somehow,

**Comment by Tgoraj** [comment]
Ok, so plugging a 3s battery in solved it but my plane only uses 4s batteries so… what do I do?why is there no solution to this issue?

**Comment by MrD-RC** [comment]
Hold the aircraft still. Its calibrating the onboard sensors. It can’t calibrate the gyro if it’s moving.
