### ISSUE TITLE
afroflight32 rev.6 flashing / blheli 1wire passthroug issues

### ISSUE THREAD

**Issue by pegaz666** [iNavFlight/inav#569]
Hello all, that's my first post here hopefully i'm writting in the right place. Thank you all for all the input in that great project.

I'm having a few issues: 
1st. I wanted to try iNav 1.2 rc5 and after flashing my afroflight32 rev.6 the board is not connecting to the configurator anymore. Tried all 1.2 release candidates and they are having the same issue. I've done full chip erease etc. Everytime after flashing with those I need to do the bootloader trick to bring board back to live. No issues with cleanflight or iNav 1.1. Works like a charm. No matter what i do any of those 1.2s are not booting up properly and i'm unable to connect to the configurator.

2nd issuse I have is blheli suite- with a cleanflight it works like a charm, but it does not work while I'm on iNav (even 1.1) I can't connect with the escs. Everytime I need to change escs settings (they all have blheli bootloaders) i need to flash back to cleanflight in order to get blheli suit working. 
Are these issues known? Am I doing something wrong? Any chance to get them fixed? 
Thank you

**Comment by pegaz666** [comment]
Just found out that the 1.2 (stable) is out -this time it flashed without any issues but my esc are loosing sync and I'm unable to take off . Only one prop is spinning, calibrating them via configurator/motor tab is not helping either- just one prop is working only. When i play with the sliders in the configurator they all work fine...master slider and they are spinning all together. Blheli Suite still doesn't work at all with this firmware

**Comment by DzikuVx** [comment]
Can you provide us a CLI dump ?

**Comment by pegaz666** [comment]
Already went back to iNav 1.1 all good now but i have saved cli dump before so here it is: 

# version

# INAV/NAZE 1.2.0 Sep  7 2016 / 11:26:35 (6cc415a)

# pflags

# Persistent config flags: 0x00000001

# dump master

# mixer

mixer QUADX
mmix reset
smix reset

# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_NRF24
feature -SOFTSPI
feature RX_PPM
feature VBAT
feature INFLIGHT_ACC_CAL
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature FAILSAFE
feature TELEMETRY
feature ONESHOT125

# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map

map AETR1234

# serial

serial 0 1 115200 38400 0 115200
serial 1 0 115200 38400 0 115200
serial 30 0 9600 38400 0 115200
serial 31 2 115200 19200 0 115200

set looptime = 2000
set i2c_overclock = OFF
set gyro_sync = OFF
set gyro_sync_denom = 2
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1040
set max_throttle = 2000
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 261
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = EGNOS
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 500
set nav_max_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 300
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = FIXED
set nav_rth_altitude = 3000
set nav_mc_bank_angle = 40
set nav_mc_hover_thr = 1290
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SPEK1024
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = CW180FLIP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 3
set failsafe_off_delay = 200
set failsafe_throttle = 1275
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 150
set failsafe_procedure = RTH
set rx_min_usec = 970
set rx_max_usec = 2030
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 3
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set magzero_x = -30
set magzero_y = -91
set magzero_z = -67
set acczero_x = 45
set acczero_y = 65
set acczero_z = 82
set accgain_x = 4092
set accgain_y = 4086
set accgain_z = 4061

# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 h
rxfail 4 h
rxfail 5 h
rxfail 6 s 1000
rxfail 7 s 2000
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile

profile 0

# aux

aux 0 1 3 1850 2100
aux 1 2 3 1350 1650
aux 2 3 2 900 1650
aux 3 10 2 900 1200
aux 4 9 1 900 1200
aux 5 12 0 900 1175
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 65
set nav_pos_i = 120
set nav_pos_d = 10
set nav_posr_p = 180
set nav_posr_i = 15
set nav_posr_d = 100
set nav_navr_p = 10
set nav_navr_i = 5
set nav_navr_d = 8
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set flaperon_throw_offset = 250
set flaperon_throw_inverted = OFF
set mode_range_logic_operator = OR
set default_rate_profile = 0
set gimbal_mode = NORMAL
set mag_declination = -40
set mag_hold_rate_limit = 90
set p_pitch = 30
set i_pitch = 20
set d_pitch = 70
set p_roll = 30
set i_roll = 20
set d_roll = 70
set p_yaw = 100
set i_yaw = 40
set d_yaw = 0
set p_level = 120
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000

# dump rates

# rateprofile

rateprofile 0

set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 29
set thr_expo = 0
set roll_rate = 6
set pitch_rate = 6
set yaw_rate = 2
set tpa_rate = 0
set tpa_breakpoint = 1500

#

**Comment by DzikuVx** [comment]
I think I know what the problem is: PIDs. INAV 1.2 changed a lot in terms of PID scaling and default values. 

Did you just copied PIDs from 1.1 to 1.2? 

Also you rates look rather odd... only 60dps ? 

Please read https://github.com/iNavFlight/inav/wiki/PID-conversion-from-pre-1.2-to-1.2 and https://github.com/iNavFlight/inav/wiki/Rate-conversion-for-INAV-1.2

**Comment by pegaz666** [comment]
I haven't touched any PIDs and did not copy them from previous versions . I keept PID's and Rates stock as they came with the firmware. I don't know how to tune them that's why i did not touch them. From rates section i only changed thr_mid from 50 to 29 as my quad hoovers at 29% of throttle. Restoring configurator from restore file does not restore PIDs so that's not the case ;( could you also tell me what is the story with Blheli Suite that doesn't work? Is it only me or that the known issue
That has not been resolved yet??

**Comment by DzikuVx** [comment]
I do not know what you did, but those are not default PID values of inav 1.2. 

> Restoring configurator from restore file does not restore PIDs so that's not the case ;( 

Are you sure of that? Those Pids did not appeared from nowhere

**Comment by xdigyx** [comment]
BLHeli interface has been removed for Naze32 target due to insufficient memory of F1. So you need to configure and calibrate (parameters PPM min/max) ESCs through BLHeli suite connected directly (not through FC). Once it's done, you do not need to calibrate via configurator/motor tab. I have the same hardware and works fine.

**Comment by oleost** [comment]
@pegaz666 Please do a firmware flash with clean erase and then post cli dump. 

Without editing anything.

**Comment by pegaz666** [comment]
Hi - DzikuVx was right those PID values got restored from previous version so I took another chance and re-flashed it now again making sure that PID's are not gonna be changed BUT the problem is still there. Just one prop is spinning... here is a clean CLI dump ( i always got full chip erased marked during every flashing)

# dump

# version

# INAV/NAZE 1.2.0 Sep  7 2016 / 11:26:35 (6cc415a)

# pflags

# Persistent config flags: 0x00000001

# dump master

# mixer

mixer QUADX
mmix reset
smix reset

# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_NRF24
feature -SOFTSPI
feature RX_PPM
feature VBAT
feature INFLIGHT_ACC_CAL
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature FAILSAFE
feature TELEMETRY
feature ONESHOT125

# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map

map AETR1234

# serial

serial 0 1 115200 38400 0 115200
serial 1 0 115200 38400 0 115200
serial 30 0 9600 38400 0 115200
serial 31 2 115200 19200 0 115200

set looptime = 2000
set i2c_overclock = OFF
set gyro_sync = OFF
set gyro_sync_denom = 2
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1040
set max_throttle = 2000
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 261
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = EGNOS
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = OFF
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 500
set nav_max_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 300
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = FIXED
set nav_rth_altitude = 3000
set nav_mc_bank_angle = 40
set nav_mc_hover_thr = 1290
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SPEK1024
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = CW180FLIP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 3
set failsafe_off_delay = 200
set failsafe_throttle = 1275
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 150
set failsafe_procedure = RTH
set rx_min_usec = 970
set rx_max_usec = 2030
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 3
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set magzero_x = -30
set magzero_y = -91
set magzero_z = -67
set acczero_x = 45
set acczero_y = 65
set acczero_z = 82
set accgain_x = 4092
set accgain_y = 4086
set accgain_z = 4061

# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 h
rxfail 4 h
rxfail 5 h
rxfail 6 s 1000
rxfail 7 s 2000
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile

profile 0

# aux

aux 0 1 3 1850 2100
aux 1 2 3 1350 1650
aux 2 3 2 900 1650
aux 3 10 2 900 1200
aux 4 9 1 900 1200
aux 5 12 0 900 1175
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 65
set nav_pos_i = 120
set nav_pos_d = 10
set nav_posr_p = 180
set nav_posr_i = 15
set nav_posr_d = 100
set nav_navr_p = 10
set nav_navr_i = 5
set nav_navr_d = 8
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set flaperon_throw_offset = 250
set flaperon_throw_inverted = OFF
set mode_range_logic_operator = OR
set default_rate_profile = 0
set gimbal_mode = NORMAL
set mag_declination = -40
set mag_hold_rate_limit = 90
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_level = 20
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 500
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000

# dump rates

# rateprofile

rateprofile 0

set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 29
set thr_expo = 0
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500

#

**Comment by pegaz666** [comment]
Just checked one thing: after DISABLING "one shot esc" all props started spinning (quad was a bit wobbly) , re-enabling tha feature again brought the problem back again. So there is something wrong with one shot escs in 1.2
@xdigyx - i'm unable to calibrate them the other way than via FC. They are hard soldered to the frame - it's Diatone Tyrant 180, and the FC got micro JTS ports

**Comment by xdigyx** [comment]
Regarding ESC setup/calibration: as I already wrote from 1.2+ BLHeli interface will not be supported  (as far as I know). So you either should flash old FW to setup the ESCs or you would need to use external tools (I see it's not an easy task in your case but it's not impossible). You should not re-calibrate ESCs via configurator/motor tab once you setup PPM min/max from BLHeli suite.

Regarding OneShot I can not help you much.

**Comment by martinbudden** [comment]
@pegaz666 , one thing you can do is reflash your FC to betaflight, calibrate the ESCs and then reflash back to iNav.

**Comment by pegaz666** [comment]
@martinbudden - this is what I'm doing, taking it back to cleanflight, use Blheli suite to change the settings and then back to iNav but this is not my major problem now. The major problem is that my thing is not flying on any 1.2 ( not all the props a spinning) when on 1.1 everything works as it should

**Comment by xdigyx** [comment]
if you got an oscilloscope you could compare outputs (1.2 vs 1.1). If not then maybe an arduino with a simple program to compare times of outputs HIGH/LOW.

Try release https://github.com/iNavFlight/inav/releases/tag/1.2-RC4
after this one PWM mapping has been changed.

**Comment by pegaz666** [comment]
That's the thing - i tried 1.2-RC3, 1.2-RC4, 1.2-RC5 before and non of them were booting my FC properly (they were kind of bricking it). That was the main issue why I posted that problem here. To bring it back to live I had to be shortening the bootloader pads . Only the final 1.2 fixed the booting problem but now I've got this

**Comment by digitalentity** [comment]
@pegaz666 can you please verify that the issue is still present with 1.3-RC1?
