### ISSUE TITLE
Matek F411-Wing SoftSerial RX on LED pin

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav#5692]
At present there is firmware for - `FD SoftSerial` and `2 x SoftSerial TX`.

Although having one SoftSerial as an RX (LED pin) and the other a TX (ST1), would be very useful.
This would allow the TX to be used for` VTX audio control` and the RX to be used for `ESC telemetry`. Giving this compact FC even more functionality for small planes.

Thanks

**Comment by MATEKSYS** [comment]
Softserial_tx can be used as softserial_rx also, they are both defined on same pin.

#if defined(MATEKF411_SFTSRL2)
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_TX_PIN     PA0 // ST1 pad
#define SOFTSERIAL_1_RX_PIN     PA0
#define USE_SOFTSERIAL2
#define SOFTSERIAL_2_TX_PIN     PA8 // LED pad
#define SOFTSERIAL_2_RX_PIN     PA8
