### ISSUE TITLE
Firmware flashing FPV camera on Runcam Hybrid via FC

### ISSUE THREAD

**Issue by JeanFPV** [iNavFlight/inav#5709]
Hi.
I have 1 question about topic. 

Mobile app SpeedyBee allow upgrade firmware version fpv camera on Hybrid. And does that via Betaflight or Kiss. Well, I try flash via BF way, but in real FC was Inav. Flash is failure, camera have black screen. 
After I flash Betaflight to FC, this repair flasing is well. Camera is work.

I ask in SpeedyBee moders, why app have no support INAV? 
They answer: Dear users, since the iNav firmware does not support the transparent transmission function, there is no way to upgrade the camera's firmware.

And now, I just ask, why not?

P.S. Sorry for my ignorance and thank you!

**Comment by Tduru** [comment]
thats just how it is, unfortunately. i used a spare f411 wing board, flashed it with betaflight and upgraded my runcam hybrid with zero issues.
