### ISSUE TITLE
have auto trim ignore "servo" outputs that are set to direct RC channel

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#5719]
## Current Behavior
Current behavior is that auto trim will also "trim" the midpoint for channels that are set to "RC channel xx" in the mixer tab to whatever value they're at when auto trim is set.

For example, my Servo 5 (lights channel) is set to RC Channel 10 if it's "off (-100/1000uS) then that's what the mid point gets set to. if it's "on" (100/2000uS) then that's what the midpoint gets set to.

![image](https://user-images.githubusercontent.com/1495297/81752950-a1d46f00-9480-11ea-9470-ebc38f93800d.png)

## Desired Behavior
auto trim to ignore any servo mixer set to a specific RC channel

## Suggested Solution
ignore any servo output that is specifically set to an RC channel

## Who does this impact? Who is this for?
Anyone that uses a pan/tilt, PWM controlled switches or lights etc

**Comment by wx4cb** [comment]
Bump. Is this possible?

**Comment by wx4cb** [comment]
bump?

**Comment by avsaase** [comment]
I'm working on a new auto trim feature that will also make it configurable which servos are trimmed.

**Comment by avsaase** [comment]
Closed by https://github.com/iNavFlight/inav/pull/6708.
