### ISSUE TITLE
MATEKF765 2.5.0_RC1 no Input from SBUS Tx

### ISSUE THREAD

**Issue by Kraligor** [iNavFlight/inav#5764]
## Current Behavior
No input from transmitter is registered in the configurator.

## Steps to Reproduce

1. Flash MATEKF765 2.5.0 RC1
2. Bind transmitter
3. Open configurator, go to Receiver tab
4. Move controls on transmitter

## Expected behavior
Input from transmitter should be registered and shown in the Receiver tab. It works with 2.4.0.

---

Dump attached

- FC Board name and vendor: MATEKSYS F765
- INAV version string:  INAV/MATEKF765 2.5.0 May  9 2020 / 15:18:11 (272de567d)

[MATEKF765-2.5.0_RC1.txt](https://github.com/iNavFlight/inav/files/4658865/MATEKF765-2.5.0_RC1.txt)

**Comment by digitalentity** [comment]
Please provide dump of the configuration.

**Comment by Kraligor** [comment]
> Please provide dump of the configuration.

Attached to the OP.

**Comment by stronnag** [comment]
Configuration error from your dump. I seriously doubt this worked in 2.4.
```
set receiver_type = MSP
```
Please reopen if this is not the case, also consider social media for future support issues.
