### ISSUE TITLE
OSD Component CPU Loading

### ISSUE THREAD

**Issue by CadmonkeyFPV** [iNavFlight/inav#5768]
I'm running a Kakute F7 and the OSD component is loading the CPU >80%. I tried turning off OSD elements with no improvement, and I tried slowing the loop time from 500us all the way down to 3500us and saw no improvement. What's going on? Betaflight on the same hardware only uses at max 0.8% CPU.
![OSD Task Meter-inav](https://user-images.githubusercontent.com/65134608/82675787-50ac4400-9c13-11ea-9943-12601961de22.jpg)
![OSD Task Meter-beta](https://user-images.githubusercontent.com/65134608/82675789-50ac4400-9c13-11ea-8b8b-cba2b05732d1.jpg)

**Comment by DzikuVx** [comment]
The `max/us` i is the task execution that includes initialization and as such should not be counted. As such, there is really no problem as average processing time is 45us
