### ISSUE TITLE
When I connect the magnetometer wires to the flight controller, I don't pick up satellites.

### ISSUE THREAD

**Issue by Christianmix** [iNavFlight/inav#5777]
I am assembling a ZMR250 with a f411 wing flight controller and ts100 radiolink gps. I'm using the firmware inav 2.4 matek f411 rssi, when I look at the inava configurator, it seems to be all right, all the lights on the configurator turn on blue, gyro, accel, mag, baro and gps, I go to the gps tab and there it shows total messages going up the numbers, but even after 10 minutes in an open place I don't have a satellite connection, I disconnect the magnetometer wires in my flight controller, at the same moment I have 13 stelites, and the mag light in the inav configurator turns red, but I have good satellites, remembering that when I sell only the magnetometer wires, it works well, it shows me the north perfectly, I move perfectly, it works very well, but I can't get satellites even with the light of the gps in the configurator of the inv being blue. What can it be?
![01](https://user-images.githubusercontent.com/32267109/82839552-1d351800-9ea6-11ea-926f-59ef273b8d12.jpg)

![02](https://user-images.githubusercontent.com/32267109/82839555-232af900-9ea6-11ea-889b-8367ad1c36b6.jpg)

![WhatsApp Image 2020-05-25 at 16 37 01](https://user-images.githubusercontent.com/32267109/82839560-28884380-9ea6-11ea-8d60-ec003681ba37.jpeg)

**Comment by Sekilsgs2** [comment]
I'm think this is electrical noise to GPS from magnetometer - you can try add some capacitor (maybe 470u) between + and - of magnetometer. GPS don't like electrical noise
