### ISSUE TITLE
Optical Flow telemetry

### ISSUE THREAD

**Issue by Chick92** [iNavFlight/inav#5788]
Is there a way to use a Matek optical flow board with Inav, and also either echo the serial data from the board to another serial port? 

Is the data from the optical flow sensor available in the mavlink telemetry output?

Thanks

**Comment by digitalentity** [comment]
No. Optical flow data alone doesn't have much use, why would you need that data?

**Comment by Chick92** [comment]
Global positioning in GPS denied environments.
