### ISSUE TITLE
"Stop motors on low throttle" not works correct in reversible mode on rover

### ISSUE THREAD

**Issue by WizzX-FPV** [iNavFlight/inav#5789]
## Current Behavior
If "Stop motors on low throttle" is checked than in 3D (reversible) mode it will hardly stop the motor close to max reverse throttle

## Steps to Reproduce
1. If moving throttle stick from center to max position, motor turn from min till max speed forward what is OK
2. If moving throttle stick from center to min position, motor run backward and speed is rising but close to max speed motor just stops hardly
3. position of stop is probable defined by "Motor IDLE power [%]"

## Expected behavior
"Stop motors on low throttle" should stops motor only in centre stick position forward/backwards in 3D mode.

## Suggested solution(s)
define separate conditions for "Stop motors on low throttle" for 2D mode and 3D mode

## Additional context

- FC Board name and vendor:
MATEK F722 STD
- INAV version string:
2.4

**Comment by DzikuVx** [comment]
@WizzX-FPV 3D support in 2.4 is broken and is supposed to work correctly in INAV 2.5. Please try with INAV 2.5 RC2
