### ISSUE TITLE
Failsafe - Configurable PosHold and/or RTH on signal loss

### ISSUE THREAD

**Issue by brat002** [iNavFlight/inav#58]
Could you add position hold as configurable action on failsafe event?

**Comment by digitalentity** [comment]
Current upcoming task is RTH on failsafe event. Why would you want poshold on lost radio?

**Comment by brat002** [comment]
In LOS or near by LOS conditions you can restore control just by antenna alignment. No need RTH for all. Automatic RTH may be dangerous on long ranges with many building and trees.
As proposal - fire PH for failsafe on "configurable timeout seconds" and then RTH. It will be safe for most.

Maybe auto landing in RTH mode will be good solution also.

**Comment by digitalentity** [comment]
Interesting idea. I'll consider entering poshold for some time (configurable) and then execute normal RTH sequence.

**Comment by MauroMombelli** [comment]
Instead of timing, if battery status can be estimated I would use that.
Also a "soft landing in place" option may be useful.

**Comment by digitalentity** [comment]
Thanks for the idea. First of all we need to get RTH working reliably, then go for advanced failsafe mechanisms.

**Comment by digitalentity** [comment]
RTH on RX signall loss is working now (tested)
