### ISSUE TITLE
2.5-RC2 Reversible Throttle Not Going to Full Power

### ISSUE THREAD

**Issue by KenImhof** [iNavFlight/inav#5802]
## Current Behavior

When throttle is reversed, throttle only goes to 1150ms and not to full reverse power of 1000ms.

## Steps to Reproduce

1. Erase and flash 2.5-RC2
2. Enable Reversible Motor Mode
3. Set max_throttle = 2000 to get fully positive throttle

## Expected behavior

From the motor output window, motors should go to 2000ms with full positive throttle and 1000ms at full reverse throttle, but reverse throttle only goes to 1150ms.

## Suggested solution(s)

Problem is the generateThrottleCurve is using a minThrottle of around 1150 with the added idle percentage.  One solution is to use motorConfig()->mincommand as the min_throttle has been removed from this version.

**Comment by KenImhof** [comment]
This change will also address #1879 .

**Comment by DzikuVx** [comment]
With #6030 `throttle_idle` can now be set to `0` what allows full output from `min_command` to `max_throttle`
