### ISSUE TITLE
Strange Magnetometer/compass behavior with F722-PX.

### ISSUE THREAD

**Issue by timothyavid** [iNavFlight/inav#5803]
## Current Behavior
Strange Magnetometer/compass behavior with F722-PX.
I can not get any compass to work with my F722-px.

As the quadcopter rotates the difference between its real rotations and the recorded magnetic position get more and more mismatched, It also seems to drift around sometimes.

1. I have tried every compass angle.
2. Calibrated about 30 times inside and outside.
3. Tried reflashing the board with 2.4 and 2.5 -  4 times. {Full chip erase}
4. Tried a Matek M8Q-5883 and a BN880 - same problem.
5. Moved GPS module away from anything metal on the quadcopter.

This is what is happening:
https://imgur.com/ClfWx8m
https://imgur.com/DrcTJdO

## Additional context
There are 45 IC2 errors when connected to the configurator, is this important?
CLI DUMP https://pastebin.com/iFXEpevy
Wiring: http://www.mateksys.com/wp-content/uploads/2020/01/F722-PX_wiring2.jpg

---
# version
# INAV/MATEKF722PX 2.5.0 May 26 2020 / 12:47:41 (d84bcb733)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by timothyavid** [comment]
I have been trying to solve this for 2 days :-(      I'm at my wits' end!

**Comment by giacomo892** [comment]
I have compass and GPS running on my F722PX without troubles.
It's likely you have alignment issues and interference.

**Comment by timothyavid** [comment]
> I have compass and GPS running on my F722PX without troubles.
> It's likely you have alignment issues and interference.

I found it was been caused by my GPS been at a  -20 degree pitch angle.

Can I tell inav my gps/compass is tilted?

**Comment by giacomo892** [comment]
In CLI:
align_board_roll 
align_board_pitch 
align_board_yaw

Next time do not open an issue here but contact the community on telegram or facebook

**Comment by timothyavid** [comment]
> In CLI:
> align_board_roll
> align_board_pitch
> align_board_yaw
> 
> Next time do not open an issue here but contact the community on telegram or facebook

Thanks,

Won't align_board change the FC alignment?

**Comment by brainbubblersbest** [comment]
Mag_align_xxx would be the thing. Just to clear it out
