### ISSUE TITLE
Inav mavlink version

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#5805]
What version of mavlink is inav using?

Is it v1 or v2 or some hybrid?

**Comment by Beardyblair** [comment]
It will talk to either version.

**Comment by wx4cb** [comment]
> It will talk to either version.

that's not what i asked 😄 i was testing some firmware that pulls the mavlink feed but it turns out it was the firmware that i was given to test, it was only supporting version 2 of mavlink and was just ignoring version 1 sentences. the supplier fixed that so now it works.

but to answer the OP, it's version 1.
