### ISSUE TITLE
Sp racing F3  ， cannot burn the inav firmware（STM32 - timed out, programming: FAILED）

### ISSUE THREAD

**Issue by medib2** [iNavFlight/inav#5810]
Sp racing F3  ， cannot burn the inav firmware（STM32 - timed out, programming: FAILED）
![微信图片_20200605091345](https://user-images.githubusercontent.com/28833105/83843021-bd0c6480-a736-11ea-8794-67470c9832f1.jpg)

**Comment by medib2** [comment]
Although the verification failed，it still can connect to the computer  ,  operate the motor and servos.

**Comment by medib2** [comment]
For  the same  sp racing F3,  now I can burn  any firmware correctly using  inav-1.7.3,  but  editions newer than 1.7.3 can not work.

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/86816436-193f0d00-c084-11ea-9f3c-d6acb1e12446.png)

I was able to flash with Recovery procedure descibed in Configurator.

**Comment by medib2** [comment]
Thanks
