### ISSUE TITLE
Modes documentation for other thins than planes

### ISSUE THREAD

**Issue by brunofporto** [iNavFlight/inav#5813]
## Current Behavior
The modes documentation is very good and clear about planes. But nothing about multi-copters or other types of vehicles. I would add myself the information but the issue is that I really do not know it yet.

## Desired Behavior
Have a description of the expected behavior or compatibility of the modes for other vehicles other than planes.

## Suggested Solution
Write a quick and simple description of each, and if they are compatible, and how to use them. Then we can add to it later :)

## Who does this impact? Who is this for?
Everyone not flying a plane

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav/wiki/Modes applies to both FW and MR
