### ISSUE TITLE
Matek 722SE Sbus not working

### ISSUE THREAD

**Issue by UnCorpuscler** [iNavFlight/inav#5821]
went from 2.4 to 2.5 and it can no longer communicate with my r9mm, reverted to 2.4 to confirm this and is working properly.

**Comment by digitalentity** [comment]
Can't reproduce. Please flash with full erase and reconfigure.

**Comment by DzikuVx** [comment]
I have 2 quads with this FC, both with SBUS and INAv 2.5. On both works without any problems

**Comment by UnCorpuscler** [comment]
I just reproduced this on the matek F405SE as well, same deal, flash 2.5 no channel response, flash 2.4, back to normal.  I can make a video if you would like.

**Comment by digitalentity** [comment]
As advised in the release notes, you should flash with full erase. I also have F405-WING and S.Bus works perfectly

**Comment by UnCorpuscler** [comment]
@digitalentity I thought that was obvious, I do that on every flash. I’m tellin ya mate I’m not dull, if I leave everything as is and flash 2.5 there’s nothing. However because no one else is getting this, I will leave it be.

**Comment by digitalentity** [comment]
@UnCorpuscler this is interesting. It's not the first time FrSky is breaking S.Bus compatibility. Can you try with another receiver, i.e. XM+?
