### ISSUE TITLE
Crash burnout Matek Wing F405, anyone knows why ?

### ISSUE THREAD

**Issue by Bogdanu2018** [iNavFlight/inav#5830]
Hello,
Recently had this crash with the Matek Wing F405 FC.
Anyone experienced similar ? What should be checked ?

https://youtu.be/gIjLotWO3og

Thanks

- FC Board name and vendor: Matek Wing F405
- INAV version string: 2.4

**Comment by DzikuVx** [comment]
This looks like electical failure or voltage going too low for LDO to provide stable voltage for the CPU. There was a 70A current draw and voltage dopped below 3.5V per cell already
