### ISSUE TITLE
Doesn't detect gyro and accell

### ISSUE THREAD

**Issue by FFF200** [iNavFlight/inav#5835]
OMNIBUS F4 Nano V6
Target: Firework V2

INav 2.0-2.4 works well.
INav 2.5 - does not define an accelerometer and gyro.
In Configuration, resets it to NONE.
Manual selection doesn't help.
In the upper panel, accel and gyro are lit red.
Flash witch full chip erase.

![image](https://user-images.githubusercontent.com/55140942/84197382-82922700-aaaa-11ea-9b0a-614d7d133bc7.png)

![image](https://user-images.githubusercontent.com/55140942/84197456-9f2e5f00-aaaa-11ea-86ee-da338515cfaa.png)

![image](https://user-images.githubusercontent.com/55140942/84197486-ac4b4e00-aaaa-11ea-9842-59302a86a011.png)

Set manually. Does not work.

![image](https://user-images.githubusercontent.com/55140942/84197522-bf5e1e00-aaaa-11ea-80d5-bf941b95e68b.png)

![image](https://user-images.githubusercontent.com/55140942/84197549-cc7b0d00-aaaa-11ea-9fc5-503ce531a662.png)

Again I flash with full Erase **iNav 2.4** - and everything works.
On iNav 2.2, I flew safely on this setup until I decided to upgrade to 2.5 to get new filters.

iNav 2.4-immediately after the firmware:

![image](https://user-images.githubusercontent.com/55140942/84197966-7d81a780-aaab-11ea-8940-50126500c93b.png)

# diff

# version
# INAV/FIREWORKSV2 2.5.0 Jun  7 2020 / 11:10:57 (694767938)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# start the command batch
batch start

# resources

# mixer

# servo mix

# servo

# logic

# gvar

# gf

# feature

# beeper

# map

# serial

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout

# master
set looptime = 500
set gyro_sync = OFF
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 110
set gyro_lpf_type = PT1
set dynamic_gyro_notch_enabled = ON
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 120
set acc_hardware = MPU6000
set mag_hardware = QMC5883
set baro_hardware = BMP280
set pitot_hardware = NONE
set applied_defaults = 2
set mc_airmode_type = THROTTLE_THRESHOLD

# profile
profile 1

set mc_p_pitch = 44
set mc_i_pitch = 75
set mc_d_pitch = 25
set mc_i_roll = 60
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_hz = 110
set dterm_lpf_type = PT1
set dterm_lpf2_hz = 170
set dterm_lpf2_type = PT1
set use_dterm_fir_filter = OFF
set dterm_setpoint_weight =  0.750
set d_boost_factor =  1.500
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_yaw_expo = 70
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# battery_profile
battery_profile 1

# end the command batch
batch end

**Comment by FFF200** [comment]
The main and only gyroscope is not defined...

In iNav 2.4, it was registered separately, there is no description of it here, or rather it stands as secondary in the conditions target = FIREWORKS V2

![image](https://user-images.githubusercontent.com/55140942/84257686-662fd200-ab1e-11ea-997b-d3529ac56be5.png)

**Comment by digitalentity** [comment]
Interesting. This change was tested on FIREWORKS V2 board. Can you please post output of the status and version command from 2.4.0 ?

**Comment by FFF200** [comment]
Please write what you need to output.
I will do.

Now I will compile the firmware with my changes, check it in the evening and test it. But it will only be for the OMNIBUS F4 Nano V6.
In IMU_1, I will write the MPU6000 parameters from iNav 2.4

In 2.4, there was an explicit definition of MPU6000 and it worked.
In 2.5, it was removed and compatibility with OMNIBUS F4 Nano V6 by Target disappeared.

**Comment by FFF200** [comment]
status and version - ОК.
I'll write this evening.

**Comment by FFF200** [comment]
I'll test it tonight:

```
#if defined(OMNIBUSF4V6)
#   define IMU_1_CS_PIN            PA4
#   define IMU_1_SPI_BUS           BUS_SPI1
#   define IMU_1_ALIGN             CW180_DEG
#   define IMU_2_CS_PIN            PC14
#   define IMU_2_SPI_BUS           BUS_SPI1
#   define IMU_2_ALIGN             CW0_DEG
#else
    // FIREWORKS V2 - only for OMNIBUS F4 Nano V6
#   define IMU_1_CS_PIN            PA4			// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_1_SPI_BUS           BUS_SPI1		// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_1_ALIGN             CW180_DEG	// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_2_CS_PIN            PC14  		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#   define IMU_2_SPI_BUS           BUS_SPI1		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#   define IMU_2_ALIGN             CW0_DEG		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#endif
```

**Comment by FFF200** [comment]
2.4

`# version 
# INAV/FIREWORKSV2 2.4.0 Feb 11 2020 / 22:09:19 (bcd4caef9)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

# status
System Uptime: 179 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.51V (1S battery - NOT PRESENT)
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
Stack size: 6144, Stack address: 0x10010000, Heap available: 1928
I2C Errors: 0, config size: 5705, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 4, cycle time: 503, PID rate: 1988, RX rate: 49, System rate: 9
Arming disabled flags: COMPASS ACC RX CLI
`

**Comment by FFF200** [comment]
and 2.5

# version
# INAV/FIREWORKSV2 2.5.0 Jun  7 2020 / 11:10:57 (694767938)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# status
System Uptime: 18 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.51V (1S battery - NOT PRESENT)
CPU Clock=168MHz, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=NONE, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
Stack size: 6144, Stack address: 0x10010000, Heap available: 1948
I2C Errors: 0, config size: 5803, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 8, cycle time: 103, PID rate: 9708, RX rate: 49, System rate: 9
Arming disabled flags: ANGLE CAL COMPASS HWFAIL RX CLI
VTX: band: A, chan: -, power: / (60 mW)

**Comment by FFF200** [comment]
and my test fix 2.5

my fix (branch) works!

![image](https://user-images.githubusercontent.com/55140942/84290205-11a34b80-ab4c-11ea-8b87-73f10b8c886f.png)


`# version
# INAV/FIREWORKSV2 2.5.1 Jun 10 2020 / 18:50:38 (839a87739)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# status
System Uptime: 127 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.52V (1S battery - NOT PRESENT)
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
Stack size: 6144, Stack address: 0x10010000, Heap available: 1928
I2C Errors: 0, config size: 5775, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 2, cycle time: 502, PID rate: 1992, RX rate: 49, System rate: 9
Arming disabled flags: COMPASS ACC RX CLI
VTX: band: A, chan: -, power: /
`

`#if defined(OMNIBUSF4V6)
#   define IMU_1_CS_PIN            PA4
#   define IMU_1_SPI_BUS           BUS_SPI1
#   define IMU_1_ALIGN             CW180_DEG
#   define IMU_2_CS_PIN            PC14
#   define IMU_2_SPI_BUS           BUS_SPI1
#   define IMU_2_ALIGN             CW0_DEG
#else
    // FIREWORKS V2 - only for OMNIBUS F4 Nano V6
#   define IMU_1_CS_PIN            PA4			// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_1_SPI_BUS           BUS_SPI1		// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_1_ALIGN             CW180_DEG	// OmnibusF4 Nano v6 and OmnibusF4 V6 has a MPU6000
#   define IMU_2_CS_PIN            PC14  		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#   define IMU_2_SPI_BUS           BUS_SPI1		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#   define IMU_2_ALIGN             CW0_DEG		// replaced from OMNIBUSF4V6, does not interfere with work, tested flashing OMNIBUSF4V6  
#endif`

**Comment by FFF200** [comment]
Please tell me how to change the Current sensor to RX4 ?

To solder an external current sensor to it.

In Target only:
#define CURRENT_METER_ADC_CHANNEL ADC_CHN_1

**Comment by digitalentity** [comment]
From where did you get `#define IMU_2_CS_PIN PC14` ? This will break actual Fireworks V2 board.

**Comment by FFF200** [comment]
Yes, I did for the Omnibus F4 Nano V6 (target Fireworks). Test.

![image](https://user-images.githubusercontent.com/55140942/84295701-9776c500-ab53-11ea-8113-c66f79e069f9.png)

Since I don't know how to combine them both.
Inav 2.4 did not use _IMU_ and there was an override for MPU6000:

![image](https://user-images.githubusercontent.com/55140942/84296468-ba55a900-ab54-11ea-9196-99a720fc1494.png)

I also tried to flash 2.5 target OmnibusF4V6, and it has the same parameters and the accelerometer worked:

![image](https://user-images.githubusercontent.com/55140942/84296866-5384bf80-ab55-11ea-9be9-cdaae5e1577d.png)

In 2.4, the OMNIBUSF4V6 or Fireworks selection block (including my Omnibus nano) only defined the MPU6500.

MPU6000 was defined below for all. And everything worked.

In 2.5, the selection block defines both accelerometers rigidly, but this is not suitable for Omnibus nano, since the first one is MPU6000 on PA4 BUS_SPI1 - like OMNIBUSF4V6.

It is necessary to either return the definition scheme as in 2.4 or enter a new Target for Omnibus nano, which is probably unnecessary.

**Comment by AlexAlle2020** [comment]
I have the same problem on this controller. Sadness.

**Comment by digitalentity** [comment]
Fixed by #5838, will go live in 2.5.1 patch release

**Comment by FFF200** [comment]
Temporary solution.
CLI: set gyro_to_use = 1

**Comment by digitalentity** [comment]
Fix verified on Omnibus F4 Nano V6

**Comment by markpmasonst** [comment]
I don't believe this is fixed. The final inav 2.5 still has the issue.

**Comment by digitalentity** [comment]
2.5.1 containing the fix is not released yet. Wait for it

**Comment by AlexAlle2020** [comment]
"Temporary solution. CLI: set gyro_to_use = 1"  Did it and it works. How reliable is this solution, can I fly far?

**Comment by FFF200** [comment]
A colleague checked and flies. Please note that the gyroscope will need to be turned over in the settings, since the second gyroscope is used from the fireworks.  the fix is not quite correct in version 2.5.1. it will work exactly the same way - with an inverted gyroscope. in omnibus nano, it is located as in omnibusf4. in 2.4, this was taken into account.

**Comment by AlexAlle2020** [comment]
да конечно я перевернул , полетал на коптере пару паков рядом (пару часов) , так вроде все ок . Глвное чтоб гира где то далеко не отвалилась) спасибо.

**Comment by AlexAlle2020** [comment]
I also noticed that the current sensor does not read from the telemetry of the motor regulators, and the video transmitter power is not regulated.

**Comment by FFF200** [comment]
> да конечно я перевернул , полетал на коптере пару паков рядом (пару часов) , так вроде все ок . Глвное чтоб гира где то далеко не отвалилась) спасибо.

Удачи!

**Comment by FFF200** [comment]
> I also noticed that the current sensor does not read from the telemetry of the motor regulators, and the video transmitter power is not regulated.

у меня регуляторы blhelly s без телеметрии. поэтому использую внешний датчик на RX4.

**Comment by FFF200** [comment]
> I also noticed that the current sensor does not read from the telemetry of the motor regulators, and the video transmitter power is not regulated.

I have blhelly s controllers without telemetry. therefore, I use an external sensor on the RX4. I will check the video transmitter control. but the pit stop seems to be working

**Comment by elaugaste** [comment]
Current via ESC telemetry not work on nano v6 :(  on rx4  must connect blheli32 telemetry

**Comment by FFF200** [comment]
Analog current on rx4:

-#define UART4_RX_PIN            PA1
+#define UART4_RX_PIN            NONE

-#define ADC_CHANNEL_1_PIN               PC1
+#define ADC_CHANNEL_1_PIN               PA1

Profit.

**Comment by AlexAlle2020** [comment]
> > да конечно я перевернул , полетал на коптере пару паков рядом (пару часов) , так вроде все ок . Глвное чтоб гира где то далеко не отвалилась) спасибо.
> 
> Удачи!

Я думаю меня простят что пишу на русском языке , в инглише не силен . А боюсь что гугл переведет не верно . OMNIBUS F4 Nano V6 Target: Firework V2, USB смотрит назад  . С выходом Inav 2.5.1  я заметил что все так же аксель надо разворачивать не так как в Inav 2.3.0 положение другое Pitch Degrees 180 , но это не беда , развернул чтоб модель в Inаv конфигураторе вращалась верно . Танцы начались с включением компаса , раньше положение компаса было cw90 flip в inav 2.3.0 и летало все нормально   , но такое положение никак не  подходит для inav 2.5.1  , чтоб моделька в конфигураторе себя вела адекватно ,пришлось поставить MAG AlignmentGPS CW90 .но с таким расположением коптер при удержании точки по ЖПС улетает в китай, компас конечно калибровал по новой  . Я понимаю что проблема в расположении акселя и компаса , но ведь моделька во вкладке Setup ведет себя адекватно . ХЗ куда копать .

**Comment by Dteksolutions** [comment]
I'm having the exact same issue on 5.1.0, 5.0 etc.

**Comment by willyfpv** [comment]
I have the same issue trying to update to 7.1. can you please fix this bug?

**Comment by sensei-hacker** [comment]
> I have the same issue trying to update to 7.1. can you please fix this bug?


If the group and accelerometer aren't detected, that generally means you flashed a target that is not correct for the FC you have.

Please attach a photo of your FC and a screenshot of the top of Configurator, where it shows which target has been flashed.

**Comment by willyfpv** [comment]
i know is the correct target because reverting to 2.0.1 all works perfectly.
btw
![photo_2024-12-08_20-55-07](https://github.com/user-attachments/assets/de9e2297-b8f4-4cc8-9122-99cc925691bf)
![photo_2024-12-08_20-55-03](https://github.com/user-attachments/assets/efdd0a00-a0f1-42d5-a45e-060d90665841)
ad the status command on cli report this:

INAV/FIREWORKSV2 7.1.2 May 31 2024 / 22:08:14 (4e1e59eb)
GCC-10.3.1 20210824 (release)
System Uptime: 21 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.03V (0S battery - NOT PRESENT)
CPU Clock=168MHz, BARO=BMP280
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=NONE, MAG=NONE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
Stack size: 6144, Stack address: 0x10010000, Heap available: 1648
I2C Errors: 0, config size: 10253, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 54, cycle time: 1015, PID rate: 985, RX rate: 9, System rate: 9
Arming disabled flags: ANGLE CAL HWFAIL RX CLI
OSD: MAX7456 [30 x 16]
VTX: band: A, chan: 2, power: 1 (25 mW), freq: 5845 MHz

**Comment by willyfpv** [comment]
thank you for the support!!!

**Comment by sensei-hacker** [comment]
@willyfpv 
You posted in an old thread about the Nano V6, saying you have the same FC. Which works fine with INAV 7.2.1 - I have one right here.

When I asked for a picture of your board, you posted the instruction sheet for a Fireworks V2.

Please post a pic of YOUR FC.
I can't make your FC work without knowing what YOU have. A Fireworks V2 is not the same board board as a Nano V6, is not the same as Nano V7, is not the same as an Omnibus V5.

**Comment by sensei-hacker** [comment]
For reference, here's what I mean.
Here are pics of my Nano V6 rev 2. (Running INAV 7.1.2).

![IMG_20241208_151418246](https://github.com/user-attachments/assets/4fbb314c-c4bc-4010-8c05-1d2185253326)

![IMG_20241208_151409915](https://github.com/user-attachments/assets/b8836ad4-1c58-4ebb-a33f-fb61ebef4719)

**Comment by willyfpv** [comment]
> @willyfpv You posted in an old thread about the _Nano V6_, saying you have the same. (Which works fine with INAV 7.2.1 - I have one right here).
> 
> When I asked for a picture of your board, you posted the instruction sheet for a _Fireworks V2_.
> 
> Please post a pic of YOUR FC. I can't make your FC work without knowing what YOU have. A Fireworks V2 is not the same board as a Nano V6, is not the same as Nano V7, is not the same as an Omnibus V5. Please post a good pic of YOUR flight controller.
> 
> Thank you.

I'm so sorry,my bad ,my FC IS THE V2,the one in the instructions sheet.
I cannot post a real pic because is inside a FUNJET under a vtx.
I mistakenly thought that the target was the only thing that was important.
I'm new to interacting in the thread of GitHub🙏so sorry

**Comment by sensei-hacker** [comment]
> I'm so sorry,my bad ,my FC IS THE V2,the one in the instructions sheet. I cannot post a real pic because is inside a FUNJET under a vtx. I mistakenly thought that the target was the only thing that was important. I'm new to interacting in the thread of GitHub🙏so sorry

Okay, likely you will have better luck if you go into the Configuration tab of Configurator and select MPU6000 for your accelerometer. The default value of "auto" may also work.  Please let me know if that solves your issue.

If not, we may have to find a way to get a close-up pic of your board - even though that would be a hassle.

**Comment by willyfpv** [comment]
![photo_2024-12-09_18-44-33](https://github.com/user-attachments/assets/fcc06e16-85c5-4a57-a9e4-70513d689ce6)
this is the board.
ive tried your solution but with no luck,
after messing a little around with github i've found a solution that works (only tested on ground )

this commands : 
set gyro_to_use = 1
set acc_hardware = auto
and magically now detects both...any idea why? i want to understand a bit more if you can explain it to me.
THANKS a lot

**Comment by sensei-hacker** [comment]
Glad you got that working.

That's what the manufacturer says to do for a related board, the Omnibus V6:

https://store.myairbot.com/flight-controller/omnibusf4v6.html

I was thinking selecting it on the Configuration tab would have the same effect, but you said you tried that and it didn't.

I've updated the documentation for these boards:
https://github.com/iNavFlight/inav/blob/96078ad1a7bf2aeac48150c7a017ec60f4367c3c/docs/boards/Omnibus%20F4.md

**Comment by willyfpv** [comment]
Thank you for the bottom of my heart for the patience and the support in resolving this
Has been a pleasure meeting you.
Thank you
