### ISSUE TITLE
The drone does not start in inav 2.5

### ISSUE THREAD

**Issue by shakalby** [iNavFlight/inav#5840]
iNav 2.5 does not run the drone and commands from the remote control do not work, the remote Radiolink AT 10 ii, the minimum value of sticks and toggle switches 1071 below is not done, in inav 2.4.1 everything worked

**Comment by digitalentity** [comment]
We need more information. What exactly doesn't work? Configuration diff?

**Comment by Seeelefant** [comment]
I kind of have the same problem.
[inav_data_log.zip](https://github.com/iNavFlight/inav/files/4767246/inav_data_log.zip)

**Comment by shakalby** [comment]
> We need more information. What exactly doesn't work? Configuration diff?

the problem is that the drone does not start the engines!!! the problem is that the firmware sees that the lower position of the sticks is 1071, will the remote be calibrated in the future as in ardupilot or as in tarot zyx m??? The problem was solved as follows, in the remote control there is a setting You need to turn the END POINT in the remote

**Comment by Seeelefant** [comment]
Well, after starting the motors they simply stop after some seconds. I am simply not able to take off.
My diff is as follows:

Entering CLI Mode, type 'exit' to return, or 'help'

# diff

# version
# INAV/KAKUTEF7 2.5.0 Jun  7 2020 / 10:53:28 (694767938)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# start the command batch
batch start

# resources

# mixer

mmix reset

mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mix
smix reset

smix 0 0 18 100 0 -1
smix 1 1 18 100 0 -1

# servo

# logic

# gvar

# gf

# feature
feature GPS
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 4096 115200 115200 0 115200
serial 2 2 115200 115200 0 115200
serial 3 32 115200 115200 0 115200

# led

# color

# mode_color

# aux
aux 0 0 4 1500 2100
aux 1 1 0 900 1400
aux 2 3 0 1200 1375
aux 3 11 0 1375 1550
aux 4 11 6 1800 2100
aux 5 10 0 1600 1800
aux 6 46 6 1750 2100
aux 7 13 5 1300 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 26 1 V
osd_layout 0 1 13 1 V
osd_layout 0 2 0 0 V
osd_layout 0 7 13 14 V
osd_layout 0 9 0 3 V
osd_layout 0 10 22 4 V
osd_layout 0 11 1 4 V
osd_layout 0 12 0 5 V
osd_layout 0 14 0 14 V
osd_layout 0 15 0 1 V
osd_layout 0 20 18 12 V
osd_layout 0 21 0 12 V
osd_layout 0 22 14 11 V
osd_layout 0 23 24 3 V
osd_layout 0 24 12 2 V
osd_layout 0 28 23 14 V
osd_layout 0 30 2 13 V
osd_layout 0 31 24 11 V
osd_layout 0 34 9 3 V
osd_layout 0 37 1 6 V
osd_layout 0 38 1 7 V
osd_layout 0 41 8 11 V
osd_layout 0 42 17 11 V
osd_layout 0 48 23 7 V
osd_layout 0 105 26 5 V

# master
set looptime = 250
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 115
set gyro_lpf_type = PT1
set gyro_stage2_lowpass_type = PT1
set dynamic_gyro_notch_enabled = ON
set dynamic_gyro_notch_q = 200
set dynamic_gyro_notch_min_hz = 140
set acc_hardware = MPU6000
set acczero_x = 35
set acczero_y = -17
set acczero_z = -210
set accgain_x = 4072
set accgain_y = 4073
set accgain_z = 4050
set align_mag = CW270FLIP
set mag_hardware = HMC5883
set magzero_x = 63
set magzero_y = -146
set magzero_z = -61
set baro_hardware = BMP280
set pitot_hardware = NONE
set min_check = 1050
set motor_pwm_protocol = DSHOT600
set throttle_idle =  11.000
set failsafe_procedure = RTH
set bat_voltage_src = SAG_COMP
set model_preview_type = 3
set applied_defaults = 2
set gps_provider = UBLOX7
set gps_sbas_mode = EGNOS
set mc_airmode_type = THROTTLE_THRESHOLD
set nav_use_midthr_for_althold = ON
set nav_user_control_mode = CRUISE
set osd_video_system = PAL
set vtx_band = 1
set vtx_channel = 2
set vtx_power = 2
set vtx_low_power_disarm = ON

# profile
profile 1

set mc_p_pitch = 26
set mc_i_pitch = 60
set mc_d_pitch = 28
set mc_p_roll = 22
set mc_i_roll = 50
set mc_d_roll = 24
set mc_p_yaw = 44
set mc_i_yaw = 70
set dterm_lpf_hz = 110
set dterm_lpf_type = PT1
set dterm_lpf2_hz = 170
set dterm_lpf2_type = PT1
set use_dterm_fir_filter = OFF
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.850
set d_boost_factor =  1.500
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set rc_yaw_expo = 70
set roll_rate = 85
set pitch_rate = 85
set yaw_rate = 75

# battery_profile
battery_profile 1

set bat_cells = 4
set battery_capacity = 2200
set battery_capacity_warning = 550
set battery_capacity_critical = 330

# end the command batch
batch end

**Comment by Beardyblair** [comment]
I had this in angle mode, acro or horizon arm fine. Matek fF722-PX   FW 2.5.0

**Comment by shakalby** [comment]
The problem was solved as follows, in the remote control there is a setting You need to turn the END POINT in the remote

**Comment by Seeelefant** [comment]
Hi shakalby, can you add a little explaination on that? Which END POINT do I have to adjust?
