### ISSUE TITLE
Extra sensor protocol and connection.

### ISSUE THREAD

**Issue by driver33** [iNavFlight/inav#5846]
## Current Behavior
There is no possibilty od adding extra sensor for telemetry for example tachometer for gas engines, temerature of head(s), etc.  Creatiing such sensor based on arduino is  not a big deal.

## Desired Behavior
Read data from sensor and put them into telemetry. 

## Suggested Solution
Create simple protocol maybe on I2C bus which allows you to send data to FC. 
On the FC side create simple mapping sensor form I2C to sensor in telemetry depends which telemetry you use.

Possible solution example using ardunio with tachometer and 2 thermometers  (I use such configuration in my planes)

1. aruino has his own I2C arddess. 
2. sensors are numbers 1(RPM), 2(Temp), 3(Temp).
3. each sensor is send in frame [start],[number],[value],[stop] (its just an idea)
4. mapping in FC will allows you to map sensor number to telemetry name.
4a. Maybe mapping shall also allows you to extra sensor not mentioned on the list nor in telemetry? 
5. List of possible sensors in telemetry shall be taken from telemetry sensor list.

This idea comes because F.Port creation. I think it's not possible to "inject" extra sensor as I do now on S.Port. Injection is that FC and arduino works parrallel on the S.Port wire.
Additionally anyone will be able to create his own, not predefined sensors.

**Comment by Kai2510** [comment]
Adding a way to transport or merely log extra sensor data is really useful for doing researches. All it needs is to get the received data (i2c or USART) forwarded and incorperated to telemetry or log. 
For example, DIY AOA/AOS sensors (who would send angle data to controller board), DIY tachometers (hall effect sensor or light sensor), force sensors, etc. 
And for using the data to control... Just leave it to future development.
