### ISSUE TITLE
Elevon deflections very small. Is this OK?

### ISSUE THREAD

**Issue by rsilk1949** [iNavFlight/inav#5849]
I believe I am ready for the maiden flight with the Dart 250g (flying weight 250 gm), running iNav 2.4 on a Matek 41S board.
When checking for correct deflection (nose up/down, roll right/left) the up/down directions look correct in manual, acro and angle mode.

However, when using the radio, the maximum deflection angle is very different with each of the 3 modes.
Manual looks like it is fine -- deflects around  +/- 5mm
Acro deflects around +- 2mm
Angle deflects around +- 1mm

Is this normal?

Also when moving the model around  (nose up/down, roll right/left) in angle mode, the max deflection is again only +- 1mm.

**Comment by DzikuVx** [comment]
https://youtu.be/o2RwTeBbvos

pt., 12 cze 2020, 19:17 użytkownik issue-label-bot[bot] <
notifications@github.com> napisał:

**Comment by rsilk1949** [comment]
Many tx for highlighting the video which explains everything. I will test after arming (prop off).

If these tips and tricks videos were placed in 1 or more youtube playlists and well advertised on the inav wiki, this knowledge base would be much more accessible.

**Comment by rsilk1949** [comment]
Many tx for highlighting the video. I will test after arming -- props off ;)
