### ISSUE TITLE
Logging for Changes?

### ISSUE THREAD

**Issue by Kleinerben** [iNavFlight/inav#5856]
## Current Behavior
Everytime when something is changed in the config, a diff /all is needed to save the previous settings or i need to write it down which things i´ve changed. 

## Desired Behavior
A "Change - History - Tab" would be great. Which logs the Changes, the previous value and maybe the date. If its not possible to generate this automatically even a "Notepad - Tab" would be great, where i can write the changes and the date in manually. 

## Suggested Solution
Build in a tab in the configurator. Tracking the changes automatically would be insane, but even just a "Notepad" - function would help.

## Who does this impact? Who is this for?
All INAV - Users.. but also other flight software doesnt have this feature.

## Additional context
Sometimes... especially in the fine tuning, for althold, positionhold, rth etc, i try to change different values. There are a lot. At the end maybe i wanna set a value back to the default. But then i will have to remember which value i´ve changed, and there are many vaules which doesnt apper in the Tabs just in the CLI. I guess this is very helpful especially for those who are not deep into these variables and their meaning. 

Or maybe i can make a note what the variable is for.

**Comment by digitalentity** [comment]
Not possible, we don't have memory for storing a journal of changes
