### ISSUE TITLE
inav-2.5.1.zip - 2.6.0 inside

### ISSUE THREAD

**Issue by dsaboot** [iNavFlight/inav#5861]
I've download inav-2.5.1.zip and compile it with my "target fix" for full duplex serial port support.
But in output I've recieved inav_2.6.0_MATEKF411SE.hex instead of inav_2.5.1_MATEKF411SE.hex
So configurator don't want to work with 2.6.0 firmware :-D

**Comment by digitalentity** [comment]
check out the `release_2.5.1` branch  with git

**Comment by dsaboot** [comment]
Thanks for advice! Now it's ok!
