### ISSUE TITLE
Jeti duplex telemetry does not work ...

### ISSUE THREAD

**Issue by Turtletrumpet** [iNavFlight/inav#5868]
Hello,

i use a Matek F405 wing flight controller with a Jeti Duplex dc16. for the receiver i use the UART2 with RX2/TX2 and as protocol jetiexbus. The servo deflections seem to be transmitted correctly, but unfortunately the telemetry data transmission is missing.
I have a 2.2kOhm resistor between rx2 and tx2, but this did not improve anything.
If you need more information, please ask.
I hope you can help me.

regards,

Turtle

**Comment by Turtletrumpet** [comment]
Ooops, I forgot to mention that I am using the current version 2.5.1 of iNav.

**Comment by RoadyFPV** [comment]
thats true, i started a request for implementation of the optimized code. #4711

**Comment by Turtletrumpet** [comment]
Hello,
is there any new information in the meantime, when the telemetry for Jeti will work?
Thanks!

regards,

Dirk

**Comment by RoadyFPV** [comment]
I don't know exactly. But it is being worked on.

**Comment by Turtletrumpet** [comment]
Is there a new version to test available?
