### ISSUE TITLE
DAC (RunCam) Control

### ISSUE THREAD

**Issue by chrisman92** [iNavFlight/inav#5869]
## Current Behavior
DAC pad on Matek F405 AIO FC not supported

## Desired Behavior

support for DAC pad on Matek F405 AIO FC

## Suggested Solution
Mimic DAC control configuration from Betaflight (I’m sure that’s easier said than done)

## Who does this impact? Who is this for?
All users with RunCam FPV camera containing an OSD pin and no TX/RX along with a flight controller with DAC pads.

## Additional context
This would be very helpful as pilots can use the simple transmitter stick combination to adjust camera setting without yet again, “an extra piece of equipment.”

@DzikuVx , would really like the opportunity to work with you and team to help the overall INAV experience easier for all.  Please let me know if there’s anything else I can do to help/contribute to our hobby.

**Comment by P-I-Engineer** [comment]
i would like this also on the matek F405 CTR.

would cherry picking it from betaflight work?
