### ISSUE TITLE
Turtle Mode

### ISSUE THREAD

**Issue by chrisman92** [iNavFlight/inav#5870]
## Current Behavior
No “Flip over after crash mode” if quad lands upside down

## Desired Behavior
Allow turtle mode mode

## Suggested Solution
Copy Betaflight configuration

## Who does this impact? Who is this for?
Anyone running inav that flips their quad over accidentally

## Additional context
Although primarily tailored to “freestyle pilots, even if flying cinematically and you accidentally hit a tree and flip over (yes this has happened to me), this would be extremely handy.

**Comment by digitalentity** [comment]
Duplicate of #5126
