### ISSUE TITLE
Brushless motor rc rocket vertical landig

### ISSUE THREAD

**Issue by clementpeleman** [iNavFlight/inav#5878]
Hi, i am planning on building a brushless motor rc rocket. I only want to use **1** motor and control it with 2/4 fins fitted with servo's on them. I think the take off would not be that hard to pull off but i want it to land back vertically. Is it possible to invert the servo output mid flight? So when i go into a freefall, the servo's correct for **the bottom to stay down**. I would also add some friction flaps.

**Comment by DzikuVx** [comment]
Yes, it is possible to prepare 2 sets of servo rules in the mixer and then switch between then using logic conditions.
1. Prepare 2 Logic conditions activated by a switch. One of ascend, one for descend
2. Prepere set of smix rules for ascent active when one of LC is true
3. Prepare second set of rules that will take over when othe LC is active
