### ISSUE TITLE
Global Variables not incrementing correctly with logic conditions.

### ISSUE THREAD

**Issue by nik012003** [iNavFlight/inav#5883]
## Current Behavior

![Screenshot 2020-06-24 at 18 56 56](https://user-images.githubusercontent.com/10795335/85599265-a4fc7680-b64c-11ea-9622-94f54a3830c1.png)
As you can see from this screenshot I've set the global variable 0 to increment, but global var 1 increments.
This happens both on 2.5.1 and 2.6.0. Omnibus F4 Pro v3

## Steps to Reproduce
1. paste this in the cli :

```
logic 0 1 -1 5 1 7 0 0 0
logic 1 1 0 3 5 0 0 899 0
logic 2 1 1 19 5 0 0 50 0
logic 3 1 -1 12 1 7 0 0 0
logic 4 1 -1 1 5 0 0 0 0
logic 5 1 -1 7 4 3 4 4 0
logic 6 1 5 20 5 0 0 50 0
logic 7 0 -1 0 0 0 0 0 0
logic 8 0 -1 0 0 0 0 0 0
logic 9 0 -1 0 0 0 0 0 0
logic 10 0 -1 0 0 0 0 0 0
logic 11 0 -1 0 0 0 0 0 0
logic 12 0 -1 0 0 0 0 0 0
logic 13 0 -1 0 0 0 0 0 0
logic 14 0 -1 0 0 0 0 0 0
logic 15 0 -1 0 0 0 0 0 0
```

dump : [https://pastebin.com/51FmwHTM](https://pastebin.com/51FmwHTM)

CLI 'version' command : INAV/OMNIBUSF4V3 2.5.1 Jun 16 2020 / 12:32:45 (098a574b3) GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

- FC Board name and vendor: OmnibusF4 v3 (Chinese clone)
- INAV version string: 2.5.1 and 2.6.0

**Comment by DzikuVx** [comment]
It's not a bug. Operand "Global Variable" means: value currently stored in a GVAR.
Your GVAR 0 holds `1`. 
When `GVAR INC - Global Variable 0 - Value 1` it evaluates as:

Increase the value of GVAR with index stored GVAR 0 by a value of `1`

To increase the value of GVAR0 you need:
`GVAR INC - Value 0 - Value 1`
