### ISSUE TITLE
INAV 2.5.1 pit mode not activating

### ISSUE THREAD

**Issue by LordGeorge-1992** [iNavFlight/inav#5889]
Hardware

Matek f411-wse
Tbs pro32 Nano

INAV ver: 2.5.1

Issue.
Pit mode does not activate automatically, even when lowest power until first arm is selected.
Pit mode does activate correctly when using the OSD commands.
Any help would be amazing.

Thanks 
George

**Comment by Pairan** [comment]
same on Matek F722 and AKK Race Ranger on iNav v2.5.1

**Comment by 0crap** [comment]
Same here, no PIT mode on a Rush TANK 5.8GHz VTX.
Using iNav 2.6.0 Alfa2, VTX uses TBS SmartAudio V1.
