### ISSUE TITLE
Incredible skyline drift

### ISSUE THREAD

**Issue by dsaboot** [iNavFlight/inav#5890]
## Current Behavior
Today it was really annoying, the horizon angle went 35 degrees or more, the plane simply could not fly in Angle mode, I switch to manuall mode and land, but if it happened far from takeoff and in the return home mode, who knows, it would back or not.
[https://youtu.be/xOhsyCsKXm0](url)
it's already set imu_acc_ignore_rate = 10
![hd](https://user-images.githubusercontent.com/25885270/85948396-5ce59880-b959-11ea-84e0-d4921bb27c01.jpg)

Inav 2.5.1
Matek F411-WING
Wing Z84
PID and filters setting from Z-84 profile (aplyed Z84 profile in configurator)

**Comment by sdfsdf107** [comment]
It seems that this is a know bug.
git checkout remotes/origin/dzikuvx-bno055-secondary-imu

**Comment by dsaboot** [comment]
It's  a know bug - then horizon drift near 10deg, but I have 35-45deg.

**Comment by dsaboot** [comment]
After many tests, with very low freq filter setting, looks ok. Horizon drift not so high, as in past.
