### ISSUE TITLE
CLRACING F4 Target

### ISSUE THREAD

**Issue by maybenikhil** [iNavFlight/inav#5892]
I have the CLRACING F4, which a fully-featured F405 FC (it's the Bardwell FC, which is just a variant of that). Currently there is no INAV target for it.

I was hoping that an INAV target could be added, but I am not sure what that would involve, as Bardwell himself says there is no INAV target. Thank you!

**Comment by digitalentity** [comment]
I like the "Bardwell himself" quote :smile:. Our "new target policy" is available [here](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md#new-target-additions)

There is a `CLRACINGF4AIR`, is the `CLRACINGF4` different and how?
