### ISSUE TITLE
Quadcopter on iNav 2.1.0: flyaway during RTH

### ISSUE THREAD

**Issue by DiscoMan18** [iNavFlight/inav#5893]
Closed the issue. It was totally my fault. Home reset mode was accidentally enabled along with poshold mode.

**Comment by DiscoMan18** [comment]
Anyway please check for a possible bug with RTH mode. It's not working correctly while Home Reset mode is active. Yesterday I got a failsafe while being only 70 meters from takeoff point. The quad ascended to preset RTH altitude, 60 meters in my case, but then started to drift down the wind, flying away from me. On the OSD correct distance and direction to the takeoff point were shown. 

Before failsafe fired, there were two flight modes active: POSHOLD and HOME RESET.

**Comment by stronnag** [comment]
Please reproduce the problem on a contemporary version of inav, 2.1.0 is no longer supported.
