### ISSUE TITLE
Can't free resources

### ISSUE THREAD

**Issue by carlybaby69** [iNavFlight/inav#5901]
I am unable to free resources in iNAV. For example I have the following resource:

B05: LED1 OUT

If I type:

resource LED1 OUT NONE

Then it simply lists out all the resources again as if I had simply typed resource. Expected is that I would see resource is freed message. Target is OmnibusF4V3Pro.

**Comment by stronnag** [comment]
The `resource` command in inav only lists resources and is well documented. This is a feature.

**Comment by DzikuVx** [comment]
There is no resource mapping in INAV

**Comment by tfoutfou** [comment]
@carlybaby69 
you have to make a custom target and compile it

If you give me all the needed parameters i can do it for you if you dont know how

**Comment by carlybaby69** [comment]
Hi,
Thanks! I’ve been making my own custom targets anyway as this board did not have an internal baro. 
I have no more UARTS and want to use Smart Audio therefore want to enable soft serial on the LED instead. If I go to resources I see this:
B05: LED1
I would therefore like to assign this as my soft serial port. The thing I don't understand is when I look at target.h I see the LED defined as:
#define LED0                    PB5
Do what should I be defining soft serial 1 as? The target.h file doesn't seem to map to what I see in resources. Any help appreciated. Thanks!------ 
Original Message ------
On  Saturday, 4 Jul, 2020 At 22:42, tfoutfou<notifications@github.com> 
wrote:


@carlybaby69 <https://github.com/carlybaby69>
  you have to make a custom target and compile it
If you give me all the needed parameters i can do it for you if you dont 
know how
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/iNavFlight/inav/issues/5901#issuecomment-653815698> 
, or unsubscribe

**Comment by tfoutfou** [comment]
it s kind of a mess in the target.h file because there is many version of the board.  and i am not familiar with omnibus board.

LED PB5  is the onbard led indicating the status of the board 
You might want to use the LED STRIP pad right ? wich is PB6

but i would suggest you to use PWM5 pad or PWM6 pad  wich are respectively  PA1 and PA8


in target REMOVE this whole section:

> #if defined(OMNIBUSF4V3) && !(defined(OMNIBUSF4V3_S6_SS) || defined(OMNIBUSF4V3_S5S6_SS) || defined(OMNIBUSF4V3_S5_S6_2SS))
> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PC6     // shared with UART6 TX
> #define SOFTSERIAL_1_TX_PIN     PC6     // shared with UART6 TX
> 
> #define SERIAL_PORT_COUNT       5       // VCP, USART1, USART3, USART6, SOFTSERIAL1
> 
> #elif defined(OMNIBUSF4V3_S6_SS)        // one softserial on S6
> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PA8     // S6 output
> #define SOFTSERIAL_1_TX_PIN     PA8     // S6 output
> 
> #define SERIAL_PORT_COUNT       5       // VCP, USART1, USART3, USART6, SOFTSERIAL1
> 
> #elif defined(OMNIBUSF4V3_S5S6_SS)      // one softserial on S5/RX S6/TX
> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PA1     // S5 output
> #define SOFTSERIAL_1_TX_PIN     PA8     // S6 output
> 
> #define SERIAL_PORT_COUNT       5       // VCP, USART1, USART3, USART6, SOFTSERIAL1
> 
> #elif defined(OMNIBUSF4V3_S5_S6_2SS)    // two softserials, one on S5 and one on S6
> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PA1     // S5 output
> #define SOFTSERIAL_1_TX_PIN     PA1     // S5 output
> 
> #define USE_SOFTSERIAL2
> #define SOFTSERIAL_2_RX_PIN     PA8     // S6 output
> #define SOFTSERIAL_2_TX_PIN     PA8     // S6 output
> 
> #define SERIAL_PORT_COUNT       6       // VCP, USART1, USART3, USART6, SOFTSERIAL1, SOFTSERIAL2
> 
> #else                                   // One softserial on versions other than OMNIBUSF4V3
> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PC8     // pad labelled CH5 on OMNIBUSF4PRO
> #define SOFTSERIAL_1_TX_PIN     PC9     // pad labelled CH6 on OMNIBUSF4PRO
> 
> #define SERIAL_PORT_COUNT       5       // VCP, USART1, USART3, USART6, SOFTSERIAL1
> #endif
> 

and then write :

> #define USE_SOFTSERIAL1
> #define SOFTSERIAL_1_RX_PIN     PA1
> #define SOFTSERIAL_1_TX_PIN     PA1
> 
> #define SERIAL_PORT_COUNT       5


it might do the trick
(in the configuration tab dont forget to enable CPU based Serial Port  , and then configure SmartAudio in the Port Tab for SoftSerial1)

solder SmartAudio wire to PWM5 and test it

**Comment by tfoutfou** [comment]
and to clarify about PB5 vs B05  they are the same

just add a "P" , remove the "0"  and B05 become PB5.

Dont quote me on that but PB5 is the real name for the CPU pin , and B05 is to be presented to the human eye as a more readable format.

because if you have PB1 PB11 PB14 PB8
if you dont put the "0"  the order is  B1 B11 B14 B8
if you put the "0" the order is B01 B08 B11 B14  (classified in numerical order)

**Comment by carlybaby69** [comment]
Thank you. I think I can do this. My board is a strange clone. A '9g 
Omnibus F4 AIO'. The Omnibus F4 V3 Pro target works quite well:



This is fitted in a quad so my free pins are Buz+, Buz -, TX6 (sbus on 
RX6 which I am using) , PPM, LED. What's your recommendation?

Here are my resources:

# resource
IO:
----------------------
A00: FREE
A01: FREE
A02: MOTOR4 OUT
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: FREE
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE
A14: FREE
A15: OSD CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B02: FREE
B03: FREE
B04: BEEPER OUT
B05: LED1 OUT
B06: FREE
B07: SDCARD IN
B08: FREE
B09: FREE
B10: I2C2 SCL
B11: I2C2 SDA
B12: SDCARD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE
C01: ADC CH1
C02: ADC CH2
C03: FREE
C04: MPU EXTI
C05: FREE
C06: SOFTSERIAL1 UART TX/RX
C07: SERIAL6 UART RX
C08: INVERTER OUT
C09: INVERTER OUT
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: FREE
C14: FREE
C15: FREE
D00: FREE
D01: FREE
D02: FREE
D03: FREE
D04: FREE
D05: FREE
D06: FREE
D07: FREE
D08: FREE
D09: FREE
D10: FREE
D11: FREE
D12: FREE
D13: FREE
D14: FREE
D15: FREE


Thanks for your help! Much appreciated!
------ Original Message ------

**Comment by carlybaby69** [comment]
Looks like my resources didn't send:

A00: FREE
A01: FREE
A02: MOTOR4 OUT
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: FREE
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE
A14: FREE
A15: OSD CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B02: FREE
B03: FREE
B04: BEEPER OUT
B05: LED1 OUT
B06: FREE
B07: SDCARD IN
B08: FREE
B09: FREE
B10: I2C2 SCL
B11: I2C2 SDA
B12: SDCARD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE
C01: ADC CH1
C02: ADC CH2
C03: FREE
C04: MPU EXTI
C05: FREE
C06: SOFTSERIAL1 UART TX/RX
C07: SERIAL6 UART RX
C08: INVERTER OUT
C09: INVERTER OUT
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: FREE
C14: FREE
C15: FREE
D00: FREE
D01: FREE
D02: FREE
D03: FREE
D04: FREE
D05: FREE
D06: FREE
D07: FREE
D08: FREE
D09: FREE
D10: FREE
D11: FREE
D12: FREE
D13: FREE
D14: FREE
D15: FREE

------ Original Message ------
