### ISSUE TITLE
DPS310 barometer reports incorrect temperature

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#5925]
Reported by @MATEKSYS.

**Comment by MATEKSYS** [comment]
https://github.com/Infineon/DPS310-Pressure-Sensor#temperature-measurement-issue

**Comment by digitalentity** [comment]
Thanks @MATEKSYS, found that already. #5926 reads temp correctly for me.

**Comment by MATEKSYS** [comment]
![image](https://user-images.githubusercontent.com/23047106/86997624-202f6200-c1e1-11ea-81ea-e0a15b700a15.png)
Baro temp readout is correct now.   Thanks
