### ISSUE TITLE
iNav 2.5.1 Matek F411 Wing Mixer Issue

### ISSUE THREAD

**Issue by mrduncan626** [iNavFlight/inav#5931]
When setting up the Configurator (v2.5.0) Mixer on a Matek F411 Wing (flashed with v2.5.1) as a Nano Talon V-tail, servo’s 3 and 4 are mapped to 4 outputs (S4, S5, S6, and S7).  

Please advise on how to connect the elevon servos to the FC.

![Matek F411 Wing Mixer Issue](https://user-images.githubusercontent.com/8952073/87108148-2e07d600-c227-11ea-8614-06b4ef743fa9.jpg)

**Comment by jreise-d** [comment]
Same here since version 2.4. It seems to be a bug in the configurator, inav runs without an error. See issue in the configurator page https://github.com/iNavFlight/inav-configurator/issues/913

**Comment by mrduncan626** [comment]
Same bug is covered under the configurator issues page as noted above.  Closing this issue.
