### ISSUE TITLE
Disable GPS from OSD

### ISSUE THREAD

**Issue by almumen** [iNavFlight/inav#5932]
## Current Behavior
I was flying my drone and crashed and my GPS failed (HW failure). I wanted to fly without GPS but it did not allow me to Arm.

## Desired Behavior

I am looking for a way to disable GPS (from OSD) so that I can fly like Betaflight whithout GPS when I want even if both compass and GPS have failed without the need to disable them from the configurator.

## Suggested Solution

Add the ability to disable GPS and Compass from OSD. This should allow fpv pilot to fly after a crash which damages the GPS.

## Who does this impact? Who is this for?

It is for any FPV pilot to allow him to fly after crash and enjoy the rest of battery packs.

**Comment by DzikuVx** [comment]
It is possible to arm without GPS fix with yaw stick override

**Comment by almumen** [comment]
Many thanks 😊
