### ISSUE TITLE
Undocumented differential steering for rover / tank

### ISSUE THREAD

**Issue by NestWolfsteiner** [iNavFlight/inav#5935]
## Current Behavior
Initial Rover and Boat support (@DzikuVx)
Starting from version 2.5, INAV supports Rovers and Boats (more general: ground and water vehicles without altitude control with yaw steering only. Remark: tanks and vehicles with differential steering are also supported).

## Desired Behavior
Documentation for differential steering is required 

## Suggested Solution
Provide documentation

## Who does this impact? Who is this for?
Enables usage of INAV 2.5 and newer for tanks and vehicles with differential steering

**Comment by DzikuVx** [comment]
https://youtu.be/9194OzsHOFc
