### ISSUE TITLE
Motor remapping

### ISSUE THREAD

**Issue by undefine-man** [iNavFlight/inav#5939]
## Current Behavior

can't remapping the motor number.
## Suggested Solution

add this feature like Betaflight
## Who does this impact? Who is this for?

all users install esc unconventionally or just need this feature.
## Additional context

I once used betaflight , and my ESC was installed backwards for some reasons and i didn't make any adjustment to the cable ,cause betaflight can remap the motor number in CLI. But i fond it doesn't support this function after i switch to inav .So i hope this new feature can help inav more friendly to use .

**Comment by DzikuVx** [comment]
INAV Configurator 2.6 has a Motor Wizard that does the same by modifying the mixer.

**Comment by Tep-S** [comment]
@DzikuVx why there no such option for airplane? I can't use second motors as servo, can't use led pin as servo.
Just option in cli would save a lot of time and money.

**Comment by Pavel-trying** [comment]
> INAV Configurator 2.6 has a Motor Wizard that does the same by modifying the mixer.

It not works, motors starts at the same positions as before "wizard mixer"... How i can fix it?

**Comment by DzikuVx** [comment]
Wizard modifies the mixer nit output order. Effect is the same

**Comment by Pavel-trying** [comment]
> Wizard modifies the mixer nit output order. Effect is the same

Thanks man, i found your video about that right after typed it..
Thanks for your videos, i love you man!

**Comment by Pavel-trying** [comment]
But another mapping problem, why i cant add 3-th servo?
It connected to S10 pin. How to do it?

Board Matek H743
<img width="1728" alt="2022-03-19 о 11 32 16" src="https://user-images.githubusercontent.com/64655703/159115851-ff8bec59-ccf8-4f48-b406-d87e437dd094.png">
