### ISSUE TITLE
Full duplex softserial-1 for Matek F411-WSE

### ISSUE THREAD

**Issue by Target0815** [iNavFlight/inav#5940]
## Current Behavior
Softserial-1 is currently only a TX.

## Desired Behavior
Softserial-1 should be fullduplex RX/TX

## Suggested Solution
Fullduplex Softwareserial-1 as this is also generated by default as a target for Matek F411-Wing. Only a small change is necessary:

So far:
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_TX_PIN     PB9 // ST1 pad
#define SOFTSERIAL_1_RX_PIN     PB9

New:
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_TX_PIN     PB9 // ST1 pad
#define SOFTSERIAL_1_RX_PIN     PB10 // LED pad

This would give us 2 full UARTS (GPS, CRSF) and 1 Softserial e.g. for the DJI FPV System (OSD). 

## Who does this impact? Who is this for?
All users with DJI FPV system on copters and plane. Or of course all users who need a 3rd serial port.

**Comment by satsepp** [comment]
would be nice to Control camera device although.

Sepp

**Comment by fchansa** [comment]
Full ack!
For use of gps/crossfire/dji air unit it's neccessary to have a softserial with fullduplex RX/TX!

**Comment by gregm412** [comment]
Does anyone have a build with this enabled? I found one at https://fpv-community.de/threads/matek-f411-wse-softserial.85747/  but I'm unable to download.

**Comment by Target0815** [comment]
Download from this post: https://fpv-community.de/threads/matek-f411-wse-softserial.85747/post-1051752 (may be, that you have to be registered at the forum).

**Comment by Feldsalat** [comment]
Here: [2.5.1](https://workupload.com/file/ThpWwcXQ9JT)

**Comment by tobiasbischoff** [comment]
Please do it!

**Comment by dl1bg** [comment]
My F411WSE is also waiting to be used with GPS + Smartport + Caddx Vista. Would highly appreciate this feature!

**Comment by dl1bg** [comment]
@Feldsalat 
Tested, works fine.
I do not have enough knowledge to make a pull request by my own. But if anyone does, I will be happy to test it, brew the coffee or spend a beer.

**Comment by alexvazquez** [comment]
Is this a new firmware that I can flash in INAV? I need to use my Caddx vista

**Comment by alexvazquez** [comment]
> My F411WSE is also waiting to be used with GPS + Smartport + Caddx Vista. Would highly appreciate this feature!

Did you make it work? Appreciate it

**Comment by chr0mcom** [comment]
i need this for dji vtx

**Comment by dl1bg** [comment]
My EFX Racer plane works very nice with INAV; automatic flaps, RTH on failsafe and OSD is really usefull.
Unfortunately, there is no space for a bigger flight controller than the F411, so I can use this one or nothing.

UART1: GPS (RTH, speed measurement)
UART2: Receiver (FPORT in my case)
SOFTSERIAL1: DJI FPV system
I do not really think that someone would buy full color LED for the price of DJI OSD or ESC telemetry.

Still using the build from @Feldsalat, but it would be really kind if someone could spend the time to make a pull request. As stated above, I would be happy to brew him the coffee or spend a beer.

**Comment by alexvazquez** [comment]
> My EFX Racer plane works very nice with INAV; automatic flaps, RTH on failsafe and OSD is really usefull.
> Unfortunately, there is no space for a bigger flight controller than the F411, so I can use this one or nothing.
> 
> UART1: GPS (RTH, speed measurement)
> UART2: Receiver (FPORT in my case)
> SOFTSERIAL1: DJI FPV system
> I do not really think that someone would buy full color LED for the price of DJI OSD or ESC telemetry.
> 
> Still using the build from @Feldsalat, but it would be really kind if someone could spend the time to make a pull request. As stated above, I would be happy to brew him the coffee or spend a beer.

Nice, basically same build I need, where did you connected the DJI FPV RX and TX? Led pin and what other?

**Comment by dl1bg** [comment]
RX from DJI (Caddx Vista in this case): ST1
RT from DJI (Caddx Vista in this case): LED

**Comment by alexvazquez** [comment]
> @alexvazquez
> RX from DJI (Caddx Vista in this case): ST1
> RT from DJI (Caddx Vista in this case): LED

@dl1bg Does the firmware is available to flash via INAV or I have to download from someplace the HEX file? Appreciate it

**Comment by thedoble** [comment]
I would like this too! This board is great for small builds with gps/xfire/dji

**Comment by jstoeffler** [comment]
This seems fixed, isn’t it?

https://github.com/iNavFlight/inav/pull/6353

**Comment by alexvazquez** [comment]
Does anyone know where to get the firmware MATEKF411SE_FD_SFTSRL1 ? Appreciate so much

**Comment by alexvazquez** [comment]
> This seems fixed, isn’t it?
> 
> #6353

Hi, did you get the HEX in order to test that OSD works on ST1 and LED pins?

**Comment by jstoeffler** [comment]
I've tried with the V3.0-rc1: https://github.com/iNavFlight/inav/releases/tag/3.0.0 – inav_3.0.0_MATEKF411SE_FD_SFTSRL1.hex

And I can confirm it works

**Comment by baddb1** [comment]
> I've tried with the V3.0-rc1: https://github.com/iNavFlight/inav/releases/tag/3.0.0 – inav_3.0.0_MATEKF411SE_FD_SFTSRL1.hex
> 
> And I can confirm it works

I just flashed with V3.0. What pin is for Tx and what is Rx? Thanks

**Comment by jstoeffler** [comment]
> > I've tried with the V3.0-rc1: https://github.com/iNavFlight/inav/releases/tag/3.0.0 – inav_3.0.0_MATEKF411SE_FD_SFTSRL1.hex
> > And I can confirm it works
> 
> I just flashed with V3.0. What pin is for Tx and what is Rx? Thanks


@baddb1 If you read this thread you will find this information:

```
RX from DJI (Caddx Vista in this case): ST1
RT from DJI (Caddx Vista in this case): LED

```

**Comment by bnmoore** [comment]
Does this work for HDZero? I can't seem to get it to work.

**Comment by MrD-RC** [comment]
> Does this work for HDZero? I can't seem to get it to work.

No, HDZero needs an actual UART, not SoftSerial.

**Comment by bnmoore** [comment]
Confirmed. HDZero worked on an actual UART. Is this a hard limit or just something that iNav or HDZero enforces due to performance?
