### ISSUE TITLE
Airbot OmniNXT f7

### ISSUE THREAD

**Issue by Cynicus** [iNavFlight/inav#5943]
Target OMNIBUSF7NXT
Airbot

file: target.h

Betaflight:
#define USE_UART2
#define UART2_RX_PIN            PA3
#define UART2_TX_PIN            PA2

INAV:
#define USE_UART2
#define UART2_RX_PIN            NONE
#define UART2_TX_PIN            PA2

UART2 is free on board. Why UART2_RX_PIN NONE?
UART1 reserved for smartaudio/trump.

SBUS not work on UART2 with this configuration

**Comment by Cynicus** [comment]
Target OMNIBUSF7NXT
Airbot

file: target.h

Betaflight:
#define USE_UART2
#define UART2_RX_PIN            PA3
#define UART2_TX_PIN            PA2

INAV:
#define USE_UART2
#define UART2_RX_PIN            NONE
#define UART2_TX_PIN            PA2

UART2 is free on board. Why UART2_RX_PIN NONE?
UART1 reserved for smartaudio/trump.

With this configuration SBUS not work on UART2

**Comment by digitalentity** [comment]
Which board specifically? OMNIBUSF7NXT target is used on a lot of clones.

**Comment by Cynicus** [comment]
> Which board specifically? OMNIBUSF7NXT target is used on a lot of clones.

Original Airbot OmniNXT F7
https://store.myairbot.com/flight-controller/omnibus-f7/omninxtf7.html

**Comment by Cynicus** [comment]
I made changes on my local comp and rebuild inav 2.5.1. All work fine!
