### ISSUE TITLE
Arming disabled flags

### ISSUE THREAD

**Issue by mateo356** [iNavFlight/inav#5944]
Hi everyone,
I can't solve problem with Arming disabled flags: THR (from status CLI command)  . Do you have any suggestion how to setup throttle, I didn't find any useful tutorial? I'm using Spektrum receiver and omnibusF f4 flight controler (FW 2.5.1.)  Best regards

**Comment by stronnag** [comment]
You could try the project documentation, for example the RX document, and in particular https://github.com/iNavFlight/inav/blob/master/docs/Rx.md#receiver-channel-range-configuration which would seem to directly address your problem.
