### ISSUE TITLE
attitude.raw

### ISSUE THREAD

**Issue by johnyb97** [iNavFlight/inav#5946]
hello,
i am going through the code and i have difficulties finding where are the values in attitude.raw updated.
This values are used in pid.c, line 526
const float angleErrorDeg = DECIDEGREES_TO_DEGREES(angleTarget - attitude.raw[axis]);
Could you direct me to the place in the code where this value is updated?
Thank you for your help

**Comment by DzikuVx** [comment]
it's a `union` https://www.tutorialspoint.com/cprogramming/c_unions.htm
