### ISSUE TITLE
Global Variables not working, storing all in GV0

### ISSUE THREAD

**Issue by DungAdumbs** [iNavFlight/inav#5947]
## Current Behavior
Global variables all being stored in GV0

## Steps to Reproduce
https://youtu.be/vb553Fstqco
Video pretty well shows part of issues.  GV0-3 are all showing on GV0 on programming tab.  Confirmed by setting up Smix to output GV's.  Outputs indeed show only GV0 is being used.  I have seen incorrect values appear in other variable slots GV1-3 as well on my actual set up.

## Expected behavior
GV's go where intended.

## Suggested solution(s)
I have no clue

## Additional context
https://pastebin.com/p7fmDBEQ

---
# version
# INAV/MATEKF405SE 2.5.1 Jun 16 2020 / 12:50:26 (098a574b3)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

MXK405wing

**Comment by DzikuVx** [comment]
Since we just talked about that on Telegram, we can close
