### ISSUE TITLE
speedybee F7 Target

### ISSUE THREAD

**Issue by GaryMcDonogh** [iNavFlight/inav#5952]
Good day.

Is there any info if you are able to have a firmware target for the SPEEDYBEE F7 board?

Kndly

Gay

**Comment by fluffy** [comment]
Just as a note to anyone looking at this feature request, I see there is a unified target for this at https://github.com/betaflight/unified-targets/blob/master/configs/default/SPBE-SPEEDYBEEF7.config

**Comment by DzikuVx** [comment]
HEX was missing from the release. Board now released with INAV 2.5.2
