### ISSUE TITLE
Unable to arm "throttle not low" even when set

### ISSUE THREAD

**Issue by Ziov1** [iNavFlight/inav#5960]
I'm having an issue with being unable to arm due to throttle not being low. I've set it in receiver options and also in controller to the 1000 - 2000.

I also set it using set min_check = 1000 but still the same issue.

I don't seem to able to solve it, tried all the ways I did from searching online. 

Please help.
F722 se, x9d+.

**Comment by DzikuVx** [comment]
THR has to be below `min_check`. But without diff or any extra data like a screenshow from the Receiver tab, we can not help

**Comment by Ziov1** [comment]
Have attached files thanks.
![Capture1](https://user-images.githubusercontent.com/67508429/87973336-421dc400-cac0-11ea-8bcd-3a431f10cb6b.PNG)
![Capture2](https://user-images.githubusercontent.com/67508429/87973339-434ef100-cac0-11ea-97f1-dad2adb0aa27.PNG)
[diff.txt](https://github.com/iNavFlight/inav/files/4949457/diff.txt)

**Comment by DzikuVx** [comment]
`set min_check = 1050` should do it

**Comment by Ziov1** [comment]
same issue

**Comment by Ziov1** [comment]
Did a little more looking into it, not sure if related but magnomiter was not active, was getting i2c errors. They kept counting up. Activated magnomiter and i2c errors are at 45.
While magnomiter is active I can't get a GPS lock without it I get 16 Satalites. I'm using a Matek GPS M8q 5883.

**Comment by Ziov1** [comment]
Still getting issue, sorted gps magnomiter.

**Comment by Mateyhv** [comment]
> 
> 
> Still getting issue, sorted gps magnomiter.

Can you upload a video somewhere?

**Comment by Ziov1** [comment]
> > Still getting issue, sorted gps magnomiter.
> 
> Can you upload a video somewhere?

What do you need video of?

**Comment by liyifei1171-del** [comment]
I got the same issue as you, can you tall me how you fix it

**Comment by sensei-hacker** [comment]
> I got the same issue as you, can you tall me how you fix it

Look in your Receiver tab.
Is the channel marked Throttle low?
