### ISSUE TITLE
Servo and motor not working on flying wing

### ISSUE THREAD

**Issue by stinkyElias** [iNavFlight/inav#5961]
Hello. I'm completely new to iNav and FCs. I'm currently building a flying wing with Matek F765 WING and iNav. I have followed YouTube tutorials and iNav's Fixed Wing guide, but when I want to test the servos and motors there's only one servo that is working (servo pin 3/left wing). The servo on pin 4/right wing will immediately go to full end point after plugging in the battery.
In iNav, I have enable the servos and motor and I can see that the FC is responding to my stick movements correctly.
After countless Google searches I have not found any useful tips to fix this problem.
Any help would be appreciated :D

**Comment by DzikuVx** [comment]
We can not help without any data. CLI diff, Mixer tab screenshot. Whatever you can give us

**Comment by ubervav** [comment]
Yes, of course. Here is a screenshot of the mixer tab. It's just the flying wing preset.

![MixerTab](https://user-images.githubusercontent.com/65676062/88030126-24da0b80-cb3b-11ea-8bc4-2b35e28ee84d.JPG)

CLI diff:

[INAV_cli_F765_20200721_101500.txt](https://github.com/iNavFlight/inav/files/4952170/INAV_cli_F765_20200721_101500.txt)

Please let me know if you need more information.

**Comment by PhilippeKonrad** [comment]
I am having the same issue on 2.5.2 for KakuteF4V2, only servo 4 isn't responding.

3 works flawlessly, but servo 4 boots, twitches, and goes to end point. 

Then no response from that servo, either via outputs tab or with tx. 

I ran the servo through a tester and it works fine. 

How did you resolve?

**Comment by ubervav** [comment]
Unfortunately I didn’t resolve it. Nothing was working for me, no forums or help from others. I’ve been busy for a long time and haven’t been able to look at it for a while. I will have another look during the holiday seasons.
If you resolve it, please let me know. Maybe we could cooperate on this matter!

Fra: PhilippeKonrad <notifications@github.com>
Sendt: torsdag 5. november 2020 23:17
Til: iNavFlight/inav <inav@noreply.github.com>
Kopi: ubervav <elias-tennis@hotmail.com>; State change <state_change@noreply.github.com>
Emne: Re: [iNavFlight/inav] Servo and motor not working on flying wing (#5961)


I am having the same issue on 2.5.2 for KakuteF4V2, only servo 4 isn't responding.

3 works flawlessly, but servo 4 boots, twitches, and goes to end point.

Then no response from that servo, either via outputs tab or with tx.

I ran the servo through a tester and it works fine.

How did you resolve?
