### ISSUE TITLE
SUPPORT: Change beeper RX_SET tone to continuous single beep

### ISSUE THREAD

**Issue by bigbrainbonobo** [iNavFlight/inav#5963]
Hi all, is it possible to change the RX_SET beep tone?

I've hooked up a push/pull solenoid to the buzzer- pad on my Matek F7 22se and am using its AUX channel to switch it on/ off for use as a payload dropping mechanism for fishing.

My issue is that when activated, the RX_SET tone buzzes on/off in quick succession as noted here: https://github.com/iNavFlight/inav/blob/master/docs/Buzzer.md

Is it possible to change it to a single, continuous beep with a single, continuous pulse?

Many thanks for any advice!

**Comment by craigmunday** [comment]
Have you considered  using a down rigger line release?  This is what I intend on trying for fishing
