### ISSUE TITLE
TPA settings to be selected in the Adjustments drop-down and OSD

### ISSUE THREAD

**Issue by StuweFPV** [iNavFlight/inav#5965]
## Current Behavior
Changing the TPA settings currently requires to do this on the ground. This is a setting that totally makes sense to me to be able to change/test this during the flight without having to land in between.

## Desired Behavior
Being able to test/set correct TPA settings in the air with switches like any other Adjustments functions.

## Suggested Solution
Add the **TPA Breakpoint** and the **TPA Rate** to be selected in the Adjustments drop-down list. It would also be helpful if TPA settings could be displayed in the OSD.

## Who does this impact? Who is this for?
All that use TPA settings

**Comment by stuwe911** [comment]
I'm closing this issue now because TPA never worked properly for fixed wings. It becomes obsolete in v4.0 with the introduction of selecting via programming the PID profiles. This is a much better solution to the problem mentioned above even though a curve would be better than 3 set profiles.
