### ISSUE TITLE
Killed GPS after updating from 2.4.0 to 2.5.1 on an Omnibus F4 Pro V3

### ISSUE THREAD

**Issue by mrduncan626** [iNavFlight/inav#5972]
Most of my fixed wing aircraft have Matek FC's except for two which have Omnibus F4 Pro V3 FC’s.  I been running iNav on the two Omnibus FC’s for about 3 years on a fixed wing configured with a BN-180 GPS.  When I update from iNav 2.4.0 to 2.5.1, the two BN-180 GPS’s totally failed (power LEDs on the GPS’s turned off) after about 30 minutes.  After installing two new GPS’s on the Omnibus FC fixed wing resulted in two GPS's failing again (power LEDs on the GPS’s turned off) after about 30 minutes.  

However, updating all my other Matek FC fixed wing aircrafts from 2.4.0 to 2.5.1 had no effect on the GPS’s.

**Comment by giacomo892** [comment]
Omnibuses are known to send spurious high voltage on 5V lines. INAV is not related to board power management.
