### ISSUE TITLE
Brushless rocket servo's 

### ISSUE THREAD

**Issue by clementpeleman** [iNavFlight/inav#5975]
I have 4 servo's connected to a omnibusf4 fc. I edited the target.c file and i want to use my 4 main motor pwm outputs to drive my 4 servo's. This is my inav setup:
![Untitled](https://user-images.githubusercontent.com/28512676/88296615-3a982e00-ccff-11ea-9cba-43a55aeb3034.png)
![Untitled2](https://user-images.githubusercontent.com/28512676/88296621-3d931e80-ccff-11ea-94be-5e0005d2fb56.png)
But i cant get my servo's to start moving. they are all connected to the same 5v bec that can handle 3A.
As you can see on the last picture, the values are changing when i move the board.

**Comment by DzikuVx** [comment]
Omnibus F4 supports 4 servos in airplane configuration out of the box on S2-S6
