### ISSUE TITLE
Release 2.5.2

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#5978]
Patch release.
Will only contain minor bug fixes, minor cosmetic features, new targets not requiring changes to the main code base.

Backports/cherry-picks are welcome to `release_2.5.2` branch. This branch will NOT be merged to `master`.

**Comment by digitalentity** [comment]
Backported FLYWOOF411 and FLYWOOF7DUAL targets (6fb36826fda86e071985e83e839a309b9a1f44ec)

**Comment by snaewe** [comment]
Please, please please, merge my PR #5980  ;-)

**Comment by digitalentity** [comment]
Cherry-picked support for FOXEERF722V2 (c02049d9e818dcd16160043d2219b8ce1c17d4f1)

**Comment by digitalentity** [comment]
Cherry-picked #5980 (90cbceee8c8cb8b4a178c5b612e2943ed4630a59)

**Comment by DzikuVx** [comment]
cherry-picked ce96a748462b9d1426e0854baf7e5bc706f76b27
