### ISSUE TITLE
External Servo Driver not working on 2.5

### ISSUE THREAD

**Issue by frederik-raphael** [iNavFlight/inav#5989]
**Current Behavior**
INAV 2.4 is the last version where the External Servo Driver actually functions
even typing in the command "feature PWM_SERVO_DRIVER" after 2.4 gives an error.

## Steps to Reproduce

1. Downgrading to 2.4 and using the driver
2. Upgrading to 2.5(.1 or .0) and not beeing able to use it

## Expected behavior
typing "feature PWM_SERVO_DRIVER" shouldn't give an error and actually function.

- FC Board name and vendor:
- INAV version string: Tried multiple like Matek405, KakuteF4, KakuteF7 & Omnibus

**Comment by stronnag** [comment]
Changed for 2.5 ...

```
# get servo
servo_protocol = PWM
Allowed values: PWM, SERVO_DRIVER, SBUS
```
Please confirm this addresses your problem.
