### ISSUE TITLE
Led strip on NAZE 32

### ISSUE THREAD

**Issue by langph** [iNavFlight/inav#599]
I have a Skyline 32 advanced 1.1 and would really like to add a LED for status purposes. Is it possible to enable led strip for  release 1.2 as it was on release 1.1?

**Comment by DzikuVx** [comment]
@langph you might want to read #457 
Bottom line is you would have to compile your own version of INAV

**Comment by martinbudden** [comment]
Perhaps we should put something in the wiki about this.

**Comment by stronnag** [comment]
Like the existing "Getting Started " page that no one appears to read?

**Comment by martinbudden** [comment]
You're right. It's all there on the "Getting Started" page. I must confess I haven't read that for ages.

**Comment by stronnag** [comment]
Really, we should perhaps
1. Fix the configurator so it points to iNav builds (not CF builds)
2. When the user selects a F1 build, show some text that warns them about missing features / points them go the wiki

**Comment by DzikuVx** [comment]
I think 1 was done
about 2, I have a plan to work on configurator a little, so maybe it will be done

**Comment by langph** [comment]
I have overlooked that, looked in the release notes and saw that led strip was re-enabled in 1.1, hence my question.

The Features safe to remove are incomplete though.

I will compile my own. Would it be possible to read out a board and deselect support for sensors etc. that it does not have, compile on the spot and then upload it in the board? Might save some space for new features.

---

Van: Martin Budden notifications@github.com
Verzonden: dinsdag 13 september 2016 10:36
Aan: iNavFlight/inav
CC: langph; Mention
Onderwerp: Re: [iNavFlight/inav] Led strip on NAZE 32 (#599)

You're right. It's all there on the "Getting Started" page. I must confess I haven't read that for ages.

##

**Comment by oleost** [comment]
@langph Feel free to help out making that list more complete. 

Also updated wiki with a small video to help out.
