### ISSUE TITLE
Add PINIO on LED pin when LED_STRIP disabled

### ISSUE THREAD

**Issue by nikram77** [iNavFlight/inav#6003]
## Current Behavior
PINIO are only on pins designed by manufactures, no PINIO for external devices.

## Desired Behavior
PINIO on LED pin, when led strip is disabled.
Enabling led strip would disable PINIO output.

## Suggested Solution
I`m not a developer, but this needs another BOXUSER3 in modes and somethin like softserial switch in configuration (led strip ON then PINIO OFF).

## Who does this impact? Who is this for?
Everybody who wants to activate thing like external DVR, ext. video switcher, ext. "pit mode" switches. Probably lots of other devices in the future.

## Additional context
I just did a custom build for my F722 Wing, by swapping led pin with vtx switcher (PINIO1_PIN) and commenting LED_STRIP definition. I wanted to add PINIO3_PIN, but then realized there is no USER3 mode. Adding that is above my skills. I don`t use vtx switcher on this build so no problem. But it would be nice to have option to just enable external PINIO output on any FC.

**Comment by art1946** [comment]
/this would be great.I to have been trying to figure out how to use vtx on off switch(xilo) like in beta flight using pinio commands

**Comment by arvilla3533** [comment]
@DzikuVx Saw this issue as completed, any docs on how to set this up? Thanks!

**Comment by sensei-hacker** [comment]
It's going through be much easier to set up in INAV 10. For now:

https://github.com/iNavFlight/inav/blob/da2a35cbd8f6c84a2d3d723337c4cdc1cd783837/docs/LED%20pin%20PWM.md#programming-tab-example-for-using-the-led-pin-as-a-pinio-such-as-for-turning-a-vtx-or-camera-on-and-off

**Comment by arvilla3533** [comment]
> It's going through be much easier to set up in INAV 10. For now:
> 
> https://github.com/iNavFlight/inav/blob/da2a35cbd8f6c84a2d3d723337c4cdc1cd783837/docs/LED%20pin%20PWM.md#programming-tab-example-for-using-the-led-pin-as-a-pinio-such-as-for-turning-a-vtx-or-camera-on-and-off

thanks!
