### ISSUE TITLE
INAV 2.5 GPS

### ISSUE THREAD

**Issue by mickey2011** [iNavFlight/inav#6008]
INAV 2.5, Wing FC board, FF35 Inav target, Beitain 220 GPS. All working perfectly in INAV 2.4 and earlier, but not in 2.5.

Green GPS symbol appears in INAV Configurator, GPS reports 1000's of messages, but no GPS coordinates. Using UBLOX setting and tried various baud speeds. Using RX/TX2 as standard for 'Wing FC' board.

Anyone else with the same issue?

**Comment by DzikuVx** [comment]
Leave the model outside for 30 miutes. Acquiring GPS lock is GPS module internal affair
