### ISSUE TITLE
Matek f722se constant reboot. 

### ISSUE THREAD

**Issue by geniusboywonder2020** [iNavFlight/inav#6012]
hello. I have a matek f722se that was running iNav ok until one day I had no osd and I could not get a connection. After a few hours I tried again and it just worked. One day I was configuring the quad to add gps features and it lost connection then the fc was stuck in a constant boot loop when powered by battery or usb.

I cannot stay connect long enough to configure the flight controller. 

I have however managed to flash betaflight to the same flight controller with no issues. Is there likely to be a software issue here or faulty hardware? 

Apologies for no cli dump but I am unable to get one before a disconnect. The fc is a matek f722se and I’m using the target matekf722se

**Comment by DzikuVx** [comment]
This looks like hardware failure or broken configuration. Enter DFU by holding the button during powering and flash with full chip erase enabled
