### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by fenglaijun** [iNavFlight/inav#6017]
i had met this error,please help me,thanks!

make SPRACINGF3
echo "" && \
        echo "Building SPRACINGF3" && \
        CFLAGS= make -j 8 TARGET=SPRACINGF3 && \
        echo "Building SPRACINGF3 succeeded."

Building SPRACINGF3
make[1]: 正在进入目录 `/home/dog/inav'
/home/dog/inav/src/utils/compiler.rb:38: warning: Insecure world writable dir /home/dog in PATH, mode 040777
settings.yaml -> settings_generated.h, settings_generated.c
./src/utils/settings.rb:748: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG
        add_condition = -> (c) {
                            ^
./src/utils/settings.rb:748: syntax error, unexpected tLAMBEG, expecting keyword_end
./src/utils/settings.rb:755: syntax error, unexpected '}', expecting keyword_end
./src/utils/settings.rb:887: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG
        add_value = -> (v) {
                        ^
./src/utils/settings.rb:887: syntax error, unexpected tLAMBEG, expecting keyword_end
./src/utils/settings.rb:894: syntax error, unexpected '}', expecting keyword_end
make[1]: *** [obj/main/SPRACINGF3/settings_generated.h] 错误 1
make[1]:正在离开目录 `/home/dog/inav'
make: *** [SPRACINGF3] 错误 2

**Comment by shellixyz** [comment]
Your version of Ruby is probably too old. What is `ruby -v` displaying ?

**Comment by fenglaijun** [comment]
> Your version of Ruby is probably too old. What is `ruby -v` displaying ?

thanks!this is because i did not intall ruby.now i can build it success!

**Comment by fenglaijun** [comment]
ruby didn't install
