### ISSUE TITLE
Hard code specific RTH lat / long coordinates in iNAV?

### ISSUE THREAD

**Issue by mikey0514** [iNavFlight/inav#6022]
**Scenario:** 
Flying fixed wing and plugging in / taking off around some obstacles that would make it unsafe to do a fail safe RTH landing.

There is a field a few hundred yards from where I take off, that would be perfect for a fail safe RTH landing..

**Desired Behavior:**
Ability to set specific RTH lat/long coordinates in iNAV, instead of using location where battery is plugged in.

This would allow me to set coordinates where it would be safe for the plane to land, in case of fail safe.

Other ways to achieve desired behavior?

Thanks.

**Comment by stronnag** [comment]
Currently you can modify the RTH home with `nav_rth_home_offset_distance` and `nav_rth_home_offset_direction`.
In 2.6 you can use `safehome` #5995
