### ISSUE TITLE
Let INAV figure out rates on FW

### ISSUE THREAD

**Issue by avsaase** [iNavFlight/inav#6025]
## Current Behavior

The PIFF controller on fixed wing uses the airplane's maximum roll, pitch and yaw rates for it's stabilization. Finding the correct rates can be a bit of a pain, especially for planes that can't do nice clean rolls and loops without a lot of other pilot input. Measuring the yaw rate is even more difficult, since rudder often has a strong roll response. In that case a black box log is the only method to figure out the rates, but this requires a computer which is often impractical.

## Desired Behavior

The gyroscope should be able to measure the rotation rates on full control surface deflection.

## Suggested Solution

Make `AUTOTUNE` a two-stage process where it first determines the rates on full control surface deflection, and then tunes the PIFF values using those rates. Ideally it would be possible to also do each stage separately if the user only want to do one or the other.

## Who does this impact? Who is this for?

All fixed wing pilots.

**Comment by avs2** [comment]
Anyone?

**Comment by FPVZaphod** [comment]
Great idea!
Measurement can be initiated once the stick reaches maximum deflection, then wait a short while till the rate reaches a stable value.

**Comment by mf0o** [comment]
I really wonder why this hasnt been a topic for a longer time but I guess that setting is underestimated by most pilots. Secondly, with the scale-down-trend more and more smaller FCs dont even have blackbox capabilities - at least my last two planes doesnt.

An AUTOROLL feature would be awesome, extracting rates from DVR or external footage still feels like a nasty workaround. 

How could the function work in detail?
- new mode? (i.e. place on the manual channel)
- watch the roll/pitch channel
- start measuring once the channel is (and keep) at max
- stop measuring after 1sec
- print °deg on status/warning field (no auto-set/save for first release)
- repeat at #2 

Thoughts?
