### ISSUE TITLE
Set up guide for Flow camera - matek opflow

### ISSUE THREAD

**Issue by Chick92** [iNavFlight/inav#6042]
Has anyone had any luck with getting this sensor to work? 

The setup guide produced by matek systems is outdated and leaves a lot to be desired.

I cant get the UAV to do anything productive with the sensor, other than go nuts and yeet itself into a wall.

I’m intending to fly in GPS denied environments, and being able to maintain a stable hover is key, I essentially want to replicate a mavic mini.

Someone doing a setup / tuning video would be VERY helpful. 

Thanks!

**Comment by digitalentity** [comment]
Can you please highlight  issues with the  Matek's guide so we can fix them?
