### ISSUE TITLE
Target request: SucceX-D F7 V2.1 TwinG Flight Controller

### ISSUE THREAD

**Issue by bckenneth** [iNavFlight/inav#6057]
Is that possible create a target for SucceX-D F7 V2.1 TwinG Flight Controller for Inav.
Targer:iflight_f722_twing
please create one
Thanks

**Comment by nambuco** [comment]
+1

**Comment by jerryt1** [comment]
+1

**Comment by Lusby** [comment]
+1
the quad this FC is in, Chimera7, is a perfect candidate for iNav (may need a GPS upgrade)

**Comment by schmidi-dev** [comment]
Whats the status? I'm confused by contradictory information.

**Comment by vpominchuk** [comment]
+1 
very interesting and affordable drone made by iFlight on this controller. It's will be great if we can make it much better flashing INAV. Thank you.

**Comment by MaikFPV** [comment]
+1
please add target - stay healthy

**Comment by prohelper** [comment]
> 
> 
> is this the target? **inav_2.6.0_IFLIGHTF7_TWING**

To what i can see this target doesnt have UART 3 for some reason. Is there anyway mabye they can update the target?

**Comment by janmj** [comment]
> > is this the target? **inav_2.6.0_IFLIGHTF7_TWING**
> 
> To what i can see this target doesnt have UART 3 for some reason. Is there anyway mabye they can update the target?

Uart 3 is used for i2c. This is mentioned on the wiring schematic on the iflight site. But is the current inav target otherwise functioning on the V 2 1 board?

**Comment by mtshare** [comment]
+1

**Comment by prohelper** [comment]
I dont have access to my drone at the moment. I remember the ports being different from betaflights config

**Comment by mtshare** [comment]
@prohelper so the target is correct (**IFLIGHTF7_TWING**)?

**Comment by nowaythatsok** [comment]
Does anyone have an update on this? Is there a target now for this FC?

**Comment by MaikFPV** [comment]
Closed = implemented? Can someone confirm working target? Thanks a lot!

**Comment by ridgeracer** [comment]
I use this target for an older Iflight F722 TwinG BT. Can’t confirm if compass will work on Uart3 which should be SDA/SDL. GPS doesn’t work on Uart4 or Uart5. Conflicts with M1 servo output. Currently set M3 to dshot150. GPS works on Uart2. RX works on Uart1. Servo outputs confirmed working on M1 - M4. So this target can use full Uarts on 4 or 5. Can others confirm same?
