### ISSUE TITLE
PID tuning for GPS hold 

### ISSUE THREAD

**Issue by courierdude** [iNavFlight/inav#606]
Hi all. My first post so I hope I'm doing this right. 
QAV540G
Naze32 full
Ublox m8n
When in GPS hold, the quad wanders up to about 10 meters. Was showing signs of long slow toilet bowling so I've re calibrated compass (on the naze board). Can someone point me to a link where I can research how to tune the GPS PIDS to try and lock this baby in? I've searched and searched but can't seem to find the info I need. 
Just in case it's needed...
FE;§$M>eÑ¿$M>n·×
Entering CLI Mode, type 'exit' to return, or 'help'
# dump
# version
# INAV/NAZE 1.1.0 May 11 2016 / 02:37:17 (1f49891)
# pflags
# Persistent config flags: 0x00000001
# dump master
# mixer

mixer QUADX
mmix reset
smix reset
# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature RX_PPM
feature VBAT
feature MOTOR_STOP
feature SOFTSERIAL
feature GPS
feature FAILSAFE
feature TELEMETRY
feature RSSI_ADC
feature BLACKBOX
# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
# map

map AETR1234
# serial

serial 0 1 115200 38400 0 115200
serial 1 2 115200 115200 0 115200
serial 30 0 115200 38400 0 115200
serial 31 0 115200 38400 0 115200
# led

led 0 15,15:ES:IA:0
led 1 15,8:E:WF:0
led 2 15,7:E:WF:0
led 3 15,0:NE:IA:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:IA:0
led 7 0,7:W:WF:0
led 8 0,8:W:WF:0
led 9 0,15:SW:IA:0
led 10 7,15:S:WF:0
led 11 8,15:S:WF:0
led 12 7,7:U:WF:0
led 13 8,7:U:WF:0
led 14 7,8:D:WF:0
led 15 8,8:D:WF:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0:::0
led 29 0,0:::0
led 30 0,0:::0
led 31 0,0:::0
# color

color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

set looptime = 2000
set emf_avoidance = OFF
set i2c_overclock = OFF
set gyro_sync = OFF
set gyro_sync_denom = 2
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 1000
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = OFF
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.200
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = ON
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 300
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_altitude = 1000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_min_fly_thr = 1200
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SBUS
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set yaw_control_direction = 1
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = RTH
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set magzero_x = 245
set magzero_y = -162
set magzero_z = -114
set acczero_x = 59
set acczero_y = 91
set acczero_z = 304
set accgain_x = 4110
set accgain_y = 4063
set accgain_z = 4022
# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h
# dump profile
# profile

profile 0
# aux

aux 0 1 0 900 2100
aux 1 3 0 1300 2100
aux 2 3 2 1650 2100
aux 3 10 0 1775 2100
aux 4 9 2 1700 2100
aux 5 12 1 1800 2100
aux 6 17 1 1300 1700
aux 7 22 1 900 1300
aux 8 23 2 1700 2100
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000
# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 30
set nav_pos_i = 0
set nav_pos_d = 0
set nav_posr_p = 30
set nav_posr_i = 8
set nav_posr_d = 45
set nav_navr_p = 14
set nav_navr_i = 20
set nav_navr_d = 80
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set default_rate_profile = 0
set gimbal_mode = NORMAL
set mag_declination = 2040
set p_pitch = 40
set i_pitch = 20
set d_pitch = 70
set p_roll = 30
set i_roll = 20
set d_roll = 70
set p_yaw = 100
set i_yaw = 40
set d_yaw = 0
set p_level = 120
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
# dump rates
# rateprofile

rateprofile 0

set rc_rate = 90
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
# 

Thankyou

**Comment by DzikuVx** [comment]
Default GPS Hold PIDs are good and solid, usually there is no need to retune it.
If I have to guess I would tell, that the reason is onboard magnetometer too close to power cables, ESCs or other electrical devices. Built in magnetometers are extremely sensitive and in 95% of cases they are the reason UAV can not keep position.
Blackbox log would be very helpful to confirm that.
rearrange cables, but better use external magnetometer far away from all metalic/electric devices

**Comment by courierdude** [comment]
Thank you so much for replying. I am running a Naze32 f/c and just purchased a http://www.hobbyking.com/hobbyking/store/__99119__Mini_Ublox_NEO_M8N_GPS_for_Naze32_Flip32.html. 
But it doesn't appear to have the compass wired which is why I'm still using the compass on the Naze32. I've moved the f/c as far as possible from the power wires, but obviously not far enough. Any suggestions if it's possible to shield the compass from interference?

**Comment by bk79** [comment]
Put some aluminium foil with heat shrink around esc/wire and solder a wire
on it connected to the negative of the battery plug

Il 17/set/2016 15:01, "Phil" notifications@github.com ha scritto:

**Comment by courierdude** [comment]
Thanks, I'll give it a try. Does any one know if you can identify interference of the compass through iNav GUI? I see there's a moving graph but I don't know how to decipher the read out. It is looking pretty steady even after I throttle up with no props of course. If it was getting interference, I would have expected it to be all over the show.

**Comment by bk79** [comment]
Easy way is to verify on the main window if north corresponds to 0 heading
with everything off then move to the graph tab and read the values for x y
z, now tie it so it cannot move from where it is so to keep always 0
heading and north, install props and run motors then go and read the values
again they probably are different. If heading and north is not shown...it
means you have a trouble.....an easier way to test it make a run in ph if
it makes toilet bowls it means you have a problem with mag

**Comment by courierdude** [comment]
Excellent. Thank you. I'll check it out.

**Comment by stronnag** [comment]
Black box log. fly straight lines at reasonable throttle. Post the logs. Someone here (me, digitalentity, others) will analyse it for you and check the correlation between mag direction and heading from GPS.

**Comment by courierdude** [comment]
Great. Thank you. Raining here at the moment, not due to clear for several days. I'll do it as soon as possible.
Actually now I think of it, I've flown a few times and I think the Black box has been recording. Can you point to a link so I can learn how to get the info?

**Comment by stronnag** [comment]
Not sure there are any links. I use a script (from mwptools/samples) that correlates heading (attitude[2]/100) against calculated course from consecutive  GPS locations where the speed is greater than some value (say 4m/s) and throttle above some value (say 1500). The arbitrary values to help ensure we are in steady flight where the GPS will give reasonable directional information (which is not the case in hover).

**Comment by MarcoPTG** [comment]
Hello Guys. My copter after iNav 1.2 become a little unstable on PosHold and i am trying to improve the GPS PID Values but its a little bit hard but i will keep trying. The RTH is working Fine but need to improve the NavR PID Values to be more stable. But the iNav need the Autotune for PID values. I didn't test the Mag Mode and if i can help on this count me in. I am a newbie on this. 
PS: Do you guys know if the Fail Safe RTH is working? My doesn't work. Only Fail Safe Land.
Thanks.
MSilva.

**Comment by blakowl** [comment]
Can you explains the Pos, Posr, and Navr abbreviations in the GPS tuning pids please

**Comment by oleost** [comment]
Use rcgroups thread for support. Also there are some brief explanations on in the cli.md document.

This issue is closed, please continue on rcgroups thread.

**Comment by georgekucher** [comment]
Hi!
Should I configure the GPS PIDs if I have old BT_GPS [module](http://www.mondoplast.ro/eng/Bluetooth-GPS-receiver-West-Studio-BT-77-pg_ft-2655) which runs at 1Hz and 16 channels on NMEA protocol? The problem I'm facing with is, not even bowling but fast running from side to side. When I'm enabling PH mode, after couple of seconds the quadcopter rapidly runs aside for near 5 meters, then to the opposite direction but more far, and so on in 15-30 meters radius of the point where PH was turned on.
The MAG is external and mounted 10-15 cm below the FC and other wiring (excepting the main BAT, its in 5 cm of it). I'll upload a video with OSD to be sure.
Sadly I have Flip32 (F1 NAZE) board and can't have a blackbox logging.

Or maybe this old GPS is a crap and I should throw it to trash?)))

**Comment by georgekucher** [comment]
[Here](https://youtu.be/R_-d7vSzAW4) it is.
Sorry for quality ;)

**Comment by digitalentity** [comment]
1Hz GPS is not enough for INAV to function properly. Technically the code may be able to cope with such slow update rate, but it's really on the edge.

**Comment by georgekucher** [comment]
Should I try to switch GPS velocity? May it help?

**Comment by digitalentity** [comment]
You can try configuring your GPS for 5Hz update rate - it may help. Changing settings likely won't help.

**Comment by georgekucher** [comment]
Specs says that 1Hz is max ((

**Comment by georgekucher** [comment]
Please look if everything else settings is ok


# INAV/NAZE 1.8.0 Nov 10 2017 / 20:15:28 (912d1315)
feature -RX_PPM
feature -VBAT
feature -RX_UIB
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature VBAT
feature GPS
feature CURRENT_METER
feature LED_STRIP
feature PWM_OUTPUT_ENABLE
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED
map AETR5678
name -
serial 0 1 115200 38400 0 115200
serial 1 2 115200 38400 0 115200
led 0 4,6::C:0
led 1 5,6::C:0
led 2 6,6::C:0
led 3 7,6::C:0
led 4 8,6::C:0
led 5 9,6::C:0
led 6 10,6::C:0
led 7 11,6::C:0
led 8 0,7::CW:2
led 9 1,7::CW:2
led 10 2,7::CW:2
led 11 3,7::CW:2
led 12 4,7::CNW:2
led 13 5,7::CNW:2
led 14 6,7::CNW:2
led 15 7,7::CNW:2
led 16 4,8::CO:0
led 17 5,8::CO:0
led 18 6,8::G:0
led 19 7,8::CO:0
led 20 8,8::CO:0
led 21 9,8::G:0
led 22 10,8::CO:0
led 23 11,8::CO:0
led 24 8,7::CNW:2
led 25 9,7::CNW:2
led 26 10,7::CNW:2
led 27 11,7::CNW:2
led 28 12,7::CW:2
led 29 13,7::CW:2
led 30 14,7::CW:2
led 31 15,7::CW:2
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0
aux 0 0 0 1275 2100
aux 1 2 1 1125 1275
aux 2 2 1 1725 1875
aux 3 3 1 1500 2100
aux 4 9 1 1925 2100
aux 5 9 1 1300 1500
aux 6 21 1 900 1100
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000
set looptime = 2000
set gyro_sync = ON
set gyro_sync_denom = 16
set align_gyro = DEFAULT
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 70
set moron_threshold = 32
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set align_acc = DEFAULT
set acc_hardware = MPU6050
set acc_lpf_hz = 15
set acczero_x = 70
set acczero_y = 17
set acczero_z = -210
set accgain_x = 4010
set accgain_y = 4074
set accgain_z = 4029
set align_mag = CW270
set mag_hardware = QMC5883
set mag_declination = 610
set magzero_x = -218
set magzero_y = 355
set magzero_z = -15
set mag_calibration_time = 30
set baro_hardware = MS5611
set baro_use_median_filter = ON
set receiver_type = PPM
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_smoothing = ON
set rx_spi_rf_channel_count = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set min_throttle = 1050
set max_throttle = 1980
set min_command = 1000
set motor_pwm_rate = 8000
set motor_pwm_protocol = MULTISHOT
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 208
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 100
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 600
set current_meter_offset = 33
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 5
set deadband = 5
set yaw_deadband = 5
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = OFF
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 100
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 10
set nav_min_rth_distance = 500
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = FS_ONLY
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 4000
set nav_mc_bank_angle = 15
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 5000
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 5000
set nav_fw_launch_climb_angle = 18
set ledstrip_visual_beeper = OFF
set i2c_speed = 400KHZ
set cpu_underclock = OFF
set debug_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = ON
set stats_total_time = 1449
set stats_total_dist = 1494
set tz_offset = 0
profile 1

set mc_p_pitch = 80
set mc_i_pitch = 30
set mc_d_pitch = 18
set mc_p_roll = 80
set mc_i_roll = 30
set mc_d_roll = 18
set mc_p_yaw = 95
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 5
set fw_i_pitch = 7
set fw_ff_pitch = 50
set fw_p_roll = 5
set fw_i_roll = 7
set fw_ff_roll = 50
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 2400
set rate_accel_limit_yaw = 360
set heading_hold_rate_limit = 10
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 40
set pitch_rate = 40
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500

**Comment by digitalentity** [comment]
Config looks ok to me. With proper GPS you should be good to go.

**Comment by georgekucher** [comment]
What do you think about [this one](https://m.banggood.com/7M8M-Ublox-M8N-GPS-Module-for-APM-Pixhawk-CC3D-Naze32-F3-Flight-Control-p-1078657.html)

**Comment by digitalentity** [comment]
Nah, that's a quite crappy module. 
I'd go for a trusted BN-880 https://www.banggood.com/UBLOX-NEO-M8N-BN-880-Flight-Control-GPS-Module-Dual-Module-Compass-p-971082.html
Alternatively there's also this module which I prefer to any other so far https://www.banggood.com/Ublox-NEO-M8N-Flight-Controller-GPS-with-Protective-Shell-for-PIX-PX4-Pixhawk-p-1005394.html

**Comment by georgekucher** [comment]
Thank you!
But the sad thing is that I've already ordered it on Saturday(((
Should I cancel the order or might it work properly?
The specs are the same. Or do you have some negative feedback on it?

**Comment by blakowl** [comment]
I was having major trouble, never could get the GPS hold to work.  It
turned out it was my GPS receiver. I ordered this one and it worked
perfectly.


Usmile Beitian NEO-M8N GPS Module with Built-in HMC5883L Compass Protective
Case for Ublox PX4 PIX APM2.5/2.6 Pixhawk
https://www.amazon.com/dp/B01EH3819W?ref=yo_pop_ma_swf

**Comment by georgekucher** [comment]
Which GPS did you use when you had a trouble?
Was that the one I ordered?
https://m.banggood.com/7M8M-Ublox-M8N-GPS-Module-for-APM-Pixhawk-CC3D-Naze32-F3-Flight-Control-p-1078657.html

**Comment by blakowl** [comment]
No it was a neo6m

**Comment by georgekucher** [comment]
Oh! Ok, so fingers crossed))

**Comment by georgekucher** [comment]
Hey guys!
Finally I got a newer board (Matek F722-STD) and I still can't get my quad a GPS hold.
A GPS module seems to work fine. I think my mag QMC5883 is not working properly.
@digitalentity could you please have a look on blackbox logs?
I've even combined them with video to see more details.
p.s. I'm using cam gimbal, so rolls and pitches can be seen only on OSD bars on video.

Here is my dump:
[dump.txt](https://github.com/iNavFlight/inav/files/2046253/dump.txt)

Logs with PH attempts:
https://drive.google.com/file/d/1rp2x7gbO5cZelk0bwZj7FsBdij4XzTdE/view?usp=sharing
https://youtu.be/KpQk_ELnrug (from 2min)

Logs with yaws:
https://drive.google.com/file/d/15t4xv0xar2PE8ynqmY3m4DC4KfuCyEVk/view?usp=sharing
https://youtu.be/pAP0gguNBrE (from 4min)

**Comment by georgekucher** [comment]
Sorry for confusing. All work now. Just reconfigured from the very begin (from flashing the board) step by step. I think the problem was that I was calibrating accelerometer with mag enabled (just a guess). This time I did the accelerometer calibration first, then I've enabled the MAG and calibrated it as well. No drifting any more. Pos Hold works. Woohhooo!
