### ISSUE TITLE
accel calibration problem , omnibus fireworks v2 , inav 2.5.1  ,  2.5.2  

### ISSUE THREAD

**Issue by igor-kutuzov** [iNavFlight/inav#6081]
omnibus fireworks v2 , inav 2.5.1 2.5.2 accel calibration is not working, 2.5.0 it's working well , also Current Sensor Offset in millivolt steps 32,6 is wrong , right is around 330 i think

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by digitalentity** [comment]
Please provide a more detailed description and a video demonstrating the acc calibration issue on a board flashed with full erase.

**Comment by igor-kutuzov** [comment]
video https://youtu.be/hG2EbpWF8qQ

**Comment by digitalentity** [comment]
This is not calibration - this is gyro/acc not detected. What board is this exactly (which model, manufacturer)?

**Comment by igor-kutuzov** [comment]
omnibus fireworks v2 original, inav 2.5.0.  it's working well , 2.5.1   2.5.2. not working  
![IMG_20200831_114739](https://user-images.githubusercontent.com/70440414/91701778-6faa6280-eb80-11ea-8e85-ade464e9d56a.jpg)

**Comment by digitalentity** [comment]
This may be caused by the workaround for Omnibus F4V6. Try going to CLI and executing the following:

```
set gyro_to_use = 1
save
```

**Comment by igor-kutuzov** [comment]
it's working now, thanks.
