### ISSUE TITLE
INAV development IDE

### ISSUE THREAD

**Issue by johncook1212** [iNavFlight/inav#6094]
Hello to all,

I work on a project with a small drone and would like to code a few parts into INAV, hence I've read the "build with eclipse" document but could ramp up an appropriate IDE. also tried with older versions of eclipse but it didn't work.
Could someone please share a more up to date the required environment? and some short steps?

Thanks in advance,
John

**Comment by DzikuVx** [comment]
Just use Visual Studio Code with WSL plugin like most of devs

czw., 3 wrz 2020, 17:33 użytkownik issue-label-bot[bot] <
notifications@github.com> napisał:

**Comment by johncook1212** [comment]
@DzikuVx  - Thanks for the prompt answer. 
As I am new to FW development, are there other packages or toolchains that are required to start?
One of the target is to work on the places where PID is coded. So if there is more info regarding on where to dig it will be great :)
Best,
John

**Comment by DzikuVx** [comment]
Full text search is your friend when finding what goes where. Surprisinly PID code is in the pic.c file.

On topic of VS Code, C/C++ plugin from Microsoft and Remote - WSL plugis (also Microsoft) is all you need for starters

**Comment by johncook1212** [comment]
@DzikuVx - Thanks, I will continue from there.
John
