### ISSUE TITLE
WP - RTH land option

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#61]

**Comment by digitalentity** [comment]
I'm re-scheduling this for 1.2

**Comment by stronnag** [comment]
As this is defined by the MSP parameter 1 (mw-nav compatible), we could also treat this as parameter a bitmap and extend to other options such as no rotation on reaching the home WP, rotate in opposite direction to arm (for FPV pilots). Or perhaps rotation is better covered by a configuration option, so it applies to both manual RTH and mission RTH.

**Comment by digitalentity** [comment]
Closed by #366
