### ISSUE TITLE
PH yaw highly unstable in 1.2.1

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#611]
I really didn't intend to discover another mag issue. I tested 737c7d0 for horizon mode, in so doing I found that PH no longer works. The heading changes by c. 60° in 2 minutes (https://vimeo.com/183033739) with significant toilet-bowling.

In comparison, 1.2.0 is utterly stable (https://vimeo.com/183033738) is almost the same location and orientation.

Alas, the internal flash was full (mea culpa, so I can have the fun of repeating this experiment and getting bb logs).

Note this is the one of my 3 iNav machines that is not affected by #586.

**Comment by digitalentity** [comment]
Very interesting indeed. Looks like mag is either gone completely wrong or got disabled (if read will fail IMU will ignore the mag data).

**Comment by stronnag** [comment]
The mag is not disabled (the 'leds' in the bottom right are sensor status). The reported heading is perfectly correct --- I know this field very well. The mag is working correctly, as reported over LTM. 

The the videos are two of s series of experiments over an hour. 
1.2.0 PH yaw always stable, with or without 0f63bc6,
1.2.1 Always rotated counter-clockwise, but the reported heading direction was geospatially correct.

**Comment by digitalentity** [comment]
Hm... If possible, can you verify MAG mode?

**Comment by stronnag** [comment]
yes, and I'll explicitly enable it with PH.

**Comment by digitalentity** [comment]
Interestingly enough, current 1.2.1 is not that different from 1.2.0 - I'm puzzled.

**Comment by stronnag** [comment]
Join the puzzled club. I did not expect this .... tomorrow there will be logs

**Comment by stronnag** [comment]
Here's some more information. There is a blackbox log at http://seyrsnys.myzen.co.uk/inav_121_ph/BBLOG_155023.TXT with a variety of 1.2.0 and 1.2.1 logs in it.

Index: 1 fw: INAV 1.2.1 (737c7d0) SPRACINGF3 
Index: 2 fw: INAV 1.2.1 (737c7d0) SPRACINGF3
Index: 3 fw: INAV 1.2.1 (737c7d0) SPRACINGF3
Index: 4 fw: INAV 1.2.0 (a5f7067) SPRACINGF3
Index: 5 fw: INAV 1.2.0 (a5f7067) SPRACINGF3
Index: 6 fw: INAV 1.2.1 (737c7d0) SPRACINGF3
Index: 7 fw: INAV 1.2.0 (a5f7067) SPRACINGF3

For the purposes of this report, Indices 1 and 5 are not interesting.

Index 2, 1.2.1 : PH 'toilet bowl' and yaw variation.
Index 3: 1.2.1  : PH 'toilet bowl' and yaw variation (patched to remove  0f63bc6)
Index 4: 1.2.0 :  Stable PH, insignificant yaw variation. MAG enforced on PH (as for all subsequent tests)
Index 6: 1.2.1 : PH 'toilet bowl', no yaw variation (MAG enforced).

From index6 and the 10m range circle, the PH diameter is c. 2m, compared  with c. 0 in 1.2.0.

Index 2 (1.2.1)
![index_2](https://cloud.githubusercontent.com/assets/158229/18609577/1f8bce7e-7cfd-11e6-8423-8125da156c55.png)

Index 3: (1.2.1)
![index_3](https://cloud.githubusercontent.com/assets/158229/18609583/3c2d09da-7cfd-11e6-9280-454e6b2e6be9.png)

Index 4 (1.2.0 yeh!!!, ph circle so small you can hardly see it)
![index_4](https://cloud.githubusercontent.com/assets/158229/18609589/575e6c58-7cfd-11e6-9b8e-0ad0548d9f76.png)

Index 6 (1.2.1 PH forced MAG)
![index_6](https://cloud.githubusercontent.com/assets/158229/18609594/72134df2-7cfd-11e6-8084-b9151b366725.png)

Hardware is a 250mm dead cat aka 'Cecil the Lion', (custom mix), SPRF3 (thanks @hydra) Neo6M, BMP180, HMC5883. CLI Dump at //seyrsnys.myzen.co.uk/inav_121_ph/dc_sprf3_fp.txt

Some further tests were run on my 420mm quad (the #431 test bed), whilst they are not as extreme, behaviour under 1.2.1 is a noticeable regression v. 1.2.0, and a report on that platform will follow soon.

**Comment by digitalentity** [comment]
@stronnag thanks for testing. I'll try to have a look at the logs soon.
Did you try to `git bisect` the problem on development branch?

**Comment by digitalentity** [comment]
@stronnag just a thought:
The most significant thing that changed in the code is filtering - @martinbudden did some work porting notch filter code (see daf9ba7ddef6da91d52123b53801f01b60344500 and #592). I wonder if there's a bug in the code that affects flight performance.

**Comment by stronnag** [comment]
I will look into testing a reverted daf9ba7 / #592 build tomorrow.

**Comment by digitalentity** [comment]
Specifically, I have a hunch about this change:
https://github.com/iNavFlight/inav/commit/daf9ba7ddef6da91d52123b53801f01b60344500#diff-340f0f98312ec72859f73ed36f86423dR52

Navigation code assumes that `dT` may vary and keeping that in mind the code is using RC-filter which allows that.

It's very high probability that at very first PH cycle filtering code is called with `dT` smaller than actual position estimate update rate:
https://github.com/iNavFlight/inav/blob/master/src/main/flight/navigation_rewrite_multicopter.c#L404
and
https://github.com/iNavFlight/inav/blob/master/src/main/flight/navigation_rewrite_multicopter.c#L445-L446

Effect of that is much lower cutoff frequency and much bigger delay in PH response.

**Comment by digitalentity** [comment]
Before @martinbudden used cached `dT` in calculating the RC-filter first cycle with small `dT` value didn't cause us any trouble, but now it's affecting overall performance.

Personally, I think we shouldn't use cached `dT` in `pt1FilterApply4` which by it's name is expected to use the `dT` value that is passed to the function.

**Comment by digitalentity** [comment]
@stronnag don't revert the https://github.com/iNavFlight/inav/commit/daf9ba7ddef6da91d52123b53801f01b60344500, instead apply this patch - 1f8e360

I have a strong belief that it will solve the problem.

Good luck testing and huge thanks!

**Comment by stronnag** [comment]
OK, I have un-reverted daf9ba7 and will apply 1f8e360 and try again tomorrow --- it's wine o'clock here now.

**Comment by digitalentity** [comment]
@stronnag I forgot that you are at GMT time zone :smile: 
Good night!

**Comment by stronnag** [comment]
It's not late, just a pleasant Romanian Pinot Noir! Anyway, would you prefer I test an unadulterated pt1-filter-change branch or patch 1f8e360  into the horizon-mode-changes branch. I can do either.

**Comment by digitalentity** [comment]
Sorry, with all those time zones, jet lags and traveling I got completely
lost in time :)

Horizon code shouldn't affect PH performance, you can test any variant
which is more convenient! I hope the filtering patch will solve the issue
completely.

**Comment by stronnag** [comment]
no problem. I appreciate the time zone issue, I'm so happy I'm not doing the mega business travel thing any more.  I have the pt1-filter-change branch ready to go.

**Comment by martinbudden** [comment]
I made the change to the filter because of the desire to share the code with betaflight more than anything else. I sort of assumed `dT` remains constant, but I guess that is an invalid assumption. If the tests show it causes the problem I'll make a PR to change it back.

**Comment by stronnag** [comment]
@martinbudden, no problem. The real problem is that testing struggles to keep up with the rate of change (which is only going to get worst as the N hemisphere days shorten). Still, at least the unique (for CF derivatives) saving of acc / mag configuration makes in-field flashing and testing practical.

**Comment by martinbudden** [comment]
We have been through a phase of code refactoring, which included adding the new IO and F4 support. It's not quite finished - there's still parameter groups to go, and there's also some minor refactoring of the receiver code I want to do.

But after that I hope to spend my time on adding new stuff - so hopefully things will stop breaking and the testing requirement will be less.

**Comment by stronnag** [comment]
well if you run out of things to do, there's always the wonderful βF 'diff' and 'diff all' CLI options, which I think would save a lot of iNav uses a lot of trouble.

**Comment by stronnag** [comment]
I flew many flights (PH, RTH, WP) today on the pt1-filter-change branch and it fixes the problem. Perfect nav performance again. Please merge.

**Comment by digitalentity** [comment]
Fix merged
