### ISSUE TITLE
Altitude in OSD stuck at 0

### ISSUE THREAD

**Issue by Epiphron123** [iNavFlight/inav#6112]
## Current Behavior
Altitude in OSD always reads 0. Altitude over MSL is also stuck at the altitude of arming, even though the GPS altitude in telemetry is accurate and updates regularly (I'm using a BN880Q). I don't have a baro on my FC (mamba f405) but I'm looking forward to adding an external one over I2C. Also, the quad refuses to enter POSHOLD and RTH modes when I flip the switches, it stays in ACRO mode.

## Expected behavior
A reading of the GPS altitude in OSD. 

## Additional context
Here's a _dump_: https://pastebin.com/tUfgJQvi

---

Diatone Mamba F405mk2

# INAV/MAMBAF405 2.5.2 Aug  4 2020 / 10:42:50 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by DzikuVx** [comment]
INAV 2.5 requires BARO on multirotors. INAV 2.6 will allow for GPS only
