### ISSUE TITLE
No Hdop Telemetry sensor

### ISSUE THREAD

**Issue by Totals680** [iNavFlight/inav#6120]
When i discover sensors in my Taranis X9D+ SE i cant get hdop to show up i do get GPS, GPSspd, and Alt, i would like use hdop in the lua when i try to configure it currently in the lua the setting "GPS HDOP View" is maked with "--"

Specs 
matek F405 wingse
crossfire diversity
Matek SAM-M8Q GPS
Taranis x9d+se
full size crossfire tx

**Comment by OptimusTi** [comment]
Hello @Totals680,

Get sat lock and post a picture of the Pilot screen.

**Comment by Totals680** [comment]
Seems the signal bars are connected to the number of satalites
![image](https://user-images.githubusercontent.com/71127296/92985495-5d241780-f4f6-11ea-86c0-e478dde29c88.jpg)

**Comment by OptimusTi** [comment]
The signal bars are connected to the HDOP. Check the inav luaTelemetry docs.

**Comment by Totals680** [comment]
So what would be the reason it doesn’t give me an option to change it to a numerical value as this would be more informative

**Comment by OptimusTi** [comment]
That would be a question for the LuaTelemetry Gitahub

and maybe this?

"Options without selections have either been disabled by another option setting or are not available on your transmitter or telemetry protocol."
