### ISSUE TITLE
Vb2 cu2 definitions

### ISSUE THREAD

**Issue by jrhoad** [iNavFlight/inav#6121]
After some testing I arrived at the conclusion that the f765 cannot handle the power draw my edf requires, so I wired up an Attopilot 180a external current sensor. To my surprise I found out that even though they (vb2 and cu2) exist they are not defined and not supported by Inav. Support for external current sensor on this board (and others if this is a widespread thing) would be a game changer for myself and possibly other running high power setups. As it sits right now, I will have to change over to ardupilot to get current readings, and I really don't want to, inav is my favorite!!

**Comment by breadoven** [comment]
Why can't you connect the current sensor to the standard current ADC this board seems to have, just uses a 3.3V input ?
