### ISSUE TITLE
Inav target request for HIFIONRC F722 pro

### ISSUE THREAD

**Issue by krizw** [iNavFlight/inav#6132]
## Current Behavior
I came across the flight controller on a recommendation by Dronemesh (youtube), it has a tremendous specification, and I expected an Inav target would soon appear. I have been unable to contact the manufacturer to request their assistance with an Inav target 

## Desired Behavior
An INAV target or assistance getting one

## Suggested Solution
Development of an INAV target.

## Who does this impact? Who is this for?
Those who have purchased this flight controller with INAV in mind.

## Additional context
A Betaflight target exists as  HIFIONRC F7

**Comment by krizw** [comment]
I have contacted a retailer in the UK (cheapdrone.co.uk), that sells this board, and they are interested in supporting my target request by sending a board to a developer, Where and who is willing to assist?

**Comment by DzikuVx** [comment]
@digitalentity ?

**Comment by kang2000** [comment]
I hope this board will be able to run with INAV too.

**Comment by rob-riggen** [comment]
I have this board and it is very capable. I also would like to see an inav target for hifionrc f7 pro v2.

**Comment by digitalentity** [comment]
Retailer in the UK (cheapdrone.co.uk) wants this board to be featured in our wiki as well which is not in scope of [the hardware policy](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md). I guess that's a no-go, unfortunately, unless there is _another_ retailer or board manufacturer who's willing to follow the process.

**Comment by stronnag** [comment]
However, there is ample precedent for the board to have an entry in the official project documentation ("Board - FOO.md"), which can include links to vendors (as happens for a number of Banggood marketed MATEK boards), if that is the vendor's concern.

If they want additional publicity (mention on the Configurator, and / or in the wik ie.g. [Supported Boards](https://github.com/iNavFlight/inav/wiki/Supported-boards) (which looks horribly outdated) then perhaps there could be a support / sponsorship arrangement, should be vendor wish to be a supporter.

**Comment by digitalentity** [comment]
> If they want additional publicity (mention on the Configurator, and / or in the wik ie.g. Supported Boards (which looks horribly outdated) then perhaps there could be a support / sponsorship arrangement, should be vendor wish to be a supporter.

Yes, that's what I communicated to them. Featuring a vendor is orthogonal to adding support for a board and should be subject to a separate discussion and agreement.

**Comment by krizw** [comment]
> > If they want additional publicity (mention on the Configurator, and / or in the wik ie.g. Supported Boards (which looks horribly outdated) then perhaps there could be a support / sponsorship arrangement, should be vendor wish to be a supporter.
> 
> Yes, that's what I communicated to them. Featuring a vendor is orthogonal to adding support for a board and should be subject to a separate discussion and agreement.

Is this the end, or have there been other conversations with the vendor? I agree with your point and expected some issues regarding links to the companies product page. I hope something can be arranged that suits everyone.

**Comment by digitalentity** [comment]
There were no further email exchange. I guess the vendor is not interested in INAV supporting this board.

**Comment by ltwin8** [comment]
Hello, just saw this issue. I have worked on support for HIFIONRC F722 (AIO and Pro I hope, since both use same unified target in BF).
#6489 Please take a look. I could not test myself, because my hardware is still I shipping

**Comment by waldviertler** [comment]
Hello!

I just got the new HIFIONRC F722 Pro V2 and so I tried to flash inav_2.7.0_HIFIONRCF722.hex on it. I use the INAV Configurator 2.6.1.
But after a successful flashing it told me that I have to update the firmware - ... 
Only CLI was showing after that - and I had to go back to BF.

**Comment by ltwin8** [comment]
You need the beta of the configurator, just a Moment, i will Compiler 2.6 for you, That should work with configurator 2.6

**Comment by ltwin8** [comment]
[inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)

**Comment by waldviertler** [comment]
Thank you very much!
I try it right now.
It looks as it works, but I have to find out why the magnetometer (BN-880) is not recognized.

**Comment by ltwin8** [comment]
we came across this issue before, the "internal" i2c where Baro is connected is not the same as i2c pads afaik

**Comment by ltwin8** [comment]
you can try to solder to the i2c used by the barometer, however that requires steady hands

**Comment by waldviertler** [comment]
In BF I also had no magnetometer at first, but then I used this command in CLI:
set mag_bustype = I2C
set mag_i2c_device = 1
set mag_i2c_address = 0

-- but that does not work with INAV.

Sorry, but I am not that good in soldering...

**Comment by ltwin8** [comment]
okay, maybe you then have to set something in inav? like mag-type?
maybe go with low-ish i2c speed

**Comment by waldviertler** [comment]
Like 100 or 400 khz I2C Speed?
I have tried that - bud it does not find the magnetometer ether.

**Comment by Lagarda** [comment]
Hi to All,

I'm novice here. 
I bought recently the board FC HIFIONRC F7 PRO V2. Would you please tell me how to flash it? 
I tried to connect via rx/tx but not successfully. If i press boot button and use usb port the system stops to see it.

**Comment by waldviertler** [comment]
You have to connect the FC to your computer via a USB cable. Then open the INAV Configurator - there should a new com appear in the right upper corner. (like COM8). Go to Firmware Flasher in the menu on the left side.
Use "Load Firmware [Local]" from bottom right to load inav_2.6.0_HIFIONRCF722.hex from Itwin8 (you have to unzip the file from inav_2.6.0_HIFIONRCF722.hex.zip. Then use "Flash Firmware" (It has to be in DFU-mode for flashing).
I hope this helps!

**Comment by Lagarda** [comment]
> You have to connect the FC to your computer via a USB cable. Then open the INAV Configurator - there should a new com appear in the right upper corner. (like COM8). Go to Firmware Flasher in the menu on the left side.
> Use "Load Firmware [Local]" from bottom right to load inav_2.6.0_HIFIONRCF722.hex from Itwin8 (you have to unzip the file from inav_2.6.0_HIFIONRCF722.hex.zip. Then use "Flash Firmware" (It has to be in DFU-mode for flashing).
> I hope this helps!

Doesn't work like that. As soon as i switch to DFU the com port is lost, and it sees as unknown device

**Comment by ltwin8** [comment]
> > You have to connect the FC to your computer via a USB cable. Then open the INAV Configurator - there should a new com appear in the right upper corner. (like COM8). Go to Firmware Flasher in the menu on the left side.
> > Use "Load Firmware [Local]" from bottom right to load inav_2.6.0_HIFIONRCF722.hex from Itwin8 (you have to unzip the file from inav_2.6.0_HIFIONRCF722.hex.zip. Then use "Flash Firmware" (It has to be in DFU-mode for flashing).
> > I hope this helps!
> 
> Doesn't work like that. As soon as i switch to DFU the com port is lost, and it sees as unknown device

try impulserc driver fixer

**Comment by waldviertler** [comment]
Thats ok. In DFU mode there are no com ports. But it does not flash?

**Comment by Lagarda** [comment]
> Thats ok. In DFU mode there are no com ports. But it does not flash?

No unfortunately it doesn't flash

**Comment by waldviertler** [comment]
what happens when you dont flash - instead connect to a com? Do you see the CLI menu?

**Comment by Lagarda** [comment]
> what happens when you dont flash - instead connect to a com? Do you see the CLI menu?

Yes, cli mode is available.
Initial flash is betaflight 4.2.0

It connects to COM25, as soon as I try flash it having Inav or Betaflight it turns to COM11 (local port) when in boot mode and the flashing process endless

**Comment by Lagarda** [comment]
> what happens when you dont flash - instead connect to a com? Do you see the CLI menu?

I even tried to connect through rx/tx using usb to TTL adapter and  demostratorGUI but it says the board is read-only

**Comment by Lagarda** [comment]
![1231](https://user-images.githubusercontent.com/77048198/113710403-50624d80-96ec-11eb-93c3-d63d4ddafe0b.jpg)
![1234](https://user-images.githubusercontent.com/77048198/113710406-50fae400-96ec-11eb-9159-cc8bc0b92f7c.jpg)

**Comment by waldviertler** [comment]
What happens when you connect to USB then type `dfu` in CLI - does it connect in dfu mode?

**Comment by Lagarda** [comment]
> What happens when you connect to USB then type `dfu` in CLI - does it connect in dfu mode?

It says no such command

**Comment by waldviertler** [comment]
Hmmm. Also in Betaflight?

**Comment by krizw** [comment]
I would recommend watching some YouTube videos, painless 360, search for flashing FC firmware.On 6 Apr 2021 18:33, Lagarda ***@***.***> wrote:

What happens when you connect to USB then type dfu in CLI - does it connect in dfu mode?

It says no such command

**Comment by Lagarda** [comment]
> Hmmm. Also in Betaflight?

yeap

**Comment by Lagarda** [comment]
I have installed DFU (the impulseRC) but it conflicts with win7 kernel

**Comment by Lagarda** [comment]
![IMG_8854](https://user-images.githubusercontent.com/77048198/113763649-989c6280-9722-11eb-8561-df4b1d491170.jpg)
![IMG_8852](https://user-images.githubusercontent.com/77048198/113763660-9c2fe980-9722-11eb-81b7-4d1903908e38.jpg)
![IMG_8855](https://user-images.githubusercontent.com/77048198/113763701-a81bab80-9722-11eb-9948-469514cdd9f2.jpg)
![IMG_8853](https://user-images.githubusercontent.com/77048198/113763731-b36ed700-9722-11eb-8766-bce6d5e44e4a.jpg)
![IMG_8857](https://user-images.githubusercontent.com/77048198/113763751-b8338b00-9722-11eb-84b8-86e861b56d62.jpg)

**Comment by Lagarda** [comment]
![IMG_8865](https://user-images.githubusercontent.com/77048198/113763893-e6b16600-9722-11eb-92cc-57cb5d991056.jpg)
![IMG_8862](https://user-images.githubusercontent.com/77048198/113763908-e9ac5680-9722-11eb-94b7-ac1c67b34358.jpg)
![IMG_8864](https://user-images.githubusercontent.com/77048198/113763920-eca74700-9722-11eb-9e04-b6e4c93e2719.jpg)
![IMG_8861](https://user-images.githubusercontent.com/77048198/113763929-f3ce5500-9722-11eb-8de3-15b7c1ef1ec5.jpg)
![IMG_8859](https://user-images.githubusercontent.com/77048198/113763966-ff218080-9722-11eb-937f-ec907866382a.jpg)

**Comment by Lagarda** [comment]
I tried to rich erase via gui demonstrator, it reflects smth, but anyway i cant succeed

**Comment by waldviertler** [comment]
Usually you have to flash within BF oder INAV. I don't even know if its working with the gui demostrator...
What Itwin8 mentioned was this driver fixer from impulserc:
[https://impulserc.blob.core.windows.net/utilities/ImpulseRC_Driver_Fixer.exe](url)

**Comment by waldviertler** [comment]
![Inavflash](https://user-images.githubusercontent.com/287651/113765475-9b945480-971c-11eb-8282-630385a6e27f.jpg)

**Comment by Lagarda** [comment]
Solved
I finally managed with STM 32 CUBE programmer.
I have uploaded the inav 2.6.0 but i'm in cli mode only? What should i do then for normal gui?

**Comment by Lagarda** [comment]
I have flashed my FC with 2.7.0. but it works only in CLI mode, do you know how to fix it?

**Comment by Foxli212** [comment]
Добрый день с компосом еще не решили рроблему ?

**Comment by waldviertler** [comment]
Unfortunately not. I'm back to Betaflight.

**Comment by Foxli212** [comment]
Betaflight есть удержания позиции ?

**Comment by Lagarda** [comment]
> Добрый день с компосом еще не решили проблему ?

Нет еще. Попробовал оба компаса (магнетометра) QMC and HMC не работают.

**Comment by Lagarda** [comment]
ПОдскажите, на какой порт GPS вешать? Does anybody can tell me what port to connect GPS?

**Comment by waldviertler** [comment]
With _port_ do you mean UART?

**Comment by Lagarda** [comment]
> With _port_ do you mean UART?

yeap UART

**Comment by waldviertler** [comment]
If you soldered on like me, its on UART5.
I have:
UART2 = Crossfire Receiver
UART4 = Bluetooth (MSP)
UART5 = GPS
UART6 = DJI HD (MSP)
![gps](https://user-images.githubusercontent.com/287651/114709066-6d220500-9d2c-11eb-834c-c751faec0b43.jpg)

**Comment by Lagarda** [comment]
Thanks, for your help! Do you know if any special settings for GPS module needed? Like i have in CC3D - 33800, UBX only, 5Hz, etc

**Comment by waldviertler** [comment]
No, I dont have used any special settings for my GPS module (BN-880). GPS has worked instantly - only the magnetometer does not work with INAV. 
Which GPS module do you use?

**Comment by Lagarda** [comment]
> No, I dont have used any special settings for my GPS module (BN-880). GPS has worked instantly - only the magnetometer does not work with INAV.

What's in the code? I mean what i2c address is used? 

> Which GPS module do you use?

![gps](https://user-images.githubusercontent.com/77048198/114720245-892fa180-9d40-11eb-8ff9-f34985fe7d80.jpg)

**Comment by waldviertler** [comment]
Your module shows: VCC, RX, TX and GND. 

Module --- FlightController
VCC goes to 5V
RX goes to T5 (this is UART5)
TX goes to R5 (this is UART5)
GND goes to GND

I dont see SDA and SCL -- these go usually to the SDA and SCL pads on the flightcontroller and only they use i2c!

**Comment by virtus2232323** [comment]
When flashing in hifion rc with mamba f722 firmware, a magnetometer worked for me, it is connected to UART 3. but there is a minus, the barometer stopped working .... can someone give the firmware or instructions on how to fight !!!! Thank you!!!!

**Comment by Foxli212** [comment]
Поевилась прошивка ???

**Comment by Lagarda** [comment]
> When flashing in hifion rc f722 with mamba f722 firmware, a magnetometer worked for me, it is connected to UART 3. but there is a minus, the barometer stopped working .... can someone give the firmware or instructions on how to fight !!!! Thank you!!!!

I cant flash with Mambas firmware, the FC hangs on and no any response.

**Comment by Lagarda** [comment]
> Your module shows: VCC, RX, TX and GND.
> 
> Module --- FlightController
> VCC goes to 5V
> RX goes to T5 (this is UART5)
> TX goes to R5 (this is UART5)
> GND goes to GND
> 
> I dont see SDA and SCL -- these go usually to the SDA and SCL pads on the flightcontroller and only they use i2c!

Yes thanks! UART5 works fine. I even switched to beitian GPS module.

**Comment by Lagarda** [comment]
> If you soldered on like me, its on UART5.
> I have:
> UART2 = Crossfire Receiver
> UART4 = Bluetooth (MSP)
> UART5 = GPS
> UART6 = DJI HD (MSP)
> ![gps](https://user-images.githubusercontent.com/287651/114709066-6d220500-9d2c-11eb-834c-c751faec0b43.jpg)

Would you gimme more details how to connect FrSky LRS to UART2 (R9M slim +OTA receiver)?

**Comment by waldviertler** [comment]
![hifirion](https://user-images.githubusercontent.com/287651/121072431-7fbb3680-c7d1-11eb-9ee6-c4b17bd9ed19.jpg)
Should be like this.

**Comment by Lagarda** [comment]
> You need the beta of the configurator, just a Moment, i will Compile 2.6 for you, That should work with configurator 2.6

Hi. May I ask you to make change in the main code and add I2C addresses like for HMC5885? And make one more compilation then?

**Comment by FlyChenPiPi** [comment]
> [inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)

I have a relatively stable version of inav 2.5.2 from hifinorc manufacturer. I hope it can help you in your development
[HIFIONRC F7 INAV2.5.2 BETA.zip](https://github.com/iNavFlight/inav/files/6738007/HIFIONRC.F7.INAV2.5.2.BETA.zip)

**Comment by FlyChenPiPi** [comment]
> 非常感谢你！
> 我现在就试试。
> 它看起来可以正常工作，但我必须找出无法识别磁力计 (BN-880) 的原因。
You can try the version I sent in the previous layer. It seems to be relatively stable in my use.

**Comment by FlyChenPiPi** [comment]
> 您可以尝试焊接到气压计使用的 i2c，但这需要稳定的双手

Are pb6 and pb7 soldered to MCU? It still doesn't seem to recognize magnetometers like hmc5883

**Comment by Lagarda** [comment]
> > [inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)
> 
> I have a relatively stable version of inav 2.5.2 from hifinorc manufacturer. I hope it can help you in your development
> [HIFIONRC F7 INAV2.5.2 BETA.zip](https://github.com/iNavFlight/inav/files/6738007/HIFIONRC.F7.INAV2.5.2.BETA.zip)

Thanks! But why relatively? What are your doubts?

**Comment by FlyChenPiPi** [comment]
> > > [inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)
> > 
> > 
> > I have a relatively stable version of inav 2.5.2 from hifinorc manufacturer. I hope it can help you in your development
> > [HIFIONRC F7 INAV2.5.2 BETA.zip](https://github.com/iNavFlight/inav/files/6738007/HIFIONRC.F7.INAV2.5.2.BETA.zip)
> 
> Thanks! But why relatively? What are your doubts?

This firmware can recognize the magnetic sensor of bn880, hmc5883, etc. I've been using the 5infpv multi rotor for about half a year, and I haven't found any problems. However, some friends said that using the firmware "f722 star" will cause downtime when the ws2812 light band is on and flashing continuously, but I've never encountered it myself.

My English is very bad, the above comes from machine translation.

**Comment by Lagarda** [comment]
> > > > [inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)
> > > 
> > > 
> > > I have a relatively stable version of inav 2.5.2 from hifinorc manufacturer. I hope it can help you in your development
> > > [HIFIONRC F7 INAV2.5.2 BETA.zip](https://github.com/iNavFlight/inav/files/6738007/HIFIONRC.F7.INAV2.5.2.BETA.zip)
> > 
> > 
> > Thanks! But why relatively? What are your doubts?
> 
> This firmware can recognize the magnetic sensor of bn880, hmc5883, etc. I've been using the 5infpv multi rotor for about half a year, and I haven't found any problems. However, some friends said that using the firmware "f722 star" will cause downtime when the ws2812 light band is on and flashing continuously, but I've never encountered it myself.
> 
> My English is very bad, the above comes from machine translation.

Thanks Pal!
Don't worry on your English, evth was clear and perfect.

**Comment by Bolgor** [comment]
Anyone know about future of this target?

**Comment by DusKing1** [comment]
From my point of view, the HIFIONRC is already a dead brand and all the product from the HIFIONRC is discontinued. There's no need to give future support for a dead brand that can't even survive until INAV offers official support for them, not mentioned that they also have zero interest on INAV.

**Comment by Bolgor** [comment]
I see few new product but the new 3rd edition of f7 fc. But u have a right.

**Comment by Lagarda** [comment]
I have finally built and laready had a maiden flight with beta 2.5.2 with Mag and Baro - works well evth.

**Comment by Bolgor** [comment]
Super information. Can u share a hex file after tests? Thanks for your work;-)

**Comment by Lagarda** [comment]
> Super information. Can u share a hex file after tests? Thanks for your work;-)

Thanks! I'm not sure aout the hex. If you mean dump - is attached. If you mean the FW (not mine) is also attached earlier.

[the_tower_set](https://user-images.githubusercontent.com/77048198/145096306-8ac2f7e0-0ebe-4a33-80ca-f86840235c36.jpg)
![gps_mount](https://user-images.githubusercontent.com/77048198/145096316-5b53e66c-3a14-4c82-bab8-1d786c8e2757.jpg)
![led_beeper_mount](https://user-imag
[HIFIONRC.F7.INAV2.5.2.BETA.zip](https://github.com/iNavFlight/inav/files/7671191/HIFIONRC.F7.INAV2.5.2.BETA.zip)
es.githubusercontent.com/77048198/145096329-098d8abe-fb02-42d6-a461-d2575a4610ca.jpg)

[hifionrcf722pro2.txt](https://github.com/iNavFlight/inav/files/7671184/hifionrcf722pro2.txt)
![drone7``](https://user-images.githubusercontent.com/77048198/145096288-1d960f01-c4e4-47c5-9bfa-e9e9d328eaab.jpg)
![mag_mounting](https://user-images.githubusercontent.com/77048198/145096296-a637d0e2-ca97-4b35-9817-d63ab2d2d414.jpg)
![baro_mounting](https://user-images.githubusercontent.com/77048198/145096301-ee15b51b-7d16-42bc-a743-94bb2a53861b.jpg)
!

**Comment by Lagarda** [comment]
> Super information. Can u share a hex file after tests? Thanks for your work;-)
[HIFIONRC.F7.INAV2.5.2.BETA.zip](https://github.com/iNavFlight/inav/files/7671226/HIFIONRC.F7.INAV2.5.2.BETA.zip)

**Comment by OdinochkA15** [comment]
It's a shame that you have removed support for the HIFIONRC board. The fact that they were no longer produced and the brand died does not mean that users no longer have them. Users want to fly the hifionrc board, but your lack of support makes them leave for BF. I have this board. And I want to fly

**Comment by krizw** [comment]
It was never supported.On 24 Dec 2021 14:24, OdinochkA15 ***@***.***> wrote:
It's a shame that you have removed support for the HIFIONRC board. The fact that they were no longer produced and the brand died does not mean that users no longer have them. Users want to fly the hifionrc board, but your lack of support makes them leave for BF. I have this board. And I want to fly

**Comment by OdinochkA15** [comment]
> > [inav_2.6.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/6255222/inav_2.6.0_HIFIONRCF722.hex.zip)
> 
> I have a relatively stable version of inav 2.5.2 from hifinorc manufacturer. I hope it can help you in your development [HIFIONRC F7 INAV2.5.2 BETA.zip](https://github.com/iNavFlight/inav/files/6738007/HIFIONRC.F7.INAV2.5.2.BETA.zip)

But then what kind of firmware is it? And I remember that I was flashing this board inav

**Comment by b-zarev** [comment]
HIFIONRC F722 pro completely matches JHEMCU F7
[inav_4.0.0_JHEF7DUAL.zip](https://github.com/iNavFlight/inav/files/7918025/inav_4.0.0_JHEF7DUAL.zip)

**Comment by Bolgor** [comment]
> HIFIONRC F722 pro completely matches JHEMCU F7 [inav_4.0.0_JHEF7DUAL.zip](https://github.com/iNavFlight/inav/files/7918025/inav_4.0.0_JHEF7DUAL.zip)

Awesome information. Who knows maybe Hifionrc leave brand and started with new name - JHEMCU?

**Comment by OdinochkA15** [comment]
> Awesome information. Who knows maybe Hifionrc leave brand and started with new name - JHEMCU?

I could be wrong, but Jhemcu seems to have come before Hifionrc. And it is POSSIBLE that the latter took the payment of the former and only applied their logo, while the firmware remained the same. It's bad that I did not save the original firmware version ((

**Comment by Bolgor** [comment]
> > Awesome information. Who knows maybe Hifionrc leave brand and started with new name - JHEMCU?
> 
> I could be wrong, but Jhemcu seems to have come before Hifionrc. And it is POSSIBLE that the latter took the payment of the former and only applied their logo, while the firmware remained the same. It's bad that I did not save the original firmware version ((

What original firmware version? Hifionrc or JHEMCU?

**Comment by OdinochkA15** [comment]
Hifionrc

**Comment by Bolgor** [comment]
Betaflight / STM32F7X2 (S7X2) 4.2.0 Jun 14 2020 / 03:05:26 (8f2d21460) MSP API: 1.43
# config: manufacturer_id: HFOR, board_name: HIFIONRCF7, version: 3fe1585c
Hex: 
https://github.com/betaflight/betaflight/releases/download/4.2.0/betaflight_4.2.0_STM32F7X2.hex

Or

Betaflight / STM32F7X2 (S7X2) 4.1.0 Oct 16 2019 / 11:58:45 (c37a7c91a) MSP API: 1.42

Hex: https://github.com/betaflight/betaflight/releases/download/4.1.0/betaflight_4.1.0_STM32F7X2.hex

Maybe it'll help. I have dump file too for 4.2
