### ISSUE TITLE
Problem with building in Windows 10 with Linux Subsystem

### ISSUE THREAD

**Issue by romko1** [iNavFlight/inav#6139]
Hello,
I followed the instructions given here:
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20with%20Linux%20Subsystem.md

In step: make MATEKF405
![pb_compilation](https://user-images.githubusercontent.com/34416051/93793785-96b3fb80-fc37-11ea-956a-901d66d5ffea.jpg)
Thank you for any good advice.

**Comment by stronnag** [comment]
Perhaps you could provide us with some information to be able to help:

* The output of `uname -a`
* The output of `ruby --version`
* The output of `ls -l /bin/sh`
* The output of `echo $SHELL`

**Comment by stronnag** [comment]
And also please confirm that you ran all the steps in Ubuntu, specifically cloning the repo (and you did not unpack a zip file in Windows).

**Comment by romko1** [comment]
Of course, I used the git command (no zip file in Windows).
oh, sorry, here you go:
![pb_compilation2](https://user-images.githubusercontent.com/34416051/93801734-b8ff4680-fc42-11ea-8ef0-cc692b1fb637.jpg)

**Comment by huhen** [comment]
I have a similar problem - the reason for the parenthesis in the path variable.
eg:
>echo $PATH
>... /mnt/c/Program\ Files\ (x86)/Common\ Files/Oracle/Java/javapath ...

[This](https://github.com/microsoft/WSL/issues/1493#issuecomment-417639271) solution helped me(reset the second bit, for example 15->13)

**Comment by romko1** [comment]
Hello,
slight forward.
I added `PATH = "$ PATH: / usr / bin"` to the .bashrc file, I modified the registry: the Flags registry value should be changed from 7 to 5 as a result and got here:
![pb_compilation3](https://user-images.githubusercontent.com/34416051/93946679-27730000-fd3a-11ea-9796-f9f302bce647.jpg)

**Comment by romko1** [comment]
I came across an error why it gave me an error. The reason I do it all is to create my own firmware. So far, compilers have not minded overwriting files in the TARGET directory. The remedy is as follows: it is necessary to modify the given files directly, e.g. in Midnight Commander (MC).

I finally managed to create my own firmware. As stated in the instructions, it is FW v.2.6.0, unfortunately with the current inav configurator v.2.5.0 I can't read it. 
Please is there a newer inav configurator? Well thank you.

**Comment by stronnag** [comment]
> Please is there a newer inav configurator? Well thank you.

pretty recent builds may be found at http://seyrsnys.myzen.co.uk/inav-configurator-next/

**Comment by DzikuVx** [comment]
OK, as I experienced the problem by myself, I was able to confirm that this works:

1. apply https://github.com/microsoft/WSL/issues/1493#issuecomment-417639271
1. Restart WSL and preferably Windows as well
1. Run `cmake ..` from `build` folder again
1. `make TARGET` should be working

**Comment by MrD-RC** [comment]
Just a note. This fix worked on my PC. But, on my laptop, the value in flags  is 15 and not 7. Setting it to 5 reset the WSL environment, as if I had unregistered it.
