### ISSUE TITLE
Add dshot and rpm support for FF_F35_LIGHTNING

### ISSUE THREAD

**Issue by SilentZen** [iNavFlight/inav#6143]
## Current Behavior
No
#define USE_DSHOT
#define USE_ESC_SENSOR
 in target.h

## Desired Behavior
Have
#define USE_DSHOT
#define USE_ESC_SENSOR
 in target.h

## Suggested Solution
Add
#define USE_DSHOT
#define USE_ESC_SENSOR
 in target.h

## Who does this impact? Who is this for?
Planes to check RPM

## Additional context
Tested and compiled fine, tested flying and worked, also checked tasks and CPU utilization did not drastically increase.

**Comment by DzikuVx** [comment]
@SilentZen please propose a Pull Request with the change and if you own FF35 test
