### ISSUE TITLE
Allow GVars to be shown on OSD

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#6150]
I would like to be able to add the values of GVars to the OSD for testing purposes. 

The way I would see it working, is to be able to select GVARS 1 through 4 to add to the OSD. They could be in a new test section on the component list on the left of the OSD page. Once added, a new element is added to the OSD and can be moves like the other elements. They could be shown as GV1: 00000

This can be useful for testing logic conditions and global functions.

**Comment by joleeee** [comment]
I'll try implementing this.

**Comment by DzikuVx** [comment]
will be released with 2.6
