### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by aerocar** [iNavFlight/inav#6169]
I am absolutely new to this. Have Matek F411SE. Do I need to power it from battery and then connect USB to PC with iNAV? 
When I  click on CONNECT, nothing happens. Ports open then close. I downloaded firmware but no uploading.

**Comment by giacomo892** [comment]
This is a development environment. Please get in contact with other users on Telegram or Facebook official groups you can find here https://github.com/iNavFlight/inav for support.
