### ISSUE TITLE
Target F411WSE with one more UART

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#6175]
## Current Behavior
Currently the target has only UART1 and UART2 defined. Additionally Softserial1 and 2 can be used! But somehow this is not enough while there are pins I don't need!
Yet it is [specified to have 3 UARTS](https://www.st.com/en/microcontrollers-microprocessors/stm32f411ce.html) :
```
Up to 3 UARTs (2 x 12.5 Mbit/s, 1 x 6.25 Mbit/s), ISO 7816 interface, LIN, IrDA, modem control)
```

## Desired Behavior
I would like to make the pins something like this:
```c
#define USE_UART3
#define UART3_TX_PIN            PB6 // ### normally defined for I2C1_SCL
#define UART3_RX_PIN            PB7 // ### normally defined for I2C1_SDA
```
But is possible and just that easy? Does the WSE offer 5 UARTS like defined in inav/src/main/target/MATEKF411SE/target.h ?
If so, then a new Target with these new mappings would be awesome and save my day! 

## Who does this impact? Who is this for?
All wing pilots who need another UART for anything like Radar module, camera control or whatever is in need of a fast UART

**Comment by Pairan** [comment]
would this be possible like that @MATEKSYS ?

**Comment by MATEKSYS** [comment]
not possible.
ominibus target made many guys think TX3/RX3 pins can be used as I2C,  This is limited to certain pins.  It is not a common rule.

**Comment by Pairan** [comment]
Okay ... is there anything else I could re-define to make it happen? there are so many things I won't use so it became tempting ;)
