### ISSUE TITLE
UPDATE RSSI OSD ELEMENT FROM BETAFLIGHT FOR PROPERLY SCALED CROSSFIRE LQ READINGS (ex 1:100 instead of 99)

### ISSUE THREAD

**Issue by LOLDERS** [iNavFlight/inav#6176]
Hi there,

Recently started fling planes with a friend.  We build full RMRC Goblins with INAV and GPS functionality. We have everything dialled in with GPS Hold and RTH working. I fly with Crossfire. As we want to start going for longer range flights, I realized that Inav doesn't have the new Betaflight LQ OSD elements. Could you pull the code and update INAV for us Crossfire users to get LQ displayed the same way as in Betalfight. It is no longer 99 which was a scaling issues. It's now 2 numbers separated with a : 

Thanks!

Liam

**Comment by Pairan** [comment]
this should already be done with v2.6 if I remember right ...

**Comment by OptimusTi** [comment]
Like Pairan mentioned, this should become available in 2.6. The new stuff shows RFMode : LQ%, RSSI (dBm), VTX Power (mW), and SRN (dB). The GIF below shows a quick antenna null

![antennanull](https://user-images.githubusercontent.com/45466510/95024707-d83ea080-0652-11eb-9f3b-23688b7a037e.gif)

**Comment by DzikuVx** [comment]
If done, then let's close it
