### ISSUE TITLE
'SMART' RTH for ground based models using previous route to return to home

### ISSUE THREAD

**Issue by Painless360** [iNavFlight/inav#6184]
In the current version of INAV there is a simple RTH mode for ground based vehicles that returns the model back to the HOME location in a straight line. This is unhelpful in instances where the model has an obstruction between it and the HOME location (sandbank, logs, unpassable terrain etc.).

Would it be possible for the model to record the route taken and in the event of an RTH operation use that stored route to calculate the most direct and safe path back to the HOME location using it?

**Comment by MrD-RC** [comment]
Added with https://github.com/iNavFlight/inav/pull/7988
