### ISSUE TITLE
Modified-new target & Congfigurator version don't match

### ISSUE THREAD

**Issue by al21883** [iNavFlight/inav#6186]
I've Just created a custom target from fresh updated Inav repository. It has been labeled with 2.6.0 version, but lates configurator version is 2.5.0.
After flashing it on the board, Inav Configurator only allows me to use CLI. When I try to open any other tab, i get the message "You need to upgrade your firmware before you can use <tab name>"

Thanks in advance for your help.

**Comment by ShikOfTheRa** [comment]
You need to build the latest gui configurator. Build instructions are on the main github page for the configurator

**Comment by al21883** [comment]
Intetesting... I'll try.
Thanks!!

**Comment by al21883** [comment]
Perfect, definitively, not a bug.
Thanks again.
