### ISSUE TITLE
DJI Remote Control does not work when UART set to DJI VTX

### ISSUE THREAD

**Issue by matt454** [iNavFlight/inav#6202]
## Current Behavior
Video feed with OSD in DJI HD goggles works. 
Receiver does not.

If I enable SERIAL RX in ports for UART 1 then DJI Remote will work but the headset will not have an OSD. 

## Steps to Reproduce
Go into ports and set UART one peripherals to DJI FPV HD VTX 
Go into receiver and set to serial and SBUS fast (after reboot this is not set and remote does not have effect)

## Expected behavior
Both DJI receiver and OSD over Video feed work

## Additional context

- FC Board name and vendor: MATEK F411 WING

# version
# INAV/MATEKF411 2.5.2 Aug  4 2020 / 10:25:53 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

Dump here: https://pastebin.com/jbgJiKyA

**Comment by matt454** [comment]
<img width="1792" alt="Screenshot 2020-10-09 at 20 50 04" src="https://user-images.githubusercontent.com/7594859/95626002-652d9380-0a71-11eb-8d1a-8445359e2807.png">
<img width="1792" alt="Screenshot 2020-10-09 at 20 49 38" src="https://user-images.githubusercontent.com/7594859/95626016-68288400-0a71-11eb-9493-71d324eec1f7.png">

**Comment by digitalentity** [comment]
This is working as intended. DJI HD VTX needs 3 signal lines:

![image](https://user-images.githubusercontent.com/11059099/95652065-c0ea3200-0aee-11eb-8742-95f7b8bb250e.png)

* UART RX/TX should to connected to a serial port configured as `DJI FPV VTX`
* DJI HDL should be configured to a port configured as `Serial RX`, serial receiver should be set to `SBUS` or `SBUS fast` - aligned with the DJI FPV settings.

**Comment by matt454** [comment]
Thanks, I followed this and connected the DJI HDL wire to RX, tried, failed, switched to TX on UART 2. On both I set the UART to serial RX and on both the receiver had no connection.
