### ISSUE TITLE
 black box data is incomplete

### ISSUE THREAD

**Issue by AndreyOsipkov** [iNavFlight/inav#6214]
## Steps to Reproduce

1. read the log from the black box
2. try to open it in a view, but there is very little data there. Although the file size is large
I don't know if there is a firmware error or the controller itself. 
I would like to read this data
---

- FC Board name and vendor: matek f-722mini
- INAV version string: 2.5.2
- INAV-configurator version string: 2.5.0

[blackbox_log_2020-10-11_150753.zip](https://github.com/iNavFlight/inav/files/5361821/blackbox_log_2020-10-11_150753.zip)

**Comment by Beardyblair** [comment]
What viewer are you using?

**Comment by AndreyOsipkov** [comment]
> What viewer are you using?

blackbox-tools 0.4.4
blackbox-log-viewer 3.4.0

**Comment by theproff777** [comment]
I am seeing a similar issue.

I am on:
Omnibus F7 Pro
iNav 2.6.0
blackbox-tool 0.4.3
blackbox-log-viewer 3.4.0
INAV-configurator 2.6.0
INAV/OMNIBUSF7V2 2.6.0

I am using OpenLog and even bought a new device thinking there was an issue with the one I had.

**Comment by gcmcnutt** [comment]
See if this is related: https://github.com/iNavFlight/inav/issues/7066

**Comment by stronnag** [comment]
The log decodes correctly with current `blackbox-decode`
