### ISSUE TITLE
can't enable MSP when peripherals set to "DJI FPV VTX" on same serial port

### ISSUE THREAD

**Issue by singlag** [iNavFlight/inav#6216]
can't enable MSP when peripherals set to "DJI FPV VTX" on same serial port

when peripherals set to "DJI FPV VTX", such as "serial 5 **2097152** 115200 115200 0 115200", you can't enable MSP due to it will change to "serial 5 **1** 115200 115200 0 115200", you only can choose either one (actually, serial setting will be reset when click save if you enable both)

## Steps to Reproduce
1. enable MSP and peripherals set to "DJI FPV VTX" on same serial port
2. click save and reboot
3. serial setting will be reset to default

## Expected behavior
allow to enable MSP when peripherals set to "DJI FPV VTX" on same serial port, due to DJI FPV need enable MSP to change PID profile via goggles and need to set peripherals to "DJI FPV VTX" for OSD

---
# version
# INAV/MATEKF405SE 2.5.2 Aug  4 2020 / 10:24:57 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

- FC Board name and vendor: Matek F405 Wing
- INAV version string: # INAV/MATEKF405SE 2.5.2 Aug  4 2020 / 10:24:57 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# diff

# version
# INAV/MATEKF405SE 2.5.2 Aug  4 2020 / 10:24:57 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# start the command batch
batch start

# resources

# mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000

# servo mix
smix reset

smix 0 2 0 -95 0 -1
smix 1 3 0 -95 0 -1
smix 2 4 1 -85 0 -1
smix 3 5 1 85 0 -1
smix 4 4 2 75 0 -1
smix 5 5 2 75 0 -1
smix 6 7 13 400 0 -1

# servo
servo 2 1000 2000 1546 100
servo 3 1000 2000 1546 100
servo 7 1000 2000 1500 -100

# logic

# gvar

# gf

# feature
feature -TX_PROF_SEL
feature -SOFTSERIAL
feature MOTOR_STOP
feature GPS
feature LED_STRIP
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 0 64 115200 115200 0 115200
serial 1 0 115200 115200 0 115200
serial 4 2 115200 57600 0 115200
serial 5 2097152 115200 115200 0 115200

# led
led 0 0,0::S:3
led 1 0,1::G:6
led 2 0,2::CW:6
led 3 0,3::CW:6
led 4 0,4::CW:6
led 5 0,5::CW:6
led 6 0,6::CW:6
led 7 0,7::A:0

# color

# mode_color
mode_color 6 0 2
mode_color 6 1 6

# aux
aux 0 0 2 1800 2100
aux 1 1 1 900 1200
aux 2 8 5 1200 2100
aux 3 3 0 1925 2100
aux 4 10 3 1800 2100
aux 5 12 1 1800 2100
aux 6 36 0 1300 1700
aux 7 37 4 1975 2100
aux 8 21 5 1975 2100
aux 9 13 3 1800 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 14 10 V
osd_layout 0 1 0 14 H
osd_layout 0 3 8 6 H
osd_layout 0 4 8 6 H
osd_layout 0 6 24 14 H
osd_layout 0 7 25 14 V
osd_layout 0 8 9 14 V
osd_layout 0 9 1 2 H
osd_layout 0 11 11 11 V
osd_layout 0 12 0 14 V
osd_layout 0 13 16 8 V
osd_layout 0 14 12 12 V
osd_layout 0 15 10 8 V
osd_layout 0 20 19 1 V
osd_layout 0 21 19 0 V
osd_layout 0 22 15 9 V
osd_layout 0 23 16 12 V
osd_layout 0 24 24 3 H
osd_layout 0 26 12 7 V
osd_layout 0 28 24 12 H
osd_layout 0 31 0 0 H
osd_layout 0 32 14 11 V
osd_layout 0 33 3 8 H
osd_layout 0 34 11 2 H
osd_layout 0 41 15 9 V
osd_layout 0 42 11 9 V
osd_layout 0 46 24 1 H
osd_layout 0 47 24 0 H
osd_layout 0 85 7 7 H
osd_layout 0 86 5 12 H
osd_layout 0 87 0 10 H
osd_layout 0 96 2 4 H
osd_layout 0 100 6 4 H
osd_layout 0 105 0 1 H

# master
set gyro_hardware_lpf = 20HZ
set gyro_lpf_hz = 35
set acc_hardware = MPU6000
set acczero_x = 85
set acczero_y = -32
set acczero_z = -439
set accgain_x = 4105
set accgain_y = 4102
set accgain_z = 4063
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set rssi_channel = 17
set serialrx_provider = CRSF
set blackbox_rate_denom = 2
set throttle_idle =  7.000
set failsafe_delay = 8
set failsafe_procedure = RTH
set align_board_pitch = -30
set align_board_yaw = 1800
set model_preview_type = 28
set 3d_deadband_low = 1425
set 3d_neutral = 1475
set servo_pwm_rate = 330
set small_angle = 180
set applied_defaults = 3
set gps_sbas_mode = AUTO
set gps_min_sats = 5
set inav_w_z_baro_p =  0.350
set nav_extra_arming_safety = OFF
set nav_position_timeout = 10
set nav_min_rth_distance = 300
set nav_rth_allow_landing = FS_ONLY
set nav_rth_altitude = 12000
set nav_fw_cruise_thr = 1450
set nav_fw_min_thr = 1350
set nav_fw_max_thr = 1850
set nav_fw_climb_angle = 22
set nav_fw_dive_angle = 16
set nav_fw_loiter_radius = 6000
set nav_fw_launch_accel = 1000
set nav_fw_launch_max_angle = 90
set nav_fw_launch_thr = 1800
set nav_fw_launch_idle_thr = 1500
set nav_fw_launch_motor_delay = 100
set nav_fw_launch_timeout = 30000
set nav_fw_launch_climb_angle = 33
set osd_rssi_alarm = 60
set osd_time_alarm = 15
set osd_alt_alarm = 200
set osd_current_alarm = 30
set osd_gforce_alarm =  4.000
set osd_gforce_axis_alarm_min = -4.000
set osd_gforce_axis_alarm_max =  4.000
set osd_coordinate_digits = 8
set name = MQ-9

# profile
profile 1

set fw_ff_pitch = 100
set fw_p_roll = 4
set fw_ff_roll = 55
set fw_ff_yaw = 120
set fw_p_level = 15
set max_angle_inclination_rll = 600
set max_angle_inclination_pit = 600
set tpa_rate = 12
set rc_yaw_expo = 70
set roll_rate = 25
set pitch_rate = 14
set yaw_rate = 9

# battery_profile
battery_profile 1

set vbat_cell_detect_voltage = 423
set vbat_max_cell_voltage = 421
set battery_capacity = 1500
set battery_capacity_warning = 825
set battery_capacity_critical = 300

# end the command batch
batch end

**Comment by digitalentity** [comment]
This is working as intended. INAV doesn't support PID tuning from DJI Goggles.
