### ISSUE TITLE
Stage 1 failsafe throttle setting needs change to work with nav_use_midrc_for_althold = 1

### ISSUE THREAD

**Issue by rb1205** [iNavFlight/inav#622]
When the FC triggers failsafe stage 1 (eg. due to a loss of radio link) a smart thing to do is to set the aux channels to engage POSHOLD and ALTHOLD modes to stop the multicopter wherever it is, so that it can wait peacefully the timeouts for the failure to clear or to initiate RTH/landing/whatever.

However, this can't be achieved if nav_use_midrc_for_althold is set to 1 because there's no way to force the throttle to midrc during failsafe: it can be either set to "auto" (which is just idle) or to hold the last valid value received (VERY unsafe in this case as could cause a drop or a flyaway). We need either to make the auto policy smarter or to extend the "set" policy to throttle as well, so that one can issue a "rxfail 3 s 1500" to failsafe throttle to center.

I've made a simple change in pull request #623 that should enable the "set" failsafe mode for all flight channels.

**Comment by oleost** [comment]
"to hold the last valid value received (VERY unsafe in this case as could cause a drop or a flyaway). We need either to make the auto policy smarter or to extend the "set" policy to throttle as well, so that one can issue a "rxfail 3 s 1500" to failsafe throttle to center."

I can't see how this is safer than hold.

With these proposed settings the aircraft will spin up motors if failsafe engages while it's armed.

With the hold function it will stay at current throttle, so if your in air it will stay and on bench / ground not spin up.

**Comment by oleost** [comment]
Also, stage 1 is very short and should in neither cases cause a fly away.

**Comment by rb1205** [comment]
> With the hold function it will stay at current throttle, so if your in air it will stay

Not necesarly true. If you're flying "aggressively" or even freestyling your throttle could be any position from 0% to 100%. In those cases you could gain (or lose) up to 10 meters just in the first second, expecially if you set the failsafe to engage leveled flight (high throttle+level flight=up it goes).

> With these proposed settings the aircraft will spin up motors if failsafe engages while it's armed.

Just barely: there's a little spike of motor power when ALTHOLD mode kicks in, but the FC soon realizes that the height doesn't change and creeps back to little more than idle throttle. Besides, it's the same if you have "hold" failsafe throttle policy and engage ALTHOLD with nav_use_midrc_for_althold set to 0, which AFAIK is a very common setup.

> Also, stage 1 is very short and should in neither cases cause a fly away.

Yeah that's true, i should probably rephrase it in "uncontrolled rise in altitude".

I dunno, I agree that the "hold" approach is good enough for the typical racing quadcopter that cleanflight aims to, but for inav i feel like it's lackluster. We tipically have larger, heavier and more expensive machines, and we have more sensors able to avoid crashes, let's use them. Also, I think that failsafe stage 1 could be used as a user-tweakable configuration to wait for GPS signal before triggering emergency landing (see #733)
