### ISSUE TITLE
Board Support to add: SP Racing H7 Extreme

### ISSUE THREAD

**Issue by TheNewbFlyer** [iNavFlight/inav#6221]
This board has 2 gyros, a 400 MHz cpu, and a ton of features. Am I missing something, or can this board still not be supported?

**Comment by countxerox** [comment]
I should think if there was enough interest they would add support to sell more boards, but if not then I suppose its not worth the effort or there’s currently something else more worthwhile to do with it

**Comment by OptimusTi** [comment]
Looks like it's already in the works. See # 5827
