### ISSUE TITLE
Support for Kakute F7 mini v3

### ISSUE THREAD

**Issue by GoodGame90** [iNavFlight/inav#6231]
## Current Behavior
I have flashed my Kakute f7 mini v3 with the target KAKUTEF7MINI, but after flashing I couldn't connect to my bord via INAV, aka my FC was unresponsive, but detected as mentioned inthe device manager. All my hardware and software is updated.

## Desired Behavior

I wish to connect to my FC.

**Comment by DzikuVx** [comment]
#6138
