### ISSUE TITLE
GHST protocol support for INAV

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#6236]
Add a support for IRC GHST protocol to INAV as it would make possible to use Ghost and telemetry downlink.

@tonycake would you be willing to assist?

**Comment by tonycake** [comment]
Absolutely, is there a developer familiar with the Rx driver architecture in iNav that could provide some guidance?

**Comment by DzikuVx** [comment]
@tonycake Betaflight and INAV are quite similar in that manner. Direct copy-paste will not work, but they are pretty similar that internal code of the functions and port handling should not differ much.
