### ISSUE TITLE
Naze32 wont arm when Nav features would be programmed

### ISSUE THREAD

**Issue by WernerSch** [iNavFlight/inav#625]
Hello

i have a flip32+ and inav 1.2.  I have programmed the Nav Modes RTH and Position Hold to a switch on my Sender. When i do this i cant arm my Copter. No Mode of both are activ. I get outside to get a GPS fix. GPS works fine and the inav App shows the Position on the map. But i dont can arm my Copter. 
I delete both Nav modes. After that i can armed my Copter.
I dont understand this. GPS works buts i cant use it. Somebody can help?

kind regards
Werner

**Comment by DzikuVx** [comment]
Please provide screenshot of Cobfigurator Modes tab and or CLI dump

**Comment by WernerSch** [comment]
Hello

here the dump and the Screenshot.

2016-09-22 @ 14:30:13 -- Running - OS: Windows, Chrome: 53.0.2785.116, Configurator: 1.0.2
2016-09-22 @ 14:30:13 -- You are using an old version of INAV - Configurator. There may be a more recent version with improvements and fixes.
2016-09-22 @ 14:30:18 -- Serial port successfully opened with ID: 1
2016-09-22 @ 14:30:18 -- MultiWii API version received - 1.21.0
2016-09-22 @ 14:30:19 -- Flight controller info, identifier: INAV, version: 1.2.0
2016-09-22 @ 14:30:19 -- Running firmware released on: Sep 7 2016 11:26:35
2016-09-22 @ 14:30:19 -- Board: AFNA, version: 1
2016-09-22 @ 14:30:19 -- Unique device ID received - 0x672ff575650877067032633
2016-09-22 @ 14:31:08 -- CLI mode detected
Setup
Ports
Configuration
Failsafe
PID Tuning
Receiver
Modes
Adjustments
Servos
GPS
Motors
Race Transponder
LED Strip
Sensors
Tethered Logging
Blackbox
CLI
Note: Leaving CLI tab or pressing Disconnect will automatically send "exit" to the board. With the latest firmware this will make the controller restart and unsaved changes will be lost.

Entering CLI Mode, type 'exit' to return, or 'help'

# dump

# version

# INAV/NAZE 1.2.0 Sep  7 2016 / 11:26:35 (6cc415a)

# pflags

# Persistent config flags: 0x00000001

# dump master

# mixer

mixer QUADX
mmix reset
smix reset

# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_NRF24
feature -SOFTSPI
feature RX_PPM
feature MOTOR_STOP
feature GPS
feature FAILSAFE
feature ONESHOT125

# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map

map AETR1234

# serial

serial 0 1 115200 57600 0 115200
serial 1 2 115200 57600 0 115200

set looptime = 2000
set i2c_overclock = OFF
set gyro_sync = OFF
set gyro_sync_denom = 2
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1095
set max_throttle = 1905
set min_command = 1050
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 1050
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 300
set nav_max_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_altitude = 1000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SBUS
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1500
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = SET-THR
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set magzero_x = 58
set magzero_y = -72
set magzero_z = 230
set acczero_x = -43
set acczero_y = -1
set acczero_z = -58
set accgain_x = 4068
set accgain_y = 4086
set accgain_z = 4094

# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile

profile 0

# aux

aux 0 0 0 1925 2100
aux 1 1 1 900 1075
aux 2 2 1 1950 2100
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 65
set nav_pos_i = 120
set nav_pos_d = 10
set nav_posr_p = 180
set nav_posr_i = 15
set nav_posr_d = 100
set nav_navr_p = 10
set nav_navr_i = 5
set nav_navr_d = 8
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set flaperon_throw_offset = 250
set flaperon_throw_inverted = OFF
set mode_range_logic_operator = OR
set default_rate_profile = 0
set gimbal_mode = NORMAL
set mag_declination = 0
set mag_hold_rate_limit = 90
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_level = 20
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000

# dump rates

# rateprofile

rateprofile 0

set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500

# 

![22-09-2016 14-30-43]

(https://cloud.githubusercontent.com/assets/22211324/18748208/7e26c114-80d1-11e6-8159-558574870d41.jpg)

![22-09-2016 14-31-00](https://cloud.githubusercontent.com/assets/22211324/18748223/8b3abd9c-80d1-11e6-8daa-d600f19864d5.jpg)

the NAV modes are disabled at moment. Now i can armed the copter. Before i use AUX3 for enable NAV POSHOLD & NAV RTH

kind regards
Werner

**Comment by oleost** [comment]
How many gps sats do you have locked in? You need 6 or more,  and 3d fix

**Comment by WernerSch** [comment]
ok oleost. This i must check tomorrow. Now its dark in germany :-)

I test inav today without GPS function and have now the next Problem. I calibrate the sensors and leraned on the ESC. But the motors turn irregular. It was a horror. I have Afro ESC 30A and BlHeli
Should i make a new issue?
Can i post here a video, so its the best to see the problem

kind regards
Werner

**Comment by oleost** [comment]
New issue with as much detail as possible if your are sure it's a bug. 

If you believe it can be user error go to the forum and ask, also here provide as much info as possible. The wiki gives you a template for asking for help.

**Comment by WernerSch** [comment]
Thats it :-) Thanks for help. After 7 Sats the Copter can be armed. 
But when i test the Copter on my terrace i have only 4 Sats. Then i can not armed it and make some tests. Must i always disable the GPS feature in the inav App before?

kind regards
Werner

**Comment by rb1205** [comment]
This is a bug tracking page, you can't open an issue because you can't figure out how to set up your quad. Head over to the [forum ](http://www.rcgroups.com/forums/showthread.php?t=2495732) and ask for help there.

**Comment by oleost** [comment]
No you don't, there is a setting disabling this extra safety. 

Read Wiki and please close this issue.

**Comment by digitalentity** [comment]
@WernerSch please consider reading the wiki.
