### ISSUE TITLE
Add nav_fw_control_smoothness too OSD Adjustments

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#6267]
@MrD-RC added a lot of missing fixed Wing settings to the configurator for 2.6, including Control smoothness. 
But it would be very handy if this value could be tuned in flight to see the result in real time. 

So please add it to the in flight adjustment together with a corresponding OSD item.

**Comment by MrD-RC** [comment]
I have a working solution for this. https://youtu.be/O7uJ6SPf62U

However, the sticking point for pull request https://github.com/iNavFlight/inav/pull/6242 needs to be resolved before any new adjustments can be added to iNav.
