### ISSUE TITLE
Enable DJI : OSD_ESC_TEMPERATURE

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav#6277]
I would like to request the BLHeli_32 ESC temperature be enabled, so that it can be seen on the DJI OSD.
This would be helpful for fixed wing flight. Especially since the AIR UNIT displaces a lot of heat into the fuselage, that increases the ESC's operation temperature.

![ESC temp](https://user-images.githubusercontent.com/47995726/98603979-135d7f00-2337-11eb-8661-5071b7649b9e.PNG)
.
This OSD symbol is available in the DJI goggles in BetaFlight

**Comment by digitalentity** [comment]
DJI VTX hardware doesn't support this OSD item.

**Comment by Jetrell** [comment]
@digitalentity Thank you for informing me of that. 
I had not personally tested it with Betaflight. I had just seen so people on Youtube that showed they had the ESC temperature symbol on the OSD in the DJI goggles. 
So I assumed it would work. I noticed it didn't appear on the OSD in iNav.  So now I know why.

I'll close this now.

**Comment by Jetrell** [comment]
@digitalentity Can you please humor me with an explanation in the way MSP communicates differently with the DJI goggles in iNav compared to BetaFlight?
I just don't understand why  DJI supports ESC temperature on the OSD in BF. But can't for iNav?

Thanks

https://forum.dji.com/thread-203712-1-1.html

**Comment by digitalentity** [comment]
Ok, so this was added recently. Reopening and will look into enabling ESC temp for INAV as well

**Comment by Jetrell** [comment]
@digitalentity Thank you for adding this!
