### ISSUE TITLE
MAG (internal or external) Not detected 

### ISSUE THREAD

**Issue by gantonjo** [iNavFlight/inav#631]
Good evening.

Thanks for your efforts in making the iNavFlight.

I have a [10DOF SpRacing F3 Clone from Banggood  with internal compass](http://www.banggood.com/Upgrade-NAZE32-F3-Flight-Controller-Acro-6-DOF-Deluxe-10-DOF-for-Multirotor-Racing-p-1010232.html) and in addition I have an [Ublox Neo-7M GPS/Compass from Hobbyking](https://www.hobbyking.com/hobbyking/store/uh_viewItem.asp?idProduct=55558). The latter I used on my HKPilot 2.7 FC but now I have moved that to my newer platform.

Problem is that neither the internal compass on the F3 FC, nor the external compass in the Neo-7M is detected (connected to I2C bus). I have tried iNavFlight 1.2.0 and 1.2.1 to same result. 

To verify that this was not caused by HW error, I flashed the F3 FC with TriFlight 0.5 and there all sensors were detected and working. Going back and forth between iNavFlight 1.2.x and TriFlight 0.5 show same result. iNavFlight does not detect the compasses.

Thanks in advance for your help in getting the compass work, preferably the external one as it is on a pole.

Best regards Gantonjo

**Comment by jflyper** [comment]
@gantonjo 
Do you know what the type of mag devices are used for internal and external compass?

**Comment by gantonjo** [comment]
@jflyper 
According to the spec, the SPRF3 clone has a HMC5883 compass internally, and the external one in my GPS should be a HMC5883l digital compass. Whithout knowing anything about these, I would guess both compasses are equal.

**Comment by jflyper** [comment]
@gantonjo 
It they are both HMC5883s, then you should remove one of them (presumably the internal one).

This is a separate problem from the detection problem you have with 1.2 and later.

They have the same address, so they respond simultaneously to read and writes over the I2C bus. Because I2C bus is open collector/open drain bus, any device that pull the bus low wins. It is usually the case if two different device with the same address are present on a bus, they compete for the bus and the result is a chaos.

For your case, you have two instances of the same device, and they may be detected because they respond to identification reads in the same way. However, once they are access for compass reads, you can expect less precision, because you will loose 1s from a device if another device write 0s on a particular bit and vice versa. Differences in bits are more likely in less significant bits, thus loss of precision there.

So, even though your mags are detected in the TriFlight, you are getting less than one from two.

EDIT: This is the first case that I heard of, two HMC5883 detected and (look like) they are operational.

**Comment by gantonjo** [comment]
Thnanks, @jflyper .
Hmm... I am not sure about your answer, because even without the external compass connected, the internal one is not detected by iNav.

EDIT: I'm not at home to check sensor readings from TriFlight with only internal compass detected. Will see tonight if I have time to reflash with TriFlight to check this.

**Comment by jflyper** [comment]
@gantonjo 
Yeah, the exact twin compass problem is orthogonal to the detection problem.

**Comment by digitalentity** [comment]
INAV 1.2+ has better sensor error detection. I believe many would prefer compass to be not detected on the ground than to misbehave in flight.

**Comment by gantonjo** [comment]
I accept the reasons for improving sensor detection, if there where faults in it. But, "if it ain't broke, don't fix it".

Now I have done a test with only the onboard mag connected  (that is, external mag and GPS is disconnected). Here is the status, bootlog and dump:

`# status
System Uptime: 27 seconds, Voltage: 0 \* 0.1V (1S battery - NOT PRESENT), System load: 0.02
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611
Cycle Time: 2013, I2C Errors: 1, config size: 2004

# resource

## IO:

A00: PPM IN
A01: FREE 
A02: FREE 
A03: FREE 
A04: ADC BATTERY
A05: ADC CURRENT
A06: FREE 
A07: FREE 
A08: LED STRIP OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: FREE 
A12: FREE 
A13: FREE 
A14: FREE 
A15: FREE 
B00: SOFTSERIAL2 UART RX
B01: SOFTSERIAL2 UART TX
B02: FREE 
B03: LED1 OUT
B04: SOFTSERIAL1 UART RX
B05: SOFTSERIAL1 UART TX
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: FREE 
B10: FREE 
B11: FREE 
B12: FLASH CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C13: MPU EXTI
C14: FREE 
C15: BEEPER OUT
F00: FREE 
F01: FREE 
F03: FREE 
F04: FREE 

# bootlog

Time Evt            Description  Parameters
   0:  0          CONFIG_LOADED 
   0:  1       SYSTEM_INIT_DONE 
 500: 19   TIMER_CHANNEL_MAPPED  (0, 0, 0, 0)
 500: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 500: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 500: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 500: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (7, 6, 1, 3)
 501: 19   TIMER_CHANNEL_MAPPED  (8, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (9, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (10, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (11, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (12, 6, 2, 3)
 501:  2          PWM_INIT_DONE 
 511:  3       EXTRA_BOOT_DELAY 
1047:  9         GYRO_DETECTION  (2, 0, 0, 0)
1163: 10          ACC_DETECTION  (3, 0, 0, 0)
1210: 11         BARO_DETECTION  (3, 0, 0, 0)
1210: 12          MAG_DETECTION  (2, 0, 0, 0)
2064: 15 HMC5883L_READ_OK_COUNT  (0, 0)
2064: 16   HMC5883L_READ_FAILED  (5, 5)
2064: 17    HMC5883L_SATURATION  (5, 5)
2164: 14        MAG_INIT_FAILED 
2164: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
2164:  4       SENSOR_INIT_DONE 
2715:  5          GPS_INIT_DONE 
2715:  6     LEDSTRIP_INIT_DONE 
2765:  7    TELEMETRY_INIT_DONE 
2816:  8           SYSTEM_READY 

# dump

# version

# INAV/SPRACINGF3 1.2.0 Sep  7 2016 / 11:32:00 (6cc415a)

# pflags

# Persistent config flags: 0x00000001

# dump master

# mixer

mixer TRI
mmix reset
smix reset

# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_NRF24
feature -SOFTSPI
feature RX_PPM
feature VBAT
feature SOFTSERIAL
feature GPS
feature FAILSAFE
feature TELEMETRY
feature CURRENT_METER
feature LED_STRIP
feature ONESHOT125
feature BLACKBOX

# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map

map TAER1234

# serial

serial 0 1 115200 38400 0 115200
serial 1 0 115200 38400 0 115200
serial 2 0 115200 38400 0 115200
serial 30 32 115200 38400 0 115200
serial 31 2 115200 57600 0 115200

# led

led 0 15,0:NE:CI:1
led 1 14,1:NE:CI:1
led 2 13,2:N:C:1
led 3 12,3:N:C:1
led 4 11,4:N:CB:1
led 5 10,5:N:CB:1
led 6 10,6:S:CB:2
led 7 11,5:S:CB:2
led 8 12,4:S:CW:2
led 9 13,3:S:CW:2
led 10 14,2:ES:CI:2
led 11 15,1:ES:CI:2
led 12 0,0:NW:CI:1
led 13 1,1:NW:CI:1
led 14 2,2:N:C:1
led 15 3,3:N:C:1
led 16 4,4:N:CB:1
led 17 5,5:N:CB:1
led 18 5,6:S:CB:2
led 19 4,5:S:CB:2
led 20 3,4:S:CW:2
led 21 2,3:S:CW:2
led 22 1,2:SW:CI:2
led 23 0,1:SW:CI:2
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color

color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color

mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

set looptime = 2000
set i2c_overclock = OFF
set gyro_sync = OFF
set gyro_sync_denom = 2
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 8
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1080
set max_throttle = 1850
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 1000
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = EGNOS
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_auto_mag_decl = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 300
set nav_max_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_altitude = 1000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SPEK1024
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 1000
set current_meter_offset = 3
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 1811
set align_board_pitch = 34
set align_board_yaw = 2700
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = OFF
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = SET-THR
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SPIFLASH
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set acczero_x = 91
set acczero_y = -130
set acczero_z = -869
set ledstrip_visual_beeper = OFF
set accgain_x = 4064
set accgain_y = 4068
set accgain_z = 3992

# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile

profile 0

# aux

aux 0 1 0 900 1125
aux 1 2 0 1150 1600
aux 2 25 0 1800 1975
aux 3 4 0 1450 1675
aux 4 3 0 1350 1675
aux 5 12 2 900 1275
aux 6 14 2 1300 1700
aux 7 22 1 1300 1700
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 65
set nav_pos_i = 120
set nav_pos_d = 10
set nav_posr_p = 180
set nav_posr_i = 15
set nav_posr_d = 100
set nav_navr_p = 10
set nav_navr_i = 5
set nav_navr_d = 8
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set flaperon_throw_offset = 250
set flaperon_throw_inverted = OFF
set mode_range_logic_operator = OR
set default_rate_profile = 0
set gimbal_mode = NORMAL
set mag_declination = 220
set mag_hold_rate_limit = 90
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_level = 20
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000

# dump rates

# rateprofile

rateprofile 0

set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500
`

**Comment by digitalentity** [comment]
Is the problem still valid with 1.3-RC1?

**Comment by gantonjo** [comment]
Thanks for your answer @digitalentity. I will check this later this week, perhaps already tonight if time permits.

**Comment by digitalentity** [comment]
Thanks

**Comment by gantonjo** [comment]
Hi, @digitalentity et al. Thank you for your efforts with iNavFlight.
Tonight I tried to flash the 1.3-RC1 to my SPRF3 clone. First try did not reveal any improvements. Then I tested another board I had laying around. I had TriFlight on that, but due to baro not showing up on that board I was expecting it to be faulty. Well, that board did show mag (both in TriFlight and in iNavFlight 1.3-RC1). One thing I decided to test on this board was to remove the foam I had on the baro. Voila! There the baro came to life!

Then I removed the foam from the SPRF3 mentioned in my first posts . Now I am able to see both the GPS, baro and mag. How to see if it is the Internal mag or the mag in the UBLOX GPS I am not sure. Here you see the status and bootlog:
`# bootlog
Time Evt            Description  Parameters
   0:  0          CONFIG_LOADED 
   0:  1       SYSTEM_INIT_DONE 
 501: 19   TIMER_CHANNEL_MAPPED  (0, 0, 0, 0)
 501: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 501: 19   TIMER_CHANNEL_MAPPED  (7, 6, 1, 3)
 501: 19   TIMER_CHANNEL_MAPPED  (8, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (9, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (10, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (11, 6, 2, 3)
 501: 18  TIMER_CHANNEL_SKIPPED  (12, 6, 2, 3)
 501:  2          PWM_INIT_DONE 
 547:  9         GYRO_DETECTION  (2, 0, 0, 0)
 663: 10          ACC_DETECTION  (3, 0, 0, 0)
 708: 11         BARO_DETECTION  (3, 0, 0, 0)
 708: 12          MAG_DETECTION  (2, 0, 0, 0)
2367: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
2367:  4       SENSOR_INIT_DONE 
2918:  5          GPS_INIT_DONE 
2918:  6     LEDSTRIP_INIT_DONE 
2968:  7    TELEMETRY_INIT_DONE 
3036:  8           SYSTEM_READY 

# status

System Uptime: 138 seconds, Voltage: 0 \* 0.1V (1S battery - NOT PRESENT), System load: 0.04
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Cycle Time: 2012, I2C Errors: 2, config size: 1988
`
At the moment the weather is way to bad for testing the TriCopter (RCExplorer V4-ish) outside. Anyway, seeing the sensors again make me optimistic for a better experience. I will maybe even flash the iNavFlight that has been modified with TriFlight improvements at a later stage. Look forward to having the TriFlight performance with added iNavFlight Nav performance;-) I maybe even will build a quad to test pure iNavFlight performance, just to learn what it can and cannot do;-)

Again, thanks for your great efforts.

**Comment by digitalentity** [comment]
Looking forward to your findings.

**Comment by digitalentity** [comment]
Can we close the issue?

**Comment by gantonjo** [comment]
@digitalentity, you may close this issue. I did see some glitches in the detection of the mag after I answered you yesterday, but I believe that is due to something in my hardware. Thanks again.
