### ISSUE TITLE
Flight mode sensor never receives any data

### ISSUE THREAD

**Issue by Batperson** [iNavFlight/inav#6317]
I am running iNav2.5.2 with a Crossfire Nano rx / Radiomaster TX16S tx. I have enabled telemetry and I see all sensors except FM are receiving values. The telemetry screen on my radio never shows an * next to FM, indicating that data is not being received. I would like to resolve this problem so I can use iNav lua telemetry, could somebody help me to troubleshoot? Thanks.

![IMG_20201118_122400_resized_20201119_032540819](https://user-images.githubusercontent.com/16805899/99625854-fa22a400-2a95-11eb-95b7-e26ce19733ec.jpg)

**Comment by Xedos9er** [comment]
Downgrade to opentx 2.3.9, it´s a but introduced by 2.3.10.

**Comment by OptimusTi** [comment]
https://github.com/opentx/opentx/issues/8089

**Comment by Batperson** [comment]
Thanks Optimus, looks like TBS have documented it here: https://www.team-blacksheep.com/tbs-tracer-manual.pdf
And they have fixed it in the nightly builds, so hopefully a fix will be released soon.

**Comment by Pounii25** [comment]
> Downgrade to opentx 2.3.9, it´s a but introduced by 2.3.10.

I did't use 2.3.9... there is any way to download that .bin file? I really can't understand why companion force to the last one when you still able to flash previous version from your own back up. this function does not increase the safety and stability of the radio, it only causes problems
