### ISSUE TITLE
FrSky RXSR-FC The receiver does not work

### ISSUE THREAD

**Issue by Retlsnake** [iNavFlight/inav#6332]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---
 

- FC Board name and vendor: RXSR-FC  ( FrSky)
- INAV version string: INAV/OMNIBUSF7NXT 2.6.0 Nov 17 2020 / 11:30:27 (1a490f4d)

# version
# INAV/OMNIBUSF7NXT 2.6.0 Nov 17 2020 / 11:30:27 (1a490f4d)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**The integrated receiver does not work. It works normally (FPORT) on versions 2.5.x.**
 FrSky RXSR-FC (OMNINXT F7)

**Comment by pahlabi** [comment]
i have the same issue. after flash MatekF722 FC on inav 2.6 RXSR Fport is not working.
