### ISSUE TITLE
Default Motor Protocol, Standard or Oneshot125 ?

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav#6334]
What should the default motor protocol be with iNav 2.6 ?

The documentation states STANDARD as the default but if you load a 2.5 settings DIFF that didn't include motor_pwm_protocol because it was set to STANDARD the motor protocol in Configurator shows as ONESHOT125. If you save this and do a DIFF motor_pwm_protocol is again missing from the DIFF indicating that ONESHOT125 is the default. If you then set STANDARD, save and do a DIFF then motor_pwm_protocol = STANDARD is included showing it's no longer the default.

**Comment by stronnag** [comment]
#6029 
Perhaps someone forgot to update the documentation.

**Comment by stronnag** [comment]
addressed by #6335
