### ISSUE TITLE
NEO-M9N doesn't work with 2.6.0

### ISSUE THREAD

**Issue by slackista** [iNavFlight/inav#6338]
#### Current Behavior
Matek M9N-5883 doesn't work with 2.6.0 RC3

#### Steps to Reproduce
1. Soldier GPS to UART4.
2. Configure ports tab. Only check GPS in UART4. Save and reboot.
3. Enable "GPS for Navigation" and UBLOX7 protocol in Configuration tab. Save and reboot.

#### Expected behavior
GPS have fix(green led blinks) but no data in GPS tab and GPS has red label on top.

#### Additional context
I have connected that GPS unit with usb-ttl to u-center and works as expected.

inav-configurator 2.6-RC1
Matek405CTR
INAV/MATEKF405 2.6.0 Nov 20 2020 / 23:34:41 (27266e34)

**Comment by digitalentity** [comment]
This is strange as M9N was tested on MATEKF405SE target was was working fine. Can you post a diff of your config and photo of how it's connected?

**Comment by digitalentity** [comment]
Matek M9N-5883 connected to PIXRACER and working fine:

![Screenshot from 2020-11-23 21-16-52](https://user-images.githubusercontent.com/11059099/100010885-3ecd7880-2dd1-11eb-8a36-973683cb4462.png)

**Comment by DzikuVx** [comment]
I have M9N connected to KakuteF7 and it's also working fine with 2.6

**Comment by slackista** [comment]
```
Entering CLI Mode, type 'exit' to return, or 'help'

# diff

# version
# INAV/MATEKF405 2.6.0 Nov 20 2020 / 23:34:41 (27266e34)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# start the command batch
batch start

# resources

# mixer

# servo mix

# servo

# safehome

# logic

# gvar

# feature
feature GPS

# beeper

# map

# serial
serial 0 0 115200 115200 0 115200
serial 1 0 115200 115200 0 115200
serial 3 2 115200 115200 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout

# master
set looptime = 500
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 110
set gyro_lpf_type = PT1
set dynamic_gyro_notch_enabled = ON
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 120
set acc_hardware = MPU6000
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set receiver_type = NONE
set blackbox_rate_denom = 2
set applied_defaults = 2
set gps_provider = UBLOX7
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set mc_airmode_type = THROTTLE_THRESHOLD

# profile
profile 1

set mc_p_pitch = 44
set mc_i_pitch = 75
set mc_d_pitch = 25
set mc_i_roll = 60
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_hz = 110
set dterm_lpf_type = PT1
set dterm_lpf2_hz = 170
set dterm_lpf2_type = PT1
set d_boost_factor =  1.500
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set setpoint_kalman_enabled = ON
set setpoint_kalman_q = 200
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_yaw_expo = 70
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# battery_profile
battery_profile 1


# end the command batch
batch end
```

After command `gpspasstrough` I can see bytes in console. After closing configurator I open u-center and it works but poorly, I can't change baudrate and interface shows tearing. After minute several satiates in the u-center.

![image](https://user-images.githubusercontent.com/20584264/100016535-dd5dd780-2dd9-11eb-8297-893eda3085dd.png)
PS: I've checked connection wires with multimeter before power on.

**Comment by stronnag** [comment]
And with `gps_ublox_use_galileo = OFF` ?

**Comment by slackista** [comment]
* `gps_ublox_use_galileo = OFF` does nothing.
* `gps_auto_config = OFF`:
![image](https://user-images.githubusercontent.com/20584264/100018259-7a217480-2ddc-11eb-8883-f74bbb8bb7a9.png)

**Comment by MATEKSYS** [comment]
Just tested. M9N works fine with F405-CTR & 2.6_RC3

@slackista Type CLI "defaults", reconfigure it

**Comment by slackista** [comment]
Did it several times. Same behavior. I also have SAM-M8N and works without issues with the same UART on this FC.

**Comment by slackista** [comment]
I think my M9N unit have defect. In statistic `TimeStartup` variable doesn't increment like it should.
### NEO-M9N:
![neo-m9n](https://user-images.githubusercontent.com/20584264/100035938-7e12be00-2dff-11eb-8e09-ea381e1bc6f5.png)
### SAM-M8N:
![sam-m8n](https://user-images.githubusercontent.com/20584264/100035980-94207e80-2dff-11eb-88b7-dfe04780e53f.png)
![sam-m8n-connection](https://user-images.githubusercontent.com/20584264/100035988-97b40580-2dff-11eb-8af7-f8b5954abec0.png)
### And iNav with M8N:
![Screenshot_2020-11-24_02-34-26](https://user-images.githubusercontent.com/20584264/100036000-9da9e680-2dff-11eb-8eaa-fadbe108f0c4.png)

**Comment by slackista** [comment]
It turns out I had faulty cheap usb-ttl and unable to properly reset cfg to default values of M9N-5883. After connecting to better adapter and reset to defaults it works. Thanks guys for support!
