### ISSUE TITLE
HAKRC F722 Support

### ISSUE THREAD

**Issue by MachaCeleste** [iNavFlight/inav#6340]
I would like to request inav support of this flight controller:
https://usa.banggood.com/HAKRC-F722-Flight-Controller-OSD-BEC-5V2A-9V2A-3-9S-MPU6000-for-RC-Drone-FPV-Racing-p-1481002.html?utm_source=googleshopping&utm_medium=cpc_organic&gmcCountry=US&utm_content=minha&utm_campaign=minha-usg-pc&currency=USD&createTmp=1&utm_source=googleshopping&utm_medium=cpc_bgcs&utm_content=frank&utm_campaign=frank-ssc-usg-all-0624-11sale&ad_id=443954062698&gclid=CjwKCAiA-_L9BRBQEiwA-bm5fucuYHloyHpACkKXASjAeE5JjDWpTe3CQqjc53Vok7ZcuPbCM1oH_BoC5xoQAvD_BwE&cur_warehouse=CN

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
