### ISSUE TITLE
New target support for QiotekZealotF427

### ISSUE THREAD

**Issue by QioTek** [iNavFlight/inav#6351]
## Current Behavior
New target QiotekZealotF427

## Desired Behavior
New target support for QiotekZealotF427 

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotF427/README.md

**Comment by digitalentity** [comment]
Please have a read at https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
