### ISSUE TITLE
INAV Cinewhoop

### ISSUE THREAD

**Issue by rgp1942** [iNavFlight/inav#6359]
Is there such a thing as an RTF/PNP Cinewhoop with INAV and altitude hold?  If not, why not.  If so, where?  Thanks!

**Comment by digitalentity** [comment]
This is the wrong place to ask. INAV supports quads regardless of them being a Cinewhoop or not. The question should probably be directed to manufacturers of Cinewoop-type quads (iFlight maybe?)
