### ISSUE TITLE
INAV - Configurator reports old version

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#636]
When running INAV Configurator v1.0.2 it reports:

"You are using an old version of INAV - Configurator. There may be a more recent version with improvements and fixes."

Yet, Google extension store shows v1.0.2 as the latest.  Is there a newer version or is the app incorrectly reporting that it's old when it's not?

**Comment by digitalentity** [comment]
This is a bug. Please re-open it in Configurator repository.

**Comment by teckel12** [comment]
Configurator bug, reported correctly.
