### ISSUE TITLE
We should get rid of the docs directory and move all documentation to the wiki

### ISSUE THREAD

**Issue by martinbudden** [iNavFlight/inav#637]
Currently anyone who wants to update the documentation has to do it with a PR.

This makes it much harder for people to update the documentation.

**Comment by digitalentity** [comment]
The problem with wiki is that it's not version-specific. If we change settings the whole wiki gets affected and while code changes are not merged to official release it's confusing for users.

**Comment by martinbudden** [comment]
I'd overlooked that.
