### ISSUE TITLE
2.6 Release notes - wrong version number

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#6379]
In the **Upgrading from 2.5** section, it states 

`2. Upgrade to INAV 2.5 using the Full Erase option in the configurator.`

it should read

`2. Upgrade to INAV 2.6 using the Full Erase option in the configurator.`

![image](https://user-images.githubusercontent.com/17590174/101239182-6aa80280-36dd-11eb-9582-a56303c15f42.png)

**Comment by stronnag** [comment]
corrected
