### ISSUE TITLE
SAFEHOME Coordinate Entry

### ISSUE THREAD

**Issue by TonyCulshaw** [iNavFlight/inav#6411]
## Current Behavior
The system incorrectly interprets SAFEHOME coordinates when entering a longitude that starts with two zeros. This happens when the origin is close to the Greenwich meridian meaning the user is unable to enter codes correctly. It may be the same with latitude near the equator, but I haven't tried it.

According to Google Maps, the Lat/Long of my home point is 51.18649462696605, -0.08311700710310847

EG entering "safehome 0 1 511864946 -00831170" in the CLI 
produces coordinates of:
safehome 0 1 511864946 -831170

I would expect coordinates of 511865098 -008343460

INAV Version 2.6
Matek F411 WSE

**Comment by stronnag** [comment]
There is no problem here, the CLI uses decimal degress * 1e7. 511864946 -831170 is correct. About 500m W of the Jolly Farmer, according to mwp's safehome tool, reading the CLI data.
![Screenshot-20201214112707-970x598](https://user-images.githubusercontent.com/158229/102076285-6aa3b300-3dff-11eb-858a-03e0d84c8601.png)
