### ISSUE TITLE
[2.6] GPS - Ground Assistance Type

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav#6412]
When I set GPS Ground Assistance Type to "Disabled", using the iNav Configurator, it seems the GPS still reports SBAS as Enabled and on Auto-Scan.
I would expect Disabled.
![Ground Assistance Type - OFF](https://user-images.githubusercontent.com/31951195/102094524-ba47a600-3e22-11eb-9b41-aa348256688a.jpg)

When I set GPS Ground Assistance Type to EGNOS, using the iNav Configurator, it is not using the correct sat numbers if I'm not mistaken.
According to the EGNOS website it should be PRN 123,136.
![Ground Assistance Type - EGNOS](https://user-images.githubusercontent.com/31951195/102094745-f844ca00-3e22-11eb-94b3-afa20238d088.jpg)
![EGNOS](https://user-images.githubusercontent.com/31951195/102094909-27f3d200-3e23-11eb-85a3-8aab0c6a9f11.jpg)

I tested this by using the iNav Configurator 2.6 to change iNav settings and used the CLI "gpspassthrough" command to connect ublox u-center to read back the settings from my GPS. (Beitian BN-220)

Hope the devs can have a look to see if this is correct behaviour, or need some improvement.
Thx!

**Comment by digitalentity** [comment]
Looks like UBX8 and above have deprecated the `enabled` field in the `UBX-CFG-SBAS` message. We'll have to implement `UBX-CFG-GNSS` message to enable/disable SBAS properly on Ublox8 and Ublox9 receivers.

**Comment by 0crap** [comment]
Thx for having a look.

One more screenshot, in case you need it, to show the complete GPS configuration I normally set in the GUI.
(Ground Assistance Type set to European EGNOS is of course the one I play with, because I live in the EU.)
No other changes done on CLI.

![GPS setting](https://user-images.githubusercontent.com/31951195/102132784-5fc73d80-3e54-11eb-9ffa-65c6c4d1891e.jpg)

**Comment by 0crap** [comment]
For the fun of it I also checked BF on this issue.
They seem to have it working correctly.
When disabled it does read back from the GPS as SBAS Subsystem Disabled.
When enabled with EGNOS, I read back the correct sats.

![BF SBAS](https://user-images.githubusercontent.com/31951195/102265118-ec3a3480-3f16-11eb-9cd5-241252b79488.jpg)

**Comment by stronnag** [comment]
* If Galileo is configured, we use  `UBX-CFG-GNSS` to enable 3 SBAS channels.
* The UBLOX M8N documentation states (or at stated when we implemented this)  (5.1 SBAS (Satellite Based Augmentation Systems)) we should use 120,124,126. We set this mask (+131) (0x851).
*  we  would need to change the `UBX-CFG-SBAS` mask if the PRNs have indeed changed.

**Comment by stronnag** [comment]
ESA announcement https://egnos-user-support.essp-sas.eu/new_egnos_ops/sites/default/files/library/official_docs/service_notice_15.pdf

So we're only 3 years late ... let me try implementing that.

**Comment by 0crap** [comment]
> ESA announcement https://egnos-user-support.essp-sas.eu/new_egnos_ops/sites/default/files/library/official_docs/service_notice_15.pdf
> 
> So we're only 3 years late ... let me try implementing that.

After 3 years that pdf seems outdated as well. :-)
Here you can find the current operational sats.

https://egnos-user-support.essp-sas.eu/new_egnos_ops/egnos_system_realtime

That is: 123,136 and 126.

**Comment by stronnag** [comment]
OK, now (hack, hack) if I enable Galileo, I see :
![Screenshot-20201217193544-536x456](https://user-images.githubusercontent.com/158229/102534722-25051580-409f-11eb-9c8d-332a73ff0a57.png)

As per the latest ESA informaton

**Comment by stronnag** [comment]
However as @digitalentity noted, we still need UBX-CFG-GNSS for the non-Galileo case, otherwise we won't have SBAS on other augmentation systems.

**Comment by 0crap** [comment]
> OK, now (hack, hack) if I enable Galileo, I see :

I guess you mean "if I enable Ground Assistance Type is EGNOS".
Galileo is something else, that is the EU counterpart of GPS from the USA.

**Comment by stronnag** [comment]
I know well what Galileo is (I happened to have implemented in inav). We only enable SBAS now when Galileo is set (using `UBX-CFG-GNSS`). The PR will use `UBX-CFG-GNSS` to correctly enable SBAS as required regardless of SBAS.

**Comment by 0crap** [comment]
Ahh, thx, I see. I have Galileo always enabled indeed.
I didn't test Ground Assistance Type with Galileo switched off.
(It really helps, often 20 sats in flight.)

**Comment by stronnag** [comment]
The whole of our `UBX-CFG-GNSS` needs cleaning up, it does stuff that it shouldn't necessarily do (like set SBAS unconditionally if Galileo is enabled). So a revisit is long overdue.

**Comment by 0crap** [comment]
Thx for helping out!
SBAS switched off will help speeding up initial fix (I hope), great if it can be decoupled from the Galileo setting.

**Comment by stronnag** [comment]
It will be decoupled. And part of #6431 will be to also verify that we current PRNs for the other systems.
