### ISSUE TITLE
Altitude switches between home and gps when crsf and mavlink telemetry run simultaneously 

### ISSUE THREAD

**Issue by iblackymb** [iNavFlight/inav#6413]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior

https://photos.app.goo.gl/3AFYEz9vywPS42WZ8
Same behavior is seen sending the telemetry through 
the internal bluetooth of the crossfire module, so i think that a opentx bug is not probable.

The problem disappears using Sbus instead on crsf as serial rx protocol.

Same behavior on 3 planes, current and  default settings tested.

Steps to Reproduce

1. Crsf serial rx protocol 
2. Mavlink telemetry enabled
3. INAV 2.5.2 
4. 

## Expected behavior

Stable alt data through telemetry to be used with an antenna tracker.

## Suggested solution(s)

Maybe giving the option to disable crsf telemetry output or be able to choose between home and gps Altitude.

## Additional context

---

- FC Board name and vendor: matek f765 and f405
- INAV version string: 2.5.2

**Comment by OptimusTi** [comment]
Have you tried to delete and rediscover the telemetry sensors? I can't reproduce the problem here.

**Comment by iblackymb** [comment]
Hi Optimus.

Yes deleted them several time, tried with a new opentx model too.

**Comment by iblackymb** [comment]
Just to add some more data.

I just set up a new f765 with inav 2.6, only with the essential settings to make work the gps and rc, and I'm getting the same behavior.

**Comment by iblackymb** [comment]
> Have you tried to delete and rediscover the telemetry sensors? I can't reproduce the problem here.

Hi Optimus

Can you tell me your setup? I dont know what else to try, the only way I make it work together is disconnecting the CRSF RX cable.

**Comment by iblackymb** [comment]
Hi,

I just tried to disabling crsf, using sbus to send the rc channels and receive the telemetry by mavlink. Just realized that testing each one separately, crsf telemetry send the relative altitude, and mavlink send the gps telemetry. This is why I have this variances when both telemetry runs simultaneously.

Problem is that I need the mavlink telemetry to use my tracker, and now with inav I found useful the crsf state in the osd info.

**Comment by HazzaHFPV** [comment]
I actually have the exact same problem. Crossfire Nano Rx on latest Firmware (4.11) with an F4 flight Controller with Baro onboard and a BN880 GPS including a Compass.
Only Crossfire connected: Height above Ground received via telemetry.
Mavlink Telemetry connected: Height above sea-level shown.
Both connected: value jumps between the two as in @iblackymb video.

So far I was not able to pinpoint the problem or solve it.

**Comment by Maxeemo** [comment]
Hi, I have the exact same problem, have you solved in some way?

**Comment by b14ckyy** [comment]
if both use the same sensor ID, there is nothing we can do about it. Disable one of the sensors with the altitude you don't want in the sensors list of OTX/ETX.
