### ISSUE TITLE
WP SET POI and SET HEAD parse error in Configurator

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav#6414]
When you enter a SET POI or SET HEAD WP in the CLI, e.g. wp 4 7 0 0 0 0 0 0 0, you get a parse error and the WP isn't saved. Seems these WP types are missing from cli.c:

https://github.com/iNavFlight/inav/blob/cada68e4e263f026f089a7a4b68e0ace6290e822/src/main/fc/cli.c#L1463

These WP types are supposed to work in 2.6.0 so a bug ?

INAV 2.6.0

**Comment by stronnag** [comment]
Yes, it's a bug, mea culpa. Forgot about the CLI stuff.
