### ISSUE TITLE
Accelerometer Calibration gives conflicting results

### ISSUE THREAD

**Issue by Sedgee** [iNavFlight/inav#6443]
I'm getting a problem with a GEPRC SPAN F722 HD BT FC board using INAV 2.6. The board is aligned correctly with the arrow on top pointing forward.
I have corrected 90deg yaw which makes the graphic in Setup page correct but when I go into sensors it shows that the orientation is out by 90deg.
If I set yaw back to 0deg then the Sensors page shows it working correctly but the Setup page graphic is out 90deg on yaw.
Either way I get the same result when calibrating Accelerometer. It says it's worked and health in setup says good but craft doesn't match graphics....same as your pic.
Any help would be appreciated.
![image](https://user-images.githubusercontent.com/31081650/102951844-b2909d00-44c5-11eb-832d-851890ef7119.png)

**Comment by DzikuVx** [comment]
The calibration is performed in sensor frame of reference. The order of positions does not matter as long every position is captured and the one facing the ACC chip UP is the first one
