### ISSUE TITLE
Default number of sats to 0 if GPS lost

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#6474]
## Current Behaviour
Currently, if the GPS is lost (hardware/wiring failure) the number of satellites remain at the current value.

## Desired Behaviour
If the GPS is lost, set the number of satellites to 0.

## Who does this impact? Who is this for?
Anyone using the programming functions who use the sats as a sanity check or feature enabler. 

## Additional context
While keeping all the other data from the GPS (coords etc) is extremely useful if the GPS is lost. The same is not true for the satellite count. In fact, if used in the programming to enable switches, it could actually cause issues.

I believe that the sat count should always be kept live, including setting to 0 if the GPS is lost. There is no benefit from keeping this value persistent.

**Comment by rb1205** [comment]
Seconded. Locked sat number is used as generic GPS fix validation in logical conditions, radio telemetry, OSD etc. Forcing it to zero when GPS fix is no longer valid would make lots of sense for all those uses.

**Comment by Christoph-Hofmann** [comment]
Could someone of the devs check if this https://github.com/Christoph-Hofmann/inav/commit/2b6b2794e192ef30da913d82c880c9a57f77c896
fixes the issue.
