### ISSUE TITLE
Quadcopter not very stable in inav gps hold 

### ISSUE THREAD

**Issue by goobisoft** [iNavFlight/inav#6481]
I m using latest inav firmware i think 2.6 and in gps hold mode it does pos hold but it Twitches and wobbles not stable 
Hardware using 
Omnibus f4prov2
Blheli_s 
2212 920kv motors with 10 inch props 
Gps ublox m8n neo 
I m getting good no of satellites more then 10 atleast 
Still wobbles there is less wobble in normal angle mode but when i switch pos hold there is more wobble and twitch  and also props are balanced

**Comment by JuliooCesarMDM** [comment]
an acquaintance of mine has the same problem, the multirotor maintains the position, however when handling the sticks, the quad is unstable and also accelerates upwards.

**Comment by goobisoft** [comment]
> an acquaintance of mine has the same problem, the multirotor maintains the position, however when handling the sticks, the quad is unstable and also accelerates upwards.

Can u tell me what position and velocity options does in gps pid tunning

**Comment by JuliooCesarMDM** [comment]
default configuration that comes in inav
