### ISSUE TITLE
New Target Request; HIFIONRC F7 AIO 25A/45A

### ISSUE THREAD

**Issue by ltwin8** [iNavFlight/inav#6489]
## Current Behavior
No fitting target found in inav

## Desired Behavior
Please add a target for the board https://www.banggood.com/25_5x25_5mm-HIFIONRC-AIO-F7-Flight-Controller-OSD-Built-in-45A-Blheli_S-2-6S-4-In-1-Brushless-ESC-for-FPV-Racing-Drone-p-1716359.html?cur_warehouse=CN&rmmds=search

I think this board has good potential for inav since it has many useful features, for example:
7 full UARTs
A Barometric pressure sensor
25A or 45A 2-6S capable ESC (with BB2 MCU, G-H-30) (depending on version)
5V 3A SBEC
whoop-sized, 25.5 x 25.5 mm

## Suggested Solution

the resource assignments can be found in here:

https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/HFOR-HIFIONRCF7.config

## Who does this impact? Who is this for?
likely big part of the hobby since sub 250g is more and more important, this board is light (7.5g) and also packs good features, ESCis not only capable for whoops, I rn it on 1900kv 2306 6S 5" "toothpick-style"

## Additional context
I think the above resources are suitable to add the target to the official iNav, if I understand correctly, the target should be very close to the already supported mamba F722 FC

**Comment by ltwin8** [comment]
`/*
 * This file is part of INAV.
 *
 * INAV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * INAV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with INAV.  If not, see <http://www.gnu.org/licenses/>.
 */

//this is Part of INAV Sourcecode, more exactly target.h for MAMBAF722, modified by LTwin8 to fit HIFIONRCF7 AIO and HIFIONRCF7 PRO

//Used resources are the INAV-Code and the Betaflight unified target file https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/HFOR-HIFIONRCF7.config

#pragma once

#define USE_TARGET_CONFIG

#define TARGET_BOARD_IDENTIFIER         "HFOR"
#define USBD_PRODUCT_STRING             "HIFIONRCF7"

// ******** Board LEDs  **********************
#define LED0                            PA15                            //taken from unified target
//#define LED1                            PC14                          //No 2nd LED defined in unified target

// ******* Beeper ***********
#define BEEPER                          C15                             //taken from unified target
#define BEEPER_INVERTED


// ******* GYRO and ACC ********
#define USE_EXTI
#define GYRO_INT_EXTI                   PC4                             //taken from unified target, additional Interrupt available on C03
#define USE_MPU_DATA_READY_SIGNAL

#define MPU6000_CS_PIN                  SPI1_NSS_PIN                    //B02 & A04, taken from unified target
#define MPU6000_SPI_BUS                 BUS_SPI1

#define USE_IMU_MPU6000
#define IMU_MPU6000_ALIGN               CW90_DEG                        //taken from unified target

// *************** Baro **************************
#define USE_I2C
#define USE_I2C_DEVICE_2

#define I2C2_SCL                        PB6        // SCL pad TX3       //taken from unified target
#define I2C2_SDA                        PB7        // SDA pad RX3       //taken from unified target
#define DEFAULT_I2C_BUS                 BUS_I2C2

#define USE_BARO
#define BARO_I2C_BUS                    DEFAULT_I2C_BUS

#define USE_BARO_BMP280
#define USE_BARO_MS5611

//*********** Magnetometer / Compass *************
//#define USE_MAG
//#define MAG_I2C_BUS                     DEFAULT_I2C_BUS               //taken from unified target, no mag onboard

//#define USE_MAG_HMC5883
//#define USE_MAG_QMC5883
//#define USE_MAG_LIS3MDL

// ******* SERIAL ********
#define USE_VCP
#define USE_UART1
#define USE_UART2
#define USE_UART3
#define USE_UART4
#define USE_UART5
#define USE_UART6
//#define USE_SOFTSERIAL1
//SoftSerial not needed, 6 full UARTs available, for example: GPS, ESC-telemetry, S.Port, VTX (TBS, IRC or DJI), Bluetooth, 1 free UART left, 2 free UARTS left if using only one uart for RC&telemetry (F.Port or CRSF for example)

#define UART1_TX_PIN                    PA9                             //taken from unified target
#define UART1_RX_PIN                    PA10                            //taken from unified target

#define UART2_TX_PIN                    PA2                             //taken from unified target
#define UART2_RX_PIN                    PA3                             //taken from unified target

#define UART3_TX_PIN                    PB10                            //taken from unified target
#define UART3_RX_PIN                    PB11                            //taken from unified target

#define UART4_TX_PIN                    PA0                             //taken from unified target
#define UART4_RX_PIN                    PA1                             //taken from unified target

#define UART5_TX_PIN                    PC12                            //taken from unified target
#define UART5_RX_PIN                    PD2                             //taken from unified target

#define UART6_TX_PIN                    PC6                             //taken from unified target
#define UART6_RX_PIN                    PC7                             //taken from unified target

#define SOFTSERIAL_1_TX_PIN             PA2                             //taken from unified target
#define SOFTSERIAL_1_RX_PIN             PA2                             //taken from unified target

#define SERIAL_PORT_COUNT               8

// ******* SPI ********
#define USE_SPI

#define USE_SPI_DEVICE_1                                                //taken from unified target //MPU6000
#define SPI1_NSS_PIN                    PA4                             //taken from unified target //Gyro CS 2
#define SPI1_SCK_PIN                    PA5                             //taken from unified target
#define SPI1_MISO_PIN                   PA6                             //taken from unified target
#define SPI1_MOSI_PIN                   PA7                             //taken from unified target

#define USE_SPI_DEVICE_2                                                //taken from unified target //OSD Chip
#define SPI2_NSS_PIN                    PB12                            //taken from unified target
#define SPI2_SCK_PIN                    PB13                            //taken from unified target
#define SPI2_MISO_PIN                   PB14                            //taken from unified target
#define SPI2_MOSI_PIN                   PB15                            //taken from unified target

#define USE_SPI_DEVICE_3                                                //taken from unified target // BlackBox Flash
#define SPI3_NSS_PIN                    PC13                            //taken from unified target
#define SPI3_SCK_PIN                    PC10                            //taken from unified target
#define SPI3_MISO_PIN                   PC11                            //taken from unified target
#define SPI3_MOSI_PIN                   PB5                             //taken from unified target

// ******* ADC ********
#define USE_ADC
#define ADC_CHANNEL_1_PIN               PC2                             //taken from unified target
#define ADC_CHANNEL_2_PIN               PC0                             //taken from unified target
#define ADC_CHANNEL_3_PIN               PC1                             //taken from unified target

#define VBAT_ADC_CHANNEL                ADC_CHN_1
#define RSSI_ADC_CHANNEL                ADC_CHN_2
#define CURRENT_METER_ADC_CHANNEL       ADC_CHN_3

#define VBAT_SCALE_DEFAULT              1100                            //unknown

// ******* OSD ********
#define USE_OSD                                                         //matches unified target
#define USE_MAX7456
#define MAX7456_SPI_BUS                 BUS_SPI2
#define MAX7456_CS_PIN                  SPI2_NSS_PIN

//******* FLASH ********
#define USE_FLASHFS                                                     //matches unified target, exact chip type not known yet, but seems right, the 30.5mm HIFIONRC has 16MB BB
#define USE_FLASH_M25P16
#define M25P16_CS_PIN                   SPI3_NSS_PIN
#define M25P16_SPI_BUS                  BUS_SPI3

#define ENABLE_BLACKBOX_LOGGING_ON_SPIFLASH_BY_DEFAULT                  //yes, no SD Card

//************ LEDSTRIP *****************
#define USE_LED_STRIP
#define WS2811_PIN                      PA8                             //taken from unified target

// ******* FEATURES ********
#define DEFAULT_RX_FEATURE              FEATURE_RX_SERIAL
#define SERIALRX_UART                   SERIAL_PORT_USART2              //taken from Product Page
#define SERIALRX_PROVIDER               SERIALRX_SBUS

#define DEFAULT_FEATURES                (FEATURE_OSD | FEATURE_TELEMETRY) //no SoftSerial

#define TARGET_IO_PORTA                 0xffff                          //not sure
#define TARGET_IO_PORTB                 0xffff                          //not sure
#define TARGET_IO_PORTC                 0xffff                          //not sure
#define TARGET_IO_PORTD                 (BIT(2))                        //not sure

#define MAX_PWM_OUTPUT_PORTS            8                               //not sure, would guess 4, because its aiming towards quadcopters
#define TARGET_MOTOR_COUNT              4                               //taken from unified target, Motors 1,2,3,4 are located on PB0, PB1, PB4, PB3

// ESC-related features
#define USE_DSHOT
#define USE_SERIALSHOT
#define USE_ESC_SENSOR
#define USE_SERIAL_4WAY_BLHELI_INTERFACE
`

Above is a modified target.h file (taken from MAMBAF722) and modified to fit the HIFIONRCF7 AIO and HIFIONRCF7 PRO

**Comment by ltwin8** [comment]
`/*
 * This file is part of INAV.
 *
 * INAV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * INAV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with INAV.  If not, see <http://www.gnu.org/licenses/>.
 */


//this is Part of INAV Sourcecode, more exactly target.h for MAMBAF722, modified by LTwin8 to fit HIFIONRCF7 AIO and HIFIONRCF7 PRO

//Used resources are the INAV-Code and the Betaflight unified target file https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/HFOR-HIFIONRCF7.config


#include <stdbool.h>
#include <stdint.h>

#include <platform.h>

#include "common/axis.h"

#include "config/config_master.h"
#include "config/feature.h"

#include "drivers/sensor.h"
#include "drivers/pwm_esc_detect.h"
#include "drivers/pwm_output.h"
#include "drivers/serial.h"

#include "fc/rc_controls.h"

#include "flight/failsafe.h"
#include "flight/mixer.h"
#include "flight/pid.h"

#include "rx/rx.h"

#include "io/serial.h"

#include "sensors/battery.h"
#include "sensors/sensors.h"

#include "telemetry/telemetry.h"

void targetConfiguration(void)
{
   //no hardwired UARTs, no Softserial
}
`

Above is a modified config.c file (taken from MAMBAF722) and modified to fit the HIFIONRCF7 AIO and HIFIONRCF7 PRO

**Comment by ltwin8** [comment]
[HIFIONRCF722.zip](https://github.com/iNavFlight/inav/files/5810055/HIFIONRCF722.zip)

Hello, I compiled the file and it seems to work, sadly still not able to test since the hardware is on its way to me from china.
@digitalentity @DzikuVx 

I hope you can Pull this piece into the main code if you approve it.

**Comment by krizw** [comment]
> [HIFIONRCF722.zip](https://github.com/iNavFlight/inav/files/5810055/HIFIONRCF722.zip)
> 
> Hello, I compiled the file and it seems to work, sadly still not able to test since the hardware is on its way to me from china.
> @digitalentity @DzikuVx
> 
> I hope you can Pull this piece into the main code if you approve it.

Where is the hex file for me to try?

**Comment by ltwin8** [comment]
> > [HIFIONRCF722.zip](https://github.com/iNavFlight/inav/files/5810055/HIFIONRCF722.zip)
> > Hello, I compiled the file and it seems to work, sadly still not able to test since the hardware is on its way to me from china.
> > @digitalentity @DzikuVx
> > I hope you can Pull this piece into the main code if you approve it.
> 
> Where is the hex file for me to try?

hello, there you go.
but please, be careful! I have not really programmed iNav before, but I guess it should be okay, Please test the Gyro and motors before flying without props...

even if this does not work one should be able to flash back to Betaflight "Note: STM32 bootloader is stored in ROM, it cannot be bricked."

I am more into hardware than deep dive in iNav Software, but I think it should not harm your hardware (besides if it crashes or so)

maybe you can test without props and let me know

thanks for your help


[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5810234/inav_2.7.0_HIFIONRCF722.hex.zip)

**Comment by krizw** [comment]
Hello, I had a very quick go with your Hex, on the bench, the barometer 
was unavailable (RED), the battery voltage read about 1.4v and the DJI 
OSD was not showing. Motors ran and were in the correct order, CRSF 
receiver worked and showed correctly in a tab, GPS worked, Accelerometer 
calibrated ok. Ports tab showed Uarts 1 to 6 ok, but then another Uart 1 
between 5 and 6.

Thank you for your work, I hope we can get an official build eventually. 
I will try any other versions you make.

Cheers

Chris
------ Original Message ------

**Comment by ltwin8** [comment]
Thanks for testing.

motors ran on dshot?
which UART was the DJI OSD? have you tried all? maybe I mixed something up (for example inav uart2 is board uart5)
- sorry edit while writing: I skip this for now, I remember something that DJI OSD and Inav don't like each other.

Battery not working, OK I thought that would be so, have you tried and adjusted the scale? I had no idea and just set 110 if that not works, what does *Analog* RSSI and current show?
background: VBAT, RSSI, CURR are all ADC Channels, maybe I mixed them up and as soon as you plug the lipo for example RSSI shows strange behavior

CRSF Worked on a UART? numbering correct? 

Baro was unavailable that means the I2C is not working, looking into it.


second UART1 shown, okay, I look into that

**Comment by ltwin8** [comment]
Update on Baro: I am looking into the type, I2C Bus should be okay, PB06 as SCL PB07 as SDA

I am looking into #define USE_I2C_PULLUP

attached a new hex, should address I2C

[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5810768/inav_2.7.0_HIFIONRCF722.hex.zip)

**Comment by ltwin8** [comment]
Duplicated UART, my bad, sorry, soft serial was still in there...
updated 👍 

[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5810791/inav_2.7.0_HIFIONRCF722.hex.zip)

**Comment by krizw** [comment]
Dshot 300 workedDJI osd was on UART 1Crsf was on UART 2ESC telemetry on UART 3BLUETOOTH on UART 4 (forgot to test) MSPGPS on UART 5All connections worked in BF 4.2.4On 13 Jan 2021 19:31, ltwin8 <notifications@github.com> wrote:
Thanks for testing.
motors ran on dshot?
which UART was the DJI OSD? have you tried all? maybe I mixed something up (for example inav uart2 is board uart5)
sorry edit while writing: I skip this for now, I remember something that DJI OSD and Inav don't like each other.
Battery not working, OK I thought that would be so, have you tried and adjusted the scale? I had no idea and just set 110 if that not works, what does Analog RSSI and current show?
background: VBAT, RSSI, CURR are all ADC Channels, maybe I mixed them up and as soon as you plug the lipo for example RSSI shows strange behavior
CRSF Worked on a UART? numbering correct?
Baro was unavailable that means the I2C is not working, looking into it.
second UART1 shown, okay, I look into that

**Comment by ltwin8** [comment]
Okay, shot working should mean timer correct, good thing

Maybe you can try again DJI osd, one UART1 was soft serial with wrong pins in disguise, so maybe in the last uploaded hex it works.

does the blackbox work?

Can you upload fonts to the analog osd? (I know you use digital just to see if the SPI Interface to it works, I think iNav errors out if it can not communicate with the OSD during uploading)

Does the Battery voltage show correct after "set vbat_scale = 1100" ?

so just to keep track the issues
-DJI OSD not working
-VBAT wrong Value
-duplicated UART 
-Baro not working

I will update List when issue is fixed

**Comment by krizw** [comment]
DJI osd workingOsd analogue font loadsBatt voltage works with 1100 scaleBaro working ( on bench not flown )Data flash shows data saved ( not checked data content )Good workOn 13 Jan 2021 20:04, ltwin8 <notifications@github.com> wrote:
Okay, shot working should mean timer correct, good thing
Maybe you can try again DJI osd, one UART1 was soft serial with wrong pins in disguise, so maybe in the last uploaded hex it works.
does the blackbox work?
Can you upload fonts to the analog osd? (I know you use digital just to see if the SPI Interface to it works, I think iNav errors out if it can not communicate with the OSD during uploading)
Does the Battery voltage show correct after "set vbat_scale = 1100" ?
so just to keep track the issues
-DJI OSD not working
-VBAT wrong Value
-duplicated UART
-Baro not working
I will update List when issue is fixed

**Comment by ltwin8** [comment]
Okay, thanks for testing.

If any issues please update me

I can not guarantee, but I think flying should be okay.

**Comment by krizw** [comment]
could you define the magnetometer, please

//*********** Magnetometer / Compass *************
//#define USE_MAG
//#define MAG_I2C_BUS DEFAULT_I2C_BUS //taken from unified target, no mag onboard

//#define USE_MAG_HMC5883
//#define USE_MAG_QMC5883
//#define USE_MAG_LIS3MDL

**Comment by krizw** [comment]
Could you add the magnetometer, please?


------ Original Message ------

**Comment by ltwin8** [comment]
Hello,

AFAIK there is no magnetometer on the board?

Maybe add one through I2C?

**Comment by krizw** [comment]
I have added one on the I2C, i think drivers required, it's not working as it is.On 23 Jan 2021 21:00, ltwin8 <notifications@github.com> wrote:
Hello,
AFAIK there is no magnetometer on the board?
Maybe add one through I2C?

**Comment by ltwin8** [comment]
Okay, i will compile a version for it

**Comment by ltwin8** [comment]
I hope this will help you

[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5861062/inav_2.7.0_HIFIONRCF722.hex.zip)

**Comment by krizw** [comment]
Obviously, I have no idea, but this is how it is set up on my matek 
f405. Thanks in advance.


// *************** I2C ****************************// SLC clash with 
WS2812 LED#ifdef MATEKF405OSD    // OSD - no native I2C    #define 
USE_I2C    #define USE_I2C_DEVICE_EMULATED    #define 
I2C_DEVICE_EMULATED_SHARES_UART3    #define SOFT_I2C    #define 
SOFT_I2C_SCL            PC10 //TX3 pad    #define SOFT_I2C_SDA 
PC11 //RX3 pad    #define DEFAULT_I2C_BUS         BUS_I2C_EMULATED#else 
// AIO / CTR / STD    #define USE_I2C    #define USE_I2C_DEVICE_1 
#define I2C1_SCL                PB6    #define I2C1_SDA 
PB7    #define DEFAULT_I2C_BUS         BUS_I2C1#endif#define 
USE_BARO#define BARO_I2C_BUS                DEFAULT_I2C_BUS#define 
USE_BARO_BMP280#define USE_BARO_MS5611#define USE_BARO_BMP085#define 
USE_BARO_DPS310#define USE_MAG#define MAG_I2C_BUS 
DEFAULT_I2C_BUS#define USE_MAG_AK8963#define USE_MAG_AK8975#define 
USE_MAG_HMC5883#define USE_MAG_QMC5883#define USE_MAG_IST8310#define 
USE_MAG_IST8308#define USE_MAG_MAG3110#define USE_MAG_LIS3MDL#define 
TEMPERATURE_I2C_BUS         DEFAULT_I2C_BUS#define 
USE_RANGEFINDER#define USE_RANGEFINDER_MSP#define 
USE_RANGEFINDER_HCSR04_I2C#define RANGEFINDER_I2C_BUS 
DEFAULT_I2C_BUS#define PITOT_I2C_BUS               DEFAULT_I2C_BUS


------ Original Message ------

**Comment by krizw** [comment]
You are fast, wow.


------ Original Message ------

**Comment by ltwin8** [comment]
i have uncommented 

`
#define MAG_I2C_BUS DEFAULT_I2C_BUS //taken from unified target, no mag onboard

#define USE_MAG_HMC5883
#define USE_MAG_QMC5883
#define USE_MAG_LIS3MDL
`

that should do.

**Comment by krizw** [comment]
> I hope this will help you
> 
> [inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5861062/inav_2.7.0_HIFIONRCF722.hex.zip)

no improvement.

**Comment by ltwin8** [comment]
Oh okay, could you try if your setup works on BF? (the baro itself?)

**Comment by krizw** [comment]
> Oh okay, could you try if your setup works on BF? (the baro itself?)

BARO works on both BF and INAV
MAG does not work on either

**Comment by ltwin8** [comment]
sorry, I mean the mag, okay, if it not works maybe is the wiring wrong?

**Comment by krizw** [comment]
You cannot even get the MAG icon in RED (settings correct, but no data), 
even if my wiring were wrong (2 wires) the MAG icon would be red.

------ Original Message ------

**Comment by ltwin8** [comment]
i will test it once I have the hardware and mill test where the Pads are connected.

so mag do not work in BF either?

**Comment by Bolgor** [comment]
Hello. I had problem witch beitian BN 880 mag on Hifionrc f7 pro on betaflight. I am a beginner but I managed to turn on the magnitometr after resource remaping of pads and few changes in cliI can send the dump file witch my configuration but I dont know IT is correct. Maybe that will help you.

**Comment by ltwin8** [comment]
I guess you used UART 3 for that?

**Comment by Bolgor** [comment]
Probably. I check it tomorrow.

**Comment by ltwin8** [comment]
https://www.st.com/resource/en/datasheet/stm32f723vc.pdf

Page 81/82, so you used i2c capable pins...

done that in my repo for the AIO where UART 3 should be i2c

but I do not know inav well enough to know how to use 2 i2c (internal baro, external mag for example) Busses

**Comment by Bolgor** [comment]
After only remapping mag didn't work. I change few options in cli and mag started:

set align_mag = CW270FLIP
set mag_align_roll = 0
set mag_align_pitch = 1800
set mag_align_yaw = 2700
set mag_bustype = I2C
set mag_i2c_device = 2
set mag_i2c_address = 0
set mag_spi_device = 2
set mag_hardware = AUTO
set mag_declination = 0
set mag_calibration = 50,-40,-260
set baro_bustype = I2C
set baro_spi_device = 1
set baro_i2c_device = 1
set baro_i2c_address = 0
set baro_hardware = AUTO

But I don't know that parameters will help you.

**Comment by krizw** [comment]
Did the mag show up in red after you remapped, and then blue after CLI changes?On 27 Jan 2021 08:06, Bolgor <notifications@github.com> wrote:
After only remapping mag didn't work. I change few options in cli and mag started:
set align_mag = CW270FLIP
set mag_align_roll = 0
set mag_align_pitch = 1800
set mag_align_yaw = 2700
set mag_bustype = I2C
set mag_i2c_device = 2
set mag_i2c_address = 0
set mag_spi_device = 2
set mag_hardware = AUTO
set mag_declination = 0
set mag_calibration = 50,-40,-260
set baro_bustype = I2C
set baro_spi_device = 1
set baro_i2c_device = 1
set baro_i2c_address = 0
set baro_hardware = AUTO
But I don't know that parameters will help you.

**Comment by Bolgor** [comment]
I don't remember about red blinking light (remapped that few months ago) after remapping but maybe this movie will be helpful:
https://youtu.be/coHFI4fsTes

**Comment by krizw** [comment]
What remapping did you do, to get the mag working?

------ Original Message ------

**Comment by ltwin8** [comment]
[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5882661/inav_2.7.0_HIFIONRCF722.hex.zip)
 maybe you can try this, SCL on on TX3 and SDA on RX3

**Comment by LeonardovichD** [comment]
Hi! I have hifionrc board and want to work it with inav. Could Ihelp you with some tests? I'm  able to do some one by one steps, but i'm noob in programming

**Comment by ltwin8** [comment]
can you measure where the SDA and SCL Pads are connected to? which cpu pins

**Comment by LeonardovichD** [comment]
> can you measure where the SDA and SCL Pads are connected to? which cpu pins

If you write how to do this)

**Comment by ltwin8** [comment]
you take a multimeter with very fine tips and measure in resistance mode where the pads are connected to, continuity testing

**Comment by LeonardovichD** [comment]
![Uploading IMG_20210127_234829.jpg…]()

**Comment by LeonardovichD** [comment]
10pin scl
11pin sda

**Comment by LeonardovichD** [comment]
https://drive.google.com/file/d/1Ace4vfIft7m2OiXP0cshKjpYQP5rGQcT/view?usp=drivesdk

**Comment by Bolgor** [comment]
I made this changes:
resource MOTOR 5 C09 remapping to resource SERIAL_RX 3 C09 after that resource MOTOR 5 NONE
resource MOTOR 6 C08 remapping to resource SERIAL_TX 3 C08 after that resource MOTOR 6 NONE
resource I2C_SCL 2 NONE remapping to resource I2C_SCL 2 B10
resource I2C_SDA 2 NONE remapping to resource I2C_SDA 2 B11

**Comment by LeonardovichD** [comment]
It was helpful?

**Comment by ltwin8** [comment]
Pin 10 and pin 11 are needed the uart3 pins regarding to configuration. so an additional bus

**Comment by ltwin8** [comment]
thank you, that was helpful

**Comment by ltwin8** [comment]
just let me change something, I can not #define use_mag because error.

I hope it is enough to set external i2c bus default and then do it in configurator

**Comment by ltwin8** [comment]
[inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5883062/inav_2.7.0_HIFIONRCF722.hex.zip)

Default bus set to the Pads (Port B bit 10 and 11), UART3 NOT usable, that are the i2c2 pins
i2c1 (internal, connected to Baro) not any more default


when testing please report back if:

- baro working
- external i2c working (either SDA SCL Pads or uart3 pads (for example for the AIO))

**Comment by Shothertz** [comment]
Hi! The pic https://drive.google.com/file/d/1Ace4vfIft7m2OiXP0cshKjpYQP5rGQcT/view?usp=drivesdk is 90° out.
SDA is on pin 59 (PB7) and SCL on pin 58 (PB6)
The internal baro and the external mag runs on the same i2c bus
resource I2C_SCL 1 B06
resource I2C_SDA 1 B07

Set the mag i2c on adresses 0

set mag_bustype = I2C
set mag_i2c_device = 1
**set mag_i2c_address = 0**
set mag_spi_device = 0
set mag_hardware = AUTO
set mag_declination = 0
set mag_calibration = 0,0,0
set baro_bustype = I2C
set baro_spi_device = 0
set baro_i2c_device = 1
set baro_i2c_address = 0
set baro_hardware = AUTO

Tested and working on mine HIFIONRC F7 PRO V2 + GPS BN880 + mag on BetaFlight

**Comment by Shothertz** [comment]
![STM32F722xx_pinout_SDA_SCL](https://user-images.githubusercontent.com/22113550/106063497-8e456300-60f8-11eb-9763-ce9fe083096a.PNG)

**Comment by krizw** [comment]
> Hi! The pic https://drive.google.com/file/d/1Ace4vfIft7m2OiXP0cshKjpYQP5rGQcT/view?usp=drivesdk is 90° out.
> SDA is on pin 59 (PB7) and SCL on pin 58 (PB6)
> The internal baro and the external mag runs on the same i2c bus
> resource I2C_SCL 1 B06
> resource I2C_SDA 1 B07
> 
> Set the mag i2c on adresses 0
> 
> set mag_bustype = I2C
> set mag_i2c_device = 1
> **set mag_i2c_address = 0**
> set mag_spi_device = 0
> set mag_hardware = AUTO
> set mag_declination = 0
> set mag_calibration = 0,0,0
> set baro_bustype = I2C
> set baro_spi_device = 0
> set baro_i2c_device = 1
> set baro_i2c_address = 0
> set baro_hardware = AUTO
> 
> Tested and working on mine HIFIONRC F7 PRO V2 + GPS BN880 + mag on BetaFlight

Yes that's working for me also in Betaflight, now we just need to convert the working settings to INAV, great job.

**Comment by LeonardovichD** [comment]
What's next? I need to install hex file?

**Comment by LeonardovichD** [comment]
Board does not connected after flashing.
"No configuration received within 10 sec"

**Comment by LeonardovichD** [comment]
Upgrade 30.5x30.5mm HIFIONRC F722 Pro V2 F7 OSD Bluetooth Flight Controller w/ 5V 10V BEC & 45A BL_32 3-6S 4in1 ESC Stack for DJI Air Unit / Caddx RC Drone
https://www.banggood.com/Upgrade-30_5x30_5mm-HIFIONRC-F722-Pro-V2-F7-OSD-Bluetooth-Flight-Controller-w-or-5V-10V-BEC-and-45A-BL_32-3-6S-4in1-ESC-Stack-for-DJI-Air-Unit-or-Caddx-RC-Drone-p-1674952.html?cur_warehouse=CN&rmmds=search
Maybe it's because I have another hifionrc. But it will be great if it works)

**Comment by LeonardovichD** [comment]
I figured out what was happened: my fc burnt after flashing

**Comment by ltwin8** [comment]
how did the FC burn? that should not happen only because of flashing.

**Comment by Shothertz** [comment]
Leonardo, I experieced your same problem whit mine FC and I resolved by reconnect 5/6 times the USB ;)

**Comment by ltwin8** [comment]
my hardware arrived at customs today, maybe I will be able to test on it within next week

**Comment by Bolgor** [comment]
Short circuit?

**Comment by ltwin8** [comment]
i have received my hardware and tested it, however the important part, the mag on the matek gps is not working, not detectable at all, even if scanning for addresses, so I can not investigate further on the i2c problem.

the remaining part should work, I have a hifionrc FC with GPS (bn220) and crsf in working condition under inav. sadly no mag because of the not working gps.

but from what I have set up so far I can not notice a problem in inav.

**Comment by Lagarda** [comment]
Hi to All,

I'm novice here.
I bought recently the board FC HIFIONRC F7 PRO V2. Would you please tell me how to flash it?
I tried to connect via rx/tx but not successfully. If i press boot button and use usb port the system stops to see it.

**Comment by Lagarda** [comment]
> Hi to All,
> 
> I'm novice here.
> I bought recently the board FC HIFIONRC F7 PRO V2. Would you please tell me how to flash it?
> I tried to connect via rx/tx but not successfully. If i press boot button and use usb port the system stops to see it.

Solved!

**Comment by xeller8u** [comment]
Hey guys I dont know what happened but i could conenct fine to my hifionrc f7 pro v2 fine at first but now no matter which USB port I plug into and no matter which cable I use I can't connect to beta flight normally it would show up as com 6 but I'm getting nothing in fact it's really weird when I plug into some USB ports I don't get anything on the board at all and when I plug into another one I get the Bluetooth light flashing I don't hear any sound when I plug it in and I still can't connect to betaflight. on my phone I can see the Bluetooth target as " Hifionrc" but I can't connect to it 'cause it asks for a password and I don't know what the password is and I have to punch in something I can't just hit ok. so no lights no sound when i plug in usb to the fc and i checked that same usb port with my other quad and betaflight pops up with com6 and loads just fine .. so all i am getting is just the BT light flashing on and off green every 1 sec. please tell me you guys might have an idea.. one thing i should mentio is that i stupidly glued my buzzer on top of the usb port but then i had to reorient my VTX so I had to take off the buzzer and I carefully took it off I did have to wiggle back and forth a few times quite a few times and I don't know if that's it because the bt ligyht comes on so maybe its getting power but no data connection?  they appear to be all soldered fine and not loose but i may be wrong..

**Comment by Foxli212** [comment]
Добрый день еще не решили броблему с компасам ?

**Comment by virtus2232323** [comment]
Hello everyone! Tell me how to solve the compass problem in inav? In Betaflight, the issue was resolved. I inserted this code into СLI, but what about the ainav?

Set the mag i2c on adresses 0

set mag_bustype = I2C
set mag_i2c_device = 1
set mag_i2c_address = 0
set mag_spi_device = 0
set mag_hardware = AUTO
set mag_declination = 0
set mag_calibration = 0,0,0
set baro_bustype = I2C
set baro_spi_device = 0
set baro_i2c_device = 1
set baro_i2c_address = 0
set baro_hardware = AUTO

**Comment by virtus2232323** [comment]
When flashing in hifion rc with mamba f722 firmware, a magnetometer worked for me, it is connected to UART 3. but there is a minus, the barometer stopped working .... can someone give the firmware or instructions on how to fight !!!! Thank you!!!!

**Comment by virtus2232323** [comment]
pilkinn everything is simple i connected the magnetometer to uart 3 as mentioned above. and entered the commands that I wrote below and everything worked in Betaflight,.

**Comment by Bolgor** [comment]
Any information about supporting this FC in future iInav releases?

**Comment by Lagarda** [comment]
Can somebody compile the new FM where I2C addresses of 2 main magnetometers will be included? HMC and QMC 5885

**Comment by Lagarda** [comment]
> Can somebody compile the new FM where I2C addresses of 2 main magnetometers will be included? HMC and QMC 5885

FW - firm ware

**Comment by krizw** [comment]
Has anyone compiled anything lately, maybe Inav 3.0?

**Comment by Lagarda** [comment]
> Has anyone compiled anything lately, maybe Inav 3.0?

Hi! There is another branch where PiPi offered beta version 2.5.2 as relatively stable.

https://github.com/iNavFlight/inav/issues/6132

**Comment by Foxli212** [comment]
Все супер работает спасибо

**Comment by Lagarda** [comment]
> Все супер работает спасибо

И магнитометр китайский тоже? Версия 2.5.2 норм?

**Comment by Lagarda** [comment]
> Все супер работает спасибо

Покажешь, что в финале получилось?

**Comment by Foxli212** [comment]
Gps BN880Q сразу зароботал и баро имаг и gps калибровал дома вышел на улицу все заработала и удержания и вазрат дамой

**Comment by Foxli212** [comment]
> Я надеюсь, что это поможет вам
> 
> [inav_2.7.0_HIFIONRCF722.hex.zip](https://github.com/iNavFlight/inav/files/5861062/inav_2.7.0_HIFIONRCF722.hex.zip)

Переделай пожалуста под 3.0 прошивку
