### ISSUE TITLE
Clear indication of compass failure

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#650]
A number of compass-related issues appear recently. In case it happens in the field, there is no clear indication to the pilot that some navigational features (including emergency RTH) may not work.

For GPS and BARO we may observe telemetry and OSD reports. But there's no such thing for MAG.

What would be the best indication method:
- re-using some telemetry fields (e.g. GPS related)?
- led-strip error indication?
- audible alert (buzzer)?
- arm-block (sufficient only for boot-time failure)?
- all the above?

**Comment by stronnag** [comment]
There already is, LTM (and MSP) report compass heading.

**Comment by digitalentity** [comment]
I think @krzysztofmatula is talking about indicating that compass is not available (misdetected, failed).

**Comment by krzysztofmatula** [comment]
Correct. 
The heading reports sent over telemetry do change (based on ACC/GYRO) even if MAG hardware fails or is not detected. It is quite hard to judge the HW state out of these readings.

**Comment by nibborg** [comment]
Maybe the LCD screen can be used. At this moment is prety useless.
Something like Mag:No , Fail , Ok on the screen on the startup .
This is indeed usefull for the other sensors too (accel, gyro, sonar, gps...)

At this time exist the boot-time event logging, but you need to connect the pc to the board.
Some indications on the screen will be very helpfull.

**Comment by stronnag** [comment]
Status indication also exists via telemetry for mwp and probably ezgui. This is an OSD problem, not a iNav problem. iNav already publishes the sensor status on demand.

**Comment by giacomo892** [comment]
@stronnag happens that the mag is reported as OK but when you have a look in the sensor tab mag value are stuck. 
Heading is calculated only with gyro with no indications

**Comment by stronnag** [comment]
got it. Status is only established at boot. Quite impressive how accurate the IMU is if you disconnect the mag after boot.

**Comment by giacomo892** [comment]
@stronnag yes :) but tend to drift if you move fast :)

**Comment by krzysztofmatula** [comment]
Continued in: https://github.com/iNavFlight/inav/pull/744
