### ISSUE TITLE
Pixel OSD: vertical deflection of ahi too low

### ISSUE THREAD

**Issue by jreise-d** [iNavFlight/inav#6514]
## Current Behavior
When using boards with Pixel OSD and setting _ahi_style = line_, the vertical deflection of the artificial horizon is too small. The horizon moves out of the screen only at >90° pitch angle and not at 20° pitch angle as desired. With _ahi_style = default_ the displayed deflection is correct.

An adjustment of the ahi deflection with the cli parameter _osd_artificial_horizon_max_pitch_ as in earlier iNav versions is unfortunately not possible with Pixel OSD.

Tested with iNav 2.6.0 on Matek F722-WPX and on F405-Wing with external Matek Pixel OSD.

## Steps to Reproduce
1. Flash iNav 2.6.0 on F722-WPX
2. Update Pixel OSD to FW 2.0.0 with FrSky OSD Tool 2.0.3
3. Upload OSD Font Vision in iNav Configurator
4. cli: _set osd_ahi_vertical_offset = 0_
5. _set osd_ahi_style = line_
6. move the board and look at the ahi

---
# version
# INAV/MATEKF722WPX 2.6.0 Dec  4 2020 / 12:19:14 (cada68e4)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by Pairan** [comment]
hola @fiam  ! ... is that something you can help with?
