### ISSUE TITLE
Target.C - timerHardware Broken

### ISSUE THREAD

**Issue by lavachemist** [iNavFlight/inav#6517]
I have built a custom INAV target for an unsupported board (JHEMCU F7 Dual). Other users asked me to share the custom target, so I wanted to make it as usable for fixed wing and multirotor. I think I discovered a bug in the process. I have one output pin (PB3/S4) in Target.C which is on a separate timer from all of the other pins. I configured it so that it can be either a multirotor motor, fixed wing motor or fixed wing servo (screenshot below). If I choose a flying wing configuration with two servos and one motor, the Mixer shows that S1 and S2 are servos and S4 is a fixed wing motor, as expected. However, if I run the resource command in CLI, I can see that it actually assigned the motor to S5.

![image](https://user-images.githubusercontent.com/48248311/104872661-757cc680-591c-11eb-8878-0474e6e5f66a.png)

Here you can see that the mixer thinks that Motor 1 was assigned to S4 (PB3):
![image](https://user-images.githubusercontent.com/48248311/104873222-02744f80-591e-11eb-971d-0c139c245062.png)

Here you can see that the CLI resource commands shows it assigned to S5 (PC9):
![image](https://user-images.githubusercontent.com/48248311/104873686-13719080-591f-11eb-86cb-cb1ca6214daa.png)

If I change the options for S4 in Target.C so that it is can only be a fixed wing motor, the mixer works properly and the motor is assigned correctly according to the resource command.

## Steps to Reproduce
1. Add a third option to any of the outputs in Target.C and compile
2. Flash the target to a board and configure the mixer so that it uses the output.
3. Run the 'resource' command in CLI and see if the mixer is lying to you.

## Expected behavior
I expect the Mixer to not lie to me. It is telling me that it assigned an output to a certain pin, but it actually assigned it to a different pin.

## Suggested solution(s)
If this is unexpected behavior, the mixer should be repaired. If it is expected behavior - perhaps it should be documented because it is not intuitive.

## Additional context
Here is a copy of my target files: 
[JHEF7D_INAV_BrokenMixer.zip](https://github.com/iNavFlight/inav/files/5827911/JHEF7D_INAV_BrokenMixer.zip)

- FC Board name and vendor: JHEMCU F7 Dual
- INAV version string: 
# version
# INAV/JHEF7D 2.6.0 Jan 17 2021 / 17:37:57 (cada68e4)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by digitalentity** [comment]
You have both `TIM_USE_FW_SERVO` and `TIM_USE_FW_MOTOR` defined for S4 (TIM2_CH2). This is not a compatible configuration - in this case `TIM_USE_FW_SERVO` takes precedence.

Closing as WAI.
