### ISSUE TITLE
Can`t control ESC or ARM when Reverse ESC mode is toggled. 

### ISSUE THREAD

**Issue by 7yatna** [iNavFlight/inav#6525]
Good day INAV Community. 

thank you so much for your great support and work to make the hobby better. and i hope the newest Remote ID decisions don`t affect the RC hobby as we know it now. 

so, I Have an issue and hoping someone might seen or experienced something similar. 

I did try to search for something similar but i couldn't find an answer or anything showing the same behavior. 

I`m Building A HEX Copter running Matek F722-SE FC. I'm running INAV the most recent stable firmware 2.6  and using the Inav 2.6 configurator as well. 

I did a mistake when I ordered the 80A ESC. 

they turned out to be Bidirectional and reversible ESC. which I know not ideally for drone applications, it took so long to buy and money went in them so I`m trying to use as i saw that INAV can support reversible ESCs. 

When the option for reversible ESC is NOT toggled, the FC can Arm and i can Manually enable the motor outputs and move the esc Sliders from the configurator. 

but of course this will not work as the esc will be going in the wrong way. and always will be on. 

so when i toggle the reversible ESCs 

i can see that the default throttle on the sliders is 1460 which is good and make sense. 
but the FC cant arm, i cant even toggle the motor output to enable the sliders manually. 

i checked the CLI to see if there is alarms. 

CLI is reporting THR and CLI 

i know this is a drone which am pretty sure there is a setting i need to change manually to enable the reversible ESC. 

i tried playing with min_check, min_command, all i could find related to throttle. 

so a drone with reversible ESCs how to enable that and arm ?? 

I'm sorry if missing details, but I can help adding if anything needed. 

thank you in advance. 
Karim.

**Comment by DzikuVx** [comment]
Throttle has to be in a mid position to arm bith reversible esc
