### ISSUE TITLE
Remove usused/not popular flight modes

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#653]
This was proposed in #469 , remove unused/not implemented/not popular flight modes:
- [x] BOXGOV
- [x] BOXLEDMAX
- [x] BOXCAMTRIG -> can be done with _channel forwarding_
- [x] BOXSERVO1 - 3 -> can be done with _channel forwarding_

There is a plan to use BOXLLIGHTS as part of #296 so this might stay

**Comment by digitalentity** [comment]
This will free up 6 flight mode slots for something more useful i.e.
- weak leveling flight mode
- airplane servo trimming (#555)

etc.

**Comment by DzikuVx** [comment]
To keep compatibility, `box` will be kept in CLI and MSP but set to 0 everywhere/ignored
