### ISSUE TITLE
Quad Won't Arm - States there is no RC link but the receiver works

### ISSUE THREAD

**Issue by duncansshand** [iNavFlight/inav#6546]
## Current Behavior

Specs:
iNav 2.6
HGLRC F7222 
Spektrum 4650 SRLX2 Receiver
Spektrum DXe Transmitter

Everything is working perfectly on my quad, it is passing all pre-aming validation check but I cannot arm the quad. 

In the CLI it states it won't arm due to the RC link not being detected but the receiver tab shows inputs and movements from RC.  On the OSD it also states it is in '!FS!' and 'Unable to arm - No RC link' but the RSSI varies around 98 and the throttle is registered on stick movements. 

Due to the flight controller stating there is no RC link the quad is constantly in failsafe mode.

![image](https://user-images.githubusercontent.com/56200798/106396058-91449a00-63fd-11eb-871a-02239a1f623a.png)

![image](https://user-images.githubusercontent.com/56200798/106396072-a15c7980-63fd-11eb-8ec0-7ecbdd148aed.png)

![image](https://user-images.githubusercontent.com/56200798/106396077-a6b9c400-63fd-11eb-92a7-5829c8c4fda8.png)

In the screenshot below it says in the first status that it is unable to arm due ARMSW RX CLI. After deactiving the armswitch, you can see in the second status that is no an arming disabled flag therefore the flight controller is registering the RC inputs.

![image](https://user-images.githubusercontent.com/56200798/106396108-db2d8000-63fd-11eb-8ecd-766c56bce7a8.png)

I have tried 2 different UARTs and had no luck, both on TX pads as advised. 

## Suggested solution(s)

I thought that it could possibly be the receiver sending false signals for unused channels (e.g. channel 16) that are out of range and is triggering the failsafe. 

## Additional context

![image](https://user-images.githubusercontent.com/56200798/106396197-555e0480-63fe-11eb-9cae-408d43533798.png)

**Comment by breadoven** [comment]
Channels 24 and 25 seem to be showing non zero values below the valid channel signal value (rx_min_usec = 750). Could be causing the problem.

**Comment by duncansshand** [comment]
> Channels 24 and 25 seem to be showing non zero values below the valid channel signal value (rx_min_usec = 750). Could be causing the problem.

Yeah that was another thing I thought could be causing the problem. Sometimes the channels read ~65300 

I have no idea what to do here, is there anyway in the CLI to disable these unused channels?

**Comment by duncansshand** [comment]
Solved the problem.

Downgraded the firmware on the receiver to a version released back in March 2019. 

One of the later firmware updates had a feature that sent the failsafe signal upon initiate which was locking iNav in failsafe mode.

The drone now arms and doesnt stay in failsafe.

Duncan

**Comment by kochge** [comment]
I've the same problem. SRLX2 works fine with DX8i transmitter, but it fails on DX6i. 
It seems that the SRLX2 Receiver reports invalid values on some channels when using the DX6i transmitter, but it works fine on DX8i. Is there any possibility to disable the failsafe check on these higher channels, as they are not required anyway?
