### ISSUE TITLE
RC via Mavlink

### ISSUE THREAD

**Issue by harryjph** [iNavFlight/inav#6571]
## Current Behavior

Separate Mavlink and RC UART connections are required when using Crossfire. Or any control link, for that matter.

## Desired Behavior

Be able to control an aircraft using a single Mavlink UART via Crossfire. Also, control via joystick on GCS etc.

## Suggested Solution

Add Mavlink as a serial RX provider. Once selected, RC commands are taken from Mavlink.
**I plan to implement and PR this myself**.

## Who does this impact? Who is this for?

Anyone using Crossfire who wants Mavlink mission upload / telemetry and RC on the same UART (especially important on F411 chips!)

## Additional context

This is just a tracking issue to gauge interest (as I've seen this asked for before) and for any relevant discussion, **I plan to implement and PR this myself as long as maintainers think this would be a useful contribution**.

**Comment by cgrrty** [comment]
Hi
I want RC via Mavlink with openhd
Thanks

**Comment by cgrrty** [comment]
How's it going? when will it be released?

**Comment by wx4cb** [comment]
would be nice, but i think they need to fix the mavlink implementation itself first :) that said, a full mavlink v2 implementation would be cool

**Comment by cgrrty** [comment]
PX4 and ardupilot support RC with mavlink now

**Comment by harry1453** [comment]
@cgrrty as I said in telegram I've been working on it, I have an implementation but have not had the time to try it out beyond compiling it, so it's not ready yet at all. unfortunately other things are taking up my time at the moment. I promise I'll get back on this soon

@wx4cb I've implemented MAVLink V2 as part of my changes.

**Comment by wx4cb** [comment]
@harry1453 cant wait
