### ISSUE TITLE
sp racing F3 external mag Problem

### ISSUE THREAD

**Issue by jereitor** [iNavFlight/inav#660]
Hello, I have problems with HMC5883 in FC SP Racing F3 in Betafligth is solved. It will be solved in Inav?. 
https://github.com/betaflight/betaflight/pull/626
Thank you.

Sorry my bad English much.
Translated with google translate

**Comment by digitalentity** [comment]
Please share details of your setup.

Recently we are encountering numerous issues with HMC5883 chips due to lower error tolerance for critical sensors. Cleanflight and Betaflight don't care, but for INAV compass is a critical component.

**Comment by jereitor** [comment]
I am sorry
https://github.com/betaflight/betaflight/pull/626

**Comment by DzikuVx** [comment]
I would have to say: let's close it. I'm using HMC5883l with my SPRF3 without any problems now.
@stronnag @digitalentity  Thoughts?

**Comment by stronnag** [comment]
I agree, I've had no mag issues since @digitalentity fixed up the last set of driver issues.
