### ISSUE TITLE
Heading-hold - allow to set compass value by programming tab

### ISSUE THREAD

**Issue by poi2poi** [iNavFlight/inav#6642]
## Current Behavior
Heading-hold will keep the aircraft flying in the current direction

## Desired Behavior
Let user set a compass heading value through programming tab for Heading-hold mode or similar mode

## Suggested Solution
- Add variable heading_hold_bearing or similar
- Add option in Programming tab to set this variable

## Who does this impact? Who is this for?
i.e. pilots flying without GPS sensor but have a compass in FC, who like to easily fix a goal without creating a mission in Mission Planer

**Comment by DzikuVx** [comment]
Done in #6644
