### ISSUE TITLE
Motor arm sound player through ESC

### ISSUE THREAD

**Issue by poi2poi** [iNavFlight/inav#6643]
## Current Behavior
Motor arming sound is played only through auxiliary buzzer

## Desired Behavior
Please enable MOTOR ARMED sound being played through ESC

## Who does this impact? Who is this for?
Everyone without a buzzer

**Comment by Jetrell** [comment]
@poi2poi  if you require the motors to make the same tone as the beeper does when armed?
The reason it doesn't presently, relates to - #6645
