### ISSUE TITLE
beeper RX_SET & RX_LOST do not work with ESC buzzer (DSHOT600)

### ISSUE THREAD

**Issue by chillside** [iNavFlight/inav#6645]
## Current Behavior

I have a built-in buzzer and it works well. But I would like to turn on the ESC buzzer too. ESC only beep when turned on, but do not beep when beeper is turned on or power is lost

Dshot600 ESC protocol is on. I try CLI commands: `beeper ALL` & `beeper RX_SET` `beeper RX_LOST` and save. But to no avail

---

version
INAV/KAKUTEF7HDV 2.6.0 Dec  4 2020 / 11:41:25 (cada68e4)
GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

- FC Board name and vendor: Kakute F7 hdv
- INAV version string: 2.6.1

**Comment by Jetrell** [comment]
@chillside  iNav doesn't have DShot Beacon at the flick of a switch, like BF does.

**Comment by chillside** [comment]
> @chillside iNav doesn't have DShot Beacon at the flick of a switch, like BF does.

why? it is sad. will there ever be?

**Comment by Jetrell** [comment]
iNav doesn't have` DShot Command`  required to externally control BLheli.
There has been interest. Not so much in this feature, but in `Flip Crash` 'turtle mode' that also requires `DShot Command` to operate.

**Comment by poi2poi** [comment]
Well.. why can't we take a few code-snippets from the Betaflight sourcecode and make our ESC go beep-beep.. ? Would be great..

**Comment by Jetrell** [comment]
> 
> 
> Well.. why can't we take a few code-snippets from the Betaflight sourcecode and make our ESC go beep-beep.. ? Would be great..

@poi2poi Sounds ideal to me.

@DzikuVx I remember you talking about this on your live stream. Is there any reason @poi2poi could not port DShot command?

**Comment by Jetrell** [comment]
@chillside @poi2poi  If this gets implemented #6685. It will go most of the way towards having the motor/ESC as a beeper.

**Comment by harry1453** [comment]
I'm working on this now.
