### ISSUE TITLE
Use both compass heading and GPS CoG for navigation 

### ISSUE THREAD

**Issue by YohanHadji** [iNavFlight/inav#6650]
## Current Behavior

Currently **if my understanding of the navigation code is good**, either only the compass or only the gps course over ground is used, to know in which direction the model is moving. 

Problem : 
- The gps can't be used if the wind speed is close to the plane's flight speed.
- The compass only takes into account the direction in which the model is pointing, not the direction in which it is moving, so rth is less efficient with a compass than with a gps. 

## Desired Behavior

Use both orientation given by the compass and the orientation given by the gps by mixing them according to the ground speed. 

## Suggested Solution

A function that can be activated, to mix the orientation given by the compass and the orientation given by the gps according to the ground speed. 

At low speed: only the compass is used, and then the higher the speed, the more the orientation given by the gps is used 

See this picture for more clarity : 

![IMG_5017](https://user-images.githubusercontent.com/58160726/109415195-8c9ce280-79b7-11eb-943d-43272522cc99.JPG)

Function exclusion : 

- if the ground speed is lower than "x" (see picture) and the difference between compass and gps course over ground > 90, use only the compass
- if the ground speed is higher than "x" (see picture) and the difference between compass and gps course over ground > 90, use only gps 

## Who does this impact? Who is this for?

All users using navigations modes (RTH, Waypoint..etc)

**Comment by b14ckyy** [comment]
Final implementation with https://github.com/iNavFlight/inav/pull/9387
