### ISSUE TITLE
FR: Calculated glideslope

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#6651]
I was thinking that we have access to the vertical speed and obviously the ground speed, i would be a great addition imho to be able to calculate the glide slope as an osd item.

glideslope in general is the averaged result of sink rate (- Vspd) over ground speed. 

we already have all the necessary variables and also would be a good thing for tuning things like the linear descent etc (again another item we already have).

Just a thought.

**Comment by avsaase** [comment]
Is the glide slope not the other way around, the horizontal speed over the sink rate?

**Comment by wx4cb** [comment]
@avsaase it may well be, have to look it up, but when im out in full size, ground speed in Knots *5 is the way i usually do it, that will get you the vspd descent rate you need

**Comment by breadoven** [comment]
Closed by https://github.com/iNavFlight/inav/pull/6939.
