### ISSUE TITLE
 iFlight SucceX-E F7

### ISSUE THREAD

**Issue by IngressoDev** [iNavFlight/inav#6657]
Is it possible to use my fc (iFlight SucceX-E F7) with iNav?
There is no selection in the "Flash Firmware" tab for my fc like it is in betaflight.

Is it possible to choose a similar firmware?
I don't know how to create a new firmware spicific for my fc, but i have no fear to be a guinea pig :)

Regards

Edit:
I found my type in Betaflight but i have no idea how to port it to iNav:
https://github.com/betaflight/betaflight/tree/master/src/main/target/STM32_UNIFIED

STM32F7X2.mk

**Comment by G9xy** [comment]
If there is no published firmware target for your FC you can flash it from local file.

See my post: [https://github.com/iNavFlight/inav/issues/6711#issuecomment-892387900](url)

**Comment by RipperGOT** [comment]
> If there is no published firmware target for your FC you can flash it from local file.
> 
> See my post: [https://github.com/iNavFlight/inav/issues/6711#issuecomment-892387900](url)

Can you post it again?

I bought a Nazgul!!!!😬
