### ISSUE TITLE
Matek F411-WSE No Servo Communication

### ISSUE THREAD

**Issue by YRasamat** [iNavFlight/inav#6672]
Hi, i have a rmrc recruit v2 that im putting inav into, Im originally from the multirotor world so i don't exactly know how to deal with servo's. I know my servo's are supposed to centralize when the wing gets plugged in but i tried off the Flight controllers BEC, and a seperate 2-8s 5v, 12v bec(yes its on 5v) and im very sure its not powered. When using a servo tester it responds perfectly(running off the flight controllers bec) but it seems like i cant communicate to the wing itself. I had my servos setup on s3, s4, now one of them is on s5 because i thought maybe i needed a different order. Im very inexperienced to inav so any help is appreciated

**Comment by xxJohnxx** [comment]
Can you attach screenshots from your Mixer and Output settings please? A likely guess would be that there are some issues with your setup there.
