### ISSUE TITLE
Feature Request: allow logical conditions to enable modes (eg beeper)

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#6697]
it would be a good idea to allow logical conditions to trigger certain modes (such as the beeper)

for example, if you're in failsafe, have a logical condition enable the beeper so that its an automatic thing. this would save a channel on a channel limited receiver for example.

**Comment by DzikuVx** [comment]
The next release of INAV will allow to override RC channels with Logic Conditions. So you will be able to do it and many more
