### ISSUE TITLE
Servo Outputs on OmnibusF4V6

### ISSUE THREAD

**Issue by carlybaby69** [iNavFlight/inav#6700]
Inav thinks that OmnibusF4V6 has 8 pwm outputs. However it only has 6 per this diagram:

https://i1.wp.com/blog.dronetrest.com/wp-content/uploads/2018/10/OMnibus-F4-V6-Pinout-Top.jpg?w=1165&ssl=1

So what seems to be happening is that 2 servos are being assigned to S7 and S8. 

I see in the target that MAX_PWM_OUTPUT_PORTS is set to 8. I know that this shares a lot with FIREWORKSV2, would an if statement help so that if OmnibusF4V6 then we only get 6 PWM outputs?

**Comment by DzikuVx** [comment]
The fact that some board does not have outputs as pads is a problem with the board itself.
