### ISSUE TITLE
Buzzer off when connected to usb

### ISSUE THREAD

**Issue by samcollins910** [iNavFlight/inav#6701]
Is it possible to have implemented the buzzer off when connected to usb as per betaflight. 
This will benefit everyone who uses inav and configurator, especially with the advent of these 4 inch drones with the built in lost buzzer / vifly type thing. Those are blooming loud.

**Comment by avsaase** [comment]
Have a look at https://github.com/iNavFlight/inav/blob/master/docs/Buzzer.md

**Comment by samcollins910** [comment]
Haha.. many thanks. I didn't think to look in the cli..

Thank you.
