### ISSUE TITLE
iNav Target Request for iFlight Beast F745 and H743 AIOs

### ISSUE THREAD

**Issue by fictionfact12** [iNavFlight/inav#6710]
These two iFlight Beast AIOs are supported on betaflight. Would be great to see them on iNav for LR builds. Thank You

**Comment by N3frain** [comment]
i second this. they have barometers and should work great with inav. i built a 7" LR quad with the h7 one and would love to run inav on it

**Comment by cpnmercury** [comment]
they are missing SDA/SCL pads

**Comment by llambkin** [comment]
Yes please :)

**Comment by secretman28** [comment]
> they are missing SDA/SCL pads

i2c and uart 4and 7 share the same no? can be remap to uart4 or 7 pin?

im not programer but on datasheet seam they can be alternative fonction from what i under stand

**Comment by fa-lk** [comment]
Following, would be great to see a target for INAV like the IFLIGHT_H743_AIO_V2 in betaflight 🙂
