### ISSUE TITLE
more than 3 digits on osd efficiency display

### ISSUE THREAD

**Issue by JaKoB-FR** [iNavFlight/inav#6713]
## Current Behavior
Efficiency (mah/km) display on osd the last 3 digits, causing value superior to 999mah/km not to be displayed correctly.

## Steps to Reproduce
1.set display of efficiency on the osd
2.fly high current demand & low pitch value (low horizontal speed)
3.observe the osd display

## Expected behavior
display more than 3 digits for this value

## Suggested solution(s)
allow an extra room for the 4th digit in the osd

## Additional context
Was observed on RTH at low speed (5m/s) facing laminar wind, for instance 1245mah/km was diplayed as 245mah/km

- FC Board name and vendor: diatone mamba f405 mk2
- INAV version string: 2.7.0 (test)

**Comment by avsaase** [comment]
I think we should switch to x.xx Ah/km format when the value goes above 1000. Same with the power OSD element that only goes to 1000W, which isn't really that much. Doing this requires making some new OSD characters though.
