### ISSUE TITLE
CLI.md align_board in deci-degree

### ISSUE THREAD

**Issue by Ralf-W** [iNavFlight/inav#672]
In https://github.com/iNavFlight/inav/blob/master/docs/Cli.md MIN and MAX for "align_board_roll", "align_board_pitch", and "align_board_yaw" read -180 and 360. But they should read -1800 and 3600 for iNAV.

BTW. - Why do these limits use more than 360°? Should it be -1800 to 1800 or 0 to 3600?

**Comment by DzikuVx** [comment]
Implementation in #757
