### ISSUE TITLE
Sensitivity of stick in horizon mode

### ISSUE THREAD

**Issue by rsilk1949** [iNavFlight/inav#6723]
Up to now I have been using Angle mode for controlling my wing. I have just started to use horizon mode to enable loops etc.
As I understand it, horizon mode acts like angle mode until the stick is moved more than a certain amount from centre stick.
At what point does control switch from angle to horizon?
Can the transition point be varied to allow a beginner to gain confidence? What would be the impact of such changes?

Robin

**Comment by avsaase** [comment]
@rsilk1949 it seems your questions has been answered so I'll close the issue.
