### ISSUE TITLE
Please add RC via mavlink protocol 

### ISSUE THREAD

**Issue by cgrrty** [iNavFlight/inav#6729]
## Current Behavior
Inav mavlink does not support RC
If telemetry and RC is supported at the same time, it will occupy one more serial port.
## Desired Behavior
Mavlink telemetry and RC are supported on the same serial port.
## Who does this impact? Who is this for?
The board with few serial port resources can be used for telemetry and RC through mavlink.

**Comment by wx4cb** [comment]
duplicate of https://github.com/iNavFlight/inav/issues/6571
