### ISSUE TITLE
QMC5883 MAG not working

### ISSUE THREAD

**Issue by tomxygen** [iNavFlight/inav#6734]
I can't get a QMC5883 board to work on INAV.
I tested it with an Arduino and it works fine, but INAV simply doesn't recognize it and in the "status" command says MAG=unavailable.

Is there anything else I could try?

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/113116864-256c8b00-920e-11eb-8a59-a321faf0731e.png)

QMC5883 works perfectly well with INAV. I suppose it is something specific to your build that is causing the problem

**Comment by butcher51** [comment]
I have the same problem, my setup is the same as on the picture above, with other magnetometer it's working.
