### ISSUE TITLE
Support BetaFPV SMO 4k Cam remote control

### ISSUE THREAD

**Issue by Skipp1609** [iNavFlight/inav#6736]
## Current Behavior
There is no possibility to remote control the BetaFPV SMO Cam by flight controller connection

## Desired Behavior
Power and recording should be controlled by flight controller connection
## Suggested Solution
needs a configuration just like in BetaFlight (see attached file)

## Who does this impact? Who is this for?
possibilty to operate the Cam by remote control

## Additional context
none
![SMO remote control for BetaFlight](https://user-images.githubusercontent.com/81240960/112151400-79a9b680-8be1-11eb-9f40-98358d61a0f6.jpg)

**Comment by Papsi77** [comment]
+1
That would be great 😉

**Comment by konraddi** [comment]
+2
Absolutely needed! :)

**Comment by lightpixel73** [comment]
+3
would be great.. also requested in the facebook Inac fixed wing group...

**Comment by SilentZen** [comment]
+4 was hoping to have it enable on arm then realised inav didn't support it.

**Comment by mattcave** [comment]
My reading of the docs suggests that the camera just needs the voltage to go high then low on the remote recording pin for the camera to start recording. If that's the case, some of the fixed wing oriented FCs from Matek already have a simple switch built into them that can be controlled by a spare channel. Would that work?
