### ISSUE TITLE
Add Average Cell voltage on crossfire telemetry

### ISSUE THREAD

**Issue by UweHeim** [iNavFlight/inav#6741]
## Current Behavior
So far the CRSF telemetry shows just the main battery voltage as RxBt.
e.g. a 3S battery having 9.9V total shows up with 9.9V. This is unfortunately the only thing you can get.
This information is not perfect.
You can't set alarms or Audio messages in OpenTX to act on low voltage (e.g. Cell voltage < 3.5v) unless you know the cell-count of the battery in advance.

## Desired Behavior
Many pilots started to use quadcopters with different numbers of cells 3-4-5-6s, moreover, many builds can work with multiple different batteries. Thus, the main battery voltage (in my opinion) is not enough. The average cell voltage is more useful. So my suggestion is to add the average cell voltage to the CRSF telemetry or, if that is not possible, add the possibility to select between the main battery voltage and the average cell voltage.

## Suggested Solution
It works on Betaflight like a charme with
set report_cell_voltage = ON

The big unfortunate: NOT so in iNav...
The setting does exist, however it seems only dealing with s.port - not sure why, because for FrSky, there is a perfectly working A4 sensor which is providing cell voltage out-of-the-box

See this video
https://www.youtube.com/watch?v=Ek-E_rVu59U&t=162s

If it would work at least as it works on betaflight, it would be OK.
Other ways to do it, would also be OK.
However, adopting the betaflight solution could be the easiest way to do it and it would be well testes in the betaflight world. It works pretty well for me on 5 quads. No issues. No negative sideeffects. By default this value is OFF, changing nothing for everyone who does not like it.

## Who does this impact? Who is this for?
Everyone using planes, quadcopters or any devices with different batteries.

**Comment by avsaase** [comment]
This is in the works. #6720
