### ISSUE TITLE
Programming RC_CHANNEL_OVERRIDE not working in 2.7

### ISSUE THREAD

**Issue by rts18** [iNavFlight/inav#6754]
I cannot get `RC_Channel_Override `to work with the 2.7 development firmware.
The logic condition outputs as active in the Programming tab. But the output channel does not get overridden. Either on the device or the receiver tab.

I have tried multiple channels, values and logic states. I am reasonably sure I haven't overlooked anything.

@DzikuVx  Can I ask that you take a look?
Thanks

**Comment by DzikuVx** [comment]
@rts18 it works like expected

![image](https://user-images.githubusercontent.com/966811/113116157-78920e00-920d-11eb-9cdb-b4289345e588.png)

![image](https://user-images.githubusercontent.com/966811/113116184-7d56c200-920d-11eb-8b22-1c8e11fa04d7.png)

**Comment by rts18** [comment]
@DzikuVx Thank you for testing it out.

This is why I couldn't get it working.

![Prog tab](https://user-images.githubusercontent.com/78670415/113133105-09e39d80-926b-11eb-9df5-037d334c119c.JPG)

Please don't take this as criticism. 
As an average Joe, I assumed  that operand 'A' would be defined as an `RC Channel` and not a `Value`, because it is that channel that is being overridden.
The confusing part, is the condition can also be met by using operand "A' `RC channel`. But it doesn't output unless operand 'A' is defined as a `Value`.

Is it possible not to have the condition met by two operand commands. So us simple people can work it out easier?

Thanks

**Comment by DzikuVx** [comment]
Operand RC channel is a getter. If it would be used, you would not be able
to set rc channel based on other value.

śr., 31 mar 2021, 13:45 użytkownik rts18 ***@***.***> napisał:

**Comment by OptimusTi** [comment]
@DzikuVx Any chance to change operand name of "RC Channel" to "Get RC Cannel"? I lost a few hours trying to figure out the same thing. Now that I know that the operand s a getter, it makes sense, but then, the docs should say that operand RC Channel “gets” instead of “points to”.

Another suggestion is to split the operand in two?

"Get RC Channel" is the getter. 
"RC Channel" sets the value.

**Comment by wx4cb** [comment]
maybe rename it to RC Channel Value ? or some derivative of that to make it obvious ?
