### ISSUE TITLE
Temperature sensor from DPS310 barometer not recognized

### ISSUE THREAD

**Issue by nickoe** [iNavFlight/inav#6762]
## Current Behavior

I got a new Mateksys F405-WSE flight controller, it contains a DPS310 barometer.

I have read this doc: https://github.com/iNavFlight/inav/blob/master/docs/Temperature%20sensors.md

It mentions that:
> When a new temperature sensor is connected it is automatically detected and will appear in the output of the temp_sensor command. 

But I don't see any temperature sensors, not even with the `temp_sensors` command in the CLI:

```
# version
# INAV/MATEKF405SE 2.6.1 Feb 25 2021 / 10:39:37 (64249b1a)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# temp_sensor
temp_sensor 0 0 0 0 0 0 
temp_sensor 1 0 0 0 0 0 
temp_sensor 2 0 0 0 0 0 
temp_sensor 3 0 0 0 0 0 
temp_sensor 4 0 0 0 0 0 
temp_sensor 5 0 0 0 0 0 
temp_sensor 6 0 0 0 0 0 
temp_sensor 7 0 0 0 0 0 
```

## Steps to Reproduce

1. Configure your FC for your plane, enable telemetry etc. (probably not needed)
2. Enable the DPS310 
3. Observe that the temperature values are all -100  in the "Sensors" pane. 

## Expected behavior

I would expect the temperature reading from the DPS310 to show up with a real value.

As far as I understand the support was added in 2.6.0, see mentions of DPS310 in  https://github.com/iNavFlight/inav/releases/tag/2.6.0

It does appear to be enabled on the firmware target MATEKF405SE: https://github.com/iNavFlight/inav/pull/5862/commits/e030235c64f6bd1d0f25c21d697edfcc1e40b202

I enabled it as a baromter in and it appears to work as a barometer in the sensors readings as well, the setting looks like:
![image](https://user-images.githubusercontent.com/352202/113041997-eea95d00-919a-11eb-92b9-0f7477f705c8.png)

## Additional context

`dump`: https://pastebin.com/raw/FE0X5kev

---

- FC Board name and vendor: [F405-WSE](http://www.mateksys.com/?portfolio=f405-wse)
- INAV version string: `# INAV/MATEKF405SE 2.6.1 Feb 25 2021 / 10:39:37 (64249b1a)`

**Comment by DzikuVx** [comment]
In this context, DPS310  is used as a barometer, not temperature sensor

**Comment by nickoe** [comment]
@rts18 @DzikuVx I don't have FPV gear and did not look there, I see that option now.

I tried to enable it ,but I don't see any new field when I try to discover new telemetry sensors on my remote. So I can't use it as a temperature source for telemetry?

**Comment by avsaase** [comment]
@nickoe AFAIK telemetry does not include any temperature data.

**Comment by nickoe** [comment]
Ok, I will close thus issue then. Thank you all!
