### ISSUE TITLE
Multirotor braking partial runaway

### ISSUE THREAD

**Issue by rts18** [iNavFlight/inav#6777]
I only recently tested this feature in 2.6.1 to find out how it worked. Because no one could tell me anything about it.
I did many tests and altered the set points to what suited my particular quad. Most of the setting changes are due to this quad being old and under powered. And it lost many meters of altitude in the braking phase, with the stock settings.

After one runaway in my first test session, some weeks back. I went to a larger area to do some more trial runs today.

It took me a while to figure it out, until I finally got the knack of what triggers the runaway, and could induce it regularly.

Its not a total runaway, but it almost doubles its throttle and speed for around 30meters, before it finally brakes.

How to -
Place it in Poshold. From a stable 3D hover, push the elevator stick full forward until the quad picks up speed. 
At around 35kph, the pitch would slightly bob up about 1°. If the pitch stick is released at that point. The quad will runaway instead of brake.
This point can be seen in the DVR. When the pitch angle goes from 21° to 19°, then I released the stick and it then tilts all the way to 33° and shoots off.
Its interesting to note that `nav_mc_bank_angle` = 22.

https://user-images.githubusercontent.com/78670415/113410763-ebfb7180-93ff-11eb-9a14-b58cd0ac6cd1.mp4

[Diff all.txt](https://github.com/iNavFlight/inav/files/6249279/Diff.all.txt)

_With no disrespect to the work that went into coding and testing this feature._ 
I must say that I only reported it so someone else doesn't get the surprise of it taking off in a small location, as I did.

I'm not likely to use this feature again, because it requires Cruise mode to operate in. And it only works in PosHold.
I find that extremely limiting. 
It would be much better if this feature would work when a quad is flying in Attitude mode using Air/Angle or Horizon modes. Then by switching to PosHold, it would enable braking.

**Comment by jkmzpap** [comment]
After crashing my 5 inch drone and experiencing the same behavior with another 5 inch drone I removed this mode.
Both drones are using betaflight f4 fc using iNav 2.6.1. In a small field one must be very quick to change to RTH in order to save the drone. It is strange that MC Braking existsts since iNav version 2.2 but still faces problems. Unfrotunately I don't have a video or blackbox file to share.
