### ISSUE TITLE
Unstable position hold in strong winds

### ISSUE THREAD

**Issue by edlang90** [iNavFlight/inav#6779]
## Current Behavior
When in position hold mode, the quad holds its position relatively well, even in strong winds (I might need to tune the NAV PIDs a bit). However, when I try to move the quad in any direction, the movement is mostly dictated by the wind and not the sticks. To get to a desired position, I have to compensate for the wind.

## Steps to Reproduce
1. Fly a quadcopter in a windy environment with position hold 
2. With the front of the drone facing the wind, move the stick to input roll command (it is important to not move the pitch axis)
3. Observe how the drone moves sideways, but is also pushed back by the wind

## Expected behavior
In position hold, have the drone be relatively immune to wind movements and only follow stick commands

## Suggested solution(s)
When in position hold mode, instead of using the stick inputs as commands they could be used to move the target position of the drone. This way, when the sticks are moved the drone moves to the desired position and is relatively resilient to external forces.

- FC Board name and vendor: INAV/MATEKF722 2.6.0 Dec  4 2020 / 12:11:30 (cada68e4)
- INAV version string: GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by avsaase** [comment]
That's what the Cruise User Control Mode on the Advanced tuning tab does.

![2021-04-03 11_07_12-INAV Configurator](https://user-images.githubusercontent.com/880421/113473930-ec7e2180-946c-11eb-88c4-c07e8d872b13.png)
