### ISSUE TITLE
Blackbox Explorer uses 32 bit value for timestamp, truncates after ~71 minutes of log

### ISSUE THREAD

**Issue by mirov** [iNavFlight/inav#6786]
## Current Behavior
Long Blackbox log files seem to be recorded correctly in INAV.  However, Blackbox Explorer (v3.4.0 tested) apparently uses a 32 bit value in an internal time representation, and apparently with 1uSec time quanta hits the limit of the 32 bit value and truncates the log at about 71 minutes.  An older "Cleanflight" version does not show this issue.  It is not yet clear if mwptools is OK.

## Steps to Reproduce

1.  Simple long duration log of a system sitting on a test bench logging data

## Suggested solution(s)

BB Explorer should use 64 bit timestamps, that's gotta be good until we get much better batteries.

## Additional context
Attached is a sample log that in fact is about 140 min of runtime but shows up at ~71 min.
[2021-04-03_140_min_decimated_200_blackbox_log_2021-04-03_204321.LOG](https://github.com/iNavFlight/inav/files/6254776/2021-04-03_140_min_decimated_200_blackbox_log_2021-04-03_204321.LOG)
Note that this log file was recorded with blackbox_rate_denom=200 to drop the sample rate down to about 5Hz so that the log would fit into the small-ish FC dataflash. 

---

BB Explorer v3.4.0

**Comment by stronnag** [comment]
This is not a firmware bug, the log is displayed correctly sized in `blackbox_decode`. Please raise in the [correct project](https://github.com/iNavFlight/blackbox-log-viewer/issues).
