### ISSUE TITLE
Incorrect Longitude displayed in DJI FPV goggles V2

### ISSUE THREAD

**Issue by kelleysislander** [iNavFlight/inav#6791]
I just got the V2 goggles and the longitude is incorrectly displayed, but it does follow waypoints fine, so the issue is just the displayed value.  Please see the attached images.

![v1_goggles_correct_longitude](https://user-images.githubusercontent.com/552098/112899798-38654b00-90a8-11eb-9ab8-d9dd848f9fe6.jpg)
![v2_goggles_incorrect_longitude](https://user-images.githubusercontent.com/552098/112899869-503ccf00-90a8-11eb-8378-73a6707037d5.jpg)
![in_the_field_actual_coords](https://user-images.githubusercontent.com/552098/112899922-5fbc1800-90a8-11eb-8691-e5cc0eac09c7.PNG)
![v2_goggles_in_the_field](https://user-images.githubusercontent.com/552098/112899954-68145300-90a8-11eb-90d8-a86a9a5e00c6.jpg)

**Comment by DzikuVx** [comment]
Since it's working in V1 and broken in V2, we have to assume it's a problem with V2 firmware, not INAV. Both types of goggles are fed the same data from INAV side

**Comment by digitalentity** [comment]
Alternatively we can figure out what DJI expects and add a bit to `dji_worksarounds`. Question is - do we want to?

**Comment by kelleysislander** [comment]
Hi,
Thanks for replying... Yes it is an unexpected data condition that the V2 goggles don't know how to handle, but V1's do.
It would be nice to have this displaying correctly.
My workaround is that I do have the coordinates displaying in my radio, so if I do go down I still have a way of seeing the last known position.
Cheers,
Bill
***@***.***

 

    On Monday, April 5, 2021, 03:53:46 AM CDT, Paweł Spychalski ***@***.***> wrote:  
 
 


Since it's working in V1 and broken in V2, we have to assume it's a problem with V2 firmware, not INAV. Both types of goggles are fed the same data from INAV side

**Comment by kelleysislander** [comment]
Ya, sorry for the duplicate ;)  I opened it originally under configurator as #6770 and a dev replied not a configurator issue so I opened it here. Should have closed that one...

**Comment by pbreed** [comment]
I believe this is fixed in the latest V2 goggles software. 606 .
