### ISSUE TITLE
Alarm for additional temperature sensors

### ISSUE THREAD

**Issue by expipiplus1** [iNavFlight/inav#6803]
In addition to the existing min/max alarms for the built-in IMU/Baro/ESC temperature sensors, it would be great to have these alarm available for the additional temperature sensors (for example, bat/motor/vtx/external)

**Comment by avsaase** [comment]
You can configure the alarms for the other temperature sensors in the CLI: [Temperature sensors.md](https://github.com/iNavFlight/inav/blob/master/docs/Temperature%20sensors.md)

**Comment by expipiplus1** [comment]
Ah, of course. Thanks!
