### ISSUE TITLE
Please add support for SPEEDYBEE F7 V2 FC target

### ISSUE THREAD

**Issue by jokeane** [iNavFlight/inav#6809]
## Current Behavior
It appears you already support the V2 SPEEDYBEE F7, but the SPEEDYBEE F7 V2 is slightly different.

## Desired Behavior
Support SPEEDYBEE F7 V2 please.

## Suggested Solution
Modify existing SPEEDYBEE F7 to make SPEEDYBEE F7 V2 target.

## Who does this impact? Who is this for?
Long range quad users. 

## Additional context
I've had really nice results with INAV so far on my 7" LR quads. Looking forward to replacing BF on this new FC. Thanks!

**Comment by suhast222** [comment]
It would be very nice to have the speedybee f7 v2 target, any chance to get it. By 3.0?
Does the speedybee f7 work on the v2?
Regards.

**Comment by krizw** [comment]
> It would be very nice to have the speedybee f7 v2 target, any chance to get it. By 3.0?
> Does the speedybee f7 work on the v2?
> Regards.

Speedybee confirmed today on FB that an Inav build is coming.

**Comment by mtshare** [comment]
+1

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/130404180-b1390f3a-841f-460c-9277-ebb4b12fcc20.png)
