### ISSUE TITLE
barometer filter unusable

### ISSUE THREAD

**Issue by JulioCesarMatias** [iNavFlight/inav#6818]
in the file `navigation_pos_estimator.c` the baro reading filtered in 1hz is never used, the pt1FilterApply3 function returns the filtered value, but it is never used.

https://github.com/iNavFlight/inav/blob/7d24ebd5f75470526f0fba45b890789454b6b36a/src/main/navigation/navigation_pos_estimator.c#L328

**Comment by DzikuVx** [comment]
`pt1FilterApply3` returns but also modifies the passed filter state as it's passed as a pointer

**Comment by JulioCesarMatias** [comment]
to obtain the filtered value in 1hz of the baro, it would be necessary to get the direct value in the function `pt1FilterApply3`, for example,` posEstimator.baro.alt = pt1FilterApply3 (& posEstimator.baro.avgFilter, posEstimator.baro.alt, US2S (baroDtUs) );` , or use the `posEstimator.baroa.vgFilter.state` pointer.See and test the sketch I passed on for testing >> https://pastebin.com/KNHMZF61

**Comment by JulioCesarMatias** [comment]
![notwork](https://user-images.githubusercontent.com/25625982/114427139-28ae3200-9b91-11eb-99c6-402b73675f91.png)

using INAV method

**Comment by JulioCesarMatias** [comment]
![filterok](https://user-images.githubusercontent.com/25625982/114427182-3794e480-9b91-11eb-8bd5-f8489badfa27.png)

the correct method

**Comment by JulioCesarMatias** [comment]
`posEstimator.baro.avgFilter` is used only in the pt1 filter functions, but it is never used in other functions in order to obtain the `.state`.


I can't see that it works

**Comment by digitalentity** [comment]
That's a remainder of AGL estimation. Indeed, curretly the LPF'ed value of the baro altitude is never used and that's WAI.

**Comment by JulioCesarMatias** [comment]
will it be removed in the future? Why does alt-hold not work, it’s too slow
