### ISSUE TITLE
Telemetry issues with Inav & FC-F411 WSE

### ISSUE THREAD

**Issue by Viper1200** [iNavFlight/inav#6836]
With regard to the Telemetry issues I was having with the FC-411-WSE I may have finally found the root cause & it appears to be nothing to do with the Code.
First, a bit of background; 
I have three of the F411-WSE boards, all using the same firmware & software & and attached to essentially the same hardware. Two work perfectly fine and the third has all the issues with telemetry. 
Connections between the FC and the FRSky Rx are SBUS & SmartPort as per the MATEK F411-WSE manual. I have also tested with three different transmitters & at least as many receivers & all show the same results as in the video.

From recent extensive testing I have found that the STM32F IC is temperature sensitive, at room temp the telemetry output is either very sporadic or non existent but once the IC is warmed (just slightly) then the Telemetry output starts working fine & continues to till the IC cools back down.
I have produced a video (that I will attempt to attach below) showing the ongoing testing etc. This was provided to MATEK however in their wisdom they have determined that this is NOT a hardware fault but more likely a coding issue.
When pressed on the issue MATEK could NOT explain how warming an IC could rewrite & correct faulty code but none the less they still maintained there was no hardware issue & therefore no warranty claim.
Given the amount of chatter on line re telemetry issues with this FC it will be interesting to know if anyone else finds the same temperature related problem or if I was just unlucky to get one faulty board out of three recently purchased.  

https://youtu.be/zv5gkrOSr9E

**Comment by Viper1200** [comment]
Further information re the Telemetry issues, I am using iNav Configurator V2.6.1 and there appears to be a discrepancy between the GUI and the CLI with regard ti TELEMETRY.
With TELEMETRY turned ON in the GUI the CLI DUMP shows telemetry_switch = OFF, while DIFF does NOT show it at all.
If you set telemetry_switch = ON within the CLI it then shows up as ON in both the DUMP & DIFF file HOWEVER the TELEMETRY function then no longer works at all.  
With the CLI showing telemetry_switch = OFF and the GUI showing Telemetry ON the TELEMETRY function does work but it is a bit sporadic and does NOT appear to send data continuously back to the radio. A lot of the time, whilst the Rx telemetry is scanning fine, the FC telemetry will completely stop scanning & then when a Telemetry Fail alarm comes up it will start scanning again, only to drop out sometime later.

Hope someone with far more knowledge than me can look at the code around the telemetry issue and resolve it.  The Flight Controller appears to work flawlessly but I really only purchased it to get the telemetry back from my plane.

**Comment by Viper1200** [comment]
Thought I may have got a response on this, I guess it's just me having the hardware issue.

**Comment by Mateyhv** [comment]
No easy answer but my guess is there is something flawed with the way the STM32F411 is used on the WSE board regarding softserial. A friend of mine has had lots os issues setting the SS for telemetry. Sometimes it worked, others did not... totaly random, kind of what happens in your case. My suggestion is to get rid of that board or ask for replacement. Unfortunately the F411 wing is no long into production the twin SS work flawlessly.
