### ISSUE TITLE
Arm mode won't turn blue even though every safety check is green

### ISSUE THREAD

**Issue by Pit89** [iNavFlight/inav#6840]
Hardware
transmitter: Spektrum dx6i
receiver: spm4650
FC: mamba f405 mk2 stack 
firmware: furyf40sd
gps compass: matek M8Q-5883
barometer: bmp180

Hey, a couple of weeks ago i decided to get into the fpv hobby.  I bought all the pieces and successfully soldered them to the fc. Unfortunately i'm having some problems, for the last couple of days i tried to look for the answer on google but i haven't found it.
The problem i'm running into is in the modes, when i try to flip the switches on my transmitter, the boxes don't turn blue. It happens to pos_hold, rth (even with 3d fix) and arm but weirdly the buzzer works. I don't know if the problem is related to the transmitter, some settings that i overlooked or hardware issues.
I also noticed that if i set the modes in order to have the stick inside the range and try to arm the drone(without having it connected to my laptop via usb) the blue light on my fight controller goes from blinking slowly( 1 blink a second) to really fast.
I'm attaching also the status and dump readouts.
Hopefully someone knows what's going on.
 Thanks in advance, Pietro.
[Logs.txt](https://github.com/iNavFlight/inav/files/6325619/Logs.txt)

**Comment by avsaase** [comment]
You cannot arm into a navigation mode. You also cannot enable a navigation mode when you are disarmed, so the box in the configurator won't light up.
