### ISSUE TITLE
RX_MSP not present?? 

### ISSUE THREAD

**Issue by conkerkh** [iNavFlight/inav#686]
I don't understand why you removed it and there is NRF?? MSP is really useful since you can control quad and at the same time fetch telemetry data about copter could you please add it back?

**Comment by conkerkh** [comment]
Sorry I've seen it's been raised before didn't notice that one...

**Comment by stronnag** [comment]
Just add it back and build your own hex if you really need it.

**Comment by conkerkh** [comment]
Yep I noticed it's been disabled for sub 128k targets.
