### ISSUE TITLE
Programming VBAT 1V=10 or 1V=100?

### ISSUE THREAD

**Issue by vincecate** [iNavFlight/inav#6883]
In the programming tab the menu for VBAT includes "1V=10" but in my testing it seems 1V = 100.
So I thought I would put 118 for 11.8V but really I have to put 1180.   This video shows the experiment:

https://www.youtube.com/watch?v=_AK419Al_vo

So I think it should say "1V=100".

This is iNav 2.6.1 for fixed wing.

**Comment by stronnag** [comment]
https://github.com/iNavFlight/inav/blob/master/docs/Programming%20Framework.md#flight

**Comment by vincecate** [comment]
In the pull down menu, not in the code, it says 1V=10.   That is all that is wrong.

**Comment by stronnag** [comment]
1. Please enter configurator issues in the configurator tracker
2. It's already fixed
