### ISSUE TITLE
GPS Time format

### ISSUE THREAD

**Issue by Impulze75** [iNavFlight/inav#6894]
## Current Behavior
  GPS time only shows Hour and minutes.

## Desired Behavior
 I want to have Hour/Minutes/Seconds diplayed on OSD for timestamp purpose.

## Suggested Solution

 Just change format

## Who does this impact? Who is this for?
 All Inav user that want a more accurate timestamp overlay in video.

**Comment by rts18** [comment]
@Impulze75 Adding seconds would be best to have configurable.  
Not everyone requires seconds. Having it added will take up more screen space if a user prefers to have time located at the sides.

**Comment by Impulze75** [comment]
Yes, thats configurable would be perfect 🙂 Betaflight have seconds when using GPS time, but i prefer using inav 😊


/Mattias

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by Impulze75** [comment]
So how do i get a inav version that supports seconds?  

Regards, Mattias

**Comment by Jetrell** [comment]
> 
> 
> So how do i get a inav version that supports seconds?

@Impulze75 You can add the pull request yourself and see if a developer in interested in merging it.
Or in the meantime if you are able. Port that part of the code from BetaFlight and make your own iNav build with it added.

> 
> 
> I want there will have date OSD also.

@ghostkcleung `Years/Months/Day` and `Hour/Minutes/Seconds` can be found at the bottom of the OSD arming page.

**Comment by Impulze75** [comment]
> > So how do i get a inav version that supports seconds?
> 
> @Impulze75 You can add the pull request yourself and see if a developer in interested in merging it.
> Or in the meantime if you are able. Port that part of the code from BetaFlight and make your own iNav build with it added.
> 

I guess i could do it myself, but is there any "how to" links for doing own builds?

/Mattias

**Comment by breadoven** [comment]
> > > So how do i get a inav version that supports seconds?
> > 
> > 
> > @Impulze75 You can add the pull request yourself and see if a developer in interested in merging it.
> > Or in the meantime if you are able. Port that part of the code from BetaFlight and make your own iNav build with it added.
> 
> I guess i could do it myself, but is there any "how to" links for doing own builds?
> 
> /Mattias

Build your own firware:
https://github.com/iNavFlight/inav/tree/master/docs/development

I could have a look at adding seconds. As said before though it increases the length of the time field which most users probably wouldn't want. However, if the seconds are optional this isn't such an issue.

**Comment by Impulze75** [comment]
> > > > So how do i get a inav version that supports seconds?
> > > 
> > > 
> > > @Impulze75 You can add the pull request yourself and see if a developer in interested in merging it.
> > > Or in the meantime if you are able. Port that part of the code from BetaFlight and make your own iNav build with it added.
> > 
> > 
> > I guess i could do it myself, but is there any "how to" links for doing own builds?
> > /Mattias
> 
> Build your own firware:
> https://github.com/iNavFlight/inav/tree/master/docs/development
> 
> I could have a look at adding seconds. As said before though it increases the length of the time field which most users probably wouldn't want. However, if the seconds are optional this isn't such an issue.

That sound awesome! I have a specific need to timestamp using inav in a remote controlled fullscale car.  Im only using the inav for OSD purpose with the GPS.

/Mattias
