### ISSUE TITLE
Dshot beeper GPS lock issue 3.0

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav#6940]
## Current Behavior
Dshot beeper will not work with a GPS fix.
Once a fix is lost. It will commence working again.

## Steps to Reproduce

1. Enable beeper in the CLI
2. Turn On beeper switch and it will work.
3. Once the GPS gets a valid fix. The beeper stops working.
4. Cover the GPS.. Once the Lock is lost, the beeper starts working again.

- FC Board name and vendor: BLheli_32 Rev - 32.8
- INAV version string: current 3.0 development

**Comment by avsaase** [comment]
> Once Air mode throttle threshold is met. Disarming the quad will cause the motors to burst into life for a moment and flip the quad over. This effect only occurs if there is a GPS fix.

So essentially after every flight disarming causes the motors to spin up enough to flip over the quad?

**Comment by DzikuVx** [comment]
@kernel-machine any idea?
