### ISSUE TITLE
[Pixel OSD] Some artefacts at the edge of screen 

### ISSUE THREAD

**Issue by railbox-org** [iNavFlight/inav#6941]
Hi,

I ve noticed some artefacts appear at the edge of the screen at 17min of flight. Looks like the place is constant. I don`t have anything assigned in this area of OSD.
Board: MATEK722WPX
![osd](https://user-images.githubusercontent.com/55380219/117566186-7ac17500-b0b5-11eb-8ba4-fa2356ab4e7b.JPG)
![osd1](https://user-images.githubusercontent.com/55380219/117566187-7b5a0b80-b0b5-11eb-902c-962567adca7b.JPG)
![osd2](https://user-images.githubusercontent.com/55380219/117566189-7bf2a200-b0b5-11eb-8899-5042a49920ee.JPG)
[INAV_cli_ASW-28_20210509_104536.txt](https://github.com/iNavFlight/inav/files/6447195/INAV_cli_ASW-28_20210509_104536.txt)

**Comment by Jetrell** [comment]
@railbox see this site for Frsky pixel OSD issues.
https://github.com/FrSkyRC/PixelOSD/issues
