### ISSUE TITLE
RTH reduce speed when close to home

### ISSUE THREAD

**Issue by ghostkcleung** [iNavFlight/inav#6965]
## Current Behavior

The drone speed is keep "nav_max_speed" when RTH mode active.
## Desired Behavior

Reduce to the specified speed within the specified range.
## Suggested Solution

Add 2 options:

set rth_descent_dist
set rth_descent_speed

**Comment by Jetrell** [comment]
@ghostkcleung There is a new addition to 3.0. That will allow the RTH descent speed to be adjusted in two stages, 
`nav_landing_maxalt_vspd ` and  `nav_landing_minalt_vspd`. This allows faster descent and slower touch-down.

As for having an RTH distance from home, deceleration setting....  I think that would be a good idea. 
It would prevent home position over-shoot, when RTH `nav_max_speed` is set at any reasonable high value. (>500cm/s in most cases)
