### ISSUE TITLE
GEPRCF722 support

### ISSUE THREAD

**Issue by mooiweertje** [iNavFlight/inav#6978]
## Current Behavior
GEPRCF722 not supported

## Desired Behavior
GEPRCF722 supported

## Suggested Solution
add GEPRCF722 support

## Who does this impact? Who is this for?
Lee Schofield, GEPRCF722 users, GepRC Crocodile Baby 5 owners.

**Comment by mooiweertje** [comment]
I made an implementation to be tested.
binary
[jnav_2.6.1.4_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6493212/jnav_2.6.1.4_GEPRCF722.zip)
source
[GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6493214/GEPRCF722.zip)

**Comment by Sedgee** [comment]
Thanks for this, I have the HD version of this board, will give it a go and let you know how it goes.

**Comment by mooiweertje** [comment]
I don't even know if it will install and run at all but it matches the BF config as as .

**Comment by mooiweertje** [comment]
> Thanks for this, I have the HD version of this board, will give it a go and let you know how it goes.

Well I never made an implementation without having the board itself so this might prove to be a challenge. I hope it installs and runs.

**Comment by Sedgee** [comment]
Well I never made an implementation so again thanks. I'll take it cautiously and here's hoping.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mooiweertje** [comment]
Skip the hope, add patience and perseverance and I have no doubt it will work soon.

**Comment by mooiweertje** [comment]
This is the board of the GepRC Crocodile Baby 5?
![image](https://user-images.githubusercontent.com/37510531/118480573-b7731900-b712-11eb-91b2-a8f14eb70c26.png)
![image](https://user-images.githubusercontent.com/37510531/118480756-f2754c80-b712-11eb-8fa3-efaaac0fac3f.png)

**Comment by Sedgee** [comment]
Hope suffices till perseverance and patience pays off.
Is that the board you've compiled for?
I'm out at the mo but I'll update my spec when I get home.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mooiweertje** [comment]
The build is setup the same as BF GEPRCF722 target.

**Comment by mooiweertje** [comment]
> Thanks for this, I have the HD version of this board, will give it a go and let you know how it goes.

Is it working?

**Comment by Sedgee** [comment]
Not had chance to test due to weather, will be a few days looking at the forecast. Will let you know as soon as I get the opportunity.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mooiweertje** [comment]
Does it flash and run on the board?

**Comment by shcho76** [comment]
Thank you mooiweertje~~!! 
I'm super newbie for drone and inav~~!! 

I flashed your firmware to my span f722 hd fc  and it's run normally!! Great job bros!

I built up for 3inch cinewhoop with gps(without compass) and baro sensor.

I found a issue for the althold, 

When i setup without use hover throttle option. Alt hold function is almost acceptable but the drone reach the sky with full throttle when i choose althold with disable hover throttle option

 I tried to fix it... change some value, set cli commands...Just follow github discussion.. but still reach the moon ~ ~ 

I'm not sure what i did are correct or no correct ^^

**Comment by mooiweertje** [comment]
That sounds like the normal iNav config challenge.

Nice to hear the build is working. If any hardware or pad doesn't seem to work I can help you.

**Comment by shcho76** [comment]
I'd like to add some sensor(optical-flow, ridar, gps with compass, ). Already ordered matek gps and optocal-flow 

I have wondering about uart port. According to manual there are 5uart available. But i found only 2 vacant uart pin.

The pin diagram of f722 hd version is perfect same as your pic'.. i couldn't find not only uart3(may be share with scl sda pin)but also uart4 pin. 
And only 4 uart detected on BF & INAV configurator.
![port](https://user-images.githubusercontent.com/84860122/119694061-d77ba880-be87-11eb-8986-91c0c29f1849.png

 i requested pin out definition to geprc  fot  soft serial setup but they never answers..

**Comment by mooiweertje** [comment]
There are 4 uarts mapped. 1, 2, 4 and 6. The first one in your picture, VCP, is the USB port.

**Comment by mooiweertje** [comment]
There are 4 uarts mapped. 1, 2, 4 and 6. The first one in your picture, VCP, is the USB port. The board itself shows pads for 3 but not 4. That is rather odd. But I'm not sure if the board pictures are correct. I wanted to show pictured of the Baby 5 board but I'm not sure what it looks like. I'm pretty sure the mapping in the software is correct for the board in the baby 5 though.

**Comment by mooiweertje** [comment]
Here it says the BF target is 'GEPRCF722 AIO' but in BF that target does not exist.So I used GEPRCF722. https://geprc.com/product/geprc-crocodile5-baby-lr-hd-longrange-fpv/

**Comment by mooiweertje** [comment]
There is a third target called GEPR-GEPRCF722_BT which has all 6 uarts mapped.

**Comment by mooiweertje** [comment]
The one in the picture seems to have pads for uart 1, 2, 3 and 6 which doesn't match any of the three targets.

**Comment by mooiweertje** [comment]
If there are no pads for the uarts, softserial will not help you.

**Comment by shcho76** [comment]
I looking for crocobile baby fc pic's.. but i can't 

I checked out youtude about croco' baby 4. 
The  f722aio fc looks like 20mmx20mm. So I think the pin diagram of  f722 aio is similar f722 stable series 

Anyway i was so lucky if you had a target firmware of f722 aio for BF. I never get inav firmware !! 😁🤣

**Comment by robustini** [comment]
> 
> 
> I made an implementation to be tested. I don't have the hardware just BF build config. Let me know what the findings are and I will make repairs.
> binary: [jnav_2.6.1.4_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6493212/jnav_2.6.1.4_GEPRCF722.zip)
> source: [GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6493214/GEPRCF722.zip)

Much appreciated your work, thank you!
I have this board, I think it is identical simply remarked: https://it.aliexpress.com/item/1005002006771976.html?spm=a2g0s.9042311.0.0.114f4c4dJpuaQS 
I can compile and test this build, my only problem is that I have the magnetometer obviously connected to SDA / SCL (RX3 / TX3) and I don't know how to remap it in Target.h.
I also have camera control on Motor5 (B06), of course everything works on Betaflight.
If you help me I can test it, thanks!

**Comment by mooiweertje** [comment]
The Betaflight B04 is the real digital B04. That pin on the CPU is connected in the FC print with motor pad 1.

**Comment by mooiweertje** [comment]
The Betaflight B04 is the real digital B04. That pin on the CPU is connected in the FC print with motor pad 1.
It's strange indeed that the BF I2C 2 binding is not the same pads as UART3. Maybe there is some electronics involved here?

**Comment by robustini** [comment]
> 
> 
> The Betaflight B04 is the real digital B04. That pin on the CPU is connected in the FC print with motor pad 1.

Thanks again for the target, tested everything and it seems almost ok!
I don't just work blackbox (says "onboard SD cardd fatal error) and WS2811 led strip, obviously in BF they work.
What could it be?

**Comment by mooiweertje** [comment]
Do you use the GEPRCF722 or GEPRCF722BT betaflight firmware?

**Comment by mooiweertje** [comment]
Do you use the GEPRCF722 or GEPRCF722BT betaflight firmware?
I just noticed the GEPRCF722BT had the same pin mapping for I2C-2 as UART3.

**Comment by robustini** [comment]
I use GEPRCF722, I2C (mag) for fine with your target.

**Comment by mooiweertje** [comment]
If I understand correctly you've got a receiver and a magnetometer on the same two pads RX3/TX3/SDA/SCL?

**Comment by robustini** [comment]
No, serial rx is on UART2, see my image.
UART3 is only for I2C here.

**Comment by robustini** [comment]
![immagine](https://user-images.githubusercontent.com/3864712/120169881-ae994180-c200-11eb-978c-b15cfaee6b45.png)

**Comment by mooiweertje** [comment]
And the led strip is working too?

**Comment by robustini** [comment]
As I wrote above LED and internal flash blackbox doesn't work with your target file.

**Comment by mooiweertje** [comment]
And in betaflight the both work on the GEPRCF722 target?
So you don't use the GEPRCF722BT betaflight firmware?

I'm just making sure so I'm sure I know what to look for. The mappings of the different GEPRCF722xxx betaflight firmwares are rather different.

**Comment by robustini** [comment]
In Betaflight this board is flashed with the same hex as many other F7s ([betaflight_4.2.9_STM32F7X2.hex](betaflight_4.2.9_STM32F7X2.hex)), and after the flash from the configurator a different config file is sent which performs the correct remap for the various boards.
For example for my board this config is automatic written after the flash: https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/GEPR-GEPRCF722.config 

![immagine](https://user-images.githubusercontent.com/3864712/120171722-a0e4bb80-c202-11eb-83b6-1de6d9279e9d.png)

**Comment by mooiweertje** [comment]
yes thank you. i saw something missing in the led strip part. Haven't found what's missing in the flash yet.. I'll make a new build for you later today.

**Comment by mooiweertje** [comment]
yes thank you. i saw something missing in the led strip part. Haven't found what's missing in the flash yet.. I'll make a new build for you later today.

thanks for testing!

**Comment by robustini** [comment]
I'm checking your target too.h, I can't find where the problem lies.

**Comment by mooiweertje** [comment]
For the led strip a timer needs to be defined in target.c.

**Comment by mooiweertje** [comment]
For the led strip a timer needs to be defined in target.c.
    DEF_TIM(TIM1, CH1, PA8, TIM_USE_LED, 0, 0),                            // LED STRIP  D(1, 5, 3)

**Comment by mooiweertje** [comment]
As far as I know all the SD card reader needs is an SPI bus and CS line which is exactly like the betaflight target.

**Comment by mooiweertje** [comment]
Does this one fix the led strip?

[jnav_2.6.1.4_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6569408/jnav_2.6.1.4_GEPRCF722.zip)

**Comment by mooiweertje** [comment]
The Betaflight config has a DMA config which I never seen in iNav.

**Comment by mooiweertje** [comment]
It could be the led strip timer ought to be:

DEF_TIM(TIM1, CH1, PA8, TIM_USE_LED, 1, 0), // LED STRIP D(1, 5, 3)

**Comment by mooiweertje** [comment]
If previous build doesn't fix the LED strip this one might.

[jnav_2.6.1.4_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6569538/jnav_2.6.1.4_GEPRCF722.zip)

**Comment by mooiweertje** [comment]
I don't know what's wrong with the SD card reader.

**Comment by robustini** [comment]
> 
> 
> If previous build doesn't fix the LED strip this one might.
> 
> [jnav_2.6.1.4_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6569538/jnav_2.6.1.4_GEPRCF722.zip)

Led now work fine but the pin would like inverted. 
SD Card reader same issue.

**Comment by mooiweertje** [comment]
Ok.
I don't know what to do about the SD card. The mapping seems to be all right.

**Comment by mooiweertje** [comment]
I updated the previous links to the new build with led strip fixed.

**Comment by mooiweertje** [comment]
As far as I know all the SD card reader needs is an SPI bus and CS line which is exactly like the betaflight target.
I don't know what to do about the SD card. The mapping seems to be all right.

**Comment by robustini** [comment]
> 
> 
> As far as I know all the SD card reader needs is an SPI bus and CS line which is exactly like the betaflight target.
> I don't know what to do about the SD card. The mapping seems to be all right.

Please can you share the updated target fle? Thanks!

**Comment by mooiweertje** [comment]
I updated the previous links to the new build with led strip fixed.

**Comment by mooiweertje** [comment]
So all is working so far except the SD card reader?

**Comment by robustini** [comment]
Yes!

**Comment by robustini** [comment]
> 
> 
> So all is working so far except the SD card reader?

Sorry, I wouldn't want to be wrong, but you declared SDCARD, while this board has an internal flash used as Blackbox storage.
Isn't that the mistake?

**Comment by robustini** [comment]
Example, take from "FURYF4OSD" target.h:

// *************** M25P256 flash ********************
#define USE_FLASHFS
#define USE_FLASH_M25P16
#define M25P16_SPI_BUS          BUS_SPI3
#define M25P16_CS_PIN           PB3

**Comment by robustini** [comment]
I'm compiling the code with this, I'm confident:

// *************** M25P256 flash ********************
#define USE_FLASHFS
#define USE_FLASH_M25P16
#define M25P16_SPI_BUS          BUS_SPI2
#define M25P16_CS_PIN           PB12

#define ENABLE_BLACKBOX_LOGGING_ON_SDCARD_BY_DEFAULT

**Comment by mooiweertje** [comment]
Ah yes, you're right. It's flash not SD.
If your build works please share. If not I will have a look at it again tomorrow using your findings.

> > So all is working so far except the SD card reader?
> 
> Sorry, I wouldn't want to be wrong, but you declared SDCARD, while this board has an internal flash used as Blackbox storage.
> Isn't that the mistake?

**Comment by robustini** [comment]
[GEPRCF722.ZIP](https://github.com/iNavFlight/inav/files/6570046/GEPRCF722.ZIP)

![immagine](https://user-images.githubusercontent.com/3864712/120189308-78b38780-c217-11eb-9e67-ef6a0d414087.png)

**Comment by robustini** [comment]
I had hoped the magnetometer would work, but it didn't, damn.
It finds it but no data moves in SENSOR.

**Comment by robustini** [comment]
@mooiweertje could you point me in the right direction to add EXUAVF4PRO as a target as well?
I am trying but I have constant compilation errors.

**Comment by mooiweertje** [comment]
Can you email your target E4P src files to robustine@mooiweertje.nl? We'll continue our talk through email

**Comment by mooiweertje** [comment]
I get a build error on your target def: undefined reference to `USBD_MSC_EMFAT_fops'

> Tested in flight at the moment only in Angle mode.
> All devices are working correctly.
> 
> [GEPRCF722.ZIP](https://github.com/iNavFlight/inav/files/6570046/GEPRCF722.ZIP)
> 
> ![immagine](https://user-images.githubusercontent.com/3864712/120189308-78b38780-c217-11eb-9e67-ef6a0d414087.png)

**Comment by mooiweertje** [comment]
Can you delete the messages you posted here that we already handled? We're making good progress.

**Comment by robustini** [comment]
> 
> 
> I get a build error on your target def: undefined reference to `USBD_MSC_EMFAT_fops'
> 
> > Tested in flight at the moment only in Angle mode.
> > All devices are working correctly.
> > [GEPRCF722.ZIP](https://github.com/iNavFlight/inav/files/6570046/GEPRCF722.ZIP)
> > ![immagine](https://user-images.githubusercontent.com/3864712/120189308-78b38780-c217-11eb-9e67-ef6a0d414087.png)

Here it is compied without problems, and I even flew there.

**Comment by mooiweertje** [comment]
It was a local problem in the library structure. It's building now and I updated the links at the top.

**Comment by mooiweertje** [comment]
If you like you can make a pull request for this board.

**Comment by mooiweertje** [comment]
For the EXUAVF4PRO please send your target files to robustini@mooiweertje.nl or create an issue here similar to this one but for EXUAVF4PRO.

**Comment by robustini** [comment]
The pull request: https://github.com/iNavFlight/inav/pull/7055

**Comment by robustini** [comment]
Unfortunately, the procedure for getting a new target approved on INAVit requires quite particular steps.
So let's keep these files, we will need them in the future, for those who know how compile the code.

**Comment by mooiweertje** [comment]
Totally agree. But if you do and succeed, the iNav team will maintain it in the future.

**Comment by mooiweertje** [comment]
I can merge iNav 3.0 with my JNav branch when it is released en upload the 3.0 binaries here.

**Comment by mooiweertje** [comment]
I can merge iNav 3.0 with my JNav branch when it is released en upload the 3.0 binaries here. If the target files format didn't change.

**Comment by mooiweertje** [comment]
Version 3.0.0! Test carefully!

Binary: [jnav_3.0.0.6_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6681217/jnav_3.0.0.6_GEPRCF722.zip)

**Comment by robustini** [comment]
> 
> 
> Version 3.0.0! Test carefully!
> 
> Binary: [jnav_3.0.0.6_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6681217/jnav_3.0.0.6_GEPRCF722.zip)

I am aligned with yesterday's master, my flights continue without problems, and with the camera control integrated in my fork.

**Comment by mooiweertje** [comment]
> > Version 3.0.0! Test carefully!
> > Binary: [jnav_3.0.0.6_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6681217/jnav_3.0.0.6_GEPRCF722.zip)
> 
> I am aligned with yesterday's master, my flights continue without problems, and with the camera control integrated in my fork.

Mine with 3.0.0-final

**Comment by mooiweertje** [comment]
Version 3.0.1! Test carefully!

Binary: [jnav_3.0.1.8_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/6765955/jnav_3.0.1.8_GEPRCF722.zip)

**Comment by MrOizo79** [comment]
Any update for this target for 4.0? :)

**Comment by mooiweertje** [comment]
Plz enoy, JNAV 5.0.0.0.

Test and use at your own risk.

Using DJIOSD the speed/altitude/home distance will show max values when disarmed.

[jnav_5.0.0.0_GEPRCF722.zip](https://github.com/iNavFlight/inav/files/9735733/jnav_5.0.0.0_GEPRCF722.zip)
