### ISSUE TITLE
mission WP speed always around 10 km/h in OSD, not as described in mission file and uploaded to EEPROM  

### ISSUE THREAD

**Issue by alccrl** [iNavFlight/inav#7015]
This attached eeprom mission file :

![Mission file](https://user-images.githubusercontent.com/78967144/119274626-253aab80-bc11-11eb-8221-b9c7ab56502a.png)

is executed at 10 Km / h gps speed, not as described in mission file 
parameter1="1000"
parameter1="2000"
parameter1="3000".

Environment:
Inavflight 3.0.0-RC.
Mateksys 722-STD, gps, mag, baro.
Quad in NAV_POS_HOLD while starting Wp mission MODE (custom built QAV-250 quad).
Mission is executed as expected (included hold for 20s on wp4) , except for quad speed, that is always shown around 10 km/h, for every wp leg 1,2,3,4. I tried to look at black box files, but it is not clear the mapping of the various speeds.

Alfredo

Any idea ?

**Comment by stronnag** [comment]
Proabably, you have set the `nav_auto_speed` in the cli, the mission will not exceed that.

**Comment by alccrl** [comment]
I just checked : I have set nav_auto_speed = 300 in my configuration.

**Comment by stronnag** [comment]
So working as designed then.

**Comment by alccrl** [comment]
Thanks,
but I would have close the issue after a retest and check that documentation is enough clear about it, in other words after a check about what design is, because settings.md and inav configurator do not specify exactly what the setting nav_auto_speed is for.
I work quite always In POS_HOLD (that is part of nav), and I can reach 100 km/h in such situation, no limits lay around.
Some time the prefix "nav_" may be confusing. In this case must be associated to waypoint nav, that is a nav subset.

Am I wrong ?

Alfredo
