### ISSUE TITLE
3.0 RC1 - Blackbox logging rate not able to be set higher than 25% (1/4) on F405 wing

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#7016]
F405 Wing, Latest release candidate, not sure if this is a configurator issue or not, but you cannot set the logging rate higher than 1/4 (25%). 

Symptom: Logging rate shows as 25 %

To Reproduce: Set it higher than 25% (i usually do 100%)

let it reboot and go back in to the BB tab and it's back at 25% again

```
# get black
blackbox_rate_num = 1
Allowed range: 1 - 65535

blackbox_rate_denom = 4
Allowed range: 1 - 65535

blackbox_device = SDCARD
Allowed values: SERIAL, SPIFLASH, SDCARD

```

![image](https://user-images.githubusercontent.com/1495297/119276996-2bb62c80-bbeb-11eb-94db-f4bc088d95e4.png)

**Comment by avsaase** [comment]
Do you use 4kHz loop time? I ask because blackbox logging is limited to 1kHz.

**Comment by stronnag** [comment]
#6127 probably

**Comment by wx4cb** [comment]
> Do you use 4kHz loop time? I ask because blackbox logging is limited to 1kHz.

that's entirely possible, lemme check in a minute - never thought about that

**Comment by wx4cb** [comment]
> #6127 probably

most likely.

**Comment by wx4cb** [comment]
yea thats what it is....
