### ISSUE TITLE
Programmed Text message Output in OSD

### ISSUE THREAD

**Issue by FPVZaphod** [iNavFlight/inav#7020]
## Current Behavior
n.A.

## Desired Behavior
It would be great to display custom Text messages, controlled by programming section, on the OSD

## Suggested Solution
In OSD Menu, add a new Item "Text Box" which can be placed somwhere on the OSD.
In "Programming" Tab, add the possibility for "OSD Text" .  There you can choose a Text appearing in the OSD Text Box.
Maybe with the option to choose if the Text remains until deleted, or for a certain amount of time.
Probably even with the Option to show a GVAR. 

## Who does this impact? Who is this for?
Everbody using the programming features. Would be nice to be able to program a visual feedback if the programming does something. Useful also to create custom alerts.

## Additional context
To integrate DJI OSD, this text box could also override the craft name. But this needs prioritization, like "iNav Alerts" overrides "OSD Textbox" overrides https://github.com/iNavFlight/inav/issues/5945

**Comment by avsaase** [comment]
I posted the same idea here: https://github.com/iNavFlight/inav/issues/6241. I'll close this issue to keep things organized.
