### ISSUE TITLE
fw_autotune_ff_to_p_gain and fw_autotune_p_to_d_gain aren't what they seem to be

### ISSUE THREAD

**Issue by ilya-epifanov** [iNavFlight/inav#7034]
## Current Behavior
`fw_autotune_ff_to_p_gain` sets P to FF gain in percentage, *not* FF to P gain.
`fw_autotune_p_to_d_gain` sets D to P gain in percentage, *not* P to D gain.

## Expected behavior
Settings shouldn't have misleading (and completely wrong) names.

## Suggested solution(s)
Since people might have set these options already, I propose to rename them instead of changing what they do.

- INAV version string: 3.0.0 (should've been called 3.0.0-RC1)

**Comment by b14ckyy** [comment]
Yep that hit me too and @avsaase corrected me on that. 
But that won't change for 3.0. Only real bugfixes as it is in RC phase. But that is a good idea for 3.1. Soem work on the PIDFF controller is needed anyway.
