### ISSUE TITLE
Mamba F405 and Frsy xm+ not working

### ISSUE THREAD

**Issue by CharliePapa92** [iNavFlight/inav#7044]
## Current Behavior
Currently I´m running my quad on Betafligt. To use the better GPS features I´m planing to use INAV. I´m using a Mamba F405 stack and a FR sky xm+ reciever via Sbus. This configuration is working well unter Cleanflight and betaflight. Under Inav I don´t see any reciever inputs.  

## Steps to Reproduce
1.Flash Inav 
2. do the calibration 
3.assign uart one as serial Rx (like in Betaflight)
4. choose sbus in reciever tab 

## Expected behavior
I should get an reciever input

## Suggested solution(s)
I´ve tried inverting isgnal and half clock. Both isn´t working. 
Do you have an Idea what to do? 
BR Chris

**Comment by pranjalk197** [comment]
Just reset all settings from the option on first tab of configurator. It worked. Somehow reflash with full chip erase wasn't helping but reset settings worked!??
