### ISSUE TITLE
Support for Skystars F405HD mini

### ISSUE THREAD

**Issue by beeonlinecy** [iNavFlight/inav#7053]
## Current Behavior
No official support

## Desired Behavior
Support multirotors

## Suggested Solution
There is already a working target done and tested by me.

## Who does this impact? Who is this for?
Those who want to get a cheap good quality F4 flight controller.

## Additional context
This FC is a 20x20 small, cheap and good quality, having 
-6 uarts , 
-4 outputs, 
-current input, 
-i2c bus
-8Mb blackbox
-OSD
-Baro
It is confirmed on my test 5" multirotor(quad) with fully working gps,mag and baro.

**Comment by balist911** [comment]
Nice idea. Will make many people happy.

**Comment by beeonlinecy** [comment]
> Nice idea. Will make many people happy.

If there is anybody there who already have this FC and want to try my firmware build I am not greedy to share it

**Comment by balist911** [comment]
I'll be very thankful. balist911@gmail.com

**Comment by beeonlinecy** [comment]
forgot to tell you:
this is only tested with quads, if you are planning to try airplanes , be
careful it may burn your servo. Maybe i should build another version
separately for planes with different pinout one day

чт, 3 июн. 2021 г. в 12:42, balist911 ***@***.***>:

**Comment by balist911** [comment]
I need firmware for a quadcopter. I won't use it on an airplane. Thanks
