### ISSUE TITLE
Ublox via I2C was tested, and confirmed to be impossible/impractical because Ublox only supports 100kHz I2C clock which is way too slow.

### ISSUE THREAD

**Issue by mirov** [iNavFlight/inav#7059]
I came across this older issue when looking at I2C interfaced Ublox GPS modules:
             Ublox via I2C was tested, and confirmed to be impossible/impractical
             because Ublox only supports 100kHz I2C clock which is way too slow.

             _Originally posted by @digitalentity in 
              https://github.com/iNavFlight/inav/issues/2653#issuecomment-356789537_

The UBlox NEO-M8 module spec says that it has a DDC port that is a 400KHz I2C slave-only interface.  My understanding is that you can get data out of the part, but it must be polled and read fast enough not to have internal overruns.  Is that the primary issue ?  On a busy flight controller we just can't pull characters out often enough ?

The motivation for me at least is trying to hook a GPS up to my new CrazyF4 ELRS AIO FC.  It doesn't have spare uarts that I've been able to find, but I can bring out two pins to get an I2C bus (and hook up a MAG/Baro at the same time).  I'd sure like to use it for INAV and have a working RTH / Mission capable quad.  As others have noted, I would imagine that there's some value in having even a slow GPS stream for RTH use.

-Russ

**Comment by pranjalk197** [comment]
Polling won't be an issue since F4s have DMA. I don't know if DMA is used here but DMA offloads the processor from polling and waiting till transaction complete time.
