### ISSUE TITLE
FS-i6x does not working with FURYF4OSD

### ISSUE THREAD

**Issue by kotikvadik** [iNavFlight/inav#7062]
I have a Mamba F405 mk2 flight controller. Target firmware FURYF4OSD. I also use the Flysky FS-i6x remote control with FS-X14S receiver in SBUS mode. FS-X14S connected to FC via RX1 as recomended. If I use INAV with MAMBA F405 board version 2.6.1 everything works fine. But if in INAV I select the FURYF4OSD board with any firmware, for example, v 2.6.1, there is no reaction to the movements of the remote control sticks. What would you suggest.

**Comment by pranjalk197** [comment]
Same issue from INAV 3.0 RC2 with FLYSKY FS IA6b (IBUS) on MATEK F722 STD.

**Comment by SpencerMKSmith** [comment]
I'm having this issue also with my recently purchased Mamba F405 mk2 stack.

**Comment by kotikvadik** [comment]
This does not work with FURYF4OSD! When I upload the firmware for the MAMBA F405, everything works fine.
