### ISSUE TITLE
Blackbox data corrupted

### ISSUE THREAD

**Issue by DarthPlasma** [iNavFlight/inav#7077]
I have problems in reading the blackbox data with inav 3.0. The data appear corrupted and the blackbox shows the model spinning randomly  at a rate of 50000-90000 deg/s

I tried different loggin rates (down to 1/32) with no success

**Comment by wx4cb** [comment]
reformat the SD card and use the latest BB explorer

**Comment by avsaase** [comment]
On my F405-WSE the logs are corrupted when I transfer them via msc but they work fine when I copy them via a USB SD-card reader.

**Comment by wx4cb** [comment]
> On my F405-WSE the logs are corrupted when I transfer them via msc but they work fine when I copy them via a USB SD-card reader.

interesting... cus the logs for the tundra were transferred over msc (FC buried in the fuse) but i had to reformat it first using guiformatter and then it worked fine... I did notice though however, when the drive was loaded in windows the FAT table was what was corrupt.
