### ISSUE TITLE
Inav 3 does not remember the home point

### ISSUE THREAD

**Issue by kasatka60** [iNavFlight/inav#7081]
## Steps to Reproduce

1. RTH mode enable
2. Arming
3. launch fixed wing
4. RTH don't work

on Inav 2.6.1 work fine
- INAV version string:
3.0.0 RC1 and 3.0.0 RC2
matek f722-wing
permanently enabled launch mode

**Comment by stronnag** [comment]
Blackbox log needed

**Comment by kasatka60** [comment]
ok

**Comment by kasatka60** [comment]
I repeated my actions now and now inav remembers the home point.
Sorry. The topic can be closed.
