### ISSUE TITLE
BUG - Dshot Beeper activating on craft without Dshot ESC enabled

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav#7083]
ISSUE:
The Dshot beeper is enabled and active on craft using non Dshot enabled ESCs, e.g. `motor_pwm_protocol `set to STANDARD. This results in the Dshot beeper Arming blocker being set and system messages appearing when not relevant.

SOLUTION:
It appears the Dshot beeper only checks if Dshot is defined for a particular FC not whether it's actually being used. Activation of the Dshot beeper should instead check the motor protocol being used to determine if it should be enabled for a particular configuration.

INAV 3.0.0

**Comment by Jetrell** [comment]
@breadoven I agree with your assessment.
I think I've been a little insulated from this bug. Due to only having _non armed_ beeper commands active and only using Dshot.
