### ISSUE TITLE
Build with VSCode

### ISSUE THREAD

**Issue by JulioCesarMatias** [iNavFlight/inav#7085]
after doing everything in the documents, the VSCode returns errors in the functions, but to compile and generate the .hex file it works normal. Is it normal to show errors like this?

![Captura de tela 2021-06-06 131342](https://user-images.githubusercontent.com/25625982/120931703-1f40d200-c6c9-11eb-925c-3fcd3681772d.png)

**Comment by JulioCesarMatias** [comment]
![Captura de tela 2021-06-06 132440](https://user-images.githubusercontent.com/25625982/120932042-962a9a80-c6ca-11eb-91d7-5d5598d8352d.png)

**Comment by shellixyz** [comment]
It is probably not finding some headers. Might work better if you cmake configure the project from VSC

**Comment by JulioCesarMatias** [comment]
I couldn't solve

**Comment by JulioCesarMatias** [comment]
closing without solution
