### ISSUE TITLE
V-Tail servos is not working on KAKUTE F7 mini V3

### ISSUE THREAD

**Issue by emotialist** [iNavFlight/inav#7097]
I am trying to set up a V-TAIL plane using Holybro KAKUTE F7 mini V3. I considered that will be a good idea, because this controller have 6 dedicated physical motor outputs (M1-M6). I flashed the 3.0.0 RC2 firmware, then set platform type to "Airplane" and mixer preset to VTAIL with single aileron channel. Also, I enabled the PWM output. The tail servos is not working (except throttle), craft is not arming, OSD shows the message "PWM INIT ERROR". Next, I tried to set mixer preset to V-Tail with 2 aileron channels, having same result. Finally, when I changed preset to "flying wing", message "PWM INIT ERROR" is disappeared. 
I repeated above steps with 2.6.1 firmware version, the result is the same. 

## Current Behavior
The tail servos is not working, craft is not arming, OSD constantly shows the messages "PWM INIT ERROR" and "UNABLE TO ARM".

![pwm_issue](https://user-images.githubusercontent.com/85498263/121147844-eb40ea80-c849-11eb-8923-b39a4f81e157.jpg)

## Steps to Reproduce

1. Flash the firmware 3.0.0 RC2 on KAKUTE F7 mini V3
2. Select the "airplane" platform and any of V-Tail mixer preset.
3. Enable the PWM outputs
4. See the OSD message "PWM INIT ERROR"

## Expected behavior
V-tail control PWM signals is expected on M4-M5 outputs for V-tail with single-aileron channel preset, and on M5-M6 for two-aileron channels preset respectively.

## Suggested solution(s)

I supposed, it might be associated to number of servo outputs required for preset, but I'm not sure.

## Additional context

---

- FC Board name and vendor:
Holybro KAKUTE F7 mini V3

**Comment by stronnag** [comment]
Insufficient servos for application
https://github.com/iNavFlight/inav/wiki/Boards,-Targets-and-PWM-allocations#board-kakutef7miniv3
