### ISSUE TITLE
No way to setup OSD for DJI on SP RACING F4 EVO

### ISSUE THREAD

**Issue by pmarkiewicz** [iNavFlight/inav#7112]
## Current Behavior
I flashed v 3.0 to SP Racing F4 EVO to use one with DJI (there is no OSD chip on this board)
I cannot setup OSD on OSD page and get error while trying to setup OSD from cmd line.
OSD is enabled in configuration, DJI is setup in ports

## Expected behavior
Lack of OSD chip shouldn't prevent OSD setup for DJI

## Suggested solution(s)
For current situation OSD configuration should be available based on configuration tab, not on board features

INAV/SPRACINGF4EVO 3.0.0 Jun 12 2021 / 13:06:27 (3c7b1b7c)
[INAV_cli_AR_WING_20210613_205723.txt](https://github.com/iNavFlight/inav/files/6644636/INAV_cli_AR_WING_20210613_205723.txt)

EDIT: screen shots added
![osd1](https://user-images.githubusercontent.com/483107/121865286-102bd680-ccfe-11eb-993f-7aca79f286b2.PNG)
![osd2](https://user-images.githubusercontent.com/483107/121865289-10c46d00-ccfe-11eb-891f-a9a0c66b1af9.PNG)

**Comment by Scavanger** [comment]
Your're right, since every FC can can used with DJI HD, OSD should be enabled for all targets.

Suggested solution:
Add `#define USE_OSD`  to target/common.h

**Comment by wx4cb** [comment]
but the DJI system doesn't use the osd setup anyway, it gets all its information from MSP commands so there is nothing to setup.

You cannot control positions etc. anyway. only thing you can do is to use the CRAFT_NAME trick for things.

**Comment by Scavanger** [comment]
@wx4cb That is completely wrong. Not all elements are supported, but they are set up in the same way as with the analogue OSD, via drag and drop in the Configurator or via the osd_layouts command.

**Comment by wx4cb** [comment]
> @wx4cb That is completely wrong. Not all elements are supported, but they are set up in the same way as with the analogue OSD, via drag and drop in the Configurator or via the osd_layouts command.

then i stand corrected... i thought you couldn't change anything in there
