### ISSUE TITLE
Return to home speed or throttle in Airplane mixer

### ISSUE THREAD

**Issue by LilTeo14** [iNavFlight/inav#7117]
Hello! I was testing the return home function for the first time, I activated the function with a switch and the plane started to turn correctly to the starting position but under the throttle power to 64% which caused the plane to enter after a few seconds. in loss.
![image](https://user-images.githubusercontent.com/44703219/121974925-7e988500-cd4e-11eb-9931-6025b3699f55.png)

I want to know where I can configure so that the return to home function always goes with the throttle to the maximum, and also that it cannot exceed a certain inclination in the pitch to avoid the loss.

![image](https://user-images.githubusercontent.com/44703219/121974975-9c65ea00-cd4e-11eb-9816-a1fa9f99e47f.png)

**Comment by Mateyhv** [comment]
RTH throttle is commanded by cruise throttle.
Bank angle limit you can find under PID tunning tab.

**Comment by LilTeo14** [comment]
@Mateyhv Do you know any link where I explain what each option in the advanced tuning section consists of

**Comment by Jetrell** [comment]
> I want to know where I can configure so that the return to home function always goes with the throttle to the maximum, and also that it cannot exceed a certain inclination in the pitch to avoid the loss.

That will be controlled by the functions outlined in red. 
The info tab `?` gives a brief run down of what each function does.

![FW adv tune](https://user-images.githubusercontent.com/47995726/121986749-70904600-cdda-11eb-8c1e-00e11dfd523d.JPG)

Failing that. You can read through both these links for full iNav fixed wing tuning and set up.
https://github.com/iNavFlight/inav/blob/master/docs/INAV_Fixed_Wing_Setup_Guide.pdf
 https://github.com/iNavFlight/inav/blob/master/docs/INAV_Wing_Tuning_Masterclass.pdf
