### ISSUE TITLE
Board align, inverted mis-calculates  transition through 180

### ISSUE THREAD

**Issue by RobinMosedale** [iNavFlight/inav#7123]
See discussion between Robin Mosedale and Alexander on INAV Fixed Wing Facebook.

FC is inverted and back to front.
Pitch has been corrected by CLI set board_align_pitch = 1800
To realign for roll (otherwise roll right demands further roll right)
CLI set board_align_roll = 1800 (or -1800 with similar effect)

This Inverts the board model on the setup screen, and 3d orientation changes reflected correctly.

However, switching to Horizon mode, one can observe the role axis transitioning through 180 degrees not as 
178, 179,180,181, 182 etc
but
178,179,180, -179, -178 etc

As a result, the fc suddenly thinks it has rotated on its back, and full aileron correction is applied. See videos on facebook, transitioning 1 degree the other way see the opposite full deflection

The effect is observed if set either 1800 or -1800 however the latter displays dramatic oscillation around 180 degrees point
Clearly the calculations around the 180 vertical axis are wrong. Alexander has pointed to src/main/sensors/boardalignment.c

I'm not convinced since the setup page shows the correct orientation. Inspecting the code (No annotation/description but should be self evident) I'm not convinced the error is there. Probably embedded within the guidance code somewhere correcting roll.

**Comment by avsaase** [comment]
Can you add a `diff` from the CLI? Paste it on Pastebin or something and post the link here.

**Comment by avsaase** [comment]
Also, try 
```
set board_align_roll = 1800 # flip the board upside down
set board_align_pitch = 0
set board_align_yaw = 1800 # Make the arrow point backwards
```

**Comment by RobinMosedale** [comment]
Wilco. About 2 hours I'll be in touchRobin
-------- Original message --------From: Alexander van Saase ***@***.***> Date: 15/06/2021  16:58  (GMT+00:00) To: iNavFlight/inav ***@***.***> Cc: RobinMosedale ***@***.***>, Author ***@***.***> Subject: Re: [iNavFlight/inav] Board align, inverted mis-calculates 
  transition through 180 (#7123) 
Also, try
set board_align_roll = 1800 # flip the board upside down
set board_align_pitch = 0
set board_align_yaw = 1800 # Make the arrow point backwards

**Comment by RobinMosedale** [comment]
Wilco. Will report in about 2 hoursRobin
-------- Original message --------From: Alexander van Saase ***@***.***> Date: 15/06/2021  16:58  (GMT+00:00) To: iNavFlight/inav ***@***.***> Cc: RobinMosedale ***@***.***>, Author ***@***.***> Subject: Re: [iNavFlight/inav] Board align, inverted mis-calculates 
  transition through 180 (#7123) 
Also, try
set board_align_roll = 1800 # flip the board upside down
set board_align_pitch = 0
set board_align_yaw = 1800 # Make the arrow point backwards

**Comment by RobinMosedale** [comment]
Regards
Robin

**Comment by RobinMosedale** [comment]
Attempted as suggested. Aileron deflection remains incorrect with these settings

**Comment by RobinMosedale** [comment]
Responded on githubRobin
-------- Original message --------From: Alexander van Saase ***@***.***> Date: 15/06/2021  16:58  (GMT+00:00) To: iNavFlight/inav ***@***.***> Cc: RobinMosedale ***@***.***>, Author ***@***.***> Subject: Re: [iNavFlight/inav] Board align, inverted mis-calculates 
  transition through 180 (#7123) 
Also, try
set board_align_roll = 1800 # flip the board upside down
set board_align_pitch = 0
set board_align_yaw = 1800 # Make the arrow point backwards

**Comment by RobinMosedale** [comment]
Closed. Caused by RC channel throws not set to max 200 on full forward and right.
Then reverse in FC for aileron, and reverse v tail mixing for yaw
