### ISSUE TITLE
FLYWOO f411 v2

### ISSUE THREAD

**Issue by ben9751** [iNavFlight/inav#7127]
- FC Board name and vendor: Flywoo Goku f411 v2
- INAV version string: 3.0.0

Hi,
I have wanted to run inav on my lr4 explorer analogue for a while, but every inav target I find has incorrect mapping of outputs. I have also tried and failed to make my own custom target, as I am not quite sure how to do it.
Please could someone compile a target based on the following cli dump: https://cdn.shopifycdn.net/s/files/1/0010/7410/2324/files/SBUS-analog_F411_V2_BF4.20_EXPOLR-4INCH-T5-R6.txt?v=1610447305

Thank you and have a nice day.

**Comment by mooiweertje** [comment]
I noticed the v1 still has the bugs where TX2 is not configured and S3 doesn't do DShot.
