### ISSUE TITLE
Cannot calibrate accelerometer using sticks

### ISSUE THREAD

**Issue by pensnarik** [iNavFlight/inav#7129]
Hi, I have an issue in both 2.6.1 and 3.0.0 firmware versions. I calibrated accelerometer in iNav configurator but when I started to flight I saw that my drone constantly moves in one direction. I tried to calibrate it using sticks using "Left Up" + "Down" stick positions and saw "Accelerometer not calibrate" on the screen. Also I can't hear beeps when trying to calibrate using stick commands "Trim Acc Right", "Trim Acc Left" etc. I flashed firmware 3.0.0 but still no luck. I have Matek F405-SE controller.

## Current Behavior

When I'm trying to calibrate accelerometer using sticks I cannot hear sounds, controller just reboots.

## Steps to Reproduce

1. Plug in battery.
2. Perform "Acc Trim left" command from sticks
3. Controller reboots

## Expected behavior

1. Plug in battery.
2. Perform "Acc Trim left" command from sticks
3. Hear one "beep" every 1-2 seconds as a confirmation that acc is trimming.

## Suggested solution(s)

Unfortunately, I don't know what to do.

## Additional context

Here is my "diff all" result for 2.6.1: https://pastebin.com/CYSYEDYQ

---
- Matek F405-SE
- INAV version string: 2.6.1 and 3.0.0

**Comment by DzikuVx** [comment]
Most probably you activated `Acc calibrate` command. You have to run full 6-point acc calibration. The best way is to use Configurator.
The Acc trim modifies board alignment, not trims acc. I see that in your diff you have it already setup
```
set align_board_roll = 40
set align_board_pitch = 4
```

My suggestion is to zero those values.

On top of that, you have not stated if drift happens in Angle or Acro mode

**Comment by pensnarik** [comment]
Hi, Paweł. Thank you for your reply. The drift happens in Angle mode. I perform full 6-point acc calibration many times. Also, I still cannot understand why controller reboots every time I try to calibrate it using sticks.
