### ISSUE TITLE
Blackbox files are corrupted

### ISSUE THREAD

**Issue by pensnarik** [iNavFlight/inav#7130]
I configured blackbox and it used to work correctly but after few flights I discovered that new logs contain only 0x00. The files look like they have a correct size but they contain only zero bytes.

## Current Behavior
inav writes zeros to blackbox log files.

## Steps to Reproduce
1. Insert SD card, initialize it in inav-configurator.
2. Make a few flights.
3. All new files contain only zeros.

## Expected behavior
I expect to see a valid data in blackbox logs.

- FC Board name and vendor: Matek F405-SE
- INAV version string: 2.6.1, 3.0.0 (tried both)

**Comment by Minecraftman04** [comment]
I have the same problem with my f722-px, when i open the file in blackbox explorer, it just say something along the lines of, corrupt/can't be opened.

**Comment by pensnarik** [comment]
Hi, @DzikuVx . Why did you close the issue?
