### ISSUE TITLE
DJI Improvements for craft_name probelms

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#7135]
@Scavanger there are a couple of problems with #7098
So far I found out that:

1. Text `CRAFT_NAME` is displayed when no craft name
2. I found no way to remove `CRAFT_NAME` text from cycle
3. Crossfire LQ alarm displayed although I have no crossfire
4. GPS speed displayed although no GPS and element is not configured

**Comment by Scavanger** [comment]
@DzikuVx 
I have fixed 1, 2 and 3.
Unfortunately, I cannot confirm 4. I can switch the OSD element on and off normally.
