### ISSUE TITLE
inav 3.0 gps ublox7 ,update time cannot reach 10hz,max 6.3hz and move up and down

### ISSUE THREAD

**Issue by nkorls** [iNavFlight/inav#7136]
![Q5P({{($5CJ7R{L67TMT}O8](https://user-images.githubusercontent.com/10917488/122495443-a02e9080-d01c-11eb-8077-a6e3872569ae.png)

**Comment by nkorls** [comment]
this gps works fine with inav2.6

**Comment by nkorls** [comment]
![image](https://user-images.githubusercontent.com/10917488/122496136-d6b8db00-d01d-11eb-92e6-ff4acbd56f0f.png)

![image](https://user-images.githubusercontent.com/10917488/122496101-ca348280-d01d-11eb-9707-2473370666bd.png)

use ublox not ublox7,the update time is 5hz and stable

**Comment by nkorls** [comment]
![image](https://user-images.githubusercontent.com/10917488/122496994-454a6880-d01f-11eb-859c-21579d4f9275.png)

ublox7

**Comment by Scavanger** [comment]
You have the protocol set to UBLOX, NOT Ublox7 as you write.
Set it to UBLOX7 and you will get the 10 HZ update rate.

**Comment by nkorls** [comment]
![image](https://user-images.githubusercontent.com/10917488/122567213-021de300-d07b-11eb-83c8-2586a4d6923b.png)
![image](https://user-images.githubusercontent.com/10917488/122567251-0ea23b80-d07b-11eb-8b3b-16818e7b7370.png)
![image](https://user-images.githubusercontent.com/10917488/122567258-11049580-d07b-11eb-9fa1-40e6e9bf49fe.png)
![image](https://user-images.githubusercontent.com/10917488/122567279-1661e000-d07b-11eb-9e76-a90c61348d62.png)

**Comment by nkorls** [comment]
![image](https://user-images.githubusercontent.com/10917488/122584031-744af380-d08c-11eb-8eaa-ccb3b512d752.png)

![image](https://user-images.githubusercontent.com/10917488/122584081-8167e280-d08c-11eb-9649-1d409fdefb8b.png)

The problem is solved
