### ISSUE TITLE
Error compiling settings.md on ubuntu

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#7141]
I'm getting the error:

```
Executing task: python src/utils/update_cli_docs.py <

  File "src/utils/update_cli_docs.py", line 77
    member[key] = f'`{member[key][1:]}`'
                                       ^
SyntaxError: invalid syntax
```

Python version 2.7.18
Python-yaml version 5.3.1-1ubuntu0.1

**Comment by stronnag** [comment]
These days, `python` is `python3`.

Your system is broken / obsolete.

**Comment by MrD-RC** [comment]
Sorted.

**Comment by stronnag** [comment]
We should probably have a python3 shebag at the top of the script for users with older distros ....

**Comment by MrD-RC** [comment]
To be honest, I hardly use ubuntu, and never used python. I just thought that python is python, and it would be the latest version. It gets more confusing when in Windows, using the command Python ...... did compile the docs.
