### ISSUE TITLE
SpeedyBee F7 V2 support

### ISSUE THREAD

**Issue by mooiweertje** [iNavFlight/inav#7144]
## Current Behavior
No SpeedyBee F7 V2 support

## Desired Behavior
SpeedyBee F7 V2 support

## Suggested Solution
Implement SpeedyBee F7 V2 support

## Who does this impact? Who is this for?
SpeedyBee F7 V2 users

## Additional context
Working target files below.

**Comment by mooiweertje** [comment]
This is a test build, be careful. Tested on the bench, basic functions working.

Bluetooth not working.

Binary: [jnav_3.0.0.1_SPEEDYBEEF7V2.zip](https://github.com/iNavFlight/inav/files/6681129/jnav_3.0.0.1_SPEEDYBEEF7V2.zip)
Source [SPEEDYBEEF7V2.zip](https://github.com/iNavFlight/inav/files/6681127/SPEEDYBEEF7V2.zip)

**Comment by mooiweertje** [comment]
@DzikuVx Lovely thanks. For FixedWing I assigned the led pin to a motor and S1-4 to servos on behalve of a friend.

**Comment by maRCnh33** [comment]
I use this firmware but i have a problem. In the modes tab there is no option for "RTH", also no "POSHOLD" 

i am afraid that the failsafe won't work.

**Comment by mooiweertje** [comment]
> I use this firmware but i have a problem. In the modes tab there is no option for "RTH", also no "POSHOLD"
> 
> i am afraid that the failsafe won't work.

That issue is not specific for this target but for all tagets so iNav in general, Please create a new issue.

**Comment by maRCnh33** [comment]
Make sure that *Enable motor and servo output *is enabled

otherwise motors wont spin and servo's wont work....

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op di 10 aug. 2021 om 18:31 schreef Romdrone ***@***.***>:

**Comment by maRCnh33** [comment]
maybe this information is handy for you!

https://inavfixedwinggroup.com/guides/getting-started/inav-fixed-wing-setup-guide/

Op di 10 aug. 2021 om 18:45 schreef maRCnh33 ***@***.***>:

**Comment by Romdrone** [comment]
Thanks for the good advice..

**Comment by maRCnh33** [comment]
Motors are spinning  now?

Op di 10 aug. 2021 19:19 schreef Romdrone ***@***.***>:

**Comment by Romdrone** [comment]
Absolutely!!!!
Thanks again

**Comment by Romdrone** [comment]
Now I'm trying to figure out how to remap my motors..!!!

Le mar. 10 août 2021 à 19:36, Romuald Graffan ***@***.***> a
écrit :

**Comment by Romdrone** [comment]
Gonna get there..

Le mar. 10 août 2021 à 19:36, Romuald Graffan ***@***.***> a
écrit :

**Comment by Romdrone** [comment]
A quick question.. The quad I'm converting to inav used to run betaflight and I installed a realpit modul that allows me thrue a pinio command to switch on or off my vtx... Should I give it up or is there a way to get it to work with inav..?

**Comment by maRCnh33** [comment]
Sorry i dont know..

Sorry

Maybe someone else can help you woth that

Op di 10 aug. 2021 20:46 schreef Romdrone ***@***.***>:

**Comment by mooiweertje** [comment]
@Romdrone All the questions you ask are not specific to this board. You can test the pinio and if it doesn't work please report here and I will try to resolve the issue you have.
How to use iNav you can read in the manual of your hardware or iNav docs, etc.

**Comment by Romdrone** [comment]
Thank you for the answer.

Le mer. 11 août 2021 à 09:55, Mooiweertje ***@***.***> a
écrit :

**Comment by mooiweertje** [comment]
All the questions you ask are not specific to this board. You can test the pinio and if it doesn't work please report here and I will try to resolve the issue you have.
How to use iNav you can read in the manual of your hardware or iNav docs, etc.

**Comment by mooiweertje** [comment]
@Romdrone  All the questions you ask are not specific to this board. You can test the pinio and if it doesn't work please report here and I will try to resolve the issue you have.
How to use iNav you can read in the manual of your hardware or iNav docs, etc.
iNav is not betaflight so following betaflight documentation doesn't help with iNav.

**Comment by mooiweertje** [comment]
Something about pinio and iNav: https://youtu.be/FYcaot9tvc4

**Comment by Romdrone** [comment]
The "set pinio_box = 40,41,42,43" always results in a "invalid name"


Le mer. 11 août 2021 à 23:22, Mooiweertje ***@***.***> a
écrit :

**Comment by mooiweertje** [comment]
@Romdrone If you think that is a missing feature you can report this in a separate iNav issue.

**Comment by mooiweertje** [comment]
@Romdrone If you think that is a missing feature maybe you can report this in a separate iNav issue. Watching the pinbox video of @DzikuVx it seems there is no need to "set pinio_box = 40,41,42,43"

**Comment by mooiweertje** [comment]
@Romdrone Can you please remove your answered questions to keep this page clean?

**Comment by avsaase** [comment]
Some cleanup ☝🏻

**Comment by Romdrone** [comment]
I removed all my messages. Didn't I??

**Comment by mooiweertje** [comment]
@avsaase thanks

**Comment by ryet9** [comment]
Hello.. I still can't get jnav_3.0.0.8_SPEEDYBEEF7V2 to work with 3.0.1 configurator


# INAV/SPEEDYBEEF7V2 3.0.1 Jul  5 2021 / 05:09:04 (fa7bb22d)
You didn't update your version untill the 6th of July.. PLEASE tell me how I stole ur code again & pretended it was mine.

also I had bluetooth working.. but hey, just ignore that facts... show me jnav_3.0.0.8 working with 3.0.1 configurator.

"In the open source community is what you are doing here not so nice. Pretending you made something while you just copied from someone else. The firmware you call old and not working works just fine so you are even lying about it.
Please remove this page." -- mooiweertje aka Mooi Weertje on youtube.

So whats the lie ? - there isn't one, apology accepted!!

**Comment by mooiweertje** [comment]
@ryet9 If you helped improving this build you would have contributed here and not copy what's here to your own VLOG.

**Comment by mooiweertje** [comment]
@ryet9 If you helped improving this build you would have contributed here and not copy what's here to your own VLOG. I don't see any help here from you so I son't know what you refer to when you say you will never help anymore.

**Comment by mooiweertje** [comment]
@ryet9 If you helped improving this build you would have contributed here and not copy what's here to your own VLOG. I don't see any help here from you so I son't know what you refer to when you say you will never help anymore. You're not helping and you never did.

**Comment by ryet9** [comment]
You need to check the dates b4 u say I copied anything... also ur right.. I have never helped here... and I wont be, I do like the project all the best with it, but go fuck urself.

**Comment by mooiweertje** [comment]
If you like what I do for you thanks would be appreciated.

**Comment by mooiweertje** [comment]
The reason nobody is working on this target anymore is that it is working fine as it is and it is moved to the next iNav release.
If you like what I do for you thanks would be appreciated.

**Comment by ryet9** [comment]
yeah it's fine, ..Thanks. <3

**Comment by mooiweertje** [comment]
@ryet9 hahaha, lovely

**Comment by mooiweertje** [comment]
@ryet9 You're welcome

**Comment by ryet9** [comment]
What does that have to do with anything? 40, should I grow up or something?
how about you, assuming I time travelled to the future.. stole your code.. compiled it so I could get 10 views on ma youtube

**Comment by mooiweertje** [comment]
@stronnag Can this complete issue be removed or closed for commenting? I'm the creator but I can't do this.

**Comment by ryet9** [comment]
close the hell out of it, but do know I didn't steal your code b4 you even posted it, very insulting.

**Comment by ryet9** [comment]
Comments deleted, do the same @mooiweertje ?
