### ISSUE TITLE
Mavlink not working in 3.0.0 final

### ISSUE THREAD

**Issue by mtnmikev** [iNavFlight/inav#7156]
## Current Behavior 
No Mavlink connectivity 

## Steps to Reproduce
I opened an issue on RC1 and this was fixed in a nightly.  The fix did not make it to RC 2 or 3.0.0 stable

## Expected behavior
Mavlink data to tracker via Crossfire Bluetooth 

## Suggested solution(s)

Matek F405 wing
3.0.0

**Comment by OptimusTi** [comment]
there's something new coming soon...

**Comment by mtnmikev** [comment]
This is the build I was given  
http://seyrsnys.myzen.co.uk/inav_dev/?fbclid=IwAR0nPw0y_W1G6AiOwXoFaLla_t_Ewbc2CKllLrqLE3tzl-9SKU-fTDyjzxM

**Comment by stronnag** [comment]
1. Use an official build
2. It works for me
3. In any case, the builds at http://seyrsnys.myzen.co.uk/inav_dev/ are now 3.1 (current master)

**Comment by stronnag** [comment]
As inav demonstrably generates protocol valid Mavlink (V1 and V2), I'm closing this. If you wish to have it investigated further, please provide:

* cli `diff`
* Serial capture of mavlink direct from inav (i.e. without CRSF)
* Serial capture of mavlink over CRSF
