### ISSUE TITLE
Matek F722 STD Baro fail in 3.0 

### ISSUE THREAD

**Issue by RipperGOT** [iNavFlight/inav#7159]
The barometer indicates -44220 in the sensors tab and 50 I2C errors, with previous version does not happen .
![Captura de pantalla 2021-06-21 153535](https://user-images.githubusercontent.com/86242264/122771513-ca937e80-d2a6-11eb-8ebd-8f1d9a5a3b21.jpg)

**Comment by DzikuVx** [comment]
see #7163
