### ISSUE TITLE
X-Racer level drift

### ISSUE THREAD

**Issue by mmormota** [iNavFlight/inav#716]
Test condition:
usb cable connected, the board is horizontal, the pitch and roll axis keeps drifting. The drift is fast, 10...50 degree/minute. The acc sensor graph showing that the x and y value is constant 0.

Board: X-Racer F3
Fw: SPRACINGF3 1.2.1. 
clean install with full chip erase, no settings changed

**Comment by oleost** [comment]
Start here and then report back.. 

https://github.com/iNavFlight/inav/wiki/4.-Sensor-calibration

**Comment by digitalentity** [comment]
@mmormota is this bug fixed after 6-point accelerometer calibration?

**Comment by digitalentity** [comment]
Closing due to no feedback.
