### ISSUE TITLE
Flywoo F411 HEXA target is missing

### ISSUE THREAD

**Issue by Guili123** [iNavFlight/inav#7169]
Flywoo sells the Firefly iNav edition, but have an iNav 3.0 RC used for this.
Since Flywoo has not released a final version on their website I was expecting that is available within
the iNav configurator.
Two F411`s are available, but not the F411 Hexa Edition.
Same for the F7 Hexa Version, but not sure if another Flywoo F7 is compatible.

Please add the Flywoo F411 Hex target for iNav.
Thanks

**Comment by d-hartmann** [comment]
I‘d be interested in this as well. No Goku F411 hex target is available. Can wen assist in getting this target be made available?

**Comment by fanedi** [comment]
interested too

**Comment by Guili123** [comment]
Send me an PM on Facebook: https://bit.ly/3s79LPx
I compiled an target based on iNav 3.0.1. and I can send it to you.

**Comment by UnchartedBull** [comment]
@Guili123 any chance you still have the build files with all the definitions? Would love to have them handy to build iNav 5 and future iNav releases. Thanks!

**Comment by d-hartmann** [comment]
Would really be great to have a recent version of Inav available. My 👍, if that could be made possible.
