### ISSUE TITLE
DShot MAMBA405

### ISSUE THREAD

**Issue by PATRONzzz** [iNavFlight/inav#7175]
I have a "Mamba F405minimk3 DJI + MAMBA F50_BL32 4IN1 ESC 60A 6S" board and companion 4in1 esc which run Betaflight 4.1 without problem. However, when I try to use DShot (any variant) in my newly minted INav firmware then motor4 does not spin up.

Motor 4 also does not spin up using passthrough to BLHelsuite32 if the FC is running INav but it does if the FC is running Betaflight.

In other posts, the same problems were encountered on the F722. As I understand it, it is necessary to make changes to the code.

inav_3.0.0_MAMBAF405US.hex

**Comment by DzikuVx** [comment]
Mamba mk3 uses `_I2C` target
