### ISSUE TITLE
Support multiple I2C buses at the same time 

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#718]
While working on #717 and #688 I've discovered that we do not initialize multiple I2C devices even if target requires that.
For example REVO target, built-in MAG and BARO usues I2CDEV_1 while I2C pins on board are connected to I2CDEV_2

**Comment by digitalentity** [comment]
Initialisation of `I2C_DEVICE_EXT` came along with 0d4a3988929c7a0e6ba17a4bae28043e01a7b4a2

However sensor can be compiled only to use one or the other. I.e. on REVO we can have support either for onboard HMC5883L or the external one. Can't support both and switch by a CLI option.

**Comment by DzikuVx** [comment]
OK, I'm closing this one since it solves the problem I've raised. Sensor assignment is completely different thing
