### ISSUE TITLE
UK OSD units are not what are used in the UK

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#7191]
Hi guys, the UK units aren't what's actually used here.

Altitude should be in feet
Distance should be in miles
Temperature should be in C

We don't use km at all.

**Comment by wx4cb** [comment]
dang.. would be nice to multiple +1 this lol

**Comment by MrD-RC** [comment]
@wx4cb I’ve written the code, and it’s been added to the 3.1 milestone. Hopefully it will be merged. 

A lot of the UK FPV pilots I know just use imperial, because “UK” is not UK. 

Once it’s merged, I’ll also be working on a GA (General Aviation) units set. This has already gone down very well, with positive support.

**Comment by wx4cb** [comment]
yup darren... "uk" is EU LOL imho but yea the GA thing would be cool. as that's what i'm used to
