### ISSUE TITLE
INAV 3.0 TURTLE Model Wrong motor steering

### ISSUE THREAD

**Issue by ethanCavendish** [iNavFlight/inav#7194]
![image](https://user-images.githubusercontent.com/18661793/123513198-5863d500-d6be-11eb-9098-44ce26aeb0ac.png)

https://user-images.githubusercontent.com/18661793/123513213-6dd8ff00-d6be-11eb-9b70-3533d35dc744.mp4

FC: Omnibus F4V3S

**Comment by avsaase** [comment]
Please provide more info.

**Comment by JulioCesarMatias** [comment]
> Please provide more info.

.

**Comment by JulioCesarMatias** [comment]
this is weird

**Comment by JulioCesarMatias** [comment]
does your multirotor fly normally? Why are the engines really inverted

**Comment by JohnRambo7039** [comment]
> does your multirotor fly normally? Why are the engines really inverted

It can fly normally, only but with TURTLE mode on, the motor steering is reverse

**Comment by JohnRambo7039** [comment]
this is my dump:

[# dump.log](https://github.com/iNavFlight/inav/files/6720394/dump.log)

**Comment by JohnRambo7039** [comment]
What else do I need to offer?

**Comment by JulioCesarMatias** [comment]
> What else do I need to offer?


What version of inav are you using? already tried with another version to see if the problem still exists?

**Comment by JulioCesarMatias** [comment]
> What else do I need to offer?


for now nothing, you just need to wait for someone to help you, or have the same problem as you so that the developers find and fix the problem.

**Comment by througer** [comment]
Same problem here. The multirotor works normally, but in turtle mode the motors do not get reversed. 
I have checked if the ESC have the right fw, also ESC beeping is working.

INAV 3.0.1
FC: OmnibusF4V3
4in1 30A ESC blheli_s 16.7

**Comment by avsaase** [comment]
I noticed this problem myself yesterday. The correct motors spin up but do so in the wrong direction.

**Comment by Oleg-Si** [comment]
Same problem here. The multirotor works normally, but in turtle mode the motors do not get reversed.

INAV 3.0.1
FC: Matek F405-SE
ESC: Spedix ES30 HV 30A 3-6S BLHeli_S

**Comment by Odin263** [comment]
Same problem here.

INAV 3.0.2 / INAV 3.1.0
FC: IFLIGHT SUCCEX F7 mini
ESC: G_H_30_REV16_73
DSHOT 600

Maybe this can help someone:
![image](https://user-images.githubusercontent.com/90968252/133889087-40e715fc-7616-4829-a6a7-cdcae85a1dc4.png)

**Comment by JulioCesarMatias** [comment]
> Same problem here.
> 
> INAV 3.0.2 / INAV 3.1.0
> FC: IFLIGHT SUCCEX F7 mini
> ESC: G_H_30_REV16_73
> DSHOT 600
> 
> Maybe this can help someone:
> ![image](https://user-images.githubusercontent.com/90968252/133889087-40e715fc-7616-4829-a6a7-cdcae85a1dc4.png)


I believe this will not solve anything

**Comment by JulioCesarMatias** [comment]
the last PR that made a lot of changes was this >> https://github.com/iNavFlight/inav/commit/1a6f96ce32b39c9092fcc0ae1b27936814c16e19


maybe the problem is in this PR, but I haven't found anything at the moment.

**Comment by Odin263** [comment]
Everything is correct with the bracket. I got it wrong. The error is
also not in turtle mode. The 3D mode does not work either and
therefore something is wrong with the change in the direction of
rotation. I will continue to search for it with my possibilities.


Am Sa., 18. Sept. 2021 um 16:42 Uhr schrieb Julio Cesar Matias <
***@***.***>:

**Comment by englebert** [comment]
Guys, I fixed mine!!
Below is the patch...
diff --git a/src/main/drivers/pwm_output.c b/src/main/drivers/pwm_output.c
index 37f0bda43..f69895900 100644
--- a/src/main/drivers/pwm_output.c
+++ b/src/main/drivers/pwm_output.c
@@ -357,7 +357,7 @@ static int getDShotCommandRepeats(dshotCommands_e cmd) {
     switch (cmd) {
         case DSHOT_CMD_SPIN_DIRECTION_NORMAL:
         case DSHOT_CMD_SPIN_DIRECTION_REVERSED:
-            repeats = 6;
+            repeats = 10;
             break;
         default:
             break;
