### ISSUE TITLE
OmnibusF4V3  HMC5883 (BN-880 Mangeto) hardware error only on inav 3.0 

### ISSUE THREAD

**Issue by krl91** [iNavFlight/inav#7207]
## Current Behavior

with inav 3.0 and omnibusf4v3 firmware I cannot have  HMC5883, but if I use 2.5.1 BMP280 and HMC5883  are working perfectly fine.

## Steps to Reproduce
 
1. install inav 3.0 omnibusF4v3 firmware (for omnibus F4 v5 ) with last inav configurator stable version (29/06/2021)
2. Calibrate the gyroscope 
3. configure HMC5883 (magnetometer) and BMP280 (barometer)
4. magnetometer is red
5. Calibrate the magnetometer
6. Magnetometer is still red
7. redo the same with inav 2.5.1 and inav configurator 2.5 both  (magneto and baro) are working fine

## Expected behavior
HMC5883 should work with BMP280 (both  are in i2c)

## Additional context
dump from 2.5.1

---
[inav2.5.1_ok.txt](https://github.com/iNavFlight/inav/files/6729700/inav2.5.1_ok.txt)

- FC Board name and vendor: Airbot omnibus F4 V5 (original)

**Comment by JulioCesarMatias** [comment]
looking at your dump, the compass is not calibrated.

**Comment by JulioCesarMatias** [comment]
your IMU is also not calibrated.

**Comment by JulioCesarMatias** [comment]
whenever you put a firmware version on your flight controller, it is highly recommended that the sensors be recalibrated.

**Comment by krl91** [comment]
Hi, you're right, I forgot to write it but I did the configuration in both cases.

**Comment by JulioCesarMatias** [comment]
> Hi, you're right, I forgot to write it but I did the calibration in both cases. (I just updated the issue)


ok, weird, the dump shows that the compass has not been calibrated. Have you ever tried to redo the calibration again?

**Comment by JulioCesarMatias** [comment]
it seems to me that nothing was done, because the mix was also not configured

**Comment by JulioCesarMatias** [comment]
did you update the firmware with "Full chip erase"?

**Comment by krl91** [comment]
Maybe it was not the good dump, I did it again :
[inav2.5.1_ok_2.txt](https://github.com/iNavFlight/inav/files/6729764/inav2.5.1_ok_2.txt)

 and yes, always full chip erase (I had to unplug the BN-880 if not I cannot erase)

**Comment by JulioCesarMatias** [comment]
use iNav communication channels to try to solve your problem:

https://t.me/INAVFlight

https://www.facebook.com/groups/INAVOfficial

**Comment by JulioCesarMatias** [comment]
> use iNav communication channels to try to solve your problem:
> 
> https://t.me/INAVFlight
> 
> https://www.facebook.com/groups/INAVOfficial


I haven't found any problem here that matches yours. I recommend you to try telegram or facebook

**Comment by JulioCesarMatias** [comment]
did you select the compass template manually, or let iNav automatically search the i2c bus? Maybe it could be a QMC5883 instead of an HMC5883

**Comment by JulioCesarMatias** [comment]
about the title of the issue, it's not a conflict, the i2c addresses are different.

**Comment by krl91** [comment]
Ok thanks, I correct it

**Comment by krl91** [comment]
Ok, I don't know why exactly but it works now.. I was recording a video and this time

**Comment by JulioCesarMatias** [comment]
você trocou manualmente de HMC5883 para QMC5883?

**Comment by mainframecn** [comment]
i had a similar issue and had to reduce the I2C speed (configuration) from 800khz to 400khz.
