### ISSUE TITLE
Matek F405-CTR with iNav 3.0.0 does not recognize baro or battery voltage

### ISSUE THREAD

**Issue by mrduncan626** [iNavFlight/inav#7208]
Just flashed 3.0.0 on my Matek F405-CTR and Battery Voltage and the Baro are no longer working.  

1. The Configurator did find the Baro (BMP280).   Configurator Sensors Tab indicate the baro is -40,000 and altitude is 0.  
2. The Battery Voltage is enabled in the Configurator.  When a 4S Lipo is connected to the FC, the voltage display is 0v

ReFlashed back to 2.6.1 and Battery Voltage and the Baro are working correctly. 

From CLI:
version
INAV/MATEKF405 3.0.0 Jun 12 2021 / 12:25:44 (3c7b1b7c)
GCC-9.3.1 20200408 (release)

**Comment by JulioCesarMatias** [comment]
make your FC Dump available. Flashed with "Full Erase Chip"?

**Comment by JulioCesarMatias** [comment]
are you using a led strip?

**Comment by JulioCesarMatias** [comment]
I've also seen some people say that they were only able to make the barometer work with the battery connected to the FC.

**Comment by JulioCesarMatias** [comment]
Matek recommend `CLI “defaults” after reflashing`

**Comment by mrduncan626** [comment]
Using your recommendations resulted in the same non-functional battery voltage and baro readings.

**Comment by avsaase** [comment]
@mrduncan626 the baro issue is known and will be fixed in 3.0.1. Untill then it is save to fly with this because it it just an offset in the baro calibration, which will be reset to zero when arming.

**Comment by mrduncan626** [comment]
Thanks for the answer.  I'll waiting until 3.0.1 is released.

**Comment by avsaase** [comment]
Then I'll close this issue now.

**Comment by JulioCesarMatias** [comment]
> @mrduncan626 the baro issue is known and will be fixed in 3.0.1. Untill then it is save to fly with this because it it just an offset in the baro calibration, which will be reset to zero when arming.


I thought this was just on matekf722, thanks for explaining
