### ISSUE TITLE
Slowing servos only works once.

### ISSUE THREAD

**Issue by HealsScott** [iNavFlight/inav#7220]
## Current Behavior
Flaps deploy slowly the 1st time they are engaged but revert back to fast the 2nd time.

## Steps to Reproduce

1. Programming tab: Set logic condition to be on when a rc channel is high (your flaps switch)
2. Mixer tab: set flaps servos to your flaps switch channel only when the logic condition is on.
3. Set flaps servo to 40 (400pwm) per second.
4. Hit flaps switch, flaps cone down slow, turn off flaps switch, flaps go up, turn on flaps switch, flaps come down fast.

## Expected behavior
 flaps deploy slowly every time, not just the 1st time.

## Suggested solution(s)

3.0
- FC Board name and vendor:
Matek f765
- INAV version string:
-3.0

**Comment by DzikuVx** [comment]
Speed is not respected when LC is deactivated. Suggested solution is to set servo position from GVAR and set GVAR in -500:500 when switch is switched

**Comment by HealsScott** [comment]
Hi Pawel,Thanks for the response.I understand all of that except for the actual critical part of "-500:500 when switch is switched"Any help for a laymen?
-------- Original message --------From: Paweł Spychalski ***@***.***> Date: 6/7/21  9:59 pm  (GMT+08:00) To: iNavFlight/inav ***@***.***> Cc: HealsScott ***@***.***>, Author ***@***.***> Subject: Re: [iNavFlight/inav] Slowing servos only works once. (#7220) 
Speed is not respected when LC is deactivated. Suggested solution is to set servo position from GVAR and set GVAR in -500:500 when switch is switched

**Comment by DzikuVx** [comment]
You have to build you own mixer rules with Programming Tab in configurator
