### ISSUE TITLE
Matek H743-SLIM goes to solid red light (but not DFU mode) after choosing Octo x8

### ISSUE THREAD

**Issue by alexrjohnston** [iNavFlight/inav#7231]
iNav 3.0.1 and 3.0.1 configurator
Matek H743-SLIM

Recreate:
flash iNav 3.0.1 to board
choose Mini Quad option on first connect
set mixer to octo x8
now set any of the presets - FC crashes to just a red light even after power cycle.
only way to restore is reflash

edit: 
choosing the preset first then Octo x8 causes the same thing

**Comment by DzikuVx** [comment]
@alexrjohnston for the time being, please use Multishot ESC protocol. It happens only with DSHOT

**Comment by DzikuVx** [comment]
@MATEKSYS do you have any insights? Seems like resource clash

**Comment by DzikuVx** [comment]
Important, happens only when DSHOT output is assigned to S8. Hexa with DSHOT or 7 DSHOT outputs are working fine

**Comment by MATEKSYS** [comment]
We have tested X8 Dshot without any clash,  
Try the firmware attached in this PR.  in fact.  It was built from 3.1 development,  We modified the version number to make it work with configurator 3.0
https://github.com/iNavFlight/inav/pull/7185

**Comment by DzikuVx** [comment]
@MATEKSYS OK, I will recheck build from `master` to verify

**Comment by DzikuVx** [comment]
Retested, build from `master` , enabling DSHOT600 and OctaX prohibits board from booting

**Comment by MATEKSYS** [comment]
seems it is something related to configurator 3.0.1.  I was using configurator 3.0.0 before.  now I am using 3.0.1, when I set Dshot and X8, FC will freeze.

**Comment by DzikuVx** [comment]
The only changes between 3.0.0 and 3.0.1 was the updated flashing procedure that works with Full Chip Erase on H7. This is not this.

Also, verified your firmware. Not working. I think it's DMA Stream assignment problem. We are not using DMAMUX since it was causing other problems, and there is no DMA1 Stream8

**Comment by DzikuVx** [comment]
@alexrjohnston  @MATEKSYS please see #7232
