### ISSUE TITLE
RTH Failsafe enabled WITHOUT GPS

### ISSUE THREAD

**Issue by maRCnh33** [iNavFlight/inav#7233]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CO
**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.RTH is available and can be enabled without GPS installed
2.
3.
4.

## Expected behavior
Drone will fall down to the ground when activating RTH

## Suggested solution(s)
Please repair/fix this

## Additional context

---

- FC Board name and vendor:
- INAV version string: 3

**Comment by stronnag** [comment]
This is documented feature of inav. GPS is required for RTH,

**Comment by stronnag** [comment]
For completeness, that we allow users to configure RTH wiith GPS detected is **also a feature**

**Comment by mooiweertje** [comment]
I understand that RTH will not work on a quad without a compass?

**Comment by mooiweertje** [comment]
There are some people that expect a quad to RTH when failsafe is activated (mode switch) because because they configured it that way but the quad just drops?
