### ISSUE TITLE
No Target for my FC

### ISSUE THREAD

**Issue by mchaos** [iNavFlight/inav#7241]
## Current Behavior
There is no current target for my FC, FPVM_BETAFLIGHTF7

## Desired Behavior
I'd like to see a target for it so I can use this on one of my builds. Or at least if someone knows of a target which is nearly the same to which I would just have to fix some mappings to make it work.

## Suggested Solution
Compile a Target for FPVM_BETAFLIGHTF7 or just let me know one that will work?

## Who does this impact? Who is this for?
Anyone with an FPVM_BETAFLIGHTF7

## Additional context
Thanks in advance.

**Comment by mchaos** [comment]
Wow...not even a peep? No one wants to address this at all with at least some lame excuse? Guess I'm not using Inav....:(

**Comment by OptimusTi** [comment]
peep

https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by Mateyhv** [comment]
> 
> 
> Wow...not even a peep? No one wants to address this at all with at least some lame excuse? Guess I'm not using Inav....:(

Maybe its better to get an FC that already has a target for Inav instead of asking that someone spends lots of time developing a target for you.
