### ISSUE TITLE
#define DEFAULT_RX_FEATURE  FEATURE_RX_SERIAL

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#725]
Looks like `#define DEFAULT_RX_FEATURE      FEATURE_RX_SERIAL` is not working

**Comment by WaspFPV** [comment]
Did you assign a port for it in the default serial settings? If no port is selected when feature Serial_rx is used, it will revert to PWM/PPM and save that config.
Personally, I would use PPM as safe default since Serial RX needs more setup (port, protocol, etc)

**Comment by DzikuVx** [comment]
There is something more than that since configurator landed in a strange
"no rx state"

śr., 26.10.2016, 11:23 użytkownik André notifications@github.com napisał:

**Comment by oleost** [comment]
@DzikuVx What is the status on this one?

**Comment by DzikuVx** [comment]
Not sure if it still exists, did not saw it for a longer time

**Comment by DzikuVx** [comment]
obsolete
