### ISSUE TITLE
Mavlink doesn't send GPS position since 3.0

### ISSUE THREAD

**Issue by pitersonfascist** [iNavFlight/inav#7257]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior
After upgrading to IINAV 3.0 telemetry over Mavlink stopped sending GPS coordinates as well as the number of satellites.
But still, I get GPS speed.

## Steps to Reproduce

1. Flash inav 3.0 or 3.0.1
2. set telemetry protocol to Mavlink
3. All sensors are sent (attitude, battery, current, RSSI) except GPS coordinates

## Expected behavior
GPS position is sent over Mavlink telemetry protocol as it was in all previous Inav versions

## Additional context

---

- FC Board name and vendor: Matek F405, Matek F411SE, FC10DOF
- INAV version string: 3.0.0, 3.0.1

**Comment by stronnag** [comment]
Works OK here, valid mavlink telemetry includes:

* mavlink_msg_gps_raw_int
* mavlink_msg_global_position_int
* mavlink_msg_gps_global_origin

For both Mavlink v1 and Mavlink v2
