### ISSUE TITLE
Target KAKUTEF4V2 3.1.0 GPS fix become laggier.

### ISSUE THREAD

**Issue by konstantinfpv** [iNavFlight/inav#7261]
Here what I found while tested the 3.1.0 KAKUTEF4V2 hex where @DzikuVx fixed the gyro. #7235 
GPS fix becomes laggier.

My quad is at the window and powered by USB for more than 60 minutes, so I have a Hotstart condition.

Test algorithm:
#ROUND 1
1. Flash KAKUTEF4V2 3.0.1. 
2. Set UART 6 GPS
3. Apply Config 
```
gps_provider = UBLOX7
gps_sbas_mode = EGNOS
gps_dyn_model = AIR_1G
gps_auto_config = ON
gps_auto_baud = ON
gps_ublox_use_galileo = ON
gps_min_sats = 6
inav_use_gps_velned = ON
inav_use_gps_no_baro = OFF
inav_w_z_gps_p =  0.200
inav_w_z_gps_v =  0.100
inav_w_xy_gps_p =  1.000
inav_w_xy_gps_v =  2.000

```
![3 0 1 uberfast fix](https://user-images.githubusercontent.com/84969930/125534597-1dcccf30-839f-44b5-a7e0-3bf4ba32fcb1.JPG)
#RESULT I received Fix in less than 250 messages and GPS Statistics is alive when I open the GPS tab. The update time is always 10.0Hz. GPS indicator in the configurator is blue (on).

#ROUND 2
1. Flash KAKUTEF4V2 3.0.1. 
2. Set UART 6 GPS
3. Apply Config above
![3 1 0 no fix](https://user-images.githubusercontent.com/84969930/125534864-376ed2c0-b032-46b8-81e6-6799bf7bcd6c.JPG)
#RESULT No fix, GPS Statistics is frozen except Update time that is glitching 9.9-12Hz. . GPS indicator in the configurator is blue (on).

UPDATE I got Statistic alive and fix after UBERLONG 28k messages, if I turn it off for 2 min I receive statistics alive and fix not less than 2500 messages, but that result is unstable, cos after I paste CLI dump and saved I've again got endless boot time.
![Снимок](https://user-images.githubusercontent.com/84969930/125536100-6a137a3b-4ddb-40f5-93ed-de0ff6f3896e.JPG)

#ROUND 3
1. Repeat flashing 3.0.1 like in ROUND1
#RESULT GPS fix instantly less than 250 messages.

FC Board name and vendor: Holybro Kakute f4 v2 mini
INAV version string: 3.1.0

**Comment by DzikuVx** [comment]
This is up to your GNSS receiver and GNSS satellites to obtain valid fix.
INAV is not target specific in that case and if GPS icon is blue, that means INAV did all it could: port is configured, GNSS receiver configured and INAV is receiving data from the GNSS receiver.

It's also not a problem of 3.1 as yesterday I tested GPS on latest code with no problem

**Comment by konstantinfpv** [comment]
> This is up to your GNSS receiver and GNSS satellites to obtain valid fix.
> INAV is not target specific in that case and if GPS icon is blue, that means INAV did all it could: port is configured, GNSS receiver configured and INAV is receiving data from the GNSS receiver.
> 
> It's also not a problem of 3.1 as yesterday I tested GPS on latest code with no problem

I'm 100% sure it's not the GNSS, my GNSS setup works in BF, a bit faster in EMUFLIGHT and it works super fast in INAV3.0.1, is there any chance to test 3.0.1 Kakutef4v2 with MPU6000? The problem came out in INAV 3.1.0 only.
