### ISSUE TITLE
More flexibility to outputs designated for motors. (S2 in particular)

### ISSUE THREAD

**Issue by paul-fornage** [iNavFlight/inav#7263]
For lack of a better word, I will be referring to the collection of pads that output signals for servos and motors as 'outputs' 
e.g. S1, S2, S3...

## Current Behavior
Example: Someone has a board with 6 outputs and wants to control 5 servos and 1 motor. They can't. Not because of a hardware limitation, (as far as I can tell, correct me if I'm wrong) but because the target.c file for the board in use dictates that S1 and S2 are for motors. These outputs can still output the same servo PWM as S3-S6, but are heavily restricted in the configurator. Say this person wants to link S2 to the RC roll input, the motor mixer will not allow this because motor mixers need to have a throttle element... By this, I mean you can not set the throttle weight to '0'

## Desired Behavior
The motor outputs are more flexible

## Suggested Solution
I have suggested 3 different solutions of varying difficulty to implement:

1: The outputs each have a switch to toggle between servo and motor. I see how this would require quite a bit of reworking, so not likely to happen. However, this would be the least restricting to the user.

2: The motor outputs can be linked to a logic condition from the programming tab, regardless of whether or not throttle is mixed. This would allow a workaround for users who wish to output an RC input channel on S2.

3: Allow the throttle weight in the motor mixer to be set to 0. This wouldn't allow for any complex mixing, but at least people can partially get around the problem.

## Who does this impact? Who is this for?
This is for people who build; single motor planes, boats, cars, and especially tanks. For example, people following [this tutorial by Pawel](https://www.youtube.com/watch?v=9194OzsHOFc) will not lose the ability to use S1 and S2. Suggested solutions 2 and 3 would only affect those looking to use S2 with a servo, while suggested solution 1 could affect people who never encountered this limitation.
Some flight controllers only have one motor output, and will not be as affected by this limitation.

## Additional context
Not super important, but I have spent about 8 straight hours trying to learn how to compile the iNav code so that I could change the word 'MOTOR' to 'SERVO' on my board. I think that for a firmware as open and multipurpose as iNav, I should not have to go through all these hoops to just output RC roll input on S2.

**Comment by DzikuVx** [comment]
@paulwrath1223 what you propose is impossible since it indeed is a hardware limitation of the SMT32 MCUs. Not every pin can be assigned to every function. On top of that, if two pins (S1-S2) are assigned to the same timer (and in case of S1-S2 they almost always are), it's impossible to mix servo and motor output on them.

https://www.youtube.com/watch?v=v4R-pnO4srU
