### ISSUE TITLE
Unable to calibrate Matek F405-Wing accelerometer

### ISSUE THREAD

**Issue by Alhazred81** [iNavFlight/inav#7317]
Hello Together,

After flashing matekf405se 3.0.1 firmware on my Matek F405 Wing I tried to calibrate the acceleration sensor, but even after several tries the upside down position stayed uncalibrated. After re-flashing to 3.0.0 the calibration went without any issues.

Regards,
Balázs

**Comment by JulioCesarMatias** [comment]
did you use "Full Chip Erase" at the time of the update?

**Comment by Alhazred81** [comment]
Yes, that's my standard way :) surprisingly, after the third reflash it does now, so sorry for the inconvenience and please disregard the topic.
