### ISSUE TITLE
Failsafe RTH disarming UAV when no GPS fix

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#732]
Steps to reproduce:
 1. Set failsafe procedure to RTH
 2. ARM
 3. Trigger failsafe in GPS-denied area

Effect:
UAV disarms and falls out of the sky.

Scheduling for 1.3 as this is a critical safety issue.

**Comment by digitalentity** [comment]
Invalid issue, bad test case.

**Comment by mooiweertje** [comment]
I have had a few failsafes resulting in a disarm but I think it is not related to GPS.
I lost a €300 wing today because of this.
