### ISSUE TITLE
Matek H743 SD card reader not working for blackbox logging

### ISSUE THREAD

**Issue by ccdevisser79** [iNavFlight/inav#7320]
## Current Behavior
The onboard SD card reader on the Matek H743 Slim can not be used in INAV Firmware version 3.0.1 to log blackbox data; the SD card is not discovered.

## Steps to Reproduce
1. Flash INAV 3.0.1 firmware on Matek H743 (Slim). 
2. Use preset for 5inch quadrotor (overpowered).
3. Insert micro SD card in onboard cardreader (32 GB, class 10), check that card is oriented correctly in tiny slot.
4. Open INAV configurator, connect to FC through com port, everything works fine, including digital air data probe (Matek ASPD 4525), great!
5. Go to Blackbox Tab: only "Serial Port" is available as "Blackbox logging device" in the drop down menu, the SD card is not discovered.
6. Flight data is not logged on the onboard SD card after arming the quad.

## Expected behavior
1. With the SD card inserted the option to log data to the onboard SD card should be available in the dropdown menu in the Blackbox tab in INAV configurator.
2. Logging to the onboard SD card should work for the Matek H743 (Slim).

## Suggested solution(s)
1. Add SD cardreader support in the firmware for the Matek H743 (Slim).

## Additional context
Using INAV configurator 3.0.1

---

#version
# INAV/MATEKH743 3.0.1 Jul  4 2021 / 16:39:44 (cb6726e2)
# GCC-9.3.1 20200408 (release)

- FC Board name and vendor: Matek H743 Slim
- INAV version string: 3.0.1

**Comment by avsaase** [comment]
As mentioned in the release notes, this still needs to be implemented on H7: https://github.com/iNavFlight/inav/issues/6371.
