### ISSUE TITLE
Current version 3.1.0 is not compatible with inav configurator

### ISSUE THREAD

**Issue by Damel91** [iNavFlight/inav#7329]
I tried compiling this version of inav but when I get into inav configurator i get the error that it can't configure it because is 3.1.0 instead of 3.0.1

**Comment by stronnag** [comment]
3.1.0 is the development version, the release version is 3.0.1
If you really want a development configurator, you can either:
* Build your own from source
* Use the archives from http://seyrsnys.myzen.co.uk/inav-configurator-next/

**Comment by derekquad** [comment]
i really need the IFLIGHT_SUCCEX_E_F4 /IFLIGHT_SUCCEX_E_F7 because i already purchase and was hopping to build  the hold position etc. is it possible? coz i dont the target in the inav configurator. but i saw the recommended  FC IFLIGHT_SUCCEX_E_F4

**Comment by fanedi** [comment]
> i really need the IFLIGHT_SUCCEX_E_F4 /IFLIGHT_SUCCEX_E_F7 because i already purchase and was hopping to build the hold position etc. is it possible? coz i dont the target in the inav configurator. but i saw the recommended FC IFLIGHT_SUCCEX_E_F4

flywoo an hglrc have a lot of iNav compliant FC
