### ISSUE TITLE
RTH in GPS-denied environment result in instant emergency landing

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#733]
In a GPS-denied environment activating RTH (either manually or by failsafe) result in instant emergency landing.

It would be better to create two scenarios:

 1. **Manual RTH** - disallow pilot to activate RTH
 2. **Failsafe RTH** - allow the UAV to drift with the wind and maintain only altitude for a certain timeout to allow GPS to recover, then switch to emergency landing.

**Comment by DzikuVx** [comment]
was this not covered some time ago with gps-glitch? Emergency landing was supposed to be triggered only after some time passed. Or this is different case?

**Comment by digitalentity** [comment]
That's a different case. If GPS is lost when RTH is already in progress it will wait for _nav_position_timeout_ seconds. However if GPS is not available when RTH is only being activated - instant emergency landing is triggered.

**Comment by digitalentity** [comment]
Implementation in #745, closing.
