### ISSUE TITLE
Getting right target for iflight succex-e f4 v2.1 and high shaking issue

### ISSUE THREAD

**Issue by Damel91** [iNavFlight/inav#7336]
The problem is that I have an iflight succex-e f4 v2.1 flight controller that was flying smooth with betaflight, then I added gps and a compass. I flashed inav 3.0.0 final but compass and barometer weren't agree to exist together. So I found the issue and it was about the target like this issue here already reported https://github.com/iNavFlight/inav-configurator/issues/1057, with betaflightf4 is not good for it. So I compiled inav 3.0.0 final some time ago and with default pid the drone was shaking a lot, while on betaflight I had higher pid values. Just for the record I always do a full chip erase. So then I compiled this version and downloaded the inav configurator wich is in development state. I faced the same issue, and again, I did a full chip erase. I'm supposing there is something wrong with diff as I heard or something like that. The fact is that I had to put D values to 9 and 10 to not get so much shaking, and set tpa to 30% on betaflight the D values were around 40 so for I divided them by 1,5. Thanks :)

**Comment by Dave4675** [comment]
This were my pid settings on betaflight.
![Schermata da 2021-08-05 00-19-02](https://user-images.githubusercontent.com/22644045/128643960-6a7d9d0e-9f9b-4c74-867b-22d9328fe691.png)

**Comment by Dave4675** [comment]
This is the target that works with this board, I don'have understood yet how to set filters correctly before building the firmware version. This target itself is a copy of BETAFLIGHTF4 with i2c issue solved.
