### ISSUE TITLE
unexpected loss of control INAV 2.61

### ISSUE THREAD

**Issue by capblack** [iNavFlight/inav#7337]
Hello, I have had an unexpected loss of control three times.
The last one I had a card incorporated in the blackbox, but the data is confusing for me, and from what I can understand the readings of rcData and rcCommand are incongruous, so it would seem rcData entered fail safe inside the receiver leaving the joystics in the center and engine low at 1010us
therefore the quad should have fallen, but instead rcCommand raises the engine to 70% and begins to climb aggressively
after this I partially regained control, but the response was still partial and with a lot of lag
after turning off and reconnecting the battery, everything seems normal
[LOG00006.TXT](https://github.com/iNavFlight/inav/files/6951473/LOG00006.TXT)

https://www.youtube.com/watch?v=iWu_CB-ViNo

Full video , https://drive.google.com/file/d/1sTjxjN1sYoqxvkST2hA82IOEQkMS6hTJ/view?usp=sharing

Although the quad was a few meters away, I can think that it was an interference from the Dji video air unit but the reaction of the quad cannot be explained
I would like to understand what happened, thank you very much

https://pastebin.com/kbb4gfgy

# version
# INAV/KAKUTEF7 2.6.1 Feb 25 2021 / 10:28:17 (64249b1a)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

Tx Futaba T8FG 
Rx Corona R820FA
video DJI FPV AIR UNIT

**Comment by DzikuVx** [comment]
There are no failsafe events logged. The low throttle you mention happened dring RTH so it was ignored. Check reciver failsafe configuration and radio mixes and switches
