### ISSUE TITLE
new target for HOBBYWING-XROTORF7CONV

### ISSUE THREAD

**Issue by maxgame91** [iNavFlight/inav#7343]
## Desired Behavior
Is it possible to have a target for INAV for the Hobbywing F7 FC (name of the target in the title.
Can't find it in the confgurator

## Suggested solution(s)
An Inav target for this FC

## Additional context
dump : https://pastebin.com/TX20dVsz

- FC Board name and vendor: Hobbywing F7
- https://www.hobbywing.com/goods.php?id=681

**Comment by ikherty** [comment]
it's actual for me and my friend too

**Comment by ikherty** [comment]
[XROTORF7CONV_3.0.1_4.0.0.zip](https://github.com/iNavFlight/inav/files/7774637/XROTORF7CONV_3.0.1_4.0.0.zip)

**Comment by AlejandroBaltazar** [comment]
@ikherty hi, by any chance do you have a more recent iNav HEX for the XRotor? The ZIP here has 3.0.1/4.0.0 only. If there’s an updated build or target/env name to compile myself, a link would help. Thanks!

**Comment by ikherty** [comment]
> [@ikherty](https://github.com/ikherty) hi, by any chance do you have a more recent iNav HEX for the XRotor? The ZIP here has 3.0.1/4.0.0 only. If there’s an updated build or target/env name to compile myself, a link would help. Thanks!

 No, I don’t fly iNav anymore

**Comment by kayraaytug** [comment]
Check https://github.com/kayraaytug/HOBBYWING_XROTORF7CON-INAV
