### ISSUE TITLE
AHI not working in the latest `master`

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#7348]
AHI is not showing up in the latest master with latest fonts from INAV Configurator.
I have a feeling that this is connected with https://github.com/iNavFlight/inav/pull/7255 and https://github.com/iNavFlight/inav-configurator/pull/1322

@MrD-RC could you do a sanity check if latest version display AHI? I'm time limited ATM

**Comment by avsaase** [comment]
Works just find for me.

**Comment by MrD-RC** [comment]
Works fine for me.

Downloaded master firmware and configurator, flashed with full chip erase, calibrated accelerometer, enabled AHI in OSD and uploaded default font.

https://youtu.be/RTaKKh_j-w4
