### ISSUE TITLE
Fully Ghost Telemetry to support Lua Telemetry

### ISSUE THREAD

**Issue by Louis-Land** [iNavFlight/inav#7358]
Currently, Ghost transmitters on ghst protocol have the more basic telemetry enabled. It is not enough to match what is support with Crossfire or FrSky transmitters. 

Currently missing: cell voltage, roll, pitch yaw,... This means a person cannot use the https://github.com/teckel12/LuaTelemetry script because all telemetry is not there on the transmitter.

## Desired Behavior
Have ghst protocol have the same level of telemetry support as Crossfire and FrSky to support https://github.com/teckel12/LuaTelemetry lau scripts

**Comment by DzikuVx** [comment]
This is not inav issue but Ghost issue. It offer only those telemetry sensors, nothing more
