### ISSUE TITLE
Burst of throttle when switching to POSHOLD or ALTHOLD from ANGLE mode

### ISSUE THREAD

**Issue by samtkeen** [iNavFlight/inav#7360]
happened on two different but similar slight controllers (Matek f722 STD and PX) but when switching from angle mode to either GPS mode the motors burst in throttle (worse when at non-zero throttle). issue is made worse by increase in hover throttle setting, attached are two blackbox logs (props off but same behaviour occurs with them on) one log with 1000 hover throttle and one with 1300 hover thottle. in second log zero throttle and slightly raised throttle both recorded. 
[blackbox_log_2021-08-19_195817.zip](https://github.com/iNavFlight/inav/files/7017237/blackbox_log_2021-08-19_195817.zip)

**Comment by DiscoMan18** [comment]
Check your build for vibrations, make sure that your FC is soft-mounted to the frame (using silicon or rubber spacers/nuts that come with your FC/ESCs). Generally this behaviour cause by excessive vibrations. Soft mounting your FC is required.
