### ISSUE TITLE
Spline Curve to WayPoint navigation

### ISSUE THREAD

**Issue by JulioCesarMatias** [iNavFlight/inav#7418]
I don't know if anyone has thought about it to implement in iNav, but in the last few days I've been thinking about it. Adding Spline Curve mode to iNav would be nice, but I don't know if this is the right time for it. I have a sketch of the algorithm I got from ArduPilot, which is at the link below. Spline Curve mode is to make the UAV curves in wapypoint mode instead of straight lines, example in the images below. And I was also thinking that there should be a command in the CLI for the user to choose whether he wants Spline Curve mode active in waypoint mode or not.

https://github.com/JulioCesarMatias/WayPointSlipeCurve

![images](https://user-images.githubusercontent.com/25625982/132026311-f1c2be07-2a99-481c-8944-89b262592a5a.png)

![images](https://user-images.githubusercontent.com/25625982/132026306-5ec54fd8-2cce-4dba-a4f7-73bd73573647.jpg)

**Comment by larrykabo** [comment]
needs to be an option

**Comment by JulioCesarMatias** [comment]
> needs to be an option


it takes dedication to implement it in iNav and free time to test. And at the moment I don't have either
