### ISSUE TITLE
OSD to big

### ISSUE THREAD

**Issue by Migges2k** [iNavFlight/inav#7420]
Hey,
I have a problem with my OSD.
that OSD is is too big. How do I get it set correctly?
The cam and inav are each set to PAL.

I don't know my way around very well because I'm new. And find nothing in the forum.
Picture attached

Hardware:
Cam: Foxeer T-Rex
FC: F765
TX5258 

![osd](https://user-images.githubusercontent.com/45370597/132119089-bd00c516-29d4-4161-878d-a983616e1890.jpg)

**Comment by DzikuVx** [comment]
Move elements so they all fit into physical screen.
