### ISSUE TITLE
MSP UART not communicating on boot up 3.0.1

### ISSUE THREAD

**Issue by flyingbandit** [iNavFlight/inav#7429]
Using an ESP Lora radar module on an MSP enabled UART. 

On first power up with USB or battery, the ESP32 does not detect the FC. Pressing the reset on the ESP fixes the connection.

The issue exists in 3.0.1, but 2.6.1 works as expected.

Steps to Reproduce

1. Connect ESP32 to spare UART with MSP enabled
2. Power on the FC
3. Note 'NO FC' displayed on ESP OLED
4. Restart - Connection works
5. Downgrade to 2.6.1, the problem is not occurring, upgrade to 3.0.1, problem resumes.

Expected behaviour
No reset required after power on to connect ESP

# version
# INAV/MATEKF405SE 3.0.1 Jul  4 2021 / 14:17:22 (753c4479)
# GCC-9.3.1 20200408 (release)

**Comment by DzikuVx** [comment]
Please open this issue on ESP32 Radar project
