### ISSUE TITLE
Emax Tinhawk V1 Won't Bind

### ISSUE THREAD

**Issue by filo-hulk** [iNavFlight/inav#7438]
I bought a used emax tinyhawk v1 and it's bind button was broken off so I tried to do it in betaflight using CLI but it wouldn't work, I also found out that its FC version was very old so I flashed it to its latest. After flashing, every time I plugged it in either battery or to computer, it stayed solid red no other color, so I read the manual and it said to put the CLI dump file so I did and I got back others this times its solid blue and rapid flashing red. What does it mean and how to bind with my Radiomaster tx12. In my ports tab I have the serial rx for the second line switched on, I don't know if this means anything. Also in my Config tab the receiver mode used to be serial based receiver but I changed to SPI RX so I could put in the bind command and for my SPI Bus Receiver Provider I put to Frsky D. What colors am I looking for to and how do I know that it's binded?
![Screenshot (1949)](https://user-images.githubusercontent.com/90658923/133171208-b251aedd-feb5-4d62-a78e-9b71c14495b0.png)
![Screenshot (1950)](https://user-images.githubusercontent.com/90658923/133171212-ffdb5526-9b31-40ff-90a0-2de9612a87ad.png)
![Screenshot (1952)](https://user-images.githubusercontent.com/90658923/133171213-bbdcb67a-f571-4e2d-8342-6c7ac87412d7.png)
![Screenshot (1953)](https://user-images.githubusercontent.com/90658923/133171214-9ec0c418-211d-4ab8-9885-97b4af79f987.png)
![241760769_1049190659168542_4991973643069073164_n](https://user-images.githubusercontent.com/90658923/133171228-15aed25f-9261-4853-b162-e2bb678de4ad.jpg)

https://user-images.githubusercontent.com/90658923/133171232-bd1eed6a-0495-4724-a541-8f2de649548c.mp4

**Comment by avsaase** [comment]
You need to consult the Betaflight support channels.
