### ISSUE TITLE
Request of SpeedyBee F7V2 Wifi BLE chip disable during ARM 

### ISSUE THREAD

**Issue by abimaputra78** [iNavFlight/inav#7449]
@DzikuVx

Dear Pawel, 
Please kindly help for SpeedyBeeF7V2 board there was an internal wifi/ble chip. Can it be turned off during arm? To avoid 2.4Ghz interference. I requested this since in Inav no remap resources and pinio setup. 🙏  This is true PA15 control those enable like in Betaflight but I didn't see any correlation with arm flag. Not sure about this. 

Could u pls help. Thanks and appreciate this.

![Screenshot_20210916-133126](https://user-images.githubusercontent.com/49124286/133564281-49b6308a-cfb6-4593-bf13-1ba2774b433a.png)

Thanks so much
Ditto

**Comment by martink1974** [comment]
is this fixed is 3.0.2 ? this would explain failsafes i have had at medium  range on 3.0.1

**Comment by martink1974** [comment]
no its not fixed this still affects range of 2.4g links

**Comment by abimaputra78** [comment]
Yes. In 3.0.2 no pinio destination for turn it off. Pin A15

**Comment by mrechte** [comment]
I confirm, ARMING does not disable Bluetooth module with iNAV 4.1.0.

Speedybee support says this should work out of the box with iNAV...

For BF they give some instructions on the CLI to make it work: https://speedybee.zendesk.com/hc/en-us/articles/5390784259099-Will-flashing-custom-firmware-for-SpeedyBee-F7-V2-flight-controller-affect-Bluetooth-and-WIFI-functions-

Does iNAV provides some equivalent commands ?

```
# resource
IO:
----------------------
...
A15: PINIO1 OUT
...

# get pinio_box
pinio_box1 = 47
Allowed range: 0 - 255

pinio_box2 = 255
Allowed range: 0 - 255

pinio_box3 = 255
Allowed range: 0 - 255

pinio_box4 = 255
Allowed range: 0 - 255
```

**Comment by mrechte** [comment]
Could somebody kindly give directions in source code, where to customize target in order to change PÏNIO1 level when arming/disarming ?
Thanks

**Comment by mrechte** [comment]
In Speedybee target.h, one can find:
   ` #define USE_PINIOBOX`

In main/fc/fc_core.c:processRX(), one can find:
```
#ifdef USE_PINIOBOX
    pinioBoxUpdate();
#endif
```

In main/io/piniobox.c:pinioBoxUpdate(), one can see a loop on the 4 pins (PINIO_COUNT):
    `pinioSet(i, IS_RC_MODE_ACTIVE(pinioBoxRuntimeConfig.boxId[i]));`

In main/fc/rc_modes.c, one can see:
```
bool IS_RC_MODE_ACTIVE(boxId_e boxId)
{
    return bitArrayGet(rcModeActivationMask.bits, boxId);
}
```


In main/io/piniobox.h, one can see
`#define BOX_PERMANENT_ID_USER1      47`

So I would assume that PINIO1_PIN is assigned to BOXUSER1 flight mode (defined in rc_modes.h) ?

In inav Mode config, I tried to assign USER1 to the same channel then ARM, expecting that it would drive PINIO1. Unfortunately it does not work.
