### ISSUE TITLE
My First Build X Class iFlight 880mm 13 inches Prop

### ISSUE THREAD

**Issue by mgphonexxxx** [iNavFlight/inav#7452]
Hey Gyus i build X Class iFlight 880mm Size quadcopter . everything is ok but at angle flight mode my quad wobble and climb down .

i used 
iFlight Twin D F722 FC
Xing 400kv and MAS 13 inches Prop

I think this issue because Gyro And PID . i tune PID but still wobbles . Pls Help us guys Here is my PID Setting

![image](https://user-images.githubusercontent.com/90264633/133640035-26fc2b0e-6386-4720-876e-591b1924d912.jpeg)

**Comment by Vissie26** [comment]
Can you post your CLI dump file so i can check some settings for you. I have built a large (690mm) size quadcopter in the past running inav.

**Comment by mgphonexxxx** [comment]
Ok
