### ISSUE TITLE
DJI Speed Selection not working for OSD

### ISSUE THREAD

**Issue by AlexandruIspas89** [iNavFlight/inav#7482]
## Current Behavior
Cannot set the dji_speed_source via CLI in order to use the Analog Airspeed Sensor ASPD-7002 with Matek F411-WSE on a ZOHD drift with CADDX VISTA

## Steps to Reproduce
Try to set the  dji_speed_source in the CLI of any release of INAV 3.0.1. 

 get dji_speed_source
ERROR: Invalid name

## Expected behavior
I want to be able to select the source of airspeed indication. In this case I want to use IAS as this model is very speed dependent. 

## Additional context
CLI dump here:
https://pastebin.com/VvJxV8WT

version
INAV/MATEKF411SE_FD_SFTSRL1 3.0.1 Jul  4 2021 / 14:23:42 (753c4479)
GCC-9.3.1 20200408 (release)

**Comment by stronnag** [comment]
```
Entering CLI Mode, type 'exit' to return, or 'help'

# get dji
```
...
```
dji_message_speed_source = 3D
Allowed values: GROUND, 3D, AIR
```
