### ISSUE TITLE
Succex Force vtx cant get 800mw by osd.

### ISSUE THREAD

**Issue by LilTeo14** [iNavFlight/inav#7489]
## Current Behavior
The vtx is a succex Force vtx with trump protocol.

![image](https://user-images.githubusercontent.com/44703219/135628485-48553214-4698-4316-933e-ecdece0cdff2.png)
When i select power 1, i get 1 blink in the vtx, when i select power 2 i get 2 bink, when i select power 3 i get 2 blink too, when i select power 4 i get 3 blink, and i cant get the 4 blink on the vtx(800mw).

I also tried set power to 5 by programming but didnt work.

Also in osd i get 25-100-200-400 in osd when it should be 25-100-400-800

https://user-images.githubusercontent.com/44703219/135630588-1bba0558-427c-4c9d-bbe2-d8920b9ae3d1.mp4

---
- FC Board name and vendor:
Wing FC-10

- INAV version string:
INAV/FF_F35_LIGHTNING 3.0.1 Jul  4 2021 / 13:33:27 (753c4479)
GCC-9.3.1 20200408 (release)

-Dump:
https://pastebin.com/BxYjY9gh

**Comment by MartinWa** [comment]
I have the same problem. Is there a known solution?

**Comment by AJAY-GANI** [comment]
I too have same problem pls give me a solution

**Comment by yo8ssv** [comment]
I have almost same issue. Inav 6.1 i can change band and channet but note the power. In 5.0 i could change the power to 400 mW
