### ISSUE TITLE
Remap servos or motors 

### ISSUE THREAD

**Issue by jag3957** [iNavFlight/inav#7503]
With betaflight and SucceX-D F7 V2.2 TwinG Flight Controller is possible change motor out to servo out. the links are here to check and if possible add this feature to INAV.

I want to add camera tilt servo using motor out M5 in this FC with betaflight is possible with remap source with INAV I understand I have to compile my own firmware, that is really complex for me and mean every time INAV get updated I must compile again.

so if anybody can add this feature to INAV or make a video or something explaining how to make it easy I will really appreciate.

adding a camera servo tilt using motor out: https://youtu.be/CQw8diCkup8

<img width="747" alt="Screen Shot 2021-10-09 at 23 39 33" src="https://user-images.githubusercontent.com/85746687/136680907-c15a2e77-24b3-4b57-a83d-28c05779b328.png">

**Comment by SuiX187** [comment]
Hello,
similar Problem here.
i only have 2 UART´s at jhemcu play f4 (1x CRSF; 1x GPS) but i use SmartAudio via IRC Tramp on LED Pin.
in BF i easy can remap the source but i always read "No resource remapping in INAV"
At this point i cant use Inav for my projekt (BF has not enought GPS Features)
