### ISSUE TITLE
Skystars F7 HD FC

### ISSUE THREAD

**Issue by JackGisto** [iNavFlight/inav#7511]
## Desired Behavior

i and few people of my team would like to ask you if it's possible to share Skystars F7 HD Target of Inav

**Comment by MrD-RC** [comment]
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by invisiblethings2** [comment]
You can test this [SKYSTARSF7HD inav target](http://forum.rcdesign.ru/f123/thread443443-350.html#post8158183). My drone flies on it.

**Comment by assasinfil** [comment]
@invisiblethings2 i compiled latest firmware and i see one bug, icons in companion is not active. But arming ok.
