### ISSUE TITLE
Mamba F4 (Fury f4 OSD)

### ISSUE THREAD

**Issue by YngwieXXX** [iNavFlight/inav#7517]
Hello, I try to make a flying wing with inav and the mamba FC.
It have a some problems:
-Cant use SBUS (only works with old firmware 2.1 and need to use an old inav configurator)
-Servos doesn't woks (I put servos in signal 3 and 4 and it's impossible to get move)
Anyone have same issues?
Regards

**Comment by MrD-RC** [comment]
It sounds like you're trying to use the old build that was posed on #4262 years ago? Why not just use the latest configurator and the MAMBAF405 target? From reading the post, that is the official version of the target you are trying to use, which older versions did have SBUS issues.

https://github.com/iNavFlight/inav-configurator/releases
