### ISSUE TITLE
Support Sonar on SP Racing F3 EVO

### ISSUE THREAD

**Issue by kitchung** [iNavFlight/inav#753]
CleanFlight 1.14.0, released yesterday enabled Sonar support for the SP Racing F3 EVO. Please consider adding support in iNav. Please see https://github.com/cleanflight/cleanflight/commit/6b03f97c522442b27b3c480ab79a2d85ded85366

**Comment by DzikuVx** [comment]
@kitchung do you own EVO and are you willing to test it?

**Comment by kitchung** [comment]
Yes, I am building a new quad with an EVO board now with all necessary parts (board, HC-SR04 sonar module, 1k resistors). Initial testing will be bench testing.

**Comment by martinbudden** [comment]
Closing. Addressed by PR https://github.com/iNavFlight/inav/pull/759

**Comment by kitchung** [comment]
FYI bench test of sonar on SP F3 EVO with Clean flight 1.14 was successful. I'll test iNav as soon as binaries are available.

**Comment by martinbudden** [comment]
Great, thanks for testing.

**Comment by kitchung** [comment]
Well, that was for CleanFlight 1.14; will test iNav as soon as binaries are available.

**Comment by oleost** [comment]
@kitchung You could setup your own build eviroment, tbh its really quick and it was you that requested this.

Anyway, here is latest developement hex for evo. use with caution. https://drive.google.com/open?id=0B-yHzNtOXxbEM0hYcnhUUzBPOFU

**Comment by kitchung** [comment]
@oleost  Thanks for the binaries. Bench testing was successful!

**Comment by neKraehe** [comment]
@martinbudden @kitchung  Hello! I would like to test out Sonar on the SP F3 EVO aswell, what are the pins that I need to use and will I need the 1k resistors with them? What are the needed settings in the gui for that? Thanks in forward!

**Comment by DzikuVx** [comment]
@neKraehe Sonar support is disabled in INAV 1.6 on all targets
