### ISSUE TITLE
Implementation of a record display in the DJI OSD

### ISSUE THREAD

**Issue by Ninjamic** [iNavFlight/inav#7537]
Hello, I have a question about the feasibility to use the Caddx Peanut camera better via inav....

The Caddx Peanut can be controlled perfectly via inav, I use the vtx port on my matek 722 se fc and switch it via the user1.

if the vtx port briefly 5v is output, the recording of the Peanut starts or stops. 

A momentary disadvantage is that I no status stands during the flight and I can therefore easily forget whether the Peanut is recording or not....

Would it be possible to project a status into the OSD for this application so that this is visible via the DJI OSD?

Possibly it is also possible to use the "Pilot Name" here and display "Recording" or similar......

An idea would be to use the value of the vario for this to simply see an R for Record or similar....?!

Would be great if you can implement a solution, thanks and greetings

Michael

**Comment by erstec** [comment]
@Ninjamic how FC knows if Recording are started/stopped? There is one-way signalling, like pressing button. Afterall you should look at camera led to decide if it recording or not.
