### ISSUE TITLE
Would be nice if a LAND waypoint would actually land a Fixed Wing

### ISSUE THREAD

**Issue by tonycake** [iNavFlight/inav#7543]
For controlled landings at the end of a fixed-wing waypoint mission it would be nice if a waypoint tagged as 'Land' actually terminated the flight. 

Currently, at this point, the fixed wing model just heads to the skies again (which gets tricky if the landing was carefully planned in a tight space). 

Would it make sense to immediately disarm, or otherwise disable the motor at the land waypoint?

![image](https://user-images.githubusercontent.com/10763856/139025660-728b353b-b7e9-41c9-b22a-6a24b802dcf1.png)

**Comment by wx4cb** [comment]
landing in inav for a fixed wing is more of a controlled crash than anything else. it would be nice to be able to do this, however one thing i can see is that you would need to make sure that the direction the aircraft is flying in would be the one you are landing in. also i would suggest putting your landing waypoint away from where you want the actual landing to "touch the ground" as obviously it doesn't go straight down like it would on a multi rotor (if that makes sense)

**Comment by tonycake** [comment]
Makes sense, but surely for a fixed wing, the LDG should at minimum cut the throttle? That green bar to the left of the image above is a row of trees, the green area is a rather steep slope, I expected the altitude to not be perfect, and for the model to touch down at some point between WP15 and WP17, what I didn't expect is that at the LDG waypoint, it would apply full power and fly directly into the trees...

**Comment by StuweFPV** [comment]
I don't really autoland my planes and if then i use the PitLab system. That's the only one i know that really works. but it's fare more complicated than you think. you have to exactly define your runway and glideangle. AoA of the plane etc. your request goes kinda into the direction of #7629 but i think inav is far away from a proper autolanding for a wing.
As of your disarm question you could set nav_disarm_on_landing = ON that should take care of that issue.

**Comment by b14ckyy** [comment]
Done https://github.com/iNavFlight/inav/pull/9713
