### ISSUE TITLE
i have a rush blade f7 its on the targets list in code but not in code

### ISSUE THREAD

**Issue by chirag-43** [iNavFlight/inav#7554]

**Comment by chirag-43** [comment]
i tried making a custom traget but failed miserably and don't want to burn my fc if anyone has a hex file for it would be great

**Comment by DzikuVx** [comment]
Process of building INAv is described here https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20or%2011%20with%20Linux%20Subsystem.md
