### ISSUE TITLE
If no barometer then modes depends on it should not be listed

### ISSUE THREAD

**Issue by mrnams** [iNavFlight/inav#7557]
## Steps to Reproduce

1. Connect FC to iNav Configurator which don't have barometer sensor or disable barometer from Configuration
2. Go to Modes in iNav Configurator
3. We will see Modes like NAV RTH,NAV POSHOLD, MAV WP etc which requires barometer

## Expected behavior

If mandatory hardware for mode is missing then those Modes should not be listed.
OR
Have option to Hide Modes whose mandatory hardware is missing
## Suggested solution(s)

Un-list Modes which are depend on some hardware and that hardware is missing.

## Additional context

---

# version
# INAV/MATEKH743 3.0.2 Sep 15 2021 / 10:30:36 (66011184)
# GCC-9.3.1 20200408 (release)
![image](https://user-images.githubusercontent.com/31761152/139795925-a9ce80e9-9ab6-4b13-930d-57e1136e37cd.png)
![image](https://user-images.githubusercontent.com/31761152/139796183-85d82edb-9a2b-4ed1-b634-2712c2958c1e.png)

**Comment by jeffhendrix** [comment]
Shouldn't this be an inav configurator request?

**Comment by MrD-RC** [comment]
No, the firmware tells the configurator which boxmodes to display. So if the hardware is disabled, its down to the firmware not to send the modes over.

**Comment by erstec** [comment]
@jeffhendrix
Currently all mentioned modes are active when it is Multirotor, have Compass, have Accelerometer and GPS.
Or if it is not Multirotor and have ACC and GPS.

There is no relations between them and BARO at all, except for NAV ALT HOLD and SURFACE.

Does anybody can confirm if mentioned modes should be really dependant on BARO? I don't see this relation from 'navigation' sources.
Then I will put PR to RC then.

**Comment by erstec** [comment]
@jeffhendrix @MrD-RC 
According https://github.com/iNavFlight/inav/blob/master/docs/Navigation.md all those modes are non stricted to BARO and use it if present.

I think this issue can be closed.
