### ISSUE TITLE
Caddx Peanut start/stop record function on a UART

### ISSUE THREAD

**Issue by rc-charlie** [iNavFlight/inav#7558]
## Current Behavior
The Caddx Peanut camera has been marketed "for FPV" as having a feature where you can start and stop recording via a UART TX pin. However, the only documentation describing how to go about this is for Betaflight (please see attached photo). Unfortunately (although I accept the reasons why... having seen Pavel's video on the subject) resource mapping is unavailable in iNav, so it is not currently possible to easily assign a UART TX pin for controlling the Caddx Peanut.

## Desired Behavior
The ability to select "Caddx Peanut" in the peripherals drop down menu on a UART in the Ports tab within iNav

Upon save and reboot, an extra mode will appear in the modes tab (similar what happens when RunCam Device is selected) 

User can now assign an RC channel to that mode to control the Caddx Peanut start/stop record function

## Suggested Solution
According to the instructions for Betaflight, they are able to use RESOURCE to switch off serial function of a UART TX pin, and reassign it with PINIO function at an interval of 40,255,255,255 

This is not possible for users of iNav, therefore request it be built into future versions as described above, as already there are peripheral choices for RunCam Device, 

## Who does this impact? Who is this for?

This would greatly benefit all iNav users who wish to purchase the relatively new to market Caddx Peanut action camera. It is a relatively inexpensive camera compared to the GoPro series of cameras, it's very lightweight so good for sub250g builds and quads. I predict that many iNav users may wish to purchase this camera for their projects, but currently aren't able to take full advantage of it's remote start/stop feature.

![20211102_213318](https://user-images.githubusercontent.com/88059809/139961277-8c489b2f-688e-4435-a399-283316929d07.jpg)

**Comment by donne1226** [comment]
I want this feature too

**Comment by brousselle** [comment]
I have tried to enable pinio for my specific target MATEKF405SE as explained here: https://www.youtube.com/watch?v=2zElnakFQRU
It seems to work pretty well.
i left the default pinio_box1 at 47.

**Comment by rc-charlie** [comment]
> I have tried to enable pinio for my specific target MATEKF405SE as explained here: https://www.youtube.com/watch?v=2zElnakFQRU It seems to work pretty well. i left the default pinio_box1 at 47.

Excellent, I'll go take a look.

**Comment by sketch4x4** [comment]
Mine works fine following the instructions provided. One little issue is that you have to toggle the switch once to turn on the camera and then again to record. Which is different to the onboard button, where one press turns on and starts recording. 

Running this on a helio spring board 
resourced ledstrip to the pinio 1 (tx1 pad is damaged and I have no other uarts free), I used the same 40,255,255,255 provided in the manual.

**Comment by AdamGFPV** [comment]
I'd love to have this feature, without the need to use the suggested workaround.

**Comment by rc-charlie** [comment]
> Mine works fine following the instructions provided. One little issue is that you have to toggle the switch once to turn on the camera and then again to record. Which is different to the onboard button, where one press turns on and starts recording.
> 
> Running this on a helio spring board resourced ledstrip to the pinio 1 (tx1 pad is damaged and I have no other uarts free), I used the same 40,255,255,255 provided in the manual.

You don't understand what is being asked here. Those instructions are just for betaflight firmware. this is an INAV git feature request, as resource mapping is not possible on INAV firmware

**Comment by b14ckyy** [comment]
Implemented with https://github.com/iNavFlight/inav/pull/5993 on Flight controllers that support it.
