### ISSUE TITLE
No Dshot Support?

### ISSUE THREAD

**Issue by BryanFPV** [iNavFlight/inav#7582]
Hello! I can not set DSHOT on inav 3.0.2 (Configurator v3.0.2). Inav resets DSHOT to standard pwm protocol after "save and reboot". Am I missing something? I have DALRC F405 AIO and Flycolor Raptor 30A with BLS. On earlier versions of inav I had the same issue. Setting DSHOT in betaflight works fine.

**Comment by stronnag** [comment]
As documented on the [wiki](https://github.com/iNavFlight/inav/wiki/Boards,-Targets-and-PWM-allocations#board-dalrcf405).

Unless someone who owns the board offers a DSHOT PR for thr board, this will remain the case.
