### ISSUE TITLE
Freezing when Current Limit activates and flashes OSD throttle_pos

### ISSUE THREAD

**Issue by freddybloggs** [iNavFlight/inav#7593]
## Current Behavior
FC often freezes and drops out o the sky when power limit activates, it has something to do with osdFormatThrottlePosition I have stopped it happening by adding the "1" here, I am not sure if it's because I also have the OSD_POWER on the screen and this is flashing, this has been happening since the power limit was introduced I was blaming my F4 FC for a while until I changed it yesterday for a Matek F722SE

static void osdFormatThrottlePosition(char *buff, bool autoThr, textAttributes_t *elemAttr)
...........
#ifdef USE_POWER_LIMITS1
    if (powerLimiterIsLimiting()) {
        TEXT_ATTRIBUTES_ADD_BLINK(*elemAttr);
    }
#endif
 

## Steps to Reproduce

1. turn on OSD_THROTTLE_POS_AUTO_THR and OSD_THROTTLE_POS and OSD_POWER
2. set current limit to say 2500 draw 26 amps
3. the motors will stop the osd will freeze and the craft will drop out of the sky
4. 

## Expected behavior
to keep flying and not to draw too much current from 4s2p 18650 batteries

## Suggested solution(s)
I am not sure how to fix this problem, I turned off the flashing in OSD_THROTTLE_POS

## Additional context

---
# version
when power limits were introduced up until Nov 8 version 4.0.0

- FC Board name and vendor:
- INAV version string:
# INAV/MATEKF722SE  4.0.0 Nov 8 2021 / 13:16:57 (ac9d91bd)
# GCC-10.2.1 20201103 (release)
# version
# INAV/OMNIBUSF4PRO 4.0.0 Sep 20 2021 / 01:42:58 (ac9d91bd)
# GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
This will be fixed in the next release candidate
