### ISSUE TITLE
VGOODRCF4

### ISSUE THREAD

**Issue by cryptictuna** [iNavFlight/inav#7595]
Hi guys, i have acquired several VGOODRCF4 based on stm32f405    , there is firmware targets in CLeanflight, with same name as beteflight as well, VGOODRVF4 (STM32F405)    can this be ported over to INAV? it has 6 uarts, and onboard baro as well. would be perfect in Inav..

**Comment by cryptictuna** [comment]
Closed with no resolve or even comments MONTHS LATER. ., .. so awesome

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DzikuVx** [comment]
And how do you expected this works? I buy samples for my own money and develop a target in my spare time? 
Manufacturer is apparently not interested in having this board supported in INAV and nobody else offered to build a target file.
