### ISSUE TITLE
[Feature]add MavLink Code Telemetry to use Tower App  

### ISSUE THREAD

**Issue by Linjieqiang** [iNavFlight/inav#76]
First,Thanks your hard wroking.The Code was very nice.But I suggest quickly add the Mavlink Support so I can use Tower (https://github.com/DroidPlanner/Tower) to control the copter like APM!

**Comment by digitalentity** [comment]
Hi, thanks for your interest in iNav.
Unfortunately telemetry in iNav doesn't provide means to control the copter. It's one-way communication from FC to OSD/Ground.

**Comment by Linjieqiang** [comment]
But why not remove CLI and replace by Mavlink control?

**Comment by digitalentity** [comment]
Removing CLI is a good idea, but replacing it by MavLink is definitely NOT a good idea - we already have MSP, why reinvent the wheel for pushing settings to the FC?

**Comment by digitalentity** [comment]
A Mavlink-MSP proxy might be a solution in your case.

**Comment by Linjieqiang** [comment]
Oh ,I know.Thanks
