### ISSUE TITLE
PosHold with Optical flow not working above 1m height

### ISSUE THREAD

**Issue by andrefreitas97** [iNavFlight/inav#7622]
## Current Behavior
When using PosHold indoors with Matek lidar 3901-L0X (and ALTHOLD with barometer) the quad keeps horizontal position hold only below a certain altitude (~1m). Above that height the opflow sensor seems to lose reference and the quad starts to drift. I already maxed the values of the cli commands nav_max_terrain_follow_alt and inav_max_surface_altitude and the problem still occurs.

## Expected behavior
Since the opflow sensor PMW3901 in the matek board should work between 80 mm and infinity, I expected that position hold should work above the  80 mm height to the max value defined in the cli.

## Suggested solution(s)
I am not sure how this can be solved.

# version
# INAV/KAKUTEF7HDV 4.0.0 Nov 12 2021 / 10:00:08 (a6c7d81c)
# GCC-10.2.1 20201103 (release)

FC Board name and vendor: Kakute F7 HDV

**Comment by DzikuVx** [comment]
Used lidar has a practical range of 1m. Hardware limitation, won't fix

**Comment by andrefreitas97** [comment]
My problem is related to the range of the opflow sensor and not the lidar. What I don´t understand is why the opflow is not capable of keeping horizontal position hold above 1m (**not using surface mode**. only althold with barometer and poshold)

**Comment by avsaase** [comment]
The opflow sensor cannot properly see the ground when the distance is too large.

**Comment by andrefreitas97** [comment]
Thanks for the reply avsaase! I already expected that could be the problem but what I don´t understand is why they advertise that this sensor has a range of 80cm to infinity when it actually "stops working" at about 1m of the ground.

**Comment by DzikuVx** [comment]
No no. The OpFlow sensor has a range up to infinity. But it only return angular translation. To convert that to linear translation distance to tracked surface is required. And this comes from lidar. When you go out of lidar range, opflow data becomes useless

**Comment by andrefreitas97** [comment]
Oh!! Finally someone can perfectly explain the reason behind it! Thank you so much!

**Comment by VanLaser** [comment]
> No no. The OpFlow sensor has a range up to infinity. But it only return angular translation. To convert that to linear translation distance to tracked surface is required. And this comes from lidar. When you go out of lidar range, opflow data becomes useless

I have a related question - is it possible to add another lidar (like TFMini Plus for example), and use it in conjunction with the opflow data from the Matek unit? Basically to achieve what the OP asked. Thanks for all the INAV work BTW!

**Comment by andrefreitas97** [comment]
Yes it works! I did exactly that and know opflow works until the max altitude of the tfmini

**Comment by VanLaser** [comment]
That's great, thanks! :)
