### ISSUE TITLE
Query: IS this going to be in the mainstream branch?

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#7650]
Just noticed in the docs section of the repo that there is a "non addressable light switch" feature documented.

Are there any plans on putting this into the main releases at any point? also, what pin output is required on an FC, I Assume that  for example on the Matek F765WSE board there is an RTS/CTS pin available which would normally only ever be high or low, maybe that can be repurposed ?

https://github.com/iNavFlight/inav/blob/master/docs/Lights.md

**Comment by DzikuVx** [comment]
There are no such plans
