### ISSUE TITLE
SPRacingF3 EVO compass not detected (occasionally)

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#766]
Affected version: 1.3, development

**Comment by digitalentity** [comment]
Once in a while compass IS in fact detected correctly.

**Comment by rb1205** [comment]
I had this issue every now and then in 1.2 when I rebooted the FC without cycling power, then it was apparently gone in 1.2.1. in 1.3 is back and more frequently than in 1.2, happens even at the initial power on.

**Comment by digitalentity** [comment]
Looks like the issue is solved by latest development code.
