### ISSUE TITLE
No pitch & roll control below 1100us throttle in horizon mode / as expected following position hold on off cycle

### ISSUE THREAD

**Issue by dirtbag00** [iNavFlight/inav#7665]
## Current Behavior   FC Matek H743 slim  INAV 4.0.0 RC2
Flight controller seems to have no control of stability under 1100us throttle. The quad will just tip over and fall if you pull low throttle in horizon mode. 
If I switch to position hold then back into horizon mode the quad acts as expected, i.e It falls while maintaining pitch and roll.

## Steps to Reproduce
1. INAV 4.0.0 + Matek H743 slim
2. take off in horizon mode and pull throttle to zero.
2.quad loses control of pitch and roll 
3.
4.

## Expected behavior
Quad should maintain pitch and roll at any throttle while in horizon mode.

## Suggested solution(s)
It works as expected after engaging / disengaging position hold 

# version
# INAV/MATEKH743 4.0.0 Nov 26 2021 / 12:08:23 (f996170e)
# GCC-10.2.1 20201103 (release)

- FC Board name and vendor: Matek H743 slim
- INAV version string: 4.0.0 rc2

**Comment by avsaase** [comment]
In the Configuration tab, enable the "Permanently enable airmode" toggle.

**Comment by dirtbag00** [comment]
yea that's already on.

**Comment by DzikuVx** [comment]
Airmode kicks in permanently only after Throttle crosses 1300us value. Just take off with more oomph of lower the `airmode_throttle_threshold` in CLI

**Comment by dirtbag00** [comment]
Hey Pawel, thanks man! was struggling with that. Much appreciated
