### ISSUE TITLE
VCP not stable on F4 boards

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#767]
Encountered on Pixracer target (#466) rebased on development (a3b81e36e2dcc78ddc74877852d093c4c795e34a).

VCP connection to Configurator freezes after a while. Board CPU is very busy in `VCP_Ctrl` and `usbVcpFlush`. F1 (CC3D) and F3 (EVO) targets don't seem to be affected.

Can anybody confirm the issue on their F4 boards?

**Comment by digitalentity** [comment]
Interestingly, issue is resolved with disabling LTO. Another instance of (in)famous memory corruption bug?

**Comment by DzikuVx** [comment]
tested with Flip32 F4, no problems

**Comment by jflyper** [comment]
> Interestingly, issue is resolved with disabling LTO. Another instance of (in)famous memory corruption bug?

In betaflight, I've experienced the opposite case; disabling LTO wedges F3 and F4 targets upon entering CLI: betaflight/betaflight#1454.

**Comment by digitalentity** [comment]
I'll keep it open, but low priority
