### ISSUE TITLE
DPS310 baro misidentified as SPL06 - iNav 4.0

### ISSUE THREAD

**Issue by dingrgh** [iNavFlight/inav#7671]
## Current Behavior

The DPS310 baro incorrectly identified as an SPL06.

## Steps to Reproduce
1. In the Configuration, set Baro to AUTO.
2. Save and Reboot.
3. Baro shows as 'SPL06' instead of 'DPS310'.

## Expected behavior
The baro in the Matek F722-WPX should have been auto-detected as a DPS310.

## Suggested solution(s)
Code should correctly differentiate between DPS310 and SPL06.

## Additional context
Baro correctly identified as DPS310 in iNav 3.x.
As a workaround, baro can be set to DPS310.

---

- FC Board name and vendor: Matek F722-WPX
- INAV version string:  INAV/MATEKF722WPX 4.0.0 Dec 15 2021 / 15:09:49 (c20a9852)

**Comment by MrD-RC** [comment]
DPS310 and SPL06 have same chip ID 0x10 in driver. So the FC firmware can't distinguish between them.
