### ISSUE TITLE
FC Freeze randomly in Inav 4.0.0 with JetiEXBUS

### ISSUE THREAD

**Issue by RoadyFPV** [iNavFlight/inav#7672]
The FC Freezes randomly after a couple of minutes.

See here: https://github.com/iNavFlight/inav/issues/7434

**Comment by RoadyFPV** [comment]
Would it be possible for a developer to compile the current release version with GCC 9 for me?

**Comment by RoadyFPV** [comment]
After I have now tried a lot, I think I have found the issue why the FC freezes randomly.

It really seems to be with the ExBus protocol and the GCC10 compiler. Tests showed that the version with GCC9 compiler does not lead to any freezes. When I use INAV 4.1.0 rc1 with ExBus the FC freezes involuntarily.

Since the Jeti receivers can also output SBUS I switched to this protocol. The freezes are gone.
Unfortunately, the telemetry then no longer works.

This is a realy dangerous bug and should be followed up.

**Comment by RoadyFPV** [comment]
@marv-t maybe u can assist here?

**Comment by RoadyFPV** [comment]
I did some more testing today. I had connected the receiver to UART2 on the Matek f722se. There was always this freeze. I have now switched to UART6, there the problem does not seem to occur. I will continue to monitor and test this.

**Comment by RoadyFPV** [comment]
@stronnag is it possible that you compile me 4.1 release with gcc 9?

**Comment by stronnag** [comment]
no, I have no instances of old GCC.

**Comment by RoadyFPV** [comment]
seems like when i disable telemetry feature the bug is gone

**Comment by DzikuVx** [comment]
@RoadyFPV probably this fixes it https://github.com/iNavFlight/inav/pull/8024
I can not test thought

**Comment by RoadyFPV** [comment]
@DzikuVx Thanks, i will test it asap.

**Comment by RoadyFPV** [comment]
@DzikuVx I need a MATEKF722SE target to test it.

**Comment by DzikuVx** [comment]
[inav_5.0.0_MATEKF722SE.zip](https://github.com/iNavFlight/inav/files/8675446/inav_5.0.0_MATEKF722SE.zip)
@RoadyFPV

**Comment by RoadyFPV** [comment]
Thank you, Is this only a test version or is It flyable.

**Comment by RoadyFPV** [comment]
Issue is still threre, fc freeze randomly

**Comment by RobinatiNav** [comment]
Hi RoadyFPV, did the 50Hz change really help?

**Comment by RoadyFPV** [comment]
Jea on inav i only have bench test....
Betaflight works without freezes on 50 hz

**Comment by RobinatiNav** [comment]
> Jea on inav i only have bench test.... for flight i wait for inav 6 release and use gcc9
> 
> Betaflight works without freezes on 50 hz

Thanks. When you have iNav 6 compiled with GCC 9 could you share it with me please? I would like to test it.

**Comment by RoadyFPV** [comment]
I am trying my best. Please remind me if I forget

**Comment by RoadyFPV** [comment]
Wich Target do you need?

I compile inav 6 for myself MATEKF722SE with GCC9.3.1 right now, i hope it works.
This is a realy pain in the a....

**Comment by RobinatiNav** [comment]
> Wich Target do you need?
> 
> I compile inav 6 for myself MATEKF722SE with GCC9.3.1 right now, i hope it works. This is a realy pain in the a....

MATEKH743

**Comment by RobinatiNav** [comment]
> Wich Target do you need?
> 
> I compile inav 6 for myself MATEKF722SE with GCC9.3.1 right now, i hope it works. This is a realy pain in the a....

GOOD LUCK ;)

**Comment by RoadyFPV** [comment]
[inav_6.0.0_MATEKH743GCC9.3.1.zip](https://github.com/iNavFlight/inav/files/11069835/inav_6.0.0_MATEKH743GCC9.3.1.zip)

**Comment by RobinatiNav** [comment]
> [inav_6.0.0_MATEKH743GCC9.3.1.zip](https://github.com/iNavFlight/inav/files/11069835/inav_6.0.0_MATEKH743GCC9.3.1.zip)
> 
> Take care and give it a good bench test

WOW! Thank you very much :)

**Comment by RoadyFPV** [comment]
your welcome

**Comment by RobinatiNav** [comment]
> your welcome

I do not want to be bad guy but could you please compile this one too, please? MAMBAF722_WING I have 2 FCs. If you say No I am OK with it, You have done a lot already

**Comment by RoadyFPV** [comment]
Pls test the first file first, and give me a feedback, i try it to compile it then.

**Comment by RobinatiNav** [comment]
> Pls test the first file first, and give me a feedback, i try it to compile it then.

OK, deal. :) I have installed it already.

**Comment by RoadyFPV** [comment]
pls share a cli.

-version and status

**Comment by RobinatiNav** [comment]
> pls share a cli.
> 
> -version and status

I know I look stupid now. Could you please be more specific? I do not know what version and what status and what about cli you want. About cli do you mean DIFF?

**Comment by RoadyFPV** [comment]
jea instead diff type version

**Comment by RobinatiNav** [comment]
# version
# INAV/MATEKH743 6.0.0 Mar 25 2023 / 19:48:11 (GITDIR-N)
# GCC-9.3.1 20200408 (release)

**Comment by RobinatiNav** [comment]
# status
INAV/MATEKH743 6.0.0 Mar 25 2023 / 19:48:11 (GITDIR-N)
GCC-9.3.1 20200408 (release)
System Uptime: 82 seconds
Current Time: 2041-06-28T03:04:00.000+02:00
Voltage: 15.30V (4S battery - OK)
CPU Clock=480MHz, GYRO=ICM42605, ACC=ICM42605, BARO=DPS310
STM32 system clocks:
  SYSCLK = 480 MHz
  HCLK   = 240 MHz
  PCLK1  = 120 MHz
  PCLK2  = 120 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
SD card: Startup failed
Stack size: 6144, Stack address: 0x20020000, Heap available: 1716
I2C Errors: 50, config size: 9067, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = none
  AIRSPEED : configured = ADC 4, used = none
System load: 1, cycle time: 1003, PID rate: 997, RX rate: 124, System rate: 10
Arming disabled flags: CLI
OSD: MSP DisplayPort: DJI Compatability mode [30 x 16]
VTX: not detected

**Comment by RoadyFPV** [comment]
thx looks good so far.. 
can u force the freeze?

**Comment by RobinatiNav** [comment]
after a few min. I just lost the telemetry :(

**Comment by RobinatiNav** [comment]
I changed the 100Hz to 50Hz now

**Comment by RobinatiNav** [comment]
after about 5 min. I lost the telemetry again even with 50Hz :(

**Comment by RoadyFPV** [comment]
only telemetry lost, fc is running?

i will test it tomorrow. my issue is telemetry is blinking and fc is frozen with a solid light an no reacton on usb

**Comment by RobinatiNav** [comment]
> only telemetry lost, fc is running?
> 
> i will test it tomorrow. my issue is telemetry is blinking and fc is frozen with a solid light an no reacton on usb. Only with gcc10
> 
> i'm not a dev.

FC was OK and control surfaces were moving with a Tx sticks. Only telemetry was gone but I lost FC mainly during the flight.

**Comment by RoadyFPV** [comment]
@marv-t can you take a look or can you guess what is going wrong?

**Comment by RobinatiNav** [comment]
> @marv-t can you take a look or can you guess what is going wrong?

I do not know. I got frozen (I mean telemetry only) twice a couple minutes after it was flashed with hex file compiled in GCC 9.3.1 but after that it is still running without freezing. I was outside in a yard taxing on the grass and it was OK. It is windy outside this weekend. When it is calm down I will fly it.

**Comment by RobinatiNav** [comment]
still ON and no freezing :)

**Comment by RoadyFPV** [comment]
The main problem with gcc10 is that on bench looks ok but in mid flight the fc can freeze...
This cost me a Dart XL, the BUG is since using GCC10 an no one can find the BUG.
The reason why i compile it with gcc9 is that there is no freeze and save to fly.

**Comment by RoadyFPV** [comment]
@RobinatiNav i have now flashd inav6 original with gcc10 and switch to 100 hz tx freq.
iam wiggeling the throttle stick as fast as i can and the fc is freezing instantly no surface wiggeling no telemetry

**Comment by RoadyFPV** [comment]
the fc freezes after a few minutes without me doing anything
next test i switch to 50 hz

**Comment by RobinatiNav** [comment]
> the fc freezes after a few minutes without me doing anything
> next test i switch to 50 hz

I am on 100Hz and 400Kz in I2C. So far no freezing but I have very minimalisting setup on Matek FC. There is only GPS module, LED strip with 2 LEDs (Arming, GPS), and EXBus connection to Rx. NO PWM outputs, no nav modes, no fail safe.

It was running over 1 hour yesterday with no freezing and it is running right now. If you send me .hex file for MAMBA it would be much better that one is fully installed.

**Comment by RoadyFPV** [comment]
> > the fc freezes after a few minutes without me doing anything
> > next test i switch to 50 hz
> 
> I am on 100Hz and 400Kz in I2C. So far no freezing but I have very minimalistic setup on Matek FC. There is only GPS module, LED strip with 2 LEDs (Arming, GPS), and EXBus connection to Rx. No PWM outputs, no nav modes, no fail safe.
> 
> It was running over 1 hour yesterday with no freezing and it is running right now. If you send me .hex file for MAMBA it would be much better that one is fully installed.

Jea with GCC9 or?
Iam on stock inav6 with gcc10 right now

**Comment by RobinatiNav** [comment]
> > > the fc freezes after a few minutes without me doing anything
> > > next test i switch to 50 hz
> > 
> > 
> > I am on 100Hz and 400Kz in I2C. So far no freezing but I have very minimalistic setup on Matek FC. There is only GPS module, LED strip with 2 LEDs (Arming, GPS), and EXBus connection to Rx. No PWM outputs, no nav modes, no fail safe.
> > It was running over 1 hour yesterday with no freezing and it is running right now. If you send me .hex file for MAMBA it would be much better that one is fully installed.
> 
> Jea with GCC9 or? Iam on stock inav6 with gcc10 right now

GCC 9.3.1 I am testing MATEK using GCC 9.3.1 too

**Comment by RoadyFPV** [comment]
test with gcc10 50 HZ tx rate no freeze since around 30min test is runnin.

**Comment by RobinatiNav** [comment]
> test with gcc10 50 HZ tx rate no freeze since around 30min test is runnin.

OK, I will try MAMBA with a stock 6.0 on 50Hz

**Comment by RoadyFPV** [comment]
60 min no freeze with 50hz test still runnin. i can wiggle sicks telemetry ok....

**Comment by RobinatiNav** [comment]
I am running it on 100Hz and receiver set from AUTO to half duplex ON. It is running over 10 min. with no freezing but I don't do any crazy throttle movement because my wife is at home and she doesn't like it. :D Well, she is on the way outside.... ;)

**Comment by RobinatiNav** [comment]
I like Mike's idea: https://github.com/iNavFlight/inav/issues/8899#issuecomment-1483923863

**Comment by RobinatiNav** [comment]
Wife is gone and after just a few second on throttle the telemetry got frozen.

**Comment by RoadyFPV** [comment]
ok i will try to compile MAMBAF722_WING with gcc9

is target MAMBAF722_WING right?

**Comment by RobinatiNav** [comment]
> ok i will try to compile MAMBAF722_WING with gcc9
> 
> is target MAMBAF722_WING right?

I think, it is a time.

**Comment by RoadyFPV** [comment]
test with inav 6 and gcc10 on 50 hz 120min runtime no freeze and i cant force a freeze by wiggeling the sticks

**Comment by RobinatiNav** [comment]
> test with inav 6 and gcc10 on 50 hz 120min runtime no freeze and i cant force a freeze by wiggeling the sticks

Maybe the problem is noise from ESC. I am really curious how it will go with .hex file from GCC 9.3.1

**Comment by RoadyFPV** [comment]
i have 2x 60 amp esc connectet

**Comment by RobinatiNav** [comment]
> i have 2x 60 amp esc connected

In MAMBA configuration, I have one 45A FMS predator V1 and in MATEK configuration I have 45A FMS Predator V2

**Comment by RoadyFPV** [comment]
[inav_6.0.0_MAMBAF722_WINGGCC9.3.1.zip](https://github.com/iNavFlight/inav/files/11071262/inav_6.0.0_MAMBAF722_WINGGCC9.3.1.zip)

**Comment by RobinatiNav** [comment]
> inav_6.0.0_MAMBAF722_WINGGCC9.3.1.zip

thank you :)

**Comment by RobinatiNav** [comment]
Trying to freeze but it holds, not freezing at all.

**Comment by RobinatiNav** [comment]
After 5 min. on heavy throttle not freezing.

**Comment by RoadyFPV** [comment]
https://github.com/iNavFlight/inav/issues/7434

**Comment by RobinatiNav** [comment]
Well, I do not know what to say. Also, I am curious wha devs are going to say.

**Comment by RobinatiNav** [comment]
> #7434

I read it a week ago. I think I have read everything. :)

**Comment by RobinatiNav** [comment]
After another 15 mins of testing outside (only taxing in a grass) no freezing.

**Comment by RoadyFPV** [comment]
i think there schould be no freeze with gcc9

**Comment by RobinatiNav** [comment]
> i think there schould be no freeze with gcc9

Well, thinking is not enough. ;)

**Comment by RoadyFPV** [comment]
> > i think there schould be no freeze with gcc9
> 
> Well, thinking is not enough. ;) At least it is a good sign and it makes me thinking optimistic.

iam compiled inav 4 + 5 + 5.1 for me with gcc9 because nobody could help with the bug.
And i have done many flights without issues

**Comment by RobinatiNav** [comment]
In my MATEK setup the FC only does telemetry and OSD. Servo outputs are under Rx control. I will start testing in the air here. Later I will keep servo outputs under Jeti Rx control but will configure nav modes and servo outputs on FC side but only to give the FC more work. If that passes OK. I will take MAMBA to the air but for start without nav modes....

**Comment by RobinatiNav** [comment]
> > > i think there schould be no freeze with gcc9
> > 
> > 
> > Well, thinking is not enough. ;) At least it is a good sign and it makes me thinking optimistic.
> 
> iam compiled inav 4 + 5 + 5.1 for me with gcc9 because nobody could help with the bug. And i have done many flights without issues

It is really promising. :) I am really glad you made hex file for me.

**Comment by RoadyFPV** [comment]
> > > > i think there schould be no freeze with gcc9
> > > 
> > > 
> > > Well, thinking is not enough. ;) At least it is a good sign and it makes me thinking optimistic.
> > 
> > 
> > iam compiled inav 4 + 5 + 5.1 for me with gcc9 because nobody could help with the bug. And i have done many flights without issues
> 
> It is promising. :) I am really glad you made hex files for me.

since there are so many different setups, i can't guarantee that nothing will happen, test a lot before you start

**Comment by RobinatiNav** [comment]
The wing weakened, so I managed to fly. I was flying with my MATEK setup. In this one FC doesn't fly the model only shows OSD and telemetry. Anyway, it did not freeze. :) I flew 3 batteries, so together 15 mins.

**Comment by happylandings** [comment]
> [inav_6.0.0_MATEKH743GCC9.3.1.zip](https://github.com/iNavFlight/inav/files/11069835/inav_6.0.0_MATEKH743GCC9.3.1.zip)
> 
> Take care and give it a good bench test

Christoph, after I went through exbus related topics here I learnt that you have found a solution in GCC 9.3.1 compiler. It looks like it works on the bench, did you fly it, too?

**Comment by RoadyFPV** [comment]
unfortunately i haven't had the chance to fly 6.0 yet, but what i can say is that the problem exists since version 4. i have flown all versions from INAV 4 on with gcc9 without any problems.

**Comment by happylandings** [comment]
> unfortunately i haven't had the chance to fly 6.0 yet, but what i can say is that the problem exists since version 4. i have flown all versions from INAV 4 on with gcc9 without any problems.

Thank you. The most important information for me is that it is reliable when compiled in GCC9. I have downloaded your matekh743.hex and will give it a try.

**Comment by happylandings** [comment]
I flew 18 batteries during last 3 days all with success. The telemetry neither failed nor flight controller. It was pure pleasure.

**Comment by RoadyFPV** [comment]
I dont know why INAV is not going back to GCC9 until we found a dev who can debug this issue.
i think there are just not enough people who use jeti.

**Comment by happylandings** [comment]
> I dont know why INAV is not going back to GCC9 until we found a dev who can debug this issue.
> i think there are just not enough people who use jeti.

I understand your attitude and I agree with you. I am very happy that at least you can do it. I am pretty happy with an INAV 6 and maybe I will stay with it some time. If the problem is related to the GCC only, it might be solved itself by the time.

**Comment by happylandings** [comment]
All together this week I flew 30 batteries, aprox. 2:45h without any problem whatsoever. Testing is done.

**Comment by RoadyFPV** [comment]
https://github.com/iNavFlight/inav/issues/8899

**Comment by RoadyFPV** [comment]
If we can find the difference between 7.1.2 and 8, maybe we can find the issue causing the freeze?
