### ISSUE TITLE
I NEED A CLI DUMP TXT file from INAV 4

### ISSUE THREAD

**Issue by maRCnh33** [iNavFlight/inav#7673]
Before i upgrade to inav 4 i like to see what's in the CLI DUMP of INAV 4.

I hope someone can place it here for me, tnx very much!

**Comment by maRCnh33** [comment]
why it is closed?

**Comment by stronnag** [comment]
> why it is closed?

(a) This is not an issue
(b) This is not a support forum, as the template you deleted made clear.

**Comment by maRCnh33** [comment]
tnx
