### ISSUE TITLE
Feature Request: Continue with WP mission on failsafe / lost contact with TX.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#770]
Request to have a new failsafe setting during Waypoint mission.

Failsafe_during_waypoint = Use_failsafe_procedure (Default)
Failsafe_during_waypoint = Continue with current WP mission

This would enable simular functionality found in example [Ardupilot](http://ardupilot.org/copter/docs/radio-failsafe.html)

So people can fly out of range missions.

**Comment by oleost** [comment]
#1475

**Comment by vitalyga** [comment]
I'm also highly interested in this feature. Can somebody clarify what is the status? I saw it was added to 1.9 milestone, then removed, then closed... Is that somehow dropped/forgotten?
