### ISSUE TITLE
Feature Request: please add Soft_Serial for the SP Racing F3 Evo target

### ISSUE THREAD

**Issue by helicocrasher** [iNavFlight/inav#771]
Cleanflight has added Soft_Serials for the SP Racing F3 Evo in release v1.14.0 Nov/2 2016.
Intended usage: 
Ser1: OSD
Ser2: SBUS
Ser3: GPS
Soft_Ser1: Bluetooth for Eazy_GUI

**Comment by oleost** [comment]
Already done.
https://github.com/iNavFlight/inav/pull/760

Please use search function next time first..
And close this.

**Comment by helicocrasher** [comment]
Thanks - cool!
Sorry, was using default search filters ... (is open) so I did not see.
