### ISSUE TITLE
OSD on goggle is not showing Average Cell Voltage

### ISSUE THREAD

**Issue by brownviper** [iNavFlight/inav#7721]
## Steps to Reproduce

1. battery cell voltage in setup tab shows the battery voltage
2. selected battery cell voltage on OSD tab
3. on the goggle osd I see mA/(can not make out the symbol) ESC 3
4. it not showing the average cell voltage 

## Expected behavior
I m expecting to see 3.90V

## Additional context

https://pastebin.com/BDxaqzzS
---

# version
# INAV/MATEKF722SE 3.0.2 Sep 15 2021 / 10:24:04 (66011184)
# GCC-9.3.1 20200408 (release)

- FC Board name and vendor:
- Lumenier LUX F7 Ultimate Flight Controller (Dual Gyros)
- INAV version string:

**Comment by avsaase** [comment]
> 3\. on the goggle osd I see mA/(can not make out the symbol) ESC 3

This suggests you don't have the correct font installed.

**Comment by StuweFPV** [comment]
I agree. it works fine for me and i always use cell voltage. upload the font before any diff

**Comment by brownviper** [comment]
I v used all the available fonts, with and without Lipo power.
however, when I used iNav 3.0.2 the dont get the font issue

**Comment by StuweFPV** [comment]
maybe you wana double-check the setting: osd_stats_min_voltage_unit
default would be BATTERY but you want CELL

**Comment by avsaase** [comment]
> maybe you wana double-check the setting: osd_stats_min_voltage_unit default would be BATTERY but you want CELL

That's only for the disarm summary.

**Comment by StuweFPV** [comment]
yeah sorry my mistake. it was late... just an idea. but maybe still worth a try to check if it works in the stats in order to narrow down the issue?

**Comment by MrD-RC** [comment]
@brownviper  Are you saying that you're having this issue on 3.0.2, as indicated by the diff? If so, I can honestly say that I've never seen this issue. What version of configurator are you using?

**Comment by brownviper** [comment]
sorry for the late reply guys,
the issue about the font was mainly showing in version 4. even with uploading different fonts!
when I dropped to 3.02 all seem to work

**Comment by MrD-RC** [comment]
You were using configurator 4.0 with firmware 4.0 I assume? The configurator and firmware major version numbers need to match.
