### ISSUE TITLE
H743 Wing + SDCard + 4.0.0 = "No configuration received within 10 seconds, communication failed"

### ISSUE THREAD

**Issue by LinkinL0gs** [iNavFlight/inav#7722]
## Current Behavior
When an SDcard is in the SDcard slot of my H743 Wing it is impossible to connect to over USB, yea I KNOW ABOUT THE VCP and the FS this and FS that. I'd spent the better part of the past 2 weeks considering giving up RC altogether as a hobby after banging my head against a wall for longer than i'd like to admit.  Then this evening i decided to remove the sdcard and VOILA, Magic, I can connect again and configure the Quite Awesome 4.0.0.  I then made sure to follow the instructions for setting up the blackbox at inavfixedwinggroup and as soon as i plugged back in "No configuration received within 10 seconds, communication failed" Until such time that I removed the SDcard and plugged it back in.  Boom! connected no problemo. 

## Steps to Reproduce

1. Insert SDcard into H743
2. Attempt to connect via USB through windows configurator
3. You won't be able to, I promise you...
4. Unless it's something to do with my particular SDcard: Team 500x 32GB

![d0bbb12a6214e69da6712d079d729b4f](https://user-images.githubusercontent.com/97209669/148327423-e2f5ceae-c407-4305-b1ed-72abe30bfe9a.jpg)

## Expected behavior

I'd been expecting to be able to connect to the FC using USB like i had been in 3.0.1, and yea i know the sdcard hadn't been available at that point but i was still able to connect with the card in the slot, i liked it being there cause i didn't wanna lose it before it was supported. 

## Suggested solution(s)

No clue 🤷 But I appreciate all yinz' work

## Additional context

[](https://pastebin.com/nrqrC0PH)
![image](https://user-images.githubusercontent.com/97209669/148326703-1949b089-7e47-4e4f-9336-3c3cfa0e9659.png)

I feel bad for blaming this on STM and lashing out at them on twitter  = ( 
https://twitter.com/linkinlogs/status/1473151161398091781

---

# INAV/MATEKH743 4.0.0 Dec 15 2021 / 15:18:48 (c20a9852)
# GCC-10.2.1 20201103 (release)

- FC Board name and vendor: Matek H743 Wing
- INAV version string: 4.0.0

**Comment by LinkinL0gs** [comment]
Having read the High CPU load thread in issue thread #7707 I'm going to give their work around solution a try here and see if that resolves what i'm dealing with!  *crosses fingers* will circle back afterwards.

**Comment by bkleiner** [comment]
Closing in favor of https://github.com/iNavFlight/inav/issues/7759 please comment there if your issue was resolved by using a different sdcard or by waiting longer for the sdcard to init
