### ISSUE TITLE
Please ximplement this Alignment Tool for Compass Alignment. 

### ISSUE THREAD

**Issue by brainbubblersbest** [iNavFlight/inav#7748]
[Genius and very intuitive. Follow that Link. ](https://kernel-machine.github.io/INavMagAlignHelper/)

[Github Page](https://github.com/kernel-machine/INavMagAlignHelper) 

I cant imagine a better way for doing this.
This should somehow find a way into the Inav Configurator.

@DzikuVx?

**Comment by DzikuVx** [comment]
Done in #7757

**Comment by brainbubblersbest** [comment]
Not was expected. 😅 But eqal functional 😆
