### ISSUE TITLE
Failsafe not working on development.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#775]
Hi. First I want to say I have not gotten to test this on iNav 1.3 yet because of time limitation.

Im having some issues getting Failsafe RTH working reliable on my fixed wing.

Made and video while I did several attempt.

Only LOG25 and around 5 minutes in the video it works. I have not found the reason for it working that time and not the other.

Dump, and logs and video of all attempts are in this link: https://drive.google.com/open?id=0B-yHzNtOXxbEX1dxSTZod3lnT0U

I will try to do so more backtracking and figuring out whats going on, but if someone have some ideas what to test, or what can be the cause it would be great. @digitalentity ?

**Comment by oleost** [comment]
![logfailed](https://cloud.githubusercontent.com/assets/5670710/20139130/d6e3c83c-a684-11e6-94ca-95e851c3d8eb.PNG)

![log-25](https://cloud.githubusercontent.com/assets/5670710/20139131/d6e3f618-a684-11e6-8c9c-95fc3ced4755.PNG)

**Comment by oleost** [comment]
Noticed on the LOG25 it says BARO, while on this board I have baro disabled.

Also noticing on my telemetry gAlt tells the actually altitude. Like 30m above sea level, and not from the point of arming.

Is there a bug regarding using Gps altitude only compared to baro?

**Comment by digitalentity** [comment]
Blackbox explorer doesn't show correct values at the moment.
`failsafePhase = 2` is actually `RETURN_TO_HOME`, not "LANDING"
`BARO` is actually `NAV ALTHOLD`

**Comment by digitalentity** [comment]
@oleost how are you testing failsafe? Turning off your TX?

**Comment by oleost** [comment]
@digitalentity Yes, turning off TX

There was only 1 time where I screwed up and disarmed instead 👎  But then I said so in video

**Comment by digitalentity** [comment]
In most of the logs navState is stuck at 8 (RTH_INITIALIZE)

This is a synergistic effect of two factors:
1) You are not flying the airplane (speed is low) and you don't have a compass = true heading is unknown so no RTH can be executed as INAV doesn't know where airplane is going
2) Actual bug that doesn't allow the RTH_INITIALIZE state to be re-checked. The bug was introduced by #745.

Fix pending.
