### ISSUE TITLE
Random motor output to 0

### ISSUE THREAD

**Issue by charlesmarseille** [iNavFlight/inav#7756]
## Current Behavior
7" quad arm dips randomly, uncorrelated to throttle, angle or flight mode.
I witnessed another instance where both front motors got 0% (not triggered at the same time, but overlapping intervals).
![inav_motor_output_o_throttle_problem_7inch](https://user-images.githubusercontent.com/36216289/149603802-be8ce878-0c8d-45dd-92ef-0035821d4757.jpg)

## Expected behavior
smooth flight, relatively equal motor output through normal range of motion.
If motor desyncs, I expected the motor output to go to 100% and not 0 (since the arm dips).

- FC Board name and vendor: matek f722se
- INAV version string: 
INAV/MATEKF722SE 3.0.2 Sep 15 2021 / 10:24:04 (66011184)
GCC-9.3.1 20200408 (release)

**Comment by Odin263** [comment]
The sum of the buoyancy of all motors should remain constant even when corrected. As a result, an engine sometimes has to drop to 0, otherwise the quad would shoot up uncontrollably.

**Comment by charlesmarseille** [comment]
The arm litterally dips towards the ground and the quad must recover. 
This is not a normal behaviour, as can be seen in the logs.
