### ISSUE TITLE
Need PINIO and USER1 mode for Matek F405SE

### ISSUE THREAD

**Issue by donne1226** [iNavFlight/inav#7763]
## Current Behavior
![image](https://user-images.githubusercontent.com/19684509/149879985-05640d12-d4c6-4357-9b68-1749970aa8c8.png)
Caddx peanut remote control need PINIO feature. but Matek F405SE inav firmware not support

## Desired Behavior
 Add PINIO and USER1 mode to Matek F405SE

**Comment by Mateyhv** [comment]
@donne1226 are you able to compile the target yourself with PINIO?

**Comment by donne1226** [comment]
@Mateyhv I do watched a [tutorial video](https://youtu.be/2zElnakFQRU), I'm worry about the future upgrade if I compile it myself

**Comment by sevrugin** [comment]
Hi! Have you tested PINIO2? 
I tried to use your patch with 4.1 version
On Configurator I assigned USER2 to the switch. It switched when I change the switch position
#resource 
A08: PINIO1 OUT
B15: PINIO2 OUT

# get pinio_
pinio_box1 = 0
pinio_box2 = 41
pinio_box3 = 255
pinio_box4 = 255

After firmware was flashed I tried to measure the voltage between G and S8 - no differences between ON and OFF switch position

**Comment by sevrugin** [comment]
Updated
I just set 
pinio_box1 = 47
pinio_box2 = 48

**Comment by donne1226** [comment]
This issue has been solved on version 5.1.  many thanks for developer's hard work

**Comment by Refick79** [comment]
> огромное
Привет. У меня так и не получается настроить pinio в inav.   Полетник f405 se пытаюсь повесить на tx4 управляющий пин камеры и не получается(( прошит inav 5.1. Помогите разобраться.
