### ISSUE TITLE
iNAV Target Request for iFlight Succex-D Mini F7 2-6S Flight Controller

### ISSUE THREAD

**Issue by MrMeapz** [iNavFlight/inav#7765]
## Current Behavior
As far as I can tell there is no iNav target yet for this flight controller. I did try to flash a custom .hex file from another feature request but that ended up being for the Succex-E which is not my flight controller and the gyro did not work with that firmware.

## Desired Behavior
A firmware target for the Succex-D Mini F7. I have a GPS on board.

## Suggested Solution
Added iNav support for the Succex-D Mini F7 flight controller.

## Who does this impact? Who is this for?
Anyone that has the iFlight Nazgul Evoque F5D Digital version (DJI Caddx Vista) which is a very popular drone on the market right now.

## Additional context
If anyone can help make this happen I would highly appreciate it. I can't wait to use iNav on my Nazgul for my long range flights using my Li-Ion pack. I have provided a dump of my Nazgul Evoque F5D Digital as attachment to this post (it is from Betaflight however, I don't know how useful that is).

[BTFL_cli_Nazgul_F5D_20220102_152939.txt](https://github.com/iNavFlight/inav/files/7890199/BTFL_cli_Nazgul_F5D_20220102_152939.txt)

**Comment by Odin263** [comment]
Hello @MeapVR , I think you got something wrong there. As far as I know, the D in Succex-D stands for double gyro. The target for this is available in iNav:
![image](https://user-images.githubusercontent.com/90968252/150009401-605b4ee7-d6ae-428e-9f25-8062acc3277b.png)

what you need is the target iFlight BLITZ F7, which is also already available in iNav:
![image](https://user-images.githubusercontent.com/90968252/150009700-70941650-c65f-4132-a10b-87cc91fc3a77.png)

**Comment by MeapVR** [comment]
Thank you. I will check this out.
