### ISSUE TITLE
bug/feature? Servos freeze at extremeties while in the menus

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#7775]
INAV v4.0 release, servos freeze in MAX positions when entering the OSD menu. this can cause un-needed stress on servos attached to the rudder and pitch channels by driving them (potentially) over the limits of the servo or control surface in the case of binding.

fix: set the servos to be centered to their mid range when in the OSD menu.

Affects: All fixed wings

**Comment by OptimusTi** [comment]
Found out why. I'll give it a crack and post a PR if I can make it work.

**Comment by OptimusTi** [comment]
> Found out why. I'll give it a crack and post a PR if I can make it work. 

Can't make it work. Can't find a way to reset the servos after entering the cms. 😟

**Comment by wx4cb** [comment]
@OptimusTi  couldnt you just freeze them at 1500 ?

**Comment by OptimusTi** [comment]
I thought of doing that before line 769 but I couldn't figure it out. Maybe doing a little auto servo test to make it look cool

**Comment by wx4cb** [comment]
> I thought of doing that before line 769 but I couldn't figure it out. Maybe doing a little auto servo test to make it look cool

somewhere around line 1313

**Comment by wx4cb** [comment]
@OptimusTi  not sure if you can do this but maybe (at lines 1311-1313 etc
```
    if (!cmsInMenu) {
        // Detect menu invocation
        if (IS_MID(THROTTLE) && IS_LO(YAW) && IS_HI(PITCH) && !ARMING_FLAG(ARMED)) {
             THROTTLE = YAW = PITCH = 1500;
            cmsMenuOpen();
            rcDelayMs = BUTTON_PAUSE;    // Tends to overshoot if BUTTON_TIME
        }
```

**Comment by MrD-RC** [comment]
I’m sure the servos used to be disabled in the CMS. But were re-enabled when servo adjustments were added to the CMS?

**Comment by OptimusTi** [comment]
It's the other way around. Until 2 years ago, servos were active in the cms.

**Comment by OptimusTi** [comment]
> @OptimusTi  not sure if you can do this but maybe (at lines 1310-1315) etc
> 
> ```
> 
>     if (!cmsInMenu) {
> 
>         // Detect menu invocation
> 
>         if (IS_MID(THROTTLE) && IS_LO(YAW) && IS_HI(PITCH) && !ARMING_FLAG(ARMED)) {
> 
>              THROTTLE = 0;
> 
>              YAW = PITCH = 1500;
> 
>             cmsMenuOpen();
> 
>             rcDelayMs = BUTTON_PAUSE;    // Tends to overshoot if BUTTON_TIME
> 
>         }
> 
> ```

Nope. That's not it.

**Comment by JulioCesarMatias** [comment]
https://github.com/iNavFlight/inav/pull/5319

**Comment by wx4cb** [comment]
> #5319

guess this is finally going to be fixed lol

**Comment by JulioCesarMatias** [comment]
> > #5319
> 
> guess this is finally going to be fixed lol

do you want to test?

**Comment by wx4cb** [comment]
> > > #5319
> > guess this is finally going to be fixed lol
> do you want to test?
to be honest, i havent got the time right now as im in the middle of major projects at work, and moving house
