### ISSUE TITLE
"beeper -ALL" settings not applied to DSHOT? 

### ISSUE THREAD

**Issue by miro-hartinger** [iNavFlight/inav#7786]
****

## Current Behavior
Well it seems that "beeper -ALL" is only applied to beeper and ESC signaling goes through. So when all is disabled and HW health is bad or airplane inits - the ESC MOTOR signals (beeps).

[Video](https://youtu.be/iJTQXsX_Fxs)

## Steps to Reproduce

1. Clean install INAV 4.0.0 on MATEK wing F411. Connected beeper and BLHELI32 ESC.
2. Setup whole plane and last thing opened CLI and Typed in "beeper -ALL"
3. End CLI with "save"
4. Connect in configurator and check CLI "beeper" showing ALL DISABLED
5. Closed Configrator - disconnected USB
-----
1. Connect USB
2. Open configurator
3. Hardware health is red because GPS has no power
4. Connect BATTERY and hear init beeps 1-2-3 from ESC
5. ESC now starts beeping instead of beeper (beeper accepts settings all disabled)
6. ESC MOTORS beeps untill GPS is init and HARDWARE HEALTH is ok
7. NEXT any other input for beeper is signaled by ESC

## Expected behavior
ESC MOTOR signaling/beeping should match settings in "beeper"

## Suggested solution(s)
I am no expert but expand beeper settings to DSHOT communication?

## Additional context
BLHELI 32 
---
# version
# INAV/MATEKF411 4.0.0 Dec 15 2021 / 15:00:06 (c20a9852)
# GCC-10.2.1 20201103 (release)

- FC Board name and vendor:
Matek WING F411
- INAV version string:
INAV/MATEKF411 4.0.0 Dec 15 2021 / 15:00:06 (c20a9852)

**Comment by b14ckyy** [comment]
CLosing due to age. @ me if this is still an issue in 7.1 RC1
