### ISSUE TITLE
BUG: ELRS SA Control conflicting with INAV

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#7796]
had issues with SA on 4.0/4.1 with elrs? getting errors "vtx_power invalid setting".

when i go into the vtx menu the whole FC locks up. checked in CLI and it's setting vtx_power to 8.... manually set itback to 4 in the cli, saved, went back into the osd after a reboot, but it will not change the power on arming and then it's all locked up again.

f765 wse, tbs unify pro32 with SA setup..

Also same thing on an f411wse with a unify evo

Control link is elrs

**Comment by wx4cb** [comment]
ok this is reproducable.

the issue is the vtx control in the ELRS LUA script was overriding the INAV SA and causing it to lock up when in the OSD VTX Menu.

The temporary fix is to disable the SA control in the ELRS LUA Script.

The Permanent Fix that it needs: if SA is enabled in the ports tab ignore ANY SA commands coming from the receiver

**Comment by avsaase** [comment]
AFAIK INAV does not support MSP from the receiver. That's also why the betaflight Lua script does not work with INAV.

**Comment by wx4cb** [comment]
@avsaase  something is causing inav to freeze. so that would explain it.

maybe we can silently drop those packets? because it's definately causing an issue.. as soon as i turned off in the lua it worked. 

so some how the vtx_power cli variable is getting set because it definately went to "8" and when i changed it to 6 it went to 6
