### ISSUE TITLE
i2c gps not recognized anymore

### ISSUE THREAD

**Issue by bk79** [iNavFlight/inav#78]
I've tried using master branch and after the flash on CC3D i2c nav board is not recognized and from CLI I cannot set gps_provider =I2C

**Comment by digitalentity** [comment]
New setting is `gps_provider = I2C-NAV` (https://github.com/iNavFlight/inav/wiki/iNav-CLI-variables)

**Comment by bk79** [comment]
ok closing

**Comment by digitalentity** [comment]
Please reopen if the issue persists
