### ISSUE TITLE
Matek H743 ADC issue

### ISSUE THREAD

**Issue by audio98** [iNavFlight/inav#7813]
ADC for both current and Vbat give correct values after "save and reboot"  but are static and do not change until the next "save and reboot"
All other features GPS, Magnetometer, LED lights, camera tilt servo, Barometer. motors work properly.

**Comment by audio98** [comment]
Works in iNav 3.02 but not in 4.0

**Comment by terryfritz99** [comment]
This has fixed the problem I had with no Current value displayed in OSD in 4.0.0 Thank you for the fix.
