### ISSUE TITLE
mmix does not work properly in INAV 4.0

### ISSUE THREAD

**Issue by ABLomas** [iNavFlight/inav#7817]
With 4.0 release something happen with GUI control and custom mixer. Downloaded fresh copy of 4.0 configurator, installed copy to kakute F7.
OK, just trying to swap motors: https://t.me/INAVFlight/220834 - it reverts after reboot without any effect.
Going to do the same with mixers (swapping control axis in GUI, in other words, putting "-1" for 1 to swap motors) has no effect.
One guy in INAV TG said that doing the same via CLI does not work, too (https://t.me/INAVFlight/221196), while "Miel'O'txin" said, that motor wizard is working for him.
Earlier i could do just do something like:
`mixer custom
mmix reset
mmix ....`
in CLI alone, but now "mixer" command is unavailable and documentation (https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md) does not explain how to swap different mixers (for example, from QUADX to QUAD+ or get current mixer modified).

I just re-tried to do custom mmix in CLI with swapped axis, after 'save' and reboot 'mmix' command output is empty. Loaded mixer via GUI - mmix lists custom values, but motor wizard again does not work. 

So, in short - changing motor order does not work on some platforms and there is no (clear/documented) way to work around this issue in CLI.

**Comment by stronnag** [comment]
see  https://github.com/iNavFlight/inav/wiki/Custom-mixes-for-exotic-setups

custom mixer works fine for my vtail, last time I tried it.

```
# mixer
mmix 0  1.000 -0.580  0.580  1.000
mmix 1  1.000 -0.460 -0.390 -0.500
mmix 2  1.000  0.580  0.580 -1.000
mmix 3  1.000  0.460 -0.390  0.500
```

**Comment by ABLomas** [comment]
Agree, that is may work, but let's try - here is default QuadX mixer:
```
# mmix
mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000
```

Tested by working in hands - due to my copter being inverted configuration - motors need to be swapped - so it stabilizes in wrong order.
OK, let's enter those lines:
```
mmix 0  1.000 1.000  -1.000 -1.000
mmix 1  1.000 1.000 1.000  1.000
mmix 2  1.000 -1.000 -1.000  1.000
mmix 3  1.000 -1.000 1.000 -1.000
```

So final mixer becomes:
```
# mmix
mmix 0  1.000  1.000 -1.000 -1.000
mmix 1  1.000  1.000  1.000  1.000
mmix 2  1.000 -1.000 -1.000  1.000
mmix 3  1.000 -1.000  1.000 -1.000
```
(maybe wrong for actual configuration, but now should invert axis stabilisation for sure)
...save
...and here i have the same stabilisation (if rotate copter in hands - the same motors are speeding up as in QuadX config).

I know, this is working for some, but here is one setup which is not working OK on 4.0 for me (starting from the same motor wizard, i linked video above).

**Comment by DzikuVx** [comment]
It is working for all cases. There is a misconception: custom mixer does not change the motor order. Custom mixer changes the mixer. Motor connected to S1 will still be connected to S1, S2 will be S2 and so on.
