### ISSUE TITLE
Pid tune via dji V1 googles

### ISSUE THREAD

**Issue by klaudius666** [iNavFlight/inav#7831]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1. Changing rates in googles
2.the rate change and quickly go back to initial value

3.
4.

## Additional context

---

- FC Board name and vendor: mambaf722i2c
- INAV version string: 3.0

**Comment by klaudius666** [comment]
Same for pids

**Comment by Scavanger** [comment]
Use iNav 4. Inflight adjustments are supported via the craft name field.
