### ISSUE TITLE
bug in Soft I2C driver

### ISSUE THREAD

**Issue by night-ghost** [iNavFlight/inav#784]
There is a bug in
```
static bool I2C_Start(void)
{
    SDA_H;
    SCL_H;
    I2C_delay();
    if (!SDA_read) {
        return false;
    }
    SDA_L;
    I2C_delay();
    if (SDA_read) {
        return false;
    }
    SDA_L;
    I2C_delay();
    return true;
}

```

should be 
```

    SCL_L;
    I2C_delay();
    return true;
}
```

**Comment by DzikuVx** [comment]
@digitalentity ??

**Comment by digitalentity** [comment]
Yes, this is a bug. Will fix, however we don't use soft-i2c anywhere

**Comment by digitalentity** [comment]
PR in place. Closing

**Comment by night-ghost** [comment]
> however we don't use soft-i2c anywhere

Soft_i2c is much more reliable than SoftSerial so on some boards it is better to move external i2c to Input port via it, and to use the FlexiPort as a 2nd hardware serial.

**Comment by digitalentity** [comment]
> Soft_i2c is much more reliable than SoftSerial so on some boards it is better to move external i2c to Input port via it, and to use the FlexiPort as a 2nd hardware serial.

Hm... didn't think about it from that perspective. Also soft-i2c consumes much less memory compared to softserial.

**Comment by digitalentity** [comment]
See #788 to track the idea.
