### ISSUE TITLE
Voltage doesn't update in osd or configurator when RGB multicolor led is enabled.

### ISSUE THREAD

**Issue by JonasStalmans** [iNavFlight/inav#7853]
## Current Behavior

When multicolor RGB led option is enabled, voltage doesn't update => neither in the OSD. I am using a lumenier H7 HD ultimate: target: mateksys H745. Firmware 4.0.0

## Steps to Reproduce

1. turn on multicolor RGB led: Save and reboot
2. Plug in Battery 
3. check voltage in Inav configurator
4. unplug battery and check voltage in Inav configurator

## Expected behavior

Voltage to be shown and updated correctly with a minimum delay.

## Suggested solution(s)

---

- FC Board name and vendor: MATEKH743 Lumenier
- INAV version string: 4.0.0

**Comment by DzikuVx** [comment]
Fixed in 4.1
