### ISSUE TITLE
DJI OSD Distance to home missing leading zero after decimal point 

### ISSUE THREAD

**Issue by roteron1** [iNavFlight/inav#7857]
Whenever a new full km is reached, there is a missing leading zero after the decimal, i.e. 1.01km displays as 1. 1km. This repeats for every new km. There appears to be a space instead of a zero.

**Comment by Scavanger** [comment]
This is not a bug in iNav. iNav only provides the pure number, the formatting is done in the DJI glasses. This must be fixed in the DJI firmware.

**Comment by DzikuVx** [comment]
Just like @Scavanger said, this is DJI OSD bug, INAV is only providing value, not formatting
