### ISSUE TITLE
If failsafe is initated without throttle it will disarm. Unsafe for FW.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#786]
Tested on both official 1.3 release and later 1.4 development.

The case:

If Stage 1 throttle is set to auto the failsafe wont work.
If Stage 1 throttle is set to hold, the failsafe will work IF you have throttle applied from the TX when loosing signal / going into failsafe.

https://drive.google.com/open?id=0B-yHzNtOXxbERkUwVHJuS3czVDA

3 logs and cli dump.

On all three logs TX sticks want to cmmand 1700us, but motor output is only 1000us except on LOG0038 when both throttle is set to hold and throttle is applied.

In case with fixed wing, where one often can find yourself flying without throttle this is critical.

**Comment by oleost** [comment]
Does #789 also fix this?

**Comment by digitalentity** [comment]
Yes, but with a limitation - if your throttle is LOW for longer then `failsafe_throttle_low_delay` it will disarm.

**Comment by digitalentity** [comment]
We need a possibility to disable this feature - "disarm instead of failsafe when throttle is LOW for too long".

**Comment by digitalentity** [comment]
Will fix this as a part of #789 as well

**Comment by digitalentity** [comment]
Fixed. ~~Wiki and docs need updating.~~ Now `failsafe_throttle_low_delay = 0` means "don't disarm when failsafe at low throttle".

Docs updated.

**Comment by oleost** [comment]
Great. Will do some testing in a couple of hours.

**Comment by oleost** [comment]
Btw with all my test I had throttle cut shorter period than failsafe_throttle_low_delay = 100

**Comment by oleost** [comment]
Fixed as a part of#789
