### ISSUE TITLE
Matek 405 MiniTE

### ISSUE THREAD

**Issue by Grumpyrse** [iNavFlight/inav#7874]
When is this board going to be supported?
Thankyou

**Comment by FNNCFPV** [comment]
> 

When is that releasing?

**Comment by Jetrell** [comment]
Around late June.

**Comment by helicocrasher** [comment]
Would be nice to have it earlier. :-)

The F722 SE Mini is no more available and the F405 MiniTE is the best replacement.
Having it ready for maiden today with the Matek FW 4.1 build. 
One present issue with that is: entering the blackbox tab in the configurator crashes the FC. So no way to erase the the BB memory.

**Comment by MATEKSYS** [comment]
@helicocrasher  fixed  http://www.mateksys.com/Downloads/FW/inav_4.1.0_MATEKF405TE.hex

**Comment by helicocrasher** [comment]
@MATEKSYS 
another issue observed.
The OSD is not displaying at all the values that are supposed to flash.
For example altitude when above set alarm limit. Instead of flashing noting is displayed at all.
Any chance to reproduce and fix? :-)  
Thank you

**Comment by OptimusTi** [comment]
Use
set display_force_sw_blink = ON

Some boards require this.

**Comment by MATEKSYS** [comment]
No any target has "display_force_sw_blink" definitions.  All have it set to off by default in INAV fw

**Comment by MrD-RC** [comment]
My point is more “Why not?” If all boards that use that target require it to be enabled (only one FC uses that target); why not add it to the target config? It would make life easier for the end user. 

The problem only starts when you have multiple FCs on the same target where one could require this, another doesn’t.

**Comment by MATEKSYS** [comment]
> 

nothing to do with target,  if multiple FCs use the same target, no possible one require it, others don't. 
same theory for all other FC with other targets,  no possible F405-miniTE requires it,  others don't require it if they all don't have this definition in target.

**Comment by MATEKSYS** [comment]
If need to set display_force_sw_blink = ON by default,  it is better to add this into INAV code for all targets

**Comment by DzikuVx** [comment]
#7924
