### ISSUE TITLE
Unable to get INAV to recognize VL53L0X sensor (I2C)

### ISSUE THREAD

**Issue by armsp** [iNavFlight/inav#7879]
## Current Behavior
Since the past week I have been trying everything to get INAV to recognize my VL53L0X sensor. On the i2c bus, I have a magnetometer and the VL53L0X tof sensor attached. The magnetometer works well, but inav shows red for the VL53L0X sonar sensor as the screenshot below shows -
![image](https://user-images.githubusercontent.com/12681262/156946403-32e204ec-1d35-4db5-b640-6627a3340610.png)
Any idea how to ensure that inav recognizes it?

## Expected behavior
The sonar sensor is recognized and is blue in color instead of red.

## Setup Details
My flight controller is [Diatone Mamba Stack Basic F405 Mini MK3.5](https://www.team-blacksheep.com/products/product:5206)
```
# version
# INAV/MAMBAF405US_I2C 4.1.0 Feb 11 2022 / 10:39:20 (611d26f4)
# GCC-10.2.1 20201103 (release)
```

CONFIGURATOR - 4.1.0
FC FIRMWARE - 4.1.0

**Comment by DzikuVx** [comment]
Please verify that VL53L0X is configured to use `0x29` address

**Comment by armsp** [comment]
@DzikuVx That helped...thanks so much Pawel! I get the sensor readings now.
On a side note, I want to attach a flight computer (R-Pi) to INAV FC, but it is not quite clear to me if INAV supports Mavlink or MultiWii and how to go about interfacing and sending commands...is there a Wiki or proper documentation for this?

**Comment by Killerbeans** [comment]
I'm having the same problem. I have connected a TOF 10120. Not detecting it. Where do I find the address for it? Thanks
