### ISSUE TITLE
Record Flight Hours / Total Flight Distance on FC 

### ISSUE THREAD

**Issue by Jullibach** [iNavFlight/inav#7884]
Hi,
I guess a lot of people would like to have a feature that records the total Flight Time of a Model. (Lifetime) 
Nowadays no one knows how long his airplane flew, and how far it came.
Maybe we can have a simple solution that we can read the data in the Configurator via the CLI, or we could have a new OSD element?

**Comment by MrD-RC** [comment]
This exists. 
To turn it on in CLI `set stats = ON`. Then use `get stats` To see the total time, total distance, and total energy.
