### ISSUE TITLE
Turtle mode INAV 4.1 and 5.0

### ISSUE THREAD

**Issue by andreasabatino01** [iNavFlight/inav#7887]

**Comment by andreasabatino01** [comment]
I have an FC Mamba F405 I2C with INAV. I have a problem with turtle mode, in particular, when I activate it, only the front right and rear right motors rotate in the opposite direction in all possible combinations. The other two motors rotate in the same direction of flight. Tested with both INAV 4.1 and INAV 5.0 with this version: https://github.com/iNavFlight/inav/pull/7733. How can I solve?

**Comment by DzikuVx** [comment]
fixed by #7733
