### ISSUE TITLE
WP - Store waypoints in non-volatile memory

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#79]
Use onboard dataflash for waypoint storage (if available)

**Comment by stronnag** [comment]
Having just 15 waypoints is somewhat limiting, especially on F3 (even multiwii managed > 100).
How about at least having the MAX WAYPOINTS as a TARGET define? 
Or protected by `#ifndef`so people who would like to blow some memory on more way-points can so do if they compile there own images?

**Comment by digitalentity** [comment]
Let's see if non-volatile waypoint storage can be done towards 1.3.
Having MAX_WAYPOINTS a per-target define is a good idea, will do.

**Comment by digitalentity** [comment]
@stronnag have a look at #395
