### ISSUE TITLE
INAV - No OSD Needed - Compile Error

### ISSUE THREAD

**Issue by Digital256** [iNavFlight/inav#7902]
I have a project where I don't need OSD. When I disable all the OSD references in the target files I get an error compiling the code.

Compile error appears in src/main/rx/rx.c
      undefined reference to 'osdConfig_System'

The src/main/rx/rx.c code includes this.
       #include "rx/crsf.h"

The src/main/rx/crssf.c code includes this.
      #include "io/osd.h"

Also  src/main/rx/crssf.c has code using OSD for calculations.

Recommended Solution:
    #ifdef USE_OSD

I'm using the latest code from GitHub.

![Compile Error](https://user-images.githubusercontent.com/98717468/158278472-d22dcb75-4962-4bd7-aa37-2d977d0f0374.png)

**Comment by DzikuVx** [comment]
@Digital256 you are welcome to propose a pull request that fixes that. It's an open-source and seems like you know what you are doing :)

**Comment by Digital256** [comment]
Will do.
