### ISSUE TITLE
Altitude hold slow oscillations about 1m in height

### ISSUE THREAD

**Issue by andrefreitas97** [iNavFlight/inav#7922]
## Current Behavior

Altitude oscillates very slowly around 1m in height in PosHold mode.

## Expected behavior

I would like to improve altitude hold precision. The question is: is it possible to get better accuracy than the 1m oscilation that i am experiencing? At the moment I am using KAKUTEF7 HDV with BMP280 barometer and TFmini S (default PID).

If it is possible, which settings should i change. I already tried changing inav_w_z parameters but with no success :(

- INAV version: 4.1.0

**Comment by Jetrell** [comment]
There are many issues that can effect altitude positional accuracy. 
* Lack of tight cell foam barometer buffer.
* Prop wash air disturbances from the arms on a specific frame.
* Air temperature.
* The MR is experiencing higher than expected ACC noise. 

Changing settings for a quick fix isn't always easy. Analyzing your log data, and making changes accordingly is best.
Increasing the Barometer weight is not likely to help if its experiencing the above mentioned issues.. It may actually make it worse... Reducing `inav_w_z_baro_p` the smallest amount may help.

The effect of low GPS HDOP, can improve things from flight to flight. But don't increase `inav_w_z_gps`... GPS altitude inconsistency is too great.

There are a couple of other settings that can help... But you need a firm grasp of what they do... Or changing them will potentially make it worse.

**Comment by andrefreitas97** [comment]
Thank you for your help! I already tried increasing inav_w_z_baro_p but never thought about lowering. I will give that a go and see if it helps.
