### ISSUE TITLE
Mamba F722 mini mk3 basic gyro not recognized

### ISSUE THREAD

**Issue by rotel57** [iNavFlight/inav#7923]
## Current Behavior

Inav do not find gyro and acc (grey) new installation  found that  Diatone change mpu 6000 to 6500 in newer boards. 
The FC work with betaflight  

## Steps to Reproduce

1.
2.
3.
4.

## Expected behavior

 think need resource for 6500 mpu
## Additional context

---

- FC Board name and vendor: mamba F722 mini mk3 basic   Diatone 
- INAV version string: any

**Comment by DzikuVx** [comment]
#7965
