### ISSUE TITLE
Matek F411-Wing servo to motor remap

### ISSUE THREAD

**Issue by MattCall1995** [iNavFlight/inav#7927]
Hi guys,

I'm trying to configure a old DJI flamewheel hexacopter to use iNav. I'm trying to get it working with the F411-wing FC.
This controller has 6 "S" pins so I thought I would be able to have 6 motor outputs. The F411-wing has 2 dedicated motor output on the PCB (power pads next to the signal pads). 
But I can only assign 4 motors in inav and the other 2 can be set as servo. I haven't tried to use 3 and 4 (1 & 2 are the dedicated motor outputs).

Seems strange that only 2 addition motor outputs can be configured whilst all off them should be a basic 50Hz signal.

Am I missing something? Is this a limit with this board? Can the servo outputs be remapped as motor outputs?

Thanks!

**Comment by MrD-RC** [comment]
Why is it strange that a flight controller designed for planes only has 2 motor outputs? To be honest, I find it more strange that you can assign 4 motors. 

Its all down to timers. You can’t have motors and servos on the same timer. 

There is no remapping in iNav.

**Comment by DzikuVx** [comment]
This will be available with INAV 5 and `output_mode` setting
