### ISSUE TITLE
Unable to flash Matek 405std

### ISSUE THREAD

**Issue by Smyffy82** [iNavFlight/inav#7932]
## Steps to Reproduce

1.hold boot button
2.connect usb
3.firmware target Matek 405std
4.erase and flash board

## Expected behavior
 firmware flashed successfully without being stuck   #`#halfway`

## Suggested solution(s)
<!-- How could we solve this issue? What changes would need to made to INAV? -

- FC Board name and vendor:405std MATEK
- INAV version string:

**Comment by 0crap** [comment]
It might help to give some more info.
- Did it work in the past?
- Which version do you try to flash?
- Which target do you select?
- Do you use Full chip erase?

There are no known issues flashing the Matek F405-STD
(Use one myself.)

**Comment by Smyffy82** [comment]
MATEKF405STD
4.2.11 - 09-11-2021 20:48
Full chip erase
Manual baud rate 57600

**Comment by Smyffy82** [comment]
Gets halfway through flashing…
Then at the top left “USB device successfully closed” but flashing yellow bar freezes

**Comment by MrD-RC** [comment]
Have you tried putting the baud rate back to automatic?

**Comment by Smyffy82** [comment]
Baud rate is set back to automatic but still freezes during the process 
It’s BetaFlight I’m trying to flash on to the board not Inav although this is probably the wrong place to post this it’s been suggested to me that I desolder everything off the board and start again to see if that works

**Comment by MrD-RC** [comment]
If the issue is with BetaFlight, it has nothing to do with iNav. This should be posted on the [BetaFlight GitHub](https://github.com/betaflight/betaflight-configurator/issues).

**Comment by Smyffy82** [comment]
![6E28FEC0-A2A1-441E-9DB0-59151C140D77](https://user-images.githubusercontent.com/102487303/161044265-7473ed5e-dd59-4271-9d75-656bbbaa9f84.jpeg)
#

**Comment by MrD-RC** [comment]
Again, this is BetaFlight. Please post the issue on their GitHub, which I linked to in my last message. 

This has nothing to do with iNav.
