### ISSUE TITLE
T-Motor F7 Pro V2 target missing internal 16MB flash blackbox

### ISSUE THREAD

**Issue by FPVMartin** [iNavFlight/inav#7953]
## Current Behavior
target TMOTORF7V2 missing black box. Manufacturer states that this flight controller has 16MB flash blackbox. Betaflight picks up the flash blackbox but INAV does not

## could it be possible to add the flash blackbox to this target?

Let me know if you need a "dump" or "diff" file.

Thank you.

P.S.
I'm totally new to this.

- FC Board name and vendor: T-Motor F7 Pro V2 from T-Motor
- INAV version string: INAV 4.1 on FC (see attached screenshot)

![image](https://user-images.githubusercontent.com/95198077/162024027-759ffdbb-4a72-4c67-b8b9-d193babc2790.jpeg)

![image](https://user-images.githubusercontent.com/95198077/162024070-875c9a27-31ce-4bf4-89f7-d6130b27754a.png)

**Comment by FPVMartin** [comment]
Here is some info on the FC

Specifications

Mounting Pattern: 30.5x30.5mm/M3
Dimensions: 37x37x7.5mm
MCU: STM32F722 RET6
Target: TMOTOR F7 V2
Blackbox: 16MB Flash
Built-in OSD: AT7456
ESC Signal: M1-M8
BEC: 10V/2A, 5V/3A
Barometer: BMP280
Input Voltage: 3-8S
Motor Outputs: 8
IMU: MPU6000
USB: Type-C
Weight: 8.1g
UARTS: 6
WiFi: Yes

**Comment by OptimusTi** [comment]
Are you sure you are using the right target?

**Comment by FPVMartin** [comment]
I've been using the TMOTOR F7 V2 target. That's the e only TMotor target I saw in INAV.

**Comment by FPVMartin** [comment]
I did re-flash it just in case there was an issue with the first flash but still no blackbox login.

**Comment by OptimusTi** [comment]
> I've been using the TMOTOR F7 V2 target. That's the e only TMotor target I saw in INAV.

That doesn't mean it's the correct target. There was another target that was removed on 4.1.

Does it work with Betaflight?  Check if it works in EmuFlight.

**Comment by FPVMartin** [comment]
I check on BF and it worked. Do I need to download INAV 4.0?

The manufacturer mentions that the target is TMOTOTF7V2.

I'm new to INAV. I'm not familiar with finding proper targets for FC except for what the manufacturer says.

**Comment by FPVMartin** [comment]
It was the same target for BF

**Comment by erstec** [comment]
@FPVMartin I see TMOTOR F7 V2 differs from TMOTOR F7, mentioned by @OptimusTi, by `SPI3` pins used
But in this case you should lose UART3 TX/RX and ADC2 (Current meter)... as mentioned pins are mapped to those peripherals.

You can build custom FW for "removed" TMOTOR F7 target to test, if you want, by enabling it in CMakeList.txt, in same target forder...

NOTE: In BF code SPI3 related part are totally same to INAV, for both V1 and V2 accordingly

**Comment by FPVMartin** [comment]
Ok, this jargon is a bit out of my understanding.

I can try the TMOTORF7 instead of V2

I have GPS on UART 3. I'll have to move it to another UART

**Comment by erstec** [comment]
> Ok, this jargon is a bit out of my understanding.
> 
> I can try the TMOTORF7 instead of V2
> 
> I have GPS on UART 3. I'll have to move it to another UART

Ok :) In simple words, if you have working UART3, in your case it is GPS with TMOTOR F7 V2 target flahed, it seems you have correct target selected.
Can you show photo of your FC?

**Comment by FPVMartin** [comment]
Ok, I'll send you a pic as soon as I'm home later today.

Here is a generic idea of what it looks like

**Comment by FPVMartin** [comment]
![image](https://user-images.githubusercontent.com/95198077/162068469-3c83589f-5890-4c06-ad29-eb2d3a2ddef0.jpeg)

![image](https://user-images.githubusercontent.com/95198077/162068494-af21556c-5750-436c-b82b-595340306b22.jpeg)

**Comment by FPVMartin** [comment]
![image](https://user-images.githubusercontent.com/95198077/162070616-df71e1c8-4ae6-427b-8a36-5a25b8d0342a.jpeg)

**Comment by FPVMartin** [comment]
Here is a pic of my set up I took when I completed the build last weekend. I'll send you more when I'm home.

**Comment by erstec** [comment]
> Here is a pic of my set up I took when I completed the build last weekend. I'll send you more when I'm home.

Thank you. It is more than enough :) I will take a look to code tomorrow

Just to clarify, you are using TMOTORF7V2 on BF and BlackBox works ok?
And few more points: during flashing INAV Full chip erase are turned on? and BlackBox not working without any configuration, just after flashing INAV too?

**Comment by FPVMartin** [comment]
Yes, I put on BF and blackbox worked then I flashed INAV with full chip erase and blackbox does not work.

**Comment by FPVMartin** [comment]
With TMOTORF7V2 as target

**Comment by FPVMartin** [comment]
Thank You for looking into it

**Comment by FPVMartin** [comment]
I see. I guess I'll add a micro SD card reader to record the blackbox.

Thank you for looking into it.

I was hoping to copy/paste the blackbox pin out from BF to INAV but that won't do anything.

**Comment by erstec** [comment]
@eksperts do it work with EmuFlight? Or @FPVMartin can check that too?

**Comment by FPVMartin** [comment]
I didn't try emuflight. I don't have the configurator. I have BF and INAV. I'm looking to use poshold and RTH so I can got through the drone declaration thing here in Canada amd be able to fly in controlled airspace (where our local racetrack is located)

I just assume BF and emuflight are similar that way.

I can always try it if you need more data on this.

Let me know.

**Comment by FPVMartin** [comment]
Is the issue with the code in INAV or it's a thing strictly with that board?

**Comment by erstec** [comment]
@FPVMartin BetaFlight don't use targets, but use defaults, applied after flashing unified targets FW. EmuFlight uses targets, same as INAV, that why I asking you to try EF.

There is no answer to your second question rn, whithout having exact same FC it is hard to find what wrong and took time ;) I will get same FC in 7-9 workdays, but till that you can assist. You know, getting board doesn't mean having freetime to debug, dig code and etc.

**Comment by FPVMartin** [comment]
Of course. I'll install emuflight and see it blackbox works.

**Comment by eksperts** [comment]
I checked. Installed Emu
<img width="343" alt="Screenshot 2022-04-07 at 16 56 31" src="https://user-images.githubusercontent.com/7188878/162216668-ce6aa4ed-5617-43ed-a577-b05c473f93db.png">
and BB is there
<img width="1092" alt="Screenshot 2022-04-07 at 16 57 51" src="https://user-images.githubusercontent.com/7188878/162216754-4b39d773-5e34-421e-8f28-cbf7cc8adaaf.png">

cc: @erstec

**Comment by FPVMartin** [comment]
Oh wow. So it's strictly an INAV thing

**Comment by erstec** [comment]
I just found FC with same behaviour, IFlight F4 SuceX-D AIO, with 8MB onboard flash, but it don't show it in Configurator. I'll can go deep now

**Comment by erstec** [comment]
@eksperts @FPVMartin I need some assist, can you check FW attached. flash it, and show me CLI 'status' output, please.

[inav_4.1.0_TMOTORF7V2.hex.zip](https://github.com/iNavFlight/inav/files/8450812/inav_4.1.0_TMOTORF7V2.hex.zip)

**Comment by eksperts** [comment]
roger @erstec:
```
# status
System Uptime: 13 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE, IMU2=NONE
Stack size: 6144, Stack address: 0x20010000, Heap available: 2028
I2C Errors: 285, config size: 8830, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 6, cycle time: 1014, PID rate: 986, RX rate: 49, System rate: 10
Arming disabled flags: ACC HWFAIL RX CLI
VTX: not detected
SPI FLASH Status: 3 0 16777215 - 256 0 0 0 0
```

**Comment by erstec** [comment]
> roger @erstec:
> 
> ```
> # status
> System Uptime: 13 seconds
> Current Time: 2041-06-28T01:04:00.000+00:00
> Voltage: 0.00V (1S battery - NOT PRESENT)
> CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
> STM32 system clocks:
>   SYSCLK = 216 MHz
>   HCLK   = 216 MHz
>   PCLK1  = 54 MHz
>   PCLK2  = 108 MHz
> Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE, IMU2=NONE
> Stack size: 6144, Stack address: 0x20010000, Heap available: 2028
> I2C Errors: 285, config size: 8830, max available config: 16384
> ADC channel usage:
>    BATTERY : configured = ADC 1, used = ADC 1
>       RSSI : configured = ADC 3, used = none
>    CURRENT : configured = ADC 2, used = ADC 2
>   AIRSPEED : configured = none, used = none
> System load: 6, cycle time: 1014, PID rate: 986, RX rate: 49, System rate: 10
> Arming disabled flags: ACC HWFAIL RX CLI
> VTX: not detected
> SPI FLASH Status: 3 0 16777215 - 256 0 0 0 0
> ```

Thank you!

Here is next one. Do the same if you can.

[inav_4.1.0_TMOTORF7V2.hex.zip](https://github.com/iNavFlight/inav/files/8451920/inav_4.1.0_TMOTORF7V2.hex.zip)

**Comment by FPVMartin** [comment]
I don't know how to open this file. 😬

**Comment by erstec** [comment]
> I don't know how to open this file. 😬

You don't need to open it, just run INAV configurator, go to Firmware Flasher tab (don't press Connect after start) and then press Load Firmware [Local] instead of you doing [Online] normally, select provided HEX (unzip it of course before) and then Flash Firmware. Simple :)

**Comment by FPVMartin** [comment]
here you go

status
System Uptime: 14 seconds
Current Time: 2041-06-28T02:04:00.000+01:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, RANGEFINDER=MSP, OPFLOW=MSP
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=UNAVAILABLE, RANGEFINDER=FAILING, OPFLOW=FAILING, GPS=NONE, IMU2=NONE
Stack size: 6144, Stack address: 0x20010000, Heap available: 1924
I2C Errors: 65, config size: 8830, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = none, used = none
System load: 10, cycle time: 505, PID rate: 1980, RX rate: 49, System rate: 9
Arming disabled flags: NAV HWFAIL RX CLI
VTX: not detected
SPI FLASH Status: 3 0 0 16777215 - 1 1 2 - 256 0 0 0 0

#

**Comment by erstec** [comment]
Okay, it is fixed and tested.

For those who need 4.1.0 version with fix -  HEX attached.
[inav_4.1.0_TMOTORF7V2.hex.zip](https://github.com/iNavFlight/inav/files/8459626/inav_4.1.0_TMOTORF7V2.hex.zip)

PR will follow

**Comment by samsab1** [comment]
hello
with __INAV 911, this FC seems to be in trouble with  I2C (with last firmware) : I2C error number rise rapidly, magnetometer doesn't work properly. does anyone got a solution?
best regards
