### ISSUE TITLE
iNav not arming but it doesn't give the cause

### ISSUE THREAD

**Issue by francis916** [iNavFlight/inav#7971]
## Current Behavior

iNav 4.1 on Matek F411-WSE won't arm without giving the reason.

# status
System Uptime: 337 seconds
Current Time: 2022-04-16T13:19:53.796+00:00
Voltage: 10.92V (3S battery - OK)
CPU Clock=96MHz, GYRO=MPU6000, ACC=MPU6000, BARO=SPL06
STM32 system clocks:
  SYSCLK = 96 MHz
  HCLK   = 96 MHz
  PCLK1  = 48 MHz
  PCLK2  = 96 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK, IMU2=NONE
Stack size: 6144, Stack address: 0x20020000, Heap available: 1728
I2C Errors: 0, config size: 8808, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = ADC 2
  AIRSPEED : configured = ADC 4, used = none
System load: 15, cycle time: 1027, PID rate: 973, RX rate: 90, System rate: 9
Arming disabled flags: CLI
VTX: band: R, chan: 5, power: 1 (25 mW), freq: 5806 MHz

## Steps to Reproduce

1. Install iNave 4.1 on Matek F411-WSE
2. Connect GPS, Spektrum SPM4650
3. Turn ARM switch on after GPS fixing

## Expected behavior
 FC armed.

## Suggested solution(s)
 Not known. 

## Additional context

Hi. I setup iNav 4.1 on Matek F411-WSE but it won't arm without giving the reason. 

- I tried it after getting GPS fixing and also tried nav_extra_arming_safety OFF. 

- I noticed that throttle value is 6% when ARM switch is on and lowered it to 0 by trimming at NX8. Still didn't arm. 

- I didn't install the camera because it's meant to be a LOS plane for me but I installed the VTX to see error messages when I couldn't arm it.

- Motor works fine in 'Motors' tab in iNav. ESC calibration was done at the tab - increasing it to 100% before connecting the battery and decreasing it to 0% in a few seconds. 

I think it's a bug because it is not arming giving a reason. I hope it's not a stupid mistake of mine.

Thank you.

--------Components
FC Matek F411-WSE
ESC AtomRC 30A 2~4S BLS ESC
Model AtmoRC Mobula 650mm Delta Wing
RX Spektrum SPM4650
TX Spektrum NX8
GPS Beitian BN-220
VTX Goku VTX625
Cam None

https://user-images.githubusercontent.com/18643755/163711204-5998bf95-3f24-4efa-8f9c-ab20639bbee4.mov

![Prearming checks](https://user-images.githubusercontent.com/18643755/163711352-1af6f948-cfa3-458f-92ad-23e88709fb85.png)
![Calibration](https://user-images.githubusercontent.com/18643755/163711343-b105b2f3-db3f-49dd-88cb-45e8119f7be3.png)
![Modes](https://user-images.githubusercontent.com/18643755/163711347-164b8299-dac3-425a-a961-b7484bd3352b.png)
![Motor 1](https://user-images.githubusercontent.com/18643755/163711350-4cf09ef3-67b0-4812-9964-13fb792f5426.png)
![Motor 2](https://user-images.githubusercontent.com/18643755/163711351-e80fe21d-1bb5-46ad-90f5-74b9baf84b21.png)
![Receiver 1](https://user-images.githubusercontent.com/18643755/163711353-c247f3c1-d6b8-4100-8c67-aef95680d881.png)
![Receiver 2](https://user-images.githubusercontent.com/18643755/163711355-00959df0-d3ca-4771-963e-fd48071ef32c.png)

![IMG_1639](https://user-images.githubusercontent.com/18643755/163711370-f17ed1ee-4510-4571-bdeb-f8c545d491aa.JPG)
![Screen Shot 2022-04-17 at 18 33 08](https://user-images.githubusercontent.com/18643755/163711373-66b5e50a-b7ce-490f-9610-5d05c45bf57a.png)
![Screen Shot 2022-04-17 at 18 34 02](https://user-images.githubusercontent.com/18643755/163711375-db68ff68-b9f1-418d-aef7-c89a70f7f003.png)
![Screen Shot 2022-04-17 at 18 34 16](https://user-images.githubusercontent.com/18643755/163711376-fc451e42-cdf5-4f60-a8df-723112eeda11.png)
![Screen Shot 2022-04-17 at 18 34 24](https://user-images.githubusercontent.com/18643755/163711378-53126a35-0d1c-4e3b-b5d8-8a754d3b7aa9.png)
![Screen Shot 2022-04-17 at 18 34 31](https://user-images.githubusercontent.com/18643755/163711381-72ba556c-6b85-4678-9696-c06b9efecf11.png)
![Screen Shot 2022-04-17 at 18 34 44](https://user-images.githubusercontent.com/18643755/163711383-c6e408e9-4315-4e7d-8c4c-6dcff503fecf.png)
![Screen Shot 2022-04-17 at 18 35 13](https://user-images.githubusercontent.com/18643755/163711384-dbe3165b-23a1-4c55-9c14-e4d0197f6062.png)
![Screen Shot 2022-04-17 at 18 35 20](https://user-images.githubusercontent.com/18643755/163711385-f05a8f26-7769-402b-832c-45ece9c3e804.png)
![Screen Shot 2022-04-17 at 18 37 23](https://user-images.githubusercontent.com/18643755/163711386-7ddaa521-2989-4905-92c9-4071c5efe40b.png)

https://pastebin.com/aXq4334S
---

- FC Board name and vendor: Matek F411-WSE
- INAV version string:# INAV/MATEKF411SE 4.1.0 Feb 11 2022 / 10:58:30 (611d26f4)
# GCC-10.2.1 20201103 (release)

**Comment by francis916** [comment]
I added a capacitor to the FC, soldered at the 2nd motor tab. Could it be the cause by any chance? Thanks.

**Comment by Jetrell** [comment]
As the OSD shows, its not seeing low throttle.
You don't want to touch the radio trims. Try setting the idle throttle to 0%... Idle is for multi-rotor use.
Also try adjusting the `min_check`, possibly lower.

**Comment by francis916** [comment]
> As the OSD messages show, its not seeing low throttle.
> You don't want to touch the radio trims. Try setting the _Motor idle power_ to 0%... Idle is for multi-rotor use.
> Also try adjusting the `min_check`, possibly lower.

Thanks! Will try.

**Comment by francis916** [comment]
Solved! I tried rxrange, Motor idle power to 0%. Thank you!

**Comment by Jetrell** [comment]
@francis916 That's good to hear. Please close this help request now.  Thanks
