### ISSUE TITLE
baro and altitude strange wrong 

### ISSUE THREAD

**Issue by lzkk4** [iNavFlight/inav#7975]
hey guys,sorry for may poor language.I made a flight control  imitating MATEKf411-wing.everything going well on betaflight,but,on inav,the barometer and altitude went wrong . 

## Steps to Reproduce

1.i use bmp280 barometer,the same problem when i change one,but ok with betaflight.

2.In configurator sensors tab,the value "baro" accurately is altitude ,when use finger press the barometer,this value reduce.
I set  a constant in the struct sensors/barometer/ baro.baroalti like 999,the configurator show this constant on "baro"

3.the value "alt"is influenced by accelerator z axis，when put the flight control upside ,alt grows slowly,when the reverse side，reduce.when i choose none accelerator,the alt keep zero.

![QQ截图20220420222855](https://user-images.githubusercontent.com/67060386/164260202-97e416ee-0853-4554-aa7a-e7cb7240c4d7.png)

## Suggested solution(s)
sorry i am not good at programming,and don't know how to debug.

---
# version
INAV/MATEKF411 4.1.0 Feb 11 2022 / 10:55:39 (611d26f4)
GCC-10.2.1 20201103 (release)

**Comment by lzkk4** [comment]
maybe you could tell me how inav get altitude? from bmp280's register in barometer_bmp280.c,after flitering we get baro.baropresure and baro.baroalt,and then? where is the altitude been assigned?

**Comment by erstec** [comment]
@lzkk4 if you asking about Altitude shown in Configurator it is obtained via:
https://github.com/iNavFlight/inav/blob/2f2719c31363bc956ae6f0fadcd2251eff832c95/src/main/fc/fc_msp.c#L609

`baro.BaroAlt` itself is assigned here:
https://github.com/iNavFlight/inav/blob/2f2719c31363bc956ae6f0fadcd2251eff832c95/src/main/sensors/barometer.c#L377

All baro filterings, zero calibration and etc are in: https://github.com/iNavFlight/inav/blob/2f2719c31363bc956ae6f0fadcd2251eff832c95/src/main/sensors/barometer.c

**Comment by lzkk4** [comment]
@erstec thank you very much . I set a constant 999 replace baroGetLatestAltitude in fc_msp.c, but it show in “Baro” .
![IMG_20220421_203247](https://user-images.githubusercontent.com/67060386/164460331-f16f9f6f-7afe-4685-aa0d-f570e5eb4708.jpg)

   And “Alt” still just influenced by accelerator.  I am confused about where “Alt”come from?

**Comment by erstec** [comment]
@lzkk4 
Your question is "From where Configurator takes Altitude on Sesnors tab".
Why not to look at Configurator code? :)

https://github.com/iNavFlight/inav-configurator/blob/aa21987b2565e9cbc184da40eb211ac81ea8c378/js/msp/MSPHelper.js#L181
is parsing

https://github.com/iNavFlight/inav-configurator/blob/aa21987b2565e9cbc184da40eb211ac81ea8c378/tabs/sensors.js#L441-454
is displaying and exactly
https://github.com/iNavFlight/inav-configurator/blob/aa21987b2565e9cbc184da40eb211ac81ea8c378/tabs/sensors.js#L548-554

FW side is known by you already

**Comment by lzkk4** [comment]
@erstec wait! you mean in Configurator sensors tab, "Alt" means estimated altitude from accelerometer,and "Baro" means baroaltitude from barometer instead of pressure? oh my god,it means that my flight-controler has no problem at all? oh,this problem confused me for a month,so the real problem come from bad accelerometer's fluctuation. Anyhow,thankyou a lot for answer my confusion.
