### ISSUE TITLE
Mixer speed does not work with Logical Condition

### ISSUE THREAD

**Issue by StuweFPV** [iNavFlight/inav#7987]
## Current Behavior
When creating a mixer that is active via Logical Condition, the Speed entry is completely ignored. After a reboot or fresh start, the slowing down of the Servos works ONCE when enabling. After that, the speed value is ignored and the servos move as fast as they can. If Active is set to "always" it works just fine but this is not always possible like in my case, when i tried to mix crow flaps with a switch. My result now is (see pic below) that the flaps move slowly, but the ailerons and elevator move as fast as they can.

## Steps to Reproduce
1. Create any mixer i.e. Flaperons and set any value >0 in Speed
2. Leave "Active" on "always"
3. Test - It should work just fine
4. Now create a Logical Condition like "Switch Nr1 high"
5. In Mixer set the Flaperons "Active" on "LC1
6. Test - you'll see that any LC pending mixer ignores the speed

## Expected behavior
Expect that the speed value is used when a mixer is conditioned on a LC all the time

## Suggested solution(s)
Fix it if possible

- Matek F405-Wing
- INAV 4.1.0

Pic: red - speed is ignored / green - speed works

![LC crow flaps](https://user-images.githubusercontent.com/61394342/164998820-c50ca9d2-c882-4b0c-a9c2-ff172430b338.jpg)

**Comment by DzikuVx** [comment]
Correct, this is expected behavior.
If you want you can implement ramp-up with LC, pass to GVAR and assign GVAR to a servo input.
LC's are ON/OFF in this context
