### ISSUE TITLE
Poshold problem

### ISSUE THREAD

**Issue by muhanGit** [iNavFlight/inav#7996]
Hello!!! I have Inav4.1 controller OmniF4V3. When I turn on NavPoshold quadcopter starts behaving strangely XY. It doesn't always show up. Compass calibrated. 
![image](https://user-images.githubusercontent.com/76404482/165705989-b8b4ff4b-180f-4c55-94be-96fbef9a1842.png)

Don't know the reason? Thank you!!!

**Comment by DzikuVx** [comment]
https://youtu.be/FlEm0-pXNf0
