### ISSUE TITLE
Have a graphical map data cache in Mission Planner.

### ISSUE THREAD

**Issue by MortyFleem** [iNavFlight/inav#7998]
## Current Behavior
iNav Mission Planner seemingly has no map cache, so when I open Mission Planner out in the field, on my laptop (with limited or no phone signal to provide a Wi-Fi hotspot) - all I get is a blank screen where the map once was thus cannot alter my waypoints.

## Desired Behavior
Have at least a last-used map zoom level in a cache.

**Comment by DzikuVx** [comment]
See here https://github.com/iNavFlight/inav-configurator#how-to-setup-a-mapproxy-server-for-offline-caching-and-mission-planning
