### ISSUE TITLE
INAV 4.1.0 RTH shoots up and falls down

### ISSUE THREAD

**Issue by akurekin** [iNavFlight/inav#8017]
My hardware: MATEK 405SE control board.

Please help!

## Current Behavior
Hi, I experience a very wrong behaviour of INAV in RTH mode. 
When RTH mode switches ON the copter shoots up at full power to the RTH height f 30 meters, then stops and starts returning home. At home position it starts the descent down at high speed to the 10 meter height (the hover height), goes past this height for a couple of meters and then climbs up at full power again and then descends down. I nearly crashed my drone at these manoeuvrers. What is going on?  Is INAV 4.1.0 really so bad?

In POS.HOLD the drone is stable and holds the height. It climbs up at proper speed, no complains, but it goes down too fast.

# version
# INAV/MATEKF405SE 4.1.0 Feb 11 2022 / 10:52:32 (611d26f4)
# GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
Blackbox log required, in the mean time, watch this: https://www.youtube.com/watch?v=aE5oVbBtlig

**Comment by akurekin** [comment]
Thanks for the video with explanation. It looks like I could, at least partly, solve the problem by:
- downgrading INAV to v3.0.1
- increasing the I2C clock rate and also the board clock rate to max values.
- shielding the barometer with foam

**Comment by akurekin** [comment]
I'll bring the logs from my next flight

**Comment by DzikuVx** [comment]
* 4.1 and 3.0.1 have the same RTH procedure, so I'm not sure what downgrade would change
* I2C clock would change nothing
* foam on baro might help

**Comment by akurekin** [comment]
HI, the log file enclosed.  I moved to INAV v3.0.1 but it did not help to solve the problem
As the issue has not been close, may I ask to reopen the issue?
Many thanks.

[]([LOG00053.TXT](https://github.com/iNavFlight/inav/files/8695535/LOG00053.TXT))

**Comment by akurekin** [comment]
[LOG00053.TXT](https://github.com/iNavFlight/inav/files/8695548/LOG00053.TXT)

**Comment by akurekin** [comment]
I tried to add foam to the barometer but it did not help. 
A couple of times I succeeded to start RTH but was not successful next time.
The success in RTH was random.

**Comment by akurekin** [comment]
I also tried to put a controller on foam pads to dampen the vibrations from motors but it did not help. I am using the motors from Mavic with folding blades and when the motors start they may vibrate until the blades will unfold completely.
