### ISSUE TITLE
baro mode has gone???

### ISSUE THREAD

**Issue by jiekchenid** [iNavFlight/inav#802]
baro mode 被 替代成了nave althold了嘛？？？现在定高模式需要GPS来执行了，BARO不在起作用了嘛。。。有没有纯靠 BARO起作用的模式

**Comment by DzikuVx** [comment]
There is only ALTHOLD mode and this is per design.

**Comment by oleost** [comment]
English?

And baro is replaced with althold mode, which also holds altitude but uses data from the inertial estimator instead of only relying on barometer. Its should work without GPS.

**Comment by jiekchenid** [comment]
@oleost   but  the INAV 1.3    haven't    baro mode   only have nav althold   need gps

**Comment by digitalentity** [comment]
@jiekchenid NAV ALTHOLD doesn't need GPS, only barometer sensor.

**Comment by jiekchenid** [comment]
![qq 20161116230128](https://cloud.githubusercontent.com/assets/460270/20352144/3d3b2180-ac51-11e6-904e-f7d2e62e054c.png)
and  i can't  turn on  nav althold mode   i don't know why

i do calibrate the accelerometer.  but cannot turn on nav althold mode  now ican't armed even naze32 rev5.......

**Comment by oleost** [comment]
Probably because you have failed to calibrate the accelerometer. Please take you time and read trough the wiki. 

iNav is not cleanflight and there are some difference. You need to read the wiki.

**Comment by jiekchenid** [comment]
@oleost   thanks  iread wiki now its working  but another problems  why  navposhold  mode   can not armed???????

为什么设置了nav poshold   电机就无法解锁了，，该模式下也无法激活？

**Comment by juzhen698** [comment]
nav poshold 包括其他用到GPS的模式都要在能收到卫星，而且能定位后才能解锁。

**Comment by Leen-35** [comment]
你的解锁了吗？我的也解不了锁，六面校准，油门行程最大最下也设置了也行。
