### ISSUE TITLE
Add airspeed units to telemetry documentation

### ISSUE THREAD

**Issue by tmcadam** [iNavFlight/inav#8031]
I have a pitot tube airspeed sensor (MATEK DIGITAL AIRSPEED SENSOR ASPD-4525) connected to Inav. The sensor is reading and outputting S.Port telemetry which I am using on the TX16S in the Inav telemetry widget. The TX16S thinks the telemetry  unit is in kts, but from the code I think it might be in m/s (as the pressure reading is in Pascals). 

Would it be possible to clarify this unit in the wiki/docs for S.Port Telemetry?

**Comment by MrD-RC** [comment]
It is sent as knots * 10.

**Comment by tmcadam** [comment]
Many thanks
