### ISSUE TITLE
Ailerons Move on their own with throttle input (fixed wing)

### ISSUE THREAD

**Issue by kaladek** [iNavFlight/inav#8036]
****

## Current Behavior
odd behavior: went flying today with my wing and the latest inav. After 30 minutes of flying, my plane started to want to turn right all the time so I landed it (barely-- got difficult since it wanted to keep turning to the right) and noticed that the right aileron was raised and not returning to level no matter what I did (even those the plane was level, the aileron would stay raised). Putting it into acro mode fixed it. On the ground testing it, if I raised the throttle even a bit, the aileron would move to the up position by itself without any input from the controller or any movement from the plane.  I have checked my channels and my throttle only moves my throttle and there is no other mixes. 

What gives?? Why wont the ailerons move back to center in the air with no stick input when the plane is otherwise flying level and straight? See video

[https://youtu.be/PRjjnfEmxvM]

On the blackbox log, the roll PID keeps going up quickly while the throttle is up. I think this is the issue but I cannot find the cause.

[LOG00001.TXT](https://github.com/iNavFlight/inav/files/8693729/LOG00001.TXT)

## Steps to Reproduce

1. put plane into angle or hor mode
2. put throttle up
3. ailerons move up by themselves without any input for roll or pitch and with the plane being perfectly level and still.
4. turn throttle to 0% and the ailerons go back to neutral.

## Expected behavior
there should be no aileron movement only when throttle is applied. 

## Suggested solution(s)
there should be no aileron movement only when throttle is applied. 

## Additional context
only happens in angle or horizon mode.
https://pastebin.com/ZNTKpVmC
---

# version
# INAV/MATEKF765SE 4.1.0 Feb 11 2022 / 11:13:21 (611d26f4)
# GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/966811/169954468-e2b65f22-3bbc-4cec-b75b-08430daea498.png">
There is no bug, everything is like it should be. You have horizon mode on and a small attitude error from FC not being level to the ground. Everyime you apply the throttle INAV tries to correct the error by moving the control surfaces. As the control loop is open (it's not flying but lies flat on the ground), it fails to do so, error accumulates etc
