### ISSUE TITLE
Kakute F7 gyro problem

### ISSUE THREAD

**Issue by oldrootbeer** [iNavFlight/inav#8042]
Hi there.
I've tried 4.0 and 4.1 for a kakute f7. The sensors tab show the gyro is ok. But when I arm, there is no attitude control. It flys away.
3.0.2 I think was ok (custom hdzero build). Betaflight is ok too.

**Comment by DzikuVx** [comment]
for the record, what was it @oldrootbeer ?

**Comment by oldrootbeer** [comment]
@DzikuVx ah I'm used to betaflight so the airmode threshold caught me out whilst performing a hand gyro check on arm.

**Comment by oldrootbeer** [comment]
Umm. I use props out. Forgot to set in cli. Bf is easier
