### ISSUE TITLE
RTH unexpected behaviour

### ISSUE THREAD

**Issue by akurekin** [iNavFlight/inav#8046]
## Current Behavior

Dangerous behaviour of quad when switching on RTH mode. I was flying at slow speed and Angle mode was activated. When I activated RTH mode my quad started turning back to me, but it made a sharp move and a turning angle became close to 180 degrees. The quad actually turned upside down and then recovered. This accident happened multiple times at random. I enclosed a LOG file. In this record the accident  happened at time 4.31.171

## Steps to Reproduce

1. Fly a drone and activate Angle mode. Move to the distance far enough to trigger failsafe and wait for RTH mode be activated automatically. 
2. Observe the drone turning home
3. Save your drone from falling upside down by using control sticks

## Expected behavior

After switching to RTH mode the drone should smoothly start moving home

## Suggested solution(s)

Testing if Ardupilot has the same behaviour

- FC Board name and vendor: MATEK405SE
- INAV version string: 3.0.1
- 
[LOG00091.TXT](https://github.com/iNavFlight/inav/files/8751755/LOG00091.TXT)

**Comment by breadoven** [comment]
Bit strange, the normal RTH worked fine but the Failsafe RTH sent full Pitch and Roll commands initially for some reason. Was this switched Failsafe mode or a real Failsafe due to signal loss ? How did you recover it with the sticks if it was in Failsafe ?

**Comment by akurekin** [comment]
It was a real railsafe, you can check RSSI graph, RSSI=0 for short time interval and after that I could control the drone. However, the same behaviour happened  several times when I activated RTH manually.
