### ISSUE TITLE
naze32 10dof rev5  刷的最新版 太抖了，不如BFCF固件干稳定

### ISSUE THREAD

**Issue by jiekchenid** [iNavFlight/inav#806]
naze32 10dof rev5  INAV1.3       太抖了，不如BF或CF固件稳定

Too shaking, as BF or CF firmware stability

**Comment by digitalentity** [comment]
Tune PIDs and filters.

Consider changing default settings to 

```
set gyro_soft_lpf_hz = 90
set dterm_lpf_hz = 42
set gyro_lpf = 188HZ
```

Also, please use RCGroups thread for support - what you describe is NOT a firmware issue.
