### ISSUE TITLE
hallo habe einen neuen mamba f722 mk03 und er erkennt das Gyro nicht ( in betafliht keine Probleme) und bei meine allten Manba mk3 auch kein Problem.Was Mach Ich Falsch

### ISSUE THREAD

**Issue by Mulli311** [iNavFlight/inav#8060]
* Habe einen neuen mamba f722 mk03 und er erkennt das Gyro nicht ( in betafliht keine Probleme) und bei meine allten Manba mk3 auch kein Problem.Was Mach Ich Falsch

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
That will be supported in INAV 5.0
