### ISSUE TITLE
Mamba DJI F722 MK2 not working gyro, accel and more.

### ISSUE THREAD

**Issue by Akvavno** [iNavFlight/inav#8063]
Hi,
trying to flash FC with iNAV 4.1.0 mamba f722 i2c firmware. Gyro, accel, uarts, gps not working. Only onboard baro and i2c external mag present.
On betaflight 4.2.11 mamba i2c all  work. inav supporting this FC?

**Comment by DzikuVx** [comment]
This will be fixed in INAV 5

**Comment by Akvavno** [comment]
Thanks, 
flash iNAV 5, all sensors work.
