### ISSUE TITLE
Rx Serial not being set on Omnibus F4 FC

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav#8065]
After flashing an Omnibus F4 board and loading a Diff `receiver_type `remains set at None in spite of `serialrx_provider `being correctly set as CRSF. On power up there is no RC link available.

The Diff used was saved after previously setting `receiver_type `to SERIAL but doesn't include the `receiver_type `setting because it's clearly seen as a default when set to SERIAL and in fact this is correct for the Omnibus F4 board since the target.h file includes `DEFAULT_RX_TYPE         RX_TYPE_SERIAL`. The Diff does include the `serialrx_provider `setting however, set to CRSF.

This seems specific to the Omnibus F4 board. Other boards used are also set to CRSF and don't include the `receiver_type `setting in the Diff but Serial gets set correctly by default so not sure what the issue is, probably the firmware rather than Configurator.

INAV version 5.0 current master.

**Comment by DzikuVx** [comment]
Let me check that later. It seems that default does not point to serial in case of this board
