### ISSUE TITLE
INAV 5.0 target hex files for matek H743 and FF F35 

### ISSUE THREAD

**Issue by 66nola66** [iNavFlight/inav#8067]
Maybe I am missing it???? Where are the 5.0 updated hex files??? I downloaded the configurator but when I go to flash the FC I only see the 4.1 hex file. I need matek h743 and the FF F35.

**Comment by Jetrell** [comment]
![Capture](https://user-images.githubusercontent.com/47995726/170924731-b550a9fa-06c1-4049-94e4-8df1e42380ed.JPG)

**Comment by 66nola66** [comment]
THANK YOU!!! I apologize didnt remember that they would be in the unstable revisions. LOVE 5.0!!!
    On Monday, May 30, 2022, 05:01:39 AM CDT, Paweł Spychalski ***@***.***> wrote:  
 
 


Closed #8067 as completed.
