### ISSUE TITLE
Unstable braking (yaw spin) after cruising in POSHOLD (ATTI) at over 110km/h 

### ISSUE THREAD

**Issue by andrefreitas97** [iNavFlight/inav#8068]
## Current Behavior

Last week I decided to test the max speed of my multicopter while cruising in POSHOLD (ATTI) trying different max_angle settings. When I tested over 35º of angle max I was achieving over 110kmh in straigh line but then a problem appeared. I noticed that sometimes at this speed if I released the pitch stick the drone would not brake smoothly but instead do what seemed to be an uncontroled yaw spin (~180º) and then stabilize.

## Expected behavior

I would expect the drone to brake "smoothly", keeping its current heading without the unexpected yaw spin.

## Suggested solution(s)

I suspect the culprit may be the PID settings which are the default but may be too low for my build: 5 inch drone with ~850g. I tried increasing P values in all axis but with no success.
This said, I am not sure if this is the true source of the problem and would like to know if anyone already faced this problem and how to solve it.

Later, if possible I will try to upload a video of this flight.

---

- FC Board name: KAKUTEF7
- INAV version string: 4.1

**Comment by Jetrell** [comment]
When increasing the `nav_mc_bank_angle` above default. The possibility of magnetometer interference becomes more likely.
As the quad tilts forward in flight at higher angles, the compass can experience greater magnetic deviation from the motors. Which did not show up when level, or at lower bank angles.

The fact it stabilized, showed it had enough Yaw authority and gain on Proportional and Integral.

I've entered **Poshold** from **Acro**, at 130km/h with a 3 inch quad. That shows no bad tendencies. 
But its `nav_mc_bank_angle` is only set to 26°. 

`nav_manual_speed` only supports a maximum passive velocity of 72km/h, when under pilot input in Poshold. The code was never rated for 110km/h. But that doesn't mean it won't make it to that speed with enough bank angle.
