### ISSUE TITLE
iNav V5 RC2 - Broken MSP support for barometer

### ISSUE THREAD

**Issue by robustini** [iNavFlight/inav#8080]
## Current Behavior

Already with iNav V4.1 the support for MSP peripherals had some known problems, with the V5 RC2 the Mateksys GPS M8Q-CAN the barometer is not recognized.
While with V4.1 it works with V5 and with the same parameters it doesn't work.
Tested on ZEEZF7 V1.2 on UART2. 3 and 4.

## Steps to Reproduce

1. Configure the device correctly in MSP
2. Look at the screen and it will give you the barometer in red.
3. Try with iNav V4.1 and the barometer will be recognized

## Suggested solution(s)

@digitalentity since you did the first implementation about MSP support please found the issue and fix the code, thanks!

## Additional context

![immagine](https://user-images.githubusercontent.com/3864712/171868093-96b75a1e-25d7-44fd-ab27-6408e106540a.png)

---

INAV/ZEEZF7 5.0.0 Jun  2 2022 / 07:57:45 (3914c4f0)
GCC-10.2.1 20201103 (release)

**Comment by JulioCesarMatias** [comment]
Hi Marco, I'm a big fan of your work at ArduPilot. About this problem, I believe I found where the error is occurring, but to be sure of that, I need you to select the Barometer "FAKE" instead of "MSP".

**Comment by JulioCesarMatias** [comment]
You can get the corrected build for your flight controller here >> https://github.com/iNavFlight/inav/actions/runs/2437143945

You can select "MSP" type Barometer and everything will work normally

**Comment by robustini** [comment]
Hi @JulioCesarMatias, I'am honored to have you as a fan!
I looked at the code too but I couldn't find the problem, apparently there was a baro missing in the list, great job, thanks!!!

**Comment by robustini** [comment]
Closed with https://github.com/iNavFlight/inav/issues/7576, work fine so please merge, thanks!

**Comment by robustini** [comment]
@DzikuVx  there is a problem with the configurator, irrelevant but there is.
In CLI the gps is set correctly in MSP, but then marks it as DJI Naza.

![immagine](https://user-images.githubusercontent.com/3864712/178109137-fe35866d-127e-43bb-a15a-b36e08471429.png)

**Comment by JulioCesarMatias** [comment]
> @DzikuVx there is a problem with the configurator, irrelevant but there is. In CLI the gps is set correctly in MSP, but then marks it as DJI Naza.
> 
> ![immagine](https://user-images.githubusercontent.com/3864712/178109137-fe35866d-127e-43bb-a15a-b36e08471429.png)

this is just a mismatch... Old Configurator vs iNav branch master for FC. Make this checkout with iNav 6.0 (Master version).

.Hex file >> https://github.com/iNavFlight/inav/actions/runs/2641160041

Configurator >> http://seyrsnys.myzen.co.uk/inav-configurator-next/
