### ISSUE TITLE
ZEEZ F7, TIM_USE_MC_SERVO, ON INAV POSSIBLE

### ISSUE THREAD

**Issue by fxbd1** [iNavFlight/inav#8103]
I am bulding a clective piched MC.
The fc is not communicating with the servos correctly and i am struggeling to finde the reason why

i know that i need a 50hz pwm signal and i thought that with the ordenairy inav settings it will be done but no.
i think maybe zeez f7 is not suppoting TIM_USE_MC_SERVO 
am i right?
should i go with a different board or can i do a workaround?
thanks
Felix

**Comment by DzikuVx** [comment]
this will not work on this board
