### ISSUE TITLE
5.0-RC3 forces motor pwm to 500Hz

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav#8113]
## Current Behavior
Flashing 5.0-RC3, using the iNav Configurator 5.0-RC2.
`set motor_pwm_protocol = STANDARD` forces `set motor_pwm_rate = 500`
It does not matter if you use the GUI or set it using the CLI.

The drop down menu shows 50, 400, 500 Hz as an option, but even if you select 400Hz and click "save and reboot" it comes back as 500 Hz.
I'm not sure this is intended.
STANDARD has always been 400 Hz for motor_pwm_rate.

## Steps to Reproduce

1. Flash RC3 with full chip erase
2. Paste in a diff from RC2
3. See the motor pwm rate is changed to 500 Hz automagically
4. Set back to 400 Hz and after "save and reboot" it's back at 500 Hz

## Expected behavior

STANDARD should stick to 400 Hz

## Suggested solution(s)

Ask kindly to fix this
(5.0-RC2 has the correct behavior)

## Additional context

![Outputs](https://user-images.githubusercontent.com/31951195/173227617-980149b2-8de9-420f-a835-80419ed5d084.png)
![drop_down_menu](https://user-images.githubusercontent.com/31951195/173227598-9bbf290e-7f18-48d6-87ff-72452cbf89f5.png)
![motor_pwm_rate](https://user-images.githubusercontent.com/31951195/173227622-e3501b85-3d95-4b3a-aa40-bd44fd89068d.png)

---

```
# version
# INAV/MATEKF405 5.0.0 Jun 10 2022 / 09:11:07 (dfa9f6f6)
# GCC-10.2.1 20201103 (release)
```

- FC Board name and vendor:
- INAV version string: MATEKF405
- Board is [Matek F405-STD](http://www.mateksys.com/?portfolio=f405-std)

**Comment by DzikuVx** [comment]
This is irrelevant in RC3. Motor refresh rate is now fixed to the protocol and the setting `motor_pwm_rate` is not in use anymore.
Final Configurator 5 will remove this field completely
