### ISSUE TITLE
Profile change bug

### ISSUE THREAD

**Issue by hali9** [iNavFlight/inav#812]
How many Profile is in INAV. In cleanflight are 3 profile.
But when I change in inav-configurator to profile 3 then I get profile 1.
In CLI set profile to 2 then I get profile 0.

**Comment by digitalentity** [comment]
Unable to reproduce on INAV 1.4-RC1

**Comment by hali9** [comment]
On INAV 1.4-RC1 still there is a problem.
I use inav_1.4.0_CC3D.hex, maybe target is significant?

**Comment by digitalentity** [comment]
This is a target-specific bug indeed.
We have a flash-size-specific `MAX_PROFILE_COUNT` definition:
```
#if FLASH_SIZE <= 128
#define MAX_PROFILE_COUNT 2
#else
#define MAX_PROFILE_COUNT 3
#endif
```

Not sure why we need this though.

**Comment by digitalentity** [comment]
Looks like it has been recently introduced in https://github.com/iNavFlight/inav/commit/46fee424be7c79fff8427fdd1f42efae71f09624. @martinbudden do you remember why? This doesn't seem to affect binary size (at least not much).
