### ISSUE TITLE
5.0 RC2 ESC telemetry Temp reading not working

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav#8133]
## Current Behavior

![ESC temp](https://user-images.githubusercontent.com/31951195/174430567-7aa29496-7e29-4ded-95d2-f8e9490eeffd.png)
ESC temp reading stays at 0 degrees Celcius

## Steps to Reproduce

1. connect ESC telemetry wire to FC
2. add ESC temp reading to OSD 
3. ESC temp is stuck at 0 degrees Celcius
4. ESC RPM counter works fine (So ESC to FC connection is confirmed to be correct.)

## Expected behavior

ESC temp reading gives correct values on OSD

## Suggested solution(s)

Ask kindly to look into this.

## Additional context

This is a new build, so I have no clue if this ever worked on older iNav releases,
Used components:
- Matek [H743-WING V2](http://www.mateksys.com/?portfolio=h743-wing-v2) flight controller
- Holybro [Tekko32 F4 45A](http://www.holybro.com/product/tekko32-f4-45a-esc/) BLHeli32 ESC
The FC is flashed with iNav 5.0 RC2
The ESC is flashed with BLHeli 32 v32.9 

---

- FC Board name and vendor: MATEK
- INAV version string: 
```
# version
# INAV/MATEKH743 5.0.0 Jun 10 2022 / 09:38:43 (dfa9f6f6)
# GCC-10.2.1 20201103 (release)
```
[diff all](https://pastebin.com/embed_iframe/uvbwwCsR?theme=dark)

**Comment by MrD-RC** [comment]
Working fine on my 5.0 install.
- Matek F405-STD
- iFlight SucceX-E Slick 45A ESC (no idea which version of BLHeli_32)

![image](https://user-images.githubusercontent.com/17590174/174431313-c83f6d40-bc47-40f6-8ee0-e33ee42f1af7.png)

**Comment by erstec** [comment]
Same. Works fine on H743-SLIM + T-motor F55A PRO

**Comment by 0crap** [comment]
Which BLHeli32 version did you use?

**Comment by erstec** [comment]
> Which BLHeli32 version did you use?

32.8 I believe, need to check when will back home after weekend

**Comment by 0crap** [comment]
I flashed the ESC to v32.8 and it gives the same issue, ESC temp stays at 0 degrees C.

**Comment by Mateyhv** [comment]
Matek F405 Wing - v5.0.0 RC3 with Tekko32 F3 35A v32.8 here. Reporting temp and RPM just fine, no difference since 4.1, 4.0, etc.

**Comment by DzikuVx** [comment]
tested with BLHeli 32.9. multiple FCs and INAV 5. All the time wors like expected

**Comment by 0crap** [comment]
> tested with BLHeli 32.9. multiple FCs and INAV 5. All the time wors like expected

It does not work "all the time", that's why I reported it.
Anyway in the link above, to the BLHeli32 Github issue, you can read why this happens.
In short, this case is not iNav related.

Thx to all that replied to this issue.
