### ISSUE TITLE
RUSH BALDE : I HOPE RUSH BLADE FC CAN SUPPORT BY INAV.

### ISSUE THREAD

**Issue by LYCH90** [iNavFlight/inav#8142]

**Comment by LYCH90** [comment]
I HOPE RUSH BLADE FC CAN SUPPORT BY INAV.

**Comment by MrD-RC** [comment]
You need to speak to Rush and show them that their customers want iNav support. This document shows the policy for adding new targets.  

https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
