### ISSUE TITLE
Matek F411-WTE voltage sensor not working

### ISSUE THREAD

**Issue by AndreaB321** [iNavFlight/inav#8143]
****

## Current Behavior
On my Matek F411 WTE, flashed with either 5.0 Rc3 (F411te) or 4.1, the Lipo is plugged but the battery voltage on the configurator shows 0v, Cell count shows 1 and from the CLI:
Voltage: 0.00V (1S battery - NOT PRESENT)

The motor spins up at a limited pace, servos work (5v), camera and vtx (on vbat) are ok.
Telemetry doesn't also report any bat voltage.

Please note I'm not sure whether this is a software or a hardware issue. This FC is quite recent, I don't have another one available nor know anyone else running it.

## Steps to Reproduce
1. get a Matek F411-WTE
2. wire everything as usual
3. plug in the lipo

## Expected behavior
Battery is recognised and correct voltage shown.

## Additional context
CLI Dump:
https://pastebin.com/TprvC8V7

---

- FC Board name and vendor: MATEKF411TE
- INAV version string: 5.0.0 Jun 10 2022 / 09:25:02 (dfa9f6f6)

**Comment by AndreaCCIE** [comment]
![](https://media.discordapp.net/attachments/967468251179270144/988773935455825941/Screenshot_2022-06-21_at_12.52.43.png)

![](https://media.discordapp.net/attachments/967468251179270144/988774074476032050/Screenshot_2022-06-21_at_12.55.03.png)

![](https://media.discordapp.net/attachments/967468251179270144/988774433235808316/Screenshot_2022-06-21_at_12.56.30.png)

https://user-images.githubusercontent.com/48698293/174880981-aac199a4-6c9a-4266-a358-e388c1a34bfd.mov

**Comment by MATEKSYS** [comment]
Be careful with the resistor on the right of solder iron when soldering the Dupont pins
![image](https://user-images.githubusercontent.com/23047106/175188182-99e89aba-d36f-4d5d-8670-c690734c1187.png)

**Comment by Doloki676** [comment]
I have same problem in inav

**Comment by Zuzle** [comment]
I have the same problem. I figured out that on of the resistors on my board is dead. I tried to replace it with a new 1k one. But now the voltage is inaccurate even if I try to adjust the scale. Does anyone know what kind of resistor has to be there?
![Uploading IMG_2162.jpeg…]()

**Comment by MATEKSYS** [comment]
> I have the same problem. I figured out that on of the resistors on my board is dead. I tried to replace it with a new 1k one. But now the voltage is inaccurate even if I try to adjust the scale. Does anyone know what kind of resistor has to be there?
> 
![image](https://github.com/iNavFlight/inav/assets/23047106/ebff904a-39b9-45cd-8341-8347f8ac7274)
