### ISSUE TITLE
H743 targets must use ADC3 for PC2_C / PC3_C  (Fix current measurement wrong on H743 targets)

### ISSUE THREAD

**Issue by hogthrob** [iNavFlight/inav#8146]
## Current Behavior
Current measurement when set to ADC for MAMBAH743 is completely wrong.
Same board with Betaflight shows reasonable current measurements
 
## Steps to Reproduce
1. Flash any release supporting the MAMBAH743 (or any other target using H743 and C03 for current measurement)
2. Set current scale to the recommended value for the board (MAMBAH743: 80)
3. Observe current value with battery connected, it will be wrong and very high. in my case around 84
4. Flash Betaflight
5. Same procedure, see low values (<1A) when idle and going up if motors are spun up.

## Expected behavior
Show correct value.

## Suggested solution(s)
Use ADC3 for all ADC input instead of ADC1 for H743 targets, see datasheet https://www.st.com/resource/en/datasheet/stm32h743vi.pdf page 67 as all 4 analog inputs on the board are availabe on ADC3. 

## Additional context
Implementation in https://github.com/iNavFlight/inav/blob/master/src/main/drivers/adc_stm32h7xx.c uses same ADC for all inputs, but this is not working for the STM32H743, 
---

- FC Board name and vendor: Diatone Mamba H743 MK4
- INAV version string:
INAV/MAMBAH743 5.0.0 Jun 20 2022 / 21:14:33 (6e88012b)
GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
@hogthrob of course you should submit abPR
