### ISSUE TITLE
Inav 5.0 rc3 matek f411wse heading drift 1deg/minute

### ISSUE THREAD

**Issue by d2f2** [iNavFlight/inav#8152]
Matek f411wse 
Inav 5 rc3 vs inav 4.1

## Current Behavior
 setup screen @ inav configurator shows that heading is incrasing about 1 deg per every minute, so also air plane pictogram rotate in the app window. 
No rotation at 4.1 or mayble 1deg per 10 min (May be not present rotation for real). 

## Steps to Reproduce
1. Full chip erase flash inav 5 rc3
2. calibrate acc with 6 steps or paste calibrate vals at cli - doesnt make difference 
3. Save
4. See rotation in setup Windows in configurator app

## Expected behavior
4.1 doesnt have rotation. The same acc vals in cli. 

## Suggested solution(s)
Is this correct behavior? 

## Additional context

---

- FC Board name and vendor: matek f411wse, target matek f411se
- INAV version string: 4.1.0 Feb 11 2022 10:58:30

**Comment by breadoven** [comment]
This has always been there as far back as I can remember. Without a magnetometer there is nothing to provide a reliable heading when the plane is static on the bench so the heading will drift. It's not important so long as it works in flight with a GPS providing heading info.
