### ISSUE TITLE
OmniNXT, in position hold the copter runs away, while compass shows right directions

### ISSUE THREAD

**Issue by Chrisi2009** [iNavFlight/inav#8154]
At first, my build hardware:

Quadcopter with 3 cells LiPo
FC OmniNXT F7
GPS BN-880
SW: INAV4.1

This things working fine...
Flight in angle mode.
The copter is very stable in the air.
After much setups, the compass itself works fine. On the OSD it shwos the right direction in degrees/north/east and so on. Also the OSD shows the staring point and its way to home. On Inav the google map also shows everything wright.

But here are my 2 issues:

1.)
If i switch on position hold, the copter drifts straightly away in random direction.
It never hold its position for a piece of a second.

2.)
If i switch on RTH, the copter lifts up to its setup altitude (in test 5m), turns to north (correctly i think) and then he fly away in 90 degrees CCW (mostly west) and fly away.

What could be wrong ? Why does it fly back in wrong direction, although the OSD shows correct arrow ?

After reading so much in google, my compass is installed correctly, it shows the right degrees and direction to home and so on. (north=0°, east=90°...)

Is there anything i didnt see ?

Chris

**Comment by Jetrell** [comment]
Hi Chris.. Many times the compass can seem correct when level. But in reality it isn't. 
If it was calibrated with localized magnetic interference. Mostly from the quad itself. This can lead to the effect you are experiencing. 
The GPS course can also give the impression that things are okay, with the home arrow pointing in the correct direction.

Try to calibrate it again... Once the calibration is complete, its important that you compare the motion of the quad, to the virtual rendered image on the Configurator Setup page.. Make sure the quad moves the same as that image, on all axis's...When its moving sideways, nose down, nose up etc....  If it doesn't move exactly the same, then its experiencing magnetometer interference.
