### ISSUE TITLE
motor_pwm_rate reverts to 500 after setting to 400

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#8172]
## Steps to Reproduce

1. iNav 5.0.0 final, flashed (in my case over 4.1.0)
2. I install my "diff all" file from the previous 4.1.0
3. I save the current 5.0.0 diff all and run a Winmerge diff between the two files
4. I notice that motor_pwm_rate now defaults to 16000, but was previously 400
5. I consult the docs which say that this is only for brushed motors, I am using brushless so it probably wont affect anything, but still want to keep things the same as they were.

6. From the CLI I run
# set motor_pwm_rate = 400
motor_pwm_rate set to 400

7. # save

8. After reboot, from the CLI I run
# get motor_pwm_rate
motor_pwm_rate = 500
Allowed range: 50 - 32000

value which has persisted is not what was set.

## Expected behavior
When I set motor_pwm_rate to 400, it should persist as 400 after I save and reboot and not change to 500., 
400 is within the valid range of 50 - 32000

## Suggested solution(s)
Allow the value set in the CLI to persist as it was set, when saved.

## Additional context
https://pastebin.com/AbBzGsEH

# version
# INAV/MATEKH743 5.0.0 Jun 20 2022 / 11:25:06 (d2adf35c)
# GCC-10.2.1 20201103 (release)

**Comment by 0crap** [comment]
https://github.com/iNavFlight/inav/issues/8113
