### ISSUE TITLE
Caddx on F411 Wing INAV

### ISSUE THREAD

**Issue by Signellox** [iNavFlight/inav#8179]
- OSD on F411 for DJI Googles did not work
- INAV and Configurator 4.1.0
- Port  Softserials :  Peripherals set to DJI FPV VTX 115200
- CLI Status VTX not detected
- White Caddx RX is on Softserials 1 (ST1)
- Grey on LED (but not defined because define did not work)

![image](https://user-images.githubusercontent.com/35845416/176508137-9f8851bb-6d2f-4da6-9681-c30f0ae65c27.png)
![image](https://user-images.githubusercontent.com/35845416/176508223-3f42136c-91b0-4bb5-8123-bda32f8f9c4b.png)

**Comment by DzikuVx** [comment]
DJI FPV will not work on SoftSerial. You need one of hardware serials for this port speed
