### ISSUE TITLE
CRAFT_NAME still displaying when using DJI OSD elements

### ISSUE THREAD

**Issue by EjectSteve** [iNavFlight/inav#8188]
## Steps to Reproduce

1. Enable DJI elements for warnings for  CRAFT_NAME field
2.Warnings and other elements display properly but they cycle through and CRAFT_NAME appears among the items displayed
3.  CRAFT_NAME displays even if you have entered something else in craftname field like MYQUAD
4.

## Expected behavior
If nothing is entered in craft name field, CRAFT_NAME should not display when showing DJI osd elments.  If a CRAFT_NAME field is entered, it should flash among the other DJI elements displayed
## Additional context

https://pastebin.com/0SNhxBJz

---
[
# version
# INAV/HGLRCF722 5.0.0 Jun 20 2022 / 10:27:31 (d2adf35c)
# GCC-10.2.1 20201103 (release

- FC Board name and vendor: HGLRC 722
- INAV version string: INAV/HGLRCF722 5.0.0 Jun 20 2022 / 10:27:31 (d2adf35c)

**Comment by DzikuVx** [comment]
Setup osd from defaults, do not restore previous OSD configuration
