### ISSUE TITLE
naze32 rev5 10dof  posthold modes can't activate

### ISSUE THREAD

**Issue by jiekchenid** [iNavFlight/inav#819]
![inav3 gps](https://cloud.githubusercontent.com/assets/460270/20600597/63a24904-b28f-11e6-8534-cf9185783a02.JPG)

naze32 rev5 10dof  posthold modes can't activate  when i turn on  nav postholds ..gps is ok and armed althold can activate   ,,,,,,,,,,,,only nav postholds can not activate    why??????

**Comment by stronnag** [comment]
Mag not calibrated, probably. See multiple discussions on RCG .
