### ISSUE TITLE
INAV 5: After Landing not able to arm due to "CLI ACTIVE"

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#8194]
## Current Behavior
I was flying my fresh configured INAV 5 Wing yesterday and landed it after 50m (launch aborted- to little throttle). After having the wing at hand again I wanted to ARM and launch it again.

This wasn't possible at that moment as the OSD reported "unable to ARM CLI ACTIVE". I repowered the wing and everything was ok again. 

## Steps to Reproduce
currently I don't know how to reproduce this without just mumbling speculations - 

## Expected behavior
don't block the arming as no USB was connected and CLI wasn't used.

## Suggested solution(s)
ARM :) ... 

## Additional context
Here is a video of it
 
https://user-images.githubusercontent.com/8381714/177255416-e0b77922-10b3-427e-899a-7cb6795b6ff1.mov

---

- FC Board name and vendor: MATEKF405SE
- INAV version string: 5.0.0 (3a379a7)

**Comment by JulioCesarMatias** [comment]
This is quite strange! The flight controller only enters CLI mode when the `#` command via the MSP port. I don't know how this command was interpreted...

**Comment by Pairan** [comment]
The only thing that can comes in mind while hearing MSP is that the ESP32-RADAR was connected to a free UART (MSP). That talks to INAV via MSP ... but we fly this pretty much and it never happened for us! I don't know if that could be the case. But others than that I could not build the bridge to MSP ...

**Comment by stronnag** [comment]
The conditions for entering CLI are:
* There is no pending MSP processing (so it's not part of an MSP payload)
* 100ms elapses since the `#` was received with no other activity on the port.

So it is unlikely that normal MSP processing caused this. Some noisy glitch on the serial connection (cosmic rays, sun-spots etc.) ???
