### ISSUE TITLE
biqua-filter version not arming

### ISSUE THREAD

**Issue by bk79** [iNavFlight/inav#82]
I'm unable to arm via yaw after uploading

**Comment by digitalentity** [comment]
Was unable to confirm the issue. What board and what RX are you using?

**Comment by bk79** [comment]
cc3d rx_ppm

**Comment by stronnag** [comment]
I have no problem stick arming (dodo).

**Comment by digitalentity** [comment]
cc3d + ppm receiver, no problems with arming on biquad latest code. possibly a nav_extra_arming_safety feature doing its job and preventing arming without a GPS lock?

**Comment by bk79** [comment]
yes I don't have any gps lock but i tried even disabling gps which shouldn't trigger it

**Comment by bk79** [comment]
confirmed setting nav_extra_arming_safety= OFF i can arm again
