### ISSUE TITLE
naze32 rev5 10dof  horizon modes can't activate  why?????

### ISSUE THREAD

**Issue by jiekchenid** [iNavFlight/inav#820]
naze32 rev5 10dof  horizon modes can't activate  why?????

**Comment by digitalentity** [comment]
Horizon mode works fine. Please use RCGroups thread for support.

**Comment by oleost** [comment]
Hi.

There is no reason Horizon mode should not active.

Are you sure it's horizon mode you mean, or is it NAV modes?

Additionally information like CLI dump and if it's working in iNav 1.3 or iNav 1.4rc-1 is also key information to give.

Please use regroups for user support, closing this one.  (But read the wiki first ) https://www.rcgroups.com/forums/showthread.php?t=2495732&page=1

Edit: Your fast DE.

**Comment by jiekchenid** [comment]
its work i turn on angle mode so  can't activate horizon modes
