### ISSUE TITLE
Fixed Wing Servo auto trim

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#821]
Idea for a method for automatic servo trim for fixed wings.

1. New flight mode "AUTOTRIM"
1. Take off 
1. Fly level in Acro or Angle
1. When pilot activates AUTOTRIM , FC will record average output on every servo and store as new servo midpoint
1. Next activation of autotrim can happen only after AUTOTRIM off cycle

Averaging should not take longer that 1s, perhaps LPF with very low cutoff would do enough. PIlot should not move sticks during autotriming

**Comment by oleost** [comment]
Sounds like a good plan.

#555 Can be closed if this feature comes.

**Comment by digitalentity** [comment]
I like this approach better than #555.

**Comment by digitalentity** [comment]
I'll set it to 1.5, let's see what we can do.

**Comment by digitalentity** [comment]
PR ready to merge, closing.
