### ISSUE TITLE
Inav 5.0 OSD not populating

### ISSUE THREAD

**Issue by joneszee69** [iNavFlight/inav#8232]
I loaded Inav 5.0 on my matek 722 WPX Target FC and I cannot get the OSD to populate. When I  first turn on OSD menu there are a few things that appear on screen and in my goggles  like voltage,amp,RSSI and timer. As soon as I try to set up my custom values and hit save all of the OSD characters show on the screen but go away in my goggles  and I have nothing but The video feed with no OSD characters at all in goggles (I am using analog video system ) . I am using the default OSD setting and in configuration I have OSD tab turned on. I even tried it in auto , Pal and NTSD. I even tried moving the Characters around the screen and still nothing. I also tried to reload firmware, still nothing. I since downgraded to 4.0 and have no problem in OSD. Thanks

**Comment by MrD-RC** [comment]
Just a thought. As it's the WPX. Is the FrSky OSD set on UART 6 on the ports page?

**Comment by StuweFPV** [comment]
The graphical OSD's can sometimes be tricky. Make sure you have updated the graphical OSD to at least v2.0 AND the font before playing around in iNAV's osd page. https://github.com/frskyrc/frskyosdapp/releases
Like Darren said the port has to be activated as well and don't use AUTO settings for the camera detection. Especially Matek products don't like that. Just set what you use all the way throught -> Cam-FC-(VTX-VRX)-Goggles

**Comment by joneszee69** [comment]
Thanks guys for the info I will try it out then update

Thank you and have a great day!!!

**Comment by joneszee69** [comment]
Thanks guys for all your help the problem was I didn’t have the frisky OSD protocol selected, I must’ve tried to put something on that UART 6 and never reset it. Thank you Darren for your recommendation to check  the UART…👍🏻😀

**Comment by joneszee69** [comment]
Thanks guys for all your help the problem was I didn’t have the frisky OSD protocol selected, I must’ve tried to put something on that UART 6 and never reset it. Thank you Darren for your recommendation to check  the UART and all the other guys suggestions…👍🏻😀

**Comment by joneszee69** [comment]
Thank you you’re correct I did not have the Frsky OSD Protocol on UART6. Problem solved. Thanks again for taking the time to help me out😁👍🏻

Thank you and have a great day!!!
