### ISSUE TITLE
MATEK F411TE - Can not enable GPS

### ISSUE THREAD

**Issue by TrueKillRob** [iNavFlight/inav#8240]
INAV Version: 5.0.0
Controller: MATEK F411TE
GPS: TBS M8-2

When I enable GPS in the Configuration-Tab it is disabled again after "Save and Reboot"
When I confugre UART1, where the GPS is connected, as GPS, the UART is completly restored to default after "Save and Restore"
When I configure on the GPS-Tab (Enabling UBLOX or UBLOX7 ...) it is disabled after "Save and Restore"

Thank you for any Help
Robert

**Comment by erstec** [comment]
> INAV Version: 5.0.0 Controller: MATEK F411TE GPS: TBS M8-2
> 
> When I enable GPS in the Configuration-Tab it is disabled again after "Save and Reboot" When I confugre UART1, where the GPS is connected, as GPS, the UART is completly restored to default after "Save and Restore" When I configure on the GPS-Tab (Enabling UBLOX or UBLOX7 ...) it is disabled after "Save and Restore"
> 
> Thank you for any Help Robert

You need to disable all other things on UART1, like MSP, Serial RX and etc.
It works as should, I've just tested it on same FC.
