### ISSUE TITLE
iNav 5.1.0 - 6 axis calibration problem with Matek H743-Slim

### ISSUE THREAD

**Issue by robustini** [iNavFlight/inav#8275]
## Current Behavior

I am noticing that with the Matek H743-Slim I have this anomaly in the 6-axis calibration of the accelerometers/gyro.
If I start from the normal position when I arrive upside down it resets all the others five.
If I start from the upside down and do the other five, it completes it.

## Steps to Reproduce

1. Flash iNav V5.1.0
2. Try the 6 axis calibration starting from the normal position
3. Retry the 6 axis calibration starting from the upside down position

## Expected behavior

It should be possible to perform the operation from any axis.

## Additional context

https://user-images.githubusercontent.com/3864712/182018337-23f5e7ad-f21e-49fa-844d-a0276e8df718.mp4

---

- FC Board name and vendor: Matwk H743-Slim V1.5
- INAV version string: # 5.1.0 Jul 30 2022 / 09:30:58 (331450bc)

**Comment by MrD-RC** [comment]
The accelerometer is on the underside of that flight controller. So the first calibration needs to be performed with the flight controller upside down. The accelerometer needs to be the right way up.
