### ISSUE TITLE
RUSH_BLADE_F7 BMP280 Barometer doesn't work

### ISSUE THREAD

**Issue by NikitaKA** [iNavFlight/inav#8295]
## Current Behavior
RUSHFPV RUSH BLADE F722 FLIGHT CONTROLLER FOR DJI DIGITAL FPV SYSTEM supports BMP280 (and it works fine in Betaflight and Emuflight), but not in iNav.

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/2543427/183249034-bfd39544-6f97-4ceb-8f15-65b8c2938273.png)

## Suggested solution(s)
Add/fix support for BMP280 in RUSH_BLADE_F7 target.

## Version
INAV/RUSH_BLADE_F7 5.1.0 Aug  4 2022 / 12:57:00 (2590629e)
GCC-10.2.1 20201103 (release)

**Comment by DavyJohnes** [comment]
@NikitaKA any updates on this? Did you make it work?

**Comment by NikitaKA** [comment]
> @NikitaKA any updates on this? Did you make it work?

Unfortunately not. Swapped to Matek F405SE...

**Comment by NoviKurniawan** [comment]
no fix for this bug yet? I tried the latest update (INAV 6.1.1) but still got the same error

**Comment by LYCH90** [comment]
This situation is still happended with INAV6.1.1. Please fix it sirs

**Comment by Firesail99** [comment]
Flywoo 745 AIO hat auch den Barometer BMP280 verbaut. Dieser wird auch hier INAV5.0 - 6.1.1 nicht  erkannt bzw. lässt sich nicht aktivieren. Gibt es hier eine Lösung? (In Betaflight wird der Barometer sofort erkannt)

**Comment by LYCH90** [comment]
Developer INAV  may be dont care?

**Comment by Firesail99** [comment]
Ich habe  von Flywoo für den 745 AIO eine eigene spezielle INAV 6.x bekommen. Der Baro funktioniert jetzt. Flywoo sagt sie wären mit INAV Entwicklung in Kontakt.......

**Comment by UmbrelaCorp** [comment]
Blade V1.1 f7 digital has hardware
QMP6988 as barometer according to betaflight, it works OK in bf4.4 but been trying for couple days now to get it working on 6.1.1 inav

**Comment by b14ckyy** [comment]
Is this still an issue with 7.1?
