### ISSUE TITLE
Missing Surface Mode

### ISSUE THREAD

**Issue by Duncan-USAero** [iNavFlight/inav#8339]
Title, I can not find surface mode in the modes tab when setting up my aircraft, I have a benewake tfmini I am trying to use for altitude hold/terrain following indoors and it currently seems to be using only the barometer, the Lidar is working (Verified in the debug screen).

- FC Board name and vendor: Matek H743
- INAV version: 5.0

**Comment by MrD-RC** [comment]
Fixed https://github.com/iNavFlight/inav/pull/8171
