### ISSUE TITLE
MAMBAF722 2022B Target

### ISSUE THREAD

**Issue by chucky-whiskers** [iNavFlight/inav#8352]
## Current Behavior
No target yet.

## Desired Behavior
 I want to run my Mamba F722 Mk4 with  ICM42688P gyro in iNAV

## Suggested Solution
Create Board Target

## Who does this impact? Who is this for?
Mamba users, ICM42688P users, etc...

## Additional context
Same board as MAMBAF722 2022A with different gyro chip

**Comment by JulioCesarMatias** [comment]
duplication of https://github.com/iNavFlight/inav/discussions/8345

**Comment by JulioCesarMatias** [comment]
now we can close this order, the target has been added
