### ISSUE TITLE
SKYSTARS F722 HD PRO2 - accelerometer not working

### ISSUE THREAD

**Issue by mauroS123** [iNavFlight/inav#8355]
## accelerometer not working on INAV 5.1 -  Same board tested with betaflight and all working fine.

---

- FC Board name and vendor: skystars f722 hd pro 2
- INAV version string: 5.1

**Comment by JulioCesarMatias** [comment]
Are you sure it's PRO2? maybe it's the PRO3

**Comment by JulioCesarMatias** [comment]
ok, we need to add the MPU6000 drivers for this target

**Comment by mauroS123** [comment]
It is PRO2 and have BMI270 gyro. 
If I set to "AUTO", on first time the gyro works, but after a reboot it no more works again

**Comment by JulioCesarMatias** [comment]
hmmm... I had seen on the web that the IMU was an MPU-6000, but that's ok...

**Comment by mauroS123** [comment]
No, it's BMI270.  If I set "auto" it found BMI270 and working. If I disconnect USB and reconnect remain on BMI270 but not works. Then I set again "auto", reboot and it works again one time.

**Comment by mauroS123** [comment]
this is the pro3 and also have BMI270     http://skystars-rc.com/Products/ESC/2022/0716/103.html

**Comment by 9886834239** [comment]
> ok, we need to add the MPU-6000 drivers for this target

Yes, Skystars F722 HD Pro2 uses MPU-6000. Same is the issue with my board, can't detect the gyro and accelerometer after flashing iNav.

**Comment by mauroS123** [comment]
The board have bmi270.  If you manual set it works until first reboot

**Comment by 9886834239** [comment]
I could see mpu6000 in my Fc, please consider this.

**Comment by mauroS123** [comment]
My board v2 have bmi 270 and works only if I manually set that. If I set mpu6000 dont works.

**Comment by JulioCesarMatias** [comment]
@9886834239  I can include the drives in the target

@mauroS123  I don't know how to solve your problem

**Comment by mauroS123** [comment]
I would want to retry to flash INAV. Can you confirm that the target have now the driver ?

**Comment by 9886834239** [comment]
@JulioCesarMatias  
Hi,
 Have you uploaded the drivers for MPU6000?
Could you please tell us when we can expect this update?

**Comment by JulioCesarMatias** [comment]
[inav_6.0.0_SKYSTARSF722HD.zip](https://github.com/iNavFlight/inav/files/9620237/inav_6.0.0_SKYSTARSF722HD.zip)

**Comment by mauroS123** [comment]
Thanks. Now working.

**Comment by JulioCesarMatias** [comment]
> Thanks. Now working. INAV have found and set automaticaly BMI270 gyro.

strange the BMI-270 now works fine for you... I just added the MPU-6000 drivers

**Comment by mauroS123** [comment]
Works perfects. Only a little bug during calibration sequence. After the calibration on the second position (upside down) I need to recalibrate the first one that loses its value.

**Comment by mauroS123** [comment]
I think now it working due a bug fix inside inav 6.0 release and not due mpu6000 driver.

**Comment by MrD-RC** [comment]
> Works perfects. Only a little bug during calibration sequence. After the calibration on the second position (upside down) I need to recalibrate the first one that loses its value.

It looks like the IMU is on the underside if that flight controller. So the first position should have the FC upside down. This would have the IMU right side up.

**Comment by mauroS123** [comment]
Yes imu is on the underside of the board

**Comment by 9886834239** [comment]
Thank you, now I could able to run my fc with MPU6000 drivers.
