### ISSUE TITLE
Servo not showing up in outputs for Speedybee V3

### ISSUE THREAD

**Issue by Tjjohnston** [iNavFlight/inav#8362]
I am trying to get just the Tilt function from a servo on a multirotor from a channel. When I add the servo to the mixer it does not show up in the outputs/motors. I have heard it will even assign a compatible pad when you add a servo mixer, yet this has not happened. 
Is it that the Speedybee V3 does not allow a servo? That sounds crazy to me! 
The speedybee v3 has the 4 extra motor pads, so I would think that would be the route to go, but if those will not work do you know any other way I could wire that up to the flight controller?

Thanks for all the hard work on INav!

**Comment by MrD-RC** [comment]
SpeedybeeF7v3 has no servo outputs on the multi-rotor platform.
