### ISSUE TITLE
Flashing non-iNav Hardware

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8364]

**Comment by neutron1954** [comment]
I want to migrate from Betaflight 4.3.1 to iNav 5.1 on a quad with a SpeedyBee F7 v3 controller.  When I prepared to wipe and flash the new firmware, I saw a warning that said "Please do not try to flash non-iNav hardware with this firmware flasher."  Should I be using another method to wipe the old firmware (Betaflight) and flash it with iNav??

**Comment by DzikuVx** [comment]
Everything is fine, flash without fear
