### ISSUE TITLE
SmartAudio only changes Band and Ch for OpenVTX, Power stuck at 0.

### ISSUE THREAD

**Issue by j-keiter** [iNavFlight/inav#8365]
Inav 5.1 using Inav 5.1 Configurator on an HGLRC F722 Zeus flight controller with an EWRF vtx connected to an ImmersionRC Power meter.  UART3 TX set to smartaudio.  

Smart Audio only controls band and channel NOT power when talking to an EWRF vtx running openVTX.
Tramp is able to control power but only offers 25,100,600mW settings.
Hoping a developer can figure out why power is not changing but band and channel are when talking to openVTX.
Betaflight worked.  I was able to change power via smartaudio.

## Additional context

https://pastebin.com/vnUQreyM

---

Entering CLI Mode, type 'exit' to return, or 'help'

# version
# INAV/HGLRCF722 5.1.0 Aug 19 2022 / 11:27:05 (76f22b25)
# GCC-10.2.1 20201103 (release)

# 
- FC Board name and vendor:
- INAV version string:

**Comment by b14ckyy** [comment]
INAV does not support Power level 0 (PIT Mode) by design as many VTX on the market act weirdly and can lock up in PIT mode. Same can happen with BF but to prevent issues, PIT mode was never implemented in the first place.
