### ISSUE TITLE
SpeedyBee F7 V3 Black Box Issue 

### ISSUE THREAD

**Issue by Diver6691** [iNavFlight/inav#8370]
Hi,
I'm new in INAV and I want to know if my SpeedyBee F7 V3 has a problem or if it is a bug .
I can't retrieve any files from the fc . In betaflight I can see the on board card  as external drive but in INAV I have not that option. Am I doing something wrong ? 
I attach two screen shots .
Thanks in advance
![InavBB](https://user-images.githubusercontent.com/112702490/188141429-ea2bf792-6c4c-429d-88ab-9403cbfbc132.jpg)
![InavPORTS](https://user-images.githubusercontent.com/112702490/188141452-2c01d5e7-7178-4094-8f95-265c8663a91e.jpg)

**Comment by stronnag** [comment]
Did you try following the [documentation](https://github.com/iNavFlight/inav/blob/master/docs/USB_Mass_Storage_(MSC)_mode.md) ?

**Comment by Diver6691** [comment]
Thanks
