### ISSUE TITLE
Skystars F722 landing RTH 

### ISSUE THREAD

**Issue by obiwikii** [iNavFlight/inav#8378]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****hello, 
I am following my tests of the rth which has a problem. when the drone turns before initiating the descent, the bometer goes negative and the drone climbs on its own. Everything else is working

## Steps to Reproduce

1. after alt10m and 50m
2.switch rth
3.
4.

## Additional context

---
Entering CLI Mode, type 'exit' to return, or 'help'

# diff all

# version
# INAV/SKYSTARSF722HD 5.1.0 Aug 19 2022 / 12:53:41 (76f22b25)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# mixer

mmix reset

mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mixer

# servo

# safehome

# feature
feature GPS
feature PWM_OUTPUT_ENABLE

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS

# map
map TAER

# serial
serial 4 2 115200 115200 0 115200

# led

# color

# mode_color

# aux
aux 0 0 4 1700 2100
aux 1 51 5 1700 2100
aux 2 1 1 900 1300
aux 3 11 2 1300 1700
aux 4 10 3 1300 1700
aux 5 52 0 1700 2100
aux 6 27 0 1300 1700

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 23 0 H
osd_layout 0 1 12 0 H
osd_layout 0 7 23 11 V
osd_layout 0 11 23 8 V
osd_layout 0 12 23 7 V
osd_layout 0 13 1 9 V
osd_layout 0 14 1 11 V
osd_layout 0 15 1 10 V
osd_layout 0 22 14 11 V
osd_layout 0 23 1 8 V
osd_layout 0 28 22 10 V
osd_layout 0 32 23 9 V

# logic

# global vars

# programmable pid controllers

# master
set looptime = 500
set gyro_main_lpf_hz = 110
set gyro_main_lpf_type = PT1
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 120
set setpoint_kalman_q = 200
set gyro_zero_x = 2
set gyro_zero_y = 4
set gyro_zero_z = -5
set ins_gravity_cmss =  976.719
set acc_hardware = BMI270
set acczero_x = 22
set acczero_y = -71
set acczero_z = -22
set accgain_x = 4086
set accgain_y = 4083
set accgain_z = 4088
set align_mag = CW270FLIP
set mag_hardware = QMC5883
set magzero_x = -245
set magzero_y = -796
set magzero_z = 1008
set maggain_x = 1467
set maggain_y = 1479
set maggain_z = 1582
set align_mag_roll = -300
set align_mag_pitch = 1800
set align_mag_yaw = 2700
set baro_hardware = BMP280
set serialrx_provider = CRSF
set blackbox_rate_denom = 2
set motor_pwm_protocol = DSHOT300
set failsafe_procedure = RTH
set align_board_pitch = 2
set current_meter_scale = 290
set motor_direction_inverted = ON
set model_preview_type = 3
set applied_defaults = 2
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set airmode_type = THROTTLE_THRESHOLD
set nav_rth_altitude = 2000
set i2c_speed = 800KHZ

# profile
profile 1

set mc_p_pitch = 44
set mc_i_pitch = 75
set mc_d_pitch = 25
set mc_i_roll = 60
set mc_p_yaw = 35
set mc_i_yaw = 80
set dterm_lpf_type = PT3
set d_boost_min =  0.800
set d_boost_max =  1.200
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

# 

- FC Board name and vendor: skystars f722 
- INAV version string: 5.1

**Comment by breadoven** [comment]
Is this related to https://github.com/iNavFlight/inav/issues/8381 ?
