### ISSUE TITLE
problem with baro INAV 5.0.0 - target MAMBAF405US_I2C

### ISSUE THREAD

**Issue by Torchi** [iNavFlight/inav#8381]
Same problem has been probably already issued, I attach here my description and data.

Model already flown 3-4 times. I had already noticed a minor problem with altitude. This time was a severe problem.
Took off in HOLD and sky rocketed (see movie attached).
Switched to ACRO / ANGLE in order to descend and land.  Altitude has been all the time obviously wrong (see movie attached).

I attach flight blackbox and diff.

https://user-images.githubusercontent.com/18173871/189526440-8cb8cc17-ab13-4355-a17f-84578d34bec3.mp4

https://user-images.githubusercontent.com/18173871/189526443-ff25e1b2-d1de-4298-a4a3-81e8b5693dff.mp4

[INAV_cli_Super_8_20220908_163058.txt](https://github.com/iNavFlight/inav/files/9542449/INAV_cli_Super_8_20220908_163058.txt)
[blackbox_log_2022-09-10_112811.TXT](https://github.com/iNavFlight/inav/files/9542450/blackbox_log_2022-09-10_112811.TXT)

**Comment by stronnag** [comment]
Not a happy baro.
![blackbox_log_2022-09-10_112811-alt#1](https://user-images.githubusercontent.com/158229/189532516-12630302-b70f-4eae-8a0b-89e27e272c69.png)

**Comment by breadoven** [comment]
Is the Baro chip exposed to direct sunlight by any chance ?

**Comment by Torchi** [comment]
Yes, it can be exposed to sunlight.
Here is a picture of quad.   A circle shows where FCB is located: it is under a carbon fiber roof  (that is narrow and with small openings).

![IMG_20220820_094304055](https://user-images.githubusercontent.com/18173871/189571288-ffa8c50a-a40f-46f8-a2c7-f3cfcef2444b.jpg)

This is the side of the FCB facing up (and approximatively rotated the same).
In the circle I have outlined what "I believe" is the baro chip.

![1](https://user-images.githubusercontent.com/18173871/189571509-8d5f6806-c3a8-47c8-aa51-42ca9b355c63.jpg)

I guess this is the reason of the baro malfunctioning ... ?!

**Comment by breadoven** [comment]
I've noticed the altitude varies wildly if the chip has direct sunlight on it. The BMP280 chip is light sensitive apparently, gets in through the small hole in the case. I've seen errors of over 80m. Not as much as in your case but easy enough to rule this out by covering the chip with some open cell foam which is something you should do anyway to damp out pressure changes from prop wash etc.

**Comment by Torchi** [comment]
Ok, I am convinced  (also calmed because i have seen that chip is used in many FCB types and the problem is frightening when it manifests). I shall do, with this model, as you suggest.

**Comment by obiwikii** [comment]
perfect now for me
