### ISSUE TITLE
"DROP" Failsafe mode does not work with MATEK F405 WMN

### ISSUE THREAD

**Issue by swagprincess** [iNavFlight/inav#8397]
## Current Behavior
If the "DROP" failsafe mode is selected in the failsafe tab, when failsafe is active, the motor stays on at the throttle it was.

## Steps to Reproduce
1. Set failsafe mode to "DROP" on MATEK F405 WMN.
2. Get it to failsafe.

## Expected behavior
The motor should stop and servos go to their midpoints.

## Suggested solution(s)
Probably some bug in the firmware for this board

## Additional context
I am using ELRS 868mhz with R9M/R9MX

https://pastebin.com/6tPxAcWK

- FC Board name and vendor: INAV/MATEKF405TE
- INAV version string: 5.1.0

**Comment by hapsti** [comment]
reset my settings and fixed it
