### ISSUE TITLE
Autolaunch is not working

### ISSUE THREAD

**Issue by dirkmaat** [iNavFlight/inav#8402]
I can fly with my plane in Manual mode horizon mode Gps mode. When i put Permanently autolaunch on. Then gives the system Not ok en cannot arm. This is my video https://www.youtube.com/watch?v=9ouc4EnMkog
What am i doing wrong?

**Comment by breadoven** [comment]
Go into Configurator CLI tab and type "status". This will tell you why it isn't arming. Auto launch related Arming issue is likely due to the roll/pitch stick not being centred so check roll and pitch values are 1500 in the Configurator Receiver tab. Any other value will cause problems.

**Comment by dirkmaat** [comment]
thank you. I have adjusted the value in my transmitter under outputs so that in inav it is 1500. Now I can turn on Autolaunch permanently and also put it on arm. Can test it well outside.
