### ISSUE TITLE
New flight controller

### ISSUE THREAD

**Issue by Shivam123-45** [iNavFlight/inav#8404]
## Additional context
 sky stars H7hd flight controller firmware

**Comment by Shivam123-45** [comment]
Where is sky stars H743 flight controller firmware

**Comment by peterbrady** [comment]
I see this closed as completed, but I only see Skystars F7 controllers in the iNav configurator. Am I looking in the wrong location?

**Comment by konstkarapan** [comment]
There is a target for this fc in inav. It is called:"SKYSTARSH743HD"
