### ISSUE TITLE
INAV Not Arming - CLI = VTX: not detected

### ISSUE THREAD

**Issue by rcflightguru** [iNavFlight/inav#8405]
Arming disabled flags: NAV HWFAIL RX CLI
INAV Not Arming - "CLI = VTX: not detected"
Looking for a solution to this

**Comment by gavin-jennings** [comment]
Getting this error.
Mamba F405 Mini
INAV 5.1.0
Using CRSF Sixty9, no smart audio setup as it is handled in the TBS lua on the TX
Any help is appreciated.
Thanks
