### ISSUE TITLE
Safe Disarm

### ISSUE THREAD

**Issue by sdellava** [iNavFlight/inav#8419]
## Current Behavior
Disarm command is immediatelly executed, but although it is not a frequent case, it may happen to unintentionally disarm the drone/airplane while flying.

## Desired Behavior
The disarm command should be executed only in specific conditions.

## Suggested Solution
I suggest introducing an optional configuration parameter indicating a height from the home from which the disarm command is ignored.  In example, disarming above 10 m from the ground can always be considered a mistake.

Obviously, disarming is a safety maneuver to be performed in case of loss of control of the aircraft with risk that it may produce serious damage to property and people.

So I suggest that there should also be an emergency procedure that can bypass the height limit: if a disarm - arm - disarm sequence is given within 2 seconds above the heigt limit, then the flight controller should actually disarm.

## Who does this impact? Who is this for?
Everyone

**Comment by DzikuVx** [comment]
No, there will be no changes like that to disarm procedure. INAV always disarms when command is give. Pilot, if wants, can add extra conditions on the radio like 2 switch arm->disarm
