### ISSUE TITLE
Prefer BARO altitude over GPS altitude for airplanes

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#842]
Airplanes allow GPS altitude to be used. Current code fuses BARO+GPS with preference of GPS. In case of GPS glitching we may have a large change in altitude which is unwanted.

![image](https://cloud.githubusercontent.com/assets/11059099/20693528/ac5e5cb6-b62a-11e6-86fd-d8a64aa0c656.png)

We should prefer BARO over GPS if both sensors are available.

**Comment by oleost** [comment]
Yes agree

**Comment by digitalentity** [comment]
PR in place. Closing.
