### ISSUE TITLE
Add support for DJI wtfos MSP-OSD full screen

### ISSUE THREAD

**Issue by jeffhendrix** [iNavFlight/inav#8433]
The new wtfos project ([https://github.com/fpv-wtf/wtfos](https://github.com/fpv-wtf/wtfos))
allows the drawing of all OSD elements on the DJI FPV goggles. 
iNav currently uses the HDZERO mode to take advantage of this feature, but it's limited to 50x18 and the goggles are capable of 60x22.

Changes are required to iNav and the configurator, but should be fairly simple (leveraging the HDZERO code).

**Comment by jeffhendrix** [comment]
Can someone assign this to me, I have the code almost finished.

**Comment by erstec** [comment]
> Can someone assign this to me, I have the code almost finished.

It is not needed to be assigned. You are welcome to open pull request with your code here for INAV and in https://github.com/iNavFlight/inav-configurator/pulls for INAV Configurator.

But if you prefer, I can assing this issue to you )

**Comment by jeffhendrix** [comment]
> > Can someone assign this to me, I have the code almost finished.
> 
> It is not needed to be assigned. You are welcome to open pull request with your code here for INAV and in https://github.com/iNavFlight/inav-configurator/pulls for INAV Configurator.
> 
> But if you prefer, I can assing this issue to you )
I just didn't want someone else to duplicate the work
I hope to have a PR soon (I might play with it for a day or 2 first)

**Comment by erstec** [comment]
> > > Can someone assign this to me, I have the code almost finished.
> > 
> > 
> > It is not needed to be assigned. You are welcome to open pull request with your code here for INAV and in https://github.com/iNavFlight/inav-configurator/pulls for INAV Configurator.
> > But if you prefer, I can assing this issue to you )
> > I just didn't want someone else to duplicate the work
> > I hope to have a PR soon (I might play with it for a day or 2 first)

Anyone can do same development as your one.
As @stronnag already explained you in Discord: _if someone else comes along with a better implementation, we'll take that. It's not exclusivity, it merit that counts_

**Comment by stronnag** [comment]
But just the fact that you raised the issue and said you're working on it is enough. 
We're not a megacorp, we don't do "waterfall", we don't have a list of staff to assign work.

We self-manage and welcome contributions, so thanks for volunteering.
