### ISSUE TITLE
Improper config on BMI270 hardware gyro lpf

### ISSUE THREAD

**Issue by shota3527** [iNavFlight/inav#8443]
Also mentioned by @VanLaser here
https://github.com/iNavFlight/inav/pull/7356#issuecomment-1177490974
On bmi270 the "default" gyro HW LPF is not 256Hz, but 751Hz.
Current Betaflight`s default is 3.2k gyro data rate with OSR4 mode (about 187.75Hz lpf)
This graph shows there is massive gyro noise when set to 3.2k gyro data rate with Normal mode(751Hz lpf)
![image](https://user-images.githubusercontent.com/38871576/193809760-f22e6646-b094-43d6-a9ca-3c8aeae9e837.png)

I am currently experiencing some gyro tracking issues on MATEKF411WTE(BMI270), There are always about 5-10deg less in ahrs when I perform 360roll. I suspect it is caused by excessive noise in gyro measurements <- it is confirmed that gyro scale factor error is causing this

more information here
https://www.youtube.com/watch?v=UWiysMidBHM&t=586s
https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BMI270-OSR-mode-behaviour/td-p/52020

**Comment by JulioCesarMatias** [comment]
A little sad to know you need a "DNA" to configure OSR2 and OSR4

**Comment by JulioCesarMatias** [comment]
But, we really need to correct the filter configuration of this IMU... With the current standards it is bad to fly in modes that use the autopilot system.

**Comment by JulioCesarMatias** [comment]
https://github.com/betaflight/betaflight/commit/a9f9477d3ef9503d406d04ebf6028d0fec4f260f
