### ISSUE TITLE
Matek F405 TE  acelerometer calibration data recording issue

### ISSUE THREAD

**Issue by Antipilas** [iNavFlight/inav#8449]
Matek F405 TE
Inav ...4.1 and above also tested with 5.1

With different units I have tried to calibrate accelerometer as always and in the first calibration register 4096 in all axis and trying again did not start de calibration and shows " calibration finished"

**Comment by b14ckyy** [comment]
on some FCs for some reason (I don't know why) a specific orientation triggers a finish of the calibration as soon as you do that. 
Try doing that orientation that gives you the "finish" falsly at first or at last and do the other orientations first. This should work if it is the same cause as for 1 or 2 FCs I have. 

@DzikuVx said it has something to do with a threshold triggered but I didn't exactly understand that.
