### ISSUE TITLE
iNAV 5.1.0 OSD issues

### ISSUE THREAD

**Issue by JimValo** [iNavFlight/inav#8459]
I have a Matek F411-WTE FC and in iNAV I set my warning altitude at 400 feet when I fly in my goggles the altitude is there until I reach 400 feet then it completely disappears and I see nothing on the altitude but then when I go below 400 feet the altitude comes back why I think it’s supposed to just flash but it disappears?

**Comment by OptimusTi** [comment]
There are some boards that do not support the "blink" feature of the MAX OSD chip. You can fix this by setting the following command in the CLI: set display_force_sw_blink = ON
