### ISSUE TITLE
SpeedyBee F7 V2 INAV - Remap to use 2 aux channels (pan/tilt) on CH1 and CH2

### ISSUE THREAD

**Issue by maRCnh33** [iNavFlight/inav#8466]
I have installed INAV 3 on a rc plane, there i have a RX with SBUS and PPM, 8 channels PPM... so i used CH5 for PAN and CH6 for TILT. It works very good!

Now i have another plane, a Multiplex Twinstar ND. On that plane i like to have the same setup as the other plane. But, on the twinstar i have another rx, also with SBUS and PPM. But on this RX there are 4 analog outputs, CH1, 2, 3 and 4. So i have to use CH1 and CH2 for pan/tilt. But HOW can i change the MAPPING from AETR to 12AETR ?? Please help me!

I use INAV 3.0.0.18 ( a friend of me modified the firmware to get my throttle output on the LED port (because i need 2x AIL, 1x ELE, 1x Throttle and 1x RUDDER, So thats why... 

Is it possible to remap ???

I hope someone can help me, tnx!

Marc

**Comment by JulioCesarMatias** [comment]
you will only be able to do this through direct changes to the algorithm. Through the configurator it is not possible
