### ISSUE TITLE
Dose inav support BE-180,BE-280 GPS Modules？

### ISSUE THREAD

**Issue by ss8688** [iNavFlight/inav#8467]
<img width="169" alt="image" src="https://user-images.githubusercontent.com/59367202/195966379-5a7b2c64-1ecd-43d3-8b9f-c5985e58f79a.png">
This is new Beitian GPS Module with 10 gen M10050. But I can not find any information about it.Can it work with inav?

**Comment by JulioCesarMatias** [comment]
yes
