### ISSUE TITLE
Airplane launch assistant improvements

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#847]
Fix non-detected launches when throwing a flying wing by the wingtip.

**Comment by digitalentity** [comment]
@oleost this will probably have to wait for after the New Year. Too much testing is required.

**Comment by oleost** [comment]
No problem. Just postpone to 1.6
Remember you can always ask me to do some test.

But of course, now its christmas / new year and the days are short so its limited whats time left to do some testing.

**Comment by digitalentity** [comment]
I'd rather keep it in 1.5 for now - maybe I'll have the time to implement new logic

**Comment by digitalentity** [comment]
Yee-ha! Experimental #878 done!

**Comment by flounderscore** [comment]
How are you supposed to trigger the launch?

**Comment by digitalentity** [comment]
It's not for triggering the launch, it's detecting the launch. You just throw the airplane and INAV takes over helping you to reach stable climb.

**Comment by oleost** [comment]
@flounderscore  https://github.com/iNavFlight/inav/wiki/8.-Navigation-modes#launch---airplane-launch-assistant
