### ISSUE TITLE
Set servo values at specific waypoints in INAV Configurator

### ISSUE THREAD

**Issue by joymonkey** [iNavFlight/inav#8471]
## Current Behavior
INAV Mission Planner (in Configurator 5.1) allows you to create a waypoint, and configure options for the waypoint to set it to "JUMP" , "SET_HEAD" and "RTH" along with a couple of parameter values.

## Desired Behavior
I'd love to have the functionality where I could add a Servo command at a specific waypoint, to have the specified servo move to the specified angle.

## Suggested Solution
Coding magic.

## Who does this impact? Who is this for?
Users wanting more control over camera gimbals, payload droppers, or other fancy custom gadgetry that might use a servo signal (like say, having your multirotor fly close to your friends house and have a servo-powered cardboard hand flip them the middle finger - surely hilarity would ensue?).

## Additional context
I love you. There, I said it.

**Comment by b14ckyy** [comment]
The waypoint side of things is done. Only the Programming side has to be done next. Then you can use these cusom values as a Programming trigger to set conditions to TRUE and trigger events.
