### ISSUE TITLE
Add new target - mRo PixRacer R15

### ISSUE THREAD

**Issue by RoboViz** [iNavFlight/inav#8477]
## Current Behavior
Only Pixracer R14 is supported

## Desired Behavior
Support Pixracer R15

## Suggested Solution
I think the difference between R14 and R15 is minor. I don't know what is the solution, but you guys have much more experience.

## Who does this impact? Who is this for?
Added target HW.

**Comment by JulioCesarMatias** [comment]
what has changed is the exchange of the secondary IMU and the compass.

R14:
ICM-20608-G (IMU)
HMC5983 (Mag)

R15:
ICM-20602 or ICM-20608 (IMU)
LIS3MDL (Mag)

iNav already has ICM-20602, ICM-20608 and LIS3MDL drivers included in this target. You can use `PIXRACER HSE_MHZ 24` target without problems, everything will work.
