### ISSUE TITLE
Please re-add LED feature to naze32 target

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav#85]
Me and most likely many others love the LED support and use it for orientation, warnings and many other things. You've done a incredible job on inav so far, but removing the led support on naze targets was not the best idea I think. I know, this decision was made because of code size, but there are maybe some other functions that can be left out that are not so important as led support. For example: I think most of us can live without the OLED support or support just 16 LEDs instead of 32 if this helps. In this state it is much more harder to fly LOS and I often can't hear the buzzer on my model and have no visual signal for low voltage alarm.

**Comment by digitalentity** [comment]
Assigning to 1.1 milestone - possibly will fit with slimmed GPS code.

**Comment by digitalentity** [comment]
Fixed
