### ISSUE TITLE
Show Alarms as System Messages / Extra element

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#8506]
## Current Behavior
Right now, all alarms only make OSD Items blink. This means we cannot have Alarms for Items that are not on Screen. Also Blinking on MSP-DP based systems (Basically all digital FPV systems now) has issues with very slow blink rates or disappearing elements. 

## Desired Behavior
Show Alarms as System Messages and/or blinking as Options. 

## Suggested Solution
I suggest that any Alarm can be shown as a System message. 
There should be 3 Settings to select from for Alarms: Blinking / System Message / Both
If multiple alarms appear, they should rotate as usual
If possible, general Info messages like Waypoint info or Radar Info should be disabled when an alarm happens to make sure it is not missed. 

Alternative: 
Instead of using system messages, another option could be to have a dedicated OSD element for warnings. This element could be placed individually on the screen or any layout and show something like this: WARN:XXXXX
So this dedicated OSD element would just be 10 chars wide and show the actual warning element with its value. Leaving 5 chars for the OSD element should be sufficient for all the warning elements. maybe 6 if needed. I guess the used mAh needs 6 fields as the unit consists of 2 fields + 4 digits

## Who does this impact? Who is this for?
Any Pilot in General but mostly Digital Pilots where the OSD Elements have usually a very slow update rate to preserve bandwidth. 
This also allows a cleaner OSD with less elements while still preserve critical warnings like ESC Temp, IMU temp or RSSI/SNR Alarms while only having LQ on screen. 

## Additional context
-

**Comment by tonyyng** [comment]
> Also Blinking on MSP-DP based systems (Basically all digital FPV systems now) has issues with very slow blink rates or disappearing elements.

Can you provide more information on the slow blink rates for MSP-DP?  Is a solution for this problem not possible?  I'm encountering this issue with INAV 6.0 and DJIWTF and haven't found it discussed anywhere.

**Comment by b14ckyy** [comment]
closing as duplicate of https://github.com/iNavFlight/inav/issues/8121
