### ISSUE TITLE
Flip32 F4 Tricopter configuration doesn't work

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#851]
Reported by a user who replaced Flip32 with Flip32-F4 on his Tri.

**Comment by oleost** [comment]
Where are servo output on Flip32 F4?

If it the same as F3 it's on pin 7 and that's different from the pin 1 he is used from on naze32

**Comment by DzikuVx** [comment]
Ha, this is a very good question, since I have no idea :(
Let's find it, but probably we will have to move it from where it is right now

**Comment by DzikuVx** [comment]
Yes, we have a bug, servo outouts in non-airplane configurations are not initialized at all

**Comment by digitalentity** [comment]
Let's put this on hold for now until @martinbudden does his big thing with config access macros.

**Comment by martinbudden** [comment]
Hope to get the config access macro change in next week.

**Comment by digitalentity** [comment]
Fxied by https://github.com/iNavFlight/inav/pull/872
