### ISSUE TITLE
inav 6.0 and matek f405-wse

### ISSUE THREAD

**Issue by Daramidon** [iNavFlight/inav#8520]
inav 6.0 firmware is not installed on matek f405-wse there is not enough memory in the flight controller.

**Comment by Daramidon** [comment]
<img width="960" alt="inav 6 0" src="https://user-images.githubusercontent.com/117340783/199664558-33318655-ea70-485e-899e-c277684a3815.png">

**Comment by Jetrell** [comment]
I'll ask a silly question. Are you sure its a F405, you have connected?  They have 1024KB of flash.

Here is my attempt to flash the Matek F405-WSE. It was fine.

![Capture](https://user-images.githubusercontent.com/47995726/199665819-cd824793-4e0f-4f5d-90dc-1349e382e6a2.JPG)

**Comment by MrD-RC** [comment]
I think you have an F411-WSE. Not F405-WSE. The F405-WSE has 1024KB of flash. The F411-WSE has 512KB flash. I'm pretty certain you have just chosen the wrong target.

**Comment by Daramidon** [comment]
ошибся с прошивкой. вопрос решен.

**Comment by Daramidon** [comment]
Thanks.  I already figured it out.  I really messed up the firmware.  but
it's all right now.

чт, 3 нояб. 2022 г., 10:27 Darren Lines ***@***.***>:
