### ISSUE TITLE
INAV V1.4  naze32  frsky/smartport   bug

### ISSUE THREAD

**Issue by wolflonezx11** [iNavFlight/inav#855]
hi 

INAV V1.4  naze32  frsky/smartport   bug

Unrecognized bug
Please take quick action.

**Comment by digitalentity** [comment]
Some more details will help. How receiver is connected, config dump etc.

**Comment by oleost** [comment]
Smartport has been removed on naze32 due to size limitations.
See wiki https://github.com/iNavFlight/inav/wiki/1.-Getting-started-with-iNav

**Comment by digitalentity** [comment]
@oleost thanks! Funny, I removed that myself and forgot :laughing:
