### ISSUE TITLE
why do “cfTasks[taskId].totalExecutionTime = 0” have two？

### ISSUE THREAD

**Issue by ZhaoSQ-CH** [iNavFlight/inav#8552]
#  Current Behavior
There is two “cfTasks[taskId].totalExecutionTime = 0”, where is code:  https://github.com/iNavFlight/inav/blob/fae79547f25843fb879a7c8f287994873b5d0018/src/main/scheduler/scheduler.c#L200
why is code programming ？
# Steps to Reproduce

# Expected behavior

# Suggested solution(s)

# Additional context

**Comment by JulioCesarMatias** [comment]
No big deal... It's just a duplication that happened accidentally when this part was being written
