### ISSUE TITLE
Upixels U30 Flow sensor

### ISSUE THREAD

**Issue by ltwin8** [iNavFlight/inav#8561]
Hello, 

i have just bought an Upixels Optical flow sensor and used it with ardupilot, now i wonder if it is possible to use it with inav, it hjas the UPIXELS chipset and i remember reading that it was one of the milestones for 3.0 (#5873) but have not found any documentation.

reason is i can not use the matek sensor but have to use opflow and ToF due to space on different boards

Can someone provide a link to documentation?

**Comment by b14ckyy** [comment]
Still not supported yet. Closing as duplicate as there is a ticket for that request.
