### ISSUE TITLE
"Saving default settings" / "Waiting for data" hangs on Configurator 5.0.0 MAC (M1), Omnibus F4Pro

### ISSUE THREAD

**Issue by gronat** [iNavFlight/inav#8565]
I have Configureator 5.0.0 on MAC (M1 chip) and Omnibus F4Pro. I flashed the board with both the 5.0.0 and the 5.1.0 firmware. Had to flash using Betaflight since Configurator did not work; no idea why. Just downloaded HEX using iNav and flashed with the Betaflight chrome addon. iNav can connect to the FC but hangs on "Saving default settings" or "Waiting for data", respectively. 

How to reproduce:
1. Open iNav
2. Plug the board in the USB and click "Connect"
3. The "Default values" dialogue shows up -> select "Wing with a tail"
4. it hangs on "Device - Saving default settings" .....
5. after some time (e.g. 2h) close the dialogue clicking the "X" in the top right corner
6. Accelerometer readings do work, the box moves as the FC is moved
7. Now, click "Mixer"
8.  Hangs for "Waiting for data"....

If I Disconnect and connect now and click "Wing with a tail" I only see the dialogue window but no text displayed. I am new to iNav (switching from ArduPilot), but I expect that saving the settings should take seconds.

**Comment by stronnag** [comment]
1. This is a configurator issue and should be raised against the configurator project
2. As you're running this on aarch64 under emulation, and the MacOS configurator is known to work on native amd64, it is extremely unlikley that the INAV project can assist you further.
