### ISSUE TITLE
Continous Servo trim acts wrong on V-Tail Mixes

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#8571]
## Current Behavior
If a Plane with a V-Tail mix has Continous Servo trim active, it is likely that, for the Pitch Axis, the servos are trimmed in opposite directions. I was finally able to reproduce and it seems like this happens, if Pitch has a negative + Positive mixed servo and no Inverted output. Both servo 2 and 3 are trimmed into the same direction (signal wise) but that means that one control surface goes up and the other one goes down. 

Problem is unrelated of the yaw mix. With V-Tail both servos only on a pitch mixer, the behavior is the same. Its always the left or lower servo in the numbering that has an inverted trim behavior. 

![image](https://user-images.githubusercontent.com/33039058/203005201-2dadd8d0-ba16-4ccf-ad60-3fad6b53178a.png)
![image](https://user-images.githubusercontent.com/33039058/203005335-a8721ceb-5336-4a48-9ca0-97ad0a980456.png)

## Steps to Reproduce

1. Set up a V-Tail plane with same configuration: Mixer with one pitch servo inverted, outputs both V-Tail servos uninverted
2. Go fly with Yaw Integral at 0 to disable Continous trim on that axis
3. Enable continous servo trim
4. Check control surfaces after landing

## Expected behavior
Pitch axis continous trim goes into the correct direction no matter what Mixer or Servo direction is set on each Servo. 

## Suggested solution(s)
Take mixer and output reversal both into account for trimming Pitch on a V-Tail.

## Additional context
I will try to get more Information from other pilots and compare their mixer and output settings with mine to find common factors. 
Here is a Log of the last flight with Servotrim Debug enabled: 
[LOG00040.zip](https://github.com/iNavFlight/inav/files/10054890/LOG00040.zip)

---

- FC Board name and vendor: Any
- INAV version string: Issue started to appear with INAV 3.0 and Continous Servo trim feature implemented.

**Comment by b14ckyy** [comment]
@Jetrell as far as I am concerned this does not really seem to help. The Continous servo trim does not touch yaw at all if the Integral on yaw is set to 0. But the pitch trim seems to trim the servos in the opposite way. At least it looks like it. 

All planes reported so far have in the outputs tab either both V-Tail servos reversed or none reversed. Never differently. I will try another test flight when possible but then reverse one servo only and compensate with the mixer to see how that behaves.

**Comment by Jetrell** [comment]
Here is the mixers on a Mini Talon.. Noticed that the Pitch stabilization servo's both have positive weight, compared to your example. Which is what you thought could be an issue.. But by not having Stabilized Yaw. It makes it easier to get the Pitch mixing correct in this manor.
This Talon has no issues running Continuous servo trim.

![Mini Talon](https://user-images.githubusercontent.com/47995726/203474788-ac3e415c-d572-4510-ae6d-943b2deb78c8.JPG)

![servo's](https://user-images.githubusercontent.com/47995726/203474896-66d563db-159a-42d7-a9ba-8fab1bad74d8.JPG)

**Comment by Jetrell** [comment]
> Here is the mixers on a Mini Talon.. Noticed that the Pitch stabilization servo's both have positive weight. Which is what said is the issue. 
But by not having Stabilized Yaw. It makes it easier for people to get the Pitch mixing correct in this manor. This Talon has no issues running Continuous servo trim.
> 
> ![Mini Talon](https://user-images.githubusercontent.com/47995726/203474788-ac3e415c-d572-4510-ae6d-943b2deb78c8.JPG)
> 
> ![servo's](https://user-images.githubusercontent.com/47995726/203474896-66d563db-159a-42d7-a9ba-8fab1bad74d8.JPG)

**Comment by b14ckyy** [comment]
@Jetrell This is really interesting. 
you ar ethe only one so far not reporting trim issues and your V-Tail servos are running the opposite in the outputs tab (one inverted, one not)
Allt eh people reporting issues including myself are running both servos either inverted or uninverted and the direction change happens in the Mixer. 
So I really need to change that in my setup and doublecheck if the issue still persists then. If it does we should have tracked down the root cause.

**Comment by Jetrell** [comment]
That's why I thought the simplification of just using RC Yaw is helping to workaround the problem. Because you don't have to take into account the Yaw stabilization response.  Only RC Yaw control.
I've experienced the same issue with a nano talon a few releases back.. But I don't have that plane and its setup, to now compare.

> So I really need to change that in my setup and double check if the issue still persists then. If it does we should have tracked down the root cause.

Let me know what you find.

**Comment by b14ckyy** [comment]
So far all people reporting the same issue have, had the mixes and reverses set as in the example above. 
Either both V-Tail servos unreversed or both reversed and all correct movements regulated in the mixer. 

I have now changed that. Reversed Servo 3 (right Tail servo) so it runs opposite to the left servo 2 from the outputs and changed the mixer accordingly to have all directions correct again. Another test pilot did the same and goes for a test flight right now. 

![image](https://user-images.githubusercontent.com/33039058/203608913-2f295db0-926d-4c82-a5f6-14d65687dd00.png)
![image](https://user-images.githubusercontent.com/33039058/203608935-271df43b-80f7-4d3a-8cea-10f1621e6a63.png)

**Comment by b14ckyy** [comment]
OK it behaves the same with this configuration. So next step would be to disable yaw entirely and see what happens.

**Comment by kasatka60** [comment]
![123](https://user-images.githubusercontent.com/61105679/204094448-3fa6c779-75f4-4aab-bda9-bd0913fbe409.png)
![124](https://user-images.githubusercontent.com/61105679/204094450-337fb184-e3a3-49ab-a3ad-6ffb67f1bc77.png)
![IMG_7198](https://user-images.githubusercontent.com/61105679/204094462-3dfce5de-b9d0-40c7-a91f-5c66c184a633.jpg)
inav 6.0 fp1

**Comment by b14ckyy** [comment]
OK we have confirmation now. The wrong trim behavior is unrelated to yaw. Shawn made a test flight today with no yaw mix. Both servos plain pure Pitch mixed. Still the left servo, as always, is trimmed down instead of up like the right servo. 

so there is just a trim value inverted for dual servo pitch controls. @avsaase do you think you can have a look if you have overlooked something back then? You know the code best.
