### ISSUE TITLE
Target sensors non identifiable after flash.

### ISSUE THREAD

**Issue by Vthorn06** [iNavFlight/inav#8580]
****

## Current Behavior
Target is "flywoo f7 dual"
On the flywoo website listed as:
Flywoo goku GN722 EVO aio

After flashing with online available target firmware no onboard sensor is detected acc/gyro and baro.

![20221124_145348.jpg](https://user-images.githubusercontent.com/97136819/203746290-bfff5027-b850-422b-a769-be9a5f55d9bb.jpg)

## Steps to Reproduce
flash the above board with 
Flywoof7dual target

## Expected behavior
acc/gyro and baro should work and populate, but that is not the case

## Suggested solution(s)
one of the devs should look into this

## Additional context
I have 2 of the above boards, responding the same way.
its not the hardware as well since betaflight detects the sensors with no problem and everything is working

I know it have 2 gyros.
I tried gyro_to_use cli command as well.

And lastly,
I compiled custom targets with only one gyro/acc use at a time. No luck

---

- FC Board name and vendor:
- INAV version string:

**Comment by yashbajaj2011** [comment]
email me on this id - yashbajaj2011@gmail.com
i will send u the hex which works
