### ISSUE TITLE
Allow remap motor and servo pins

### ISSUE THREAD

**Issue by xpol** [iNavFlight/inav#8582]
I want to use Matek H743 mini (the one designed for drones) for planes.
But according to its layout, the S1-S4 are in a JST 8pin socket which is not ideal for servos.
<img width="729" alt="Matek-H743-mini" src="https://user-images.githubusercontent.com/20248/203959524-cd680510-f053-4c56-8681-9fd015d3a5d8.png">

So I'd like to use, S1~S4 for motors (maybe only S1-2, and leave S3 and S4 free) and S5-S8 for servos.

## Current Behavior
But the current iNav only gives me the following mapping:
<img width="1035" alt="Current" src="https://user-images.githubusercontent.com/20248/203958341-ad97edcb-abeb-4156-b55f-f8614d79def2.png">

## Desired Behavior
And What I wanted:
<img width="1035" alt="Wanted" src="https://user-images.githubusercontent.com/20248/203958487-041da04d-3398-48b8-a0ac-91d64d82d229.png">

## Suggested Solution

- Can I change the iNav/Configurator code to implement this? Where should I start?
- Feature #1145 should also be a solution for this.

## Who does this impact? Who is this for?

Airplane users
Users of rich IO flight controllers, like Matek H743 mini, will need this.

**Comment by breadoven** [comment]
Surely you can still add servo mixers for S7 and S8 allowing the use of the through hole pin connections for S5 to S8,. Then set up as required, roll, pitch, yaw etc. Servo mixers S3 and S4 just don't get used, Not remapping but should still work so long as you don't need more than 2 motors.

**Comment by xpol** [comment]
Got what I want, just replace the `TIM_USE_FW_SERVO` with `TIM_USE_FW_MOTOR`.
For me I changed for on *S3* and *S4* in the [here](https://github.com/iNavFlight/inav/blob/master/src/main/target/MATEKH743/target.c#L38-L39).
