### ISSUE TITLE
MSP display-port does not work with the new DJI O3 air units

### ISSUE THREAD

**Issue by OlivierC-FR** [iNavFlight/inav#8596]
Gear : 
DJI Goggles V2, not rooted, not WTFOS modified, with newest official DJI firmware (v1.04.0000 2022-11-15)
DJI O3 air unit, with newest official DJI firmware (v1.01.0000 2022-11-15)
Matek F722-SE
INAV 6 FP1
INAV configurator FP2

O3 AU is connected to the UART, peripheral = MSP displayport, the OSD does not show in the V2 goggles.

Can see a basic link is up tho, the O3 detects the arming, that is then used to auto-trigger the recording and auto switch out of the low power state. Only information shown from INAV are the messages "motor armed" and "motor disarmed" bottom right, no other OSD data is displayed, other than what the O3 make itself (supply voltage, and video stream stats).

The issue being in DJI's hand or INAV's side is to be debated later :)

----

3 screencap below are from Betaflight latest version, 4.3.2, the OSD works in the V2 by just checking MSP for the UART. 

![Capture d’écran 2022-11-30 151455](https://user-images.githubusercontent.com/25566932/204827342-469e1785-74ee-44e6-9348-b794d8119283.jpg)
![photo_2022-11-30_15-39-26](https://user-images.githubusercontent.com/25566932/204827346-4f914afa-f645-4ef9-8b51-27c38e868b4b.jpg)

![Capture d’écran 2022-11-30 151548](https://user-images.githubusercontent.com/25566932/204827334-5ca336c0-3302-4429-b6a4-c466c0448426.jpg)

**Comment by deethee** [comment]
Can confirm this. Flying without OSD on a wing makes this o3 air unit worthless.

**Comment by a1axx** [comment]
Here is the compatible character set 
![image](https://user-images.githubusercontent.com/47070080/205068439-32c8b1b1-9bdc-4442-b319-acd56f8f845c.png)

**Comment by a1axx** [comment]
Passed on from a user on discord:

![image](https://user-images.githubusercontent.com/47070080/205069822-95b9fabb-a940-497b-aa2e-282a5a24c7b9.png)

**Comment by MrD-RC** [comment]
That character set is pretty much useless for a full INAV OSD. Looks like DJI have done it again.

**Comment by deethee** [comment]
Could you describe how you add the heartbeat or link the more detailed Information to that discord?

**Comment by MrD-RC** [comment]
I'm going to close this issue, as it is basically the same problem with issue https://github.com/iNavFlight/inav/issues/8578 That problem being DJI.
