### ISSUE TITLE
Zero looptime value problem

### ISSUE THREAD

**Issue by demvlad** [iNavFlight/inav#8605]
If i set looptime value to zero in cli (set looptime=0),
then INAV-configurator does not show configuration after connecting, and flight controller does not work. As write in help, valid value of looptime are 0....9000.

- FC Board name and vendor: Matek F411WSE
- INAV version string: 5.1, 6.0

**Comment by stronnag** [comment]
Don't do that then. 
The CLI comes with no guarantee to protect from stupidity.

**Comment by stronnag** [comment]
It is also documented behaviour.
https://github.com/iNavFlight/inav/blob/master/docs/Settings.md#looptime

**Comment by demvlad** [comment]
Thank you for answer.
I have read this information before. It is wrote : "Setting it to zero does 
not limit loop time, so it will go as fast as possible..."..
I thought this will work as described in this document... Ok, never mind, i 
will not do this in future...

Jonathan Hudson ***@***.***> 4 декабря 2022 г. 22:47:19 написал:
