### ISSUE TITLE
Heading is drifting to set position (F3 EVO with MAG)

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [iNavFlight/inav#861]
After first failed GPS POS HOLD test I tried my F3 EVO board on the desk and realized that the heading is drifting to some set position all the time, degree per second or so.

Problem existed even when powering from USB (no noise from BEC or ESC). Raw data in sensor tab looks OK, no drift there. Any idea what's wrong?

**Comment by stronnag** [comment]
You mag calibration values are bizarre. I don't use the on board (as I value my machines), but my on board mag appears to calibrate reasonably sanely:
````
set magzero_x = -100
set magzero_y = 464
set magzero_z = -231
````
Compare to your dump:
````
set magzero_x = -625
set magzero_y = -1
set magzero_z = -8777
````
To me it looks as if your calibration is bad, or the hardware is faulty.

**Comment by ArkadiuszNiemiec** [comment]
Yeah, that's the result of one of many fast calibration. 
I did proper one:
> set magzero_x = 287
> set magzero_y = 407
> set magzero_z = -1089

EDIT: I think that my screen was offsetting my heading... :D
I will have to test it on longer USB, but everything looks OK now, thanks!

**Comment by martindb** [comment]
Ekci how do you solve your problem? I have a sp racing f3 clone (banggood), and magnetometer is not holding the heading.... just drifting all the time. Tested with different versions and also cleanflight, same behavior. No magnetic fields near the board.
https://youtu.be/Fy_t_NbFGRY

**Comment by ArkadiuszNiemiec** [comment]
Sorry for this late answer. Electromagnetic interference from power distribution board was my main problem, nothing to do with software. I solved id by placing grounded copper plane between both PCBs.
Try testing it further away from your laptop.
