### ISSUE TITLE
Speedybee F7 V3 x8 DSHOT not working 

### ISSUE THREAD

**Issue by ITTV-tools** [iNavFlight/inav#8615]
## Current Behavior
Motor 6 is not working with DSHOT. 

## Steps to Reproduce
1. Set Mixer Profile to x8
2. Try to sping the motors

## Expected behavior
Motor should spin

## Suggested solution(s)
I have read someting Bitbang in Betaflight code. But I dont know how hard it is to implement.
---

Version: 6.0.0 FP1 Release Candidat

- FC Board name and vendor: SPEEDYBEEF7V3

**Comment by DzikuVx** [comment]
It's a know limitation. Use MULTISHOT protocol. There will be no flight performance degradation at all
