### ISSUE TITLE
Ublox and NMEA in GPS mixed up

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#862]
INAV/NAZE 1.4.0 Nov 28 2016 / 10:55:47

Have a CRIUS  cn 06 v2.0 GPS. configured 56700/5Hz with only NMEA protocol enabled.

Checked in U-Center. Have to activate Ublox protocol, to get gps working. NMEA and UBLOX seem to be mixed up.

**Comment by stronnag** [comment]
Which FC ? See also https://github.com/iNavFlight/inav/wiki/Hardware-and-feature-support-map

**Comment by ghost** [comment]
Sorry. Flip32+ with bt slave on uart1 and crius gps on uart2

**Comment by stronnag** [comment]
No problem, it helps to read the documentation before opening issues. Closing.
