### ISSUE TITLE
iFLIGHT BLITZ F722 Barometer and Magnetometer not recognised

### ISSUE THREAD

**Issue by dzaro-dev** [iNavFlight/inav#8629]
## Current Behavior
MODEL: Stock confighuration of iFLIGHT BOB57 (old Vista version, not O3 Air Unit version)
After flashing INAV 5.1.0 (latest stable) to iFLIGHT BLITZ F722, the barometer and magnetometer are not recognised.
The magnetometer is not recognised when power is connecte to the iFLIGHT GPS unit.
The bareomter is not recogines when power is connected via the USB-C port. 
PS: Some images of the FC board do not show the barometer in the location where it should be. I can confirm that mine has one soldered on and it works fine in Betaflight. 

## Steps to Reproduce
1. Flash INAV 5.1.0.
2. Load defaults for 3-7" quad.
3. Go to "Configuration" tab 
4. Change I2C speed from 400 to 800kHz.
5. Chnage Barometer from "None" to "DPS310"
6. Change Magentometer from "None" to "QMC5883".
7. Press "Save and reboot"

## Expected behavior
Both magnetometer and barometer should be recognised but are not. 

## Suggested solution(s)
Check the firmware target for iFLIGHT BLITZ F722. There seems to be some issue with how the I2C is configured.
EDIT: Target seems to be OK. I2C SCL and SDA are on PB8 and PB9, respectively as they should be.
EDIT2: There are some major differences in the **barometer_dps310.c** files of [INAV](https://github.com/iNavFlight/inav/blob/master/src/main/drivers/barometer/barometer_dps310.c) and [Betaflight](https://github.com/betaflight/betaflight/blob/master/src/main/drivers/barometer/barometer_dps310.c), which might help in identifying why the Barometer is not recognised or read correctly. 

## Additional context
- FC Board name and vendor: iFLIGHT BLITZ F722
- INAV version string: 5.1.0 (76f22b25)

**Comment by b14ckyy** [comment]
If this is still n issue with 7.0 or 7.1 We will reopen. Close for now

**Comment by b14ckyy** [comment]
@antichamber try the build from my post here: https://github.com/iNavFlight/inav/issues/9826#issuecomment-2052084512
you probably have a new version and I added the ICM gyro to the target for 7.1.1 patch. 

Baro is porobably a FC design issue. It should work if you connect the battery first and then USB. Seems like that baro error happens only when FC is powered by USB alone.
