### ISSUE TITLE
MAMBAH743_2022B board orientation wrong

### ISSUE THREAD

**Issue by PhilippMolitor** [iNavFlight/inav#8645]
## Current Behavior
The `MAMBAH743_2022B` is the updated variant of the `MAMBAH743` board, which features ICM-42688 Gyros instead of the previously used MPU6000 or BMI270.
It seems like the default gyro orientation from the predecessor board is still applied to the new `_2022B` variant, which results in an orientation that is off by 90°.

## Steps to Reproduce
Install the default target and change nothing in the configuration.

## Suggested solution(s)
I set the board yaw orientation to `-90`, this aligned the board correctly in the 3d view. Unfortunately I don't know the correct Syntax for INAV target code, otherwise this would have been a pull request.

---

- FC Board name and vendor: MAMBAH743_2022B 
- INAV version string: 6.0.0-FP1

**Comment by DzikuVx** [comment]
Was fixed in #8505
