### ISSUE TITLE
Probleme Raper extrem Foxeer Inav

### ISSUE THREAD

**Issue by Fabwize** [iNavFlight/inav#8647]
how can we enter the VTX tables of the reaper extrem foxeer don inav 5.1 and inav 6

when I look at the frequencies and power in the osd, I only see 0 in power and ..../0 in frequency as the value that appears.
it is connected in serial port 2 as described by Mateksys and also in Serial 2 Tramp , in the port tab of inav.

I don't have this problem with the TBS unify, and I tried with 2 different reaper extrem foxeer, same problem.

thanks.

- FC Board name and vendor: F411WTE MATEK
- FC boead name H743 Wlite Matek
- INAV version string: 6.O FF2

**Comment by MrD-RC** [comment]
There are no VTx tables in INAV.

**Comment by Fabwize** [comment]
> Il n'y a pas de tables VTx dans INAV.

is there a solution to make the VTX reaper extrem work with the smart audio correctly ?

**Comment by MrD-RC** [comment]
@Fabwize I don't have that VTx. Could you try this to see if the power works.

[inav_6.0.0_MATEKF411TE.zip](https://github.com/iNavFlight/inav/files/10308011/inav_6.0.0_MATEKF411TE.zip)

**Comment by Fabwize** [comment]
@MrD-RC 
hello, I have already tried, when the frequency and power are displayed on the OSD, it displays ../0
the power remains blocked in 25mw while I ask for tramp power 5=600mw=2.5w Foxeer Reaper extrem

**Comment by Fabwize** [comment]
@MrD-RC thanks, i will try quick

**Comment by Fabwize** [comment]
@MrD-RC  this file dont work in CLI
where i ave to put?

**Comment by MrD-RC** [comment]
> @MrD-RC  this file dont work in CLI
> 
> where i ave to put?

It's firmware. You need to flash it to the flight controller. Make sure to make a 'diff all' of your current setup. You will need to use the 6.0 FP2 version of Configurator too. I this works, I can submit the change to be in INAV 6.0.

**Comment by Fabwize** [comment]
@MrD-RC I just flashed, it does not work, there is no more compass, GPS, pitito, there is nothing in blue at the top of the page and the frequency and power channels do not change either.

**Comment by MrD-RC** [comment]
That is setup. The things that changed had nothing to do with the compass etc.

**Comment by Fabwize** [comment]
@MrD-RC 
<img width="1280" alt="Capture d’écran 2022-12-27 à 18 26 42" src="https://user-images.githubusercontent.com/120101738/209702470-b66d7233-63b7-4a35-9a1a-8ccd01dbafde.png">
<img width="1280" alt="Capture d’écran 2022-12-27 à 18 26 34" src="https://user-images.githubusercontent.com/120101738/209702484-a0adeae1-d769-4791-a941-754d5120eb1d.png">

**Comment by Fabwize** [comment]
IF is possible, i need target for F411TWE and H743Wlite . is for F411TE fror nanodrak, H743Wlite for caipirina V2.
thanks.

**Comment by MrD-RC** [comment]
This firmware was just to test, not to fly with.

**Comment by Fabwize** [comment]
@MrD-RC thanks i anderstand. but no irc tramp connexion no work.
i cant change fréquency , band and power level

**Comment by Fabwize** [comment]
I welded in serial 2 on the FC

<img width="1280" alt="Capture d’écran 2022-12-28 à 22 10 19" src="https://user-images.githubusercontent.com/120101738/209872568-ae502b20-22e3-4258-b4c1-5b5d9ab7c8e0.png">

**Comment by MrD-RC** [comment]
[inav_6.0.0_MATEKF411TE.hex.zip](https://github.com/iNavFlight/inav/files/10321894/inav_6.0.0_MATEKF411TE.hex.zip)

I did notice that there was a discrepancy in the power names. So this may have caused an issue. If not, then it is more than just the power table that is the issue.

**Comment by Fabwize** [comment]
@MrD-RC  i juste try, exacly the same. the vtx dont change fréquancy and chanel, only the osd change.
thanks

**Comment by Fabwize** [comment]
@MrD-RC Happy new year, 
do you whant i send to you the VTX?
i dont want no money, i send you free. 
just if you can re send to me, when you finish work? if you cant , is not too bad.

**Comment by Fabwize** [comment]
@MrD-RC Hello, i progress
 mabe is beacose the F411twe dont ave serial port.
ST2 is soft serial. ans smart audio good work on soft serial, but irc tramp dont work.

i ave H743Wlite. 
can you give to me a target to try with dem?
and tel me who to soldering .

<img width="1280" alt="Capture d’écran 2023-01-03 à 09 39 50" src="https://user-images.githubusercontent.com/120101738/210323671-96c80675-748b-49f8-b0da-c919070148f2.png">

**Comment by MrD-RC** [comment]
I've used IRC Tramp on SoftSerial with a Matek VTx and it works fine. Unfortunately I have no time to look at this at the moment. I am away with work.

**Comment by Fabwize** [comment]
Thanks for the answer, i anderstand, no time everytime.
soft serial and irc tramp is a bad combo. sometime work sometime dont work, i try all ready with the originaly VTX Tramp.
dis is beacose cant change baude or nothing , this soft serial is a emulation da uart.
i will try on H743Wlite and comeback with you.
thanks again for your time and work.
