### ISSUE TITLE
Angle Flight Mode for Boats and Rovers

### ISSUE THREAD

**Issue by DaveBow12** [iNavFlight/inav#8650]

**Comment by DzikuVx** [comment]
But what would Angle Domin those cases?

**Comment by stronnag** [comment]
In any case, the hydrodynamics involved are way beyond the capabilities of INAV. Maritime auto-pilots are a very different domain, sailing APs even more so.

**Comment by DaveBow12** [comment]
Angle can easily adjust hydro foils just as it sdjusts the ailerons and elevator of fixed wing planes to keep the boat level.
Yes hydro dynamics are different and more powerful servos may be required.  Others have already been doing this by programming there boat as an airplane and they have made it work.  There are also boats that use air wings, just like race car wings, to keep boats level.  I expect this is an easy change so why not make Angle availabe in the boat and rover configuration?
