### ISSUE TITLE
Skipping UART2 pins is not done in a board-independent way

### ISSUE THREAD

**Issue by Linjieqiang** [iNavFlight/inav#866]
Recently,I use STM32F1 chip to make my mini brushed copter.But I found if I opened the GPS with UART2,the motor M2 & M4 can not move.I try to use other timer but it didn't work.So I think maybe some bugs in the timer and uart2.

This is my mini brushed copter design chart.I want to use GPS with uart2 and use telemetry with uart1.Looking forward to your reply.

[image](https://cloud.githubusercontent.com/assets/10217966/20925582/c7a24410-bbf2-11e6-96e9-e64913dad337.png)

**Comment by digitalentity** [comment]
@Linjieqiang what target?

**Comment by Linjieqiang** [comment]
My new define target.
![image](https://cloud.githubusercontent.com/assets/10217966/20925965/ee1c2afa-bbf4-11e6-9ea6-7b5871e68623.png)
![image](https://cloud.githubusercontent.com/assets/10217966/20925967/f1f66816-bbf4-11e6-8ea1-f19c62210049.png)
![image](https://cloud.githubusercontent.com/assets/10217966/20925971/fb782cbc-bbf4-11e6-9983-411eb3d0f198.png)

**Comment by digitalentity** [comment]
F1 or F3?

**Comment by Linjieqiang** [comment]
F1.But I think CC3D & NAZE have the same problem.

**Comment by digitalentity** [comment]
CC3D and NAZE doesn't have this problem

**Comment by Linjieqiang** [comment]
But what's wrong with my target?I haven't found the problem.

**Comment by digitalentity** [comment]
Ok, this is not affecting other targets by coincidence.

NAZE target have PWM3 and PWM4 channels dedicated for PWM receiver, and those are shared between UART2 and PWM inputs. I'll fix the underlying issue. Stay tuned.

**Comment by Linjieqiang** [comment]
But what should I do to let my new mini copter fly?

**Comment by digitalentity** [comment]
@Linjieqiang have a look at 34ae508b1cc720f38164c38d2818bbfbfde8c057

**Comment by Linjieqiang** [comment]
OK.Let me have a check.

**Comment by Linjieqiang** [comment]
I just had a try and it worked!Amazing!Thanks @digitalentity

**Comment by digitalentity** [comment]
@Linjieqiang no problem. It's a long lurking issue. We have only a few F1 targets, so we never noticed before.

**Comment by Linjieqiang** [comment]
OK.I closed the issue.
