### ISSUE TITLE
5.1.0 complete configuration wiped after trying to access vtx from OSD

### ISSUE THREAD

**Issue by Davidsastresas** [iNavFlight/inav#8685]
I had a working setup based on h743 slim.

I have a vtx hdzero freestyle connected only to serial port ( no smartaudio ) using MSP. 

I tried to access the vtx settings by osd, and after changing the channel and going to set, the FC started beeping and after connecting to the configurator, everything was wiped.

Any thoughts?

**Comment by b14ckyy** [comment]
You should not enable MSP for HDZero. This is not betaflight. You enable HDZero on the Peripherals tab (if it is 5.1) or MSP-Displayport (6.0 FP1 and newer)

not sure why it wiped but maybe HDZero has sent a command over MSP to inav that caused a corruption of the config.

**Comment by Davidsastresas** [comment]
Understood. Thank you!
