### ISSUE TITLE
TBS smartaudio using mateksys f411-wte and atlatl hv micro V2 not working

### ISSUE THREAD

**Issue by ashewan** [iNavFlight/inav#8687]
# version
# INAV/MATEKF411TE 5.1.0 Aug 19 2022 / 12:19:47 (76f22b25)
# GCC-10.2.1 20201103 (release)
Target
FCF411-FTE
Makefile
MATEKF411TE
Receiver is a FrSky ARCHER M+
Camera RunCam model Phoenix 2
Video TX Atlatl HV micro

Connections as per MATEKSYS F411-WTE product page:
Video to ST2
SmartPort to ST1
In INAV Ports SOFTSERIAL1 set to Telemetry SmartPort Auto
SOFTSERIAL2 set to Peripherals TBS SmartAudio 115200

Yaw left Pitch forward brings up OSD menu
'Features' lists VTX but no SA or TR and operations eg power, change screen value but not on Video Tx

CLI set vtx ops do not work eg set vtx_band=4 neither does programming as per Pawel Spychalski.

Everything else working 
Anybody got the Pawel method working at least?
Thanks

**Comment by b14ckyy** [comment]
Seems like no one was able to look into this. 
Don't know if this is still an issue but most likely a compatibility issue with teh specific VTX. As F411 goe EOL and won't get official updates anymore, its unlikely this will be investigated further. Going to close.
