### ISSUE TITLE
Just wondering why there is no kakuteh7v2 target listed for inav 6 fp1? It's relatively new but there's a target for inav 5.1. I checked using the configurator flash firmware dropdown and at the github release page.
 Thanks

### ISSUE THREAD

**Issue by Junnicutt** [iNavFlight/inav#8692]
**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
5.1 was release after 6.0FP1
