### ISSUE TITLE
Matek F405 WMN and Jeti Receiver - how to setup connection

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8701]
Trying to setup my Jeti with the Matek F405 WMN
Connecting the Jeti with SBUS or JETIEXBUS to the WMN Board to Pin SBUS is not working.

At INAV the Port UART2 and RX= Serial RX

But nothing is working on Jeti TX-RX
The FC itself works, meaning the Servos are working, GPS is working and the Motor could be activated by INAV

Could anyone give me some hints how to connect the Jeti Receiver to the Matk F405 WMN?

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by RoadyFPV** [comment]
Connect your Reciever to UART TX!
Setup your RX port you are using to EX BUS
Choos Serial RX in configurator on the UART u have connected the RX 
Setup Serial Reciever and provider is JETI EXBUS

**Comment by RoadyFPV** [comment]
[How to setup your RX and FC for Jeti Ex-Bus.pdf](https://github.com/iNavFlight/inav/files/10611019/How.to.setup.your.RX.and.FC.for.Jeti.Ex-Bus.pdf)

maybe helpful

**Comment by RobinatiNav** [comment]
Hi boomerschnecke, I am interested how it went. Did you manage to use JETIEXBUS in iNav? If so, is it reliable? Do you fly it often? Many thanks for your answers.

**Comment by boomerschnecke** [comment]
Hi RobintiNav, 
it was working successfully. But not very stable in my eyes.
You have to do an resisitor with 1.2k within Rx und Tx at the FC. Look into Jeti pages. There you find an description.
All telemetry was working well. But the reaction from tranmitter to FC was not very stable. Or sometimes it seems to be some delay within. 
So I switched back to SBUS. This works well up to now

**Comment by RobinatiNav** [comment]
Hi, thank you :) check this #7672

**Comment by RoadyFPV** [comment]
> Hi RobintiNav, it was working successfully. But not very stable in my eyes. You have to do an resisitor with 1.2k within Rx und Tx at the FC. Look into Jeti pages. There you find an description. All telemetry was working well. But the reaction from tranmitter to FC was not very stable. Or sometimes it seems to be some delay within. So I switched back to SBUS. This works well up to now


marv-t optimized the code on betaflight, so no resistor is necessary any more. after that optimation no problems at all.
than he implemented the code to inav... no problem.

After INAV switched to GCC10 the issue still exists..
Same happens to betaflight after switch to gcc10..

**Comment by RoadyFPV** [comment]
Pls read also

Line 35

https://github.com/iNavFlight/inav/blob/master/src/main/rx/jetiexbus.c

**Comment by boomerschnecke** [comment]
Thanks for the information
if the resistor is not necessary any more, how to do the connection?
Could the SBUS connection than be used for JetiEX Bus connection? Or how to connect this physically correctly?

**Comment by RoadyFPV** [comment]
no only solder your wire coming from your Reciever directly to the UART TX PIN on the FC thats all

**Comment by RobinatiNav** [comment]
- connect receiver signal cable to Tx port.
- choose EXBUS for serial port in device Explorer
- 
![Snímka obrazovky 2023-03-26 o 12 52 42](https://user-images.githubusercontent.com/123115426/227770961-fc97e1fc-2f3c-4db2-bd21-ef69afa8a91f.png)
<img width="1199" alt="Snímka obrazovky 2023-03-26 o 12 53 16" src="https://user-images.githubusercontent.com/123115426/227770968-7f74236a-3957-42d1-bb7b-04909236f0ed.png">

**Comment by boomerschnecke** [comment]
Thank you for information

**Comment by boomerschnecke** [comment]
Hi RobinatiNav, I would like to know, if the system really works if you only connect the Tx from the FC to the Jeti receiver. Jeti Telemetry should work fine, but what about the stick commands the receiver is transferring to the FC? 
An connection to Rx of the FC should also be necessary? Or not?
Best regards

**Comment by RoadyFPV** [comment]
> [How to setup your RX and FC for Jeti Ex-Bus.pdf](https://github.com/iNavFlight/inav/files/10611019/How.to.setup.your.RX.and.FC.for.Jeti.Ex-Bus.pdf)
> 
> maybe helpful

**Comment by boomerschnecke** [comment]
Thanks for the quick response.
I was just wondering because its a bidirectional communication line but only Tx is used......
So this works for telemetry of Jeti AND with Jeti Transmitter stick commands?

**Comment by boomerschnecke** [comment]
I will try it
Thank you

**Comment by RoadyFPV** [comment]
Jea it works fine, until inav is using GCC10. 
Only use GCC9 comiled versions for flights

**Comment by boomerschnecke** [comment]
Ok, but sorry, how can I do this? Do I have to compile myself? Up to now I´m using the files from the INAV Downloads directly.

**Comment by RoadyFPV** [comment]
U can flash a version and check with cli command "version" the gcc version is it not GCC10 its fine.
If u are able to compile it yourself u can use the newest version of inav

**Comment by boomerschnecke** [comment]
So checked it: Version is GCC-10.2.1 
So this means I would have to compile the source code by myself with GCC9 ?
Do you know the background why it works with GCC9 and not with GCC10?

**Comment by boomerschnecke** [comment]
can you please send a download link to me for the compiler? Is it free?

**Comment by RoadyFPV** [comment]
The FC is freezing. we dont  know why but with gcc9 there is no issue.

for compiling:
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20or%2011%20with%20MSYS2.md
