### ISSUE TITLE
Motor activation only possible if Arm State was activated und deactivated 5 times

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8721]
Motor is only working if Arm State is reached after 5 times been activated and deactivated
Otherwise not working
Why is this the case? 
Is there any other possibility to get the motor working?

Inav 5.1  Matek F405WMN 

**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by MrD-RC** [comment]
You likely have something blocking arm. Look at the system messages in your OSD or type status in to the CLI.
