### ISSUE TITLE
Target MAMBAH743 2022B - board alignment seams incorrect

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#8724]
## Current Behavior
Just tried to maiden a Quad with the above target. Turned out that I had to correct the `alignment_board_yaw` param to the value `-900` in order to get the orientation right.

I double checked the marking on the board and I had build it in accordingly!
![MK4-H743-V2_F55_700x](https://user-images.githubusercontent.com/8381714/213867008-01af8b38-9dd1-4aec-8ebb-f7f852076120.jpg)

After arming it freaked out entirely and crashed!

## Steps to Reproduce
1. flash the Target MAMBAH743 2202B to the Board
2. arm the quad and launch
3. your quad will freak out as it doesn't seem to have the right orientation
4. hope the quad survived
5. add `set align_board_yaw = -900` and save
6. launch ... and fly! :)

## Expected behavior
I would have assumed the quad to fly properly as the markings are correct. Perhaps somebody could confirm this. The Board was purchased in December 22 directly from Diatone.

## Suggested solution(s)
change the Target to have and -90° alignment on yaw axis. Perhaps it's to be done in the file `target.h`

---
- FC Board name and vendor: INAV/MAMBAH743_2022B 
- INAV version string: 5.1.0 Aug 26 2022 / 10:04:28 (b63e68a6)

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav/pull/8505
