### ISSUE TITLE
SpeedyBee F405 V3 uSD card vs OSD interference

### ISSUE THREAD

**Issue by Pedrolomel** [iNavFlight/inav#8733]
Hello
       I found issue with OSD interference(or even OSD disappear) when uSDHC card(4GB) is inserted for blackbox logging. Tested for two FCs copies and different uSDHC cards. 

FC: SpeedyBee F405 V3
FW: iNAV 5.1

**Comment by Pedrolomel** [comment]
Hellow

Some screenshots documenting current issue:

Without uSD card:

![Screenshot_20230127-143743](https://user-images.githubusercontent.com/123595258/215101523-fc392fa9-af2f-45b0-bad2-590767a5e06d.png)
 
uSD card inserted:

![Screenshot_20230127-143717](https://user-images.githubusercontent.com/123595258/215101858-7f1fbc16-1664-4592-a680-0109c6542ecf.png)

**Comment by Phil-MC** [comment]
How was it formatted? 
Did you follow speedybee or Inav guidlines for formatting?

**Comment by Pedrolomel** [comment]
Yes, but It doesn't matter. I have formatting using SDcard tool from SD org. page.

**Comment by Phil-MC** [comment]
OK, it makes the information more complete. Windows 10 doesn't offer it any more. Sent from Outlook for Android

**Comment by girgine** [comment]
Hi Pedrolomel, I have the same FCC but after flashing 5.1 , I cant access to the FCC (USB time-out error), is there a specific instruction to flash this FCC with INAV? did you use the standard firmware that came with INAV 5.1?
thanks

**Comment by Phil-MC** [comment]
You must use the firmware name provided by speedybee on their website. I did, and it worked . Did you choose v3?

**Comment by girgine** [comment]
they just point to inav 5 to their web site, I didnt see a firmware file , was there? (checking it again..) thanks
I did choose v3 from inav 5.1 flasher, it does the flash without an issue but then cant connect to FCC.. (if chose only F405, it can connect but its not my fcc ..)

**Comment by Pedrolomel** [comment]
> You must use the firmware name provided by speedybee on their website. I did, and it worked . Did you choose v3?

Yes. I have chose firmware for target SPEEDYBEEF405V3.

**Comment by Pedrolomel** [comment]
> they just point to inav 5 to their web site, I didnt see a firmware file , was there? (checking it again..) thanks I did choose v3 from inav 5.1 flasher, it does the flash without an issue but then cant connect to FCC.. (if chose only F405, it can connect but its not my fcc ..)

Remove SD card (If inserted). With some SD cards,  SpeedyBee F405V3 can't connect to configurator.

**Comment by girgine** [comment]
Wow! removed the SD-Card and it worked - cant believe this :(

thanks very much! it seems I need to look for another SD-card then :)

**Comment by Phil-MC** [comment]
The file isn't there but the name of the firmware is.SPEEDYBEEF405V3There are issues with the SD CARD. The system uses the card in a way it was not designed for and thus has speed problems. T'm experimenting at the moment.Sent from Outlook for Android

**Comment by Pedrolomel** [comment]
> Wow! removed the SD-Card and it worked - cant believe this :(
> 
> thanks very much! it seems I need to look for another SD-card then :)

I'm afraid it doesn't solve problem. I have switched off OSD on iNAV config. tab. After that, all uSD cards has recognized properly by FC and connection problems disappear. I gues, the problem is related  to the conflict between OSD chip and uSD cards. In short, OSD and uSD can't works together.

**Comment by Phil-MC** [comment]
That finding is very interesting. Is the OSD interaction with the SD card affected by loading an OSD FONT in the Configurator?Sent from Outlook for Android

**Comment by Phil-MC** [comment]
I have tried turning off the OSD myself and the BlackBox log is recorded on an ordinary SD card as you say. So I can cofirm this anomaly.

**Comment by Pedrolomel** [comment]
> I have tried turning off the OSD myself and the BlackBox log is recorded on an ordinary SD card as you say. So I can cofirm this anomaly.

**Comment by Phil-MC** [comment]
I notice in the Flight Modes section of the speedybee app there are two related ones:
Enable/Disable BlackBox Recording
Enable/Disable OSD
So it is possible to set a Transmitter switch to select one combination or the other.

**Comment by Pedrolomel** [comment]
With Betaflight firmware, OSD and blackbox logging simultaneously works fine. In my opinion the fault is on iNAV side.

**Comment by Phil-MC** [comment]
INAV requires deep access to the FC in order to provide functions that are not available in BetaFlight. The OSD and BlackBox functions occupy the same internal bus in the design of the FC. This is what causes the issue.Sent from Outlook for AndroidFrom: Pedrolomel ***@***.***>Sent: Thursday, 2 February 2023, 08:11To: iNavFlight/inav ***@***.***>Cc: Philip ***@***.***>; Comment ***@***.***>Subject: Re: [iNavFlight/inav] SpeedyBee F405 V3 uSD card vs OSD interference (Issue #8733)
With Betaflight firmware, OSD and blackbox logging simultaneously works fine. In my opinion the fault is on iNAV side.

**Comment by Pedrolomel** [comment]
> INAV requires deep access to the FC in order to provide functions that are not available in BetaFlight. The OSD and BlackBox functions occupy the same internal bus in the design of the FC. This is what causes the issue.Sent from Outlook for AndroidFrom: Pedrolomel ***@***.***>Sent: Thursday, 2 February 2023, 08:11To: iNavFlight/inav ***@***.***>Cc: Philip ***@***.***>; Comment ***@***.***>Subject: Re: [iNavFlight/inav] SpeedyBee F405 V3 uSD card vs OSD interference (Issue #8733) With Betaflight firmware, OSD and blackbox logging simultaneously works fine. In my opinion the fault is on iNAV side. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

There is no such issues on MATEK targets with iNAV firmware. if on MATEK targets iNAV works, so It could work on SpeedyBee target....I hope.

**Comment by shirase** [comment]
I tried decreasing SDCARD_BUS_SPEED BUS_SPEED_SLOW and max7456Init BUS_SPEED_SLOW. It helped me.

**Comment by shirase** [comment]
> I tried decreasing SDCARD_BUS_SPEED BUS_SPEED_SLOW and max7456Init BUS_SPEED_SLOW. It helped me.

I did some tests. And it works absolutely unstable. OSD disappears. After 30 seconds the logs stops. But you can connect to the FC with SD card and OSD.

**Comment by shirase** [comment]
If disable DEVFLAGS_USE_MANUAL_DEVICE_SELECT for DEVHW_SDCARD then everything works. 

https://github.com/iNavFlight/inav/commit/8913f6c4366b6eb4853cbefb4c9e9d6ef55c0edc

**Comment by Phil-MC** [comment]
Thanks for the update.

**Comment by shirase** [comment]
I can't figure out what DEVFLAGS_USE_MANUAL_DEVICE_SELECT is used for. Who knows? What does it affect?

**Comment by Phil-MC** [comment]
Thanks for the update.
I don't recognise the CLI entry, where did you get it from?

**Comment by shirase** [comment]
This is from the inav code. You can try the compiled version.
https://disk.yandex.ru/d/8qYjAU4mwVU71g

**Comment by Phil-MC** [comment]
Thanks, so that wasn't a CLI entry. Was it from target.c ?

**Comment by Phil-MC** [comment]
I have verified that the Configurator will not connect unless the Blackbox SD CARD is removed.

**Comment by Pedrolomel** [comment]
https://github.com/iNavFlight/inav/issues/8733#issuecomment-1408457424

**Comment by Phil-MC** [comment]
I have found that with WalkSnail Avatar set there is no problem with having Blackbox and OSD in use at the same time. I don't know if this is as a result of the fix or because of the MSP Display Port use.
