### ISSUE TITLE
Linear Descent radius relative to the home point

### ISSUE THREAD

**Issue by beeonlinecy** [iNavFlight/inav#8739]
## Current Behavior
In case if AT_LEAST_LINEAR_DESCENT mode is used for RTH, 
the aircraft will start descending immedieately and all the way towards the home point.

## Desired Behavior
Would be more logical to set a radius around the home point of where the 
linear descent will start.

## Who does this impact? Who is this for?
Airplane users

## Additional context
In some cases you have to gain higher than AT_LEAST altitude in order to have good signal, 
but in the case where RTH has started, the plane will descend immediately, being 1/2 of the max altitude
on the 1/2 way home, causing a risk to not get your signal back even on 1/2 way to home.
If the linear descent would start at the desired distance to home, this would both achieve economy during rth
(Economy is necessary during RTH because we want our model back safe) and higher brobability of getting 
your control back much prior to reaching home point

**Comment by b14ckyy** [comment]
I actually like that Idea!
