### ISSUE TITLE
Add MSP VTX functionality

### ISSUE THREAD

**Issue by MartinHugh** [iNavFlight/inav#8750]
## Current Behavior
Currently VTX control is available via Smart Audio.   This requires a dedicated UART
Betaflight and Quicksilver now use MSPVtx (for OpenVTX and HDZero) which uses the MSP UART to control the VTX.

## Desired Behavior
Implement MSP VTX, so that MSP protocols encompass VTX control, thereby saving a UART

## Who does this impact? Who is this for?
Any iNav user who may want Smart Audio commands without needing a dedicated UART

An added benefit is that any iNav users of HDZero Whoop vTXs (which do not support Smart Audio) would now have the ability control the vtx from the transmitter by using MSPVtx over the existing MSP UART

Edit: Also note that the lack of this functionality means that iNav users cannot make use of ELRS backpack functionality

**Comment by sebas1984x** [comment]
We need this!

**Comment by robhaswell** [comment]
There is also the 500mW double-stack board, which is great for wings, that does not support Smart Audio.

**Comment by DerWolle82** [comment]
We realy need this!

**Comment by MartinHugh** [comment]
Another strong requirement for this is that ELRS Backpack (which allows users to change channels on both goggles and aircraft, sumultaneously, from a LUA command), is not usable with iNav.  

This is because the part which commands the vtx to switch channels requires MSP-VTX.

**Comment by MrMap** [comment]
I must admit that it took me some time of trying and trying to control the HD Zero Freestyle VTX via the UART, only before I had to realize that it could not work without SA (simplex and one extra UART). 
I thought well I remember that years ago TBS has VTX control over UART for analog VTX, surely the same concept (now MSP VTX) is available in iNav 6.1?! Nope. 
Well - I hope this is on the devs prio list - it would be so nice.

**Comment by sebas1984x** [comment]
> I must admit that it took me some time of trying and trying to control the HD Zero Freestyle VTX via the UART, only before I had to realize that it could not work without SA (simplex and one extra UART). I thought well I remember that years ago TBS has VTX control over UART for analog VTX, surely the same concept (now MSP VTX) is available in iNav 6.1?! Nope. Well - I hope this is on the devs prio list - it would be so nice.

https://github.com/hd-zero/hdzero-vtx/pull/141

**Comment by DzikuVx** [comment]
Added in #9166
