### ISSUE TITLE
LEDs not working on iFlight BLITZ F722 and BLITZ F722 MINI

### ISSUE THREAD

**Issue by dzaro-dev** [iNavFlight/inav#8757]
## Current Behavior
After enabling support for LED strip and configuring the "0th" LED to be any arbitrary color, the LED does not turn on no matter what.

## Steps to Reproduce

1. Flash INAV 6.0.0 (FP1 or RC1) with full chip erase enabled.
2. Enable support for multicolor LED strip in INAV configurator. 
![image](https://user-images.githubusercontent.com/23706061/216050722-d2cff745-a9c2-4334-9f96-d13d50615115.png)
3. Open LED tab, select Wire Ordering Mode and select any point to see a zero diplatyed.
4. Exit Wire Ordering Mode and select a solid color (any).
5. Plug in the battery and the LED does not turn on. 

## Expected behavior
After plugging in the battery, the connected LED shoudl come on. The functinality of the LED has previously been verified when Betaflight was flashed and the LED was working fine. I have also tested previous versions of INAV and those didn't work either.

## Suggested solution(s)
There might be a slight difference in the way the LED driver is written in Betaflight and INAV and it may be that the incorrect pad on the FC is used to output the LED signal. I tried to trace the relevant pad to check what exactly is connected betwwen the LED connector and the F722 processor, but do to passive components in te way, I was not able to determine which pin is indirectly connected to that pad. 

Here is the difference:

BF:
resource LED_STRIP 1 A08
resource LED 1 C15

INAV:
C15: LED1 OUT

![image](https://user-images.githubusercontent.com/23706061/216051245-fc0cb5ad-6397-4a51-b0ef-484805c1a8b6.png)

![image](https://user-images.githubusercontent.com/23706061/216052863-bb61bbf4-c36b-4cc9-9632-590b053ba3f5.jpg)

## Additional context

version
INAV/IFLIGHT_BLITZ_F722 6.0.0 Oct 20 2022 / 14:35:29 (d1f6f19a)
GCC-10.2.1 20201103 (release)

**Comment by mmosca** [comment]
The pin definitions match.

LED_STRIP in BF is called WS2811_PIN in INAV and is defined as PA8, same as BF.

I don't have hardware to test, but the pin definition is not the problem.
PC15 should be the status led.

**Comment by mmosca** [comment]
Can you share a dump of your config and screenshot of the configurator with the LED assignment?

**Comment by bishko** [comment]
I've attached the dump files for both INAV and BTFL here:

[INAV_6.0.0_cli_BOB57.txt](https://github.com/iNavFlight/inav/files/10568440/INAV_6.0.0_cli_BOB57.txt)
[BTFL_4.3.2_cli_BOB57.txt](https://github.com/iNavFlight/inav/files/10568441/BTFL_4.3.2_cli_BOB57.txt)

**Comment by bishko** [comment]
@mmosca Your change fixed the LED issue !

Thank you very much !

**Comment by bishko** [comment]
@mmosca Your change fixed the issue and you were right about the timing being an issue. 

Thank you very much for your help!

**Comment by mmosca** [comment]
I will a

**Comment by mmosca** [comment]
I will submit a pull request next week, and close this issue when merged. Does the blitz mini use the same target?

**Comment by bishko** [comment]
Yes, it does. 
Some guy wrote to me on discord and I sent him your hex so that he can try. 
He flashed it and told me that it worked for his F722_MINI as well.

**Comment by timotrino** [comment]
I confirm it worked on my Blitz F722 mini.
Thank you @mmosca !

**Comment by thephantom07** [comment]
Hello I am having same problem with the BLiTZ Mini F7 V1.2, leds not working, shall I just update the firmware to the newest version 4.5.0? Or what I shall I do? Thank you. 
![image](https://github.com/iNavFlight/inav/assets/21017667/2b708f27-3496-4210-b2d9-4fa68adc46ae)

**Comment by sensei-hacker** [comment]
> Hello I am having same problem with the BLiTZ Mini F7 V1.2, leds not working, shall I just update the firmware to the newest version 4.5.0? Or what I shall I do? Thank you. ![image](https://private-user-images.githubusercontent.com/21017667/341654752-2b708f27-3496-4210-b2d9-4fa68adc46ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTAyNjYsIm5iZiI6MTcxODk0OTk2NiwicGF0aCI6Ii8yMTAxNzY2Ny8zNDE2NTQ3NTItMmI3MDhmMjctMzQ5Ni00MjEwLWIyZDktNGZhNjhhZGM0NmFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2MDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMzE1NWZkNDZmZmM0YTA0NmI0ZWRkNDAwNjE3ZGE3NmExMGU0YTJhMTE1M2ZhYmMxYzE5MmMyOTAzM2IzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.soP7lK6hZHtXy21P1-T9f9GBlRcWHXYN5FUQeOdaGyY)


The newest version of INAV (7.1.2) will fix it.
Your screenshot is Betaflight, an entirely different firmware with their own GitHub. For questions about *Betaflight*, it would be best to ask the Betaflight folks.
