### ISSUE TITLE
LEDs not working on Matek F405-WSE

### ISSUE THREAD

**Issue by Andy0679** [iNavFlight/inav#8758]
When trying to set LEDs on LED tab in Configurator 6 RC 1 the squares don't show a number nor stay selected.

**Comment by cmanley** [comment]
I've got the same firmware and board and the LEDs work for me.
My settings for wing tip nav lights:
```
feature LED_STRIP
led 0 0,0::CIWE:2
led 1 1,0::CIWE:6
```

**Comment by Helipro** [comment]
> When trying to set LEDs on LED tab in Configurator 6 RC 1 the squares don't show a number nor stay selected.
Or you using orientation tags?  I couldnt get leds to save if orientations were selected in 6.1 or .6.2.
https://github.com/iNavFlight/inav/issues/8823

**Comment by dzhibas** [comment]
i do have configurator 6.1.0 with matek f405-wse and led strip shows me "0 remaining" but through CLI with commands like
```
led 0 0,0::CIWE:2
led 1 1,0::CIWE:6
etc...
```

stuff works. why is it "0 remaining" in UI and not able to select leds

**Comment by dzhibas** [comment]
Oh, i'v upgraded to latest target and LED Strip started to work:
![image](https://github.com/iNavFlight/inav/assets/400147/7dbe3430-7838-4ece-a6e0-59d9f45ea4c0)
![image](https://github.com/iNavFlight/inav/assets/400147/34676a82-199e-4d9a-b1c4-d67fedbd0b0d)

i have no issues anymore
