### ISSUE TITLE
Mag spikes filtering (feature request)

### ISSUE THREAD

**Issue by 11digits** [iNavFlight/inav#876]
In some cases I see huge spikes on my quad from the MAG (maybe due to interference) - Would it be possible to implement a sort of filter like the baro ?

**Comment by 11digits** [comment]
Would a median filter work for this? I already implemented it using the pre-existing median filter used for baro. Did not test it but compiled ok.


[compass.c.txt](https://github.com/iNavFlight/inav/files/636079/compass.c.txt)

**Comment by digitalentity** [comment]
I think it's better to fight the cause, not the consequence - try removing mag away from power wires, twist connecting wires toghether etc.
