### ISSUE TITLE
BF43COMPAT home distance broken below 100m

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#8768]
![vlcsnap-2023-02-05-17h28m03s398](https://user-images.githubusercontent.com/966811/216831770-67ca40b0-b916-48da-b255-ae3db8ff1620.png)

Below 100m of home distance, Home Distance OSD element is displayed as unknow character with trailing 1 after the distance

**Comment by mmosca** [comment]
#8776 may also fix this.

It uses the same function changed to fix the amp reading on the other issue.

If the field has a 4 character length for the number, and it ends up being a number with 3 digits on the integer component, it would return a shorter string "###" instead of " ###" or "###."
