### ISSUE TITLE
BF43COMPAT Current broken above 10A

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#8769]
![Uploading vlcsnap-2023-02-05-17h33m18s720.png…]()

With BF43COMPAT current Current OSD element is broken above 10A. See bottom left corner

**Comment by mmosca** [comment]
The image is broken? Is it broken due to the osd element being too small?

**Comment by DzikuVx** [comment]
Yeah it's formatting. Ai will try to take a look as well. Wonder who will be the first 😄

**Comment by mmosca** [comment]
I think the draft pull request should fix the issue, but I will probably move the functions I use in the unit test to a separate file, so I can simplify the #ifdefs
