### ISSUE TITLE
INAV6 Alt value dose not change on Sensors Tab

### ISSUE THREAD

**Issue by msfujino** [iNavFlight/inav#8772]
On the Sensor tab, the Baro value changes, but the Alt value does not. This was not a problem with INAV 5, but it occurs with INAV 6. Flash firmware is 6.0.0-RC1-MAMBAF405US I2C-2023-1-29 13:24.
![BaroAlt](https://user-images.githubusercontent.com/50060737/216939733-a10f653a-b3ce-4d51-8d8b-3392cd0abd27.jpg)

**Comment by Jetrell** [comment]
@msfujino  I gave it a test with 6.0.0-RC1 and a MAMBAF405_2022A target.  It works if the board is powered by a battery, and not just the USB supply.

![baro](https://user-images.githubusercontent.com/47995726/217095830-7394c55b-a028-43f5-a5d2-95ea1184d1c5.JPG)

**Comment by msfujino** [comment]
I forgot that calibration is required. Resolved.
