### ISSUE TITLE
HAKRC F7230D with HAKRCK DF722 firmware does not recognize accelerometer and gyro.

### ISSUE THREAD

**Issue by PaxHitech88** [iNavFlight/inav#8773]
## Current Behavior
After loading the HAKRCKD722 firmware accelerometer and gyroscope are not recognized in INAV 6.0. 
## Steps to Reproduce

1. Flash Firmware in HAKRC F7230D
2. Calibrate

## Expected behavior
Correct recognition of the accelerometer and gyroscope of the FC HAKRC F7230D in order to configure the FC correctly 

## Suggested solution(s)
Implement the FC HAKRC F7230D or have it recognize the accelerometer and barometer.

## Additional context
I request this for personal use after having asked and searched in various INAV groups on the social Facebook, having asked in telegram and discord. After making these requests I noticed that many users have the same HR and would like to use INAV on their quads too.

I attach here the link to the site where I bought the FC in order to see the FC. 
https://it.aliexpress.com/item/1005004859612345.html?spm=a2g0o.order_list.order_list_main.52.32c83696bTWzlT&gatewayAdapt=glo2ita
I would add that I have tried several times to load the compatible firmware (see MATEK F722, MATEK F722SE, MATEK F722mini, HAKRCKD722, etc.) but to no avail, currently I have loaded the Bataflight 4.4 HAKRC F722 firmware with accelerometer and gyroscope set manually (ACC_SPI_MPU6500 GYRO_SPI_MPU6500) at the time of the firmware flash .

- FC Board name and vendor: HAKRC F7230D
- INAV version string: 6.0.0

**Comment by PaxHitech88** [comment]
I managed to solve the problem, now the HAKRC F7230D board is recognized correctly, the accelerometer and the gyroscope are recognized and calibrated correctly. I did a flight test and it flies fine. I have yet to test the RTH and failsafe.

**Comment by PaxHitech88** [comment]
To make INAV work correctly with this card you need to load the firmware for MATEK F722 SE, then set the accelerometer and gyroscope manually from the CLI with the commands:
set gyro_to_use=1
set acc_hardware=MPU6500
save and restart.
Then just continue with the configuration in the traditional way.

**Comment by htagv** [comment]
![3092A286-8F8B-41c9-A4C1-B13DD96DC72B](https://user-images.githubusercontent.com/89235291/218396413-55da3f9d-12ca-4a60-be8f-4c5150038bc7.png)
没有找到黑匣子芯片

**Comment by PaxHitech88** [comment]
I'm having the same problem, I'm trying to fix it as soon as I can update.

**Comment by PaxHitech88** [comment]
> 
> ![3092A286-8F8B-41c9-A4C1-B13DD96DC72B](https://user-images.githubusercontent.com/89235291/218396413-55da3f9d-12ca-4a60-be8f-4c5150038bc7.png)
> 没有找到黑匣子芯片

I solved the problem by uploading the firmware for matek F722 mini, the settings I wrote above are still valid.

**Comment by htagv** [comment]
你真棒

**Comment by htagv** [comment]
Unable to unlock，After unlocking, the drop rings, but there is no error in the log
![184F0396-C027-435a-8E84-61A17B3CAB09](https://user-images.githubusercontent.com/89235291/219852966-ef1e36ea-8aad-4d66-9f40-ff96d97072dd.png)

**Comment by PaxHitech88** [comment]
> Unable to unlock，After unlocking, the drop rings, but there is no error in the log
> ![184F0396-C027-435a-8E84-61A17B3CAB09](https://user-images.githubusercontent.com/89235291/219852966-ef1e36ea-8aad-4d66-9f40-ff96d97072dd.png)
> 

Is the card firmware correct?  did you set accelerometer and gyroscope correctly?  did you set the barometer?  can you send the configuration to see how they are set up?

**Comment by htagv** [comment]
Set it up, it turns out that the throttle value on the remote control is high, the default is 1100, and it can be unlocked by changing it to 1000

**Comment by htagv** [comment]
How do I set throttle travel inside INAV?

**Comment by htagv** [comment]
如何设置低电压保护，自动返航

**Comment by whwxxstsyd** [comment]
> 如何设置低电压保护，自动返航

兄弟，你这板子的陀螺仪是6500的吗

**Comment by PaxHitech88** [comment]
no, it's a MPU 6000

**Comment by whwxxstsyd** [comment]
> no, it's a MPU 6000

No wonder，Thanks
