### ISSUE TITLE
Servo mixer speed ignored when logic condition is used (v6.0.0 RC1)

### ISSUE THREAD

**Issue by cmanley** [iNavFlight/inav#8774]
## Current Behavior
What I'm doing is implementing flaperons using a 2 position switch connected to RC channel 7 based on the awesome tutorial by Mr.D with a Speed of 100 in the mix:
https://www.mrd-rc.com/tutorials-tools-and-testing/flight-controller-therapy/adding-flaps-in-inav-the-best-way/#7-adding-flaperons-in-inav

The switch channel values are sent as 1000ms (flaps up) to 2000ms (flaps down).
There are a few ways to prevent the the flap part of the mix from raising the ailerons above the flat position when switch is set to flaps up:
1. Either transmit value 1500ms from handset.
2. or use the flaperon mode.
3. or disable the the mix in INAV using a logic condition so that the mix is only active when channel is high.

I chose the latter, because it seems safer, especially in cases of fail safe. (Update: I should've chosen 2, but the problem with 3 still remains)

Without the logic condition, the slow speed effect works fine.
With the logic condition assigned, the flaperons move slowly down the first time, but then all up and down movements afterwards ignore the Speed setting.

Bonus bug:
The configurator allows entering Speed values > 127, but when one saves and reboots, those values are replaced by negative values. 

## Steps to Reproduce

1. Add a flaperon mix following Mr.D's instructions.
3. Set Speed to 100 for the 2 flap RC Channel rows in Servo mixer.
4. Create Logic Condition 0, enabled, Operation=High, Operand A = Get RC Channel 7, Active = Always
5. Assign Logic Condition 0 to flap rows in Servo mix.

## Expected behavior
Flaps lower and raise from/to flat position slowly.

## Suggested solution(s)
I have no idea.

## Additional context
```
# Mixer: servo mixer
smix 0 1 1 100 0 -1
smix 1 2 0 100 0 -1
smix 2 3 0 100 0 -1
smix 3 2 10 80 100 0
smix 4 3 10 -80 100 0

# Outputs [servo]
servo 1 1000 2000 1455 -100
servo 2 1000 2200 1515 -100
servo 3 800 2000 1515 -100
```

---
- FC Board name and vendor: Matek F405 WSE
- INAV version string: INAV/MATEKF405SE 6.0.0 Jan 29 2023 / 12:15:30 (b3555517) GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
This is a know feature. Servo speed is applied only to servo input, not activation. 
If you want to have servo speed applied for activation routines, assign one of GVARs as input and modify GVAR value with Logic Conditions
