### ISSUE TITLE
Smart audio not saving changed PID

### ISSUE THREAD

**Issue by miggy1952** [iNavFlight/inav#8789]
MATEKF765 and 6.0.0-RC2

Using smart audio I changed the PIDS and exited by save/reboot but the new value was not changed. 
Had to use stick commands to save the new value.

**Comment by MrD-RC** [comment]
SmartAudio had nothing to do with PIDs. It is used to adjust the power and channel of supported VTx.

**Comment by miggy1952** [comment]
OK thanks
