### ISSUE TITLE
Many OSD options do not save (INAV 6 RC2)

### ISSUE THREAD

**Issue by ABLomas** [iNavFlight/inav#8790]
Something is wrong with saving options changed from OSD (CMS menu).
They actually change, but selecting "Save and reboot" makes them disappear (values are not written).
Things i tried:
 - osd_hud options
 - mission related options
 - few things from "Misc" menu
... none of them survived "save".
On other hand - values actually change - if i had first waypoint > 100m (default value) and can't select mission due to checks - i go to OSD menu, increase value, exit without reboot - and it works. So values are changed, but not saved.
INAV 6 RC2 (the same on preview), Matek F405-WMN (same on 405-WING and OMNIBUSF4).

Short video demonstrating issue: https://t.me/INAVFlight/237678

**Comment by breadoven** [comment]
Settings save if you just use Save and Exit but if you use Save and Reboot. Looks like a bug ... needs fixing.
