### ISSUE TITLE
Very slow Pitch, Roll or Yaw Telemetry

### ISSUE THREAD

**Issue by Barnall** [iNavFlight/inav#8799]
.

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior
 Radio Telemetry very slow (+- 12/15 seconds) in reporting/showing changes in plane orentation.
My controller is a radiomaster tx16s running edgetx ver 2.8, my fc board is a atomrc F405, running inav 5.1, elrs receiver running ver 3.2.  The FC and inav appears to be working correctly except for this issue.

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by mmosca** [comment]
The lua script relies on the telemetry link and that can be quite slow, depending on the telemetry rate. 

Play around with your telemetry rate to improve performance. The more telemetry packets you send, the faster your lua update rate will be.

**Comment by DzikuVx** [comment]
Telemetry speed depends on telemtry protocol. On top of that ELRS by default has very low telemetry rate and custom sensors are sent with low priority. Increase telemetry rate on ELRS to speed it up

**Comment by Barnall** [comment]
Great 🤪. Well clarified,  have adjusted the packet rate, big improvement.
Thanks so much guys.

**Comment by Swainic** [comment]
> Telemetry speed depends on telemtry protocol. On top of that ELRS by default has very low telemetry rate and custom sensors are sent with low priority. Increase telemetry rate on ELRS to speed it up

I have the same problem with TX16S, ELRS 915mz Emax module. The first 10 sensors are updated constantly and read pretty much real time values. The problem is the roll and pitch are at 21 and 22 on the list and only get updated about every 5 seconds which makes that part of the INAV display completely useless. I've seen YouTube videos of INAV setup where the FC reacts immediately on the INAV screen when moved side to side, so what is the problem with my setup? I am installing my FC in a sailplane and don't want FPV, so the pitch and roll is important to refer to. Can I not re-assign the pitch and roll higher up the list?

**Comment by Keltron3030** [comment]
> > Telemetry speed depends on telemtry protocol. On top of that ELRS by default has very low telemetry rate and custom sensors are sent with low priority. Increase telemetry rate on ELRS to speed it up
> 
> I have the same problem with TX16S, ELRS 915mz Emax module. The first 10 sensors are updated constantly and read pretty much real time values. The problem is the roll and pitch are at 21 and 22 on the list and only get updated about every 5 seconds which makes that part of the INAV display completely useless. Changing the packet rate does nothing to alter this speed on the bench. I've seen YouTube videos of INAV setup where the FC reacts immediately on the INAV screen when moved side to side, so what is the problem with my setup? I am installing my FC in a sailplane and don't want FPV, so the pitch and roll is important to refer to. Can I not re-assign the pitch and roll higher up the list?

Not sure if you got this solved but the answer is likely that you need to decrease telemetry ratio so the data is sent more often. I find 1:4 is good enough for my taste.

https://www.expresslrs.org/info/telem-bandwidth/

**Comment by MrD-RC** [comment]
You need to speed up the telemetry rate in ELRS or use a different RC link.

**Comment by Swainic** [comment]
Thanks Darren and Keltron. In fact I found the problem was more with the
Telemetry Ratio which I have increased to 1:8 and I also bumped up the
Packet rate to 100Hz. The reaction speed on the INAV display is now pretty
good and it works exactly how I expected it to with this setting.
