### ISSUE TITLE
Can`t set DSHOT protocols in INAV 6 rc2 (SpeedyBee f405 v3)

### ISSUE THREAD

**Issue by konikav** [iNavFlight/inav#8817]
The motor_pwm_protocol = dshot300 parameter cannot be saved. It always returns to Multishot after rebooting.

**Comment by stronnag** [comment]
Intentionally disabled.

**Comment by robustini** [comment]
> Intentionally disabled.

Why????

**Comment by 040572** [comment]
Why

**Comment by 040572** [comment]
So what is the solution
