### ISSUE TITLE
DJI O3 air unit - OSD battery voltage

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8840]
Hi, would it be possible to manage somehow to see OSD battery voltage like in the video? I see 0,0V now on DJI goggles 2. Of course I can choose to see bat voltage in iNav OSD but I would like to see it using dji OSD. It can be done in Betaflight (shown in video) and ardupilot, too. Maybe it is possible in iNav but I do not know how.

https://www.youtube.com/watch?v=KIis4hB_duQ&t=2s
<img width="1001" alt="Snímka obrazovky 2023-02-27 o 20 53 57" src="https://user-images.githubusercontent.com/123115426/221669350-29e9a64e-0fa5-4242-907d-1f42b37d27f5.png">

<img width="1013" alt="Snímka obrazovky 2023-02-27 o 20 53 36" src="https://user-images.githubusercontent.com/123115426/221669334-4bd4a111-10ac-4336-9ada-ff8670cd6bf8.png">

**Comment by RobinatiNav** [comment]
Thank you Marcelo :)

**Comment by mmosca** [comment]
It will make it to 6.0 after all. 

Should be included in the next rc.

**Comment by RobinatiNav** [comment]
Well done Marcelo :)

**Comment by RobinatiNav** [comment]
Hi Marcelo, it works! Many thanks. You maybe do not know but you fixed 3 things in one. Not only voltage is present in native dji OSD but arming command passes through, so when armed O3 air unit changes its state from low power to full power, and also auto recording works when armed, too. Good job :)
