### ISSUE TITLE
Betafpv F722 AIO (ICM42688gyro support？

### ISSUE THREAD

**Issue by keisukesamba** [iNavFlight/inav#8841]
I installed inav5.1 using Betafpv F722 ICM42688 version.

I have put it in the configurator but the gyro is not responding in the setup tab.

I have tried all the gyros that can be selected in the configurator tab (even FAKE) and they do not work.

Is the ICM42688 gyro not supported by inav?
Please if anyone knows, please help.

Versions I have tried
Configurator V5.1.0 and 6.0RC2 try
FC firmware V5.1.0 and V6.0.0RC2 try

**Comment by mmosca** [comment]
Can you try with the hex included in this zip file?

I am also interested in knowing if the gyro orientation is correct out of the box.

[inav_6.0.0_BETAFPVF722.zip](https://github.com/iNavFlight/inav/files/10866453/inav_6.0.0_BETAFPVF722.zip)

**Comment by mmosca** [comment]
@keisukesamba did you get a chance to test the above firmware?
