### ISSUE TITLE
INAV6 RC2 : USER1 without function on MAMBAH743_2022B

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#8844]
## Current Behavior
USER1 mode is not working in TARGET MAMBAH743_B2022 

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/8381714/222410171-12e1c9b9-1944-4631-b319-7da5a0b79379.png">

## Steps to Reproduce
1. simply attach the vtx to the 9v pin and choose USER1 to be active/inactive
2. Power won't switch off

## Expected behavior
The power should become switchable as described in the manual (FC)

## Suggested solution(s)
enable mode USER1 to control the 9v pin to power a connected VTX/WALKSNAIL/O3 on/off

---

### version
 - INAV/MAMBAH743_2022B 6.0.0 Feb  9 2023 / 11:19:13 (92b237e5)
 - GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
Are you sure it's `MAMBAH743_B2022` not `MAMBAH743` target? They differ in PINIO assignment and 2022B has a mapping exactly like requested by Diatone

**Comment by Pairan** [comment]
It’s the Mamba H743 v2 stack … the website says it like this:

MCU: 480MHz STM32H743
GYRO: DUAL ICM-42688-P
Target：MAMBA H743_2022B

so I would assume it to be the right target.

**Comment by DzikuVx** [comment]
Then Diatone must have changed something again... I'll talk to them

**Comment by DzikuVx** [comment]
I have samples, but they might be pre-production batch

**Comment by Pairan** [comment]
In case you have a test build, I can try it out on my quad

**Comment by DzikuVx** [comment]
[inav_6.0.0_MAMBAH743_2022B.zip](https://github.com/iNavFlight/inav/files/10888491/inav_6.0.0_MAMBAH743_2022B.zip)
 @Pairan please test this hex

**Comment by Pairan** [comment]
just a sec ...

**Comment by Pairan** [comment]
Sadly it didn't work. The Walksnail Airunit wasn't shut down and kept working while enabling/disabling `USER1`.

**Comment by Pairan** [comment]
this didn't fix it. Guess we'll have to wait for Diatone ...

The Airunit connected to 9v pad kept on while switching USER1 on/off

**Comment by DzikuVx** [comment]
@Pairan I spoke with Diatone and looks like current target is correct. I will retest something

**Comment by Pairan** [comment]
Thanks a lot, Pawel - If you need some testing then let me know. Test Rig is currently on RC3

**Comment by GootyS** [comment]
Does iNAV support the dual gyro Mamba H743? Not having much luck with BF an this board.

**Comment by marcdornan** [comment]
This is not working on Mamba H743 V2 (4th Gen) on iNav 6.1.1 using MAMBAH743_2022B target, It seems to be non functional as Pairan reported on March 2023. I tested it by flashing Betaflight and it worked fine: 9V is applied to the VTX power pin when User 1 is set up on the modes tab and a channel is mapped.

**Comment by ioakimov** [comment]
As mentioned in #9455 
USER2 (instead of USER1) is switching power on VTX.
