### ISSUE TITLE
Turtle Mode on Inav 5.1

### ISSUE THREAD

**Issue by koklimabc** [iNavFlight/inav#8849]
So far I'm using SpeedyBee F405V3 under Inav 5.1 but I din't able to find the turtle mode option under Mode Tab.

Is there anywhere to set it up?

**Comment by Jetrell** [comment]
It only works if the ESC has Dshot capability..
Then you need to have `ESC output/telemetry` selected under Peripherals in the Ports tab. 
And a Dshot protocol has to be selected under the Outputs tab..  
Only then will Turtle appear under the modes tab.
