### ISSUE TITLE
INAV 6RC2: INAV logo not showing correctly (AVATAR)

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#8851]
While booting up the INAV logo is not assembled correctly in HD/AVATAR/WALKSNAIL #firstworldproblem

## Current Behavior
<img width="1403" alt="Bildschirm­foto 2023-03-05 um 06 50 58" src="https://user-images.githubusercontent.com/8381714/222943972-fe51920c-e4bd-479c-88f2-186c913375cb.png">

## Steps to Reproduce

1. flash current INAV 6RC2
2. set it up as AVATAR OSD
3. BOOT
4. watch

## Expected behavior
the clean an correct assembled INAV logo ... (and animated fireworks whatsoever perhaps )

## Suggested solution(s)
The assembly of the logo in HD seems to need a different setup

**Comment by MrD-RC** [comment]
This is expected. The AVATAR firmware still uses the 5.1 font. At the moment, there upload of custom INAV fonts needs to be fixed by Walksnail. They will have the 6.0 font in time for the stable release.
