### ISSUE TITLE
Feature Request: Failsafe Approach Mission

### ISSUE THREAD

**Issue by cfitches** [iNavFlight/inav#8855]
## Current Behavior
Currently for fixed wing during a failsafe landing it 'loiters' down to its approach. Even fields etc tend to have trees, hedges, powerlines that it can loiter into. Safe home is great as it limits damage to people and buildings however it can still be difficult to avoid trees and hedges. Even a flying club people tend to gather at one area and given the loiter behaviour it can be hard to know what exactly the plane will do and where it will fly over and how many circles it will perform. 

## Desired Behavior
Fixed wing craft follows a designated a safe approach i.e. terrain and obstacles are taken into account by user programming it into configurator. 

## Suggested Solution
Ability to create a WP Failsafe mission for the craft to intersect with. So that it follows the mission to approach your failsafe area more safely with no loiter. You would then add this as a failsafe option. 

## Who does this impact? Who is this for?
Airplane users, people that fly from almost any area. Maybe very important for those that fly in more built up areas.

**Comment by MrD-RC** [comment]
Thanks Marc. I was going to link to your FR, but forgot 🤣
