### ISSUE TITLE
ESC Telemetry not working!

### ISSUE THREAD

**Issue by samnikos7** [iNavFlight/inav#8872]
I'm using FF F35_LIGHTNING FC with iNav 5.1, Skystars Talon32 Slim40 ESC on a Zohd Dart250 wing using Dshot600 protocol. Everything works perfect except ESC Telemetry (RPM, Temp etc). I've already tried to change the AUTO TELEMETRY (ON-OFF) from BlHeliSuite 32, use another RX UART of the FC with no luck. I don't receive any data (debug, OSD).

**Comment by MrD-RC** [comment]
Just to confirm. You have run a wire from the T pad on the ESC to a UART Rx pad, and enabled the ESC Telemetry peripheral on the ports page?

**Comment by samnikos7** [comment]
Yes, of course. 
The ESC is sending data, I can read them using BlHeliTv tool and rs232 usb.
![image_2023-03-10_232348890](https://user-images.githubusercontent.com/87907405/224431065-90796ac1-2e74-475e-9922-94fea1f14f81.png)
