### ISSUE TITLE
LOITER mode should be renamed in OSD 

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8873]
LOITER mode should be renamed in OSD. There is still HOLD showing. I would prefer to see LOIT there. ;) Thanks

<img width="1239" alt="Snímka obrazovky 2023-03-11 o 13 42 09" src="https://user-images.githubusercontent.com/123115426/224485230-1bb2fdb2-c2c4-4732-b2a7-26b44ce131dd.png">

**Comment by MrD-RC** [comment]
Makes sense
