### ISSUE TITLE
Matek F405 TE, multirotor, use PVM outputs 5-8 not only for motors but for servos too. 

### ISSUE THREAD

**Issue by MikeZakhar** [iNavFlight/inav#8883]
## Current Behavior
When user setup controller and select multirotor craft type then 1-8 pvm outputs reserved to motors but only 2 (9 and 10) for servos.

## Desired Behavior
When user setup for example a quadrocopter PVM outputs 5-8 should be available for servos too.

## Suggested Solution
Option 1: use different PVM output map for quadrocopter, hexacopter and octocopter.
Option 2: give to user ability to select which outputs will be used for motors which for servos.

## Who does this impact? Who is this for?
Quadracopter users which need more than 3 servo outputs.

## Additional Context
2 servos output it's not enough even for such simple case like camera with 2 axis gimbal and zoom.

**Comment by b14ckyy** [comment]
Implemented in 7.0 with https://github.com/iNavFlight/inav/pull/9268
