### ISSUE TITLE
Time to diagnose failsafe - RTH Failsafe land delay

### ISSUE THREAD

**Issue by carlybaby69** [iNavFlight/inav#8893]
Current Scenario - User drops TX. Rummage in field to put in battery back in etc. Plane enters failsafe and crash lands at Home point.

New Scenario - user drops TX. Rummage in field ….Plane enters failsafe and loiters at home point for configurable amount of time. User finds battery and exits failsafe.

A failsafe RTH land delay setting would be nice.

**Comment by MrD-RC** [comment]
Duplicate of https://github.com/iNavFlight/inav/issues/4123
