### ISSUE TITLE
Add Iflight succex-e f7 v2 flight controller support 

### ISSUE THREAD

**Issue by Ovalleader12** [iNavFlight/inav#8903]
Fc name: iflight succex-e f7 v2
Bf target name: IFLIGHT_SUCCEX_E_F7

**Comment by fermiums22** [comment]
In order to officially add it, they ask to send a prototype to them. I myself compiled the firmware for myself. But this is a difficult path, and there are no guarantees.
[IFLIGHT_SUCCEX_E_F7.zip](https://github.com/iNavFlight/inav/files/11151927/IFLIGHT_SUCCEX_E_F7.zip)

**Comment by Ovalleader12** [comment]
Dude then you do much

**Comment by Ovalleader12** [comment]
how do i go about flashing this? i see that its a c and an h file

**Comment by fermiums22** [comment]
I'm not going to collect all the firmware versions for you.
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20or%2011%20with%20Linux%20Subsystem.md
