### ISSUE TITLE
CRSF connection lost on EEPROM save

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#8905]
INAV 6.0 RC3 loses CRSF RC signal after Save is hit on Modes tab in configurator. Failsafe is not triggered, only power cycle restores CRSF RC input. Telemetry is not lost, only incoming RC data.

Steps to reproduce:
1. Set CRSF as a protocol
2. Power FC
3. Power radio
4. Connect to Configurator
5. Go to Modes tab
6. Hit save
7. Go to receiver tab
8. RC channels are not longer updating

Important: hitting save on different pages results in the same situation. Using "Save and reboot" does not cause this problem.

Theory: EEPROM save break timing and causes CRSF protocol to go out of sync

**Comment by DzikuVx** [comment]
Running theory, cause by 
```
void suspendRxSignal(void)
{
    failsafeOnRxSuspend();
    suspendRxSignalUntil = micros() + SKIP_RC_ON_SUSPEND_PERIOD;
    skipRxSamples = SKIP_RC_SAMPLES_ON_RESUME;
}```

**Comment by OptimusTi** [comment]
Cannot replicate the issue with TBS Crossfire. Works fine.

**Comment by MrD-RC** [comment]
If it’s and ELRS issue. Try turning off their VTX Administrator. I’m sure that was found to be the cause of some problems.

**Comment by DzikuVx** [comment]
VTX Administrator is Off.

**Comment by DzikuVx** [comment]
This seems to be a race condition of some kind. Using 
```
void writeEEPROM(void)
{
    // suspendRxSignal();
    writeConfigToEEPROM();
    // resumeRxSignal();
}
```
Fixes the issue. However, not sure what is the role of `suspendRxSignal`. Will investigate.

I consider it a minor issue as it happens only during 'save` not during flight

**Comment by breadoven** [comment]
Is this all boards or an H743 ? there was this other issue https://github.com/iNavFlight/inav/issues/8409. I managed to find the `suspendRxSignal` is related to https://github.com/iNavFlight/inav/issues/8409#issuecomment-1255452269.

Does it happen if you Save from the CMS without rebooting ?

**Comment by DzikuVx** [comment]
@breadoven it's a race condition that can happen on fast board with fast RC link. I already have a fix. But yes, it seems to be related to #8409

**Comment by rmaia3d** [comment]
I can't replicate this, on a H743Slim (Matek) board running ELRS (FrSky R9Mini flashed with ELRS 3.2.0). I'm using 100Hz packet rate, though. So maybe it only happens with faster packet rates?

Also, I'm using a custom build of the configurator, up to commit ce4906f0 (Jan 29th), and the Inav code is also custom, built from the "release 6.0.0" branch.

**Comment by DzikuVx** [comment]
@Slash7FPV check if hex attached in https://github.com/iNavFlight/inav/pull/8907 fixes the problem for you

**Comment by Slash7FPV** [comment]
Just checked. Firmware #8907 did not fix the problem. Rxloss still happens after save command.

Good news might be that i was not able to reproduce the bug on Matek F722WPX and F405 Wing.

**Comment by rmaia3d** [comment]
Using a custom build from the configurator release_6.1.0 branch, I was able to replicate the problem. But with the H743Slim only. With F722SE and F405CTR (both from Matek), no problems at all.

Also, with the H743 I only get the error on the Modes tab. Click "Save" on the PID Tuning tab, or on the OSD tab, results in no problems with the Rx data. It continues normally from those tabs.

However, I tested again with an older version of the configurator (built from commit ce4906f0 (Jan 29th)) and in this version, no problems at all in any tab. Even the modes tab works fine with the H743 Slim V3.

So maybe it was a mod introduced after Jan 29th that broke this functionality?

**Comment by DzikuVx** [comment]
As soon as I will find some time, I will bisect and find offending commit.
@rmaia3d you say it might be Configurator related? We have reports of freezing with save from CMS

**Comment by rmaia3d** [comment]
> @rmaia3d you say it might be Configurator related? We have reports of freezing with save from CMS

I am not entirely sure, but it could be Configurator related, yes. With the "older" Configurator version, I couldn't replicate the issue at all, even trying some 10 times in a row with the H743 board. It worked fine every single time. 

So that's what leads me to think that maybe the problem could be in the Configurator.

**Comment by Slash7FPV** [comment]
tried to replicate the bug "in flight". When you maybe accidentially disarm in flight the bug can be triggered and the rc link will not come back. 
1. i armed the plane with H743. 
2. rudders, telemetrie, motors, all working fine. Could go flying.
3. i disarm "by mistake" (by switch). no "configurator save" involved here.
4. when trying to rearm again the FC stays in the rx loss state. rearming or other commands via TX not possible.

https://youtu.be/7E-eoGc-3bE

**Comment by DzikuVx** [comment]
@Slash7FPV do you have continuous servo autotrim enabled? Or total distance meter?

**Comment by Slash7FPV** [comment]
cont. servo autotrim is active, yes

**Comment by DzikuVx** [comment]
Cont. Serve Autotrim saves trims on disarm. Until this is not resolved, disable it

**Comment by breadoven** [comment]
Any reason why the 6.1.0 firmware in https://github.com/iNavFlight/inav/issues/8409#issuecomment-1489525011 seemed to work rather than the 6.0.0 tried here. Are then not the same @DzikuVx ?

**Comment by DzikuVx** [comment]
I'm not sure @breadoven I will dig into it when I will find some time.

**Comment by DzikuVx** [comment]
According to bisect, the commit that introduced the problem was 17456069737b1ce3562bdd26a17df648e9cf1b89 but I don't see anything that mighrt have caused than in the changeset. I will have to investigate deeper

**Comment by DzikuVx** [comment]
Second bisect also points to 17456069737b1ce3562bdd26a17df648e9cf1b89 and one more time no idea why it's happening

**Comment by DzikuVx** [comment]
I'm more and more inclined to think this is not 17456069737b1ce3562bdd26a17df648e9cf1b89 although bisect pointed this twice. 6.0.0 with reverted 17456069737b1ce3562bdd26a17df648e9cf1b89 also has this problem

**Comment by joneszee69** [comment]
I am new to fixed wing and I am having same problem with my build . I just switch over my two planes  from 4.0 to 6.0 . Plane [1] has Matek H743-wing-v2 FC and Plane [2] has a Matek F411se FC. Plane [1] has this problem (ran fine on 4.0). Plane [2] does not have this problem on either 4.0 or 6.0... All my settings as far as flight modes and configurator settings are the same.

**Comment by rmaia3d** [comment]
> I am new to fixed wing and I am having same problem with my build . I just switch over my two planes from 4.0 to 6.0 . Plane [1] has Matek H743-wing-v2 FC and Plane [2] has a Matek F411se FC. Plane [1] has this problem (ran fine on 4.0). Plane [2] does not have this problem on either 4.0 or 6.0... All my settings as far as flight modes and configurator settings are the same.

Can you try using the Configurator 6.0 RC1 (yes, an older release, from Jan 29th) with plane [1] and see if you still have the problem? 

With me, running the older configurator version I couldn't replicate the problem with the H743 board, so I suspect it may actually be a configurator issue. If you also don't see a problem with the older configurator, it could add strength to this thesis.

**Comment by joneszee69** [comment]
Definitely will try and post back. Probably within a day or so when I get home.

**Comment by Jetrell** [comment]
Just a bit more info.. A friend who was using 6.0 full release. With a Matek H743 Wing and a GHOST radio system... Had his RX lock up, after Saving some settings in the OSD tab.

**Comment by DzikuVx** [comment]
After more checks I think there is a general problem with H7 eeprom save procedure. It seems like it's interacting with serial port processing in a way that I don't understands right now.

**Comment by joneszee69** [comment]
I disabled continuous servo trim and put it on a switch and still had problems. Do I need to disable it out of the CLI or just leave it switched off  and not put it on a switch?

**Comment by rmaia3d** [comment]
> Just a bit more info.. A friend who was using 6.0 full release. With a Matek H743 Wing and a GHOST radio system... Had his RX signal lock up, after Saving some settings in the OSD tab... He then proceed to the Receiver tab. To find that nothing was responding.

Can you ask your friend to try with an older release of the Configurator, like RC1 and see if he still gets the same problem?

**Comment by rmaia3d** [comment]
Another thing that occurred to me that could be reason for these errors:

In commit [17cba63](https://github.com/rmaia3d/inav/commit/17cba6342c11dfb78cc108120f73fac9ac8736da) there has been a change in the optimization of H7 code to a more aggressive level. 

Then, in commit [47ce779](https://github.com/iNavFlight/inav/commit/47ce779a92e331dc54d861b169043d5b7d7036ed), the diff shows several instances of calls like this:
```function1();
  function2();
  function3();```

This has bitten me before in other codes. Some of these repetitive patterns of the same function calls, at aggressive optimization levels,  get optimized out generating undesirable (and hard to detect) behavior. With hardware debugging, by tracing through the code, it may be possible to confirm (or not) if the calls are made as expected.

The fact that it only happens with the H7 boards and that it seems like the optimization level was changed only for H7 boards, could be a pointer that it may be related to the optimization itself.

**Comment by DzikuVx** [comment]
@rmaia3d that could be it. Interesting that I tried to bisect this thing twice and always pointed me to a different code. Oh well, I will try to check the optimization today

**Comment by 0crap** [comment]
>...
> 
> This has bitten me before in other codes. Some of these repetitive patterns of the same function calls, at aggressive optimization levels, get optimized out generating undesirable (and hard to detect) behavior. With hardware debugging, by tracing through the code, it may be possible to confirm (or not) if the calls are made as expected.
> 
> The fact that it only happens with the H7 boards and that it seems like the optimization level was changed only for H7 boards, could be a pointer that it may be related to the optimization itself.

Nice observation!
Is it possible to compile a 6.0.0 hex without the more aggressive optimization?
Seems like an interesting thing to test. 💯

**Comment by stronnag** [comment]
I spent some like looking at this sort of issue (mainly for compilers > 10),  and made some [copious notes]( https://gist.github.com/stronnag/08f79fa9ae3c1f23e2f6631df1d37fb5#file-inav-and-modern-compilers-md).

Executive summary: Violating GCC's rules on optimisation with LTO plus CMake's opinionated compiler options doesn't make for happiness on embedded ARM, at least with modern compilers; it might also be behind some of the other weird things we see with older compilers.

**Comment by DzikuVx** [comment]
[inav_6.0.0_MATEKH743.zip](https://github.com/iNavFlight/inav/files/11146919/inav_6.0.0_MATEKH743.zip)

@0crap @Slash7FPV  you can try this hex

**Comment by 0crap** [comment]
> [inav_6.0.0_MATEKH743.zip](https://github.com/iNavFlight/inav/files/11146919/inav_6.0.0_MATEKH743.zip)
> 
> @0crap @Slash7FPV you can try this hex

Holy crap!!
This hex fixes the issue on my H743. 🥇 

I can perfectly reproduce the issue as per opening post on 6.0.0 release.
The added hex fixes it!
I hit save on the Modes tab multiple times to see if I'm dreaming. :-)
(I did not fly the model, but only bench tested it.)

Seems like we are on the good track smashing this bug. 💯

**Comment by DzikuVx** [comment]
I wonder if that fixes #8899 on H743 as well

**Comment by RobinatiNav** [comment]
> I wonder if that fixes #8899 on H743 as well

Pawel do you mean the JETIEXBUS problem?

**Comment by joneszee69** [comment]
Looking good so far on this end also. looks like you nailed it, thank you for all your time and support.

**Comment by 0crap** [comment]
> > I wonder if that fixes #8899 on H743 as well
> 
> Pawel do you mean the JETIEXBUS problem? I was so into solving the JETIEXBUS problem, so I didn't even notice this problem existed.

Yes.
Just flash the hex a few posts above here and see if the behavior of your issue #8899 changes.

**Comment by RobinatiNav** [comment]
> > > I wonder if that fixes #8899 on H743 as well
> > 
> > 
> > Pawel do you mean the JETIEXBUS problem? I was so into solving the JETIEXBUS problem, so I didn't even notice this problem existed.
> 
> Yes. Just flash the hex a few posts above here and see if the behavior of your issue #8899 changes. (On the Matek H743-WLITE V3 board.)

Ocrap, do you know what is the issue  #8899 about?

**Comment by RobinatiNav** [comment]
> > > > I wonder if that fixes #8899 on H743 as well
> > > 
> > > 
> > > Pawel do you mean the JETIEXBUS problem? I was so into solving the JETIEXBUS problem, so I didn't even notice this problem existed.
> > 
> > 
> > Yes. Just flash the hex a few posts above here and see if the behavior of your issue #8899 changes. (On the Matek H743-WLITE V3 board.)
> 
> Ocrap, do you know what is the issue #8899 about? It is not related to H7 but any FC when JETIEXBUS protocol is used.

**Comment by b14ckyy** [comment]
Friend of mine still saw the CRSF disconnect after disarming (with cont. servo trim on) yesterday. He says it usually works now and is not always but he had at least one instance where it still happened.

**Comment by j-keiter** [comment]
[vokoscreenNG-2023-05-27_06-51-14.webm](https://github.com/iNavFlight/inav/assets/24608664/b93b0a03-de7d-4604-9fc8-e8d51534ebed)
Hitting modes button causes parachute to turn red for failsafe?  Receiver tab still shows stick movement from transmitter.
Skystars H743  Inav 6.1
