### ISSUE TITLE
INAV 6.0 RC4

### ISSUE THREAD

**Issue by ricardovalmeida** [iNavFlight/inav#8906]
HEY
I'm using inav 6.0 rc4 to control a tricopter.
My radio is a TGY-I6 and my cc3d revolution flight control board.
I am unable to configure INAV in PPM mode.
I don't know if this version of INAV supports PPM?
Which most current version of INAV still supports PPM?
can you help me
thanks.

**Comment by MrD-RC** [comment]
PPM was removed from INAV in version 5.0 I believe. Only serial protocols are accepted now.
