### ISSUE TITLE
DSHOT can not be configured for SPEEDYBEEF405V3

### ISSUE THREAD

**Issue by xabc1** [iNavFlight/inav#8919]
It always return to MULTISHOT after saving it. I'm using Inav 6.0.

**Comment by xabc1** [comment]
went back to 5.1 but still the same - DSHOT can't be configured on this FC

**Comment by stronnag** [comment]
Duplicate of #8817, #8910

**Comment by xabc1** [comment]
Just an update. DSHOT works in betaflight for SPEEDYBEEF405V3. Even works with bidirectional.
