### ISSUE TITLE
BF 4.4 HD OSD support 

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8930]
Dji has brought new firmware for Goggles 2 which supports latest BF 4.4 HD OSD. It is a time to bring HD for goggles 2 into the iNav :)

**Comment by roroid** [comment]
in displayport_msp_osd.c just do this and recompile for your target

![339249756_153458494016447_7228993741254628911_n](https://user-images.githubusercontent.com/1607400/229270469-9fde899d-30bf-44de-8c1f-36bfdd780dad.jpg)

**Comment by MrD-RC** [comment]
Fixed with https://github.com/iNavFlight/inav/pull/8707
