### ISSUE TITLE
icm 42688p

### ISSUE THREAD

**Issue by davifelix** [iNavFlight/inav#8936]
Good afternoon. I have an All in One JHEMCU flight card GHF405AIO-icm pro. BetaFlight firmware 4.3.1 on which I can not make a proper tune Because of this ICM 42688P gyroscope. 
 It does not hold the line and vibrates continuously, if I give all the gas the engines seem to go crazy. What can I do to try to solve? Thank you all.

**Comment by mmosca** [comment]
We can't help with betaflight and I don't think that fc is supported by inav.
Maybe you should try Betaflight's discord.
