### ISSUE TITLE
No OSD w/ DJI 03 Air/Goggles 2/ Matek w743 wlite

### ISSUE THREAD

**Issue by bonem1dr** [iNavFlight/inav#8941]
Still cant get my osd to work. I am running the most recent release Inav 6.0.0 with DJI 03 air unit, goggle 2, matek h743 wlite fc and have tried both using the msp display port option with bf43compt and DJI FPV VTX options with no luck. Only thing different I see is when I use bf43compt in my goggles it allows me to use canvas mode in normal or hd, but still no OSD at all...

**Comment by mmosca** [comment]
post your diff.

**Comment by RobinatiNav** [comment]
> Still cant get my osd to work. I am running the most recent release Inav 6.0.0 with DJI 03 air unit, goggle 2, matek h743 wlite fc and have tried both using the msp display port option with bf43compt and DJI FPV VTX options with no luck. Only thing different I see is when I use bf43compt in my goggles it allows me to use canvas mode in normal or hd, but still no OSD at all...

Did you enable OSD in configuration menu? I have the same setup and it works. Here is my setup. I have 2 screens and 3 pos switch (ALT1, ALT2, and NO OSD)

<img width="1198" alt="Snímka obrazovky 2023-04-02 o 22 26 41" src="https://user-images.githubusercontent.com/123115426/229377367-ac0ec1b9-cfa7-447a-99f6-69fc4bf7cc7b.png">
<img width="1197" alt="Snímka obrazovky 2023-04-02 o 22 26 07" src="https://user-images.githubusercontent.com/123115426/229377370-154f1477-a197-4a6f-805a-69d16bb90343.png">
<img width="1199" alt="Snímka obrazovky 2023-04-02 o 22 24 11" src="https://user-images.githubusercontent.com/123115426/229377362-a289aa39-4d2a-40b6-ac56-2ad22d9e364b.png">
<img width="1198" alt="Snímka obrazovky 2023-04-02 o 22 24 40" src="https://user-images.githubusercontent.com/123115426/229377366-f7abeef1-14e5-4bc6-8104-b615c2975552.png">

**Comment by bonem1dr** [comment]
Thats how I have it but I didn't try the osd alt 2 switch.
would love to try it but my FC failed and my plane death spiraled into a
lake and was a total loss...

thanks for the info tho!

**Comment by RobinatiNav** [comment]
> Thats how I have it but I didn't try the osd alt 2 switch. would love to try it but my FC failed and my plane death spiraled into a lake and was a total loss... thanks for the info tho!
> […](#)

I am sorry you lost the plane. I crashed twice already. Both time with Matek H743-WLITE. First time I partly damaged PDB board and second time with a new PDB. There is something strange happening with iNav and maybe it is related to Matek H743-WLITE too
