### ISSUE TITLE
3D OSD map

### ISSUE THREAD

**Issue by sdellava** [iNavFlight/inav#8944]
## Current Behavior
The OSD map/radard feature show the UAV relative position to the home or vice versa in a 2D map.

## Desired Behavior
Home (and others waypoints) is a 3D point, so it could be possible to show the relative position of the home the the OSD, taking in consideration the current UAV orientation in the space and adapt the logical home point view.
Basically it works like artificial horizon, keeping the home points (and other WPS) logically fixed in the field of view. 
  
  ## Suggested Solution
In this picture you can see a simpliefied view of how the 3D map mode should appear in the OSD.  Of corse in 3D mode the map do not provide distance information but this information is already available as numeric field.

![image](https://user-images.githubusercontent.com/11772150/229450996-4831679a-c9ef-4e83-9df4-c2e261ba7ba4.png)

If the he home is outside of the FOV simply the home is not visible:

![image](https://user-images.githubusercontent.com/11772150/229459856-0f6d8446-7e1d-4b6a-aae8-5a66211a50f6.png)

## Who does this impact? Who is this for?
All map users.

When flying in mountains pilots need to take in consideration the the home position inside of the 3D space to evaluate where is possible to fly without risk to loose the radio link. This is very difficult to evaluate simply looking the scenario. This is a real case view of about 1000mt over the home point represented by the red dot.

![image](https://user-images.githubusercontent.com/11772150/229456584-457a509f-ec4f-4ac7-8c92-598f0dbac6b1.png)

The horizontal distance from the home point is just 250 mt. The dashed line represent the crest of the mountain that must not be crossed, otherwise the connection with the UAV will be lost. However, without having the location of the home in the field of view indicated here by the red dot, it is not at all obvious that that ridge is not to be crossed.

The 2D map do not show the home in the red dot position so it is not useful to evaluate/imagin the red dashed line.

This picture show an other critical area to fly:

![image](https://user-images.githubusercontent.com/11772150/229459262-02512dba-a59a-41ad-aabf-6e672e3777bc.png)

The red space is a flat land about 200 mt over the home. If the UAV descend in that area the ridge represented by the red dashed line become an obstacle that can block the radio link. 

Flying low in that area with the home streight in front, before to loose the view of the home the 3D map should appear like this image providing a clear information that the ridge is a critical obstacle:

![image](https://user-images.githubusercontent.com/11772150/229526002-c2191fc6-420c-4cdb-b8db-5b04d1d14e9d.png)

**Comment by rmaia3d** [comment]
I'm not I understood correctly your idea, but wouldn't what you are suggesting also require the OSD to have some kind of access to 3D terrain elevation databases?

**Comment by sdellava** [comment]
No, It is clear that if the home point is behind an obstacle the OSD still represent it in front of the osbstacle. Let see this example:

![image](https://user-images.githubusercontent.com/11772150/229499753-2597f408-ec47-4874-9298-c6825e815afd.png)

But before to arrive in that situation, hopefully the pilot had this view:

![image](https://user-images.githubusercontent.com/11772150/229500089-5f4b14f1-43eb-4530-b9de-79eea8ebcc1e.png)

So it has the clear percption that it is dangerous to descent much more.

No surface information is required to represent the map in 3D view.

**Comment by sdellava** [comment]
To simplify the work of the devs, I defined the mathematics required to implement the algorithm.

This image shows the overall scenario in a simplified way 

![image](https://user-images.githubusercontent.com/11772150/230381154-5df4cc8e-2056-4cec-9550-e95c5d3f4cdf.png)

This is the view from above
![image](https://user-images.githubusercontent.com/11772150/230381331-b0aac3d6-d320-487d-984a-0267e4fb42ff.png)

and this is the view from the side

![image](https://user-images.githubusercontent.com/11772150/230381561-83c27b81-5261-4d6b-a7db-b1f0a38835f4.png)

Questo è un esempio reale, con informazioni prese da google map:
![image](https://user-images.githubusercontent.com/11772150/230381704-3bcdf3f1-0f6f-4737-8015-6b8a5eed6639.png)

In this excel file, I used aerospace trigonometric formulas to calculate the distance and angles between the two points and then estimate the relative position of Home in an XY grid.

Parameter to provide:
- P1 and P2 latitude, longitude and altitude
- Pitch and heading
- Portion of the FOV (horizontal and vertical) to be represented in the OSD grid (in example 80 deg of the 160 total camera FOV)
- dimension of the OSD grid representing the portion of the used FOV 

In red the position X,H in the grid of the Home in the OSD 3D map.

[3D MAP Math.xlsx](https://github.com/iNavFlight/inav/files/11170709/3D.MAP.Math.xlsx)

**Comment by rmaia3d** [comment]
Check this video around the 2:00 mark. It shows the OSD recording from a DJI Avata, and I believe it shows the H icon (which I took as meaning home) having the behavior you are proposing to be implemented into Inav. Isn't it?

https://youtu.be/sA6vngripF8

**Comment by sdellava** [comment]
Yes. Exactly. I was not aware that Dji did it. Nice.

I was thinking that this feature can have other interesting uses. Being
able to show the home point means that we can show any points in the space.
So we can create a route of wp and they will be visible in sequence with an
additional  arrow pointing to the next wp.
This use can lead to "distance race" where recording the osd many pilots
can compete to run the same route in the shorter time.

Il lun 10 apr 2023, 02:29 Rodrigo Maia ***@***.***> ha
scritto:

**Comment by rts18** [comment]
@sdellava It would seem the most difficult part of this feature would be persuading all the digital manufactures to implement OSD canvas mode into their systems.  
I guess you're aware that both analog and digital OSD, use character display port.

Most of the requirements for such a feature already exist. But I hazard a guess, that the radar HUD code is as good as it can be.

@rmaia3d It appears the Goggle 2 and 03 already have canvas mode. But limit its use to the current provision of the open source platforms, and only to a level that suits their sales.
I could envision HDzero getting onboard quickly. and Walksnail being the last to attempt it. As yet, they still don't support iNAV custom OSD.

**Comment by sdellava** [comment]
@rts18 I'm not sure I understand your concern. I fly INAV and Walksnail and use radar mode which obviously uses characters to represent home point and uav position.

My proposal is to change the display of the home point, or other wp, according to the actual view.

The actual view is always done by "writing" characters in the space made by X columns and Y rows of characters.  Each point p(X,Y) in the grid corresponds to an angular range (horizontal and vertical). Thus the processing of the 3D map is simply to calculate at which point p(X,Y) it is appropriate to display the home symbol, depending on its location and the current view.

The only problem I really see with digital systems using the MSP protocol to get the data and display the OSD is that the refresh rate will not be high and this may make the 3D mode useless for free style. But I don't think anybody cares about a 3D map in free style. The use of this feature is certainly useful in Long Range and for aircraft.

**Comment by rts18** [comment]
>I'm not sure I understand your concern. I fly INAV and Walksnail and use radar mode which obviously uses characters to represent home point and uav position.

I was simply conveying the limitations of a character based OSD, comparing to the higher visual accuracy of a pixel drawn canvas display.
The present method jumps from character to character, and not smoothly from pixel to pixel. This limitation constrains HD vertical accuracy, from between 18 to 22 steps, depending on the system, and even less for analog. 

> So we can create a route of wp and they will be visible in sequence with an
additional  arrow pointing to the next wp. 

Isn't that what this present setting already does.
* `osd_hud_wp_disp`
 `osd_hud_homepoint`

**Comment by sdellava** [comment]
@rts18 more clear now .... and .... I totally miss the **hud** !!!

So yes, I guess it it what I was looling for and therefore, for the moment, I close this feature request.  

May be in the future I'll reopen if I'll find some additional need. 

Thanks all for the contribution.

**Comment by rmaia3d** [comment]
> @sdellava It would seem the most difficult part of this feature would be persuading all the digital manufactures to implement OSD canvas mode into their systems. I guess you're aware that both analog and digital OSD, use character display port.
> 
> Most of the requirements for such a feature already exist. But I hazard a guess, that the radar HUD code is as good as it can be.
> 
> @rmaia3d It appears the Goggle 2 and 03 already have canvas mode. But limit its use to the current provision of the open source platforms, and only to a level that suits their sales. I could envision HDzero getting onboard quickly. and Walksnail being the last to attempt it. As yet, they still don't support iNAV custom OSD.

Just a correction, Walksnail does fully support the Inav OSD, much better than the O3 compatibility mode. Only thing that Walksnail does not support (for now), concerning the Inav OSD, is custom fonts. But the default font includes all current icons and glyphs that Inav uses. The dev team at Walksnail is already working on adding custom font support and it will come in a future firmware update.

Also, I'm not sure what your concern regarding a "true canvas mode" for this feature is. Granted, the character positioning has a "lower resolution", going pixel by pixel would be far smoother, but the current character grid implementation does not impede such a feature.

**Comment by sdellava** [comment]
@rmaia3d thank for your clarifications.

I was aware about the "true canvas mode" but I'm not sure it will be implemented by WS. Maybe HDZero mostly used for race, but WS is much more interesting for long range (with both quads and airplanes) and freestyle. In this two cases the "pixel mode" could impact on the overall video quality requiring much more bandwith to transfer data, than the simple "characther mode" with low refresh rate.

Anyway, for long range,  that was my primary focus, the overly precision is not required. We just need an indication where the home is, just to simplify the orientation in from a new point of view.
