### ISSUE TITLE
New arming feature.

### ISSUE THREAD

**Issue by Lalbabu2001** [iNavFlight/inav#8965]
## Current Behavior
When i want to arm my quad i need to toggle a switch.
## Desired Behavior
I want to make it smart, reducing no of switches and complexity, just put the throttle full down and right ( like we used in multivii) to arm the quad.

And left to disarm! 
I know i made a request to add a feature to limit sticks boundries, that will create a conflict here  , 
So I also have a solution , we will use two limit slider one for trottle, and other for yaw, so that a certain limit this feature will work 
For an Example
If i the yaw stick is limited to 200 value , we will adjust the arming values to throttle=1000
And yaw= 1700 (1500+200)
For disarm throttle = 1000
  Yaw 1300(1500-200).

**Comment by MrD-RC** [comment]
Stick arming was removed for safety. It will not be added back. You need to arm with a switch.
