### ISSUE TITLE
Skystars H7 dual bmi270

### ISSUE THREAD

**Issue by Some-Won-1** [iNavFlight/inav#8967]
## Current Behavior
No firmware in 6.0 configurator to flash.

Requesting addition.

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav/pull/8954

**Comment by Some-Won-1** [comment]
I can not find the Skystars H7 HD, Dual gyro, BMI 270 in a stable release.
Should I not fly with this firmware? When will it be trustworthy?

**Comment by DzikuVx** [comment]
It was release ith INAV 6.1
