### ISSUE TITLE
Automatic flaperons in certain flight modes

### ISSUE THREAD

**Issue by robustini** [iNavFlight/inav#8968]
## Current Behavior

It would be very interesting if flaperons were automatically tied to gps or air speed, i.e. they would go into action when, for example, gps speed is below a certain speed, but not in takeoff where perhaps they can be extended manually.
This functionality is already present in Ardupilot and is described [here](https://ardupilot.org/plane/docs/flaperons-on-plane.html).

## Desired Behavior

They should be automatic only in some flight modes, escliuding Acro, Manual and Angle.
By setting, for example, 13 m/s groundspeed the flaperons go into action below that speed.
Therefore, it would also be interesting if iNav based Cruise (navigation) speed not on the amount of throttle but really using gps speed or airspeed, I have never understood why it is tied to a µs throttle value whether there is sensor technology capable of better performance.

## Suggested Solution

Two settable parameters:
1) speed below which the flaperons are automatically activated/deactivated
2) speed at which the flaperons extend and retracted (in degrees/second)
Obviously, this minimum speed threshold will have to be maintained for a period of time before the flaperons activate, to avoid continuous switching, for example 1 second.

**Comment by DzikuVx** [comment]
@robustini this can be done with Programming Framework without any code changes 
https://github.com/iNavFlight/inav/blob/master/docs/Programming%20Framework.md

**Comment by robustini** [comment]
Top, thanks!
