### ISSUE TITLE
ACCELOMETER and GYRO problem  FLYWOOF411 

### ISSUE THREAD

**Issue by ozmec** [iNavFlight/inav#8976]
I am experiencing an issue with the gyroscope and accelerometer in INAV.  I am not receiving any response from the gyroscope and accelerometer despite ensuring that the hardware is properly connected and wired. I also checked in betaflight and there is working fine.

I am using INAV version 6.0 and the FLYWOOF411_5IN1_AIO flight controller board. 
Firmware : 6.0.0. FLYWOOF411

![image](https://user-images.githubusercontent.com/71973785/231543095-14683846-66bb-4ef4-83fa-9139e4f976a7.png)

**Comment by mmosca** [comment]
What gyro does your board have?
