### ISSUE TITLE
Add ability to show 'stats_total_dist' in the OSD

### ISSUE THREAD

**Issue by Painless360** [iNavFlight/inav#8980]
## Current Behaviour
https://github.com/iNavFlight/inav/blob/master/docs/Settings.md shows that this is tracked but I can't find a way to have this shown in the OSD while flying., Just shown in the summary screen after each flight (when configured)

## Desired Behaviour
To be able to select and display this as an item on the OSD. Ideally to have the value updated 'LIVE' similar to the ODOMETER in a car or motorcycle too.

## Suggested Solution
Add stats_total_dist as an option in the OSD and look at being able to show it incrementing in real time in the OSD.

## Who does this impact? Who is this for?
All pilots who fly their model regularly and want to track total flight distance.

**Comment by Jetrell** [comment]
Just to clarify.. I assume you mean `Max Distance` under the stats ? 

![Stats](https://user-images.githubusercontent.com/47995726/231902644-633b54e0-9744-44f1-8bdf-1b6cdc39bfcd.JPG)

 `Stats_total_dist`.  The `Traveled Distance` odometer can already be displayed on the OSD. 

![td](https://user-images.githubusercontent.com/47995726/231904116-97884a16-277e-4f47-b13e-1cf0d1a374c0.JPG)
![dis](https://user-images.githubusercontent.com/47995726/231904305-a2a933df-dc68-42d3-b107-db5d45b63bbb.JPG)

**Comment by Sidd-86** [comment]
Trip distance resets on each flight, while "stats_total_dist" accumulates each trip and is essentially craft milage from all the flights combined, just like ODO meter in a car, and not its trip meter, which can be reset. 
Total distance data starts recording after "stats" are turned ON, by default its off, and are saved after each disarm. 
![43ab1297757b4425914ef3f56ee91433](https://user-images.githubusercontent.com/130835622/232209159-c1f5e860-55df-47b7-aa10-db95a37a522e.png)

![Screenshot_20230415_124451_Samsung Internet](https://user-images.githubusercontent.com/130835622/232209266-58e566e4-250a-4837-9e82-6b99dbe7ebc6.jpg)

Would be nice to be able to see these informations in one of the OSD layouts; aircraft lifetime total combined distance, combined flight time, energy used etc., which are also recorded/included when "stats" feature is turned ON.

**Comment by Jetrell** [comment]
Sorry @Painless360  and @Sidd-86 .. I'd forgot all about that feature..
The ironic thing, is that I have it enabled on an F411-wing build. 
```
stats = ON
stats_total_time = 2000
stats_total_dist = 2000
stats_total_energy = 1000
```
But I've never seen it display the Total's on the stats screen after disarming.

I assume the feature still exists. And hasn't been removed at some point ?
I imagine it would store the Odometer stats into the Eeprom. So I guess it would loose any store stats data when the FC is flashed on an update, with full chip erase.

**Comment by OptimusTi** [comment]
Looks like there's code for this for the stats screen. Looks like ODOMETER only shows if you're using "meters" and have the STATS on: 
![image](https://user-images.githubusercontent.com/45466510/232233711-3aa26610-ef2c-4de0-9f7f-356dde901299.png)

Printing stats_total_dist (converted to the proper unit) + getTotalTravelDistance() to the screen could work ??

**Comment by MrD-RC** [comment]
The total distance on the stats screen shows all units. The switch is to show in the appropriate units selected by the OSD. Will show the odometer distance in kilometres, miles, and nautical miles.

I've made a start on this. Not done any testing yet.

https://github.com/iNavFlight/inav/tree/MrD_Add-odometer-to-OSD
https://github.com/iNavFlight/inav-configurator/tree/MrD_Add-odometer-to-OSD

**Comment by Sidd-86** [comment]
Thanks to all of you for looking into this.
