### ISSUE TITLE
Servo motor on boat/rover not returns to neutral position when applying throttle in default ACRO Mode.

### ISSUE THREAD

**Issue by sakisdog** [iNavFlight/inav#8990]
## Current Behavior

Tested in Rover and Boat with iNav v4.1 on a Omnibus F4 Pro. Did reinstall the firmware several times. I use reversible esc/motors. 
When I arm the flight controller and push the throttle stick upwards, if I move the yaw stick to the left or right repeatedly, the servo fails to return to its neutral position until I move the throttle down. This happens only in default mode/ACRO. If i switch to manual mode servo works as expected. If i change the Stabilized Yaw setting to RC Yaw servo works fine.
Check the video -> https://youtu.be/93V1htoIA8w
## Steps to Reproduce

1. Arm the rover/boat
2. Move throttle up a little bit
3. Move YAW stick left or right 
4. The servo arm does not return to it's neutral position until you move the throttle down.

## Expected behavior

The Servo should return to it's neutral position

## Additional context

https://youtu.be/93V1htoIA8w
---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
This is expected, PID Controller accumulated error. Advice: do not use Acro on rover/boats or lower PID YAW I component to `0`
