### ISSUE TITLE
New target for new Foxeer H7 43

### ISSUE THREAD

**Issue by nemfpv** [iNavFlight/inav#9003]
Current Behavior
I can't install INAV 6 on my new FC Foxeer H7 43

Desired Behavior
I wish I had the possibility to install Inav on the new board instead of its original betaflight for my long range drone

Suggested Solution
probably the Inav firmware on this FC would have many more features available to make long range flight safer

Since Inav is an excellent firmware for long range drones, I'd like to give this FC a chance too. The board has several UARTs available and a Barometer.
Who does this impact? Who is this for?
People using Long range Drone
Additional context
here is the Flight Controller link https://www.foxeer.com/foxeer-h7-mpu6000-fc-8s-dual-bec-barometer-x8-g-503

**Comment by MrD-RC** [comment]
You should contact Foxeer and let them know that there is demand for an INAV target for their flight controller. 

There is a new hardware policy that must be followed. https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
