### ISSUE TITLE
INAV 6.1 RC1 BFHDCOMPAT OSD AHI Not Horizontally Centered

### ISSUE THREAD

**Issue by prelator** [iNavFlight/inav#9006]
## Current Behavior
Using the new BFHDCOMPAT OSD mode with the DJI O3 Air Unit and DJI Goggles V2 set to HD display mode, the artificial horizon indicator and its sidebars at not centered, but are way off to the left of the screen. Movable elements can be moved into the proper positions, but the fixed elements like the AHI cannot be positioned in the center of the screen. 

The picture below shows what this looks like (sorry for bad photo - can't record OSD on Goggles V2 DVR). Note that the other elements on the screen can be moved to the correct positions even though they're not in this photo. The AHI being off center is the important part.

![20230423_140557](https://user-images.githubusercontent.com/5984862/233876950-410961e8-e260-4f68-bd7a-c29a64708ab2.jpg)

## Steps to Reproduce

1.  Using INAV 6.1 RC1, set OSD mode to BFHDCOMPAT with a DJI O3 Air Unit and DJI Goggles V2 (not sure if happens with Goggles 
2. Save OSD settings.

## Expected behavior
Fixed OSD elements including the artificial horizon indicator and its sidebars should be positioned in the center of the screen in HD mode as they are in SD mode.

## Suggested solution(s)
Some sort of horizontal offset may be needed to ensure the fixed position OSD elements are centered in the HD canvas.

---
- FC Board name and vendor: INAV/MATEKF405TE_SD 6.1.0 Apr 21 2023 / 17:48:27 (https://github.com/iNavFlight/inav/commit/2d7a057d03a33e7cb6ff2c33673faf264f4775a7)
- INAV version string: GCC-10.2.1 20201103 (release)

**Comment by mmosca** [comment]
Can you share your diff?

The elements are too far left to be a simple issue with alignment. Do you have any right aligned elements?

The image seems to sugest you are set to BF43COMPAT on INAV, but have the goggles set to HD canvas size.

**Comment by prelator** [comment]
The picture above is confusing, because while it was set to BFHDCompat mode, I hadn't actually moved any of the elements from their regular BF43COMPAT mode positions. I could however move them to the right side of the screen and that would work fine. I didn't get a picture of it when I did this, but at one point I had all the moveable elements positioned around the perimeter of the screen but the AHI was still off to the left. Changing from regular BFCOMPAT to HD BFCOMPAT mode didn't make any difference where the AHI was positioned when the Goggles V2 were set to to HD display mode.

**Comment by happylandings** [comment]
The HD canvas mode was added to Goggles 2. You try to apply it on goggles V2.

**Comment by prelator** [comment]
Update: I upgraded to 6.1 stable and this issue is still happening. With BFHDCOMPAT mode in INAV and the HD display mode set in the Goggles V2, the AHI is still way off to the left, as pictured below. I can move other elements to the right positions (you can see my RSSI readouts on the far right side of the screen, which are the only ones I moved), but the AHI and other fixed elements are still way over on the left. If I change the offset settings for the AHI, it moves it up and down just fine, but there is no setting to move it side to side. One possible solution would be to add a horizontal AHI offset setting in future releases. Until this is fixed, HD mode will still not be usable for the O3 Air Unit and Goggles V2. Not sure if this happens with the Goggles 2 or not.

![20230512_212047](https://github.com/iNavFlight/inav/assets/5984862/0e7ea1d5-9653-4222-a308-08ba3cd8410a)

My complete diff is below:
`# diff all

# version
# INAV/MATEKF405TE_SD 6.0.0 Mar 22 2023 / 10:21:39 (084101ac)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# Mixer: motor mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000

# Mixer: servo mixer
smix reset

smix 0 1 1 100 0 -1
smix 1 2 0 100 0 -1
smix 2 3 0 100 0 -1
smix 3 4 2 100 0 -1

# Outputs [servo]
servo 1 1000 2000 1670 -100
servo 2 1000 2000 1515 -100
servo 3 1000 2000 1595 -100
servo 4 1000 2000 1500 -100

# safehome

# features
feature BAT_PROF_AUTOSWITCH
feature MOTOR_STOP
feature GPS
feature PWM_OUTPUT_ENABLE
feature FW_AUTOTRIM

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS
blackbox GYRO_RAW
blackbox -PEAKS_R
blackbox -PEAKS_P
blackbox -PEAKS_Y

# Receiver: Channel map

# Ports
serial 3 33554432 115200 115200 0 115200
serial 4 2 115200 115200 0 115200

# LEDs

# LED color

# LED mode_color

# Modes [aux]
aux 0 0 0 1600 2100
aux 1 2 1 1325 1450
aux 2 12 1 900 1075
aux 3 53 1 1525 1675
aux 4 11 1 1750 1875
aux 5 10 1 1925 2100
aux 6 21 3 1900 2100
aux 7 54 3 1400 1600
aux 8 36 6 1400 1600
aux 9 13 2 1900 2100
aux 10 47 5 1900 2100

# Adjustments [adjrange]

# Receiver rxrange

# temp_sensor

# Mission Control Waypoints [wp]
#wp 0 invalid

# OSD [osd_layout]
osd_layout 0 0 27 2 H
osd_layout 0 1 0 14 V
osd_layout 0 2 0 0 V
osd_layout 0 3 8 6 V
osd_layout 0 4 8 6 V
osd_layout 0 6 24 14 V
osd_layout 0 7 14 13 V
osd_layout 0 9 14 15 V
osd_layout 0 11 9 15 V
osd_layout 0 12 9 14 V
osd_layout 0 13 3 8 H
osd_layout 0 14 0 1 V
osd_layout 0 15 24 8 V
osd_layout 0 20 12 0 V
osd_layout 0 21 1 0 V
osd_layout 0 22 15 2 V
osd_layout 0 23 0 2 V
osd_layout 0 24 6 1 V
osd_layout 0 25 23 6 H
osd_layout 0 26 24 10 V
osd_layout 0 28 24 15 H
osd_layout 0 29 11 12 H
osd_layout 0 30 2 3 V
osd_layout 0 34 11 1 V
osd_layout 0 37 0 12 H
osd_layout 0 38 0 15 V
osd_layout 0 40 24 13 V
osd_layout 0 43 0 0 V
osd_layout 0 54 0 13 V
osd_layout 0 85 3 8 V
osd_layout 0 96 24 6 V
osd_layout 0 100 14 14 H
osd_layout 0 108 17 2 H
osd_layout 0 109 24 0 V
osd_layout 0 110 26 1 V
osd_layout 0 111 25 4 H
osd_layout 0 112 25 2 V
osd_layout 0 128 0 11 V

# Programming: logic
logic 0 1 -1 51 1 9 0 1000 0
logic 1 1 0 42 0 2 0 0 0
logic 2 1 -1 51 1 9 0 1500 0
logic 3 1 2 42 0 1 0 0 0
logic 4 1 -1 51 1 9 0 2000 0
logic 5 1 4 42 0 3 0 0 0
logic 6 1 -1 8 3 0 3 2 0
logic 7 1 6 42 0 1 0 0 0

# Programming: global variables

# Programming: PID controllers

# master
set gyro_main_lpf_hz = 25
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 30
set gyro_zero_x = 12
set gyro_zero_y = -8
set ins_gravity_cmss =  975.946
set acc_hardware = ICM42605
set acczero_x = -4
set acczero_y = 4
set acczero_z = -6
set accgain_x = 4094
set accgain_y = 4100
set accgain_z = 4090
set align_mag = CW270FLIP
set mag_hardware = NONE
set baro_hardware = SPL06
set blackbox_rate_denom = 32
set motor_pwm_protocol = STANDARD
set failsafe_procedure = RTH
set platform_type = AIRPLANE
set has_flaps = ON
set model_preview_type = 14
set small_angle = 180
set ahrs_inertia_comp_method = ADAPTIVE
set disarm_kill_switch = OFF
set applied_defaults = 3
set gps_sbas_mode = AUTO
set gps_ublox_use_galileo = ON
set airmode_type = STICK_CENTER_ONCE
set nav_wp_radius = 5000
set nav_wp_max_safe_distance = 500
set nav_rth_climb_ignore_emerg = ON
set nav_rth_allow_landing = FS_ONLY
set nav_rth_alt_mode = EXTRA
set nav_rth_alt_control_override = ON
set nav_rth_altitude = 10000
set nav_rth_home_altitude = 8000
set nav_fw_bank_angle = 45
set nav_fw_climb_angle = 30
set nav_fw_control_smoothness = 5
set nav_fw_launch_accel = 1300
set nav_fw_launch_max_angle = 70
set nav_fw_launch_motor_delay = 0
set nav_fw_launch_timeout = 10000
set nav_fw_launch_max_altitude = 10000
set nav_fw_launch_climb_angle = 30
set nav_fw_allow_manual_thr_increase = ON
set osd_video_system = BF43COMPAT
set osd_units = IMPERIAL
set osd_time_alarm = 0
set osd_alt_alarm = 0
set osd_dist_alarm = 0
set osd_neg_alt_alarm = 0
set osd_link_quality_alarm = 50
set osd_rssi_dbm_alarm = -100
set osd_switch_indicators_align_left = OFF
set tz_offset = -420
set tz_automatic_dst = USA

# profile
profile 1

set fw_p_pitch = 15
set fw_i_pitch = 10
set fw_d_pitch = 5
set fw_ff_pitch = 182
set fw_p_roll = 18
set fw_i_roll = 12
set fw_d_roll = 7
set fw_ff_roll = 20
set fw_p_yaw = 55
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set fw_yaw_iterm_freeze_bank_angle = 15
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set fw_level_pitch_trim =  2.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 29
set pitch_rate = 7
set yaw_rate = 3

# profile
profile 2

set fw_p_pitch = 15
set fw_i_pitch = 10
set fw_d_pitch = 5
set fw_ff_pitch = 18
set fw_p_roll = 15
set fw_i_roll = 10
set fw_d_roll = 7
set fw_ff_roll = 8
set fw_p_yaw = 25
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 80
set fw_p_level = 40
set fw_i_level = 0
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.500
set fw_iterm_limit_stick_position =  1.000
set nav_fw_pos_z_p = 15
set nav_fw_pos_z_d = 5
set nav_fw_pos_xy_p = 60
set d_boost_min =  1.000
set d_boost_max =  1.000
set tpa_rate = 1
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 40
set pitch_rate = 9
set yaw_rate = 3
set manual_roll_rate = 65
set manual_pitch_rate = 60

# profile
profile 3

set fw_i_pitch = 30
set fw_d_pitch = 3
set fw_ff_pitch = 150
set fw_i_roll = 30
set fw_d_roll = 3
set fw_ff_roll = 8
set fw_p_yaw = 25
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set fw_p_level = 40
set fw_i_level = 0
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_iterm_throw_limit = 500
set fw_turn_assist_pitch_gain =  0.500
set fw_iterm_limit_stick_position =  1.000
set nav_fw_pos_z_p = 15
set nav_fw_pos_z_d = 5
set nav_fw_pos_xy_p = 60
set d_boost_min =  1.000
set d_boost_max =  1.000
set fw_level_pitch_trim =  4.000
set tpa_rate = 1
set rc_expo = 60
set rc_yaw_expo = 30
set roll_rate = 40
set pitch_rate = 9
set yaw_rate = 3
set manual_roll_rate = 65
set manual_pitch_rate = 60

# battery_profile
battery_profile 1

set bat_cells = 4
set vbat_min_cell_voltage = 310
set vbat_warning_cell_voltage = 330
set battery_capacity = 8400
set battery_capacity_warning = 2100
set battery_capacity_critical = 1260
set throttle_idle =  5.000
set nav_fw_launch_thr = 1900
set nav_fw_launch_idle_thr = 1200

# battery_profile
battery_profile 2

set bat_cells = 4
set battery_capacity = 4000
set battery_capacity_warning = 1000
set battery_capacity_critical = 600
set throttle_idle =  5.000

# battery_profile
battery_profile 3

set throttle_idle =  5.000

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

# `

**Comment by dugdiamond-git** [comment]
I am also getting the same issue with 6.1. GogglesV2 and Mateksys H743WLITE.

Here is my DIFF:

# version
# INAV/MATEKH743 6.1.0 May 11 2023 / 13:29:16 (d6ce6e70)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# Mixer: motor mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000

# Mixer: servo mixer
smix reset

smix 0 1 1 100 0 -1
smix 1 2 0 100 0 -1
smix 2 3 0 100 0 -1
smix 3 4 2 100 0 -1
smix 4 5 8 100 0 -1

# Outputs [servo]
servo 1 1000 2000 1500 -100
servo 2 1000 2000 1500 -100
servo 3 1000 2000 1500 -100
servo 4 1000 2000 1500 -100
servo 5 1000 2000 1500 -100

# safehome

# features
feature -TX_PROF_SEL
feature -BLACKBOX
feature THR_VBAT_COMP
feature MOTOR_STOP
feature GPS
feature PWM_OUTPUT_ENABLE
feature FW_LAUNCH
feature FW_AUTOTRIM

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS
blackbox -GYRO_RAW
blackbox -PEAKS_R
blackbox -PEAKS_P
blackbox -PEAKS_Y

# Receiver: Channel map

# Ports
serial 1 2 115200 115200 0 115200
serial 3 262144 115200 115200 0 115200
serial 7 33554432 115200 115200 0 115200

# LEDs

# LED color

# LED mode_color

# Modes [aux]
aux 0 0 1 1950 2100
aux 1 1 3 900 1050
aux 2 2 3 1400 1600
aux 3 12 3 1950 2100
aux 4 53 4 900 1050
aux 5 11 6 900 1050
aux 6 10 6 1950 2100
aux 7 21 5 1950 2100
aux 8 54 5 900 1050
aux 9 36 7 900 1050

# Adjustments [adjrange]

# Receiver rxrange

# temp_sensor

# Mission Control Waypoints [wp]
#wp 0 invalid

# OSD [osd_layout]
osd_layout 0 0 47 0 V
osd_layout 0 1 2 0 V
osd_layout 0 7 25 15 V
osd_layout 0 9 24 14 V
osd_layout 0 11 2 7 V
osd_layout 0 12 1 8 V
osd_layout 0 13 2 16 V
osd_layout 0 14 37 0 V
osd_layout 0 15 1 6 V
osd_layout 0 22 22 1 V
osd_layout 0 23 24 1 V
osd_layout 0 25 40 6 H
osd_layout 0 26 41 9 V
osd_layout 0 27 7 15 H
osd_layout 0 28 46 3 V
osd_layout 0 30 13 16 V
osd_layout 0 32 2 1 V
osd_layout 0 34 21 0 V
osd_layout 0 37 2 3 H
osd_layout 0 38 24 2 V
osd_layout 0 40 46 4 H
osd_layout 0 41 8 17 H
osd_layout 0 42 8 16 H
osd_layout 0 46 41 9 H
osd_layout 0 47 41 10 H
osd_layout 0 85 2 15 V
osd_layout 0 96 1 13 V
osd_layout 0 110 46 12 V
osd_layout 0 112 46 13 H
osd_layout 0 119 22 17 V
osd_layout 0 123 3 5 H
osd_layout 0 130 1 10 H

# Programming: logic

# Programming: global variables

# Programming: PID controllers

# master
set gyro_main_lpf_hz = 25
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 30
set gyro_zero_x = -22
set gyro_zero_y = 9
set ins_gravity_cmss =  989.419
set acc_hardware = ICM42605
set acczero_x = -6
set acczero_y = 6
set acczero_z = 20
set accgain_x = 4087
set accgain_y = 4087
set accgain_z = 4101
set align_mag = CW270FLIP
set mag_hardware = NONE
set baro_hardware = SPL06
set pitot_hardware = MS4525
set serialrx_provider = CRSF
set motor_pwm_protocol = STANDARD
set failsafe_procedure = RTH
set align_board_pitch = 2
set align_board_yaw = 1800
set vbat_scale = 2100
set current_meter_scale = 150
set platform_type = AIRPLANE
set model_preview_type = 14
set small_angle = 180
set ahrs_inertia_comp_method = ADAPTIVE
set applied_defaults = 3
set gps_provider = UBLOX7
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set airmode_type = STICK_CENTER_ONCE
set nav_wp_radius = 5000
set nav_wp_max_safe_distance = 500
set nav_rth_allow_landing = NEVER
set nav_rth_altitude = 5000
set nav_rth_trackback_mode = FS
set safehome_usage_mode = RTH_FS
set nav_fw_bank_angle = 45
set fw_loiter_direction = YAW
set nav_fw_control_smoothness = 2
set nav_fw_launch_max_angle = 75
set nav_fw_launch_motor_delay = 100
set nav_fw_launch_max_altitude = 60000
set nav_fw_launch_climb_angle = 25
set nav_fw_allow_manual_thr_increase = ON
set osd_video_system = BFHDCOMPAT
set osd_units = METRIC_MPH
set osd_dist_alarm = 0
set osd_neg_alt_alarm = 0
set osd_crosshairs_style = AIRCRAFT
set osd_horizon_offset = 1
set osd_main_voltage_decimals = 2
set osd_plus_code_digits = 13
set osd_switch_indicators_align_left = OFF
set i2c_speed = 800KHZ
set tz_automatic_dst = EU
set dshot_beeper_enabled = OFF

# profile
profile 1

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 80
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_p_yaw = 50
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 18
set pitch_rate = 9
set yaw_rate = 3

# profile
profile 2

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 80
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_p_yaw = 50
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 18
set pitch_rate = 9
set yaw_rate = 3

# profile
profile 3

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 80
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_p_yaw = 50
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 18
set pitch_rate = 9
set yaw_rate = 3

# battery_profile
battery_profile 1

set bat_cells = 3
set battery_capacity = 6500
set battery_capacity_warning = 2600
set battery_capacity_critical = 1950
set nav_fw_max_thr = 1800
set nav_fw_launch_thr = 1800
set nav_fw_launch_idle_thr = 1250

# battery_profile
battery_profile 2

set throttle_idle =  5.000

# battery_profile
battery_profile 3

set throttle_idle =  5.000

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

#

**Comment by mmosca** [comment]
I tried to reproduce it, but no luck.

Did you guys change the video system on the cli? The configurator appears to move the AHI whenever it changes canvas size for me.

**Comment by prelator** [comment]
I did it in the configurator.

**Comment by Ifeo-A** [comment]
@prelator @mmosca 
I just got the DJI Goggles 2 and I've got the same issue. I'm on INAV Configurator 6.1.0

**Comment by MrD-RC** [comment]
Did you reboot the flight controller after changes the video for at and reboot your DJI system?

**Comment by dugdiamond-git** [comment]
> Did you reboot the flight controller after changes the video for at and reboot your DJI system?

Inav was not the issue.... It was that WTFOS that needed updating. It all works now as axpected. Thanks for your reply

**Comment by MrD-RC** [comment]
I saw an email reply to this issue, which I can’t see here on the site saying:

> Inav was not the issue.... It was that WTFOS that needed updating. It all works now as axpected. Thanks for your reply

With WTFOS, don’t use BF43COMPAT or BFHDCOMPAT. You should use the WTF video type setting. You will be compromising your OSD by using the COMPAT types with WTF. They don’t support all elements and have a small area.

**Comment by BigMacOne** [comment]
Just got goggles 3 and O3 Au. Matek 722 I nav 6.1.0. Goggles on HD canvas BTcomp setting... Same issue. AhI way off left. Initially all the fonts were a mess or not showing including question marks... After multiple re boots on things it is improving. Fonts mostly usable but horizon indicator stuck left! Old Air unit on goggles V2 with wtfos was luvly.

**Comment by prelator** [comment]
I actually solved this issue on my Goggles V2 simply by power cycling both the goggles and flight controller. My mistake was thinking just changing OSD settings in the INAV configurator fully took effect without rebooting. Most OSD settings do but not switching to HD mode.

**Comment by BigMacOne** [comment]
> I actually solved this issue on my Goggles V2 simply by power cycling both the goggles and flight controller. My mistake was thinking just changing OSD settings in the INAV configurator fully took effect without rebooting. Most OSD settings do but not switching to HD mode.

Early days with V3 goggles O3. I will try 'fully' re booting the kit making changes on OSD. Fingers crossed.

**Comment by BigMacOne** [comment]
No luck with re boot scenario. On closer examination the entire display is left shifted ie values displayed in config screen to extreme right, appear at centre on goggles. Hence AhI is way left. Can't position anything in goggles to right of centre scree. As if 50% of display is missing! I like the goggles, light, comfortable and great display but this is going to be a head banger....

**Comment by BigMacOne** [comment]
Suppose I will grow to love AhI on left eye... Like an Apache pilot monicle.

**Comment by samsab1** [comment]
hello same pb here with speedybee f405 WING with inav 7.1.2 and airunit O3 + google2: air cross and horizon side bar not centred whate ever BFHD or BF43COMP. i do not  know what to do do

with F405 V4 speedybee  on a quad, no pb, O3 is centered

**Comment by BigMacOne** [comment]
Happy to say I have fixed mine! Flashed FC to I nav 6.0.1. From 6.0.0. This small upgrade gives you another osd option in configurator... DJIHDCOMP. That was it. All centred. Can't comment on 7.1.2 but sure you will need the DJIHD option somewhere along the process. Good luck.

**Comment by BigMacOne** [comment]
Should have added its a screen format problemo ie 4.3 or 16.9

**Comment by BigMacOne** [comment]
In CLI enter    if it will accept it? 



set osd_video_system = DJIHDCOMPAT

**Comment by samsab1** [comment]
# set osd_video_system = DJIHDCOMPAT
### ERROR: Invalid value. Allowed values: AUTO, PAL, NTSC, HDZERO, DJIWTF, AVATAR, BF43COMPAT, BFHDCOMPAT

**Comment by BigMacOne** [comment]
That must be because of the I nav version installed...  Take it configurator and FC flash are same? There must be another command for V 7......  I can confirm on 7.i.0 that goggles V2 work fine on old air unit. Mine are wtf rooted. Check wiki for problem....

**Comment by BigMacOne** [comment]
On goggles settings menu, check for canvas or HD mode... Set HD if you have that option?

**Comment by samsab1** [comment]
i use inav configurator 7.1.1 and FC SPEEDYBEE F405 Wing flashed with INAV **7.1.2**; do you suggest to downgrad firmware to 7.1.1?

**Comment by samsab1** [comment]
So, my last setting 

inav 7.1.2
uart5: MSP DISPLAY
OSD: BFHD

Google2 canvas: HD



don't ask why, **but now it works** as it should.....
thanks again for your help
i was struggeling since 48 hours, but now, it works, so strange.

**Comment by BigMacOne** [comment]
BTW, I have a FW on I nav 7.1.0 with speedybee f405 and original air unit V2 goggles. Will be fitting O3 to it soon and goggles 3 let you know what happens re osd!
