### ISSUE TITLE
INAV 6.0: No ESC Temperature in OSD

### ISSUE THREAD

**Issue by x8n1620** [iNavFlight/inav#9008]
## Current Behavior
My ESC Telemetry is only partially working. RPM works fine, the Temp-Sensor is not working. Always 0°C
When I disable UART1 or pull the connector, the RPM is already gone, so my ESC Telemetry configuration is working.
I try multiple Baud-Rates, no change.
I try to switch Auto Telemetry On or Of in the ESC, no change.

FC: Matek F405-WMN
ESC: Holybro Tekko32 F4 45A

## Steps to Reproduce
FC: Matek F405-WMN
ESC: Holybro Tekko32 F4 45A
ESC Telemetry on UART1

## Expected behavior
ESC Temp is shown in the OSD

## Suggested solution(s)
?

Version:
- FC Board name and vendor: Matek F405-WMN, Target: MATEKF405TE
- INAV version string: # INAV/MATEKF405TE 6.0.0 Mar 22 2023 / 10:20:32 (084101ac)
# GCC-10.2.1 20201103 (release)

**Comment by MrD-RC** [comment]
That ESC doesn't output temperature telemetry.
