### ISSUE TITLE
INAV 610RC1 - Virtual Airspeed Sensor stopped working

### ISSUE THREAD

**Issue by Awapp** [iNavFlight/inav#9020]
Virtual Airspeed Sensor stopped working: 
I did an official INAV600 clean install in 2 wings with Matek F411WSE and F405WMN. 
Fly nearly all the time on predicted Airspeed - pitot_hardware = virtual, works like a charm.  
Updated to official INAV610RC1, Diff all. 
Everything else remained the same. Dump All is equal to INAV600 dump all.
Airspeed now blinking 0 kmh.  
Went back to official NAV600 and airspeed works again.

**Comment by MrD-RC** [comment]
Fixed by https://github.com/iNavFlight/inav/pull/9019
