### ISSUE TITLE
[6.1-RC1] (Auto)-throttle icon analog OSD

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav#9041]
## Current Behavior
(Auto)-throttle icon on OSD shows weird "I" sign in front of it.
Using ANALOG OSD.
(And yes, I updated my fonts on v6.1 RC1 with lipo connected.)

## Steps to Reproduce
1. Add (Auto) throttle icon to analog OSD

## Expected behavior
Just show the S icon as it was before.
The weird I sign is just unwanted clutter.

## Suggested solution(s)
Remove large I sign from the auto-throttle OSD element.

## Additional context
Picture:
![auto_throttle_icon](https://user-images.githubusercontent.com/31951195/236688034-e0dcbc65-10d4-4a49-9e5f-d9ba92955acd.jpg)

---

 version
 INAV/MATEKF405 6.1.0 Apr 21 2023 / 17:41:41 (2d7a057d)
 GCC-10.2.1 20201103 (release)

- FC Board name and vendor: MATEKF405
- INAV version string: 6.1 RC1

**Comment by MrD-RC** [comment]
That is showing that is is the scaled throttle.

**Comment by 0crap** [comment]
OK, thx.
Still unwanted but OK, it is what it is.
