### ISSUE TITLE
Feature Request: Unconstrained altitude OSD readout

### ISSUE THREAD

**Issue by prelator** [iNavFlight/inav#9048]
## Current Behavior
OSD altitude readout is limited to only 3 characters and switches to either kilometers or kilo-feet for numbers over 1000.

## Desired Behavior
Digital OSDs have plenty of room for more than 3 characters for altitude. It would be really nice if there were a setting to allow the altitude readout to be unconstrained in length, with values staying in feet for imperial and meters for metric. In the US especially, altitude is always in feet so having it display values like 1.50 for 1500 feet just looks weird and lacks precision. I understand this solution was adopted solely because of a 3 character limit on the altitude readouts, which seems unnecessary since other displays on the OSD are able to display more than 3 characters just fine.

## Suggested Solution
Remove the character limit for OSD altitude displays and allow it to be unconstrained. Stop converting to kilometers / kilo-feet for numbers above 1000. It would be fine if this was an optional setting.

## Who does this impact? Who is this for?
Users who fly at altitudes over 1000 feet/meters, or anyone who is using the MSL altitude display and lives at an altitude over 1000 feet/meters.

**Comment by Zimenkov** [comment]
Absolutely agree. 1.03 and 1030 take the same four digits. We need more precise during flight. The same for the altitude and for the distance. 
![AltBetter](https://github.com/iNavFlight/inav/assets/36876767/671918fe-f651-4959-a8b3-a68a5cb71668)
