### ISSUE TITLE
OSD - HD Canvas mode

### ISSUE THREAD

**Issue by happylandings** [iNavFlight/inav#9049]
## Current Behavior
In HD canvas mode all elements in OSD are smaller....

## Desired Behavior
Is it possible to have some elements bigger e.g. Artificial Horizon?

Also, is it possible to have warnings shown in red colour?

Thanks.

**Comment by MrD-RC** [comment]
The resolution is defined by DJI, as is the font. So there is nothing INAV can do to change this. If you want a larger font, go back to using BF43COMPAT.

Also, no. We can’t have warnings in red. Currently no infrastructure exists to do this in INAV. If it did, DJI control the font.
