### ISSUE TITLE
Foxeer F722 v4 no accelerometer or gyro

### ISSUE THREAD

**Issue by pendor** [iNavFlight/inav#9059]
## Current Behavior
INAV 6.1.0 has no accel or gyro for FOXEERF722V4

```
INAV/FOXEERF722V4_X8 6.1.0 May 11 2023 / 12:04:39 (d6ce6e70)
GCC-10.2.1 20201103 (release)
System Uptime: 59 seconds
Current Time: 2023-05-20T21:40:15.430+00:00
Voltage: 15.44V (4S battery - OK)
CPU Clock=216MHz, BARO=DPS310, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=UNAVAILABLE, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
```

## Steps to Reproduce
1. Install on recently made Foxeer F722v4

## Expected behavior
Accel & Gyro

## Suggested solution(s)
Add MPU6000 to config (PR inbound).  It looks like Foxeer may have made a late revision to the board that switched from ICM42605 to MPU6000.

---

- FC Board name and vendor: FOXEERF722V4_X8
- INAV version string: INAV/FOXEERF722V4_X8 6.1.0 May 11 2023 / 12:04:39 (d6ce6e70)

**Comment by DzikuVx** [comment]
fixed by #9070
