### ISSUE TITLE
Multishot not sending valid signal on power on

### ISSUE THREAD

**Issue by odddollar** [iNavFlight/inav#9064]
## Current Behaviour

I have an ESC that doesn't run BLHeli or support Dshot, so I'm using Multishot. The ESC is a Full Metal Racing 22A 2-4s. When the flight controller is plugged into my laptop and is receiving power, then the battery is plugged into the plane, the ESC makes a series of beeps that indicates it's receiving a valid Multishot signal and I am able to control the motor through the outputs tab of Inav Configurator.

Then when I disconnect my laptop and plug in the plane's battery, the ESC makes a series of beeps that indicate it isn't receiving a valid signal. If I plug in my laptop to the flight controller, then the battery and wait for the ESC to receive a valid Multishot signal, then unplug my laptop, I am able to arm and control the motor as usual via my transmitter.

It appears as though the flight controller isn't sending out a valid Multishot signal as soon as it is powered on. I am not aware of the firmware this ESC uses, and I only have the manual for the Full Metal Racing 30A 2-6s ESC, the bigger brother of the one I'm using. These manual images are attached below.

## Steps to Reproduce

Works
1. Power on flight controller without powering on ESC
2. Power on ESC after several seconds
3. ESC receives valid Multishot signal
4. Control throttle as normal

Doesn't work
1. Power on ESC and flight controller simultaneously
2. ESC doesn't receive valid Multishot signal

## Expected behaviour

The ESC makes the series of beeps indicating a valid Multishot signal on power on, without having to power on the flight controller beforehand.

## Suggested solution(s)

Make the flight controller emit a valid Multishot signal immediately after power on.

## Additional context
[Manual for ESC](https://imgur.com/a/RbV9oK1)

[dump all](https://pastebin.com/TLRB98yT)

- FC Board name and vendor: JHEMCU F411 NOXE v3
- INAV version string: INAV/JHEMCUF411NOXEv3 6.1.0 May 16 2023 / 14:09:37 (d6ce6e70)

**Comment by DzikuVx** [comment]
Sending multishot immediately on boot is not possible as FC has to boot before setting anything on outputs.
What you experience is a problem with ESC as ESC should wait with protocol detection until valid frames arrive. All ESC I ever tested were doing it correctly
