### ISSUE TITLE
Is it possible to increase OSD refresh rate from 1Hz to 2 or 4 Hz in WTF-OS?

### ISSUE THREAD

**Issue by DarthPlasma** [iNavFlight/inav#9068]
## Current Behavior
The OSD refreshes at 1Hz rate. Although it is completely accettable, it would be useful to have double or quadruple that rate.

## Desired Behavior
4 Hz OSD refresh rate

## Who does this impact? Who is this for?
Anyone

**Comment by MrD-RC** [comment]
I don’t know where you saw that. The MSP DisplayPort updates at around 60Hz.

The draw function is called at 250Hz. The actual draw is performed every 4th iteration (62.5Hz). This updates all changed characters. The full screen redraw is also called every 1 second. The latter can be changed in CLI. For example, setting it to 5 would be every 0.5 seconds. However, that setting is a balance. You should only need to change it of you have a lot of artifacting. Also, with range or other signal losses, you could see loss of OSD if this is set too low. The default is a decent average.

**Comment by MrD-RC** [comment]
![Uploading IMG_8964.jpeg…]()
