### ISSUE TITLE
UAV does stop and hover during RTH trackback, sometimes for very long, before going towards the next

### ISSUE THREAD

**Issue by DarthPlasma** [iNavFlight/inav#9069]
## Current Behavior
When testing RTH trackback, the quad follows the previous positions recorded but sometimes it stops (sometimes for 30 seconds) and howers in a particular waypoint, consuming battery and delaying the recovery of the link in case of a failsafe or a video link loss

## Steps to Reproduce
Just flyin some lines and angles and then hit RTH or force the failsafe by switch

## Expected behavior
Once the quad reaches the waypoint should rotate and go to the next, without howering for longer than 1-2 seconds

## Suggested solution(s)
I suppose that some checks that the quad is really in the position give false negatives, so maybe increasing the tolerance (or letting it to be chosen by the operator) could solve it.

---

- FC Board name and vendor: MAMBA H743 and Hakute H7
- INAV version string: 6.0.0

**Comment by Jetrell** [comment]
If `WAYPOINT RADIUS` or `ENFORCE ALTITUDE AT WAYPOINT` is set too low. The quad will pause until it gets within the distance of the tracking marker, you have set on those functions. Then it will proceed to the next Trackback point.
 This will occur more often in windy conditions.

Increase the Waypoint radius. Or turn off Enforce altitude at waypoint. to prevent this. 

![Capture](https://github.com/iNavFlight/inav/assets/47995726/4240b027-77d8-4d12-8e4b-098064d4c388)

**Comment by DarthPlasma** [comment]
The enforce altitude was already disabled (0) and the waypont radius was 100cm, increased it to 2.5meters

**Comment by breadoven** [comment]
The other option is to use `nav_mc_wp_slowdown` which works with Trackback from 6.1. This should stop it hesitating at trackpoints as it tries to get within the waypont radius "tag" distance.
