### ISSUE TITLE
Use mavlink_msg_home_position to publish home position (instead of mavlink_msg_gps_global_origin)

### ISSUE THREAD

**Issue by Consti10** [iNavFlight/inav#9074]
## Current Behavior
mavlink_msg_gps_global_origin is used to publish the home position. I don't think this is the best fit though (it creates incompability with gcs that work with ardupilot)

## Desired Behavior
INAV shall work just as well with gcs that are also used with ardupilot.

## Suggested Solution
Replace mavlink_msg_gps_global_origin with mavlink_msg_home_position

## Who does this impact? Who is this for?
All inav users using mavlink telemetry.

## Additional context
https://github.com/iNavFlight/inav/pull/9072

**Comment by b14ckyy** [comment]
Moving to Discussion as change request
