### ISSUE TITLE
Speedybee F405 Wing RSSI/Airspeed ADC assignment

### ISSUE THREAD

**Issue by GhostRyderFPV** [iNavFlight/inav#9084]
## Current Behavior
Hello Team! I use the Subject FC flashed with 6.1, with a FrSky L9R Rx bound to a Radiomaster Zorro 4in1 multiprotocol. Everything during initial setup went swimmingly, except analog RSSI reading in Setup tab and OSD. Both reported RSSI as 0 no matter what I tried; cycling the Analog RSSI option in Configuration tab, setting a random CH Number in Receiver tab and back to Disable, I could not get RSSI to work. But I swapped ADC assignments between RSSI and Airspeed, now I have perfect RSSI 

## Steps to Reproduce
1. Connect Analog RSSI pin on FC to Analog RSSI out on Frsky Rx
2. According to Speedybee, RSSI assignment is "RSSI_ANA_PIN 14, RSSI_TYPE 2" and Airspeed "ARSPD_ANA_PIN 15, ARSPD_TYPE 2"
3. Get ADC_channel revealed RSSI assigned to Ch 4, Airspeed Ch 3.
4. I set "set airspeed_adc_channel=4" and "set rssi_adc_channel = 3" and saved
5. I observe normal Analog RSSI behavior in Setup Tab and OSD

## Expected behavior
Normal RSSI behavior when 0-3.3V RSSI signal applied to RSSI pad on FC

## Suggested solution(s)
Future firmware swap RSSI and Airspeed ADC Channel assignments.

## Additional context
I cannot verify working (currently, are you reading this Matek?) Airspeed Sensor ADC CH assignment as I do not have the sensor type. Would be willing to test!

---

- FC Board name and vendor: SpeedyBee F405 Wing APP
- INAV version string: INAV/SPEEDYBEEF405WING 6.1.0 May 11 2023 / 14:03:50 (d6ce6e70) GCC-10.2.1 20201103 (release)

**Comment by b14ckyy** [comment]
Should be fixed with https://github.com/iNavFlight/inav/pull/9817 but expect it in 8.0
