### ISSUE TITLE
Increase navigation update rate for newer ublox GPS modules

### ISSUE THREAD

**Issue by mluessi** [iNavFlight/inav#9087]
## Current Behavior

When using a newer ublox GPS (e.g. M9, M10, F9P), the GPS update rate is configured to be only 5 Hz, while the hardware supports much higher rates. E.g. the F9P supports 18 Hz with 3 constellations, 25 Hz with two. Older ublox modules (M7, M8) use 10 Hz. 

## Steps to Reproduce
Connect ublox module, check rate 

## Expected behavior
The GPS navigation rate should be set higher if the hardware supports it.

## Suggested solution(s)
Set rate higher depending on ublox GPS being used

- FC Board name and vendor: NA
- INAV version string: NA

**Comment by mmosca** [comment]
#9103 will set m9/m10 to 10Hz if configured to use UBLOX7.

I may add a way to configure the update rate for future proofing and supporting higher rates.

Increasing update rates may also affect the number of satellites a module can track which is the reason behind m9+ currently being set to 5Hz.

**Comment by mmosca** [comment]
This will be available in 7.0

**Comment by cmanley** [comment]
Is there a way to configure this in ublox u-center 2? I tried setting it to 10hz for my HGLRC M100 MINI for use in INAV 6.1 but it INAV still connects at 5hz. My guess is that this GNSS unit doesn't have flash memory.

**Comment by mmosca** [comment]
You need inav 7, as inav 6 will auto configure it to 5Hz[]s,Marcelo Bezerra ***@***.***>On 30 Oct 2023, at 21:11, Craig Manley ***@***.***> wrote:﻿
Is there a way to configure this in ublox u-center 2? I tried setting it to 10hz for my HGLRC M100 MINI for use in INAV 6.1 but it INAV still connects at 5hz. My guess is that this GNSS unit doesn't have flash memory.

**Comment by cmanley** [comment]
Thank you, I understand now, and thanks for the MR too.
