### ISSUE TITLE
Minor issue: why is craft name forced to uppercase since v6.1.0?

### ISSUE THREAD

**Issue by cmanley** [iNavFlight/inav#9088]
## Current Behavior
Setting a mixed case craft name in v6.1.0, will result in the get returning the string in uppercase. I noticed it first in the file names after saving diffs.

## Steps to Reproduce

set name = Bonsai
save
get name
\# BONSAI

## Expected behavior
get name
\# Bonsai

## Suggested solution(s)
It worked with this firmware:
INAV/MATEKF411TE 6.0.0 Feb  9 2023 / 11:36:15 (92b237e5)
So something changed in between. I've been searching through the commits in the version compare but couldn't find where or why the new buglet/behaviour was introduced. It could be a configurator issue, but it's hard (for me) to tell where it's happening.

## Additional context
- FC Board name and vendor: all my boards, e.g. KF411 WTE, F405 WMN
- INAV version string: INAV/MATEKF411TE 6.1.0 May 11 2023 / 13:14:43 (d6ce6e70)

**Comment by cmanley** [comment]
Found the commit: 
https://github.com/iNavFlight/inav/commit/2cad65a860552673a0e70eddda2094b6f1fc1c5c
So it seams it was done because the OSD (which type?) doesn't support lowercase. 
But it affects the saved file name b.t.w. Wouldn't it be better to do the conversion when passing the string to the OSD.

**Comment by mmosca** [comment]
All types of OSD. INAV's font does not include lower case characters.

Yes, it probably would be nice to handle it in the cli.
