### ISSUE TITLE
BUG - Configurator save button causes RC link to drop indefinitely

### ISSUE THREAD

**Issue by malinhiles** [iNavFlight/inav#9118]
## Current Behavior
When my aircraft is plugged into inav configurator, pressing any "save" button permanently interrupts RC until aircraft reboot. When this happens the receiver still has power and still shows, by all metrics, that it has perfect connection to the RC transmitter. Using CRSF  and crossfire nano rx.

## Steps to Reproduce

1. Power up aircraft, establish connection with rc radio
2. Plug flight controller into a computer and open up inav configurator
3. Connect
4. Navigate to any tab with this save button in the bottom right corner
![image](https://github.com/iNavFlight/inav/assets/93371446/5e429a72-a307-4e3f-8e20-1784a2dbf7fd)

5. Press save
6. servos stop reacting to sticks, no receiver values shown on receiver tab. Receiver is still fully connected to rc transmitter and is receiving power
7. Reboot
8. Control is regained.

## Additional context
https://pastebin.com/y6P1aFfx

---
# version
# INAV/MATEKH743 6.0.0 Mar 22 2023 / 10:48:04 (084101ac)
# GCC-10.2.1 20201103 (release)

MATEK H743-WLITE

**Comment by MrD-RC** [comment]
This has been fixed in6.1
