### ISSUE TITLE
Manual Mode always on if any range is present...

### ISSUE THREAD

**Issue by chucky-whiskers** [iNavFlight/inav#9121]
**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior
![20230613_144801.jpg](https://github.com/iNavFlight/inav/assets/97908335/579daf8b-8888-47b6-9e86-1bcaaf9e35ac)

## Steps to Reproduce

1. Matek H743-WLITE
2. INAV 6.1.0
3. FBUS TD MX receiver (16 channel mode) on UART 6
4. If manual mode has any range, manual mode will be active regardless of switch position.

## Expected behavior
 Manual mode should only be active when the switch position is within the given range. 

## Additional context

---

- FC Board name and vendor: Matek H743-WLITE RDQ
- INAV version string: #INAV/MATEKH743 6.1.0 May 11 2023 / 13:29:16 (d6ce6e70)
#GCC-10.2.1 20201103 (release)

**Comment by MrD-RC** [comment]
Calibrate your accelerometer. 

https://youtu.be/TzExKM_GDA0
