### ISSUE TITLE
SpeedyBee F405 Quadrocopter Mixer Wizard for Motors no working

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#9146]
INAV 6.1.0
SpeedyBee F405 Firmware Jun 13 2023
SB43 Version 0

The Quadrocopter Mixer Wizard for Motors is not working correctly
Its not possible to rearrange the motor position like it should be

**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
Mixer wizard modifies mixer, not motor order. It's working fine, but it changes something else than you expect
