### ISSUE TITLE
 msc mode does not work again

### ISSUE THREAD

**Issue by lida2003** [iNavFlight/inav#9160]
## Current Behavior
It seems msc issue is back, see https://github.com/iNavFlight/inav/issues/5860

6.1.1FW + inav configurator 6.1.0 + AOCODARCH7DUAL （Onboard Flash）  ==》 USB drive can't be opend, no BB log, but it can save log as TXT file.

## Steps to Reproduce
1. Fly with blackbox enabled
2. blackbox tab, [save flash to file...] button works well, there is a txt log file
3. cli tab, [MSC] button works, but only usb drive "INAV_FC" appears, it can't be opened.

So we can't get BB log files.

## Expected behavior
Open USB drive, and copy BB log files to the computer as it was.

## Additional context

Only below U driver appears, it can't be opened.

![图片](https://github.com/iNavFlight/inav/assets/1296171/4abd84ec-495b-427b-863c-85038252b68a)

- FC Board name and vendor:  AOCODARCH7DUAL （Onboard Flash）
- INAV version string: 6.1.1 [AOCODARCH7DUAL]
- STM32 H743

**Comment by carlybaby69** [comment]
Same issue on a Matek 765 Wing. Same SD card and same laptop with a Matek F405 Matek Wing msc command works fine.

**Comment by DzikuVx** [comment]
Tested on INAV7 and H7 
![image](https://github.com/iNavFlight/inav/assets/966811/28446c8c-b31c-4d87-af0c-35ac6aed3197)
 and everthing seems to be working. Slow and you have to wait circa 1m for files to appear, but works
