### ISSUE TITLE
SpeedyBee F405 INAV 6.1.1 and Matek LIDAR causes landing of copter

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#9164]
SpeedyBee F405 with INAV 6.1.1. and Matek LIDAR causes landing of the copter

After switching SURFACE Mode togehter with ANGLE Mode and NAV ALTHOLD causes immidiate landing of the copter.
Copter then restarts and lands again and so on

Could be reproduced all time with SURFACE Mode

LIDAR was installed and calibrated like discribed in MATEK instruction
Also with modification of the mentioned parameters

**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment]
This lidar has extrenely short range. 1m is doable indoors. Outdoor only when it's relatively dark. This is intended to happen and depends on light level and surface type
