### ISSUE TITLE
Remaining Flight Distance values missing in OSD

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#9182]
## Current Behavior
OSD shows no values for the remaining flight distance. No dashes or any character at all. 

## Steps to Reproduce
1. Set up necessary values for remaining flight time and distance
2. Enable both items in OSD
3. Fly the plane
4. Remaining flight time values are shown but for distance there is no value, just the icon. 

## Expected behavior
Remaining Flight distance shown in OSD

## Suggested solution(s)
none

## Additional context
- Fonts loaded but no change (Impact in my case)
- Pixel and Character OSD as well as MSP-DP affected
- need to check previous versions of INAV

some screenshots: 
![image](https://github.com/iNavFlight/inav/assets/33039058/a541f8d7-4aa5-452b-bafa-bd28a50992e5)
![WhatsApp Bild 2023-07-20 um 11 47 11](https://github.com/iNavFlight/inav/assets/33039058/12f73b38-e45e-4a64-a6bd-4b437b78007b)
![image](https://github.com/iNavFlight/inav/assets/33039058/0d3e7c8d-cc88-49fe-a6ab-302e69c35714)

---

- FC Board name and vendor: Matek F722-WPX, Matek F411-WSE, Matek F405-WSE
- INAV version string: INAV 6.1.1 Release

**Comment by JulioCesarMatias** [comment]
A check logic was broken after this commit:
https://github.com/iNavFlight/inav/commit/e0840a4ae6e7784ec46ccff8c61e47b1576dce90#diff-da6a9ff6562212212bb06f79de4b84480c7c52e772d3708498a21a640d8fd7aaR213

See this OSD line:
https://github.com/iNavFlight/inav/blob/366db3a347a3c0c965d505519093f2f848178396/src/main/io/osd.c#L2125


The verification logic of "ARMING_FLAG(ARMED)" in True and False state are checked at the same time in:

`if ((!ARMING_FLAG(ARMED)) || (distanceMeters == -1)) {
            buff[4] = SYM_BLANK;
            buff[5] = '\0';
            strcpy(buff + 1, "---");`

**Comment by MrD-RC** [comment]
@breadoven Would this line not need to be `!ARMING_FLAG(ARMED)`.  Surely if should be calculating the wind if armed, not disarmed?

https://github.com/iNavFlight/inav/blob/e0840a4ae6e7784ec46ccff8c61e47b1576dce90/src/main/flight/rth_estimator.c#L213

**Comment by breadoven** [comment]
> @breadoven Would this line not need to be `!ARMING_FLAG(ARMED)`. Surely it should be calculating if armed, not disarmed?
> 
> https://github.com/iNavFlight/inav/blob/e0840a4ae6e7784ec46ccff8c61e47b1576dce90/src/main/flight/rth_estimator.c#L213

The ! is for both` (FIXED_WING_LEGACY || ARMED)`, i.e. if not a plane and not armed then return. So if you're armed and a plane it shouldn't return so should work as required when armed (but not when disarmed). Having said that it's not right. If it was a multirotor for instance it wouldn't return as it should when armed. It should have been a `&&` rather than a `||`. Negated `||`'s seem a bit confusing for some reason.

**Comment by JulioCesarMatias** [comment]
I think the style of development should change in relation to this... The use of '!((condition) or (condition))' could no longer be accepted, and should it always be revised by the merger to only accept the type: '((!condition) or (!condition))'

**Comment by breadoven** [comment]
Is anyone working on a fix for this or is something else being worked on to get around the general issue of `char `being limited to a byte causing problems for higher value symbols ?

**Comment by MrD-RC** [comment]
@breadoven I have a working fix. Just need to submit the PR.
