### ISSUE TITLE
Can add ICM-42688-P to FURYF4OSD(MAMBA F405 MK2 V2)

### ISSUE THREAD

**Issue by SanKin42** [iNavFlight/inav#9192]
I am using MAMBA F405 MK2 V2,GYRO is ICM-42688-P, inav, version 6.1.1

I've tried all the gyroscopes that can be selected in the Configurator TAB (even the fake ones), but they don't work.

Can anyone help me?

**Comment by b14ckyy** [comment]
ICM42688-P uses the same driver as the 42605. Just set it to auto and save and reboot, it should select the correct one automatically. If not, the target is probably the wrong one. Diatone only refers to Betaflight. The target could be non working on INAV
