### ISSUE TITLE
Improve scheduler with a possibility to yield a long-running task

### ISSUE THREAD

**Issue by night-ghost** [iNavFlight/inav#921]
and not task switch to scheduler? I don't know how it here but profiling of Arducopter shows 67% of CPU time just in delay()

**Comment by digitalentity** [comment]
Because scheduler is cooperative, not preemptive. There is no such thing as task switch.

**Comment by night-ghost** [comment]
What a speed of closing! :) JFYI, even cooperative scheduler CAN switch tasks  -  https://github.com/night-ghost/ardupilot/blob/master/libraries/AP_HAL_REVOMINI/Scheduler.cpp#L562

**Comment by digitalentity** [comment]
This is not an APM, our scheduler assumes task is never interrupted. 
However having a `yield()` for long running tasks might be a good thing. Re-opening :)

**Comment by night-ghost** [comment]
that code ALSO is not a APM because it is just mine hack, APM has the same problem. See: task calls delay() so scheduler knows than this time is free for another tasks. All that it need is a maximal time in the task before next yield() in tasks to not miss time

**Comment by night-ghost** [comment]
so all low-priority tasks such as telemetry, LEDS and so on can be scheduled in free time

**Comment by digitalentity** [comment]
That's already happening with current code - low priority tasks are scheduled only if enough free time is available.

**Comment by night-ghost** [comment]
how much % of time spent in delay() ?

**Comment by digitalentity** [comment]
delay is almost never used in run-time code, only in initialisation code.

**Comment by night-ghost** [comment]
Well then here is much better than in the APM

**Comment by digitalentity** [comment]
Usually tasks here are designed in such a way that they don't have to wait or keep their own time-driven scheduling for slow events.
