### ISSUE TITLE
Rangefinder Sensor (VL53L1X) not working an Speedybee F7V3, II

### ISSUE THREAD

**Issue by maxledfreak** [iNavFlight/inav#9211]
Revering to this closed bug, because it is not fixed but closed: 
https://github.com/iNavFlight/inav/issues/9188 
@druckgott

**Comment by mmosca** [comment]
How did you test it?

**Comment by druckgott** [comment]
Fixed and tested
https://github.com/iNavFlight/inav/commit/b686ee96e10c5d4cd3a433d08b568ff41bfe2636

**Comment by mmosca** [comment]
most likely resolved by #9221
