### ISSUE TITLE
acoda-Rc f4 v2 no accelerometer dected

### ISSUE THREAD

**Issue by naseraliomran** [iNavFlight/inav#9217]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior

the acc and the gyr is not detected  ihave MPU 6500 it says in the cli unavailable i tried all the f4 target and its the same

thanks for helping me 

## Expected behavior

- FC Board name and vendor: Acoda f4 v1.0
- INAV version string :INAV 6.1.1

**Comment by snaewe** [comment]
I have the same problem. @naseraliomran Does your FC look like this:

![20230912_213013](https://github.com/iNavFlight/inav/assets/4468/2c8c5f1f-9aa8-4e38-8a01-d60e2984bd62)

i.e. does your version have the MPU6000 IMU ?

**Comment by snaewe** [comment]
@sensei-hacker 

![20230913_072551.jpg](https://github.com/iNavFlight/inav/assets/4468/2beb21e5-a583-4b4d-81c9-300e60e9cfe1)

**Comment by sensei-hacker** [comment]
Thanks. I was curious because you had referenced the V1 issue and wrote your board model as "FC Board name and vendor: Acoda f4 v1.0", but changed the V2 target. I see your board is marked V2.

**Comment by sensei-hacker** [comment]
@naseraliomran  Sorry I didn't see this issue before. Can you please confirm whether your board silkscreen says V1, V1.1, or V2?

I believe I tested the target on a V1.1.
