### ISSUE TITLE
Request for new INav Target: TMOTORF7

### ISSUE THREAD

**Issue by samuraitheta** [iNavFlight/inav#9236]
## Current Behavior
I have a quad with a TMotor F722 (V1.0). The Betaflight Target is TMOTORF7. I tried the TMOTORF7V2 target and two of the motors don’t spin. 

## Desired Behavior
I would love a target for this FC so I can put a compass and GPS on this quad.

**Comment by MrD-RC** [comment]
New targets require the following of the hardware policy https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

You would need to contact TMotor and let them know that you would like a target. They may not be interested as it is a older board, and the later version already has a target.
