### ISSUE TITLE
Aocoda-rc H7 9volts is not working. 

### ISSUE THREAD

**Issue by capblack** [iNavFlight/inav#9238]
Hi Aocoda-rc H7 9 volts for dji ait unit not working , I tink there will be one enable, because with betafligth it is working

**Comment by capblack** [comment]
sorry INAV 6.1.1

**Comment by capblack** [comment]
Can this be fixed in the current version or in the future one? thank you

**Comment by mmosca** [comment]
Some fc have a feature to turn on/off the power to the vtx.

Try checking if you have USER1/USER2 modes and play with activating/deactivating those modes.

**Comment by capblack** [comment]
ok right activating user1 on modes , solve the problem.
thank you
