### ISSUE TITLE
Wrong Altitude Position 

### ISSUE THREAD

**Issue by fabianorigobello** [iNavFlight/inav#9248]
Hello, I installed SpeedyBee F405 WING FC board with INAV 6.0 on my plane but the Altitude showed me incorrect position. 1300 meter instead of 0 meter (or close to that) Can you guys help me, please? 

![Capture](https://github.com/iNavFlight/inav/assets/142517544/e3a356ff-271a-4a1e-9f94-2609fcb39e48)
![image(1)](https://github.com/iNavFlight/inav/assets/142517544/9650ce81-24ed-403d-80e0-5ebedea1169a)

diff

# version
# INAV/SPEEDYBEEF405WING 6.0.0 Mar  2 2023 / 10:57:01 (33223a65)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# resources

# Mixer: motor mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.300
mmix 1  1.000  0.000  0.000 -0.300

# Mixer: servo mixer
smix reset

smix 0 1 0 -100 0 -1
smix 1 2 0 -100 0 -1
smix 2 3 1 50 0 -1
smix 3 3 2 -50 0 -1
smix 4 4 1 -50 0 -1
smix 5 4 2 -50 0 -1

# Outputs [servo]

# safehome

# features
feature -BLACKBOX
feature -AIRMODE
feature MOTOR_STOP
feature GPS
feature DASHBOARD
feature PWM_OUTPUT_ENABLE

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS
blackbox -GYRO_RAW
blackbox -PEAKS_R
blackbox -PEAKS_P
blackbox -PEAKS_Y

# Receiver: Channel map

# Ports
serial 2 2 115200 57600 0 115200
serial 4 2097152 115200 115200 0 115200
serial 5 0 115200 115200 0 115200

# LEDs

# LED color

# LED mode_color

# Modes [aux]
aux 0 0 0 1300 2100
aux 1 1 2 900 1300
aux 2 2 2 1300 1700
aux 3 12 2 1800 2100
aux 4 10 1 1475 2100

# Adjustments [adjrange]

# Receiver rxrange

# temp_sensor

# Mission Control Waypoints [wp]
#wp 0 invalid

# OSD [osd_layout]
osd_layout 0 1 22 1 V
osd_layout 0 2 0 0 V
osd_layout 0 3 8 6 V
osd_layout 0 7 10 6 V
osd_layout 0 9 21 3 V
osd_layout 0 11 2 3 H
osd_layout 0 12 1 4 H
osd_layout 0 14 2 2 V
osd_layout 0 15 1 1 V
osd_layout 0 22 13 5 V
osd_layout 0 23 11 4 V
osd_layout 0 28 13 10 V
osd_layout 0 30 1 9 V
osd_layout 0 32 22 2 V
osd_layout 0 97 8 0 V
osd_layout 0 99 25 5 V

# Programming: logic

# Programming: global variables

# Programming: PID controllers

# master
set gyro_main_lpf_hz = 25
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 30
set gyro_zero_x = 4
set gyro_zero_y = -10
set gyro_zero_z = 5
set ins_gravity_cmss =  982.112
set acc_hardware = ICM42605
set acczero_x = 1
set acczero_y = -6
set acczero_z = 18
set accgain_x = 4074
set accgain_y = 4102
set accgain_z = 4103
set align_mag = CW270FLIP
set mag_hardware = NONE
set baro_hardware = SPL06
set rssi_channel = 8
set motor_pwm_protocol = DSHOT300
set failsafe_procedure = RTH
set platform_type = AIRPLANE
set has_flaps = ON
set model_preview_type = 34
set small_angle = 180
set ahrs_inertia_comp_method = ADAPTIVE
set applied_defaults = 3
set gps_sbas_mode = AUTO
set airmode_type = STICK_CENTER_ONCE
set inav_w_z_baro_p =  0.000
set nav_wp_radius = 5000
set nav_wp_max_safe_distance = 500
set nav_rth_allow_landing = FS_ONLY
set nav_rth_altitude = 5000
set nav_fw_control_smoothness = 2
set nav_fw_launch_motor_delay = 100
set nav_fw_launch_max_altitude = 5000
set nav_fw_launch_climb_angle = 25
set tz_automatic_dst = USA
set vtx_band = 5
set vtx_channel = 5
set vtx_power = 5
set vtx_low_power_disarm = UNTIL_FIRST_ARM
set dji_use_adjustments = ON

# profile
profile 1

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 80
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_p_yaw = 50
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 18
set pitch_rate = 9
set yaw_rate = 3

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# save configuration
save

# end the command batch
batch end

# 

**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by SRIPARTH007** [comment]
I guess its the MSL (mean sea level) thats the altitude of your plane from the sea level not from the ground if you want to find the altitude from ground calibrate the barometer placing on the floor there is no problem with that GPS
