### ISSUE TITLE
ws-m181 gps is detected properly but cannot get a fix

### ISSUE THREAD

**Issue by sgrizzi** [iNavFlight/inav#9257]
I am using a ws-m181 gps connected to a CrazyF405 FC, running INAV 6.1 firmware. The FC is powered with a 1s battery.
All sensors are detected correctly, including the GPS (icons are all blue).
GPS is on uart1 @115200 baud. Protocol UBLOX7 (I also tried UBLOX with no changes). Galileo satellites also active.
Update time: ca. 10Hz. "Total messages" count up steadily.

With this configuration I get a fix randomly, very seldom...
When I use gpspassthough in CLI I can see only garbled text... rarely do I see output strings in clear.
Connections are correct -and sometimes the gps does work...
The board is powered with a LiPo @3.9V.

Has anybody any hint for me on how to fix this problem? is there a way (e.g. a CLI command) to force a restart/re-initialization of uart1?
Thanks in advance.

**Comment by capblack** [comment]
hello the voltage is not enough for the correct operation of the gps, it needs 5v minimum 4.5v but not recommended

**Comment by sgrizzi** [comment]
That was my fear... but an onboard buck-boost is generating 5V directly from the LiPo.
I measure ca.4.5V when the FC is just supplied via the usb cable, and 4.957V when the LiPo is connected.
The buck-boost takes a bit of time to get to the nominal output voltage, maybe the GPS is initialized before the nominal voltage has been reached.
That was also the reason of my question on whether it is possible to manually re-initialize the GPS.
Unfortunately there is no "auto" selection available for the GPS interface speed.
