### ISSUE TITLE
FOXEER v4  mpu6000.  dji o3  not have  OSD

### ISSUE THREAD

**Issue by y957128156** [iNavFlight/inav#9290]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by y957128156** [comment]
Open the DJIFPV VTX port to display the aircraft battery level. Opening the MSP Displayport does not display the aircraft battery level. The receiving device is the latest firmware of DJI goggles2

**Comment by y957128156** [comment]
![1694424924189](https://github.com/iNavFlight/inav/assets/108682047/7f9f03f9-7d62-4367-8626-1c24b665e7c3)

**Comment by mmosca** [comment]
Can you post a diff all and a screenshot of your ports tab?

**Comment by y957128156** [comment]
[inav6.1.1.txt](https://github.com/iNavFlight/inav/files/12581547/inav6.1.1.txt)
[BF4.42.txt](https://github.com/iNavFlight/inav/files/12581548/BF4.42.txt)

**Comment by y957128156** [comment]
This is the file of the same flight controller, it works fine in bf

**Comment by y957128156** [comment]
> 您可以发布所有差异和端口选项卡的屏幕截图吗？

![微信图片_20230912102210](https://github.com/iNavFlight/inav/assets/108682047/c6784b2d-1c4e-4473-9dfc-fc7dadc5065d)
