### ISSUE TITLE
iNav 6.1 fixed wing cruise navPos[2] jumps

### ISSUE THREAD

**Issue by helicocrasher** [iNavFlight/inav#9311]
## Current Behavior
I have observed two strange things with iNav 6.1 on two of my flying wings. 

1. At some occasions in cruise mode the vario is showning constant sink of ~1m/s (wrongly) and the height is staying constant (as expected).
2. Somtimes in cruisemode the OSD shows a very brief jump in height +10 or 20 meters. The NavPos{2} in blackbox is also showing these jumps.  Baro and GPs height do not have this jumps 
As a consequnce the plane is immedately throttling down to correct for the perceived height error. 

## Steps to Reproduce

I have recently pulled 11 blackbox logs from one of my wings. 9 logs do not show this behavior, 2 logs show it. 
I do not recall to have made changes to the settings of that plane. 
So I have no idea how to reproduce or provoke the behavior.

## Expected behavior

1.  Some fluctuation of the Vario OSD readings is ok in cruise but a permanent offset when keeping the height is not Ok.
2.  No height jumps that disturbe the cruise. 

## Additional context

---

https://pastebin.com/z1WiXAE0

- FC Board name and vendor:
- INAV version string:
 version
 INAV/MATEKF405TE 6.1.0 May 11 2023 / 13:05:49 (d6ce6e70)
 GCC-10.2.1 20201103 (release)

![grafik](https://github.com/iNavFlight/inav/assets/23324242/40c89088-f5e5-4071-b1ed-31cd2b87aa2f)

![grafik](https://github.com/iNavFlight/inav/assets/23324242/fbe106b3-a56b-40c9-ab89-7fa19e048c8b)

other example other plane 

![grafik](https://github.com/iNavFlight/inav/assets/23324242/7e1edff6-fce1-437a-be88-341d1b771b59)

https://www.dropbox.com/scl/fi/30ggfsc8ku6nsjt47tjvu/blackbox_log_2023-09-16_134612.TXT?rlkey=1dbzjd9tfkw272ank2immbtea&dl=0

**Comment by breadoven** [comment]
It would be useful if you could provide the full log file.

**Comment by Feldsalat** [comment]
I have jumps like that too. Not always and on different planes. Just like here:
[https://youtu.be/Oqidg0h63Gc](url)
I don't have any logs.

**Comment by breadoven** [comment]
Something doesn't look right there with the vertical velocity. It's constantly negative over a circa 30s period but vertical position remains roughly constant as does the Baro altitude. Almost looks like some sort of error correction kicks in bumping up the vertical position by the height that would have been lost of the vertical velocity was correct. Accelerations don't look excessive so not obvious what's causing it unless it's a GPS issue. Check the GPS heights.

**Comment by helicocrasher** [comment]
@breadoven thanks 
Yes vertical velocity is weird. 
I have put the OSD video here https://youtu.be/iYJT-RL6dj0
The sequence with the 4 bumps in the middle of the graph.
Then below a new graph with the GPS height added. 
Someway the GPS height looks like scaled up ... 

![grafik](https://github.com/iNavFlight/inav/assets/23324242/13f4a551-5e8f-443a-8c94-60f824b7f33d)

**Comment by helicocrasher** [comment]
More Flight height graphs 

![grafik](https://github.com/iNavFlight/inav/assets/23324242/a84db0fc-3a9f-4366-bfd9-a663a9f4f042)

![grafik](https://github.com/iNavFlight/inav/assets/23324242/e1a5f1f6-6715-4937-896a-e858d6c90a6b)

**Comment by b14ckyy** [comment]
This was fixed in 6.1.1 and was the main reason for that patch. See https://github.com/iNavFlight/inav/pull/9111

**Comment by helicocrasher** [comment]
More Flight height graphs 

![grafik](https://github.com/iNavFlight/inav/assets/23324242/a84db0fc-3a9f-4366-bfd9-a663a9f4f042)

**Comment by helicocrasher** [comment]
> This was fixed in 6.1.1 and was the main reason for that patch. See #9111

Uh so simple! I missed that release.
@b14ckyy  Thanks
I will upgrade my planes now.
