### ISSUE TITLE
Confusing what flight controllers are actually supported regarding drones/quadcopters

### ISSUE THREAD

**Issue by kelvincdeen** [iNavFlight/inav#9316]
## Supported FC for drones

I have found the boards list of what flight controllers are supported but it gives mixed signals. 
- for a Matek F411 FC there is shown a completely different FC than I am looking at.
- said to support most F4/F7 FC but very vague what actually is supported.
## Making it easier to comprehend what is supported for drones

Maybe I am still too new and just impotent regarding this firmware, but no matter how much I google I can't find any website for simple how-to. (as far as 'simple' can qualify for firm/software like INAV)
- a simple general tutorial to see if a certain F4 or F7 flight controller (for e.g. drones) can be compatible with INAV.
- this tutorial being a simple overview on what pins you need to make INAV work for (fpv)drones.
- how to move pins around in software if you have access to the FC schematic to make INAV work. 
## Suggested Solution

- Straight forward document or tutorial to identify if a board is actually compatible. 
- Maybe identify what makes a supported Betaflight FC also support INAV?
## Who does this impact? Who is this for?

Everyone that flies FPV drones to make a migration, or just pure curiosity for what INAV is all about. Made easy.
- intermediate know how 
## Additional context with example

A simple example: 
The baby ape pro v2 has a STM32f411 FC MCU, it has the target MATEK F411 (it is noted by DarwinFPV that it's the target for Betaflight, to be fair). If I look at the supported boards list on it has the MATEK F411, and it does have this target in the INAV configurator, but it show a completely other FC when I click on full specifications than the baby ape pro v2 has. This is really confusing. Maybe it is because INAV is more limited regarding flashable FC's than Betaflight or me wanting something to be possible when it's not.

PS. I am not sure if this post is relevant here, but I will give it a shot since most whom will deal with this same issue I am dealing with right now will be looking at the INAV GitHub and wiki. 

Hence I am placing this here. Otherwise I apologize.

**Comment by MrD-RC** [comment]
[This article](https://github.com/iNavFlight/inav/wiki/Supported-boards) and the Wiki article in the **Boards documentation** section cover which MCUs and specifically which targets are available. https://github.com/iNavFlight/inav/wiki/Boards,-Targets-and-PWM-allocations Specifically covers the Signal outputs. Having 4 motors available is all that’s really required for it to be a “quad” flight controller. 

BetaFlight targets, even the names, are not the same as INAV targets. Check the manufacturer’s web site for the INAV target name.
