### ISSUE TITLE
SUMD not workding /  selectable

### ISSUE THREAD

**Issue by DietmarM** [iNavFlight/inav#9317]
Running # INAV/MATEKF722MINI 6.1.1 Jun 13 2023 / 11:47:50 (42ced253)
CONFIGURATOR6.1.0

Serial receiver is connected on R2 - worked in INAV 2.5.2

When selecting serial and SUMD - > save and reboot -> no receiver selected

Also manual change in CLI to SUMD does not help - no receiver signals are shown in configurator and does not work

do I do something wrong in 6.11 or is there a bug?

diff

# version
# INAV/MATEKF722MINI 6.1.1 Jun 13 2023 / 11:47:50 (42ced253)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# resources

# Mixer: motor mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000

# Mixer: servo mixer
smix reset

smix 0 1 1 100 0 -1
smix 1 2 0 100 0 -1
smix 2 3 0 100 0 -1
smix 3 4 2 100 0 -1
smix 4 5 8 100 0 -1
smix 5 6 8 100 0 -1

# Outputs [servo]

# safehome

# features
feature -TX_PROF_SEL
feature -TELEMETRY
feature -CURRENT_METER
feature -OSD
feature MOTOR_STOP
feature LED_STRIP
feature PWM_OUTPUT_ENABLE

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS
blackbox -GYRO_RAW
blackbox -PEAKS_R
blackbox -PEAKS_P
blackbox -PEAKS_Y

# Receiver: Channel map
map TAER

# Ports

# LEDs

# LED color

# LED mode_color

# Modes [aux]

# Adjustments [adjrange]

# Receiver rxrange

# temp_sensor

# Mission Control Waypoints [wp]
#wp 0 invalid

# OSD [osd_layout]

# Programming: logic

# Programming: global variables

# Programming: PID controllers

# master
set gyro_main_lpf_hz = 25
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 30
set gyro_zero_x = -63
set gyro_zero_y = 25
set gyro_zero_z = -15
set ins_gravity_cmss =  978.577
set acc_hardware = MPU6000
set acczero_x = 64
set acczero_y = -20
set acczero_z = -7
set accgain_x = 4077
set accgain_y = 4106
set accgain_z = 4011
set align_mag = CW270FLIP
set mag_hardware = NONE
set baro_hardware = NONE
set receiver_type = NONE
set rc_filter_auto = OFF
set serialrx_provider = SUMD
set serialrx_halfduplex = OFF
set motor_pwm_protocol = STANDARD
set align_board_yaw = 900
set platform_type = AIRPLANE
set has_flaps = ON
set model_preview_type = 14
set output_mode = MOTORS
set small_angle = 180
set ahrs_inertia_comp_method = ADAPTIVE
set applied_defaults = 3
set airmode_type = STICK_CENTER_ONCE
set nav_wp_radius = 5000
set nav_wp_max_safe_distance = 500
set nav_rth_allow_landing = FS_ONLY
set nav_rth_altitude = 5000
set nav_fw_control_smoothness = 2
set nav_fw_launch_motor_delay = 100
set nav_fw_launch_max_altitude = 5000
set nav_fw_launch_climb_angle = 25

# profile
profile 1

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 80
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_p_yaw = 50
set fw_i_yaw = 0
set fw_d_yaw = 20
set fw_ff_yaw = 255
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.400
set nav_fw_pos_z_p = 25
set nav_fw_pos_z_d = 8
set nav_fw_pos_xy_p = 55
set d_boost_min =  1.000
set d_boost_max =  1.000
set rc_expo = 30
set rc_yaw_expo = 30
set roll_rate = 18
set pitch_rate = 9
set yaw_rate = 3

# battery_profile
battery_profile 1

set throttle_idle =  5.000

# save configuration
save

# end the command batch
batch end

**Comment by stronnag** [comment]
SUMD was intentionally removed some time ago as obsolete / unused.
