### ISSUE TITLE
reactivate SUMD for F7 and if possible also for F4

### ISSUE THREAD

**Issue by DietmarM** [iNavFlight/inav#9319]

**Comment by MrD-RC** [comment]
As stated in https://github.com/iNavFlight/inav/issues/9317#issuecomment-1737225011 SUMD was removed intentionally and will not be re-added. If I remember correctly, all SUMD systems can be upgraded to a different protocol that is supported.

**Comment by DietmarM** [comment]
> If I remember correctly, all SUMD systems can be upgraded to a different protocol that is supported.

This is unfortunately not valid for all receivers. Is there any way to get it working for GR 12SH e.g.?
