### ISSUE TITLE
inav 1.4  Y6 Mixer 

### ISSUE THREAD

**Issue by wolflonezx11** [iNavFlight/inav#932]
HI 

inav 1.4  Y6 Mixer .. NO
I do not have a choice
Let me know
Y6 I want to make a copter.
Please.

**Comment by digitalentity** [comment]
What board? Exotic mixers are not available on F1 boards like CC3D & NAZE. 
You can always make a custom mix https://github.com/iNavFlight/inav/wiki/Custom-mixes-for-exotic-setups#hexa-y6

**Comment by wolflonezx11** [comment]
NAZE32 F1  Board 
Please.

**Comment by digitalentity** [comment]
Use custom mix from the link provided above

**Comment by wolflonezx11** [comment]
Thank you


2016-12-15 14:55 GMT+09:00 Konstantin Sharlaimov <notifications@github.com>:
