### ISSUE TITLE
[6.1.1] fixed wing, iterm to zero on fast rolls?

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav#9328]
## Current Behavior
On "fast" rolls the bounce on center stick (when you stop the roll) is large and easily seen with FPV flights.
`set fw_iterm_limit_stick_position =  0.125` is already in place and limits the I term during a roll.
_(Unfortunately that does not help much, because I term unwinds anyway when the limit stick position ends.)_

When doing the same roll in manual mode, there is very little bounce to be seen when you stop the roll. 
The Blackbox log shows why, **iterm is zero when in manual mode**.

![Screenshot 2023-09-30 200203](https://github.com/iNavFlight/inav/assets/31951195/dfde823a-2475-4b81-a016-97ae059e181e)

![Screenshot 2023-09-30 200245](https://github.com/iNavFlight/inav/assets/31951195/2e68d506-d6d6-4372-b45f-8c790dc5ff92)

## Expected behavior
No bounce when you stop a roll in ACRO mode.

## Suggested solution(s)
In ACRO, create a setting that can set iterm to zero during fast moves.

- version
- INAV/MATEKH743 6.1.1 Jun 13 2023 / 11:52:23 (42ced253)
- GCC-10.2.1 20201103 (release)

**Comment by Jetrell** [comment]
@0crap This has certainly been an issue for a while.
The problem with `fw_iterm_limit_stick_position`. Is that it only prevents the i-term from growing.. It doesn't reset it back to zero. Which still leaves some accumulated i-term, that has to unwind at center stick.
I think it would be better if it cleared the i-term error, when the stick released speed (back to center), exceeds the PID loop time when it sees the i-term shrinking.

**Comment by 0crap** [comment]
Indeed an issue for quite a while.
And frustrating everytime when you try to tune a new airplane.
I sure hope the time is right to fix this one.
(After the AHI fix this is now my number one issue to make INAV perfect for planks.)

A proper fixed wing iterm relax on roll should fix this.
Pitch is not an issue because a looping is a relatively slow move.
Roll stops however is an pain in the butt...

**Comment by 0crap** [comment]
[Housekeeping] This one should finally be closed by https://github.com/iNavFlight/inav/pull/9905
Which we will test upcoming flying season.
