### ISSUE TITLE
I2C1 not working on AT32F43X target 

### ISSUE THREAD

**Issue by ujara** [iNavFlight/inav#9357]
## Current Behavior
i2C device non operative on i2C1 port of AT32F43x target using inav 6.1.1

## Steps to Reproduce

1. Add i2c device to i2C1 bus on any AT32F43x target running inav 6.1.1 like BMP280 barometer in i2C mode

## Expected behavior
i2C device shows up in inav 6.1.x configurator after addition 

## Suggested solution(s)
Observed in "drivers/bus_i2c_at32f43x.c" in i2C hardware map, i2C1 is GPIO_MUX_8 when it should be GPIO_MUX_4. The datasheet from Artery Semi. says its MUX4.  Changing to MUX4 does allow i2C device added on i2C1 to show up and behave correctly on i2C1 for AT32F435x target 

- FC Board name and vendor: Custom board 
- INAV version string:  6.1.1

**Comment by DzikuVx** [comment]
#9412
