### ISSUE TITLE
Aileron differencal and elevator/Aileron rate split

### ISSUE THREAD

**Issue by druckgott** [iNavFlight/inav#9359]
## Current Behavior
There is vcurrently now way to habe a aileron differencation so that up is more then down. 
There is now way to have Differential expro between aileron and elevator

## Desired Behavior
Add the way that we can have aileron differencation so that down aileron is less then up. Aileron
Habe 2 fields for expro elevator and aileron

## Suggested Solution
Add the way that we can have aileron differencation so that down aileron is less then up. Aileron
Habe 2 fields for expro elevator and aileron

## Who does this impact? Who is this for?
Vetter behavior for pilot in flying the plane because you can reach the configuration you should have to get a good flying plane

**Comment by MrD-RC** [comment]
You can already set up differential in INAV.

https://youtu.be/YLxkRg671J8?si=WKo9R6gDQMVx8PQp
