### ISSUE TITLE
Mamba H743 V2 with ICM-42688 P Dual Gyro

### ISSUE THREAD

**Issue by marcdornan** [iNavFlight/inav#9367]
I have flashed this with iNav 6.1 Mamba H743 2022B and I notice that this gyro is not available in the drop downs in the configurator. It is responding to movement when I use ICM 42605. Is it safe or wise to use this? I assumed that ICM 42688 has been around for a while now so I assumed it would be supported in iNav -- or are the gyro options specified for each target? Can we get this added to Mamba Mk4 H743 V2?

**Comment by FedorVG** [comment]
Same problem with Mamba MK4 F722 APP ICM42688P (MAMBA F722 2022B target)
Is it possible to add

**Comment by DzikuVx** [comment]
ICM426xx driver is enabled on `MAMBAH743_2022B` as well on `MAMBAF722_2022B`
