### ISSUE TITLE
ESC output Standard 50 Hz framrate

### ISSUE THREAD

**Issue by wolfffgang** [iNavFlight/inav#9368]
- FC Board name and vendor: Speedybee F405 wing
- INAV version string: 2023-10-13 @ 12:51:13 -- Running - OS: Windows, Chrome: 98.0.4758.82, Configurator: 6.1.0
- 
 Output setup for Standard ESC produces a frame rate of 400 Hz.
In the wing applications the framerate of 90% populat ESC use as Standard 50 Hz framerate.
I tested with Speedybee F405 wing standard esc from robbe

**Comment by DzikuVx** [comment]
All modern ESC support this PWM rate. And by modern I mean even 8 years old

**Comment by dakopian** [comment]
I have the same problem with my Mini Apprentice S. It doesn't work with a 400Hz refresh rate. Please add an option to slow that down.

**Comment by sensei-hacker** [comment]
> I have the same problem with my Mini Apprentice S. It doesn't work with a 400Hz refresh rate. Please add an option to slow that down.

If you have one that's actually incapable of 400 Hz, you can instead connect it as "servo".  In the mixer, just set that "servo" as stabilized throttle.  This is how we always did it before quads ("drones") were around, needing much higher speed ESCs.

When doing that, be sure to also always remember the old rule - any time the battery is attached, the prop can spin - so prop removed when you're working on the plane indoors!

**Comment by dakopian** [comment]
Thanks! Actually, I already replaced the ESC with a BLHeli_S-based one. Given their affordability, there was no sense in messing with that old ESC. Everything works perfectly now.
