### ISSUE TITLE
ADC Channels 5 and 6

### ISSUE THREAD

**Issue by dcan999** [iNavFlight/inav#9373]
## Current Behavior
Channels 5 and 6 are not available to define

## Desired Behavior
Allow users to redefine ADC 5 and 6 to VB2 and CU2 pins to have INAV use that voltage and current for OSD and calculations. 

Are these channels defined in INAV at all? Matek shows them on their INAV mapping, but when I connect battery voltage to VB2 I get no voltage reading, even when I tried to redefine the VB2 pin to ADC CH1. I want to use the VB2 and CU2 pads on my H743-Wlite to connect an external voltage/current sensor and have INAV use those values for current limiting and in the OSD. CLI only shows channels 1-4 available to swap. I know I can use the RSSI pad on CH3 for the 0-3.3v current output, but CH4 is 0-6.6v and the external current sensor vsense output is 0-3.3v. It would be nice to be able to use VB2/CU2 on ADC CH5 and CH6 and also this would allow two different battery voltage/currents to be shown on OSD.

I tried compiling my own target with 5 and 6 redefined but it didn't work.

**Comment by DzikuVx** [comment]
Done in https://github.com/iNavFlight/inav/pull/9180
