### ISSUE TITLE
FC lockup when armed if telemetry is configured on USB-VCP

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav#9375]
## Current Behavior
If telemetry is enabled over USB-VCP together with MSP, the FC will lock up as soon as the craft is armed. 

## Steps to Reproduce

1. Set a telemetry Protocol (Tested with LTM and MAVLINK) on USB-VCP parallel to MSP
2. Enable Telemetry Output in Configuration tab
3. Set up an RC Protocol with telemetry (in my case FPORT)
4. Wait for a satellite fix
5. Make sure prop is off or use USB Power only
6. Arm with radio
Result: Telemetry stops completely, no LED indicators, no disarm indicator. INAV seems to completely lock up and also can't conenct back to Configurator after disarming. 

## Expected behavior
FC Continues working and outputs telemetry over USB (For testing purposes or companion computers in Craft that have USB)

## Suggested solution(s)
Either no lock up or if not supported to have telemetry parallel to MSP on USB, then maybe add a sanity check for that. 

## Additional context
I was working with MWPTools and testing telemetry tacking features when I discovered this behavior. 
If I disable telemetry output in Configuration tab, I still get telemetry on the radio though but then it does not lock up anymore. 
[INAV_6.1.1_cli_T1_RANGER_20231016_173142.txt](https://github.com/iNavFlight/inav/files/12918822/INAV_6.1.1_cli_T1_RANGER_20231016_173142.txt)

---

- FC Board name and vendor: Matek F722-WPX, MATEKF405TE_SD
- INAV version string:
INAV/MATEKF405TE_SD 6.1.1 Jun 13 2023 / 11:29:16 (42ced253)
GCC-10.2.1 20201103 (release)

**Comment by stronnag** [comment]
Cannot reproduce with either `LTM` or `MAVLink` on MATEKF405 with current master `INAV v7.0.0  MATEKF405 (37b882ae)`

**Comment by b14ckyy** [comment]
I was able to narrow it down further. This is now the Release version of 6.1.1 and it behaves the same. DIFF added. 
I found that when I disable telemetry output in config tab, but keep LTM set on USB-VCP the issue does not happen. Does that option only affect dedicated Serial telemetry but not RC link telemetry? 
I wonder if it has to do with the RC Link telemetry. 
Maybe it was accidently fixed down the master line in 7.0.0 I will try that later.

**Comment by stronnag** [comment]
Well, if you disable telemetry, you won't get telemetry. 
I've used MSP/LTM and RX telemetry together, successfully in numerous versions for INAV over many years. 

Does this just happen for you on VCP? 
Have you tested it on other UARTS?

**Comment by b14ckyy** [comment]
Other UARTs work fine. It just happens when I set telemetry on USB-VCP while also MSP is enabled on USB. 

> Well, if you disable telemetry, you won't get telemetry.
That is what confuses me. When I Disable telemetry Switch in Configuration, I still get telemetry on my radio over the RC Link. Is that supposed to happen?

**Comment by stronnag** [comment]
Tested this again on `release_7.0.0` / c2577e47. With:

```
# MAVLink, LTM
serial 20 257 115200 115200 115200 115200
serial 0 17 115200 115200 115200 115200
```
and
```
# LTM, MAVLink
serial 20 17 115200 115200 115200 115200
serial 0 257 115200 115200 115200 115200
```

* Both ports have MSP + Telemetry
* No lockups
* Armed, expected telemetry seen on both VCP and USART
* There was also Smartport telemetry on a soft-serial UART, received at all times.
