### ISSUE TITLE
Profile change activates Failsafe

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#938]
In some cases, changing profile 1 to profile 2 causes Failsafe state to activate when receiver is not connected

**Comment by digitalentity** [comment]
Hm... I'll have a look

**Comment by digitalentity** [comment]
@DzikuVx I'm unable to reproduce the issue. What board did you use? Dump will also help.

**Comment by DzikuVx** [comment]
I will try to write more datails and reproduce again. 
Setup is: Omibnus F4, X4RSB, SBUS

**Comment by oleost** [comment]
Tried replicating, no sucess. 

Setup AirbotF4. Frsky XSR connected with SBUS.
Changed rateprofile trough Aux1 changing between 3 different profiles. (Setiup using adjustment tab )

**Comment by oleost** [comment]
Tried replicating, no sucess. 

Setup AirbotF4. Frsky XSR connected with SBUS.
Changed rateprofile trough Aux1 changing between 3 different profiles. (Setiup using adjustment tab )

Also disconnected the receiver and change profile with rateprofile command in CLI, did not see the failsafe symbol lit up there either.

**Comment by DzikuVx** [comment]
It was strange because if I remember correctly, it was engaging failsafe only from profile 1 to 2. Not from 2 to 1
