### ISSUE TITLE
FC MAMBA F722 I2C needs baro DPS310 updates

### ISSUE THREAD

**Issue by xnerkax** [iNavFlight/inav#9381]
Hi after 3hours of searching whats wrong with my new geprc m10 dq i finally found that the target.h file does not have line that defines the baro dps310. So if someone can update the firmware with new line that would be great. thank you.
// *************** Baro **************************
#define USE_BARO
#define BARO_I2C_BUS                    DEFAULT_I2C_BUS
#define USE_BARO_BMP280
#define USE_BARO_MS5611

**Comment by YI-BOYANG** [comment]
It seems more cumbersome to modify the target files of other brands in the official inav project. Please provide an email address so that I can send the firmware with dps310 added to you.

**Comment by xnerkax** [comment]
Thanks.
nerijus.monkus@gmail.com
