### ISSUE TITLE
RM3100 compass does not work with I2C bus

### ISSUE THREAD

**Issue by Shazhko-Artem** [iNavFlight/inav#9390]
It is impossible to connect an external compass RM3100 via the I2C bus since it is registered strictly for SPI. 
https://github.com/iNavFlight/inav/blob/f5b33a0cc5b47e24e217b66490a8f79e957da365/src/main/target/common_hardware.c#L248C1-L252C7
This is very strange because the code itself in [compass_rm3100.c](https://github.com/iNavFlight/inav/blob/master/src/main/drivers/compass/compass_rm3100.c) is written without reference to the I2C or SPI buses. Can this be fixed? I tried to correct the registration myself and add `USE_MAG_RM3100` to the FC target, the compass began to be displayed in the inav-configurator, but it does not see the data from the compass, perhaps the code still needs to be edited somewhere.

**Comment by cramredan1** [comment]
I see **DzikuVx** inadvertendly closed this thread, whereas on my side (and others I presume) we still get it wrong in iNAV... 8.0

. Impossible to connect a Mateksys RM3100 magnetometer in SERIAL UART/MSP protocol NOT DETECTED / RED ICON
. Impossible to connect a Drotek RM3100 magnetometer in I2C mode. NOT DETECTED / RED ICON

Whereas these exact devices are perfectly recognized in Ardupilot 4.5.7

Is the RM3100 compass taken in charge other than through the SPI port (as accurately stated by Shazhko-Artem in this original post), which is useless for devices which do not provide that port ?

Thanks for the reply.
