### ISSUE TITLE
Problem with matek F405CTR gyroscope

### ISSUE THREAD

**Issue by ZvEroBoY36** [iNavFlight/inav#9406]
Hello.  This flight controller is available and has been updated with new firmware version 6.1.1.  And I started having problems with the gyroscope, it floats from 0 to 2 on the scale.  In the meantime, when I installed firmware 1.8, the problems with the gyroscope disappeared.  What could be the reason please help.

**Comment by DzikuVx** [comment]
due to more aggressive filtering, small variations are expected. There will be no problems in flight

**Comment by ZvEroBoY36** [comment]
My quadcopter behaved poorly in flight due to these problems.

**Comment by ZvEroBoY36** [comment]
How can this aggressive filtering be reduced?  There are options?  среда, 25 октября 2023г., 22:11 +07:00 от Paweł Spychalski  ***@***.*** :
