### ISSUE TITLE
Current Behavior
Hi MAMBA F722IC ports tab on Inav 7 rc1 do not let to make the same changes as it was on inav 6. First photo is status from inav7. Second photo is what i want to set on inav 7. Third photo what was set on inav 6 and it was working. When i try to put frsky with serial rx and then save and reboot it just reboots to default.
Gps i am using is geprc m10 dq.

### ISSUE THREAD

**Issue by xnerkax** [iNavFlight/inav#9439]
![20231103_153805.jpg](https://github.com/iNavFlight/inav/assets/34602615/3b2297aa-915f-42cb-9ea6-6b100216f549)

![20231103_153703.jpg](https://github.com/iNavFlight/inav/assets/34602615/0cb7f88a-fb2f-4ee0-8ca4-9a329e8fe82e)

![20231103_155856.jpg](https://github.com/iNavFlight/inav/assets/34602615/63cc6a73-5963-413b-a478-9e4ff6d7febf)

**Comment by MrD-RC** [comment]
You shouldn’t be able to set telemetry and Serial RX on the same UART. What is your rc link setup?

**Comment by xnerkax** [comment]
Im using teranis qx7 with r9m with fport

**Comment by MrD-RC** [comment]
Then you just set SerialRX and in the receiver page set the protocol to FPORT. You don’t set anything on the ports page in the telemetry column.
