### ISSUE TITLE
INAV 7.0.0 RC1 KAKUTE F7 motors output bug

### ISSUE THREAD

**Issue by capblack** [iNavFlight/inav#9442]
INAV 7.0.0 RC1 KAKUTE F7 motors output bug , motor 1 is not working and the 2,3,4  It's messy
quad x profile

**Comment by mmosca** [comment]
Can you post a picture of your mixer tab? Did you check if the outputs match what you expect, like it is described in the release notes?

**Comment by capblack** [comment]
![kakute](https://github.com/iNavFlight/inav/assets/16296480/0bebc9c8-fbe7-4a95-ab9c-9815c1351627)

Hello, this is what I have after loading the diff file from inav 6.1.1
I hope I'm not omitting something due to ignorance of the new mixer

**Comment by mmosca** [comment]
That looks correct. Can you double check it still works in inav 6.1.1 and it is not a hardware issue. 

The motor allocation matches inav 6 and older, so I wouldn’t expect a change in behavior.

**Comment by capblack** [comment]
Hi yes is correct on INAV 6.1.1

**Comment by mmosca** [comment]
Turns out the new motor assignment code is too smart and exposes an old timer conflict
Thanks for reporting

**Comment by capblack** [comment]
I have tried it as props and with this firmware it works fine. , then I will try it in flight
