### ISSUE TITLE
[7.0.0 RC1] Ez Tune enabled FCs show still PID tuning options in stick command menu.

### ISSUE THREAD

**Issue by materia79** [iNavFlight/inav#9449]
## Current Behavior
After EZ Tune has been enabled the stick command menu (cms) still shows regular PID Tuning options which should not be used anymore and are only deactivated properly in the INAV Configurator.

## Steps to Reproduce
1. Flash INAV 7.0.0 to a Flight Controller
2. Enable EZ Tune in the configurator, save and reboot
3. Activate the stick command menu
4. Navigate to "PID Tuning"

## Expected behavior
PID tuning configuration should not be possible anymore via the stick command menu after EZ Tune has been enabled.

## Suggested solution(s)
Instead offering PID tuning on a Flight Controller where EZ Tune has been enabled show the EZ Tune configuration in the stick command menu.

## Additional context
![photo_2023-11-06_16-12-16](https://github.com/iNavFlight/inav/assets/3817250/d07b8d7d-2117-4d69-bd63-fde90a242cbf)

- FC Board name and vendor:
- INAV version string:
![photo_2023-11-06_16-12-16 (2)](https://github.com/iNavFlight/inav/assets/3817250/c0aa6650-da23-42a5-b6de-091b4f6c8e8b)

**Comment by b14ckyy** [comment]
Fixed with https://github.com/iNavFlight/inav/pull/9813
