### ISSUE TITLE
On inav 7 rc1 got mag qmc5883l issue

### ISSUE THREAD

**Issue by xnerkax** [iNavFlight/inav#9450]
Hi i have geprc m10 dq unit and have a issue with magnetometer that is shown in the picture, i dont have readings in every direction as you can see it dosent go below 0 but in inav 6.1.1 it does. Maybe someone has the same problem and knows the fix. Tried to calibrate numerous of time. The board is mamba f722 i2c![20231105_194104.jpg](https://github.com/iNavFlight/inav/assets/34602615/ddd55a5e-151d-477f-b8ed-a599bd24dcc0)

**Comment by shota3527** [comment]
Hi, this commit will fix this 8e7cc6bb32c34950d8074c1b47805d986978cd65

**Comment by xnerkax** [comment]
Hi i made the changes now it shows. If someone needs it is whit added dps310 baro and updated fc msp file.

**Comment by xnerkax** [comment]
[mambaf722_i2c.zip](https://github.com/iNavFlight/inav/files/13283479/mambaf722_i2c.zip)

**Comment by mmosca** [comment]
Have you tried with INAV 7.0 rc2?

**Comment by xnerkax** [comment]
Yes i tried it the day it was released and it was the same

**Comment by mmosca** [comment]
> > Hi, this commit will fix this [8e7cc6b](https://github.com/iNavFlight/inav/commit/8e7cc6bb32c34950d8074c1b47805d986978cd65)
> 
> Is this suppose to be included in v7 ? Or for anyone to selfcompile if needed?

Try rc3.

**Comment by Thidsa** [comment]
Just what i wanted to know that its included allready. thx
