### ISSUE TITLE
MATEKSYS Optical Flow & Lidar Sensor - 3901-L0X

### ISSUE THREAD

**Issue by anselbear** [iNavFlight/inav#9451]
## Current Behavior
Configuration Button doesnt configure sensor. 

## Steps to Reproduce

1. Hardware Benewake TF Mini Plus (range finder)
2. Matek 3901-LOX optical flow and rangefinder
3. Flight Controller Mamba MK4 F722 Mini
4. ## Expected behavior
Unable to successfully completethe configurationof the Matek 3901-LOX
Process freezes and no configuration is completed.

## Suggested solution(s)

This worked flawlessly in INAV 6
## Additional context

https://pastebin.com/38L3n72v
---

- FC Board name and vendor:
- Hardware Benewake TF Mini Plus (range finder)
2. Matek 3901-LOX optical flow and rangefinder
3. Flight Controller Mamba MK4 F722 Mini
- INAV version string:
INAV 7

**Comment by b14ckyy** [comment]
did you test this with INAV 7 or 7.1 RC1? If it is still an issue we can reopen.
