### ISSUE TITLE
ESC's beeping @ zero throttle In RC1 configurator w/ DShot

### ISSUE THREAD

**Issue by Kiiski1** [iNavFlight/inav#9469]
## Current Behavior
<ESC's beeping twice per second when throttle in output tab is zero

## Steps to Reproduce
1. Set motors to DShot with Speedybee F405 v3. in either BLHeli S or Bluejay.
2. Plug in battery, ESC's do expected tones then beep ~2 times per second non-stop
3. Connect to INav 7 RC1
4. Go to outputs tab and raise throttle value one click up and beeping stops, motors spin up correctly
5. Lower throttle value and beeping begins again
6.
7.

## Expected behavior
Plug in battery and not have incessant beeping

## Additional context
Dump
https://pastebin.com/kDKQbtZZ

---

# version
# INAV/SPEEDYBEEF405V3 7.0.0 Oct 31 2023 / 13:54:20 (fdb61d3a)
# GCC-10.3.1 20210824 (release)

- FC Board name and vendor: Speedybee F405v3
- INAV version 7.0.0-RC1

**Comment by DzikuVx** [comment]
I just tested this setup and it's working fine. 
@Kiiski1 beeping is caused by one of audible alerts. Probably Virtual Pitot. Ensure all sensors are blue in the configurators top bar
