### ISSUE TITLE
Esc alarm on Diatone MAMBA F722_2022B AIO between INAV6.1.1 and 7.0RC2 

### ISSUE THREAD

**Issue by Pancronos** [iNavFlight/inav#9484]
Firmware for MAMBAF722_2022B with Inav 6.1.1 works fine with motor and default configuration. 
When firmware is upgraded to 7.0RC2 upon connecting the battery esc starts beeping. Tried with config from 6.1 and with brand new config, still beeps. reflashing 6.1 all works fine.
Attached diff
[INAV_6.1.1_cli_20231112_214347.txt](https://github.com/iNavFlight/inav/files/13329164/INAV_6.1.1_cli_20231112_214347.txt)
[INAV_7.0.0_cli_20231112_175854.txt](https://github.com/iNavFlight/inav/files/13329165/INAV_7.0.0_cli_20231112_175854.txt)

**Comment by DzikuVx** [comment]
Have you tried disabling the Virtual Pitot in Configuration tab?
