### ISSUE TITLE
7.0.0-RC2 - Wrong motor mapping in SpeedyBee F7 V3 BL32

### ISSUE THREAD

**Issue by agoliveira** [iNavFlight/inav#9488]
## Current Behavior

The automatic mixing for a quad using the 7.0.0-RC2 in the SpeedyBee F7 V3 BL32 FC is mapping motor 4 to S6 instead of S4.
![image](https://github.com/iNavFlight/inav/assets/13205716/87e839db-df80-4dd1-a2cc-812abe75069e)
If the timer outputs are set to MOTORS, the mapping is correct
![image](https://github.com/iNavFlight/inav/assets/13205716/c15c4305-73f4-4c1e-947d-a36d47f57bf0)
This does not happen with INAV 6.1.1

## Steps to Reproduce
Install INAV 7.0.0-RC2 or RC1 in the FC, set initial mixer to multirotor 7".

## Expected behavior
The motors should be mapped as per the second image (S1 -> motor 1, S2 -> motor 2, etc).

## Suggested solution(s)
Mapping should be the same as 6.1.1, this is a regression.

## Additional context
Dump: https://pastebin.com/xQWZVnct

- FC Board name and vendor: SpeedyBee F405 V4 BLS 55A 30x30 Stack
- INAV version string: # INAV/SPEEDYBEEF7V3 7.0.0 Nov  8 2023 / 15:41:13 (a54849be)
GCC-10.3.1 20210824 (release)

**Comment by mmosca** [comment]
This was fixed in #9475 and will be include in the next release (rc3 or 7.0 final, whichever comes first)

**Comment by agoliveira** [comment]
Thanks. I did search for it but wasn't able to find it probably because of the way the FC was mispelled.
