### ISSUE TITLE
RFC - remove hard-coded motor & servo templates

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#95]
I was looking at the code in mixer.c, and it looks like a fair amount of space is invested in storing hard-coded motor layout templates. It seems to me that it would be more efficient & effective to treat all motor & servo layouts and 'custom mixes' that must be user-configured over serial & stored in EEPROM, versus having them all taking up flash space. Removing the unused layouts would free up a bit of space for other features. You really don't need a bunch of large motor layout float arrays stored in flash when you're only running a quad or a flying wing (1 motor+2 servos).

This would obviously cause a serious break from mainstream CF, and would require new docs in order to show users how to load custom motor/servo layouts (even for basic setups such as a quad with no servos). However, I believe it might be worthwhile, and doesn't look like it would require _too_ many changes to the mixer code.

feedback is welcome

**Comment by digitalentity** [comment]
I think it's best to have a few preconfigured mixes for most common types of frames (X4, X6, Y6, Tricopter, Airplane, Flying wing) and allow the exotic setups only as custom motor mixes.

**Comment by csurf** [comment]
ok, so I take it you'd be more/less opposed to this idea? I figured it might be an easy way to reclaim some flash space since only one template/motor layout is ever used, and it's only setup once during initial configuration. It seems it would make more sense to have the templates loaded via configurator. However, I see how this would require major modifications to configurator.

If you don't see a way forward with this idea, feel free to close it out...

**Comment by digitalentity** [comment]
No opposed. This is a great idea, but we have to modify both iNav and
Configurator to do this. At the moment we might just want to remove less
frequently used mixers.

**Comment by digitalentity** [comment]
Partially done in #143
