### ISSUE TITLE
Organize profile config

### ISSUE THREAD

**Issue by sambas** [iNavFlight/inav#950]
Profile config has some unnessesary items in it that can cause confusion and/or other issues when not set properly. 
While working on diff command so far I have found these:
modeActivationCondition_t (cli aux)
adjustmentRange_t (cli adjrange)
servoParam_t (cli servo)
gimbalConfig_t

These could be dropped under master config to be global for all profiles and free some memory (2xsizeof(those)).
Anyone using these with different profiles?

**Comment by digitalentity** [comment]
This is no longer relevant.
