### ISSUE TITLE
1.5RC1 broken on EVO / Tricopter

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#951]
The EVO tri servo does not react at all (on arm or to yaw) on builds after 716a4893. There are two obvious culprits (EVO forwarding or other tri work).

Discovered testing #946, the output of which works for (development) 716a4893 but not on cli-diff, which was synced to the more recent commits. Further bisection in progress.

**Comment by stronnag** [comment]
005062fb works, so (damn it) it's the final EVO channel forwarding commit (6b28d5f9) that breaks it.

And having the diff (thanks  #946 / @sambas ) makes re-configuring / testings so much easier :)

**Comment by digitalentity** [comment]
Thanks! Will fix asap.

**Comment by digitalentity** [comment]
Fixed
