### ISSUE TITLE
[FW] No smooth transition Autolaunch -> WP Mode

### ISSUE THREAD

**Issue by Scavanger** [iNavFlight/inav#9533]
At the moment it is not possible to switch seamlessly to waypoint mode after autolaunch, all other flight modes work without any problems. 
If you switch to waypoint mode during autolaunch, the (W)RTH mode appears instead. It must be switched to another mode.
With the upcoming autoland mode for fixed wings, completely autonomous missions would then be possible.

**Comment by breadoven** [comment]
The code for control of WP, RTH and Manual modes needs refactoring really, it's messy after many revisions over time, needs properly cleaning up ... including allowing WP mode to work immediately after Launch without reverting to RTH instead.
