### ISSUE TITLE
INAV Black box not working - Matek H743 slim V3

### ISSUE THREAD

**Issue by Hex-Davis** [iNavFlight/inav#9540]
## Current Behavior
I'm having an issue with the black box in INAV failing to crate a useable flight log or not creating one at all.

## Additional context
[Shendrone INAV dump_file.docx](https://github.com/iNavFlight/inav/files/13579024/Shendrone.INAV.dump_file.docx)

The Black box logging is set for on-board SD card slot, the SD card is a 32G formatted fat32 in 32Kbs it has been checked via H2testw and came back with a wright of ~25Mbs/s without any errors. I did try a 4G card that had 10Mbs/s but this appeared to have no positive impact. Looking around i found suggestions about the 'logging rate' and the 'loop time', ultimately suggesting a lower collection rate of ~10-20Hz. I've changed these two values around a few times for higher and lower collection rates to no avail. I have the black box mode activate off the same channel as the mode Arm so it starts logging when Armed and stops when disarmed but all I'm getting is unreliable/unusable data, if any data is collected at all.

[LOG00001.TXT](https://github.com/iNavFlight/inav/files/13578927/LOG00001.TXT)     This is a copy of one of the logs that should have been two logs about 15 sec long but for some reason is one about 3 sec long.

My last steps taken where trying past versions of firmware. I went from 6.1.1 to 6.1.0 to 6.0.0 same issue in all of them. I then changed to Betaflight which worked right away, i was able to load logged files into 'BlackBox explorer' and 'Pid toolbox' with out issue. i would just keep using betaflight but i built this drone with the intention to have it fly missions.
Right now im thinking the SD card and FC checks out else log recording in Betaflight would also have been a problem, so im back to looking at software set up again. Any direction would be greatly appreciated.

---

- FC Board name and vendor: Matek H743 slim V3
- INAV version string: # INAV/MATEKH743 6.1.1 Jun 13 2023 / 11:52:23 (42ced253) # GCC-10.2.1 20201103 (release)

**Comment by stronnag** [comment]
The log looks fine:

* No corrupted headers
* c. 11 seconds of data
* Disarm by switch recorded at end

```
$ blackbox_decode --stdout > /dev/null  LOG00001.TXT 

Log 1 of 1, start 00:15.119, end 00:26.011, duration 00:10.892

Statistics
Looptime           2502 avg            0.6 std dev (0.0%)
I frames      18   88.0 bytes avg     1584 bytes total
P frames      17   68.7 bytes avg     1168 bytes total
E frames       1    6.0 bytes avg        6 bytes total
S frames      21   44.0 bytes avg      924 bytes total
Frames        35   78.6 bytes avg     2752 bytes total
Data rate    3Hz    663 bytes/s       6700 baud

2 frames failed to decode, rendering 0 loop iterations unreadable. 
4318 loop iterations weren't logged because of your blackbox_rate settings (10804ms, 99.20%)

Generated by INAV blackbox_decode 7.0.0

```


```
$ tail -c 29 LOG00001.TXT 
End of log (disarm reason:4)
```

**Comment by stronnag** [comment]
The log is complete according to your log settings. There is no apparent firmware issue in the minimal log offered. Logging at 1/200 with a 2500ms looptime is not useful.

**Comment by Hex-Davis** [comment]
After this was marked as closed i decided to just wait to see if an up-date would come out to fix the issue. No such luck. This issue continues to persist. Attached is another file recorded 50% loop time (1/2),cycle time was 2500. this recording should be roughly 80sec long but is <2sec long. it appears to be the first 2sec of the flight.
something maybe related is when looking at the available data in the black box analyzer the X-axis values for frequency are "infinity Hz"??
[Uploading LOG00001.TXT…]()
