### ISSUE TITLE
all three gps sattelites get disabled when enabling BeiDou

### ISSUE THREAD

**Issue by tippfehlr** [iNavFlight/inav#9548]
## Current Behavior
When I try to enable BeiDou Sattelites (CN) via GPS tab or cli, after rebooting all three, Galileo, BeiDou and Glonass are disabled again (in ui and in cli).

## Steps to Reproduce
1. enable Galileo and Glonass and reboot: works as expected
2. enable BeiDou Sattelites and reboot: all three are disabled again

## Expected behavior
all three stay activated

## Suggested solution(s)
--

## Additional context
https://pastebin.com/zg48j9fb
Opened an issue in [inav-configurator](https://github.com/iNavFlight/inav-configurator/issues/1914) first, but this is probably an issue with inav itself.

---

```
# version
# INAV/SPEEDYBEEF405WING 7.0.0 Dec  5 2023 / 11:06:36 (895a4f31)
# GCC-10.3.1 20210824 (release)
```

**Comment by P-I-Engineer** [comment]
had same issue, but it's correct.

beidou and glonass share the same stuff. so you can only use 1.
