### ISSUE TITLE
hangs when saving

### ISSUE THREAD

**Issue by RRCrrc** [iNavFlight/inav#9565]
just flashed final stable inav 7.0 and latest configurator
Clicked on "airplane with tail"
then it hanged and never went further during the "saving data" popup with the vertical bars moving the whole time.
after 10 minutes i clicked X top right corner and popup disappeared
airplane image is there and all looks fine but i do not know for sure if it saved it all
is there a way to verify all is good such as pasting my diff all text into cli and moving on and doing something?
thank you so much for this wonderful new version for all you work. CAN'T WAIT TO TRY CRUISE OUT AND THE REST.

**Comment by MrD-RC** [comment]
Duplicate, already fixed in a PR.
