### ISSUE TITLE
No Data Flashchip found 

### ISSUE THREAD

**Issue by FarmboyFPV** [iNavFlight/inav#9567]
I am getting a NO DATAFLASH CHIP on INAV 7.    Getting this on both of my Speedybee WIng.  One is brand new.   Blackbox is enabled with SD cards.     This just started after I reflashed my INAV and was not doing this even without a SD card before.  Tried Reflashing many time with no avail.    No one has a solution.    This is keeping the system from recognizing the receiver  so I'm at a standstill.

**Comment by b14ckyy** [comment]
You see No Dataflash Chip because the FC has no Dataflash Chip ;) 

this field refers to FCs with soldered on flash chip. It does not show SD capacity. Maybe worth a change in the future but not a bug right now. In Blackbox tab you see the SD card status.
