### ISSUE TITLE
Not detecting Gyro, Accel, on SkystarsF22 mini hd based board INAV 7.0.0

### ISSUE THREAD

**Issue by sachinyadav1990** [iNavFlight/inav#9591]
This is similar to Issue #8303, but is happening to SkystarsF22 mini hd based board INAV 7.0.0

Current Behavior
INAV 7.0.0: Accel, Gyro, detected, GYRO not lit up and Acell is lit RED. Manual selection does not help.

![image](https://github.com/iNavFlight/inav/assets/9860571/ce3ad589-cff3-4d1f-987e-2af2e6aee6db)

![image](https://github.com/iNavFlight/inav/assets/9860571/baac5b2e-60ae-4e7c-925e-9d33079002e6)

**Comment by mmosca** [comment]
What INAV target is recommended by the manufacturer for this board?
