### ISSUE TITLE
Doesn't detect gyro and accell Inav 7.0.0, 

### ISSUE THREAD

**Issue by Restuadkh** [iNavFlight/inav#9593]
## Steps to Reproduce

1. Instal inav 7.0.0 into Target : FURYF4OSD, with accl ICM42668P
![Screenshot 2023-12-23 235747](https://github.com/iNavFlight/inav/assets/35425285/2243fde2-139e-42b6-ad80-5a4343e12280)
2. set to ICM42605
![image](https://github.com/iNavFlight/inav/assets/35425285/66167fc8-d092-4675-9ab0-5367fe5c25f7)
3. alternatif i adding the sensor mpu6500 and mpu6050, but is a same
4. 

## Additional context

---

- FC Board name and vendor: Mamba f405 MK2 V2, FURYF4OSD
- INAV version string: 7.0.0

**Comment by mmosca** [comment]
What happens if you set accelerometer to auto and reboot?

**Comment by mmosca** [comment]
No response.
