### ISSUE TITLE
Vtx ultra Long Range akk

### ISSUE THREAD

**Issue by spajkr** [iNavFlight/inav#9595]
Hello, could you please advise me how to set it so that I have 3W power set on the vtx. When I try to set it up, I have a max of 500 power

**Comment by b14ckyy** [comment]
No worries. Ignore what power level the OSD shows. the VTX has 5 power levels: 250/500/1000/2000/3000mW

so just select the Power level 5 and you are good. Use the Channel/Band/Power OSD element that shows the power level instead of mW to not get confused.
