### ISSUE TITLE
Motor #1 doesn't rotate when the craft is armed with Multishot protocol. [Speedybee F405 v3]

### ISSUE THREAD

**Issue by johndoe422** [iNavFlight/inav#9602]
Stack: Speedybee F405 v3 50A BLSheli ESCs
Form Factor: 5 inch quad, no FPV system, 2300kv motors, 4S 1550mah batteries, Radiomaster TX12 MKII ELRS Transmitter.

Issue: with Multishot protocol selected, motor number 1 doesn't rotate when the craft is armed. 

throttle_idle =  10.000
throttle_scale =  0.750
thr_expo = 60
thr_mid = 47

**Comment by sensei-hacker** [comment]
If you choose to use Multishot, the ESCs need to be calibrated. Has that been done?
