### ISSUE TITLE
MAMBAF722_I2C GPS+Magnetometer don't work together

### ISSUE THREAD

**Issue by Vins1417** [iNavFlight/inav#9610]
## Current Behavior
On the Mamba F722 35A MK1, target MAMBAF722_I2C, the gps connects to the uart4 and SCL & SDA pads.

After flashing firmware 7.0.0 the barometer and magnetometer are recognized without problem. (Note that in the basic configuration the UART4 port is checked MSP).

When you configure UART4 as GPS, the MSP check mark disappears and the barometer and magnetometer are no longer recognized and appear in red.

## Steps to Reproduce

1. Flash to firmware 7.0.0 -> the barometer and magnetometer works fine.
2. Configure UART4 as GPS, save and reboot
3. The barometer and magnetometer are no longer recognized and appear in red

## Expected behavior
Configure UART4 as GPS save and reboot and magicaly the barometer and magnetometer works fine.

---

# version
# INAV/MAMBAF722_I2C 7.0.0 Dec  5 2023 / 10:21:16 (895a4f31)
# GCC-10.3.1 20210824 (release)
![carte-de-vol-mamba-aio-f722-mk1-35a-6s-8bits-schema](https://github.com/iNavFlight/inav/assets/148378237/797f62cd-6da3-4303-b882-36b3ba52f014)
![Capture](https://github.com/iNavFlight/inav/assets/148378237/827ba2d5-9e0b-4870-b3f1-3efa1b4c8953)
![Capture1](https://github.com/iNavFlight/inav/assets/148378237/604b7653-44bf-4f46-bb3d-7f575aeb35d9)

**Comment by mmosca** [comment]
Did you test with usb only, or did you test with the battery connected? Is the gps actually powered?

**Comment by sensei-hacker** [comment]
The I2C board has the built-in Bluetooth on UART4. That's why it's set for MSP.
You could try connecting GPS to UART5.

**Comment by Vins1417** [comment]
> Did you test with usb only, or did you test with the battery connected? Is the gps actually powered?

hoo it works perfectly with the battery!!  Thanks a lot !!  but it's strange because without the GPS the barometer was fine without the battery.

**Comment by Vins1417** [comment]
> The I2C board has the built-in Bluetooth on UART4. That's why it's set for MSP. You could try connecting GPS to UART5.

are you sure ??  because I never knew that there was bluetooth on this card.. and in the doc the gps is on uart4... you weren't confusing it with the f722 APP stack??

**Comment by mmosca** [comment]
> 
> hoo it works perfectly with the battery!! Thanks a lot !! but it's strange because without the GPS the barometer was fine without the battery.

Hard to figure out. But the unpowered magnetometer may have caused issues in the i2c bus. I will close this, since connecting the battery fixes the issue.
