### ISSUE TITLE
Frsky telemetry sats in degrees

### ISSUE THREAD

**Issue by MichaelETHOS** [iNavFlight/inav#9620]
#Hello everyone, after a long break with inav I started again.  I built a vtol and use frsky ethos with a tdmx receiver.  Now I want to understand the telemetry and I'm not getting anywhere with it.  the number of satellites are displayed in degrees ° (temp2) at Ethos.  how can I set that I can see the number of sats as a number on the x20.  or is it possible to update inav so that it displays the frsky telemetry better like Crossfire or jeti.  A friend uses jeti and he gets it displayed as sats.  thank you for your help.

**Comment by MrD-RC** [comment]
The issue is that the LUA script doesn’t exist of ETHOS. The number of sats is part of the Tmp2 (not Temp2) sensor. You can see how to understand the values in the telemetry.md document. It is not a temperature reading l, so should not be displayed in degrees.
