### ISSUE TITLE
KakuteH7 not recognizing any Rx.

### ISSUE THREAD

**Issue by finiteuser** [iNavFlight/inav#9628]
## Current Behavior
Brand new Holybro KakuteH7. Been flashed with ardupilot, betaflight, and inav. Been tried with multiple Rx's - ones that definitely work with other flight controllers, and are definitely bound to the radio.  In every instance, the FC does not detect the Rx or respond to stick inputs.  Settings are as per the following images

![inav1](https://github.com/iNavFlight/inav/assets/145856092/a8ca3281-90ea-4fef-8c0d-3817ae539910)
![inav2](https://github.com/iNavFlight/inav/assets/145856092/420aa7d1-d2ae-4f9a-ba00-fc71f4e8d0c5)
![attached diagram](https://github.com/iNavFlight/inav/assets/145856092/67415058-98ce-4f09-b871-d2f2997eae82)

New issue just today: The gps no longer works. It used to work. It hasn't been rewired or changed at all. It just stopped working.  The FC can still "see" the gps. But even sitting in an open window of 15 minutes, it never acquires any satellites. This is new behavior. 
![gps](https://github.com/iNavFlight/inav/assets/145856092/b5281c37-2b22-42d3-ae31-9c561dea2ba9)

## Steps to Reproduce

1. Connect any ELRS receiver to my (brand new) KakuteH7
2. The receiver page will not register any inputs from the controller.
3.  Contact Holybro support. Ask for assistance
4. They tell you to contact inav developers and make this report.

## Expected behavior
The bars on the receiver tab should move as I move the sticks

## Suggested solution(s)
If this is a software or configurating issue, *please* tell me what I did wrong.

## Additional context
I personally suspect that I have a hardware issue but Holybro support won't help me until I exhaust every avenue.
https://pastebin.com/agH1ecnG

INAV/KAKUTEH7 7.0.0 Dec  7 2023 / 12:43:28 (91ca1047)
# GCC-10.3.1 20210824 (release)

**Comment by sensei-hacker** [comment]
The config looks sane. Have you tried a different uart, just to see?
The most common problem this reminds me of is having the receiver rx connected to the FC rx, and the tx connected to tx.  It should be rx to tx, tx to rx.  You may be aware of that, but it's worth checking.

**Comment by finiteuser** [comment]
I tried it on UART1 and it was the same.  The FC doesn't see the RC.  I connected it backwards (tx to tx and rx to rx) a when I was swapping different receivers onto the flight controller.  It's pretty consistent.  

Except for the part where it's slowly getting worse. It used to work under this configuration.  
![64a0bd1cce2b948fdcb84fd8fca61d064bc1b5d1](https://github.com/iNavFlight/inav/assets/145856092/48dce10f-a190-4b8b-bcf8-f048bc0fb2b0)
(This screenshot is from January 6). 

But it stopped working.  In edgeTX I inverted channel 5, (so arming could be "high"), and I left it out overnight.   Then the FC and RC stopped communicating. Except that the Receiver gets telemetry data back from the Rx. 
![inav](https://github.com/iNavFlight/inav/assets/145856092/c5fc08fd-4320-47e5-bbc0-06d5d20be1e0)
It can see the number of sats and the battery voltage.  So it has a one-way connection.

It has one-way connection; it used to work fine. (But it never worked in betaflight or arducopter), and it's slowly getting worse. For example today the "Sats" number never went above zero even when I left it in an open window for 10 minutes.  But the gps still shows up as blue and doesn't generate any error messages. It doesn't matter how many gps sats it can see if I can't get the RC to work, but I just think it's interesting that now it has two things not working instead of one.  (And on uart1 it also does the weird one-way telemetry thing).

**Comment by sensei-hacker** [comment]
ELRS uses the Rx and tx wires exactly as they are named. It receives RC commands on RX and sends telemetry on TX.  So you may have one bad connection.  Could be a wire broken inside the insulation or inside the connector.

**Comment by finiteuser** [comment]
The broken connection must not be between the receiver and the ends of the wires soldered to it.  I have verified this with a multimeter. I have good conductivity between the solder pad on the receiver and the solder pad on the flight controller.  If there is a bad connection, I believe it is on the flight controller  itself, and somewhere common to all serial ports.  Does such an area exist? 

Is there something like a "common hardware group serial reception area?" The issue must be in the "receive" area, since the flight controller transmits telemetry data to the radio in my hand via the one on the quad. So the 'transmit' side of things seems to be working.
