### ISSUE TITLE
INAV 7 not logging yaw set point or rc command

### ISSUE THREAD

**Issue by bw1129** [iNavFlight/inav#9636]
I notice that yaw set point and yaw RC command are not being logged in INAV 7. Tried logfiles from serveral different sources. It just shows a string of zeros. roll and pitch are fine. here is a screenshot of an example, zoomed 500%. yaw (YELLOW) is perfectly flat with no deviation from 0.
![image](https://github.com/iNavFlight/inav/assets/17284912/7e19c769-787a-43ea-adec-3dcee1ded015)

**Comment by DzikuVx** [comment]
Just quickly checked and everthing looks fine over here 
![image](https://github.com/iNavFlight/inav/assets/966811/3fec2385-cb29-4d1c-98fd-246e313e0918)

Maybe you could share more details @bw1129

**Comment by b14ckyy** [comment]
Any input on that or is this obsolete?

**Comment by bw1129** [comment]
It seems fine on some FCs so for now I assume it was an SD card logging issue.
