### ISSUE TITLE
Possible gyro readout error

### ISSUE THREAD

**Issue by DarthPlasma** [iNavFlight/inav#9638]
Custom BOB57 with Diatone Mamba H743 mark 4

## Current Behavior
After updating to Inav 7 i noticed some Pitch jerk movement, investigating the RAW gyro signal shows some strange occasional full scale spikes (up to 2000 raw value) only on the pitch signal, usually negative. This spike is shaped by the filtering to a longer peak that screws up temporarily the DTERM and hence the motor output, then dissipating in a couple of ms but causing the motors to give a false pitch output that produces noticeable twitch on the motors.

## Steps to Reproduce
It happens everytime I fly since the update, at least 2-5 times each minute.

## Expected behavior
Spikes to be absent on the raw gyro

## Suggested solution(s)
Checking if there is some incompatibility problem with the ICP42688-p readout

- FC Board name and vendor: Diatone Mamba H743 mark 4
- INAV version string: 7.0.0
![immagine](https://github.com/iNavFlight/inav/assets/80295410/755b67bb-e2d0-4bc5-95cc-bd9af15dffa5)
![immagine](https://github.com/iNavFlight/inav/assets/80295410/8ceca12a-ec90-406c-bc68-e81fb72582e5)
![immagine](https://github.com/iNavFlight/inav/assets/80295410/fa2c11e2-8d2c-4f5f-ab55-a13d31b63df5)

**Comment by DarthPlasma** [comment]
It happens even with the drone armed on ground, props removed 
![immagine](https://github.com/iNavFlight/inav/assets/80295410/8498dbe6-25f2-4859-aa75-c641e799e04c)

**Comment by mmosca** [comment]
Can you try 7.1 rc1?
I made some changes to the filtering in the icm42688p gyro and that got rid of a similar issue I had with the same fc.

**Comment by mmosca** [comment]
Fixed by #9675 

Feel free to re-open if it still happens after 7.1RC1

**Comment by DarthPlasma** [comment]
The issue seems to be resolved, at least in a quick basement testing 😊

**Comment by DarthPlasma** [comment]
Unfortunately the spikes are more rare but not disappeared totally. In 8 minutes arm time i had 8 spikes, and 1 in another 4 minute flight

**Comment by DarthPlasma** [comment]
this is the blackbox of the drone armed on ground

 https://we.tl/t-nyEGVo3tnr

**Comment by DarthPlasma** [comment]
Ok issue resolved al 100%. The residual spikes were from leds connected on the 5V of the FC. Using a BEC wiped out the last problems
