### ISSUE TITLE
Matek F722STD,  alignment problem 

### ISSUE THREAD

**Issue by capblack** [iNavFlight/inav#9651]
Hello, I have an alignment problem with an old Matek F722STD, after updating to INAV7, it started with a tendency to the right, and I used the alignment tool to correct this tendency, but it seemed to act totally different from what I do, first I corrected the roll +2, but in practice it responds to the pitch, the FC alignment is standard up front, I'm doing something wrong, thank you

**Comment by DzikuVx** [comment]
Alignment tool is to set up orienatation, not calibrate and trim the acc.
Recalibrate accelerometer, check for vibrations
