### ISSUE TITLE
Autolaunch topic with 7.0.0 compared to 6.1.1 (fixed Wing, Funjet)

### ISSUE THREAD

**Issue by druckgott** [iNavFlight/inav#9653]
## Current Behavior
With 6.1.1 after some optimisations the autolaunch worked quite good with the fixed wing funjet
Now I updated to 7.0.0 and the funjet rotates quite much. It´s not realy smoth and i nearly crashed.

## Steps to Reproduce
Flash 7.0.0 with same diff of 6.1.1

## Expected behavior
same behaviour like 6.1.1

## Suggested solution(s)
attached the logs it looks so different see below
[LOG00045.TXT](https://github.com/iNavFlight/inav/files/13998649/LOG00045.TXT)

Is there anything changed between the autolaunch behavior on both verisons

## Additional context
7.0.0 diff
[INAV_7.0.0_cli_FUNJET_20240114_171807_diff.txt](https://github.com/iNavFlight/inav/files/13998639/INAV_7.0.0_cli_FUNJET_20240114_171807_diff.txt)
6.1.1 diff
[INAV_6.1.1_cli_FUNJET_20240114_170544_diff.txt](https://github.com/iNavFlight/inav/files/13998640/INAV_6.1.1_cli_FUNJET_20240114_170544_diff.txt)

- FC Board name and vendor:
- Speedybee Wing F405 fixed wing
- INAV version string:
- 7.0.0
[LOG00057.TXT](https://github.com/iNavFlight/inav/files/13998653/LOG00057.TXT)
- 6.1.1
[LOG00044.TXT](https://github.com/iNavFlight/inav/files/13998648/LOG00044.TXT)

**Comment by MrD-RC** [comment]
Nothing has changed for autolaunch in 7.0.

**Comment by druckgott** [comment]
Are there any other changed which can have influence the Autolaunch roll behavior

**Comment by druckgott** [comment]
Here is some refacroting where Code in Autolaunch is changed or not

https://github.com/iNavFlight/inav/pull/9287/files

**Comment by Jetrell** [comment]
>     * 7.0.0
>       [LOG00057.TXT](https://github.com/iNavFlight/inav/files/13998653/LOG00057.TXT)
> 
>     * 6.1.1
>       [LOG00044.TXT](https://github.com/iNavFlight/inav/files/13998648/LOG00044.TXT)

Looking at the logs.. It appears from the 7.0 log, that you moved the roll stick to full deflection, straight after `launch_in_progress` began... Which cancelled auto launch. And caused it to roll rather abruptly from looking at the `setpointRate[roll]` and rapid i-term roll accumulation.

![Capture](https://github.com/iNavFlight/inav/assets/47995726/2e934458-6094-4ef2-b539-58c5871deb72)

**Comment by druckgott** [comment]
the point is that on 7.0.0 it rolls much more then on 6.1.1 is the feeling. We did many tests on 6.1.1 to get it to a good behavior. Then i flashed to 7.0.0 and all 3 starts it rolls quite mutch and I put my handy to the stickts to roll it back.
[LOG00057.TXT](https://github.com/iNavFlight/inav/files/14001071/LOG00057.TXT)

**Comment by Jetrell** [comment]
As soon as you move the stick past `nav_fw_launch_abort_deadband`. It will cancel auto launch. And in your case, become Horizon mode.
So we can't be seen from logs 57, what would have happened if auto launch had continued.
While in the log 44 from 6.1.1. Auto launch was completed.


> Here is some refacroting where Code in Autolaunch is changed or not
> 
> https://github.com/iNavFlight/inav/pull/9287/files

That just looks to be cleanup for multirotor throttle tilt compensation.

But the throttle scaling was refactored.. Including launch idle throttle changes. https://github.com/iNavFlight/inav/pull/9287
So it may be providing less available throttle in 7.0, with the same launch throttle setting from 6.1.1... Which might explain why the roll axis felt lazy at launch.

**Comment by druckgott** [comment]
Ok why is this done does this makes sence or whata the background?

**Comment by b14ckyy** [comment]
that change only affects multirotor not fixed wings.
