### ISSUE TITLE
Add new Target for Hobbywing XRotor F7 with Barometer

### ISSUE THREAD

**Issue by nishthapa** [iNavFlight/inav#9661]
## Current Behavior

There is no target for the Hobbywing XRotor F7 Flight Controller. Although the newer revisions of this Flight Controller don't come with a built in Barometer, there are empty solder pads for it. I was able to install a BMP280 by verifying the pads by probing with my multimeter. I have also verified the baro output in Betaflight.

## Desired Behavior

After installing a BMP280 to it, it might become a fully featured board capable of running the latest version of INAV (version 7)

## Suggested Solution

A target can be added for the Hobbywing XRotor F7 Flight Controller with diy barometer installed at the empty pads or just with an external barometer connected via I2C

## Who does this impact? Who is this for?

This is for all the users of the Hobbywing XRotor F7 Flight Controller which used to come with a barometer but now doesn't and was unfortunately dropped as an INAV Target.

**Comment by mmosca** [comment]
New hardware is added according to INAV's new hardware policy. https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
