### ISSUE TITLE
Create SpeedyBee F405v4 Target with Support for SoftSerial (for use cases like SmartPort specifically).

### ISSUE THREAD

**Issue by Painless360** [iNavFlight/inav#9673]
On the existing Speedybee F405V4 flight controller, there isn't a way to use SmartPort for FrSky receivers with INAV. 

Using the resource mapping in Betaflight, it is possible to reassign the LED or CC pad for this function. See https://speedybee.zendesk.com/hc/en-us/articles/21197634652059-How-to-Use-SmartPort-Telemetry-Data-Transmission-on-F405v4-Flight-Controller for full details

Could a alternative target with this modification be created so that pilots using SmartPort can access the same telemetry as Betaflight on this flight controller? 

Thank you in advance for looking at this request. Happy flying!

**Comment by b14ckyy** [comment]
Hey Lee. That should work already. Based on the Target definitions, if you enable softserial support in the Configuration tab > Features, the Tx2 pad will become a bidirectional softserial pad. You can use that for smartport telemetry and even invert it if needed.
