### ISSUE TITLE
When using self-compile firmware, unable to save mixer.

### ISSUE THREAD

**Issue by yxc407** [iNavFlight/inav#9725]
I flash the firmware I compiled into the flight controller, everything is fine, except that I cannot modify and save the mixer section. I tested three flight controllers, even if my firmware is not modified, simply compiled and flash, it is the same.

**Comment by sensei-hacker** [comment]
Probably timer problems. Which target, and where are your changes?

**Comment by yxc407** [comment]
OK,let me check,thank you

**Comment by yxc407** [comment]
> Probably timer problems. Which target, and where are your changes?

I am attempting to make modifications from within the code.
<img width="497" alt="螢幕擷取畫面 2024-02-16 153609" src="https://github.com/iNavFlight/inav/assets/143247595/3d8528dc-b3da-4b83-ab76-3fcc2ff69752">

This is the result I obtained after flashing.
<img width="476" alt="螢幕擷取畫面 2024-02-16 153452" src="https://github.com/iNavFlight/inav/assets/143247595/84853915-630f-43e3-a775-aff532f6f1bf">
<img width="320" alt="image" src="https://github.com/iNavFlight/inav/assets/143247595/0cf7067f-6b13-4809-9526-a32b07d4ca11">

My flight controller is JHEMCUF405, the target is JHEMCUF405, only modifying the code in target.c.
IMU and Baro are both displaying and receiving data normally, only the mixer cannot be modified and saved.

**Comment by rizacelik** [comment]
Replace **TIM_USE_MOTOR** with **TIM_USE_OUTPUT_AUTO**

**Comment by yxc407** [comment]
> Replace **TIM_USE_MOTOR** with **TIM_USE_OUTPUT_AUTO**

Sorry, I didn't explain clearly. I didn't originally modify this part of the code. This is the result after my modification, which is the same as the result before the modification.

**Comment by sensei-hacker** [comment]
There is no command called "mixer", so that's why you're getting the error that's an unknown command.

There's mmix (motor mix) and smix (servo mix).

As Rizacelik said, that should generally be TIM_USE_OUTPUT_AUTO, whether you modified it or not.
