### ISSUE TITLE
SPEEDYBEE F405V3 stopped working with inav

### ISSUE THREAD

**Issue by vasilisaaue** [iNavFlight/inav#9747]
I flashed the flight controller via inav and everything became normal. For several days the drone just stood on the shelf, I decided to connect it to the inav, but it did not connect. opens a connection and closes after a few seconds. Reflashing and completely erasing the chip did not help. I even flashed the drone on Betaflight and it worked. after which I flashed the drone again in INAV, but it no longer works. Help me please! There is no SD card inserted into my flight controller!

P.S . The drone also stopped responding to commands when connecting equipment

**Comment by mmosca** [comment]
What version inav and configurator?

What operating system?

**Comment by vasilisaaue** [comment]
> What version inav and configurator?
> 
> 
> 
> What operating system?

Inav 7.00 . Windows 11.

**Comment by mmosca** [comment]
try disconnecting any devices on uart1 and 3 to see if it makes a difference
