### ISSUE TITLE
Separate failsafe scenarios for AUTO/NAV and MANUAL modes

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#977]
For better user-friendliness we need a smarter failsafe procedure that will act depending on current flight mode and flight conditions.

If UAV is flown manually - RTH (or land if no GPS is available)
If UAV is executing autonomous mission - continue mission

Voltage failsafe/geo-fencing can be part of this "smart" failsafe.

What do you think?

**Comment by stronnag** [comment]
I like this proposal. geo-fencing welcome. Note that there is extant MSP_(SET_)_NAVCONFIG  message permitting the setting / getting of (inter alia) geo-fence radius, however there may be too much legacy junk there and we'd be better to do our own control message.

**Comment by oleost** [comment]
"If UAV is executing autonomous mission - continue mission" is basically #770 

Please make it user configurable. Like for me personally I would never let the aircraft do WP mission by itself.

There are high risk running WP mission without TX control and this should be a conscious choice.

**Comment by digitalentity** [comment]
@oleost yes, it's #770. I just want this to be a more flexible failsafe mechanism. I might as well make a failsafe mode matrix (user-configurable) where you'll be able to chose different procedure for different flight mode.

**Comment by DzikuVx** [comment]
@digitalentity I think this should be closed now. Am I right?

**Comment by digitalentity** [comment]
@DzikuVx not yet. We still can't have one setup that will initiate failsafe RTH when flying manually and do nothing when on WP mission. I'll just reschedule it for 1.7 since most of the implementation is already there.

**Comment by oleost** [comment]
#1475
