### ISSUE TITLE
use takeoff heading as heading for landing.

### ISSUE THREAD

**Issue by P-I-Engineer** [iNavFlight/inav#9773]
## Current Behavior
I HAVE NOT TESTED THE NEW LAND, ONLY READ DOC.
plane attempts to determine wind direction and land into the wind.

## Desired Behavior
option to land using heading that plane took off from.

## Suggested Solution
record takeoff direction and use this for landing direction. 

## Who does this impact? Who is this for?
this is useful when flying from areas that coming in from other headings would lead to crashing.

## Additional context

thanks

**Comment by b14ckyy** [comment]
With the new Autoland you can define up to 4 safe approach directions for landing that can be flown precisely on a well tuned plane. 
Launch heading is not reliable enough, especially with no compass present or in crosswinds. That's no option.
