### ISSUE TITLE
iflight blitz atf435 flight controller

### ISSUE THREAD

**Issue by bwilliams1132** [iNavFlight/inav#9782]
inav wont read my accelerometer or gyro only barometer...everything works in betaflight..no issues

**Comment by KznProkuror** [comment]
Same problem, I went through everything in the sensors, it doesn’t want to find it(

**Comment by KznProkuror** [comment]
> inav wont read my accelerometer or gyro only barometer

Did you manage to solve the problem?

**Comment by bwilliams1132** [comment]
U got a way to fix it

**Comment by bwilliams1132** [comment]
No I was hoping you did

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Phil-MC** [comment]
The manufacturer might well have updated the chips on the board. It is only advertised for Betaflight so the INAV TARGET may well be out of date.

**Comment by Phil-MC** [comment]
The advertised components are
Gyro: BMI270
Barometer: DPS310
OSD Chip: AT7456E
Flash: 32MB (Blackbox flash)
UARTS: 6

**Comment by bwilliams1132** [comment]
Ok thanks for your help phil

**Comment by Phil-MC** [comment]
As far as I can see from the TARGET . h the basic drivers are all covered. 
With a number of users reporting the same problem, it is unlikely to be a faulty board.

It needs someone with Betaflight on the board to check their devices (resources?) and see if they have been altered.

**Comment by bwilliams1132** [comment]
I just got my stock betaflight cli dump....



Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Phil-MC** [comment]
I looked but couldn't find any reference to the IMU device in your dump.

**Comment by Phil-MC** [comment]
@mmosca Any ideas?

**Comment by KznProkuror** [comment]
> @mmoscaЕсть идеи?

My sensors are also not detected, how can I help? I'll give you all the information

**Comment by Phil-MC** [comment]
Thanks @mmosca for sorting it out.
