### ISSUE TITLE
Fixed wing failsafe landing

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#979]
Current "LAND" stage 2 is unusable for fixed wing. For FW we should set pre-defined roll/pitch/yaw/throttle, not only throttle.

**Comment by isilcala** [comment]
actually what I'm doing is on failsafe, override an aux channel to set the plane to horizon mode, then with a pre-set throttle it might be possible to land the plane. going to test it out if the weather allows in the coming days.
