### ISSUE TITLE
The vtx smart audio osd on Inav 7 is not the same as the one in the Rush tank solo user manual.

### ISSUE THREAD

**Issue by reaareoo** [iNavFlight/inav#9795]
Hello everyone,
I just installed rush tank solo on speedybee F7 v3 using Inav7.  after everything was on I started to open the osd via the radio transmitter then went into the vtx settings and apparently couldn't find the "config" menu.  can anyone help me, any help will be valuable to me.

**Comment by b14ckyy** [comment]
Is SmartAudio properly configured and you can control the VTX power, channel and band with the INAV confiscator settings?
