### ISSUE TITLE
bidirectional mavlink telemetry

### ISSUE THREAD

**Issue by anemostec** [iNavFlight/inav#980]
in order to be able to use other gcs such as tower or mission planner I propose to add the mavlink bidirectional link support to inav.
In order to do that, we will fetch the relatvie code from ardupilot and bring it to inav. Will that be of any interest?
what pitfalls do you see in this dev approach?

**Comment by oleost** [comment]
How would this cooperate with MSP?

And is there wiser to have an layer translating mavlink to MSP somehow ?

**Comment by anemostec** [comment]
the input mavlink telemetry will be used mainly for navigation purpose, thus those input messages will call the exact same navigation function as the MSP messages. MSP is just a layer in between, I don't see the benefit to call them rather than the final destination functions

**Comment by stronnag** [comment]
I think there is a danger it would make the message parsing layer much more fragile than it is now. As Tower is open source, why not fix it it allow unsolicited telemetry rather than adding complexity to iNav?

Or just use ezgui?

**Comment by anemostec** [comment]
tower and mission planner are working actually with inav
the waypoints support, flight mode changing is not since the inav mavlink telemetry is just an output one, no input supported yet

**Comment by digitalentity** [comment]
Flight mode changing won't be possible as it's only driven by RC RX driver. Uploading a mission via MAVLink would be nice - you are welcome to submit a PR for bi-directional telemetry.

**Comment by anemostec** [comment]
ok for the bi-directional telemetry, but I still don't understand why we 
could not call the function used by the RC RX driver to change the 
flight mode

**Comment by digitalentity** [comment]
Because next update from RC RX will change flight mode back according to transmitter switches.

**Comment by anemostec** [comment]
oh ok, got you

but we could put a global variable to tell RC RX to not change flight 
mode back if flight mode was already changed by telemetry unless the 
user willingly change the RC RX switch position

**Comment by magictex** [comment]
Is someone working on this issue ?
Simple question because I'm also interested and can maybe help to port Mavlink incoming messages to iNav.
Thanks

**Comment by martinbudden** [comment]
@magictex , no one is actively working on this at the moment. But if you wish to submit a PR it would be most welcome.

**Comment by magictex** [comment]
@martinbudden Thanks for the answer. Will check with a friend of mine and work on it then.

**Comment by digitalentity** [comment]
@magictex I have this issue in my schedule after merging in some sonar-related code.

**Comment by magictex** [comment]
@digitalentity Thanks for the info. Will be glad to test it when you'll release it ! :-)

**Comment by digitalentity** [comment]
Closing - let's continue in relevant PR #1461
