### ISSUE TITLE
Enable 3D Speed in BB decoder

### ISSUE THREAD

**Issue by redjetvark** [iNavFlight/inav#9800]
## Current Behavior
Ground speed in various units, alt in cm

## Desired Behavior
3D Speed is several units

## Suggested Solution
Coded into inav BB decoder

## Who does this impact? Who is this for?
All

**Comment by b14ckyy** [comment]
Has nothing to do with the firmware. Please post requests regarding blackbox decode in the corresponding repo: 
https://github.com/iNavFlight/blackbox-tools
