### ISSUE TITLE
Русификатор конфигуратора

### ISSUE THREAD

**Issue by techenging** [iNavFlight/inav#9802]
Файл русификации конфигуратора
Для русификации INAV - Конфигуратор: откройте папку "_locales" в скачанном каталоге конфигуратора, создайте в этой папке папку "ru" и сохраните скачанный здесь файл messages.json в этой папке. При запуске конфигуратор самостоятельно запустит русскую версию при условии, что язык системы русский.
[messages.json](https://github.com/iNavFlight/inav/files/14629779/messages.json)

**Comment by S1mdar** [comment]
на 9 версию работает ?

**Comment by techenging** [comment]
> на 9 версии работает ?

Без понятия, я и на 8й не проверял
