### ISSUE TITLE
BLHeli will not connect ESC when iNAV feature "Reversible motors" is enabled

### ISSUE THREAD

**Issue by NorthIceMan** [iNavFlight/inav#9810]
## Summary:
When "Reversible motors mode (for use with reversible ESCs)" is enabled (slider to right) - BLHeli will not connect to ESC and gives the error "initialization of flight controller denied  Please check all motors are stopped"

This Reversible motors mode is enabled in iNAV 7.0 in Configuration tab under "Other Features".  When this feature is disabled BLHeli will then connect ok.

The same error message was a problem with iNAV ver 2.2

## Current Behavior
BLHeli will not connect ESC (Holybro_Tekko32_F4_45A)

## Steps to Reproduce

1. Connect FC to computer
2. Run BLHeli Suite32
3. Try "Connect" in BLHeli configurator

## Expected behavior
BLHeli should connect ESC (Holybro_Tekko32_F4_45A) with Reversible motors enabled
## Suggested solution(s)
?Fix incompatibility of Reversible motors and BLHeli ESC communications in iNAV 7.0 ?

## Additional context
BLHeli will connect OK if Reversible motors is not enabled
---

# version
# INAV/SPEEDYBEEF405WING 7.0.0 Jan 26 2024 / 18:42:39 (118cd485)
# GCC-10.3.1 20210824 (release)
Note: this is the PINIO flash-ware

- FC Board name and vendor:
F405 Wing Mini Easy Fly  by SpeedyBee

**Comment by Helipro** [comment]
@NorthIceMan Dshot reversible motors works great for me, using the newest INAV.  I can access the bl-heli suites just fine through USB>Inav>dual ESC's.  I just set 2 up on F765.  I used the last official bl-heli release, not the beta release.  After selecting Bi directional reversible ESC I was still able to go back in and change the motor direction and beeper volume with no problem.
