### ISSUE TITLE
Tmotorf7v2 has no accelerometer ICM42688 as an option

### ISSUE THREAD

**Issue by Delvien** [iNavFlight/inav#9816]
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [INAV Discord Server](https://discord.gg/peg2hhbYwN)
* [INAV Official on Facebook](https://www.facebook.com/groups/INAVOfficial)
* [INAV Official on Telegram](https://t.me/INAVFlight)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Steps to Reproduce

1. Flash current inav 7.0 target TMOTORF7v2 

## Expected behavior
Ability to select ICM42688  gyro

## Suggested solution(s)
Add driver for ICM42688 

## Additional context

INAV/TMOTORF7V2 7.0.0 DEC 5 2023 / 11:12:23 (895a4f31)
GCC-10.3.1 202210824 (release)

- FC Board name and vendor:T-motor F7 pro https://pyrodrone.com/products/t-motor-f7-pro-flight-controller-30x30mm
- INAV version string: 7.0.0

**Comment by b14ckyy** [comment]
Not a bug. Use the ICM42605. They use the exact same driver and is also auto-selected when switching to auto. This is normal. 

![image](https://github.com/iNavFlight/inav/assets/33039058/b60e344a-cf9a-412b-9e0a-a672fec022a5)

**Comment by Delvien** [comment]
AUTO does not automatically select ICM42605. When selecting ICM42605 it also does not work. 


<img width="1141" alt="image" src="https://github.com/iNavFlight/inav/assets/4016679/34dabd60-c055-4502-b4b1-1083be62caa7">

<img width="486" alt="image" src="https://github.com/iNavFlight/inav/assets/4016679/5ea83289-5053-4779-bba6-196a59792403">


Gyro in Betaflight works.

**Comment by mmosca** [comment]
@b14ckyy I think gyro is missing from the target, probably because the manufacturer changed the board at some point due to availability.

**Comment by Delvien** [comment]
> @b14ckyy I think gyro is missing from the target, probably because the manufacturer changed the board at some point due to availability.

I confirmed your build here: https://discord.com/channels/791437907478577172/881440703811559435/1220322311937327164

made gyro function.

**Comment by b14ckyy** [comment]
Thx @mmosca 
these constant revision changes of some manufacturers are really a pain in the A
