### ISSUE TITLE
Make "Heading Hold" work with rudderless airplanes / fixedwing

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#982]
Make "Heading Hold" work with rudderless airplanes / fixedwing

**Comment by digitalentity** [comment]
Putting this into 1.7 milestone. Not sure we can create something working in 1.6

**Comment by marbalon** [comment]
I think it is quite easy, just like someone told before, set the WP far away using current bearing. Maybe we can put this in 1.6 ? ;-) After this week I will try to focus on testing 1.6 on wing so can test this too. It is really useful feature for planes.

**Comment by digitalentity** [comment]
Yes, it's a useful feature, but we have a handful of features in 1.6 already. If we won't do feature freze we'll never release it :smile:

**Comment by digitalentity** [comment]
Oops, totally forgot about this. Will have to move to 1.8
