### ISSUE TITLE
MAMBAF722_2022B ... DJI O3 AU not recognised

### ISSUE THREAD

**Issue by dugdiamond-git** [iNavFlight/inav#9825]
## Steps to Reproduce

1. Flash with ANY inav version (i have tried upto and including 7.1.0RC1).
2. Attach O3 AU to flight stack (correctly with battery providing power to quad)
3. No power given to AU ??? (not red or green light on AU)
4. 'BF4.5' flashed (same target 'equivalent')..... O3 AU gets power, and binds/works as expected !!!!!

---
diff all

# version
# INAV/MAMBAF722_2022B 7.1.0 Feb 14 2024 / 15:12:29 (49325426)
# GCC-10.3.1 20210824 (release)

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# Timer overrides

# Outputs [servo]

# safehome

# Fixed Wing Approach

# features
feature GPS
feature PWM_OUTPUT_ENABLE

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS
blackbox -GYRO_RAW
blackbox -PEAKS_R
blackbox -PEAKS_P
blackbox -PEAKS_Y

# Receiver: Channel map

# Ports
serial 2 33554432 115200 115200 0 115200
serial 3 0 115200 115200 0 115200
serial 4 2 115200 115200 0 115200

# LEDs

# LED color

# LED mode_color

# Modes [aux]
aux 0 0 0 1700 2100
aux 1 1 1 900 1300
aux 2 2 1 1300 1700
aux 3 53 4 1700 2100
aux 4 11 3 1700 2100
aux 5 10 5 1700 2100
aux 6 13 2 1700 2100

# Adjustments [adjrange]

# Receiver rxrange

# temp_sensor

# Mission Control Waypoints [wp]
#wp 0 invalid

# OSD [osd_layout]
osd_layout 0 0 48 1 V
osd_layout 0 1 8 3 V
osd_layout 0 2 0 0 V
osd_layout 0 3 8 6 V
osd_layout 0 4 8 6 V
osd_layout 0 5 45 9 V
osd_layout 0 6 45 10 V
osd_layout 0 7 29 16 V
osd_layout 0 9 28 15 V
osd_layout 0 14 38 1 V
osd_layout 0 15 7 9 V
osd_layout 0 22 20 1 V
osd_layout 0 23 28 2 V
osd_layout 0 28 23 11 H
osd_layout 0 30 17 17 V
osd_layout 0 32 8 5 V
osd_layout 0 34 25 1 V
osd_layout 0 38 8 2 V
osd_layout 0 85 8 12 V
osd_layout 0 110 47 2 V
osd_layout 0 112 46 3 V
osd_layout 0 120 8 11 V
osd_layout 0 123 8 6 V

# Programming: logic

# Programming: global variables

# Programming: PID controllers

# OSD: custom elements

# master
set looptime = 500
set gyro_main_lpf_hz = 90
set gyro_main_lpf_type = PT1
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 60
set dynamic_gyro_notch_mode = 3D
set setpoint_kalman_q = 200
set gyro_zero_x = 15
set gyro_zero_y = -10
set ins_gravity_cmss =  983.126
set acc_hardware = ICM42605
set acczero_x = 20
set acczero_y = -12
set acczero_z = 7
set accgain_x = 4145
set accgain_y = 4090
set accgain_z = 4097
set align_mag = CW270FLIP
set mag_hardware = QMC5883
set magzero_x = -819
set magzero_y = 473
set magzero_z = 160
set maggain_x = 1157
set maggain_y = 370
set maggain_z = 1525
set align_mag_pitch = 1800
set align_mag_yaw = -900
set baro_hardware = SPL06
set receiver_type = SERIAL
set rc_filter_smoothing_factor = 40
set serialrx_provider = CRSF
set blackbox_rate_denom = 2
set motor_pwm_protocol = DSHOT300
set failsafe_procedure = RTH
set align_board_yaw = 1800
set applied_defaults = 5
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set deadband = 2
set yaw_deadband = 2
set airmode_type = THROTTLE_THRESHOLD
set osd_video_system = DJIWTF
set osd_switch_indicators_align_left = OFF

# mixer_profile
mixer_profile 1

set model_preview_type = 3

# Mixer: motor mixer

mmix reset

mmix 0  1.000 -1.000 -1.000  1.000
mmix 1  1.000 -1.000  1.000 -1.000
mmix 2  1.000  1.000 -1.000 -1.000
mmix 3  1.000  1.000  1.000  1.000

# Mixer: servo mixer

# mixer_profile
mixer_profile 2

# Mixer: motor mixer

# Mixer: servo mixer

# profile
profile 1

set mc_p_pitch = 44
set mc_i_pitch = 85
set mc_d_pitch = 28
set mc_i_roll = 75
set mc_d_roll = 26
set mc_p_yaw = 40
set mc_i_yaw = 80
set max_angle_inclination_rll = 450
set max_angle_inclination_pit = 450
set dterm_lpf_hz = 80
set dterm_lpf_type = PT3
set mc_iterm_relax = RPY
set d_boost_min =  0.800
set d_boost_max =  1.200
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set smith_predictor_delay =  1.500
set tpa_rate = 20
set tpa_breakpoint = 1200
set rc_expo = 75
set rc_yaw_expo = 75
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

set vbat_min_cell_voltage = 300

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
mixer_profile 1
profile 1
battery_profile 1

# save configuration
save

#

**Comment by b14ckyy** [comment]
INAV has nothing to do with power delivery to the Air Unit (unless the FC has a VTX power switch and you set the Usermode to be OFF). 
Just checked the Documentation. It has a power switch for the VTX that needs to be configured: 
![image](https://github.com/iNavFlight/inav/assets/33039058/1a8eaca5-b19f-449a-b1f6-640df0ce0c03)

https://www.diatone.us/products/mb-mk4-f722-app-fc
This is 100% your issue.
