### ISSUE TITLE
SBUS on PPM pin?

### ISSUE THREAD

**Issue by night-ghost** [iNavFlight/inav#984]
Does INAV supports SBUS on PPM pin? If no I just finished debugging of universal PPM/SBUS/DSM input driver by timer compare channel.

**Comment by rolfz** [comment]
Same question, other way around, does inav support PPM on the SBUS pin ? or what pin does it work on? I have a nice old Quanton board ! According to the code, PPM is working on PWMIN 1 is that correct ? Currently only SBUS works on RX2 on my board !

**Comment by DzikuVx** [comment]
I'm closing this since there are only limited cases where it can work, inlcuding inverters. Thanks
