### ISSUE TITLE
Can't change altitude in Mission control

### ISSUE THREAD

**Issue by Vins1417** [iNavFlight/inav#9850]
## Current Behavior
Altitude cannot be changed if Sea level Ref is checked. When you enter a value higher than that indicated by default, the following message appears.

![image_2024-03-24_164206812](https://github.com/iNavFlight/inav/assets/148378237/b16464db-a66f-4545-ada3-eb0b3b121f2b)

## Steps to Reproduce
Go to Mission Control tab
Add a point
In the point settings, check Sea Level Ref and then increase the Alt value

## Expected behavior
A calculation of the correct elevation...

- FC Board name and vendor: SpeedyBee F405 Mini
- INAV version string: 
# version
# INAV/SPEEDYBEEF405MINI 7.1.0 Feb 14 2024 / 15:55:53 (49325426)
# GCC-10.3.1 20210824 (release)

**Comment by breadoven** [comment]
This is a Configurator issue already covered by https://github.com/iNavFlight/inav-configurator/issues/1987. Should be fixed now.

**Comment by Vins1417** [comment]
I reinstalled the 7.1.0 RC1 configurator and it doesn't work..

**Comment by breadoven** [comment]
The fix isn't included in RC1. It'll be included in the next release of Configurator.
