### ISSUE TITLE
inav outputs ESC always reverts to MULTISHOT ESC protocol selection when using bluejay ESC Firmware

### ISSUE THREAD

**Issue by guerradr** [iNavFlight/inav#9872]
## Current Behavior
When selecting a different ESC protocol on the Outputs  Tab of the INAV Configurator ans Press Save and Reboot, after reboot there is always MULTISHOT selected. Using Bluejay Firmware v0.19.0 and bl_heli_S with same result.

## Steps to Reproduce
1. Select Outputs Tab and Choose different ESC protocol
2. Save and Reboot
3. Choose Outputs Tab -> after loading the config MULTISHOT is set as ESC protocol
4. Additionally when using CLI to change motor_pwm_protocol it reverts after reboot as well to the MULTISHOT protocol

```
# get motor_pwm_protocol 
motor_pwm_protocol = MULTISHOT
Allowed values: STANDARD, ONESHOT125, MULTISHOT, BRUSHED, DSHOT150, DSHOT300, DSHOT600


# set motor_pwm_protocol = DSHOT300
motor_pwm_protocol set to DSHOT300
# get motor_pwm_protocol 
motor_pwm_protocol = DSHOT300
Allowed values: STANDARD, ONESHOT125, MULTISHOT, BRUSHED, DSHOT150, DSHOT300, DSHOT600
``` 

## Expected behavior
Selected ESC protocol should remain after reboot.

## Suggested solution(s)
Bug Fix

## Additional context
![Screenshot 2024-03-29 174556](https://github.com/iNavFlight/inav/assets/20811561/275567ee-dc86-4926-a268-ae086a10c3cd)

---

- FC Board name and vendor: INAV/BEEROTORF4 7.0.0 Dec  5 2023 / 09:37:23 (895a4f31)
- INAV version string: GCC-10.3.1 20210824 (release)

**Comment by stronnag** [comment]
This is expected behaviour for boards that do not support DSHOT
