### ISSUE TITLE
INAV Black box not working - Matek H743 slim V3 #9540

### ISSUE THREAD

**Issue by Hex-Davis** [iNavFlight/inav#9876]
I'm having an issue with the black box in INAV failing to crate a useable flight log or not creating one at all.

The Black box logging is set for on-board SD card slot, the SD card is a 32G formatted fat32 in 32Kbs it has been checked via H2testw and came back with a wright of ~25Mbs/s without any errors. I did try a 4G card that had 10Mbs/s but this appeared to have no positive impact. Looking around i found suggestions about the 'logging rate' and the 'loop time', ultimately suggesting a lower collection rate of ~10-20Hz. I've changed these two values around a few times for higher and lower collection rates to no avail. I have the black box mode activate off the same channel as the mode Arm so it starts logging when Armed and stops when disarmed but all I'm getting is unreliable/unusable data, if any data is collected at all.

This is a Reopening of this ticket (#9540) as the issues was never solved. After it was marked as closed i decided to just wait to see if an up-date would come out to fix the issue. I'm now using INAV 7 and black box 7.0.0 but the problem is still there. This issue continues to persist. Attached is a file recorded 50% loop time (1/2),cycle time was 2500. this recording should be roughly 80sec long but is <2sec long. it appears to be the first 2sec of the flight.
something maybe related is when looking at the available data in the black box analyzer the X-axis values for frequency are "infinity Hz"??
[LOG00001.TXT](https://github.com/iNavFlight/inav/files/14809290/LOG00001.TXT)

any recommendations or assistance would be greatly appreciated, Thank you.

**Comment by Hex-Davis** [comment]
Here are 4 more flights with greater than 2min of flight time each.

[LOG00002.TXT](https://github.com/iNavFlight/inav/files/14813523/LOG00002.TXT)
[LOG00001.TXT](https://github.com/iNavFlight/inav/files/14813525/LOG00001.TXT)
[LOG00003.TXT](https://github.com/iNavFlight/inav/files/14813522/LOG00003.TXT)
[LOG00004.TXT](https://github.com/iNavFlight/inav/files/14813521/LOG00004.TXT)

**Comment by b14ckyy** [comment]
Hi Hex. 
this is a known issue with logging right now. Especially the H7 is a bit troublesome. If I remember correctly, with F765 for example the fastest stable logging rate I was able to achieve was 500Hz. With H7 and F4 as well as F722 everything above 250Hz can cause issues. 

you can reduce the logging fields by disabling some you don't need to allow higher rates but for now it is how it is until a better SD driver implementation can be found. 

If you wanna do noise analysis, you can disable most fields except gyro and accellerometer data and it should be easy to run 1000Hz (actually overkill already). For pure flight recording I have my logs running at 30Hz on all my fixed wing craft.

**Comment by Hex-Davis** [comment]
I will give this a shot! Thank you very much i have been beating my head against this so long now.
