### ISSUE TITLE
Aileron Selection

### ISSUE THREAD

**Issue by Sotm12** [iNavFlight/inav#9888]
## Current Behavior
Inav Wing when you select Airplane With Tail assigns 2 aileron Servo assignment with no option to only have 1 aileron output. 
## Desired Behavior
Inav Wing when you select Airplane With Tail assigns 2 aileron Servo output  with no option to only have 1 aileron output. Need to be able to select only 1 Aileron output so that you add someother function to an additional output!! 
## Suggested Solution
Re-program the firmware so that either 1 or 2 aileron outputs may be selected. there by allowing one additional other output servo to be used. This has been wanted since early versions of Inav, why hasn't this changed? 

## Who does this impact? Who is this for?
Who is this for?  All Fixed Airplane users, not everyone flys with "Dual" ailerons. Most use 1 channel and a "Y" harness for their ailerons!!! This would allow an additional numbered servo for other assignment!!!

**Comment by Sotm12** [comment]
You cannot select only one aileron!!!!!!!!!!!!!!!!!!!!!!!!!!

Duh!!!

**Comment by sensei-hacker** [comment]
Seriously, try actually clicking where I have marked.
Either the red or the blue.  Try it.  See what happens when you click the button marked in green.
It works way better than yelling "duh!!"

Also, please consider whether you want assistance, or you want any future messages from you to be immediately deleted.  You can choose which happens by how you choose to respond.

**Comment by MrD-RC** [comment]
> You cannot select only one aileron!!!!!!!!!!!!!!!!!!!!!!!!!! Duh!!! 

There is no need to be rude to people who are trying to help you! If you do what @sensei-hacker said. You would have what you want.

**Comment by Sotm12** [comment]
My Bad.
It did not accept a different receiver input when originally tried. I.e. I wanted to assign RC Channel 10 to it for a nose wheel steering mix. After I have re-booted everything, Inav, transmitter, model selection on transmitter, receiver, it will now accept the channel selection. Thank you for your help. I’ll close the matter.\0/

Duane

**Comment by Sotm12** [comment]
NOT BEING RUDE _ _VERY FRUSTRATED!!!!!!!!!!!!!!

**Comment by Sotm12** [comment]
What ever, guess you have never been frustrated Huh?

**Comment by DzikuVx** [comment]
Adults should control their emotions and act accordingly to the situation. Your reaction was an example of lack of emotion control. For the future: please learn how to control your emotions and act as a grown up adult human being. Thank you
