### ISSUE TITLE
RX_Parallel_PWM AETR1234 Channel Map Broken in 1.5RC3 for Naze

### ISSUE THREAD

**Issue by dbechth** [iNavFlight/inav#989]
The channel mapping appears to be broken in 1.5RC3 for the Naze hardware. Flashing 1.5RC3 with full chip erase and then setting receiver mode to RX_Parallel_PWM causes ThrottleStick to come in as Aux1, YawStick comes in as Aux2, Aux1Switch to come in as Aux3, and Aux2Switch to come in as Aux4. RollStick and PitchStick do not seem to come in anywhere. I have switched back to 1.4 stable as a sanity check and confirmed that everything is working as expected.  For further investigation I can confirm that 1.5RC1 has the same behavior as RC3.

**Comment by digitalentity** [comment]
Please upload the full dump of your configuration. Also please provide information about what board are you using exactly - there are several variants of NAZE boards.

**Comment by digitalentity** [comment]
Also, please test if the issue is solved in this hex.
[inav_1.5.0_NAZE.hex.gz](https://github.com/iNavFlight/inav/files/676581/inav_1.5.0_NAZE.hex.gz)

**Comment by dbechth** [comment]
The board is a NAZE32 Rev6. See full 1.4 dump below. I have tried loading this to 1.5RC3 with the result described above. I will try the .hex you suggested and report back.
[inavv1.4 12-28-2016.txt](https://github.com/iNavFlight/inav/files/676592/inavv1.4.12-28-2016.txt)

**Comment by dbechth** [comment]
I loaded the .hex and my cli dump and everything looks as expected. Its too dark to fly right now but ill try to fly tomorrow after work. Thanks for the ultra fast response! Please let me know if there is anything else I can test.

**Comment by digitalentity** [comment]
Great, thanks for testing!

**Comment by digitalentity** [comment]
Fixed
