### ISSUE TITLE
Arteficial horizon not showing up in osd

### ISSUE THREAD

**Issue by udum6** [iNavFlight/inav#9906]
Hi, I have a problem with my inav plane. The problem is that my artificial horizon isn't showing up eaven after flashing the Flight controller. The rest of the osd works except from the artificial horizon. The fc is matek f405 wing v2. Thanks for  help.

**Comment by MrD-RC** [comment]
What video system?

If analogue, did you upload the font to the flight controller?

**Comment by udum6** [comment]
Yes system is analougue but what do you mean upload the font to the flight controller. Like upload the alingment of the board to the fc

**Comment by MrD-RC** [comment]
On the OSD page. At the bottom there is the font upload options. It needs to be installed on the OSD chip. You should do this whenever you update.

**Comment by udum6** [comment]
Thank you so much it works. You got yourself a subscriber.
