### ISSUE TITLE
Run-time compass check

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#991]
I figure failing compass is one most common cause of fly-aways. We need to implement run-time checking that compass is alive and kicking and treat compass loss the same way we do with GPS loss.

Also, compass failure in PosHold while GPS is still working good may result in FlyAway as PosHold controller doesn't protect itself against incorrect heading.

**Comment by martinbudden** [comment]
That sounds a good plan.

**Comment by digitalentity** [comment]
I figure this will have to wait for 1.7. Too invasive change.
