### ISSUE TITLE
Wiki::Telemetry::LTM::Tuning_frame format broken

### ISSUE THREAD

**Issue by inobelar** [iNavFlight/inav#9914]
Accordingly to project Wiki, [format of Tuning frame](https://github.com/iNavFlight/inav/wiki/Lightweight-Telemetry-(LTM)#tuning-frame-t) seems broken:

> The payload is 12 bytes. This frame is not transmitted by INAV telemetry.
>
> | Data | Format |
> | ---- | ---- |
> | P-roll | uint8 |
> | I-roll | uint8 |
> | D-roll | uint8 |
> | P-pitch | uint8 |
> | P-pitch | uint8 |
> | I-pitch | uint8 |
> | D-yaw | uint8 |
> | I-yaw | uint8 |
> | rates-roll | uint8 |
> | rates-pitch | uint8 |
> | rates-yaw | uint8 |

First of all, table contains `11` bytes (not `12`), and `P-pitch` described **twice**. It seems like here is must be data from PID-regulator, so maybe it must be the next: P/I/D-roll, P/I/D-pitch, P/I/D-yaw, rates-roll/pitch/yaw ?

| Data | Format |
| ---- | ---- |
| P-roll | uint8 |
| I-roll | uint8 |
| D-roll | uint8 |
| P-pitch | uint8 |
| I-pitch | uint8 |
| D-pitch | uint8 |
| P-yaw | uint8 |
| I-yaw | uint8 |
| D-yaw | uint8 |
| rates-roll | uint8 |
| rates-pitch | uint8 |
| rates-yaw | uint8 |

**Comment by stronnag** [comment]
Anyone can edit the wiki .....
No need for an issue.
