### ISSUE TITLE
FW - Auto Launch - linear throttle ramp up

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav#992]
Linear throttle ramp up for fixedwing auto launch mode to prevent ESC from getting out of sync if using with feature "Motor Stop"
~This feature is already implemented in other nav modes.~
As discussed in forum, 100ms ramp up should be enough.

**Comment by digitalentity** [comment]
Just to clarify - this feature is NOT implemented anywhere in the code. Other NAV modes apply LPF to throttle to smooth the possible rapid changes.

**Comment by digitalentity** [comment]
I'm scheduling this to 1.6 - it's a good thing to have.

**Comment by gregorg** [comment]
Also, this feature could help to limit twists due to too many prop torque at launch.
