### ISSUE TITLE
multiple include file

### ISSUE THREAD

**Issue by rizacelik** [iNavFlight/inav#9932]
This is not a bug but it is a situation where more than one file is included. It's probably been there for a long time.

#include "drivers/pwm_output.h"
#include "drivers/pwm_output.h"

https://github.com/iNavFlight/inav/blob/master/src/main/fc/fc_init.c#L62

**Comment by breadoven** [comment]
Fixed by https://github.com/iNavFlight/inav/pull/9940/files.
