### ISSUE TITLE
When I use angle mode during idle, the PID doesn't work

### ISSUE THREAD

**Issue by yxc407** [iNavFlight/inav#9938]
Why when I use angle mode during idle, the PID doesn't work and I can't use pitch, roll, and yaw for control? But when I use althold mode during idle, the PID does work?I use multicopter.

**Comment by b14ckyy** [comment]
Enable AIRMODE. that's exactly for that. 
![image](https://github.com/iNavFlight/inav/assets/33039058/68ce50cd-ca81-481c-96f5-da120000e813)

**Comment by yxc407** [comment]
> Enable AIRMODE. that's exactly for that. ![image](https://private-user-images.githubusercontent.com/33039058/321940383-68ce50cd-ca81-481c-96f5-da120000e813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTYwMzgsIm5iZiI6MTcxMjkxNTczOCwicGF0aCI6Ii8zMzAzOTA1OC8zMjE5NDAzODMtNjhjZTUwY2QtY2E4MS00ODFjLTk2ZjUtZGExMjAwMDBlODEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA5NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWM3NjIxMDhjZjllNDg0ZjliYzEyNTdmMzJjZWFlNDk5ODNiNzg4OWI2NTE1YmUzZDllMDk5NjkxN2ViZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqzzokj0Wm3l_pWCo7lgBrm92ZfkfCAIuwA4NEYXPkQ)

However, after enabling AIRMODE, even in angle mode at idle, there is still no PID correction and it cannot be controlled.

**Comment by yxc407** [comment]
> Enable AIRMODE. that's exactly for that. ![image](https://private-user-images.githubusercontent.com/33039058/321940383-68ce50cd-ca81-481c-96f5-da120000e813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTYwMzgsIm5iZiI6MTcxMjkxNTczOCwicGF0aCI6Ii8zMzAzOTA1OC8zMjE5NDAzODMtNjhjZTUwY2QtY2E4MS00ODFjLTk2ZjUtZGExMjAwMDBlODEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA5NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWM3NjIxMDhjZjllNDg0ZjliYzEyNTdmMzJjZWFlNDk5ODNiNzg4OWI2NTE1YmUzZDllMDk5NjkxN2ViZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqzzokj0Wm3l_pWCo7lgBrm92ZfkfCAIuwA4NEYXPkQ)

This is in angle mode during idle.
<img width="802" alt="螢幕擷取畫面 2024-04-12 180135" src="https://github.com/iNavFlight/inav/assets/143247595/dcca2ca2-f500-4931-9e5b-f27015fa8212">

This is in althold mode during idle.
<img width="914" alt="螢幕擷取畫面 2024-04-12 180200" src="https://github.com/iNavFlight/inav/assets/143247595/21bdb733-24c4-421e-8b2e-584946efcd50">

**Comment by b14ckyy** [comment]
Can you post a video please? What do you mean with IDLE? whent he quad is on the ground sitting the PID controls are supposed to be offline with no throttle. Airmode only kicks in when you throttle up to lift off. This is to prevent a freakout of the quad.

**Comment by yxc407** [comment]
> Can you post a video please? What do you mean with IDLE? whent he quad is on the ground sitting the PID controls are supposed to be offline with no throttle. Airmode only kicks in when you throttle up to lift off. This is to prevent a freakout of the quad.

This is angle mode, motors idle power.
https://github.com/iNavFlight/inav/assets/143247595/c29026e7-1315-4ea5-93f4-699b78d0eb00
This is althold mode, motors idle power.
https://github.com/iNavFlight/inav/assets/143247595/637abc1f-4cce-4e61-bedb-1144e36dae20

**Comment by yxc407** [comment]
> Can you post a video please? What do you mean with IDLE? whent he quad is on the ground sitting the PID controls are supposed to be offline with no throttle. Airmode only kicks in when you throttle up to lift off. This is to prevent a freakout of the quad.

I hope that for quadcopters, during the angle mode when the motors are idling, it can still allow control input and have the PIDs active, similar to how the althold mode works in inav. By idling, I mean when the throttle stick on the radio transmitter is at its lowest position after arming.

**Comment by DzikuVx** [comment]
To unlock control THROTTLE has to be raised at least once above 20% mark. This is safety measurement to prevent windup before takeoff

**Comment by yxc407** [comment]
> To unlock control THROTTLE has to be raised at least once above 20% mark. This is safety measurement to prevent windup before takeoff

Lastly, I'd like to ask, if I want to modify it to be like Betaflight where I can control the throttle below 20%, I would need to modify the code instead of adjusting the parameters?
