### ISSUE TITLE
MATEK F405 WING V2 - Firmware Issue (INav 6.0 and up)

### ISSUE THREAD

**Issue by QuocSiPHU** [iNavFlight/inav#9960]
## Steps to Reproduce

1. Open Inave 7.1, Plug in the FC in DFU mode (with the boot button)
2. Select Target MATEKF405SE (specified on the FC)
3. Load the firmware Online
4. Flash successfully, wait until led stop blinking, unplug the usb cable
5. Restart Inav, plug on the USB cable, click Connect (with the right port)
6. Inav open the serial port and after 10 sec, close the connection (communication failed)

## Expected behavior
Be able to connect to the board and setup the FC like another one.

## Suggested solution(s)
Fix the MATEKF405SE firmware for MATEKSYS F405 WING V2

## Additional context
The F405 Wing V2 got new sensors (ICM42688 and DSP310)
Apparently they are not recognized in either MATEKF405SE 6.0 nor 7.0
I've tried flashing with  MATEKF405 TE 6.0 and 7.0 as recommended on Mateksys website, however I still can't get connected

No dump available while I can't connect to the FC
---

- FC Board name and vendor: MATEKSYS F405 WING V2
- INAV version string: 7.0.0 MATEKF405SE - 2023-12-6 16:32 (stable)

**Comment by sensei-hacker** [comment]
Is anything connected to the board, especially to uart 1 or UART 3?

**Comment by QuocSiPHU** [comment]
Just only the board itself (No receiver, no servo, no GPS)
I've tried flashing with Betaflight (firmware 4.3.2 November 2021), got the connection, got the gyro and Baro working.
I connected my ELRS receiver and got channels responses on screen.
However no motor nor servo is working until now.

**Comment by b14ckyy** [comment]
Did you enable full chip erase?
Can you please test if the same happens with inav 7.0 build from matek itself?

https://www.mateksys.com/?p=5159#tab-id-3

**Comment by QuocSiPHU** [comment]
Hi b14ckyy,
Each flashing, I always do a full erase.
I just flash with link you provided (build 7.0 from Mateksys), and fortunately it work.
I can connect from Inav. I continue checking all the functions and will keep you aware.
Thanks

**Comment by b14ckyy** [comment]
Can you please provide a detailed picture of the FC itself? 
Its a bit weird as the MATEKF405SE Target has not been changed over the last 5 Months and I am sure I have seen people using this FC with official INAV builds. 
@MATEKSYS has anything been changed on later revisions of this board?

**Comment by QuocSiPHU** [comment]
> Did you enable full chip erase? Can you please test if the same happens with inav 7.0 build from matek itself?
> 
> https://www.mateksys.com/?p=5159#tab-id-3

Working hardware: Elrs Receiver, Servos, Led

not yet tested : Motor (have to be Ok)

not yet working :
GPS on UART4 (indoor testing, not getting satellites)
Buzzer (well wired) not getting any sound

**Comment by QuocSiPHU** [comment]
> Can you please provide a detailed picture of the FC itself? Its a bit weird as the MATEKF405SE Target has not been changed over the last 5 Months and I am sure I have seen people using this FC with official INAV builds. @MATEKSYS has anything been changed on later revisions of this board?

![z5363208925480_10056d83b549805aa6cf20257c70598a](https://github.com/iNavFlight/inav/assets/94967058/6ce32630-0848-44a4-b08e-48d419e6fb3f)

**Comment by QuocSiPHU** [comment]
I try powering the FC with rcv + servo + led (no USB to INAV)
The FC doesn't react to movement and the led is off (battery status)
The FC seems hanging!

**Comment by b14ckyy** [comment]
Please also with the cover removed. 
Sorry for the extra effort but we would like to check if something is off with the used components.

**Comment by QuocSiPHU** [comment]
![z5363341840567_e14998edfadb54c2b0b6b0f3c6adfeac](https://github.com/iNavFlight/inav/assets/94967058/7f84bdd1-5f55-4e1b-9a6f-2e0ccc9373ab)
![z5363341845335_24a92381ee8b96501e55bed8f7c896f6](https://github.com/iNavFlight/inav/assets/94967058/370b3fb0-2a53-42b6-9f92-6066fa755e17)

**Comment by QuocSiPHU** [comment]
I try to reflash twice but can't get the connection back! hic!

**Comment by QuocSiPHU** [comment]
However If I reflash with Betaflight 4.3.2 (only this version), I will get the connection back and the gyro/baro are working normally!

**Comment by OptimusTi** [comment]
![image](https://github.com/iNavFlight/inav/assets/45466510/dc9538db-fc2d-44d4-ba1e-3a9e94f00143)

Check these pins.

**Comment by QuocSiPHU** [comment]
Those pins are intentionally connected in order to power S5 to S9 from the on board Bec.
It's indicated in the FC manual.
As I will not have more than 4 servos and it will not generate any over power consumption on the FC.

**Comment by MATEKSYS** [comment]
> Can you please provide a detailed picture of the FC itself? Its a bit weird as the MATEKF405SE Target has not been changed over the last 5 Months and I am sure I have seen people using this FC with official INAV builds. @MATEKSYS has anything been changed on later revisions of this board?

nothing changed, just one PCB version since F405-WING-V2 release.

**Comment by MATEKSYS** [comment]
Just try flashing INAV7.1.0 to F405-WING-V2, works normal.
Probably you had it flashed with wrong target.
post some screentshot of "firmware flasher" tab

"I've tried flashing with MATEKF405 TE 6.0 and 7.0 as recommended on Mateksys website, however I still can't get connected"
I am courious where did you see we recommended MATEKF405TE target for F405-WING-V2.

**Comment by QuocSiPHU** [comment]
> Just try flashing INAV7.1.0 to F405-WING-V2, works normal. Probably you had it flashed with wrong target. post some screentshot of "firmware flasher" tab
> 
> "I've tried flashing with MATEKF405 TE 6.0 and 7.0 as recommended on Mateksys website, however I still can't get connected" I am courious where did you see we recommended MATEKF405TE target for F405-WING-V2.

Hi Mateksys, nice to read from you.
I'm using INAV 7.1.0 to flash the firmware [inav_7.0.0_MATEKF405SE]
from this link https://www.mateksys.com/Downloads/FW/inav_7.0.0_MATEKF405SE.hex

You talked about F405-WING-V2, but I have no idea where to get this firmware!

When power up the FC, I get the red led on and if the blue one is blinking, I can connect my FC to INAV.
If the blue led is off, I get "communication failed"
During the FC start up, I also have the green led blinking few time and then off.
I have no idea about the led signification.

Yesterday, I flashed twice but cannot get access from INAV.
Today, the board functioning but I'm not confident about its reliability.

If setup in a plane, the communication issue could be source of danger for people.
Thanks for your support.

**Comment by QuocSiPHU** [comment]
> > Can you please provide a detailed picture of the FC itself? Its a bit weird as the MATEKF405SE Target has not been changed over the last 5 Months and I am sure I have seen people using this FC with official INAV builds. @MATEKSYS has anything been changed on later revisions of this board?
> 
> nothing changed, just one PCB version since F405-WING-V2 release.

![z5363341840567_e14998edfadb54c2b0b6b0f3c6adfeac](https://github.com/iNavFlight/inav/assets/94967058/3244b651-f481-43c3-a2f6-0d32e7974400)
![z5363341845335_24a92381ee8b96501e55bed8f7c896f6](https://github.com/iNavFlight/inav/assets/94967058/ddf2363b-eeb6-4f63-9a39-6df30dea416c)

**Comment by QuocSiPHU** [comment]
> Just try flashing INAV7.1.0 to F405-WING-V2, works normal. Probably you had it flashed with wrong target. post some screentshot of "firmware flasher" tab
> 
> "I've tried flashing with MATEKF405 TE 6.0 and 7.0 as recommended on Mateksys website, however I still can't get connected" I am courious where did you see we recommended MATEKF405TE target for F405-WING-V2.

MATEKF405TE was a typing mistake from me!
Hereunder a screen shot showing some info one connected for your perusal.
<img width="1306" alt="Screenshot 2024-04-20 at 07 01 20" src="https://github.com/iNavFlight/inav/assets/94967058/f2fca4bd-e2f8-4462-9724-4942dd57fd0e">

**Comment by sensei-hacker** [comment]
It might not hurt to take old toothbrush or something and clean up some of the extra solder bits around those pins - especially UART1 and UART3.  Then inspect with another close-up photo or a magnifying glass and strong light.

The soldering looks good on S1 and S9 - the shape shows both the pin and pad are wetted, with

**Comment by QuocSiPHU** [comment]
> It might not hurt to take old toothbrush or something and clean up some of the extra solder bits around those pins - especially UART1 and UART3. Then inspect with another close-up photo or a magnifying glass and strong light. Just to be sure there aren't shorts from tiny solder whiskers and solder "dust" laying around on the board.
> 
> The soldering looks good on S1 and S9 - the shape shows both the pin and pad are wetted.
> 
> Because many of the other pins have enlarged balls of solder on them, and there are extra bits of solder in between, it's hard to know what might be shorted to what.

I did check the connection with a multimeter and there is no short on any pin.
However, your recommendation is right, and I'll clean up the board for removing unnecessary risk!
Thanks

**Comment by QuocSiPHU** [comment]
> Just try flashing INAV7.1.0 to F405-WING-V2, works normal. Probably you had it flashed with wrong target. post some screentshot of "firmware flasher" tab
> 
> "I've tried flashing with MATEKF405 TE 6.0 and 7.0 as recommended on Mateksys website, however I still can't get connected" I am courious where did you see we recommended MATEKF405TE target for F405-WING-V2.

With the version 7.0.0 downloaded from your website, hopefully things keep working well.
Now I try to setup a buzzer but can't get any sound.
Could you help me please.
Thanks

**Comment by QuocSiPHU** [comment]
The FC keep working!
Hope to definitively close this case. 
Thanks to all
