### ISSUE TITLE
FC NeuronRC AT32F435mini uart2 uart3 not working

### ISSUE THREAD

**Issue by konstantinfpv** [iNavFlight/inav#9972]
## Current Behavior
Soldered MSP Lidar+Optical Flow (microair mtf-01) to R3 T3 pins, set UART3 = MSP, Set Rangefinder = MSP, OpticalFlow = MSP. Rangefinder and Optical flow icon are red. Microair mtf-01 is working properly on other INAV board.
Soldered  Matek M8Q GPS to R2 T2 pins, set UART2 = GPS, set use GPS for navigation, set ublox protocol  baud 115400,  GPS icon is red,  no update in GPS tab.
## Steps to Reproduce

1. Solder to pads t2 r2 GPS
2. Solder to pads t3 r3 microair mtf-01
3. Solder GPS and microair mtf-01 V and G wires to 5v and G pads.
4. Connect FC to PC,  connect to configurator.
5. Connect lipo if needed.
6. Check that GPS and microair mtf-01 are working (lights on)
7. Setup GPS and microair mtf-01
8. GPS, Lidar, Flow icons are red.

## Expected behavior
On other INAV boards GPS is working, microair mtf-01 is working (can be calibrated and can see logs with data)

## Suggested solution(s)
Maybe wrong resourse adress for TX2 RX2 TX3 RX3 pins
## Additional context
[]
(https://micoair.com/index.php/optical_range_sensor_mtf-01/)

 (https://pastebin.com/qxSZ608X)

---

# INAV/NEUTRONRCF435MINI 7.1.0 Mar 27 2024 / 14:08:56 (59a6ee61)
# GCC-10.3.1 20210824 (release)

**Comment by bkleiner** [comment]
UART3 was fixed in https://github.com/iNavFlight/inav/pull/10333
Lets discuss UART2 in https://github.com/iNavFlight/inav/issues/10356
