### ISSUE TITLE
Does anyone able to use RX_MSP on NAZE32 rev6 with nav 1.4?

### ISSUE THREAD

**Issue by liutairan** [iNavFlight/inav#998]
I block out the SKIP_RX_MSP in common.h, but it still doesn’t work with inav 1.4
It used to work with 1.2.1 after I block out SKIP_RX_MSP.

Anyone have idea how to solve this problem? 
Thanks!

**Comment by oleost** [comment]
Try iNav 1.5RC3. if I remember correctly there was a bug which already been reported and corrected.

**Comment by liutairan** [comment]
@oleost Thanks! I just tried 1.5RC3 and it works. Thanks you!
