### ISSUE TITLE
Only one servo works  f405 v2 wing

### ISSUE THREAD

**Issue by InzynierMamon** [iNavFlight/inav#9984]
Working on a fixed wing (full tail, separate flaps), matek f405-wing v2, with spectrum ESC (spmxae1060 smart esc)Tx (Spektrum NX8 8-Channel DSMX) and Rx.  Rx(Spektrum SRXL2 DSMX) wire hooked into Tx2, setup in inav as per spektrum recommendation---only the s3 servo moves when moving Tx sticks, motor will not turn using radio, it turns when adding throttle  in inav.  channel map reflects true stick movement for all like there is no problem .  Servos test OK. What could be the issue? Thanks in advance.

**Comment by sensei-hacker** [comment]
Sounds like mixer issues. Can you please attach a screenshot of your mixer.

Also double check that the motor and servos are actually attached to the outputs shown in your mixer.

**Comment by InzynierMamon** [comment]
On closer look s3 (elevator) and s4 (left aileron) are working 

S1 ESC Vx pin removed, servos have Vx connected

Receiver on Tx2

More and more I'm thinking it has to be the solder points (although I think I soldered well) --- what would be the best way to check--hook up voltmeter and move the radio sticks?


![image](https://github.com/iNavFlight/inav/assets/168347432/f4fbd389-0b27-4b3d-b604-c604b4110824)

![image](https://github.com/iNavFlight/inav/assets/168347432/52bd649d-b7c9-401f-bf2a-c6395e6f9eb5)

![image](https://github.com/iNavFlight/inav/assets/168347432/83986cba-5975-40b1-b5b1-f0745f55cc53)

![image](https://github.com/iNavFlight/inav/assets/168347432/acb9c101-1576-4b48-8052-e6a82939fd2f)

![image](https://github.com/iNavFlight/inav/assets/168347432/d78a6d5a-f3de-4ef0-9694-7601dfc391dc)

![image](https://github.com/iNavFlight/inav/assets/168347432/38fa95b2-2fe6-4455-8ac9-48b1c56d4d50)

![image](https://github.com/iNavFlight/inav/assets/168347432/c8ac430b-663a-4bd3-9c4a-1fbad9d9ca16)

![image](https://github.com/iNavFlight/inav/assets/168347432/60bb131e-4266-4f7f-ab0d-b8670855457f)

![image](https://github.com/iNavFlight/inav/assets/168347432/307941b6-e24b-4934-b8ef-3c2f5132fcc6)

**Comment by sensei-hacker** [comment]
The first thing I would check with a multimeter is remove power and check continuity between each pair of adjacent pins. 

If you find continuity between pins, also check continuity to ground.

**Comment by MATEKSYS** [comment]
![image](https://github.com/iNavFlight/inav/assets/23047106/e0584131-7091-4103-9618-cc783580cd7e)

**Comment by InzynierMamon** [comment]
Vx2 to Vx pad bridge created--all servos now working -- thanks for the pointers. 

Now just S1 ESC/motor doesn't respond to throttle stick inputs on Tx(everything in iNAV indicates it should), have Vx disconnected in the ESC S1 pins.

**Comment by InzynierMamon** [comment]
I'm unable to calibrate ESC -- not allowed to turn on motor test mode and motor value at 1460.  

![image](https://github.com/iNavFlight/inav/assets/168347432/4b8a5a33-9154-440c-adb8-98f567afa07c)

**Comment by sensei-hacker** [comment]
> I'm unable to calibrate ESC -- not allowed to turn on motor test mode and motor value at 1460.

Yeah, you can't enable the motor with the throttle already halfway half. Drop the throttle stick to zero and turn off bidirectional motors if you don't actually need to run your motor backwards.  If you're building a rover, which does need to be able to go backwards, that's a different procedure.
